const names = {
  "030": "Asie orientale",
  "039": "Europe méridionale",
  "145": "Asie occidentale",
  "151": "Europe orientale",
  "154": "Europe septentrionale",
  "155": "Europe occidentale",
  "AC": "île de l’Ascension",
  "AX": "îles d’Åland",
  "BN": "Brunei",
  "BV": "île Bouvet",
  "BY": "Bélarus",
  "CC": "îles Cocos (Keeling)",
  "CI": "République de Côte d’Ivoire",
  "CK": "îles Cook",
  "CX": "île Christmas",
  "Deva": "devanagari",
  "FK": "îles Malouines",
  "FM": "Micronésie",
  "FO": "îles Féroé",
  "Gujr": "gujarati",
  "HM": "îles Heard et McDonald",
  "Hanb": "hanb",
  "Hans": "idéogrammes han simplifiés",
  "Hant": "idéogrammes han traditionnels",
  "Hrkt": "syllabaires japonais",
  "IC": "îles Canaries",
  "IM": "île de Man",
  "IO": "territoire britannique de l’océan Indien",
  "MF": "Saint-Martin (France)",
  "MM": "Myanmar",
  "MP": "Mariannes du Nord",
  "NF": "île Norfolk",
  "Olck": "ol chiki",
  "PN": "îles Pitcairn",
  "QO": "Océanie lointaine",
  "RE": "la Réunion",
  "SX": "Saint-Martin (Pays-Bas)",
  "TL": "Timor-Leste",
  "UM": "îles mineures éloignées des États-Unis",
  "VA": "Cité du Vatican",
  "VC": "Saint-Vincent-et-les Grenadines",
  "VG": "îles Vierges britanniques",
  "VI": "îles Vierges américaines",
  "Zsye": "zsye",
  "ady": "adygué",
  "aeb": "Tunisian Arabic",
  "akz": "Alabama",
  "aln": "Gheg Albanian",
  "ang": "vieil anglais",
  "arn": "araukan",
  "aro": "Araona",
  "arq": "Algerian Arabic",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "asa": "assou",
  "ase": "American Sign Language",
  "avk": "Kotava",
  "az": "azerbaïdjanais",
  "bar": "Bavarian",
  "bbc": "Batak Toba",
  "bbj": "ghomala",
  "be_BY": "biélorusse (Bélarus)",
  "bew": "Betawi",
  "bez": "bena",
  "bfq": "Badaga",
  "bho": "bhojpuri",
  "bik": "bicol",
  "bjn": "Banjar",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "brh": "Brahui",
  "byn": "bilen",
  "byv": "medumba",
  "chg": "tchagatay",
  "chn": "chinook",
  "ckb": "kurde central",
  "cps": "Capiznon",
  "cr": "cri",
  "de_AT": "allemand (Autriche)",
  "de_CH": "allemand (Suisse)",
  "den": "slave",
  "dgr": "tlicho",
  "dtp": "Central Dusun",
  "efi": "efik",
  "egl": "Emilian",
  "eka": "ekajuk",
  "en_CC": "anglais (Îles Cocos (Keeling))",
  "en_FM": "anglais (Micronésie)",
  "en_SX": "anglais (Saint-Martin (Pays-Bas))",
  "en_VC": "anglais (Saint-Vincent-et-les Grenadines)",
  "es_419": "espagnol latino-américain",
  "es_SV": "espagnol (Salvador)",
  "esu": "yupik central",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fit": "Tornedalen Finnish",
  "fr_MF": "français (Saint-Martin (France))",
  "frc": "cajun",
  "frp": "franco-provençal",
  "fy": "frison",
  "fy_NL": "frison (Pays-Bas)",
  "gan": "Gan Chinese",
  "gbz": "dari",
  "gil": "gilbertais",
  "glk": "Gilaki",
  "goh": "vieux haut-allemand",
  "gom": "Goan Konkani",
  "gu": "gujarati",
  "gu_IN": "goudjarâtî (Inde)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "gv": "manx",
  "hak": "Hakka Chinese",
  "hif": "Fiji Hindi",
  "hsn": "Xiang Chinese",
  "ht": "haïtien",
  "ii": "yi de Sichuan",
  "ii_CN": "yi de Sichuan (Chine)",
  "ilo": "ilokano",
  "izh": "Ingrian",
  "jam": "Jamaican Creole English",
  "jmc": "machame",
  "jut": "Jutish",
  "kbd": "kabardin",
  "kde": "makonde",
  "ken": "kenyang",
  "kg": "kongo",
  "kgp": "Kaingang",
  "khw": "Khowar",
  "kiu": "Kirmanjki",
  "kl": "kalaallisut",
  "kln": "kalenjin",
  "kmb": "kiMboundou",
  "kos": "kusaien",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "kru": "kurukh",
  "ks": "kashmiri",
  "ksb": "chambala",
  "ksh": "kölsch",
  "lfn": "Lingua Franca Nova",
  "lij": "Ligurian",
  "liv": "live",
  "lmo": "Lombard",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lus": "lushai",
  "luy": "oluluyia",
  "lzh": "chinois classique",
  "lzz": "Laz",
  "mai": "maithili",
  "mas": "masai",
  "mdf": "moksa",
  "mer": "merou",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshall",
  "mr": "marathe",
  "mrj": "Western Mari",
  "mua": "mundang",
  "mwr": "marwari",
  "mwv": "mentawai",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nds_NL": "bas saxon",
  "nia": "nias",
  "niu": "niué",
  "njo": "ao naga",
  "nl_SX": "néerlandais (Saint-Martin (Pays-Bas))",
  "nmg": "kwasio",
  "nov": "Novial",
  "nv": "navaho",
  "nwc": "newari classique",
  "ny": "nyanja",
  "nyn": "nkole",
  "or": "oriya",
  "pau": "palauan",
  "pcd": "Picard",
  "pdc": "allemand de Pennsylvanie",
  "pdt": "bas allemand mennonite",
  "peo": "vieux perse",
  "pfl": "palatin",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "prg": "Prussian",
  "pro": "ancien occitan",
  "qug": "Chimborazo Highland Quichua",
  "rar": "rarotonga",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rom": "tzigane",
  "rtm": "Rotuman",
  "ru_BY": "russe (Bélarus)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "valaque",
  "rw_RW": "kinyarwanda (Rwanda)",
  "sat": "santal",
  "saz": "Saurashtra",
  "sbp": "sangu",
  "sdc": "Sassarese Sardinian",
  "sdh": "kurde méridional",
  "se": "sami du Nord",
  "seh": "sena",
  "sei": "seri",
  "sg": "sangho",
  "sga": "vieil irlandais",
  "sgs": "Samogitian",
  "si_LK": "cingalais (Sri Lanka)",
  "sli": "Lower Silesian",
  "sly": "selayar",
  "sma": "sami du Sud",
  "smj": "sami de Lule",
  "smn": "sami d’Inari",
  "sms": "sami skolt",
  "st": "sesotho",
  "stq": "frison de Saterland",
  "suk": "sukuma",
  "sus": "sosso",
  "sw_CD": "swahili congolais",
  "szl": "Silesian",
  "tcy": "Tulu",
  "tem": "temne",
  "tet": "tetum",
  "tkr": "Tsakhur",
  "tly": "Talysh",
  "to": "tongan",
  "to_TO": "tongan (Tonga)",
  "tru": "turoyo",
  "tsd": "Tsakonian",
  "ttt": "Muslim Tat",
  "tyv": "touva",
  "tzm": "tamazight",
  "ug_Arab": "ouïgour (arabe)",
  "ug_Arab_CN": "ouïgour (arabe, Chine)",
  "ug_CN": "ouïgour (Chine)",
  "vec": "Venetian",
  "vep": "Veps",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapuk",
  "vro": "Võro",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "xmf": "Mingrelian",
  "yrl": "Nheengatu",
  "yue": "chinois, cantonais",
  "zea": "Zeelandic",
  "zh_Hans_CN": "chinois (idéogrammes han simplifiés, Chine)",
  "zh_Hans_HK":
      "chinois (idéogrammes han simplifiés, R.A.S. chinoise de Hong Kong)",
  "zh_Hans_MO":
      "chinois (idéogrammes han simplifiés, R.A.S. chinoise de Macao)",
  "zh_Hans_SG": "chinois (idéogrammes han simplifiés, Singapour)",
  "zh_Hant_HK":
      "chinois (idéogrammes han traditionnels, R.A.S. chinoise de Hong Kong)",
  "zh_Hant_MO":
      "chinois (idéogrammes han traditionnels, R.A.S. chinoise de Macao)",
  "zh_Hant_TW": "chinois (idéogrammes han traditionnels, Taïwan)",
  "zun": "zuni"
};
