const names = {
  "af": "Tiếng Nam Phi",
  "akz": "Alabama",
  "aln": "Gheg Albanian",
  "arn": "Tiếng Araucanian",
  "aro": "Araona",
  "arq": "Algerian Arabic",
  "arz": "Egyptian Arabic",
  "ase": "American Sign Language",
  "bar": "Bavarian",
  "bbc": "Batak Toba",
  "bew": "Betawi",
  "bfq": "Badaga",
  "bjn": "Banjar",
  "bn": "Tiếng Bengali",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "brh": "Brahui",
  "bs": "Tiếng Nam Tư",
  "ckb": "Tiếng Kurd Sorani",
  "cps": "Capiznon",
  "de_CH": "Tiếng Đức (Thụy Sĩ)",
  "dtp": "Central Dusun",
  "egl": "Emilian",
  "en_GB": "Tiếng Anh (Vương quốc Anh)",
  "en_US": "Tiếng Anh (Hoa Kỳ)",
  "es_ES": "Tiếng Tây Ban Nha (Tây Ban Nha)",
  "esu": "Central Yupik",
  "ext": "Extremaduran",
  "fa_AF": "Tiếng Ba Tư (Afghanistan)",
  "fil": "Tiếng Philipin",
  "fo": "Tiếng Faore",
  "frc": "Cajun French",
  "frp": "Arpitan",
  "frr": "Tiếng Frisian Miền Bắc",
  "ga": "Tiếng Ai-len",
  "gan": "Gan Chinese",
  "gd": "Tiếng Xentơ (Xcốt len)",
  "glk": "Gilaki",
  "gom": "Goan Konkani",
  "gur": "Frafra",
  "hak": "Hakka Chinese",
  "hif": "Fiji Hindi",
  "hsn": "Xiang Chinese",
  "it": "Tiếng Ý",
  "izh": "Ingrian",
  "jam": "Jamaican Creole English",
  "jut": "Jutish",
  "ka": "Tiếng Gruzia",
  "km": "Tiếng Khơ-me",
  "ks": "Tiếng Kashmiri",
  "lt": "Tiếng Lít-va",
  "mnc": "Tiếng Manchu",
  "ms": "Tiếng Malaysia",
  "mt": "Tiếng Malt",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "njo": "Ao Naga",
  "nl_BE": "Tiếng Hà Lan (Bỉ)",
  "nso": "Bắc Sotho",
  "nwc": "Tiếng Newari Cổ điển",
  "or": "Tiếng Oriya",
  "prg": "Prussian",
  "pt_BR": "Tiếng Bồ Đào Nha (Brazil)",
  "pt_PT": "Tiếng Bồ Đào Nha (Bồ Đào Nha)",
  "qug": "Chimborazo Highland Quichua",
  "ro": "Tiếng Rumani",
  "ro_MD": "Tiếng Rumani (Moldova)",
  "sh": "Tiếng Xéc bi - Croatia",
  "sma": "TIếng Sami Miền Nam",
  "sq": "Tiếng An-ba-ni",
  "st": "Tiếng Sesotho",
  "su": "Tiếng Sudan",
  "syc": "Tiếng Syria Cổ điển",
  "tet": "Tetum",
  "ti": "Tiếng Tigrigya",
  "tk": "Tiếng Turk",
  "uk": "Tiếng Ucraina",
  "ur": "Tiếng Uđu",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "yi": "Tiếng Y-đit",
  "za": "Tiếng Zhuang",
  "zh_Hans": "Tiếng Trung (Giản thể)",
  "zh_Hant": "Tiếng Trung (Phồn thể)"
};
