const names = {
  "001": "Ao",
  "002": "Awherika",
  "003": "Amerika Te Raki",
  "005": "Amerika ki te Tonga",
  "009": "Oceania",
  "011": "Awherika ki te Hauauru",
  "013": "Amerika Waenganui",
  "014": "Awherika ki te Rawhiti",
  "015": "Awherika ki te Raki",
  "017": "Awherika Waenganui",
  "018": "Awherika ki te Tonga",
  "019": "Amerika",
  "021": "Amerika ki te Raki",
  "029": "Karipiana",
  "030": "Ahia ki te Rawhiti",
  "034": "Ahia ki te Tonga",
  "035": "Ahia ki te Tonga",
  "039": "Europe ki te Tonga",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Rohe Micronesian",
  "061": "Poronihia",
  "062": "Ahia ki te Tonga-Waenganui",
  "142": "Ahia",
  "143": "Ahia Waenganui",
  "145": "Ahia Uru",
  "150": "Europe",
  "151": "Europe Rawhiti",
  "154": "Europe Raki",
  "155": "Europe Hauauru",
  "172": "Tuhinga o mua",
  "200": "Czechoslovakia",
  "202": "Awherika-Sahara o Awherika",
  "419": "Amerika Latina",
  "830": "Moutere Channel",
  "AC": "Motu Whakaekea",
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua & Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Netherlands Antilles",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Kaukarai Albanian",
  "Ahom": "Ahom",
  "Arab": "Arapika",
  "Aran": "Nastaliq",
  "Armi": "Imperial Aramaic",
  "Armn": "Armenia",
  "Avst": "Avestan",
  "BA": "Bosnia & Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Parahi",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "Hainamana",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Bangla",
  "Bhks": "Bhaiksuki",
  "Blis": "Tohu Koretake",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Bugina",
  "Buhd": "Buhid",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo - Kinshasa",
  "CF": "Central African Republic",
  "CG": "Congo - Brazzaville",
  "CH": "Switzerland",
  "CI": "Côte d’Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "Haina",
  "CO": "Colombia",
  "CP": "Moutere o Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia me Montenegro",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "Cakm": "Chakma",
  "Cans": "Whakakotahitia Takawaenga Aboriginal o Kanata",
  "Cari": "Kariana",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Kopiti",
  "Cprt": "Kaipiripi",
  "Cyrl": "Hīririki",
  "Cyrs": "Church Old Slavonic Cyrillic",
  "DD": "Tiamana Rawhiti",
  "DE": "Tiamana",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "Deva": "Devanagari",
  "Diak": "Ruku Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Duployan poto",
  "EA": "Ceuta & Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "EU": "Uniana o Europi",
  "EZ": "Eurozone",
  "Egyd": "Uropi a te Ihipiana",
  "Egyh": "Hieratic Ihipa",
  "Egyp": "Hieroglyphs Ihipiana",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "Etiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "Wīwī",
  "FX": "Metropolitan France",
  "GA": "Gabon",
  "GB": "Hononga o Piritene",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "Georgian Khutsuri",
  "Geor": "Georgian",
  "Glag": "Glagolitik",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gothic",
  "Gran": "Grantha",
  "Grek": "Kiriki",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "Hanb": "Han me Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "Māmā",
  "Hant": "Tukuiho",
  "Hatr": "Hatran",
  "Hebr": "Hiperu",
  "Hira": "Hiragana",
  "Hluw": "Anierolian Hieroglyphs",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Tapukapuka Hapanihi",
  "Hung": "Hungarian Tawhito",
  "IC": "Moutere Canary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "Inia",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Itāria",
  "Inds": "Indus",
  "Ital": "Italic Tawhito",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Hapani",
  "Jamo": "Jamo",
  "Java": "Java",
  "Jpan": "Hapanihi",
  "Jurc": "Jurchen",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "St. Kitts & Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kits": "Hōtuhi iti a Khitan",
  "Knda": "Kannada",
  "Kore": "Koreana",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "Lana": "Lanna",
  "Laoo": "Rao",
  "Latf": "Latino Whati",
  "Latg": "Latina Gaelic",
  "Latn": "Rātina",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Raina A",
  "Linb": "Raina B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydian",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MI": "Moutere o Midway",
  "MK": "Makerōnia ki te Raki",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao SAR China",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "Hieroglyph Maya",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitic Cursive",
  "Mero": "Meroiti",
  "Mlym": "Malayalam",
  "Modi": "Modi",
  "Mong": "Mongolian",
  "Moon": "Marama",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Myanmar",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Rohe kūpapa",
  "NU": "Niue",
  "NZ": "Aotearoa",
  "Nand": "Nandinagari",
  "Narb": "Arapia Raki tawhito",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Odia",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Te Rohe Whakawhirinaki o Nga Moutere o te Moananui a Kiwa",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "St. Pierre & Miquelon",
  "PN": "Pitcairn Islands",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territories",
  "PT": "Portugal",
  "PU": "Nga Moutere o te Moananui a Kiwa",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Rohe Canal o Panama",
  "Palm": "Palmyrene",
  "Pauc": "Pau Cin Hau",
  "Perm": "Permic Tawhito",
  "Phag": "Phags-pa",
  "Phli": "Tuhinga Pahlavi",
  "Phlp": "---------------- Pahlavi",
  "Phlv": "Pukapuka Pahlavi",
  "Phnx": "Poikene",
  "Plrd": "Pono Pollard",
  "Prti": "Parthian Tuhinga",
  "QA": "Qatar",
  "QO": "Oceania Waho",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Rūhia",
  "RW": "Rwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "St. Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "São Tomé & Príncipe",
  "SU": "Uniana o nga Ropu Hapori Soviet",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "Samr": "Hamaria",
  "Sara": "Sarati",
  "Sarb": "Arapia ki te Tonga Tonga",
  "Saur": "Saurashtra",
  "Sgnw": "WaitohuTuhi",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "Sinhala",
  "Sogd": "Sogdian",
  "Sogo": "Sogdian tawhito",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundana",
  "Sylo": "Syloti Nagri",
  "Syrc": "Hiriani",
  "Syre": "Estrangelo Syriac",
  "Syrj": "Syriac ki te Hauauru",
  "Syrn": "Syriac ki te Rawhiti",
  "TA": "Tristan da Cunha",
  "TC": "Turks & Caicos Islands",
  "TD": "Chad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad & Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Tai Tai Hou",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Hinuka",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibetana",
  "Tirh": "Tirhuta",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "U.S. Outlying Islands",
  "UN": "United Nations",
  "US": "Hononga o Amerika",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "Ugar": "Ugaritic",
  "VA": "Vatican City",
  "VC": "St. Vincent & Grenadines",
  "VD": "Te Tai Tokerau Vietnam",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Korero Korero",
  "WF": "Wallis & Futuna",
  "WK": "Wake Moutere",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudo-Nako",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "Persian tawhito",
  "Xsux": "Sumero-Akkadian Cuneiform",
  "YD": "Te Manapori Manapori Manapori o Yemen",
  "YE": "Yemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Rohe Tē Mōhiotia",
  "Zanb": "Zanabazar Tapawha",
  "Zinh": "Ka kainga",
  "Zmth": "Tuhinga Pāngarau",
  "Zsye": "Emoji",
  "Zsym": "Tohu",
  "Zxxx": "Tuhikore",
  "Zyyy": "Momo",
  "Zzzz": "Momotuhi Tē Mōhiotia",
  "aa": "Tawhiti",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arapi",
  "af": "Awherika",
  "af_NA": "Āwherika (Namibia)",
  "af_ZA": "Awherika (Awherika ki te Tonga)",
  "afa": "Reo Afro-Asiatic",
  "afh": "Afrihili",
  "agq": "Aue",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadian",
  "akz": "Arapama",
  "ale": "Aleut",
  "alg": "Reo Algonquian",
  "aln": "Gheg Albanian",
  "alt": "Altai ki te Tonga",
  "am": "Amharic",
  "am_ET": "Amharic (Etiopia)",
  "an": "Aragonese",
  "ang": "Ingarihi tawhito",
  "anp": "Angika",
  "apa": "Reo Apache",
  "ar": "Arapi",
  "ar_001": "Arapi Paerewa Hou",
  "ar_AE": "Arāpi (United Arab Emirates)",
  "ar_BH": "Arāpi (Bahrain)",
  "ar_DJ": "Arāpi (Djibouti)",
  "ar_DZ": "Arāpi (Algeria)",
  "ar_EG": "Arāpi (Ihipa)",
  "ar_EH": "Arāpi (Sahara ki te Hauauru)",
  "ar_ER": "Arāpi (Eritrea)",
  "ar_IL": "Arāpi (Iharaira)",
  "ar_IQ": "Arāpi (Iraq)",
  "ar_JO": "Arāpi (Horano)",
  "ar_KM": "Arāpi (Kōmoro)",
  "ar_KW": "Arāpi (Kuwait)",
  "ar_LB": "Arāpi (Repanona)",
  "ar_LY": "Arāpi (Libya)",
  "ar_MA": "Arāpi (Moroko)",
  "ar_MR": "Arāpi (Mauritania)",
  "ar_OM": "Arāpi (Omana)",
  "ar_PS": "Arāpi (Whenua Pirihitia)",
  "ar_QA": "Arāpi (Qatar)",
  "ar_SA": "Arāpi (Arapia Arapia)",
  "ar_SD": "Arāpi (Sudana)",
  "ar_SO": "Arāpi (Somalia)",
  "ar_SS": "Arāpi (Sudan ki te Tonga)",
  "ar_SY": "Arāpi (Hiria)",
  "ar_TD": "Arāpi (Tohu)",
  "ar_TN": "Arāpi (Tunisia)",
  "ar_YE": "Arāpi (Yemen)",
  "arc": "Arame",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Arapi Arapi",
  "ars": "Najdi Arapi",
  "art": "Reo Hainamana",
  "arw": "Arawak",
  "ary": "Moroccan Arapi",
  "arz": "Arapi Ihipa",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "Reo Waitohu Amerikana",
  "ast": "Asturian",
  "ath": "Te Reo Athapascan",
  "aus": "Reo Ahitereiria",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijan (Azerbaijan)",
  "az_Arab": "Azerbaijan (Arāpi)",
  "az_Cyrl": "Azerbaijan (Hiririki)",
  "az_Cyrl_AZ": "Azerbaijan (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijan (Latin)",
  "az_Latn_AZ": "Azerbaijan (Latin, Azerbaijan)",
  "azb": "Azerbaijani ki te Tonga",
  "ba": "Bashkir",
  "bad": "Banda",
  "bai": "Te Reo Bamileke",
  "bal": "Baluchi",
  "ban": "Hainamana",
  "bar": "Paparia",
  "bas": "Basaa",
  "bat": "Reo Baletiko",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarusian",
  "be_BY": "Belarusian (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Parāoa",
  "bfq": "Badaga",
  "bg": "Bulgarian",
  "bg_BG": "Bulgarian (Bulgaria)",
  "bgn": "Balochi Hauauru",
  "bh": "Bihari",
  "bho": "Behia",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bangla",
  "bn_BD": "Bengali (Bangladesh)",
  "bn_IN": "Bengali (India)",
  "bnt": "Bantu",
  "bo": "Tibetana",
  "bo_CN": "Tibet (Haina)",
  "bo_IN": "Tibet (Inia)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Peretana",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnia (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnia (Hiririki)",
  "bs_Cyrl_BA": "Bosnia (Hiririki, Bosnia me Herzegovina)",
  "bs_Latn": "Bosnia (Latin)",
  "bs_Latn_BA": "Bosnia (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "Bugina",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Itari)",
  "cad": "Caddo",
  "cai": "Te Reo Inia o Amerika ki waenganui",
  "car": "Kariri",
  "cau": "Te Reo Caucasian",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cel": "Reo Celtic",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Kopata",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Kurdish Waenganui",
  "cmc": "Reo Hihi",
  "co": "Korsikana",
  "cop": "Kopiti",
  "cpe": "Pakeha hangai i te Ingarihi, Pidgin ranei",
  "cpf": "French-based Creole, Pidgin ranei",
  "cpp": "Pouaka hangai i Potukara, Pidgin ranei",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Turikana Crimean",
  "crp": "Creole, Pidgin ranei",
  "crs": "Seselwa Creole French",
  "cs": "Czech",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "Hukurei Hahi",
  "cus": "Reo Cushitic",
  "cv": "Chuvash",
  "cy": "Wales",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Tenimana",
  "da_DK": "Tenimana (Tenimaka)",
  "da_GL": "Tenimana (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Tiamana",
  "de_AT": "Tiamana Atiria",
  "de_BE": "Tiamana (Belgium)",
  "de_CH": "Tiamana Ōkawa Huiterangi",
  "de_DE": "Tiamana (Tiamana)",
  "de_LI": "Tiamana (Liechtenstein)",
  "de_LU": "Tiamana (Luxembourg)",
  "del": "Delaware",
  "den": "He pononga",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Reo Dravidian",
  "dsb": "Turoritana Raro",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Tatimana Tati",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Kanaana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ihipiana Tahito",
  "eka": "Ekajuk",
  "el": "Kiriki",
  "el_CY": "Kiriki (Kaiperu)",
  "el_GR": "Kiriki (Kariki)",
  "elx": "Elamite",
  "en": "Ingarihi",
  "en_AG": "Ingarihi (Antigua & Barbuda)",
  "en_AI": "Ingarihi (Anguilla)",
  "en_AS": "Ingarihi (American Samoa)",
  "en_AU": "Ingarihi Ahitereiriana",
  "en_BB": "Ingarihi (Barbados)",
  "en_BE": "Ingarihi (Belgium)",
  "en_BM": "Ingarihi (Bermuda)",
  "en_BS": "Ingarihi (Bahamas)",
  "en_BW": "Ingarihi (Botswana)",
  "en_BZ": "Ingarihi (Belize)",
  "en_CA": "Ingarihi Kānata",
  "en_CC": "Ingarihi (Cocos (Keeling) Motu)",
  "en_CK": "Ingarihi (Kuki Airani)",
  "en_CM": "Ingarihi (Cameroon)",
  "en_CX": "Ingarihi (Motu Kirihimete)",
  "en_DG": "Ingarihi (Diego Garcia)",
  "en_DM": "Ingarihi (Dominica)",
  "en_Dsrt": "Ingarihi (Deseret)",
  "en_ER": "Ingarihi (Eritrea)",
  "en_FJ": "Ingarihi (Fiji)",
  "en_FK": "Ingarihi (Moutere Falkland)",
  "en_FM": "Ingarihi (Micronesia)",
  "en_GB": "Ingarihi Piritene",
  "en_GD": "Ingarihi (Grenada)",
  "en_GG": "Ingarihi (Guernsey)",
  "en_GH": "Ingarihi (Ghana)",
  "en_GI": "Ingarihi (Gibraltar)",
  "en_GM": "Ingarihi (Gambia)",
  "en_GU": "Ingarihi (Guam)",
  "en_GY": "Ingarihi (Guyana)",
  "en_HK": "Ingarihi (Hong Kong SAR China)",
  "en_IE": "Ingarihi (Ireland)",
  "en_IM": "Ingarihi (Motu o te Tangata)",
  "en_IN": "Ingarihi (Inia)",
  "en_IO": "Ingarihi (Te Rohe Moana o Inia o Ingarangi)",
  "en_JE": "Ingarihi (Jersey)",
  "en_JM": "Ingarihi (Jamaica)",
  "en_KE": "Ingarihi (Kenya)",
  "en_KI": "Ingarihi (Kiribati)",
  "en_KN": "Ingarihi (St. Kitts me Nevis)",
  "en_KY": "Ingarihi (Moutere Cayman)",
  "en_LC": "Ingarihi (St. Lucia)",
  "en_LR": "Ingarihi (Liberia)",
  "en_LS": "Ingarihi (Lesotho)",
  "en_MG": "Ingarihi (Madagascar)",
  "en_MH": "Ingarihi (Nga Moutere o Marshall)",
  "en_MO": "Ingarihi (Macau SAR China)",
  "en_MP": "Ingarihi (Nga Moutere o Mariana ki te Raki)",
  "en_MS": "Ingarihi (Montserrat)",
  "en_MT": "Ingarihi (Malta)",
  "en_MU": "Ingarihi (Mauritius)",
  "en_MW": "Ingarihi (Malawi)",
  "en_MY": "Ingarihi (Malaysia)",
  "en_NA": "Ingarihi (Namibia)",
  "en_NF": "Ingarihi (Motu Norfolk)",
  "en_NG": "Ingarihi (Nigeria)",
  "en_NR": "Ingarihi (Nauru)",
  "en_NU": "Ingarihi (Niue)",
  "en_NZ": "Ingarihi (Aotearoa)",
  "en_PG": "Ingarihi (Papua New Guinea)",
  "en_PH": "Ingarihi (Philippines)",
  "en_PK": "Ingarihi (Pakistan)",
  "en_PN": "Ingarihi (Nga Moutere o Pitcairn)",
  "en_PR": "Ingarihi (Puerto Rico)",
  "en_PW": "Ingarihi (Palau)",
  "en_RW": "Ingarihi (Rwanda)",
  "en_SB": "Ingarihi (Solomon Islands)",
  "en_SC": "Ingarihi (Seychelles)",
  "en_SD": "Ingarihi (Sudan)",
  "en_SG": "Ingarihi (Singapore)",
  "en_SH": "Ingarihi (St. Helena)",
  "en_SL": "Ingarihi (Sierra Leone)",
  "en_SS": "Ingarihi (Sudan ki te Tonga)",
  "en_SX": "Ingarihi (Sint Maarten)",
  "en_SZ": "Ingarihi (Swaziland)",
  "en_TC": "Ingarihi (Nga Moutere o Turks & Caicos)",
  "en_TK": "Ingarihi (Tokelau)",
  "en_TO": "Ingarihi (Tonga)",
  "en_TT": "Ingarihi (Trinidad & Tobago)",
  "en_TV": "Ingarihi (Tuvalu)",
  "en_TZ": "Ingarihi (Tanzania)",
  "en_UG": "Ingarihi (Uganda)",
  "en_UM": "Ingarihi (Nga Moutere o U.S.)",
  "en_US": "Ingarihi Amerikana",
  "en_VC": "Ingarihi (St.Vincent & Grenadines)",
  "en_VG": "Ingarihi (Motu Motu o Ingarangi)",
  "en_VI": "Ingarihi (Motu Motu o U.S.)",
  "en_VU": "Ingarihi (Vanuatu)",
  "en_WS": "Ingarihi (Hāmoa)",
  "en_ZA": "Ingarihi (Awherika ki te Tonga)",
  "en_ZM": "Ingarihi (Zambia)",
  "en_ZW": "Ingarihi (Zimbabwe)",
  "enm": "Ingarihi Waenganui",
  "eo": "Esperanto",
  "es": "Paniora",
  "es_419": "Paniora Amerika ki te Tonga",
  "es_AR": "Paniora (Argentina)",
  "es_BO": "Paniora (Bolivia)",
  "es_CL": "Paniora (Chile)",
  "es_CO": "Paniora (Colombia)",
  "es_CR": "Paniora (Costa Rica)",
  "es_CU": "Paniora (Cuba)",
  "es_DO": "Paniora (Dominican Republic)",
  "es_EA": "Paniora (Ceuta & Melilla)",
  "es_EC": "Paniora (Ecuador)",
  "es_ES": "Paniora Uropi",
  "es_GQ": "Paniora (Guinea Equatorial)",
  "es_GT": "Paniora (Guatemala)",
  "es_HN": "Paniora (Honduras)",
  "es_IC": "Paniora (Nga Moutere Canary)",
  "es_MX": "Paniora Mēhikana",
  "es_NI": "Paniora (Nicaragua)",
  "es_PA": "Paniora (Panamana)",
  "es_PE": "Paniora (Peru)",
  "es_PH": "Paniora (Philippines)",
  "es_PR": "Paniora (Puerto Rico)",
  "es_PY": "Paniora (Paraguay)",
  "es_SV": "Paniora (El Salvador)",
  "es_US": "Paniora (United States)",
  "es_UY": "Paniora (Uruguay)",
  "es_VE": "Paniora (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Pahia",
  "fa_AF": "Pahia (Afghanistan)",
  "fa_IR": "Pahia (Iran)",
  "fan": "Koretake",
  "fat": "Fanti",
  "ff": "Tuakiri",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finelani)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fiu": "Reo Finno-Ugrian",
  "fj": "Whitiana",
  "fo": "Faroese",
  "fo_FO": "Faroese (Moutere Faroe)",
  "fon": "Fon",
  "fr": "Wīwī",
  "fr_BE": "Parani (Belgium)",
  "fr_BF": "Parani (Burkina Faso)",
  "fr_BI": "Wīwī (Burundi)",
  "fr_BJ": "Wīwī (Pēneti)",
  "fr_BL": "Parani (St. Barthélemy)",
  "fr_CA": "Wīwī Kānata",
  "fr_CD": "French (Kongo - Kinshasa)",
  "fr_CF": "Wīwī (Rōpū Awherika o Awherika)",
  "fr_CG": "Wīwī (Kongo - Brazzaville)",
  "fr_CH": "Wīwī Huiterangi",
  "fr_CI": "French (Côte d'Ivoire)",
  "fr_CM": "Wīwī (Cameroon)",
  "fr_DJ": "Wīwī (Djibouti)",
  "fr_DZ": "Wīwī (Algeria)",
  "fr_FR": "Wīwī (Parani)",
  "fr_GA": "Wīwī (Gabon)",
  "fr_GF": "Wīwī (Guiana Wīwī)",
  "fr_GN": "French (Guinea)",
  "fr_GP": "Wīwī (Guadeloupe)",
  "fr_GQ": "French (Guinea Equatorial)",
  "fr_HT": "Parani (Haiti)",
  "fr_KM": "French (Komoro)",
  "fr_LU": "Wīwī (Luxembourg)",
  "fr_MA": "Wīwī (Moroko)",
  "fr_MC": "Wīwī (Monako)",
  "fr_MF": "Parani (St. Martin)",
  "fr_MG": "Wīwī (Madagascar)",
  "fr_ML": "Wīwī (Mali)",
  "fr_MQ": "French (Martinique)",
  "fr_MR": "Wīwī (Mauritania)",
  "fr_MU": "Wīwī (Mauritius)",
  "fr_NC": "Wīwī (New Caledonia)",
  "fr_NE": "Wīwī (Nikera)",
  "fr_PF": "Wīwī (French Polynesia)",
  "fr_PM": "Parani (St. Pierre & Miquelon)",
  "fr_RE": "Wīwī (Réunion)",
  "fr_RW": "Wīwī (Rwanda)",
  "fr_SC": "Wīwī (Seychelles)",
  "fr_SN": "Wīwī (Senegal)",
  "fr_SY": "Wīwī (Hiria)",
  "fr_TD": "Wīwī (Chad)",
  "fr_TG": "Wīwī (Togo)",
  "fr_TN": "Parani (Tunisia)",
  "fr_VU": "Wīwī (Vanuatu)",
  "fr_WF": "Wīwī (Wallis me Futuna)",
  "fr_YT": "Wīwī (Mayotte)",
  "frc": "Cajun Wiwi",
  "frm": "French Wiwi",
  "fro": "French tawhito",
  "frp": "Arpitan",
  "frr": "Frisian ki te Raki",
  "frs": "Frisian ki te Rawhiti",
  "fur": "Friulian",
  "fy": "Frisian Hauauru",
  "fy_NL": "Frisian Hauauru (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Airihi (Airani)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Hainamana",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Gaelic Kotimana",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gem": "Reo Tiamana",
  "gez": "Aue",
  "gil": "Gilbertese",
  "gl": "Karikiana",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Tiamana Runga Waenganui",
  "gn": "Guarani",
  "goh": "Tiamana Rawa Tawhito",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Kiriki Onamata",
  "gsw": "Switzerland Tiamana",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (Inia)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Motu o te Tangata)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Kanaana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Nigeria)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Hainamana",
  "haw": "Hawaiian",
  "he": "Hiperu",
  "he_IL": "Hiperu (Iharaira)",
  "hi": "Hindi",
  "hi_IN": "Hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hiti",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Kroatii",
  "hr_BA": "Kroatii (Bosnia & Herzegovina)",
  "hr_HR": "Kroati (Croatia)",
  "hsb": "Sorbian",
  "hsn": "Xiang Hainamana",
  "ht": "Haiti Creole",
  "hu": "Hanekaria",
  "hu_HU": "Hungarian (Hungary)",
  "hup": "Hupa",
  "hy": "Armenia",
  "hy_AM": "Armenia (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indonesian",
  "id_ID": "Indonesian (Indonesia)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (Haina)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Tohu Reo",
  "ine": "Reo Indo-Pakeha",
  "inh": "Ingush",
  "io": "Ido",
  "ira": "Reo Iranian",
  "iro": "Reo Iroquoian",
  "is": "Tiorangi",
  "is_IS": "Tiorangi (Tiorangi)",
  "it": "Ītariana",
  "it_CH": "Itari (Switzerland)",
  "it_IT": "Itari (Itari)",
  "it_SM": "Itari (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Hapanihi",
  "ja_JP": "Hapanihi (Hapani)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Miihini",
  "jpr": "Hura-Pahia",
  "jrb": "Hura-Arapi",
  "jut": "Jutish",
  "jv": "Java",
  "ka": "Georgian",
  "ka_GE": "Hōriana (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Reo Khoisan",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Hiririki)",
  "kk_Cyrl_KZ": "Kazakh (Hiririki, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Kemupodia)",
  "kmb": "Ko Kemehuru",
  "kn": "Kannada",
  "kn_IN": "Kannada (Inia)",
  "ko": "Koreana",
  "ko_KP": "Korea (Korea ki te Raki)",
  "ko_KR": "Koreana (Korea ki te Tonga)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arapi)",
  "ks_Arab_IN": "Kashmiri (Arapi, Inia)",
  "ks_IN": "Kashmiri (Inia)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Koroneihana",
  "ku": "Kurihi",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Kornihi",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Hiririki)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Latina",
  "lad": "Ladino",
  "lag": "Rangi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Kongo - Kinshasa)",
  "ln_CF": "Lingala (Central Africa Republic)",
  "ln_CG": "Lingala (Kongo - Brazzaville)",
  "lo": "Rao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Ruri Raki",
  "lt": "Riwaiana",
  "lt_LT": "Ritihia (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Kongo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Hainamana Hainamana",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Reo Austronesian",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Maori",
  "mg_MG": "Maori (Madagascar)",
  "mga": "Airihi Waenganui",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Māori",
  "mic": "Mi'kmaq",
  "min": "Minangkabau",
  "mis": "Te Reo rereke",
  "mk": "Maketonia",
  "mk_MK": "Maketonia (Makeronia)",
  "mkh": "Te Reo Mon-Khmer",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Hiririki)",
  "mn_Cyrl_MN": "Mongolian (Hiririki, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Te Reo Manobo",
  "mo": "Mooritana",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (Inia)",
  "mrj": "Mari Hauauru",
  "ms": "Malay",
  "ms_BN": "Malay (Brunei)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malay (Singapore)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Reo maha",
  "mun": "Reo Munda",
  "mus": "Muscogee",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Burmese",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "Myene",
  "myn": "Reo Maya",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nah": "Nahuatl",
  "nai": "Te Reo Inia o Amerika ki te Raki",
  "nan": "Min Nan Hainamana",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Bokmål No Norewai",
  "nb_NO": "Bokmål Nōwei (Nōwei)",
  "nb_SJ": "Bokmål o Norewai (Svalbard me Jan Mayen)",
  "nd": "Ndebele ki te Raki",
  "nd_ZW": "Ndebele ki te Raki (Zimbabwe)",
  "nds": "Tiamana Iti",
  "nds_NL": "Tatimana Haamana iti",
  "ne": "Nepali",
  "ne_IN": "Nepali (India)",
  "ne_NP": "Nepali (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Te Reo Kiwi-Kordofanian",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Tatimana",
  "nl_AW": "Tatimana (Aruba)",
  "nl_BE": "Tatimana (Belgium)",
  "nl_BQ": "Tatimana (Karipiana Netherlands)",
  "nl_CW": "Tatimana (Curaçao)",
  "nl_NL": "Tatimana (Netherlands)",
  "nl_SR": "Tatimana (Suriname)",
  "nl_SX": "Tatimana (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Nynorsk Nōwei (Nōwei)",
  "nnh": "Ngiemboon",
  "no": "Nōwei",
  "no_NO": "Nōwei (Nōwei)",
  "nog": "Nogai",
  "non": "Norse tawhito",
  "nov": "Whakahauhau",
  "nqo": "N’Ko",
  "nr": "Ndebele ki te Tonga",
  "nso": "Northern Sotho",
  "nub": "Reo Nubian",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Newari Tauhira",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Hinituana",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Etiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Odia",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Turikana Ottoman",
  "oto": "Te Reo Otomia",
  "pa": "Pāniora",
  "pa_Arab": "Punjabi (Arapi)",
  "pa_Arab_PK": "Punjabi (Arapi, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "paa": "Reo Papua",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Pikard",
  "pcm": "Pidgin Nigeria",
  "pdc": "Pennsylvania Tiamana",
  "pdt": "Plautdietsch",
  "peo": "Persian tawhito",
  "pfl": "Palatine Tiamana",
  "phi": "Reo Piripi",
  "phn": "Poikene",
  "pi": "Pali",
  "pl": "Pōrana",
  "pl_PL": "Pōrana (Pōrana)",
  "pms": "Piedmontese",
  "pnt": "Ponotiko",
  "pon": "Pohnpeian",
  "pra": "Reo Prakrit",
  "prg": "Pirimia",
  "pro": "Whakamatau Tawhito",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Pōtikī",
  "pt_AO": "Potukara (Angola)",
  "pt_BR": "Pōtikī Parahi",
  "pt_CV": "Potukara (Cape Verde)",
  "pt_GW": "Potukara (Guinea-Bissau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Potukara (Mozambique)",
  "pt_PT": "Pōtikī Uropi",
  "pt_ST": "Potukara (São Tomé & Príncipe)",
  "pt_TL": "Potukara (Timor-Leste)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romana",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Romanian",
  "ro_MD": "Romanian (Moldova)",
  "ro_RO": "Romanian (Romania)",
  "roa": "Reo Romance",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Pūtake",
  "rtm": "Rotuman",
  "ru": "Ruhiana",
  "ru_BY": "Ruhia (Belarus)",
  "ru_KG": "Ruhia (Kyrgyzstan)",
  "ru_KZ": "Ruhia (Kazakhstan)",
  "ru_MD": "Ruhia (Mouldova)",
  "ru_RU": "Ruhia (Russia)",
  "ru_UA": "Ruhia (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromania",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Hainamana",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sai": "Te Reo Inia o Amerika ki te Tonga",
  "sal": "Reo Harihi",
  "sam": "Hamaria Hamaria",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Harariniana",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinia",
  "sdh": "Kurdish ki te Tonga",
  "se": "Sami ki te Raki",
  "se_FI": "Sami ki te Raki (Pinetana)",
  "se_NO": "Sami ki te Raki (Norway)",
  "se_SE": "Sami ki te Raki (Sweden)",
  "see": "Seneca",
  "seh": "Hena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Reo Semitita",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central Africa Republic)",
  "sga": "Irish tawhito",
  "sgn": "Reo Waitohu",
  "sgs": "Samogitian",
  "sh": "Hoko-Croatia",
  "sh_BA": "Serbo-Kroati (Bosnia & Herzegovina)",
  "shi": "Shilha",
  "shi_Latn": "Shilha (Latina)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Arapia Chadian",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Reo Siouan",
  "sit": "Reo Hinengaro-Tibet",
  "sk": "Korowhai",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sla": "Reo Slavic",
  "sli": "Silesian Raro",
  "sly": "Selayar",
  "sm": "Hāmoa",
  "sma": "Sami ki te Tonga",
  "smi": "Reo Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somali",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Etiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdien",
  "son": "Songhai",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Maketonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia me Herzegovina)",
  "sr_Cyrl": "Serbian (Hiririki)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssa": "Reo Nilo-Saharan",
  "ssy": "Saho",
  "st": "Sotho ki te Tonga",
  "stq": "Saterland Frisian",
  "su": "Sundana",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Huitene",
  "sv_AX": "Huitene (Islandsland Islands)",
  "sv_FI": "Huitene (Pinetana)",
  "sv_SE": "Huitene (Sweden)",
  "sw": "Swahili",
  "sw_CD": "Kongo Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Komorana",
  "swc": "Kongo Swahili",
  "syc": "Syriac Tauhira",
  "syr": "Hiriani",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamati (Inia)",
  "ta_LK": "Tamati (Sri Lanka)",
  "ta_MY": "Tamati (Malaysia)",
  "ta_SG": "Tamil (Singapore)",
  "tai": "Reo Tai",
  "tcy": "Tulu",
  "te": "Hinuka",
  "te_IN": "Katini (Inia)",
  "tem": "Wā",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "Thai",
  "th_TH": "Thai (Thailand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Etiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tonga",
  "to_TO": "Tonga (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Korukure",
  "tr_CY": "Turkish (Kaiperu)",
  "tr_TR": "Turkish (Turkey)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tattoo",
  "tum": "Tumbuka",
  "tup": "Te Reo Tupi",
  "tut": "Reo Altaic",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahiti",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arapi)",
  "ug_Arab_CN": "Uyghur (Arapi, Haina)",
  "ug_CN": "Uyghur (Haina)",
  "uga": "Ugaritic",
  "uk": "Iukereiniana",
  "uk_UA": "Iukureini (Iukureini)",
  "umb": "Umbundu",
  "und": "Reo Tē Mōhiotia",
  "ur": "Urdu",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arapi)",
  "uz_Arab_AF": "Uzbek (Arapi, Afghanistan)",
  "uz_Cyrl": "Uzbek (Hiririki)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "vai_Latn": "Vai (Latina)",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Vietnamese",
  "vi_VN": "Vietnamese (Vietnam)",
  "vls": "Flemish Hauauru",
  "vmf": "Matua-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wak": "Reo Wakashan",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Reo Turikana",
  "wo": "Wolof",
  "wuu": "Wu Hainamana",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Hineramana",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Hapanihi",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "ypk": "Reo Yupik",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "yue_Hans": "Cantonese (Hainamana Maama)",
  "yue_Hant": "Cantonese (Hainamana Tawhito)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Tohu Koretake",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Paerewa Moroccan Tamazight",
  "zh": "Hainamana",
  "zh_CN": "Hainamana (Haina)",
  "zh_HK": "Hainamana (Hong Kong SAR Haina)",
  "zh_Hans": "Hainamana Māmā",
  "zh_Hans_CN": "Hainamana (Maama, Haina)",
  "zh_Hans_HK": "Hainamana (Maama, Hong Kong SAR Haina)",
  "zh_Hans_MO": "Hainamana (Maama, Macau SAR Haina)",
  "zh_Hans_SG": "Hainamana (Maama, Singapore)",
  "zh_Hant": "Hainamana Tukuiho",
  "zh_Hant_HK": "Hainamana (Tawhito, Hong Kong SAR Haina)",
  "zh_Hant_MO": "Hainamana (Taketake, Macau SAR Haina)",
  "zh_Hant_TW": "Hainamana (Tawhito, Taiwan)",
  "zh_MO": "Hainamana (Macau SAR China)",
  "zh_SG": "Hainamana (Singapore)",
  "zh_TW": "Hainamana (Taiwan)",
  "znd": "Zande",
  "zu": "Zulu",
  "zu_ZA": "Zulu (Awherika ki te Tonga)",
  "zun": "Zuni",
  "zxx": "Kaore he korero reo",
  "zza": "Zaza"
};
