const names = {
  "001": "máilbmi",
  "002": "Afrihkká",
  "003": "dávvi-Amerihkká ja gaska-Amerihkká",
  "005": "mátta-Amerihkká",
  "009": "Oseania",
  "011": "oarji-Afrihkká",
  "013": "gaska-Amerihkká",
  "014": "nuorta-Afrihkká",
  "015": "davvi-Afrihkká",
  "017": "gaska-Afrihkká",
  "018": "mátta-Afrihkká",
  "019": "Amerihkká",
  "021": "dávvi-Amerihkká",
  "029": "Karibia",
  "030": "nuorta-Ásia",
  "034": "mátta-Ásia",
  "035": "mátta-nuorta-Ásia",
  "039": "mátta-Eurohpá",
  "053": "Austrália ja Ođđa-Selánda",
  "054": "Melanesia",
  "057": "Mikronesia guovllus",
  "061": "Polynesia",
  "142": "Ásia",
  "143": "gaska-Ásia",
  "145": "oarji-Ásia",
  "150": "Eurohpá",
  "151": "nuorta-Eurohpá",
  "154": "davvi-Eurohpá",
  "155": "oarji-Eurohpá",
  "419": "lulli-Amerihkká",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Ovttastuvvan Arábaemiráhtat",
  "AF": "Afghanistan",
  "AG": "Antigua ja Barbuda",
  "AI": "Anguilla",
  "AL": "Albánia",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antárktis",
  "AR": "Argentina",
  "AS": "Amerihká Samoa",
  "AT": "Nuortariika",
  "AU": "Austrália",
  "AW": "Aruba",
  "AX": "Ålánda",
  "AZ": "Aserbaižan",
  "Arab": "arába",
  "BA": "Bosnia-Hercegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgária",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Vuolleeatnamat Karibe",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet-sullot",
  "BW": "Botswana",
  "BY": "Vilges-Ruošša",
  "BZ": "Belize",
  "CA": "Kanáda",
  "CC": "Cocos-sullot",
  "CD": "Kongo-Kinshasa",
  "CF": "Gaska-Afrihká dásseváldi",
  "CG": "Kongo-Brazzaville",
  "CH": "Šveica",
  "CI": "Elfenbenariddu",
  "CK": "Cook-sullot",
  "CL": "Čiile",
  "CM": "Kamerun",
  "CN": "Kiinná",
  "CO": "Kolombia",
  "CP": "Clipperton-sullot",
  "CR": "Costa Rica",
  "CU": "Kuba",
  "CV": "Kap Verde",
  "CW": "Curaçao",
  "CX": "Juovllat-sullot",
  "CY": "Kypros",
  "CZ": "Čeahkka",
  "Cyrl": "kyrillalaš",
  "DE": "Duiska",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Dánmárku",
  "DM": "Dominica",
  "DO": "Dominikána dásseváldi",
  "DZ": "Algeria",
  "EA": "Ceuta ja Melilla",
  "EC": "Ecuador",
  "EE": "Estlánda",
  "EG": "Egypta",
  "EH": "Oarje-Sahára",
  "ER": "Eritrea",
  "ES": "Spánia",
  "ET": "Etiopia",
  "EU": "Eurohpa Uniovdna",
  "FI": "Suopma",
  "FJ": "Fijisullot",
  "FK": "Falklandsullot",
  "FM": "Mikronesia",
  "FO": "Fearsullot",
  "FR": "Frankriika",
  "GA": "Gabon",
  "GB": "Stuorra-Británnia",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Frankriikka Guayana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Kalaallit Nunaat",
  "GM": "Gámbia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Ekvatoriála Guinea",
  "GR": "Greika",
  "GS": "Lulli Georgia ja Lulli Sandwich-sullot",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Grek": "greikkalaš",
  "HK": "Hongkong",
  "HM": "Heard- ja McDonald-sullot",
  "HN": "Honduras",
  "HR": "Kroátia",
  "HT": "Haiti",
  "HU": "Ungár",
  "Hang": "hangul",
  "Hani": "kiinnaš",
  "Hans": "álki",
  "Hant": "árbevirolaš",
  "Hira": "hiragana",
  "IC": "Kanáriasullot",
  "ID": "Indonesia",
  "IE": "Irlánda",
  "IL": "Israel",
  "IM": "Mann-sullot",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Islánda",
  "IT": "Itália",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordánia",
  "JP": "Japána",
  "KE": "Kenia",
  "KG": "Kirgisistan",
  "KH": "Kambodža",
  "KI": "Kiribati",
  "KM": "Komoros",
  "KN": "Saint Kitts ja Nevis",
  "KP": "Davvi-Korea",
  "KR": "Mátta-Korea",
  "KW": "Kuwait",
  "KY": "Cayman-sullot",
  "KZ": "Kasakstan",
  "Kana": "katakana",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lietuva",
  "LU": "Luxembourg",
  "LV": "Látvia",
  "LY": "Libya",
  "Latn": "láhtenaš",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldávia",
  "ME": "Montenegro",
  "MF": "Frankriikka Saint Martin",
  "MG": "Madagaskar",
  "MH": "Marshallsullot",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Burma",
  "MN": "Mongolia",
  "MO": "Makáo",
  "MP": "Davvi-Mariánat",
  "MQ": "Martinique",
  "MR": "Mauretánia",
  "MS": "Montserrat",
  "MT": "Málta",
  "MU": "Mauritius",
  "MV": "Malediivvat",
  "MW": "Malawi",
  "MX": "Meksiko",
  "MY": "Malesia",
  "MZ": "Mosambik",
  "NA": "Namibia",
  "NC": "Ođđa-Kaledonia",
  "NE": "Niger",
  "NF": "Norfolksullot",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Vuolleeatnamat",
  "NO": "Norga",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Ođđa-Selánda",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Frankriikka Polynesia",
  "PG": "Papua-Ođđa-Guinea",
  "PH": "Filippiinnat",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint Pierre ja Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Palestina",
  "PT": "Portugála",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Románia",
  "RS": "Serbia",
  "RU": "Ruošša",
  "RW": "Rwanda",
  "SA": "Saudi-Arábia",
  "SB": "Salomon-sullot",
  "SC": "Seychellsullot",
  "SD": "Davvisudan",
  "SE": "Ruoŧŧa",
  "SG": "Singapore",
  "SH": "Saint Helena",
  "SI": "Slovenia",
  "SJ": "Svalbárda ja Jan Mayen",
  "SK": "Slovákia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somália",
  "SR": "Surinam",
  "SS": "Máttasudan",
  "ST": "São Tomé ja Príncipe",
  "SV": "El Salvador",
  "SX": "Vuolleeatnamat Saint Martin",
  "SY": "Syria",
  "SZ": "Svazieana",
  "TA": "Tristan da Cunha",
  "TC": "Turks ja Caicos-sullot",
  "TD": "Tčad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thaieana",
  "TJ": "Tažikistan",
  "TK": "Tokelau",
  "TL": "Nuorta-Timor",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Durka",
  "TT": "Trinidad ja Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzánia",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "U.S. Outlying Islands",
  "US": "Amerihká ovttastuvvan stáhtat",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "VA": "Vatikána",
  "VC": "Saint Vincent ja Grenadine",
  "VE": "Venezuela",
  "VG": "Brittania Virgin-sullot",
  "VI": "AOS Virgin-sullot",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis ja Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Jemen",
  "YT": "Mayotte",
  "ZA": "Mátta-Afrihká",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "dovdameahttun guovlu",
  "Zxxx": "orrut chállojuvvot",
  "Zzzz": "dovdameahttun chállin",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "acehgiella",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "afrikánsagiella",
  "af_NA": "afrikánsagiella (Namibia)",
  "af_ZA": "afrikánsagiella (Mátta-Afrihká)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Amharic",
  "am_ET": "Amharic (Ethiopia)",
  "an": "aragoniagiella",
  "ang": "boares eaŋgalasgiella",
  "anp": "Angika",
  "ar": "arábagiella",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "arábagiella (Ovttastuvvan Arábaemiráhtat)",
  "ar_BH": "arábagiella (Bahrain)",
  "ar_DJ": "arábagiella (Djibouti)",
  "ar_DZ": "arábagiella (Algeria)",
  "ar_EG": "arábagiella (Egypta)",
  "ar_EH": "arábagiella (Oarje-Sahára)",
  "ar_ER": "arábagiella (Eritrea)",
  "ar_IL": "arábagiella (Israel)",
  "ar_IQ": "arábagiella (Irak)",
  "ar_JO": "arábagiella (Jordánia)",
  "ar_KM": "arábagiella (Komoros)",
  "ar_KW": "arábagiella (Kuwait)",
  "ar_LB": "arábagiella (Libanon)",
  "ar_LY": "arábagiella (Libya)",
  "ar_MA": "arábagiella (Marokko)",
  "ar_MR": "arábagiella (Mauretánia)",
  "ar_OM": "arábagiella (Oman)",
  "ar_PS": "arábagiella (Palestina)",
  "ar_QA": "arábagiella (Qatar)",
  "ar_SA": "arábagiella (Saudi-Arábia)",
  "ar_SD": "arábagiella (Davvisudan)",
  "ar_SO": "arábagiella (Somália)",
  "ar_SS": "arábagiella (Máttasudan)",
  "ar_SY": "arábagiella (Syria)",
  "ar_TD": "arábagiella (Tčad)",
  "ar_TN": "arábagiella (Tunisia)",
  "ar_YE": "arábagiella (Jemen)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "asturiagiella",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "vilges-ruoššagiella",
  "be_BY": "vilges-ruoššagiella (Vilges-Ruošša)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "bulgáriagiella",
  "bg_BG": "bulgáriagiella (Bulgária)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "bengalgiella",
  "bn_BD": "bengalgiella (Bangladesh)",
  "bn_IN": "bengalgiella (India)",
  "bo": "tibetagiella",
  "bo_CN": "tibetagiella (Kiinná)",
  "bo_IN": "tibetagiella (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretonagiella",
  "br_FR": "bretonagiella (Frankriika)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "bosniagiella",
  "bs_BA": "bosniagiella (Bosnia-Hercegovina)",
  "bs_Cyrl": "bosniagiella (kyrillalaš)",
  "bs_Cyrl_BA": "bosniagiella (kyrillalaš, Bosnia-Hercegovina)",
  "bs_Latn": "bosniagiella (láhtenaš)",
  "bs_Latn_BA": "bosniagiella (láhtenaš, Bosnia-Hercegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "katalánagiella",
  "ca_AD": "katalánagiella (Andorra)",
  "ca_ES": "katalánagiella (Spánia)",
  "ca_FR": "katalánagiella (Frankriika)",
  "ca_IT": "katalánagiella (Itália)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "marigiella",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "corsicagiella",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "čeahkagiella",
  "cs_CZ": "čeahkagiella (Čeahkka)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "kymragiella",
  "cy_GB": "kymragiella (Stuorra-Británnia)",
  "da": "dánskkagiella",
  "da_DK": "dánskkagiella (Dánmárku)",
  "da_GL": "dánskkagiella (Kalaallit Nunaat)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "duiskkagiella",
  "de_AT": "duiskkagiella (Nuortariika)",
  "de_BE": "duiskkagiella (Belgia)",
  "de_CH": "duiskkagiella (Šveica)",
  "de_DE": "duiskkagiella (Duiska)",
  "de_LI": "duiskkagiella (Liechtenstein)",
  "de_LU": "duiskkagiella (Luxembourg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "divehigiella",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "dzongkhagiella",
  "dz_BT": "dzongkhagiella (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "greikkagiella",
  "el_CY": "greikkagiella (Kypros)",
  "el_GR": "greikkagiella (Greika)",
  "elx": "Elamite",
  "en": "eaŋgalsgiella",
  "en_AG": "eaŋgalsgiella (Antigua ja Barbuda)",
  "en_AI": "eaŋgalsgiella (Anguilla)",
  "en_AS": "eaŋgalsgiella (Amerihká Samoa)",
  "en_AU": "eaŋgalsgiella (Austrália)",
  "en_BB": "eaŋgalsgiella (Barbados)",
  "en_BE": "eaŋgalsgiella (Belgia)",
  "en_BM": "eaŋgalsgiella (Bermuda)",
  "en_BS": "eaŋgalsgiella (Bahamas)",
  "en_BW": "eaŋgalsgiella (Botswana)",
  "en_BZ": "eaŋgalsgiella (Belize)",
  "en_CA": "eaŋgalsgiella (Kanáda)",
  "en_CC": "eaŋgalsgiella (Cocos-sullot)",
  "en_CK": "eaŋgalsgiella (Cook-sullot)",
  "en_CM": "eaŋgalsgiella (Kamerun)",
  "en_CX": "eaŋgalsgiella (Juovllat-sullot)",
  "en_DG": "eaŋgalsgiella (Diego Garcia)",
  "en_DM": "eaŋgalsgiella (Dominica)",
  "en_ER": "eaŋgalsgiella (Eritrea)",
  "en_FJ": "eaŋgalsgiella (Fijisullot)",
  "en_FK": "eaŋgalsgiella (Falklandsullot)",
  "en_FM": "eaŋgalsgiella (Mikronesia)",
  "en_GB": "eaŋgalsgiella (Stuorra-Británnia)",
  "en_GD": "eaŋgalsgiella (Grenada)",
  "en_GG": "eaŋgalsgiella (Guernsey)",
  "en_GH": "eaŋgalsgiella (Ghana)",
  "en_GI": "eaŋgalsgiella (Gibraltar)",
  "en_GM": "eaŋgalsgiella (Gámbia)",
  "en_GU": "eaŋgalsgiella (Guam)",
  "en_GY": "eaŋgalsgiella (Guyana)",
  "en_HK": "eaŋgalsgiella (Hongkong)",
  "en_IE": "eaŋgalsgiella (Irlánda)",
  "en_IM": "eaŋgalsgiella (Mann-sullot)",
  "en_IN": "eaŋgalsgiella (India)",
  "en_IO": "English (British Indian Ocean Territory)",
  "en_JE": "eaŋgalsgiella (Jersey)",
  "en_JM": "eaŋgalsgiella (Jamaica)",
  "en_KE": "eaŋgalsgiella (Kenia)",
  "en_KI": "eaŋgalsgiella (Kiribati)",
  "en_KN": "eaŋgalsgiella (Saint Kitts ja Nevis)",
  "en_KY": "eaŋgalsgiella (Cayman-sullot)",
  "en_LC": "eaŋgalsgiella (Saint Lucia)",
  "en_LR": "eaŋgalsgiella (Liberia)",
  "en_LS": "eaŋgalsgiella (Lesotho)",
  "en_MG": "eaŋgalsgiella (Madagaskar)",
  "en_MH": "eaŋgalsgiella (Marshallsullot)",
  "en_MO": "eaŋgalsgiella (Makáo)",
  "en_MP": "eaŋgalsgiella (Davvi-Mariánat)",
  "en_MS": "eaŋgalsgiella (Montserrat)",
  "en_MT": "eaŋgalsgiella (Málta)",
  "en_MU": "eaŋgalsgiella (Mauritius)",
  "en_MW": "eaŋgalsgiella (Malawi)",
  "en_MY": "eaŋgalsgiella (Malesia)",
  "en_NA": "eaŋgalsgiella (Namibia)",
  "en_NF": "eaŋgalsgiella (Norfolksullot)",
  "en_NG": "eaŋgalsgiella (Nigeria)",
  "en_NR": "eaŋgalsgiella (Nauru)",
  "en_NU": "eaŋgalsgiella (Niue)",
  "en_NZ": "eaŋgalsgiella (Ođđa-Selánda)",
  "en_PG": "eaŋgalsgiella (Papua-Ođđa-Guinea)",
  "en_PH": "eaŋgalsgiella (Filippiinnat)",
  "en_PK": "eaŋgalsgiella (Pakistan)",
  "en_PN": "eaŋgalsgiella (Pitcairn)",
  "en_PR": "eaŋgalsgiella (Puerto Rico)",
  "en_PW": "eaŋgalsgiella (Palau)",
  "en_RW": "eaŋgalsgiella (Rwanda)",
  "en_SB": "eaŋgalsgiella (Salomon-sullot)",
  "en_SC": "eaŋgalsgiella (Seychellsullot)",
  "en_SD": "eaŋgalsgiella (Davvisudan)",
  "en_SG": "eaŋgalsgiella (Singapore)",
  "en_SH": "eaŋgalsgiella (Saint Helena)",
  "en_SL": "eaŋgalsgiella (Sierra Leone)",
  "en_SS": "eaŋgalsgiella (Máttasudan)",
  "en_SX": "eaŋgalsgiella (Vuolleeatnamat Saint Martin)",
  "en_SZ": "eaŋgalsgiella (Svazieana)",
  "en_TC": "eaŋgalsgiella (Turks ja Caicos-sullot)",
  "en_TK": "eaŋgalsgiella (Tokelau)",
  "en_TO": "eaŋgalsgiella (Tonga)",
  "en_TT": "eaŋgalsgiella (Trinidad ja Tobago)",
  "en_TV": "eaŋgalsgiella (Tuvalu)",
  "en_TZ": "eaŋgalsgiella (Tanzánia)",
  "en_UG": "eaŋgalsgiella (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "eaŋgalsgiella (Amerihká ovttastuvvan stáhtat)",
  "en_VC": "eaŋgalsgiella (Saint Vincent ja Grenadine)",
  "en_VG": "eaŋgalsgiella (Brittania Virgin-sullot)",
  "en_VI": "eaŋgalsgiella (AOS Virgin-sullot)",
  "en_VU": "eaŋgalsgiella (Vanuatu)",
  "en_WS": "eaŋgalsgiella (Samoa)",
  "en_ZA": "eaŋgalsgiella (Mátta-Afrihká)",
  "en_ZM": "eaŋgalsgiella (Zambia)",
  "en_ZW": "eaŋgalsgiella (Zimbabwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "spánskkagiella",
  "es_419": "Latin American Spanish",
  "es_AR": "spánskkagiella (Argentina)",
  "es_BO": "spánskkagiella (Bolivia)",
  "es_CL": "spánskkagiella (Čiile)",
  "es_CO": "spánskkagiella (Kolombia)",
  "es_CR": "spánskkagiella (Costa Rica)",
  "es_CU": "spánskkagiella (Kuba)",
  "es_DO": "spánskkagiella (Dominikána dásseváldi)",
  "es_EA": "spánskkagiella (Ceuta ja Melilla)",
  "es_EC": "spánskkagiella (Ecuador)",
  "es_ES": "spánskkagiella (Spánia)",
  "es_GQ": "spánskkagiella (Ekvatoriála Guinea)",
  "es_GT": "spánskkagiella (Guatemala)",
  "es_HN": "spánskkagiella (Honduras)",
  "es_IC": "spánskkagiella (Kanáriasullot)",
  "es_MX": "spánskkagiella (Meksiko)",
  "es_NI": "spánskkagiella (Nicaragua)",
  "es_PA": "spánskkagiella (Panama)",
  "es_PE": "spánskkagiella (Peru)",
  "es_PH": "spánskkagiella (Filippiinnat)",
  "es_PR": "spánskkagiella (Puerto Rico)",
  "es_PY": "spánskkagiella (Paraguay)",
  "es_SV": "spánskkagiella (El Salvador)",
  "es_US": "spánskkagiella (Amerihká ovttastuvvan stáhtat)",
  "es_UY": "spánskkagiella (Uruguay)",
  "es_VE": "spánskkagiella (Venezuela)",
  "esu": "Central Yupik",
  "et": "esttegiella",
  "et_EE": "esttegiella (Estlánda)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "persijagiella",
  "fa_AF": "persijagiella (Afghanistan)",
  "fa_IR": "persijagiella (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "suomagiella",
  "fi_FI": "suomagiella (Suopma)",
  "fil": "filippiinnagiella",
  "fit": "Tornedalen Finnish",
  "fj": "fidjigiella",
  "fo": "fearagiella",
  "fo_FO": "fearagiella (Fearsullot)",
  "fon": "Fon",
  "fr": "fránskkagiella",
  "fr_BE": "fránskkagiella (Belgia)",
  "fr_BF": "fránskkagiella (Burkina Faso)",
  "fr_BI": "fránskkagiella (Burundi)",
  "fr_BJ": "fránskkagiella (Benin)",
  "fr_BL": "fránskkagiella (Saint Barthélemy)",
  "fr_CA": "fránskkagiella (Kanáda)",
  "fr_CD": "fránskkagiella (Kongo-Kinshasa)",
  "fr_CF": "fránskkagiella (Gaska-Afrihká dásseváldi)",
  "fr_CG": "fránskkagiella (Kongo-Brazzaville)",
  "fr_CH": "fránskkagiella (Šveica)",
  "fr_CI": "fránskkagiella (Elfenbenariddu)",
  "fr_CM": "fránskkagiella (Kamerun)",
  "fr_DJ": "fránskkagiella (Djibouti)",
  "fr_DZ": "fránskkagiella (Algeria)",
  "fr_FR": "fránskkagiella (Frankriika)",
  "fr_GA": "fránskkagiella (Gabon)",
  "fr_GF": "fránskkagiella (Frankriikka Guayana)",
  "fr_GN": "fránskkagiella (Guinea)",
  "fr_GP": "fránskkagiella (Guadeloupe)",
  "fr_GQ": "fránskkagiella (Ekvatoriála Guinea)",
  "fr_HT": "fránskkagiella (Haiti)",
  "fr_KM": "fránskkagiella (Komoros)",
  "fr_LU": "fránskkagiella (Luxembourg)",
  "fr_MA": "fránskkagiella (Marokko)",
  "fr_MC": "fránskkagiella (Monaco)",
  "fr_MF": "fránskkagiella (Frankriikka Saint Martin)",
  "fr_MG": "fránskkagiella (Madagaskar)",
  "fr_ML": "fránskkagiella (Mali)",
  "fr_MQ": "fránskkagiella (Martinique)",
  "fr_MR": "fránskkagiella (Mauretánia)",
  "fr_MU": "fránskkagiella (Mauritius)",
  "fr_NC": "fránskkagiella (Ođđa-Kaledonia)",
  "fr_NE": "fránskkagiella (Niger)",
  "fr_PF": "fránskkagiella (Frankriikka Polynesia)",
  "fr_PM": "fránskkagiella (Saint Pierre ja Miquelon)",
  "fr_RE": "fránskkagiella (Réunion)",
  "fr_RW": "fránskkagiella (Rwanda)",
  "fr_SC": "fránskkagiella (Seychellsullot)",
  "fr_SN": "fránskkagiella (Senegal)",
  "fr_SY": "fránskkagiella (Syria)",
  "fr_TD": "fránskkagiella (Tčad)",
  "fr_TG": "fránskkagiella (Togo)",
  "fr_TN": "fránskkagiella (Tunisia)",
  "fr_VU": "fránskkagiella (Vanuatu)",
  "fr_WF": "fránskkagiella (Wallis ja Futuna)",
  "fr_YT": "fránskkagiella (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "oarjifriisagiella",
  "fy_NL": "oarjifriisagiella (Vuolleeatnamat)",
  "ga": "iirragiella",
  "ga_IE": "iirragiella (Irlánda)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "gujaratagiella",
  "gu_IN": "gujaratagiella (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "manksgiella",
  "gv_IM": "manksgiella (Mann-sullot)",
  "gwi": "Gwichʼin",
  "ha": "haussagiella",
  "ha_GH": "haussagiella (Ghana)",
  "ha_Latn": "haussagiella (láhtenaš)",
  "ha_Latn_GH": "haussagiella (láhtenaš, Ghana)",
  "ha_Latn_NE": "haussagiella (láhtenaš, Niger)",
  "ha_Latn_NG": "haussagiella (láhtenaš, Nigeria)",
  "ha_NE": "haussagiella (Niger)",
  "ha_NG": "haussagiella (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "hawaiigiella",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "hindigiella",
  "hi_IN": "hindigiella (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "kroátiagiella",
  "hr_BA": "kroátiagiella (Bosnia-Hercegovina)",
  "hr_HR": "kroátiagiella (Kroátia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "haitigiella",
  "hu": "ungárgiella",
  "hu_HU": "ungárgiella (Ungár)",
  "hup": "Hupa",
  "hy": "armeenagiella",
  "hy_AM": "armeenagiella (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "indonesiagiella",
  "id_ID": "indonesiagiella (Indonesia)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "islánddagiella",
  "is_IS": "islánddagiella (Islánda)",
  "it": "itáliagiella",
  "it_CH": "itáliagiella (Šveica)",
  "it_IT": "itáliagiella (Itália)",
  "it_SM": "itáliagiella (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "japánagiella",
  "ja_JP": "japánagiella (Japána)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "javagiella",
  "ka": "georgiagiella",
  "ka_GE": "georgiagiella (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "kazakgiella",
  "kk_Cyrl": "kazakgiella (kyrillalaš)",
  "kk_Cyrl_KZ": "kazakgiella (kyrillalaš, Kasakstan)",
  "kk_KZ": "kazakgiella (Kasakstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "kambodiagiella",
  "km_KH": "kambodiagiella (Kambodža)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "koreagiella",
  "ko_KP": "koreagiella (Davvi-Korea)",
  "ko_KR": "koreagiella (Mátta-Korea)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "gárjilgiella",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "kurdigiella",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "komigiella",
  "kw": "kornagiella",
  "kw_GB": "kornagiella (Stuorra-Británnia)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "láhtengiella",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "luxemburggagiella",
  "lb_LU": "luxemburggagiella (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "laogiella",
  "lo_LA": "laogiella (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "liettuvagiella",
  "lt_LT": "liettuvagiella (Lietuva)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "látviagiella",
  "lv_LV": "látviagiella (Látvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "mokšagiella",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "maorigiella",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "makedoniagiella",
  "mk_MK": "makedoniagiella (Makedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "mongoliagiella",
  "mn_Cyrl": "mongoliagiella (kyrillalaš)",
  "mn_Cyrl_MN": "mongoliagiella (kyrillalaš, Mongolia)",
  "mn_MN": "mongoliagiella (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Malay",
  "ms_BN": "Malay (Brunei)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malay (Singapore)",
  "mt": "maltagiella",
  "mt_MT": "maltagiella (Málta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "burmagiella",
  "my_MM": "burmagiella (Burma)",
  "mye": "Myene",
  "myv": "ersagiella",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "girjedárogiella",
  "nb_NO": "girjedárogiella (Norga)",
  "nb_SJ": "girjedárogiella (Svalbárda ja Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "nepaligiella",
  "ne_IN": "nepaligiella (India)",
  "ne_NP": "nepaligiella (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "hollánddagiella",
  "nl_AW": "hollánddagiella (Aruba)",
  "nl_BE": "hollánddagiella (Belgia)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "hollánddagiella (Curaçao)",
  "nl_NL": "hollánddagiella (Vuolleeatnamat)",
  "nl_SR": "hollánddagiella (Surinam)",
  "nl_SX": "hollánddagiella (Vuolleeatnamat Saint Martin)",
  "nmg": "Kwasio",
  "nn": "ođđadárogiella",
  "nn_NO": "ođđadárogiella (Norga)",
  "nnh": "Ngiemboon",
  "no": "dárogiella",
  "no_NO": "dárogiella (Norga)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "oksitánagiella",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "panjabigiella",
  "pa_Arab": "panjabigiella (arába)",
  "pa_Arab_PK": "panjabigiella (arába, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "panjabigiella (India)",
  "pa_PK": "panjabigiella (Pakistan)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "polskkagiella",
  "pl_PL": "polskkagiella (Polen)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "portugálagiella",
  "pt_AO": "portugálagiella (Angola)",
  "pt_BR": "portugálagiella (Brasil)",
  "pt_CV": "portugálagiella (Kap Verde)",
  "pt_GW": "portugálagiella (Guinea-Bissau)",
  "pt_MO": "portugálagiella (Makáo)",
  "pt_MZ": "portugálagiella (Mosambik)",
  "pt_PT": "portugálagiella (Portugála)",
  "pt_ST": "portugálagiella (São Tomé ja Príncipe)",
  "pt_TL": "portugálagiella (Nuorta-Timor)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "romanšgiella",
  "rm_CH": "romanšgiella (Šveica)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "romániagiella",
  "ro_MD": "romániagiella (Moldávia)",
  "ro_RO": "romániagiella (Románia)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "ruoššagiella",
  "ru_BY": "ruoššagiella (Vilges-Ruošša)",
  "ru_KG": "ruoššagiella (Kirgisistan)",
  "ru_KZ": "ruoššagiella (Kasakstan)",
  "ru_MD": "ruoššagiella (Moldávia)",
  "ru_RU": "ruoššagiella (Ruošša)",
  "ru_UA": "ruoššagiella (Ukraina)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "sardigiella",
  "scn": "sisiliagiella",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "davvisámegiella",
  "se_FI": "davvisámegiella (Suopma)",
  "se_NO": "davvisámegiella (Norga)",
  "se_SE": "davvisámegiella (Ruoŧŧa)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "selkupagiella",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "serbokroatiagiella",
  "sh_BA": "serbokroatiagiella (Bosnia-Hercegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "slovákiagiella",
  "sk_SK": "slovákiagiella (Slovákia)",
  "sl": "slovenagiella",
  "sl_SI": "slovenagiella (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoagiella",
  "sma": "lullisámegiella",
  "smj": "julevsámegiella",
  "smn": "anárašgiella",
  "sms": "nuortalašgiella",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somali",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdien",
  "sq": "albánagiella",
  "sq_AL": "albánagiella (Albánia)",
  "sq_MK": "albánagiella (Makedonia)",
  "sq_XK": "albánagiella (Kosovo)",
  "sr": "serbiagiella",
  "sr_BA": "serbiagiella (Bosnia-Hercegovina)",
  "sr_Cyrl": "serbiagiella (kyrillalaš)",
  "sr_Cyrl_BA": "serbiagiella (kyrillalaš, Bosnia-Hercegovina)",
  "sr_Cyrl_ME": "serbiagiella (kyrillalaš, Montenegro)",
  "sr_Cyrl_RS": "serbiagiella (kyrillalaš, Serbia)",
  "sr_Cyrl_XK": "serbiagiella (kyrillalaš, Kosovo)",
  "sr_Latn": "serbiagiella (láhtenaš)",
  "sr_Latn_BA": "serbiagiella (láhtenaš, Bosnia-Hercegovina)",
  "sr_Latn_ME": "serbiagiella (láhtenaš, Montenegro)",
  "sr_Latn_RS": "serbiagiella (láhtenaš, Serbia)",
  "sr_Latn_XK": "serbiagiella (láhtenaš, Kosovo)",
  "sr_ME": "serbiagiella (Montenegro)",
  "sr_RS": "serbiagiella (Serbia)",
  "sr_XK": "serbiagiella (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "ruoŧagiella",
  "sv_AX": "ruoŧagiella (Ålánda)",
  "sv_FI": "ruoŧagiella (Suopma)",
  "sv_SE": "ruoŧagiella (Ruoŧŧa)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "shimaorigiella",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Malaysia)",
  "ta_SG": "Tamil (Singapore)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "ŧaigiella",
  "th_TH": "ŧaigiella (Thaieana)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "durkagiella",
  "tr_CY": "durkagiella (Kypros)",
  "tr_TR": "durkagiella (Durka)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "tahitigiella",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "udmurtagiella",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "ukrainagiella",
  "uk_UA": "ukrainagiella (Ukraina)",
  "umb": "Umbundu",
  "und": "dovdameahttun giella",
  "ur": "urdugiella",
  "ur_IN": "urdugiella (India)",
  "ur_PK": "urdugiella (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnamgiella",
  "vi_VN": "vietnamgiella (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "vallonagiella",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "kantongiella",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "kiinnágiella",
  "zh_CN": "kiinnágiella (Kiinná)",
  "zh_HK": "kiinnágiella (Hongkong)",
  "zh_Hans": "kiinnágiella (álki)",
  "zh_Hans_CN": "kiinnágiella (álki, Kiinná)",
  "zh_Hans_HK": "kiinnágiella (álki, Hongkong)",
  "zh_Hans_MO": "kiinnágiella (álki, Makáo)",
  "zh_Hans_SG": "kiinnágiella (álki, Singapore)",
  "zh_Hant": "kiinnágiella (árbevirolaš)",
  "zh_Hant_HK": "kiinnágiella (árbevirolaš, Hongkong)",
  "zh_Hant_MO": "kiinnágiella (árbevirolaš, Makáo)",
  "zh_Hant_TW": "kiinnágiella (árbevirolaš, Taiwan)",
  "zh_MO": "kiinnágiella (Makáo)",
  "zh_SG": "kiinnágiella (Singapore)",
  "zh_TW": "kiinnágiella (Taiwan)",
  "zu": "Zulu",
  "zu_ZA": "Zulu (South Africa)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
