const names = {
  "001": "Világ",
  "002": "Afrika",
  "003": "Észak-Amerika",
  "005": "Dél-Amerika",
  "009": "Óceánia",
  "011": "Nyugat-Afrika",
  "013": "Közép-Amerika",
  "014": "Kelet-Afrika",
  "015": "Észak-Afrika",
  "017": "Közép-Afrika",
  "018": "Afrika déli része",
  "019": "Amerika",
  "021": "Amerika északi része",
  "029": "Karib-térség",
  "030": "Kelet-Ázsia",
  "034": "Dél-Ázsia",
  "035": "Délkelet-Ázsia",
  "039": "Dél-Európa",
  "053": "Ausztrálázsia",
  "054": "Melanézia",
  "057": "Mikronéziai régió",
  "061": "Polinézia",
  "142": "Ázsia",
  "143": "Közép-Ázsia",
  "145": "Nyugat-Ázsia",
  "150": "Európa",
  "151": "Kelet-Európa",
  "154": "Észak-Európa",
  "155": "Nyugat-Európa",
  "202": "Szubszaharai Afrika",
  "419": "Latin-Amerika",
  "AC": "Ascension-sziget",
  "AD": "Andorra",
  "AE": "Egyesült Arab Emírségek",
  "AF": "Afganisztán",
  "AG": "Antigua és Barbuda",
  "AI": "Anguilla",
  "AL": "Albánia",
  "AM": "Örményország",
  "AN": "Holland Antillák",
  "AO": "Angola",
  "AQ": "Antarktisz",
  "AR": "Argentína",
  "AS": "Amerikai Szamoa",
  "AT": "Ausztria",
  "AU": "Ausztrália",
  "AW": "Aruba",
  "AX": "Åland-szigetek",
  "AZ": "Azerbajdzsán",
  "Arab": "Arab",
  "Aran": "Nasztalik",
  "Armi": "Birodalmi arámi",
  "Armn": "Örmény",
  "Avst": "Avesztán",
  "BA": "Bosznia-Hercegovina",
  "BB": "Barbados",
  "BD": "Banglades",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgária",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolívia",
  "BQ": "Holland Karib-térség",
  "BR": "Brazília",
  "BS": "Bahama-szigetek",
  "BT": "Bhután",
  "BV": "Bouvet-sziget",
  "BW": "Botswana",
  "BY": "Belarusz",
  "BZ": "Belize",
  "Bali": "Balinéz",
  "Batk": "Batak",
  "Beng": "Bengáli",
  "Blis": "Bliss jelképrendszer",
  "Bopo": "Bopomofo",
  "Brah": "Brámi",
  "Brai": "Vakírás",
  "Bugi": "Buginéz",
  "Buhd": "Buhid",
  "CA": "Kanada",
  "CC": "Kókusz (Keeling)-szigetek",
  "CD": "Kongó - Kinshasa",
  "CF": "Közép-afrikai Köztársaság",
  "CG": "Kongó - Brazzaville",
  "CH": "Svájc",
  "CI": "Elefántcsontpart",
  "CK": "Cook-szigetek",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "Kína",
  "CO": "Kolumbia",
  "CP": "Clipperton-sziget",
  "CR": "Costa Rica",
  "CS": "Szerbia és Montenegró",
  "CU": "Kuba",
  "CV": "Zöld-foki Köztársaság",
  "CW": "Curaçao",
  "CX": "Karácsony-sziget",
  "CY": "Ciprus",
  "CZ": "Csehország",
  "Cakm": "Csakma",
  "Cans": "Egyesített kanadai őslakos jelek",
  "Cari": "Kari",
  "Cham": "Csám",
  "Cher": "Cseroki",
  "Copt": "Kopt",
  "Cprt": "Ciprusi",
  "Cyrl": "Cirill",
  "Cyrs": "Óegyházi szláv cirill",
  "DE": "Németország",
  "DG": "Diego Garcia",
  "DJ": "Dzsibuti",
  "DK": "Dánia",
  "DM": "Dominika",
  "DO": "Dominikai Köztársaság",
  "DZ": "Algéria",
  "Deva": "Devanagári",
  "Dsrt": "Deseret",
  "EA": "Ceuta és Melilla",
  "EC": "Ecuador",
  "EE": "Észtország",
  "EG": "Egyiptom",
  "EH": "Nyugat-Szahara",
  "ER": "Eritrea",
  "ES": "Spanyolország",
  "ET": "Etiópia",
  "EU": "Európai Unió",
  "EZ": "Eurózóna",
  "Egyd": "Egyiptomi demotikus",
  "Egyh": "Egyiptomi hieratikus",
  "Egyp": "Egyiptomi hieroglifák",
  "Ethi": "Etióp",
  "FI": "Finnország",
  "FJ": "Fidzsi",
  "FK": "Falkland-szigetek",
  "FM": "Mikronézia",
  "FO": "Feröer szigetek",
  "FR": "Franciaország",
  "GA": "Gabon",
  "GB": "Egyesült Királyság",
  "GD": "Grenada",
  "GE": "Grúzia",
  "GF": "Francia Guyana",
  "GG": "Guernsey",
  "GH": "Ghána",
  "GI": "Gibraltár",
  "GL": "Grönland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Egyenlítői-Guinea",
  "GR": "Görögország",
  "GS": "Déli-Georgia és Déli-Sandwich-szigetek",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Bissau-Guinea",
  "GY": "Guyana",
  "Geok": "Grúz kucsuri",
  "Geor": "Grúz",
  "Glag": "Glagolitikus",
  "Goth": "Gót",
  "Grek": "Görög",
  "Gujr": "Gudzsaráti",
  "Guru": "Gurmuki",
  "HK": "Hongkong KKT",
  "HM": "Heard-sziget és McDonald-szigetek",
  "HN": "Honduras",
  "HR": "Horvátország",
  "HT": "Haiti",
  "HU": "Magyarország",
  "Hanb": "Han bopomofóval",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "Egyszerűsített",
  "Hant": "Hagyományos",
  "Hebr": "Héber",
  "Hira": "Hiragana",
  "Hmng": "Pahawh hmong",
  "Hrkt": "Katakana vagy hiragana",
  "Hung": "Ómagyar",
  "IC": "Kanári-szigetek",
  "ID": "Indonézia",
  "IE": "Írország",
  "IL": "Izrael",
  "IM": "Man-sziget",
  "IN": "India",
  "IO": "Brit Indiai-óceáni Terület",
  "IQ": "Irak",
  "IR": "Irán",
  "IS": "Izland",
  "IT": "Olaszország",
  "Inds": "Indus",
  "Ital": "Régi olasz",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordánia",
  "JP": "Japán",
  "Jamo": "Jamo",
  "Java": "Jávai",
  "Jpan": "Japán",
  "KE": "Kenya",
  "KG": "Kirgizisztán",
  "KH": "Kambodzsa",
  "KI": "Kiribati",
  "KM": "Comore-szigetek",
  "KN": "Saint Kitts és Nevis",
  "KP": "Észak-Korea",
  "KR": "Dél-Korea",
  "KW": "Kuvait",
  "KY": "Kajmán-szigetek",
  "KZ": "Kazahsztán",
  "Kali": "Kajah li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Knda": "Kannada",
  "Kore": "Koreai",
  "Kthi": "Kaithi",
  "LA": "Laosz",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Srí Lanka",
  "LR": "Libéria",
  "LS": "Lesotho",
  "LT": "Litvánia",
  "LU": "Luxemburg",
  "LV": "Lettország",
  "LY": "Líbia",
  "Lana": "Lanna",
  "Laoo": "Lao",
  "Latf": "Fraktur latin",
  "Latg": "Gael latin",
  "Latn": "Latin",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Lineáris A",
  "Linb": "Lineáris B",
  "Lyci": "Líciai",
  "Lydi": "Lídiai",
  "MA": "Marokkó",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegró",
  "MF": "Saint Martin",
  "MG": "Madagaszkár",
  "MH": "Marshall-szigetek",
  "MK": "Észak-Macedónia",
  "ML": "Mali",
  "MM": "Mianmar",
  "MN": "Mongólia",
  "MO": "Makaó KKT",
  "MP": "Északi Mariana-szigetek",
  "MQ": "Martinique",
  "MR": "Mauritánia",
  "MS": "Montserrat",
  "MT": "Málta",
  "MU": "Mauritius",
  "MV": "Maldív-szigetek",
  "MW": "Malawi",
  "MX": "Mexikó",
  "MY": "Malajzia",
  "MZ": "Mozambik",
  "Mand": "Mandai",
  "Mani": "Manicheus",
  "Maya": "Maja hieroglifák",
  "Mero": "Meroitikus",
  "Mlym": "Malajálam",
  "Mong": "Mongol",
  "Moon": "Moon",
  "Mtei": "Meitei mayek",
  "Mymr": "Burmai",
  "NA": "Namíbia",
  "NC": "Új-Kaledónia",
  "NE": "Niger",
  "NF": "Norfolk-sziget",
  "NG": "Nigéria",
  "NI": "Nicaragua",
  "NL": "Hollandia",
  "NO": "Norvégia",
  "NP": "Nepál",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Új-Zéland",
  "Nkoo": "N’ko",
  "OM": "Omán",
  "Ogam": "Ogham",
  "Olck": "Ol chiki",
  "Orkh": "Orhon",
  "Orya": "Oriya",
  "Osma": "Oszmán",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Francia Polinézia",
  "PG": "Pápua Új-Guinea",
  "PH": "Fülöp-szigetek",
  "PK": "Pakisztán",
  "PL": "Lengyelország",
  "PM": "Saint-Pierre és Miquelon",
  "PN": "Pitcairn-szigetek",
  "PR": "Puerto Rico",
  "PS": "Palesztin Terület",
  "PT": "Portugália",
  "PW": "Palau",
  "PY": "Paraguay",
  "Perm": "Ópermikus",
  "Phag": "Phags-pa",
  "Phli": "Felriatos pahlavi",
  "Phlp": "Psalter pahlavi",
  "Phlv": "Könyv pahlavi",
  "Phnx": "Főniciai",
  "Plrd": "Pollard fonetikus",
  "Prti": "Feliratos parthian",
  "QA": "Katar",
  "QO": "Külső-Óceánia",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Románia",
  "RS": "Szerbia",
  "RU": "Oroszország",
  "RW": "Ruanda",
  "Rjng": "Redzsang",
  "Roro": "Rongorongo",
  "Runr": "Runikus",
  "SA": "Szaúd-Arábia",
  "SB": "Salamon-szigetek",
  "SC": "Seychelle-szigetek",
  "SD": "Szudán",
  "SE": "Svédország",
  "SG": "Szingapúr",
  "SH": "Szent Ilona",
  "SI": "Szlovénia",
  "SJ": "Svalbard és Jan Mayen",
  "SK": "Szlovákia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Szenegál",
  "SO": "Szomália",
  "SR": "Suriname",
  "SS": "Dél-Szudán",
  "ST": "São Tomé és Príncipe",
  "SV": "Salvador",
  "SX": "Sint Maarten",
  "SY": "Szíria",
  "SZ": "Szváziföld",
  "Samr": "Szamaritán",
  "Sara": "Szarati",
  "Saur": "Szaurastra",
  "Sgnw": "Jelírás",
  "Shaw": "Shaw ábécé",
  "Sidd": "Sziddham",
  "Sinh": "Szingaléz",
  "Sogd": "Szogd",
  "Sogo": "Ószogd",
  "Sund": "Szundanéz",
  "Sylo": "Sylheti nagári",
  "Syrc": "Szíriai",
  "Syre": "Estrangelo szíriai",
  "Syrj": "Nyugat-szíriai",
  "Syrn": "Kelet-szíriai",
  "TA": "Tristan da Cunha",
  "TC": "Turks- és Caicos-szigetek",
  "TD": "Csád",
  "TF": "Francia Déli Területek",
  "TG": "Togo",
  "TH": "Thaiföld",
  "TJ": "Tádzsikisztán",
  "TK": "Tokelau",
  "TL": "Kelet-Timor",
  "TM": "Türkmenisztán",
  "TN": "Tunézia",
  "TO": "Tonga",
  "TR": "Törökország",
  "TT": "Trinidad és Tobago",
  "TV": "Tuvalu",
  "TW": "Tajvan",
  "TZ": "Tanzánia",
  "Tagb": "Tagbanwa",
  "Tale": "Tai Le",
  "Talu": "Új tai lue",
  "Taml": "Tamil",
  "Tavt": "Tai viet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Berber",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibeti",
  "UA": "Ukrajna",
  "UG": "Uganda",
  "UM": "Az USA lakatlan külbirtokai",
  "UN": "Egyesült Nemzetek Szervezete",
  "US": "Egyesült Államok",
  "UY": "Uruguay",
  "UZ": "Üzbegisztán",
  "Ugar": "Ugari",
  "VA": "Vatikán",
  "VC": "Saint Vincent és a Grenadine-szigetek",
  "VE": "Venezuela",
  "VG": "Brit Virgin-szigetek",
  "VI": "Amerikai Virgin-szigetek",
  "VN": "Vietnám",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Látható beszéd",
  "WF": "Wallis és Futuna",
  "WS": "Szamoa",
  "XA": "Pszeudo-nyelvjárások",
  "XB": "Pszeudo-kétirányú",
  "XK": "Koszovó",
  "Xpeo": "Óperzsa",
  "Xsux": "Ékírásos suméro-akkád",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yiii": "Ji",
  "ZA": "Dél-afrikai Köztársaság",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Ismeretlen körzet",
  "Zinh": "Származtatott",
  "Zmth": "Matematikai jelrendszer",
  "Zsye": "Emoji",
  "Zsym": "Szimbólum",
  "Zxxx": "Íratlan nyelvek kódja",
  "Zyyy": "Meghatározatlan",
  "Zzzz": "Ismeretlen írásrendszer",
  "aa": "afar",
  "ab": "abház",
  "ace": "achinéz",
  "ach": "akoli",
  "ada": "adangme",
  "ady": "adyghe",
  "ae": "avesztán",
  "aeb": "Tunisian Arabic",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namíbia)",
  "af_ZA": "afrikaans (Dél-afrikai Köztársaság)",
  "afa": "afroázsiai nyelv",
  "afh": "afrihili",
  "agq": "agem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Ghána)",
  "akk": "akkád",
  "akz": "Alabama",
  "ale": "aleut",
  "alg": "algonkin nyelv",
  "aln": "Gheg Albanian",
  "alt": "dél-altaji",
  "am": "amhara",
  "am_ET": "amhara (Etiópia)",
  "an": "aragonéz",
  "ang": "óangol",
  "anp": "angika",
  "apa": "apacs nyelvek",
  "ar": "arab",
  "ar_001": "modern szabányos arab",
  "ar_AE": "arab (Egyesült Arab Emirátus)",
  "ar_BH": "arab (Bahrein)",
  "ar_DJ": "arab (Dzsibuti)",
  "ar_DZ": "arab (Algéria)",
  "ar_EG": "arab (Egyiptom)",
  "ar_EH": "arab (Nyugat-Szahara)",
  "ar_ER": "arab (Eritrea)",
  "ar_IL": "arab (Izrael)",
  "ar_IQ": "arab (Irak)",
  "ar_JO": "arab (Jordánia)",
  "ar_KM": "arab (Comore-szigetek)",
  "ar_KW": "arab (Kuvait)",
  "ar_LB": "arab (Libanon)",
  "ar_LY": "arab (Líbia)",
  "ar_MA": "arab (Marokkó)",
  "ar_MR": "arab (Mauritánia)",
  "ar_OM": "arab (Omán)",
  "ar_PS": "arab (Palesztin Terület)",
  "ar_QA": "arab (Katar)",
  "ar_SA": "arab (Szaúd-Arábia)",
  "ar_SD": "arab (Szudán)",
  "ar_SO": "arab (Szomália)",
  "ar_SS": "arab (Dél-Szudán)",
  "ar_SY": "arab (Szíria)",
  "ar_TD": "arab (Csád)",
  "ar_TN": "arab (Tunézia)",
  "ar_YE": "arab (Jemen)",
  "arc": "arámi",
  "arn": "araucani",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "ars": "nedzsdi arab",
  "art": "mesterséges nyelv",
  "arw": "aravak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "asszámi",
  "as_IN": "asszámi (India)",
  "asa": "asu",
  "ase": "American Sign Language",
  "ast": "asztúr",
  "ath": "atapaszkan nyelvek",
  "aus": "ausztrál nyelvek",
  "av": "avar",
  "avk": "Kotava",
  "awa": "awádi",
  "ay": "ajmara",
  "az": "azerbajdzsáni",
  "az_AZ": "azerbajdzsáni (Azerbajdzsán)",
  "az_Cyrl": "azerbajdzsáni (Cirill)",
  "az_Cyrl_AZ": "azerbajdzsáni (Cirill, Azerbajdzsán)",
  "az_Latn": "azerbajdzsáni (Latin)",
  "az_Latn_AZ": "azerbajdzsáni (Latin, Azerbajdzsán)",
  "azb": "South Azerbaijani",
  "ba": "baskír",
  "bad": "banda",
  "bai": "bamileke nyelvek",
  "bal": "balucsi",
  "ban": "balinéz",
  "bar": "Bavarian",
  "bas": "basza",
  "bat": "balti nyelv",
  "bax": "bamun",
  "bbc": "Batak Toba",
  "bbj": "gomala",
  "be": "belorusz",
  "be_BY": "belorusz (Fehéroroszország)",
  "bej": "bedzsa",
  "bem": "bemba",
  "ber": "berber",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "Badaga",
  "bg": "bolgár",
  "bg_BG": "bolgár (Bulgária)",
  "bgn": "nyugati beludzs",
  "bh": "bihari",
  "bho": "bodzspuri",
  "bi": "bislama",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (Latin)",
  "bm_Latn_ML": "bambara (Latin, Mali)",
  "bn": "bengáli",
  "bn_BD": "bengáli (Banglades)",
  "bn_IN": "bengáli (India)",
  "bnt": "bantu",
  "bo": "tibeti",
  "bo_CN": "tibeti (Kína)",
  "bo_IN": "tibeti (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "breton",
  "br_FR": "breton (Franciaország)",
  "bra": "braj",
  "brh": "Brahui",
  "brx": "bodo",
  "bs": "bosnyák",
  "bs_BA": "bosnyák (Bosznia-Hercegovina)",
  "bs_Cyrl": "bosnyák (Cirill)",
  "bs_Cyrl_BA": "bosnyák (Cirill, Bosznia-Hercegovina)",
  "bs_Latn": "bosnyák (Latin)",
  "bs_Latn_BA": "bosnyák (Latin, Bosznia-Hercegovina)",
  "bss": "koszi",
  "btk": "batak",
  "bua": "burját",
  "bug": "buginéz",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "katalán",
  "ca_AD": "katalán (Andorra)",
  "ca_ES": "katalán (Spanyolország)",
  "ca_FR": "katalán (Franciaország)",
  "ca_IT": "katalán (Olaszország)",
  "cad": "caddo",
  "cai": "egyéb közép-amerikai indián",
  "car": "karib",
  "cau": "egyéb kaukázusi",
  "cay": "kajuga",
  "cch": "atszam",
  "ccp": "csakma",
  "ce": "csecsen",
  "ceb": "cebui",
  "cel": "egyéb kelta",
  "cgg": "kiga",
  "ch": "csamoró",
  "chb": "csibcsa",
  "chg": "csagatáj",
  "chk": "csukéz",
  "chm": "mari",
  "chn": "csinuk zsargon",
  "cho": "csoktó",
  "chp": "csipevé",
  "chr": "cseroki",
  "chy": "csejen",
  "ckb": "szoráni kurd",
  "cmc": "csam nyelv",
  "co": "korzikai",
  "cop": "kopt",
  "cpe": "egyéb angol alapú kreol és pidgin",
  "cpf": "egyéb francia alapú kreol és pidgin",
  "cpp": "portugál alapú kreol vagy pidgin",
  "cps": "Capiznon",
  "cr": "krí",
  "crh": "krími tatár",
  "crp": "kreol és pidzsin",
  "crs": "szeszelva kreol francia",
  "cs": "cseh",
  "cs_CZ": "cseh (Csehország)",
  "csb": "kasub",
  "cu": "egyházi szláv",
  "cus": "kusita nyelv",
  "cv": "csuvas",
  "cy": "walesi",
  "cy_GB": "walesi (Egyesült Királyság)",
  "da": "dán",
  "da_DK": "dán (Dánia)",
  "da_GL": "dán (Grönland)",
  "dak": "dakota",
  "dar": "dargva",
  "dav": "taita",
  "day": "dajak",
  "de": "német",
  "de_AT": "német (Ausztria)",
  "de_BE": "német (Belgium)",
  "de_CH": "német (Svájc)",
  "de_DE": "német (Németország)",
  "de_LI": "német (Liechtenstein)",
  "de_LU": "német (Luxemburg)",
  "del": "delavár",
  "den": "szlevi",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "egyéb dravida",
  "dsb": "alsó szorb",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "közép holland",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "diula",
  "dz": "butáni",
  "dz_BT": "butáni (Bhután)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "eve",
  "ee_GH": "eve (Ghána)",
  "ee_TG": "eve (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "óegyiptomi",
  "eka": "ekadzsuk",
  "el": "görög",
  "el_CY": "görög (Ciprus)",
  "el_GR": "görög (Görögország)",
  "elx": "elamit",
  "en": "angol",
  "en_AG": "angol (Antigua és Barbuda)",
  "en_AI": "angol (Anguilla)",
  "en_AS": "angol (Amerikai Szamoa)",
  "en_AU": "angol (Ausztrália)",
  "en_BB": "angol (Barbados)",
  "en_BE": "angol (Belgium)",
  "en_BM": "angol (Bermuda)",
  "en_BS": "angol (Bahama-szigetek)",
  "en_BW": "angol (Botswana)",
  "en_BZ": "angol (Belize)",
  "en_CA": "angol (Kanada)",
  "en_CC": "angol (Kókusz-szigetek)",
  "en_CK": "angol (Cook-szigetek)",
  "en_CM": "angol (Kamerun)",
  "en_CX": "angol (Karácsony-sziget)",
  "en_DG": "angol (Diego Garcia)",
  "en_DM": "angol (Dominika)",
  "en_ER": "angol (Eritrea)",
  "en_FJ": "angol (Fidzsi-szigetek)",
  "en_FK": "angol (Falkland-szigetek)",
  "en_FM": "angol (Mikronézia)",
  "en_GB": "angol (Egyesült Királyság)",
  "en_GD": "angol (Grenada)",
  "en_GG": "angol (Guernsey)",
  "en_GH": "angol (Ghána)",
  "en_GI": "angol (Gibraltár)",
  "en_GM": "angol (Gambia)",
  "en_GU": "angol (Guam)",
  "en_GY": "angol (Guyana)",
  "en_HK": "angol (Hongkong SAR Kína)",
  "en_IE": "angol (Írország)",
  "en_IM": "angol (Man-sziget)",
  "en_IN": "angol (India)",
  "en_IO": "angol (Brit Indiai-óceáni Terület)",
  "en_JE": "angol (Jersey)",
  "en_JM": "angol (Jamaica)",
  "en_KE": "angol (Kenya)",
  "en_KI": "angol (Kiribati)",
  "en_KN": "angol (Saint Kitts és Nevis)",
  "en_KY": "angol (Kajmán-szigetek)",
  "en_LC": "angol (Santa Lucia)",
  "en_LR": "angol (Libéria)",
  "en_LS": "angol (Lesotho)",
  "en_MG": "angol (Madagaszkár)",
  "en_MH": "angol (Marshall-szigetek)",
  "en_MO": "angol (Makaó SAR Kína)",
  "en_MP": "angol (Északi Mariana-szigetek)",
  "en_MS": "angol (Montserrat)",
  "en_MT": "angol (Málta)",
  "en_MU": "angol (Mauritius)",
  "en_MW": "angol (Malawi)",
  "en_MY": "angol (Malajzia)",
  "en_NA": "angol (Namíbia)",
  "en_NF": "angol (Norfolk-sziget)",
  "en_NG": "angol (Nigéria)",
  "en_NR": "angol (Nauru)",
  "en_NU": "angol (Niue)",
  "en_NZ": "angol (Új-Zéland)",
  "en_PG": "angol (Pápua Új-Guinea)",
  "en_PH": "angol (Fülöp-szigetek)",
  "en_PK": "angol (Pakisztán)",
  "en_PN": "angol (Pitcairn-szigetek)",
  "en_PR": "angol (Puerto Rico)",
  "en_PW": "angol (Palau)",
  "en_RW": "angol (Ruanda)",
  "en_SB": "angol (Salamon-szigetek)",
  "en_SC": "angol (Seychelle-szigetek)",
  "en_SD": "angol (Szudán)",
  "en_SG": "angol (Szingapúr)",
  "en_SH": "angol (Szent Ilona)",
  "en_SL": "angol (Sierra Leone)",
  "en_SS": "angol (Dél-Szudán)",
  "en_SX": "angol (Sint Maarten)",
  "en_SZ": "angol (Szváziföld)",
  "en_TC": "angol (Turks- és Caicos-szigetek)",
  "en_TK": "angol (Tokelau)",
  "en_TO": "angol (Tonga)",
  "en_TT": "angol (Trinidad és Tobago)",
  "en_TV": "angol (Tuvalu)",
  "en_TZ": "angol (Tanzánia)",
  "en_UG": "angol (Uganda)",
  "en_UM": "angol (Amerikai Csendes-óceáni Szigetek)",
  "en_US": "angol (Egyesült Államok)",
  "en_VC": "angol (Saint Vincent és a Grenadine-szigetek)",
  "en_VG": "angol (Brit Virgin-szigetek)",
  "en_VI": "angol (Amerikai Virgin-szigetek)",
  "en_VU": "angol (Vanuatu)",
  "en_WS": "angol (Szamoa)",
  "en_ZA": "angol (Dél-afrikai Köztársaság)",
  "en_ZM": "angol (Zambia)",
  "en_ZW": "angol (Zimbabwe)",
  "enm": "közép angol",
  "eo": "eszperantó",
  "es": "spanyol",
  "es_419": "latin-amerikai spanyol",
  "es_AR": "spanyol (Argentína)",
  "es_BO": "spanyol (Bolívia)",
  "es_CL": "spanyol (Chile)",
  "es_CO": "spanyol (Kolumbia)",
  "es_CR": "spanyol (Costa Rica)",
  "es_CU": "spanyol (Kuba)",
  "es_DO": "spanyol (Dominikai Köztársaság)",
  "es_EA": "spanyol (Ceuta és Melilla)",
  "es_EC": "spanyol (Ecuador)",
  "es_ES": "spanyol (Spanyolország)",
  "es_GQ": "spanyol (Egyenlítői-Guinea)",
  "es_GT": "spanyol (Guatemala)",
  "es_HN": "spanyol (Honduras)",
  "es_IC": "spanyol (Kanári-szigetek)",
  "es_MX": "spanyol (Mexikó)",
  "es_NI": "spanyol (Nicaragua)",
  "es_PA": "spanyol (Panama)",
  "es_PE": "spanyol (Peru)",
  "es_PH": "spanyol (Fülöp-szigetek)",
  "es_PR": "spanyol (Puerto Rico)",
  "es_PY": "spanyol (Paraguay)",
  "es_SV": "spanyol (Salvador)",
  "es_US": "spanyol (Egyesült Államok)",
  "es_UY": "spanyol (Uruguay)",
  "es_VE": "spanyol (Venezuela)",
  "esu": "Central Yupik",
  "et": "észt",
  "et_EE": "észt (Észtország)",
  "eu": "baszk",
  "eu_ES": "baszk (Spanyolország)",
  "ewo": "evondo",
  "ext": "Extremaduran",
  "fa": "perzsa",
  "fa_AF": "perzsa (Afganisztán)",
  "fa_IR": "perzsa (Irán)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fulani",
  "ff_CM": "fulani (Kamerun)",
  "ff_GN": "fulani (Guinea)",
  "ff_MR": "fulani (Mauritánia)",
  "ff_SN": "fulani (Szenegál)",
  "fi": "finn",
  "fi_FI": "finn (Finnország)",
  "fil": "filippínó",
  "fit": "Tornedalen Finnish",
  "fiu": "finnugor nyelv",
  "fj": "fidzsi",
  "fo": "feröeri",
  "fo_FO": "feröeri (Feröer-szigetek)",
  "fon": "fon",
  "fr": "francia",
  "fr_BE": "francia (Belgium)",
  "fr_BF": "francia (Burkina Faso)",
  "fr_BI": "francia (Burundi)",
  "fr_BJ": "francia (Benin)",
  "fr_BL": "francia (Saint-Barthélemy)",
  "fr_CA": "francia (Kanada)",
  "fr_CD": "francia (Kongó - Kinshasa)",
  "fr_CF": "francia (Közép-afrikai Köztársaság)",
  "fr_CG": "francia (Kongó - Brazzaville)",
  "fr_CH": "francia (Svájc)",
  "fr_CI": "francia (Elefántcsontpart)",
  "fr_CM": "francia (Kamerun)",
  "fr_DJ": "francia (Dzsibuti)",
  "fr_DZ": "francia (Algéria)",
  "fr_FR": "francia (Franciaország)",
  "fr_GA": "francia (Gabon)",
  "fr_GF": "francia (Francia Guyana)",
  "fr_GN": "francia (Guinea)",
  "fr_GP": "francia (Guadeloupe)",
  "fr_GQ": "francia (Egyenlítői-Guinea)",
  "fr_HT": "francia (Haiti)",
  "fr_KM": "francia (Comore-szigetek)",
  "fr_LU": "francia (Luxemburg)",
  "fr_MA": "francia (Marokkó)",
  "fr_MC": "francia (Monaco)",
  "fr_MF": "francia (Saint Martin)",
  "fr_MG": "francia (Madagaszkár)",
  "fr_ML": "francia (Mali)",
  "fr_MQ": "francia (Martinique)",
  "fr_MR": "francia (Mauritánia)",
  "fr_MU": "francia (Mauritius)",
  "fr_NC": "francia (Új-Kaledónia)",
  "fr_NE": "francia (Niger)",
  "fr_PF": "francia (Francia Polinézia)",
  "fr_PM": "francia (Saint Pierre és Miquelon)",
  "fr_RE": "francia (Reunion)",
  "fr_RW": "francia (Ruanda)",
  "fr_SC": "francia (Seychelle-szigetek)",
  "fr_SN": "francia (Szenegál)",
  "fr_SY": "francia (Szíria)",
  "fr_TD": "francia (Csád)",
  "fr_TG": "francia (Togo)",
  "fr_TN": "francia (Tunézia)",
  "fr_VU": "francia (Vanuatu)",
  "fr_WF": "francia (Wallis- és Futuna-szigetek)",
  "fr_YT": "francia (Mayotte)",
  "frc": "cajun francia",
  "frm": "közép francia",
  "fro": "ófrancia",
  "frp": "Arpitan",
  "frr": "északi fríz",
  "frs": "keleti fríz",
  "fur": "friuli",
  "fy": "nyugati fríz",
  "fy_NL": "fríz (Hollandia)",
  "ga": "ír",
  "ga_IE": "ír (Írország)",
  "gaa": "ga",
  "gag": "gagauz",
  "gan": "gan kínai",
  "gay": "gajo",
  "gba": "gbaja",
  "gbz": "Zoroastrian Dari",
  "gd": "skót gael",
  "gd_GB": "skót gael (Egyesült Királyság)",
  "gem": "germán nyelv",
  "gez": "geez",
  "gil": "ikiribati",
  "gl": "galíciai",
  "gl_ES": "galíciai (Spanyolország)",
  "glk": "Gilaki",
  "gmh": "közép felső német",
  "gn": "guarani",
  "goh": "ófelső német",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gót",
  "grb": "grebó",
  "grc": "ógörög",
  "gsw": "svájci német",
  "gu": "gudzsarati",
  "gu_IN": "gudzsarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "guszii",
  "gv": "man-szigeti",
  "gv_IM": "man-szigeti (Man-sziget)",
  "gwi": "gvicsin",
  "ha": "hausza",
  "ha_GH": "hausza (Ghána)",
  "ha_Latn": "hausza (Latin)",
  "ha_Latn_GH": "hausza (Latin, Ghána)",
  "ha_Latn_NE": "hausza (Latin, Niger)",
  "ha_Latn_NG": "hausza (Latin, Nigéria)",
  "ha_NE": "hausza (Niger)",
  "ha_NG": "hausza (Nigéria)",
  "hai": "haida",
  "hak": "hakka kínai",
  "haw": "hawaii",
  "he": "héber",
  "he_IL": "héber (Izrael)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligajnon",
  "him": "himaháli",
  "hit": "hittite",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "horvát",
  "hr_BA": "horvát (Bosznia-Hercegovina)",
  "hr_HR": "horvát (Horvátország)",
  "hsb": "felső szorb",
  "hsn": "xiang kínai",
  "ht": "haiti kreol",
  "hu": "magyar",
  "hu_HU": "magyar (Magyarország)",
  "hup": "hupa",
  "hy": "örmény",
  "hy_AM": "örmény (Örményország)",
  "hz": "herero",
  "ia": "interlingva",
  "iba": "iban",
  "ibb": "ibibió",
  "id": "indonéz",
  "id_ID": "indonéz (Indonézia)",
  "ie": "interlingue",
  "ig": "igbó",
  "ig_NG": "igbó (Nigéria)",
  "ii": "szecsuán ji",
  "ii_CN": "szecsuán ji (Kína)",
  "ijo": "idzsó",
  "ik": "inupiak",
  "ilo": "ilokó",
  "inc": "egyéb indiai",
  "ine": "indoeurópai nyelv",
  "inh": "ingus",
  "io": "idó",
  "ira": "iráni",
  "iro": "irokéz nyelvek",
  "is": "izlandi",
  "is_IS": "izlandi (Izland)",
  "it": "olasz",
  "it_CH": "olasz (Svájc)",
  "it_IT": "olasz (Olaszország)",
  "it_SM": "olasz (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "japán",
  "ja_JP": "japán (Japán)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "zsidó-perzsa",
  "jrb": "zsidó-arab",
  "jut": "Jutish",
  "jv": "jávai",
  "ka": "grúz",
  "ka_GE": "grúz (Grúzia)",
  "kaa": "kara-kalpak",
  "kab": "kabije",
  "kac": "kacsin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "kabardi",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "kabuverdianu",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "Kaingang",
  "kha": "kaszi",
  "khi": "egyéb koiszan",
  "kho": "kotanéz",
  "khq": "kojra-csíni",
  "khw": "Khowar",
  "ki": "kikuju",
  "ki_KE": "kikuju (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "kazah",
  "kk_Cyrl": "kazah (Cirill)",
  "kk_Cyrl_KZ": "kazah (Cirill, Kazahsztán)",
  "kk_KZ": "kazah (Kazahsztán)",
  "kkj": "kakó",
  "kl": "grönlandi",
  "kl_GL": "grönlandi (Grönland)",
  "kln": "kalendzsin",
  "km": "kambodzsai",
  "km_KH": "kambodzsai (Kambodzsa)",
  "kmb": "kimbundu",
  "kn": "kannada",
  "kn_IN": "kannada (India)",
  "ko": "koreai",
  "ko_KP": "koreai (Észak-Korea)",
  "ko_KR": "koreai (Dél-Korea)",
  "koi": "komi-permják",
  "kok": "konkani",
  "kos": "kosrei",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karacsáj-balkár",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "karelai",
  "kro": "kru",
  "kru": "kuruh",
  "ks": "kásmíri",
  "ks_Arab": "kásmíri (Arab)",
  "ks_Arab_IN": "kásmíri (Arab, India)",
  "ks_IN": "kásmíri (India)",
  "ksb": "sambala",
  "ksf": "bafia",
  "ksh": "kölsch",
  "ku": "kurd",
  "kum": "kumük",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "korni",
  "kw_GB": "korni (Egyesült Királyság)",
  "ky": "kirgiz",
  "ky_Cyrl": "kirgiz (Cirill)",
  "ky_Cyrl_KG": "kirgiz (Cirill, Kirgizisztán)",
  "ky_KG": "kirgiz (Kirgizisztán)",
  "la": "latin",
  "lad": "ladino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxemburgi",
  "lb_LU": "luxemburgi (Luxemburg)",
  "lez": "lezg",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgi",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Kongó - Kinshasa)",
  "ln_CF": "lingala (Közép-afrikai Köztársaság)",
  "ln_CG": "lingala (Kongó - Brazzaville)",
  "lo": "laoszi",
  "lo_LA": "laoszi (Laosz)",
  "lol": "mongó",
  "lou": "louisianai kreol",
  "loz": "lozi",
  "lrc": "északi luri",
  "lt": "litván",
  "lt_LT": "litván (Litvánia)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Kongó - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushai",
  "luy": "lujia",
  "lv": "lett",
  "lv_LV": "lett (Lettország)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "madurai",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makaszar",
  "man": "mandingó",
  "map": "ausztronéz",
  "mas": "masai",
  "mde": "maba",
  "mdf": "moksán",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "mauritiusi kreol",
  "mg": "málgas",
  "mg_MG": "málgas (Madagaszkár)",
  "mga": "közép ír",
  "mgh": "makua-metó",
  "mgo": "meta’",
  "mh": "marshalli",
  "mi": "maori",
  "mic": "mikmak",
  "min": "minangkabau",
  "mis": "egyéb nyelvek",
  "mk": "macedón",
  "mk_MK": "macedón (Macedónia)",
  "mkh": "egyéb mon-khmer",
  "ml": "malajálam",
  "ml_IN": "malajálam (India)",
  "mn": "mongol",
  "mn_Cyrl": "mongol (Cirill)",
  "mn_Cyrl_MN": "mongol (Cirill, Mongólia)",
  "mn_MN": "mongol (Mongólia)",
  "mnc": "mandzsu",
  "mni": "manipuri",
  "mno": "manobó nyelvek",
  "mo": "moldvai",
  "moh": "mohawk",
  "mos": "moszi",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "Western Mari",
  "ms": "maláj",
  "ms_BN": "maláj (Brunei)",
  "ms_Latn": "maláj (Latin)",
  "ms_Latn_BN": "maláj (Latin, Brunei)",
  "ms_Latn_MY": "maláj (Latin, Malajzia)",
  "ms_Latn_SG": "maláj (Latin, Szingapúr)",
  "ms_MY": "maláj (Malajzia)",
  "ms_SG": "maláj (Szingapúr)",
  "mt": "máltai",
  "mt_MT": "máltai (Málta)",
  "mua": "mundang",
  "mul": "többszörös nyelvek",
  "mun": "munda nyelvek",
  "mus": "krík",
  "mwl": "mirandéz",
  "mwr": "marvari",
  "mwv": "Mentawai",
  "my": "burmai",
  "my_MM": "burmai (Mianmar (Burma))",
  "mye": "myene",
  "myn": "maja nyelvek",
  "myv": "erzjány",
  "mzn": "mázanderáni",
  "na": "naurui",
  "nah": "nahuati",
  "nai": "észak-amerikai indián nyelv",
  "nan": "min nan kínai",
  "nap": "nápolyi",
  "naq": "nama",
  "nb": "norvég bokmal",
  "nb_NO": "norvég bokmal (Norvégia)",
  "nb_SJ": "norvég bokmal (Spitzbergák és Jan Mayen-szigetek)",
  "nd": "északi ndebele",
  "nd_ZW": "északi ndebele (Zimbabwe)",
  "nds": "alsónémet",
  "nds_NL": "alsószász",
  "ne": "nepáli",
  "ne_IN": "nepáli (India)",
  "ne_NP": "nepáli (Nepál)",
  "new": "nevari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "niger-kordofan nyelv",
  "niu": "niui",
  "njo": "Ao Naga",
  "nl": "holland",
  "nl_AW": "holland (Aruba)",
  "nl_BE": "holland (Belgium)",
  "nl_BQ": "holland (Holland Karib-térség)",
  "nl_CW": "holland (Curaçao)",
  "nl_NL": "holland (Hollandia)",
  "nl_SR": "holland (Suriname)",
  "nl_SX": "holland (Sint Maarten)",
  "nmg": "ngumba",
  "nn": "norvég nynorsk",
  "nn_NO": "norvég nynorsk (Norvégia)",
  "nnh": "ngiemboon",
  "no": "norvég",
  "no_NO": "norvég (Norvégia)",
  "nog": "nogaj",
  "non": "óskandináv",
  "nov": "Novial",
  "nqo": "n’kó",
  "nr": "déli ndebele",
  "nso": "északi szotó",
  "nub": "núbiai nyelv",
  "nus": "nuer",
  "nv": "navahó",
  "nwc": "klasszikus newari",
  "ny": "nyanja",
  "nym": "nyamvézi",
  "nyn": "nyankole",
  "nyo": "nyoró",
  "nzi": "nzima",
  "oc": "okszitán",
  "oj": "ojibva",
  "om": "oromói",
  "om_ET": "oromói (Etiópia)",
  "om_KE": "oromói (Kenya)",
  "or": "orija",
  "or_IN": "orija (India)",
  "os": "oszét",
  "os_GE": "oszét (Grúzia)",
  "os_RU": "oszét (Oroszország)",
  "osa": "osage",
  "ota": "ottomán török",
  "oto": "otomi nyelv",
  "pa": "pandzsábi",
  "pa_Arab": "pandzsábi (Arab)",
  "pa_Arab_PK": "pandzsábi (Arab, Pakisztán)",
  "pa_Guru": "pandzsábi (Gurmuki)",
  "pa_Guru_IN": "pandzsábi (Gurmuki, India)",
  "pa_IN": "pandzsábi (India)",
  "pa_PK": "pandzsábi (Pakisztán)",
  "paa": "pápuai nyelv",
  "pag": "pangaszinan",
  "pal": "pahlavi",
  "pam": "pampangan",
  "pap": "papiamentó",
  "pau": "palaui",
  "pcd": "Picard",
  "pcm": "nigériai pidgin",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "óperzsa",
  "pfl": "Palatine German",
  "phi": "Fülöp-szigeteki nyelv",
  "phn": "főniciai",
  "pi": "pali",
  "pl": "lengyel",
  "pl_PL": "lengyel (Lengyelország)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "pohnpei",
  "pra": "prakrit nyelvek",
  "prg": "porosz",
  "pro": "óprovánszi",
  "ps": "pastu",
  "ps_AF": "pastu (Afganisztán)",
  "pt": "portugál",
  "pt_AO": "portugál (Angola)",
  "pt_BR": "portugál (Brazília)",
  "pt_CV": "portugál (Zöld-foki Köztársaság)",
  "pt_GW": "portugál (Guinea-Bissau)",
  "pt_MO": "portugál (Makaó SAR Kína)",
  "pt_MZ": "portugál (Mozambik)",
  "pt_PT": "portugál (Portugália)",
  "pt_ST": "portugál (Sao Tomé és Príncipe)",
  "pt_TL": "portugál (Kelet-Timor)",
  "qu": "kecsua",
  "qu_BO": "kecsua (Bolívia)",
  "qu_EC": "kecsua (Ecuador)",
  "qu_PE": "kecsua (Peru)",
  "quc": "kicse",
  "qug": "Chimborazo Highland Quichua",
  "raj": "radzsasztáni",
  "rap": "rapanui",
  "rar": "rarotongai",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "réto-román",
  "rm_CH": "réto-román (Svájc)",
  "rn": "kirundi",
  "rn_BI": "kirundi (Burundi)",
  "ro": "román",
  "ro_MD": "román (Moldova)",
  "ro_RO": "román (Románia)",
  "roa": "román nyelv",
  "rof": "rombo",
  "rom": "roma",
  "root": "ősi",
  "rtm": "Rotuman",
  "ru": "orosz",
  "ru_BY": "orosz (Fehéroroszország)",
  "ru_KG": "orosz (Kirgizisztán)",
  "ru_KZ": "orosz (Kazahsztán)",
  "ru_MD": "orosz (Moldova)",
  "ru_RU": "orosz (Oroszország)",
  "ru_UA": "orosz (Ukrajna)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromán",
  "rw": "kiruanda",
  "rw_RW": "kiruanda (Ruanda)",
  "rwk": "rwo",
  "sa": "szanszkrit",
  "sad": "szandave",
  "sah": "jakut",
  "sai": "dél-amerikai indián nyelv",
  "sal": "szelis nyelv",
  "sam": "szamaritánus arámi",
  "saq": "szamburu",
  "sas": "sasak",
  "sat": "szantáli",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "szangu",
  "sc": "szardíniai",
  "scn": "szicíliai",
  "sco": "skót",
  "sd": "szindhi",
  "sdc": "Sassarese Sardinian",
  "sdh": "dél-kurd",
  "se": "északi számi",
  "se_FI": "északi számi (Finnország)",
  "se_NO": "északi számi (Norvégia)",
  "se_SE": "északi számi (Svédország)",
  "see": "szeneka",
  "seh": "szena",
  "sei": "Seri",
  "sel": "szölkup",
  "sem": "egyéb szemita",
  "ses": "kojra-szenni",
  "sg": "szangó",
  "sg_CF": "szangó (Közép-afrikai Köztársaság)",
  "sga": "óír",
  "sgn": "jelnyelv",
  "sgs": "Samogitian",
  "sh": "szerbhorvát",
  "sh_BA": "szerbhorvát (Bosznia-Hercegovina)",
  "shi": "tachelhit",
  "shn": "san",
  "shu": "csádi arab",
  "si": "szingaléz",
  "si_LK": "szingaléz (Srí Lanka)",
  "sid": "szidamó",
  "sio": "sziú nyelvek",
  "sit": "sinotibeti nyelv",
  "sk": "szlovák",
  "sk_SK": "szlovák (Szlovákia)",
  "sl": "szlovén",
  "sl_SI": "szlovén (Szlovénia)",
  "sla": "szláv nyelv",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "szamoai",
  "sma": "déli számi",
  "smi": "lapp nyelv",
  "smj": "lule számi",
  "smn": "inar sami",
  "sms": "koltta lapp",
  "sn": "sona",
  "sn_ZW": "sona (Zimbabwe)",
  "snk": "szoninke",
  "so": "szomáliai",
  "so_DJ": "szomáliai (Dzsibuti)",
  "so_ET": "szomáliai (Etiópia)",
  "so_KE": "szomáliai (Kenya)",
  "so_SO": "szomáliai (Szomália)",
  "sog": "sogdien",
  "son": "szongai",
  "sq": "albán",
  "sq_AL": "albán (Albánia)",
  "sq_MK": "albán (Macedónia)",
  "sq_XK": "albán (Koszovó)",
  "sr": "szerb",
  "sr_BA": "szerb (Bosznia-Hercegovina)",
  "sr_Cyrl": "szerb (Cirill)",
  "sr_Cyrl_BA": "szerb (Cirill, Bosznia-Hercegovina)",
  "sr_Cyrl_ME": "szerb (Cirill, Montenegró)",
  "sr_Cyrl_RS": "szerb (Cirill, Szerbia)",
  "sr_Cyrl_XK": "szerb (Cirill, Koszovó)",
  "sr_Latn": "szerb (Latin)",
  "sr_Latn_BA": "szerb (Latin, Bosznia-Hercegovina)",
  "sr_Latn_ME": "szerb (Latin, Montenegró)",
  "sr_Latn_RS": "szerb (Latin, Szerbia)",
  "sr_Latn_XK": "szerb (Latin, Koszovó)",
  "sr_ME": "szerb (Montenegró)",
  "sr_RS": "szerb (Szerbia)",
  "sr_XK": "szerb (Koszovó)",
  "srn": "szranai tongó",
  "srr": "szerer",
  "ss": "sziszuati",
  "ssa": "nílusi-szaharai nyelv",
  "ssy": "szahó",
  "st": "szeszotó",
  "stq": "Saterland Frisian",
  "su": "szundanéz",
  "suk": "szukuma",
  "sus": "szuszu",
  "sux": "sumér",
  "sv": "svéd",
  "sv_AX": "svéd (Åland-szigetek)",
  "sv_FI": "svéd (Finnország)",
  "sv_SE": "svéd (Svédország)",
  "sw": "szuahéli",
  "sw_CD": "kongói szuahéli",
  "sw_KE": "szuahéli (Kenya)",
  "sw_TZ": "szuahéli (Tanzánia)",
  "sw_UG": "szuahéli (Uganda)",
  "swb": "comorei",
  "swc": "kongói szuahéli",
  "syc": "klasszikus szír",
  "syr": "szíriai",
  "szl": "Silesian",
  "ta": "tamil",
  "ta_IN": "tamil (India)",
  "ta_LK": "tamil (Srí Lanka)",
  "ta_MY": "tamil (Malajzia)",
  "ta_SG": "tamil (Szingapúr)",
  "tai": "thai nyelv",
  "tcy": "Tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "teszó",
  "ter": "terenó",
  "tet": "tetum",
  "tg": "tadzsik",
  "th": "thai",
  "th_TH": "thai (Thaiföld)",
  "ti": "tigrinja",
  "ti_ER": "tigrinja (Eritrea)",
  "ti_ET": "tigrinja (Etiópia)",
  "tig": "tigré",
  "tiv": "tiv",
  "tk": "türkmén",
  "tkl": "tokelaui",
  "tkr": "Tsakhur",
  "tl": "tagalog",
  "tl_PH": "tagalog (Fülöp-szigetek)",
  "tlh": "klingon",
  "tli": "tlingit",
  "tly": "Talysh",
  "tmh": "tamasek",
  "tn": "szecsuáni",
  "to": "tonga",
  "to_TO": "tonga (Tonga)",
  "tog": "nyasa tonga",
  "tpi": "tok pisin",
  "tr": "török",
  "tr_CY": "török (Ciprus)",
  "tr_TR": "török (Törökország)",
  "tru": "Turoyo",
  "trv": "tarokó",
  "ts": "conga",
  "tsd": "Tsakonian",
  "tsi": "csimsiáni",
  "tt": "tatár",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tup": "tupi nyelv",
  "tut": "altáji nyelv",
  "tvl": "tuvalu",
  "tw": "twi",
  "twq": "szavák",
  "ty": "tahiti",
  "tyv": "tuvai",
  "tzm": "közép-marokkói tamazigt",
  "udm": "udmurt",
  "ug": "ujgur",
  "ug_Arab": "ujgur (Arab)",
  "ug_Arab_CN": "ujgur (Arab, Kína)",
  "ug_CN": "ujgur (Kína)",
  "uga": "ugariti",
  "uk": "ukrán",
  "uk_UA": "ukrán (Ukrajna)",
  "umb": "umbundu",
  "und": "ismeretlen nyelv",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakisztán)",
  "uz": "üzbég",
  "uz_AF": "üzbég (Afganisztán)",
  "uz_Arab": "üzbég (Arab)",
  "uz_Arab_AF": "üzbég (Arab, Afganisztán)",
  "uz_Cyrl": "üzbég (Cirill)",
  "uz_Cyrl_UZ": "üzbég (Cirill, Üzbegisztán)",
  "uz_Latn": "üzbég (Latin)",
  "uz_Latn_UZ": "üzbég (Latin, Üzbegisztán)",
  "uz_UZ": "üzbég (Üzbegisztán)",
  "vai": "vai",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnami",
  "vi_VN": "vietnami (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapük",
  "vot": "votják",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "vallon",
  "wae": "walser",
  "wak": "vakas nyelv",
  "wal": "valamo",
  "war": "varaó",
  "was": "vasó",
  "wbp": "Warlpiri",
  "wen": "szorb nyelvek",
  "wo": "volof",
  "wuu": "wu kínai",
  "xal": "kalmük",
  "xh": "hosza",
  "xmf": "Mingrelian",
  "xog": "szoga",
  "yao": "jaó",
  "yap": "japi",
  "yav": "jangben",
  "ybb": "jemba",
  "yi": "jiddis",
  "yo": "joruba",
  "yo_BJ": "joruba (Benin)",
  "yo_NG": "joruba (Nigéria)",
  "ypk": "jupik nyelv",
  "yrl": "Nheengatu",
  "yue": "kantoni",
  "za": "zsuang",
  "zap": "zapoték",
  "zbl": "Bliss jelképrendszer",
  "zea": "Zeelandic",
  "zen": "zenaga",
  "zgh": "marokkói tamazight",
  "zh": "kínai",
  "zh_CN": "kínai (Kína)",
  "zh_HK": "kínai (Hongkong SAR Kína)",
  "zh_Hans": "kínai (egyszerűsített)",
  "zh_Hans_CN": "kínai (Egyszerűsített, Kína)",
  "zh_Hans_HK": "kínai (Egyszerűsített, Hongkong SAR Kína)",
  "zh_Hans_MO": "kínai (Egyszerűsített, Makaó SAR Kína)",
  "zh_Hans_SG": "kínai (Egyszerűsített, Szingapúr)",
  "zh_Hant": "kínai (hagyományos)",
  "zh_Hant_HK": "kínai (Hagyományos, Hongkong SAR Kína)",
  "zh_Hant_MO": "kínai (Hagyományos, Makaó SAR Kína)",
  "zh_Hant_TW": "kínai (Hagyományos, Tajvan)",
  "zh_MO": "kínai (Makaó SAR Kína)",
  "zh_SG": "kínai (Szingapúr)",
  "zh_TW": "kínai (Tajvan)",
  "znd": "zande",
  "zu": "zulu",
  "zu_ZA": "zulu (Dél-afrikai Köztársaság)",
  "zun": "zuni",
  "zxx": "nincs nyelvészeti tartalom",
  "zza": "zaza"
};
