const names = {
  "001": "swět",
  "002": "Afrika",
  "003": "Pódpołnocna Amerika",
  "005": "Pódpołdnjowa Amerika",
  "009": "Oceaniska",
  "011": "Pódwjacorna Afrika",
  "013": "Srjejźna Amerika",
  "014": "pódzajtšna Afrika",
  "015": "pódpołnocna Afrika",
  "017": "srjejźna Afrika",
  "018": "pódpołdnjowa Afrika",
  "019": "Amerika",
  "021": "pódpołnocny ameriski kontinent",
  "029": "Karibiska",
  "030": "pódzajtšna Azija",
  "034": "pódpołdnjowa Azija",
  "035": "krotkozajtšna Azija",
  "039": "pódpołdnjowa Europa",
  "053": "Awstralazija",
  "054": "Melaneziska",
  "057": "Mikroneziska (kupowy region)",
  "061": "Polyneziska",
  "142": "Azija",
  "143": "centralna Azija",
  "145": "pódwjacorna Azija",
  "150": "Europa",
  "151": "pódzajtšna Europa",
  "154": "pódpołnocna Europa",
  "155": "pódwjacorna Europa",
  "419": "Łatyńska Amerika",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Zjadnośone arabiske emiraty",
  "AF": "Afghanistan",
  "AG": "Antigua a Barbuda",
  "AI": "Anguilla",
  "AL": "Albańska",
  "AM": "Armeńska",
  "AO": "Angola",
  "AQ": "Antarktis",
  "AR": "Argentinska",
  "AS": "Ameriska Samoa",
  "AT": "Awstriska",
  "AU": "Awstralska",
  "AW": "Aruba",
  "AX": "Åland",
  "AZ": "Azerbajdžan",
  "Arab": "arabski",
  "Armn": "armeński",
  "BA": "Bosniska a Hercegowina",
  "BB": "Barbados",
  "BD": "Bangladeš",
  "BE": "Belgiska",
  "BF": "Burkina Faso",
  "BG": "Bulgarska",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "St. Barthélemy",
  "BM": "Bermudy",
  "BN": "Brunei",
  "BO": "Boliwiska",
  "BQ": "Karibiska Nižozemska",
  "BR": "Brazilska",
  "BS": "Bahamy",
  "BT": "Bhutan",
  "BV": "Bouvetowa kupa",
  "BW": "Botswana",
  "BY": "Běłoruska",
  "BZ": "Belize",
  "Beng": "bengalski",
  "Bopo": "bopomofo",
  "Brai": "braillowe pismo",
  "CA": "Kanada",
  "CC": "Kokosowe kupy",
  "CD": "Kongo-Kinshasa",
  "CF": "Centralnoafriska republika",
  "CG": "Kongo-Brazzaville",
  "CH": "Šwicarska",
  "CI": "Côte d’Ivoire",
  "CK": "Cookowe kupy",
  "CL": "Chilska",
  "CM": "Kamerun",
  "CN": "China",
  "CO": "Kolumbiska",
  "CP": "Clippertonowa kupa",
  "CR": "Kosta Rika",
  "CU": "Kuba",
  "CV": "Kap Verde",
  "CW": "Curaçao",
  "CX": "Gódowne kupy",
  "CY": "Cypriska",
  "CZ": "Česka republika",
  "Cyrl": "kyriliski",
  "DE": "Nimska",
  "DG": "Diego Garcia",
  "DJ": "Džibuti",
  "DK": "Dańska",
  "DM": "Dominika",
  "DO": "Dominikańska republika",
  "DZ": "Algeriska",
  "Deva": "devanagari",
  "EA": "Ceuta a Melilla",
  "EC": "Ekwador",
  "EE": "Estniska",
  "EG": "Egyptojska",
  "EH": "Pódwjacorna Sahara",
  "ER": "Eritreja",
  "ES": "Špańska",
  "ET": "Etiopiska",
  "EU": "Europska unija",
  "Ethi": "etiopiski",
  "FI": "Finska",
  "FJ": "Fidži",
  "FK": "Falklandske kupy",
  "FM": "Mikroneziska",
  "FO": "Färöje",
  "FR": "Francojska",
  "GA": "Gabun",
  "GB": "Zjadnośone kralejstwo",
  "GD": "Grenada",
  "GE": "Georgiska",
  "GF": "Francojska Guyana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grönlandska",
  "GM": "Gambija",
  "GN": "Gineja",
  "GP": "Guadeloupe",
  "GQ": "Ekwatorialna Gineja",
  "GR": "Grichiska",
  "GS": "Pódpołdnjowa Georgiska a Pódpołdnjowe Sandwichowe kupy",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Gineja-Bissau",
  "GY": "Guyana",
  "Geor": "georgiski",
  "Grek": "grichiski",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "Wósebna zastojnstwowa cona Hongkong",
  "HM": "Heardowa kupa a McDonaldowe kupy",
  "HN": "Honduras",
  "HR": "Chorwatska",
  "HT": "Haiti",
  "HU": "Hungorska",
  "Hang": "hangul",
  "Hani": "han",
  "Hans": "zjadnorjone",
  "Hant": "tradionalne",
  "Hebr": "hebrejski",
  "Hira": "hiragana",
  "IC": "Kanariske kupy",
  "ID": "Indoneziska",
  "IE": "Irska",
  "IL": "Israel",
  "IM": "Man",
  "IN": "Indiska",
  "IO": "Britiski indiskooceaniski teritorium",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Islandska",
  "IT": "Italska",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Jordaniska",
  "JP": "Japańska",
  "Jpan": "japański",
  "KE": "Kenia",
  "KG": "Kirgizistan",
  "KH": "Kambodža",
  "KI": "Kiribati",
  "KM": "Komory",
  "KN": "St. Kitts a Nevis",
  "KP": "Pódpołnocna Koreja",
  "KR": "Pódpołdnjowa Koreja",
  "KW": "Kuwait",
  "KY": "Kajmaniske kupy",
  "KZ": "Kazachstan",
  "Kana": "katakana",
  "Khmr": "khmer",
  "Knda": "kannada",
  "Kore": "korejski",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberija",
  "LS": "Lesotho",
  "LT": "Litawska",
  "LU": "Luxemburgska",
  "LV": "Letiska",
  "LY": "Libyska",
  "Laoo": "laoski",
  "Latn": "łatyński",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldawska",
  "ME": "Carna Góra",
  "MF": "St. Martin",
  "MG": "Madagaskar",
  "MH": "Marshallowe kupy",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolska",
  "MO": "Wósebna zastojnstwowa cona Macao",
  "MP": "Pódpołnocne Mariany",
  "MQ": "Martinique",
  "MR": "Mawretańska",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Malediwy",
  "MW": "Malawi",
  "MX": "Mexiko",
  "MY": "Malajzija",
  "MZ": "Mosambik",
  "Mlym": "malayalamski",
  "Mong": "mongolski",
  "Mymr": "burmaski",
  "NA": "Namibija",
  "NC": "Nowa Kaledoniska",
  "NE": "Niger",
  "NF": "Norfolkowa kupa",
  "NG": "Nigerija",
  "NI": "Nikaragua",
  "NL": "Nižozemska",
  "NO": "Norwegska",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nowoseelandska",
  "OM": "Oman",
  "Orya": "oriya",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Francojska Polyneziska",
  "PG": "Papua-Neuguinea",
  "PH": "Filipiny",
  "PK": "Pakistan",
  "PL": "Pólska",
  "PM": "St. Pierre a Miquelon",
  "PN": "Pitcairnowe kupy",
  "PR": "Puerto Rico",
  "PS": "Palestinski awtonomny teritorium",
  "PT": "Portugalska",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Katar",
  "QO": "wenkowna Oceaniska",
  "RE": "Réunion",
  "RO": "Rumuńska",
  "RS": "Serbiska",
  "RU": "Ruska",
  "RW": "Ruanda",
  "SA": "Saudi-Arabiska",
  "SB": "Salomony",
  "SC": "Seychelle",
  "SD": "Sudan",
  "SE": "Šwedska",
  "SG": "Singapur",
  "SH": "St. Helena",
  "SI": "Słowjeńska",
  "SJ": "Svalbard a Jan Mayen",
  "SK": "Słowakska",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalija",
  "SR": "Surinamska",
  "SS": "Pódpołdnjowy Sudan",
  "ST": "São Tomé a Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syriska",
  "SZ": "Swasiska",
  "Sinh": "singhaleski",
  "TA": "Tristan da Cunha",
  "TC": "Turks a Caicos kupy",
  "TD": "Čad",
  "TF": "Francojski pódpołdnjowy a antarktiski teritorium",
  "TG": "Togo",
  "TH": "Thailandska",
  "TJ": "Tadźikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmeniska",
  "TN": "Tuneziska",
  "TO": "Tonga",
  "TR": "Turkojska",
  "TT": "Trinidad a Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansanija",
  "Taml": "tamilski",
  "Telu": "telugu",
  "Thaa": "thaana",
  "Thai": "thaiski",
  "Tibt": "tibetski",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "Ameriska Oceaniska",
  "US": "Zjadnośone staty Ameriki",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatikańske město",
  "VC": "St. Vincent a Grenadiny",
  "VE": "Venezuela",
  "VG": "Britiske kněžniske kupy",
  "VI": "Ameriske kněžniske kupy",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis a Futuna",
  "WS": "Samoa",
  "XK": "Kosowo",
  "YE": "Jemen",
  "YT": "Mayotte",
  "ZA": "Pódpołdnjowa Afrika (Republika)",
  "ZM": "Sambija",
  "ZW": "Simbabwe",
  "ZZ": "njeznaty region",
  "Zsym": "symbole",
  "Zxxx": "bźez pisma",
  "Zyyy": "powšykne",
  "Zzzz": "njeznate pismo",
  "aa": "afaršćina",
  "ab": "abchazšćina",
  "af": "afrikans",
  "agq": "aghem",
  "ak": "akanšćina",
  "am": "amharšćina",
  "an": "aragonšćina",
  "ang": "anglosaksojšćina",
  "ar": "arabšćina",
  "ar_001": "moderna wusokoarabšćina",
  "arn": "arawkašćina",
  "as": "asamšćina",
  "asa": "pare",
  "ast": "asturšćina",
  "av": "awaršćina",
  "ay": "aymaršćina",
  "az": "azerbajdžanšćina",
  "ba": "baškiršćina",
  "be": "běłorušćina",
  "bem": "bemba",
  "bez": "bena",
  "bg": "bulgaršćina",
  "bi": "bislamšćina",
  "bm": "bambara",
  "bn": "bengalšćina",
  "bo": "tibetšćina",
  "br": "bretonšćina",
  "brx": "bodo",
  "bs": "bosnišćina",
  "bug": "bugišćina",
  "ca": "katanlanšćina",
  "cgg": "chiga",
  "ch": "čamoršćina",
  "cho": "choctawšćina",
  "chr": "cherokee",
  "ckb": "sorani",
  "co": "korsišćina",
  "cr": "kri",
  "cs": "češćina",
  "cy": "walizišćina",
  "da": "danšćina",
  "dav": "taita",
  "de": "nimšćina",
  "de_AT": "awstriska nimšćina",
  "de_CH": "šwicarska wusokonimšćina",
  "dje": "zarma",
  "dsb": "dolnoserbšćina",
  "dua": "duala",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dz": "dzongkha",
  "ebu": "embu",
  "ee": "ewe",
  "el": "grichišćina",
  "en": "engelšćina",
  "en_AU": "awstralska engelšćina",
  "en_CA": "kanadiska engelšćina",
  "en_GB": "britiska engelšćina",
  "en_US": "ameriska engelšćina",
  "eo": "esperanto",
  "es": "špańšćina",
  "es_419": "łatyńskoamerikańska špańšćina",
  "es_ES": "europejska špańšćina",
  "es_MX": "mexikańska špańšćina",
  "et": "estišćina",
  "eu": "baskišćina",
  "fa": "persišćina",
  "fi": "finšćina",
  "fil": "filipinšćina",
  "fj": "fidžišćina",
  "fo": "ferejšćina",
  "fr": "francojšćina",
  "fr_CA": "kanadiska francojšćina",
  "fr_CH": "šwicarska francojšćina",
  "fy": "frizišćina",
  "ga": "iršćina",
  "gag": "gagauzšćina",
  "gd": "šotišćina",
  "gl": "galicišćina",
  "gn": "guarani",
  "got": "gotišćina",
  "gsw": "šwicarska nimšćina",
  "gu": "gudžaratšćina",
  "guz": "gusii",
  "gv": "manšćina",
  "ha": "hausa",
  "haw": "hawaiišćina",
  "he": "hebrejšćina",
  "hi": "hindišćina",
  "hr": "chorwatšćina",
  "hsb": "górnoserbšćina",
  "ht": "haitišćina",
  "hu": "hungoršćina",
  "hy": "armeńšćina",
  "ia": "interlingua",
  "id": "indonešćina",
  "ig": "igbo",
  "ii": "sichuan yi",
  "ik": "inupiak",
  "io": "ido",
  "is": "islandšćina",
  "it": "italšćina",
  "iu": "inuitšćina",
  "ja": "japańšćina",
  "jgo": "ngomba",
  "jmc": "machame",
  "jv": "javašćina",
  "ka": "georgišćina",
  "kab": "kabylšćina",
  "kam": "kamba",
  "kde": "makonde",
  "kea": "kapverdšćina",
  "khq": "koyra chiini",
  "ki": "kikuyu",
  "kk": "kazachšćina",
  "kl": "grönlandšćina",
  "kln": "kalenjin",
  "km": "kambodžanšćina",
  "kn": "kannadšćina",
  "ko": "korejańšćina",
  "koi": "komi-permyak",
  "kok": "konkani",
  "kri": "krio",
  "ks": "kašmiršćina",
  "ksb": "šambala",
  "ksf": "bafia",
  "ku": "kurdišćina",
  "kw": "kornišćina",
  "ky": "kirgišćina",
  "la": "łatyńšćina",
  "lag": "langi",
  "lb": "luxemburgšćina",
  "lg": "gandšćina",
  "li": "limburšćina",
  "lkt": "lakotšćina",
  "ln": "lingala",
  "lo": "laošćina",
  "lt": "litawšćina",
  "lu": "luba-katanga",
  "luo": "luo",
  "luy": "luhya",
  "lv": "letišćina",
  "mas": "masaišćina",
  "mer": "meru",
  "mfe": "mauriciska kreolšćina",
  "mg": "malgašćina",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mi": "maorišćina",
  "mk": "makedońšćina",
  "ml": "malajamšćina",
  "mn": "mongolšćina",
  "moh": "mohawkšćina",
  "mr": "maratišćina",
  "ms": "malajšćina",
  "mt": "maltašćina",
  "mua": "mundang",
  "mus": "krik",
  "my": "burmašćina",
  "na": "naurušćina",
  "naq": "nama",
  "nb": "norwegske bokmål",
  "nd": "pódpołnocne ndebele",
  "nds": "dolnonimšćina",
  "ne": "nepalšćina",
  "nl": "nižozemšćina",
  "nl_BE": "flamšćina",
  "nmg": "kwasio",
  "nn": "norwegske nynorsk",
  "no": "norwegšćina",
  "nqo": "n’ko",
  "nus": "nuer",
  "nv": "navaho",
  "nyn": "nyankole",
  "oc": "okcitanšćina",
  "om": "oromo",
  "or": "orojišćina",
  "pa": "pandžabšćina",
  "pl": "pólšćina",
  "prg": "prusčina",
  "ps": "paštunšćina",
  "pt": "portugalšćina",
  "pt_BR": "brazilska portugalšćina",
  "pt_PT": "europejska portugalšćina",
  "qu": "kečua",
  "quc": "kʼicheʼ",
  "rm": "retoromańšćina",
  "rn": "kirundišćina",
  "ro": "rumunšćina",
  "ro_MD": "moldawišćina",
  "rof": "rombo",
  "ru": "rušćina",
  "rw": "kinjarwanda",
  "rwk": "rwa",
  "sa": "sanskrit",
  "saq": "samburu",
  "sbp": "sangu",
  "sc": "sardinšćina",
  "scn": "sicilianišćina",
  "sd": "sindšćina",
  "se": "lapšćina",
  "seh": "sena",
  "ses": "koyra senni",
  "sg": "sango",
  "sh": "serbochorwatšćina",
  "shi": "tašelhit",
  "si": "singalšćina",
  "sk": "słowakšćina",
  "sl": "słowjeńšćina",
  "sm": "samošćina",
  "sma": "pódpołdnjowa samišćina",
  "smj": "lule-samišćina",
  "smn": "inari-samišćina",
  "sms": "skolt-samišćina",
  "sn": "šonšćina",
  "so": "somališćina",
  "sq": "albanšćina",
  "sr": "serbišćina",
  "ss": "siswati",
  "st": "pódpołdnjowa sotšćina (Sesotho)",
  "stq": "saterfrizišćina",
  "su": "sundanšćina",
  "sv": "šwedšćina",
  "sw": "swahilišćina",
  "sw_CD": "kongojska swahilišćina",
  "ta": "tamilšćina",
  "te": "telugšćina",
  "teo": "teso",
  "tg": "tadžikišćina",
  "th": "thailandšćina",
  "ti": "tigrinja",
  "tk": "turkmeńšćina",
  "tl": "tagalog",
  "tn": "tswana",
  "to": "tonganšćina",
  "tr": "turkojšćina",
  "ts": "tsonga",
  "tt": "tataršćina",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitišćina",
  "tzm": "centralnoatlaski tamazight",
  "ug": "ujguršćina",
  "uk": "ukrainšćina",
  "und": "njeznata rěc",
  "ur": "urdušćina",
  "uz": "usbekšćina",
  "vai": "vai",
  "vi": "vietnamšćina",
  "vo": "volapük",
  "vun": "vunjo",
  "wa": "walonšćina",
  "wo": "wolof",
  "xh": "xhosa",
  "xog": "soga",
  "yi": "jidišćina",
  "yo": "jorubšćina",
  "za": "zhuang",
  "zgh": "standardny marokkański tamazight",
  "zh": "chinšćina",
  "zh_Hans": "chinšćina (zjadnorjona)",
  "zh_Hant": "chinšćina (tradicionalna)",
  "zu": "zulu",
  "zxx": "žedno rěcne wopśimjeśe"
};
