const names = {
  "001": "Món",
  "002": "Àfrica",
  "003": "Amèrica del Nord",
  "005": "Amèrica del Sud",
  "009": "Oceania",
  "011": "Àfrica occidental",
  "013": "Amèrica Central",
  "014": "Àfrica oriental",
  "015": "Àfrica septentrional",
  "017": "Àfrica central",
  "018": "Àfrica meridional",
  "019": "Amèrica",
  "021": "Amèrica septentrional",
  "029": "Carib",
  "030": "Àsia oriental",
  "034": "Àsia meridional",
  "035": "Àsia sud-oriental",
  "039": "Europa meridional",
  "053": "Australàsia",
  "054": "Melanèsia",
  "057": "Regió de la Micronèsia",
  "061": "Polinèsia",
  "062": "Sud-Àsia Central",
  "142": "Àsia",
  "143": "Àsia central",
  "145": "Àsia occidental",
  "150": "Europa",
  "151": "Europa oriental",
  "154": "Europa septentrional",
  "155": "Europa occidental",
  "172": "Comunitat d’Estats Independents",
  "200": "Txecoslovàquia",
  "202": "Àfrica subsahariana",
  "419": "Amèrica Llatina",
  "830": "Illes del Canal",
  "AC": "Illa de l’Ascensió",
  "AD": "Andorra",
  "AE": "Emirats Àrabs Units",
  "AF": "Afganistan",
  "AG": "Antigua i Barbuda",
  "AI": "Anguilla",
  "AL": "Albània",
  "AM": "Armènia",
  "AN": "Antilles Neerlandeses",
  "AO": "Angola",
  "AQ": "Antàrtida",
  "AR": "Argentina",
  "AS": "Samoa Nord-americana",
  "AT": "Àustria",
  "AU": "Austràlia",
  "AW": "Aruba",
  "AX": "Illes Åland",
  "AZ": "Azerbaidjan",
  "Adlm": "adlam",
  "Afak": "afaka",
  "Aghb": "albanès caucàsic",
  "Ahom": "ahom",
  "Arab": "àrab",
  "Aran": "nastaliq",
  "Armi": "arameu imperial",
  "Armn": "armeni",
  "Avst": "avèstic",
  "BA": "Bòsnia i Hercegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Bèlgica",
  "BF": "Burkina Faso",
  "BG": "Bulgària",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benín",
  "BL": "Saint Barthélemy",
  "BM": "Bermudes",
  "BN": "Brunei",
  "BO": "Bolívia",
  "BQ": "Carib Neerlandès",
  "BR": "Brasil",
  "BS": "Bahames",
  "BT": "Bhutan",
  "BV": "Bouvet",
  "BW": "Botswana",
  "BY": "Belarús",
  "BZ": "Belize",
  "Bali": "balinès",
  "Bamu": "bamum",
  "Bass": "bassa vah",
  "Batk": "batak",
  "Beng": "bengalí",
  "Bhks": "bhaiksuki",
  "Blis": "símbols Bliss",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "braille",
  "Bugi": "buginès",
  "Buhd": "buhid",
  "CA": "Canadà",
  "CC": "Illes Cocos",
  "CD": "Congo - Kinshasa",
  "CF": "República Centreafricana",
  "CG": "Congo - Brazzaville",
  "CH": "Suïssa",
  "CI": "Côte d’Ivoire",
  "CK": "Illes Cook",
  "CL": "Xile",
  "CM": "Camerun",
  "CN": "Xina",
  "CO": "Colòmbia",
  "CP": "Illa Clipperton",
  "CR": "Costa Rica",
  "CS": "Sèrbia i Montenegro",
  "CU": "Cuba",
  "CV": "Cap Verd",
  "CW": "Curaçao",
  "CX": "Illa Christmas",
  "CY": "Xipre",
  "CZ": "Txèquia",
  "Cakm": "chakma",
  "Cans": "síl·labes dels aborígens canadencs unificats",
  "Cari": "carià",
  "Cham": "cham",
  "Cher": "cherokee",
  "Chrs": "Corasmian",
  "Cirt": "cirth",
  "Copt": "copte",
  "Cprt": "xipriota",
  "Cyrl": "ciríl·lic",
  "Cyrs": "ciríl·lic de l’antic eslau eclesiàstic",
  "DD": "Alemanya Oriental",
  "DE": "Alemanya",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Algèria",
  "Deva": "devanagari",
  "Diak": "Immersions Akuru",
  "Dogr": "Dogra",
  "Dsrt": "deseret",
  "Dupl": "taquigrafia Duployé",
  "EA": "Ceuta i Melilla",
  "EC": "Equador",
  "EE": "Estònia",
  "EG": "Egipte",
  "EH": "Sàhara Occidental",
  "ER": "Eritrea",
  "ES": "Espanya",
  "ET": "Etiòpia",
  "EU": "Unió Europea",
  "EZ": "zona euro",
  "Egyd": "demòtic egipci",
  "Egyh": "hieràtic egipci",
  "Egyp": "jeroglífic egipci",
  "Elba": "elbasan",
  "Elym": "Elimàtic",
  "Ethi": "etiòpic",
  "FI": "Finlàndia",
  "FJ": "Fiji",
  "FK": "Illes Malvines",
  "FM": "Micronèsia",
  "FO": "Illes Fèroe",
  "FR": "França",
  "FX": "França metropolitana",
  "GA": "Gabon",
  "GB": "Regne Unit",
  "GD": "Grenada",
  "GE": "Geòrgia",
  "GF": "Guaiana Francesa",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenlàndia",
  "GM": "Gàmbia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Guinea Equatorial",
  "GR": "Grècia",
  "GS": "Illes Geòrgia del Sud i Sandwich del Sud",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea Bissau",
  "GY": "Guyana",
  "Geok": "georgià hucuri",
  "Geor": "georgià",
  "Glag": "glagolític",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "gòtic",
  "Gran": "grantha",
  "Grek": "grec",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "Hong Kong (RAE Xina)",
  "HM": "Illa Heard i Illes McDonald",
  "HN": "Hondures",
  "HR": "Croàcia",
  "HT": "Haití",
  "HU": "Hongria",
  "Hanb": "han amb bopomofo",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanunoo",
  "Hans": "simplificat",
  "Hant": "tradicional",
  "Hatr": "Hatran",
  "Hebr": "hebreu",
  "Hira": "hiragana",
  "Hluw": "jeroglífic anatoli",
  "Hmng": "pahawh hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "katakana o hiragana",
  "Hung": "hongarès antic",
  "IC": "Illes Canàries",
  "ID": "Indonèsia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Illa de Man",
  "IN": "Índia",
  "IO": "Territori Britànic de l’Oceà Índic",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Islàndia",
  "IT": "Itàlia",
  "Inds": "escriptura de la vall de l’Indus",
  "Ital": "cursiva antiga",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordània",
  "JP": "Japó",
  "Jamo": "jamo",
  "Java": "javanès",
  "Jpan": "japonès",
  "Jurc": "jürchen",
  "KE": "Kenya",
  "KG": "Kirguizistan",
  "KH": "Cambodja",
  "KI": "Kiribati",
  "KM": "Comores",
  "KN": "Saint Christopher i Nevis",
  "KP": "Corea del Nord",
  "KR": "Corea del Sud",
  "KW": "Kuwait",
  "KY": "Illes Caiman",
  "KZ": "Kazakhstan",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharosthi",
  "Khmr": "khmer",
  "Khoj": "khoja",
  "Kits": "Petit guió Khitan",
  "Knda": "kannada",
  "Kore": "coreà",
  "Kpel": "kpelle",
  "Kthi": "kaithi",
  "LA": "Laos",
  "LB": "Líban",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Libèria",
  "LS": "Lesotho",
  "LT": "Lituània",
  "LU": "Luxemburg",
  "LV": "Letònia",
  "LY": "Líbia",
  "Lana": "lanna",
  "Laoo": "lao",
  "Latf": "llatí fraktur",
  "Latg": "llatí gaèlic",
  "Latn": "llatí",
  "Lepc": "lepcha",
  "Limb": "limbu",
  "Lina": "lineal A",
  "Linb": "lineal B",
  "Lisu": "lisu",
  "Loma": "loma",
  "Lyci": "lici",
  "Lydi": "lidi",
  "MA": "Marroc",
  "MC": "Mònaco",
  "MD": "Moldàvia",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Illes Marshall",
  "MI": "Illes Midway",
  "MK": "Macedònia del Nord",
  "ML": "Mali",
  "MM": "Myanmar (Birmània)",
  "MN": "Mongòlia",
  "MO": "Macau (RAE Xina)",
  "MP": "Illes Mariannes del Nord",
  "MQ": "Martinica",
  "MR": "Mauritània",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Maurici",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mèxic",
  "MY": "Malàisia",
  "MZ": "Moçambic",
  "Mahj": "mahajani",
  "Maka": "Makasar",
  "Mand": "mandaic",
  "Mani": "maniqueu",
  "Marc": "Marchen",
  "Maya": "jeroglífics maies",
  "Medf": "Medefaidrin",
  "Mend": "mende",
  "Merc": "cursiva meroítica",
  "Mero": "meroític",
  "Mlym": "malaiàlam",
  "Modi": "modi",
  "Mong": "mongol",
  "Moon": "moon",
  "Mroo": "mro",
  "Mtei": "manipurí",
  "Mult": "multani",
  "Mymr": "birmà",
  "NA": "Namíbia",
  "NC": "Nova Caledònia",
  "NE": "Níger",
  "NF": "Norfolk",
  "NG": "Nigèria",
  "NI": "Nicaragua",
  "NL": "Països Baixos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Zona neutral",
  "NU": "Niue",
  "NZ": "Nova Zelanda",
  "Nand": "Nandinagari",
  "Narb": "antic nord-aràbic",
  "Nbat": "nabateu",
  "Newa": "newar",
  "Nkgb": "geba",
  "Nkoo": "n’Ko",
  "Nshu": "nü shu",
  "OM": "Oman",
  "Ogam": "ogham",
  "Olck": "santali",
  "Orkh": "orkhon",
  "Orya": "oriya",
  "Osge": "osage",
  "Osma": "osmanya",
  "PA": "Panamà",
  "PC": "Territori de confiança de les Illes del Pacífic",
  "PE": "Perú",
  "PF": "Polinèsia Francesa",
  "PG": "Papua Nova Guinea",
  "PH": "Filipines",
  "PK": "Pakistan",
  "PL": "Polònia",
  "PM": "Saint-Pierre-et-Miquelon",
  "PN": "Illes Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Territoris palestins",
  "PT": "Portugal",
  "PU": "Miscel·lània Illes del Pacífic dels EUA",
  "PW": "Palau",
  "PY": "Paraguai",
  "PZ": "Zona del Canal de Panamà",
  "Palm": "palmirè",
  "Pauc": "Pau Cin Hau",
  "Perm": "antic pèrmic",
  "Phag": "phagspa",
  "Phli": "pahlavi inscripcional",
  "Phlp": "psalter pahlavi",
  "Phlv": "pahlavi",
  "Phnx": "fenici",
  "Plrd": "pollard miao",
  "Prti": "parthià inscripcional",
  "QA": "Qatar",
  "QO": "Territoris allunyats d’Oceania",
  "Qaag": "zawgyi",
  "RE": "Illa de la Reunió",
  "RO": "Romania",
  "RS": "Sèrbia",
  "RU": "Rússia",
  "RW": "Ruanda",
  "Rjng": "rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "rongo-rongo",
  "Runr": "rúnic",
  "SA": "Aràbia Saudita",
  "SB": "Illes Salomó",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Suècia",
  "SG": "Singapur",
  "SH": "Saint Helena",
  "SI": "Eslovènia",
  "SJ": "Svalbard i Jan Mayen",
  "SK": "Eslovàquia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somàlia",
  "SR": "Surinam",
  "SS": "Sudan del Sud",
  "ST": "São Tomé i Príncipe",
  "SU": "Unió de Repúbliques Socialistes Soviètiques",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Síria",
  "SZ": "eSwatini",
  "Samr": "samarità",
  "Sara": "sarati",
  "Sarb": "sud-aràbic antic",
  "Saur": "saurashtra",
  "Sgnw": "escriptura de signes",
  "Shaw": "shavià",
  "Shrd": "shrada",
  "Sidd": "siddham",
  "Sind": "devangari",
  "Sinh": "singalès",
  "Sogd": "Sogdian",
  "Sogo": "Vell Sogdian",
  "Sora": "sora sompeng",
  "Soyo": "Soyombo",
  "Sund": "sundanès",
  "Sylo": "syloti nagri",
  "Syrc": "siríac",
  "Syre": "siríac estrangelo",
  "Syrj": "siríac occidental",
  "Syrn": "siríac oriental",
  "TA": "Tristan da Cunha",
  "TC": "Illes Turks i Caicos",
  "TD": "Txad",
  "TF": "Territoris Australs Francesos",
  "TG": "Togo",
  "TH": "Tailàndia",
  "TJ": "Tadjikistan",
  "TK": "Tokelau",
  "TL": "Timor Oriental",
  "TM": "Turkmenistan",
  "TN": "Tunísia",
  "TO": "Tonga",
  "TR": "Turquia",
  "TT": "Trinitat i Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzània",
  "Tagb": "tagbanwa",
  "Takr": "takri",
  "Tale": "tai le",
  "Talu": "nou tai lue",
  "Taml": "tàmil",
  "Tang": "tangut",
  "Tavt": "tai viet",
  "Telu": "telugu",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagàlog",
  "Thaa": "thaana",
  "Thai": "tailandès",
  "Tibt": "tibetà",
  "Tirh": "tirhut",
  "UA": "Ucraïna",
  "UG": "Uganda",
  "UM": "Illes Perifèriques Menors dels EUA",
  "UN": "Nacions Unides",
  "US": "Estats Units",
  "UY": "Uruguai",
  "UZ": "Uzbekistan",
  "Ugar": "ugarític",
  "VA": "Ciutat del Vaticà",
  "VC": "Saint Vincent i les Grenadines",
  "VD": "Vietnam del Nord",
  "VE": "Veneçuela",
  "VG": "Illes Verges Britàniques",
  "VI": "Illes Verges Nord-americanes",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "Visp": "llenguatge visible",
  "WF": "Wallis i Futuna",
  "WK": "Illa Wake",
  "WS": "Samoa",
  "Wara": "varang kshiti",
  "Wcho": "Wancho",
  "Wole": "woleai",
  "XA": "pseudoaccents",
  "XB": "pseudobidi",
  "XK": "Kosovo",
  "Xpeo": "persa antic",
  "Xsux": "cuneïforme sumeri-accadi",
  "YD": "República Democràtica Popular del Iemen",
  "YE": "Iemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "yi",
  "ZA": "República de Sud-àfrica",
  "ZM": "Zàmbia",
  "ZW": "Zimbàbue",
  "ZZ": "regió desconeguda",
  "Zanb": "Plaça Zanabazar",
  "Zinh": "heretat",
  "Zmth": "notació matemàtica",
  "Zsye": "emoji",
  "Zsym": "símbols",
  "Zxxx": "sense escriptura",
  "Zyyy": "comú",
  "Zzzz": "escriptura desconeguda",
  "aa": "àfar",
  "ab": "abkhaz",
  "ace": "atjeh",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adigué",
  "ae": "avèstic",
  "aeb": "Tunisian Arabic",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namíbia)",
  "af_ZA": "afrikaans (República de Sud-àfrica)",
  "afa": "llengua afroasiàtica",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "àkan",
  "ak_GH": "àkan (Ghana)",
  "akk": "accadi",
  "akz": "alabama",
  "ale": "aleuta",
  "alg": "llengua algonquina",
  "aln": "albanès geg",
  "alt": "altaic meridional",
  "am": "amhàric",
  "am_ET": "amhàric (Etiòpia)",
  "an": "aragonès",
  "ang": "anglès antic",
  "anp": "angika",
  "apa": "llengua apatxe",
  "ar": "àrab",
  "ar_001": "àrab estàndard modern",
  "ar_AE": "àrab (Emirats Àrabs Units)",
  "ar_BH": "àrab (Bahrain)",
  "ar_DJ": "àrab (Djibouti)",
  "ar_DZ": "àrab (Algèria)",
  "ar_EG": "àrab (Egipte)",
  "ar_EH": "àrab (Sàhara Occidental)",
  "ar_ER": "àrab (Eritrea)",
  "ar_IL": "àrab (Israel)",
  "ar_IQ": "àrab (Iraq)",
  "ar_JO": "àrab (Jordània)",
  "ar_KM": "àrab (Comores)",
  "ar_KW": "àrab (Kuwait)",
  "ar_LB": "àrab (Líban)",
  "ar_LY": "àrab (Líbia)",
  "ar_MA": "àrab (Marroc)",
  "ar_MR": "àrab (Mauritània)",
  "ar_OM": "àrab (Oman)",
  "ar_PS": "àrab (Palestina)",
  "ar_QA": "àrab (Qatar)",
  "ar_SA": "àrab (Aràbia Saudita)",
  "ar_SD": "àrab (Sudan)",
  "ar_SO": "àrab (Somàlia)",
  "ar_SS": "àrab (Sudan del Sud)",
  "ar_SY": "àrab (Síria)",
  "ar_TD": "àrab (Txad)",
  "ar_TN": "àrab (Tunísia)",
  "ar_YE": "àrab (Iemen)",
  "arc": "arameu",
  "arn": "mapudungu",
  "aro": "araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "ars": "àrab najdi",
  "art": "llengua artificial",
  "arw": "arauac",
  "ary": "Moroccan Arabic",
  "arz": "àrab egipci",
  "as": "assamès",
  "as_IN": "assamès (Índia)",
  "asa": "pare",
  "ase": "llengua de signes americana",
  "ast": "asturià",
  "ath": "llengua atapascana",
  "aus": "llengua australiana",
  "av": "àvar",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aimara",
  "az": "azerbaidjanès",
  "az_AZ": "azerbaidjanès (Azerbaidjan)",
  "az_Arab": "Azerí (àrab)",
  "az_Cyrl": "azerbaidjanès (ciríl·lic)",
  "az_Cyrl_AZ": "azerbaidjanès (ciríl·lic, Azerbaidjan)",
  "az_Latn": "azerbaidjanès (llatí)",
  "az_Latn_AZ": "azerbaidjanès (llatí, Azerbaidjan)",
  "azb": "South Azerbaijani",
  "ba": "baixkir",
  "bad": "banda",
  "bai": "bamileké",
  "bal": "balutxi",
  "ban": "balinès",
  "bar": "bavarès",
  "bas": "basa",
  "bat": "llengua bàltica",
  "bax": "bamum",
  "bbc": "Batak Toba",
  "bbj": "ghomala",
  "be": "belarús",
  "be_BY": "bielorús (Bielorússia)",
  "bej": "beja",
  "bem": "bemba",
  "ber": "berber",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "badaga",
  "bg": "búlgar",
  "bg_BG": "búlgar (Bulgària)",
  "bgn": "balutxi occidental",
  "bh": "bihari",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bicol",
  "bin": "edo",
  "bjn": "Banjar",
  "bkm": "kom",
  "bla": "blackfoot",
  "bm": "bambara",
  "bm_Latn": "bambara (llatí)",
  "bm_Latn_ML": "bambara (llatí, Mali)",
  "bn": "bengalí",
  "bn_BD": "bengalí (Bangla Desh)",
  "bn_IN": "bengalí (Índia)",
  "bnt": "bantu",
  "bo": "tibetà",
  "bo_CN": "tibetà (Xina)",
  "bo_IN": "tibetà (Índia)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretó",
  "br_FR": "bretó (França)",
  "bra": "braj",
  "brh": "brahui",
  "brx": "bodo",
  "bs": "bosnià",
  "bs_BA": "bosnià (Bòsnia i Hercegovina)",
  "bs_Cyrl": "bosnià (ciríl·lic)",
  "bs_Cyrl_BA": "bosnià (ciríl·lic, Bòsnia i Hercegovina)",
  "bs_Latn": "bosnià (llatí)",
  "bs_Latn_BA": "bosnià (llatí, Bòsnia i Hercegovina)",
  "bss": "akoose",
  "btk": "batak",
  "bua": "buriat",
  "bug": "bugui",
  "bum": "bulu",
  "byn": "bilin",
  "byv": "medumba",
  "ca": "català",
  "ca_AD": "català (Andorra)",
  "ca_ES": "català (Espanya)",
  "ca_FR": "català (França)",
  "ca_IT": "català (Itàlia)",
  "cad": "caddo",
  "cai": "llengua ameríndia d'Amèrica Central",
  "car": "carib",
  "cau": "llengua caucàsica",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "chakma",
  "ce": "txetxè",
  "ceb": "cebuà",
  "cel": "llengua cèltica",
  "cgg": "chiga",
  "ch": "chamorro",
  "chb": "txibtxa",
  "chg": "txagatai",
  "chk": "chuuk",
  "chm": "mari",
  "chn": "pidgin chinook",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cherokee",
  "chy": "xeiene",
  "cic": "Chickasaw",
  "ckb": "kurd central",
  "cmc": "txam",
  "co": "cors",
  "cop": "copte",
  "cpe": "llengua criolla o pidgin basada en l'anglès",
  "cpf": "llengua criolla o pidgin basada en el francès",
  "cpp": "llengua criolla o pidgin basada en el portuguès",
  "cps": "Capiznon",
  "cr": "cree",
  "crh": "tàtar de Crimea",
  "crp": "llengua criolla o pidgin",
  "crs": "francès crioll de les Seychelles",
  "cs": "txec",
  "cs_CZ": "txec (República Txeca)",
  "csb": "caixubi",
  "cu": "eslau eclesiàstic",
  "cus": "llengua cuixítica",
  "cv": "txuvaix",
  "cy": "gal·lès",
  "cy_GB": "gal·lès (Regne Unit)",
  "da": "danès",
  "da_DK": "danès (Dinamarca)",
  "da_GL": "danès (Grenlàndia)",
  "dak": "dakota",
  "dar": "darguà",
  "dav": "taita",
  "day": "daiak",
  "de": "alemany",
  "de_AT": "alemany (Àustria)",
  "de_BE": "alemany (Bèlgica)",
  "de_CH": "alemany (Suïssa)",
  "de_DE": "alemany (Alemanya)",
  "de_LI": "alemany (Liechtenstein)",
  "de_LU": "alemany (Luxemburg)",
  "del": "delaware",
  "den": "slavi",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "llengua dravídica",
  "dsb": "baix sòrab",
  "dtp": "Central Dusun",
  "dua": "douala",
  "dum": "neerlandès mitjà",
  "dv": "divehi",
  "dyo": "diola",
  "dyu": "jula",
  "dz": "dzongka",
  "dz_BT": "dzongka (Bhutan)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "ewe",
  "ee_GH": "ewe (Ghana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egl": "emilià",
  "egy": "egipci antic",
  "eka": "ekajuk",
  "el": "grec",
  "el_CY": "grec (Xipre)",
  "el_GR": "grec (Grècia)",
  "elx": "elamita",
  "en": "anglès",
  "en_AG": "anglès (Antigua i Barbuda)",
  "en_AI": "anglès (Anguilla)",
  "en_AS": "anglès (Samoa Nord-americana)",
  "en_AU": "anglès (Austràlia)",
  "en_BB": "anglès (Barbados)",
  "en_BE": "anglès (Bèlgica)",
  "en_BM": "anglès (Bermudes)",
  "en_BS": "anglès (Bahames)",
  "en_BW": "anglès (Botswana)",
  "en_BZ": "anglès (Belize)",
  "en_CA": "anglès (Canadà)",
  "en_CC": "anglès (illes Cocos)",
  "en_CK": "anglès (illes Cook)",
  "en_CM": "anglès (Camerun)",
  "en_CX": "anglès (illa Christmas)",
  "en_DG": "anglès (Diego Garcia)",
  "en_DM": "anglès (Dominica)",
  "en_Dsrt": "Anglès (Deseret)",
  "en_ER": "anglès (Eritrea)",
  "en_FJ": "anglès (Fiji)",
  "en_FK": "anglès (Illes Malvines)",
  "en_FM": "anglès (Micronèsia)",
  "en_GB": "anglès (Regne Unit)",
  "en_GD": "anglès (Grenada)",
  "en_GG": "anglès (Guernsey)",
  "en_GH": "anglès (Ghana)",
  "en_GI": "anglès (Gibraltar)",
  "en_GM": "anglès (Gàmbia)",
  "en_GU": "anglès (Guam)",
  "en_GY": "anglès (Guyana)",
  "en_HK": "anglès (Hong Kong (RAE Xina))",
  "en_IE": "anglès (Irlanda)",
  "en_IM": "anglès (illa de Man)",
  "en_IN": "anglès (Índia)",
  "en_IO": "anglès (Territori Britànic de l’Oceà Índic)",
  "en_JE": "anglès (Jersey)",
  "en_JM": "anglès (Jamaica)",
  "en_KE": "anglès (Kenya)",
  "en_KI": "anglès (Kiribati)",
  "en_KN": "anglès (Saint Christopher i Nevis)",
  "en_KY": "anglès (Illes Caiman)",
  "en_LC": "anglès (Saint Lucia)",
  "en_LR": "anglès (Libèria)",
  "en_LS": "anglès (Lesotho)",
  "en_MG": "anglès (Madagascar)",
  "en_MH": "anglès (illes Marshall)",
  "en_MO": "anglès (Macau (RAE Xina))",
  "en_MP": "anglès (illes Mariannes del Nord)",
  "en_MS": "anglès (Montserrat)",
  "en_MT": "anglès (Malta)",
  "en_MU": "anglès (Maurici)",
  "en_MW": "anglès (Malawi)",
  "en_MY": "anglès (Malàisia)",
  "en_NA": "anglès (Namíbia)",
  "en_NF": "anglès (Norfolk)",
  "en_NG": "anglès (Nigèria)",
  "en_NR": "anglès (Nauru)",
  "en_NU": "anglès (Niue)",
  "en_NZ": "anglès (Nova Zelanda)",
  "en_PG": "anglès (Papua Nova Guinea)",
  "en_PH": "anglès (Filipines)",
  "en_PK": "anglès (Pakistan)",
  "en_PN": "anglès (illes Pitcairn)",
  "en_PR": "anglès (Puerto Rico)",
  "en_PW": "anglès (Palau)",
  "en_RW": "anglès (Ruanda)",
  "en_SB": "anglès (illes Salomó)",
  "en_SC": "anglès (Seychelles)",
  "en_SD": "anglès (Sudan)",
  "en_SG": "anglès (Singapur)",
  "en_SH": "anglès (Saint Helena)",
  "en_SL": "anglès (Sierra Leone)",
  "en_SS": "anglès (Sudan del Sud)",
  "en_SX": "anglès (Sint Maarten)",
  "en_SZ": "anglès (Swazilàndia)",
  "en_TC": "anglès (Illes Turks i Caicos)",
  "en_TK": "anglès (Tokelau)",
  "en_TO": "anglès (Tonga)",
  "en_TT": "anglès (Trinitat i Tobago)",
  "en_TV": "anglès (Tuvalu)",
  "en_TZ": "anglès (Tanzània)",
  "en_UG": "anglès (Uganda)",
  "en_UM": "anglès (illes Perifèriques Menors dels EUA)",
  "en_US": "anglès (Estats Units)",
  "en_VC": "anglès (Saint Vincent i les Grenadines)",
  "en_VG": "anglès (Illes Verges Britàniques)",
  "en_VI": "anglès (Illes Verges Nord-americanes)",
  "en_VU": "anglès (Vanuatu)",
  "en_WS": "anglès (Samoa)",
  "en_ZA": "anglès (República de Sud-àfrica)",
  "en_ZM": "anglès (Zàmbia)",
  "en_ZW": "anglès (Zimbàbue)",
  "enm": "anglès mitjà",
  "eo": "esperanto",
  "es": "espanyol",
  "es_419": "espanyol hispanoamericà",
  "es_AR": "espanyol (Argentina)",
  "es_BO": "espanyol (Bolívia)",
  "es_CL": "espanyol (Xile)",
  "es_CO": "espanyol (Colòmbia)",
  "es_CR": "espanyol (Costa Rica)",
  "es_CU": "espanyol (Cuba)",
  "es_DO": "espanyol (República Dominicana)",
  "es_EA": "espanyol (Ceuta i Melilla)",
  "es_EC": "espanyol (Equador)",
  "es_ES": "espanyol (Espanya)",
  "es_GQ": "espanyol (Guinea Equatorial)",
  "es_GT": "espanyol (Guatemala)",
  "es_HN": "espanyol (Hondures)",
  "es_IC": "espanyol (illes Canàries)",
  "es_MX": "espanyol (Mèxic)",
  "es_NI": "espanyol (Nicaragua)",
  "es_PA": "espanyol (Panamà)",
  "es_PE": "espanyol (Perú)",
  "es_PH": "espanyol (Filipines)",
  "es_PR": "espanyol (Puerto Rico)",
  "es_PY": "espanyol (Paraguai)",
  "es_SV": "espanyol (El Salvador)",
  "es_US": "espanyol (Estats Units)",
  "es_UY": "espanyol (Uruguai)",
  "es_VE": "espanyol (Veneçuela)",
  "esu": "Central Yupik",
  "et": "estonià",
  "et_EE": "estonià (Estònia)",
  "eu": "basc",
  "eu_ES": "basc (Espanya)",
  "ewo": "ewondo",
  "ext": "extremeny",
  "fa": "persa",
  "fa_AF": "persa (Afganistan)",
  "fa_IR": "persa (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "ful",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "ful (Camerun)",
  "ff_GN": "ful (Guinea)",
  "ff_MR": "ful (Mauritània)",
  "ff_SN": "ful (Senegal)",
  "fi": "finès",
  "fi_FI": "finès (Finlàndia)",
  "fil": "filipí",
  "fit": "Tornedalen Finnish",
  "fiu": "llengua finoúgrica",
  "fj": "fijià",
  "fo": "feroès",
  "fo_FO": "feroès (illes Fèroe)",
  "fon": "fon",
  "fr": "francès",
  "fr_BE": "francès (Bèlgica)",
  "fr_BF": "francès (Burkina Faso)",
  "fr_BI": "francès (Burundi)",
  "fr_BJ": "francès (Benín)",
  "fr_BL": "francès (Saint Barthélemy)",
  "fr_CA": "francès (Canadà)",
  "fr_CD": "francès (Congo - Kinshasa)",
  "fr_CF": "francès (República Centreafricana)",
  "fr_CG": "francès (Congo - Brazzaville)",
  "fr_CH": "francès (Suïssa)",
  "fr_CI": "francès (Costa d’Ivori)",
  "fr_CM": "francès (Camerun)",
  "fr_DJ": "francès (Djibouti)",
  "fr_DZ": "francès (Algèria)",
  "fr_FR": "francès (França)",
  "fr_GA": "francès (Gabon)",
  "fr_GF": "francès (Guaiana Francesa)",
  "fr_GN": "francès (Guinea)",
  "fr_GP": "francès (Guadeloupe)",
  "fr_GQ": "francès (Guinea Equatorial)",
  "fr_HT": "francès (Haití)",
  "fr_KM": "francès (Comores)",
  "fr_LU": "francès (Luxemburg)",
  "fr_MA": "francès (Marroc)",
  "fr_MC": "francès (Mònaco)",
  "fr_MF": "francès (Saint Martin)",
  "fr_MG": "francès (Madagascar)",
  "fr_ML": "francès (Mali)",
  "fr_MQ": "francès (Martinica)",
  "fr_MR": "francès (Mauritània)",
  "fr_MU": "francès (Maurici)",
  "fr_NC": "francès (Nova Caledònia)",
  "fr_NE": "francès (Níger)",
  "fr_PF": "francès (Polinèsia Francesa)",
  "fr_PM": "francès (Saint-Pierre-et-Miquelon)",
  "fr_RE": "francès (Illa de la Reunió)",
  "fr_RW": "francès (Ruanda)",
  "fr_SC": "francès (Seychelles)",
  "fr_SN": "francès (Senegal)",
  "fr_SY": "francès (Síria)",
  "fr_TD": "francès (Txad)",
  "fr_TG": "francès (Togo)",
  "fr_TN": "francès (Tunísia)",
  "fr_VU": "francès (Vanuatu)",
  "fr_WF": "francès (Wallis i Futuna)",
  "fr_YT": "francès (Mayotte)",
  "frc": "francès cajun",
  "frm": "francès mitjà",
  "fro": "francès antic",
  "frp": "Arpitan",
  "frr": "frisó septentrional",
  "frs": "frisó oriental",
  "fur": "friülà",
  "fy": "frisó occidental",
  "fy_NL": "frisó oriental (Països Baixos)",
  "ga": "irlandès",
  "ga_IE": "irlandès (Irlanda)",
  "gaa": "ga",
  "gag": "gagaús",
  "gan": "xinès gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "gaèlic escocès",
  "gd_GB": "gaèlic escocès (Regne Unit)",
  "gem": "llengua germànica",
  "gez": "gueez",
  "gil": "gilbertès",
  "gl": "gallec",
  "gl_ES": "gallec (Espanya)",
  "glk": "gilaki",
  "gmh": "alt alemany mitjà",
  "gn": "guaraní",
  "goh": "alt alemany antic",
  "gom": "concani de Goa",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gòtic",
  "grb": "grebo",
  "grc": "grec antic",
  "gsw": "alemany suís",
  "gu": "gujarati",
  "gu_IN": "gujarati (Índia)",
  "guc": "wayú",
  "gur": "Frafra",
  "guz": "gusí",
  "gv": "manx",
  "gv_IM": "manx (illa de Man)",
  "gwi": "gwich’in",
  "ha": "haussa",
  "ha_GH": "haussa (Ghana)",
  "ha_Latn": "haussa (llatí)",
  "ha_Latn_GH": "haussa (llatí, Ghana)",
  "ha_Latn_NE": "haussa (llatí, Níger)",
  "ha_Latn_NG": "haussa (llatí, Nigèria)",
  "ha_NE": "haussa (Níger)",
  "ha_NG": "haussa (Nigèria)",
  "hai": "haida",
  "hak": "xinès hakka",
  "haw": "hawaià",
  "he": "hebreu",
  "he_IL": "hebreu (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (Índia)",
  "hif": "hindi de Fiji",
  "hil": "híligaynon",
  "him": "himachali",
  "hit": "hitita",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croat",
  "hr_BA": "croat (Bòsnia i Hercegovina)",
  "hr_HR": "croat (Croàcia)",
  "hsb": "alt sòrab",
  "hsn": "xinès xiang",
  "ht": "crioll d’Haití",
  "hu": "hongarès",
  "hu_HU": "hongarès (Hongria)",
  "hup": "hupa",
  "hy": "armeni",
  "hy_AM": "armeni (Armènia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonesi",
  "id_ID": "indonesi (Indonèsia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigèria)",
  "ii": "yi sichuan",
  "ii_CN": "yi sichuan (Xina)",
  "ijo": "ijo",
  "ik": "inupiak",
  "ilo": "ilocano",
  "inc": "llengua índica",
  "ine": "llengua indoeuropea",
  "inh": "ingúix",
  "io": "ido",
  "ira": "llengua irànica",
  "iro": "iroquès",
  "is": "islandès",
  "is_IS": "islandès (Islàndia)",
  "it": "italià",
  "it_CH": "italià (Suïssa)",
  "it_IT": "italià (Itàlia)",
  "it_SM": "italià (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "japonès",
  "ja_JP": "japonès (Japó)",
  "jam": "crioll anglès de Jamaica",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "judeopersa",
  "jrb": "judeoàrab",
  "jut": "Jutish",
  "jv": "javanès",
  "ka": "georgià",
  "ka_GE": "georgià (Geòrgia)",
  "kaa": "karakalpak",
  "kab": "cabilenc",
  "kac": "katxin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "kabardí",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "crioll capverdià",
  "ken": "kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "kaingà",
  "kha": "khasi",
  "khi": "llengua khoisan",
  "kho": "khotanès",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "kikuiu",
  "ki_KE": "kikuiu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "kazakh",
  "kk_Cyrl": "kazakh (ciríl·lic)",
  "kk_Cyrl_KZ": "kazakh (ciríl·lic, Kazakhstan)",
  "kk_KZ": "kazakh (Kazakhstan)",
  "kkj": "kako",
  "kl": "grenlandès",
  "kl_GL": "grenlandès (Grenlàndia)",
  "kln": "kalenjin",
  "km": "khmer",
  "km_KH": "khmer (Cambodja)",
  "kmb": "kimbundu",
  "kn": "kannada",
  "kn_IN": "kannada (Índia)",
  "ko": "coreà",
  "ko_KP": "coreà (Corea del Nord)",
  "ko_KR": "coreà (Corea del Sud)",
  "koi": "komi-permiac",
  "kok": "concani",
  "kos": "kosraeà",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karatxai-balkar",
  "kri": "krio",
  "krj": "Kinaray-a",
  "krl": "carelià",
  "kro": "kru",
  "kru": "kurukh",
  "ks": "caixmiri",
  "ks_Arab": "caixmiri (àrab)",
  "ks_Arab_IN": "caixmiri (àrab, Índia)",
  "ks_IN": "caixmiri (Índia)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kölsch",
  "ku": "kurd",
  "kum": "kúmik",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "còrnic",
  "kw_GB": "còrnic (Regne Unit)",
  "ky": "kirguís",
  "ky_Cyrl": "kirguís (ciríl·lic)",
  "ky_Cyrl_KG": "kirguís (ciríl·lic, Kirguizistan)",
  "ky_KG": "kirguís (Kirguizistan)",
  "la": "llatí",
  "lad": "judeocastellà",
  "lag": "langi",
  "lah": "panjabi occidental",
  "lam": "lamba",
  "lb": "luxemburguès",
  "lb_LU": "luxemburguès (Luxemburg)",
  "lez": "lesguià",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburguès",
  "lij": "lígur",
  "liv": "Livonian",
  "lkt": "lakota",
  "lmo": "llombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Congo - Kinshasa)",
  "ln_CF": "lingala (República Centreafricana)",
  "ln_CG": "lingala (Congo - Brazzaville)",
  "lo": "laosià",
  "lo_LA": "laosià (Laos)",
  "lol": "mongo",
  "lou": "crioll francès de Louisiana",
  "loz": "lozi",
  "lrc": "luri septentrional",
  "lt": "lituà",
  "lt_LT": "lituà (Lituània)",
  "ltg": "Latgalian",
  "lu": "luba katanga",
  "lu_CD": "luba katanga (Congo - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luisenyo",
  "lun": "lunda",
  "luo": "luo",
  "lus": "mizo",
  "luy": "luyia",
  "lv": "letó",
  "lv_LV": "letó (Letònia)",
  "lzh": "xinès clàssic",
  "lzz": "laz",
  "mad": "madurès",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makassar",
  "man": "mandinga",
  "map": "llengua austronèsia",
  "mas": "massai",
  "mde": "maba",
  "mdf": "mordovià moksa",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "mauricià",
  "mg": "malgaix",
  "mg_MG": "malgaix (Madagascar)",
  "mga": "gaèlic irlandès mitjà",
  "mgh": "makhuwa-metto",
  "mgo": "meta’",
  "mh": "marshallès",
  "mi": "maori",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "llengua miscel·lània",
  "mk": "macedoni",
  "mk_MK": "macedoni (Macedònia)",
  "mkh": "llengua monkhmer",
  "ml": "malaiàlam",
  "ml_IN": "malaiàlam (Índia)",
  "mn": "mongol",
  "mn_Cyrl": "mongol (ciríl·lic)",
  "mn_Cyrl_MN": "mongol (ciríl·lic, Mongòlia)",
  "mn_MN": "mongol (Mongòlia)",
  "mnc": "manxú",
  "mni": "manipurí",
  "mno": "llengua manobo",
  "mo": "moldau",
  "moh": "mohawk",
  "mos": "moore",
  "mr": "marathi",
  "mr_IN": "marathi (Índia)",
  "mrj": "mari occidental",
  "ms": "malai",
  "ms_BN": "malai (Brunei)",
  "ms_Latn": "malai (llatí)",
  "ms_Latn_BN": "malai (llatí, Brunei)",
  "ms_Latn_MY": "malai (llatí, Malàisia)",
  "ms_Latn_SG": "malai (llatí, Singapur)",
  "ms_MY": "malai (Malàisia)",
  "ms_SG": "malai (Singapur)",
  "mt": "maltès",
  "mt_MT": "maltès (Malta)",
  "mua": "mundang",
  "mul": "llengües vàries",
  "mun": "llengua munda",
  "mus": "creek",
  "mwl": "mirandès",
  "mwr": "marwari",
  "mwv": "Mentawai",
  "my": "birmà",
  "my_MM": "birmà (Myanmar (Birmània))",
  "mye": "myene",
  "myn": "llengua maia",
  "myv": "mordovià erza",
  "mzn": "mazanderani",
  "na": "nauruà",
  "nah": "nàhuatl",
  "nai": "llengua ameríndia septentrional",
  "nan": "xinès min del sud",
  "nap": "napolità",
  "naq": "nama",
  "nb": "noruec bokmål",
  "nb_NO": "noruec bokmål (Noruega)",
  "nb_SJ": "noruec bokmål (Svalbard i Jan Mayen)",
  "nd": "ndebele septentrional",
  "nd_ZW": "ndebele septentrional (Zimbàbue)",
  "nds": "baix alemany",
  "nds_NL": "baix saxó",
  "ne": "nepalès",
  "ne_IN": "nepalès (Índia)",
  "ne_NP": "nepalès (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "llengua nigerokurdufaniana",
  "niu": "niueà",
  "njo": "Ao Naga",
  "nl": "neerlandès",
  "nl_AW": "neerlandès (Aruba)",
  "nl_BE": "neerlandès (Bèlgica)",
  "nl_BQ": "neerlandès (Carib Neerlandès)",
  "nl_CW": "neerlandès (Curaçao)",
  "nl_NL": "neerlandès (Països Baixos)",
  "nl_SR": "neerlandès (Surinam)",
  "nl_SX": "neerlandès (Sint Maarten)",
  "nmg": "bissio",
  "nn": "noruec nynorsk",
  "nn_NO": "noruec nynorsk (Noruega)",
  "nnh": "ngiemboon",
  "no": "noruec",
  "no_NO": "noruec (Noruega)",
  "nog": "nogai",
  "non": "nòrdic antic",
  "nov": "novial",
  "nqo": "n’Ko",
  "nr": "ndebele meridional",
  "nso": "sotho septentrional",
  "nub": "llengua nubiana",
  "nus": "nuer",
  "nv": "navaho",
  "nwc": "newari clàssic",
  "ny": "nyanja",
  "nym": "nyamwesi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzema",
  "oc": "occità",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiòpia)",
  "om_KE": "oromo (Kenya)",
  "or": "oriya",
  "or_IN": "oriya (Índia)",
  "os": "osseta",
  "os_GE": "osset (Geòrgia)",
  "os_RU": "osset (Rússia)",
  "osa": "osage",
  "ota": "turc otomà",
  "oto": "llengua otomangueana",
  "pa": "panjabi",
  "pa_Arab": "panjabi (àrab)",
  "pa_Arab_PK": "panjabi (àrab, Pakistan)",
  "pa_Guru": "panjabi (gurmukhi)",
  "pa_Guru_IN": "panjabi (gurmukhi, Índia)",
  "pa_IN": "panjabi (Índia)",
  "pa_PK": "panjabi (Pakistan)",
  "paa": "llengua papú",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiament",
  "pau": "palauà",
  "pcd": "picard",
  "pcm": "pidgin de Nigèria",
  "pdc": "alemany pennsilvanià",
  "pdt": "Plautdietsch",
  "peo": "persa antic",
  "pfl": "alemany palatí",
  "phi": "llengua filipina",
  "phn": "fenici",
  "pi": "pali",
  "pl": "polonès",
  "pl_PL": "polonès (Polònia)",
  "pms": "piemontès",
  "pnt": "pòntic",
  "pon": "ponapeà",
  "pra": "pràcrit",
  "prg": "prussià",
  "pro": "provençal antic",
  "ps": "paixtu",
  "ps_AF": "paixtu (Afganistan)",
  "pt": "portuguès",
  "pt_AO": "portuguès (Angola)",
  "pt_BR": "portuguès (Brasil)",
  "pt_CV": "portuguès (Cap Verd)",
  "pt_GW": "portuguès (Guinea Bissau)",
  "pt_MO": "portuguès (Macau (RAE Xina))",
  "pt_MZ": "portuguès (Moçambic)",
  "pt_PT": "portuguès (Portugal)",
  "pt_ST": "portuguès (São Tomé i Príncipe)",
  "pt_TL": "portuguès (Timor Oriental)",
  "qu": "quítxua",
  "qu_BO": "quítxua (Bolívia)",
  "qu_EC": "quítxua (Equador)",
  "qu_PE": "quítxua (Perú)",
  "quc": "k’iche’",
  "qug": "Chimborazo Highland Quichua",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotongà",
  "rgn": "romanyès",
  "rif": "Riffian",
  "rm": "retoromànic",
  "rm_CH": "retoromànic (Suïssa)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "romanès",
  "ro_MD": "romanès (Moldàvia)",
  "ro_RO": "romanès (Romania)",
  "roa": "llengua romànica",
  "rof": "rombo",
  "rom": "romaní",
  "root": "arrel",
  "rtm": "Rotuman",
  "ru": "rus",
  "ru_BY": "rus (Bielorússia)",
  "ru_KG": "rus (Kirguizistan)",
  "ru_KZ": "rus (Kazakhstan)",
  "ru_MD": "rus (Moldàvia)",
  "ru_RU": "rus (Rússia)",
  "ru_UA": "rus (Ucraïna)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromanès",
  "rw": "ruandès",
  "rw_RW": "ruandès (Ruanda)",
  "rwk": "rwo",
  "sa": "sànscrit",
  "sad": "sandawe",
  "sah": "iacut",
  "sai": "llengua ameríndia meridional",
  "sal": "llengua salish",
  "sam": "arameu samarità",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sard",
  "scn": "sicilià",
  "sco": "escocès",
  "sd": "sindi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "sasserès",
  "sdh": "kurd meridional",
  "se": "sami septentrional",
  "se_FI": "sami septentrional (Finlàndia)",
  "se_NO": "sami septentrional (Noruega)",
  "se_SE": "sami septentrional (Suècia)",
  "see": "seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "selkup",
  "sem": "llengua semítica",
  "ses": "songhai oriental",
  "sg": "sango",
  "sg_CF": "sango (República Centreafricana)",
  "sga": "irlandès antic",
  "sgn": "llengua de signes",
  "sgs": "Samogitian",
  "sh": "serbocroat",
  "sh_BA": "serbocroat (Bòsnia i Hercegovina)",
  "shi": "taixelhit",
  "shi_Latn": "Shilha (llatí)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "xan",
  "shu": "àrab txadià",
  "si": "singalès",
  "si_LK": "singalès (Sri Lanka)",
  "sid": "sidamo",
  "sio": "llengua sioux",
  "sit": "llengua sinotibetana",
  "sk": "eslovac",
  "sk_SK": "eslovac (Eslovàquia)",
  "sl": "eslovè",
  "sl_SI": "eslovè (Eslovènia)",
  "sla": "llengua eslava",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoà",
  "sma": "sami meridional",
  "smi": "llengua sami",
  "smj": "sami lule",
  "smn": "sami d’Inari",
  "sms": "sami skolt",
  "sn": "shona",
  "sn_ZW": "shona (Zimbàbue)",
  "snk": "soninke",
  "so": "somali",
  "so_DJ": "somali (Djibouti)",
  "so_ET": "somali (Etiòpia)",
  "so_KE": "somali (Kenya)",
  "so_SO": "somali (Somàlia)",
  "sog": "sogdià",
  "son": "songhai",
  "sq": "albanès",
  "sq_AL": "albanès (Albània)",
  "sq_MK": "albanès (Macedònia)",
  "sq_XK": "albanès (Kosovo)",
  "sr": "serbi",
  "sr_BA": "serbi (Bòsnia i Hercegovina)",
  "sr_Cyrl": "serbi (ciríl·lic)",
  "sr_Cyrl_BA": "serbi (ciríl·lic, Bòsnia i Hercegovina)",
  "sr_Cyrl_ME": "serbi (ciríl·lic, Montenegro)",
  "sr_Cyrl_RS": "serbi (ciríl·lic, Sèrbia)",
  "sr_Cyrl_XK": "serbi (ciríl·lic, Kosovo)",
  "sr_Latn": "serbi (llatí)",
  "sr_Latn_BA": "serbi (llatí, Bòsnia i Hercegovina)",
  "sr_Latn_ME": "serbi (llatí, Montenegro)",
  "sr_Latn_RS": "serbi (llatí, Sèrbia)",
  "sr_Latn_XK": "serbi (llatí, Kosovo)",
  "sr_ME": "serbi (Montenegro)",
  "sr_RS": "serbi (Sèrbia)",
  "sr_XK": "serbi (Kosovo)",
  "srn": "sranan",
  "srr": "serer",
  "ss": "swazi",
  "ssa": "llengua nilosahariana",
  "ssy": "saho",
  "st": "sotho meridional",
  "stq": "Saterland Frisian",
  "su": "sondanès",
  "suk": "sukuma",
  "sus": "susú",
  "sux": "sumeri",
  "sv": "suec",
  "sv_AX": "suec (illes Åland)",
  "sv_FI": "suec (Finlàndia)",
  "sv_SE": "suec (Suècia)",
  "sw": "suahili",
  "sw_CD": "suahili del Congo",
  "sw_KE": "suahili (Kenya)",
  "sw_TZ": "suahili (Tanzània)",
  "sw_UG": "suahili (Uganda)",
  "swb": "comorià",
  "swc": "suahili del Congo",
  "syc": "siríac clàssic",
  "syr": "siríac",
  "szl": "silesià",
  "ta": "tàmil",
  "ta_IN": "tàmil (Índia)",
  "ta_LK": "tàmil (Sri Lanka)",
  "ta_MY": "tàmil (Malàisia)",
  "ta_SG": "tàmil (Singapur)",
  "tai": "llengua tai",
  "tcy": "Tulu",
  "te": "telugu",
  "te_IN": "telugu (Índia)",
  "tem": "temne",
  "teo": "teso",
  "ter": "terena",
  "tet": "tètum",
  "tg": "tadjik",
  "th": "tai",
  "th_TH": "tailandès (Tailàndia)",
  "ti": "tigrinya",
  "ti_ER": "tigrinya (Eritrea)",
  "ti_ET": "tigrinya (Etiòpia)",
  "tig": "tigre",
  "tiv": "tiv",
  "tk": "turcman",
  "tkl": "tokelauès",
  "tkr": "tsakhur",
  "tl": "tagal",
  "tl_PH": "tagàlog (Filipines)",
  "tlh": "klingonià",
  "tli": "tlingit",
  "tly": "talix",
  "tmh": "amazic",
  "tn": "setswana",
  "to": "tongalès",
  "to_TO": "tongalès (Tonga)",
  "tog": "tonga",
  "tpi": "tok pisin",
  "tr": "turc",
  "tr_CY": "turc (Xipre)",
  "tr_TR": "turc (Turquia)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshià",
  "tt": "tàtar",
  "ttt": "tat meridional",
  "tum": "tumbuka",
  "tup": "llengua tupí",
  "tut": "llengua altaica",
  "tvl": "tuvaluà",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitià",
  "tyv": "tuvinià",
  "tzm": "amazic del Marroc central",
  "udm": "udmurt",
  "ug": "uigur",
  "ug_Arab": "uigur (àrab)",
  "ug_Arab_CN": "uigur (àrab, Xina)",
  "ug_CN": "uigur (Xina)",
  "uga": "ugarític",
  "uk": "ucraïnès",
  "uk_UA": "ucraïnès (Ucraïna)",
  "umb": "umbundu",
  "und": "idioma desconegut",
  "ur": "urdú",
  "ur_IN": "urdú (Índia)",
  "ur_PK": "urdú (Pakistan)",
  "uz": "uzbek",
  "uz_AF": "uzbek (Afganistan)",
  "uz_Arab": "uzbek (àrab)",
  "uz_Arab_AF": "uzbek (àrab, Afganistan)",
  "uz_Cyrl": "uzbek (ciríl·lic)",
  "uz_Cyrl_UZ": "uzbek (ciríl·lic, Uzbekistan)",
  "uz_Latn": "uzbek (llatí)",
  "uz_Latn_UZ": "uzbek (llatí, Uzbekistan)",
  "uz_UZ": "uzbek (Uzbekistan)",
  "vai": "vai",
  "vai_Latn": "Vai (llatí)",
  "ve": "venda",
  "vec": "vènet",
  "vep": "vepse",
  "vi": "vietnamita",
  "vi_VN": "vietnamita (Vietnam)",
  "vls": "flamenc occidental",
  "vmf": "Main-Franconian",
  "vo": "volapük",
  "vot": "vòtic",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "való",
  "wae": "walser",
  "wak": "llengua wakash",
  "wal": "wolaita",
  "war": "waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wen": "sòrab",
  "wo": "wòlof",
  "wuu": "xinès wu",
  "xal": "calmuc",
  "xh": "xosa",
  "xmf": "mingrelià",
  "xog": "soga",
  "yao": "yao",
  "yap": "yapeà",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "ídix",
  "yo": "ioruba",
  "yo_BJ": "ioruba (Benín)",
  "yo_NG": "ioruba (Nigèria)",
  "ypk": "llengua iupik",
  "yrl": "Nheengatu",
  "yue": "cantonès",
  "yue_Hans": "Cantonès (xinès simplificat)",
  "yue_Hant": "Cantonès (xinès tradicional)",
  "za": "zhuang",
  "zap": "zapoteca",
  "zbl": "símbols Bliss",
  "zea": "zelandès",
  "zen": "zenaga",
  "zgh": "amazic estàndard marroquí",
  "zh": "xinès",
  "zh_CN": "xinès (Xina)",
  "zh_HK": "xinès (Hong Kong (RAE Xina))",
  "zh_Hans": "xinès (simplificat)",
  "zh_Hans_CN": "xinès (simplificat, Xina)",
  "zh_Hans_HK": "xinès (simplificat, Hong Kong (RAE Xina))",
  "zh_Hans_MO": "xinès (simplificat, Macau (RAE Xina))",
  "zh_Hans_SG": "xinès (simplificat, Singapur)",
  "zh_Hant": "xinès (tradicional)",
  "zh_Hant_HK": "xinès (tradicional, Hong Kong (RAE Xina))",
  "zh_Hant_MO": "xinès (tradicional, Macau (RAE Xina))",
  "zh_Hant_TW": "xinès (tradicional, Taiwan)",
  "zh_MO": "xinès (Macau (RAE Xina))",
  "zh_SG": "xinès (Singapur)",
  "zh_TW": "xinès (Taiwan)",
  "znd": "zande",
  "zu": "zulu",
  "zu_ZA": "zulu (República de Sud-àfrica)",
  "zun": "zuni",
  "zxx": "sense contingut lingüístic",
  "zza": "zaza"
};
