const names = {
  "aa": "Afar",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "af": "африк",
  "ain": "Ainu",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "an": "Aragonese",
  "anp": "Angika",
  "arp": "Arapaho",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "ay": "Aymara",
  "ban": "Balinese",
  "bas": "Basaa",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bug": "Buginese",
  "byn": "Blin",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chr": "чироки",
  "chy": "Cheyenne",
  "ckb": "сорани күрд",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "уэлс",
  "dak": "Dakota",
  "dar": "Dargwa",
  "de_AT": "герман (Австри)",
  "de_CH": "герман (Швейцари)",
  "dgr": "Dogrib",
  "dsb": "ловер-сорби",
  "dv": "Divehi",
  "dz": "жонха",
  "dzg": "Dazaga",
  "efi": "Efik",
  "eka": "Ekajuk",
  "en_AU": "англи (Австрали)",
  "en_CA": "англи (Канад)",
  "en_GB": "англи (Их Британи)",
  "en_US": "англи (Америкийн Нэгдсэн Улс)",
  "es_419": "латин америкийн испани",
  "es_ES": "испани (Испани)",
  "es_MX": "испани (Мексик)",
  "ewo": "Ewondo",
  "ff": "Fulah",
  "fi": "финлянд",
  "fil": "филиппин",
  "fon": "Fon",
  "fr_CA": "франц (Канад)",
  "fr_CH": "франц (Швейцари)",
  "fur": "Friulian",
  "fy": "баруун фризын",
  "gaa": "Ga",
  "gd": "шотланд келт",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "галик",
  "gor": "Gorontalo",
  "gsw": "швейцари герман",
  "gwi": "Gwichʼin",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "ht": "гаити",
  "hu": "унгар",
  "hup": "Hupa",
  "hz": "Herero",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ii": "шичуан еи",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "jbo": "Lojban",
  "kac": "Kachin",
  "kaj": "Jju",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kfo": "Koro",
  "kha": "Khasi",
  "kj": "Kuanyama",
  "kk": "хасаг",
  "kkj": "Kako",
  "km": "камбож",
  "kmb": "Kimbundu",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ksb": "шамбала",
  "ksh": "Colognian",
  "ku": "күрд",
  "kum": "Kumyk",
  "kv": "Komi",
  "kw": "корны",
  "lad": "Ladino",
  "lez": "Lezghian",
  "li": "Limburgish",
  "loz": "Lozi",
  "lua": "Luba-Lulua",
  "lun": "Lunda",
  "lus": "Mizo",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "mdf": "Moksha",
  "men": "Mende",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "ml": "малайлам",
  "mni": "Manipuri",
  "mos": "Mossi",
  "mt": "малти",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl": "голланд",
  "nl_BE": "голланд (Белги)",
  "nnh": "Ngiemboon",
  "nog": "Nogai",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nv": "Navajo",
  "ny": "Nyanja",
  "oc": "францын окситан",
  "os": "Ossetic",
  "pa": "панжаб",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "prg": "Prussian",
  "ps": "пашто",
  "pt_BR": "португал (Бразил)",
  "pt_PT": "португал (Португал)",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "ro_MD": "румын (Молдав)",
  "root": "Root",
  "rup": "Aromanian",
  "rw": "кинярванда",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sh": "Serbo-Croatian",
  "shn": "Shan",
  "sl": "словен",
  "sm": "Samoan",
  "snk": "Soninke",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "suk": "Sukuma",
  "swb": "Comorian",
  "syr": "Syriac",
  "tem": "Timne",
  "tet": "Tetum",
  "ti": "тигрина",
  "tig": "Tigre",
  "tlh": "Klingon",
  "tn": "Tswana",
  "tpi": "Tok Pisin",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "төв атласын тамазайт",
  "udm": "Udmurt",
  "ug": "уйгар",
  "uk": "украйн",
  "umb": "Umbundu",
  "und": "тодорхойгүй хэл",
  "ve": "Venda",
  "vo": "Volapük",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "xal": "Kalmyk",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yue": "Cantonese",
  "zgh": "тамазит",
  "zh_Hans": "хятад (хялбаршуулсан)",
  "zh_Hant": "хятад (уламжлалт)",
  "zun": "Zuni",
  "zxx": "хэл зүйн агуулга байхгүй",
  "zza": "Zaza"
};
