const names = {
  "af": "ଆଫ୍ରିକାନସ୍",
  "agq": "Aghem",
  "ar_001": "Modern Standard Arabic",
  "arn": "ଆରାଉକାନିଆନ୍",
  "as": "ଆସାମୀ",
  "asa": "Asu",
  "ba": "ବଶଖିର୍",
  "bez": "Bena",
  "bla": "ବିକ୍ସିକା",
  "bn": "ବଙ୍ଗାଳୀ",
  "bo": "ତିବେତାନ୍",
  "brx": "Bodo",
  "bs": "କାଟଲାନ୍",
  "cgg": "Chiga",
  "ckb": "Central Kurdish",
  "dav": "Taita",
  "de": "ଜର୍ମାନ୍",
  "dje": "Zarma",
  "dsb": "ନିଚଳା ସର୍ବିଆନ୍",
  "dyo": "Jola-Fonyi",
  "dz": "ଭୂଟାନୀ",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "fr": "ଫ୍ରେଞ୍ଚ",
  "fy": "ପଶ୍ଚିମ ଫ୍ରିସିୟନ୍",
  "gsw": "ସ୍ବିସ୍ ଜର୍ମାନ୍",
  "guz": "Gusii",
  "gwi": "ସ୍ବିଚ୍ ଇନ୍",
  "hu": "ହଙ୍ଗେରିଆନ୍",
  "ibb": "Ibibio",
  "id": "ଇଣ୍ଡୋନେସିଆନ୍",
  "ig": "ଇଗ୍ବୋ",
  "it": "ଇଟାଲିଆନ୍",
  "iu": "ଇନକୀଟୁତ୍",
  "ja": "ଜାପାନୀଜ୍",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "ka": "ଜର୍ଜିଆନ୍",
  "kaj": "ଜ୍ଜୁ",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "khq": "Koyra Chiini",
  "kkj": "Kako",
  "kl": "ଗ୍ରୀନଲାଣ୍ଡିକ୍",
  "kln": "Kalenjin",
  "km": "ଖ୍ମେର୍",
  "kok": "କୋନକାନୀ",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ky": "କିରଗିଜ୍",
  "lag": "Langi",
  "lkt": "Lakota",
  "lus": "ଲୁସାଉ",
  "luy": "Luyia",
  "men": "ମେଣ୍ଡେ",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mk": "ମାକଡୋନିଆନ୍",
  "mn": "ମଙ୍ଗୋଲିଆନ୍",
  "mua": "Mundang",
  "mzn": "Mazanderani",
  "naq": "Nama",
  "nmg": "Kwasio",
  "nnh": "Ngiemboon",
  "nqo": "ଏନ୍କୋ",
  "nus": "Nuer",
  "pap": "ପାପିୟାମିଣ୍ଟୋ",
  "prg": "Prussian",
  "pt": "ପର୍ତ୍ତୁଗ୍ରୀଜ୍",
  "quc": "Kʼicheʼ",
  "rm": "ରେହେଟୋ-ରୋମାନ୍ସ",
  "rof": "Rombo",
  "root": "ମୂଳ",
  "ru": "ରଷିଆନ୍",
  "rwk": "Rwa",
  "sah": "ୟାକୁଟ୍",
  "saq": "Samburu",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "seh": "Sena",
  "ses": "Koyraboro Senni",
  "shi": "Tachelhit",
  "sms": "ସ୍କୋଲ୍ଟ ସାମୀ",
  "sr": "ସର୍ବିଆନ୍",
  "ss": "ସ୍ବାତୀ",
  "ssy": "Saho",
  "swb": "Comorian",
  "teo": "Teso",
  "tn": "ସେସ୍ବାନା",
  "trv": "Taroko",
  "ts": "ସୋଂଗା",
  "twq": "Tasawaq",
  "tzm": "Central Atlas Tamazight",
  "und": "ଅଜଣା ଏବଂ ଅବୈଧ ଭାଷା",
  "vun": "Vunjo",
  "wae": "Walser",
  "xog": "Soga",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yue": "Cantonese",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "ଚାଇନୀଜ୍"
};
