const names = {
  "AD": "Andore",
  "AE": "Lemila alabu",
  "AF": "Afuganisita",
  "AG": "Antiga ne Barbuda",
  "AI": "Angiye",
  "AL": "Alubani",
  "AM": "Ameni",
  "AN": "Antiye wa Olande",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Alijantine",
  "AS": "Samoa wa Ameriki",
  "AT": "Otilisi",
  "AU": "Ositali",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Ajelbayidja",
  "BA": "Mbosini ne Hezegovine",
  "BB": "Barebade",
  "BD": "Benguladeshi",
  "BE": "Belejiki",
  "BF": "Bukinafaso",
  "BG": "Biligari",
  "BH": "Bahrene",
  "BI": "Burundi",
  "BJ": "Bene",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Brineyi",
  "BO": "Mbolivi",
  "BQ": "Caribbean Netherlands",
  "BR": "Mnulezile",
  "BS": "Bahamase",
  "BT": "Butani",
  "BV": "Bouvet Island",
  "BW": "Mbotswana",
  "BY": "Byelorisi",
  "BZ": "Belize",
  "CA": "Kanada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Ditunga wa Kongu",
  "CF": "Ditunga dya Afrika wa munkatshi",
  "CG": "Kongu",
  "CH": "Swise",
  "CI": "Kotedivuale",
  "CK": "Lutanda lua Kookɛ",
  "CL": "Shili",
  "CM": "Kamerune",
  "CN": "Shine",
  "CO": "Kolombi",
  "CR": "Kositarika",
  "CS": "Nsebi ne Montenegro",
  "CU": "Kuba",
  "CV": "Lutanda lua Kapevele",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Shipele",
  "CZ": "Ditunga dya Tsheka",
  "DE": "Alemanu",
  "DJ": "Djibuti",
  "DK": "Danemalaku",
  "DM": "Duminiku",
  "DO": "Ditunga wa Duminiku",
  "DZ": "Alijeri",
  "EC": "Ekwatele",
  "EE": "Esitoni",
  "EG": "Mushidi",
  "EH": "Western Sahara",
  "ER": "Elitele",
  "ES": "Nsipani",
  "ET": "Etshiopi",
  "FI": "Filande",
  "FJ": "Fuji",
  "FK": "Lutanda lua Maluni",
  "FM": "Mikronezi",
  "FO": "Faroe Islands",
  "FR": "Nfalanse",
  "GA": "Ngabu",
  "GB": "Angeletele",
  "GD": "Ngelenade",
  "GE": "Joriji",
  "GF": "Giyane wa Nfalanse",
  "GG": "Guernsey",
  "GH": "Ngana",
  "GI": "Jibeletale",
  "GL": "Ngowelande",
  "GM": "Gambi",
  "GN": "Ngine",
  "GP": "Ngwadelupe",
  "GQ": "Gine Ekwatele",
  "GR": "Ngeleka",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Ngwatemala",
  "GU": "Ngwame",
  "GW": "Nginebisau",
  "GY": "Ngiyane",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Ondurase",
  "HR": "Krowasi",
  "HT": "Ayiti",
  "HU": "Ongili",
  "ID": "Indonezi",
  "IE": "Irelande",
  "IL": "Isirayele",
  "IM": "Isle of Man",
  "IN": "Inde",
  "IO": "Lutanda lwa Angeletele ku mbu wa Indiya",
  "IQ": "Iraki",
  "IR": "Ira",
  "IS": "Isilande",
  "IT": "Itali",
  "JE": "Jersey",
  "JM": "Jamaiki",
  "JO": "Jodani",
  "JP": "Japu",
  "KE": "Kenya",
  "KG": "Kigizisita",
  "KH": "Kambodza",
  "KI": "Kiribati",
  "KM": "Komoru",
  "KN": "Santu krístofe ne Neves",
  "KP": "Kore wa muulu",
  "KR": "Kore wa mwinshi",
  "KW": "Koweti",
  "KY": "Lutanda lua Kayima",
  "KZ": "Kazakusita",
  "LA": "Lawosi",
  "LB": "Liba",
  "LC": "Santu lisi",
  "LI": "Lishuteni",
  "LK": "Sirilanka",
  "LR": "Liberiya",
  "LS": "Lesoto",
  "LT": "Litwani",
  "LU": "Likisambulu",
  "LV": "Letoni",
  "LY": "Libi",
  "MA": "Maroke",
  "MC": "Monaku",
  "MD": "Molidavi",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagasikari",
  "MH": "Lutanda lua Marishale",
  "MK": "Masedwane",
  "ML": "Mali",
  "MM": "Myamare",
  "MN": "Mongoli",
  "MO": "Macao SAR China",
  "MP": "Lutanda lua Mariane wa muulu",
  "MQ": "Martiniki",
  "MR": "Moritani",
  "MS": "Musera",
  "MT": "Malite",
  "MU": "Morise",
  "MV": "Madive",
  "MW": "Malawi",
  "MX": "Meksike",
  "MY": "Malezi",
  "MZ": "Mozambiki",
  "NA": "Namibi",
  "NC": "Kaledoni wa mumu",
  "NE": "Nijere",
  "NF": "Lutanda lua Norfok",
  "NG": "Nijerya",
  "NI": "Nikaragwa",
  "NL": "Olandɛ",
  "NO": "Noriveje",
  "NP": "Nepálɛ",
  "NR": "Nauru",
  "NU": "Nyue",
  "NZ": "Zelanda wa mumu",
  "OM": "Omane",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Polinezi wa Nfalanse",
  "PG": "Papwazi wa Nginɛ wa mumu",
  "PH": "Nfilipi",
  "PK": "Pakisita",
  "PL": "Mpoloni",
  "PM": "Santu pététo ne Mikelu",
  "PN": "Pikairni",
  "PR": "Mpotoriku",
  "PS": "Palesine",
  "PT": "Mputulugeshi",
  "PW": "Palau",
  "PY": "Palagwei",
  "QA": "Katari",
  "RE": "Lenyo",
  "RO": "Romani",
  "RS": "Serbia",
  "RU": "Risi",
  "RW": "Rwanda",
  "SA": "Alabu Nsawudi",
  "SB": "Lutanda lua Solomu",
  "SC": "Seshele",
  "SD": "Suda",
  "SE": "Suwedi",
  "SG": "Singapure",
  "SH": "Santu eleni",
  "SI": "Siloveni",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Silovaki",
  "SL": "Siera Leone",
  "SM": "Santu Marine",
  "SN": "Senegale",
  "SO": "Somali",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome ne Presipɛ",
  "SV": "Savadore",
  "SX": "Sint Maarten",
  "SY": "Siri",
  "SZ": "Swazilandi",
  "TC": "Lutanda lua Tuluki ne Kaiko",
  "TD": "Tshadi",
  "TF": "French Southern Territories",
  "TG": "Togu",
  "TH": "Tayilanda",
  "TJ": "Tazikisita",
  "TK": "Tokelau",
  "TL": "Timoru wa diboku",
  "TM": "Tukemenisita",
  "TN": "Tinizi",
  "TO": "Tonga",
  "TR": "Tuluki",
  "TT": "Tinidade ne Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwani",
  "TZ": "Tanzani",
  "UA": "Ukreni",
  "UG": "Uganda",
  "UM": "U.S. Outlying Islands",
  "US": "Ameriki",
  "UY": "Irigwei",
  "UZ": "Uzibekisita",
  "VA": "Nvatika",
  "VC": "Santu vesa ne Ngelenadine",
  "VE": "Venezuela",
  "VG": "Lutanda lua Vierzi wa Angeletele",
  "VI": "Lutanda lua Vierzi wa Ameriki",
  "VN": "Viyetiname",
  "VU": "Vanuatu",
  "WF": "Walise ne Futuna",
  "WS": "Samoa",
  "YE": "Yemenu",
  "YT": "Mayote",
  "ZA": "Afrika ya Súdi",
  "ZM": "Zambi",
  "ZW": "Zimbabwe",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Liakan",
  "ak_GH": "Liakan (Ngana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Liamhariki",
  "am_ET": "Liamhariki (Etshiopi)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "Arabi",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Arabi (Lemila alabu)",
  "ar_BH": "Arabi (Bahrene)",
  "ar_DJ": "Arabi (Djibuti)",
  "ar_DZ": "Arabi (Alijeri)",
  "ar_EG": "Arabi (Mushidi)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arabi (Elitele)",
  "ar_IL": "Arabi (Isirayele)",
  "ar_IQ": "Arabi (Iraki)",
  "ar_JO": "Arabi (Jodani)",
  "ar_KM": "Arabi (Komoru)",
  "ar_KW": "Arabi (Koweti)",
  "ar_LB": "Arabi (Liba)",
  "ar_LY": "Arabi (Libi)",
  "ar_MA": "Arabi (Maroke)",
  "ar_MR": "Arabi (Moritani)",
  "ar_OM": "Arabi (Omane)",
  "ar_PS": "Arabi (Palesine)",
  "ar_QA": "Arabi (Katari)",
  "ar_SA": "Arabi (Alabu Nsawudi)",
  "ar_SD": "Arabi (Suda)",
  "ar_SO": "Arabi (Somali)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Arabi (Siri)",
  "ar_TD": "Arabi (Tshadi)",
  "ar_TN": "Arabi (Tinizi)",
  "ar_YE": "Arabi (Yemenu)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarusi",
  "be_BY": "Belarusi (Byelorisi)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulegari",
  "bg_BG": "Bulegari (Biligari)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bengali",
  "bn_BD": "Bengali (Benguladeshi)",
  "bn_IN": "Bengali (Inde)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "Tsheki",
  "cs_CZ": "Tsheki (Ditunga dya Tsheka)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "Lizelumani",
  "de_AT": "Lizelumani (Otilisi)",
  "de_BE": "Lizelumani (Belejiki)",
  "de_CH": "Lizelumani (Swise)",
  "de_DE": "Lizelumani (Alemanu)",
  "de_LI": "Lizelumani (Lishuteni)",
  "de_LU": "Lizelumani (Likisambulu)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Giliki",
  "el_CY": "Giliki (Shipele)",
  "el_GR": "Giliki (Ngeleka)",
  "elx": "Elamite",
  "en": "Lingelesa",
  "en_AG": "Lingelesa (Antiga ne Barbuda)",
  "en_AI": "Lingelesa (Angiye)",
  "en_AS": "Lingelesa (Samoa wa Ameriki)",
  "en_AU": "Lingelesa (Ositali)",
  "en_BB": "Lingelesa (Barebade)",
  "en_BE": "Lingelesa (Belejiki)",
  "en_BM": "Lingelesa (Bermuda)",
  "en_BS": "Lingelesa (Bahamase)",
  "en_BW": "Lingelesa (Mbotswana)",
  "en_BZ": "Lingelesa (Belize)",
  "en_CA": "Lingelesa (Kanada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Lingelesa (Lutanda lua Kookɛ)",
  "en_CM": "Lingelesa (Kamerune)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Lingelesa (Duminiku)",
  "en_ER": "Lingelesa (Elitele)",
  "en_FJ": "Lingelesa (Fuji)",
  "en_FK": "Lingelesa (Lutanda lua Maluni)",
  "en_FM": "Lingelesa (Mikronezi)",
  "en_GB": "Lingelesa (Angeletele)",
  "en_GD": "Lingelesa (Ngelenade)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Lingelesa (Ngana)",
  "en_GI": "Lingelesa (Jibeletale)",
  "en_GM": "Lingelesa (Gambi)",
  "en_GU": "Lingelesa (Ngwame)",
  "en_GY": "Lingelesa (Ngiyane)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Lingelesa (Irelande)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Lingelesa (Inde)",
  "en_IO": "Lingelesa (Lutanda lwa Angeletele ku mbu wa Indiya)",
  "en_JE": "English (Jersey)",
  "en_JM": "Lingelesa (Jamaiki)",
  "en_KE": "Lingelesa (Kenya)",
  "en_KI": "Lingelesa (Kiribati)",
  "en_KN": "Lingelesa (Santu krístofe ne Neves)",
  "en_KY": "Lingelesa (Lutanda lua Kayima)",
  "en_LC": "Lingelesa (Santu lisi)",
  "en_LR": "Lingelesa (Liberiya)",
  "en_LS": "Lingelesa (Lesoto)",
  "en_MG": "Lingelesa (Madagasikari)",
  "en_MH": "Lingelesa (Lutanda lua Marishale)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Lingelesa (Lutanda lua Mariane wa muulu)",
  "en_MS": "Lingelesa (Musera)",
  "en_MT": "Lingelesa (Malite)",
  "en_MU": "Lingelesa (Morise)",
  "en_MW": "Lingelesa (Malawi)",
  "en_MY": "Lingelesa (Malezi)",
  "en_NA": "Lingelesa (Namibi)",
  "en_NF": "Lingelesa (Lutanda lua Norfok)",
  "en_NG": "Lingelesa (Nijerya)",
  "en_NR": "Lingelesa (Nauru)",
  "en_NU": "Lingelesa (Nyue)",
  "en_NZ": "Lingelesa (Zelanda wa mumu)",
  "en_PG": "Lingelesa (Papwazi wa Nginɛ wa mumu)",
  "en_PH": "Lingelesa (Nfilipi)",
  "en_PK": "Lingelesa (Pakisita)",
  "en_PN": "Lingelesa (Pikairni)",
  "en_PR": "Lingelesa (Mpotoriku)",
  "en_PW": "Lingelesa (Palau)",
  "en_RW": "Lingelesa (Rwanda)",
  "en_SB": "Lingelesa (Lutanda lua Solomu)",
  "en_SC": "Lingelesa (Seshele)",
  "en_SD": "Lingelesa (Suda)",
  "en_SG": "Lingelesa (Singapure)",
  "en_SH": "Lingelesa (Santu eleni)",
  "en_SL": "Lingelesa (Siera Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Lingelesa (Swazilandi)",
  "en_TC": "Lingelesa (Lutanda lua Tuluki ne Kaiko)",
  "en_TK": "Lingelesa (Tokelau)",
  "en_TO": "Lingelesa (Tonga)",
  "en_TT": "Lingelesa (Tinidade ne Tobago)",
  "en_TV": "Lingelesa (Tuvalu)",
  "en_TZ": "Lingelesa (Tanzani)",
  "en_UG": "Lingelesa (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Lingelesa (Ameriki)",
  "en_VC": "Lingelesa (Santu vesa ne Ngelenadine)",
  "en_VG": "Lingelesa (Lutanda lua Vierzi wa Angeletele)",
  "en_VI": "Lingelesa (Lutanda lua Vierzi wa Ameriki)",
  "en_VU": "Lingelesa (Vanuatu)",
  "en_WS": "Lingelesa (Samoa)",
  "en_ZA": "Lingelesa (Afrika ya Súdi)",
  "en_ZM": "Lingelesa (Zambi)",
  "en_ZW": "Lingelesa (Zimbabwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "Lihispania",
  "es_419": "Latin American Spanish",
  "es_AR": "Lihispania (Alijantine)",
  "es_BO": "Lihispania (Mbolivi)",
  "es_CL": "Lihispania (Shili)",
  "es_CO": "Lihispania (Kolombi)",
  "es_CR": "Lihispania (Kositarika)",
  "es_CU": "Lihispania (Kuba)",
  "es_DO": "Lihispania (Ditunga wa Duminiku)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Lihispania (Ekwatele)",
  "es_ES": "Lihispania (Nsipani)",
  "es_GQ": "Lihispania (Gine Ekwatele)",
  "es_GT": "Lihispania (Ngwatemala)",
  "es_HN": "Lihispania (Ondurase)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Lihispania (Meksike)",
  "es_NI": "Lihispania (Nikaragwa)",
  "es_PA": "Lihispania (Panama)",
  "es_PE": "Lihispania (Peru)",
  "es_PH": "Lihispania (Nfilipi)",
  "es_PR": "Lihispania (Mpotoriku)",
  "es_PY": "Lihispania (Palagwei)",
  "es_SV": "Lihispania (Savadore)",
  "es_US": "Lihispania (Ameriki)",
  "es_UY": "Lihispania (Irigwei)",
  "es_VE": "Lihispania (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Mpepajemi",
  "fa_AF": "Mpepajemi (Afuganisita)",
  "fa_IR": "Mpepajemi (Ira)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Mfwàlànsa",
  "fr_BE": "Mfwàlànsa (Belejiki)",
  "fr_BF": "Mfwàlànsa (Bukinafaso)",
  "fr_BI": "Mfwàlànsa (Burundi)",
  "fr_BJ": "Mfwàlànsa (Bene)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Mfwàlànsa (Kanada)",
  "fr_CD": "Mfwàlànsa (Ditunga wa Kongu)",
  "fr_CF": "Mfwàlànsa (Ditunga dya Afrika wa munkatshi)",
  "fr_CG": "Mfwàlànsa (Kongu)",
  "fr_CH": "Mfwàlànsa (Swise)",
  "fr_CI": "Mfwàlànsa (Kotedivuale)",
  "fr_CM": "Mfwàlànsa (Kamerune)",
  "fr_DJ": "Mfwàlànsa (Djibuti)",
  "fr_DZ": "Mfwàlànsa (Alijeri)",
  "fr_FR": "Mfwàlànsa (Nfalanse)",
  "fr_GA": "Mfwàlànsa (Ngabu)",
  "fr_GF": "Mfwàlànsa (Giyane wa Nfalanse)",
  "fr_GN": "Mfwàlànsa (Ngine)",
  "fr_GP": "Mfwàlànsa (Ngwadelupe)",
  "fr_GQ": "Mfwàlànsa (Gine Ekwatele)",
  "fr_HT": "Mfwàlànsa (Ayiti)",
  "fr_KM": "Mfwàlànsa (Komoru)",
  "fr_LU": "Mfwàlànsa (Likisambulu)",
  "fr_MA": "Mfwàlànsa (Maroke)",
  "fr_MC": "Mfwàlànsa (Monaku)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Mfwàlànsa (Madagasikari)",
  "fr_ML": "Mfwàlànsa (Mali)",
  "fr_MQ": "Mfwàlànsa (Martiniki)",
  "fr_MR": "Mfwàlànsa (Moritani)",
  "fr_MU": "Mfwàlànsa (Morise)",
  "fr_NC": "Mfwàlànsa (Kaledoni wa mumu)",
  "fr_NE": "Mfwàlànsa (Nijere)",
  "fr_PF": "Mfwàlànsa (Polinezi wa Nfalanse)",
  "fr_PM": "Mfwàlànsa (Santu pététo ne Mikelu)",
  "fr_RE": "Mfwàlànsa (Lenyo)",
  "fr_RW": "Mfwàlànsa (Rwanda)",
  "fr_SC": "Mfwàlànsa (Seshele)",
  "fr_SN": "Mfwàlànsa (Senegale)",
  "fr_SY": "Mfwàlànsa (Siri)",
  "fr_TD": "Mfwàlànsa (Tshadi)",
  "fr_TG": "Mfwàlànsa (Togu)",
  "fr_TN": "Mfwàlànsa (Tinizi)",
  "fr_VU": "Mfwàlànsa (Vanuatu)",
  "fr_WF": "Mfwàlànsa (Walise ne Futuna)",
  "fr_YT": "Mfwàlànsa (Mayote)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ngana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Nijere)",
  "ha_NG": "Hausa (Nijerya)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (Inde)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "Hongili",
  "hu_HU": "Hongili (Ongili)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Lindonezia",
  "id_ID": "Lindonezia (Indonezi)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nijerya)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "Litali",
  "it_CH": "Litali (Swise)",
  "it_IT": "Litali (Itali)",
  "it_SM": "Litali (Santu Marine)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Liyapani",
  "ja_JP": "Liyapani (Japu)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Java",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodia)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Likoreya",
  "ko_KP": "Likoreya (Kore wa muulu)",
  "ko_KR": "Likoreya (Kore wa mwinshi)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Tshiluba",
  "lu_CD": "Tshiluba (Ditunga wa Kongu)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Limalezia",
  "ms_BN": "Limalezia (Brineyi)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Limalezia (Malezi)",
  "ms_SG": "Limalezia (Singapure)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Burmese",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "nepali",
  "ne_IN": "nepali (Inde)",
  "ne_NP": "nepali (Nepálɛ)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "olandi",
  "nl_AW": "olandi (Aruba)",
  "nl_BE": "olandi (Belejiki)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "olandi (Olandɛ)",
  "nl_SR": "olandi (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "Lipunjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Lipunjabi (Inde)",
  "pa_PK": "Lipunjabi (Pakisita)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Mpoloni",
  "pl_PL": "Mpoloni (Mpoloni)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Mputulugɛsi",
  "pt_AO": "Mputulugɛsi (Angola)",
  "pt_BR": "Mputulugɛsi (Mnulezile)",
  "pt_CV": "Mputulugɛsi (Lutanda lua Kapevele)",
  "pt_GW": "Mputulugɛsi (Nginebisau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Mputulugɛsi (Mozambiki)",
  "pt_PT": "Mputulugɛsi (Mputulugeshi)",
  "pt_ST": "Mputulugɛsi (Sao Tome ne Presipɛ)",
  "pt_TL": "Mputulugɛsi (Timoru wa diboku)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Liromani",
  "ro_MD": "Liromani (Molidavi)",
  "ro_RO": "Liromani (Romani)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Lirisi",
  "ru_BY": "Lirisi (Byelorisi)",
  "ru_KG": "Lirisi (Kigizisita)",
  "ru_KZ": "Lirisi (Kazakusita)",
  "ru_MD": "Lirisi (Molidavi)",
  "ru_RU": "Lirisi (Risi)",
  "ru_UA": "Lirisi (Ukreni)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Lisomali",
  "so_DJ": "Lisomali (Djibuti)",
  "so_ET": "Lisomali (Etshiopi)",
  "so_KE": "Lisomali (Kenya)",
  "so_SO": "Lisomali (Somali)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Lisuwidi",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Lisuwidi (Filande)",
  "sv_SE": "Lisuwidi (Suwedi)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Mtamuili",
  "ta_IN": "Mtamuili (Inde)",
  "ta_LK": "Mtamuili (Sirilanka)",
  "ta_MY": "Mtamuili (Malezi)",
  "ta_SG": "Mtamuili (Singapure)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "Ntailandi",
  "th_TH": "Ntailandi (Tayilanda)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Ntuluki",
  "tr_CY": "Ntuluki (Shipele)",
  "tr_TR": "Ntuluki (Tuluki)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "Nkrani",
  "uk_UA": "Nkrani (Ukreni)",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "Urdu",
  "ur_IN": "Urdu (Inde)",
  "ur_PK": "Urdu (Pakisita)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Liviyetinamu",
  "vi_VN": "Liviyetinamu (Viyetiname)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Nyoruba",
  "yo_BJ": "Nyoruba (Bene)",
  "yo_NG": "Nyoruba (Nijerya)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "shinɛ",
  "zh_CN": "shinɛ (Shine)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "shinɛ (Singapure)",
  "zh_TW": "shinɛ (Taiwani)",
  "zu": "Nzulu",
  "zu_ZA": "Nzulu (Afrika ya Súdi)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
