const names = {
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "af": "Afrikaans",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "am": "Amharic",
  "an": "Aragonese",
  "anp": "Angika",
  "ar_001": "Modern Standard Arabic",
  "arn": "Mapuche",
  "arp": "Arapaho",
  "as": "Assamese",
  "asa": "Asu",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "ba": "Bashkir",
  "ban": "Balinese",
  "bas": "Basaa",
  "be": "Belarusian",
  "bem": "Bemba",
  "bez": "Bena",
  "bg": "Bulgarian",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bm": "Bambara",
  "bn": "Bengali",
  "bo": "Tibetan",
  "br": "Breton",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bug": "Buginese",
  "byn": "Blin",
  "ca": "Catalan",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cs": "Czech",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "da": "Danish",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "dgr": "Dogrib",
  "dje": "Zarma",
  "dsb": "Lower Sorbian",
  "dua": "Duala",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dz": "Dzongkha",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "efi": "Efik",
  "eka": "Ekajuk",
  "en": "انګلیسي",
  "en_AU": "English (Australia)",
  "en_US": "English (United States)",
  "eo": "Esperanto",
  "es": "Spanish",
  "es_419": "Latin American Spanish",
  "es_ES": "Spanish (Spain)",
  "es_MX": "Spanish (Mexico)",
  "eu": "Basque",
  "ewo": "Ewondo",
  "ff": "Fulah",
  "fil": "Filipino",
  "fj": "Fijian",
  "fo": "Faroese",
  "fon": "Fon",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "ga": "Irish",
  "gd": "Scottish Gaelic",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gn": "Guarani",
  "gor": "Gorontalo",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "guz": "Gusii",
  "gv": "Manx",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "haw": "Hawaiian",
  "he": "عبري",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hr": "Croatian",
  "hsb": "Upper Sorbian",
  "ht": "Haitian",
  "hu": "Hungarian",
  "hup": "Hupa",
  "hy": "ارمني",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indonesian",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ii": "Sichuan Yi",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "iu": "Inuktitut",
  "ja": "جاپانی",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jv": "Javanese",
  "ka": "Georgian",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "kfo": "Koro",
  "kha": "Khasi",
  "khq": "Koyra Chiini",
  "ki": "Kikuyu",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kln": "Kalenjin",
  "km": "Khmer",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "ko": "Korean",
  "kok": "Konkani",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "kum": "Kumyk",
  "kv": "Komi",
  "kw": "Cornish",
  "ky": "Kyrgyz",
  "lad": "Ladino",
  "lag": "Langi",
  "lb": "Luxembourgish",
  "lez": "Lezghian",
  "lg": "Ganda",
  "li": "Limburgish",
  "lkt": "Lakota",
  "ln": "Lingala",
  "lo": "Lao",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lu": "Luba-Katanga",
  "lua": "Luba-Lulua",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "mas": "Masai",
  "mdf": "Moksha",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "ml": "Malayalam",
  "mn": "مغولي",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mt": "Maltese",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "my": "Burmese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nd": "North Ndebele",
  "nds": "Low German",
  "ne": "Nepali",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl": "Dutch",
  "nl_BE": "Dutch (Belgium)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "nog": "Nogai",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "ny": "Nyanja",
  "nyn": "Nyankole",
  "oc": "Occitan",
  "om": "Oromo",
  "or": "Oriya",
  "os": "Ossetic",
  "pa": "Punjabi",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "prg": "Prussian",
  "pt_BR": "Portuguese (Brazil)",
  "pt_PT": "پورتګالي (پورتګال)",
  "qu": "Quechua",
  "quc": "Kʼicheʼ",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "Romansh",
  "rn": "Rundi",
  "ro": "Romanian",
  "ro_MD": "Romanian (Moldova)",
  "rof": "Rombo",
  "root": "Root",
  "rup": "Aromanian",
  "rw": "Kinyarwanda",
  "rwk": "Rwa",
  "sad": "Sandawe",
  "sah": "Sakha",
  "saq": "Samburu",
  "sat": "Santali",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "se": "Northern Sami",
  "seh": "Sena",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sh": "Serbo-Croatian",
  "shi": "Tachelhit",
  "shn": "Shan",
  "si": "Sinhala",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "snk": "Soninke",
  "so": "Somali",
  "sq": "Albanian",
  "sr": "Serbian",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sw": "Swahili",
  "swb": "Comorian",
  "syr": "Syriac",
  "ta": "Tamil",
  "te": "Telugu",
  "tem": "Timne",
  "teo": "Teso",
  "tet": "Tetum",
  "tg": "تاجک",
  "th": "Thai",
  "ti": "Tigrinya",
  "tig": "Tigre",
  "tlh": "Klingon",
  "tn": "Tswana",
  "to": "Tongan",
  "tpi": "Tok Pisin",
  "tr": "Turkish",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "uk": "Ukrainian",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "Urdu",
  "uz": "ازبکي",
  "vai": "Vai",
  "ve": "Venda",
  "vi": "Vietnamese",
  "vo": "Volapük",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wo": "Wolof",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xog": "Soga",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yue": "Cantonese",
  "zgh": "Standard Moroccan Tamazight",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hant": "Chinese (Traditional)",
  "zu": "Zulu",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
