const names = {
  "akk": "अक्कादिआन",
  "arp": "अराफाओ",
  "arw": "अरावक",
  "ban": "बालिनीस",
  "ce": "चेचन",
  "chg": "छगाताई",
  "ckb": "सोरानी कुर्दिश",
  "dak": "दाकोता",
  "del": "डेलॅवेयर",
  "din": "दिन्का",
  "dzg": "Dazaga",
  "frc": "Cajun French",
  "gaa": "Ga",
  "gan": "Gan Chinese",
  "hak": "Hakka Chinese",
  "hsn": "Xiang Chinese",
  "ibb": "Ibibio",
  "iu": "इनुकिटुट्",
  "kkj": "Kako",
  "ksh": "Colognian",
  "lus": "लुशाई",
  "mul": "एकविध भाषा",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nnh": "Ngiemboon",
  "prg": "Prussian",
  "sah": "याकूत",
  "sba": "Ngambay",
  "ssy": "Saho",
  "trv": "Taroko",
  "wae": "Walser",
  "wal": "वलामो",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "yav": "Yangben",
  "ybb": "Yemba"
};
