const names = {
  "001": "xexeme",
  "002": "Afrika nutome",
  "003": "Dziehe Amerika nutome",
  "005": "Anyiehe Amerika nutome",
  "009": "Oceania nutome",
  "011": "Ɣetoɖoƒelɔƒo Afrika nutome",
  "013": "Titina Amerika nutome",
  "014": "Ɣedzeƒe Afrika nutome",
  "015": "Dziehe Afrika nutome",
  "017": "Titina Afrika nutome",
  "018": "Anyiehelɔƒo Afrika nutome",
  "019": "Amerika nutome",
  "021": "Dziehelɔƒo Amerika nutome",
  "029": "Karibbea nutome",
  "030": "Ɣedzeƒe Asia nutome",
  "034": "Anyiehelɔƒo Asia nutome",
  "035": "Anyiehe Ɣedzeƒe Afrika nutome",
  "039": "Anyiehelɔƒo Europa nutome",
  "053": "Australia kple New Zealand nutome",
  "054": "Melanesia nutome",
  "057": "Mikronesia",
  "061": "Pɔlinesia nutome",
  "062": "Lõuna-Kesk-Aasia",
  "142": "Asia nutome",
  "143": "Titina Asia nutome",
  "145": "Ɣetoɖoƒelɔƒo Asia nutome",
  "150": "Europa nutome",
  "151": "Ɣedzeƒe Europa nutome",
  "154": "Dziehelɔƒo Europa nutome",
  "155": "Ɣetoɖoƒelɔƒo Europa nutome",
  "172": "Sõltumatute Riikide Ühendus",
  "200": "Tšehhoslovakkia",
  "202": "Sahara-tagune Aafrika",
  "419": "Latin Amerika nutome",
  "830": "Kanalisaared",
  "AC": "Ascension ƒudomekpo nutome",
  "AD": "Andorra nutome",
  "AE": "United Arab Emirates nutome",
  "AF": "Afghanistan nutome",
  "AG": "́Antigua kple Barbuda nutome",
  "AI": "Anguilla nutome",
  "AL": "Albania nutome",
  "AM": "Armenia nutome",
  "AN": "Nedalands Antilis nutome",
  "AO": "Angola nutome",
  "AQ": "Antartica nutome",
  "AR": "Argentina nutome",
  "AS": "Amerika Samoa nutome",
  "AT": "Austria nutome",
  "AU": "Australia nutome",
  "AW": "Aruba nutome",
  "AX": "Åland ƒudomekpo nutome",
  "AZ": "Azerbaijan nutome",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Kaukaasia albaanlane",
  "Ahom": "Ahom",
  "Arab": "Arabiagbeŋɔŋlɔ",
  "Aran": "Nastaliq",
  "Armi": "aramia gbeŋɔŋlɔ",
  "Armn": "armeniagbeŋɔŋlɔ",
  "Avst": "avesta gbeŋɔŋlɔ",
  "BA": "Bosnia kple Herzergovina nutome",
  "BB": "Barbados nutome",
  "BD": "Bangladesh nutome",
  "BE": "Belgium nutome",
  "BF": "Burkina Faso nutome",
  "BG": "Bulgaria nutome",
  "BH": "Bahrain nutome",
  "BI": "Burundi nutome",
  "BJ": "Benin nutome",
  "BL": "Saint Barthélemy nutome",
  "BM": "Bermuda nutome",
  "BN": "Brunei nutome",
  "BO": "Bolivia nutome",
  "BQ": "Karibbeatɔwo ƒe Nedalanɖs nutome",
  "BR": "Brazil nutome",
  "BS": "Bahamas nutome",
  "BT": "Bhutan nutome",
  "BV": "Bouvet ƒudomekpo nutome",
  "BW": "Botswana nutome",
  "BY": "Belarus nutome",
  "BZ": "Belize nutome",
  "Bali": "balini gbeŋɔŋlɔ",
  "Bamu": "bamum gbeŋɔŋlɔ",
  "Bass": "Bassa Vah",
  "Batk": "batak gbeŋɔŋlɔ",
  "Beng": "bengaligbeŋɔŋlɔ",
  "Bhks": "Bhaiksuki",
  "Blis": "bliss ŋɔŋlɔdzesi",
  "Bopo": "bopomfogbeŋɔŋlɔ",
  "Brah": "brami gbeŋɔŋlɔ",
  "Brai": "braillegbeŋɔŋlɔ",
  "Bugi": "Lollakas",
  "Buhd": "buhid gbeŋɔŋlɔ",
  "CA": "Canada nutome",
  "CC": "Kokos (Kiling) fudomekpo nutome",
  "CD": "Kongo Kinshasa nutome",
  "CF": "Titina Afrika repɔblik nutome",
  "CG": "Kongo Brazzaville nutome",
  "CH": "Switzerland nutome",
  "CI": "Kote d’Ivoire nutome",
  "CK": "Kook ƒudomekpo nutome",
  "CL": "Tsile nutome",
  "CM": "Kamerun nutome",
  "CN": "Tsaina nutome",
  "CO": "Kolombia nutome",
  "CP": "Klipaton ƒudomekpo nutome",
  "CR": "Kosta Rika nutome",
  "CS": "Serbia kple Montenegro nutome",
  "CU": "Kuba nutome",
  "CV": "Kape Verde nutome",
  "CW": "Kurakao nutome",
  "CX": "Kristmas ƒudomekpo nutome",
  "CY": "Saiprus nutome",
  "CZ": "Tsɛk repɔblik nutome",
  "Cakm": "tsakma gbeŋɔŋlɔ",
  "Cans": "kanada wɔɖeka ƒe abɔridzin gbedodo",
  "Cari": "karia gbeŋɔŋlɔ",
  "Cham": "tsam gbeŋɔŋlɔ",
  "Cher": "tseroke gbeŋɔŋlɔ",
  "Chrs": "Chorasmian",
  "Cirt": "seif gbeŋɔŋlɔ",
  "Copt": "koptia gbeŋɔŋlɔ",
  "Cprt": "saipriot gbeŋɔŋlɔ",
  "Cyrl": "Cyrillicgbeŋɔŋlɔ",
  "Cyrs": "slavonia sirillia sɔleme gbeŋɔŋlɔ xoxotɔ",
  "DD": "Ida-Saksamaa",
  "DE": "Germania nutome",
  "DG": "Diego Garsia nutome",
  "DJ": "Dzibuti nutome",
  "DK": "Denmark nutome",
  "DM": "Dominika nutome",
  "DO": "Dominika repɔblik nutome",
  "DZ": "Algeria nutome",
  "Deva": "devanagarigbeŋɔŋlɔ",
  "Diak": "Sukeldub Akuru",
  "Dogr": "Dogra",
  "Dsrt": "deseret gbeŋɔŋlɔ",
  "Dupl": "Duployani lühikirjeldus",
  "EA": "Keuta and Melilla nutome",
  "EC": "Ekuadɔ nutome",
  "EE": "Estonia nutome",
  "EG": "Egypte nutome",
  "EH": "Ɣetoɖoƒe Sahara nutome",
  "ER": "Eritrea nutome",
  "ES": "Spain nutome",
  "ET": "Etiopia nutome",
  "EU": "Europa Wɔɖeka nutome",
  "EZ": "Eurotsoon",
  "Egyd": "egypte demotia gbeŋɔŋlɔ",
  "Egyh": "egypte hieratia gbeŋɔŋlɔ",
  "Egyp": "egypte hieroglif nuŋɔŋlɔ",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "ethiopiagbeŋɔŋlɔ",
  "FI": "Finland nutome",
  "FJ": "Fidzi nutome",
  "FK": "Falkland ƒudomekpowo nutome",
  "FM": "Mikronesia nutome",
  "FO": "Faroe ƒudomekpowo nutome",
  "FR": "France nutome",
  "FX": "Suurlinna-Prantsusmaa",
  "GA": "Gabɔn nutome",
  "GB": "United Kingdom nutome",
  "GD": "Grenada nutome",
  "GE": "Georgia nutome",
  "GF": "Frentsi Gayana nutome",
  "GG": "Guernse nutome",
  "GH": "Ghana nutome",
  "GI": "Gibraltar nutome",
  "GL": "Grinland nutome",
  "GM": "Gambia nutome",
  "GN": "Guini nutome",
  "GP": "Guadelupe nutome",
  "GQ": "Ekuatorial Guini nutome",
  "GR": "Greece nutome",
  "GS": "Anyiehe Georgia kple Anyiehe Sandwich ƒudomekpowo nutome",
  "GT": "Guatemala nutome",
  "GU": "Guam nutome",
  "GW": "Gini-Bisao nutome",
  "GY": "Guyanadu",
  "Geok": "dzɔdzia khutsiria gbeŋɔŋlɔ",
  "Geor": "gɔgiagbeŋɔŋlɔ",
  "Glag": "glagolitia gbeŋɔŋlɔ",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "gothia gbeŋɔŋlɔ",
  "Gran": "grantha gbeŋɔŋlɔ",
  "Grek": "grisigbeŋɔŋlɔ",
  "Gujr": "gudzaratigbeŋɔŋlɔ",
  "Guru": "gurmukhigbeŋɔŋlɔ",
  "HK": "Hɔng Kɔng SAR Tsaina nutome",
  "HM": "Heard kple Mcdonald ƒudomekpowo nutome",
  "HN": "Hondurasdu",
  "HR": "Kroatsia nutome",
  "HT": "Haiti nutome",
  "HU": "Hungari nutome",
  "Hanb": "Han koos Bopomofoga",
  "Hang": "hangulgbeŋɔŋlɔ",
  "Hani": "hangbeŋɔŋlɔ",
  "Hano": "hanuno gbeŋɔŋlɔ",
  "Hans": "Chinesegbeŋɔŋlɔ",
  "Hant": "Blema Chinesegbeŋɔŋlɔ",
  "Hatr": "Hatran",
  "Hebr": "hebrigbeŋɔŋlɔ",
  "Hira": "hiraganagbeŋɔŋlɔ",
  "Hluw": "Anatoolia hieroglüüfid",
  "Hmng": "pahawh hmong gbeŋɔŋlɔ",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "dzapan gbedodo tɔxee",
  "Hung": "hungaria gbeŋɔŋlɔ xoxotɔ",
  "IC": "Kanari ƒudomekpowo nutome",
  "ID": "Indonesia nutome",
  "IE": "Ireland nutome",
  "IL": "Israel nutome",
  "IM": "Aisle of Man nutome",
  "IN": "India nutome",
  "IO": "Britaintɔwo ƒe india ƒudome nutome",
  "IQ": "iraqdukɔ",
  "IR": "Iran nutome",
  "IS": "Aiseland nutome",
  "IT": "Italia nutome",
  "Inds": "indus gbeŋɔŋlɔ",
  "Ital": "aitalik xoxotɔ",
  "JE": "Dzɛse nutome",
  "JM": "Dzamaika nutome",
  "JO": "Yordan nutome",
  "JP": "Dzapan nutome",
  "Jamo": "Jamo",
  "Java": "dzavanese gbeŋɔŋlɔ",
  "Jpan": "Japanesegbeŋɔŋlɔ",
  "Jurc": "Jurchen",
  "KE": "Kenya nutome",
  "KG": "Kirgizstan nutome",
  "KH": "Kambodia nutome",
  "KI": "Kiribati nutome",
  "KM": "Komoros nutome",
  "KN": "Saint Kitis kple Nevis nutome",
  "KP": "Dziehe Korea nutome",
  "KR": "Anyiehe Korea nutome",
  "KW": "Kuwait nutome",
  "KY": "Kayman ƒudomekpowo nutome",
  "KZ": "Kazakstan nutome",
  "Kali": "kayah li gbeŋɔŋlɔ",
  "Kana": "katakanagbeŋɔŋlɔ",
  "Khar": "kharoshthi gbeŋɔŋlɔ",
  "Khmr": "khmergbeŋɔŋlɔ",
  "Khoj": "khodziki gbeŋɔŋlɔ",
  "Kits": "Khitani väike stsenaarium",
  "Knda": "kannadagbeŋɔŋlɔ",
  "Kore": "Koreagbeŋɔŋlɔ",
  "Kpel": "Kpelle",
  "Kthi": "kaithi gbeŋɔŋlɔ",
  "LA": "Laos nutome",
  "LB": "Lebanɔn nutome",
  "LC": "Saint Lusia nutome",
  "LI": "Litsenstein nutome",
  "LK": "Sri Lanka nutome",
  "LR": "Liberia nutome",
  "LS": "Lɛsoto nutome",
  "LT": "Lituania nutome",
  "LU": "Lazembɔg nutome",
  "LV": "Latvia nutome",
  "LY": "Libya nutome",
  "Lana": "lanna gbeŋɔŋlɔ",
  "Laoo": "laogbeŋɔŋlɔ",
  "Latf": "fraktur latin gbeŋɔŋlɔ",
  "Latg": "gaelia latin gbeŋɔŋlɔ",
  "Latn": "Latingbeŋɔŋlɔ",
  "Lepc": "leptsa gbeŋɔŋlɔ",
  "Limb": "limbu gbeŋɔŋlɔ",
  "Lina": "linia a gbeŋɔŋlɔ",
  "Linb": "linea b gbeŋɔŋlɔ",
  "Lisu": "fraser gbeŋɔŋlɔ",
  "Loma": "Loma",
  "Lyci": "lisia gbeŋɔŋlɔ",
  "Lydi": "lidia gbeŋɔŋlɔ",
  "MA": "Moroko nutome",
  "MC": "Monako nutome",
  "MD": "Moldova nutome",
  "ME": "Montenegro nutome",
  "MF": "Saint Martin nutome",
  "MG": "Madagaska nutome",
  "MH": "Marshal ƒudomekpowo nutome",
  "MI": "Midway saared",
  "MK": "Makedonia nutome",
  "ML": "Mali nutome",
  "MM": "Myanmar (Burma) nutome",
  "MN": "Mongolia nutome",
  "MO": "Macau SAR Tsaina nutome",
  "MP": "Dziehe Marina ƒudomekpowo nutome",
  "MQ": "Martiniki nutome",
  "MR": "Mauritania nutome",
  "MS": "Montserrat nutome",
  "MT": "Malta nutome",
  "MU": "mauritiusdukɔ",
  "MV": "maldivesdukɔ",
  "MW": "Malawi nutome",
  "MX": "Mexico nutome",
  "MY": "Malaysia nutome",
  "MZ": "Mozambiki nutome",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "mandae gbeŋɔŋlɔ",
  "Mani": "manitsia gbeŋɔŋlɔ",
  "Marc": "Marchen",
  "Maya": "mayan hieroglif gbeŋɔŋlɔ",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "meroitia atsyia gbeŋɔŋlɔ",
  "Mero": "meroitia gbeŋɔŋlɔ",
  "Mlym": "malayagbeŋɔŋlɔ",
  "Modi": "Modi",
  "Mong": "mongoliagbeŋɔŋlɔ",
  "Moon": "moon gbeŋɔŋlɔ",
  "Mroo": "Mro",
  "Mtei": "meitei mayek gbeŋɔŋlɔ",
  "Mult": "Multani",
  "Mymr": "myanmargbeŋɔŋlɔ",
  "NA": "Namibia nutome",
  "NC": "New Kaledonia nutome",
  "NE": "Niger nutome",
  "NF": "Norfolk ƒudomekpo nutome",
  "NG": "Nigeria nutome",
  "NI": "Nicaraguadukɔ",
  "NL": "Netherlands nutome",
  "NO": "Norway nutome",
  "NP": "Nepal nutome",
  "NR": "Nauru nutome",
  "NT": "Neutraalne tsoon",
  "NU": "Niue nutome",
  "NZ": "New Zealand nutome",
  "Nand": "Nandinagari",
  "Narb": "Vana Põhja-Araabia keel",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "naxi geba gbeŋɔŋlɔ",
  "Nkoo": "n’ko gbeŋɔŋlɔ",
  "Nshu": "Nüshu",
  "OM": "Oman nutome",
  "Ogam": "ogham gbeŋɔŋlɔ",
  "Olck": "ol tsiki gbeŋɔŋlɔ",
  "Orkh": "orkhon gbeŋɔŋlɔ",
  "Orya": "oriyagbeŋɔŋlɔ",
  "Osge": "Osage",
  "Osma": "osmaya gbeŋɔŋlɔ",
  "PA": "Panama nutome",
  "PC": "Vaikse ookeani saarte usalduspiirkond",
  "PE": "Peru nutome",
  "PF": "Frentsi Pɔlinesia nutome",
  "PG": "Papua New Gini nutome",
  "PH": "Filipini nutome",
  "PK": "Pakistan nutome",
  "PL": "Poland nutome",
  "PM": "Saint Pierre kple Mikelɔn nutome",
  "PN": "Pitkairn ƒudomekpo nutome",
  "PR": "Puerto Riko nutome",
  "PS": "Palestinia nutome",
  "PT": "Portugal nutome",
  "PU": "USA mitmesugused Vaikse ookeani saared",
  "PW": "Palau nutome",
  "PY": "Paragua nutome",
  "PZ": "Panama kanali tsoon",
  "Palm": "Palmüreen",
  "Pauc": "Pau Cin Hau",
  "Perm": "permia gbeŋɔŋlɔ xoxotɔ",
  "Phag": "phags-pa gbeŋɔŋlɔ",
  "Phli": "pahlavi gbeŋɔŋlɔ tɔxee",
  "Phlp": "psamta pahlavi gbeŋɔŋlɔ",
  "Phlv": "agbaleme pahlavi gbeŋɔŋlɔ",
  "Phnx": "foenesia gbeŋɔŋlɔ",
  "Plrd": "pollard gbegbɔgblɔ",
  "Prti": "parthia gbeŋɔŋlɔ tɔxee",
  "QA": "Katar nutome",
  "QO": "Outlaying Oceania nutome",
  "Qaag": "Zawgyi",
  "RE": "Réunion nutome",
  "RO": "Romania nutome",
  "RS": "Serbia nutome",
  "RU": "Russia nutome",
  "RW": "Rwanda nutome",
  "Rjng": "redza gbeŋɔŋlɔ",
  "Rohg": "Hanifi Rohingya",
  "Roro": "rongorongo gbeŋɔŋlɔ",
  "Runr": "runia gbeŋɔŋlɔ",
  "SA": "Saudi Arabia nutome",
  "SB": "Solomon ƒudomekpowo nutome",
  "SC": "Seshɛls nutome",
  "SD": "Sudan nutome",
  "SE": "Sweden nutome",
  "SG": "Singapɔr nutome",
  "SH": "Saint Helena nutome",
  "SI": "Slovenia nutome",
  "SJ": "Svalbard kple Yan Mayen nutome",
  "SK": "Slovakia nutome",
  "SL": "Sierra Leone nutome",
  "SM": "San Marino nutome",
  "SN": "Senegal nutome",
  "SO": "Somalia nutome",
  "SR": "Suriname nutome",
  "SS": "Anyiehe Sudan nutome",
  "ST": "São Tomé kple Príncipe nutome",
  "SU": "Nõukogude Sotsialistlike Vabariikide Liit",
  "SV": "El Salvadɔ nutome",
  "SX": "Sint Maarten nutome",
  "SY": "Siria nutome",
  "SZ": "Swaziland nutome",
  "Samr": "samaria gbeŋɔŋlɔ",
  "Sara": "sarati gbeŋɔŋlɔ",
  "Sarb": "anyiehe arabia gbeŋɔŋlɔ xoxotɔ",
  "Saur": "saurashtra gbeŋɔŋlɔ",
  "Sgnw": "atsyia nuŋɔŋlɔ",
  "Shaw": "tsavia gbeŋɔŋlɔ",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "sinhalagbeŋɔŋlɔ",
  "Sogd": "Sogdian",
  "Sogo": "Vana sogdi keel",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "sundana gbeŋɔŋlɔ",
  "Sylo": "sailoti nagri gbeŋɔŋlɔ",
  "Syrc": "siriak gbeŋɔŋlɔ",
  "Syre": "estrangelo siria gbeŋɔŋlɔ",
  "Syrj": "ɣetoɖoƒe siria gbeŋɔŋlɔ",
  "Syrn": "ɣedzeƒe siria gbeŋɔŋlɔ",
  "TA": "Tristan da Kunha nutome",
  "TC": "Tɛks kple Kaikos ƒudomekpowo nutome",
  "TD": "Tsad nutome",
  "TF": "Anyiehe Franseme nutome",
  "TG": "Togo nutome",
  "TH": "Thailand nutome",
  "TJ": "Tajikistan nutome",
  "TK": "Tokelau nutome",
  "TL": "Timor-Leste nutome",
  "TM": "Tɛkmenistan nutome",
  "TN": "Tunisia nutome",
  "TO": "Tonga nutome",
  "TR": "Tɛki nutome",
  "TT": "Trinidad kple Tobago nutome",
  "TV": "Tuvalu nutome",
  "TW": "Taiwan nutome",
  "TZ": "Tanzania nutome",
  "Tagb": "tagbanwa gbeŋɔŋlɔ",
  "Takr": "Takri",
  "Tale": "tai le gbeŋɔŋlɔ",
  "Talu": "tail lue gbeŋɔŋlɔ yeye",
  "Taml": "tamilgbeŋɔŋlɔ",
  "Tang": "Tangut",
  "Tavt": "tai viet gbeŋɔŋlɔ",
  "Telu": "telegugbeŋɔŋlɔ",
  "Teng": "tengwar gbeŋɔŋlɔ",
  "Tfng": "tifinagh gbeŋɔŋlɔ",
  "Tglg": "tagalog gbeŋɔŋlɔ",
  "Thaa": "thaanagbeŋɔŋlɔ",
  "Thai": "taigbeŋɔŋlɔ",
  "Tibt": "tibetgbeŋɔŋlɔ",
  "Tirh": "tirhuta gbeŋɔŋlɔ",
  "UA": "Ukraine nutome",
  "UG": "Uganda nutome",
  "UM": "U.S. Minor Outlaying ƒudomekpowo nutome",
  "UN": "Ühendrahvad",
  "US": "USA nutome",
  "UY": "uruguaydukɔ",
  "UZ": "Uzbekistan nutome",
  "Ugar": "ugaritia gbeŋɔŋlɔ",
  "VA": "Vatikandu nutome",
  "VC": "Saint Vincent kple Grenadine nutome",
  "VD": "Põhja-Vietnam",
  "VE": "Venezuela nutome",
  "VG": "Britaintɔwo ƒe Virgin ƒudomekpowo nutome",
  "VI": "U.S. Vɛrgin ƒudomekpowo nutome",
  "VN": "Vietnam nutome",
  "VU": "Vanuatu nutome",
  "Vaii": "vai gbeŋɔŋlɔ",
  "Visp": "gbegbɔgblɔ si dzena",
  "WF": "Wallis kple Futuna nutome",
  "WK": "Ärksaar",
  "WS": "Samoa nutome",
  "Wara": "varang kshiti gbeŋɔŋlɔ",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudo-aktsendid",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "persia gbeŋɔŋlɔ xoxotɔ",
  "Xsux": "sumero-akkadia kunei gbeŋɔŋlɔ",
  "YD": "Jeemeni Demokraatlik Rahvavabariik",
  "YE": "Yemen nutome",
  "YT": "Mayotte nutome",
  "Yezi": "Jezidi",
  "Yiii": "yi gbeŋɔŋlɔ",
  "ZA": "Anyiehe Africa nutome",
  "ZM": "Zambia nutome",
  "ZW": "Zimbabwe nutome",
  "ZZ": "nutome manya",
  "Zanb": "Zanabazari väljak",
  "Zinh": "gbeŋɔŋlɔ si wo dzɔ va tu",
  "Zmth": "akɔnta nuŋɔŋlɔ",
  "Zsye": "Emotikonid",
  "Zsym": "ŋɔŋlɔdzesiwo",
  "Zxxx": "gbemaŋlɔ",
  "Zyyy": "gbeŋɔŋlɔ bɔbɔ",
  "Zzzz": "gbeŋɔŋlɔ manya",
  "aa": "Afar",
  "ab": "abkhaziagbe",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "adyghegbe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "afrikaangbe",
  "af_NA": "afrikaangbe (Namibia nutome)",
  "af_ZA": "afrikaangbe (Anyiehe Afrika nutome)",
  "afa": "Afroasiaasia keel",
  "afh": "Afrihili",
  "agq": "aghemgbe",
  "ain": "Ainu",
  "ak": "blugbe",
  "ak_GH": "blugbe (Ghana nutome)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Algonkia keel",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "amhariagbe",
  "am_ET": "amhariagbe (Etiopia nutome)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "apa": "Apache keel",
  "ar": "Arabiagbe",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "arabiagbe (United Arab Emirates nutome)",
  "ar_BH": "arabiagbe (Bahrain nutome)",
  "ar_DJ": "arabiagbe (Dzibuti nutome)",
  "ar_DZ": "arabiagbe (Algeria nutome)",
  "ar_EG": "arabiagbe (Egypte nutome)",
  "ar_EH": "arabiagbe (Ɣetoɖoƒe Sahara nutome)",
  "ar_ER": "arabiagbe (Eritrea nutome)",
  "ar_IL": "arabiagbe (Israel nutome)",
  "ar_IQ": "arabiagbe (iraqdukɔ)",
  "ar_JO": "arabiagbe (Yordan nutome)",
  "ar_KM": "arabiagbe (Komoros nutome)",
  "ar_KW": "arabiagbe (Kuwait nutome)",
  "ar_LB": "arabiagbe (Lebanɔn nutome)",
  "ar_LY": "arabiagbe (Libya nutome)",
  "ar_MA": "arabiagbe (Moroko nutome)",
  "ar_MR": "arabiagbe (Mauritania nutome)",
  "ar_OM": "arabiagbe (Oman nutome)",
  "ar_PS": "arabiagbe (Palestinia nutome)",
  "ar_QA": "arabiagbe (Katar nutome)",
  "ar_SA": "arabiagbe (Saudi Arabia nutome)",
  "ar_SD": "arabiagbe (Sudan nutome)",
  "ar_SO": "arabiagbe (Somalia nutome)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "arabiagbe (Siria nutome)",
  "ar_TD": "arabiagbe (Tsad nutome)",
  "ar_TN": "arabiagbe (Tunisia nutome)",
  "ar_YE": "arabiagbe (Yemen nutome)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "ars": "Najdi araabia",
  "art": "Tehiskeel",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "assamegbe",
  "as_IN": "assamegbe (India nutome)",
  "asa": "asagbe",
  "ase": "American Sign Language",
  "ast": "asturiagbe",
  "ath": "Athapascani keel",
  "aus": "Austraalia keel",
  "av": "avariagbe",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "aymargbe",
  "az": "azerbaijangbe",
  "az_AZ": "azerbaijangbe (Azerbaijan nutome)",
  "az_Arab": "Aserbaidžaani (araabia)",
  "az_Cyrl": "azerbaijangbe (syrilliagbeŋɔŋlɔ)",
  "az_Cyrl_AZ": "azerbaijangbe (syrilliagbeŋɔŋlɔ, Azerbaijan nutome)",
  "az_Latn": "azerbaijangbe (latingbeŋɔŋlɔ)",
  "az_Latn_AZ": "azerbaijangbe (latingbeŋɔŋlɔ, Azerbaijan nutome)",
  "azb": "South Azerbaijani",
  "ba": "bashkigbe",
  "bad": "Banda",
  "bai": "Bamileke keel",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "basaagbe",
  "bat": "Balti keel",
  "bax": "bamugbe",
  "bbc": "Batak Toba",
  "bbj": "ghomalagbe",
  "be": "belarusiagbe",
  "be_BY": "belarusiagbe (Belarus nutome)",
  "bej": "Beja",
  "bem": "bembagbe",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "benagbe",
  "bfd": "bafutgbe",
  "bfq": "Badaga",
  "bg": "bulgariagbe",
  "bg_BG": "bulgariagbe (Bulgaria nutome)",
  "bgn": "Lääne-Balochi",
  "bh": "Bihari",
  "bho": "Bhojpuri",
  "bi": "bislamagbe",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "komgbe",
  "bla": "Siksika",
  "bm": "bambaragbe",
  "bm_Latn": "bambaragbe (latingbeŋɔŋlɔ)",
  "bm_Latn_ML": "bambaragbe (latingbeŋɔŋlɔ, Mali nutome)",
  "bn": "Bengaligbe",
  "bn_BD": "bengalgbe (Bangladesh nutome)",
  "bn_IN": "bengalgbe (India nutome)",
  "bnt": "Bantu",
  "bo": "tibetagbe",
  "bo_CN": "tibetagbe (Tsaina nutome)",
  "bo_IN": "tibetagbe (India nutome)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretongbe",
  "br_FR": "bretongbe (Frans nutome)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "bodogbe",
  "bs": "bosniagbe",
  "bs_BA": "bosniagbe (Bosnia kple Herzergovina nutome)",
  "bs_Cyrl": "bosniagbe (syrilliagbeŋɔŋlɔ)",
  "bs_Cyrl_BA": "bosniagbe (syrilliagbeŋɔŋlɔ, Bosnia kple Herzergovina nutome)",
  "bs_Latn": "bosniagbe (latingbeŋɔŋlɔ)",
  "bs_Latn_BA": "bosniagbe (latingbeŋɔŋlɔ, Bosnia kple Herzergovina nutome)",
  "bss": "akoosiagbe",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "bulugbe",
  "byn": "Blin",
  "byv": "medumbagbe",
  "ca": "katalagbe",
  "ca_AD": "katalagbe (Andorra nutome)",
  "ca_ES": "katalagbe (Spania nutome)",
  "ca_FR": "katalagbe (Frans nutome)",
  "ca_IT": "katalagbe (Italia nutome)",
  "cad": "Caddo",
  "cai": "Kesk-Ameerika india keel",
  "car": "Carib",
  "cau": "Kaukaasia keel",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Tšakma",
  "ce": "Chechen",
  "ceb": "Sebuanogbe",
  "cel": "Keldi keel",
  "cgg": "Chiga",
  "ch": "kamorrogbe",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "tsukesegbe",
  "chm": "tsetsniagbe",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Central Kurdish",
  "cmc": "Keraamiline keel",
  "co": "Corsican",
  "cop": "Coptic",
  "cpe": "Ingliskeelne kreooli või pidgin",
  "cpf": "Prantsusmaal asuv kreool või pidgin",
  "cpp": "Portugali päritolu kreool või Pidgin",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "crp": "Kreool või pidgin",
  "crs": "Seselwa kreooli prantsuse keel",
  "cs": "tsɛkgbe",
  "cs_CZ": "tsɛkgbe (Tsɛk repɔblik nutome)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cus": "Kuši keel",
  "cv": "Chuvash",
  "cy": "walesgbe",
  "cy_GB": "walesgbe (United Kingdom nutome)",
  "da": "denmarkgbe",
  "da_DK": "denmarkgbe (Denmark nutome)",
  "da_GL": "denmarkgbe (Grinland nutome)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Germaniagbe",
  "de_AT": "Germaniagbe (Austria)",
  "de_BE": "germaniagbe (Belgium nutome)",
  "de_CH": "Germaniagbe (Switzerland)",
  "de_DE": "germaniagbe (Germania nutome)",
  "de_LI": "germaniagbe (Litsenstein nutome)",
  "de_LU": "germaniagbe (Lazembɔg nutome)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "zamagbe",
  "doi": "Dogri",
  "dra": "Draviidi keel",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "dualagbe",
  "dum": "Middle Dutch",
  "dv": "divehgbe",
  "dyo": "dzola-fonyigbe",
  "dyu": "Dyula",
  "dz": "dzongkhagbe",
  "dz_BT": "dzongkhagbe (Bhutan nutome)",
  "dzg": "Dazaga",
  "ebu": "embugbe",
  "ee": "Eʋegbe",
  "ee_GH": "eʋegbe (Ghana nutome)",
  "ee_TG": "eʋegbe (Togo nutome)",
  "efi": "efigbe",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "grisigbe",
  "el_CY": "grisigbe (Saiprus nutome)",
  "el_GR": "grisigbe (Grisi nutome)",
  "elx": "Elamite",
  "en": "Yevugbe",
  "en_AG": "yevugbe (́Antigua kple Barbuda nutome)",
  "en_AI": "yevugbe (Anguilla nutome)",
  "en_AS": "yevugbe (Amerika Samoa nutome)",
  "en_AU": "Yevugbe (Australia)",
  "en_BB": "yevugbe (Barbados nutome)",
  "en_BE": "yevugbe (Belgium nutome)",
  "en_BM": "yevugbe (Bermuda nutome)",
  "en_BS": "yevugbe (Bahamas nutome)",
  "en_BW": "yevugbe (Botswana nutome)",
  "en_BZ": "yevugbe (Belize nutome)",
  "en_CA": "Yevugbe (Canada)",
  "en_CC": "yevugbe (Kokos (Kiling) fudomekpo nutome)",
  "en_CK": "yevugbe (Kook ƒudomekpo nutome)",
  "en_CM": "yevugbe (Kamerun nutome)",
  "en_CX": "yevugbe (Kristmas ƒudomekpo nutome)",
  "en_DG": "yevugbe (Diego Garsia nutome)",
  "en_DM": "yevugbe (Dominika nutome)",
  "en_Dsrt": "Inglise (Deseret)",
  "en_ER": "yevugbe (Eritrea nutome)",
  "en_FJ": "yevugbe (Fidzi nutome)",
  "en_FK": "yevugbe (Falkland ƒudomekpowo nutome)",
  "en_FM": "yevugbe (Mikronesia nutome)",
  "en_GB": "Yevugbe (Britain)",
  "en_GD": "yevugbe (Grenada nutome)",
  "en_GG": "yevugbe (Guernse nutome)",
  "en_GH": "yevugbe (Ghana nutome)",
  "en_GI": "yevugbe (Gibraltar nutome)",
  "en_GM": "yevugbe (Gambia nutome)",
  "en_GU": "yevugbe (Guam nutome)",
  "en_GY": "yevugbe (Guyanadu)",
  "en_HK": "yevugbe (Hɔng Kɔng SAR Tsaina nutome)",
  "en_IE": "yevugbe (Ireland nutome)",
  "en_IM": "yevugbe (Aisle of Man nutome)",
  "en_IN": "yevugbe (India nutome)",
  "en_IO": "yevugbe (Britaintɔwo ƒe india ƒudome nutome)",
  "en_JE": "yevugbe (Dzɛse nutome)",
  "en_JM": "yevugbe (Dzamaika nutome)",
  "en_KE": "yevugbe (Kenya nutome)",
  "en_KI": "yevugbe (Kiribati nutome)",
  "en_KN": "yevugbe (Saint Kitis kple Nevis nutome)",
  "en_KY": "yevugbe (Kayman ƒudomekpowo nutome)",
  "en_LC": "yevugbe (Saint Lusia nutome)",
  "en_LR": "yevugbe (Liberia nutome)",
  "en_LS": "yevugbe (Lɛsoto nutome)",
  "en_MG": "yevugbe (Madagaska nutome)",
  "en_MH": "yevugbe (Marshal ƒudomekpowo nutome)",
  "en_MO": "yevugbe (Macau SAR Tsaina nutome)",
  "en_MP": "yevugbe (Dziehe Marina ƒudomekpowo nutome)",
  "en_MS": "yevugbe (Montserrat nutome)",
  "en_MT": "yevugbe (Malta nutome)",
  "en_MU": "yevugbe (mauritiusdukɔ)",
  "en_MW": "yevugbe (Malawi nutome)",
  "en_MY": "yevugbe (Malaysia nutome)",
  "en_NA": "yevugbe (Namibia nutome)",
  "en_NF": "yevugbe (Norfolk ƒudomekpo nutome)",
  "en_NG": "yevugbe (Nigeria nutome)",
  "en_NR": "yevugbe (Nauru nutome)",
  "en_NU": "yevugbe (Niue nutome)",
  "en_NZ": "yevugbe (New Zealand nutome)",
  "en_PG": "yevugbe (Papua New Gini nutome)",
  "en_PH": "yevugbe (Filipini nutome)",
  "en_PK": "yevugbe (Pakistan nutome)",
  "en_PN": "yevugbe (Pitkairn ƒudomekpo nutome)",
  "en_PR": "yevugbe (Puerto Riko nutome)",
  "en_PW": "yevugbe (Palau nutome)",
  "en_RW": "yevugbe (Rwanda nutome)",
  "en_SB": "yevugbe (Solomon ƒudomekpowo nutome)",
  "en_SC": "yevugbe (Seshɛls nutome)",
  "en_SD": "yevugbe (Sudan nutome)",
  "en_SG": "yevugbe (Singapɔr nutome)",
  "en_SH": "yevugbe (Saint Helena nutome)",
  "en_SL": "yevugbe (Sierra Leone nutome)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "yevugbe (Swaziland nutome)",
  "en_TC": "yevugbe (Tɛks kple Kaikos ƒudomekpowo nutome)",
  "en_TK": "yevugbe (Tokelau nutome)",
  "en_TO": "yevugbe (Tonga nutome)",
  "en_TT": "yevugbe (Trinidad kple Tobago nutome)",
  "en_TV": "yevugbe (Tuvalu nutome)",
  "en_TZ": "yevugbe (Tanzania nutome)",
  "en_UG": "yevugbe (Uganda nutome)",
  "en_UM": "yevugbe (U.S. Minor Outlaying ƒudomekpowo nutome)",
  "en_US": "Yevugbe (America)",
  "en_VC": "yevugbe (Saint Vincent kple Grenadine nutome)",
  "en_VG": "yevugbe (Britaintɔwo ƒe Virgin ƒudomekpowo nutome)",
  "en_VI": "yevugbe (U.S. Vɛrgin ƒudomekpowo nutome)",
  "en_VU": "yevugbe (Vanuatu nutome)",
  "en_WS": "yevugbe (Samoa nutome)",
  "en_ZA": "yevugbe (Anyiehe Afrika nutome)",
  "en_ZM": "yevugbe (Zambia nutome)",
  "en_ZW": "yevugbe (Zimbabwe nutome)",
  "enm": "Middle English",
  "eo": "esperantogbe",
  "es": "Spanishgbe",
  "es_419": "Spanishgbe (Latin America)",
  "es_AR": "spaniagbe (Argentina nutome)",
  "es_BO": "spaniagbe (Bolivia nutome)",
  "es_CL": "spaniagbe (Tsile nutome)",
  "es_CO": "spaniagbe (Kolombia nutome)",
  "es_CR": "spaniagbe (Kosta Rika nutome)",
  "es_CU": "spaniagbe (Kuba nutome)",
  "es_DO": "spaniagbe (Dominika repɔblik nutome)",
  "es_EA": "spaniagbe (Keuta and Melilla nutome)",
  "es_EC": "spaniagbe (Ekuadɔ nutome)",
  "es_ES": "Spanishgbe (Europe)",
  "es_GQ": "spaniagbe (Ekuatorial Guini nutome)",
  "es_GT": "spaniagbe (Guatemala nutome)",
  "es_HN": "spaniagbe (Hondurasdu)",
  "es_IC": "spaniagbe (Kanari ƒudomekpowo nutome)",
  "es_MX": "Spanishgbe (Mexico)",
  "es_NI": "spaniagbe (Nicaraguadukɔ)",
  "es_PA": "spaniagbe (Panama nutome)",
  "es_PE": "spaniagbe (Peru nutome)",
  "es_PH": "spaniagbe (Filipini nutome)",
  "es_PR": "spaniagbe (Puerto Riko nutome)",
  "es_PY": "spaniagbe (Paragua nutome)",
  "es_SV": "spaniagbe (El Salvadɔ nutome)",
  "es_US": "spaniagbe (USA nutome)",
  "es_UY": "spaniagbe (uruguaydukɔ)",
  "es_VE": "spaniagbe (Venezuela nutome)",
  "esu": "Central Yupik",
  "et": "estoniagbe",
  "et_EE": "estoniagbe (Estonia nutome)",
  "eu": "basqugbe",
  "eu_ES": "basqugbe (Spania nutome)",
  "ewo": "ewondogbe",
  "ext": "Extremaduran",
  "fa": "persiagbe",
  "fa_AF": "persiagbe (Afghanistan nutome)",
  "fa_IR": "persiagbe (Iran nutome)",
  "fan": "fangbe",
  "fat": "Fanti",
  "ff": "fulagbe",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "finlanɖgbe",
  "fi_FI": "finlanɖgbe (Finland nutome)",
  "fil": "filipingbe",
  "fit": "Tornedalen Finnish",
  "fiu": "Soome-ugri keel",
  "fj": "fidzigbe",
  "fo": "faroegbe",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Fransegbe",
  "fr_BE": "fransegbe (Belgium nutome)",
  "fr_BF": "fransegbe (Burkina Faso nutome)",
  "fr_BI": "fransegbe (Burundi nutome)",
  "fr_BJ": "fransegbe (Benin nutome)",
  "fr_BL": "fransegbe (Saint Barthélemy nutome)",
  "fr_CA": "Fransegbe (Canada)",
  "fr_CD": "fransegbe (Kongo Kinshasa nutome)",
  "fr_CF": "fransegbe (Titina Afrika repɔblik nutome)",
  "fr_CG": "fransegbe (Kongo Brazzaville nutome)",
  "fr_CH": "Fransegbe (Switzerland)",
  "fr_CI": "fransegbe (Kote d’Ivoire nutome)",
  "fr_CM": "fransegbe (Kamerun nutome)",
  "fr_DJ": "fransegbe (Dzibuti nutome)",
  "fr_DZ": "fransegbe (Algeria nutome)",
  "fr_FR": "fransegbe (Frans nutome)",
  "fr_GA": "fransegbe (Gabɔn nutome)",
  "fr_GF": "fransegbe (Frentsi Gayana nutome)",
  "fr_GN": "fransegbe (Guini nutome)",
  "fr_GP": "fransegbe (Guadelupe nutome)",
  "fr_GQ": "fransegbe (Ekuatorial Guini nutome)",
  "fr_HT": "fransegbe (Haiti nutome)",
  "fr_KM": "fransegbe (Komoros nutome)",
  "fr_LU": "fransegbe (Lazembɔg nutome)",
  "fr_MA": "fransegbe (Moroko nutome)",
  "fr_MC": "fransegbe (Monako nutome)",
  "fr_MF": "fransegbe (Saint Martin nutome)",
  "fr_MG": "fransegbe (Madagaska nutome)",
  "fr_ML": "fransegbe (Mali nutome)",
  "fr_MQ": "fransegbe (Martiniki nutome)",
  "fr_MR": "fransegbe (Mauritania nutome)",
  "fr_MU": "fransegbe (mauritiusdukɔ)",
  "fr_NC": "fransegbe (New Kaledonia nutome)",
  "fr_NE": "fransegbe (Niger nutome)",
  "fr_PF": "fransegbe (Frentsi Pɔlinesia nutome)",
  "fr_PM": "fransegbe (Saint Pierre kple Mikelɔn nutome)",
  "fr_RE": "fransegbe (Réunion nutome)",
  "fr_RW": "fransegbe (Rwanda nutome)",
  "fr_SC": "fransegbe (Seshɛls nutome)",
  "fr_SN": "fransegbe (Senegal nutome)",
  "fr_SY": "fransegbe (Siria nutome)",
  "fr_TD": "fransegbe (Tsad nutome)",
  "fr_TG": "fransegbe (Togo nutome)",
  "fr_TN": "fransegbe (Tunisia nutome)",
  "fr_VU": "fransegbe (Vanuatu nutome)",
  "fr_WF": "fransegbe (Wallis kple Futuna nutome)",
  "fr_YT": "fransegbe (Mayotte nutome)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "ɣetoɖoƒe frisiagbe",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "irelanɖgbe",
  "ga_IE": "irelanɖgbe (Ireland nutome)",
  "gaa": "gɛgbe",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "skɔtlanɖ gaeliagbe",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gem": "Germaani keel",
  "gez": "Geez",
  "gil": "gilbertgbe",
  "gl": "galatagbe",
  "gl_ES": "galatagbe (Spania nutome)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "guarangbe",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "swizerlanɖtɔwo ƒe germaniagbe",
  "gu": "gujarati",
  "gu_IN": "gujarati (India nutome)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "hausagbe",
  "ha_GH": "hausagbe (Ghana nutome)",
  "ha_Latn": "hausagbe (latingbeŋɔŋlɔ)",
  "ha_Latn_GH": "hausagbe (latingbeŋɔŋlɔ, Ghana nutome)",
  "ha_Latn_NE": "hausagbe (latingbeŋɔŋlɔ, Niger nutome)",
  "ha_Latn_NG": "hausagbe (latingbeŋɔŋlɔ, Nigeria nutome)",
  "ha_NE": "hausagbe (Niger nutome)",
  "ha_NG": "hausagbe (Nigeria nutome)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "hawaigbe",
  "he": "hebrigbe",
  "he_IL": "hebrigbe (Israel nutome)",
  "hi": "Hindigbe",
  "hi_IN": "hindigbe (India nutome)",
  "hif": "Fiji Hindi",
  "hil": "hiligenɔgbe",
  "him": "Himachali",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "hiri motugbe",
  "hr": "kroatiagbe",
  "hr_BA": "kroatiagbe (Bosnia kple Herzergovina nutome)",
  "hr_HR": "kroatiagbe (Kroatsia nutome)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "haitigbe",
  "hu": "hungarigbe",
  "hu_HU": "hungarigbe (Hungari nutome)",
  "hup": "Hupa",
  "hy": "armeniagbe",
  "hy_AM": "armeniagbe (Armenia nutome)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "ibibiogbe",
  "id": "Indonesiagbe",
  "id_ID": "indonesiagbe (Indonesia nutome)",
  "ie": "Interlingue",
  "ig": "igbogbe",
  "ig_NG": "igbogbe (Nigeria nutome)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "ilikogbe",
  "inc": "Indiaanikeel",
  "ine": "Indoeuroopa keel",
  "inh": "ingusigbe",
  "io": "Ido",
  "ira": "Iraani keel",
  "iro": "Irokoo keel",
  "is": "icelanɖgbe",
  "is_IS": "icelanɖgbe (Aiseland nutome)",
  "it": "Italiagbe",
  "it_CH": "italiagbe (Switzerland nutome)",
  "it_IT": "italiagbe (Italia nutome)",
  "it_SM": "italiagbe (San Marino nutome)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Japangbe",
  "ja_JP": "dzapangbe (Dzapan nutome)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "dzavangbe",
  "ka": "gɔgiagbe",
  "ka_GE": "gɔgiagbe (Georgia nutome)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "kabardiagbe",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "cape verdegbe",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "kongogbe",
  "kgp": "Kaingang",
  "kha": "khasigbe",
  "khi": "Khoisani keel",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "kunyamagbe",
  "kk": "kazakhstangbe",
  "kk_Cyrl": "kazakhstangbe (syrilliagbeŋɔŋlɔ)",
  "kk_Cyrl_KZ": "kazakhstangbe (syrilliagbeŋɔŋlɔ, Kazakstan nutome)",
  "kk_KZ": "kazakhstangbe (Kazakstan nutome)",
  "kkj": "kakogbe",
  "kl": "kalaalisugbe",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "khmergbe",
  "km_KH": "khmergbe (Kambodia nutome)",
  "kmb": "Kimbundu",
  "kn": "kannadagbe",
  "kn_IN": "kannadagbe (India nutome)",
  "ko": "Koreagbe",
  "ko_KP": "koreagbe (Dziehe Korea nutome)",
  "ko_KR": "koreagbe (Anyiehe Korea nutome)",
  "koi": "Komi-Permyak",
  "kok": "konkaniagbe",
  "kos": "kosraeagbe",
  "kpe": "Kpelle",
  "kr": "kanuriagbe",
  "krc": "karakay-bakargbe",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "kashmirgbe",
  "ks_Arab": "kashmirgbe (arabiagbeŋɔŋlɔ)",
  "ks_Arab_IN": "kashmirgbe (arabiagbeŋɔŋlɔ, India nutome)",
  "ks_IN": "kashmirgbe (India nutome)",
  "ksb": "Shambala",
  "ksf": "bafiagbe",
  "ksh": "Colognian",
  "ku": "kurdiagbe",
  "kum": "kumikagbe",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "kirghistangbe",
  "ky_Cyrl": "kirghistangbe (syrilliagbeŋɔŋlɔ)",
  "ky_Cyrl_KG": "kirghistangbe (syrilliagbeŋɔŋlɔ, Kirgizstan nutome)",
  "ky_KG": "kirghistangbe (Kirgizstan nutome)",
  "la": "latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "lahndagbe",
  "lam": "Lamba",
  "lb": "laksembɔggbe",
  "lb_LU": "laksembɔggbe (Lazembɔg nutome)",
  "lez": "lezghiagbe",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola nutome)",
  "ln_CD": "lingala (Kongo Kinshasa nutome)",
  "ln_CF": "lingala (Titina Afrika repɔblik nutome)",
  "ln_CG": "lingala (Kongo Brazzaville nutome)",
  "lo": "laogbe",
  "lo_LA": "laogbe (Laos nutome)",
  "lol": "Mongo",
  "lou": "Louisiana kreool",
  "loz": "Lozi",
  "lrc": "Põhja-Luri",
  "lt": "lithuaniagbe",
  "lt_LT": "lithuaniagbe (Lituania nutome)",
  "ltg": "Latgalian",
  "lu": "luba-katangagbe",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "luba-lulugbe",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "luyiagbe",
  "lv": "latviagbe",
  "lv_LV": "latviagbe (Latvia nutome)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "mafagbe",
  "mag": "Magahi",
  "mai": "maitiligbe",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Austroneesia keel",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "moktsiagbe",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "malagasegbe",
  "mg_MG": "malagasegbe (Madagaska nutome)",
  "mga": "Middle Irish",
  "mgh": "makuwa-mitogbe",
  "mgo": "Metaʼ",
  "mh": "marshalgbe",
  "mi": "maorgbe",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Mitmesugune keel",
  "mk": "makedoniagbe",
  "mk_MK": "makedoniagbe (Makedonia nutome)",
  "mkh": "Esmas-khmeeri keel",
  "ml": "malayagbe",
  "ml_IN": "malayagbe (India nutome)",
  "mn": "mongoliagbe",
  "mn_Cyrl": "mongoliagbe (syrilliagbeŋɔŋlɔ)",
  "mn_Cyrl_MN": "mongoliagbe (syrilliagbeŋɔŋlɔ, Mongolia nutome)",
  "mn_MN": "mongoliagbe (Mongolia nutome)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Manobo keel",
  "mo": "Moldaavia keel",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "marathiagbe",
  "mr_IN": "marathiagbe (India nutome)",
  "mrj": "Western Mari",
  "ms": "malaygbe",
  "ms_BN": "malaygbe (Brunei nutome)",
  "ms_Latn": "malaygbe (latingbeŋɔŋlɔ)",
  "ms_Latn_BN": "malaygbe (latingbeŋɔŋlɔ, Brunei nutome)",
  "ms_Latn_MY": "malaygbe (latingbeŋɔŋlɔ, Malaysia nutome)",
  "ms_Latn_SG": "malaygbe (latingbeŋɔŋlɔ, Singapɔr nutome)",
  "ms_MY": "malaygbe (Malaysia nutome)",
  "ms_SG": "malaygbe (Singapɔr nutome)",
  "mt": "maltagbe",
  "mt_MT": "maltagbe (Malta nutome)",
  "mua": "mundangbe",
  "mul": "gbegbɔgblɔ sɔgbɔwo",
  "mun": "Munda keel",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "burmagbe",
  "my_MM": "burmagbe (Myanmar (Burma) nutome)",
  "mye": "myenegbe",
  "myn": "Maiade keel",
  "myv": "erziyagbe",
  "mzn": "Mazanderani",
  "na": "naurugbe",
  "nah": "Nahuatl",
  "nai": "Põhja-Ameerika india keel",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "nɔweigbe bokmål",
  "nb_NO": "nɔweigbe bokmål (Norway nutome)",
  "nb_SJ": "nɔweigbe bokmål (Svalbard kple Yan Mayen nutome)",
  "nd": "dziehe ndebelegbe",
  "nd_ZW": "dziehe ndebelegbe (Zimbabwe nutome)",
  "nds": "Low German",
  "nds_NL": "Hollandi madalsaks",
  "ne": "nepalgbe",
  "ne_IN": "nepalgbe (India nutome)",
  "ne_NP": "nepalgbe (Nepal nutome)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Nigeri-Kordofani keel",
  "niu": "niuegbe",
  "njo": "Ao Naga",
  "nl": "Hollandgbe",
  "nl_AW": "hɔlandgbe (Aruba nutome)",
  "nl_BE": "hɔlandgbe (Belgium nutome)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "hɔlandgbe (Nedalands nutome)",
  "nl_SR": "hɔlandgbe (Suriname nutome)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "kwasiogbe",
  "nn": "nɔweigbe ninɔsk",
  "nn_NO": "nɔweigbe ninɔsk (Norway nutome)",
  "nnh": "ngiemboongbe",
  "no": "nɔweigbe",
  "no_NO": "nɔweigbe (Norway nutome)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "anyiehe ndebelegbe",
  "nso": "dziehe sothogbe",
  "nub": "Nuubia keel",
  "nus": "nuergbe",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "nyanjagbe",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "oriyagbe",
  "or_IN": "oriyagbe (India nutome)",
  "os": "ossetiagbe",
  "os_GE": "ossetiagbe (Georgia nutome)",
  "os_RU": "ossetiagbe (Russia nutome)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "oto": "Otomi keel",
  "pa": "pundzabgbe",
  "pa_Arab": "pundzabgbe (arabiagbeŋɔŋlɔ)",
  "pa_Arab_PK": "pundzabgbe (arabiagbeŋɔŋlɔ, Pakistan nutome)",
  "pa_Guru": "pundzabgbe (gurmukhigbeŋɔŋlɔ)",
  "pa_Guru_IN": "pundzabgbe (gurmukhigbeŋɔŋlɔ, India nutome)",
  "pa_IN": "pundzabgbe (India nutome)",
  "pa_PK": "pundzabgbe (Pakistan nutome)",
  "paa": "Paapua keel",
  "pag": "pangsinagbe",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "papiamentogbe",
  "pau": "paluagbe",
  "pcd": "Picard",
  "pcm": "Nigeeria Pidgin",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phi": "Filipiini keel",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Polishgbe",
  "pl_PL": "polandgbe (Poland nutome)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "ponpeiagbe",
  "pra": "Prakriti keel",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "pashtogbe",
  "ps_AF": "pashtogbe (Afghanistan nutome)",
  "pt": "Portuguesegbe",
  "pt_AO": "pɔtugalgbe (Angola nutome)",
  "pt_BR": "pɔtugalgbe (Brazil nutome)",
  "pt_CV": "pɔtugalgbe (Kape Verde nutome)",
  "pt_GW": "pɔtugalgbe (Gini-Bisao nutome)",
  "pt_MO": "pɔtugalgbe (Macau SAR Tsaina nutome)",
  "pt_MZ": "pɔtugalgbe (Mozambiki nutome)",
  "pt_PT": "pɔtugalgbe (Portugal nutome)",
  "pt_ST": "pɔtugalgbe (São Tomé kple Príncipe nutome)",
  "pt_TL": "pɔtugalgbe (Timor-Leste nutome)",
  "qu": "kwetsuagbe",
  "qu_BO": "kwetsuagbe (Bolivia nutome)",
  "qu_EC": "kwetsuagbe (Ekuadɔ nutome)",
  "qu_PE": "kwetsuagbe (Peru nutome)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "romanshgbe",
  "rm_CH": "romanshgbe (Switzerland nutome)",
  "rn": "rundigbe",
  "rn_BI": "rundigbe (Burundi nutome)",
  "ro": "romaniagbe",
  "ro_MD": "romaniagbe (Moldova nutome)",
  "ro_RO": "romaniagbe (Romania nutome)",
  "roa": "Romaani keel",
  "rof": "rombogbe",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Russiagbe",
  "ru_BY": "rɔtsiagbe (Belarus nutome)",
  "ru_KG": "rɔtsiagbe (Kirgizstan nutome)",
  "ru_KZ": "rɔtsiagbe (Kazakstan nutome)",
  "ru_MD": "rɔtsiagbe (Moldova nutome)",
  "ru_RU": "rɔtsiagbe (Russia nutome)",
  "ru_UA": "rɔtsiagbe (Ukraine nutome)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "ruwandagbe",
  "rw_RW": "ruwandagbe (Rwanda nutome)",
  "rwk": "rwagbe",
  "sa": "sanskrigbe",
  "sad": "Sandawe",
  "sah": "sakagbe",
  "sai": "Lõuna-Ameerika india keel",
  "sal": "Salishani keel",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "santaligbe",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "sangugbe",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "sindhgbe",
  "sd_Deva": "Sindhi (devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "Lõuna-kurdi keel",
  "se": "dziehe samigbe",
  "se_FI": "dziehe samigbe (Finland nutome)",
  "se_NO": "dziehe samigbe (Norway nutome)",
  "se_SE": "dziehe samigbe (Sweden nutome)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Semiidi keel",
  "ses": "Koyraboro Senni",
  "sg": "sangogbe",
  "sg_CF": "sangogbe (Titina Afrika repɔblik nutome)",
  "sga": "Old Irish",
  "sgn": "Viipekeel",
  "sgs": "Samogitian",
  "sh": "serbo-croatiagbe",
  "sh_BA": "serbo-croatiagbe (Bosnia kple Herzergovina nutome)",
  "shi": "Tachelhit",
  "shi_Latn": "Shilha (ladina)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "sinhalgbe",
  "si_LK": "sinhalgbe (Sri Lanka nutome)",
  "sid": "Sidamo",
  "sio": "Siouani keel",
  "sit": "Hiina-tiibeti keel",
  "sk": "slovakiagbe",
  "sk_SK": "slovakiagbe (Slovakia nutome)",
  "sl": "sloveniagbe",
  "sl_SI": "sloveniagbe (Slovenia nutome)",
  "sla": "Slaavi keel",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoagbe",
  "sma": "Southern Sami",
  "smi": "Saami keel",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "shonagbe",
  "sn_ZW": "shonagbe (Zimbabwe nutome)",
  "snk": "Soninke",
  "so": "somaliagbe",
  "so_DJ": "somaliagbe (Dzibuti nutome)",
  "so_ET": "somaliagbe (Etiopia nutome)",
  "so_KE": "somaliagbe (Kenya nutome)",
  "so_SO": "somaliagbe (Somalia nutome)",
  "sog": "Sogdien",
  "son": "Songhai",
  "sq": "albaniagbe",
  "sq_AL": "albaniagbe (Albania nutome)",
  "sq_MK": "albaniagbe (Makedonia nutome)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "serbiagbe",
  "sr_BA": "serbiagbe (Bosnia kple Herzergovina nutome)",
  "sr_Cyrl": "serbiagbe (syrilliagbeŋɔŋlɔ)",
  "sr_Cyrl_BA": "serbiagbe (syrilliagbeŋɔŋlɔ, Bosnia kple Herzergovina nutome)",
  "sr_Cyrl_ME": "serbiagbe (syrilliagbeŋɔŋlɔ, Montenegro nutome)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "serbiagbe (latingbeŋɔŋlɔ)",
  "sr_Latn_BA": "serbiagbe (latingbeŋɔŋlɔ, Bosnia kple Herzergovina nutome)",
  "sr_Latn_ME": "serbiagbe (latingbeŋɔŋlɔ, Montenegro nutome)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "serbiagbe (Montenegro nutome)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "swatgbe",
  "ssa": "Nilo-Sahara keel",
  "ssy": "Saho",
  "st": "anyiehe sothogbe",
  "stq": "Saterland Frisian",
  "su": "sudangbe",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "swedengbe",
  "sv_AX": "swedengbe (Åland ƒudomekpo nutome)",
  "sv_FI": "swedengbe (Finland nutome)",
  "sv_SE": "swedengbe (Sweden nutome)",
  "sw": "swahili",
  "sw_CD": "Kongo suahiili keel",
  "sw_KE": "swahili (Kenya nutome)",
  "sw_TZ": "swahili (Tanzania nutome)",
  "sw_UG": "swahili (Uganda nutome)",
  "swb": "komorogbe",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "tamilgbe",
  "ta_IN": "tamilgbe (India nutome)",
  "ta_LK": "tamilgbe (Sri Lanka nutome)",
  "ta_MY": "tamilgbe (Malaysia nutome)",
  "ta_SG": "tamilgbe (Singapɔr nutome)",
  "tai": "Tai keel",
  "tcy": "Tulu",
  "te": "telegugbe",
  "te_IN": "telegugbe (India nutome)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "tetumgbe",
  "tg": "tadzikistangbe",
  "th": "Thailandgbe",
  "th_TH": "tailandgbe (Tailand nutome)",
  "ti": "tigrinyagbe",
  "ti_ER": "tigrinyagbe (Eritrea nutome)",
  "ti_ET": "tigrinyagbe (Etiopia nutome)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "tɛkmengbe",
  "tkl": "tokelaugbe",
  "tkr": "Tsakhur",
  "tl": "tagalogbe",
  "tl_PH": "tagalogbe (Filipini nutome)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "tswanagbe",
  "to": "tongagbe",
  "to_TO": "tongagbe (Tonga nutome)",
  "tog": "Nyasa Tonga",
  "tpi": "tok pisigbe",
  "tr": "Turkishgbe",
  "tr_CY": "tɛkigbe (Saiprus nutome)",
  "tr_TR": "tɛkigbe (Tɛki nutome)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "tsongagbe",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "tatargbe",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tup": "Tupi keel",
  "tut": "Altai keel",
  "tvl": "tuvalugbe",
  "tw": "Twi",
  "twq": "tasawakgbe",
  "ty": "tahitigbe",
  "tyv": "tuviniagbe",
  "tzm": "Central Atlas Tamazight",
  "udm": "udmurtgbe",
  "ug": "uighurgbe",
  "ug_Arab": "uighurgbe (arabiagbeŋɔŋlɔ)",
  "ug_Arab_CN": "uighurgbe (arabiagbeŋɔŋlɔ, Tsaina nutome)",
  "ug_CN": "uighurgbe (Tsaina nutome)",
  "uga": "Ugaritic",
  "uk": "ukraingbe",
  "uk_UA": "ukraingbe (Ukraine nutome)",
  "umb": "Umbundu",
  "und": "gbegbɔgblɔ manya",
  "ur": "urdugbe",
  "ur_IN": "urdugbe (India nutome)",
  "ur_PK": "urdugbe (Pakistan nutome)",
  "uz": "uzbekistangbe",
  "uz_AF": "uzbekistangbe (Afghanistan nutome)",
  "uz_Arab": "uzbekistangbe (arabiagbeŋɔŋlɔ)",
  "uz_Arab_AF": "uzbekistangbe (arabiagbeŋɔŋlɔ, Afghanistan nutome)",
  "uz_Cyrl": "uzbekistangbe (syrilliagbeŋɔŋlɔ)",
  "uz_Cyrl_UZ": "uzbekistangbe (syrilliagbeŋɔŋlɔ, Uzbekistan nutome)",
  "uz_Latn": "uzbekistangbe (latingbeŋɔŋlɔ)",
  "uz_Latn_UZ": "uzbekistangbe (latingbeŋɔŋlɔ, Uzbekistan nutome)",
  "uz_UZ": "uzbekistangbe (Uzbekistan nutome)",
  "vai": "vaigbe",
  "vai_Latn": "Vai (ladina)",
  "ve": "vendagbe",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnamgbe",
  "vi_VN": "vietnamgbe (Vietnam nutome)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "walsegbe",
  "wak": "Wakashani keel",
  "wal": "Wolaytta",
  "war": "waraygbe",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Sorbi keel",
  "wo": "wolofgbe",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "xhosagbe",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "yapesigbe",
  "yav": "yangbengbe",
  "ybb": "yembagbe",
  "yi": "Yiddish",
  "yo": "yorubagbe",
  "yo_BJ": "yorubagbe (Benin nutome)",
  "yo_NG": "yorubagbe (Nigeria nutome)",
  "ypk": "Yupiku keel",
  "yrl": "Nheengatu",
  "yue": "cantongbe",
  "yue_Hans": "Kantoni (lihtsustatud hiina)",
  "yue_Hant": "Kantoni keel (traditsiooniline hiina keel)",
  "za": "zhuangbe",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "kinagbe",
  "zh_CN": "kinagbe (Tsaina nutome)",
  "zh_HK": "kinagbe (Hɔng Kɔng SAR Tsaina nutome)",
  "zh_Hans": "kinagbe (tsainagbeŋɔŋlɔ)",
  "zh_Hans_CN": "kinagbe (tsainagbeŋɔŋlɔ, Tsaina nutome)",
  "zh_Hans_HK": "kinagbe (tsainagbeŋɔŋlɔ, Hɔng Kɔng SAR Tsaina nutome)",
  "zh_Hans_MO": "kinagbe (tsainagbeŋɔŋlɔ, Macau SAR Tsaina nutome)",
  "zh_Hans_SG": "kinagbe (tsainagbeŋɔŋlɔ, Singapɔr nutome)",
  "zh_Hant": "kinagbe (blema tsainagbeŋɔŋlɔ)",
  "zh_Hant_HK": "kinagbe (blema tsainagbeŋɔŋlɔ, Hɔng Kɔng SAR Tsaina nutome)",
  "zh_Hant_MO": "kinagbe (blema tsainagbeŋɔŋlɔ, Macau SAR Tsaina nutome)",
  "zh_Hant_TW": "kinagbe (blema tsainagbeŋɔŋlɔ, Taiwan nutome)",
  "zh_MO": "kinagbe (Macau SAR Tsaina nutome)",
  "zh_SG": "kinagbe (Singapɔr nutome)",
  "zh_TW": "kinagbe (Taiwan nutome)",
  "znd": "Zande",
  "zu": "zulugbe",
  "zu_ZA": "zulugbe (Anyiehe Afrika nutome)",
  "zun": "Zuni",
  "zxx": "gbegbɔgblɔ manɔmee",
  "zza": "Zaza"
};
