const names = {
  "ace": "Achinese",
  "an": "Aragonese",
  "ast": "Asturian",
  "ban": "Balinese",
  "bug": "Buginese",
  "chk": "Chuukese",
  "frc": "Cajun French",
  "fy": "Frisian",
  "gan": "Gan Chinese",
  "gil": "Gilbertese",
  "hak": "Hakka Chinese",
  "hr": "Croat",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "kbd": "Kabardian",
  "mad": "Madurese",
  "mh": "Marshallese",
  "ms": "Bahasa Melayu",
  "mul": "Multiple Languages",
  "nan": "Min Nan Chinese",
  "nds": "Low German",
  "niu": "Niuean",
  "nr": "South Ndebele",
  "or": "Oriya",
  "prg": "Prussian",
  "rar": "Rarotongan",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "shu": "Chadian Arab",
  "wuu": "Wu Chinese",
  "yue": "Cantonese"
};
