const names = {
  "001": "Mondo",
  "002": "Africa",
  "003": "Nord America",
  "005": "America del Sud",
  "009": "Oceania",
  "011": "Africa occidentale",
  "013": "America Centrale",
  "014": "Africa orientale",
  "015": "Nordafrica",
  "017": "Africa centrale",
  "018": "Africa del Sud",
  "019": "Americhe",
  "021": "America del Nord",
  "029": "Caraibi",
  "030": "Asia orientale",
  "034": "Asia del Sud",
  "035": "Sud-est asiatico",
  "039": "Europa meridionale",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Regione micronesiana",
  "061": "Polinesia",
  "142": "Asia",
  "143": "Asia centrale",
  "145": "Asia occidentale",
  "150": "Europa",
  "151": "Europa orientale",
  "154": "Europa settentrionale",
  "155": "Europa occidentale",
  "202": "Africa subsahariana",
  "419": "America Latina",
  "AC": "Isola Ascensione",
  "AD": "Andorra",
  "AE": "Emirati Arabi Uniti",
  "AF": "Afghanistan",
  "AG": "Antigua e Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antille Olandesi",
  "AO": "Angola",
  "AQ": "Antartide",
  "AR": "Argentina",
  "AS": "Samoa americane",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Isole Åland",
  "AZ": "Azerbaigian",
  "Afak": "afaka",
  "Aghb": "albanese caucasico",
  "Arab": "arabo",
  "Aran": "nastaliq",
  "Armi": "aramaico imperiale",
  "Armn": "armeno",
  "Avst": "avestico",
  "BA": "Bosnia ed Erzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgio",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caraibi olandesi",
  "BR": "Brasile",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Isola Bouvet",
  "BW": "Botswana",
  "BY": "Bielorussia",
  "BZ": "Belize",
  "Bali": "balinese",
  "Bamu": "bamum",
  "Bass": "Bassa Vah",
  "Batk": "batak",
  "Beng": "bengalese",
  "Blis": "simboli bliss",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "braille",
  "Bugi": "buginese",
  "Buhd": "buhid",
  "CA": "Canada",
  "CC": "Isole Cocos (Keeling)",
  "CD": "Congo - Kinshasa",
  "CF": "Repubblica Centrafricana",
  "CG": "Congo-Brazzaville",
  "CH": "Svizzera",
  "CI": "Costa d’Avorio",
  "CK": "Isole Cook",
  "CL": "Cile",
  "CM": "Camerun",
  "CN": "Cina",
  "CO": "Colombia",
  "CP": "Isola di Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia e Montenegro",
  "CU": "Cuba",
  "CV": "Capo Verde",
  "CW": "Curaçao",
  "CX": "Isola Christmas",
  "CY": "Cipro",
  "CZ": "Cechia",
  "Cakm": "chakma",
  "Cans": "simboli aborigeni canadesi unificati",
  "Cari": "carian",
  "Cham": "cham",
  "Cher": "cherokee",
  "Cirt": "cirth",
  "Copt": "copto",
  "Cprt": "cipriota",
  "Cyrl": "cirillico",
  "Cyrs": "cirillico antica chiesa slavonica",
  "DE": "Germania",
  "DG": "Diego Garcia",
  "DJ": "Gibuti",
  "DK": "Danimarca",
  "DM": "Dominica",
  "DO": "Repubblica Dominicana",
  "DZ": "Algeria",
  "Deva": "devanagari",
  "Dsrt": "deseret",
  "Dupl": "stenografia duployan",
  "EA": "Ceuta e Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egitto",
  "EH": "Sahara occidentale",
  "ER": "Eritrea",
  "ES": "Spagna",
  "ET": "Etiopia",
  "EU": "Unione Europea",
  "EZ": "Eurozona",
  "Egyd": "egiziano demotico",
  "Egyh": "ieratico egiziano",
  "Egyp": "geroglifici egiziani",
  "Ethi": "etiope",
  "FI": "Finlandia",
  "FJ": "Figi",
  "FK": "Isole Falkland",
  "FM": "Micronesia",
  "FO": "Isole Fær Øer",
  "FR": "Francia",
  "FX": "Francia metropolitana",
  "GA": "Gabon",
  "GB": "Regno Unito",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Guyana francese",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibilterra",
  "GL": "Groenlandia",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadalupa",
  "GQ": "Guinea Equatoriale",
  "GR": "Grecia",
  "GS": "Georgia del Sud e Sandwich australi",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "kutsuri",
  "Geor": "georgiano",
  "Glag": "glagolitico",
  "Goth": "gotico",
  "Gran": "grantha",
  "Grek": "greco",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "RAS di Hong Kong",
  "HM": "Isole Heard e McDonald",
  "HN": "Honduras",
  "HR": "Croazia",
  "HT": "Haiti",
  "HU": "Ungheria",
  "Hanb": "hanb",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanunoo",
  "Hans": "semplificato",
  "Hant": "tradizionale",
  "Hebr": "ebraico",
  "Hira": "hiragana",
  "Hluw": "geroglifici anatolici",
  "Hmng": "pahawn hmong",
  "Hrkt": "katanaka o hiragana",
  "Hung": "antico ungherese",
  "IC": "Isole Canarie",
  "ID": "Indonesia",
  "IE": "Irlanda",
  "IL": "Israele",
  "IM": "Isola di Man",
  "IN": "India",
  "IO": "Territorio britannico dell’Oceano Indiano",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Islanda",
  "IT": "Italia",
  "Inds": "indu",
  "Ital": "italico antico",
  "JE": "Jersey",
  "JM": "Giamaica",
  "JO": "Giordania",
  "JP": "Giappone",
  "Jamo": "jamo",
  "Java": "javanese",
  "Jpan": "giapponese",
  "Jurc": "jurchen",
  "KE": "Kenya",
  "KG": "Kirghizistan",
  "KH": "Cambogia",
  "KI": "Kiribati",
  "KM": "Comore",
  "KN": "Saint Kitts e Nevis",
  "KP": "Corea del Nord",
  "KR": "Corea del Sud",
  "KW": "Kuwait",
  "KY": "Isole Cayman",
  "KZ": "Kazakistan",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharoshthi",
  "Khmr": "khmer",
  "Khoj": "khojki",
  "Knda": "kannada",
  "Kore": "coreano",
  "Kpel": "Kpelle",
  "Kthi": "kaithi",
  "LA": "Laos",
  "LB": "Libano",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lituania",
  "LU": "Lussemburgo",
  "LV": "Lettonia",
  "LY": "Libia",
  "Lana": "lanna",
  "Laoo": "lao",
  "Latf": "variante fraktur del latino",
  "Latg": "variante gaelica del latino",
  "Latn": "latino",
  "Lepc": "lepcha",
  "Limb": "limbu",
  "Lina": "lineare A",
  "Linb": "lineare B",
  "Lisu": "lisu",
  "Loma": "loma",
  "Lyci": "lyci",
  "Lydi": "lydi",
  "MA": "Marocco",
  "MC": "Monaco",
  "MD": "Moldavia",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Isole Marshall",
  "MK": "Macedonia del Nord",
  "ML": "Mali",
  "MM": "Myanmar (Birmania)",
  "MN": "Mongolia",
  "MO": "RAS di Macao",
  "MP": "Isole Marianne settentrionali",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldive",
  "MW": "Malawi",
  "MX": "Messico",
  "MY": "Malaysia",
  "MZ": "Mozambico",
  "Mand": "mandaico",
  "Mani": "manicheo",
  "Maya": "geroglifici maya",
  "Mend": "mende",
  "Merc": "corsivo meroitico",
  "Mero": "meroitico",
  "Mlym": "malayalam",
  "Mong": "mongolo",
  "Moon": "moon",
  "Mroo": "mro",
  "Mtei": "meetei mayek",
  "Mymr": "birmano",
  "NA": "Namibia",
  "NC": "Nuova Caledonia",
  "NE": "Niger",
  "NF": "Isola Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Paesi Bassi",
  "NO": "Norvegia",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nuova Zelanda",
  "Narb": "arabo settentrionale antico",
  "Nbat": "nabateo",
  "Nkgb": "geba naxi",
  "Nkoo": "n’ko",
  "Nshu": "nushu",
  "OM": "Oman",
  "Ogam": "ogham",
  "Olck": "ol chiki",
  "Orkh": "orkhon",
  "Orya": "oriya",
  "Osma": "osmanya",
  "PA": "Panamá",
  "PE": "Perù",
  "PF": "Polinesia francese",
  "PG": "Papua Nuova Guinea",
  "PH": "Filippine",
  "PK": "Pakistan",
  "PL": "Polonia",
  "PM": "Saint-Pierre e Miquelon",
  "PN": "Isole Pitcairn",
  "PR": "Portorico",
  "PS": "Territori palestinesi",
  "PT": "Portogallo",
  "PW": "Palau",
  "PY": "Paraguay",
  "Palm": "palmireno",
  "Perm": "permico antico",
  "Phag": "phags-pa",
  "Phli": "pahlavi delle iscrizioni",
  "Phlp": "pahlavi psalter",
  "Phlv": "pahlavi book",
  "Phnx": "fenicio",
  "Plrd": "fonetica di pollard",
  "Prti": "partico delle iscrizioni",
  "QA": "Qatar",
  "QO": "Oceania lontana",
  "Qaag": "zawgyi",
  "RE": "Riunione",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Ruanda",
  "Rjng": "rejang",
  "Roro": "rongorongo",
  "Runr": "runico",
  "SA": "Arabia Saudita",
  "SB": "Isole Salomone",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Svezia",
  "SG": "Singapore",
  "SH": "Sant’Elena",
  "SI": "Slovenia",
  "SJ": "Svalbard e Jan Mayen",
  "SK": "Slovacchia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Sud Sudan",
  "ST": "São Tomé e Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Swaziland",
  "Samr": "samaritano",
  "Sara": "sarati",
  "Sarb": "arabo meridionale antico",
  "Saur": "saurashtra",
  "Sgnw": "linguaggio dei segni",
  "Shaw": "shaviano",
  "Shrd": "sharada",
  "Sind": "khudawadi",
  "Sinh": "singalese",
  "Sora": "sora sompeng",
  "Sund": "sundanese",
  "Sylo": "syloti nagri",
  "Syrc": "siriano",
  "Syre": "siriaco estrangelo",
  "Syrj": "siriaco occidentale",
  "Syrn": "siriaco orientale",
  "TA": "Tristan da Cunha",
  "TC": "Isole Turks e Caicos",
  "TD": "Ciad",
  "TF": "Terre australi francesi",
  "TG": "Togo",
  "TH": "Thailandia",
  "TJ": "Tagikistan",
  "TK": "Tokelau",
  "TL": "Timor Est",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turchia",
  "TT": "Trinidad e Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "tagbanwa",
  "Takr": "takri",
  "Tale": "tai le",
  "Talu": "tai lue",
  "Taml": "tamil",
  "Tang": "tangut",
  "Tavt": "tai viet",
  "Telu": "telugu",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagalog",
  "Thaa": "thaana",
  "Thai": "thailandese",
  "Tibt": "tibetano",
  "Tirh": "tirhuta",
  "UA": "Ucraina",
  "UG": "Uganda",
  "UM": "Altre isole americane del Pacifico",
  "UN": "Nazioni Unite",
  "US": "Stati Uniti",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "Ugar": "ugarita",
  "VA": "Città del Vaticano",
  "VC": "Saint Vincent e Grenadine",
  "VE": "Venezuela",
  "VG": "Isole Vergini Britanniche",
  "VI": "Isole Vergini Americane",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vaii",
  "Visp": "alfabeto visivo",
  "WF": "Wallis e Futuna",
  "WS": "Samoa",
  "Wara": "varang kshiti",
  "Wole": "woleai",
  "XA": "Pseudo-accenti",
  "XB": "Pseudo-bidi",
  "XK": "Kosovo",
  "Xpeo": "persiano antico",
  "Xsux": "sumero-accadiano cuneiforme",
  "YE": "Yemen",
  "YT": "Mayotte",
  "Yiii": "yi",
  "ZA": "Sudafrica",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Regione sconosciuta",
  "Zinh": "ereditato",
  "Zmth": "notazione matematica",
  "Zsye": "emoji",
  "Zsym": "simboli",
  "Zxxx": "non scritto",
  "Zyyy": "comune",
  "Zzzz": "scrittura sconosciuta",
  "aa": "afar",
  "ab": "abcaso",
  "ace": "accinese",
  "ach": "acioli",
  "ada": "adangme",
  "ady": "adyghe",
  "ae": "avestan",
  "aeb": "arabo tunisino",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibia)",
  "af_ZA": "afrikaans (Sudafrica)",
  "afa": "lingua afroasiatica",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "accado",
  "akz": "alabama",
  "ale": "aleuto",
  "alg": "lingue algonchine",
  "aln": "albanese ghego",
  "alt": "altai meridionale",
  "am": "amarico",
  "am_ET": "amarico (Etiopia)",
  "an": "aragonese",
  "ang": "inglese antico",
  "anp": "angika",
  "apa": "lingue apache",
  "ar": "arabo",
  "ar_001": "arabo moderno standard",
  "ar_AE": "arabo (Emirati Arabi Uniti)",
  "ar_BH": "arabo (Bahrein)",
  "ar_DJ": "arabo (Gibuti)",
  "ar_DZ": "arabo (Algeria)",
  "ar_EG": "arabo (Egitto)",
  "ar_EH": "arabo (Sahara Occidentale)",
  "ar_ER": "arabo (Eritrea)",
  "ar_IL": "arabo (Israele)",
  "ar_IQ": "arabo (Iraq)",
  "ar_JO": "arabo (Giordania)",
  "ar_KM": "arabo (Comore)",
  "ar_KW": "arabo (Kuwait)",
  "ar_LB": "arabo (Libano)",
  "ar_LY": "arabo (Libia)",
  "ar_MA": "arabo (Marocco)",
  "ar_MR": "arabo (Mauritania)",
  "ar_OM": "arabo (Oman)",
  "ar_PS": "arabo (Territori palestinesi)",
  "ar_QA": "arabo (Qatar)",
  "ar_SA": "arabo (Arabia Saudita)",
  "ar_SD": "arabo (Sudan)",
  "ar_SO": "arabo (Somalia)",
  "ar_SS": "arabo (Sudan del Sud)",
  "ar_SY": "arabo (Siria)",
  "ar_TD": "arabo (Ciad)",
  "ar_TN": "arabo (Tunisia)",
  "ar_YE": "arabo (Yemen)",
  "arc": "aramaico",
  "arn": "mapudungun",
  "aro": "araona",
  "arp": "arapaho",
  "arq": "arabo algerino",
  "ars": "arabo najd",
  "art": "lingua artificiale",
  "arw": "aruaco",
  "ary": "arabo marocchino",
  "arz": "arabo egiziano",
  "as": "assamese",
  "as_IN": "assamese (India)",
  "asa": "asu",
  "ase": "lingua dei segni americana",
  "ast": "asturiano",
  "ath": "lingue athabaska",
  "aus": "lingue australiane",
  "av": "avaro",
  "avk": "kotava",
  "awa": "awadhi",
  "ay": "aymara",
  "az": "azerbaigiano",
  "az_AZ": "azerbaigiano (Azerbaigian)",
  "az_Cyrl": "azerbaigiano (cirillico)",
  "az_Cyrl_AZ": "azerbaigiano (cirillico, Azerbaigian)",
  "az_Latn": "azerbaigiano (latino)",
  "az_Latn_AZ": "azerbaigiano (latino, Azerbaigian)",
  "azb": "azero meridionale",
  "ba": "baschiro",
  "bad": "banda",
  "bai": "lingue bamileke",
  "bal": "beluci",
  "ban": "balinese",
  "bar": "bavarese",
  "bas": "basa",
  "bat": "lingua baltica",
  "bax": "bamun",
  "bbc": "batak toba",
  "bbj": "ghomala",
  "be": "bielorusso",
  "be_BY": "bielorusso (Bielorussia)",
  "bej": "begia",
  "bem": "wemba",
  "ber": "berbero",
  "bew": "betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "badaga",
  "bg": "bulgaro",
  "bg_BG": "bulgaro (Bulgaria)",
  "bgn": "beluci occidentale",
  "bh": "bihari",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bicol",
  "bin": "bini",
  "bjn": "banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latino)",
  "bm_Latn_ML": "bambara (latino, Mali)",
  "bn": "bengalese",
  "bn_BD": "bengalese (Bangladesh)",
  "bn_IN": "bengalese (India)",
  "bnt": "bantu",
  "bo": "tibetano",
  "bo_CN": "tibetano (Cina)",
  "bo_IN": "tibetano (India)",
  "bpy": "bishnupriya",
  "bqi": "bakhtiari",
  "br": "bretone",
  "br_FR": "bretone (Francia)",
  "bra": "braj",
  "brh": "brahui",
  "brx": "bodo",
  "bs": "bosniaco",
  "bs_BA": "bosniaco (Bosnia-Erzegovina)",
  "bs_Cyrl": "bosniaco (cirillico)",
  "bs_Cyrl_BA": "bosniaco (cirillico, Bosnia-Erzegovina)",
  "bs_Latn": "bosniaco (latino)",
  "bs_Latn_BA": "bosniaco (latino, Bosnia-Erzegovina)",
  "bss": "akoose",
  "btk": "batak",
  "bua": "buriat",
  "bug": "bugi",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "catalano",
  "ca_AD": "catalano (Andorra)",
  "ca_ES": "catalano (Spagna)",
  "ca_FR": "catalano (Francia)",
  "ca_IT": "catalano (Italia)",
  "cad": "caddo",
  "cai": "lingua indiana dell'America Centrale",
  "car": "caribico",
  "cau": "lingua caucasica",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "chakma",
  "ce": "ceceno",
  "ceb": "cebuano",
  "cel": "celtica altra lingua",
  "cgg": "chiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "ciagataico",
  "chk": "chuukese",
  "chm": "mari",
  "chn": "gergo chinook",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cherokee",
  "chy": "cheyenne",
  "ckb": "curdo sorani",
  "cmc": "lingue chamic",
  "co": "corso",
  "cop": "copto",
  "cpe": "creolo o pidgin basati sull'inglese",
  "cpf": "creolo o pidgin basati sul francese",
  "cpp": "creolo o pidgin basati sul portoghese",
  "cps": "capiznon",
  "cr": "cree",
  "crh": "turco crimeo",
  "crp": "creolo o pidgin",
  "crs": "creolo delle Seychelles",
  "cs": "ceco",
  "cs_CZ": "ceco (Repubblica Ceca)",
  "csb": "kashubian",
  "cu": "slavo della Chiesa",
  "cus": "lingua cuscitica",
  "cv": "ciuvascio",
  "cy": "gallese",
  "cy_GB": "gallese (Regno Unito)",
  "da": "danese",
  "da_DK": "danese (Danimarca)",
  "da_GL": "danese (Groenlandia)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "day": "dayak",
  "de": "tedesco",
  "de_AT": "tedesco (Austria)",
  "de_BE": "tedesco (Belgio)",
  "de_CH": "tedesco (Svizzera)",
  "de_DE": "tedesco (Germania)",
  "de_LI": "tedesco (Liechtenstein)",
  "de_LU": "tedesco (Lussemburgo)",
  "del": "delaware",
  "den": "slave",
  "dgr": "dogrib",
  "din": "dinca",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "lingua dravidica",
  "dsb": "basso sorabo",
  "dtp": "dusun centrale",
  "dua": "duala",
  "dum": "olandese medio",
  "dv": "divehi",
  "dyo": "jola-fony",
  "dyu": "diula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhutan)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "ewe",
  "ee_GH": "ewe (Ghana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egl": "emiliano",
  "egy": "egiziano antico",
  "eka": "ekajuka",
  "el": "greco",
  "el_CY": "greco (Cipro)",
  "el_GR": "greco (Grecia)",
  "elx": "elamitico",
  "en": "inglese",
  "en_AG": "inglese (Antigua e Barbuda)",
  "en_AI": "inglese (Anguilla)",
  "en_AS": "inglese (Samoa Americane)",
  "en_AU": "inglese (Australia)",
  "en_BB": "inglese (Barbados)",
  "en_BE": "inglese (Belgio)",
  "en_BM": "inglese (Bermuda)",
  "en_BS": "inglese (Bahamas)",
  "en_BW": "inglese (Botswana)",
  "en_BZ": "inglese (Belize)",
  "en_CA": "inglese (Canada)",
  "en_CC": "inglese (Isole Cocos)",
  "en_CK": "inglese (Isole Cook)",
  "en_CM": "inglese (Camerun)",
  "en_CX": "inglese (Isola di Christmas)",
  "en_DG": "inglese (Diego Garcia)",
  "en_DM": "inglese (Dominica)",
  "en_ER": "inglese (Eritrea)",
  "en_FJ": "inglese (Figi)",
  "en_FK": "inglese (Isole Falkland)",
  "en_FM": "inglese (Micronesia)",
  "en_GB": "inglese (Regno Unito)",
  "en_GD": "inglese (Grenada)",
  "en_GG": "inglese (Guernsey)",
  "en_GH": "inglese (Ghana)",
  "en_GI": "inglese (Gibilterra)",
  "en_GM": "inglese (Gambia)",
  "en_GU": "inglese (Guam)",
  "en_GY": "inglese (Guyana)",
  "en_HK": "inglese (RAS di Hong Kong)",
  "en_IE": "inglese (Irlanda)",
  "en_IM": "inglese (Isola di Man)",
  "en_IN": "inglese (India)",
  "en_IO": "inglese (Territorio Britannico dell’Oceano Indiano)",
  "en_JE": "inglese (Jersey)",
  "en_JM": "inglese (Giamaica)",
  "en_KE": "inglese (Kenya)",
  "en_KI": "inglese (Kiribati)",
  "en_KN": "inglese (Saint Kitts e Nevis)",
  "en_KY": "inglese (Isole Cayman)",
  "en_LC": "inglese (Saint Lucia)",
  "en_LR": "inglese (Liberia)",
  "en_LS": "inglese (Lesotho)",
  "en_MG": "inglese (Madagascar)",
  "en_MH": "inglese (Isole Marshall)",
  "en_MO": "inglese (RAS di Macao)",
  "en_MP": "inglese (Isole Marianne Settentrionali)",
  "en_MS": "inglese (Montserrat)",
  "en_MT": "inglese (Malta)",
  "en_MU": "inglese (Mauritius)",
  "en_MW": "inglese (Malawi)",
  "en_MY": "inglese (Malesia)",
  "en_NA": "inglese (Namibia)",
  "en_NF": "inglese (Isola Norfolk)",
  "en_NG": "inglese (Nigeria)",
  "en_NR": "inglese (Nauru)",
  "en_NU": "inglese (Niue)",
  "en_NZ": "inglese (Nuova Zelanda)",
  "en_PG": "inglese (Papua Nuova Guinea)",
  "en_PH": "inglese (Filippine)",
  "en_PK": "inglese (Pakistan)",
  "en_PN": "inglese (Isole Pitcairn)",
  "en_PR": "inglese (Portorico)",
  "en_PW": "inglese (Palau)",
  "en_RW": "inglese (Ruanda)",
  "en_SB": "inglese (Isole Solomon)",
  "en_SC": "inglese (Seychelles)",
  "en_SD": "inglese (Sudan)",
  "en_SG": "inglese (Singapore)",
  "en_SH": "inglese (Sant’Elena)",
  "en_SL": "inglese (Sierra Leone)",
  "en_SS": "inglese (Sudan del Sud)",
  "en_SX": "inglese (Sint Maarten)",
  "en_SZ": "inglese (Swaziland)",
  "en_TC": "inglese (Isole Turks e Caicos)",
  "en_TK": "inglese (Tokelau)",
  "en_TO": "inglese (Tonga)",
  "en_TT": "inglese (Trinidad e Tobago)",
  "en_TV": "inglese (Tuvalu)",
  "en_TZ": "inglese (Tanzania)",
  "en_UG": "inglese (Uganda)",
  "en_UM": "inglese (Isole minori lontane dagli USA)",
  "en_US": "inglese (Stati Uniti)",
  "en_VC": "inglese (Saint Vincent e Grenadines)",
  "en_VG": "inglese (Isole Vergini Britanniche)",
  "en_VI": "inglese (Isole Vergini Americane)",
  "en_VU": "inglese (Vanuatu)",
  "en_WS": "inglese (Samoa)",
  "en_ZA": "inglese (Sudafrica)",
  "en_ZM": "inglese (Zambia)",
  "en_ZW": "inglese (Zimbabwe)",
  "enm": "inglese medio",
  "eo": "esperanto",
  "es": "spagnolo",
  "es_419": "spagnolo latinoamericano",
  "es_AR": "spagnolo (Argentina)",
  "es_BO": "spagnolo (Bolivia)",
  "es_CL": "spagnolo (Cile)",
  "es_CO": "spagnolo (Colombia)",
  "es_CR": "spagnolo (Costa Rica)",
  "es_CU": "spagnolo (Cuba)",
  "es_DO": "spagnolo (Repubblica Dominicana)",
  "es_EA": "spagnolo (Ceuta e Melilla)",
  "es_EC": "spagnolo (Ecuador)",
  "es_ES": "spagnolo (Spagna)",
  "es_GQ": "spagnolo (Guinea Equatoriale)",
  "es_GT": "spagnolo (Guatemala)",
  "es_HN": "spagnolo (Honduras)",
  "es_IC": "spagnolo (Isole Canarie)",
  "es_MX": "spagnolo (Messico)",
  "es_NI": "spagnolo (Nicaragua)",
  "es_PA": "spagnolo (Panamá)",
  "es_PE": "spagnolo (Perù)",
  "es_PH": "spagnolo (Filippine)",
  "es_PR": "spagnolo (Portorico)",
  "es_PY": "spagnolo (Paraguay)",
  "es_SV": "spagnolo (El Salvador)",
  "es_US": "spagnolo (Stati Uniti)",
  "es_UY": "spagnolo (Uruguay)",
  "es_VE": "spagnolo (Venezuela)",
  "esu": "yupik centrale",
  "et": "estone",
  "et_EE": "estone (Estonia)",
  "eu": "basco",
  "eu_ES": "basco (Spagna)",
  "ewo": "ewondo",
  "ext": "estremegno",
  "fa": "persiano",
  "fa_AF": "persiano (Afghanistan)",
  "fa_IR": "persiano (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fulah",
  "ff_CM": "fulah (Camerun)",
  "ff_GN": "fulah (Guinea)",
  "ff_MR": "fulah (Mauritania)",
  "ff_SN": "fulah (Senegal)",
  "fi": "finlandese",
  "fi_FI": "finlandese (Finlandia)",
  "fil": "filippino",
  "fit": "finlandese del Tornedalen",
  "fiu": "lingua ungrofinnica",
  "fj": "figiano",
  "fo": "faroese",
  "fo_FO": "faroese (Isole Faroe)",
  "fon": "fon",
  "fr": "francese",
  "fr_BE": "francese (Belgio)",
  "fr_BF": "francese (Burkina Faso)",
  "fr_BI": "francese (Burundi)",
  "fr_BJ": "francese (Benin)",
  "fr_BL": "francese (Saint-Barthélemy)",
  "fr_CA": "francese (Canada)",
  "fr_CD": "francese (Congo - Kinshasa)",
  "fr_CF": "francese (Repubblica Centrafricana)",
  "fr_CG": "francese (Congo-Brazzaville)",
  "fr_CH": "francese (Svizzera)",
  "fr_CI": "francese (Costa d’Avorio)",
  "fr_CM": "francese (Camerun)",
  "fr_DJ": "francese (Gibuti)",
  "fr_DZ": "francese (Algeria)",
  "fr_FR": "francese (Francia)",
  "fr_GA": "francese (Gabon)",
  "fr_GF": "francese (Guiana Francese)",
  "fr_GN": "francese (Guinea)",
  "fr_GP": "francese (Guadalupa)",
  "fr_GQ": "francese (Guinea Equatoriale)",
  "fr_HT": "francese (Haiti)",
  "fr_KM": "francese (Comore)",
  "fr_LU": "francese (Lussemburgo)",
  "fr_MA": "francese (Marocco)",
  "fr_MC": "francese (Monaco)",
  "fr_MF": "francese (Saint Martin)",
  "fr_MG": "francese (Madagascar)",
  "fr_ML": "francese (Mali)",
  "fr_MQ": "francese (Martinica)",
  "fr_MR": "francese (Mauritania)",
  "fr_MU": "francese (Mauritius)",
  "fr_NC": "francese (Nuova Caledonia)",
  "fr_NE": "francese (Niger)",
  "fr_PF": "francese (Polinesia Francese)",
  "fr_PM": "francese (Saint Pierre e Miquelon)",
  "fr_RE": "francese (Réunion)",
  "fr_RW": "francese (Ruanda)",
  "fr_SC": "francese (Seychelles)",
  "fr_SN": "francese (Senegal)",
  "fr_SY": "francese (Siria)",
  "fr_TD": "francese (Ciad)",
  "fr_TG": "francese (Togo)",
  "fr_TN": "francese (Tunisia)",
  "fr_VU": "francese (Vanuatu)",
  "fr_WF": "francese (Wallis e Futuna)",
  "fr_YT": "francese (Mayotte)",
  "frc": "francese cajun",
  "frm": "francese medio",
  "fro": "francese antico",
  "frp": "francoprovenzale",
  "frr": "frisone settentrionale",
  "frs": "frisone orientale",
  "fur": "friulano",
  "fy": "frisone occidentale",
  "fy_NL": "frisone occidentale (Paesi Bassi)",
  "ga": "irlandese",
  "ga_IE": "irlandese (Irlanda)",
  "gaa": "ga",
  "gag": "gagauzo",
  "gan": "gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "dari zoroastriano",
  "gd": "gaelico scozzese",
  "gd_GB": "gaelico scozzese (Regno Unito)",
  "gem": "lingua germanica",
  "gez": "geez",
  "gil": "gilbertese",
  "gl": "galiziano",
  "gl_ES": "galiziano (Spagna)",
  "glk": "gilaki",
  "gmh": "tedesco medio alto",
  "gn": "guaraní",
  "goh": "tedesco antico alto",
  "gom": "konkani goano",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotico",
  "grb": "grebo",
  "grc": "greco antico",
  "gsw": "tedesco svizzero",
  "gu": "gujarati",
  "gu_IN": "gujarati (India)",
  "guc": "wayuu",
  "gur": "Frafra",
  "guz": "gusii",
  "gv": "mannese",
  "gv_IM": "manx (Isola di Man)",
  "gwi": "gwichʼin",
  "ha": "hausa",
  "ha_GH": "hausa (Ghana)",
  "ha_Latn": "hausa (latino)",
  "ha_Latn_GH": "hausa (latino, Ghana)",
  "ha_Latn_NE": "hausa (latino, Niger)",
  "ha_Latn_NG": "hausa (latino, Nigeria)",
  "ha_NE": "hausa (Niger)",
  "ha_NG": "hausa (Nigeria)",
  "hai": "haida",
  "hak": "hakka",
  "haw": "hawaiano",
  "he": "ebraico",
  "he_IL": "ebraico (Israele)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "hindi figiano",
  "hil": "ilongo",
  "him": "himachali",
  "hit": "hittite",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croato",
  "hr_BA": "croato (Bosnia-Erzegovina)",
  "hr_HR": "croato (Croazia)",
  "hsb": "alto sorabo",
  "hsn": "xiang",
  "ht": "haitiano",
  "hu": "ungherese",
  "hu_HU": "ungherese (Ungheria)",
  "hup": "hupa",
  "hy": "armeno",
  "hy_AM": "armeno (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonesiano",
  "id_ID": "indonesiano (Indonesia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigeria)",
  "ii": "sichuan yi",
  "ii_CN": "sichuan yi (Cina)",
  "ik": "inupiak",
  "ilo": "ilocano",
  "inc": "lingua indiana",
  "ine": "lingua indoeuropea",
  "inh": "ingush",
  "io": "ido",
  "ira": "iraniana",
  "iro": "lingue irochesi",
  "is": "islandese",
  "is_IS": "islandese (Islanda)",
  "it": "italiano",
  "it_CH": "italiano (Svizzera)",
  "it_IT": "italiano (Italia)",
  "it_SM": "italiano (San Marino)",
  "iu": "inuktitut",
  "izh": "ingrico",
  "ja": "giapponese",
  "ja_JP": "giapponese (Giappone)",
  "jam": "creolo giamaicano",
  "jbo": "lojban",
  "jgo": "ngamambo",
  "jmc": "machame",
  "jpr": "giudeo persiano",
  "jrb": "giudeo arabo",
  "jut": "jutlandico",
  "jv": "giavanese",
  "ka": "georgiano",
  "ka_GE": "georgiano (Georgia)",
  "kaa": "kara-kalpak",
  "kab": "cabilo",
  "kac": "kachin",
  "kaj": "kai",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "cabardino",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "capoverdiano",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "kaingang",
  "kha": "khasi",
  "khi": "lingua khoisan",
  "kho": "khotanese",
  "khq": "koyra chiini",
  "khw": "khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenya)",
  "kiu": "kirmanjki",
  "kj": "kuanyama",
  "kk": "kazako",
  "kk_Cyrl": "kazako (cirillico)",
  "kk_Cyrl_KZ": "kazako (cirillico, Kazakistan)",
  "kk_KZ": "kazako (Kazakistan)",
  "kkj": "kako",
  "kl": "groenlandese",
  "kl_GL": "kalaallisut (Groenlandia)",
  "kln": "kalenjin",
  "km": "khmer",
  "km_KH": "khmer (Cambogia)",
  "kmb": "kimbundu",
  "kn": "kannada",
  "kn_IN": "kannada (India)",
  "ko": "coreano",
  "ko_KP": "coreano (Corea del Nord)",
  "ko_KR": "coreano (Corea del Sud)",
  "koi": "permiaco",
  "kok": "konkani",
  "kos": "kosraean",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "careliano",
  "kro": "kru",
  "kru": "kurukh",
  "ks": "kashmiri",
  "ks_Arab": "kashmiri (arabo)",
  "ks_Arab_IN": "kashmiri (arabo, India)",
  "ks_IN": "kashmiri (India)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "coloniese",
  "ku": "curdo",
  "kum": "kumyk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "cornico",
  "kw_GB": "cornico (Regno Unito)",
  "ky": "kirghiso",
  "ky_Cyrl": "chirghiso (cirillico)",
  "ky_Cyrl_KG": "chirghiso (cirillico, Kirghizistan)",
  "ky_KG": "chirghiso (Kirghizistan)",
  "la": "latino",
  "lad": "giudeo-spagnolo",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "lussemburghese",
  "lb_LU": "lussemburghese (Lussemburgo)",
  "lez": "lesgo",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburghese",
  "lij": "ligure",
  "liv": "livone",
  "lkt": "lakota",
  "lmo": "lombardo",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Congo - Kinshasa)",
  "ln_CF": "lingala (Repubblica Centrafricana)",
  "ln_CG": "lingala (Congo-Brazzaville)",
  "lo": "lao",
  "lo_LA": "lao (Laos)",
  "lol": "lolo bantu",
  "lou": "creolo della Louisiana",
  "loz": "lozi",
  "lrc": "luri settentrionale",
  "lt": "lituano",
  "lt_LT": "lituano (Lituania)",
  "ltg": "letgallo",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Congo - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushai",
  "luy": "luyia",
  "lv": "lettone",
  "lv_LV": "lettone (Lettonia)",
  "lzh": "cinese classico",
  "lzz": "laz",
  "mad": "madurese",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "mandingo",
  "map": "austronesiano",
  "mas": "masai",
  "mde": "maba",
  "mdf": "moksha",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "creolo mauriziano",
  "mg": "malgascio",
  "mg_MG": "malgascio (Madagascar)",
  "mga": "irlandese medio",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshallese",
  "mi": "maori",
  "mic": "micmac",
  "min": "menangkabau",
  "mis": "lingue diverse",
  "mk": "macedone",
  "mk_MK": "macedone (Repubblica di Macedonia)",
  "mkh": "lingua mon-khmer",
  "ml": "malayalam",
  "ml_IN": "malayalam (India)",
  "mn": "mongolo",
  "mn_Cyrl": "mongolo (cirillico)",
  "mn_Cyrl_MN": "mongolo (cirillico, Mongolia)",
  "mn_MN": "mongolo (Mongolia)",
  "mnc": "manchu",
  "mni": "manipuri",
  "mno": "manobo",
  "mo": "moldavo",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "mari occidentale",
  "ms": "malese",
  "ms_BN": "malese (Brunei)",
  "ms_Latn": "malese (latino)",
  "ms_Latn_BN": "malese (latino, Brunei)",
  "ms_Latn_MY": "malese (latino, Malesia)",
  "ms_Latn_SG": "malese (latino, Singapore)",
  "ms_MY": "malese (Malesia)",
  "ms_SG": "malese (Singapore)",
  "mt": "maltese",
  "mt_MT": "maltese (Malta)",
  "mua": "mundang",
  "mul": "multilingua",
  "mun": "lingua munda",
  "mus": "creek",
  "mwl": "mirandese",
  "mwr": "marwari",
  "mwv": "mentawai",
  "my": "birmano",
  "my_MM": "birmano (Myanmar (Birmania))",
  "mye": "myene",
  "myn": "lingue maya",
  "myv": "erzya",
  "mzn": "mazandarani",
  "na": "nauru",
  "nah": "nahuatl",
  "nai": "lingua indiana del Nord America",
  "nan": "min nan",
  "nap": "napoletano",
  "naq": "nama",
  "nb": "norvegese bokmål",
  "nb_NO": "norvegese bokmål (Norvegia)",
  "nb_SJ": "norvegese bokmål (Svalbard e Jan Mayen)",
  "nd": "ndebele del nord",
  "nd_ZW": "ndebele del nord (Zimbabwe)",
  "nds": "basso tedesco",
  "nds_NL": "basso tedesco olandese",
  "ne": "nepalese",
  "ne_IN": "nepalese (India)",
  "ne_NP": "nepalese (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "lingua niger-cordofan",
  "niu": "niue",
  "njo": "ao",
  "nl": "olandese",
  "nl_AW": "olandese (Aruba)",
  "nl_BE": "olandese (Belgio)",
  "nl_BQ": "olandese (Caraibi Olandesi)",
  "nl_CW": "olandese (Curaçao)",
  "nl_NL": "olandese (Paesi Bassi)",
  "nl_SR": "olandese (Suriname)",
  "nl_SX": "olandese (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "norvegese nynorsk",
  "nn_NO": "norvegese nynorsk (Norvegia)",
  "nnh": "ngiemboon",
  "no": "norvegese",
  "no_NO": "norvegese (Norvegia)",
  "nog": "nogai",
  "non": "norse antico",
  "nov": "novial",
  "nqo": "n’ko",
  "nr": "ndebele del sud",
  "nso": "sotho del nord",
  "nub": "nubiano",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "newari classico",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "occitano",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiopia)",
  "om_KE": "oromo (Kenya)",
  "or": "odia",
  "or_IN": "oriya (India)",
  "os": "ossetico",
  "os_GE": "ossetico (Georgia)",
  "os_RU": "ossetico (Federazione Russa)",
  "osa": "osage",
  "ota": "turco ottomano",
  "oto": "lingue otomi",
  "pa": "punjabi",
  "pa_Arab": "punjabi (arabo)",
  "pa_Arab_PK": "punjabi (arabo, Pakistan)",
  "pa_Guru": "punjabi (gurmukhi)",
  "pa_Guru_IN": "punjabi (gurmukhi, India)",
  "pa_IN": "punjabi (India)",
  "pa_PK": "punjabi (Pakistan)",
  "paa": "lingua papuana",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palau",
  "pcd": "piccardo",
  "pcm": "pidgin nigeriano",
  "pdc": "tedesco della Pennsylvania",
  "pdt": "Plautdietsch",
  "peo": "persiano antico",
  "pfl": "tedesco palatino",
  "phi": "lingua filippina",
  "phn": "fenicio",
  "pi": "pali",
  "pl": "polacco",
  "pl_PL": "polacco (Polonia)",
  "pms": "piemontese",
  "pnt": "pontico",
  "pon": "ponape",
  "pra": "pracrito",
  "prg": "prussiano",
  "pro": "provenzale antico",
  "ps": "pashto",
  "ps_AF": "pashto (Afghanistan)",
  "pt": "portoghese",
  "pt_AO": "portoghese (Angola)",
  "pt_BR": "portoghese (Brasile)",
  "pt_CV": "portoghese (Capo Verde)",
  "pt_GW": "portoghese (Guinea-Bissau)",
  "pt_MO": "portoghese (RAS di Macao)",
  "pt_MZ": "portoghese (Mozambico)",
  "pt_PT": "portoghese (Portogallo)",
  "pt_ST": "portoghese (São Tomé e Príncipe)",
  "pt_TL": "portoghese (Timor Est)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivia)",
  "qu_EC": "quechua (Ecuador)",
  "qu_PE": "quechua (Perù)",
  "quc": "k’iche’",
  "qug": "quechua dell’altopiano del Chimborazo",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotonga",
  "rgn": "romagnolo",
  "rif": "tarifit",
  "rm": "romancio",
  "rm_CH": "romancio (Svizzera)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "rumeno",
  "ro_MD": "rumeno (Moldavia)",
  "ro_RO": "rumeno (Romania)",
  "roa": "lingua romanza",
  "rof": "rombo",
  "rom": "romani",
  "root": "root",
  "rtm": "rotumano",
  "ru": "russo",
  "ru_BY": "russo (Bielorussia)",
  "ru_KG": "russo (Kirghizistan)",
  "ru_KZ": "russo (Kazakistan)",
  "ru_MD": "russo (Moldavia)",
  "ru_RU": "russo (Federazione Russa)",
  "ru_UA": "russo (Ucraina)",
  "rue": "ruteno",
  "rug": "roviana",
  "rup": "arumeno",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Ruanda)",
  "rwk": "rwa",
  "sa": "sanscrito",
  "sad": "sandawe",
  "sah": "yakut",
  "sai": "lingua indiana del Sud America",
  "sal": "lingue salish",
  "sam": "aramaico samaritano",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardo",
  "scn": "siciliano",
  "sco": "scozzese",
  "sd": "sindhi",
  "sdc": "sassarese",
  "sdh": "curdo meridionale",
  "se": "sami del nord",
  "se_FI": "sami del nord (Finlandia)",
  "se_NO": "sami del nord (Norvegia)",
  "se_SE": "sami del nord (Svezia)",
  "see": "seneca",
  "seh": "sena",
  "sei": "seri",
  "sel": "selkup",
  "sem": "lingua semitica",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (Repubblica Centrafricana)",
  "sga": "irlandese antico",
  "sgn": "lingue sign",
  "sgs": "samogitico",
  "sh": "serbo-croato",
  "sh_BA": "serbo-croato (Bosnia-Erzegovina)",
  "shi": "tashelhit",
  "shn": "shan",
  "shu": "arabo ciadiano",
  "si": "singalese",
  "si_LK": "singalese (Sri Lanka)",
  "sid": "sidamo",
  "sio": "lingue sioux",
  "sit": "lingua sino-tibetana",
  "sk": "slovacco",
  "sk_SK": "slovacco (Slovacchia)",
  "sl": "sloveno",
  "sl_SI": "sloveno (Slovenia)",
  "sla": "lingua slava",
  "sli": "tedesco slesiano",
  "sly": "selayar",
  "sm": "samoano",
  "sma": "sami del sud",
  "smi": "lingua sami",
  "smj": "sami di Lule",
  "smn": "sami di Inari",
  "sms": "sami skolt",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabwe)",
  "snk": "soninke",
  "so": "somalo",
  "so_DJ": "somalo (Gibuti)",
  "so_ET": "somalo (Etiopia)",
  "so_KE": "somalo (Kenya)",
  "so_SO": "somalo (Somalia)",
  "sog": "sogdiano",
  "son": "songhai",
  "sq": "albanese",
  "sq_AL": "albanese (Albania)",
  "sq_MK": "albanese (Repubblica di Macedonia)",
  "sq_XK": "albanese (Kosovo)",
  "sr": "serbo",
  "sr_BA": "serbo (Bosnia-Erzegovina)",
  "sr_Cyrl": "serbo (cirillico)",
  "sr_Cyrl_BA": "serbo (cirillico, Bosnia-Erzegovina)",
  "sr_Cyrl_ME": "serbo (cirillico, Montenegro)",
  "sr_Cyrl_RS": "serbo (cirillico, Serbia)",
  "sr_Cyrl_XK": "serbo (cirillico, Kosovo)",
  "sr_Latn": "serbo (latino)",
  "sr_Latn_BA": "serbo (latino, Bosnia-Erzegovina)",
  "sr_Latn_ME": "serbo (latino, Montenegro)",
  "sr_Latn_RS": "serbo (latino, Serbia)",
  "sr_Latn_XK": "serbo (latino, Kosovo)",
  "sr_ME": "serbo (Montenegro)",
  "sr_RS": "serbo (Serbia)",
  "sr_XK": "serbo (Kosovo)",
  "srn": "sranan tongo",
  "srr": "serer",
  "ss": "swati",
  "ssa": "lingua nilo-sahariana",
  "ssy": "saho",
  "st": "sotho del sud",
  "stq": "saterfriesisch",
  "su": "sundanese",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumero",
  "sv": "svedese",
  "sv_AX": "svedese (Isole Aland)",
  "sv_FI": "svedese (Finlandia)",
  "sv_SE": "svedese (Svezia)",
  "sw": "swahili",
  "sw_CD": "swahili del Congo",
  "sw_KE": "swahili (Kenya)",
  "sw_TZ": "swahili (Tanzania)",
  "sw_UG": "swahili (Uganda)",
  "swb": "comoriano",
  "swc": "congo swahili",
  "syc": "siriaco classico",
  "syr": "siriaco",
  "szl": "slesiano",
  "ta": "tamil",
  "ta_IN": "tamil (India)",
  "ta_LK": "tamil (Sri Lanka)",
  "ta_MY": "tamil (Malesia)",
  "ta_SG": "tamil (Singapore)",
  "tai": "lingua tailandese",
  "tcy": "tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tetum",
  "tg": "tagico",
  "th": "thai",
  "th_TH": "thai (Tailandia)",
  "ti": "tigrino",
  "ti_ER": "tigrino (Eritrea)",
  "ti_ET": "tigrino (Etiopia)",
  "tig": "tigre",
  "tiv": "tiv",
  "tk": "turcomanno",
  "tkl": "tokelau",
  "tkr": "tsakhur",
  "tl": "tagalog",
  "tl_PH": "tagalog (Filippine)",
  "tlh": "klingon",
  "tli": "tlingit",
  "tly": "taliscio",
  "tmh": "tamashek",
  "tn": "tswana",
  "to": "tongano",
  "to_TO": "tongano (Tonga)",
  "tog": "nyasa del Tonga",
  "tpi": "tok pisin",
  "tr": "turco",
  "tr_CY": "turco (Cipro)",
  "tr_TR": "turco (Turchia)",
  "tru": "turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "zaconico",
  "tsi": "tsimshian",
  "tt": "tataro",
  "ttt": "tat islamico",
  "tum": "tumbuka",
  "tup": "lingue tupi",
  "tut": "lingua altaica",
  "tvl": "tuvalu",
  "tw": "ci",
  "twq": "tasawaq",
  "ty": "taitiano",
  "tyv": "tuvinian",
  "tzm": "tamazight",
  "udm": "udmurt",
  "ug": "uiguro",
  "ug_Arab": "uiguro (arabo)",
  "ug_Arab_CN": "uiguro (arabo, Cina)",
  "ug_CN": "uiguro (Cina)",
  "uga": "ugaritico",
  "uk": "ucraino",
  "uk_UA": "ucraino (Ucraina)",
  "umb": "mbundu",
  "und": "lingua imprecisata",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakistan)",
  "uz": "uzbeco",
  "uz_AF": "usbeco (Afghanistan)",
  "uz_Arab": "usbeco (arabo)",
  "uz_Arab_AF": "usbeco (arabo, Afghanistan)",
  "uz_Cyrl": "usbeco (cirillico)",
  "uz_Cyrl_UZ": "usbeco (cirillico, Uzbekistan)",
  "uz_Latn": "usbeco (latino)",
  "uz_Latn_UZ": "usbeco (latino, Uzbekistan)",
  "uz_UZ": "usbeco (Uzbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "veneto",
  "vep": "vepso",
  "vi": "vietnamita",
  "vi_VN": "vietnamita (Vietnam)",
  "vls": "fiammingo occidentale",
  "vmf": "Main-Franconian",
  "vo": "volapük",
  "vot": "voto",
  "vro": "võro",
  "vun": "vunjo",
  "wa": "vallone",
  "wae": "walser",
  "wak": "lingue wakash",
  "wal": "walamo",
  "war": "waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wen": "sorabo",
  "wo": "wolof",
  "wuu": "wu",
  "xal": "kalmyk",
  "xh": "xhosa",
  "xmf": "mengrelio",
  "xog": "soga",
  "yao": "yao (bantu)",
  "yap": "yapese",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "yiddish",
  "yo": "yoruba",
  "yo_BJ": "yoruba (Benin)",
  "yo_NG": "yoruba (Nigeria)",
  "ypk": "lingue yupik",
  "yrl": "nheengatu",
  "yue": "cantonese",
  "za": "zhuang",
  "zap": "zapotec",
  "zbl": "blissymbol",
  "zea": "zelandese",
  "zen": "zenaga",
  "zgh": "tamazight del Marocco standard",
  "zh": "cinese",
  "zh_CN": "cinese (Cina)",
  "zh_HK": "cinese (RAS di Hong Kong)",
  "zh_Hans": "cinese (semplificato)",
  "zh_Hans_CN": "cinese (semplificato, Cina)",
  "zh_Hans_HK": "cinese (semplificato, RAS di Hong Kong)",
  "zh_Hans_MO": "cinese (semplificato, RAS di Macao)",
  "zh_Hans_SG": "cinese (semplificato, Singapore)",
  "zh_Hant": "cinese (tradizionale)",
  "zh_Hant_HK": "cinese (tradizionale, RAS di Hong Kong)",
  "zh_Hant_MO": "cinese (tradizionale, RAS di Macao)",
  "zh_Hant_TW": "cinese (tradizionale, Taiwan)",
  "zh_MO": "cinese (RAS di Macao)",
  "zh_SG": "cinese (Singapore)",
  "zh_TW": "cinese (Taiwan)",
  "znd": "zande",
  "zu": "zulu",
  "zu_ZA": "zulu (Sudafrica)",
  "zun": "zuni",
  "zxx": "nessun contenuto linguistico",
  "zza": "zaza"
};
