const names = {
  "001": "an Domhan",
  "002": "an Afraic",
  "003": "Meiriceá Thuaidh",
  "005": "Meiriceá Theas",
  "009": "an Aigéine",
  "011": "Iarthar na hAfraice",
  "013": "Meiriceá Láir",
  "014": "Oirthear na hAfraice",
  "015": "Tuaisceart na hAfraice",
  "017": "an Afraic Láir",
  "018": "Deisceart na hAfraice",
  "019": "Críocha Mheiriceá",
  "021": "Tuaisceart Mheiriceá",
  "029": "an Mhuir Chairib",
  "030": "Oirthear na hÁise",
  "034": "Deisceart na hÁise",
  "035": "Oirdheisceart na hÁise",
  "039": "Deisceart na hEorpa",
  "053": "an Astraláise",
  "054": "an Mheilinéis",
  "057": "an Réigiún Micrinéiseach",
  "061": "an Pholainéis",
  "062": "Áise Theas-Lár",
  "142": "an Áise",
  "143": "an Áise Láir",
  "145": "Iarthar na hÁise",
  "150": "an Eoraip",
  "151": "Oirthear na hEorpa",
  "154": "Tuaisceart na hEorpa",
  "155": "Iarthar na hEorpa",
  "172": "Comhlathas na Stát Neamhspleách",
  "200": "Seicslóvaic",
  "202": "an Afraic fho-Shahárach",
  "419": "Meiriceá Laidineach",
  "830": "Oileáin Mhuir nIocht",
  "AC": "Oileán na Deascabhála",
  "AD": "Andóra",
  "AE": "Aontas na nÉimíríochtaí Arabacha",
  "AF": "an Afganastáin",
  "AG": "Antigua agus Barbúda",
  "AI": "Angaíle",
  "AL": "an Albáin",
  "AM": "an Airméin",
  "AN": "Antillí na hÍsiltíre",
  "AO": "Angóla",
  "AQ": "an Antartaice",
  "AR": "an Airgintín",
  "AS": "Samó Mheiriceá",
  "AT": "an Ostair",
  "AU": "an Astráil",
  "AW": "Arúba",
  "AX": "Oileáin Åland",
  "AZ": "an Asarbaiseáin",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Albánach Cugasach",
  "Ahom": "Ahom",
  "Arab": "Arabach",
  "Aran": "Nastaliq",
  "Armi": "Aramach Impiriúil",
  "Armn": "Airméanach",
  "Avst": "Aivéisteach",
  "BA": "an Bhoisnia agus an Heirseagaivéin",
  "BB": "Barbadós",
  "BD": "an Bhanglaidéis",
  "BE": "an Bheilg",
  "BF": "Buircíne Fasó",
  "BG": "an Bhulgáir",
  "BH": "Bairéin",
  "BI": "an Bhurúin",
  "BJ": "Beinin",
  "BL": "Saint Barthélemy",
  "BM": "Beirmiúda",
  "BN": "Brúiné",
  "BO": "an Bholaiv",
  "BQ": "an Ísiltír Chairibeach",
  "BR": "an Bhrasaíl",
  "BS": "na Bahámaí",
  "BT": "an Bhútáin",
  "BV": "Oileán Bouvet",
  "BW": "an Bhotsuáin",
  "BY": "an Bhealarúis",
  "BZ": "an Bheilís",
  "Bali": "Bailíoch",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batacach",
  "Beng": "Beangálach",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Buigineach",
  "Buhd": "Buthaideach",
  "CA": "Ceanada",
  "CC": "Oileáin Cocos (Keeling)",
  "CD": "Poblacht Dhaonlathach an Chongó",
  "CF": "Poblacht na hAfraice Láir",
  "CG": "an Congó",
  "CH": "an Eilvéis",
  "CI": "an Cósta Eabhair",
  "CK": "Oileáin Cook",
  "CL": "an tSile",
  "CM": "Camarún",
  "CN": "an tSín",
  "CO": "an Cholóim",
  "CP": "Oileán Clipperton",
  "CR": "Cósta Ríce",
  "CS": "An tSeirbia agus Montainéagró",
  "CU": "Cúba",
  "CV": "Rinn Verde",
  "CW": "Curaçao",
  "CX": "Oileán na Nollag",
  "CY": "an Chipir",
  "CZ": "an tSeicia",
  "Cakm": "Chakma",
  "Cans": "Siollach Bundúchasach Ceanadach Aontaithe",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Seiricíoch",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Coptach",
  "Cprt": "Cipireach",
  "Cyrl": "Coireallach",
  "Cyrs": "Coireallach Slavach Sean-Eaglais",
  "DD": "Oirthear na Gearmáine",
  "DE": "an Ghearmáin",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "an Danmhairg",
  "DM": "Doiminice",
  "DO": "an Phoblacht Dhoiminiceach",
  "DZ": "an Ailgéir",
  "Deva": "Déiveanágrach",
  "Diak": "Léim Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Gearrscríobh Duployan",
  "EA": "Ceuta agus Melilla",
  "EC": "Eacuadór",
  "EE": "an Eastóin",
  "EG": "an Éigipt",
  "EH": "an Sahára Thiar",
  "ER": "an Eiritré",
  "ES": "an Spáinn",
  "ET": "an Aetóip",
  "EU": "an tAontas Eorpach",
  "EZ": "Limistéar an euro",
  "Egyd": "Éigipteach coiteann",
  "Egyh": "Éigipteach cliarúil",
  "Egyp": "Iairiglifí Éigipteacha",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "Aetópach",
  "FI": "an Fhionlainn",
  "FJ": "Fidsí",
  "FK": "Oileáin Fháclainne",
  "FM": "an Mhicrinéis",
  "FO": "Oileáin Fharó",
  "FR": "an Fhrainc",
  "FX": "An Fhrainc Chathrach",
  "GA": "an Ghabúin",
  "GB": "an Ríocht Aontaithe",
  "GD": "Greanáda",
  "GE": "an tSeoirsia",
  "GF": "Guáin na Fraince",
  "GG": "Geansaí",
  "GH": "Gána",
  "GI": "Giobráltar",
  "GL": "an Ghraonlainn",
  "GM": "an Ghaimbia",
  "GN": "an Ghuine",
  "GP": "Guadalúip",
  "GQ": "an Ghuine Mheánchiorclach",
  "GR": "an Ghréig",
  "GS": "an tSeoirsia Theas agus Oileáin Sandwich Theas",
  "GT": "Guatamala",
  "GU": "Guam",
  "GW": "Guine Bissau",
  "GY": "an Ghuáin",
  "Geok": "Khutsuri Seoirseach",
  "Geor": "Seoirseach",
  "Glag": "Glagalach",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gotach",
  "Gran": "Grantha",
  "Grek": "Gréagach",
  "Gujr": "Gúisearátach",
  "Guru": "Gurmúcach",
  "HK": "S.R.R. na Síne Hong Cong",
  "HM": "Oileán Heard agus Oileáin McDonald",
  "HN": "Hondúras",
  "HR": "an Chróit",
  "HT": "Háítí",
  "HU": "an Ungáir",
  "Hanb": "Han agus Bopomofo",
  "Hang": "Hangalach",
  "Hani": "Han",
  "Hano": "Hananúis",
  "Hans": "Simplithe",
  "Hant": "Traidisiúnta",
  "Hatr": "Hatran",
  "Hebr": "Eabhrach",
  "Hira": "Hireagánach",
  "Hluw": "Iairiglifí Anatólacha",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Siollabraí Seapánacha",
  "Hung": "Sean-Ungárach",
  "IC": "na hOileáin Chanáracha",
  "ID": "an Indinéis",
  "IE": "Éire",
  "IL": "Iosrael",
  "IM": "Oileán Mhanann",
  "IN": "an India",
  "IO": "Críoch Aigéan Indiach na Breataine",
  "IQ": "an Iaráic",
  "IR": "an Iaráin",
  "IS": "an Íoslainn",
  "IT": "an Iodáil",
  "Inds": "Indus",
  "Ital": "Sean-Iodáilic",
  "JE": "Geirsí",
  "JM": "Iamáice",
  "JO": "an Iordáin",
  "JP": "an tSeapáin",
  "Jamo": "Seamó",
  "Java": "Iávach",
  "Jpan": "Seapánach",
  "Jurc": "Jurchen",
  "KE": "an Chéinia",
  "KG": "an Chirgeastáin",
  "KH": "an Chambóid",
  "KI": "Cireabaití",
  "KM": "Oileáin Chomóra",
  "KN": "San Críostóir-Nimheas",
  "KP": "an Chóiré Thuaidh",
  "KR": "an Chóiré Theas",
  "KW": "Cuáit",
  "KY": "Oileáin Cayman",
  "KZ": "an Chasacstáin",
  "Kali": "Kayah Li",
  "Kana": "Catacánach",
  "Khar": "Kharoshthi",
  "Khmr": "Ciméarach",
  "Khoj": "Khojki",
  "Kits": "Script beag Khitan",
  "Knda": "Cannadach",
  "Kore": "Cóiréach",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "an Liobáin",
  "LC": "Saint Lucia",
  "LI": "Lichtinstéin",
  "LK": "Srí Lanca",
  "LR": "an Libéir",
  "LS": "Leosóta",
  "LT": "an Liotuáin",
  "LU": "Lucsamburg",
  "LV": "an Laitvia",
  "LY": "an Libia",
  "Lana": "Lanna",
  "Laoo": "Laosach",
  "Latf": "Laidin Fraktur",
  "Latg": "Cló Gaelach",
  "Latn": "Laidineach",
  "Lepc": "Lepcha",
  "Limb": "Liombúch",
  "Lina": "Líneach A",
  "Linb": "Líneach B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Liciach",
  "Lydi": "Lidiach",
  "MA": "Maracó",
  "MC": "Monacó",
  "MD": "an Mholdóiv",
  "ME": "Montainéagró",
  "MF": "Saint-Martin",
  "MG": "Madagascar",
  "MH": "Oileáin Marshall",
  "MI": "Oileáin Midway",
  "MK": "an Mhacadóin Thuaidh",
  "ML": "Mailí",
  "MM": "Maenmar (Burma)",
  "MN": "an Mhongóil",
  "MO": "S.R.R. na Síne Macao",
  "MP": "na hOileáin Mháirianacha Thuaidh",
  "MQ": "Martinique",
  "MR": "an Mháratáin",
  "MS": "Montsarat",
  "MT": "Málta",
  "MU": "Oileán Mhuirís",
  "MV": "Oileáin Mhaildíve",
  "MW": "an Mhaláiv",
  "MX": "Meicsiceo",
  "MY": "an Mhalaeisia",
  "MZ": "Mósaimbíc",
  "Mahj": "Mahasánach",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Mainicéasach",
  "Marc": "Marchen",
  "Maya": "Iairiglifí Máigheacha",
  "Medf": "Medefaidrin",
  "Mend": "Meindeach",
  "Merc": "Cúrsach Meroitic",
  "Mero": "Meroitic",
  "Mlym": "Mailéalamach",
  "Modi": "Modi",
  "Mong": "Mongólach",
  "Moon": "Gealach",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Maenmarach",
  "NA": "an Namaib",
  "NC": "an Nua-Chaladóin",
  "NE": "an Nígir",
  "NF": "Oileán Norfolk",
  "NG": "an Nigéir",
  "NI": "Nicearagua",
  "NL": "an Ísiltír",
  "NO": "an Iorua",
  "NP": "Neipeal",
  "NR": "Nárú",
  "NT": "Crios Neodrach",
  "NU": "Niue",
  "NZ": "an Nua-Shéalainn",
  "Nand": "Nandinagari",
  "Narb": "Sean-Arabach Thuaidh",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N-cóis",
  "Nshu": "Nüshu",
  "OM": "Óman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Oiríseach",
  "Osge": "Ósáis",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Críoch Iontaobhas Oileáin an Aigéin Chiúin",
  "PE": "Peiriú",
  "PF": "Polainéis na Fraince",
  "PG": "Nua-Ghuine Phapua",
  "PH": "na hOileáin Fhilipíneacha",
  "PK": "an Phacastáin",
  "PL": "an Pholainn",
  "PM": "San Pierre agus Miquelon",
  "PN": "Oileáin Pitcairn",
  "PR": "Pórtó Ríce",
  "PS": "na Críocha Palaistíneacha",
  "PT": "an Phortaingéil",
  "PU": "Oileáin Ilghnéitheacha an Aigéin Chiúin S.A.",
  "PW": "Oileáin Palau",
  "PY": "Paragua",
  "PZ": "Crios Canálach Panama",
  "Palm": "Palmyrene",
  "Pauc": "Pau Cin Hau",
  "Perm": "Sean-Pheirmeach",
  "Phag": "Phags-pa",
  "Phli": "Pahlavi inscríofa",
  "Phlp": "Salmóir Pahlavi",
  "Phlv": "Leabhar Pahlavi",
  "Phnx": "Féiníceach",
  "Plrd": "Pollard Foghrach",
  "Prti": "Pairtiach Inscríbhinniúil",
  "QA": "Catar",
  "QO": "an Aigéine Imeallach",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "an Rómáin",
  "RS": "an tSeirbia",
  "RU": "an Rúis",
  "RW": "Ruanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Rúnach",
  "SA": "an Araib Shádach",
  "SB": "Oileáin Sholomón",
  "SC": "na Séiséil",
  "SD": "an tSúdáin",
  "SE": "an tSualainn",
  "SG": "Singeapór",
  "SH": "San Héilin",
  "SI": "an tSlóivéin",
  "SJ": "Svalbard agus Jan Mayen",
  "SK": "an tSlóvaic",
  "SL": "Siarra Leon",
  "SM": "San Mairíne",
  "SN": "an tSeineagáil",
  "SO": "an tSomáil",
  "SR": "Suranam",
  "SS": "an tSúdáin Theas",
  "ST": "São Tomé agus Príncipe",
  "SU": "Aontas na bPoblacht Sóisialach Sóivéadach",
  "SV": "an tSalvadóir",
  "SX": "Sint Maarten",
  "SY": "an tSiria",
  "SZ": "eSuaitíní",
  "Samr": "Samárach",
  "Sara": "Sarati",
  "Sarb": "Sean-Arabach Theas",
  "Saur": "Saurashtra",
  "Sgnw": "Litritheoireacht Comharthaí",
  "Shaw": "Shawach",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "Siolónach",
  "Sogd": "Sogdian",
  "Sogo": "Sean Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundainéis",
  "Sylo": "Syloti Nagri",
  "Syrc": "Siriceach",
  "Syre": "Syriac Estrangelo",
  "Syrj": "Siriach an Iarthair",
  "Syrn": "Syriac an Oirthir",
  "TA": "Tristan da Cunha",
  "TC": "Oileáin na dTurcach agus Caicos",
  "TD": "Sead",
  "TF": "Críocha Francacha Dheisceart an Domhain",
  "TG": "Tóga",
  "TH": "an Téalainn",
  "TJ": "an Táidsíceastáin",
  "TK": "Tócalá",
  "TL": "Tíomór Thoir",
  "TM": "an Tuircméanastáin",
  "TN": "an Túinéis",
  "TO": "Tonga",
  "TR": "an Tuirc",
  "TT": "Oileán na Tríonóide agus Tobága",
  "TV": "Tuvalu",
  "TW": "an Téaváin",
  "TZ": "an Tansáin",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Deiheoingis",
  "Talu": "Tai Lue Nua",
  "Taml": "Tamalach",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Teileagúch",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagálagach",
  "Thaa": "Tánach",
  "Thai": "Téalannach",
  "Tibt": "Tibéadach",
  "Tirh": "Tirhuta",
  "UA": "an Úcráin",
  "UG": "Uganda",
  "UM": "Oileáin Imeallacha S.A.M.",
  "UN": "na Náisiúin Aontaithe",
  "US": "Stáit Aontaithe Mheiriceá",
  "UY": "Uragua",
  "UZ": "an Úisbéiceastáin",
  "Ugar": "Úgairíteach",
  "VA": "Cathair na Vatacáine",
  "VC": "San Uinseann agus na Greanáidíní",
  "VD": "Vítneam Thuaidh",
  "VE": "Veiniséala",
  "VG": "Oileáin Bhriotanacha na Maighdean",
  "VI": "Oileáin Mheiriceánacha na Maighdean",
  "VN": "Vítneam",
  "VU": "Vanuatú",
  "Vaii": "Vadhais",
  "Visp": "Óráid Infheicthe",
  "WF": "Vailís agus Futúna",
  "WK": "Oileán Wake",
  "WS": "Samó",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Bréagdhiaicriticí",
  "XB": "Bréag-Bidi",
  "XK": "an Chosaiv",
  "Xpeo": "Sean-Pheirseach",
  "Xsux": "Dingchruthach Suiméar-Acádach",
  "YD": "Poblacht Dhaonlathach Éimin",
  "YE": "Éimin",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Ís",
  "ZA": "an Afraic Theas",
  "ZM": "an tSaimbia",
  "ZW": "an tSiombáib",
  "ZZ": "Réigiún Anaithnid",
  "Zanb": "Cearnóg Zanabazar",
  "Zinh": "Oidhreacht",
  "Zmth": "Nodaireacht Mhatamaiticiúil",
  "Zsye": "Emoji",
  "Zsym": "Siombailí",
  "Zxxx": "Gan Scríobh",
  "Zyyy": "Coitianta",
  "Zzzz": "Script Anaithnid",
  "aa": "Afáiris",
  "ab": "Abcáisis",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adaigéis",
  "ae": "Aivéistis",
  "aeb": "Tunisian Arabic",
  "af": "Afracáinis",
  "af_NA": "Afracáinis (An Namaib)",
  "af_ZA": "Afracáinis (An Afraic Theas)",
  "afa": "Teanga Afra-Asiatach",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Aidhniúis",
  "ak": "Acáinis",
  "ak_GH": "Acáinis (Gána)",
  "akk": "Acáidis",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Teanga Algonquian",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Amáiris",
  "am_ET": "Amáiris (An Aetóip)",
  "an": "Aragóinis",
  "ang": "Sean-Bhéarla",
  "anp": "Angika",
  "apa": "Teanga Apache",
  "ar": "Araibis",
  "ar_001": "Araibis Chaighdeánach",
  "ar_AE": "Araibis (Aontas na nÉimíríochtaí Arabacha)",
  "ar_BH": "Araibis (Bairéin)",
  "ar_DJ": "Araibis (Djibouti)",
  "ar_DZ": "Araibis (An Ailgéir)",
  "ar_EG": "Araibis (An Éigipt)",
  "ar_EH": "Araibis (An Sahára Thiar)",
  "ar_ER": "Araibis (An Eiritré)",
  "ar_IL": "Araibis (Iosrael)",
  "ar_IQ": "Araibis (An Iaráic)",
  "ar_JO": "Araibis (An Iordáin)",
  "ar_KM": "Araibis (Oileáin Chomóra)",
  "ar_KW": "Araibis (Cuáit)",
  "ar_LB": "Araibis (An Liobáin)",
  "ar_LY": "Araibis (An Libia)",
  "ar_MA": "Araibis (Maracó)",
  "ar_MR": "Araibis (An Mháratáin)",
  "ar_OM": "Araibis (Óman)",
  "ar_PS": "Araibis (Na Críocha Palaistíneacha)",
  "ar_QA": "Araibis (Catar)",
  "ar_SA": "Araibis (An Araib Shádach)",
  "ar_SD": "Araibis (An tSúdáin)",
  "ar_SO": "Araibis (An tSomáil)",
  "ar_SS": "Araibis (An tSúdáin Theas)",
  "ar_SY": "Araibis (An tSiria)",
  "ar_TD": "Araibis (Sead)",
  "ar_TN": "Araibis (An Túinéis)",
  "ar_YE": "Araibis (Éimin)",
  "arc": "Aramais",
  "arn": "Mapúitsis",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "ars": "Araibis Najdi",
  "art": "Teanga Saorga",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Asaimis",
  "as_IN": "Asaimis (An India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Astúiris",
  "ath": "Teanga Athapascan",
  "aus": "Teanga na hAstráile",
  "av": "Aváiris",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aidhmiris",
  "az": "Asarbaiseáinis",
  "az_AZ": "Asarbaiseáinis (An Asarbaiseáin)",
  "az_Arab": "Asarbaiseáinis (Araibis)",
  "az_Cyrl": "Asarbaiseáinis (Coireallach)",
  "az_Cyrl_AZ": "Asarbaiseáinis (Coireallach, An Asarbaiseáin)",
  "az_Latn": "Asarbaiseáinis (Laidineach)",
  "az_Latn_AZ": "Asarbaiseáinis (Laidineach, An Asarbaiseáin)",
  "azb": "South Azerbaijani",
  "ba": "Baiscíris",
  "bad": "Banda",
  "bai": "Teanga Bamileke",
  "bal": "Baluchi",
  "ban": "Bailís",
  "bar": "Baváiris",
  "bas": "Basaa",
  "bat": "Teanga Mhuir Bhailt",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Bealarúisis",
  "be_BY": "Bealarúisis (An Bhealarúis)",
  "bej": "Beja",
  "bem": "Beimbis",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgáiris",
  "bg_BG": "Bulgáiris (An Bhulgáir)",
  "bgn": "Balochi an Iarthair",
  "bh": "Bihairis",
  "bho": "Bhojpuri",
  "bi": "Bioslaimis",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambairis",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Beangáilis",
  "bn_BD": "Beangáilis (An Bhanglaidéis)",
  "bn_IN": "Beangáilis (An India)",
  "bnt": "Bantu",
  "bo": "Tibéidis",
  "bo_CN": "Tibéidis (An tSín)",
  "bo_IN": "Tibéidis (An India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Briotáinis",
  "br_FR": "Briotáinis (An Fhrainc)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Boisnis",
  "bs_BA": "Boisnis (An Bhoisnia agus An Heirseagaivéin)",
  "bs_Cyrl": "Boisnis (Coireallach)",
  "bs_Cyrl_BA": "Boisnis (Coireallach, An Bhoisnia agus An Heirseagaivéin)",
  "bs_Latn": "Boisnis (Laidineach)",
  "bs_Latn_BA": "Boisnis (Laidineach, An Bhoisnia agus An Heirseagaivéin)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buiriáitis",
  "bug": "Buiginis",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalóinis",
  "ca_AD": "Catalóinis (Andóra)",
  "ca_ES": "Catalóinis (An Spáinn)",
  "ca_FR": "Catalóinis (An Fhrainc)",
  "ca_IT": "Catalóinis (An Iodáil)",
  "cad": "Caddo",
  "cai": "Teanga Indiach Mheiriceá Láir",
  "car": "Carib",
  "cau": "Teanga Chugais",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Seisnis",
  "ceb": "Seabúáinis",
  "cel": "Teanga Cheilteach",
  "cgg": "Chiga",
  "ch": "Seamóiris",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mairis",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Seiricis",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Coirdis Lárnach",
  "cmc": "Teanga Chamic",
  "co": "Corsaicis",
  "cop": "Coptais",
  "cpe": "Creole nó Pidgin atá bunaithe i mBéarla",
  "cpf": "Creole nó Pidgin atá lonnaithe sa Fhrainc",
  "cpp": "Creole nó Pidgin atá lonnaithe sa Phortaingéilis",
  "cps": "Capiznon",
  "cr": "Craís",
  "crh": "Crimean Turkish",
  "crp": "Creole nó Pidgin",
  "crs": "Criól Fraincise Seselwa",
  "cs": "Seicis",
  "cs_CZ": "Seicis (Poblacht na Seice)",
  "csb": "Caisiúibis",
  "cu": "Slavais na hEaglaise",
  "cus": "Teanga Cushitic",
  "cv": "Suvaisis",
  "cy": "Breatnais",
  "cy_GB": "Breatnais (An Ríocht Aontaithe)",
  "da": "Danmhairgis",
  "da_DK": "Danmhairgis (An Danmhairg)",
  "da_GL": "Danmhairgis (An Ghraonlainn)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Gearmáinis",
  "de_AT": "Gearmáinis (An Ostair)",
  "de_BE": "Gearmáinis (An Bheilg)",
  "de_CH": "Gearmáinis (An Eilvéis)",
  "de_DE": "Gearmáinis (An Ghearmáin)",
  "de_LI": "Gearmáinis (Lichtinstéin)",
  "de_LU": "Gearmáinis (Lucsamburg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarmais",
  "doi": "Dogri",
  "dra": "Teanga Dravidian",
  "dsb": "Sorbais Íochtarach",
  "dtp": "Central Dusun",
  "dua": "Duailis",
  "dum": "Meán-Ollainnis",
  "dv": "Divéihis",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Seoinicis",
  "dz_BT": "Seoinicis (An Bhútáin)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Éabhais",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Sean-Éigiptis",
  "eka": "Ekajuk",
  "el": "Gréigis",
  "el_CY": "Gréigis (An Chipir)",
  "el_GR": "Gréigis (An Ghréig)",
  "elx": "Elamite",
  "en": "Béarla",
  "en_AG": "Béarla (Antigua agus Barbúda)",
  "en_AI": "Béarla (Angaíle)",
  "en_AS": "Béarla (Samó Meiriceánach)",
  "en_AU": "Béarla (An Astráil)",
  "en_BB": "Béarla (Barbadós)",
  "en_BE": "Béarla (An Bheilg)",
  "en_BM": "Béarla (Beirmiúda)",
  "en_BS": "Béarla (Na Bahámaí)",
  "en_BW": "Béarla (An Bhotsuáin)",
  "en_BZ": "Béarla (An Bheilís)",
  "en_CA": "Béarla (Ceanada)",
  "en_CC": "Béarla (Oileáin Cocos (Keeling))",
  "en_CK": "Béarla (Oileáin Cook)",
  "en_CM": "Béarla (Camarún)",
  "en_CX": "Béarla (Oileán na Nollag)",
  "en_DG": "Béarla (Diego Garcia)",
  "en_DM": "Béarla (Doiminice)",
  "en_Dsrt": "Béarla (Deseret)",
  "en_ER": "Béarla (An Eiritré)",
  "en_FJ": "Béarla (Fidsí)",
  "en_FK": "Béarla (Oileáin Fháclainne)",
  "en_FM": "Béarla (An Mhicrinéis)",
  "en_GB": "Béarla (An Ríocht Aontaithe)",
  "en_GD": "Béarla (Greanáda)",
  "en_GG": "Béarla (Geansaí)",
  "en_GH": "Béarla (Gána)",
  "en_GI": "Béarla (Giobráltar)",
  "en_GM": "Béarla (An Ghaimbia)",
  "en_GU": "Béarla (Guam)",
  "en_GY": "Béarla (An Ghuáin)",
  "en_HK": "Béarla (S.R.R. na Síne Hong Cong)",
  "en_IE": "Béarla (Éire)",
  "en_IM": "Béarla (Oileán Mhanann)",
  "en_IN": "Béarla (An India)",
  "en_IO": "Béarla (Críoch Aigéan Indiach na Breataine)",
  "en_JE": "Béarla (Geirsí)",
  "en_JM": "Béarla (Iamáice)",
  "en_KE": "Béarla (An Chéinia)",
  "en_KI": "Béarla (Cireabaití)",
  "en_KN": "Béarla (San Críostóir-Nimheas)",
  "en_KY": "Béarla (Oileáin Cayman)",
  "en_LC": "Béarla (Saint Lucia)",
  "en_LR": "Béarla (An Libéir)",
  "en_LS": "Béarla (Leosóta)",
  "en_MG": "Béarla (Madagascar)",
  "en_MH": "Béarla (Oileáin Marshall)",
  "en_MO": "Béarla (S.R.R. na Síne Macao)",
  "en_MP": "Béarla (Na hOileáin Mháirianacha Thuaidh)",
  "en_MS": "Béarla (Montsarat)",
  "en_MT": "Béarla (Málta)",
  "en_MU": "Béarla (Oileán Mhuirís)",
  "en_MW": "Béarla (An Mhaláiv)",
  "en_MY": "Béarla (An Mhalaeisia)",
  "en_NA": "Béarla (An Namaib)",
  "en_NF": "Béarla (Oileán Norfolk)",
  "en_NG": "Béarla (An Nigéir)",
  "en_NR": "Béarla (Nárú)",
  "en_NU": "Béarla (Niue)",
  "en_NZ": "Béarla (An Nua-Shéalainn)",
  "en_PG": "Béarla (Nua-Ghuine Phapua)",
  "en_PH": "Béarla (Na hOileáin Fhilipíneacha)",
  "en_PK": "Béarla (An Phacastáin)",
  "en_PN": "Béarla (Oileáin Pitcairn)",
  "en_PR": "Béarla (Portó Ríce)",
  "en_PW": "Béarla (Palau)",
  "en_RW": "Béarla (Ruanda)",
  "en_SB": "Béarla (Oileáin Sholomón)",
  "en_SC": "Béarla (Na Séiséil)",
  "en_SD": "Béarla (An tSúdáin)",
  "en_SG": "Béarla (Singeapór)",
  "en_SH": "Béarla (San Héilin)",
  "en_SL": "Béarla (Siarra Leon)",
  "en_SS": "Béarla (An tSúdáin Theas)",
  "en_SX": "Béarla (Sint Maarten)",
  "en_SZ": "Béarla (An tSuasalainn)",
  "en_TC": "Béarla (Oileáin na dTurcach agus Caicos)",
  "en_TK": "Béarla (Tócalá)",
  "en_TO": "Béarla (Tonga)",
  "en_TT": "Béarla (Oileán na Tríonóide agus Tobága)",
  "en_TV": "Béarla (Tuvalu)",
  "en_TZ": "Béarla (An Tansáin)",
  "en_UG": "Béarla (Uganda)",
  "en_UM": "Béarla (Oileáin Imeallacha S.A.M.)",
  "en_US": "Béarla (Stáit Aontaithe Mheiriceá)",
  "en_VC": "Béarla (San Uinseann agus na Greanáidíní)",
  "en_VG": "Béarla (Oileáin Bhriotanacha na Maighdean)",
  "en_VI": "Béarla (Oileáin Mheiriceánacha na Maighdean)",
  "en_VU": "Béarla (Vanuatú)",
  "en_WS": "Béarla (Samó)",
  "en_ZA": "Béarla (An Afraic Theas)",
  "en_ZM": "Béarla (An tSaimbia)",
  "en_ZW": "Béarla (An tSiombáib)",
  "enm": "Meán-Bhéarla",
  "eo": "Esperanto",
  "es": "Spáinnis",
  "es_419": "Spáinnis Mheiriceá Laidinigh",
  "es_AR": "Spáinnis (An Airgintín)",
  "es_BO": "Spáinnis (An Bholaiv)",
  "es_CL": "Spáinnis (An tSile)",
  "es_CO": "Spáinnis (An Cholóim)",
  "es_CR": "Spáinnis (Cósta Ríce)",
  "es_CU": "Spáinnis (Cúba)",
  "es_DO": "Spáinnis (An Phoblacht Dhoiminiceach)",
  "es_EA": "Spáinnis (Ceuta agus Melilla)",
  "es_EC": "Spáinnis (Eacuadór)",
  "es_ES": "Spáinnis (An Spáinn)",
  "es_GQ": "Spáinnis (An Ghuine Mheánchriosach)",
  "es_GT": "Spáinnis (Guatamala)",
  "es_HN": "Spáinnis (Hondúras)",
  "es_IC": "Spáinnis (Na hOileáin Chanáracha)",
  "es_MX": "Spáinnis (Meicsiceo)",
  "es_NI": "Spáinnis (Nicearagua)",
  "es_PA": "Spáinnis (Panama)",
  "es_PE": "Spáinnis (Peiriú)",
  "es_PH": "Spáinnis (Na hOileáin Fhilipíneacha)",
  "es_PR": "Spáinnis (Portó Ríce)",
  "es_PY": "Spáinnis (Paragua)",
  "es_SV": "Spáinnis (An tSalvadóir)",
  "es_US": "Spáinnis (Stáit Aontaithe Mheiriceá)",
  "es_UY": "Spáinnis (Urugua)",
  "es_VE": "Spáinnis (Veiniséala)",
  "esu": "Central Yupik",
  "et": "Eastóinis",
  "et_EE": "Eastóinis (An Eastóin)",
  "eu": "Bascais",
  "eu_ES": "Bascais (An Spáinn)",
  "ewo": "Éabhandóis",
  "ext": "Extremaduran",
  "fa": "Peirsis",
  "fa_AF": "Peirsis (An Afganastáin)",
  "fa_IR": "Peirsis (An Iaráin)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fuláinis",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fuláinis (Camarún)",
  "ff_GN": "Fuláinis (An Ghuine)",
  "ff_MR": "Fuláinis (An Mháratáin)",
  "ff_SN": "Fuláinis (An tSeineagáil)",
  "fi": "Fionlainnis",
  "fi_FI": "Fionlainnis (An Fhionlainn)",
  "fil": "Filipínis",
  "fit": "Tornedalen Finnish",
  "fiu": "Teanga Finno-Ugrian",
  "fj": "Fidsis",
  "fo": "Faróis",
  "fo_FO": "Faróis (Oileáin Fharó)",
  "fon": "fon",
  "fr": "Fraincis",
  "fr_BE": "Fraincis (An Bheilg)",
  "fr_BF": "Fraincis (Buircíne Fasó)",
  "fr_BI": "Fraincis (An Bhurúin)",
  "fr_BJ": "Fraincis (Beinin)",
  "fr_BL": "Fraincis (Saint Barthélemy)",
  "fr_CA": "Fraincis (Ceanada)",
  "fr_CD": "Fraincis (Poblacht Dhaonlathach an Chongó)",
  "fr_CF": "Fraincis (Poblacht na hAfraice Láir)",
  "fr_CG": "Fraincis (An Congó)",
  "fr_CH": "Fraincis (An Eilvéis)",
  "fr_CI": "Fraincis (An Cósta Eabhair)",
  "fr_CM": "Fraincis (Camarún)",
  "fr_DJ": "Fraincis (Djibouti)",
  "fr_DZ": "Fraincis (An Ailgéir)",
  "fr_FR": "Fraincis (An Fhrainc)",
  "fr_GA": "Fraincis (An Ghabúin)",
  "fr_GF": "Fraincis (Guáin na Fraince)",
  "fr_GN": "Fraincis (An Ghuine)",
  "fr_GP": "Fraincis (Guadalúip)",
  "fr_GQ": "Fraincis (An Ghuine Mheánchriosach)",
  "fr_HT": "Fraincis (Háítí)",
  "fr_KM": "Fraincis (Oileáin Chomóra)",
  "fr_LU": "Fraincis (Lucsamburg)",
  "fr_MA": "Fraincis (Maracó)",
  "fr_MC": "Fraincis (Monacó)",
  "fr_MF": "Fraincis (Saint-Martin)",
  "fr_MG": "Fraincis (Madagascar)",
  "fr_ML": "Fraincis (Mailí)",
  "fr_MQ": "Fraincis (Martinique)",
  "fr_MR": "Fraincis (An Mháratáin)",
  "fr_MU": "Fraincis (Oileán Mhuirís)",
  "fr_NC": "Fraincis (An Nua-Chaladóin)",
  "fr_NE": "Fraincis (An Nígir)",
  "fr_PF": "Fraincis (Polainéis na Fraince)",
  "fr_PM": "Fraincis (Saint-Pierre-et-Miquelon)",
  "fr_RE": "Fraincis (Réunion)",
  "fr_RW": "Fraincis (Ruanda)",
  "fr_SC": "Fraincis (Na Séiséil)",
  "fr_SN": "Fraincis (An tSeineagáil)",
  "fr_SY": "Fraincis (An tSiria)",
  "fr_TD": "Fraincis (Sead)",
  "fr_TG": "Fraincis (Tóga)",
  "fr_TN": "Fraincis (An Túinéis)",
  "fr_VU": "Fraincis (Vanuatú)",
  "fr_WF": "Fraincis (Vailís agus Futúna)",
  "fr_YT": "Fraincis (Mayotte)",
  "frc": "Cajun French",
  "frm": "Meán-Fhraincis",
  "fro": "Sean-Fhraincis",
  "frp": "Arpitan",
  "frr": "Freaslainnis an Tuaiscirt",
  "frs": "Eastern Frisian",
  "fur": "Friúilis",
  "fy": "Freaslainnis Iartharach",
  "fy_NL": "Freaslainnis Iartharach (An Ísiltír)",
  "ga": "Gaeilge",
  "ga_IE": "Gaeilge (Éire)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Sínis Gan",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Gaeilge na hAlban",
  "gd_GB": "Gaeilge na hAlban (An Ríocht Aontaithe)",
  "gem": "Teanga Gearmánach",
  "gez": "Aetóipis",
  "gil": "Cireabaitis",
  "gl": "Gailísis",
  "gl_ES": "Gailísis (An Spáinn)",
  "glk": "Gilaki",
  "gmh": "Meán-Ard-Ghearmáinis",
  "gn": "Guaráinis",
  "goh": "Sean-Ard-Ghearmáinis",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Sean-Ghréigis",
  "gsw": "Gearmáinis Eilvéiseach",
  "gu": "Gúisearáitis",
  "gu_IN": "Gúisearáitis (An India)",
  "guc": "Uaúis",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manainnis",
  "gv_IM": "Manainnis (Oileán Mhanann)",
  "gwi": "Gwichʼin",
  "ha": "Hásais",
  "ha_GH": "Hásais (Gána)",
  "ha_Latn": "Hásais (Laidineach)",
  "ha_Latn_GH": "Hásais (Laidineach, Gána)",
  "ha_Latn_NE": "Hásais (Laidineach, An Nígir)",
  "ha_Latn_NG": "Hásais (Laidineach, An Nigéir)",
  "ha_NE": "Hásais (An Nígir)",
  "ha_NG": "Hásais (An Nigéir)",
  "hai": "Haida",
  "hak": "Haicéis",
  "haw": "Haváis",
  "he": "Eabhrais",
  "he_IL": "Eabhrais (Iosrael)",
  "hi": "Hiondúis",
  "hi_IN": "Hiondúis (An India)",
  "hif": "Hiondúis Fhidsí",
  "hil": "Hilgeanóinis",
  "him": "Himachali",
  "hit": "Hitis",
  "hmn": "Mongais",
  "ho": "Motúis Hírí",
  "hr": "Cróitis",
  "hr_BA": "Cróitis (An Bhoisnia agus An Heirseagaivéin)",
  "hr_HR": "Cróitis (An Chróit)",
  "hsb": "Sorbais Uachtarach",
  "hsn": "Sínis Xiang",
  "ht": "Criól Háítíoch",
  "hu": "Ungáiris",
  "hu_HU": "Ungáiris (An Ungáir)",
  "hup": "Húipis",
  "hy": "Airméinis",
  "hy_AM": "Airméinis (An Airméin)",
  "hz": "Heiréiris",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibis",
  "id": "Indinéisis",
  "id_ID": "Indinéisis (An Indinéis)",
  "ie": "Interlingue",
  "ig": "Íogbóis",
  "ig_NG": "Íogbóis (An Nigéir)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ijo": "Ijo",
  "ik": "Iniúipiaicis",
  "ilo": "Iloko",
  "inc": "Teanga Tásc",
  "ine": "Teanga Ind-Eorpach",
  "inh": "Iongúis",
  "io": "Ido",
  "ira": "Teanga na hIaráine",
  "iro": "Teanga Iroquoian",
  "is": "Íoslainnis",
  "is_IS": "Íoslainnis (An Íoslainn)",
  "it": "Iodáilis",
  "it_CH": "Iodáilis (An Eilvéis)",
  "it_IT": "Iodáilis (An Iodáil)",
  "it_SM": "Iodáilis (San Mairíne)",
  "iu": "Ionúitis",
  "izh": "Ingrian",
  "ja": "Seapáinis",
  "ja_JP": "Seapáinis (An tSeapáin)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Iútlainnis",
  "jv": "Iáivis",
  "ka": "Seoirsis",
  "ka_GE": "Seoirsis (An tSeoirsia)",
  "kaa": "Cara-Chalpáis",
  "kab": "Caibílis",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Cambais",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Congóis",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Teanga Khoisan",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Ciocúis",
  "ki_KE": "Ciocúis (An Chéinia)",
  "kiu": "Kirmanjki",
  "kj": "Cuainiáimis",
  "kk": "Casaicis",
  "kk_Cyrl": "Casaicis (Coireallach)",
  "kk_Cyrl_KZ": "Casaicis (Coireallach, An Chasacstáin)",
  "kk_KZ": "Casaicis (An Chasacstáin)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (An Ghraonlainn)",
  "kln": "Kalenjin",
  "km": "Ciméiris",
  "km_KH": "Ciméiris (An Chambóid)",
  "kmb": "Kimbundu",
  "kn": "Cannadais",
  "kn_IN": "Cannadais (An India)",
  "ko": "Cóiréis",
  "ko_KP": "Cóiréis (An Chóiré Thuaidh)",
  "ko_KR": "Cóiréis (An Chóiré Theas)",
  "koi": "Komi-Permyak",
  "kok": "Concáinis",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Canúiris",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Cairéilis",
  "kro": "Kru",
  "kru": "Curúicis",
  "ks": "Caismíris",
  "ks_Arab": "Caismíris (Arabach)",
  "ks_Arab_IN": "Caismíris (Arabach, An India)",
  "ks_IN": "Caismíris (An India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Coirdis",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Coimis",
  "kw": "Coirnis",
  "kw_GB": "Coirnis (An Ríocht Aontaithe)",
  "ky": "Cirgisis",
  "ky_Cyrl": "Cirgisis (Coireallach)",
  "ky_Cyrl_KG": "Cirgisis (Coireallach, An Chirgeastáin)",
  "ky_KG": "Cirgisis (An Chirgeastáin)",
  "la": "Laidin",
  "lad": "Laidínis",
  "lag": "Langi",
  "lah": "Puinseáibis Iartharach",
  "lam": "Lamba",
  "lb": "Lucsambuirgis",
  "lb_LU": "Lucsambuirgis (Lucsamburg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Lugandais",
  "lg_UG": "Lugandais (Uganda)",
  "li": "Liombuirgis",
  "lij": "Liogúiris",
  "liv": "Liovóinis",
  "lkt": "Lakota",
  "lmo": "Lombairdis",
  "ln": "Liongáilis",
  "ln_AO": "Liongáilis (Angóla)",
  "ln_CD": "Liongáilis (Poblacht Dhaonlathach an Chongó)",
  "ln_CF": "Liongáilis (Poblacht na hAfraice Láir)",
  "ln_CG": "Liongáilis (An Congó)",
  "lo": "Laoisis",
  "lo_LA": "Laoisis (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Luri Thuaidh",
  "lt": "Liotuáinis",
  "lt_LT": "Liotuáinis (An Liotuáin)",
  "ltg": "Latgalian",
  "lu": "Lúba-Cataingis",
  "lu_CD": "Lúba-Cataingis (Poblacht Dhaonlathach an Chongó)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Lúóis",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Laitvis",
  "lv_LV": "Laitvis (An Laitvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maitilis",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Teanga na hAstráile",
  "mas": "Másais",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Meindis",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagáisis",
  "mg_MG": "Malagáisis (Madagascar)",
  "mga": "Meán-Ghaeilge",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Mairsillis",
  "mi": "Maorais",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Teanga Ilghnéitheach",
  "mk": "Macadóinis",
  "mk_MK": "Macadóinis (An Mhacadóin)",
  "mkh": "Teanga Mon-Khmer",
  "ml": "Mailéalaimis",
  "ml_IN": "Mailéalaimis (An India)",
  "mn": "Mongóilis",
  "mn_Cyrl": "Mongóilis (Coireallach)",
  "mn_Cyrl_MN": "Mongóilis (Coireallach, An Mhongóil)",
  "mn_MN": "Mongóilis (An Mhongóil)",
  "mnc": "Manchu",
  "mni": "Manapúiris",
  "mno": "Teanga Manobo",
  "mo": "Moldáivis",
  "moh": "Móháicis",
  "mos": "Mossi",
  "mr": "Maraitis",
  "mr_IN": "Maraitis (An India)",
  "mrj": "Mairis Iartharach",
  "ms": "Malaeis",
  "ms_BN": "Malaeis (Brúiné)",
  "ms_Latn": "Malaeis (Laidineach)",
  "ms_Latn_BN": "Malaeis (Laidineach, Brúiné)",
  "ms_Latn_MY": "Malaeis (Laidineach, An Mhalaeisia)",
  "ms_Latn_SG": "Malaeis (Laidineach, Singeapór)",
  "ms_MY": "Malaeis (An Mhalaeisia)",
  "ms_SG": "Malaeis (Singeapór)",
  "mt": "Máltais",
  "mt_MT": "Máltais (Málta)",
  "mua": "Mundang",
  "mul": "Ilteangacha",
  "mun": "Teanga Munda",
  "mus": "Creek",
  "mwl": "Mioraindéis",
  "mwr": "Marmhairis",
  "mwv": "Mentawai",
  "my": "Burmais",
  "my_MM": "Burmais (Maenmar (Burma))",
  "mye": "Myene",
  "myn": "Teanga Maya",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nárúis",
  "nah": "Nahuatl",
  "nai": "Teanga Indiach Mheiriceá Thuaidh",
  "nan": "Sínis Min Nan",
  "nap": "Napóilis",
  "naq": "Nama",
  "nb": "Ioruais Bokmål",
  "nb_NO": "Ioruais Bokmål (An Iorua)",
  "nb_SJ": "Ioruais Bokmål (Svalbard agus Jan Mayen)",
  "nd": "Ndeibéilis an Tuaiscirt",
  "nd_ZW": "Ndeibéilis an Tuaiscirt (An tSiombáib)",
  "nds": "Gearmáinis Íochtarach",
  "nds_NL": "Sacsainis Íochtarach",
  "ne": "Neipeailis",
  "ne_IN": "Neipeailis (An India)",
  "ne_NP": "Neipeailis (Neipeal)",
  "new": "Newari",
  "ng": "Ndongais",
  "nia": "Nias",
  "nic": "Teanga an Nígir-Kordofanian",
  "niu": "Níobhais",
  "njo": "Ao Naga",
  "nl": "Ollainnis",
  "nl_AW": "Ollainnis (Arúba)",
  "nl_BE": "Ollainnis (An Bheilg)",
  "nl_BQ": "Ollainnis (An Ísiltír Chairibeach)",
  "nl_CW": "Ollainnis (Curaçao)",
  "nl_NL": "Ollainnis (An Ísiltír)",
  "nl_SR": "Ollainnis (Suranam)",
  "nl_SX": "Ollainnis (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Nua-Ioruais",
  "nn_NO": "Nua-Ioruais (An Iorua)",
  "nnh": "Ngiemboon",
  "no": "Ioruais",
  "no_NO": "Ioruais (An Iorua)",
  "nog": "Nogai",
  "non": "Sean-Lochlainnis",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "Ndeibéilis an Deiscirt",
  "nso": "Sútúis an Tuaiscirt",
  "nub": "Teanga Nubian",
  "nus": "Nuer",
  "nv": "Navachóis",
  "nwc": "Classical Newari",
  "ny": "Siséivis",
  "nym": "Nyamwezi",
  "nyn": "Niancóilis",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Ocsatáinis",
  "oj": "Óisibis",
  "om": "Oraimis",
  "om_ET": "Oraimis (An Aetóip)",
  "om_KE": "Oraimis (An Chéinia)",
  "or": "Oirísis",
  "or_IN": "Oirísis (An India)",
  "os": "Oiséitis",
  "os_GE": "Oiséitis (An tSeoirsia)",
  "os_RU": "Oiséitis (An Rúis)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "oto": "Teanga Otomian",
  "pa": "Puinseáibis",
  "pa_Arab": "Puinseáibis (Arabach)",
  "pa_Arab_PK": "Puinseáibis (Arabach, An Phacastáin)",
  "pa_Guru": "Puinseáibis (Gurmúcach)",
  "pa_Guru_IN": "Puinseáibis (Gurmúcach, An India)",
  "pa_IN": "Puinseáibis (An India)",
  "pa_PK": "Puinseáibis (An Phacastáin)",
  "paa": "Teanga Papuan",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pcm": "Pidgin na Nigéire",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Sean-Pheirsis",
  "pfl": "Palatine German",
  "phi": "Teanga Philippine",
  "phn": "Phoenician",
  "pi": "Páilis",
  "pl": "Polainnis",
  "pl_PL": "Polainnis (An Pholainn)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "pra": "Teanga Prakrit",
  "prg": "Prúisis",
  "pro": "Old Provençal",
  "ps": "Paistis",
  "ps_AF": "Paistis (An Afganastáin)",
  "pt": "Portaingéilis",
  "pt_AO": "Portaingéilis (Angóla)",
  "pt_BR": "Portaingéilis (An Bhrasaíl)",
  "pt_CV": "Portaingéilis (Rinn Verde)",
  "pt_GW": "Portaingéilis (Guine Bissau)",
  "pt_MO": "Portaingéilis (S.R.R. na Síne Macao)",
  "pt_MZ": "Portaingéilis (Mósaimbíc)",
  "pt_PT": "Portaingéilis (An Phortaingéil)",
  "pt_ST": "Portaingéilis (São Tomé agus Príncipe)",
  "pt_TL": "Portaingéilis (Tíomór Thoir)",
  "qu": "Ceatsuais",
  "qu_BO": "Ceatsuais (An Bholaiv)",
  "qu_EC": "Ceatsuais (Eacuadór)",
  "qu_PE": "Ceatsuais (Peiriú)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Rómainis",
  "rm_CH": "Rómainis (An Eilvéis)",
  "rn": "Rúindis",
  "rn_BI": "Rúindis (An Bhurúin)",
  "ro": "Rómáinis",
  "ro_MD": "Rómáinis (An Mholdóiv)",
  "ro_RO": "Rómáinis (An Rómáin)",
  "roa": "Teanga Rómánsacha",
  "rof": "Rombo",
  "rom": "Romainis",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Rúisis",
  "ru_BY": "Rúisis (An Bhealarúis)",
  "ru_KG": "Rúisis (An Chirgeastáin)",
  "ru_KZ": "Rúisis (An Chasacstáin)",
  "ru_MD": "Rúisis (An Mholdóiv)",
  "ru_RU": "Rúisis (An Rúis)",
  "ru_UA": "Rúisis (An Úcráin)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Arómáinis",
  "rw": "Ciniaruaindis",
  "rw_RW": "Ciniaruaindis (Ruanda)",
  "rwk": "Rwa",
  "sa": "Sanscrait",
  "sad": "Sandawe",
  "sah": "Sachais",
  "sai": "Teanga Indiach Mheiriceá Theas",
  "sal": "Teanga Salishan",
  "sam": "Aramais Shamárach",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santáilis",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sairdínis",
  "scn": "Sicilis",
  "sco": "Albainis",
  "sd": "Sindis",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "Coirdis an Deiscirt",
  "se": "Sáimis Thuaidh",
  "se_FI": "Sáimis Thuaidh (An Fhionlainn)",
  "se_NO": "Sáimis Thuaidh (An Iorua)",
  "se_SE": "Sáimis Thuaidh (An tSualainn)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Teanga Semitic",
  "ses": "Koyraboro Senni",
  "sg": "Sangóis",
  "sg_CF": "Sangóis (Poblacht na hAfraice Láir)",
  "sga": "Sean-Ghaeilge",
  "sgn": "Teanga chomharthaíochta",
  "sgs": "Samogitian",
  "sh": "Seirbea-Chróitis",
  "sh_BA": "Seirbea-Chróitis (An Bhoisnia agus An Heirseagaivéin)",
  "shi": "Tachelhit",
  "shi_Latn": "Shilha (Laidin)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Siolóinis",
  "si_LK": "Siolóinis (Srí Lanca)",
  "sid": "Sidamo",
  "sio": "Teanga Siouan",
  "sit": "Teanga Sino-Tibéidis",
  "sk": "Slóvaicis",
  "sk_SK": "Slóvaicis (An tSlóvaic)",
  "sl": "Slóivéinis",
  "sl_SI": "Slóivéinis (An tSlóivéin)",
  "sla": "Teanga Slavach",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samóis",
  "sma": "Sáimis Theas",
  "smi": "Teanga Sami",
  "smj": "Sáimis Lule",
  "smn": "Sáimis Inari",
  "sms": "Sáimis Skolt",
  "sn": "Seoinis",
  "sn_ZW": "Seoinis (An tSiombáib)",
  "snk": "Soninke",
  "so": "Somáilis",
  "so_DJ": "Somáilis (Djibouti)",
  "so_ET": "Somáilis (An Aetóip)",
  "so_KE": "Somáilis (An Chéinia)",
  "so_SO": "Somáilis (An tSomáil)",
  "sog": "Sogdánais",
  "son": "Songhai",
  "sq": "Albáinis",
  "sq_AL": "Albáinis (An Albáin)",
  "sq_MK": "Albáinis (An Mhacadóin)",
  "sq_XK": "Albáinis (An Chosaiv)",
  "sr": "Seirbis",
  "sr_BA": "Seirbis (An Bhoisnia agus An Heirseagaivéin)",
  "sr_Cyrl": "Seirbis (Coireallach)",
  "sr_Cyrl_BA": "Seirbis (Coireallach, An Bhoisnia agus An Heirseagaivéin)",
  "sr_Cyrl_ME": "Seirbis (Coireallach, Montainéagró)",
  "sr_Cyrl_RS": "Seirbis (Coireallach, An tSeirbia)",
  "sr_Cyrl_XK": "Seirbis (Coireallach, An Chosaiv)",
  "sr_Latn": "Seirbis (Laidineach)",
  "sr_Latn_BA": "Seirbis (Laidineach, An Bhoisnia agus An Heirseagaivéin)",
  "sr_Latn_ME": "Seirbis (Laidineach, Montainéagró)",
  "sr_Latn_RS": "Seirbis (Laidineach, An tSeirbia)",
  "sr_Latn_XK": "Seirbis (Laidineach, An Chosaiv)",
  "sr_ME": "Seirbis (Montainéagró)",
  "sr_RS": "Seirbis (An tSeirbia)",
  "sr_XK": "Seirbis (An Chosaiv)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Suaisis",
  "ssa": "Teanga Nilo-Shahárach",
  "ssy": "Saho",
  "st": "Seasóitis",
  "stq": "Saterland Frisian",
  "su": "Sundais",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Suiméiris",
  "sv": "Sualainnis",
  "sv_AX": "Sualainnis (Oileáin Åland)",
  "sv_FI": "Sualainnis (An Fhionlainn)",
  "sv_SE": "Sualainnis (An tSualainn)",
  "sw": "Svahaílis",
  "sw_CD": "Svahaílis an Chongó",
  "sw_KE": "Svahaílis (An Chéinia)",
  "sw_TZ": "Svahaílis (An Tansáin)",
  "sw_UG": "Svahaílis (Uganda)",
  "swb": "Comóiris",
  "swc": "Svahaílis an Chongó",
  "syc": "Classical Syriac",
  "syr": "Siricis",
  "szl": "Siléisis",
  "ta": "Tamailis",
  "ta_IN": "Tamailis (An India)",
  "ta_LK": "Tamailis (Srí Lanca)",
  "ta_MY": "Tamailis (An Mhalaeisia)",
  "ta_SG": "Tamailis (Singeapór)",
  "tai": "Teanga Tai",
  "tcy": "Tulu",
  "te": "Teileagúis",
  "te_IN": "Teileagúis (An India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Táidsícis",
  "th": "Téalainnis",
  "th_TH": "Téalainnis (An Téalainn)",
  "ti": "Tigrinis",
  "ti_ER": "Tigrinis (An Eiritré)",
  "ti_ET": "Tigrinis (An Aetóip)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Tuircméinis",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagálaigis",
  "tl_PH": "Tagálaigis (Na hOileáin Fhilipíneacha)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Suáinis",
  "to": "Tongais",
  "to_TO": "Tongais (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Tuircis",
  "tr_CY": "Tuircis (An Chipir)",
  "tr_TR": "Tuircis (An Tuirc)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Songais",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatairis",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tup": "Teanga Tupi",
  "tut": "Teanga Altaic",
  "tvl": "Tuvalu",
  "tw": "Tíbhis",
  "twq": "Tasawaq",
  "ty": "Taihítis",
  "tyv": "Tuvinian",
  "tzm": "Tamazight Atlais Láir",
  "udm": "Udmairtis",
  "ug": "Uigiúiris",
  "ug_Arab": "Uigiúiris (Arabach)",
  "ug_Arab_CN": "Uigiúiris (Arabach, An tSín)",
  "ug_CN": "Uigiúiris (An tSín)",
  "uga": "Ugaritic",
  "uk": "Úcráinis",
  "uk_UA": "Úcráinis (An Úcráin)",
  "umb": "Umbundu",
  "und": "Teanga Anaithnid",
  "ur": "Urdúis",
  "ur_IN": "Urdúis (An India)",
  "ur_PK": "Urdúis (An Phacastáin)",
  "uz": "Úisbéiceastáinis",
  "uz_AF": "Úisbéiceastáinis (An Afganastáin)",
  "uz_Arab": "Úisbéiceastáinis (Arabach)",
  "uz_Arab_AF": "Úisbéiceastáinis (Arabach, An Afganastáin)",
  "uz_Cyrl": "Úisbéiceastáinis (Coireallach)",
  "uz_Cyrl_UZ": "Úisbéiceastáinis (Coireallach, An Úisbéiceastáin)",
  "uz_Latn": "Úisbéiceastáinis (Laidineach)",
  "uz_Latn_UZ": "Úisbéiceastáinis (Laidineach, An Úisbéiceastáin)",
  "uz_UZ": "Úisbéiceastáinis (An Úisbéiceastáin)",
  "vai": "vai",
  "vai_Latn": "Vai (Laidin)",
  "ve": "Veindis",
  "vec": "Veinéisis",
  "vep": "Veps",
  "vi": "Vítneaimis",
  "vi_VN": "Vítneaimis (Vítneam)",
  "vls": "Pléimeannais Iartharach",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Vallúnais",
  "wae": "Walser",
  "wak": "Teanga Wakashan",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Teanga Sorbian",
  "wo": "Volaifis",
  "wuu": "Wu Chinese",
  "xal": "Cailmícis",
  "xh": "Cóisis",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Giúdais",
  "yo": "Iarúibis",
  "yo_BJ": "Iarúibis (Beinin)",
  "yo_NG": "Iarúibis (An Nigéir)",
  "ypk": "Teanga Yupik",
  "yrl": "Nheengatu",
  "yue": "Cantainis",
  "yue_Hans": "Cantainis (Sínis Simplithe)",
  "yue_Hant": "Cantainis (Sínis Traidisiúnta)",
  "za": "Siuáingis",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Séalainnis",
  "zen": "Zenaga",
  "zgh": "Tamazight Caighdeánach Mharacó",
  "zh": "Sínis",
  "zh_CN": "Sínis (An tSín)",
  "zh_HK": "Sínis (S.R.R. na Síne Hong Cong)",
  "zh_Hans": "Sínis (Simplithe)",
  "zh_Hans_CN": "Sínis (Simplithe, An tSín)",
  "zh_Hans_HK": "Sínis (Simplithe, S.R.R. na Síne Hong Cong)",
  "zh_Hans_MO": "Sínis (Simplithe, S.R.R. na Síne Macao)",
  "zh_Hans_SG": "Sínis (Simplithe, Singeapór)",
  "zh_Hant": "Sínis (Traidisiúnta)",
  "zh_Hant_HK": "Sínis (Traidisiúnta, S.R.R. na Síne Hong Cong)",
  "zh_Hant_MO": "Sínis (Traidisiúnta, S.R.R. na Síne Macao)",
  "zh_Hant_TW": "Sínis (Traidisiúnta, An Téaváin)",
  "zh_MO": "Sínis (S.R.R. na Síne Macao)",
  "zh_SG": "Sínis (Singeapór)",
  "zh_TW": "Sínis (An Téaváin)",
  "znd": "Zande",
  "zu": "Súlúis",
  "zu_ZA": "Súlúis (An Afraic Theas)",
  "zun": "Zúinis",
  "zxx": "Gan ábhar teangeolaíoch",
  "zza": "Zaza"
};
