const names = {
  "BR": "Brasilän",
  "CN": "Tsyinän",
  "DE": "Deutän",
  "ES": "Spanyän",
  "FR": "Fransän",
  "GB": "Regän Pebalöl",
  "GE": "Grusiyän",
  "GR": "Grikän",
  "IN": "Lindän",
  "IT": "Litaliyän",
  "JP": "Yapän",
  "MX": "Mäxikän",
  "NR": "Naureän",
  "PT": "Portugän",
  "PW": "Palauäns",
  "RU": "Rusän",
  "US": "Lamerikän",
  "de": "Deutänapük",
  "en": "Linglänapük",
  "eo": "Sperantapük",
  "es": "Spanyänapük",
  "fr": "Fransänapük",
  "it": "Litaliyänapük",
  "ja": "Yapänapük",
  "pt": "Portugänapük",
  "ru": "Rusänapük",
  "vo": "Volapük",
  "zh": "Tsyinänapük"
};
