const names = {
  "001": "pasaulis",
  "002": "Afrika",
  "003": "Šiaurės Amerika",
  "005": "Pietų Amerika",
  "009": "Okeanija",
  "011": "Vakarų Afrika",
  "013": "Centrinė Amerika",
  "014": "Rytų Afrika",
  "015": "Šiaurės Afrika",
  "017": "Vidurio Afrika",
  "018": "Pietinė Afrika",
  "019": "Amerika",
  "021": "Šiaurinė Amerika",
  "029": "Karibai",
  "030": "Rytų Azija",
  "034": "Pietų Azija",
  "035": "Pietryčių Azija",
  "039": "Pietų Europa",
  "053": "Australazija",
  "054": "Melanezija",
  "057": "Mikronezijos regionas",
  "061": "Polinezija",
  "142": "Azija",
  "143": "Centrinė Azija",
  "145": "Vakarų Azija",
  "150": "Europa",
  "151": "Rytų Europa",
  "154": "Šiaurės Europa",
  "155": "Vakarų Europa",
  "202": "Užsachario Afrika",
  "419": "Lotynų Amerika",
  "AC": "Dangun Žengimo sala",
  "AD": "Andora",
  "AE": "Jungtiniai Arabų Emyratai",
  "AF": "Afganistanas",
  "AG": "Antigva ir Barbuda",
  "AI": "Angilija",
  "AL": "Albanija",
  "AM": "Armėnija",
  "AN": "Olandijos Antilai",
  "AO": "Angola",
  "AQ": "Antarktida",
  "AR": "Argentina",
  "AS": "Amerikos Samoa",
  "AT": "Austrija",
  "AU": "Australija",
  "AW": "Aruba",
  "AX": "Alandų Salos",
  "AZ": "Azerbaidžanas",
  "Afak": "Afaka",
  "Aghb": "Kaukazo Albanijos",
  "Arab": "arabų",
  "Armi": "imperinė aramaikų",
  "Armn": "armėnų",
  "Avst": "avestano",
  "BA": "Bosnija ir Hercegovina",
  "BB": "Barbadosas",
  "BD": "Bangladešas",
  "BE": "Belgija",
  "BF": "Burkina Fasas",
  "BG": "Bulgarija",
  "BH": "Bahreinas",
  "BI": "Burundis",
  "BJ": "Beninas",
  "BL": "Sen Bartelemi",
  "BM": "Bermuda",
  "BN": "Brunėjus",
  "BO": "Bolivija",
  "BQ": "Karibų Nyderlandai",
  "BR": "Brazilija",
  "BS": "Bahamos",
  "BT": "Butanas",
  "BV": "Buvė Sala",
  "BW": "Botsvana",
  "BY": "Baltarusija",
  "BZ": "Belizas",
  "Bali": "Baliečių",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "batak",
  "Beng": "bengalų",
  "Blis": "„Bliss“ simboliai",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "brailio",
  "Bugi": "buginezų",
  "Buhd": "buhid",
  "CA": "Kanada",
  "CC": "Kokosų (Kilingo) Salos",
  "CD": "Kongas-Kinšasa",
  "CF": "Centrinės Afrikos Respublika",
  "CG": "Kongas-Brazavilis",
  "CH": "Šveicarija",
  "CI": "Dramblio Kaulo Krantas",
  "CK": "Kuko Salos",
  "CL": "Čilė",
  "CM": "Kamerūnas",
  "CN": "Kinija",
  "CO": "Kolumbija",
  "CP": "Klipertono sala",
  "CR": "Kosta Rika",
  "CS": "Serbija ir Juodkalnija",
  "CU": "Kuba",
  "CV": "Žaliasis Kyšulys",
  "CW": "Kiurasao",
  "CX": "Kalėdų Sala",
  "CY": "Kipras",
  "CZ": "Čekija",
  "Cakm": "čakma",
  "Cans": "suvienodinti Kanados aborigenų silabiniai",
  "Cari": "karių",
  "Cham": "čam",
  "Cher": "čerokių",
  "Cirt": "kirt",
  "Copt": "koptų",
  "Cprt": "kipro",
  "Cyrl": "kirilica",
  "Cyrs": "senoji bažnytinė slavų kirilica",
  "DE": "Vokietija",
  "DG": "Diego Garsija",
  "DJ": "Džibutis",
  "DK": "Danija",
  "DM": "Dominika",
  "DO": "Dominikos Respublika",
  "DZ": "Alžyras",
  "Deva": "devanagari",
  "Dsrt": "deseretas",
  "Dupl": "Duplojė stenografija",
  "EA": "Seuta ir Melila",
  "EC": "Ekvadoras",
  "EE": "Estija",
  "EG": "Egiptas",
  "EH": "Vakarų Sachara",
  "ER": "Eritrėja",
  "ES": "Ispanija",
  "ET": "Etiopija",
  "EU": "Europos Sąjunga",
  "EZ": "euro zona",
  "Egyd": "Egipto liaudies",
  "Egyh": "Egipto žynių",
  "Egyp": "egipto hieroglifai",
  "Elba": "Elbasano",
  "Ethi": "etiopų",
  "FI": "Suomija",
  "FJ": "Fidžis",
  "FK": "Folklando Salos",
  "FM": "Mikronezija",
  "FO": "Farerų Salos",
  "FR": "Prancūzija",
  "FX": "Prancūzija, Metropolitenas",
  "GA": "Gabonas",
  "GB": "Jungtinė Karalystė",
  "GD": "Grenada",
  "GE": "Gruzija",
  "GF": "Prancūzijos Gviana",
  "GG": "Gernsis",
  "GH": "Gana",
  "GI": "Gibraltaras",
  "GL": "Grenlandija",
  "GM": "Gambija",
  "GN": "Gvinėja",
  "GP": "Gvadelupa",
  "GQ": "Pusiaujo Gvinėja",
  "GR": "Graikija",
  "GS": "Pietų Džordžija ir Pietų Sandvičo salos",
  "GT": "Gvatemala",
  "GU": "Guamas",
  "GW": "Bisau Gvinėja",
  "GY": "Gajana",
  "Geok": "gruzinų kutsuri",
  "Geor": "gruzinų",
  "Glag": "glagolitik",
  "Goth": "gotų",
  "Gran": "Granta",
  "Grek": "graikų",
  "Gujr": "gudžaratų",
  "Guru": "gurmuki",
  "HK": "Ypatingasis Administracinis Kinijos Regionas Honkongas",
  "HM": "Herdo ir Makdonaldo Salos",
  "HN": "Hondūras",
  "HR": "Kroatija",
  "HT": "Haitis",
  "HU": "Vengrija",
  "Hanb": "hanbų",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanuno",
  "Hans": "supaprastinti",
  "Hant": "tradiciniai",
  "Hebr": "hebrajų",
  "Hira": "hiragana",
  "Hluw": "Anatolijaus hieroglifai",
  "Hmng": "pahav hmong",
  "Hrkt": "katakana / hiragana",
  "Hung": "senasis vengrų",
  "IC": "Kanarų salos",
  "ID": "Indonezija",
  "IE": "Airija",
  "IL": "Izraelis",
  "IM": "Meno Sala",
  "IN": "Indija",
  "IO": "Indijos Vandenyno Britų Sritis",
  "IQ": "Irakas",
  "IR": "Iranas",
  "IS": "Islandija",
  "IT": "Italija",
  "Inds": "indus",
  "Ital": "senasis italų",
  "JE": "Džersis",
  "JM": "Jamaika",
  "JO": "Jordanija",
  "JP": "Japonija",
  "Jamo": "Jamo simboliai",
  "Java": "javiečių",
  "Jpan": "japonų",
  "Jurc": "Jurchen",
  "KE": "Kenija",
  "KG": "Kirgizija",
  "KH": "Kambodža",
  "KI": "Kiribatis",
  "KM": "Komorai",
  "KN": "Sent Kitsas ir Nevis",
  "KP": "Šiaurės Korėja",
  "KR": "Pietų Korėja",
  "KW": "Kuveitas",
  "KY": "Kaimanų Salos",
  "KZ": "Kazachstanas",
  "Kali": "kajah li",
  "Kana": "katakana",
  "Khar": "karošti",
  "Khmr": "khmerų",
  "Khoj": "Khojki",
  "Knda": "kanadų",
  "Kore": "korėjiečių",
  "Kpel": "Kpelų",
  "Kthi": "kaithi",
  "LA": "Laosas",
  "LB": "Libanas",
  "LC": "Sent Lusija",
  "LI": "Lichtenšteinas",
  "LK": "Šri Lanka",
  "LR": "Liberija",
  "LS": "Lesotas",
  "LT": "Lietuva",
  "LU": "Liuksemburgas",
  "LV": "Latvija",
  "LY": "Libija",
  "Lana": "lana",
  "Laoo": "laosiečių",
  "Latf": "fraktur lotynų",
  "Latg": "gėlų lotynų",
  "Latn": "lotynų",
  "Lepc": "lepča",
  "Limb": "limbu",
  "Lina": "linijiniai A",
  "Linb": "linijiniai B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "lician",
  "Lydi": "lidian",
  "MA": "Marokas",
  "MC": "Monakas",
  "MD": "Moldova",
  "ME": "Juodkalnija",
  "MF": "Sen Martenas",
  "MG": "Madagaskaras",
  "MH": "Maršalo Salos",
  "MK": "Šiaurės Makedonija",
  "ML": "Malis",
  "MM": "Mianmaras (Birma)",
  "MN": "Mongolija",
  "MO": "Ypatingasis Administracinis Kinijos Regionas Makao",
  "MP": "Marianos Šiaurinės Salos",
  "MQ": "Martinika",
  "MR": "Mauritanija",
  "MS": "Montseratas",
  "MT": "Malta",
  "MU": "Mauricijus",
  "MV": "Maldyvai",
  "MW": "Malavis",
  "MX": "Meksika",
  "MY": "Malaizija",
  "MZ": "Mozambikas",
  "Mahj": "Mahadžani",
  "Mand": "mandėjų",
  "Mani": "maničų",
  "Maya": "malų hieroglifai",
  "Mend": "Mende",
  "Merc": "Merojitų rankraštinis",
  "Mero": "meroitik",
  "Mlym": "malajalių",
  "Modi": "Modi",
  "Mong": "mongolų",
  "Moon": "mūn",
  "Mroo": "Mro",
  "Mtei": "meitei majek",
  "Mymr": "birmiečių",
  "NA": "Namibija",
  "NC": "Naujoji Kaledonija",
  "NE": "Nigeris",
  "NF": "Norfolko sala",
  "NG": "Nigerija",
  "NI": "Nikaragva",
  "NL": "Nyderlandai",
  "NO": "Norvegija",
  "NP": "Nepalas",
  "NR": "Nauru",
  "NU": "Niujė",
  "NZ": "Naujoji Zelandija",
  "Narb": "Senasis šiaurės arabų",
  "Nbat": "Nabatėjų",
  "Nkgb": "Naxi Geba",
  "Nkoo": "enko",
  "Nshu": "Nüshu",
  "OM": "Omanas",
  "Ogam": "ogham",
  "Olck": "ol čiki",
  "Orkh": "orkon",
  "Orya": "orijų",
  "Osma": "osmanų",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Prancūzijos Polinezija",
  "PG": "Papua Naujoji Gvinėja",
  "PH": "Filipinai",
  "PK": "Pakistanas",
  "PL": "Lenkija",
  "PM": "Sen Pjeras ir Mikelonas",
  "PN": "Pitkerno salos",
  "PR": "Puerto Rikas",
  "PS": "Palestinos teritorija",
  "PT": "Portugalija",
  "PW": "Palau",
  "PY": "Paragvajus",
  "Palm": "Palmiros",
  "Pauc": "Pau Cin Hau",
  "Perm": "senieji permės",
  "Phag": "pagsa pa",
  "Phli": "rašytiniai pahlavi",
  "Phlp": "pselter pahlavi",
  "Phlv": "buk pahvali",
  "Phnx": "foenikų",
  "Plrd": "polard fonetinė",
  "Prti": "rašytiniai partų",
  "QA": "Kataras",
  "QO": "Nuošali Okeanija",
  "RE": "Reunjonas",
  "RO": "Rumunija",
  "RS": "Serbija",
  "RU": "Rusija",
  "RW": "Ruanda",
  "Rjng": "rejang",
  "Roro": "rongorongo",
  "Runr": "runų",
  "SA": "Saudo Arabija",
  "SB": "Saliamono Salos",
  "SC": "Seišeliai",
  "SD": "Sudanas",
  "SE": "Švedija",
  "SG": "Singapūras",
  "SH": "Šv. Elenos Sala",
  "SI": "Slovėnija",
  "SJ": "Svalbardas ir Janas Majenas",
  "SK": "Slovakija",
  "SL": "Siera Leonė",
  "SM": "San Marinas",
  "SN": "Senegalas",
  "SO": "Somalis",
  "SR": "Surinamas",
  "SS": "Pietų Sudanas",
  "ST": "San Tomė ir Prinsipė",
  "SV": "Salvadoras",
  "SX": "Sint Martenas",
  "SY": "Sirija",
  "SZ": "Svazilandas",
  "Samr": "samariečių",
  "Sara": "sarati",
  "Sarb": "senoji pietų Arabijos",
  "Saur": "sauraštra",
  "Sgnw": "ženklų raštas",
  "Shaw": "šavių",
  "Shrd": "Šarados",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "sinhalų",
  "Sora": "Sora Sompeng",
  "Sund": "sundų",
  "Sylo": "syloti nagri",
  "Syrc": "sirų",
  "Syre": "estrangelo siriečių",
  "Syrj": "vakarų sirų",
  "Syrn": "rytų sirų",
  "TA": "Tristanas da Kunja",
  "TC": "Terkso ir Kaikoso Salos",
  "TD": "Čadas",
  "TF": "Prancūzijos Pietų sritys",
  "TG": "Togas",
  "TH": "Tailandas",
  "TJ": "Tadžikija",
  "TK": "Tokelau",
  "TL": "Rytų Timoras",
  "TM": "Turkmėnistanas",
  "TN": "Tunisas",
  "TO": "Tonga",
  "TR": "Turkija",
  "TT": "Trinidadas ir Tobagas",
  "TV": "Tuvalu",
  "TW": "Taivanas",
  "TZ": "Tanzanija",
  "Tagb": "tagbanva",
  "Takr": "Takri",
  "Tale": "tai le",
  "Talu": "naujasis Tailando lue",
  "Taml": "tamilų",
  "Tang": "Tangut",
  "Tavt": "tai vet",
  "Telu": "telugų",
  "Teng": "tengvar",
  "Tfng": "tifinag",
  "Tglg": "tagalogų",
  "Thaa": "hana",
  "Thai": "tajų",
  "Tibt": "tibetiečių",
  "Tirh": "Tirhuta",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "Jungtinių Valstijų Mažosios Tolimosios Salos",
  "UN": "Jungtinės Tautos",
  "US": "Jungtinės Valstijos",
  "UY": "Urugvajus",
  "UZ": "Uzbekistanas",
  "Ugar": "ugaritik",
  "VA": "Vatikano Miesto Valstybė",
  "VC": "Šventasis Vincentas ir Grenadinai",
  "VE": "Venesuela",
  "VG": "Didžiosios Britanijos Mergelių Salos",
  "VI": "Jungtinių Valstijų Mergelių Salos",
  "VN": "Vietnamas",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "Visp": "matoma kalba",
  "WF": "Volisas ir Futūna",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wole": "Woleai",
  "XA": "pseudo A",
  "XB": "pseudo B",
  "XK": "Kosovas",
  "Xpeo": "senieji persų",
  "Xsux": "Šumero Akado dantiraštis",
  "YE": "Jemenas",
  "YT": "Majotas",
  "Yiii": "ji",
  "ZA": "Pietų Afrika",
  "ZM": "Zambija",
  "ZW": "Zimbabvė",
  "ZZ": "nežinoma sritis",
  "Zinh": "paveldėtas",
  "Zmth": "matematiniai simboliai",
  "Zsye": "jaustukai",
  "Zsym": "simbolių",
  "Zxxx": "neparašyta",
  "Zyyy": "bendri",
  "Zzzz": "nežinomi rašmenys",
  "aa": "afarų",
  "ab": "abchazų",
  "ace": "ačinezų",
  "ach": "akolių",
  "ada": "adangmų",
  "ady": "adygėjų",
  "ae": "avestų",
  "aeb": "Tuniso arabų",
  "af": "afrikanų",
  "af_NA": "afrikanų (Namibija)",
  "af_ZA": "afrikanų (Pietų Afrika)",
  "afa": "afroazijos kalba",
  "afh": "afrihili",
  "agq": "aghemų",
  "ain": "ainų",
  "ak": "akanų",
  "ak_GH": "akanų (Gana)",
  "akk": "akadianų",
  "akz": "alabamiečių",
  "ale": "aleutų",
  "alg": "algonkuanų kalba",
  "aln": "albanų kalbos gegų tarmė",
  "alt": "pietų Altajaus",
  "am": "amharų",
  "am_ET": "amharų (Etiopija)",
  "an": "aragonesų",
  "ang": "senoji anglų",
  "anp": "angikų",
  "apa": "apačių kalba",
  "ar": "arabų",
  "ar_001": "šiuolaikinė standartinė arabų",
  "ar_AE": "arabų (Jungtiniai Arabų Emyratai)",
  "ar_BH": "arabų (Bahreinas)",
  "ar_DJ": "arabų (Džibutis)",
  "ar_DZ": "arabų (Alžyras)",
  "ar_EG": "arabų (Egiptas)",
  "ar_EH": "arabų (Vakarų Sachara)",
  "ar_ER": "arabų (Eritrėja)",
  "ar_IL": "arabų (Izraelis)",
  "ar_IQ": "arabų (Irakas)",
  "ar_JO": "arabų (Jordanija)",
  "ar_KM": "arabų (Komorai)",
  "ar_KW": "arabų (Kuveitas)",
  "ar_LB": "arabų (Libanas)",
  "ar_LY": "arabų (Libija)",
  "ar_MA": "arabų (Marokas)",
  "ar_MR": "arabų (Mauritanija)",
  "ar_OM": "arabų (Omanas)",
  "ar_PS": "arabų (Palestinos teritorija)",
  "ar_QA": "arabų (Kataras)",
  "ar_SA": "arabų (Saudo Arabija)",
  "ar_SD": "arabų (Sudanas)",
  "ar_SO": "arabų (Somalis)",
  "ar_SS": "arabų (Pietų Sudanas)",
  "ar_SY": "arabų (Sirija)",
  "ar_TD": "arabų (Čadas)",
  "ar_TN": "arabų (Tunisas)",
  "ar_YE": "arabų (Jemenas)",
  "arc": "aramaikų",
  "arn": "mapudungunų",
  "aro": "araonų",
  "arp": "arapahų",
  "arq": "Alžyro arabų",
  "art": "dirbtinė kalba",
  "arw": "aravakų",
  "ary": "Maroko arabų",
  "arz": "Egipto arabų",
  "as": "asamų",
  "as_IN": "asamų (Indija)",
  "asa": "asu",
  "ase": "Amerikos ženklų kalba",
  "ast": "asturianų",
  "ath": "athapaskanų kalba",
  "aus": "australų kalba",
  "av": "avarikų",
  "avk": "kotava",
  "awa": "avadhi",
  "ay": "aimarų",
  "az": "azerbaidžaniečių",
  "az_AZ": "azerbaidžaniečių (Azerbaidžanas)",
  "az_Cyrl": "azerbaidžaniečių (kirilica)",
  "az_Cyrl_AZ": "azerbaidžaniečių (kirilica, Azerbaidžanas)",
  "az_Latn": "azerbaidžaniečių (lotynų)",
  "az_Latn_AZ": "azerbaidžaniečių (lotynų, Azerbaidžanas)",
  "azb": "pietų Azerbaidžano",
  "ba": "baškirų",
  "bad": "bandų",
  "bai": "bamilekų kalba",
  "bal": "baluči",
  "ban": "baliečių",
  "bar": "bavarų",
  "bas": "basų",
  "bat": "baltų kalba",
  "bax": "bamunų",
  "bbc": "batak toba",
  "bbj": "ghomalų",
  "be": "baltarusių",
  "be_BY": "baltarusių (Baltarusija)",
  "bej": "bėjų",
  "bem": "bembų",
  "ber": "berberų",
  "bew": "betavi",
  "bez": "benų",
  "bfd": "bafutų",
  "bfq": "badaga",
  "bg": "bulgarų",
  "bg_BG": "bulgarų (Bulgarija)",
  "bgn": "vakarų beludžių",
  "bh": "biharų",
  "bho": "baučpuri",
  "bi": "bislama",
  "bik": "bikolų",
  "bin": "bini",
  "bjn": "bandžarų",
  "bkm": "komų",
  "bla": "siksikų",
  "bm": "bambarų",
  "bm_Latn": "bambarų (lotynų)",
  "bm_Latn_ML": "bambarų (lotynų, Malis)",
  "bn": "bengalų",
  "bn_BD": "bengalų (Bangladešas)",
  "bn_IN": "bengalų (Indija)",
  "bnt": "bantų",
  "bo": "tibetiečių",
  "bo_CN": "tibetiečių (Kinija)",
  "bo_IN": "tibetiečių (Indija)",
  "bpy": "bišnuprijos",
  "bqi": "bakhtiari",
  "br": "bretonų",
  "br_FR": "bretonų (Prancūzija)",
  "bra": "brajų",
  "brh": "brahujų",
  "brx": "bodo",
  "bs": "bosnių",
  "bs_BA": "bosnių (Bosnija ir Hercegovina)",
  "bs_Cyrl": "bosnių (kirilica)",
  "bs_Cyrl_BA": "bosnių (kirilica, Bosnija ir Hercegovina)",
  "bs_Latn": "bosnių (lotynų)",
  "bs_Latn_BA": "bosnių (lotynų, Bosnija ir Hercegovina)",
  "bss": "akūsų",
  "btk": "batakų",
  "bua": "buriatų",
  "bug": "buginezų",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumbų",
  "ca": "katalonų",
  "ca_AD": "katalonų (Andora)",
  "ca_ES": "katalonų (Ispanija)",
  "ca_FR": "katalonų (Prancūzija)",
  "ca_IT": "katalonų (Italija)",
  "cad": "kado",
  "cai": "Centrinės Amerikos indėnų kalba",
  "car": "karibų",
  "cau": "kaukaziečių kalba",
  "cay": "kaijūgų",
  "cch": "atsamų",
  "ccp": "Čakma",
  "ce": "čečėnų",
  "ceb": "sebuanų",
  "cel": "keltų kalba",
  "cgg": "čigų",
  "ch": "čamorų",
  "chb": "čibčų",
  "chg": "čagatų",
  "chk": "čukesų",
  "chm": "marių",
  "chn": "činuk žargonas",
  "cho": "čoktau",
  "chp": "čipvėjų",
  "chr": "čerokių",
  "chy": "čajenų",
  "ckb": "soranių kurdų",
  "cmc": "čamikų kalba",
  "co": "korsikiečių",
  "cop": "koptų",
  "cpe": "kreolų arba pidžinų kalba pagal anglų",
  "cpf": "kreolų arba pidžinų kalba pagal prancūzų",
  "cpp": "kreolų arba pidžinų kalba pagal portugalų",
  "cps": "capiznon",
  "cr": "kry",
  "crh": "Krymo turkų",
  "crp": "kreolų arba pidžinų kalba",
  "crs": "Seišelių kreolų ir prancūzų",
  "cs": "čekų",
  "cs_CZ": "čekų (Čekija)",
  "csb": "kašubų",
  "cu": "bažnytinė slavų",
  "cus": "kušitik kalba",
  "cv": "čiuvašų",
  "cy": "valų",
  "cy_GB": "valų (Didžioji Britanija)",
  "da": "danų",
  "da_DK": "danų (Danija)",
  "da_GL": "danų (Grenlandija)",
  "dak": "dakotų",
  "dar": "dargva",
  "dav": "taitų",
  "day": "bidayuh kalba",
  "de": "vokiečių",
  "de_AT": "vokiečių (Austrija)",
  "de_BE": "vokiečių (Belgija)",
  "de_CH": "vokiečių (Šveicarija)",
  "de_DE": "vokiečių (Vokietija)",
  "de_LI": "vokiečių (Lichtenšteinas)",
  "de_LU": "vokiečių (Liuksemburgas)",
  "del": "delavero",
  "den": "slave",
  "dgr": "dogribų",
  "din": "dinkų",
  "dje": "zarmų",
  "doi": "dogri",
  "dra": "dravidų kalba",
  "dsb": "žemutinių sorbų",
  "dtp": "centrinio Dusuno",
  "dua": "dualų",
  "dum": "Vidurio Vokietijos",
  "dv": "divehų",
  "dyo": "džiola-foni",
  "dyu": "dyulų",
  "dz": "botijų",
  "dz_BT": "botijų (Butanas)",
  "dzg": "dazagų",
  "ebu": "embu",
  "ee": "evių",
  "ee_GH": "evių (Gana)",
  "ee_TG": "evių (Togas)",
  "efi": "efik",
  "egl": "italų kalbos Emilijos tarmė",
  "egy": "senovės egiptiečių",
  "eka": "ekajuk",
  "el": "graikų",
  "el_CY": "graikų (Kipras)",
  "el_GR": "graikų (Graikija)",
  "elx": "elamitų",
  "en": "anglų",
  "en_AG": "anglų (Antigva ir Barbuda)",
  "en_AI": "anglų (Angilija)",
  "en_AS": "anglų (Amerikos Samoa)",
  "en_AU": "anglų (Australija)",
  "en_BB": "anglų (Barbadosas)",
  "en_BE": "anglų (Belgija)",
  "en_BM": "anglų (Bermuda)",
  "en_BS": "anglų (Bahamos)",
  "en_BW": "anglų (Botsvana)",
  "en_BZ": "anglų (Belizas)",
  "en_CA": "anglų (Kanada)",
  "en_CC": "anglų (Kokosų (Kilingo) Salos)",
  "en_CK": "anglų (Kuko Salos)",
  "en_CM": "anglų (Kamerūnas)",
  "en_CX": "anglų (Kalėdų Sala)",
  "en_DG": "anglų (Diego Garsija)",
  "en_DM": "anglų (Dominika)",
  "en_ER": "anglų (Eritrėja)",
  "en_FJ": "anglų (Fidžis)",
  "en_FK": "anglų (Folklando Salos)",
  "en_FM": "anglų (Mikronezija)",
  "en_GB": "anglų (Didžioji Britanija)",
  "en_GD": "anglų (Grenada)",
  "en_GG": "anglų (Gernsis)",
  "en_GH": "anglų (Gana)",
  "en_GI": "anglų (Gibraltaras)",
  "en_GM": "anglų (Gambija)",
  "en_GU": "anglų (Guamas)",
  "en_GY": "anglų (Gajana)",
  "en_HK": "anglų (Ypatingasis Administracinis Kinijos Regionas Honkongas)",
  "en_IE": "anglų (Airija)",
  "en_IM": "anglų (Meno Sala)",
  "en_IN": "anglų (Indija)",
  "en_IO": "anglų (Indijos Vandenyno Britų Sritis)",
  "en_JE": "anglų (Džersis)",
  "en_JM": "anglų (Jamaika)",
  "en_KE": "anglų (Kenija)",
  "en_KI": "anglų (Kiribatis)",
  "en_KN": "anglų (Sent Kitsas ir Nevis)",
  "en_KY": "anglų (Kaimanų Salos)",
  "en_LC": "anglų (Šventoji Liucija)",
  "en_LR": "anglų (Liberija)",
  "en_LS": "anglų (Lesotas)",
  "en_MG": "anglų (Madagaskaras)",
  "en_MH": "anglų (Maršalo Salos)",
  "en_MO": "anglų (Ypatingasis Administracinis Kinijos Regionas Makao)",
  "en_MP": "anglų (Marianos Šiaurinės Salos)",
  "en_MS": "anglų (Montseratas)",
  "en_MT": "anglų (Malta)",
  "en_MU": "anglų (Mauricijus)",
  "en_MW": "anglų (Malavis)",
  "en_MY": "anglų (Malaizija)",
  "en_NA": "anglų (Namibija)",
  "en_NF": "anglų (Norfolko sala)",
  "en_NG": "anglų (Nigerija)",
  "en_NR": "anglų (Nauru)",
  "en_NU": "anglų (Niujė)",
  "en_NZ": "anglų (Naujoji Zelandija)",
  "en_PG": "anglų (Papua Naujoji Gvinėja)",
  "en_PH": "anglų (Filipinai)",
  "en_PK": "anglų (Pakistanas)",
  "en_PN": "anglų (Pitkernas)",
  "en_PR": "anglų (Puerto Rikas)",
  "en_PW": "anglų (Palau)",
  "en_RW": "anglų (Ruanda)",
  "en_SB": "anglų (Saliamono Salos)",
  "en_SC": "anglų (Seišeliai)",
  "en_SD": "anglų (Sudanas)",
  "en_SG": "anglų (Singapūras)",
  "en_SH": "anglų (Šv. Elenos Sala)",
  "en_SL": "anglų (Siera Leonė)",
  "en_SS": "anglų (Pietų Sudanas)",
  "en_SX": "anglų (Sint Martenas)",
  "en_SZ": "anglų (Svazilandas)",
  "en_TC": "anglų (Terkso ir Kaikoso Salos)",
  "en_TK": "anglų (Tokelau)",
  "en_TO": "anglų (Tonga)",
  "en_TT": "anglų (Trinidadas ir Tobagas)",
  "en_TV": "anglų (Tuvalu)",
  "en_TZ": "anglų (Tanzanija)",
  "en_UG": "anglų (Uganda)",
  "en_UM": "anglų (Jungtinių Valstijų Mažosios Tolimosios Salos)",
  "en_US": "anglų (Jungtinės Valstijos)",
  "en_VC": "anglų (Šventasis Vincentas ir Grenadinai)",
  "en_VG": "anglų (Didžiosios Britanijos Mergelių Salos)",
  "en_VI": "anglų (Jungtinių Valstijų Mergelių Salos)",
  "en_VU": "anglų (Vanuatu)",
  "en_WS": "anglų (Samoa)",
  "en_ZA": "anglų (Pietų Afrika)",
  "en_ZM": "anglų (Zambija)",
  "en_ZW": "anglų (Zimbabvė)",
  "enm": "Vidurio Anglijos",
  "eo": "esperanto",
  "es": "ispanų",
  "es_419": "Lotynų Amerikos ispanų",
  "es_AR": "ispanų (Argentina)",
  "es_BO": "ispanų (Bolivija)",
  "es_CL": "ispanų (Čilė)",
  "es_CO": "ispanų (Kolumbija)",
  "es_CR": "ispanų (Kosta Rika)",
  "es_CU": "ispanų (Kuba)",
  "es_DO": "ispanų (Dominikos Respublika)",
  "es_EA": "ispanų (Seuta ir Melila)",
  "es_EC": "ispanų (Ekvadoras)",
  "es_ES": "ispanų (Ispanija)",
  "es_GQ": "ispanų (Pusiaujo Gvinėja)",
  "es_GT": "ispanų (Gvatemala)",
  "es_HN": "ispanų (Hondūras)",
  "es_IC": "ispanų (Kanarų salos)",
  "es_MX": "ispanų (Meksika)",
  "es_NI": "ispanų (Nikaragva)",
  "es_PA": "ispanų (Panama)",
  "es_PE": "ispanų (Peru)",
  "es_PH": "ispanų (Filipinai)",
  "es_PR": "ispanų (Puerto Rikas)",
  "es_PY": "ispanų (Paragvajus)",
  "es_SV": "ispanų (Salvadoras)",
  "es_US": "ispanų (Jungtinės Valstijos)",
  "es_UY": "ispanų (Urugvajus)",
  "es_VE": "ispanų (Venesuela)",
  "esu": "centrinės Aliaskos jupikų",
  "et": "estų",
  "et_EE": "estų (Estija)",
  "eu": "baskų",
  "eu_ES": "baskų (Ispanija)",
  "ewo": "evondo",
  "ext": "ispanų kalbos Ekstremadūros tarmė",
  "fa": "persų",
  "fa_AF": "persų (Afganistanas)",
  "fa_IR": "persų (Iranas)",
  "fan": "fangų",
  "fat": "fanti",
  "ff": "fulahų",
  "ff_CM": "fulahų (Kamerūnas)",
  "ff_GN": "fulahų (Gvinėja)",
  "ff_MR": "fulahų (Mauritanija)",
  "ff_SN": "fulahų (Senegalas)",
  "fi": "suomių",
  "fi_FI": "suomių (Suomija)",
  "fil": "filipiniečių",
  "fit": "suomių kalbos Tornedalio tarmė",
  "fiu": "finougrų kalba",
  "fj": "fidžių",
  "fo": "farerų",
  "fo_FO": "farerų (Farerų Salos)",
  "fon": "fon",
  "fr": "prancūzų",
  "fr_BE": "prancūzų (Belgija)",
  "fr_BF": "prancūzų (Burkina Fasas)",
  "fr_BI": "prancūzų (Burundis)",
  "fr_BJ": "prancūzų (Beninas)",
  "fr_BL": "prancūzų (Sen Bartelemi)",
  "fr_CA": "prancūzų (Kanada)",
  "fr_CD": "prancūzų (Kongas-Kinšasa)",
  "fr_CF": "prancūzų (Centrinės Afrikos Respublika)",
  "fr_CG": "prancūzų (Kongas-Brazavilis)",
  "fr_CH": "prancūzų (Šveicarija)",
  "fr_CI": "prancūzų (Dramblio Kaulo Krantas)",
  "fr_CM": "prancūzų (Kamerūnas)",
  "fr_DJ": "prancūzų (Džibutis)",
  "fr_DZ": "prancūzų (Alžyras)",
  "fr_FR": "prancūzų (Prancūzija)",
  "fr_GA": "prancūzų (Gabonas)",
  "fr_GF": "prancūzų (Prancūzijos Gviana)",
  "fr_GN": "prancūzų (Gvinėja)",
  "fr_GP": "prancūzų (Gvadelupa)",
  "fr_GQ": "prancūzų (Pusiaujo Gvinėja)",
  "fr_HT": "prancūzų (Haitis)",
  "fr_KM": "prancūzų (Komorai)",
  "fr_LU": "prancūzų (Liuksemburgas)",
  "fr_MA": "prancūzų (Marokas)",
  "fr_MC": "prancūzų (Monakas)",
  "fr_MF": "prancūzų (Sen Martenas)",
  "fr_MG": "prancūzų (Madagaskaras)",
  "fr_ML": "prancūzų (Malis)",
  "fr_MQ": "prancūzų (Martinika)",
  "fr_MR": "prancūzų (Mauritanija)",
  "fr_MU": "prancūzų (Mauricijus)",
  "fr_NC": "prancūzų (Naujoji Kaledonija)",
  "fr_NE": "prancūzų (Nigeris)",
  "fr_PF": "prancūzų (Prancūzų Polinezija)",
  "fr_PM": "prancūzų (Sen Pjeras ir Mikelonas)",
  "fr_RE": "prancūzų (Reunjonas)",
  "fr_RW": "prancūzų (Ruanda)",
  "fr_SC": "prancūzų (Seišeliai)",
  "fr_SN": "prancūzų (Senegalas)",
  "fr_SY": "prancūzų (Sirija)",
  "fr_TD": "prancūzų (Čadas)",
  "fr_TG": "prancūzų (Togas)",
  "fr_TN": "prancūzų (Tunisas)",
  "fr_VU": "prancūzų (Vanuatu)",
  "fr_WF": "prancūzų (Volisas ir Futuna)",
  "fr_YT": "prancūzų (Majotas)",
  "frc": "kadžunų prancūzų",
  "frm": "Vidurio Prancūzijos",
  "fro": "senoji prancūzų",
  "frp": "arpitano",
  "frr": "šiaurinių fryzų",
  "frs": "rytų fryzų",
  "fur": "friulių",
  "fy": "vakarų fryzų",
  "fy_NL": "vakarų fryzų (Nyderlandai)",
  "ga": "airių",
  "ga_IE": "airių (Airija)",
  "gaa": "ga",
  "gag": "gagaūzų",
  "gan": "kinų kalbos dziangsi tarmė",
  "gay": "gajo",
  "gba": "gbaja",
  "gbz": "zoroastrų dari",
  "gd": "škotų (gėlų)",
  "gd_GB": "škotų (Didžioji Britanija)",
  "gem": "germanų kalba",
  "gez": "gyz",
  "gil": "kiribati",
  "gl": "galisų",
  "gl_ES": "galisų (Ispanija)",
  "glk": "gilaki",
  "gmh": "Vidurio Aukštosios Vokietijos",
  "gn": "gvaranių",
  "goh": "senoji Aukštosios Vokietijos",
  "gom": "Goa konkanių",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotų",
  "grb": "grebo",
  "grc": "senovės graikų",
  "gsw": "Šveicarijos vokiečių",
  "gu": "gudžaratų",
  "gu_IN": "gudžaratų (Indija)",
  "guc": "vajų",
  "gur": "frafra",
  "guz": "gusi",
  "gv": "meniečių",
  "gv_IM": "meniečių (Meno Sala)",
  "gwi": "gvičino",
  "ha": "hausų",
  "ha_GH": "hausų (Gana)",
  "ha_Latn": "hausų (lotynų)",
  "ha_Latn_GH": "hausų (lotynų, Gana)",
  "ha_Latn_NE": "hausų (lotynų, Nigeris)",
  "ha_Latn_NG": "hausų (lotynų, Nigerija)",
  "ha_NE": "hausų (Nigeris)",
  "ha_NG": "hausų (Nigerija)",
  "hai": "haido",
  "hak": "kinų kalbos hakų tarmė",
  "haw": "havajiečių",
  "he": "hebrajų",
  "he_IL": "hebrajų (Izraelis)",
  "hi": "hindi",
  "hi_IN": "hindi (Indija)",
  "hif": "Fidžio hindi",
  "hil": "hiligainonų",
  "him": "himačali",
  "hit": "hititų",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "kroatų",
  "hr_BA": "kroatų (Bosnija ir Hercegovina)",
  "hr_HR": "kroatų (Kroatija)",
  "hsb": "aukštutinių sorbų",
  "hsn": "kinų kalbos hunano tarmė",
  "ht": "Haičio",
  "hu": "vengrų",
  "hu_HU": "vengrų (Vengrija)",
  "hup": "hupa",
  "hy": "armėnų",
  "hy_AM": "armėnų (Armėnija)",
  "hz": "hererų",
  "ia": "tarpinė",
  "iba": "iban",
  "ibb": "ibibijų",
  "id": "indoneziečių",
  "id_ID": "indoneziečių (Indonezija)",
  "ie": "interkalba",
  "ig": "igbų",
  "ig_NG": "igbų (Nigerija)",
  "ii": "sičuan ji",
  "ii_CN": "sičuan ji (Kinija)",
  "ijo": "ijo",
  "ik": "inupiakų",
  "ilo": "ilokų",
  "inc": "indų kalba",
  "ine": "indoeuropiečių kalba",
  "inh": "ingušų",
  "io": "ido",
  "ira": "iraniečių kalba",
  "iro": "irako kalba",
  "is": "islandų",
  "is_IS": "islandų (Islandija)",
  "it": "italų",
  "it_CH": "italų (Šveicarija)",
  "it_IT": "italų (Italija)",
  "it_SM": "italų (San Marinas)",
  "iu": "inukitut",
  "izh": "ingrų",
  "ja": "japonų",
  "ja_JP": "japonų (Japonija)",
  "jam": "Jamaikos kreolų anglų",
  "jbo": "loiban",
  "jgo": "ngombų",
  "jmc": "mačamų",
  "jpr": "judėjų persų",
  "jrb": "judėjų arabų",
  "jut": "danų kalbos jutų tarmė",
  "jv": "javiečių",
  "ka": "gruzinų",
  "ka_GE": "gruzinų (Gruzija)",
  "kaa": "karakalpakų",
  "kab": "kebailų",
  "kac": "kačinų",
  "kaj": "ju",
  "kam": "kembų",
  "kar": "karenų",
  "kaw": "kavių",
  "kbd": "kabardinų",
  "kbl": "kanembų",
  "kcg": "tyap",
  "kde": "makondų",
  "kea": "Žaliojo Kyšulio kreolų",
  "ken": "kenyang",
  "kfo": "koro",
  "kg": "Kongo",
  "kgp": "kaingang",
  "kha": "kasi",
  "khi": "koisan kalba",
  "kho": "kotanezų",
  "khq": "kojra čini",
  "khw": "khovarų",
  "ki": "kikujų",
  "ki_KE": "kikujų (Kenija)",
  "kiu": "kirmanjki",
  "kj": "kuaniama",
  "kk": "kazachų",
  "kk_Cyrl": "kazachų (kirilica)",
  "kk_Cyrl_KZ": "kazachų (kirilica, Kazachstanas)",
  "kk_KZ": "kazachų (Kazachstanas)",
  "kkj": "kako",
  "kl": "kalalisut",
  "kl_GL": "kalalisut (Grenlandija)",
  "kln": "kalenjinų",
  "km": "khmerų",
  "km_KH": "khmerų (Kambodža)",
  "kmb": "kimbundu",
  "kn": "kanadų",
  "kn_IN": "kanadų (Indija)",
  "ko": "korėjiečių",
  "ko_KP": "korėjiečių (Šiaurės Korėja)",
  "ko_KR": "korėjiečių (Pietų Korėja)",
  "koi": "komių-permių",
  "kok": "konkanių",
  "kos": "kosreanų",
  "kpe": "kpelių",
  "kr": "kanurių",
  "krc": "karačiajų balkarijos",
  "kri": "krio",
  "krj": "kinaray-a",
  "krl": "karelų",
  "kro": "kru kalba",
  "kru": "kuruk",
  "ks": "kašmyrų",
  "ks_Arab": "kašmyrų (arabų)",
  "ks_Arab_IN": "kašmyrų (arabų, Indija)",
  "ks_IN": "kašmyrų (Indija)",
  "ksb": "šambalų",
  "ksf": "bafų",
  "ksh": "kolognų",
  "ku": "kurdų",
  "kum": "kumikų",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "kornų",
  "kw_GB": "kornų (Didžioji Britanija)",
  "ky": "kirgizų",
  "ky_Cyrl": "kirgizų (kirilica)",
  "ky_Cyrl_KG": "kirgizų (kirilica, Kirgizija)",
  "ky_KG": "kirgizų (Kirgizija)",
  "la": "lotynų",
  "lad": "ladino",
  "lag": "langi",
  "lah": "landa",
  "lam": "lamba",
  "lb": "liuksemburgiečių",
  "lb_LU": "liuksemburgiečių (Liuksemburgas)",
  "lez": "lezginų",
  "lfn": "naujoji frankų kalba",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgiečių",
  "lij": "ligūrų",
  "liv": "lyvių",
  "lkt": "lakotų",
  "lmo": "lombardų",
  "ln": "ngalų",
  "ln_AO": "ngalų (Angola)",
  "ln_CD": "ngalų (Kongas-Kinšasa)",
  "ln_CF": "ngalų (Centrinės Afrikos Respublika)",
  "ln_CG": "ngalų (Kongas-Brazavilis)",
  "lo": "laosiečių",
  "lo_LA": "laosiečių (Laosas)",
  "lol": "mongų",
  "lou": "Luizianos kreolų",
  "loz": "lozių",
  "lrc": "šiaurės luri",
  "lt": "lietuvių",
  "lt_LT": "lietuvių (Lietuva)",
  "ltg": "latgalių",
  "lu": "luba katanga",
  "lu_CD": "luba katanga (Kongas-Kinšasa)",
  "lua": "luba lulua",
  "lui": "luiseno",
  "lun": "Lundos",
  "luo": "luo",
  "lus": "mizo",
  "luy": "luja",
  "lv": "latvių",
  "lv_LV": "latvių (Latvija)",
  "lzh": "klasikinė kinų",
  "lzz": "laz",
  "mad": "madurezų",
  "maf": "mafų",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "Makasaro",
  "man": "mandingų",
  "map": "austronezų",
  "mas": "masajų",
  "mde": "mabų",
  "mdf": "mokša",
  "mdr": "mandarų",
  "men": "mende",
  "mer": "merų",
  "mfe": "morisijų",
  "mg": "malagasų",
  "mg_MG": "malagasų (Madagaskaras)",
  "mga": "Vidurio Airijos",
  "mgh": "makua-maeto",
  "mgo": "meta",
  "mh": "Maršalo Salų",
  "mi": "maorių",
  "mic": "mikmakų",
  "min": "minangkabau",
  "mis": "įvairios kalbos",
  "mk": "makedonų",
  "mk_MK": "makedonų (Makedonija)",
  "mkh": "mon khmer kalba",
  "ml": "malajalių",
  "ml_IN": "malajalių (Indija)",
  "mn": "mongolų",
  "mn_Cyrl": "mongolų (kirilica)",
  "mn_Cyrl_MN": "mongolų (kirilica, Mongolija)",
  "mn_MN": "mongolų (Mongolija)",
  "mnc": "manču",
  "mni": "manipurių",
  "mno": "manobo kalba",
  "mo": "moldavų",
  "moh": "mohok",
  "mos": "mosi",
  "mr": "maratų",
  "mr_IN": "maratų (Indija)",
  "mrj": "vakarų mari",
  "ms": "malajiečių",
  "ms_BN": "malajiečių (Brunėjus)",
  "ms_Latn": "malajiečių (lotynų)",
  "ms_Latn_BN": "malajiečių (lotynų, Brunėjus)",
  "ms_Latn_MY": "malajiečių (lotynų, Malaizija)",
  "ms_Latn_SG": "malajiečių (lotynų, Singapūras)",
  "ms_MY": "malajiečių (Malaizija)",
  "ms_SG": "malajiečių (Singapūras)",
  "mt": "maltiečių",
  "mt_MT": "maltiečių (Malta)",
  "mua": "mundangų",
  "mul": "kelios kalbos",
  "mun": "munda kalba",
  "mus": "krykų",
  "mwl": "mirandezų",
  "mwr": "marvari",
  "mwv": "mentavai",
  "my": "birmiečių",
  "my_MM": "birmiečių (Mianmaras (Birma))",
  "mye": "mjenų",
  "myn": "majanų",
  "myv": "erzyjų",
  "mzn": "mazenderanių",
  "na": "naurų",
  "nah": "nahuatlų",
  "nai": "Šiaurės Amerikos indėnų kalba",
  "nan": "kinų kalbos pietų minų tarmė",
  "nap": "neapoliečių",
  "naq": "nama",
  "nb": "norvegų bukmolas",
  "nb_NO": "Norvegijos rašytinė – būkmolų (Norvegija)",
  "nb_SJ": "Norvegijos rašytinė – būkmolų (Svalbardas ir Janas Majenas)",
  "nd": "šiaurės ndebelų",
  "nd_ZW": "šiaurės ndebelų (Zimbabvė)",
  "nds": "Žemutinės Vokietijos",
  "nds_NL": "Žemutinės Saksonijos (Nyderlandai)",
  "ne": "nepaliečių",
  "ne_IN": "nepaliečių (Indija)",
  "ne_NP": "nepaliečių (Nepalas)",
  "new": "nevari",
  "ng": "ndongų",
  "nia": "nias",
  "nic": "Nigerio kordofanų kalba",
  "niu": "niujiečių",
  "njo": "ao naga",
  "nl": "olandų",
  "nl_AW": "olandų (Aruba)",
  "nl_BE": "olandų (Belgija)",
  "nl_BQ": "olandų (Karibų Nyderlandai)",
  "nl_CW": "olandų (Kiurasao)",
  "nl_NL": "olandų (Nyderlandai)",
  "nl_SR": "olandų (Surinamas)",
  "nl_SX": "olandų (Sint Martenas)",
  "nmg": "kvasių",
  "nn": "naujoji norvegų",
  "nn_NO": "naujoji norvegų (Norvegija)",
  "nnh": "ngiembūnų",
  "no": "norvegų",
  "no_NO": "norvegų (Norvegija)",
  "nog": "nogų",
  "non": "senoji norsų",
  "nov": "novial",
  "nqo": "enko",
  "nr": "pietų ndebele",
  "nso": "šiaurės Soto",
  "nub": "nubijos kalba",
  "nus": "nuerų",
  "nv": "navajų",
  "nwc": "klasikinė nevari",
  "ny": "nianjų",
  "nym": "niamvezi",
  "nyn": "niankolų",
  "nyo": "niorų",
  "nzi": "nzima",
  "oc": "očitarų",
  "oj": "ojibva",
  "om": "oromų",
  "om_ET": "oromų (Etiopija)",
  "om_KE": "oromų (Kenija)",
  "or": "odijų",
  "or_IN": "orijų (Indija)",
  "os": "osetinų",
  "os_GE": "osetinų (Gruzija)",
  "os_RU": "osetinų (Rusija)",
  "osa": "osage",
  "ota": "osmanų turkų",
  "oto": "otomanų kalba",
  "pa": "pendžabų",
  "pa_Arab": "pendžabų (arabų)",
  "pa_Arab_PK": "pendžabų (arabų, Pakistanas)",
  "pa_Guru": "pendžabų (gurmuki)",
  "pa_Guru_IN": "pendžabų (gurmuki, Indija)",
  "pa_IN": "pendžabų (Indija)",
  "pa_PK": "pendžabų (Pakistanas)",
  "paa": "papuasų kalba",
  "pag": "pangasinanų",
  "pal": "vidurinė persų kalba",
  "pam": "pampangų",
  "pap": "papiamento",
  "pau": "palauliečių",
  "pcd": "pikardų",
  "pcm": "Nigerijos pidžinų",
  "pdc": "Pensilvanijos vokiečių",
  "pdt": "vokiečių kalbos žemaičių tarmė",
  "peo": "senoji persų",
  "pfl": "vokiečių kalbos Pfalco tarmė",
  "phi": "filipinų kalba",
  "phn": "finikiečių",
  "pi": "pali",
  "pl": "lenkų",
  "pl_PL": "lenkų (Lenkija)",
  "pms": "italų kalbos Pjemonto tarmė",
  "pnt": "Ponto",
  "pon": "Ponapės",
  "pra": "prakrit kalba",
  "prg": "prūsų",
  "pro": "senovės provansalų",
  "ps": "puštūnų",
  "ps_AF": "puštūnų (Afganistanas)",
  "pt": "portugalų",
  "pt_AO": "portugalų (Angola)",
  "pt_BR": "portugalų (Brazilija)",
  "pt_CV": "portugalų (Žaliasis Kyšulys)",
  "pt_GW": "portugalų (Bisau Gvinėja)",
  "pt_MO": "portugalų (Ypatingasis Administracinis Kinijos Regionas Makao)",
  "pt_MZ": "portugalų (Mozambikas)",
  "pt_PT": "portugalų (Portugalija)",
  "pt_ST": "portugalų (San Tomė ir Prinsipė)",
  "pt_TL": "portugalų (Rytų Timoras)",
  "qu": "kečujų",
  "qu_BO": "kečujų (Bolivija)",
  "qu_EC": "kečujų (Ekvadoras)",
  "qu_PE": "kečujų (Peru)",
  "quc": "kičių",
  "qug": "Čimboraso aukštumų kečujų",
  "raj": "Radžastano",
  "rap": "rapanui",
  "rar": "rarotonganų",
  "rgn": "italų kalbos Romanijos tarmė",
  "rif": "rifų",
  "rm": "retoromanų",
  "rm_CH": "retoromanų (Šveicarija)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundis)",
  "ro": "rumunų",
  "ro_MD": "rumunų (Moldova)",
  "ro_RO": "rumunų (Rumunija)",
  "roa": "romanų kalba",
  "rof": "rombo",
  "rom": "romų",
  "root": "rūt",
  "rtm": "rotumanų",
  "ru": "rusų",
  "ru_BY": "rusų (Baltarusija)",
  "ru_KG": "rusų (Kirgizija)",
  "ru_KZ": "rusų (Kazachstanas)",
  "ru_MD": "rusų (Moldova)",
  "ru_RU": "rusų (Rusija)",
  "ru_UA": "rusų (Ukraina)",
  "rue": "rusinų",
  "rug": "Rovianos",
  "rup": "aromanių",
  "rw": "kinjaruandų",
  "rw_RW": "kinjaruandų (Ruanda)",
  "rwk": "rua",
  "sa": "sanskritas",
  "sad": "sandavių",
  "sah": "jakutų",
  "sai": "Pietų Amerikos indėnų kalba",
  "sal": "sališan kalba",
  "sam": "samarėjų aramių",
  "saq": "sambūrų",
  "sas": "sasak",
  "sat": "santalių",
  "saz": "sauraštrų",
  "sba": "ngambajų",
  "sbp": "sangų",
  "sc": "sardiniečių",
  "scn": "siciliečių",
  "sco": "škotų",
  "sd": "sindų",
  "sdc": "sasaresų sardinų",
  "sdh": "pietų kurdų",
  "se": "šiaurės samių",
  "se_FI": "šiaurės samių (Suomija)",
  "se_NO": "šiaurės samių (Norvegija)",
  "se_SE": "šiaurės samių (Švedija)",
  "see": "senecų",
  "seh": "senų",
  "sei": "seri",
  "sel": "selkup",
  "sem": "samitų kalba",
  "ses": "kojraboro seni",
  "sg": "sango",
  "sg_CF": "sango (Centrinės Afrikos Respublika)",
  "sga": "senoji airių",
  "sgn": "ženklų kalba",
  "sgs": "žemaičių",
  "sh": "serbų-kroatų",
  "sh_BA": "serbų-kroatų (Bosnija ir Hercegovina)",
  "shi": "tachelhitų",
  "shn": "šan",
  "shu": "chadian arabų",
  "si": "sinhalų",
  "si_LK": "sinhalų (Šri Lanka)",
  "sid": "sidamų",
  "sio": "siouan kalba",
  "sit": "sino tibeto kalba",
  "sk": "slovakų",
  "sk_SK": "slovakų (Slovakija)",
  "sl": "slovėnų",
  "sl_SI": "slovėnų (Slovėnija)",
  "sla": "slavų kalba",
  "sli": "sileziečių žemaičių",
  "sly": "selajarų",
  "sm": "Samoa",
  "sma": "pietų samių",
  "smi": "samių kalba",
  "smj": "Liuleo samių",
  "smn": "Inario samių",
  "sms": "Skolto samių",
  "sn": "šonų",
  "sn_ZW": "šonų (Zimbabvė)",
  "snk": "soninke",
  "so": "somaliečių",
  "so_DJ": "somaliečių (Džibutis)",
  "so_ET": "somaliečių (Etiopija)",
  "so_KE": "somaliečių (Kenija)",
  "so_SO": "somaliečių (Somalis)",
  "sog": "sogdien",
  "son": "songhai",
  "sq": "albanų",
  "sq_AL": "albanų (Albanija)",
  "sq_MK": "albanų (Makedonija)",
  "sq_XK": "albanų (Kosovas)",
  "sr": "serbų",
  "sr_BA": "serbų (Bosnija ir Hercegovina)",
  "sr_Cyrl": "serbų (kirilica)",
  "sr_Cyrl_BA": "serbų (kirilica, Bosnija ir Hercegovina)",
  "sr_Cyrl_ME": "serbų (kirilica, Juodkalnija)",
  "sr_Cyrl_RS": "serbų (kirilica, Serbija)",
  "sr_Cyrl_XK": "serbų (kirilica, Kosovas)",
  "sr_Latn": "serbų (lotynų)",
  "sr_Latn_BA": "serbų (lotynų, Bosnija ir Hercegovina)",
  "sr_Latn_ME": "serbų (lotynų, Juodkalnija)",
  "sr_Latn_RS": "serbų (lotynų, Serbija)",
  "sr_Latn_XK": "serbų (lotynų, Kosovas)",
  "sr_ME": "serbų (Juodkalnija)",
  "sr_RS": "serbų (Serbija)",
  "sr_XK": "serbų (Kosovas)",
  "srn": "sranan tongo",
  "srr": "sererų",
  "ss": "svatų",
  "ssa": "Nilo Sacharos kalba",
  "ssy": "saho",
  "st": "pietų Soto",
  "stq": "Saterlendo fryzų",
  "su": "sundų",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "šumerų",
  "sv": "švedų",
  "sv_AX": "švedų (Alandų Salos)",
  "sv_FI": "švedų (Suomija)",
  "sv_SE": "švedų (Švedija)",
  "sw": "suahilių",
  "sw_CD": "Kongo suahilių",
  "sw_KE": "suahilių (Kenija)",
  "sw_TZ": "suahilių (Tanzanija)",
  "sw_UG": "suahilių (Uganda)",
  "swb": "Komorų",
  "swc": "Kongo suahilių",
  "syc": "klasikinė sirų",
  "syr": "sirų",
  "szl": "sileziečių",
  "ta": "tamilų",
  "ta_IN": "tamilų (Indija)",
  "ta_LK": "tamilų (Šri Lanka)",
  "ta_MY": "tamilų (Malaizija)",
  "ta_SG": "tamilų (Singapūras)",
  "tai": "tajų kalba",
  "tcy": "tulų",
  "te": "telugų",
  "te_IN": "telugų (Indija)",
  "tem": "timne",
  "teo": "teso",
  "ter": "Tereno",
  "tet": "tetum",
  "tg": "tadžikų",
  "th": "tajų",
  "th_TH": "tajų (Tailandas)",
  "ti": "tigrajų",
  "ti_ER": "tigrajų (Eritrėja)",
  "ti_ET": "tigrajų (Etiopija)",
  "tig": "tigre",
  "tiv": "tiv",
  "tk": "turkmėnų",
  "tkl": "Tokelau",
  "tkr": "tsakurų",
  "tl": "tagalogų",
  "tl_PH": "tagalogų (Filipinai)",
  "tlh": "klingonų",
  "tli": "tlingitų",
  "tly": "talyšų",
  "tmh": "tamašek",
  "tn": "tsvanų",
  "to": "tonganų",
  "to_TO": "tonganų (Tonga)",
  "tog": "niasa tongų",
  "tpi": "Papua pidžinų",
  "tr": "turkų",
  "tr_CY": "turkų (Kipras)",
  "tr_TR": "turkų (Turkija)",
  "tru": "turoyo",
  "trv": "Taroko",
  "ts": "tsongų",
  "tsd": "tsakonų",
  "tsi": "tsimšian",
  "tt": "totorių",
  "ttt": "musulmonų tatų",
  "tum": "tumbukų",
  "tup": "tupi kalba",
  "tut": "altaikų kalba",
  "tvl": "Tuvalu",
  "tw": "tvi",
  "twq": "tasavakų",
  "ty": "taitiečių",
  "tyv": "tuvių",
  "tzm": "Centrinio Maroko tamazitų",
  "udm": "udmurtų",
  "ug": "uigūrų",
  "ug_Arab": "uigūrų (arabų)",
  "ug_Arab_CN": "uigūrų (arabų, Kinija)",
  "ug_CN": "uigūrų (Kinija)",
  "uga": "ugaritų",
  "uk": "ukrainiečių",
  "uk_UA": "ukrainiečių (Ukraina)",
  "umb": "umbundu",
  "und": "nežinoma kalba",
  "ur": "urdų",
  "ur_IN": "urdų (Indija)",
  "ur_PK": "urdų (Pakistanas)",
  "uz": "uzbekų",
  "uz_AF": "uzbekų (Afganistanas)",
  "uz_Arab": "uzbekų (arabų)",
  "uz_Arab_AF": "uzbekų (arabų, Afganistanas)",
  "uz_Cyrl": "uzbekų (kirilica)",
  "uz_Cyrl_UZ": "uzbekų (kirilica, Uzbekistanas)",
  "uz_Latn": "uzbekų (lotynų)",
  "uz_Latn_UZ": "uzbekų (lotynų, Uzbekistanas)",
  "uz_UZ": "uzbekų (Uzbekistanas)",
  "vai": "vai",
  "ve": "vendų",
  "vec": "venetų",
  "vep": "vepsų",
  "vi": "vietnamiečių",
  "vi_VN": "vietnamiečių (Vietnamas)",
  "vls": "vakarų flamandų",
  "vmf": "pagrindinė frankonų",
  "vo": "volapiuko",
  "vot": "Votik",
  "vro": "veru",
  "vun": "vunjo",
  "wa": "valonų",
  "wae": "valserų",
  "wak": "vakašan kalba",
  "wal": "valamo",
  "war": "varai",
  "was": "Vašo",
  "wbp": "valrpiri",
  "wen": "sorbų kalba",
  "wo": "volofų",
  "wuu": "kinų kalbos vu tarmė",
  "xal": "kalmukų",
  "xh": "kosų",
  "xmf": "megrelų",
  "xog": "sogų",
  "yao": "jao",
  "yap": "japezų",
  "yav": "jangbenų",
  "ybb": "jembų",
  "yi": "jidiš",
  "yo": "jorubų",
  "yo_BJ": "jorubų (Beninas)",
  "yo_NG": "jorubų (Nigerija)",
  "ypk": "jupik kalba",
  "yrl": "njengatu",
  "yue": "kinų kalbos Kantono tarmė",
  "za": "chuang",
  "zap": "zapotekų",
  "zbl": "BLISS simbolių",
  "zea": "zelandų",
  "zen": "zenaga",
  "zgh": "standartinė Maroko tamazigtų",
  "zh": "kinų",
  "zh_CN": "kinų (Kinija)",
  "zh_HK": "kinų (Ypatingasis Administracinis Kinijos Regionas Honkongas)",
  "zh_Hans": "kinų (supaprastinti)",
  "zh_Hans_CN": "kinų (supaprastinti, Kinija)",
  "zh_Hans_HK":
      "kinų (supaprastinti, Ypatingasis Administracinis Kinijos Regionas Honkongas)",
  "zh_Hans_MO":
      "kinų (supaprastinti, Ypatingasis Administracinis Kinijos Regionas Makao)",
  "zh_Hans_SG": "kinų (supaprastinti, Singapūras)",
  "zh_Hant": "kinų (tradiciniai)",
  "zh_Hant_HK":
      "kinų (tradiciniai, Ypatingasis Administracinis Kinijos Regionas Honkongas)",
  "zh_Hant_MO":
      "kinų (tradiciniai, Ypatingasis Administracinis Kinijos Regionas Makao)",
  "zh_Hant_TW": "kinų (tradiciniai, Taivanas)",
  "zh_MO": "kinų (Ypatingasis Administracinis Kinijos Regionas Makao)",
  "zh_SG": "kinų (Singapūras)",
  "zh_TW": "kinų (Taivanas)",
  "znd": "zande",
  "zu": "zulų",
  "zu_ZA": "zulų (Pietų Afrika)",
  "zun": "Zuni",
  "zxx": "nėra kalbinio turinio",
  "zza": "zaza"
};
