const names = {
  "asa": "Asu",
  "ast": "Asturian",
  "ay": "Aymara",
  "bfd": "Bafut",
  "bss": "Akoose",
  "bug": "Buginese",
  "cgg": "Chiga",
  "chk": "Chuukese",
  "cv": "Chuvash",
  "dje": "Zarmaeg",
  "dua": "Duala",
  "frp": "Arpitan",
  "frr": "Ffriseg y Gogledd",
  "gmh": "Uchel Almaeneg Canol",
  "goh": "Hen Uchel Almaeneg",
  "kbd": "Circaseg Dwyreiniol",
  "kcg": "Tyap",
  "khw": "Khowar",
  "ki": "ki",
  "ltg": "Latgalieg",
  "mgo": "Metaʼ",
  "mrj": "Western Mari",
  "mua": "Mas",
  "mul": "mwy nag un iaith",
  "mzn": "Mazanderani",
  "nds": "Isel Almaeneg",
  "nl_BE": "Iseldireg (Gwlad Belg)",
  "nqo": "NʼKo",
  "or": "Oriya",
  "pau": "Palauan",
  "pnt": "Pontic",
  "rm": "Romaunsch",
  "root": "y Gwraidd",
  "sgs": "Samogitian",
  "smn": "Sami Inari",
  "srr": "Serer",
  "st": "Sesotheg",
  "stq": "Saterland Frisian",
  "ter": "Tereno",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Twrcmeneg",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tsd": "Tsakonian",
  "tum": "Tumbuka",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "und": "Iaith Anhysbys",
  "vep": "Veps",
  "vo": "Volapük",
  "vot": "Votic",
  "vun": "Vunjo",
  "wae": "Walser",
  "war": "Waray",
  "yav": "Yangben",
  "zgh": "Tamazight Safonol Moroco",
  "zh": "Tsieineeg",
  "zh_Hans": "Tsieineeg (Symledig)",
  "zh_Hant": "Tsieineeg (Traddodiadol)",
  "zun": "Zuni",
  "zza": "Zazäeg"
};
