const names = {
  "AD": "Andɔr",
  "AE": "Arabu mara kafoli",
  "AF": "Afiganistaŋ",
  "AG": "Antiga-ni-Barbuda",
  "AI": "Angiya",
  "AL": "Alibani",
  "AM": "Arimeni",
  "AN": "Peyiba ka Antiyi",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Arizantin",
  "AS": "Samowa amerikani",
  "AT": "Otirisi",
  "AU": "Ositirali",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azɛrbayjaŋ",
  "BA": "Bozni-Ɛrizigovini",
  "BB": "Barbadi",
  "BD": "Bɛngiladɛsi",
  "BE": "Bɛliziki",
  "BF": "Burukina Faso",
  "BG": "Buligari",
  "BH": "Bareyini",
  "BI": "Burundi",
  "BJ": "Benɛn",
  "BL": "St. Barthélemy",
  "BM": "Bermudi",
  "BN": "Burinɛyi",
  "BO": "Bolivi",
  "BQ": "Caribbean Netherlands",
  "BR": "Berezili",
  "BS": "Bahamasi",
  "BT": "Butaŋ",
  "BV": "Bouvet Island",
  "BW": "Bɔtisiwana",
  "BY": "Belarusi",
  "BZ": "Belizi",
  "CA": "Kanada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Kongo ka republiki demɔkratiki",
  "CF": "Santarafiriki",
  "CG": "Kongo",
  "CH": "Suwisi",
  "CI": "Kodiwari",
  "CK": "Kuki Gun",
  "CL": "Sili",
  "CM": "Kameruni",
  "CN": "Siniwajamana",
  "CO": "Kolombi",
  "CR": "Kɔsitarika",
  "CS": "Serbi-ni-Mɔntenegro",
  "CU": "Kuba",
  "CV": "Capivɛrdi",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cipri",
  "CZ": "Ceki republiki",
  "DE": "Alimaɲi",
  "DJ": "Jibuti",
  "DK": "Danemarki",
  "DM": "Dɔminiki",
  "DO": "Dɔmimiki republiki",
  "DZ": "Alizeri",
  "EC": "Ekwatɔr",
  "EE": "Esetoni",
  "EG": "Eziputi",
  "EH": "Western Sahara",
  "ER": "Eritere",
  "ES": "Esipaɲi",
  "ET": "Etiopi",
  "FI": "Finilandi",
  "FJ": "Fiji",
  "FK": "Maluwini Gun",
  "FM": "Mikironesi",
  "FO": "Faroe Islands",
  "FR": "Faransi",
  "GA": "Gabɔŋ",
  "GB": "Angilɛtɛri",
  "GD": "Granadi",
  "GE": "Zeyɔrzi",
  "GF": "Faransi ka gwiyani",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Zibralitari",
  "GL": "Gɔrɔhenelandi",
  "GM": "Ganbi",
  "GN": "Gine",
  "GP": "Gwadelup",
  "GQ": "Gine ekwatɔri",
  "GR": "Gɛrɛsi",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Gwatemala",
  "GU": "Gwam",
  "GW": "Gine Bisawo",
  "GY": "Gwiyana",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Hɔndirasi",
  "HR": "Kroasi",
  "HT": "Ayiti",
  "HU": "Hɔngri",
  "ID": "Ɛndonezi",
  "IE": "Irilandi",
  "IL": "Isirayeli",
  "IM": "Isle of Man",
  "IN": "Ɛndujamana",
  "IO": "Angilɛ ka ɛndu dugukolo",
  "IQ": "Iraki",
  "IR": "Iraŋ",
  "IS": "Isilandi",
  "IT": "Itali",
  "JE": "Jersey",
  "JM": "Zamayiki",
  "JO": "Zɔrdani",
  "JP": "Zapɔn",
  "KE": "Keniya",
  "KG": "Kirigizisitaŋ",
  "KH": "Kamboji",
  "KI": "Kiribati",
  "KM": "Komɔri",
  "KN": "Kristɔfo-Senu-ni-Ɲevɛs",
  "KP": "Kɛɲɛka Kore",
  "KR": "Worodugu Kore",
  "KW": "Kowɛti",
  "KY": "Bama Gun",
  "KZ": "Kazakistaŋ",
  "LA": "Layosi",
  "LB": "Libaŋ",
  "LC": "Lusi-Senu",
  "LI": "Lisɛnsitayini",
  "LK": "Sirilanka",
  "LR": "Liberiya",
  "LS": "Lesoto",
  "LT": "Lituyani",
  "LU": "Likisanburu",
  "LV": "Letoni",
  "LY": "Libi",
  "MA": "Marɔku",
  "MC": "Monako",
  "MD": "Molidavi",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagasikari",
  "MH": "Marisali Gun",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanimari",
  "MN": "Moŋoli",
  "MO": "Macao SAR China",
  "MP": "Kɛɲɛka Mariyani Gun",
  "MQ": "Maritiniki",
  "MR": "Mɔritani",
  "MS": "Moŋsera",
  "MT": "Malti",
  "MU": "Morisi",
  "MV": "Maldivi",
  "MW": "Malawi",
  "MX": "Meksiki",
  "MY": "Malɛzi",
  "MZ": "Mozanbiki",
  "NA": "Namibi",
  "NC": "Kaledoni Koura",
  "NE": "Nizɛri",
  "NF": "Nɔrofoliki Gun",
  "NG": "Nizeriya",
  "NI": "Nikaragwa",
  "NL": "Peyiba",
  "NO": "Nɔriwɛzi",
  "NP": "Nepali",
  "NR": "Nawuru",
  "NU": "Nyuwe",
  "NZ": "Zelandi Koura",
  "OM": "Omaŋ",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Faransi ka polinezi",
  "PG": "Papuwasi-Gine-Koura",
  "PH": "Filipini",
  "PK": "Pakisitaŋ",
  "PL": "Poloɲi",
  "PM": "Piyɛri-Senu-ni-Mikelɔŋ",
  "PN": "Pitikarini",
  "PR": "Pɔrotoriko",
  "PS": "Palesitini",
  "PT": "Pɔritigali",
  "PW": "Palawu",
  "PY": "Paraguwayi",
  "QA": "Katari",
  "RE": "Reyuɲɔŋ",
  "RO": "Rumani",
  "RS": "Serbia",
  "RU": "Irisi",
  "RW": "Ruwanda",
  "SA": "Arabiya Sawudiya",
  "SB": "Salomo Gun",
  "SC": "Sesɛli",
  "SD": "Sudaŋ",
  "SE": "Suwɛdi",
  "SG": "Sɛngapuri",
  "SH": "Ɛlɛni Senu",
  "SI": "Sloveni",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Slowaki",
  "SL": "Siyera Lewɔni",
  "SM": "Marini-Senu",
  "SN": "Senegali",
  "SO": "Somali",
  "SR": "Surinami",
  "SS": "South Sudan",
  "ST": "Sawo Tome-ni-Prinicipe",
  "SV": "Salivadɔr",
  "SX": "Sint Maarten",
  "SY": "Siri",
  "SZ": "Swazilandi",
  "TC": "Turiki Gun ni Kayiki",
  "TD": "Cadi",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Tayilandi",
  "TJ": "Tajikisitani",
  "TK": "Tokelo",
  "TL": "Kɔrɔn Timɔr",
  "TM": "Turikimenisitani",
  "TN": "Tunizi",
  "TO": "Tonga",
  "TR": "Turiki",
  "TT": "Trinite-ni-Tobago",
  "TV": "Tuvalu",
  "TW": "Tayiwani",
  "TZ": "Tanzani",
  "UA": "Ukɛrɛni",
  "UG": "Uganda",
  "UM": "U.S. Outlying Islands",
  "US": "Ameriki",
  "UY": "Urugwayi",
  "UZ": "Uzebekisitani",
  "VA": "Vatikaŋ",
  "VC": "Vinisɛn-Senu-ni-Grenadini",
  "VE": "Venezuwela",
  "VG": "Angilɛ ka Sungurunnin Gun",
  "VI": "Ameriki ka Sungurunnin Gun",
  "VN": "Wiyɛtinamu",
  "VU": "Vanuwatu",
  "WF": "Walisi-ni-Futuna",
  "WS": "Samowa",
  "YE": "Yemɛni",
  "YT": "Mayoti",
  "ZA": "Worodugu Afriki",
  "ZM": "Zanbi",
  "ZW": "Zimbabuwe",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "akankan",
  "ak_GH": "akankan (Gana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "amarikikan",
  "am_ET": "amarikikan (Etiopi)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "larabukan",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "larabukan (Arabu mara kafoli)",
  "ar_BH": "larabukan (Bareyini)",
  "ar_DJ": "larabukan (Jibuti)",
  "ar_DZ": "larabukan (Alizeri)",
  "ar_EG": "larabukan (Eziputi)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "larabukan (Eritere)",
  "ar_IL": "larabukan (Isirayeli)",
  "ar_IQ": "larabukan (Iraki)",
  "ar_JO": "larabukan (Zɔrdani)",
  "ar_KM": "larabukan (Komɔri)",
  "ar_KW": "larabukan (Kowɛti)",
  "ar_LB": "larabukan (Libaŋ)",
  "ar_LY": "larabukan (Libi)",
  "ar_MA": "larabukan (Marɔku)",
  "ar_MR": "larabukan (Mɔritani)",
  "ar_OM": "larabukan (Omaŋ)",
  "ar_PS": "larabukan (Palesitini)",
  "ar_QA": "larabukan (Katari)",
  "ar_SA": "larabukan (Arabiya Sawudiya)",
  "ar_SD": "larabukan (Sudaŋ)",
  "ar_SO": "larabukan (Somali)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "larabukan (Siri)",
  "ar_TD": "larabukan (Cadi)",
  "ar_TN": "larabukan (Tunizi)",
  "ar_YE": "larabukan (Yemɛni)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "biyelorisikan",
  "be_BY": "biyelorisikan (Belarusi)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "buligarikan",
  "bg_BG": "buligarikan (Buligari)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "bamanakan",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "bɛngalikan",
  "bn_BD": "bɛngalikan (Bɛngiladɛsi)",
  "bn_IN": "bɛngalikan (Ɛndujamana)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "cɛkikan",
  "cs_CZ": "cɛkikan (Ceki republiki)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "alimaɲikan",
  "de_AT": "alimaɲikan (Otirisi)",
  "de_BE": "alimaɲikan (Bɛliziki)",
  "de_CH": "alimaɲikan (Suwisi)",
  "de_DE": "alimaɲikan (Alimaɲi)",
  "de_LI": "alimaɲikan (Lisɛnsitayini)",
  "de_LU": "alimaɲikan (Likisanburu)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "gɛrɛsikan",
  "el_CY": "gɛrɛsikan (Cipri)",
  "el_GR": "gɛrɛsikan (Gɛrɛsi)",
  "elx": "Elamite",
  "en": "angilɛkan",
  "en_AG": "angilɛkan (Antiga-ni-Barbuda)",
  "en_AI": "angilɛkan (Angiya)",
  "en_AS": "angilɛkan (Samowa amerikani)",
  "en_AU": "angilɛkan (Ositirali)",
  "en_BB": "angilɛkan (Barbadi)",
  "en_BE": "angilɛkan (Bɛliziki)",
  "en_BM": "angilɛkan (Bermudi)",
  "en_BS": "angilɛkan (Bahamasi)",
  "en_BW": "angilɛkan (Bɔtisiwana)",
  "en_BZ": "angilɛkan (Belizi)",
  "en_CA": "angilɛkan (Kanada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "angilɛkan (Kuki Gun)",
  "en_CM": "angilɛkan (Kameruni)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "angilɛkan (Dɔminiki)",
  "en_ER": "angilɛkan (Eritere)",
  "en_FJ": "angilɛkan (Fiji)",
  "en_FK": "angilɛkan (Maluwini Gun)",
  "en_FM": "angilɛkan (Mikironesi)",
  "en_GB": "angilɛkan (Angilɛtɛri)",
  "en_GD": "angilɛkan (Granadi)",
  "en_GG": "English (Guernsey)",
  "en_GH": "angilɛkan (Gana)",
  "en_GI": "angilɛkan (Zibralitari)",
  "en_GM": "angilɛkan (Ganbi)",
  "en_GU": "angilɛkan (Gwam)",
  "en_GY": "angilɛkan (Gwiyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "angilɛkan (Irilandi)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "angilɛkan (Ɛndujamana)",
  "en_IO": "angilɛkan (Angilɛ ka ɛndu dugukolo)",
  "en_JE": "English (Jersey)",
  "en_JM": "angilɛkan (Zamayiki)",
  "en_KE": "angilɛkan (Keniya)",
  "en_KI": "angilɛkan (Kiribati)",
  "en_KN": "angilɛkan (Kristɔfo-Senu-ni-Ɲevɛs)",
  "en_KY": "angilɛkan (Bama Gun)",
  "en_LC": "angilɛkan (Lusi-Senu)",
  "en_LR": "angilɛkan (Liberiya)",
  "en_LS": "angilɛkan (Lesoto)",
  "en_MG": "angilɛkan (Madagasikari)",
  "en_MH": "angilɛkan (Marisali Gun)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "angilɛkan (Kɛɲɛka Mariyani Gun)",
  "en_MS": "angilɛkan (Moŋsera)",
  "en_MT": "angilɛkan (Malti)",
  "en_MU": "angilɛkan (Morisi)",
  "en_MW": "angilɛkan (Malawi)",
  "en_MY": "angilɛkan (Malɛzi)",
  "en_NA": "angilɛkan (Namibi)",
  "en_NF": "angilɛkan (Nɔrofoliki Gun)",
  "en_NG": "angilɛkan (Nizeriya)",
  "en_NR": "angilɛkan (Nawuru)",
  "en_NU": "angilɛkan (Nyuwe)",
  "en_NZ": "angilɛkan (Zelandi Koura)",
  "en_PG": "angilɛkan (Papuwasi-Gine-Koura)",
  "en_PH": "angilɛkan (Filipini)",
  "en_PK": "angilɛkan (Pakisitaŋ)",
  "en_PN": "angilɛkan (Pitikarini)",
  "en_PR": "angilɛkan (Pɔrotoriko)",
  "en_PW": "angilɛkan (Palawu)",
  "en_RW": "angilɛkan (Ruwanda)",
  "en_SB": "angilɛkan (Salomo Gun)",
  "en_SC": "angilɛkan (Sesɛli)",
  "en_SD": "angilɛkan (Sudaŋ)",
  "en_SG": "angilɛkan (Sɛngapuri)",
  "en_SH": "angilɛkan (Ɛlɛni Senu)",
  "en_SL": "angilɛkan (Siyera Lewɔni)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "angilɛkan (Swazilandi)",
  "en_TC": "angilɛkan (Turiki Gun ni Kayiki)",
  "en_TK": "angilɛkan (Tokelo)",
  "en_TO": "angilɛkan (Tonga)",
  "en_TT": "angilɛkan (Trinite-ni-Tobago)",
  "en_TV": "angilɛkan (Tuvalu)",
  "en_TZ": "angilɛkan (Tanzani)",
  "en_UG": "angilɛkan (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "angilɛkan (Ameriki)",
  "en_VC": "angilɛkan (Vinisɛn-Senu-ni-Grenadini)",
  "en_VG": "angilɛkan (Angilɛ ka Sungurunnin Gun)",
  "en_VI": "angilɛkan (Ameriki ka Sungurunnin Gun)",
  "en_VU": "angilɛkan (Vanuwatu)",
  "en_WS": "angilɛkan (Samowa)",
  "en_ZA": "angilɛkan (Worodugu Afriki)",
  "en_ZM": "angilɛkan (Zanbi)",
  "en_ZW": "angilɛkan (Zimbabuwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "esipaɲolkan",
  "es_419": "Latin American Spanish",
  "es_AR": "esipaɲolkan (Arizantin)",
  "es_BO": "esipaɲolkan (Bolivi)",
  "es_CL": "esipaɲolkan (Sili)",
  "es_CO": "esipaɲolkan (Kolombi)",
  "es_CR": "esipaɲolkan (Kɔsitarika)",
  "es_CU": "esipaɲolkan (Kuba)",
  "es_DO": "esipaɲolkan (Dɔmimiki republiki)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "esipaɲolkan (Ekwatɔr)",
  "es_ES": "esipaɲolkan (Esipaɲi)",
  "es_GQ": "esipaɲolkan (Gine ekwatɔri)",
  "es_GT": "esipaɲolkan (Gwatemala)",
  "es_HN": "esipaɲolkan (Hɔndirasi)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "esipaɲolkan (Meksiki)",
  "es_NI": "esipaɲolkan (Nikaragwa)",
  "es_PA": "esipaɲolkan (Panama)",
  "es_PE": "esipaɲolkan (Peru)",
  "es_PH": "esipaɲolkan (Filipini)",
  "es_PR": "esipaɲolkan (Pɔrotoriko)",
  "es_PY": "esipaɲolkan (Paraguwayi)",
  "es_SV": "esipaɲolkan (Salivadɔr)",
  "es_US": "esipaɲolkan (Ameriki)",
  "es_UY": "esipaɲolkan (Urugwayi)",
  "es_VE": "esipaɲolkan (Venezuwela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "perisanikan",
  "fa_AF": "perisanikan (Afiganistaŋ)",
  "fa_IR": "perisanikan (Iraŋ)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "tubabukan",
  "fr_BE": "tubabukan (Bɛliziki)",
  "fr_BF": "tubabukan (Burukina Faso)",
  "fr_BI": "tubabukan (Burundi)",
  "fr_BJ": "tubabukan (Benɛn)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "tubabukan (Kanada)",
  "fr_CD": "tubabukan (Kongo ka republiki demɔkratiki)",
  "fr_CF": "tubabukan (Santarafiriki)",
  "fr_CG": "tubabukan (Kongo)",
  "fr_CH": "tubabukan (Suwisi)",
  "fr_CI": "tubabukan (Kodiwari)",
  "fr_CM": "tubabukan (Kameruni)",
  "fr_DJ": "tubabukan (Jibuti)",
  "fr_DZ": "tubabukan (Alizeri)",
  "fr_FR": "tubabukan (Faransi)",
  "fr_GA": "tubabukan (Gabɔŋ)",
  "fr_GF": "tubabukan (Faransi ka gwiyani)",
  "fr_GN": "tubabukan (Gine)",
  "fr_GP": "tubabukan (Gwadelup)",
  "fr_GQ": "tubabukan (Gine ekwatɔri)",
  "fr_HT": "tubabukan (Ayiti)",
  "fr_KM": "tubabukan (Komɔri)",
  "fr_LU": "tubabukan (Likisanburu)",
  "fr_MA": "tubabukan (Marɔku)",
  "fr_MC": "tubabukan (Monako)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "tubabukan (Madagasikari)",
  "fr_ML": "tubabukan (Mali)",
  "fr_MQ": "tubabukan (Maritiniki)",
  "fr_MR": "tubabukan (Mɔritani)",
  "fr_MU": "tubabukan (Morisi)",
  "fr_NC": "tubabukan (Kaledoni Koura)",
  "fr_NE": "tubabukan (Nizɛri)",
  "fr_PF": "tubabukan (Faransi ka polinezi)",
  "fr_PM": "tubabukan (Piyɛri-Senu-ni-Mikelɔŋ)",
  "fr_RE": "tubabukan (Reyuɲɔŋ)",
  "fr_RW": "tubabukan (Ruwanda)",
  "fr_SC": "tubabukan (Sesɛli)",
  "fr_SN": "tubabukan (Senegali)",
  "fr_SY": "tubabukan (Siri)",
  "fr_TD": "tubabukan (Cadi)",
  "fr_TG": "tubabukan (Togo)",
  "fr_TN": "tubabukan (Tunizi)",
  "fr_VU": "tubabukan (Vanuwatu)",
  "fr_WF": "tubabukan (Walisi-ni-Futuna)",
  "fr_YT": "tubabukan (Mayoti)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "awusakan",
  "ha_GH": "awusakan (Gana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "awusakan (Nizɛri)",
  "ha_NG": "awusakan (Nizeriya)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "inidikan",
  "hi_IN": "inidikan (Ɛndujamana)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "oŋirikan",
  "hu_HU": "oŋirikan (Hɔngri)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Ɛndonezikan",
  "id_ID": "Ɛndonezikan (Ɛndonezi)",
  "ie": "Interlingue",
  "ig": "igibokan",
  "ig_NG": "igibokan (Nizeriya)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "italikan",
  "it_CH": "italikan (Suwisi)",
  "it_IT": "italikan (Itali)",
  "it_SM": "italikan (Marini-Senu)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "zapɔnekan",
  "ja_JP": "zapɔnekan (Zapɔn)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "javanekan",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "kambojikan",
  "km_KH": "kambojikan (Kamboji)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "korekan",
  "ko_KP": "korekan (Kɛɲɛka Kore)",
  "ko_KR": "korekan (Worodugu Kore)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "malɛzikan",
  "ms_BN": "malɛzikan (Burinɛyi)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "malɛzikan (Malɛzi)",
  "ms_SG": "malɛzikan (Sɛngapuri)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "birimanikan",
  "my_MM": "birimanikan (Myanimari)",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "nepalekan",
  "ne_IN": "nepalekan (Ɛndujamana)",
  "ne_NP": "nepalekan (Nepali)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "olandekan",
  "nl_AW": "olandekan (Aruba)",
  "nl_BE": "olandekan (Bɛliziki)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "olandekan (Peyiba)",
  "nl_SR": "olandekan (Surinami)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "pɛnijabikan",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "pɛnijabikan (Ɛndujamana)",
  "pa_PK": "pɛnijabikan (Pakisitaŋ)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "polonekan",
  "pl_PL": "polonekan (Poloɲi)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "pɔritigalikan",
  "pt_AO": "pɔritigalikan (Angola)",
  "pt_BR": "pɔritigalikan (Berezili)",
  "pt_CV": "pɔritigalikan (Capivɛrdi)",
  "pt_GW": "pɔritigalikan (Gine Bisawo)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "pɔritigalikan (Mozanbiki)",
  "pt_PT": "pɔritigalikan (Pɔritigali)",
  "pt_ST": "pɔritigalikan (Sawo Tome-ni-Prinicipe)",
  "pt_TL": "pɔritigalikan (Kɔrɔn Timɔr)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "rumanikan",
  "ro_MD": "rumanikan (Molidavi)",
  "ro_RO": "rumanikan (Rumani)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "irisikan",
  "ru_BY": "irisikan (Belarusi)",
  "ru_KG": "irisikan (Kirigizisitaŋ)",
  "ru_KZ": "irisikan (Kazakistaŋ)",
  "ru_MD": "irisikan (Molidavi)",
  "ru_RU": "irisikan (Irisi)",
  "ru_UA": "irisikan (Ukɛrɛni)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "ruwandakan",
  "rw_RW": "ruwandakan (Ruwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "somalikan",
  "so_DJ": "somalikan (Jibuti)",
  "so_ET": "somalikan (Etiopi)",
  "so_KE": "somalikan (Keniya)",
  "so_SO": "somalikan (Somali)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "suwɛdikan",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "suwɛdikan (Finilandi)",
  "sv_SE": "suwɛdikan (Suwɛdi)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "tamulikan",
  "ta_IN": "tamulikan (Ɛndujamana)",
  "ta_LK": "tamulikan (Sirilanka)",
  "ta_MY": "tamulikan (Malɛzi)",
  "ta_SG": "tamulikan (Sɛngapuri)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "tayikan",
  "th_TH": "tayikan (Tayilandi)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "turikikan",
  "tr_CY": "turikikan (Cipri)",
  "tr_TR": "turikikan (Turiki)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "ukɛrɛnikan",
  "uk_UA": "ukɛrɛnikan (Ukɛrɛni)",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "urudukan",
  "ur_IN": "urudukan (Ɛndujamana)",
  "ur_PK": "urudukan (Pakisitaŋ)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "wiyɛtinamukan",
  "vi_VN": "wiyɛtinamukan (Wiyɛtinamu)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "yorubakan",
  "yo_BJ": "yorubakan (Benɛn)",
  "yo_NG": "yorubakan (Nizeriya)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "siniwakan",
  "zh_CN": "siniwakan (Siniwajamana)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "siniwakan (Sɛngapuri)",
  "zh_TW": "siniwakan (Tayiwani)",
  "zu": "zulukan",
  "zu_ZA": "zulukan (Worodugu Afriki)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
