const names = {
  "001": "Dinja",
  "002": "Affrika",
  "003": "Amerika ta’ Fuq",
  "005": "Amerika t’Isfel",
  "009": "Oċejanja",
  "011": "Affrika tal-Punent",
  "013": "Amerika Ċentrali",
  "014": "Affrika tal-Lvant",
  "015": "Affrika ta’ Fuq",
  "017": "Affrika Nofsani",
  "018": "Affrika t’Isfel",
  "019": "Amerika",
  "021": "Amerika Nòrdiku",
  "029": "Karibew",
  "030": "Asja tal-Lvant",
  "034": "Asja t’Isfel Ċentrali",
  "035": "Asja tax-Xlokk",
  "039": "Ewropa t’Isfel",
  "053": "Awstralja u New Zealand",
  "054": "Melanesja",
  "057": "Reġjun ta’ Mikroneżja",
  "061": "Polinesja",
  "142": "Asja",
  "143": "Asja Ċentrali",
  "145": "Asja tal-Punent",
  "150": "Ewropa",
  "151": "Ewropa tal-Lvant",
  "154": "Ewropa ta’ Fuq",
  "155": "Ewropa tal-Punent",
  "419": "Amerika Latina",
  "AC": "Ascension Island",
  "AD": "Andorra",
  "AE": "l-Emirati Għarab Magħquda",
  "AF": "l-Afganistan",
  "AG": "Antigua u Barbuda",
  "AI": "Anguilla",
  "AL": "l-Albanija",
  "AM": "l-Armenja",
  "AN": "Antilles Olandiżi",
  "AO": "l-Angola",
  "AQ": "l-Antartika",
  "AR": "l-Arġentina",
  "AS": "is-Samoa Amerikana",
  "AT": "l-Awstrija",
  "AU": "l-Awstralja",
  "AW": "Aruba",
  "AX": "il-Gżejjer Aland",
  "AZ": "l-Ażerbajġan",
  "Arab": "Għarbi",
  "BA": "il-Bożnija-Ħerzegovina",
  "BB": "Barbados",
  "BD": "il-Bangladesh",
  "BE": "il-Belġju",
  "BF": "il-Burkina Faso",
  "BG": "il-Bulgarija",
  "BH": "il-Bahrain",
  "BI": "il-Burundi",
  "BJ": "il-Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "il-Brunei",
  "BO": "il-Bolivja",
  "BQ": "in-Netherlands tal-Karibew",
  "BR": "Il-Brażil",
  "BS": "il-Bahamas",
  "BT": "il-Bhutan",
  "BV": "Gżira Bouvet",
  "BW": "il-Botswana",
  "BY": "il-Belarussja",
  "BZ": "il-Belize",
  "Brai": "Braille",
  "CA": "il-Kanada",
  "CC": "Gżejjer Cocos (Keeling)",
  "CD": "ir-Repubblika Demokratika tal-Kongo",
  "CF": "ir-Repubblika Ċentru-Afrikana",
  "CG": "il-Kongo - Brazzaville",
  "CH": "l-Iżvizzera",
  "CI": "il-Kosta tal-Avorju",
  "CK": "Gżejjer Cook",
  "CL": "iċ-Ċili",
  "CM": "il-Kamerun",
  "CN": "iċ-Ċina",
  "CO": "il-Kolombja",
  "CP": "il-Gżira Clipperton",
  "CR": "il-Costa Rica",
  "CS": "Serbja u Montenegro",
  "CU": "Kuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "il-Gżira Christmas",
  "CY": "Ċipru",
  "CZ": "ir-Repubblika Ċeka",
  "Cyrl": "Ċirilliku",
  "DE": "il-Ġermanja",
  "DG": "Diego Garcia",
  "DJ": "il-Djibouti",
  "DK": "id-Danimarka",
  "DM": "Dominica",
  "DO": "ir-Repubblika Dominicana",
  "DZ": "l-Alġerija",
  "EA": "Ceuta u Melilla",
  "EC": "l-Ekwador",
  "EE": "l-Estonja",
  "EG": "l-Eġittu",
  "EH": "is-Saħara tal-Punent",
  "ER": "l-Eritrea",
  "ES": "Spanja",
  "ET": "l-Etjopja",
  "EU": "Unjoni Ewropea",
  "FI": "il-Finlandja",
  "FJ": "Fiġi",
  "FK": "il-Gżejjer Falkland",
  "FM": "Mikroneżja",
  "FO": "il-Gżejjer Faeroe",
  "FR": "Franza",
  "GA": "il-Gabon",
  "GB": "ir-Renju Unit",
  "GD": "Grenada",
  "GE": "il-Georgia",
  "GF": "il-Guyana Franċiża",
  "GG": "Guernsey",
  "GH": "il-Ghana",
  "GI": "Ġibiltà",
  "GL": "Greenland",
  "GM": "il-Gambja",
  "GN": "il-Guinea",
  "GP": "Guadeloupe",
  "GQ": "il-Guinea Ekwatorjali",
  "GR": "il-Greċja",
  "GS": "il-Georgia tan-Nofsinhar u l-Gżejjer Sandwich tan-Nofsinhar",
  "GT": "il-Gwatemala",
  "GU": "Guam",
  "GW": "il-Guinea-Bissau",
  "GY": "il-Guyana",
  "Grek": "Grieg",
  "HK":
      "ir-Reġjun Amministrattiv Speċjali ta’ Hong Kong tar-Repubblika tal-Poplu taċ-Ċina",
  "HM": "il-Gżejjer Heard u l-Gżejjer McDonald",
  "HN": "il-Honduras",
  "HR": "il-Kroazja",
  "HT": "il-Haiti",
  "HU": "l-Ungerija",
  "Hans": "Simplifikat",
  "Hant": "Tradizzjonali",
  "IC": "il-Gżejjer Canary",
  "ID": "l-Indoneżja",
  "IE": "l-Irlanda",
  "IL": "Iżrael",
  "IM": "Isle of Man",
  "IN": "l-Indja",
  "IO": "Territorju Brittaniku tal-Oċean Indjan",
  "IQ": "l-Iraq",
  "IR": "l-Iran",
  "IS": "l-iżlanda",
  "IT": "l-Italja",
  "JE": "Jersey",
  "JM": "il-Ġamajka",
  "JO": "il-Ġordan",
  "JP": "il-Ġappun",
  "KE": "il-Kenja",
  "KG": "il-Kirgiżistan",
  "KH": "il-Kambodja",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts u Nevis",
  "KP": "il-Korea ta’ Fuq",
  "KR": "il-Korea t’Isfel",
  "KW": "il-Kuwajt",
  "KY": "il-Gżejjer Cayman",
  "KZ": "il-Każakistan",
  "LA": "il-Laos",
  "LB": "il-Libanu",
  "LC": "Saint Lucia",
  "LI": "il-Liechtenstein",
  "LK": "is-Sri Lanka",
  "LR": "il-Liberja",
  "LS": "il-Lesoto",
  "LT": "il-Litwanja",
  "LU": "il-Lussemburgu",
  "LV": "il-Latvja",
  "LY": "il-Libja",
  "Latn": "Latin",
  "MA": "il-Marokk",
  "MC": "Monaco",
  "MD": "il-Moldova",
  "ME": "il-Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Gżejjer Marshall",
  "MK": "il-Maċedonja ta’ Fuq",
  "ML": "il-Mali",
  "MM": "il-Myanmar/Burma",
  "MN": "il-Mongolja",
  "MO":
      "ir-Reġjun Amministrattiv Speċjali tal-Macao tar-Repubblika tal-Poplu taċ-Ċina",
  "MP": "Ġżejjer Mariana tat-Tramuntana",
  "MQ": "Martinique",
  "MR": "il-Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "il-Maldivi",
  "MW": "il-Malawi",
  "MX": "il-Messiku",
  "MY": "il-Malasja",
  "MZ": "il-Mozambique",
  "NA": "in-Namibja",
  "NC": "New Caledonia",
  "NE": "in-Niġer",
  "NF": "Gżira Norfolk",
  "NG": "in-Niġerja",
  "NI": "in-Nikaragwa",
  "NL": "in-Netherlands",
  "NO": "in-Norveġja",
  "NP": "in-Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "l-Oman",
  "PA": "il-Panama",
  "PE": "il-Perù",
  "PF": "Polineżja Franċiża",
  "PG": "Papua New Guinea",
  "PH": "il-Filippini",
  "PK": "il-Pakistan",
  "PL": "il-Polonja",
  "PM": "Saint Pierre u Miquelon",
  "PN": "Gżejjer Pitcairn",
  "PR": "Puerto Rico",
  "PS": "it-Territorji Palestinjani",
  "PT": "il-Portugall",
  "PW": "Palau",
  "PY": "il-Paragwaj",
  "QA": "il-Qatar",
  "RE": "Réunion",
  "RO": "ir-Rumanija",
  "RS": "is-Serbja",
  "RU": "ir-Russja",
  "RW": "ir-Rwanda",
  "SA": "l-Arabia Sawdija",
  "SB": "il-Gżejjer Solomon",
  "SC": "is-Seychelles",
  "SD": "is-Sudan",
  "SE": "l-Iżvezja",
  "SG": "Singapore",
  "SH": "Saint Helena",
  "SI": "is-Slovenja",
  "SJ": "Svalbard u Jan Mayen",
  "SK": "is-Slovakkja",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "is-Senegal",
  "SO": "is-Somalja",
  "SR": "is-Suriname",
  "SS": "is-Sudan t’Isfel",
  "ST": "São Tomé u Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "is-Sirja",
  "SZ": "is-Swaziland",
  "TA": "Tristan da Cunha",
  "TC": "il-Gżejjer Turks u Caicos",
  "TD": "iċ-Chad",
  "TF": "It-Territorji Franċiżi tan-Nofsinhar",
  "TG": "it-Togo",
  "TH": "it-Tajlandja",
  "TJ": "it-Taġikistan",
  "TK": "it-Tokelau",
  "TL": "Timor Leste",
  "TM": "it-Turkmenistan",
  "TN": "it-Tuneżija",
  "TO": "Tonga",
  "TR": "it-Turkija",
  "TT": "Trinidad u Tobago",
  "TV": "Tuvalu",
  "TW": "it-Tajwan",
  "TZ": "it-Tanzanija",
  "UA": "l-Ukrajna",
  "UG": "l-Uganda",
  "UM": "Il-Gżejjer Minuri Mbiegħda tal-Istati Uniti",
  "US": "l-Istati Uniti",
  "UY": "l-Urugwaj",
  "UZ": "l-Użbekistan",
  "VA": "l-Istat tal-Belt tal-Vatikan",
  "VC": "Saint Vincent u l-Grenadini",
  "VE": "il-Venezwela",
  "VG": "il-Gżejjer Verġni Brittaniċi",
  "VI": "il-Gżejjer Verġni tal-Istati Uniti",
  "VN": "il-Vjetnam",
  "VU": "Vanuatu",
  "WF": "Wallis u Futuna",
  "WS": "Samoa",
  "XK": "il-Kosovo",
  "Xpeo": "Persjan Antik",
  "YE": "il-Jemen",
  "YT": "Mayotte",
  "ZA": "l-Afrika t’Isfel",
  "ZM": "iż-Żambja",
  "ZW": "iż-Żimbabwe",
  "ZZ": "Reġjun Mhux Magħruf",
  "Zxxx": "Mhux Miktub",
  "Zyyy": "Komuni",
  "Zzzz": "Kitba Mhux Magħrufa",
  "aa": "Afar",
  "ab": "Abkażjan",
  "ace": "Aċiniż",
  "ach": "Akoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikans",
  "af_NA": "Afrikans (Namibja)",
  "af_ZA": "Afrikans (Afrika t’Isfel)",
  "afa": "Afro-Asjatiku (Oħra)",
  "afh": "Afriħili",
  "agq": "Aghem",
  "ain": "Ajnu",
  "ak": "Akan",
  "ak_GH": "Akan (Gana)",
  "akk": "Akkadjen",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Lingwi Algonqwinjani",
  "aln": "Gheg Albanian",
  "alt": "Altai tan-Nofsinhar",
  "am": "Amħariku",
  "am_ET": "Amħariku (Etijopja)",
  "an": "Aragoniż",
  "ang": "Ingliż Antik",
  "anp": "Angika",
  "apa": "Lingwi Apaċi",
  "ar": "Għarbi",
  "ar_001": "Għarbi Standard Modern",
  "ar_AE": "Għarbi (Emirati Għarab Maqgħuda)",
  "ar_BH": "Għarbi (Baħrajn)",
  "ar_DJ": "Għarbi (Ġibuti)",
  "ar_DZ": "Għarbi (Alġerija)",
  "ar_EG": "Għarbi (Eġittu)",
  "ar_EH": "Għarbi (Sahara tal-Punent)",
  "ar_ER": "Għarbi (Eritreja)",
  "ar_IL": "Għarbi (Iżrael)",
  "ar_IQ": "Għarbi (Iraq)",
  "ar_JO": "Għarbi (Ġordan)",
  "ar_KM": "Għarbi (Komoros)",
  "ar_KW": "Għarbi (Kuwajt)",
  "ar_LB": "Għarbi (Libanu)",
  "ar_LY": "Għarbi (Libja)",
  "ar_MA": "Għarbi (Marokk)",
  "ar_MR": "Għarbi (Mawritanja)",
  "ar_OM": "Għarbi (Oman)",
  "ar_PS": "Għarbi (Territorju Palestinjan)",
  "ar_QA": "Għarbi (Qatar)",
  "ar_SA": "Għarbi (Għarabja Sawdita)",
  "ar_SD": "Għarbi (Sudan)",
  "ar_SO": "Għarbi (Somalja)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Għarbi (Sirja)",
  "ar_TD": "Għarbi (Ċad)",
  "ar_TN": "Għarbi (Tuneż)",
  "ar_YE": "Għarbi (Jemen)",
  "arc": "Aramajk",
  "arn": "Arawkanjan",
  "aro": "Araona",
  "arp": "Arapaħo",
  "arq": "Algerian Arabic",
  "art": "Artifiċjali (Oħra)",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamiż",
  "as_IN": "Assamese (L-Indja)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "ath": "Lingwi Atabaskani",
  "aus": "Lingwi Awstraljani",
  "av": "Avarik",
  "avk": "Kotava",
  "awa": "Awadħi",
  "ay": "Ajmara",
  "az": "Ażerbajġani",
  "az_AZ": "Ażerbajġani (Ażerbajġan)",
  "az_Cyrl": "Ażerbajġani (Ċirilliku)",
  "az_Cyrl_AZ": "Ażerbajġani (Ċirilliku, Ażerbajġan)",
  "az_Latn": "Ażerbajġani (Latin)",
  "az_Latn_AZ": "Ażerbajġani (Latin, Ażerbajġan)",
  "azb": "South Azerbaijani",
  "ba": "Baxkir",
  "bad": "Banda",
  "bai": "Lingwi Bamileke",
  "bal": "Baluċi",
  "ban": "Baliniż",
  "bar": "Bavarian",
  "bas": "Basa",
  "bat": "Baltiku (Oħra)",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarussu",
  "be_BY": "Belarussu (Bjelorussja)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Beber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaru",
  "bg_BG": "Bulgaru (Bulgarija)",
  "bh": "Biħari",
  "bho": "Bojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bengali",
  "bn_BD": "Bengali (Bangladexx)",
  "bn_IN": "Bengali (L-Indja)",
  "bnt": "Bantu",
  "bo": "Tibetjan",
  "bo_CN": "Tibetjan (Iċ-Ċina)",
  "bo_IN": "Tibetjan (L-Indja)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Brenton",
  "br_FR": "Brenton (Franza)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bożnijaku",
  "bs_BA": "Bosnijan (Bożnija Ħerżegovina)",
  "bs_Cyrl": "Bosnijan (Ċirilliku)",
  "bs_Cyrl_BA": "Bosnijan (Ċirilliku, Bożnija Ħerżegovina)",
  "bs_Latn": "Bosnijan (Latin)",
  "bs_Latn_BA": "Bosnijan (Latin, Bożnija Ħerżegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Burjat",
  "bug": "Buginiż",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalan",
  "ca_AD": "Katalan (Andorra)",
  "ca_ES": "Katalan (Spanja)",
  "ca_FR": "Katalan (Franza)",
  "ca_IT": "Katalan (L-Italja)",
  "cad": "Kaddo",
  "cai": "Amerika Ċentrali (Oħra)",
  "car": "Karib",
  "cau": "Kawkasu (Oħra)",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Ċeċen",
  "ceb": "Sibwano",
  "cel": "Keltiku (Oħra)",
  "cgg": "Chiga",
  "ch": "Ċamorro",
  "chb": "Ċibċa",
  "chg": "Ċagataj",
  "chk": "Ċukese",
  "chm": "Mari",
  "chn": "Ġargon taċ-Ċinuk",
  "cho": "Ċostaw",
  "chp": "Ċipewjan",
  "chr": "Ċerokij",
  "chy": "Xajenn",
  "ckb": "Central Kurdish",
  "cmc": "Lingwi Ċamiki",
  "co": "Korsiku",
  "cop": "Koptiku",
  "cpe": "Kreoli u Piġini, Bbażat fuq l-Ingliż (Oħra)",
  "cpf": "Kreoli u Piġini, Bbażat fuq il-Franċiż (Oħra)",
  "cpp": "Kreoli u Piġini, Bbażat fuq il-Portugiż (Oħra)",
  "cps": "Capiznon",
  "cr": "Krij",
  "crh": "Tork tal-Krimea",
  "crp": "Kreoli u Piġini (Oħra)",
  "crs": "Franċiż tas-Seselwa Creole",
  "cs": "Ċek",
  "cs_CZ": "Ċek (Repubblika Ċeka)",
  "csb": "Kashubian",
  "cu": "Slaviku tal-Knisja",
  "cus": "Kuxtiku (Oħra)",
  "cv": "Ċuvax",
  "cy": "Welsh",
  "cy_GB": "Welx (L-Ingilterra)",
  "da": "Daniż",
  "da_DK": "Daniż (Danimarka)",
  "da_GL": "Daniż (Grinlandja)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dajak",
  "de": "Ġermaniż",
  "de_AT": "Ġermaniż (Awstrija)",
  "de_BE": "Ġermaniż (Belġju)",
  "de_CH": "Ġermaniż (Svizzera)",
  "de_DE": "Ġermaniż (Il-Ġermanja)",
  "de_LI": "Ġermaniż (Liechtenstein)",
  "de_LU": "Ġermaniż (Lussemburgu)",
  "del": "Delawerjan",
  "den": "Slav",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Dravidjan (Oħra)",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Dwala",
  "dum": "Olandiż Medjevali",
  "dv": "Diveħi",
  "dyo": "Jola-Fonyi",
  "dyu": "Djula",
  "dz": "Dżongka",
  "dz_BT": "Dżongka (Butan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Gana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Eġizzjan (Antik)",
  "eka": "Ekajuk",
  "el": "Grieg",
  "el_CY": "Grieg (Ċipru)",
  "el_GR": "Grieg (Greċja)",
  "elx": "Elamit",
  "en": "Ingliż",
  "en_AG": "Ingliż (Antigua and Barbuda)",
  "en_AI": "Ingliż (Angwilla)",
  "en_AS": "Ingliż (Samoa Amerikana)",
  "en_AU": "Ingliż (Awstralja)",
  "en_BB": "Ingliż (Barbados)",
  "en_BE": "Ingliż (Belġju)",
  "en_BM": "Ingliż (Bermuda)",
  "en_BS": "Ingliż (Baħamas)",
  "en_BW": "Ingliż (Botswana)",
  "en_BZ": "Ingliż (Beliże)",
  "en_CA": "Ingliż (Kanada)",
  "en_CC": "Ingliż (Cocos (Keeling) Islands)",
  "en_CK": "Ingliż (Cook Islands)",
  "en_CM": "Ingliż (Kamerun)",
  "en_CX": "Ingliż (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Ingliż (Dominika)",
  "en_ER": "Ingliż (Eritreja)",
  "en_FJ": "Ingliż (Fiġi)",
  "en_FK": "Ingliż (Falkland Islands)",
  "en_FM": "Ingliż (Mikronesja)",
  "en_GB": "Ingliż (L-Ingilterra)",
  "en_GD": "Ingliż (Grenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Ingliż (Gana)",
  "en_GI": "Ingliż (Gibraltar)",
  "en_GM": "Ingliż (Gambja)",
  "en_GU": "Ingliż (Gwam)",
  "en_GY": "Ingliż (Gujana)",
  "en_HK": "Ingliż (Ħong Kong S.A.R. Ċina)",
  "en_IE": "Ingliż (Irlanda)",
  "en_IM": "Ingliż (Isle of Man)",
  "en_IN": "Ingliż (L-Indja)",
  "en_IO": "Ingliż (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "Ingliż (Ġamajka)",
  "en_KE": "Ingliż (Kenja)",
  "en_KI": "Ingliż (Kiribati)",
  "en_KN": "Ingliż (Saint Kitts and Nevis)",
  "en_KY": "Ingliż (Gżejjer Kajmani)",
  "en_LC": "Ingliż (Santa Luċija)",
  "en_LR": "Ingliż (Liberja)",
  "en_LS": "Ingliż (Lesoto)",
  "en_MG": "Ingliż (Madagaskar)",
  "en_MH": "Ingliż (Gżejjer ta’ Marshall)",
  "en_MO": "Ingliż (Macao S.A.R., China)",
  "en_MP": "Ingliż (Gżejjer Marjana ta’ Fuq)",
  "en_MS": "Ingliż (Montserrat)",
  "en_MT": "Ingliż (Malta)",
  "en_MU": "Ingliż (Mawrizju)",
  "en_MW": "Ingliż (Malawi)",
  "en_MY": "Ingliż (Malasja)",
  "en_NA": "Ingliż (Namibja)",
  "en_NF": "Ingliż (Norfolk Island)",
  "en_NG": "Ingliż (Niġerja)",
  "en_NR": "Ingliż (Nauru)",
  "en_NU": "Ingliż (Niue)",
  "en_NZ": "Ingliż (New Zealand)",
  "en_PG": "Ingliż (Papwa-Ginea Ġdida)",
  "en_PH": "Ingliż (Filippini)",
  "en_PK": "Ingliż (Pakistan)",
  "en_PN": "Ingliż (Pitcairn)",
  "en_PR": "Ingliż (Puerto Rico)",
  "en_PW": "Ingliż (Palau)",
  "en_RW": "Ingliż (Rwanda)",
  "en_SB": "Ingliż (Solomon Islands)",
  "en_SC": "Ingliż (Seychelles)",
  "en_SD": "Ingliż (Sudan)",
  "en_SG": "Ingliż (Singapor)",
  "en_SH": "Ingliż (Saint Helena)",
  "en_SL": "Ingliż (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Ingliż (Sważiland)",
  "en_TC": "Ingliż (Turks and Caicos Islands)",
  "en_TK": "Ingliż (Tokelaw)",
  "en_TO": "Ingliż (Tonga)",
  "en_TT": "Ingliż (Trinidad u Tobago)",
  "en_TV": "Ingliż (Tuvalu)",
  "en_TZ": "Ingliż (Tanżanija)",
  "en_UG": "Ingliż (Uganda)",
  "en_UM": "Ingliż (United States Minor Outlying Islands)",
  "en_US": "Ingliż (L-Istati Uniti)",
  "en_VC": "Ingliż (Saint Vincent and the Grenadines)",
  "en_VG": "Ingliż (British Virgin Islands)",
  "en_VI": "Ingliż (U.S. Virgin Islands)",
  "en_VU": "Ingliż (Vanwatu)",
  "en_WS": "Ingliż (Samoa)",
  "en_ZA": "Ingliż (Afrika t’Isfel)",
  "en_ZM": "Ingliż (Żambja)",
  "en_ZW": "Ingliż (Żimbabwe)",
  "enm": "Ingliż Medjevali",
  "eo": "Esperanto",
  "es": "Spanjol",
  "es_419": "Spanjol (Latin Amerikan)",
  "es_AR": "Spanjol (Arġentina)",
  "es_BO": "Spanjol (Bolivja)",
  "es_CL": "Spanjol (Ċili)",
  "es_CO": "Spanjol (Kolumbja)",
  "es_CR": "Spanjol (Kosta Rika)",
  "es_CU": "Spanjol (Kuba)",
  "es_DO": "Spanjol (Republikka Domenikana)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Spanjol (Ekwador)",
  "es_ES": "Spanjol (Spanja)",
  "es_GQ": "Spanjol (Ginea Ekwatorjali)",
  "es_GT": "Spanjol (Gwatemala)",
  "es_HN": "Spanjol (Ħonduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Spanjol (Messiku)",
  "es_NI": "Spanjol (Nikaragwa)",
  "es_PA": "Spanjol (Panama)",
  "es_PE": "Spanjol (Peru)",
  "es_PH": "Spanjol (Filippini)",
  "es_PR": "Spanjol (Puerto Rico)",
  "es_PY": "Spanjol (Paragwaj)",
  "es_SV": "Spanjol (El Salvador)",
  "es_US": "Spanjol (L-Istati Uniti)",
  "es_UY": "Spanjol (Urugwaj)",
  "es_VE": "Spanjol (Venezwela)",
  "esu": "Central Yupik",
  "et": "Estonjan",
  "et_EE": "Estonjan (Estonja)",
  "eu": "Bask",
  "eu_ES": "Bask (Spanja)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Persjan",
  "fa_AF": "Persjan (Afganistan)",
  "fa_IR": "Persjan (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulaħ",
  "ff_CM": "Fulaħ (Kamerun)",
  "ff_GN": "Fulaħ (Gineja)",
  "ff_MR": "Fulaħ (Mawritanja)",
  "ff_SN": "Fulaħ (Senegal)",
  "fi": "Finlandiż",
  "fi_FI": "Finlandiż (Finlandja)",
  "fil": "Filippino",
  "fit": "Tornedalen Finnish",
  "fiu": "Finno - Ugrijan",
  "fj": "Fiġjan",
  "fo": "Fawriż",
  "fo_FO": "Fawriż (Gżejjer Faroe)",
  "fon": "Fon",
  "fr": "Franċiż",
  "fr_BE": "Franċiż (Belġju)",
  "fr_BF": "Franċiż (Burkina Faso)",
  "fr_BI": "Franċiż (Burundi)",
  "fr_BJ": "Franċiż (Benin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Franċiż (Kanada)",
  "fr_CD": "Franċiż (Democratic Republic of the Congo)",
  "fr_CF": "Franċiż (Repubblika Afrikana Ċentrali)",
  "fr_CG": "Franċiż (Kongo)",
  "fr_CH": "Franċiż (Svizzera)",
  "fr_CI": "Franċiż (Kosta ta’ l-Avorju)",
  "fr_CM": "Franċiż (Kamerun)",
  "fr_DJ": "Franċiż (Ġibuti)",
  "fr_DZ": "Franċiż (Alġerija)",
  "fr_FR": "Franċiż (Franza)",
  "fr_GA": "Franċiż (Gabon)",
  "fr_GF": "Franċiż (Gujana Franċiża)",
  "fr_GN": "Franċiż (Gineja)",
  "fr_GP": "Franċiż (Gwadelupe)",
  "fr_GQ": "Franċiż (Ginea Ekwatorjali)",
  "fr_HT": "Franċiż (Ħaiti)",
  "fr_KM": "Franċiż (Komoros)",
  "fr_LU": "Franċiż (Lussemburgu)",
  "fr_MA": "Franċiż (Marokk)",
  "fr_MC": "Franċiż (Monako)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Franċiż (Madagaskar)",
  "fr_ML": "Franċiż (Mali)",
  "fr_MQ": "Franċiż (Martinik)",
  "fr_MR": "Franċiż (Mawritanja)",
  "fr_MU": "Franċiż (Mawrizju)",
  "fr_NC": "Franċiż (New Caledonia)",
  "fr_NE": "Franċiż (Niġer)",
  "fr_PF": "Franċiż (Polinesja Franċiża)",
  "fr_PM": "Franċiż (Saint Pierre and Miquelon)",
  "fr_RE": "Franċiż (Réunion)",
  "fr_RW": "Franċiż (Rwanda)",
  "fr_SC": "Franċiż (Seychelles)",
  "fr_SN": "Franċiż (Senegal)",
  "fr_SY": "Franċiż (Sirja)",
  "fr_TD": "Franċiż (Ċad)",
  "fr_TG": "Franċiż (Togo)",
  "fr_TN": "Franċiż (Tuneż)",
  "fr_VU": "Franċiż (Vanwatu)",
  "fr_WF": "Franċiż (Wallis and Futuna)",
  "fr_YT": "Franċiż (Majotte)",
  "frc": "Cajun French",
  "frm": "Franċiż Medjevali",
  "fro": "Franċiż Antik",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Frijuljan",
  "fy": "Frisian tal-Punent",
  "fy_NL": "Friżjan (Olanda)",
  "ga": "Irlandiż",
  "ga_IE": "Irlandiż (Irlanda)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gajo",
  "gba": "Gbaja",
  "gbz": "Zoroastrian Dari",
  "gd": "Galliku Skoċċiż",
  "gd_GB": "Galliku Skoċċiż (L-Ingilterra)",
  "gem": "Ġermaniku (Oħra)",
  "gez": "Geez",
  "gil": "Gilbertjan",
  "gl": "Gallegjan",
  "gl_ES": "Gallegjan (Spanja)",
  "glk": "Gilaki",
  "gmh": "Ġermaniku, Medjevali Pulit",
  "gn": "Gwarani",
  "goh": "Ġermaniku, Antik Pulit",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gotiku",
  "grb": "Ġerbo",
  "grc": "Grieg, Antik",
  "gsw": "Swiss German",
  "gu": "Guġarati",
  "gu_IN": "Guġarati (L-Indja)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manks",
  "gv_IM": "Manks (Isle of Man)",
  "gwi": "Gwiċin",
  "ha": "Ħawsa",
  "ha_GH": "Ħawsa (Gana)",
  "ha_Latn": "Ħawsa (Latin)",
  "ha_Latn_GH": "Ħawsa (Latin, Gana)",
  "ha_Latn_NE": "Ħawsa (Latin, Niġer)",
  "ha_Latn_NG": "Ħawsa (Latin, Niġerja)",
  "ha_NE": "Ħawsa (Niġer)",
  "ha_NG": "Ħawsa (Niġerja)",
  "hai": "Ħajda",
  "hak": "Hakka Chinese",
  "haw": "Ħawajjan",
  "he": "Ebrajk",
  "he_IL": "Ebrajk (Iżrael)",
  "hi": "Ħindi",
  "hi_IN": "Ħindi (L-Indja)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Ħimaċali",
  "hit": "Ħittit",
  "hmn": "Ħmong",
  "ho": "Ħiri Motu",
  "hr": "Kroat",
  "hr_BA": "Kroat (Bożnija Ħerżegovina)",
  "hr_HR": "Kroat (Kroazja)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "Ungeriż",
  "hu_HU": "Ungeriż (Ungerija)",
  "hup": "Ħupa",
  "hy": "Armenjan",
  "hy_AM": "Armenjan (Armenja)",
  "hz": "Ħerero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indoneżjan",
  "id_ID": "Indoneżjan (Indoneżja)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Niġerja)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (Iċ-Ċina)",
  "ijo": "Iġo",
  "ik": "Inupjak",
  "ilo": "Iloko",
  "inc": "Indjan (Oħra)",
  "ine": "Indo-Ewropew",
  "inh": "Ingush",
  "io": "Ido",
  "ira": "Iranjan",
  "iro": "Lingwi Irogwjani",
  "is": "Iżlandiż",
  "is_IS": "Iżlandiż (Islanda)",
  "it": "Taljan",
  "it_CH": "Taljan (Svizzera)",
  "it_IT": "Taljan (L-Italja)",
  "it_SM": "Taljan (San Marino)",
  "iu": "Inukitut",
  "izh": "Ingrian",
  "ja": "Ġappuniż",
  "ja_JP": "Ġappuniż (Il-Ġappun)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Lhudi-Persjan",
  "jrb": "Lhudi-Għarbi",
  "jut": "Jutish",
  "jv": "Ġavaniż",
  "ka": "Ġorġjan",
  "ka_GE": "Ġorġjan (Ġorġja)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabuljan",
  "kac": "Kaċin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Kasi",
  "khi": "Kojsan",
  "kho": "Kotaniż",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuju",
  "ki_KE": "Kikuju (Kenja)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Każak",
  "kk_Cyrl": "Każak (Ċirilliku)",
  "kk_Cyrl_KZ": "Każak (Ċirilliku, Każakstan)",
  "kk_KZ": "Każak (Każakstan)",
  "kkj": "Kako",
  "kl": "Kalallisut",
  "kl_GL": "Kalallisut (Grinlandja)",
  "kln": "Kalenjin",
  "km": "Kmer",
  "km_KH": "Kmer (Kambodja)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (L-Indja)",
  "ko": "Korejan",
  "ko_KP": "Korejan (Koreja ta’ Fuq)",
  "ko_KR": "Korejan (Koreja t’Isfel)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosrejan",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurusk",
  "ks": "Kaxmiri",
  "ks_Arab": "Kaxmiri (Għarbi)",
  "ks_Arab_IN": "Kaxmiri (Għarbi, L-Indja)",
  "ks_IN": "Kaxmiri (L-Indja)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdiż",
  "kum": "Kumiku",
  "kut": "Kutenaj",
  "kv": "Komi",
  "kw": "Korniku",
  "kw_GB": "Korniku (L-Ingilterra)",
  "ky": "Kirgiż",
  "ky_Cyrl": "Kirgiż (Ċirilliku)",
  "ky_Cyrl_KG": "Kirgiż (Ċirilliku, Kirgistan)",
  "ky_KG": "Kirgiż (Kirgistan)",
  "la": "Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Landa",
  "lam": "Lamba",
  "lb": "Letżburgiż",
  "lb_LU": "Letżburgiż (Lussemburgu)",
  "lez": "Leżgjan",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingaljan",
  "ln_AO": "Lingaljan (Angola)",
  "ln_CD": "Lingaljan (Democratic Republic of the Congo)",
  "ln_CF": "Lingaljan (Repubblika Afrikana Ċentrali)",
  "ln_CG": "Lingaljan (Kongo)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lożi",
  "lrc": "Luri tat-Tramuntana",
  "lt": "Litwanjan",
  "lt_LT": "Litwanjan (Litwanja)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Democratic Republic of the Congo)",
  "lua": "Luba-Luluwa",
  "lui": "Luwisinuż",
  "lun": "Lunda",
  "luo": "Luwa",
  "lus": "Luxaj",
  "luy": "Luyia",
  "lv": "Latvjan",
  "lv_LV": "Latvjan (Latvja)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Maduriż",
  "maf": "Mafa",
  "mag": "Magaħi",
  "mai": "Majtili",
  "mak": "Makasar",
  "man": "Mandingwan",
  "map": "Awstronesjan",
  "mas": "Masaj",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagażi",
  "mg_MG": "Malagażi (Madagaskar)",
  "mga": "Irlandiż Medjevali",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metà",
  "mh": "Marshalljaniż",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Lingwi Oħra",
  "mk": "Maċedonjan",
  "mk_MK": "Maċedonjan (Maċedonja)",
  "mkh": "Mon-Kmer (Oħra)",
  "ml": "Malayalam",
  "ml_IN": "Malajalam (L-Indja)",
  "mn": "Mongoljan",
  "mn_Cyrl": "Mongoljan (Ċirilliku)",
  "mn_Cyrl_MN": "Mongoljan (Ċirilliku, Mongolja)",
  "mn_MN": "Mongoljan (Mongolja)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Lingwi Manobo",
  "mo": "Moldavjan",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marati (L-Indja)",
  "mrj": "Western Mari",
  "ms": "Malay",
  "ms_BN": "Malajan (Brunej)",
  "ms_Latn": "Malajan (Latin)",
  "ms_Latn_BN": "Malajan (Latin, Brunej)",
  "ms_Latn_MY": "Malajan (Latin, Malasja)",
  "ms_Latn_SG": "Malajan (Latin, Singapor)",
  "ms_MY": "Malajan (Malasja)",
  "ms_SG": "Malajan (Singapor)",
  "mt": "Malti",
  "mt_MT": "Malti (Malta)",
  "mua": "Mundang",
  "mul": "Lingwi Diversi",
  "mun": "Lingwi tal-Munda",
  "mus": "Kriek",
  "mwl": "Mirandiż",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Burmiż",
  "my_MM": "Burmiż (Mjanmar)",
  "mye": "Myene",
  "myn": "Majan",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Naurujan",
  "nah": "Naħwatil",
  "nai": "Indjan tal-Amerika ta’ Fuq (Oħra)",
  "nan": "Min Nan Chinese",
  "nap": "Naplitan",
  "naq": "Nama",
  "nb": "Bokmal Norveġiż",
  "nb_NO": "Bokmahal Norveġiż (Norveġja)",
  "nb_SJ": "Bokmahal Norveġiż (Svalbard and Jan Mayen)",
  "nd": "Ndebeli tat-Tramuntana",
  "nd_ZW": "Ndebele, ta’ Fuq (Żimbabwe)",
  "nds": "Ġermaniż Komuni",
  "nds_NL": "Sassonu Komuni",
  "ne": "Nepaliż",
  "ne_IN": "Nepaliż (L-Indja)",
  "ne_NP": "Nepaliż (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nijas",
  "nic": "Niġerjan - Kordofanjan",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Olandiż",
  "nl_AW": "Olandiż (Aruba)",
  "nl_BE": "Olandiż (Belġju)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Olandiż (Olanda)",
  "nl_SR": "Olandiż (Surinam)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Ninorsk Norveġiż",
  "nn_NO": "Ninorsk Norveġiż (Norveġja)",
  "nnh": "Ngiemboon",
  "no": "Norveġiż",
  "no_NO": "Norveġiż (Norveġja)",
  "nog": "Nogai",
  "non": "Nors Antik",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Ndebele tan-Nofsinhar",
  "nso": "Soto tat-Tramuntana",
  "nub": "Lingwi Nubjani",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Newari Klassiku",
  "ny": "Nyanja",
  "nym": "Njamweżi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Oċċitan",
  "oj": "Oġibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Etijopja)",
  "om_KE": "Oromo (Kenja)",
  "or": "Odia",
  "or_IN": "Orija (L-Indja)",
  "os": "Ossettiku",
  "os_GE": "Ossettiku (Ġorġja)",
  "os_RU": "Ossettiku (Ir-Russja)",
  "osa": "Osaġjan",
  "ota": "Tork Ottoman",
  "oto": "Lingwi Otomjani",
  "pa": "Punjabi",
  "pa_Arab": "Punġabi (Għarbi)",
  "pa_Arab_PK": "Punġabi (Għarbi, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punġabi (L-Indja)",
  "pa_PK": "Punġabi (Pakistan)",
  "paa": "Papwan (Oħra)",
  "pag": "Pangasinjan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palawjan",
  "pcd": "Picard",
  "pcm": "Pidgin Niġerjan",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Persjan Antik",
  "pfl": "Palatine German",
  "phi": "Filippin (Oħra)",
  "phn": "Feniċju",
  "pi": "Pali",
  "pl": "Pollakk",
  "pl_PL": "Pollakk (Polonja)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Ponpejan",
  "pra": "Lingwi Prakriti",
  "prg": "Prussu",
  "pro": "Provenzal Antik",
  "ps": "Pashto",
  "ps_AF": "Paxtun (Afganistan)",
  "pt": "Portugiż",
  "pt_AO": "Portugiż (Angola)",
  "pt_BR": "Portugiż (Il-Brażil)",
  "pt_CV": "Portugiż (Kape Verde)",
  "pt_GW": "Portugiż (Ginea-Bissaw)",
  "pt_MO": "Portugiż (Macao S.A.R., China)",
  "pt_MZ": "Portugiż (Możambik)",
  "pt_PT": "Portugiż (Portugall)",
  "pt_ST": "Portugiż (Sao Tome and Principe)",
  "pt_TL": "Portugiż (Timor tal-Lvant)",
  "qu": "Quechua",
  "qu_BO": "Keċwa (Bolivja)",
  "qu_EC": "Keċwa (Ekwador)",
  "qu_PE": "Keċwa (Peru)",
  "quc": "K’iche’",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Raġastani",
  "rap": "Rapanwi",
  "rar": "Rarotongani",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romanz",
  "rm_CH": "Reto-Romanz (Svizzera)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Rumen",
  "ro_MD": "Rumen (Maldova)",
  "ro_RO": "Rumen (Rumanija)",
  "roa": "Romanz (Oħra)",
  "rof": "Rombo",
  "rom": "Romanesk",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Russu",
  "ru_BY": "Russu (Bjelorussja)",
  "ru_KG": "Russu (Kirgistan)",
  "ru_KZ": "Russu (Każakstan)",
  "ru_MD": "Russu (Maldova)",
  "ru_RU": "Russu (Ir-Russja)",
  "ru_UA": "Russu (Ukraina)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanjan",
  "rw": "Kinjarwanda",
  "rw_RW": "Kinjarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sai": "Indjan tal-Amerika t’Isfel (Oħra)",
  "sal": "Salixan",
  "sam": "Samaritan Aramajk",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinjan",
  "scn": "Sqalli",
  "sco": "Skoċċiż",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Sami tat-Tramuntana",
  "se_FI": "Sami ta’ Fuq (Finlandja)",
  "se_NO": "Sami ta’ Fuq (Norveġja)",
  "se_SE": "Sami ta’ Fuq (Żvezja)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Semitiku",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Repubblika Afrikana Ċentrali)",
  "sga": "Irlandiż Antik",
  "sgn": "Lingwa tas-Sinjali",
  "sgs": "Samogitian",
  "sh": "Serbo-Kroat",
  "sh_BA": "Serbo-Kroat (Bożnija Ħerżegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinħaliż (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Lingwi Suwjani",
  "sit": "Sino-Tibetjani (Oħra)",
  "sk": "Slovakk",
  "sk_SK": "Slovakk (Slovakkja)",
  "sl": "Sloven",
  "sl_SI": "Sloven (Slovenja)",
  "sla": "Slavic (Other)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Sami tan-Nofsinhar",
  "smi": "Sami languages (Other)",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Xona (Żimbabwe)",
  "snk": "Soninke",
  "so": "Somali",
  "so_DJ": "Somali (Ġibuti)",
  "so_ET": "Somali (Etijopja)",
  "so_KE": "Somali (Kenja)",
  "so_SO": "Somali (Somalja)",
  "sog": "Sogdien",
  "son": "Songaj",
  "sq": "Albaniż",
  "sq_AL": "Albaniż (Albanija)",
  "sq_MK": "Albaniż (Maċedonja)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serb",
  "sr_BA": "Serb (Bożnija Ħerżegovina)",
  "sr_Cyrl": "Serb (Ċirilliku)",
  "sr_Cyrl_BA": "Serb (Ċirilliku, Bożnija Ħerżegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serb (Latin)",
  "sr_Latn_BA": "Serb (Latin, Bożnija Ħerżegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssa": "Nilo-Saħaram",
  "ssy": "Saho",
  "st": "Soto tan-Nofsinhar",
  "stq": "Saterland Frisian",
  "su": "Sundaniż",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerjan",
  "sv": "Żvediż",
  "sv_AX": "Svediż (Gżejjer Aland)",
  "sv_FI": "Svediż (Finlandja)",
  "sv_SE": "Svediż (Żvezja)",
  "sw": "Swahili",
  "sw_CD": "Swahili tar-Repubblika Demokratika tal-Kongo",
  "sw_KE": "Swaħili (Kenja)",
  "sw_TZ": "Swaħili (Tanżanija)",
  "sw_UG": "Swaħili (Uganda)",
  "swb": "Komorjan",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Sirjan",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamil (L-Indja)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Malasja)",
  "ta_SG": "Tamil (Singapor)",
  "tai": "Tai (Oħra)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (L-Indja)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "Tajlandiż",
  "th_TH": "Tajlandiż (Tajlandja)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinja (Eritreja)",
  "ti_ET": "Tigrinja (Etijopja)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmeni",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Filippini)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Tonga (Njasa)",
  "tpi": "Tok Pisin",
  "tr": "Tork",
  "tr_CY": "Tork (Ċipru)",
  "tr_TR": "Tork (Turkija)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tup": "Tupi languages",
  "tut": "Altajk (Oħra)",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Taħitjan",
  "tyv": "Tuvinjan",
  "tzm": "Tamazight tal-Atlas Ċentrali",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Wigur (Għarbi)",
  "ug_Arab_CN": "Wigur (Għarbi, Iċ-Ċina)",
  "ug_CN": "Wigur (Iċ-Ċina)",
  "uga": "Ugaritiku",
  "uk": "Ukren",
  "uk_UA": "Ukranjan (Ukraina)",
  "umb": "Umbundu",
  "und": "Lingwa Mhix Magħrufa",
  "ur": "Urdu",
  "ur_IN": "Urdu (L-Indja)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Użbek (Afganistan)",
  "uz_Arab": "Użbek (Għarbi)",
  "uz_Arab_AF": "Użbek (Għarbi, Afganistan)",
  "uz_Cyrl": "Użbek (Ċirilliku)",
  "uz_Cyrl_UZ": "Użbek (Ċirilliku, Użbekistan)",
  "uz_Latn": "Użbek (Latin)",
  "uz_Latn_UZ": "Użbek (Latin, Użbekistan)",
  "uz_UZ": "Użbek (Użbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Vjetnamiż",
  "vi_VN": "Vjetnamiż (Vjetnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapuk",
  "vot": "Votik",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wak": "Lingwi Wakaxani",
  "wal": "Walamo",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Lingwi Sorbjani",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yo_BJ": "Joruba (Benin)",
  "yo_NG": "Joruba (Niġerja)",
  "ypk": "Lingwi Jupiċi",
  "yrl": "Nheengatu",
  "yue": "Kantoniż",
  "za": "Zhuang",
  "zap": "Żapotek",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Żenaga",
  "zgh": "Tamazight Standard tal-Marokk",
  "zh": "Ċiniż",
  "zh_CN": "Ċiniż (Iċ-Ċina)",
  "zh_HK": "Ċiniż (Ħong Kong S.A.R. Ċina)",
  "zh_Hans": "Ċiniż (Simplifikat)",
  "zh_Hans_CN": "Ċiniż (Simplifikat, Iċ-Ċina)",
  "zh_Hans_HK": "Ċiniż (Simplifikat, Ħong Kong S.A.R. Ċina)",
  "zh_Hans_MO": "Ċiniż (Simplifikat, Macao S.A.R., China)",
  "zh_Hans_SG": "Ċiniż (Simplifikat, Singapor)",
  "zh_Hant": "Ċiniż (Tradizzjonali)",
  "zh_Hant_HK": "Ċiniż (Tradizzjonali, Ħong Kong S.A.R. Ċina)",
  "zh_Hant_MO": "Ċiniż (Tradizzjonali, Macao S.A.R., China)",
  "zh_Hant_TW": "Ċiniż (Tradizzjonali, Tajwan)",
  "zh_MO": "Ċiniż (Macao S.A.R., China)",
  "zh_SG": "Ċiniż (Singapor)",
  "zh_TW": "Ċiniż (Tajwan)",
  "znd": "Żande",
  "zu": "Żulu",
  "zu_ZA": "Żulu (Afrika t’Isfel)",
  "zun": "Żuni",
  "zxx": "Bla kontenut lingwistiku",
  "zza": "Zaza"
};
