const names = {
  "AF": "افغانستان",
  "Arab": "عربی",
  "aa": "Afar",
  "ab": "abxazcha",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "af": "afrikancha",
  "agq": "ag‘emcha",
  "ain": "Ainu",
  "ak": "akancha",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "am": "amxarcha",
  "an": "Aragonese",
  "anp": "Angika",
  "ar": "arabcha",
  "ar_001": "zamonavij standart arabcha",
  "arn": "mapuchiycha",
  "arp": "Arapaho",
  "as": "assamcha",
  "asa": "asucha",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "ozarbayjoncha",
  "ba": "boshqircha",
  "ban": "Balinese",
  "bas": "Basaa",
  "be": "belaruscha",
  "bem": "bembacha",
  "bez": "benacha",
  "bg": "bolgarcha",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bm": "bambarcha",
  "bn": "bengalcha",
  "bo": "tibetcha",
  "br": "bretoncha",
  "brx": "bodocha",
  "bs": "bosniycha",
  "bug": "Buginese",
  "byn": "Blin",
  "ca": "katalancha",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "chigcha",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chr": "cherokcha",
  "chy": "Cheyenne",
  "ckb": "sorani kurd tili",
  "co": "korsiancha",
  "cs": "chexcha",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "uelscha",
  "da": "datcha",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "taitcha",
  "de_AT": "nemischa (Avstriya)",
  "de_CH": "nemischa (Shveysariya)",
  "dgr": "Dogrib",
  "dje": "zarmacha",
  "dsb": "quyi sorbcha",
  "dua": "dualcha",
  "dv": "Divehi",
  "dyo": "yola-fonyicha",
  "dz": "yovoncha",
  "dzg": "Dazaga",
  "ebu": "embucha",
  "ee": "ivicha",
  "efi": "Efik",
  "eka": "Ekajuk",
  "el": "yunoncha",
  "en_AU": "inglizcha (Avstraliya)",
  "en_CA": "inglizcha (Kanada)",
  "en_GB": "inglizcha (Birlashgan Qirollik)",
  "en_US": "inglizcha (Qoʻshma Shtatlar)",
  "eo": "esperantocha",
  "es_419": "Lotin Amerika ispanchasi",
  "es_ES": "ispancha (Ispaniya)",
  "es_MX": "ispancha (Meksika)",
  "eu": "baskcha",
  "ewo": "Ewondo",
  "fa": "دری",
  "fa_AF": "دری (افغانستان)",
  "fa_IR": "دری (Eron)",
  "ff": "Fulah",
  "fj": "fijcha",
  "fon": "Fon",
  "fr_CA": "fransuzcha (Kanada)",
  "fr_CH": "fransuzcha (Shveysariya)",
  "fur": "Friulian",
  "fy": "gʻarbiy friziancha",
  "ga": "irlandcha",
  "gaa": "Ga",
  "gag": "gagozcha",
  "gan": "Gan Chinese",
  "gd": "Scottish Gaelic",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "galitsiycha",
  "gn": "gorancha",
  "gor": "Gorontalo",
  "gsw": "shveysariya nemischasi",
  "gu": "gujoratcha",
  "guz": "guzcha",
  "gv": "mencha",
  "gwi": "Gwichʼin",
  "ha": "xauscha",
  "he": "ibroniy",
  "hi": "hindcha",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hr": "xorvatcha",
  "hsb": "yuqori sorbcha",
  "ht": "gaitcha",
  "hu": "vengrcha",
  "hup": "Hupa",
  "hy": "armancha",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "indoneyzcha",
  "ig": "igbocha",
  "ii": "zichuan yicha",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "islandcha",
  "it": "italyancha",
  "iu": "inuktitutcha",
  "ja": "yaponcha",
  "jbo": "Lojban",
  "jgo": "ngombcha",
  "jmc": "machamcha",
  "jv": "yavancha",
  "kab": "qobilcha",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "kambcha",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kde": "maqondiy",
  "kea": "kabuverdiancha",
  "kfo": "Koro",
  "kha": "Khasi",
  "khq": "qoyra-chincha",
  "ki": "kikuycha",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kl": "kalallisutcha",
  "kln": "kalenjincha",
  "km": "xmercha",
  "kmb": "Kimbundu",
  "kn": "kannadcha",
  "koi": "komi-permyakcha",
  "kok": "konkancha",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks_Arab": "kashmircha (عربی)",
  "ks_Arab_IN": "kashmircha (عربی, Hindiston)",
  "ksb": "shambalacha",
  "ksf": "bafiycha",
  "ksh": "Colognian",
  "kum": "Kumyk",
  "kv": "Komi",
  "kw": "kornishcha",
  "lad": "Ladino",
  "lag": "langcha",
  "lez": "Lezghian",
  "lg": "gandcha",
  "li": "Limburgish",
  "lkt": "lakotcha",
  "ln": "lingalcha",
  "lo": "laoscha",
  "loz": "Lozi",
  "lt": "litovcha",
  "lu": "luba-katangcha",
  "lua": "Luba-Lulua",
  "lun": "Lunda",
  "luo": "luocha",
  "lus": "Mizo",
  "luy": "luycha",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "mas": "masaycha",
  "mdf": "Moksha",
  "men": "Mende",
  "mer": "merucha",
  "mfe": "morisyencha",
  "mg": "malagasiycha",
  "mgh": "makuva-mittocha",
  "mgo": "metacha",
  "mh": "Marshallese",
  "mi": "maoriycha",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "makedoncha",
  "ml": "malayamcha",
  "mn": "mo‘g‘ulcha",
  "mni": "Manipuri",
  "moh": "mohaukcha",
  "mos": "Mossi",
  "mr": "maratcha",
  "ms": "malaycha",
  "mt": "maltacha",
  "mua": "mundangcha",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "my": "birmancha",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "naq": "namacha",
  "nb": "norvegcha bokmal",
  "nd": "shimoliy ndebelcha",
  "nds": "Low German",
  "ne": "nepalcha",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl": "gollandcha",
  "nl_BE": "gollandcha (Belgiya)",
  "nmg": "kvaziycha",
  "nn": "norvegcha ninorsk",
  "nnh": "Ngiemboon",
  "nog": "Nogai",
  "nqo": "nqoancha",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "noyrcha",
  "nv": "Navajo",
  "ny": "Nyanja",
  "nyn": "nyankolcha",
  "oc": "Occitan",
  "om": "oromocha",
  "or": "oriycha",
  "os": "Ossetic",
  "pa_Arab": "panjobcha (عربی)",
  "pa_Arab_PK": "panjobcha (عربی, Pokiston)",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "prg": "Prussian",
  "ps": "پشتو",
  "ps_AF": "پشتو (افغانستان)",
  "pt_BR": "portugalcha (Braziliya)",
  "pt_PT": "portugalcha (Portugaliya)",
  "qu": "qvechuancha",
  "quc": "qichiancha",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "romancha",
  "rn": "rundcha",
  "rof": "rombacha",
  "root": "Root",
  "rup": "Aromanian",
  "rw": "kinyarvandcha",
  "rwk": "ruandcha",
  "sa": "sanskritcha",
  "sad": "Sandawe",
  "sah": "Sakha",
  "saq": "samburcha",
  "sat": "Santali",
  "sba": "Ngambay",
  "sbp": "sanguancha",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "sindxiycha",
  "se": "shimoliy semiycha",
  "seh": "seniycha",
  "ses": "koryaboro senniycha",
  "sg": "sangoancha",
  "shi": "tachilgitcha",
  "shn": "Shan",
  "si": "sinholcha",
  "sm": "Samoan",
  "sma": "janubiy semiycha",
  "smj": "luli semiycha",
  "smn": "inari semiycha",
  "sms": "shkolt semiycha",
  "sn": "shoniycha",
  "snk": "Soninke",
  "sq": "albancha",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "su": "sundancha",
  "suk": "Sukuma",
  "sv": "shvedcha",
  "sw": "svahilcha",
  "swb": "Comorian",
  "syr": "Syriac",
  "ta": "tamilcha",
  "te": "telugvancha",
  "tem": "Timne",
  "teo": "tesoancha",
  "tet": "Tetum",
  "tg": "tojikcha",
  "th": "taycha",
  "ti": "tigrincha",
  "tig": "Tigre",
  "tk": "turkmancha",
  "tlh": "Klingon",
  "tn": "Tswana",
  "to": "tongocha",
  "tpi": "Tok Pisin",
  "tr": "turkcha",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tt": "tatarcha",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "twq": "tosovoqcha",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "markaziy atlas vaqt zonasi",
  "udm": "Udmurt",
  "ug": "uygʻurcha",
  "ug_Arab": "uygʻurcha (عربی)",
  "ug_Arab_CN": "uygʻurcha (عربی, Xitoy)",
  "uk": "ukraincha",
  "umb": "Umbundu",
  "und": "nomaʼlum til",
  "ur": "urducha",
  "uz": "اوزبیک",
  "uz_AF": "اوزبیک (افغانستان)",
  "uz_Arab": "اوزبیک (عربی)",
  "uz_Arab_AF": "اوزبیک (عربی, افغانستان)",
  "uz_Cyrl": "اوزبیک (Kiril)",
  "uz_Cyrl_UZ": "اوزبیک (Kiril, Oʻzbekiston)",
  "uz_Latn": "اوزبیک (Lotin)",
  "uz_Latn_UZ": "اوزبیک (Lotin, Oʻzbekiston)",
  "uz_UZ": "اوزبیک (Oʻzbekiston)",
  "vai": "vayancha",
  "ve": "Venda",
  "vi": "vyetnamcha",
  "vo": "Volapük",
  "vun": "vunjoancha",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "wo": "volofcha",
  "xal": "Kalmyk",
  "xh": "xosancha",
  "xog": "sogancha",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "yorubcha",
  "yue": "Cantonese",
  "zgh": "standart marokash tamazit",
  "zh": "xitoycha",
  "zh_Hans": "xitoycha (Soddalashtirilgan)",
  "zh_Hant": "xitoycha (Anʼanaviy)",
  "zu": "zuluancha",
  "zun": "Zuni",
  "zxx": "til tarkibi yoʻq",
  "zza": "Zaza"
};
