const names = {
  "arq": "Arab Algeria",
  "ast": "Astur",
  "az": "Azerbaijan",
  "bg": "Bulgar",
  "ceb": "Sebuano",
  "dsb": "Sorbia Rendah",
  "dum": "Belanda Tengah",
  "eu": "Bask",
  "fo": "Faro",
  "fr_CA": "Prancis (Kanada)",
  "fr_CH": "Prancis (Swiss)",
  "frc": "Cajun French",
  "got": "Gothik",
  "gsw": "Jerman Swiss",
  "gu": "Gujarati",
  "hsb": "Sorbia Atas",
  "ht": "Haiti",
  "id": "Bahasa Indonesia",
  "mgo": "meta’",
  "rup": "Makedo-Rumania",
  "sli": "Silesia Bawah",
  "so": "Somali",
  "sr": "Serb",
  "zh": "China",
  "zh_Hans": "China (Sederhana)",
  "zh_Hant": "China (Tradisional)"
};
