const names = {
  "001": "Mundo",
  "002": "África",
  "003": "América del Norte",
  "005": "Sudamérica",
  "009": "Oceanía",
  "011": "África occidental",
  "013": "Centroamérica",
  "014": "África oriental",
  "015": "África septentrional",
  "017": "África central",
  "018": "África meridional",
  "019": "América",
  "021": "Norteamérica",
  "029": "Caribe",
  "030": "Asia oriental",
  "034": "Asia meridional",
  "035": "Sudeste asiático",
  "039": "Europa meridional",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Región de Micronesia",
  "061": "Polinesia",
  "062": "Asia centro-sur",
  "142": "Asia",
  "143": "Asia central",
  "145": "Asia occidental",
  "150": "Europa",
  "151": "Europa oriental",
  "154": "Europa septentrional",
  "155": "Europa occidental",
  "172": "Comunidad de Estados Independientes",
  "200": "Checoslovaquia",
  "202": "África subsahariana",
  "419": "Latinoamérica",
  "830": "Islas del Canal",
  "AC": "Isla de la Ascensión",
  "AD": "Andorra",
  "AE": "Emiratos Árabes Unidos",
  "AF": "Afganistán",
  "AG": "Antigua y Barbuda",
  "AI": "Anguila",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antillas Neerlandesas",
  "AO": "Angola",
  "AQ": "Antártida",
  "AR": "Argentina",
  "AS": "Samoa Americana",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Islas Åland",
  "AZ": "Azerbaiyán",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Albanés caucásico",
  "Ahom": "Ahom",
  "Arab": "árabe",
  "Aran": "nastaliq",
  "Armi": "Arameo imperial",
  "Armn": "armenio",
  "Avst": "avéstico",
  "BA": "Bosnia y Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladés",
  "BE": "Bélgica",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Baréin",
  "BI": "Burundi",
  "BJ": "Benín",
  "BL": "San Bartolomé",
  "BM": "Bermudas",
  "BN": "Brunéi",
  "BO": "Bolivia",
  "BQ": "Caribe neerlandés",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bután",
  "BV": "Isla Bouvet",
  "BW": "Botsuana",
  "BY": "Bielorrusia",
  "BZ": "Belice",
  "Bali": "balinés",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "batak",
  "Beng": "bengalí",
  "Bhks": "Bhaiksuki",
  "Blis": "símbolos blis",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "braille",
  "Bugi": "buginés",
  "Buhd": "buhid",
  "CA": "Canadá",
  "CC": "Islas Cocos",
  "CD": "República Democrática del Congo",
  "CF": "República Centroafricana",
  "CG": "Congo",
  "CH": "Suiza",
  "CI": "Côte d’Ivoire",
  "CK": "Islas Cook",
  "CL": "Chile",
  "CM": "Camerún",
  "CN": "China",
  "CO": "Colombia",
  "CP": "Isla Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia y Montenegro",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curazao",
  "CX": "Isla de Navidad",
  "CY": "Chipre",
  "CZ": "Chequia",
  "Cakm": "Chakma",
  "Cans": "silabarios aborígenes canadienses unificados",
  "Cari": "cario",
  "Cham": "cham",
  "Cher": "cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "cirth",
  "Copt": "copto",
  "Cprt": "chipriota",
  "Cyrl": "cirílico",
  "Cyrs": "cirílico del antiguo eslavo eclesiástico",
  "DD": "Alemania del Este",
  "DE": "Alemania",
  "DG": "Diego García",
  "DJ": "Yibuti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Argelia",
  "Deva": "devanagari",
  "Diak": "Buceo Akuru",
  "Dogr": "Dogra",
  "Dsrt": "deseret",
  "Dupl": "Taquigrafía duployan",
  "EA": "Ceuta y Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egipto",
  "EH": "Sáhara Occidental",
  "ER": "Eritrea",
  "ES": "España",
  "ET": "Etiopía",
  "EU": "Unión Europea",
  "EZ": "zona euro",
  "Egyd": "egipcio demótico",
  "Egyh": "egipcio hierático",
  "Egyp": "jeroglíficos egipcios",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "etiópico",
  "FI": "Finlandia",
  "FJ": "Fiyi",
  "FK": "Islas Malvinas",
  "FM": "Micronesia",
  "FO": "Islas Feroe",
  "FR": "Francia",
  "FX": "Francia metropolitana",
  "GA": "Gabón",
  "GB": "Reino Unido",
  "GD": "Granada",
  "GE": "Georgia",
  "GF": "Guayana Francesa",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenlandia",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadalupe",
  "GQ": "Guinea Ecuatorial",
  "GR": "Grecia",
  "GS": "Islas Georgia del Sur y Sandwich del Sur",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bisáu",
  "GY": "Guyana",
  "Geok": "georgiano eclesiástico",
  "Geor": "georgiano",
  "Glag": "glagolítico",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "gótico",
  "Gran": "Grantha",
  "Grek": "griego",
  "Gujr": "gujarati",
  "Guru": "gurmuji",
  "HK": "RAE de Hong Kong (China)",
  "HM": "Islas Heard y McDonald",
  "HN": "Honduras",
  "HR": "Croacia",
  "HT": "Haití",
  "HU": "Hungría",
  "Hanb": "hanb",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanunoo",
  "Hans": "simplificado",
  "Hant": "tradicional",
  "Hatr": "Hatran",
  "Hebr": "hebreo",
  "Hira": "hiragana",
  "Hluw": "Jeroglíficos de Anatolia",
  "Hmng": "pahawh hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "silabarios japoneses",
  "Hung": "húngaro antiguo",
  "IC": "Canarias",
  "ID": "Indonesia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Isla de Man",
  "IN": "India",
  "IO": "Territorio Británico del Océano Índico",
  "IQ": "Irak",
  "IR": "Irán",
  "IS": "Islandia",
  "IT": "Italia",
  "Inds": "Indio (harappan)",
  "Ital": "antigua bastardilla",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordania",
  "JP": "Japón",
  "Jamo": "jamo",
  "Java": "javanés",
  "Jpan": "japonés",
  "Jurc": "Jurchen",
  "KE": "Kenia",
  "KG": "Kirguistán",
  "KH": "Camboya",
  "KI": "Kiribati",
  "KM": "Comoras",
  "KN": "San Cristóbal y Nieves",
  "KP": "Corea del Norte",
  "KR": "Corea del Sur",
  "KW": "Kuwait",
  "KY": "Islas Caimán",
  "KZ": "Kazajistán",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharosthi",
  "Khmr": "jemer",
  "Khoj": "Khojki",
  "Kits": "Letra pequeña de Khitan",
  "Knda": "canarés",
  "Kore": "coreano",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Líbano",
  "LC": "Santa Lucía",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesoto",
  "LT": "Lituania",
  "LU": "Luxemburgo",
  "LV": "Letonia",
  "LY": "Libia",
  "Lana": "lanna",
  "Laoo": "laosiano",
  "Latf": "latino fraktur",
  "Latg": "latino gaélico",
  "Latn": "latino",
  "Lepc": "lepcha",
  "Limb": "limbu",
  "Lina": "lineal A",
  "Linb": "lineal B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "licio",
  "Lydi": "lidio",
  "MA": "Marruecos",
  "MC": "Mónaco",
  "MD": "Moldavia",
  "ME": "Montenegro",
  "MF": "San Martín",
  "MG": "Madagascar",
  "MH": "Islas Marshall",
  "MI": "Islas Midway",
  "MK": "Macedonia del Norte",
  "ML": "Mali",
  "MM": "Myanmar (Birmania)",
  "MN": "Mongolia",
  "MO": "RAE de Macao (China)",
  "MP": "Islas Marianas del Norte",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauricio",
  "MV": "Maldivas",
  "MW": "Malaui",
  "MX": "México",
  "MY": "Malasia",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "mandeo",
  "Mani": "maniqueo",
  "Marc": "Marchen",
  "Maya": "jeroglíficos mayas",
  "Medf": "Medefaidrina",
  "Mend": "Mende",
  "Merc": "cursivo meroítico",
  "Mero": "meroítico",
  "Mlym": "malayálam",
  "Modi": "Modi",
  "Mong": "mongol",
  "Moon": "moon",
  "Mroo": "Mro",
  "Mtei": "manipuri",
  "Mult": "Multani",
  "Mymr": "birmano",
  "NA": "Namibia",
  "NC": "Nueva Caledonia",
  "NE": "Níger",
  "NF": "Isla Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Países Bajos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Zona neutral",
  "NU": "Niue",
  "NZ": "Nueva Zelanda",
  "Nand": "Nandinagari",
  "Narb": "Viejo árabe del norte",
  "Nbat": "Nabateo",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "n’ko",
  "Nshu": "Nüshu",
  "OM": "Omán",
  "Ogam": "ogham",
  "Olck": "ol ciki",
  "Orkh": "orkhon",
  "Orya": "oriya",
  "Osge": "Osage",
  "Osma": "osmaniya",
  "PA": "Panamá",
  "PC": "Territorio en fideicomiso de las islas del Pacífico",
  "PE": "Perú",
  "PF": "Polinesia Francesa",
  "PG": "Papúa Nueva Guinea",
  "PH": "Filipinas",
  "PK": "Pakistán",
  "PL": "Polonia",
  "PM": "San Pedro y Miquelón",
  "PN": "Islas Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Territorios Palestinos",
  "PT": "Portugal",
  "PU": "Miscelánea de Estados Unidos Islas del Pacífico",
  "PW": "Palaos",
  "PY": "Paraguay",
  "PZ": "Zona del Canal de Panamá",
  "Palm": "Palmyrene",
  "Pauc": "Pau Cin Hau",
  "Perm": "permiano antiguo",
  "Phag": "phags-pa",
  "Phli": "Pahlavi inscripcional",
  "Phlp": "Salterio Pahlavi",
  "Phlv": "Libro Pahlavi",
  "Phnx": "fenicio",
  "Plrd": "Pollard Miao",
  "Prti": "Parto inscripcional",
  "QA": "Catar",
  "QO": "Territorios alejados de Oceanía",
  "Qaag": "zawgyi",
  "RE": "Reunión",
  "RO": "Rumanía",
  "RS": "Serbia",
  "RU": "Rusia",
  "RW": "Ruanda",
  "Rjng": "rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "rongo-rongo",
  "Runr": "rúnico",
  "SA": "Arabia Saudí",
  "SB": "Islas Salomón",
  "SC": "Seychelles",
  "SD": "Sudán",
  "SE": "Suecia",
  "SG": "Singapur",
  "SH": "Santa Elena",
  "SI": "Eslovenia",
  "SJ": "Svalbard y Jan Mayen",
  "SK": "Eslovaquia",
  "SL": "Sierra Leona",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Sudán del Sur",
  "ST": "Santo Tomé y Príncipe",
  "SU": "Unión de Repúblicas Socialistas Soviéticas",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Esuatini",
  "Samr": "samaritano",
  "Sara": "sarati",
  "Sarb": "Viejo árabe del sur",
  "Saur": "saurashtra",
  "Sgnw": "SignWriting",
  "Shaw": "shaviano",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "cingalés",
  "Sogd": "Sogdian",
  "Sogo": "Viejo Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "sundanés",
  "Sylo": "syloti nagri",
  "Syrc": "siriaco",
  "Syre": "siriaco estrangelo",
  "Syrj": "siriaco occidental",
  "Syrn": "siriaco oriental",
  "TA": "Tristán de Acuña",
  "TC": "Islas Turcas y Caicos",
  "TD": "Chad",
  "TF": "Territorios Australes Franceses",
  "TG": "Togo",
  "TH": "Tailandia",
  "TJ": "Tayikistán",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistán",
  "TN": "Túnez",
  "TO": "Tonga",
  "TR": "Turquía",
  "TT": "Trinidad y Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwán",
  "TZ": "Tanzania",
  "Tagb": "tagbanúa",
  "Takr": "Takri",
  "Tale": "tai le",
  "Talu": "nuevo tai lue",
  "Taml": "tamil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "telugu",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagalo",
  "Thaa": "thaana",
  "Thai": "tailandés",
  "Tibt": "tibetano",
  "Tirh": "Tirhuta",
  "UA": "Ucrania",
  "UG": "Uganda",
  "UM": "Islas menores alejadas de EE. UU.",
  "UN": "Naciones Unidas",
  "US": "Estados Unidos",
  "UY": "Uruguay",
  "UZ": "Uzbekistán",
  "Ugar": "ugarítico",
  "VA": "Ciudad del Vaticano",
  "VC": "San Vicente y las Granadinas",
  "VD": "Vietnam del Norte",
  "VE": "Venezuela",
  "VG": "Islas Vírgenes Británicas",
  "VI": "Islas Vírgenes de EE. UU.",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "Visp": "lenguaje visible",
  "WF": "Wallis y Futuna",
  "WK": "Isla Wake",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudoacentos",
  "XB": "Pseudobidi",
  "XK": "Kosovo",
  "Xpeo": "persa antiguo",
  "Xsux": "cuneiforme sumerio-acadio",
  "YD": "República Democrática Popular del Yemen",
  "YE": "Yemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "yi",
  "ZA": "Sudáfrica",
  "ZM": "Zambia",
  "ZW": "Zimbabue",
  "ZZ": "Región desconocida",
  "Zanb": "Plaza Zanabazar",
  "Zinh": "heredado",
  "Zmth": "notación matemática",
  "Zsye": "emojis",
  "Zsym": "símbolos",
  "Zxxx": "no escrito",
  "Zyyy": "común",
  "Zzzz": "alfabeto desconocido",
  "aa": "afar",
  "ab": "abjasio",
  "ace": "acehnés",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adigué",
  "ae": "avéstico",
  "aeb": "Tunisian Arabic",
  "af": "afrikáans",
  "af_NA": "afrikáans (Namibia)",
  "af_ZA": "afrikáans (Sudáfrica)",
  "afa": "lengua afroasiática",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "acadio",
  "akz": "Alabama",
  "ale": "aleutiano",
  "alg": "lenguas algonquinas",
  "aln": "Gheg Albanian",
  "alt": "altái meridional",
  "am": "amárico",
  "am_ET": "amárico (Etiopía)",
  "an": "aragonés",
  "ang": "inglés antiguo",
  "anp": "angika",
  "apa": "lenguas apache",
  "ar": "árabe",
  "ar_001": "árabe estándar moderno",
  "ar_AE": "árabe (Emiratos Árabes Unidos)",
  "ar_BH": "árabe (Baréin)",
  "ar_DJ": "árabe (Yibuti)",
  "ar_DZ": "árabe (Argelia)",
  "ar_EG": "árabe (Egipto)",
  "ar_EH": "árabe (Sáhara Occidental)",
  "ar_ER": "árabe (Eritrea)",
  "ar_IL": "árabe (Israel)",
  "ar_IQ": "árabe (Iraq)",
  "ar_JO": "árabe (Jordania)",
  "ar_KM": "árabe (Comoras)",
  "ar_KW": "árabe (Kuwait)",
  "ar_LB": "árabe (Líbano)",
  "ar_LY": "árabe (Libia)",
  "ar_MA": "árabe (Marruecos)",
  "ar_MR": "árabe (Mauritania)",
  "ar_OM": "árabe (Omán)",
  "ar_PS": "árabe (Territorios Palestinos)",
  "ar_QA": "árabe (Catar)",
  "ar_SA": "árabe (Arabia Saudí)",
  "ar_SD": "árabe (Sudán)",
  "ar_SO": "árabe (Somalia)",
  "ar_SS": "árabe (Sudán del Sur)",
  "ar_SY": "árabe (Siria)",
  "ar_TD": "árabe (Chad)",
  "ar_TN": "árabe (Túnez)",
  "ar_YE": "árabe (Yemen)",
  "arc": "arameo",
  "arn": "mapuche",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "ars": "árabe najdí",
  "art": "lengua artificial",
  "arw": "arahuaco",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "asamés",
  "as_IN": "asamés (India)",
  "asa": "asu",
  "ase": "American Sign Language",
  "ast": "asturiano",
  "ath": "lenguas atabascas",
  "aus": "lenguas australianas",
  "av": "avar",
  "avk": "Kotava",
  "awa": "avadhi",
  "ay": "aimara",
  "az": "azerbaiyano",
  "az_AZ": "azerí (Azerbaiyán)",
  "az_Arab": "Azerbaiyano (árabe)",
  "az_Cyrl": "azerí (cirílico)",
  "az_Cyrl_AZ": "azerí (cirílico, Azerbaiyán)",
  "az_Latn": "azerí (latín)",
  "az_Latn_AZ": "azerí (latín, Azerbaiyán)",
  "azb": "South Azerbaijani",
  "ba": "baskir",
  "bad": "banda",
  "bai": "lenguas bamileke",
  "bal": "baluchi",
  "ban": "balinés",
  "bar": "Bavarian",
  "bas": "basaa",
  "bat": "lengua báltica",
  "bax": "bamún",
  "bbc": "Batak Toba",
  "bbj": "ghomala",
  "be": "bielorruso",
  "be_BY": "bielorruso (Bielorrusia)",
  "bej": "beja",
  "bem": "bemba",
  "ber": "bereber",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "Badaga",
  "bg": "búlgaro",
  "bg_BG": "búlgaro (Bulgaria)",
  "bgn": "baluchi occidental",
  "bh": "bihari",
  "bho": "bhoyapurí",
  "bi": "bislama",
  "bik": "bicol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latín)",
  "bm_Latn_ML": "bambara (latín, Mali)",
  "bn": "bengalí",
  "bn_BD": "bengalí (Bangladés)",
  "bn_IN": "bengalí (India)",
  "bnt": "bantú",
  "bo": "tibetano",
  "bo_CN": "tibetano (China)",
  "bo_IN": "tibetano (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretón",
  "br_FR": "bretón (Francia)",
  "bra": "braj",
  "brh": "Brahui",
  "brx": "bodo",
  "bs": "bosnio",
  "bs_BA": "bosnio (Bosnia-Herzegovina)",
  "bs_Cyrl": "bosnio (cirílico)",
  "bs_Cyrl_BA": "bosnio (cirílico, Bosnia-Herzegovina)",
  "bs_Latn": "bosnio (latín)",
  "bs_Latn_BA": "bosnio (latín, Bosnia-Herzegovina)",
  "bss": "akoose",
  "btk": "batak",
  "bua": "buriato",
  "bug": "buginés",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "catalán",
  "ca_AD": "catalán (Andorra)",
  "ca_ES": "catalán (España)",
  "ca_FR": "catalán (Francia)",
  "ca_IT": "catalán (Italia)",
  "cad": "caddo",
  "cai": "lengua india centroamericana",
  "car": "caribe",
  "cau": "lengua caucásica",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "chakma",
  "ce": "checheno",
  "ceb": "cebuano",
  "cel": "lengua celta",
  "cgg": "chiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "chagatái",
  "chk": "trukés",
  "chm": "marí",
  "chn": "jerga chinuk",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cheroqui",
  "chy": "cheyene",
  "cic": "Chickasaw",
  "ckb": "kurdo sorani",
  "cmc": "lenguas chámicas",
  "co": "corso",
  "cop": "copto",
  "cpe": "lengua criolla o pidgin basada en el inglés",
  "cpf": "lengua criolla o pidgin basada en el francés",
  "cpp": "lengua criolla o pidgin basada en el portugués",
  "cps": "Capiznon",
  "cr": "cree",
  "crh": "tártaro de Crimea",
  "crp": "lengua criolla o pidgin",
  "crs": "criollo seychelense",
  "cs": "checo",
  "cs_CZ": "checo (República Checa)",
  "csb": "casubio",
  "cu": "eslavo eclesiástico",
  "cus": "lengua cusita",
  "cv": "chuvasio",
  "cy": "galés",
  "cy_GB": "galés (Reino Unido)",
  "da": "danés",
  "da_DK": "danés (Dinamarca)",
  "da_GL": "danés (Groenlandia)",
  "dak": "dakota",
  "dar": "dargva",
  "dav": "taita",
  "day": "dayak",
  "de": "alemán",
  "de_AT": "alemán (Austria)",
  "de_BE": "alemán (Bélgica)",
  "de_CH": "alemán (Suiza)",
  "de_DE": "alemán (Alemania)",
  "de_LI": "alemán (Liechtenstein)",
  "de_LU": "alemán (Luxemburgo)",
  "del": "delaware",
  "den": "slave",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "lengua dravídica",
  "dsb": "bajo sorbio",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "neerlandés medio",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "diula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bután)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "ewé",
  "ee_GH": "ewé (Ghana)",
  "ee_TG": "ewé (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "egipcio antiguo",
  "eka": "ekajuk",
  "el": "griego",
  "el_CY": "griego (Chipre)",
  "el_GR": "griego (Grecia)",
  "elx": "elamita",
  "en": "inglés",
  "en_AG": "inglés (Antigua y Barbuda)",
  "en_AI": "inglés (Anguila)",
  "en_AS": "inglés (Samoa Americana)",
  "en_AU": "inglés (Australia)",
  "en_BB": "inglés (Barbados)",
  "en_BE": "inglés (Bélgica)",
  "en_BM": "inglés (Bermudas)",
  "en_BS": "inglés (Bahamas)",
  "en_BW": "inglés (Botsuana)",
  "en_BZ": "inglés (Belice)",
  "en_CA": "inglés (Canadá)",
  "en_CC": "inglés (Islas Cocos)",
  "en_CK": "inglés (Islas Cook)",
  "en_CM": "inglés (Camerún)",
  "en_CX": "inglés (Isla Christmas)",
  "en_DG": "inglés (Diego García)",
  "en_DM": "inglés (Dominica)",
  "en_Dsrt": "Inglés (Deseret)",
  "en_ER": "inglés (Eritrea)",
  "en_FJ": "inglés (Fiyi)",
  "en_FK": "inglés (Islas Malvinas)",
  "en_FM": "inglés (Micronesia)",
  "en_GB": "inglés (Reino Unido)",
  "en_GD": "inglés (Granada)",
  "en_GG": "inglés (Guernesey)",
  "en_GH": "inglés (Ghana)",
  "en_GI": "inglés (Gibraltar)",
  "en_GM": "inglés (Gambia)",
  "en_GU": "inglés (Guam)",
  "en_GY": "inglés (Guyana)",
  "en_HK": "inglés (RAE de Hong Kong (China))",
  "en_IE": "inglés (Irlanda)",
  "en_IM": "inglés (Isla de Man)",
  "en_IN": "inglés (India)",
  "en_IO": "inglés (Territorio Británico del Océano Índico)",
  "en_JE": "inglés (Jersey)",
  "en_JM": "inglés (Jamaica)",
  "en_KE": "inglés (Kenia)",
  "en_KI": "inglés (Kiribati)",
  "en_KN": "inglés (San Cristóbal y Nieves)",
  "en_KY": "inglés (Islas Caimán)",
  "en_LC": "inglés (Santa Lucía)",
  "en_LR": "inglés (Liberia)",
  "en_LS": "inglés (Lesoto)",
  "en_MG": "inglés (Madagascar)",
  "en_MH": "inglés (Islas Marshall)",
  "en_MO": "inglés (RAE de Macao (China))",
  "en_MP": "inglés (Islas Marianas del Norte)",
  "en_MS": "inglés (Montserrat)",
  "en_MT": "inglés (Malta)",
  "en_MU": "inglés (Mauricio)",
  "en_MW": "inglés (Malaui)",
  "en_MY": "inglés (Malasia)",
  "en_NA": "inglés (Namibia)",
  "en_NF": "inglés (Isla Norfolk)",
  "en_NG": "inglés (Nigeria)",
  "en_NR": "inglés (Nauru)",
  "en_NU": "inglés (Isla Niue)",
  "en_NZ": "inglés (Nueva Zelanda)",
  "en_PG": "inglés (Papúa Nueva Guinea)",
  "en_PH": "inglés (Filipinas)",
  "en_PK": "inglés (Pakistán)",
  "en_PN": "inglés (Islas Pitcairn)",
  "en_PR": "inglés (Puerto Rico)",
  "en_PW": "inglés (Palau)",
  "en_RW": "inglés (Ruanda)",
  "en_SB": "inglés (Islas Salomón)",
  "en_SC": "inglés (Seychelles)",
  "en_SD": "inglés (Sudán)",
  "en_SG": "inglés (Singapur)",
  "en_SH": "inglés (Santa Elena)",
  "en_SL": "inglés (Sierra Leona)",
  "en_SS": "inglés (Sudán del Sur)",
  "en_SX": "inglés (Sint Maarten)",
  "en_SZ": "inglés (Suazilandia)",
  "en_TC": "inglés (Islas Turcas y Caicos)",
  "en_TK": "inglés (Tokelau)",
  "en_TO": "inglés (Tonga)",
  "en_TT": "inglés (Trinidad y Tobago)",
  "en_TV": "inglés (Tuvalu)",
  "en_TZ": "inglés (Tanzania)",
  "en_UG": "inglés (Uganda)",
  "en_UM": "inglés (Islas menores alejadas de EE. UU.)",
  "en_US": "inglés (Estados Unidos)",
  "en_VC": "inglés (San Vicente y las Granadinas)",
  "en_VG": "inglés (Islas Vírgenes Británicas)",
  "en_VI": "inglés (Islas Vírgenes de EE. UU.)",
  "en_VU": "inglés (Vanuatu)",
  "en_WS": "inglés (Samoa)",
  "en_ZA": "inglés (Sudáfrica)",
  "en_ZM": "inglés (Zambia)",
  "en_ZW": "inglés (Zimbabue)",
  "enm": "inglés medio",
  "eo": "esperanto",
  "es": "español",
  "es_419": "español latinoamericano",
  "es_AR": "español (Argentina)",
  "es_BO": "español (Bolivia)",
  "es_CL": "español (Chile)",
  "es_CO": "español (Colombia)",
  "es_CR": "español (Costa Rica)",
  "es_CU": "español (Cuba)",
  "es_DO": "español (República Dominicana)",
  "es_EA": "español (Ceuta y Melilla)",
  "es_EC": "español (Ecuador)",
  "es_ES": "español (España)",
  "es_GQ": "español (Guinea Ecuatorial)",
  "es_GT": "español (Guatemala)",
  "es_HN": "español (Honduras)",
  "es_IC": "español (islas Canarias)",
  "es_MX": "español (México)",
  "es_NI": "español (Nicaragua)",
  "es_PA": "español (Panamá)",
  "es_PE": "español (Perú)",
  "es_PH": "español (Filipinas)",
  "es_PR": "español (Puerto Rico)",
  "es_PY": "español (Paraguay)",
  "es_SV": "español (El Salvador)",
  "es_US": "español (Estados Unidos)",
  "es_UY": "español (Uruguay)",
  "es_VE": "español (Venezuela)",
  "esu": "Central Yupik",
  "et": "estonio",
  "et_EE": "estonio (Estonia)",
  "eu": "euskera",
  "eu_ES": "euskera (España)",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fa": "persa",
  "fa_AF": "persa (Afganistán)",
  "fa_IR": "persa (Irán)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fula",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "fula (Camerún)",
  "ff_GN": "fula (Guinea)",
  "ff_MR": "fula (Mauritania)",
  "ff_SN": "fula (Senegal)",
  "fi": "finés",
  "fi_FI": "finés (Finlandia)",
  "fil": "filipino",
  "fit": "Tornedalen Finnish",
  "fiu": "lengua finoúgria",
  "fj": "fiyiano",
  "fo": "feroés",
  "fo_FO": "feroés (Islas Feroe)",
  "fon": "fon",
  "fr": "francés",
  "fr_BE": "francés (Bélgica)",
  "fr_BF": "francés (Burkina Faso)",
  "fr_BI": "francés (Burundi)",
  "fr_BJ": "francés (Benín)",
  "fr_BL": "francés (San Bartolomé)",
  "fr_CA": "francés (Canadá)",
  "fr_CD": "francés (República Democrática del Congo)",
  "fr_CF": "francés (República Centroafricana)",
  "fr_CG": "francés (República del Congo)",
  "fr_CH": "francés (Suiza)",
  "fr_CI": "francés (Costa de Marfil)",
  "fr_CM": "francés (Camerún)",
  "fr_DJ": "francés (Yibuti)",
  "fr_DZ": "francés (Argelia)",
  "fr_FR": "francés (Francia)",
  "fr_GA": "francés (Gabón)",
  "fr_GF": "francés (Guayana Francesa)",
  "fr_GN": "francés (Guinea)",
  "fr_GP": "francés (Guadalupe)",
  "fr_GQ": "francés (Guinea Ecuatorial)",
  "fr_HT": "francés (Haití)",
  "fr_KM": "francés (Comoras)",
  "fr_LU": "francés (Luxemburgo)",
  "fr_MA": "francés (Marruecos)",
  "fr_MC": "francés (Mónaco)",
  "fr_MF": "francés (San Martín)",
  "fr_MG": "francés (Madagascar)",
  "fr_ML": "francés (Mali)",
  "fr_MQ": "francés (Martinica)",
  "fr_MR": "francés (Mauritania)",
  "fr_MU": "francés (Mauricio)",
  "fr_NC": "francés (Nueva Caledonia)",
  "fr_NE": "francés (Níger)",
  "fr_PF": "francés (Polinesia Francesa)",
  "fr_PM": "francés (San Pedro y Miquelón)",
  "fr_RE": "francés (Reunión)",
  "fr_RW": "francés (Ruanda)",
  "fr_SC": "francés (Seychelles)",
  "fr_SN": "francés (Senegal)",
  "fr_SY": "francés (Siria)",
  "fr_TD": "francés (Chad)",
  "fr_TG": "francés (Togo)",
  "fr_TN": "francés (Túnez)",
  "fr_VU": "francés (Vanuatu)",
  "fr_WF": "francés (Wallis y Futuna)",
  "fr_YT": "francés (Mayotte)",
  "frc": "francés cajún",
  "frm": "francés medio",
  "fro": "francés antiguo",
  "frp": "Arpitan",
  "frr": "frisón septentrional",
  "frs": "frisón oriental",
  "fur": "friulano",
  "fy": "frisón occidental",
  "fy_NL": "frisón occidental (Países Bajos)",
  "ga": "irlandés",
  "ga_IE": "irlandés (Irlanda)",
  "gaa": "ga",
  "gag": "gagauzo",
  "gan": "chino gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "gaélico escocés",
  "gd_GB": "gaélico escocés (Reino Unido)",
  "gem": "lengua germánica",
  "gez": "geez",
  "gil": "gilbertés",
  "gl": "gallego",
  "gl_ES": "gallego (España)",
  "glk": "Gilaki",
  "gmh": "alto alemán medio",
  "gn": "guaraní",
  "goh": "alto alemán antiguo",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gótico",
  "grb": "grebo",
  "grc": "griego antiguo",
  "gsw": "alemán suizo",
  "gu": "guyaratí",
  "gu_IN": "gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusii",
  "gv": "manés",
  "gv_IM": "gaélico manés (Isla de Man)",
  "gwi": "kutchin",
  "ha": "hausa",
  "ha_GH": "hausa (Ghana)",
  "ha_Latn": "hausa (latín)",
  "ha_Latn_GH": "hausa (latín, Ghana)",
  "ha_Latn_NE": "hausa (latín, Níger)",
  "ha_Latn_NG": "hausa (latín, Nigeria)",
  "ha_NE": "hausa (Níger)",
  "ha_NG": "hausa (Nigeria)",
  "hai": "haida",
  "hak": "chino hakka",
  "haw": "hawaiano",
  "he": "hebreo",
  "he_IL": "hebreo (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "him": "himachali",
  "hit": "hitita",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croata",
  "hr_BA": "croata (Bosnia-Herzegovina)",
  "hr_HR": "croata (Croacia)",
  "hsb": "alto sorbio",
  "hsn": "chino xiang",
  "ht": "criollo haitiano",
  "hu": "húngaro",
  "hu_HU": "húngaro (Hungría)",
  "hup": "hupa",
  "hy": "armenio",
  "hy_AM": "armenio (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonesio",
  "id_ID": "indonesio (Indonesia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigeria)",
  "ii": "yi de Sichuán",
  "ii_CN": "yi de Sichuán (China)",
  "ijo": "ijo",
  "ik": "inupiaq",
  "ilo": "ilocano",
  "inc": "lengua índica",
  "ine": "lengua indoeuropea",
  "inh": "ingush",
  "io": "ido",
  "ira": "lengua irania",
  "iro": "lenguas iroquesas",
  "is": "islandés",
  "is_IS": "islandés (Islandia)",
  "it": "italiano",
  "it_CH": "italiano (Suiza)",
  "it_IT": "italiano (Italia)",
  "it_SM": "italiano (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "japonés",
  "ja_JP": "japonés (Japón)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "judeo-persa",
  "jrb": "judeo-árabe",
  "jut": "Jutish",
  "jv": "javanés",
  "ka": "georgiano",
  "ka_GE": "georgiano (Georgia)",
  "kaa": "karakalpako",
  "kab": "cabila",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "kabardiano",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "criollo caboverdiano",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "Kaingang",
  "kha": "khasi",
  "khi": "lengua joisana",
  "kho": "kotanés",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenia)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "kazajo",
  "kk_Cyrl": "kazajo (cirílico)",
  "kk_Cyrl_KZ": "kazajo (cirílico, Kazajistán)",
  "kk_KZ": "kazajo (Kazajistán)",
  "kkj": "kako",
  "kl": "groenlandés",
  "kl_GL": "groenlandés (Groenlandia)",
  "kln": "kalenjin",
  "km": "jemer",
  "km_KH": "jemer (Camboya)",
  "kmb": "kimbundu",
  "kn": "canarés",
  "kn_IN": "canarés (India)",
  "ko": "coreano",
  "ko_KP": "coreano (Corea del Norte)",
  "ko_KR": "coreano (Corea del Sur)",
  "koi": "komi permio",
  "kok": "konkaní",
  "kos": "kosraeano",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karachay-balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "carelio",
  "kro": "kru",
  "kru": "kurukh",
  "ks": "cachemiro",
  "ks_Arab": "cachemiro (árabe)",
  "ks_Arab_IN": "cachemiro (árabe, India)",
  "ks_IN": "cachemiro (India)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kölsch",
  "ku": "kurdo",
  "kum": "kumyk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "córnico",
  "kw_GB": "córnico (Reino Unido)",
  "ky": "kirguís",
  "ky_Cyrl": "kirguís (cirílico)",
  "ky_Cyrl_KG": "kirguís (cirílico, Kirguistán)",
  "ky_KG": "kirguís (Kirguistán)",
  "la": "latín",
  "lad": "ladino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxemburgués",
  "lb_LU": "luxemburgués (Luxemburgo)",
  "lez": "lezgiano",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgués",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (República Democrática del Congo)",
  "ln_CF": "lingala (República Centroafricana)",
  "ln_CG": "lingala (República del Congo)",
  "lo": "lao",
  "lo_LA": "laosiano (Laos)",
  "lol": "mongo",
  "lou": "criollo de Luisiana",
  "loz": "lozi",
  "lrc": "lorí septentrional",
  "lt": "lituano",
  "lt_LT": "lituano (Lituania)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (República Democrática del Congo)",
  "lua": "luba-lulua",
  "lui": "luiseño",
  "lun": "lunda",
  "luo": "luo",
  "lus": "mizo",
  "luy": "luyia",
  "lv": "letón",
  "lv_LV": "letón (Letonia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "madurés",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "macasar",
  "man": "mandingo",
  "map": "lengua austronesia",
  "mas": "masái",
  "mde": "maba",
  "mdf": "moksha",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "criollo mauriciano",
  "mg": "malgache",
  "mg_MG": "malgache (Madagascar)",
  "mga": "irlandés medio",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshalés",
  "mi": "maorí",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "lenguas varias",
  "mk": "macedonio",
  "mk_MK": "macedonio (Macedonia)",
  "mkh": "lengua mon-jemer",
  "ml": "malayalam",
  "ml_IN": "malayalam (India)",
  "mn": "mongol",
  "mn_Cyrl": "mongol (cirílico)",
  "mn_Cyrl_MN": "mongol (cirílico, Mongolia)",
  "mn_MN": "mongol (Mongolia)",
  "mnc": "manchú",
  "mni": "manipuri",
  "mno": "lenguas manobo",
  "mo": "moldavo",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "maratí",
  "mr_IN": "marathi (India)",
  "mrj": "Western Mari",
  "ms": "malayo",
  "ms_BN": "malayo (Brunéi)",
  "ms_Latn": "malayo (latín)",
  "ms_Latn_BN": "malayo (latín, Brunéi)",
  "ms_Latn_MY": "malayo (latín, Malasia)",
  "ms_Latn_SG": "malayo (latín, Singapur)",
  "ms_MY": "malayo (Malasia)",
  "ms_SG": "malayo (Singapur)",
  "mt": "maltés",
  "mt_MT": "maltés (Malta)",
  "mua": "mundang",
  "mul": "varios idiomas",
  "mun": "lenguas munda",
  "mus": "creek",
  "mwl": "mirandés",
  "mwr": "marwari",
  "mwv": "Mentawai",
  "my": "birmano",
  "my_MM": "birmano (Myanmar (Birmania))",
  "mye": "myene",
  "myn": "maya",
  "myv": "erzya",
  "mzn": "mazandaraní",
  "na": "nauruano",
  "nah": "náhuatl",
  "nai": "lengua india norteamericana",
  "nan": "chino min nan",
  "nap": "napolitano",
  "naq": "nama",
  "nb": "noruego bokmal",
  "nb_NO": "bokmal noruego (Noruega)",
  "nb_SJ": "bokmal noruego (Svalbard y Jan Mayen)",
  "nd": "ndebele septentrional",
  "nd_ZW": "ndebele septentrional (Zimbabue)",
  "nds": "bajo alemán",
  "nds_NL": "bajo sajón",
  "ne": "nepalí",
  "ne_IN": "nepalí (India)",
  "ne_NP": "nepalí (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "lengua níger-cordofana",
  "niu": "niueano",
  "njo": "Ao Naga",
  "nl": "neerlandés",
  "nl_AW": "neerlandés (Aruba)",
  "nl_BE": "neerlandés (Bélgica)",
  "nl_BQ": "neerlandés (Caribe neerlandés)",
  "nl_CW": "neerlandés (Curazao)",
  "nl_NL": "neerlandés (Países Bajos)",
  "nl_SR": "neerlandés (Surinam)",
  "nl_SX": "neerlandés (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "noruego nynorsk",
  "nn_NO": "nynorsk noruego (Noruega)",
  "nnh": "ngiemboon",
  "no": "noruego",
  "no_NO": "noruego (Noruega)",
  "nog": "nogai",
  "non": "nórdico antiguo",
  "nov": "Novial",
  "nqo": "n’ko",
  "nr": "ndebele meridional",
  "nso": "sotho septentrional",
  "nub": "lenguas nubias",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "newari clásico",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "occitano",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiopía)",
  "om_KE": "oromo (Kenia)",
  "or": "oriya",
  "or_IN": "oriya (India)",
  "os": "osético",
  "os_GE": "osético (Georgia)",
  "os_RU": "osético (Rusia)",
  "osa": "osage",
  "ota": "turco otomano",
  "oto": "lenguas otomanas",
  "pa": "punyabí",
  "pa_Arab": "punjabí (árabe)",
  "pa_Arab_PK": "punjabí (árabe, Pakistán)",
  "pa_Guru": "punjabí (gurmuji)",
  "pa_Guru_IN": "punjabí (gurmuji, India)",
  "pa_IN": "punjabí (India)",
  "pa_PK": "punjabí (Pakistán)",
  "paa": "lengua papú",
  "pag": "pangasinán",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palauano",
  "pcd": "Picard",
  "pcm": "pidgin de Nigeria",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "persa antiguo",
  "pfl": "Palatine German",
  "phi": "lengua filipina",
  "phn": "fenicio",
  "pi": "pali",
  "pl": "polaco",
  "pl_PL": "polaco (Polonia)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "pohnpeiano",
  "pra": "lenguas prácritas",
  "prg": "prusiano",
  "pro": "provenzal antiguo",
  "ps": "pastún",
  "ps_AF": "pastún (Afganistán)",
  "pt": "portugués",
  "pt_AO": "portugués (Angola)",
  "pt_BR": "portugués (Brasil)",
  "pt_CV": "portugués (Cabo Verde)",
  "pt_GW": "portugués (Guinea-Bisáu)",
  "pt_MO": "portugués (RAE de Macao (China))",
  "pt_MZ": "portugués (Mozambique)",
  "pt_PT": "portugués (Portugal)",
  "pt_ST": "portugués (Santo Tomé y Príncipe)",
  "pt_TL": "portugués (Timor Oriental)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivia)",
  "qu_EC": "quechua (Ecuador)",
  "qu_PE": "quechua (Perú)",
  "quc": "quiché",
  "qug": "Chimborazo Highland Quichua",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotongano",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "romanche",
  "rm_CH": "retorrománico (Suiza)",
  "rn": "kirundi",
  "rn_BI": "kiroundi (Burundi)",
  "ro": "rumano",
  "ro_MD": "rumano (Moldavia)",
  "ro_RO": "rumano (Rumanía)",
  "roa": "lengua romance",
  "rof": "rombo",
  "rom": "romaní",
  "root": "raíz",
  "rtm": "Rotuman",
  "ru": "ruso",
  "ru_BY": "ruso (Bielorrusia)",
  "ru_KG": "ruso (Kirguistán)",
  "ru_KZ": "ruso (Kazajistán)",
  "ru_MD": "ruso (Moldavia)",
  "ru_RU": "ruso (Rusia)",
  "ru_UA": "ruso (Ucrania)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "arrumano",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Ruanda)",
  "rwk": "rwa",
  "sa": "sánscrito",
  "sad": "sandawe",
  "sah": "sakha",
  "sai": "lengua india sudamericana",
  "sal": "lenguas salish",
  "sam": "arameo samaritano",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardo",
  "scn": "siciliano",
  "sco": "escocés",
  "sd": "sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "kurdo meridional",
  "se": "sami septentrional",
  "se_FI": "sami septentrional (Finlandia)",
  "se_NO": "sami septentrional (Noruega)",
  "se_SE": "sami septentrional (Suecia)",
  "see": "seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "selkup",
  "sem": "lengua semítica",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (República Centroafricana)",
  "sga": "irlandés antiguo",
  "sgn": "lenguajes de signos",
  "sgs": "Samogitian",
  "sh": "serbocroata",
  "sh_BA": "serbocroata (Bosnia-Herzegovina)",
  "shi": "tashelhit",
  "shi_Latn": "Shilha (latín)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "shan",
  "shu": "árabe chadiano",
  "si": "cingalés",
  "si_LK": "cingalés (Sri Lanka)",
  "sid": "sidamo",
  "sio": "lenguas sioux",
  "sit": "lengua sino-tibetana",
  "sk": "eslovaco",
  "sk_SK": "eslovaco (Eslovaquia)",
  "sl": "esloveno",
  "sl_SI": "esloveno (Eslovenia)",
  "sla": "lengua eslava",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoano",
  "sma": "sami meridional",
  "smi": "lengua sami",
  "smj": "sami lule",
  "smn": "sami inari",
  "sms": "sami skolt",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabue)",
  "snk": "soninké",
  "so": "somalí",
  "so_DJ": "somalí (Yibuti)",
  "so_ET": "somalí (Etiopía)",
  "so_KE": "somalí (Kenia)",
  "so_SO": "somalí (Somalia)",
  "sog": "sogdiano",
  "son": "songhai",
  "sq": "albanés",
  "sq_AL": "albanés (Albania)",
  "sq_MK": "albanés (Macedonia)",
  "sq_XK": "albanés (Kosovo)",
  "sr": "serbio",
  "sr_BA": "serbio (Bosnia-Herzegovina)",
  "sr_Cyrl": "serbio (cirílico)",
  "sr_Cyrl_BA": "serbio (cirílico, Bosnia-Herzegovina)",
  "sr_Cyrl_ME": "serbio (cirílico, Montenegro)",
  "sr_Cyrl_RS": "serbio (cirílico, Serbia)",
  "sr_Cyrl_XK": "serbio (cirílico, Kosovo)",
  "sr_Latn": "serbio (latín)",
  "sr_Latn_BA": "serbio (latín, Bosnia-Herzegovina)",
  "sr_Latn_ME": "serbio (latín, Montenegro)",
  "sr_Latn_RS": "serbio (latín, Serbia)",
  "sr_Latn_XK": "serbio (latín, Kosovo)",
  "sr_ME": "serbio (Montenegro)",
  "sr_RS": "serbio (Serbia)",
  "sr_XK": "serbio (Kosovo)",
  "srn": "sranan tongo",
  "srr": "serer",
  "ss": "suazi",
  "ssa": "lengua nilo-sahariana",
  "ssy": "saho",
  "st": "sotho meridional",
  "stq": "Saterland Frisian",
  "su": "sundanés",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumerio",
  "sv": "sueco",
  "sv_AX": "sueco (Islas Åland)",
  "sv_FI": "sueco (Finlandia)",
  "sv_SE": "sueco (Suecia)",
  "sw": "suajili",
  "sw_CD": "suajili del Congo",
  "sw_KE": "swahili (Kenia)",
  "sw_TZ": "swahili (Tanzania)",
  "sw_UG": "swahili (Uganda)",
  "swb": "comorense",
  "swc": "swahili del Congo",
  "syc": "siríaco clásico",
  "syr": "siriaco",
  "szl": "Silesian",
  "ta": "tamil",
  "ta_IN": "tamil (India)",
  "ta_LK": "tamil (Sri Lanka)",
  "ta_MY": "tamil (Malasia)",
  "ta_SG": "tamil (Singapur)",
  "tai": "lengua tai",
  "tcy": "Tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tetún",
  "tg": "tayiko",
  "th": "tailandés",
  "th_TH": "tailandés (Tailandia)",
  "ti": "tigriña",
  "ti_ER": "tigriña (Eritrea)",
  "ti_ET": "tigriña (Etiopía)",
  "tig": "tigré",
  "tiv": "tiv",
  "tk": "turcomano",
  "tkl": "tokelauano",
  "tkr": "Tsakhur",
  "tl": "tagalo",
  "tl_PH": "tagalo (Filipinas)",
  "tlh": "klingon",
  "tli": "tlingit",
  "tly": "Talysh",
  "tmh": "tamashek",
  "tn": "setsuana",
  "to": "tongano",
  "to_TO": "tongano (Tonga)",
  "tog": "tonga del Nyasa",
  "tpi": "tok pisin",
  "tr": "turco",
  "tr_CY": "turco (Chipre)",
  "tr_TR": "turco (Turquía)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshiano",
  "tt": "tártaro",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tup": "lenguas tupí",
  "tut": "lengua altaica",
  "tvl": "tuvaluano",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitiano",
  "tyv": "tuviniano",
  "tzm": "tamazight del Atlas Central",
  "udm": "udmurt",
  "ug": "uigur",
  "ug_Arab": "uigur (árabe)",
  "ug_Arab_CN": "uigur (árabe, China)",
  "ug_CN": "uigur (China)",
  "uga": "ugarítico",
  "uk": "ucraniano",
  "uk_UA": "ucraniano (Ucrania)",
  "umb": "umbundu",
  "und": "lengua desconocida",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakistán)",
  "uz": "uzbeko",
  "uz_AF": "uzbeko (Afganistán)",
  "uz_Arab": "uzbeko (árabe)",
  "uz_Arab_AF": "uzbeko (árabe, Afganistán)",
  "uz_Cyrl": "uzbeko (cirílico)",
  "uz_Cyrl_UZ": "uzbeko (cirílico, Uzbekistán)",
  "uz_Latn": "uzbeko (latín)",
  "uz_Latn_UZ": "uzbeko (latín, Uzbekistán)",
  "uz_UZ": "uzbeko (Uzbekistán)",
  "vai": "vai",
  "vai_Latn": "Vai (latín)",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnamita",
  "vi_VN": "vietnamita (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapük",
  "vot": "vótico",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "valón",
  "wae": "walser",
  "wak": "lenguas wakasha",
  "wal": "wolayta",
  "war": "waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wen": "lenguas sorbias",
  "wo": "wólof",
  "wuu": "chino wu",
  "xal": "kalmyk",
  "xh": "xhosa",
  "xmf": "Mingrelian",
  "xog": "soga",
  "yao": "yao",
  "yap": "yapés",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "yidis",
  "yo": "yoruba",
  "yo_BJ": "yoruba (Benín)",
  "yo_NG": "yoruba (Nigeria)",
  "ypk": "lenguas yupik",
  "yrl": "Nheengatu",
  "yue": "cantonés",
  "yue_Hans": "Cantonés (chino simplificado)",
  "yue_Hant": "Cantonés (chino tradicional)",
  "za": "zhuang",
  "zap": "zapoteco",
  "zbl": "símbolos Bliss",
  "zea": "Zeelandic",
  "zen": "zenaga",
  "zgh": "tamazight estándar marroquí",
  "zh": "chino",
  "zh_CN": "chino (China)",
  "zh_HK": "chino (RAE de Hong Kong (China))",
  "zh_Hans": "chino (simplificado)",
  "zh_Hans_CN": "chino (simplificado, China)",
  "zh_Hans_HK": "chino (simplificado, RAE de Hong Kong (China))",
  "zh_Hans_MO": "chino (simplificado, RAE de Macao (China))",
  "zh_Hans_SG": "chino (simplificado, Singapur)",
  "zh_Hant": "chino (tradicional)",
  "zh_Hant_HK": "chino (tradicional, RAE de Hong Kong (China))",
  "zh_Hant_MO": "chino (tradicional, RAE de Macao (China))",
  "zh_Hant_TW": "chino (tradicional, Taiwán)",
  "zh_MO": "chino (RAE de Macao (China))",
  "zh_SG": "chino (Singapur)",
  "zh_TW": "chino (Taiwán)",
  "znd": "zande",
  "zu": "zulú",
  "zu_ZA": "zulú (Sudáfrica)",
  "zun": "zuñi",
  "zxx": "sin contenido lingüístico",
  "zza": "zazaki"
};
