const names = {
  "001": "বিশ্ব",
  "002": "আফ্ৰিকা",
  "003": "উত্তৰ আমেৰিকা",
  "005": "দক্ষিণ আমেৰিকা",
  "009": "অ’চেনীয়া",
  "011": "পাশ্চাত্য আফ্ৰিকা",
  "013": "মধ্য আমেৰিকা",
  "014": "প্ৰাচ্য আফ্ৰিকা",
  "015": "উদীচ্য আফ্ৰিকা",
  "017": "মধ্য আফ্ৰিকা",
  "018": "দাক্ষিণাত্য আফ্ৰিকা",
  "019": "আমেৰিকাছ্",
  "021": "উদীচ্য আমেৰিকা",
  "029": "কেৰিবিয়ান",
  "030": "প্ৰাচ্য এছিয়া",
  "034": "দাক্ষিণাত্য এছিয়া",
  "035": "দক্ষিণ-পূব এছিয়া",
  "039": "দাক্ষিণাত্য ইউৰোপ",
  "053": "অষ্ট্ৰেলেছিয়া",
  "054": "মেলানেছিয়া",
  "057": "মাইক্ৰোনেচিয় ক্ষেত্ৰ",
  "061": "পলিনেচিয়া",
  "142": "এছিয়া",
  "143": "মধ্য এছিয়া",
  "145": "পাশ্চাত্য এছিয়া",
  "150": "ইউৰোপ",
  "151": "প্ৰাচ্য ইউৰোপ",
  "154": "উদীচ্য ইউৰোপ",
  "155": "পাশ্চাত্য ইউৰোপ",
  "202": "উপ-ছাহাৰান আফ্ৰিকা",
  "419": "লেটিন আমেৰিকা",
  "AC": "এচেনচিয়ন দ্বীপ",
  "AD": "আন্দোৰা",
  "AE": "সংযুক্ত আৰব আমিৰাত",
  "AF": "আফগানিস্তান",
  "AG": "এণ্টিগুৱা আৰু বাৰ্বুডা",
  "AI": "এনগুইলা",
  "AL": "আলবেনিয়া",
  "AM": "আৰ্মেনিয়া",
  "AO": "এংগোলা",
  "AQ": "এণ্টাৰ্কটিকা",
  "AR": "আৰ্জেণ্টিনা",
  "AS": "আমেৰিকান চামোৱা",
  "AT": "অষ্ট্ৰিয়া",
  "AU": "অষ্ট্ৰেলিয়া",
  "AW": "আৰুবা",
  "AX": "আলণ্ড দ্বীপপুঞ্জ",
  "AZ": "আজাৰবেইজান",
  "Arab": "আৰবী",
  "Armn": "আৰ্মেনীয়",
  "BA": "ব’ছনিয়া আৰু হাৰ্জেগ’ভিনা",
  "BB": "বাৰ্বাডোচ",
  "BD": "বাংলাদেশ",
  "BE": "বেলজিয়াম",
  "BF": "বুৰকিনা ফাচো",
  "BG": "বুলগেৰিয়া",
  "BH": "বাহৰেইন",
  "BI": "বুৰুণ্ডি",
  "BJ": "বেনিন",
  "BL": "ছেইণ্ট বাৰ্থলেমে",
  "BM": "বাৰ্মুডা",
  "BN": "ব্ৰুনেই",
  "BO": "বলিভিয়া",
  "BQ": "কেৰিবিয়ান নেদাৰলেণ্ডছ",
  "BR": "ব্ৰাজিল",
  "BS": "বাহামাছ",
  "BT": "ভুটান",
  "BV": "বুভে দ্বীপ",
  "BW": "ব’টচোৱানা",
  "BY": "বেলাৰুছ",
  "BZ": "বেলিজ",
  "Beng": "বাংলা",
  "Bopo": "বোপোমোফো",
  "Brai": "ব্ৰেইল",
  "CA": "কানাডা",
  "CC": "কোকোচ (কীলিং) দ্বীপপুঞ্জ",
  "CD": "কঙ্গো - কিনচাছা",
  "CF": "মধ্য আফ্রিকান প্রজাতন্ত্র",
  "CG": "কঙ্গো - ব্রাজাভিল",
  "CH": "চুইজাৰলেণ্ড",
  "CI": "কোটে ডি আইভৰ",
  "CK": "কুক দ্বীপপুঞ্জ",
  "CL": "চিলি",
  "CM": "কেমেৰুণ",
  "CN": "চীন",
  "CO": "কলম্বিয়া",
  "CP": "ক্লিপাৰটোন দ্বীপ",
  "CR": "কোষ্টা ৰিকা",
  "CU": "কিউবা",
  "CV": "কেপ ভার্দে",
  "CW": "কুৰাকাও",
  "CX": "খ্ৰীষ্টমাছ দ্বীপ",
  "CY": "চাইপ্ৰাছ",
  "CZ": "চিজেচিয়া",
  "Cyrl": "চিৰিলিক",
  "DE": "জাৰ্মানী",
  "DG": "ডিয়েগো গাৰ্চিয়া",
  "DJ": "জিবুটি",
  "DK": "ডেনমাৰ্ক",
  "DM": "ড’মিনিকা",
  "DO": "ড’মিনিকান ৰিপাব্লিক",
  "DZ": "আলজেৰিয়া",
  "Deva": "দেৱনাগৰী",
  "EA": "চেউটা আৰু মেলিলা",
  "EC": "ইকুৱেডৰ",
  "EE": "ইষ্টোনিয়া",
  "EG": "ইজিপ্ত",
  "EH": "পশ্চিমীয় ছাহাৰা",
  "ER": "এৰিত্ৰিয়া",
  "ES": "স্পেইন",
  "ET": "ইথিঅ’পিয়া",
  "EU": "ইউৰোপীয় সংঘ",
  "EZ": "ইউৰোজ’ন",
  "Ethi": "ইথিঅ’পিক",
  "FI": "ফিনলেণ্ড",
  "FJ": "ফিজি",
  "FK": "ফকলেণ্ড দ্বীপপুঞ্জ",
  "FM": "মাইক্ৰোনেচিয়া",
  "FO": "ফাৰো দ্বীপপুঞ্জ",
  "FR": "ফ্ৰান্স",
  "GA": "গেবন",
  "GB": "সংযুক্ত ৰাজ্য",
  "GD": "গ্ৰেনাডা",
  "GE": "জৰ্জিয়া",
  "GF": "ফ্ৰান্স গয়ানা",
  "GG": "গোৰেনচি",
  "GH": "ঘানা",
  "GI": "জিব্ৰাল্টৰ",
  "GL": "গ্ৰীণলেণ্ড",
  "GM": "গাম্বিয়া",
  "GN": "গিনি",
  "GP": "গুৱাডেলুপ",
  "GQ": "ইকুৱেটৰিয়েল গিনি",
  "GR": "গ্ৰীচ",
  "GS": "দক্ষিণ জৰ্জিয়া আৰু দক্ষিণ চেণ্ডৱিচ দ্বীপপুঞ্জ",
  "GT": "গুৱাটেমালা",
  "GU": "গুৱাম",
  "GW": "গিনি-বিছাও",
  "GY": "গায়ানা",
  "Geor": "জৰ্জিয়ান",
  "Grek": "গ্ৰীক",
  "Gujr": "গুজৰাটী",
  "Guru": "গুৰুমুখী",
  "HK": "হং কং এছ. এ. আৰ. চীন",
  "HM": "হাৰ্ড দ্বীপ আৰু মেকডোনাল্ড দ্বীপপুঞ্জ",
  "HN": "হন্দুৰাছ",
  "HR": "ক্ৰোৱেছিয়া",
  "HT": "হাইটি",
  "HU": "হাংগেৰী",
  "Hanb": "বোপোমোফোৰ সৈতে হান",
  "Hang": "হেঙ্গুল",
  "Hani": "হান",
  "Hans": "সৰলীকৃত",
  "Hant": "পৰম্পৰাগত",
  "Hebr": "হিব্ৰু",
  "Hira": "হিৰাগানা",
  "Hrkt": "জাপানী ছিলেবেৰিজ",
  "IC": "কেনেৰী দ্বীপপুঞ্জ",
  "ID": "ইণ্ডোনেচিয়া",
  "IE": "আয়াৰলেণ্ড",
  "IL": "ইজৰাইল",
  "IM": "আইল অফ মেন",
  "IN": "ভাৰত",
  "IO": "ব্ৰিটিছ ইণ্ডিয়ান অ’চন টেৰিট’ৰি",
  "IQ": "ইৰাক",
  "IR": "ইৰান",
  "IS": "আইচলেণ্ড",
  "IT": "ইটালি",
  "JE": "জাৰ্চি",
  "JM": "জামাইকা",
  "JO": "জৰ্ডান",
  "JP": "জাপান",
  "Jamo": "জামো",
  "Jpan": "জাপানী",
  "KE": "কেনিয়া",
  "KG": "কিৰ্গিজস্তান",
  "KH": "কম্বোডিয়া",
  "KI": "কিৰিবাটি",
  "KM": "কোমোৰোজ",
  "KN": "ছেইণ্ট কিটছ আৰু নেভিছ",
  "KP": "উত্তৰ কোৰিয়া",
  "KR": "দক্ষিণ কোৰিয়া",
  "KW": "কুৱেইট",
  "KY": "কেইমেন দ্বীপপুঞ্জ",
  "KZ": "কাজাখাস্তান",
  "Kana": "কাটাকানা",
  "Khmr": "খমেৰ",
  "Knda": "কানাড়া",
  "Kore": "কোৰিয়ান",
  "LA": "লাওচ",
  "LB": "লেবানন",
  "LC": "ছেইণ্ট লুচিয়া",
  "LI": "লিচটেনষ্টেইন",
  "LK": "শ্রীলংকা",
  "LR": "লিবেৰিয়া",
  "LS": "লেছ’থ’",
  "LT": "লিথুৱানিয়া",
  "LU": "লাক্সেমবাৰ্গ",
  "LV": "লাটভিয়া",
  "LY": "লিবিয়া",
  "Laoo": "লাও",
  "Latn": "লেটিন",
  "MA": "মৰক্কো",
  "MC": "মোনাকো",
  "MD": "মোলডোভা",
  "ME": "মণ্টেনেগ্ৰু",
  "MF": "ছেইণ্ট মাৰ্টিন",
  "MG": "মাদাগাস্কাৰ",
  "MH": "মাৰ্শ্বাল দ্বীপপুঞ্জ",
  "MK": "উত্তৰ মেচিডোনীয়া",
  "ML": "মালি",
  "MM": "ম্যানমাৰ (বাৰ্মা)",
  "MN": "মঙ্গোলিয়া",
  "MO": "মাকাও এছ. এ. আৰ. চীন",
  "MP": "উত্তৰ মাৰিয়ানা দ্বীপপুঞ্জ",
  "MQ": "মাৰ্টিনিক",
  "MR": "মাউৰিটানিয়া",
  "MS": "ম’ণ্টছেৰাট",
  "MT": "মাল্টা",
  "MU": "মৰিছাছ",
  "MV": "মালদ্বীপ",
  "MW": "মালাৱি",
  "MX": "মেক্সিকো",
  "MY": "মালয়েচিয়া",
  "MZ": "ম’জামবিক",
  "Mlym": "মালায়ালম",
  "Mong": "মঙ্গোলিয়",
  "Mymr": "ম্যানমাৰ",
  "NA": "নামিবিয়া",
  "NC": "নিউ কেলিডোনিয়া",
  "NE": "নাইজাৰ",
  "NF": "ন’ৰফ’ক দ্বীপ",
  "NG": "নাইজেৰিয়া",
  "NI": "নিকাৰাগুৱা",
  "NL": "নেডাৰলেণ্ড",
  "NO": "নৰৱে",
  "NP": "নেপাল",
  "NR": "নাউৰু",
  "NU": "নিউ",
  "NZ": "নিউজিলেণ্ড",
  "OM": "ওমান",
  "Orya": "ওড়িয়া",
  "PA": "পানামা",
  "PE": "পেৰু",
  "PF": "ফ্ৰান্স পোলেনচিয়া",
  "PG": "পাপুৱা নিউ গিনি",
  "PH": "ফিলিপাইনছ",
  "PK": "পাকিস্তান",
  "PL": "পোলেণ্ড",
  "PM": "ছেইণ্ট পিয়েৰে আৰু মিকিউৱেলন",
  "PN": "পিটকেইৰ্ণ দ্বীপপুঞ্জ",
  "PR": "পুৱেৰ্টো ৰিকো",
  "PS": "ফিলিস্তিন অঞ্চল",
  "PT": "পৰ্তুগাল",
  "PW": "পালাউ",
  "PY": "পাৰাগুৱে",
  "QA": "কাটাৰ",
  "QO": "আউটলায়িং অ’চিয়ানিয়া",
  "RE": "ৰিইউনিয়ন",
  "RO": "ৰোমানিয়া",
  "RS": "ছাৰ্বিয়া",
  "RU": "ৰাছিয়া",
  "RW": "ৰোৱাণ্ডা",
  "SA": "চৌডি আৰবিয়া",
  "SB": "চোলোমোন দ্বীপপুঞ্জ",
  "SC": "ছিচিলিছ",
  "SD": "চুডান",
  "SE": "চুইডেন",
  "SG": "ছিংগাপুৰ",
  "SH": "ছেইণ্ট হেলেনা",
  "SI": "শ্লোভেনিয়া",
  "SJ": "চাভালবাৰ্ড আৰু জন মেয়ন",
  "SK": "শ্লোভাকিয়া",
  "SL": "চিয়েৰা লিঅ’ন",
  "SM": "চান মাৰিনো",
  "SN": "চেনেগাল",
  "SO": "চোমালিয়া",
  "SR": "ছুৰিনাম",
  "SS": "দক্ষিণ চুডান",
  "ST": "চাও টোমে আৰু প্ৰিনচিপে",
  "SV": "এল ছেলভেড’ৰ",
  "SX": "চিণ্ট মাৰ্টেন",
  "SY": "চিৰিয়া",
  "SZ": "ইচ্চুটিনি",
  "Sinh": "সিংহলী",
  "TA": "ত্ৰিস্তান দ্যা কুনহা",
  "TC": "টাৰ্কছ অৰু কেইক’ছ দ্বীপপুঞ্জ",
  "TD": "চাড",
  "TF": "দক্ষিণ ফ্ৰান্সৰ অঞ্চল",
  "TG": "টোগো",
  "TH": "থাইলেণ্ড",
  "TJ": "তাজিকিস্তান",
  "TK": "টোকেলাউ",
  "TL": "টিমোৰ-লেচটে",
  "TM": "তুৰ্কমেনিস্তান",
  "TN": "টুনিচিয়া",
  "TO": "টংগা",
  "TR": "তুৰ্কি",
  "TT": "ট্ৰিনিডাড আৰু টোবাগো",
  "TV": "টুভালু",
  "TW": "টাইৱান",
  "TZ": "তাঞ্জানিয়া",
  "Taml": "তামিল",
  "Telu": "তেলুগু",
  "Thaa": "থানা",
  "Thai": "থাই",
  "Tibt": "তিব্বতী",
  "UA": "ইউক্ৰেইন",
  "UG": "উগাণ্ডা",
  "UM": "ইউ. এছ. আউটলায়িং দ্বীপপুঞ্জ",
  "UN": "ৰাষ্ট্ৰসংঘ",
  "US": "মাৰ্কিন যুক্তৰাষ্ট্ৰ",
  "UY": "উৰুগুৱে",
  "UZ": "উজবেকিস্তান",
  "VA": "ভেটিকান চিটি",
  "VC": "ছেইণ্ট ভিনচেণ্ট আৰু গ্ৰীণাডাইনছ",
  "VE": "ভেনিজুৱেলা",
  "VG": "ব্ৰিটিছ ভাৰ্জিন দ্বীপপুঞ্জ",
  "VI": "ইউ. এছ. ভাৰ্জিন দ্বীপপুঞ্জ",
  "VN": "ভিয়েটনাম",
  "VU": "ভানাটু",
  "WF": "ৱালিছ আৰু ফুটুনা",
  "WS": "চামোৱা",
  "XA": "ছুডু-একচেণ্ট",
  "XB": "ছুডু-বিডি",
  "XK": "কচ’ভ’",
  "YE": "য়েমেন",
  "YT": "মায়োট্টে",
  "ZA": "দক্ষিণ আফ্রিকা",
  "ZM": "জাম্বিয়া",
  "ZW": "জিম্বাবৱে",
  "ZZ": "অজ্ঞাত ক্ষেত্ৰ",
  "Zmth": "গাণিতিক চিহ্ন",
  "Zsye": "ইম’জি",
  "Zsym": "প্ৰতীক",
  "Zxxx": "অলিখিত",
  "Zyyy": "কোমোন",
  "Zzzz": "অজ্ঞাত লিপি",
  "aa": "আফাৰ",
  "ab": "আবখাজিয়ান",
  "ace": "আচিনিজ",
  "ach": "Acoli",
  "ada": "আদাংমে",
  "ady": "আদিগে",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "আফ্ৰিকানছ্",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "আঘেম",
  "ain": "আইনু",
  "ak": "আকান",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "আলেউট",
  "aln": "Gheg Albanian",
  "alt": "দাক্ষিণাত্য আল্টাই",
  "am": "আমহাৰিক",
  "am_ET": "Amharic (Ethiopia)",
  "an": "আৰ্গোনিজ",
  "ang": "Old English",
  "anp": "আঙ্গিকা",
  "ar": "আৰবী",
  "ar_001": "আধুনিক মানক আৰবী",
  "ar_AE": "Arabic (United Arab Emirates)",
  "ar_BH": "Arabic (Bahrain)",
  "ar_DJ": "Arabic (Djibouti)",
  "ar_DZ": "Arabic (Algeria)",
  "ar_EG": "Arabic (Egypt)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arabic (Eritrea)",
  "ar_IL": "Arabic (Israel)",
  "ar_IQ": "Arabic (Iraq)",
  "ar_JO": "Arabic (Jordan)",
  "ar_KM": "Arabic (Comoros)",
  "ar_KW": "Arabic (Kuwait)",
  "ar_LB": "Arabic (Lebanon)",
  "ar_LY": "Arabic (Libya)",
  "ar_MA": "Arabic (Morocco)",
  "ar_MR": "Arabic (Mauritania)",
  "ar_OM": "Arabic (Oman)",
  "ar_PS": "Arabic (Palestinian Territories)",
  "ar_QA": "Arabic (Qatar)",
  "ar_SA": "Arabic (Saudi Arabia)",
  "ar_SD": "Arabic (Sudan)",
  "ar_SO": "Arabic (Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Arabic (Syria)",
  "ar_TD": "Arabic (Chad)",
  "ar_TN": "Arabic (Tunisia)",
  "ar_YE": "Arabic (Yemen)",
  "arc": "Aramaic",
  "arn": "মাপুচে",
  "aro": "Araona",
  "arp": "আৰাপাহো",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "অসমীয়া",
  "as_IN": "অসমীয়া (ভাৰত)",
  "asa": "আছু",
  "ase": "American Sign Language",
  "ast": "এষ্টুৰীয়",
  "av": "আভেৰিক",
  "avk": "Kotava",
  "awa": "আৱাধি",
  "ay": "আয়মাৰা",
  "az": "আজেৰবাইজানী",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "বাছখিৰ",
  "bal": "Baluchi",
  "ban": "বালিনীজ",
  "bar": "Bavarian",
  "bas": "বাছা",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "বেলাৰুছীয়",
  "be_BY": "Belarusian (Belarus)",
  "bej": "Beja",
  "bem": "বেম্বা",
  "bew": "Betawi",
  "bez": "বেনা",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "বুলগেৰীয়",
  "bg_BG": "Bulgarian (Bulgaria)",
  "bho": "ভোজপুৰী",
  "bi": "বিছলামা",
  "bik": "Bikol",
  "bin": "বিনি",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "ছিক্সিকা",
  "bm": "বামবাৰা",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "বাংলা",
  "bn_BD": "Bengali (Bangladesh)",
  "bn_IN": "Bengali (India)",
  "bo": "তিব্বতী",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "ব্ৰেটন",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "বড়ো",
  "bs": "বছনীয়",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "বগিনীজ",
  "bum": "Bulu",
  "byn": "ব্লিন",
  "byv": "Medumba",
  "ca": "কাতালান",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "চাক্‌মা",
  "ce": "চেচেন",
  "ceb": "চিবুৱানো",
  "cgg": "চিগা",
  "ch": "চামোৰো",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "চুকিজ",
  "chm": "মাৰি",
  "chn": "Chinook Jargon",
  "cho": "চোক্টাউ",
  "chp": "Chipewyan",
  "chr": "চেৰোকি",
  "chy": "চাইয়েন",
  "ckb": "চেণ্ট্ৰেল কুৰ্ডিচ",
  "co": "কোৰ্ছিকান",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "crs": "ছেছেলৱা ক্ৰিওল ফ্ৰেন্স",
  "cs": "চেক",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "চাৰ্চ শ্লেভিক",
  "cv": "চুভাচ",
  "cy": "ৱেলচ",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "ডেনিচ",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "ডাকোটা",
  "dar": "দাৰ্গৱা",
  "dav": "তেইতা",
  "de": "জাৰ্মান",
  "de_AT": "অষ্ট্ৰেলিয়ান জাৰ্মান",
  "de_BE": "German (Belgium)",
  "de_CH": "ছুইচ হাই জাৰ্মান",
  "de_DE": "German (Germany)",
  "de_LI": "German (Liechtenstein)",
  "de_LU": "German (Luxembourg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "ডোগ্ৰিব",
  "din": "Dinka",
  "dje": "ঝাৰ্মা",
  "doi": "Dogri",
  "dsb": "ল’ৱাৰ ছোৰ্বিয়ান",
  "dtp": "Central Dusun",
  "dua": "ডুৱালা",
  "dum": "Middle Dutch",
  "dv": "দিবেহি",
  "dyo": "জোলা-ফ’নি",
  "dyu": "Dyula",
  "dz": "জোংখা",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "দাজাগা",
  "ebu": "এম্বু",
  "ee": "ইৱে",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "এফিক",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "একাজুক",
  "el": "গ্ৰীক",
  "el_CY": "Greek (Cyprus)",
  "el_GR": "Greek (Greece)",
  "elx": "Elamite",
  "en": "ইংৰাজী",
  "en_AG": "English (Antigua & Barbuda)",
  "en_AI": "English (Anguilla)",
  "en_AS": "English (American Samoa)",
  "en_AU": "অষ্ট্ৰেলিয়ান ইংৰাজী",
  "en_BB": "English (Barbados)",
  "en_BE": "English (Belgium)",
  "en_BM": "English (Bermuda)",
  "en_BS": "English (Bahamas)",
  "en_BW": "English (Botswana)",
  "en_BZ": "English (Belize)",
  "en_CA": "কানাডিয়ান ইংৰাজী",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "English (Cook Islands)",
  "en_CM": "English (Cameroon)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "English (Dominica)",
  "en_ER": "English (Eritrea)",
  "en_FJ": "English (Fiji)",
  "en_FK": "English (Falkland Islands)",
  "en_FM": "English (Micronesia)",
  "en_GB": "ব্ৰিটিছ ইংৰাজী",
  "en_GD": "English (Grenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "English (Ghana)",
  "en_GI": "English (Gibraltar)",
  "en_GM": "English (Gambia)",
  "en_GU": "English (Guam)",
  "en_GY": "English (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "English (Ireland)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "English (India)",
  "en_IO": "English (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "English (Jamaica)",
  "en_KE": "English (Kenya)",
  "en_KI": "English (Kiribati)",
  "en_KN": "English (St. Kitts & Nevis)",
  "en_KY": "English (Cayman Islands)",
  "en_LC": "English (St. Lucia)",
  "en_LR": "English (Liberia)",
  "en_LS": "English (Lesotho)",
  "en_MG": "English (Madagascar)",
  "en_MH": "English (Marshall Islands)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "English (Northern Mariana Islands)",
  "en_MS": "English (Montserrat)",
  "en_MT": "English (Malta)",
  "en_MU": "English (Mauritius)",
  "en_MW": "English (Malawi)",
  "en_MY": "English (Malaysia)",
  "en_NA": "English (Namibia)",
  "en_NF": "English (Norfolk Island)",
  "en_NG": "English (Nigeria)",
  "en_NR": "English (Nauru)",
  "en_NU": "English (Niue)",
  "en_NZ": "English (New Zealand)",
  "en_PG": "English (Papua New Guinea)",
  "en_PH": "English (Philippines)",
  "en_PK": "English (Pakistan)",
  "en_PN": "English (Pitcairn Islands)",
  "en_PR": "English (Puerto Rico)",
  "en_PW": "English (Palau)",
  "en_RW": "English (Rwanda)",
  "en_SB": "English (Solomon Islands)",
  "en_SC": "English (Seychelles)",
  "en_SD": "English (Sudan)",
  "en_SG": "English (Singapore)",
  "en_SH": "English (St. Helena)",
  "en_SL": "English (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "English (Swaziland)",
  "en_TC": "English (Turks & Caicos Islands)",
  "en_TK": "English (Tokelau)",
  "en_TO": "English (Tonga)",
  "en_TT": "English (Trinidad & Tobago)",
  "en_TV": "English (Tuvalu)",
  "en_TZ": "English (Tanzania)",
  "en_UG": "English (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "আমেৰিকান ইংৰাজী",
  "en_VC": "English (St. Vincent & Grenadines)",
  "en_VG": "English (British Virgin Islands)",
  "en_VI": "English (U.S. Virgin Islands)",
  "en_VU": "English (Vanuatu)",
  "en_WS": "English (Samoa)",
  "en_ZA": "English (South Africa)",
  "en_ZM": "English (Zambia)",
  "en_ZW": "English (Zimbabwe)",
  "enm": "Middle English",
  "eo": "এস্পেৰান্তো",
  "es": "স্পেনিচ",
  "es_419": "লেটিন আমেৰিকান স্পেনিচ",
  "es_AR": "Spanish (Argentina)",
  "es_BO": "Spanish (Bolivia)",
  "es_CL": "Spanish (Chile)",
  "es_CO": "Spanish (Colombia)",
  "es_CR": "Spanish (Costa Rica)",
  "es_CU": "Spanish (Cuba)",
  "es_DO": "Spanish (Dominican Republic)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Spanish (Ecuador)",
  "es_ES": "ইউৰোপীয়ান স্পেনিচ",
  "es_GQ": "Spanish (Equatorial Guinea)",
  "es_GT": "Spanish (Guatemala)",
  "es_HN": "Spanish (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "মেক্সিকান স্পেনিচ",
  "es_NI": "Spanish (Nicaragua)",
  "es_PA": "Spanish (Panama)",
  "es_PE": "Spanish (Peru)",
  "es_PH": "Spanish (Philippines)",
  "es_PR": "Spanish (Puerto Rico)",
  "es_PY": "Spanish (Paraguay)",
  "es_SV": "Spanish (El Salvador)",
  "es_US": "Spanish (United States)",
  "es_UY": "Spanish (Uruguay)",
  "es_VE": "Spanish (Venezuela)",
  "esu": "Central Yupik",
  "et": "এষ্টোনিয়",
  "et_EE": "Estonian (Estonia)",
  "eu": "বাস্ক",
  "eu_ES": "Basque (Spain)",
  "ewo": "ইওন্দো",
  "ext": "Extremaduran",
  "fa": "ফাৰ্ছী",
  "fa_AF": "দাৰি",
  "fa_IR": "Persian (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "ফুলাহ",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "ফিনিচ",
  "fi_FI": "Finnish (Finland)",
  "fil": "ফিলিপিনো",
  "fit": "Tornedalen Finnish",
  "fj": "ফিজিয়ান",
  "fo": "ফাৰোইজ",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "ফ’ন",
  "fr": "ফ্ৰেন্স",
  "fr_BE": "French (Belgium)",
  "fr_BF": "French (Burkina Faso)",
  "fr_BI": "French (Burundi)",
  "fr_BJ": "French (Benin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "কানাডিয়ান ফ্ৰেন্স",
  "fr_CD": "French (Congo - Kinshasa)",
  "fr_CF": "French (Central African Republic)",
  "fr_CG": "French (Congo - Brazzaville)",
  "fr_CH": "ছুইচ ফ্ৰেন্স",
  "fr_CI": "French (Côte d’Ivoire)",
  "fr_CM": "French (Cameroon)",
  "fr_DJ": "French (Djibouti)",
  "fr_DZ": "French (Algeria)",
  "fr_FR": "French (France)",
  "fr_GA": "French (Gabon)",
  "fr_GF": "French (French Guiana)",
  "fr_GN": "French (Guinea)",
  "fr_GP": "French (Guadeloupe)",
  "fr_GQ": "French (Equatorial Guinea)",
  "fr_HT": "French (Haiti)",
  "fr_KM": "French (Comoros)",
  "fr_LU": "French (Luxembourg)",
  "fr_MA": "French (Morocco)",
  "fr_MC": "French (Monaco)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "French (Madagascar)",
  "fr_ML": "French (Mali)",
  "fr_MQ": "French (Martinique)",
  "fr_MR": "French (Mauritania)",
  "fr_MU": "French (Mauritius)",
  "fr_NC": "French (New Caledonia)",
  "fr_NE": "French (Niger)",
  "fr_PF": "French (French Polynesia)",
  "fr_PM": "French (St. Pierre & Miquelon)",
  "fr_RE": "French (Réunion)",
  "fr_RW": "French (Rwanda)",
  "fr_SC": "French (Seychelles)",
  "fr_SN": "French (Senegal)",
  "fr_SY": "French (Syria)",
  "fr_TD": "French (Chad)",
  "fr_TG": "French (Togo)",
  "fr_TN": "French (Tunisia)",
  "fr_VU": "French (Vanuatu)",
  "fr_WF": "French (Wallis & Futuna)",
  "fr_YT": "French (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "ফ্ৰিউলিয়ান",
  "fy": "ৱেষ্টাৰ্ণ ফ্ৰিছিয়ান",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "আইৰিচ",
  "ga_IE": "Irish (Ireland)",
  "gaa": "গা",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "স্কটিচ গেইলিক",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "গীজ",
  "gil": "গিলবাৰ্টিছ",
  "gl": "গেলিচিয়ান",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "গুৱাৰাণী",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "গোৰোন্তালো",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "ছুইচ জাৰ্মান",
  "gu": "গুজৰাটী",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "গুছি",
  "gv": "মেংক্স",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "জিউইচিন",
  "ha": "হাউছা",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "হাৱাই",
  "he": "হিব্ৰু",
  "he_IL": "Hebrew (Israel)",
  "hi": "হিন্দী",
  "hi_IN": "Hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "হিলিগায়নোন",
  "hit": "Hittite",
  "hmn": "হমং",
  "ho": "Hiri Motu",
  "hr": "ক্ৰোৱেচিয়ান",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "আপাৰ ছোৰ্বিয়ান",
  "hsn": "Xiang Chinese",
  "ht": "হেইটিয়ান ক্ৰিয়ল",
  "hu": "হাঙ্গেৰিয়ান",
  "hu_HU": "Hungarian (Hungary)",
  "hup": "হুপা",
  "hy": "আৰ্মেনীয়",
  "hy_AM": "Armenian (Armenia)",
  "hz": "হেৰেৰো",
  "ia": "ইণ্টাৰলিংগুৱা",
  "iba": "ইবান",
  "ibb": "ইবিবিও",
  "id": "ইণ্ডোনেচিয়",
  "id_ID": "Indonesian (Indonesia)",
  "ie": "উপস্থাপন ভাষা",
  "ig": "ইগ্বো",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "ছিচুৱান ই",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "ইলোকো",
  "inh": "ইংগুচ",
  "io": "ইডো",
  "is": "আইচলেণ্ডিক",
  "is_IS": "Icelandic (Iceland)",
  "it": "ইটালিয়ান",
  "it_CH": "Italian (Switzerland)",
  "it_IT": "Italian (Italy)",
  "it_SM": "Italian (San Marino)",
  "iu": "ইনুক্টিটুট",
  "izh": "Ingrian",
  "ja": "জাপানী",
  "ja_JP": "Japanese (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "লোজ্বান",
  "jgo": "নগোম্বা",
  "jmc": "মেকহেম",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "জাভানী",
  "ka": "জৰ্জিয়ান",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "কাবাইল",
  "kac": "কাচিন",
  "kaj": "জজু",
  "kam": "কাম্বা",
  "kaw": "Kawi",
  "kbd": "কাবাৰ্ডিয়ান",
  "kbl": "Kanembu",
  "kcg": "ত্যাপ",
  "kde": "মাকোণ্ড",
  "kea": "কাবুভেৰ্ডিয়ানু",
  "ken": "Kenyang",
  "kfo": "কোৰো",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "খাচি",
  "kho": "Khotanese",
  "khq": "কোয়াৰ চিনি",
  "khw": "Khowar",
  "ki": "কিকুয়ু",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "কুয়ানিয়ামা",
  "kk": "কাজাখ",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "কাকো",
  "kl": "কালালিছুট",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "কালেনজিন",
  "km": "খমেৰ",
  "km_KH": "Khmer (Cambodia)",
  "kmb": "কিম্বুন্দু",
  "kn": "কানাড়া",
  "kn_IN": "Kannada (India)",
  "ko": "কোৰিয়ান",
  "ko_KP": "Korean (North Korea)",
  "ko_KR": "Korean (South Korea)",
  "koi": "Komi-Permyak",
  "kok": "কোংকণী",
  "kos": "Kosraean",
  "kpe": "কেপেল",
  "kr": "কানুৰি",
  "krc": "কাৰাচে-বাল্কাৰ",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "কেৰেলিয়ান",
  "kru": "কুৰুখ",
  "ks": "কাশ্মিৰী",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "চাম্বালা",
  "ksf": "বাফিয়া",
  "ksh": "কোলোগনিয়ান",
  "ku": "কুৰ্ডিচ",
  "kum": "কুমিক",
  "kut": "Kutenai",
  "kv": "কোমি",
  "kw": "কোৰ্নিচ",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "কিৰ্গিজ",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "লেটিন",
  "lad": "লাডিনো",
  "lag": "লাংগি",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "লাক্সেমবাৰ্গিচ",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "লেজঘিয়ান",
  "lfn": "Lingua Franca Nova",
  "lg": "গান্দা",
  "lg_UG": "Ganda (Uganda)",
  "li": "লিম্বুৰ্গিচ",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "লাকোটা",
  "lmo": "Lombard",
  "ln": "লিংগালা",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "লাও",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "লোজি",
  "lrc": "উদীচ্য লুৰি",
  "lt": "লিথুৱানিয়ান",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "লুবা-কাটাংগা",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "লুবা-লুলুৱা",
  "lui": "Luiseno",
  "lun": "লুণ্ডা",
  "luo": "লুও",
  "lus": "মিজো",
  "luy": "লুইয়া",
  "lv": "লাটভিয়ান",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "মাদুৰেছে",
  "maf": "Mafa",
  "mag": "মাগাহি",
  "mai": "মৈথিলী",
  "mak": "মাকাছাৰ",
  "man": "Mandingo",
  "mas": "মাছাই",
  "mde": "Maba",
  "mdf": "মোক্সা",
  "mdr": "Mandar",
  "men": "মেণ্ডে",
  "mer": "মেৰু",
  "mfe": "মৰিছিয়ান",
  "mg": "মালাগাছী",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "মাখুৱা-মিট্টো",
  "mgo": "মেটা",
  "mh": "মাৰ্চলিজ",
  "mi": "মাওৰি",
  "mic": "মিকমেক",
  "min": "মিনাংকাবাউ",
  "mk": "মেচিডোনীয়",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "মালায়ালম",
  "ml_IN": "Malayalam (India)",
  "mn": "মংগোলীয়",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "মণিপুৰী",
  "moh": "মোহোক",
  "mos": "মোছি",
  "mr": "মাৰাঠী",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "মালয়",
  "ms_BN": "Malay (Brunei)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malay (Singapore)",
  "mt": "মাল্টিজ",
  "mt_MT": "Maltese (Malta)",
  "mua": "মুণ্ডাং",
  "mul": "একাধিক ভাষা",
  "mus": "ক্ৰীক",
  "mwl": "মিৰাণ্ডিজ",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "বাৰ্মীজ",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "Myene",
  "myv": "এৰজিয়া",
  "mzn": "মাজেন্দাৰানি",
  "na": "নাউৰু",
  "nan": "Min Nan Chinese",
  "nap": "নিয়াপোলিটেন",
  "naq": "নামা",
  "nb": "নৰৱেজিয়ান বোকমাল",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "উত্তৰ নিবেবেলে",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "ল’ জাৰ্মান",
  "ne": "নেপালী",
  "ne_IN": "Nepali (India)",
  "ne_NP": "Nepali (Nepal)",
  "new": "নেৱাৰি",
  "ng": "এন্দোঙ্গা",
  "nia": "নিয়াছ",
  "niu": "নিয়ুৱান",
  "njo": "Ao Naga",
  "nl": "ডাচ",
  "nl_AW": "Dutch (Aruba)",
  "nl_BE": "ফ্লেমিচ",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Dutch (Netherlands)",
  "nl_SR": "Dutch (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "কোৱাছিঅ’",
  "nn": "নৰৱেজিয়ান নায়নোৰ্স্ক",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "নিয়েম্বোন",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "নোগাই",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "এন্কো",
  "nr": "দক্ষিণ দেবেল",
  "nso": "উদীচ্য ছোথো",
  "nus": "নুয়েৰ",
  "nv": "নাভাজো",
  "nwc": "Classical Newari",
  "ny": "ন্যাঞ্জা",
  "nym": "Nyamwezi",
  "nyn": "ন্যানকোল",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "অ’চিটান",
  "oj": "Ojibwa",
  "om": "ওৰোমো",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "ওড়িয়া",
  "or_IN": "Oriya (India)",
  "os": "ওছেটিক",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "পাঞ্জাবী",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "pag": "পংগাছিনান",
  "pal": "Pahlavi",
  "pam": "পাম্পান্গা",
  "pap": "পাপিয়ামেণ্টো",
  "pau": "পালাউৱান",
  "pcd": "Picard",
  "pcm": "নাইজেৰিয়ান পিজিন",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "প’লিচ",
  "pl_PL": "Polish (Poland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "প্ৰুছিয়ান",
  "pro": "Old Provençal",
  "ps": "পুস্ত",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "পৰ্তুগীজ",
  "pt_AO": "Portuguese (Angola)",
  "pt_BR": "ব্ৰাজিলিয়ান পৰ্তুগীজ",
  "pt_CV": "Portuguese (Cape Verde)",
  "pt_GW": "Portuguese (Guinea-Bissau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Portuguese (Mozambique)",
  "pt_PT": "ইউৰোপীয়ান পৰ্তুগীজ",
  "pt_ST": "Portuguese (São Tomé & Príncipe)",
  "pt_TL": "Portuguese (Timor-Leste)",
  "qu": "কুৱেচুৱা",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "কিচিয়ে",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "ৰাপানুই",
  "rar": "ৰাৰোতোঙ্গন",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "ৰোমানচ",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "ৰুন্দি",
  "rn_BI": "Rundi (Burundi)",
  "ro": "ৰোমানীয়",
  "ro_MD": "মোল্ডাভিয়ান",
  "ro_RO": "Romanian (Romania)",
  "rof": "ৰোম্বো",
  "rom": "Romany",
  "root": "ৰুট",
  "rtm": "Rotuman",
  "ru": "ৰাছিয়ান",
  "ru_BY": "Russian (Belarus)",
  "ru_KG": "Russian (Kyrgyzstan)",
  "ru_KZ": "Russian (Kazakhstan)",
  "ru_MD": "Russian (Moldova)",
  "ru_RU": "Russian (Russia)",
  "ru_UA": "Russian (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "আৰোমানীয়",
  "rw": "কিনয়াৰোৱাণ্ডা",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "ৰৱা",
  "sa": "সংস্কৃত",
  "sad": "ছান্দাৱে",
  "sah": "ছাখা",
  "sam": "Samaritan Aramaic",
  "saq": "ছাম্বুৰু",
  "sas": "Sasak",
  "sat": "চাওতালি",
  "saz": "Saurashtra",
  "sba": "নাংম্বে",
  "sbp": "ছাঙ্গু",
  "sc": "ছাৰ্ডিনিয়ান",
  "scn": "ছিচিলিয়ান",
  "sco": "স্কটছ",
  "sd": "সিন্ধী",
  "sdc": "Sassarese Sardinian",
  "se": "উদীচ্য ছামি",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "ছেনা",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "কোইৰাবোৰো চেন্নি",
  "sg": "ছাঙ্গো",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "তাচেলহিট",
  "shn": "চান",
  "shu": "Chadian Arabic",
  "si": "সিংহলা",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "শ্লোভাক",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "শ্লোভেনিয়ান",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "ছামোন",
  "sma": "দাক্ষিণাত্য ছামি",
  "smj": "লুলে ছামি",
  "smn": "ইনাৰি ছামি",
  "sms": "স্কোল্ট ছামি",
  "sn": "চোনা",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "ছোনিনকে",
  "so": "ছোমালি",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdien",
  "sq": "আলবেনীয়",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "ছাৰ্বিয়ান",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "স্ৰানান টোঙ্গো",
  "srr": "Serer",
  "ss": "স্বাতি",
  "ssy": "ছাহো",
  "st": "দাক্ষিণাত্য ছোথো",
  "stq": "Saterland Frisian",
  "su": "ছুণ্ডানীজ",
  "suk": "ছুকুমা",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "ছুইডিচ",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Swedish (Finland)",
  "sv_SE": "Swedish (Sweden)",
  "sw": "স্বাহিলি",
  "sw_CD": "কঙ্গো স্বাহিলি",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "কোমোৰিয়ান",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "চিৰিয়াক",
  "szl": "Silesian",
  "ta": "তামিল",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Malaysia)",
  "ta_SG": "Tamil (Singapore)",
  "tcy": "Tulu",
  "te": "তেলুগু",
  "te_IN": "Telugu (India)",
  "tem": "টিম্নে",
  "teo": "তেছো",
  "ter": "Tereno",
  "tet": "তেতুম",
  "tg": "তাজিক",
  "th": "থাই",
  "th_TH": "Thai (Thailand)",
  "ti": "টিগৰিনিয়া",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "তাইগ্ৰে",
  "tiv": "Tiv",
  "tk": "তুৰ্কমেন",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "ক্লিংগন",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "ছোৱানা",
  "to": "টোঙ্গান",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "টোক পিছিন",
  "tr": "তুৰ্কী",
  "tr_CY": "Turkish (Cyprus)",
  "tr_TR": "Turkish (Turkey)",
  "tru": "Turoyo",
  "trv": "তাৰোকো",
  "ts": "ছোঙ্গা",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "তাতাৰ",
  "ttt": "Muslim Tat",
  "tum": "তুম্বুকা",
  "tvl": "টুভালু",
  "tw": "Twi",
  "twq": "টাছাৱাক",
  "ty": "তাহিতিয়ান",
  "tyv": "তুভিনিয়ান",
  "tzm": "চেণ্ট্ৰেল এটলাছ টামাজাইট",
  "udm": "উদমুৰ্ত",
  "ug": "উইঘুৰ",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "ইউক্ৰেইনীয়",
  "uk_UA": "Ukrainian (Ukraine)",
  "umb": "উম্বুন্দু",
  "und": "অজ্ঞাত ভাষা",
  "ur": "উৰ্দু",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "উজবেক",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "ভাই",
  "ve": "ভেণ্ডা",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "ভিয়েটনামী",
  "vi_VN": "Vietnamese (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "ভোলাপুক",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "ভুঞ্জু",
  "wa": "ৱালুন",
  "wae": "ৱালছেৰ",
  "wal": "ওলেইটা",
  "war": "ৱাৰে",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "ৱোলাফ",
  "wuu": "Wu Chinese",
  "xal": "কাল্মিক",
  "xh": "হোছা",
  "xmf": "Mingrelian",
  "xog": "ছোগা",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "য়াংবেন",
  "ybb": "য়েম্বা",
  "yi": "ইদ্দিছ",
  "yo": "ইউৰুবা",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "কেণ্টোনীজ",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "ষ্টেণ্ডাৰ্ড মোৰোক্কান তামাজাইট",
  "zh": "চীনা",
  "zh_CN": "Chinese (China)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "সৰলীকৃত চীনা",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "পৰম্পৰাগত চীনা",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Chinese (Singapore)",
  "zh_TW": "Chinese (Taiwan)",
  "zu": "ঝুলু",
  "zu_ZA": "Zulu (South Africa)",
  "zun": "ঝুনি",
  "zxx": "কোনো ভাষা সমল নাই",
  "zza": "ঝাঝা"
};
