const names = {
  "aeb": "Tunisian Arabic",
  "arq": "Algerian Arabic",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "ase": "American Sign Language",
  "avk": "Kotava",
  "bar": "Bavarian",
  "bbc": "Batak Toba",
  "bew": "Betawi",
  "dtp": "Central Dusun",
  "egl": "Emilian",
  "esu": "Central Yupik",
  "ext": "Extremaduran",
  "fit": "Tornedalen Finnish",
  "frc": "Cajun French",
  "fy": "ເວສເທີນ ຟຣິຊຽນ",
  "gan": "Gan Chinese",
  "glk": "Gilaki",
  "hak": "Hakka Chinese",
  "hif": "Fiji Hindi",
  "hsb": "ຊຸບເປີຊໍບຽນ",
  "hsn": "Xiang Chinese",
  "jut": "Jutish",
  "ken": "Kenyang",
  "khw": "Khowar",
  "ks": "ຄັດຊະມີຣີ",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mk": "ແມັກເຊໂດນຽນ",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nds": "ເຢຍລະມັນຕ່ຳ ແຊກຊອນຕໍ່ຳ",
  "nov": "Novial",
  "pdc": "Pennsylvania German",
  "pfl": "Palatine German",
  "prg": "Prussian",
  "pt": "ປໍຕູກີສ",
  "qug": "Chimborazo Highland Quichua",
  "rgn": "Romagnol",
  "rm": "ໂຣແມນ",
  "ru": "ຣັດຊຽນ",
  "rue": "Rusyn",
  "see": "Seneca",
  "shn": "ໄທໃຫ່ຍ",
  "sli": "Lower Silesian",
  "stq": "Saterland Frisian",
  "tcy": "Tulu",
  "tru": "Turoyo",
  "ur": "ອູຣະດູ",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese"
};
