const names = {
  "001": "maailm",
  "002": "Aafrika",
  "003": "Põhja-Ameerika",
  "005": "Lõuna-Ameerika",
  "009": "Okeaania",
  "011": "Lääne-Aafrika",
  "013": "Kesk-Ameerika",
  "014": "Ida-Aafrika",
  "015": "Põhja-Aafrika",
  "017": "Kesk-Aafrika",
  "018": "Lõuna-Aafrika",
  "019": "Ameerika",
  "021": "Ameerika põhjaosa",
  "029": "Kariibi piirkond",
  "030": "Ida-Aasia",
  "034": "Lõuna-Aasia",
  "035": "Kagu-Aasia",
  "039": "Lõuna-Euroopa",
  "053": "Australaasia",
  "054": "Melaneesia",
  "057": "Mikroneesia (piirkond)",
  "061": "Polüneesia",
  "142": "Aasia",
  "143": "Kesk-Aasia",
  "145": "Lääne-Aasia",
  "150": "Euroopa",
  "151": "Ida-Euroopa",
  "154": "Põhja-Euroopa",
  "155": "Lääne-Euroopa",
  "202": "Sahara-tagune Aafrika",
  "419": "Ladina-Ameerika",
  "AC": "Ascensioni saar",
  "AD": "Andorra",
  "AE": "Araabia Ühendemiraadid",
  "AF": "Afganistan",
  "AG": "Antigua ja Barbuda",
  "AI": "Anguilla",
  "AL": "Albaania",
  "AM": "Armeenia",
  "AN": "Hollandi Antillid",
  "AO": "Angola",
  "AQ": "Antarktika",
  "AR": "Argentina",
  "AS": "Ameerika Samoa",
  "AT": "Austria",
  "AU": "Austraalia",
  "AW": "Aruba",
  "AX": "Ahvenamaa",
  "AZ": "Aserbaidžaan",
  "Afak": "afaka",
  "Aghb": "albaani",
  "Ahom": "ahomi",
  "Arab": "araabia",
  "Armi": "vanaaramea",
  "Armn": "armeenia",
  "Avst": "avesta",
  "BA": "Bosnia ja Hertsegoviina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaaria",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Boliivia",
  "BQ": "Hollandi Kariibi mere saared",
  "BR": "Brasiilia",
  "BS": "Bahama",
  "BT": "Bhutan",
  "BV": "Bouvet’ saar",
  "BW": "Botswana",
  "BY": "Valgevene",
  "BZ": "Belize",
  "Bali": "bali",
  "Bamu": "bamumi",
  "Bass": "bassa",
  "Batk": "bataki",
  "Beng": "bengali",
  "Blis": "Blissi sümbolid",
  "Bopo": "bopomofo",
  "Brah": "braahmi",
  "Brai": "punktkiri",
  "Bugi": "bugi",
  "Buhd": "buhidi",
  "CA": "Kanada",
  "CC": "Kookossaared",
  "CD": "Kongo DV",
  "CF": "Kesk-Aafrika Vabariik",
  "CG": "Kongo Vabariik",
  "CH": "Šveits",
  "CI": "Côte d’Ivoire",
  "CK": "Cooki saared",
  "CL": "Tšiili",
  "CM": "Kamerun",
  "CN": "Hiina",
  "CO": "Colombia",
  "CP": "Clippertoni saar",
  "CR": "Costa Rica",
  "CS": "Serbia ja Montenegro",
  "CU": "Kuuba",
  "CV": "Roheneemesaared",
  "CW": "Curaçao",
  "CX": "Jõulusaar",
  "CY": "Küpros",
  "CZ": "Tšehhi",
  "Cakm": "tšaakma",
  "Cans": "Kanada põlisrahvaste ühtlustatud silpkiri",
  "Cari": "kaaria",
  "Cham": "tšaami",
  "Cher": "tšerokii",
  "Cirt": "Cirthi",
  "Copt": "kopti",
  "Cprt": "Küprose silpkiri",
  "Cyrl": "kirillitsa",
  "Cyrs": "kürilliline kirikuslaavi",
  "DE": "Saksamaa",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Taani",
  "DM": "Dominica",
  "DO": "Dominikaani Vabariik",
  "DZ": "Alžeeria",
  "Deva": "devanaagari",
  "Dsrt": "desereti",
  "Dupl": "Duployé kiirkiri",
  "EA": "Ceuta ja Melilla",
  "EC": "Ecuador",
  "EE": "Eesti",
  "EG": "Egiptus",
  "EH": "Lääne-Sahara",
  "ER": "Eritrea",
  "ES": "Hispaania",
  "ET": "Etioopia",
  "EU": "Euroopa Liit",
  "EZ": "euroala",
  "Egyd": "egiptuse demootiline",
  "Egyh": "egiptuse hieraatiline",
  "Egyp": "egiptuse hieroglüüfkiri",
  "Elba": "Elbasani",
  "Ethi": "etioopia",
  "FI": "Soome",
  "FJ": "Fidži",
  "FK": "Falklandi saared",
  "FM": "Mikroneesia",
  "FO": "Fääri saared",
  "FR": "Prantsusmaa",
  "GA": "Gabon",
  "GB": "Suurbritannia",
  "GD": "Grenada",
  "GE": "Gruusia",
  "GF": "Prantsuse Guajaana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Gröönimaa",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Ekvatoriaal-Guinea",
  "GR": "Kreeka",
  "GS": "Lõuna-Georgia ja Lõuna-Sandwichi saared",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "hutsuri",
  "Geor": "gruusia",
  "Glag": "glagoolitsa",
  "Gonm": "Masarami gondi",
  "Goth": "gooti",
  "Gran": "grantha",
  "Grek": "kreeka",
  "Gujr": "gudžarati",
  "Guru": "gurmukhi",
  "HK": "Hongkongi erihalduspiirkond",
  "HM": "Heardi ja McDonaldi saared",
  "HN": "Honduras",
  "HR": "Horvaatia",
  "HT": "Haiti",
  "HU": "Ungari",
  "Hanb": "hanbi",
  "Hang": "korea",
  "Hani": "hani",
  "Hano": "hanunoo",
  "Hans": "lihtsustatud",
  "Hant": "traditsiooniline",
  "Hatr": "Hatra",
  "Hebr": "heebrea",
  "Hira": "hiragana",
  "Hluw": "Anatoolia hieroglüüfkiri",
  "Hmng": "phahau-hmongi kiri",
  "Hrkt": "jaapani silpkirjad",
  "Hung": "vanaungari",
  "IC": "Kanaari saared",
  "ID": "Indoneesia",
  "IE": "Iirimaa",
  "IL": "Iisrael",
  "IM": "Mani saar",
  "IN": "India",
  "IO": "Briti India ookeani ala",
  "IQ": "Iraak",
  "IR": "Iraan",
  "IS": "Island",
  "IT": "Itaalia",
  "Inds": "Induse",
  "Ital": "vanaitali",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordaania",
  "JP": "Jaapan",
  "Jamo": "jamo",
  "Java": "jaava",
  "Jpan": "jaapani",
  "Jurc": "tšurtšeni",
  "KE": "Keenia",
  "KG": "Kõrgõzstan",
  "KH": "Kambodža",
  "KI": "Kiribati",
  "KM": "Komoorid",
  "KN": "Saint Kitts ja Nevis",
  "KP": "Põhja-Korea",
  "KR": "Lõuna-Korea",
  "KW": "Kuveit",
  "KY": "Kaimanisaared",
  "KZ": "Kasahstan",
  "Kali": "kaja-lii",
  "Kana": "katakana",
  "Khar": "kharoshthi",
  "Khmr": "khmeeri",
  "Khoj": "hodžki",
  "Knda": "kannada",
  "Kore": "korea segakiri",
  "Kpel": "kpelle",
  "Kthi": "kaithi",
  "LA": "Laos",
  "LB": "Liibanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Libeeria",
  "LS": "Lesotho",
  "LT": "Leedu",
  "LU": "Luksemburg",
  "LV": "Läti",
  "LY": "Liibüa",
  "Lana": "tai-thami",
  "Laoo": "lao",
  "Latf": "ladina fraktuurkiri",
  "Latg": "ladina gaeli",
  "Latn": "ladina",
  "Lepc": "leptša",
  "Limb": "limbu",
  "Lina": "lineaarkiri A",
  "Linb": "lineaarkiri B",
  "Lisu": "lisu",
  "Loma": "loma",
  "Lyci": "lüükia",
  "Lydi": "lüüdia",
  "MA": "Maroko",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint-Martin",
  "MG": "Madagaskar",
  "MH": "Marshalli Saared",
  "MK": "Põhja-Makedoonia",
  "ML": "Mali",
  "MM": "Myanmar (Birma)",
  "MN": "Mongoolia",
  "MO": "Macau erihalduspiirkond",
  "MP": "Põhja-Mariaanid",
  "MQ": "Martinique",
  "MR": "Mauritaania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldiivid",
  "MW": "Malawi",
  "MX": "Mehhiko",
  "MY": "Malaisia",
  "MZ": "Mosambiik",
  "Mahj": "mahaadžani",
  "Mand": "mandea",
  "Mani": "mani",
  "Maya": "maaja hieroglüüfkiri",
  "Mend": "mende",
  "Merc": "meroe kursiivkiri",
  "Mero": "meroe",
  "Mlym": "malajalami",
  "Modi": "modi",
  "Mong": "mongoli",
  "Moon": "Mooni",
  "Mroo": "mruu",
  "Mtei": "meitei",
  "Mult": "Multani",
  "Mymr": "birma",
  "NA": "Namiibia",
  "NC": "Uus-Kaledoonia",
  "NE": "Niger",
  "NF": "Norfolk",
  "NG": "Nigeeria",
  "NI": "Nicaragua",
  "NL": "Holland",
  "NO": "Norra",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Uus-Meremaa",
  "Narb": "Põhja-Araabia",
  "Nbat": "Nabatea",
  "Newa": "nevari",
  "Nkgb": "nasi",
  "Nkoo": "nkoo",
  "Nshu": "nüšu",
  "OM": "Omaan",
  "Ogam": "ogam",
  "Olck": "santali",
  "Orkh": "Orhoni",
  "Orya": "oria",
  "Osge": "oseidži",
  "Osma": "osmani",
  "PA": "Panama",
  "PE": "Peruu",
  "PF": "Prantsuse Polüneesia",
  "PG": "Paapua Uus-Guinea",
  "PH": "Filipiinid",
  "PK": "Pakistan",
  "PL": "Poola",
  "PM": "Saint-Pierre ja Miquelon",
  "PN": "Pitcairni saared",
  "PR": "Puerto Rico",
  "PS": "Palestiina alad",
  "PT": "Portugal",
  "PW": "Belau",
  "PY": "Paraguay",
  "Palm": "Palmyra",
  "Perm": "vanapermi",
  "Phag": "phakpa",
  "Phli": "pahlavi raidkiri",
  "Phlp": "pahlavi psalmikiri",
  "Phlv": "pahlavi raamatukiri",
  "Phnx": "foiniikia",
  "Plrd": "Pollardi miao",
  "Prti": "partia raidkiri",
  "QA": "Katar",
  "QO": "Okeaania hajasaared",
  "RE": "Réunion",
  "RO": "Rumeenia",
  "RS": "Serbia",
  "RU": "Venemaa",
  "RW": "Rwanda",
  "Rjng": "redžangi",
  "Roro": "rongorongo",
  "Runr": "ruunikiri",
  "SA": "Saudi Araabia",
  "SB": "Saalomoni Saared",
  "SC": "Seišellid",
  "SD": "Sudaan",
  "SE": "Rootsi",
  "SG": "Singapur",
  "SH": "Saint Helena",
  "SI": "Sloveenia",
  "SJ": "Svalbard ja Jan Mayen",
  "SK": "Slovakkia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somaalia",
  "SR": "Suriname",
  "SS": "Lõuna-Sudaan",
  "ST": "São Tomé ja Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Süüria",
  "SZ": "Svaasimaa",
  "Samr": "Samaaria",
  "Sara": "sarati",
  "Sarb": "Lõuna-Araabia",
  "Saur": "sauraštra",
  "Sgnw": "viipekiri",
  "Shaw": "Shaw’ kiri",
  "Shrd": "šaarada",
  "Sidd": "siddhami",
  "Sind": "hudavadi",
  "Sinh": "singali",
  "Sora": "sora",
  "Soyo": "sojombo",
  "Sund": "sunda",
  "Sylo": "siloti",
  "Syrc": "süüria",
  "Syre": "süüria estrangelo",
  "Syrj": "läänesüüria",
  "Syrn": "idasüüria",
  "TA": "Tristan da Cunha",
  "TC": "Turks ja Caicos",
  "TD": "Tšaad",
  "TF": "Prantsuse Lõunaalad",
  "TG": "Togo",
  "TH": "Tai",
  "TJ": "Tadžikistan",
  "TK": "Tokelau",
  "TL": "Ida-Timor",
  "TM": "Türkmenistan",
  "TN": "Tuneesia",
  "TO": "Tonga",
  "TR": "Türgi",
  "TT": "Trinidad ja Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansaania",
  "Tagb": "tagbanva",
  "Takr": "taakri",
  "Tale": "tai-löö",
  "Talu": "uus tai-lõõ",
  "Taml": "tamili",
  "Tang": "tanguudi",
  "Tavt": "tai-vieti",
  "Telu": "telugu",
  "Teng": "Tengwari",
  "Tfng": "tifinagi",
  "Tglg": "tagalogi",
  "Thaa": "taana",
  "Thai": "tai",
  "Tibt": "tiibeti",
  "Tirh": "tirhuta",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "Ühendriikide hajasaared",
  "UN": "Ühinenud Rahvaste Organisatsioon",
  "US": "Ameerika Ühendriigid",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "Ugar": "ugariti",
  "VA": "Vatikan",
  "VC": "Saint Vincent ja Grenadiinid",
  "VE": "Venezuela",
  "VG": "Briti Neitsisaared",
  "VI": "USA Neitsisaared",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "Visp": "nähtava kõne",
  "WF": "Wallis ja Futuna",
  "WS": "Samoa",
  "Wara": "hoo",
  "Wcho": "vantšo",
  "Wole": "voleai",
  "XA": "pseudo-aktsent",
  "XB": "pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "vanapärsia",
  "Xsux": "sumeri-akadi kiilkiri",
  "YE": "Jeemen",
  "YT": "Mayotte",
  "Yiii": "jii",
  "ZA": "Lõuna-Aafrika Vabariik",
  "ZM": "Sambia",
  "ZW": "Zimbabwe",
  "ZZ": "tundmatu piirkond",
  "Zanb": "Dzanabadzari ruutkiri",
  "Zinh": "päritud",
  "Zmth": "matemaatiline tähistus",
  "Zsye": "emoji",
  "Zsym": "sümbolid",
  "Zxxx": "kirjakeeleta",
  "Zyyy": "üldine",
  "Zzzz": "määramata kiri",
  "aa": "afari",
  "ab": "abhaasi",
  "ace": "atšehi",
  "ach": "atšoli",
  "ada": "adangme",
  "ady": "adõgee",
  "ae": "avesta",
  "aeb": "Tuneesia araabia",
  "af": "afrikaani",
  "af_NA": "afrikaani (Namiibia)",
  "af_ZA": "afrikaani (Lõuna-Aafrika Vabariik)",
  "afa": "afroaasia keel",
  "afh": "afrihili",
  "agq": "aghemi",
  "ain": "ainu",
  "ak": "akani",
  "ak_GH": "akani (Ghana)",
  "akk": "akadi",
  "akz": "alabama",
  "ale": "aleuudi",
  "alg": "algonkini keel",
  "aln": "geegi",
  "alt": "altai",
  "am": "amhara",
  "am_ET": "amhari (Etioopia)",
  "an": "aragoni",
  "ang": "vanainglise",
  "anp": "angika",
  "apa": "apatši keel",
  "ar": "araabia",
  "ar_001": "araabia (tänapäevane)",
  "ar_AE": "araabia (Araabia Ühendemiraadid)",
  "ar_BH": "araabia (Bahrein)",
  "ar_DJ": "araabia (Djibouti)",
  "ar_DZ": "araabia (Alžeeria)",
  "ar_EG": "araabia (Egiptus)",
  "ar_EH": "araabia (Lääne-Sahara)",
  "ar_ER": "araabia (Eritrea)",
  "ar_IL": "araabia (Iisrael)",
  "ar_IQ": "araabia (Iraak)",
  "ar_JO": "araabia (Jordaania)",
  "ar_KM": "araabia (Komoorid)",
  "ar_KW": "araabia (Kuveit)",
  "ar_LB": "araabia (Liibanon)",
  "ar_LY": "araabia (Liibüa)",
  "ar_MA": "araabia (Maroko)",
  "ar_MR": "araabia (Mauritaania)",
  "ar_OM": "araabia (Omaan)",
  "ar_PS": "araabia (Palestiina alad)",
  "ar_QA": "araabia (Katar)",
  "ar_SA": "araabia (Saudi Araabia)",
  "ar_SD": "araabia (Sudaan)",
  "ar_SO": "araabia (Somaalia)",
  "ar_SS": "araabia (Lõuna-Sudaan)",
  "ar_SY": "araabia (Süüria)",
  "ar_TD": "araabia (Tšaad)",
  "ar_TN": "araabia (Tuneesia)",
  "ar_YE": "araabia (Jeemen)",
  "arc": "aramea",
  "arn": "mapudunguni",
  "aro": "araona",
  "arp": "arapaho",
  "arq": "Alžeeria araabia",
  "art": "muu tehiskeel",
  "arw": "aravaki",
  "ary": "Maroko araabia",
  "arz": "Egiptuse araabia",
  "as": "assami",
  "as_IN": "assami (India)",
  "asa": "asu",
  "ase": "Ameerika viipekeel",
  "ast": "astuuria",
  "ath": "atapaski keeled",
  "aus": "austraali keel",
  "av": "avaari",
  "avk": "Kotava",
  "awa": "avadhi",
  "ay": "aimara",
  "az": "aserbaidžaani",
  "az_AZ": "aserbaidžaani (Aserbaidžaan)",
  "az_Cyrl": "aserbaidžaani (kirillitsa)",
  "az_Cyrl_AZ": "aserbaidžaani (kirillitsa, Aserbaidžaan)",
  "az_Latn": "aserbaidžaani (ladina)",
  "az_Latn_AZ": "aserbaidžaani (ladina, Aserbaidžaan)",
  "azb": "South Azerbaijani",
  "ba": "baškiiri",
  "bad": "banda",
  "bai": "bamileke keel",
  "bal": "belutši",
  "ban": "bali",
  "bar": "baieri",
  "bas": "basaa",
  "bat": "balti keel",
  "bax": "bamuni",
  "bbc": "bataki",
  "bbj": "ghomala",
  "be": "valgevene",
  "be_BY": "valgevene (Valgevene)",
  "bej": "bedža",
  "bem": "bemba",
  "ber": "berberi",
  "bew": "betavi",
  "bez": "bena",
  "bfd": "bafuti",
  "bfq": "badaga",
  "bg": "bulgaaria",
  "bg_BG": "bulgaaria (Bulgaaria)",
  "bgn": "läänebelutši",
  "bh": "bihaari",
  "bho": "bhodžpuri",
  "bi": "bislama",
  "bik": "bikoli",
  "bin": "edo",
  "bjn": "bandžari",
  "bkm": "komi (Aafrika)",
  "bla": "mustjalaindiaani",
  "bm": "bambara",
  "bm_Latn": "bambara (ladina)",
  "bm_Latn_ML": "bambara (ladina, Mali)",
  "bn": "bengali",
  "bn_BD": "bengali (Bangladesh)",
  "bn_IN": "bengali (India)",
  "bnt": "bantu",
  "bo": "tiibeti",
  "bo_CN": "tiibeti (Hiina)",
  "bo_IN": "tiibeti (India)",
  "bpy": "bišnuprija",
  "bqi": "bahtiari",
  "br": "bretooni",
  "br_FR": "bretooni (Prantsusmaa)",
  "bra": "bradži",
  "brh": "brahui",
  "brx": "bodo",
  "bs": "bosnia",
  "bs_BA": "bosnia (Bosnia ja Hertsegoviina)",
  "bs_Cyrl": "bosnia (kirillitsa)",
  "bs_Cyrl_BA": "bosnia (kirillitsa, Bosnia ja Hertsegoviina)",
  "bs_Latn": "bosnia (ladina)",
  "bs_Latn_BA": "bosnia (ladina, Bosnia ja Hertsegoviina)",
  "bss": "akoose",
  "btk": "bataki",
  "bua": "burjaadi",
  "bug": "bugi",
  "bum": "bulu",
  "byn": "bilini",
  "byv": "medumba",
  "ca": "katalaani",
  "ca_AD": "katalaani (Andorra)",
  "ca_ES": "katalaani (Hispaania)",
  "ca_FR": "katalaani (Prantsusmaa)",
  "ca_IT": "katalaani (Itaalia)",
  "cad": "kado",
  "cai": "Kesk-Ameerika indiaani keel",
  "car": "kariibi",
  "cau": "kaukaasia keel",
  "cay": "kajuka",
  "cch": "aitšami",
  "ccp": "tšaakma",
  "ce": "tšetšeeni",
  "ceb": "sebu",
  "cel": "keldi keel",
  "cgg": "tšiga",
  "ch": "tšamorro",
  "chb": "tšibtša",
  "chg": "tšagatai",
  "chk": "tšuugi",
  "chm": "mari",
  "chn": "tšinuki žargoon",
  "cho": "tšokto",
  "chp": "tšipevai",
  "chr": "tšerokii",
  "chy": "šaieeni",
  "ckb": "sorani",
  "cmc": "tšami keeled",
  "co": "korsika",
  "cop": "kopti",
  "cpe": "inglispõhjalised kreool- ja pidžinkeeled",
  "cpf": "prantsuspõhjalised kreool- ja pidžinkeeled",
  "cpp": "portugalipõhjalised kreooli-/pidžinkeeled",
  "cps": "kapisnoni",
  "cr": "krii",
  "crh": "krimmitatari",
  "crp": "kreool- või pidžinkeel",
  "crs": "seišelli",
  "cs": "tšehhi",
  "cs_CZ": "tšehhi (Tšehhi)",
  "csb": "kašuubi",
  "cu": "kirikuslaavi",
  "cus": "muu kuši keel",
  "cv": "tšuvaši",
  "cy": "kõmri",
  "cy_GB": "kõmri (Suurbritannia)",
  "da": "taani",
  "da_DK": "taani (Taani)",
  "da_GL": "taani (Gröönimaa)",
  "dak": "siuu",
  "dar": "dargi",
  "dav": "davida",
  "day": "dajaki",
  "de": "saksa",
  "de_AT": "saksa (Austria)",
  "de_BE": "saksa (Belgia)",
  "de_CH": "saksa (Šveits)",
  "de_DE": "saksa (Saksamaa)",
  "de_LI": "saksa (Liechtenstein)",
  "de_LU": "saksa (Luksemburg)",
  "del": "delavari",
  "den": "sleivi",
  "dgr": "dogribi",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "draviidi keel",
  "dsb": "alamsorbi",
  "dtp": "keskdusuni",
  "dua": "duala",
  "dum": "keskhollandi",
  "dv": "maldiivi",
  "dyo": "fonji",
  "dyu": "djula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhutan)",
  "dzg": "daza",
  "ebu": "embu",
  "ee": "eve",
  "ee_GH": "eve (Ghana)",
  "ee_TG": "eve (Togo)",
  "efi": "efiki",
  "egl": "emiilia",
  "egy": "egiptuse",
  "eka": "ekadžuki",
  "el": "kreeka",
  "el_CY": "kreeka (Küpros)",
  "el_GR": "kreeka (Kreeka)",
  "elx": "eelami",
  "en": "inglise",
  "en_AG": "inglise (Antigua ja Barbuda)",
  "en_AI": "inglise (Anguilla)",
  "en_AS": "inglise (Ameerika Samoa)",
  "en_AU": "inglise (Austraalia)",
  "en_BB": "inglise (Barbados)",
  "en_BE": "inglise (Belgia)",
  "en_BM": "inglise (Bermuda)",
  "en_BS": "inglise (Bahama)",
  "en_BW": "inglise (Botswana)",
  "en_BZ": "inglise (Belize)",
  "en_CA": "inglise (Kanada)",
  "en_CC": "inglise (Kookossaared)",
  "en_CK": "inglise (Cooki saared)",
  "en_CM": "inglise (Kamerun)",
  "en_CX": "inglise (Jõulusaar)",
  "en_DG": "inglise (Diego Garcia)",
  "en_DM": "inglise (Dominica)",
  "en_ER": "inglise (Eritrea)",
  "en_FJ": "inglise (Fidži)",
  "en_FK": "inglise (Falklandi saared)",
  "en_FM": "inglise (Mikroneesia Liiduriigid)",
  "en_GB": "inglise (Suurbritannia)",
  "en_GD": "inglise (Grenada)",
  "en_GG": "inglise (Guernsey)",
  "en_GH": "inglise (Ghana)",
  "en_GI": "inglise (Gibraltar)",
  "en_GM": "inglise (Gambia)",
  "en_GU": "inglise (Guam)",
  "en_GY": "inglise (Guyana)",
  "en_HK": "inglise (Hongkong - Hiina erihalduspiirkond)",
  "en_IE": "inglise (Iirimaa)",
  "en_IM": "inglise (Mani saar)",
  "en_IN": "inglise (India)",
  "en_IO": "inglise (Briti India ookeani ala)",
  "en_JE": "inglise (Jersey)",
  "en_JM": "inglise (Jamaica)",
  "en_KE": "inglise (Kenya)",
  "en_KI": "inglise (Kiribati)",
  "en_KN": "inglise (Saint Kitts ja Nevis)",
  "en_KY": "inglise (Kaimanisaared)",
  "en_LC": "inglise (Saint Lucia)",
  "en_LR": "inglise (Libeeria)",
  "en_LS": "inglise (Lesotho)",
  "en_MG": "inglise (Madagaskar)",
  "en_MH": "inglise (Marshalli saared)",
  "en_MO": "inglise (Macau - Hiina erihalduspiirkond)",
  "en_MP": "inglise (Põhja-Mariaanid)",
  "en_MS": "inglise (Montserrat)",
  "en_MT": "inglise (Malta)",
  "en_MU": "inglise (Mauritius)",
  "en_MW": "inglise (Malawi)",
  "en_MY": "inglise (Malaisia)",
  "en_NA": "inglise (Namiibia)",
  "en_NF": "inglise (Norfolk)",
  "en_NG": "inglise (Nigeeria)",
  "en_NR": "inglise (Nauru)",
  "en_NU": "inglise (Niue)",
  "en_NZ": "inglise (Uus-Meremaa)",
  "en_PG": "inglise (Paapua Uus-Guinea)",
  "en_PH": "inglise (Filipiinid)",
  "en_PK": "inglise (Pakistan)",
  "en_PN": "inglise (Pitcairni saared)",
  "en_PR": "inglise (Puerto Rico)",
  "en_PW": "inglise (Belau)",
  "en_RW": "inglise (Rwanda)",
  "en_SB": "inglise (Saalomoni Saared)",
  "en_SC": "inglise (Seišellid)",
  "en_SD": "inglise (Sudaan)",
  "en_SG": "inglise (Singapur)",
  "en_SH": "inglise (Saint Helena)",
  "en_SL": "inglise (Sierra Leone)",
  "en_SS": "inglise (Lõuna-Sudaan)",
  "en_SX": "inglise (Sint Maarten)",
  "en_SZ": "inglise (Svaasimaa)",
  "en_TC": "inglise (Turks ja Caicos)",
  "en_TK": "inglise (Tokelau)",
  "en_TO": "inglise (Tonga)",
  "en_TT": "inglise (Trinidad ja Tobago)",
  "en_TV": "inglise (Tuvalu)",
  "en_TZ": "inglise (Tansaania)",
  "en_UG": "inglise (Uganda)",
  "en_UM": "inglise (Ühendriikide hajasaared)",
  "en_US": "inglise (Ameerika Ühendriigid)",
  "en_VC": "inglise (Saint Vincent ja Grenadiinid)",
  "en_VG": "inglise (Briti Neitsisaared)",
  "en_VI": "inglise (USA Neitsisaared)",
  "en_VU": "inglise (Vanuatu)",
  "en_WS": "inglise (Samoa)",
  "en_ZA": "inglise (Lõuna-Aafrika Vabariik)",
  "en_ZM": "inglise (Sambia)",
  "en_ZW": "inglise (Zimbabwe)",
  "enm": "keskinglise",
  "eo": "esperanto",
  "es": "hispaania",
  "es_419": "Latin American Spanish",
  "es_AR": "hispaania (Argentina)",
  "es_BO": "hispaania (Boliivia)",
  "es_CL": "hispaania (Tšiili)",
  "es_CO": "hispaania (Colombia)",
  "es_CR": "hispaania (Costa Rica)",
  "es_CU": "hispaania (Kuuba)",
  "es_DO": "hispaania (Dominikaani Vabariik)",
  "es_EA": "hispaania (Ceuta ja Melilla)",
  "es_EC": "hispaania (Ecuador)",
  "es_ES": "hispaania (Hispaania)",
  "es_GQ": "hispaania (Ekvatoriaal-Guinea)",
  "es_GT": "hispaania (Guatemala)",
  "es_HN": "hispaania (Honduras)",
  "es_IC": "hispaania (Kanaari saared)",
  "es_MX": "hispaania (Mehhiko)",
  "es_NI": "hispaania (Nicaragua)",
  "es_PA": "hispaania (Panama)",
  "es_PE": "hispaania (Peruu)",
  "es_PH": "hispaania (Filipiinid)",
  "es_PR": "hispaania (Puerto Rico)",
  "es_PY": "hispaania (Paraguay)",
  "es_SV": "hispaania (El Salvador)",
  "es_US": "hispaania (Ameerika Ühendriigid)",
  "es_UY": "hispaania (Uruguay)",
  "es_VE": "hispaania (Venezuela)",
  "esu": "keskjupiki",
  "et": "eesti",
  "et_EE": "eesti (Eesti)",
  "eu": "baski",
  "eu_ES": "baski (Hispaania)",
  "ewo": "evondo",
  "ext": "estremenju",
  "fa": "pärsia",
  "fa_AF": "pärsia (Afganistan)",
  "fa_IR": "pärsia (Iraan)",
  "fan": "fangi",
  "fat": "fanti",
  "ff": "fula",
  "ff_CM": "fulbe (Kamerun)",
  "ff_GN": "fulbe (Guinea)",
  "ff_MR": "fulbe (Mauritaania)",
  "ff_SN": "fulbe (Senegal)",
  "fi": "soome",
  "fi_FI": "soome (Soome)",
  "fil": "filipiini",
  "fit": "meä",
  "fiu": "soomeugri keel",
  "fj": "fidži",
  "fo": "fääri",
  "fo_FO": "fääri (Fääri saared)",
  "fon": "foni",
  "fr": "prantsuse",
  "fr_BE": "prantsuse (Belgia)",
  "fr_BF": "prantsuse (Burkina Faso)",
  "fr_BI": "prantsuse (Burundi)",
  "fr_BJ": "prantsuse (Benin)",
  "fr_BL": "prantsuse (Saint Barthélemy)",
  "fr_CA": "prantsuse (Kanada)",
  "fr_CD": "prantsuse (Kongo DV)",
  "fr_CF": "prantsuse (Kesk-Aafrika Vabariik)",
  "fr_CG": "prantsuse (Kongo-Brazzaville)",
  "fr_CH": "prantsuse (Šveits)",
  "fr_CI": "prantsuse (Côte d’Ivoire)",
  "fr_CM": "prantsuse (Kamerun)",
  "fr_DJ": "prantsuse (Djibouti)",
  "fr_DZ": "prantsuse (Alžeeria)",
  "fr_FR": "prantsuse (Prantsusmaa)",
  "fr_GA": "prantsuse (Gabon)",
  "fr_GF": "prantsuse (Prantsuse Guajaana)",
  "fr_GN": "prantsuse (Guinea)",
  "fr_GP": "prantsuse (Guadeloupe)",
  "fr_GQ": "prantsuse (Ekvatoriaal-Guinea)",
  "fr_HT": "prantsuse (Haiti)",
  "fr_KM": "prantsuse (Komoorid)",
  "fr_LU": "prantsuse (Luksemburg)",
  "fr_MA": "prantsuse (Maroko)",
  "fr_MC": "prantsuse (Monaco)",
  "fr_MF": "prantsuse (Saint Martin)",
  "fr_MG": "prantsuse (Madagaskar)",
  "fr_ML": "prantsuse (Mali)",
  "fr_MQ": "prantsuse (Martinique)",
  "fr_MR": "prantsuse (Mauritaania)",
  "fr_MU": "prantsuse (Mauritius)",
  "fr_NC": "prantsuse (Uus-Kaledoonia)",
  "fr_NE": "prantsuse (Niger)",
  "fr_PF": "prantsuse (Prantsuse Polüneesia)",
  "fr_PM": "prantsuse (Saint Pierre ja Miquelon)",
  "fr_RE": "prantsuse (Réunion)",
  "fr_RW": "prantsuse (Rwanda)",
  "fr_SC": "prantsuse (Seišellid)",
  "fr_SN": "prantsuse (Senegal)",
  "fr_SY": "prantsuse (Süüria)",
  "fr_TD": "prantsuse (Tšaad)",
  "fr_TG": "prantsuse (Togo)",
  "fr_TN": "prantsuse (Tuneesia)",
  "fr_VU": "prantsuse (Vanuatu)",
  "fr_WF": "prantsuse (Wallis ja Futuna)",
  "fr_YT": "prantsuse (Mayotte)",
  "frc": "cajun’i",
  "frm": "keskprantsuse",
  "fro": "vanaprantsuse",
  "frp": "frankoprovansi",
  "frr": "põhjafriisi",
  "frs": "idafriisi",
  "fur": "friuuli",
  "fy": "läänefriisi",
  "fy_NL": "läänefriisi (Holland)",
  "ga": "iiri",
  "ga_IE": "iiri (Iirimaa)",
  "gaa": "gaa",
  "gag": "gagauusi",
  "gan": "kani",
  "gay": "gajo",
  "gba": "gbaja",
  "gbz": "Zoroastrian Dari",
  "gd": "gaeli",
  "gd_GB": "gaeli (Suurbritannia)",
  "gem": "germaani keel",
  "gez": "etioopia",
  "gil": "kiribati",
  "gl": "galeegi",
  "gl_ES": "galeegi (Hispaania)",
  "glk": "gilaki",
  "gmh": "keskülemsaksa",
  "gn": "guaranii",
  "goh": "vanaülemsaksa",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gooti",
  "grb": "grebo",
  "grc": "vanakreeka",
  "gsw": "šveitsisaksa",
  "gu": "gudžarati",
  "gu_IN": "gudžarati (India)",
  "guc": "vajuu",
  "gur": "farefare",
  "guz": "gusii",
  "gv": "mänksi",
  "gv_IM": "mänksi (Mani saar)",
  "gwi": "gvitšini",
  "ha": "hausa",
  "ha_GH": "hausa (Ghana)",
  "ha_Latn": "hausa (ladina)",
  "ha_Latn_GH": "hausa (ladina, Ghana)",
  "ha_Latn_NE": "hausa (ladina, Niger)",
  "ha_Latn_NG": "hausa (ladina, Nigeeria)",
  "ha_NE": "hausa (Niger)",
  "ha_NG": "hausa (Nigeeria)",
  "hai": "haida",
  "hak": "hakka",
  "haw": "havai",
  "he": "heebrea",
  "he_IL": "heebrea (Iisrael)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fidži hindi",
  "hil": "hiligainoni",
  "him": "himtšali",
  "hit": "heti",
  "hmn": "hmongi",
  "ho": "hirimotu",
  "hr": "horvaadi",
  "hr_BA": "horvaadi (Bosnia ja Hertsegoviina)",
  "hr_HR": "horvaadi (Horvaatia)",
  "hsb": "ülemsorbi",
  "hsn": "sjangi",
  "ht": "haiti",
  "hu": "ungari",
  "hu_HU": "ungari (Ungari)",
  "hup": "hupa",
  "hy": "armeenia",
  "hy_AM": "armeenia (Armeenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "ibani",
  "ibb": "ibibio",
  "id": "indoneesia",
  "id_ID": "indoneesia (Indoneesia)",
  "ie": "interlingue",
  "ig": "ibo",
  "ig_NG": "ibo (Nigeeria)",
  "ii": "nuosu",
  "ii_CN": "sichuani jii (Hiina)",
  "ijo": "idžo",
  "ik": "injupiaki",
  "ilo": "iloko",
  "inc": "india keel",
  "ine": "indoeuroopa keel",
  "inh": "inguši",
  "io": "ido",
  "ira": "iraani keeled",
  "iro": "irokeesi keel",
  "is": "islandi",
  "is_IS": "islandi (Island)",
  "it": "itaalia",
  "it_CH": "itaalia (Šveits)",
  "it_IT": "itaalia (Itaalia)",
  "it_SM": "itaalia (San Marino)",
  "iu": "inuktituti",
  "izh": "isuri",
  "ja": "jaapani",
  "ja_JP": "jaapani (Jaapan)",
  "jam": "Jamaica kreoolkeel",
  "jbo": "ložban",
  "jgo": "ngomba",
  "jmc": "matšame",
  "jpr": "juudipärsia",
  "jrb": "juudiaraabia",
  "jut": "jüüti",
  "jv": "jaava",
  "ka": "gruusia",
  "ka_GE": "gruusia (Gruusia)",
  "kaa": "karakalpaki",
  "kab": "kabiili",
  "kac": "katšini",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "kareni keel",
  "kaw": "kaavi",
  "kbd": "kabardi-tšerkessi",
  "kbl": "kanembu",
  "kcg": "tjapi",
  "kde": "makonde",
  "kea": "kabuverdianu",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "kaingangi",
  "kha": "khasi",
  "khi": "khoisani keel",
  "kho": "saka",
  "khq": "koyra chiini",
  "khw": "khovari",
  "ki": "kikuju",
  "ki_KE": "kikuju (Kenya)",
  "kiu": "kõrmandžki",
  "kj": "kvanjama",
  "kk": "kasahhi",
  "kk_Cyrl": "kasahhi (kirillitsa)",
  "kk_Cyrl_KZ": "kasahhi (kirillitsa, Kasahstan)",
  "kk_KZ": "kasahhi (Kasahstan)",
  "kkj": "kako",
  "kl": "grööni",
  "kl_GL": "grööni (Gröönimaa)",
  "kln": "kalendžini",
  "km": "khmeeri",
  "km_KH": "khmeeri (Kambodža)",
  "kmb": "mbundu",
  "kn": "kannada",
  "kn_IN": "kannada (India)",
  "ko": "korea",
  "ko_KP": "korea (Põhja-Korea)",
  "ko_KR": "korea (Lõuna-Korea)",
  "koi": "permikomi",
  "kok": "konkani",
  "kos": "kosrae",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karatšai-balkaari",
  "kri": "krio",
  "krj": "kinaraia",
  "krl": "karjala",
  "kro": "kruu",
  "kru": "kuruhhi",
  "ks": "kašmiiri",
  "ks_Arab": "kašmiiri (araabia)",
  "ks_Arab_IN": "kašmiiri (araabia, India)",
  "ks_IN": "kašmiiri (India)",
  "ksb": "šambala",
  "ksf": "bafia",
  "ksh": "kölni",
  "ku": "kurdi",
  "kum": "kumõki",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "korni",
  "kw_GB": "korni (Suurbritannia)",
  "ky": "kirgiisi",
  "ky_Cyrl": "kirgiisi (kirillitsa)",
  "ky_Cyrl_KG": "kirgiisi (kirillitsa, Kõrgõzstan)",
  "ky_KG": "kirgiisi (Kõrgõzstan)",
  "la": "ladina",
  "lad": "ladiino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "letseburgi",
  "lb_LU": "letseburgi (Luksemburg)",
  "lez": "lesgi",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgi",
  "lij": "liguuri",
  "liv": "liivi",
  "lkt": "lakota",
  "lmo": "lombardi",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Kongo DV)",
  "ln_CF": "lingala (Kesk-Aafrika Vabariik)",
  "ln_CG": "lingala (Kongo-Brazzaville)",
  "lo": "lao",
  "lo_LA": "lao (Laos)",
  "lol": "mongo",
  "lou": "Louisiana kreoolkeel",
  "loz": "lozi",
  "lrc": "põhjaluri",
  "lt": "leedu",
  "lt_LT": "leedu (Leedu)",
  "ltg": "latgali",
  "lu": "Katanga luba",
  "lu_CD": "luba (Kongo DV)",
  "lua": "lulua",
  "lui": "luisenjo",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lušei",
  "luy": "luhja",
  "lv": "läti",
  "lv_LV": "läti (Läti)",
  "lzh": "klassikaline hiina",
  "lzz": "lazi",
  "mad": "madura",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makassari",
  "man": "malinke",
  "map": "austroneesia keel",
  "mas": "masai",
  "mde": "maba",
  "mdf": "mokša",
  "mdr": "mandari",
  "men": "mende",
  "mer": "meru",
  "mfe": "Mauritiuse kreoolkeel",
  "mg": "malagassi",
  "mg_MG": "malagassi (Madagaskar)",
  "mga": "keskiiri",
  "mgh": "makhuwa-meetto",
  "mgo": "meta",
  "mh": "maršalli",
  "mi": "maoori",
  "mic": "mikmaki",
  "min": "minangkabau",
  "mis": "üksikkeeled",
  "mk": "makedoonia",
  "mk_MK": "makedoonia (Makedoonia)",
  "mkh": "moni-khmeeri keel",
  "ml": "malajalami",
  "ml_IN": "malajalami (India)",
  "mn": "mongoli",
  "mn_Cyrl": "mongoli (kirillitsa)",
  "mn_Cyrl_MN": "mongoli (kirillitsa, Mongoolia)",
  "mn_MN": "mongoli (Mongoolia)",
  "mnc": "mandžu",
  "mni": "manipuri",
  "mno": "manobo keel",
  "mo": "moldova",
  "moh": "mohoogi",
  "mos": "more",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "mäemari",
  "ms": "malai",
  "ms_BN": "malai (Brunei)",
  "ms_Latn": "malai (ladina)",
  "ms_Latn_BN": "malai (ladina, Brunei)",
  "ms_Latn_MY": "malai (ladina, Malaisia)",
  "ms_Latn_SG": "malai (ladina, Singapur)",
  "ms_MY": "malai (Malaisia)",
  "ms_SG": "malai (Singapur)",
  "mt": "malta",
  "mt_MT": "malta (Malta)",
  "mua": "mundangi",
  "mul": "mitu keelt",
  "mun": "munda keel",
  "mus": "maskogi",
  "mwl": "miranda",
  "mwr": "marvari",
  "mwv": "mentavei",
  "my": "birma",
  "my_MM": "birma (Myanmar (Birma))",
  "mye": "mjene",
  "myn": "maia keeled",
  "myv": "ersa",
  "mzn": "mazandaraani",
  "na": "nauru",
  "nah": "nahua",
  "nai": "Põhja-Ameerika indiaani keel",
  "nan": "lõunamini",
  "nap": "napoli",
  "naq": "nama",
  "nb": "norra bokmål",
  "nb_NO": "norra bokmål (Norra)",
  "nb_SJ": "norra bokmål (Svalbard ja Jan Mayen)",
  "nd": "põhjandebele",
  "nd_ZW": "põhjandebele (Zimbabwe)",
  "nds": "alamsaksa",
  "nds_NL": "Hollandi alamsaksa",
  "ne": "nepali",
  "ne_IN": "nepali (India)",
  "ne_NP": "nepali (Nepal)",
  "new": "nevari",
  "ng": "ndonga",
  "nia": "niasi",
  "nic": "Nigeri-Kordofani keel",
  "niu": "niue",
  "njo": "Ao Naga",
  "nl": "hollandi",
  "nl_AW": "hollandi (Aruba)",
  "nl_BE": "hollandi (Belgia)",
  "nl_BQ": "hollandi (Hollandi Kariibi mere saared)",
  "nl_CW": "hollandi (Curaçao)",
  "nl_NL": "hollandi (Holland)",
  "nl_SR": "hollandi (Suriname)",
  "nl_SX": "hollandi (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "uusnorra",
  "nn_NO": "norra nynorsk (Norra)",
  "nnh": "ngiembooni",
  "no": "norra",
  "no_NO": "norra (Norra)",
  "nog": "nogai",
  "non": "vanapõhjala",
  "nov": "noviaal",
  "nqo": "nkoo",
  "nr": "lõunandebele",
  "nso": "põhjasotho",
  "nub": "nuubia keel",
  "nus": "nueri",
  "nv": "navaho",
  "nwc": "vananevari",
  "ny": "njandža",
  "nym": "njamvesi",
  "nyn": "njankole",
  "nyo": "njoro",
  "nzi": "nzima",
  "oc": "oksitaani",
  "oj": "odžibvei",
  "om": "oromo",
  "om_ET": "oromo (Etioopia)",
  "om_KE": "oromo (Kenya)",
  "or": "oria",
  "or_IN": "oria (India)",
  "os": "osseedi",
  "os_GE": "osseedi (Gruusia)",
  "os_RU": "osseedi (Venemaa)",
  "osa": "oseidži",
  "ota": "osmanitürgi",
  "oto": "otomi keel",
  "pa": "pandžabi",
  "pa_Arab": "pandžabi (araabia)",
  "pa_Arab_PK": "pandžabi (araabia, Pakistan)",
  "pa_Guru": "pandžabi (gurmukhi)",
  "pa_Guru_IN": "pandžabi (gurmukhi, India)",
  "pa_IN": "pandžabi (India)",
  "pa_PK": "pandžabi (Pakistan)",
  "paa": "paapua keel",
  "pag": "pangasinani",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "belau",
  "pcd": "pikardi",
  "pcm": "Nigeeria pidžinkeel",
  "pdc": "Pennsylvania saksa",
  "pdt": "mennoniidisaksa",
  "peo": "vanapärsia",
  "pfl": "Pfalzi",
  "phi": "filipiini keel",
  "phn": "foiniikia",
  "pi": "paali",
  "pl": "poola",
  "pl_PL": "poola (Poola)",
  "pms": "piemonte",
  "pnt": "pontose",
  "pon": "poonpei",
  "pra": "praakriti keel",
  "prg": "preisi",
  "pro": "vanaprovansi",
  "ps": "puštu",
  "ps_AF": "puštu (Afganistan)",
  "pt": "portugali",
  "pt_AO": "portugali (Angola)",
  "pt_BR": "portugali (Brasiilia)",
  "pt_CV": "portugali (Roheneemesaared)",
  "pt_GW": "portugali (Guinea-Bissau)",
  "pt_MO": "portugali (Macau - Hiina erihalduspiirkond)",
  "pt_MZ": "portugali (Mosambiik)",
  "pt_PT": "portugali (Portugal)",
  "pt_ST": "portugali (São Tomé ja Príncipe)",
  "pt_TL": "portugali (Ida-Timor)",
  "qu": "ketšua",
  "qu_BO": "ketšua (Boliivia)",
  "qu_EC": "ketšua (Ecuador)",
  "qu_PE": "ketšua (Peruu)",
  "quc": "kitše",
  "qug": "Chimborazo Highland Quichua",
  "raj": "radžastani",
  "rap": "rapanui",
  "rar": "rarotonga",
  "rgn": "romanja",
  "rif": "riifi",
  "rm": "romanši",
  "rm_CH": "retoromaani (Šveits)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "rumeenia",
  "ro_MD": "rumeenia (Moldova)",
  "ro_RO": "rumeenia (Rumeenia)",
  "roa": "romaani keel",
  "rof": "rombo",
  "rom": "mustlaskeel",
  "root": "root",
  "rtm": "rotuma",
  "ru": "vene",
  "ru_BY": "vene (Valgevene)",
  "ru_KG": "vene (Kõrgõzstan)",
  "ru_KZ": "vene (Kasahstan)",
  "ru_MD": "vene (Moldova)",
  "ru_RU": "vene (Venemaa)",
  "ru_UA": "vene (Ukraina)",
  "rue": "russiini",
  "rug": "roviana",
  "rup": "aromuuni",
  "rw": "ruanda",
  "rw_RW": "ruanda (Rwanda)",
  "rwk": "rvaa",
  "sa": "sanskriti",
  "sad": "sandave",
  "sah": "jakuudi",
  "sai": "Lõuna-Ameerika indiaani keel",
  "sal": "sališi keel",
  "sam": "Samaaria aramea",
  "saq": "samburu",
  "sas": "sasaki",
  "sat": "santali",
  "saz": "sauraštra",
  "sba": "ngambai",
  "sbp": "sangu",
  "sc": "sardi",
  "scn": "sitsiilia",
  "sco": "šoti",
  "sd": "sindhi",
  "sdc": "Sassarese Sardinian",
  "sdh": "lõunakurdi",
  "se": "põhjasaami",
  "se_FI": "põhjasaami (Soome)",
  "se_NO": "põhjasaami (Norra)",
  "se_SE": "põhjasaami (Rootsi)",
  "see": "seneka",
  "seh": "sena",
  "sei": "seri",
  "sel": "sölkupi",
  "sem": "semi keel",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (Kesk-Aafrika Vabariik)",
  "sga": "vanaiiri",
  "sgn": "viipekeel",
  "sgs": "žemaidi",
  "sh": "serbia-horvaadi",
  "sh_BA": "serbia-horvaadi (Bosnia ja Hertsegoviina)",
  "shi": "šilha",
  "shn": "šani",
  "shu": "Tšaadi araabia",
  "si": "singali",
  "si_LK": "singali (Sri Lanka)",
  "sid": "sidamo",
  "sio": "siuu keel",
  "sit": "hiina-tiibeti keel",
  "sk": "slovaki",
  "sk_SK": "slovaki (Slovakkia)",
  "sl": "sloveeni",
  "sl_SI": "sloveeni (Sloveenia)",
  "sla": "slaavi keel",
  "sli": "alamsileesia",
  "sly": "selajari",
  "sm": "samoa",
  "sma": "lõunasaami",
  "smi": "muu saami",
  "smj": "Lule saami",
  "smn": "Inari saami",
  "sms": "koltasaami",
  "sn": "šona",
  "sn_ZW": "šona (Zimbabwe)",
  "snk": "soninke",
  "so": "somaali",
  "so_DJ": "somaali (Djibouti)",
  "so_ET": "somaali (Etioopia)",
  "so_KE": "somaali (Kenya)",
  "so_SO": "somaali (Somaalia)",
  "sog": "sogdi",
  "son": "songai",
  "sq": "albaania",
  "sq_AL": "albaania (Albaania)",
  "sq_MK": "albaania (Makedoonia)",
  "sq_XK": "albaania (Kosovo)",
  "sr": "serbia",
  "sr_BA": "serbia (Bosnia ja Hertsegoviina)",
  "sr_Cyrl": "serbia (kirillitsa)",
  "sr_Cyrl_BA": "serbia (kirillitsa, Bosnia ja Hertsegoviina)",
  "sr_Cyrl_ME": "serbia (kirillitsa, Montenegro)",
  "sr_Cyrl_RS": "serbia (kirillitsa, Serbia)",
  "sr_Cyrl_XK": "serbia (kirillitsa, Kosovo)",
  "sr_Latn": "serbia (ladina)",
  "sr_Latn_BA": "serbia (ladina, Bosnia ja Hertsegoviina)",
  "sr_Latn_ME": "serbia (ladina, Montenegro)",
  "sr_Latn_RS": "serbia (ladina, Serbia)",
  "sr_Latn_XK": "serbia (ladina, Kosovo)",
  "sr_ME": "serbia (Montenegro)",
  "sr_RS": "serbia (Serbia)",
  "sr_XK": "serbia (Kosovo)",
  "srn": "sranani",
  "srr": "sereri",
  "ss": "svaasi",
  "ssa": "Niiluse-Sahara keel",
  "ssy": "saho",
  "st": "lõunasotho",
  "stq": "saterfriisi",
  "su": "sunda",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumeri",
  "sv": "rootsi",
  "sv_AX": "rootsi (Ahvenamaa)",
  "sv_FI": "rootsi (Soome)",
  "sv_SE": "rootsi (Rootsi)",
  "sw": "suahiili",
  "sw_CD": "Kongo suahiili",
  "sw_KE": "suahiili (Kenya)",
  "sw_TZ": "suahiili (Tansaania)",
  "sw_UG": "suahiili (Uganda)",
  "swb": "komoori",
  "swc": "Kongo suahiili",
  "syc": "vanasüüria",
  "syr": "süüria",
  "szl": "sileesia",
  "ta": "tamili",
  "ta_IN": "tamili (India)",
  "ta_LK": "tamili (Sri Lanka)",
  "ta_MY": "tamili (Malaisia)",
  "ta_SG": "tamili (Singapur)",
  "tai": "tai keel",
  "tcy": "tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tetumi",
  "tg": "tadžiki",
  "th": "tai",
  "th_TH": "tai (Tai)",
  "ti": "tigrinja",
  "ti_ER": "tigrinja (Eritrea)",
  "ti_ET": "tigrinja (Etioopia)",
  "tig": "tigree",
  "tiv": "tivi",
  "tk": "türkmeeni",
  "tkl": "tokelau",
  "tkr": "tsahhi",
  "tl": "tagalogi",
  "tl_PH": "tagalogi (Filipiinid)",
  "tlh": "klingoni",
  "tli": "tlingiti",
  "tly": "talõši",
  "tmh": "tamašeki",
  "tn": "tsvana",
  "to": "tonga",
  "to_TO": "tonga (Tonga)",
  "tog": "tšitonga",
  "tpi": "uusmelaneesia",
  "tr": "türgi",
  "tr_CY": "türgi (Küpros)",
  "tr_TR": "türgi (Türgi)",
  "tru": "turojo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "tsakoonia",
  "tsi": "tšimši",
  "tt": "tatari",
  "ttt": "lõunataadi",
  "tum": "tumbuka",
  "tup": "tupii keeled",
  "tut": "altai keel",
  "tvl": "tuvalu",
  "tw": "tvii",
  "twq": "taswaqi",
  "ty": "tahiti",
  "tyv": "tõva",
  "tzm": "tamasikti",
  "udm": "udmurdi",
  "ug": "uiguuri",
  "ug_Arab": "uiguuri (araabia)",
  "ug_Arab_CN": "uiguuri (araabia, Hiina)",
  "ug_CN": "uiguuri (Hiina)",
  "uga": "ugariti",
  "uk": "ukraina",
  "uk_UA": "ukraina (Ukraina)",
  "umb": "umbundu",
  "und": "määramata keel",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakistan)",
  "uz": "usbeki",
  "uz_AF": "usbeki (Afganistan)",
  "uz_Arab": "usbeki (araabia)",
  "uz_Arab_AF": "usbeki (araabia, Afganistan)",
  "uz_Cyrl": "usbeki (kirillitsa)",
  "uz_Cyrl_UZ": "usbeki (kirillitsa, Usbekistan)",
  "uz_Latn": "usbeki (ladina)",
  "uz_Latn_UZ": "usbeki (ladina, Usbekistan)",
  "uz_UZ": "usbeki (Usbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "veneti",
  "vep": "vepsa",
  "vi": "vietnami",
  "vi_VN": "vietnami (Vietnam)",
  "vls": "lääneflaami",
  "vmf": "Maini frangi",
  "vo": "volapüki",
  "vot": "vadja",
  "vro": "võru",
  "vun": "vundžo",
  "wa": "vallooni",
  "wae": "valsi",
  "wak": "vakaši keel",
  "wal": "volaita",
  "war": "varai",
  "was": "vašo",
  "wbp": "varlpiri",
  "wen": "sorbi keel",
  "wo": "volofi",
  "wuu": "uu",
  "xal": "kalmõki",
  "xh": "koosa",
  "xmf": "megreli",
  "xog": "soga",
  "yao": "jao",
  "yap": "japi",
  "yav": "yangbeni",
  "ybb": "jemba",
  "yi": "jidiši",
  "yo": "joruba",
  "yo_BJ": "joruba (Benin)",
  "yo_NG": "joruba (Nigeeria)",
  "ypk": "jupiki keel",
  "yrl": "njengatu",
  "yue": "kantoni",
  "za": "tšuangi",
  "zap": "sapoteegi",
  "zbl": "Blissi sümbolid",
  "zea": "zeelandi",
  "zen": "zenaga",
  "zgh": "tamasikti (Maroko)",
  "zh": "hiina",
  "zh_CN": "hiina (Hiina)",
  "zh_HK": "hiina (Hongkong - Hiina erihalduspiirkond)",
  "zh_Hans": "hiina (hiina lihtsustatud)",
  "zh_Hans_CN": "hiina (hiina lihtsustatud, Hiina)",
  "zh_Hans_HK":
      "hiina (hiina lihtsustatud, Hongkong - Hiina erihalduspiirkond)",
  "zh_Hans_MO": "hiina (hiina lihtsustatud, Macau - Hiina erihalduspiirkond)",
  "zh_Hans_SG": "hiina (hiina lihtsustatud, Singapur)",
  "zh_Hant": "hiina (hiina traditsiooniline)",
  "zh_Hant_HK":
      "hiina (hiina traditsiooniline, Hongkong - Hiina erihalduspiirkond)",
  "zh_Hant_MO":
      "hiina (hiina traditsiooniline, Macau - Hiina erihalduspiirkond)",
  "zh_Hant_TW": "hiina (hiina traditsiooniline, Taiwan)",
  "zh_MO": "hiina (Macau - Hiina erihalduspiirkond)",
  "zh_SG": "hiina (Singapur)",
  "zh_TW": "hiina (Taiwan)",
  "znd": "zande",
  "zu": "suulu",
  "zu_ZA": "suulu (Lõuna-Aafrika Vabariik)",
  "zun": "sunji",
  "zxx": "mittekeeleline",
  "zza": "zaza"
};
