const names = {
  "001": "Lume",
  "002": "Africa",
  "003": "America de Nord",
  "005": "America de Sud",
  "009": "Oceania",
  "011": "Africa Occidentală",
  "013": "America Centrală",
  "014": "Africa Orientală",
  "015": "Africa Septentrională",
  "017": "Africa Centrală",
  "018": "Africa Meridională",
  "019": "Americi",
  "021": "America Septentrională",
  "029": "Caraibe",
  "030": "Asia Orientală",
  "034": "Asia Meridională",
  "035": "Asia de Sud-Est",
  "039": "Europa Meridională",
  "053": "Australasia",
  "054": "Melanezia",
  "057": "Regiunea Micronezia",
  "061": "Polinezia",
  "142": "Asia",
  "143": "Asia Centrală",
  "145": "Asia Occidentală",
  "150": "Europa",
  "151": "Europa Orientală",
  "154": "Europa Septentrională",
  "155": "Europa Occidentală",
  "202": "Africa Subsahariană",
  "419": "America Latină",
  "AC": "Insula Ascension",
  "AD": "Andorra",
  "AE": "Emiratele Arabe Unite",
  "AF": "Afganistan",
  "AG": "Antigua și Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antilele Olandeze",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "Samoa Americană",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Insulele Åland",
  "AZ": "Azerbaidjan",
  "Arab": "arabă",
  "Aran": "nastaaliq",
  "Armn": "armeană",
  "BA": "Bosnia și Herțegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Insulele Caraibe Olandeze",
  "BR": "Brazilia",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Insula Bouvet",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "balineză",
  "Beng": "bengaleză",
  "Bopo": "bopomofo",
  "Brai": "braille",
  "CA": "Canada",
  "CC": "Insulele Cocos (Keeling)",
  "CD": "Congo - Kinshasa",
  "CF": "Republica Centrafricană",
  "CG": "Congo - Brazzaville",
  "CH": "Elveția",
  "CI": "Côte d’Ivoire",
  "CK": "Insulele Cook",
  "CL": "Chile",
  "CM": "Camerun",
  "CN": "China",
  "CO": "Columbia",
  "CP": "Insula Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia și Muntenegru",
  "CU": "Cuba",
  "CV": "Capul Verde",
  "CW": "Curaçao",
  "CX": "Insula Christmas",
  "CY": "Cipru",
  "CZ": "Cehia",
  "Cans": "silabică aborigenă canadiană unificată",
  "Copt": "coptă",
  "Cprt": "cipriotă",
  "Cyrl": "chirilică",
  "Cyrs": "chirilică slavonă bisericească veche",
  "DE": "Germania",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Danemarca",
  "DM": "Dominica",
  "DO": "Republica Dominicană",
  "DZ": "Algeria",
  "Deva": "devanagari",
  "Dsrt": "mormonă",
  "EA": "Ceuta și Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egipt",
  "EH": "Sahara Occidentală",
  "ER": "Eritreea",
  "ES": "Spania",
  "ET": "Etiopia",
  "EU": "Uniunea Europeană",
  "EZ": "Zona euro",
  "Egyd": "demotică egipteană",
  "Egyh": "hieratică egipteană",
  "Egyp": "hieroglife egiptene",
  "Ethi": "etiopiană",
  "FI": "Finlanda",
  "FJ": "Fiji",
  "FK": "Insulele Falkland",
  "FM": "Micronezia",
  "FO": "Insulele Feroe",
  "FR": "Franța",
  "FX": "Franța metropolitană",
  "GA": "Gabon",
  "GB": "Regatul Unit",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Guyana Franceză",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenlanda",
  "GM": "Gambia",
  "GN": "Guineea",
  "GP": "Guadelupa",
  "GQ": "Guineea Ecuatorială",
  "GR": "Grecia",
  "GS": "Georgia de Sud și Insulele Sandwich de Sud",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guineea-Bissau",
  "GY": "Guyana",
  "Geok": "georgiană bisericească",
  "Geor": "georgiană",
  "Glag": "glagolitică",
  "Goth": "gotică",
  "Grek": "greacă",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "R.A.S. Hong Kong a Chinei",
  "HM": "Insula Heard și Insulele McDonald",
  "HN": "Honduras",
  "HR": "Croația",
  "HT": "Haiti",
  "HU": "Ungaria",
  "Hanb": "hanb",
  "Hang": "hangul",
  "Hani": "han",
  "Hans": "simplificată",
  "Hant": "tradițională",
  "Hebr": "ebraică",
  "Hira": "hiragana",
  "Hrkt": "silabică japoneză",
  "Hung": "maghiară veche",
  "IC": "Insulele Canare",
  "ID": "Indonezia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Insula Man",
  "IN": "India",
  "IO": "Teritoriul Britanic din Oceanul Indian",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Islanda",
  "IT": "Italia",
  "Inds": "indus",
  "Ital": "italică veche",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Iordania",
  "JP": "Japonia",
  "Jamo": "jamo",
  "Java": "javaneză",
  "Jpan": "japoneză",
  "KE": "Kenya",
  "KG": "Kârgâzstan",
  "KH": "Cambodgia",
  "KI": "Kiribati",
  "KM": "Comore",
  "KN": "Saint Kitts și Nevis",
  "KP": "Coreea de Nord",
  "KR": "Coreea de Sud",
  "KW": "Kuweit",
  "KY": "Insulele Cayman",
  "KZ": "Kazahstan",
  "Kana": "katakana",
  "Khmr": "khmeră",
  "Knda": "kannada",
  "Kore": "coreeană",
  "LA": "Laos",
  "LB": "Liban",
  "LC": "Sfânta Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lituania",
  "LU": "Luxemburg",
  "LV": "Letonia",
  "LY": "Libia",
  "Laoo": "laoțiană",
  "Latf": "latină Fraktur",
  "Latg": "latină gaelică",
  "Latn": "latină",
  "Lina": "lineară A",
  "Linb": "lineară B",
  "Lydi": "lidiană",
  "MA": "Maroc",
  "MC": "Monaco",
  "MD": "Republica Moldova",
  "ME": "Muntenegru",
  "MF": "Sfântul Martin",
  "MG": "Madagascar",
  "MH": "Insulele Marshall",
  "MK": "Macedonia de Nord",
  "ML": "Mali",
  "MM": "Myanmar (Birmania)",
  "MN": "Mongolia",
  "MO": "R.A.S. Macao, China",
  "MP": "Insulele Mariane de Nord",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldive",
  "MW": "Malawi",
  "MX": "Mexic",
  "MY": "Malaysia",
  "MZ": "Mozambic",
  "Maya": "hieroglife maya",
  "Mlym": "malayalam",
  "Mong": "mongolă",
  "Mtei": "meitei mayek",
  "Mymr": "birmană",
  "NA": "Namibia",
  "NC": "Noua Caledonie",
  "NE": "Niger",
  "NF": "Insula Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Țările de Jos",
  "NO": "Norvegia",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Noua Zeelandă",
  "OM": "Oman",
  "Olck": "ol chiki",
  "Orya": "oriya",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Polinezia Franceză",
  "PG": "Papua-Noua Guinee",
  "PH": "Filipine",
  "PK": "Pakistan",
  "PL": "Polonia",
  "PM": "Saint-Pierre și Miquelon",
  "PN": "Insulele Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Teritoriile Palestiniene",
  "PT": "Portugalia",
  "PW": "Palau",
  "PY": "Paraguay",
  "Phnx": "feniciană",
  "QA": "Qatar",
  "QO": "Oceania Periferică",
  "Qaag": "zawgyi",
  "RE": "Réunion",
  "RO": "România",
  "RS": "Serbia",
  "RU": "Rusia",
  "RW": "Rwanda",
  "Runr": "runică",
  "SA": "Arabia Saudită",
  "SB": "Insulele Solomon",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Suedia",
  "SG": "Singapore",
  "SH": "Sfânta Elena",
  "SI": "Slovenia",
  "SJ": "Svalbard și Jan Mayen",
  "SK": "Slovacia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Sudanul de Sud",
  "ST": "São Tomé și Príncipe",
  "SV": "El Salvador",
  "SX": "Sint-Maarten",
  "SY": "Siria",
  "SZ": "eSwatini",
  "Sinh": "singaleză",
  "Syrc": "siriacă",
  "Syrj": "siriacă occidentală",
  "Syrn": "siriacă orientală",
  "TA": "Tristan da Cunha",
  "TC": "Insulele Turks și Caicos",
  "TD": "Ciad",
  "TF": "Teritoriile Australe și Antarctice Franceze",
  "TG": "Togo",
  "TH": "Thailanda",
  "TJ": "Tadjikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turcia",
  "TT": "Trinidad și Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Taml": "tamilă",
  "Telu": "telugu",
  "Tfng": "berberă",
  "Thaa": "thaana",
  "Thai": "thailandeză",
  "Tibt": "tibetană",
  "UA": "Ucraina",
  "UG": "Uganda",
  "UM": "Insulele Îndepărtate ale S.U.A.",
  "UN": "Națiunile Unite",
  "US": "Statele Unite ale Americii",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Statul Cetății Vaticanului",
  "VC": "Saint Vincent și Grenadinele",
  "VE": "Venezuela",
  "VG": "Insulele Virgine Britanice",
  "VI": "Insulele Virgine Americane",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis și Futuna",
  "WS": "Samoa",
  "XA": "Pseudo-accente",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "persană veche",
  "Xsux": "cuneiformă sumero-akkadiană",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "Africa de Sud",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Regiune necunoscută",
  "Zinh": "moștenită",
  "Zmth": "notație matematică",
  "Zsye": "emoji",
  "Zsym": "simboluri",
  "Zxxx": "nescrisă",
  "Zyyy": "comună",
  "Zzzz": "scriere necunoscută",
  "aa": "afar",
  "ab": "abhază",
  "ace": "aceh",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adyghe",
  "ae": "avestană",
  "aeb": "Tunisian Arabic",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibia)",
  "af_ZA": "afrikaans (Africa de Sud)",
  "afa": "limbă afro-asiatică",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "akkadiană",
  "akz": "Alabama",
  "ale": "aleută",
  "aln": "Gheg Albanian",
  "alt": "altaică meridională",
  "am": "amharică",
  "am_ET": "amharică (Etiopia)",
  "an": "aragoneză",
  "ang": "engleză veche",
  "anp": "angika",
  "apa": "limbă apașă",
  "ar": "arabă",
  "ar_001": "arabă standard modernă",
  "ar_AE": "arabă (Emiratele Arabe Unite)",
  "ar_BH": "arabă (Bahrain)",
  "ar_DJ": "arabă (Djibouti)",
  "ar_DZ": "arabă (Algeria)",
  "ar_EG": "arabă (Egipt)",
  "ar_EH": "arabă (Sahara Occidentală)",
  "ar_ER": "arabă (Eritreea)",
  "ar_IL": "arabă (Israel)",
  "ar_IQ": "arabă (Irak)",
  "ar_JO": "arabă (Iordania)",
  "ar_KM": "arabă (Comore)",
  "ar_KW": "arabă (Kuweit)",
  "ar_LB": "arabă (Liban)",
  "ar_LY": "arabă (Libia)",
  "ar_MA": "arabă (Maroc)",
  "ar_MR": "arabă (Mauritania)",
  "ar_OM": "arabă (Oman)",
  "ar_PS": "arabă (Teritoriile Palestiniene)",
  "ar_QA": "arabă (Qatar)",
  "ar_SA": "arabă (Arabia Saudită)",
  "ar_SD": "arabă (Sudan)",
  "ar_SO": "arabă (Somalia)",
  "ar_SS": "arabă (Sudanul de Sud)",
  "ar_SY": "arabă (Siria)",
  "ar_TD": "arabă (Ciad)",
  "ar_TN": "arabă (Tunisia)",
  "ar_YE": "arabă (Yemen)",
  "arc": "aramaică",
  "arn": "araucaniană",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "ars": "arabă najdi",
  "art": "limbă artificială",
  "arw": "arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "asameză",
  "as_IN": "asameză (India)",
  "asa": "asu",
  "ase": "American Sign Language",
  "ast": "asturiană",
  "aus": "limbă australiană",
  "av": "avară",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aymara",
  "az": "azeră",
  "az_AZ": "azeră (Azerbaidjan)",
  "az_Cyrl": "azeră (chirilică)",
  "az_Cyrl_AZ": "azeră (chirilică, Azerbaidjan)",
  "az_Latn": "azeră (latină)",
  "az_Latn_AZ": "azeră (latină, Azerbaidjan)",
  "azb": "South Azerbaijani",
  "ba": "bașkiră",
  "bal": "baluchi",
  "ban": "balineză",
  "bar": "Bavarian",
  "bas": "basaa",
  "bat": "limbă baltică",
  "bax": "bamun",
  "bbc": "Batak Toba",
  "bbj": "ghomala",
  "be": "belarusă",
  "be_BY": "bielorusă (Belarus)",
  "bej": "beja",
  "bem": "bemba",
  "ber": "berberă",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "Badaga",
  "bg": "bulgară",
  "bg_BG": "bulgară (Bulgaria)",
  "bgn": "baluchi occidentală",
  "bh": "bihari",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latină)",
  "bm_Latn_ML": "bambara (latină, Mali)",
  "bn": "bengaleză",
  "bn_BD": "bengaleză (Bangladesh)",
  "bn_IN": "bengaleză (India)",
  "bnt": "bantu",
  "bo": "tibetană",
  "bo_CN": "tibetană (China)",
  "bo_IN": "tibetană (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretonă",
  "br_FR": "bretonă (Franța)",
  "bra": "braj",
  "brh": "Brahui",
  "brx": "bodo",
  "bs": "bosniacă",
  "bs_BA": "bosniacă (Bosnia și Herțegovina)",
  "bs_Cyrl": "bosniacă (chirilică)",
  "bs_Cyrl_BA": "bosniacă (chirilică, Bosnia și Herțegovina)",
  "bs_Latn": "bosniacă (latină)",
  "bs_Latn_BA": "bosniacă (latină, Bosnia și Herțegovina)",
  "bss": "akoose",
  "bua": "buriat",
  "bug": "bugineză",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "catalană",
  "ca_AD": "catalană (Andorra)",
  "ca_ES": "catalană (Spania)",
  "ca_FR": "catalană (Franța)",
  "ca_IT": "catalană (Italia)",
  "cad": "caddo",
  "cai": "limbă central-amerindiană",
  "car": "carib",
  "cau": "limbă caucaziană",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "chakma",
  "ce": "cecenă",
  "ceb": "cebuană",
  "cel": "limbă celtică",
  "cgg": "chiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "chagatai",
  "chk": "chuukese",
  "chm": "mari",
  "chn": "jargon chinook",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cherokee",
  "chy": "cheyenne",
  "ckb": "kurdă centrală",
  "co": "corsicană",
  "cop": "coptă",
  "cps": "Capiznon",
  "cr": "cree",
  "crh": "turcă crimeeană",
  "crs": "creolă franceză seselwa",
  "cs": "cehă",
  "cs_CZ": "cehă (Republica Cehă)",
  "csb": "cașubiană",
  "cu": "slavonă",
  "cv": "ciuvașă",
  "cy": "galeză",
  "cy_GB": "galeză (Regatul Unit)",
  "da": "daneză",
  "da_DK": "daneză (Danemarca)",
  "da_GL": "daneză (Groenlanda)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "de": "germană",
  "de_AT": "germană (Austria)",
  "de_BE": "germană (Belgia)",
  "de_CH": "germană (Elveția)",
  "de_DE": "germană (Germania)",
  "de_LI": "germană (Liechtenstein)",
  "de_LU": "germană (Luxemburg)",
  "del": "delaware",
  "den": "slave",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "limbă dravidiană",
  "dsb": "sorabă de jos",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "neerlandeză medie",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "dyula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhutan)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "ewe",
  "ee_GH": "ewe (Ghana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "egipteană veche",
  "eka": "ekajuk",
  "el": "greacă",
  "el_CY": "greacă (Cipru)",
  "el_GR": "greacă (Grecia)",
  "elx": "elamită",
  "en": "engleză",
  "en_AG": "engleză (Antigua și Barbuda)",
  "en_AI": "engleză (Anguilla)",
  "en_AS": "engleză (Samoa Americană)",
  "en_AU": "engleză (Australia)",
  "en_BB": "engleză (Barbados)",
  "en_BE": "engleză (Belgia)",
  "en_BM": "engleză (Bermuda)",
  "en_BS": "engleză (Bahamas)",
  "en_BW": "engleză (Botswana)",
  "en_BZ": "engleză (Belize)",
  "en_CA": "engleză (Canada)",
  "en_CC": "engleză (Insulele Cocos (Keeling))",
  "en_CK": "engleză (Insulele Cook)",
  "en_CM": "engleză (Camerun)",
  "en_CX": "engleză (Insula Christmas)",
  "en_DG": "engleză (Diego Garcia)",
  "en_DM": "engleză (Dominica)",
  "en_ER": "engleză (Eritreea)",
  "en_FJ": "engleză (Fiji)",
  "en_FK": "engleză (Insulele Falkland)",
  "en_FM": "engleză (Micronezia)",
  "en_GB": "engleză (Regatul Unit)",
  "en_GD": "engleză (Grenada)",
  "en_GG": "engleză (Guernsey)",
  "en_GH": "engleză (Ghana)",
  "en_GI": "engleză (Gibraltar)",
  "en_GM": "engleză (Gambia)",
  "en_GU": "engleză (Guam)",
  "en_GY": "engleză (Guyana)",
  "en_HK": "engleză (R.A.S. Hong Kong a Chinei)",
  "en_IE": "engleză (Irlanda)",
  "en_IM": "engleză (Insula Man)",
  "en_IN": "engleză (India)",
  "en_IO": "engleză (Teritoriul Britanic din Oceanul Indian)",
  "en_JE": "engleză (Jersey)",
  "en_JM": "engleză (Jamaica)",
  "en_KE": "engleză (Kenya)",
  "en_KI": "engleză (Kiribati)",
  "en_KN": "engleză (Saint Kitts și Nevis)",
  "en_KY": "engleză (Insulele Cayman)",
  "en_LC": "engleză (Sfânta Lucia)",
  "en_LR": "engleză (Liberia)",
  "en_LS": "engleză (Lesotho)",
  "en_MG": "engleză (Madagascar)",
  "en_MH": "engleză (Insulele Marshall)",
  "en_MO": "engleză (R.A.S. Macao a Chinei)",
  "en_MP": "engleză (Insulele Mariane de Nord)",
  "en_MS": "engleză (Montserrat)",
  "en_MT": "engleză (Malta)",
  "en_MU": "engleză (Mauritius)",
  "en_MW": "engleză (Malawi)",
  "en_MY": "engleză (Malaezia)",
  "en_NA": "engleză (Namibia)",
  "en_NF": "engleză (Insulele Norfolk)",
  "en_NG": "engleză (Nigeria)",
  "en_NR": "engleză (Nauru)",
  "en_NU": "engleză (Niue)",
  "en_NZ": "engleză (Noua Zeelandă)",
  "en_PG": "engleză (Papua-Noua Guinee)",
  "en_PH": "engleză (Filipine)",
  "en_PK": "engleză (Pakistan)",
  "en_PN": "engleză (Insulele Pitcairn)",
  "en_PR": "engleză (Puerto Rico)",
  "en_PW": "engleză (Palau)",
  "en_RW": "engleză (Rwanda)",
  "en_SB": "engleză (Insulele Solomon)",
  "en_SC": "engleză (Seychelles)",
  "en_SD": "engleză (Sudan)",
  "en_SG": "engleză (Singapore)",
  "en_SH": "engleză (Sfânta Elena)",
  "en_SL": "engleză (Sierra Leone)",
  "en_SS": "engleză (Sudanul de Sud)",
  "en_SX": "engleză (Sint-Maarten)",
  "en_SZ": "engleză (Swaziland)",
  "en_TC": "engleză (Insulele Turks și Caicos)",
  "en_TK": "engleză (Tokelau)",
  "en_TO": "engleză (Tonga)",
  "en_TT": "engleză (Trinidad și Tobago)",
  "en_TV": "engleză (Tuvalu)",
  "en_TZ": "engleză (Tanzania)",
  "en_UG": "engleză (Uganda)",
  "en_UM": "engleză (Insulele Îndepărtate ale S.U.A.)",
  "en_US": "engleză (Statele Unite ale Americii)",
  "en_VC": "engleză (Saint Vincent și Grenadine)",
  "en_VG": "engleză (Insulele Virgine Britanice)",
  "en_VI": "engleză (Insulele Virgine S.U.A.)",
  "en_VU": "engleză (Vanuatu)",
  "en_WS": "engleză (Samoa)",
  "en_ZA": "engleză (Africa de Sud)",
  "en_ZM": "engleză (Zambia)",
  "en_ZW": "engleză (Zimbabwe)",
  "enm": "engleză medie",
  "eo": "esperanto",
  "es": "spaniolă",
  "es_419": "spaniolă latino-americană",
  "es_AR": "spaniolă (Argentina)",
  "es_BO": "spaniolă (Bolivia)",
  "es_CL": "spaniolă (Chile)",
  "es_CO": "spaniolă (Columbia)",
  "es_CR": "spaniolă (Costa Rica)",
  "es_CU": "spaniolă (Cuba)",
  "es_DO": "spaniolă (Republica Dominicană)",
  "es_EA": "spaniolă (Ceuta și Melilla)",
  "es_EC": "spaniolă (Ecuador)",
  "es_ES": "spaniolă (Spania)",
  "es_GQ": "spaniolă (Guineea Ecuatorială)",
  "es_GT": "spaniolă (Guatemala)",
  "es_HN": "spaniolă (Honduras)",
  "es_IC": "spaniolă (Insulele Canare)",
  "es_MX": "spaniolă (Mexic)",
  "es_NI": "spaniolă (Nicaragua)",
  "es_PA": "spaniolă (Panama)",
  "es_PE": "spaniolă (Peru)",
  "es_PH": "spaniolă (Filipine)",
  "es_PR": "spaniolă (Puerto Rico)",
  "es_PY": "spaniolă (Paraguay)",
  "es_SV": "spaniolă (El Salvador)",
  "es_US": "spaniolă (Statele Unite ale Americii)",
  "es_UY": "spaniolă (Uruguay)",
  "es_VE": "spaniolă (Venezuela)",
  "esu": "Central Yupik",
  "et": "estonă",
  "et_EE": "estoniană (Estonia)",
  "eu": "bască",
  "eu_ES": "bască (Spania)",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fa": "persană",
  "fa_AF": "persană (Afganistan)",
  "fa_IR": "persană (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fulah",
  "ff_CM": "fulah (Camerun)",
  "ff_GN": "fulah (Guineea)",
  "ff_MR": "fulah (Mauritania)",
  "ff_SN": "fulah (Senegal)",
  "fi": "finlandeză",
  "fi_FI": "finlandeză (Finlanda)",
  "fil": "filipineză",
  "fit": "Tornedalen Finnish",
  "fiu": "limbă fino-ugrică",
  "fj": "fijiană",
  "fo": "faroeză",
  "fo_FO": "faroeză (Insulele Feroe)",
  "fon": "fon",
  "fr": "franceză",
  "fr_BE": "franceză (Belgia)",
  "fr_BF": "franceză (Burkina Faso)",
  "fr_BI": "franceză (Burundi)",
  "fr_BJ": "franceză (Benin)",
  "fr_BL": "franceză (Sfântul Bartolomeu)",
  "fr_CA": "franceză (Canada)",
  "fr_CD": "franceză (Congo - Kinshasa)",
  "fr_CF": "franceză (Republica Centrafricană)",
  "fr_CG": "franceză (Congo - Brazzaville)",
  "fr_CH": "franceză (Elveția)",
  "fr_CI": "franceză (Côte d’Ivoire)",
  "fr_CM": "franceză (Camerun)",
  "fr_DJ": "franceză (Djibouti)",
  "fr_DZ": "franceză (Algeria)",
  "fr_FR": "franceză (Franța)",
  "fr_GA": "franceză (Gabon)",
  "fr_GF": "franceză (Guyana Franceză)",
  "fr_GN": "franceză (Guineea)",
  "fr_GP": "franceză (Guadelupa)",
  "fr_GQ": "franceză (Guineea Ecuatorială)",
  "fr_HT": "franceză (Haiti)",
  "fr_KM": "franceză (Comore)",
  "fr_LU": "franceză (Luxemburg)",
  "fr_MA": "franceză (Maroc)",
  "fr_MC": "franceză (Monaco)",
  "fr_MF": "franceză (Sfântul Martin)",
  "fr_MG": "franceză (Madagascar)",
  "fr_ML": "franceză (Mali)",
  "fr_MQ": "franceză (Martinica)",
  "fr_MR": "franceză (Mauritania)",
  "fr_MU": "franceză (Mauritius)",
  "fr_NC": "franceză (Noua Caledonie)",
  "fr_NE": "franceză (Niger)",
  "fr_PF": "franceză (Polinezia Franceză)",
  "fr_PM": "franceză (Saint-Pierre și Miquelon)",
  "fr_RE": "franceză (Réunion)",
  "fr_RW": "franceză (Rwanda)",
  "fr_SC": "franceză (Seychelles)",
  "fr_SN": "franceză (Senegal)",
  "fr_SY": "franceză (Siria)",
  "fr_TD": "franceză (Ciad)",
  "fr_TG": "franceză (Togo)",
  "fr_TN": "franceză (Tunisia)",
  "fr_VU": "franceză (Vanuatu)",
  "fr_WF": "franceză (Wallis și Futuna)",
  "fr_YT": "franceză (Mayotte)",
  "frc": "franceză cajun",
  "frm": "franceză medie",
  "fro": "franceză veche",
  "frp": "Arpitan",
  "frr": "frizonă nordică",
  "frs": "frizonă orientală",
  "fur": "friulană",
  "fy": "frizonă occidentală",
  "fy_NL": "frizonă occidentală (Țările de Jos)",
  "ga": "irlandeză",
  "ga_IE": "irlandeză (Irlanda)",
  "gaa": "ga",
  "gag": "găgăuză",
  "gan": "chineză gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "gaelică scoțiană",
  "gd_GB": "gaelică scoțiană (Regatul Unit)",
  "gem": "limbă germanică",
  "gez": "geez",
  "gil": "gilbertină",
  "gl": "galiciană",
  "gl_ES": "galiciană (Spania)",
  "glk": "Gilaki",
  "gmh": "germană înaltă medie",
  "gn": "guarani",
  "goh": "germană înaltă veche",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotică",
  "grb": "grebo",
  "grc": "greacă veche",
  "gsw": "germană (Elveția)",
  "gu": "gujarati",
  "gu_IN": "gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusii",
  "gv": "manx",
  "gv_IM": "manx (Insula Man)",
  "gwi": "gwichʼin",
  "ha": "hausa",
  "ha_GH": "hausa (Ghana)",
  "ha_Latn": "hausa (latină)",
  "ha_Latn_GH": "hausa (latină, Ghana)",
  "ha_Latn_NE": "hausa (latină, Niger)",
  "ha_Latn_NG": "hausa (latină, Nigeria)",
  "ha_NE": "hausa (Niger)",
  "ha_NG": "hausa (Nigeria)",
  "hai": "haida",
  "hak": "chineză hakka",
  "haw": "hawaiiană",
  "he": "ebraică",
  "he_IL": "ebraică (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "hit": "hitită",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croată",
  "hr_BA": "croată (Bosnia și Herțegovina)",
  "hr_HR": "croată (Croația)",
  "hsb": "sorabă de sus",
  "hsn": "chineză xiang",
  "ht": "haitiană",
  "hu": "maghiară",
  "hu_HU": "maghiară (Ungaria)",
  "hup": "hupa",
  "hy": "armeană",
  "hy_AM": "armeană (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indoneziană",
  "id_ID": "indoneziană (Indonezia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigeria)",
  "ii": "yi din Sichuan",
  "ii_CN": "sichuan yi (China)",
  "ik": "inupiak",
  "ilo": "iloko",
  "inc": "limbă indiană",
  "ine": "limbă indo-europeană",
  "inh": "ingușă",
  "io": "ido",
  "ira": "limbă iraniană",
  "is": "islandeză",
  "is_IS": "islandeză (Islanda)",
  "it": "italiană",
  "it_CH": "italiană (Elveția)",
  "it_IT": "italiană (Italia)",
  "it_SM": "italiană (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "japoneză",
  "ja_JP": "japoneză (Japonia)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "iudeo-persană",
  "jrb": "iudeo-arabă",
  "jut": "Jutish",
  "jv": "javaneză",
  "ka": "georgiană",
  "ka_GE": "georgiană (Georgia)",
  "kaa": "karakalpak",
  "kab": "kabyle",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kaw": "kawi",
  "kbd": "kabardian",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "kabuverdianu",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "congoleză",
  "kgp": "Kaingang",
  "kha": "khasi",
  "kho": "khotaneză",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "kazahă",
  "kk_Cyrl": "kazahă (chirilică)",
  "kk_Cyrl_KZ": "kazahă (chirilică, Kazahstan)",
  "kk_KZ": "kazahă (Kazahstan)",
  "kkj": "kako",
  "kl": "kalaallisut",
  "kl_GL": "kalaallisut (Groenlanda)",
  "kln": "kalenjin",
  "km": "khmeră",
  "km_KH": "khmeră (Cambodgia)",
  "kmb": "kimbundu",
  "kn": "kannada",
  "kn_IN": "kannada (India)",
  "ko": "coreeană",
  "ko_KP": "coreeană (Coreea de Nord)",
  "ko_KR": "coreeană (Coreea de Sud)",
  "koi": "komi-permiak",
  "kok": "konkani",
  "kos": "kosrae",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karaceai-balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "kareliană",
  "kru": "kurukh",
  "ks": "cașmiră",
  "ks_Arab": "cașmiră (arabă)",
  "ks_Arab_IN": "cașmiră (arabă, India)",
  "ks_IN": "cașmiră (India)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kölsch",
  "ku": "kurdă",
  "kum": "kumyk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "cornică",
  "kw_GB": "cornică (Regatul Unit)",
  "ky": "kârgâză",
  "ky_Cyrl": "kârgâză (chirilică)",
  "ky_Cyrl_KG": "kârgâză (chirilică, Kârgâzstan)",
  "ky_KG": "kârgâză (Kârgâzstan)",
  "la": "latină",
  "lad": "ladino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxemburgheză",
  "lb_LU": "luxemburgheză (Luxemburg)",
  "lez": "lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgheză",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Congo - Kinshasa)",
  "ln_CF": "lingala (Republica Centrafricană)",
  "ln_CG": "lingala (Congo - Brazzaville)",
  "lo": "laoțiană",
  "lo_LA": "laoțiană (Laos)",
  "lol": "mongo",
  "lou": "creolă (Louisiana)",
  "loz": "lozi",
  "lrc": "luri de nord",
  "lt": "lituaniană",
  "lt_LT": "lituaniană (Lituania)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Congo - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "mizo",
  "luy": "luyia",
  "lv": "letonă",
  "lv_LV": "letonă (Letonia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "madureză",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "mandingo",
  "map": "austroneziană",
  "mas": "masai",
  "mde": "maba",
  "mdf": "moksha",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "morisyen",
  "mg": "malgașă",
  "mg_MG": "malgașă (Madagascar)",
  "mga": "irlandeză medie",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshalleză",
  "mi": "maori",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "limbi diverse",
  "mk": "macedoneană",
  "mk_MK": "macedoneană (Macedonia)",
  "ml": "malayalam",
  "ml_IN": "malayalam (India)",
  "mn": "mongolă",
  "mn_Cyrl": "mongolă (chirilică)",
  "mn_Cyrl_MN": "mongolă (chirilică, Mongolia)",
  "mn_MN": "mongolă (Mongolia)",
  "mnc": "manciuriană",
  "mni": "manipuri",
  "mo": "moldovenească",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "Western Mari",
  "ms": "malaeză",
  "ms_BN": "malaeză (Brunei)",
  "ms_Latn": "malaeză (latină)",
  "ms_Latn_BN": "malaeză (latină, Brunei)",
  "ms_Latn_MY": "malaeză (latină, Malaezia)",
  "ms_Latn_SG": "malaeză (latină, Singapore)",
  "ms_MY": "malaeză (Malaezia)",
  "ms_SG": "malaeză (Singapore)",
  "mt": "malteză",
  "mt_MT": "malteză (Malta)",
  "mua": "mundang",
  "mul": "mai multe limbi",
  "mun": "limbă munda",
  "mus": "creek",
  "mwl": "mirandeză",
  "mwr": "marwari",
  "mwv": "Mentawai",
  "my": "birmană",
  "my_MM": "birmaneză (Myanmar (Birmania))",
  "mye": "myene",
  "myn": "limbă mayașă",
  "myv": "erzya",
  "mzn": "mazanderani",
  "na": "nauru",
  "nai": "limbă nord-amerindiană",
  "nan": "chineză min nan",
  "nap": "napolitană",
  "naq": "nama",
  "nb": "norvegiană bokmål",
  "nb_NO": "norvegiană bokmål (Norvegia)",
  "nb_SJ": "norvegiană bokmål (Svalbard și Jan Mayen)",
  "nd": "ndebele de nord",
  "nd_ZW": "ndebele de nord (Zimbabwe)",
  "nds": "germana de jos",
  "nds_NL": "saxona de jos",
  "ne": "nepaleză",
  "ne_IN": "nepaleză (India)",
  "ne_NP": "nepaleză (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "niu": "niueană",
  "njo": "Ao Naga",
  "nl": "neerlandeză",
  "nl_AW": "olandeză (Aruba)",
  "nl_BE": "olandeză (Belgia)",
  "nl_BQ": "olandeză (Insulele Caraibe Olandeze)",
  "nl_CW": "olandeză (Curaçao)",
  "nl_NL": "olandeză (Țările de Jos)",
  "nl_SR": "olandeză (Surinam)",
  "nl_SX": "olandeză (Sint-Maarten)",
  "nmg": "kwasio",
  "nn": "norvegiană nynorsk",
  "nn_NO": "norvegiană nynorsk (Norvegia)",
  "nnh": "ngiemboon",
  "no": "norvegiană",
  "no_NO": "norvegiană (Norvegia)",
  "nog": "nogai",
  "non": "nordică veche",
  "nov": "Novial",
  "nqo": "n’ko",
  "nr": "ndebele de sud",
  "nso": "sotho de nord",
  "nub": "limbă nubiană",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "newari clasică",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "occitană",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiopia)",
  "om_KE": "oromo (Kenya)",
  "or": "odia",
  "or_IN": "oriya (India)",
  "os": "osetă",
  "os_GE": "osetă (Georgia)",
  "os_RU": "osetă (Rusia)",
  "osa": "osage",
  "ota": "turcă otomană",
  "oto": "limbă otomi",
  "pa": "punjabi",
  "pa_Arab": "punjabi (arabă)",
  "pa_Arab_PK": "punjabi (arabă, Pakistan)",
  "pa_Guru": "punjabi (gurmukhi)",
  "pa_Guru_IN": "punjabi (gurmukhi, India)",
  "pa_IN": "punjabi (India)",
  "pa_PK": "punjabi (Pakistan)",
  "paa": "limbă papuașă",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palauană",
  "pcd": "Picard",
  "pcm": "pidgin nigerian",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "persană veche",
  "pfl": "Palatine German",
  "phi": "limbă filipineză",
  "phn": "feniciană",
  "pi": "pali",
  "pl": "poloneză",
  "pl_PL": "poloneză (Polonia)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "pohnpeiană",
  "prg": "prusacă",
  "pro": "provensală veche",
  "ps": "paștună",
  "ps_AF": "paștună (Afganistan)",
  "pt": "portugheză",
  "pt_AO": "portugheză (Angola)",
  "pt_BR": "portugheză (Brazilia)",
  "pt_CV": "portugheză (Capul Verde)",
  "pt_GW": "portugheză (Guineea-Bissau)",
  "pt_MO": "portugheză (R.A.S. Macao a Chinei)",
  "pt_MZ": "portugheză (Mozambic)",
  "pt_PT": "portugheză (Portugalia)",
  "pt_ST": "portugheză (Sao Tome și Principe)",
  "pt_TL": "portugheză (Timorul de Est)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivia)",
  "qu_EC": "quechua (Ecuador)",
  "qu_PE": "quechua (Peru)",
  "quc": "kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "romanșă",
  "rm_CH": "romanșă (Elveția)",
  "rn": "kirundi",
  "rn_BI": "kirundi (Burundi)",
  "ro": "română",
  "ro_MD": "română (Republica Moldova)",
  "ro_RO": "română (România)",
  "roa": "limbă romanică",
  "rof": "rombo",
  "rom": "romani",
  "root": "rădăcină",
  "rtm": "Rotuman",
  "ru": "rusă",
  "ru_BY": "rusă (Belarus)",
  "ru_KG": "rusă (Kârgâzstan)",
  "ru_KZ": "rusă (Kazahstan)",
  "ru_MD": "rusă (Republica Moldova)",
  "ru_RU": "rusă (Rusia)",
  "ru_UA": "rusă (Ucraina)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromână",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Rwanda)",
  "rwk": "rwa",
  "sa": "sanscrită",
  "sad": "sandawe",
  "sah": "sakha",
  "sai": "limbă sud-amerindiană",
  "sam": "aramaică samariteană",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardiniană",
  "scn": "siciliană",
  "sco": "scots",
  "sd": "sindhi",
  "sdc": "Sassarese Sardinian",
  "sdh": "kurdă de sud",
  "se": "sami de nord",
  "se_FI": "sami de nord (Finlanda)",
  "se_NO": "sami de nord (Norvegia)",
  "se_SE": "sami de nord (Suedia)",
  "see": "seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "selkup",
  "sem": "limbă semitică",
  "ses": "koyraboro Senni",
  "sg": "sango",
  "sg_CF": "sango (Republica Centrafricană)",
  "sga": "irlandeză veche",
  "sgn": "limbaj mimico-gestual",
  "sgs": "Samogitian",
  "sh": "sârbo-croată",
  "sh_BA": "sârbo-croată (Bosnia și Herțegovina)",
  "shi": "tachelhit",
  "shn": "shan",
  "shu": "arabă ciadiană",
  "si": "singhaleză",
  "si_LK": "singhaleză (Sri Lanka)",
  "sid": "sidamo",
  "sit": "limbă sino-tibetană",
  "sk": "slovacă",
  "sk_SK": "slovacă (Slovacia)",
  "sl": "slovenă",
  "sl_SI": "slovenă (Slovenia)",
  "sla": "limbă slavă",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoană",
  "sma": "sami de sud",
  "smj": "sami lule",
  "smn": "sami inari",
  "sms": "sami skolt",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabwe)",
  "snk": "soninke",
  "so": "somaleză",
  "so_DJ": "somaleză (Djibouti)",
  "so_ET": "somaleză (Etiopia)",
  "so_KE": "somaleză (Kenya)",
  "so_SO": "somaleză (Somalia)",
  "sog": "sogdien",
  "sq": "albaneză",
  "sq_AL": "albaneză (Albania)",
  "sq_MK": "albaneză (Macedonia)",
  "sq_XK": "albaneză (Kosovo)",
  "sr": "sârbă",
  "sr_BA": "sârbă (Bosnia și Herțegovina)",
  "sr_Cyrl": "sârbă (chirilică)",
  "sr_Cyrl_BA": "sârbă (chirilică, Bosnia și Herțegovina)",
  "sr_Cyrl_ME": "sârbă (chirilică, Muntenegru)",
  "sr_Cyrl_RS": "sârbă (chirilică, Serbia)",
  "sr_Cyrl_XK": "sârbă (chirilică, Kosovo)",
  "sr_Latn": "sârbă (latină)",
  "sr_Latn_BA": "sârbă (latină, Bosnia și Herțegovina)",
  "sr_Latn_ME": "sârbă (latină, Muntenegru)",
  "sr_Latn_RS": "sârbă (latină, Serbia)",
  "sr_Latn_XK": "sârbă (latină, Kosovo)",
  "sr_ME": "sârbă (Muntenegru)",
  "sr_RS": "sârbă (Serbia)",
  "sr_XK": "sârbă (Kosovo)",
  "srn": "sranan tongo",
  "srr": "serer",
  "ss": "swati",
  "ssy": "saho",
  "st": "sesotho",
  "stq": "Saterland Frisian",
  "su": "sundaneză",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumeriană",
  "sv": "suedeză",
  "sv_AX": "suedeză (Insulele Åland)",
  "sv_FI": "suedeză (Finlanda)",
  "sv_SE": "suedeză (Suedia)",
  "sw": "swahili",
  "sw_CD": "swahili (R.D. Congo)",
  "sw_KE": "swahili (Kenya)",
  "sw_TZ": "swahili (Tanzania)",
  "sw_UG": "swahili (Uganda)",
  "swb": "comoreză",
  "swc": "swahili Congo",
  "syc": "siriacă clasică",
  "syr": "siriacă",
  "szl": "Silesian",
  "ta": "tamilă",
  "ta_IN": "tamilă (India)",
  "ta_LK": "tamilă (Sri Lanka)",
  "ta_MY": "tamilă (Malaezia)",
  "ta_SG": "tamilă (Singapore)",
  "tai": "limbă thai",
  "tcy": "Tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "timne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tetum",
  "tg": "tadjică",
  "th": "thailandeză",
  "th_TH": "thailandeză (Thailanda)",
  "ti": "tigrină",
  "ti_ER": "tigrină (Eritreea)",
  "ti_ET": "tigrină (Etiopia)",
  "tig": "tigre",
  "tiv": "tiv",
  "tk": "turkmenă",
  "tkl": "tokelau",
  "tkr": "Tsakhur",
  "tl": "tagalog",
  "tl_PH": "tagalog (Filipine)",
  "tlh": "klingoniană",
  "tli": "tlingit",
  "tly": "Talysh",
  "tmh": "tamashek",
  "tn": "setswana",
  "to": "tongană",
  "to_TO": "tonga (Tonga)",
  "tog": "nyasa tonga",
  "tpi": "tok pisin",
  "tr": "turcă",
  "tr_CY": "turcă (Cipru)",
  "tr_TR": "turcă (Turcia)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshian",
  "tt": "tătară",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tut": "limbă altaică",
  "tvl": "tuvalu",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitiană",
  "tyv": "tuvană",
  "tzm": "tamazight din Altasul Central",
  "udm": "udmurt",
  "ug": "uigură",
  "ug_Arab": "uigură (arabă)",
  "ug_Arab_CN": "uigură (arabă, China)",
  "ug_CN": "uigură (China)",
  "uga": "ugaritică",
  "uk": "ucraineană",
  "uk_UA": "ucraineană (Ucraina)",
  "umb": "umbundu",
  "und": "limbă necunoscută",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakistan)",
  "uz": "uzbecă",
  "uz_AF": "uzbecă (Afganistan)",
  "uz_Arab": "uzbecă (arabă)",
  "uz_Arab_AF": "uzbecă (arabă, Afganistan)",
  "uz_Cyrl": "uzbecă (chirilică)",
  "uz_Cyrl_UZ": "uzbecă (chirilică, Uzbekistan)",
  "uz_Latn": "uzbecă (latină)",
  "uz_Latn_UZ": "uzbecă (latină, Uzbekistan)",
  "uz_UZ": "uzbecă (Uzbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnameză",
  "vi_VN": "vietnameză (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapuk",
  "vot": "votică",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "valonă",
  "wae": "walser",
  "wal": "wolaita",
  "war": "waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wo": "wolof",
  "wuu": "chineză wu",
  "xal": "calmucă",
  "xh": "xhosa",
  "xmf": "Mingrelian",
  "xog": "soga",
  "yao": "yao",
  "yap": "yapeză",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "idiș",
  "yo": "yoruba",
  "yo_BJ": "yoruba (Benin)",
  "yo_NG": "yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "cantoneză",
  "za": "zhuang",
  "zap": "zapotecă",
  "zbl": "simboluri Bilss",
  "zea": "Zeelandic",
  "zen": "zenaga",
  "zgh": "tamazight standard marocană",
  "zh": "chineză",
  "zh_CN": "chineză (China)",
  "zh_HK": "chineză (R.A.S. Hong Kong a Chinei)",
  "zh_Hans": "chineză (simplificată)",
  "zh_Hans_CN": "chineză (simplificată, China)",
  "zh_Hans_HK": "chineză (simplificată, R.A.S. Hong Kong a Chinei)",
  "zh_Hans_MO": "chineză (simplificată, R.A.S. Macao a Chinei)",
  "zh_Hans_SG": "chineză (simplificată, Singapore)",
  "zh_Hant": "chineză (tradițională)",
  "zh_Hant_HK": "chineză (tradițională, R.A.S. Hong Kong a Chinei)",
  "zh_Hant_MO": "chineză (tradițională, R.A.S. Macao a Chinei)",
  "zh_Hant_TW": "chineză (tradițională, Taiwan)",
  "zh_MO": "chineză (R.A.S. Macao a Chinei)",
  "zh_SG": "chineză (Singapore)",
  "zh_TW": "chineză (Taiwan)",
  "zu": "zulu",
  "zu_ZA": "zulu (Africa de Sud)",
  "zun": "zuni",
  "zxx": "fară conținut lingvistic",
  "zza": "zaza"
};
