const names = {
  "ace": "Achinese",
  "akk": "Akkadian",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "arn": "Mapuche",
  "ban": "Balinese",
  "bin": "Bini",
  "bn": "Beangailis",
  "bug": "Buginese",
  "chk": "Chuukese",
  "chn": "Chinook Jargon",
  "ckb": "Cùrdais Soranî",
  "cs": "Seacais",
  "den": "Slave",
  "dtp": "Central Dusun",
  "esu": "Central Yupik",
  "ext": "Extremaduran",
  "fa": "Farsaidh",
  "fit": "Tornedalen Finnish",
  "frc": "Cajun French",
  "fy": "Frìoslannais Siarach",
  "gan": "Gan Chinese",
  "gbz": "Zoroastrian Dari",
  "gom": "Goan Konkani",
  "hak": "Hakka Chinese",
  "hit": "Hittite",
  "hsn": "Xiang Chinese",
  "kbd": "Kabardian",
  "kho": "Khotanese",
  "krl": "Karelian",
  "ksh": "Colognian",
  "lez": "Lezghian",
  "li": "Limburgish",
  "lui": "Luiseno",
  "mad": "Madurese",
  "mic": "Micmac",
  "mrj": "Western Mari",
  "mwl": "Mirandese",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "nds": "Low German",
  "ne": "Neapàilis",
  "niu": "Niuean",
  "nso": "Leasotais Thuathach",
  "nwc": "Classical Newari",
  "ny": "Chichewa",
  "or": "Oriya",
  "pap": "Papiamento",
  "phn": "Phoenician",
  "pon": "Pohnpeian",
  "pro": "Old Provençal",
  "ps": "Pachtu",
  "qu": "Ceatsua",
  "qug": "Chimborazo Highland Quichua",
  "rar": "Rarotongan",
  "rup": "Aromanian",
  "sah": "Sachais",
  "sdc": "Sassarese Sardinian",
  "sh": "Serbo-Croatian",
  "st": "Leasotach Dheasach",
  "sux": "Sumerian",
  "ter": "Tereno",
  "th": "Tàidh",
  "to": "Tongais",
  "ttt": "Muslim Tat",
  "tvl": "Tuvalu",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Tamazight Meadhan na h-Atlas",
  "wae": "Walser",
  "wuu": "Wu Chinese",
  "yap": "Yapese",
  "yo": "Ioruba",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zun": "Zuni",
  "zxx": "Susbaint nach eil ‘na chànan",
  "zza": "Zaza"
};
