const names = {
  "001": "Wêreld",
  "002": "Afrika",
  "003": "Noord-Amerika",
  "005": "Suid-Amerika",
  "009": "Oseanië",
  "011": "Wes-Afrika",
  "013": "Sentraal-Amerika",
  "014": "Oos-Afrika",
  "015": "Noord-Afrika",
  "017": "Midde-Afrika",
  "018": "Suider-Afrika",
  "019": "Amerikas",
  "021": "Noordelike Amerika",
  "029": "Karibiese streek",
  "030": "Oos-Asië",
  "034": "Suid-Asië",
  "035": "Suidoos-Asië",
  "039": "Suid-Europa",
  "053": "Australasië",
  "054": "Melanesië",
  "057": "Mikronesiese streek",
  "061": "Polinesië",
  "062": "Suid-Sentraal-Asië",
  "142": "Asië",
  "143": "Sentraal-Asië",
  "145": "Wes-Asië",
  "150": "Europa",
  "151": "Oos-Europa",
  "154": "Noord-Europa",
  "155": "Wes-Europa",
  "172": "Statebond van Onafhanklike State",
  "200": "Tsjeggo-Slowakye",
  "202": "Afrika suid van die Sahara",
  "419": "Latyns-Amerika",
  "830": "Kanaaleilande",
  "AC": "Ascensioneiland",
  "AD": "Andorra",
  "AE": "Verenigde Arabiese Emirate",
  "AF": "Afganistan",
  "AG": "Antigua en Barbuda",
  "AI": "Anguilla",
  "AL": "Albanië",
  "AM": "Armenië",
  "AN": "Nederlands-Antille",
  "AO": "Angola",
  "AQ": "Antarktika",
  "AR": "Argentinië",
  "AS": "Amerikaanse Samoa",
  "AT": "Oostenryk",
  "AU": "Australië",
  "AW": "Aruba",
  "AX": "Ålandeilande",
  "AZ": "Azerbeidjan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Kaukasiese Albanees",
  "Ahom": "Ahom",
  "Arab": "Arabies",
  "Aran": "Nastaliq",
  "Armi": "Keiserlike Aramees",
  "Armn": "Armeens",
  "Avst": "Avestan",
  "BA": "Bosnië en Herzegowina",
  "BB": "Barbados",
  "BD": "Bangladesj",
  "BE": "België",
  "BF": "Burkina Faso",
  "BG": "Bulgarye",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Sint Barthélemy",
  "BM": "Bermuda",
  "BN": "Broenei",
  "BO": "Bolivië",
  "BQ": "Karibiese Nederland",
  "BR": "Brasilië",
  "BS": "Bahamas",
  "BT": "Bhoetan",
  "BV": "Bouvet-eiland",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "Balinese",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Bengaals",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Boeginese",
  "Buhd": "Buhid",
  "CA": "Kanada",
  "CC": "Kokoseilande",
  "CD": "Demokratiese Republiek van die Kongo",
  "CF": "Sentraal-Afrikaanse Republiek",
  "CG": "Kongo - Brazzaville",
  "CH": "Switserland",
  "CI": "Ivoorkus",
  "CK": "Cookeilande",
  "CL": "Chili",
  "CM": "Kameroen",
  "CN": "Sjina",
  "CO": "Colombië",
  "CP": "Clippertoneiland",
  "CR": "Costa Rica",
  "CS": "Serwië en Montenegro",
  "CU": "Kuba",
  "CV": "Kaap Verde",
  "CW": "Curaçao",
  "CX": "Kerseiland",
  "CY": "Ciprus",
  "CZ": "Tsjeggië",
  "Cakm": "Chakma",
  "Cans": "Verenigde Kanadese inheemse leerplanne",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmiaan",
  "Cirt": "Geboorte",
  "Copt": "Koptieses",
  "Cprt": "Cyprus",
  "Cyrl": "Sirillies",
  "Cyrs": "Ou Kerkslawiese Sirillieses",
  "DD": "Oos-Duitsland",
  "DE": "Duitsland",
  "DG": "Diego Garcia",
  "DJ": "Djiboeti",
  "DK": "Denemarke",
  "DM": "Dominica",
  "DO": "Dominikaanse Republiek",
  "DZ": "Algerië",
  "Deva": "Devanagari",
  "Diak": "Duik Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Ducouran snelskrif",
  "EA": "Ceuta en Melilla",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Egipte",
  "EH": "Wes-Sahara",
  "ER": "Eritrea",
  "ES": "Spanje",
  "ET": "Ethiopië",
  "EU": "Europese Unie",
  "EZ": "Eurosone",
  "Egyd": "Egiptiese demotiese",
  "Egyh": "Egiptiese hiëratiese",
  "Egyp": "Egiptieses hiërogliewe",
  "Elba": "Elbasan",
  "Elym": "Elymaïes",
  "Ethi": "Etiopies",
  "FI": "Finland",
  "FJ": "Fidji",
  "FK": "Falklandeilande",
  "FM": "Mikronesië",
  "FO": "Faroëreilande",
  "FR": "Frankryk",
  "FX": "Metropolitaanse Frankryk",
  "GA": "Gaboen",
  "GB": "Verenigde Koninkryk",
  "GD": "Grenada",
  "GE": "Georgië",
  "GF": "Frans-Guyana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenland",
  "GM": "Gambië",
  "GN": "Guinee",
  "GP": "Guadeloupe",
  "GQ": "Ekwatoriaal-Guinee",
  "GR": "Griekeland",
  "GS": "Suid-Georgië en die Suidelike Sandwicheilande",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinee-Bissau",
  "GY": "Guyana",
  "Geok": "Georgiese Khutsuri",
  "Geor": "Georgies",
  "Glag": "Glagolitic",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gotieses",
  "Gran": "Grantha",
  "Grek": "Grieks",
  "Gujr": "Gudjarati",
  "Guru": "Gurmukhi",
  "HK": "Hongkong SAS Sjina",
  "HM": "Heard-eiland en McDonald-eilande",
  "HN": "Honduras",
  "HR": "Kroasië",
  "HT": "Haïti",
  "HU": "Hongarye",
  "Hanb": "Han met Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "Vereenvoudig",
  "Hant": "Tradisioneel",
  "Hatr": "Hatran",
  "Hebr": "Hebreeus",
  "Hira": "Hiragana",
  "Hluw": "Anatoliese hiërogliewe",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Japannese lettergreepskrif",
  "Hung": "Ou Hongaars",
  "IC": "Kanariese Eilande",
  "ID": "Indonesië",
  "IE": "Ierland",
  "IL": "Israel",
  "IM": "Eiland Man",
  "IN": "Indië",
  "IO": "Brits-Indiese Oseaangebied",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Ysland",
  "IT": "Italië",
  "Inds": "Indus",
  "Ital": "Ou kursief",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Jordanië",
  "JP": "Japan",
  "Jamo": "Jamo",
  "Java": "Javaans",
  "Jpan": "Japannees",
  "Jurc": "Jurchen",
  "KE": "Kenia",
  "KG": "Kirgisië",
  "KH": "Kambodja",
  "KI": "Kiribati",
  "KM": "Comore",
  "KN": "Saint Kitts en Nevis",
  "KP": "Noord-Korea",
  "KR": "Suid-Korea",
  "KW": "Koeweit",
  "KY": "Kaaimanseilande",
  "KZ": "Kazakstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kits": "Khitan klein skrif",
  "Knda": "Kannada",
  "Kore": "Koreaans",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Sint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberië",
  "LS": "Lesotho",
  "LT": "Litaue",
  "LU": "Luxemburg",
  "LV": "Letland",
  "LY": "Libië",
  "Lana": "Lanna",
  "Laoo": "Lao",
  "Latf": "Fraktur Latyn",
  "Latg": "Gaelies Latyn",
  "Latn": "Latyn",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Lineêr A",
  "Linb": "Lineêr B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydiaans",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldowa",
  "ME": "Montenegro",
  "MF": "Sint Martin",
  "MG": "Madagaskar",
  "MH": "Marshall-eilande",
  "MI": "Midway-eilande",
  "MK": "Noord-Macedonië",
  "ML": "Mali",
  "MM": "Mianmar",
  "MN": "Mongolië",
  "MO": "Macau SAS Sjina",
  "MP": "Noordelike Mariana-eilande",
  "MQ": "Martinique",
  "MR": "Mauritanië",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maledive",
  "MW": "Malawi",
  "MX": "Meksiko",
  "MY": "Maleisië",
  "MZ": "Mosambiek",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "Maya-hiërogliewe",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitiese kursief",
  "Mero": "Meroities",
  "Mlym": "Malabaars",
  "Modi": "Modi",
  "Mong": "Mongools",
  "Moon": "Maan",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Mianmar",
  "NA": "Namibië",
  "NC": "Nieu-Kaledonië",
  "NE": "Niger",
  "NF": "Norfolkeiland",
  "NG": "Nigerië",
  "NI": "Nicaragua",
  "NL": "Nederland",
  "NO": "Noorweë",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Neutrale Sone",
  "NU": "Niue",
  "NZ": "Nieu-Seeland",
  "Nand": "Nandinagari",
  "Narb": "Ou Noord-Arabier",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Oriya",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Pacific Islands Trust Territory",
  "PE": "Peru",
  "PF": "Frans-Polinesië",
  "PG": "Papoea-Nieu-Guinee",
  "PH": "Filippyne",
  "PK": "Pakistan",
  "PL": "Pole",
  "PM": "Sint Pierre en Miquelon",
  "PN": "Pitcairneilande",
  "PR": "Puerto Rico",
  "PS": "Palestynse gebiede",
  "PT": "Portugal",
  "PU": "Amerikaanse diverse Stille Oseaan-eilande",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Panamakanaal Sone",
  "Palm": "Palmyrene",
  "Pauc": "Pau Cin Hau",
  "Perm": "Ou Perm",
  "Phag": "Phags-pa",
  "Phli": "Inskripsionele Pahlavi",
  "Phlp": "Psalter Pahlavi",
  "Phlv": "Bespreek Pahlavi",
  "Phnx": "Fenisieses",
  "Plrd": "Pollard Fonetiese",
  "Prti": "Inskripsie Parthian",
  "QA": "Katar",
  "QO": "Afgeleë Oseanië",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Roemenië",
  "RS": "Serwië",
  "RU": "Rusland",
  "RW": "Rwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Saoedi-Arabië",
  "SB": "Salomonseilande",
  "SC": "Seychelle",
  "SD": "Soedan",
  "SE": "Swede",
  "SG": "Singapoer",
  "SH": "Sint Helena",
  "SI": "Slowenië",
  "SJ": "Svalbard en Jan Mayen",
  "SK": "Slowakye",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalië",
  "SR": "Suriname",
  "SS": "Suid-Soedan",
  "ST": "São Tomé en Príncipe",
  "SU": "Unie van Sowjet-sosialistiese republieke",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Sirië",
  "SZ": "Eswatini",
  "Samr": "Samaritaan",
  "Sara": "Sarati",
  "Sarb": "Ou Suid-Arabier",
  "Saur": "Saurashtra",
  "Sgnw": "TekenSkryf",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "Sinhala",
  "Sogd": "Sogdian",
  "Sogo": "Ou Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Soedanees",
  "Sylo": "Syloti Nagri",
  "Syrc": "Siries",
  "Syre": "Estrangelo Siries",
  "Syrj": "Wes-Siries",
  "Syrn": "Oostelike Siries",
  "TA": "Tristan da Cunha",
  "TC": "Turks- en Caicoseilande",
  "TD": "Tsjad",
  "TF": "Franse Suidelike Gebiede",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadjikistan",
  "TK": "Tokelau",
  "TL": "Oos-Timor",
  "TM": "Turkmenistan",
  "TN": "Tunisië",
  "TO": "Tonga",
  "TR": "Turkye",
  "TT": "Trinidad en Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzanië",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Nuwe Tai Lue",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibettaans",
  "Tirh": "Tirhuta",
  "UA": "Oekraïne",
  "UG": "Uganda",
  "UM": "Klein afgeleë eilande van die VSA",
  "UN": "Verenigde Nasies",
  "US": "Verenigde State van Amerika",
  "UY": "Uruguay",
  "UZ": "Oesbekistan",
  "Ugar": "Ugaritieses",
  "VA": "Vatikaanstad",
  "VC": "Saint Vincent en die Grenadine",
  "VD": "Noord-Viëtnam",
  "VE": "Venezuela",
  "VG": "Britse Maagde-eilande",
  "VI": "VSA se Maagde-eilande",
  "VN": "Viëtnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Visible Speech-karakters",
  "WF": "Wallis en Futuna",
  "WK": "Wake Island",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudoaksente",
  "XB": "Pseudotweerigting",
  "XK": "Kosovo",
  "Xpeo": "Ou Persies",
  "Xsux": "Sumero-Akkadiese spykerskrif",
  "YD": "Volks Demokratiese Republiek Jemen",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "Suid-Afrika",
  "ZM": "Zambië",
  "ZW": "Zimbabwe",
  "ZZ": "Onbekende gebied",
  "Zanb": "Zanabazar-plein",
  "Zinh": "Geërf",
  "Zmth": "Wiskundige notasie",
  "Zsye": "Emoji",
  "Zsym": "Simbole",
  "Zxxx": "Ongeskrewe",
  "Zyyy": "Gemeenskaplik",
  "Zzzz": "Onbekende skryfstelsel",
  "aa": "Afar",
  "ab": "Abkasies",
  "ace": "Atsjenees",
  "ach": "Akoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisiese Arabies",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibië)",
  "af_ZA": "Afrikaans (Suid-Afrika)",
  "afa": "Ander Afro-Asiaties",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadies",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Algonkwiese taal",
  "aln": "Gheg Albanees",
  "alt": "Suid-Altai",
  "am": "Amharies",
  "am_ET": "Amharies (Ethiopië)",
  "an": "Aragonees",
  "ang": "Ou Engels",
  "anp": "Angika",
  "apa": "Apache-taal",
  "ar": "Arabies",
  "ar_001": "Moderne Standaardarabies",
  "ar_AE": "Arabies (Verenigde Arabiese Emirate)",
  "ar_BH": "Arabies (Bahrein)",
  "ar_DJ": "Arabies (Djiboeti)",
  "ar_DZ": "Arabies (Algerië)",
  "ar_EG": "Arabies (Egipte)",
  "ar_EH": "Arabies (Wes-Sahara)",
  "ar_ER": "Arabies (Eritrea)",
  "ar_IL": "Arabies (Israel)",
  "ar_IQ": "Arabies (Irak)",
  "ar_JO": "Arabies (Jordanië)",
  "ar_KM": "Arabies (Comore)",
  "ar_KW": "Arabies (Koeweit)",
  "ar_LB": "Arabies (Libanon)",
  "ar_LY": "Arabies (Libië)",
  "ar_MA": "Arabies (Marokko)",
  "ar_MR": "Arabies (Mauritanië)",
  "ar_OM": "Arabies (Oman)",
  "ar_PS": "Arabies (Palestynse gebiede)",
  "ar_QA": "Arabies (Katar)",
  "ar_SA": "Arabies (Saoedi-Arabië)",
  "ar_SD": "Arabies (Soedan)",
  "ar_SO": "Arabies (Somalië)",
  "ar_SS": "Arabies (Suid-Soedan)",
  "ar_SY": "Arabies (Sirië)",
  "ar_TD": "Arabies (Tsjad)",
  "ar_TN": "Arabies (Tunisië)",
  "ar_YE": "Arabies (Jemen)",
  "arc": "Aramees",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerynse Arabies",
  "ars": "Najdi Arabies",
  "art": "Kunsmatige taal",
  "arw": "Arawak",
  "ary": "Marokkaanse Arabies",
  "arz": "Egiptiese Arabies",
  "as": "Assamees",
  "as_IN": "Assamees (Indië)",
  "asa": "Asu",
  "ase": "Amerikaanse gebaretaal",
  "ast": "Asturies",
  "ath": "Athapascan taal",
  "aus": "Australiese taal",
  "av": "Avaries",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbeidjans",
  "az_AZ": "Azerbeidjans (Azerbeidjan)",
  "az_Arab": "Azerbeidjans (Arabies)",
  "az_Cyrl": "Azerbeidjans (Cyrillies)",
  "az_Cyrl_AZ": "Azerbeidjans (Sirillies, Azerbeidjan)",
  "az_Latn": "Azerbeidjans (Latyn)",
  "az_Latn_AZ": "Azerbeidjans (Latyn, Azerbeidjan)",
  "azb": "South Azerbaijani",
  "ba": "Baskir",
  "bad": "Banda",
  "bai": "Bamileke Taal",
  "bal": "Baluchi",
  "ban": "Balinees",
  "bar": "Beiers",
  "bas": "Basaa",
  "bat": "Baltiese taal",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarussies",
  "be_BY": "Wit-Russies (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaars",
  "bg_BG": "Bulgaars (Bulgarye)",
  "bgn": "Wes-Balochi",
  "bh": "Bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latyn)",
  "bm_Latn_ML": "Bambara (Latyn, Mali)",
  "bn": "Bengaals",
  "bn_BD": "Bengaals (Bangladesj)",
  "bn_IN": "Bengaals (Indië)",
  "bnt": "Bantoe",
  "bo": "Tibettaans",
  "bo_CN": "Tibettaans (Sjina)",
  "bo_IN": "Tibettaans (Indië)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Bretons",
  "br_FR": "Bretons (Frankryk)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnies",
  "bs_BA": "Bosnies (Bosnië en Herzegowina)",
  "bs_Cyrl": "Bosnies (Cyrillies)",
  "bs_Cyrl_BA": "Bosnies (Sirillies, Bosnië en Herzegowina)",
  "bs_Latn": "Bosnies (Latyn)",
  "bs_Latn_BA": "Bosnies (Latyn, Bosnië en Herzegowina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "Buginees",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalaans",
  "ca_AD": "Katalaans (Andorra)",
  "ca_ES": "Katalaans (Spanje)",
  "ca_FR": "Katalaans (Frankryk)",
  "ca_IT": "Katalaans (Italië)",
  "cad": "Kaddo",
  "cai": "Sentraal-Amerikaanse Indiese taal",
  "car": "Karib",
  "cau": "Kaukasiese taal",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Tsjaakma",
  "ce": "Tsjetsjeens",
  "ceb": "Cebuano",
  "cel": "Keltiese taal",
  "cgg": "Kiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukees",
  "chm": "Mari",
  "chn": "Chinook-jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokees",
  "chy": "Cheyennees",
  "cic": "Chickasaw",
  "ckb": "Sorani",
  "cmc": "Chamic Language",
  "co": "Korsikaans",
  "cop": "Kopties",
  "cpe": "Engels-gebaseerde Kreools of Pidgin",
  "cpf": "Frans-gebaseerde Kreools of Pidgin",
  "cpp": "Portugees-gebaseerde Kreools of Pidgin",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Krim-Turks",
  "crp": "Kreools of Pidgin",
  "crs": "Seselwa Franskreools",
  "cs": "Tsjeggies",
  "cs_CZ": "Tsjeggies (Tjeggiese Republiek)",
  "csb": "Kasjoebies",
  "cu": "Kerkslawies",
  "cus": "Kusitiese taal",
  "cv": "Chuvash",
  "cy": "Wallies",
  "cy_GB": "Wallies (Verenigde Koninkryk)",
  "da": "Deens",
  "da_DK": "Deens (Denemarke)",
  "da_GL": "Deens (Groenland)",
  "dak": "Dakotaans",
  "dar": "Dakota",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Duits",
  "de_AT": "Duits (Oostenryk)",
  "de_BE": "Duits (België)",
  "de_CH": "Duits (Switserland)",
  "de_DE": "Duits (Duitsland)",
  "de_LI": "Duits (Liechtenstein)",
  "de_LU": "Duits (Luxemburg)",
  "del": "Delaware",
  "den": "Slaaf",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Dravidiese taal",
  "dsb": "Benedesorbies",
  "dtp": "Sentraal Dusun",
  "dua": "Duala",
  "dum": "Middelnederlands",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhoetan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emiliaan",
  "egy": "Antieke Egipties",
  "eka": "Ekajuk",
  "el": "Grieks",
  "el_CY": "Grieks (Siprus)",
  "el_GR": "Grieks (Griekeland)",
  "elx": "Elamiet",
  "en": "Engels",
  "en_AG": "Engels (Antigua en Barbuda)",
  "en_AI": "Engels (Anguilla)",
  "en_AS": "Engels (Amerikaans-Samoa)",
  "en_AU": "Engels (Australië)",
  "en_BB": "Engels (Barbados)",
  "en_BE": "Engels (België)",
  "en_BM": "Engels (Bermuda)",
  "en_BS": "Engels (Bahamas)",
  "en_BW": "Engels (Botswana)",
  "en_BZ": "Engels (Belize)",
  "en_CA": "Engels (Kanada)",
  "en_CC": "Engels (Cocos- (Keeling) eilande)",
  "en_CK": "Engels (Cookeilande)",
  "en_CM": "Engels (Kameroen)",
  "en_CX": "Engels (Kerseiland)",
  "en_DG": "Engels (Diego Garcia)",
  "en_DM": "Engels (Dominica)",
  "en_Dsrt": "Engels (Deseret)",
  "en_ER": "Engels (Eritrea)",
  "en_FJ": "Engels (Fidji)",
  "en_FK": "Engels (Falklandeilande)",
  "en_FM": "Engels (Mikronesië)",
  "en_GB": "Engels (Verenigde Koninkryk)",
  "en_GD": "Engels (Grenada)",
  "en_GG": "Engels (Guernsey)",
  "en_GH": "Engels (Ghana)",
  "en_GI": "Engels (Gibraltar)",
  "en_GM": "Engels (Gambië)",
  "en_GU": "Engels (Guam)",
  "en_GY": "Engels (Guyana)",
  "en_HK": "Engels (Hongkong SAS Sjina)",
  "en_IE": "Engels (Ierland)",
  "en_IM": "Engels (Eiland Man)",
  "en_IN": "Engels (Indië)",
  "en_IO": "Engels (Britse Indiese Oseaangebied)",
  "en_JE": "Engels (Jersey)",
  "en_JM": "Engels (Jamaika)",
  "en_KE": "Engels (Kenia)",
  "en_KI": "Engels (Kiribati)",
  "en_KN": "Engels (Sint Kitts en Nevis)",
  "en_KY": "Engels (Kaaimanseilande)",
  "en_LC": "Engels (Sint Lucia)",
  "en_LR": "Engels (Liberië)",
  "en_LS": "Engels (Lesotho)",
  "en_MG": "Engels (Madagaskar)",
  "en_MH": "Engels (Marshalleilande)",
  "en_MO": "Engels (Macau SAS Sjina)",
  "en_MP": "Engels (Noordelike Mariana-eilande)",
  "en_MS": "Engels (Montserrat)",
  "en_MT": "Engels (Malta)",
  "en_MU": "Engels (Mauritius)",
  "en_MW": "Engels (Malawi)",
  "en_MY": "Engels (Maleisië)",
  "en_NA": "Engels (Namibië)",
  "en_NF": "Engels (Norfolkeiland)",
  "en_NG": "Engels (Nigerië)",
  "en_NR": "Engels (Nauru)",
  "en_NU": "Engels (Niue)",
  "en_NZ": "Engels (Nieu-Seeland)",
  "en_PG": "Engels (Papoea-Nieu-Guinee)",
  "en_PH": "Engels (Filippyne)",
  "en_PK": "Engels (Pakistan)",
  "en_PN": "Engels (Pitcairneilande)",
  "en_PR": "Engels (Puerto Rico)",
  "en_PW": "Engels (Palau)",
  "en_RW": "Engels (Rwanda)",
  "en_SB": "Engels (Solomoneilande)",
  "en_SC": "Engels (Seychelle)",
  "en_SD": "Engels (Soedan)",
  "en_SG": "Engels (Singapoer)",
  "en_SH": "Engels (Sint Helena)",
  "en_SL": "Engels (Sierra Leone)",
  "en_SS": "Engels (Suid-Soedan)",
  "en_SX": "Engels (Sint Maarten)",
  "en_SZ": "Engels (Swaziland)",
  "en_TC": "Engels (Turks- en Caicoseilande)",
  "en_TK": "Engels (Tokelau)",
  "en_TO": "Engels (Tonga)",
  "en_TT": "Engels (Trinidad en Tobago)",
  "en_TV": "Engels (Tuvalu)",
  "en_TZ": "Engels (Tanzanië)",
  "en_UG": "Engels (Uganda)",
  "en_UM": "Engels (VS klein omliggende eilande)",
  "en_US": "Engels (Verenigde State van Amerika)",
  "en_VC": "Engels (Sint Vincent en die Grenadine)",
  "en_VG": "Engels (Britse Maagde-eilande)",
  "en_VI": "Engels (Amerikaanse Maagde-eilande)",
  "en_VU": "Engels (Vanuatu)",
  "en_WS": "Engels (Samoa)",
  "en_ZA": "Engels (Suid-Afrika)",
  "en_ZM": "Engels (Zambië)",
  "en_ZW": "Engels (Zimbabwe)",
  "enm": "Middel-Engels",
  "eo": "Esperanto",
  "es": "Spaans",
  "es_419": "Latyns-Amerikaanse Spaans",
  "es_AR": "Spaans (Argentinië)",
  "es_BO": "Spaans (Bolivië)",
  "es_CL": "Spaans (Chili)",
  "es_CO": "Spaans (Colombië)",
  "es_CR": "Spaans (Costa Rica)",
  "es_CU": "Spaans (Kuba)",
  "es_DO": "Spaans (Dominikaanse Republiek)",
  "es_EA": "Spaans (Ceuta en Melilla)",
  "es_EC": "Spaans (Ecuador)",
  "es_ES": "Spaans (Spanje)",
  "es_GQ": "Spaans (Ekwatoriaal-Guinee)",
  "es_GT": "Spaans (Guatemala)",
  "es_HN": "Spaans (Honduras)",
  "es_IC": "Spaans (Kanariese Eilande)",
  "es_MX": "Spaans (Meksiko)",
  "es_NI": "Spaans (Nicaragua)",
  "es_PA": "Spaans (Panama)",
  "es_PE": "Spaans (Peru)",
  "es_PH": "Spaans (Filippyne)",
  "es_PR": "Spaans (Puerto Rico)",
  "es_PY": "Spaans (Paraguay)",
  "es_SV": "Spaans (El Salvador)",
  "es_US": "Spaans (Verenigde State van Amerika)",
  "es_UY": "Spaans (Uruguay)",
  "es_VE": "Spaans (Venezuela)",
  "esu": "Sentraal Yupik",
  "et": "Estnies",
  "et_EE": "Estnies (Estland)",
  "eu": "Baskies",
  "eu_ES": "Baskies (Spanje)",
  "ewo": "Ewondo",
  "ext": "Ekstremuraan",
  "fa": "Persies",
  "fa_AF": "Persies (Afganistan)",
  "fa_IR": "Persies (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Fins",
  "fi_FI": "Fins (Finland)",
  "fil": "Filippyns",
  "fit": "Tornedalen Fins",
  "fiu": "Fins-Ugryse taal",
  "fj": "Fidjiaans",
  "fo": "Faroëes",
  "fo_FO": "Faroees (Faroëreilande)",
  "fon": "Fon",
  "fr": "Frans",
  "fr_BE": "Frans (België)",
  "fr_BF": "Frans (Burkina Faso)",
  "fr_BI": "Frans (Burundi)",
  "fr_BJ": "Frans (Benin)",
  "fr_BL": "Frans (Sint Barthélemy)",
  "fr_CA": "Frans (Kanada)",
  "fr_CD": "Frans (Demokratiese Republiek van die Kongo)",
  "fr_CF": "Frans (Sentraal-Afrikaanse Republiek)",
  "fr_CG": "Frans (Republiek van die Kongo)",
  "fr_CH": "Frans (Switserland)",
  "fr_CI": "Frans (Ivoorkus)",
  "fr_CM": "Frans (Kameroen)",
  "fr_DJ": "Frans (Djiboeti)",
  "fr_DZ": "Frans (Algerië)",
  "fr_FR": "Frans (Frankryk)",
  "fr_GA": "Frans (Gaboen)",
  "fr_GF": "Frans (Frans-Guyana)",
  "fr_GN": "Frans (Guinee)",
  "fr_GP": "Frans (Guadeloupe)",
  "fr_GQ": "Frans (Ekwatoriaal-Guinee)",
  "fr_HT": "Frans (Haïti)",
  "fr_KM": "Frans (Comore)",
  "fr_LU": "Frans (Luxemburg)",
  "fr_MA": "Frans (Marokko)",
  "fr_MC": "Frans (Monaco)",
  "fr_MF": "Frans (Sint Martin)",
  "fr_MG": "Frans (Madagaskar)",
  "fr_ML": "Frans (Mali)",
  "fr_MQ": "Frans (Martinique)",
  "fr_MR": "Frans (Mauritanië)",
  "fr_MU": "Frans (Mauritius)",
  "fr_NC": "Frans (Nieu-Kaledonië)",
  "fr_NE": "Frans (Niger)",
  "fr_PF": "Frans (Frans-Polinesië)",
  "fr_PM": "Frans (Sint Pierre en Miquelon)",
  "fr_RE": "Frans (Réunion)",
  "fr_RW": "Frans (Rwanda)",
  "fr_SC": "Frans (Seychelle)",
  "fr_SN": "Frans (Senegal)",
  "fr_SY": "Frans (Sirië)",
  "fr_TD": "Frans (Tsjad)",
  "fr_TG": "Frans (Togo)",
  "fr_TN": "Frans (Tunisië)",
  "fr_VU": "Frans (Vanuatu)",
  "fr_WF": "Frans (Wallis en Futuna)",
  "fr_YT": "Frans (Mayotte)",
  "frc": "Cajun Frans",
  "frm": "Midde-Frans",
  "fro": "Ou Frans",
  "frp": "Arpitan",
  "frr": "Noord-Fries",
  "frs": "Oosterse Fries",
  "fur": "Friuliaans",
  "fy": "Wes-Fries",
  "fy_NL": "Wes-Fries (Nederland)",
  "ga": "Iers",
  "ga_IE": "Iers (Ierland)",
  "gaa": "Gaa",
  "gag": "Gagauz",
  "gan": "Gan-Sjinees",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Skotse Gallies",
  "gd_GB": "Skotse Gallies (Verenigde Koninkryk)",
  "gem": "Germaanse taal",
  "gez": "Geez",
  "gil": "Gilbertees",
  "gl": "Galisies",
  "gl_ES": "Galisies (Spanje)",
  "glk": "Gilaki",
  "gmh": "Middelhoogduits",
  "gn": "Guarani",
  "goh": "Ou Hoogduits",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Goties",
  "grb": "Grebo",
  "grc": "Antieke Grieks",
  "gsw": "Switserse Duits",
  "gu": "Goedjarati",
  "gu_IN": "Goedjarati (Indië)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Eiland Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latyn)",
  "ha_Latn_GH": "Hausa (Latyn, Ghana)",
  "ha_Latn_NE": "Hausa (Latyn, Niger)",
  "ha_Latn_NG": "Hausa (Latyn, Nigerië)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigerië)",
  "hai": "Haida",
  "hak": "Hakka-Sjinees",
  "haw": "Hawais",
  "he": "Hebreeus",
  "he_IL": "Hebreeus (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (Indië)",
  "hif": "Fidji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hetities",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Kroaties",
  "hr_BA": "Kroaties (Bosnië en Herzegowina)",
  "hr_HR": "Kroaties (Kroasië)",
  "hsb": "Oppersorbies",
  "hsn": "Xiang-Sjinees",
  "ht": "Haïtiaans",
  "hu": "Hongaars",
  "hu_HU": "Hongaars (Hongarye)",
  "hup": "Hupa",
  "hy": "Armeens",
  "hy_AM": "Armeens (Armenië)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Ibanees",
  "ibb": "Ibibio",
  "id": "Indonesies",
  "id_ID": "Indonesies (Indonesië)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigerië)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (Sjina)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Indiese taal",
  "ine": "Indo-Europese taal",
  "inh": "Ingush",
  "io": "Ido",
  "ira": "Iraanse taal",
  "iro": "Iroquoiaanse taal",
  "is": "Yslands",
  "is_IS": "Yslands (Ysland)",
  "it": "Italiaans",
  "it_CH": "Italiaans (Switserland)",
  "it_IT": "Italiaans (Italië)",
  "it_SM": "Italiaans (San Marino)",
  "iu": "Inuïties",
  "izh": "Ingrian",
  "ja": "Japannees",
  "ja_JP": "Japannees (Japan)",
  "jam": "Jamaikaanse Creoolse Engels",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Joods-Persies",
  "jrb": "Joods-Arabies",
  "jut": "Jutish",
  "jv": "Javaans",
  "ka": "Georgies",
  "ka_GE": "Georgies (Georgië)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardiaans",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongolees",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Khoisan-taal",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenia)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazaks",
  "kk_Cyrl": "Kazaks (Sirillies)",
  "kk_Cyrl_KZ": "Kazaks (Sirillies, Kazakstan)",
  "kk_KZ": "Kazaks (Kazakstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Groenland)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Kambodja)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (Indië)",
  "ko": "Koreaans",
  "ko_KP": "Koreaans (Noord-Korea)",
  "ko_KR": "Koreaans (Suid-Korea)",
  "koi": "Komi-Permyaks",
  "kok": "Konkani",
  "kos": "Kosraërs",
  "kpe": "Kpellees",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelies",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kasjmirs",
  "ks_Arab": "Kasjmirs (Arabies)",
  "ks_Arab_IN": "Kasjmirs (Arabies, Indië)",
  "ks_IN": "Kasjmirs (Indië)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Keuls",
  "ku": "Koerdies",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Kornies",
  "kw_GB": "Kornies (Verenigde Koninkryk)",
  "ky": "Kirgisies",
  "ky_Cyrl": "Kirgisies (Sirillies)",
  "ky_Cyrl_KG": "Kirgisies (Sirillies, Kirgisië)",
  "ky_KG": "Kirgisies (Kirgisië)",
  "la": "Latyn",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxemburgs",
  "lb_LU": "Luxemburgs (Luxemburg)",
  "lez": "Lezghies",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgs",
  "lij": "Liguries",
  "liv": "Livonies",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingaals",
  "ln_AO": "Lingaals (Angola)",
  "ln_CD": "Lingaals (Demokratiese Republiek van die Kongo)",
  "ln_CF": "Lingaals (Sentraal-Afrikaanse Republiek)",
  "ln_CG": "Lingaals (Republiek van die Kongo)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Noord-Luri",
  "lt": "Litaus",
  "lt_LT": "Litaus (Litaue)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Demokratiese Republiek van die Kongo)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Letties",
  "lv_LV": "Letties (Letland)",
  "lzh": "Literêre Chinees",
  "lzz": "Laz",
  "mad": "Madurees",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Austronesiese taal",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisjen",
  "mg": "Malgassies",
  "mg_MG": "Malgassies (Madagaskar)",
  "mga": "Midde-Iers",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta’",
  "mh": "Marshallees",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabaus",
  "mis": "Diverse taal",
  "mk": "Masedonies",
  "mk_MK": "Masedonies (Macedonië)",
  "mkh": "Maandag-Khmer-taal",
  "ml": "Malabaars",
  "ml_IN": "Malabaars (Indië)",
  "mn": "Mongools",
  "mn_Cyrl": "Mongools (Sirillies)",
  "mn_Cyrl_MN": "Mongools (Sirillies, Mongolië)",
  "mn_MN": "Mongools (Mongolië)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Manobo-taal",
  "mo": "Moldawies",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (Indië)",
  "mrj": "Wes-Mari",
  "ms": "Maleis",
  "ms_BN": "Maleis (Broenei)",
  "ms_Latn": "Maleis (Latyn)",
  "ms_Latn_BN": "Maleis (Latyn, Broenei)",
  "ms_Latn_MY": "Maleis (Latyn, Maleisië)",
  "ms_Latn_SG": "Maleis (Latyn, Singapoer)",
  "ms_MY": "Maleis (Maleisië)",
  "ms_SG": "Maleis (Singapoer)",
  "mt": "Maltees",
  "mt_MT": "Maltees (Malta)",
  "mua": "Mundang",
  "mul": "Verskeie tale",
  "mun": "Munda Taal",
  "mus": "Kreek",
  "mwl": "Mirandees",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Birmaans",
  "my_MM": "Birmaans (Mianmar (Birma))",
  "mye": "Myene",
  "myn": "Maya-taal",
  "myv": "Erzya",
  "mzn": "Masanderani",
  "na": "Nauru",
  "nah": "Nahuatl",
  "nai": "Noord-Amerikaanse Indiese taal",
  "nan": "Min Nan-Sjinees",
  "nap": "Neapolitaans",
  "naq": "Nama",
  "nb": "Boeknoors",
  "nb_NO": "Noorse Bokmål (Noorweë)",
  "nb_SJ": "Noorse Bokmål (Svalbard en Jan Mayen)",
  "nd": "Noord-Ndebele",
  "nd_ZW": "Noord-Ndebele (Zimbabwe)",
  "nds": "Nederduits",
  "nds_NL": "Nedersaksies",
  "ne": "Nepalees",
  "ne_IN": "Nepalees (Indië)",
  "ne_NP": "Nepalees (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Niger-Kordofaniese taal",
  "niu": "Niueaans",
  "njo": "Ao Naga",
  "nl": "Nederlands",
  "nl_AW": "Nederlands (Aruba)",
  "nl_BE": "Nederlands (België)",
  "nl_BQ": "Nederlands (Karibiese Nederland)",
  "nl_CW": "Nederlands (Curaçao)",
  "nl_NL": "Nederlands (Nederland)",
  "nl_SR": "Nederlands (Suriname)",
  "nl_SX": "Nederlands (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Nuwe Noors",
  "nn_NO": "Noorweegse Nynorsk (Noorweë)",
  "nnh": "Ngiemboon",
  "no": "Noors",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Oudnoors",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Suid-Ndebele",
  "nso": "Noord-Sotho",
  "nub": "Nubiese taal",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Klassieke Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Oksitaans",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopië)",
  "om_KE": "Oromo (Kenia)",
  "or": "Oriya",
  "or_IN": "Oriya (Indië)",
  "os": "Osseties",
  "os_GE": "Osseties (Georgië)",
  "os_RU": "Osseties (Rusland)",
  "osa": "Osage",
  "ota": "Ottomaanse Turks",
  "oto": "Otomiese taal",
  "pa": "Pandjabi",
  "pa_Arab": "Pandjabi (Arabies)",
  "pa_Arab_PK": "Pandjabi (Arabies, Pakistan)",
  "pa_Guru": "Pandjabi (Gurmukhi)",
  "pa_Guru_IN": "Pandjabi (Gurmukhi, Indië)",
  "pa_IN": "Pandjabi (Indië)",
  "pa_PK": "Pandjabi (Pakistan)",
  "paa": "Papoeaanse taal",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauaans",
  "pcd": "Picard",
  "pcm": "Nigeriese Pidgin",
  "pdc": "Pennsylvania Duits",
  "pdt": "Plautdietsch",
  "peo": "Ou Persies",
  "pfl": "Palatynse Duits",
  "phi": "Filippynse taal",
  "phn": "Fenisies",
  "pi": "Pali",
  "pl": "Pools",
  "pl_PL": "Pools (Pole)",
  "pms": "Piëmontees",
  "pnt": "Ponties",
  "pon": "Pohnpeian",
  "pra": "Prakrit-taal",
  "prg": "Pruisies",
  "pro": "Ou Provençaalse",
  "ps": "Pasjto",
  "ps_AF": "Pasjto (Afganistan)",
  "pt": "Portugees",
  "pt_AO": "Portugees (Angola)",
  "pt_BR": "Portugees (Brasilië)",
  "pt_CV": "Portugees (Kaap Verde)",
  "pt_GW": "Portugees (Guinee-Bissau)",
  "pt_MO": "Portugees (Macau SAS Sjina)",
  "pt_MZ": "Portugees (Mosambiek)",
  "pt_PT": "Portugees (Portugal)",
  "pt_ST": "Portugees (Sao Tome en Principe)",
  "pt_TL": "Portugees (Oos-Timor)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivië)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "K’iche’",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongaans",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Reto-Romaans",
  "rm_CH": "Reto-Romaans (Switserland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Roemeens",
  "ro_MD": "Roemeens (Moldowa)",
  "ro_RO": "Roemeens (Roemenië)",
  "roa": "Romantiese taal",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Russies",
  "ru_BY": "Russies (Belarus)",
  "ru_KG": "Russies (Kirgisië)",
  "ru_KZ": "Russies (Kazakstan)",
  "ru_MD": "Russies (Moldowa)",
  "ru_RU": "Russies (Rusland)",
  "ru_UA": "Russies (Oekraïne)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanies",
  "rw": "Rwandees",
  "rw_RW": "Rwandees (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawees",
  "sah": "Sakhaans",
  "sai": "Suid-Amerikaanse Indiese taal",
  "sal": "Salishan-taal",
  "sam": "Samaritaan Aramees",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santalies",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinies",
  "scn": "Sisiliaans",
  "sco": "Skots",
  "sd": "Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardiese",
  "sdh": "Suid-Koerdies",
  "se": "Noord-Sami",
  "se_FI": "Noordelike Sami (Finland)",
  "se_NO": "Noordelike Sami (Noorweë)",
  "se_SE": "Noordelike Sami (Swede)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Semitiese taal",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Sentraal-Afrikaanse Republiek)",
  "sga": "Ou Iers",
  "sgn": "Gebare taal",
  "sgs": "Samogitian",
  "sh": "Serwo-Kroaties",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shi_Latn": "Shilha (Latyn)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Tsjadiese Arabies",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Siouan taal",
  "sit": "Sino-Tibetaanse taal",
  "sk": "Slowaaks",
  "sk_SK": "Slowaaks (Slowakye)",
  "sl": "Sloweens",
  "sl_SI": "Sloweens (Slowenië)",
  "sla": "Slawiese taal",
  "sli": "Neder-Silezië",
  "sly": "Selayar",
  "sm": "Samoaans",
  "sma": "Suid-Sami",
  "smi": "Sami-taal",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somalies",
  "so_DJ": "Somalies (Djiboeti)",
  "so_ET": "Somalies (Ethiopië)",
  "so_KE": "Somalies (Kenia)",
  "so_SO": "Somalies (Somalië)",
  "sog": "Sogdien",
  "son": "Songhai",
  "sq": "Albanees",
  "sq_AL": "Albanees (Albanië)",
  "sq_MK": "Albanees (Macedonië)",
  "sq_XK": "Albanees (Kosovo)",
  "sr": "Serwies",
  "sr_BA": "Serwies (Bosnië en Herzegowina)",
  "sr_Cyrl": "Serwies (Cyrillies)",
  "sr_Cyrl_BA": "Serwies (Sirillies, Bosnië en Herzegowina)",
  "sr_Cyrl_ME": "Serwies (Sirillies, Montenegro)",
  "sr_Cyrl_RS": "Serwies (Sirillies, Serwië)",
  "sr_Cyrl_XK": "Serwies (Sirillies, Kosovo)",
  "sr_Latn": "Serwies (Latyn)",
  "sr_Latn_BA": "Serwies (Latyn, Bosnië en Herzegowina)",
  "sr_Latn_ME": "Serwies (Latyn, Montenegro)",
  "sr_Latn_RS": "Serwies (Latyn, Serwië)",
  "sr_Latn_XK": "Serwies (Latyn, Kosovo)",
  "sr_ME": "Serwies (Montenegro)",
  "sr_RS": "Serwies (Serwië)",
  "sr_XK": "Serwies (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swazi",
  "ssa": "Nilo-Sahara taal",
  "ssy": "Saho",
  "st": "Suid-Sotho",
  "stq": "Saterfries",
  "su": "Sundanees",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumeries",
  "sv": "Sweeds",
  "sv_AX": "Sweeds (Ålandeilande)",
  "sv_FI": "Sweeds (Finland)",
  "sv_SE": "Sweeds (Swede)",
  "sw": "Swahili",
  "sw_CD": "Kongo Swahili",
  "sw_KE": "Swahili (Kenia)",
  "sw_TZ": "Swahili (Tanzanië)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comoraans",
  "swc": "Swahili (Kongo)",
  "syc": "Klassieke Siries",
  "syr": "Siries",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamil (Indië)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Maleisië)",
  "ta_SG": "Tamil (Singapoer)",
  "tai": "Tai taal",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (Indië)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetoem",
  "tg": "Tadjiks",
  "th": "Thai",
  "th_TH": "Thai (Thailand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopië)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmeens",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongaans",
  "to_TO": "Tongaans (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Turks",
  "tr_CY": "Turks (Siprus)",
  "tr_TR": "Turks (Turkye)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tataars",
  "ttt": "Moslem-tatoeëring",
  "tum": "Toemboeka",
  "tup": "Tupi-taal",
  "tut": "Altaïese taal",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahities",
  "tyv": "Tuvinees",
  "tzm": "Sentraal-Atlas-Tamazight",
  "udm": "Udmurt",
  "ug": "Uighur",
  "ug_Arab": "Uighur (Arabies)",
  "ug_Arab_CN": "Uighur (Arabies, Sjina)",
  "ug_CN": "Uighur (Sjina)",
  "uga": "Ugarities",
  "uk": "Oekraïens",
  "uk_UA": "Oekraïens (Oekraïne)",
  "umb": "Umbundu",
  "und": "Onbekende taal",
  "ur": "Oerdoe",
  "ur_IN": "Oerdoe (Indië)",
  "ur_PK": "Oerdoe (Pakistan)",
  "uz": "Oezbeeks",
  "uz_AF": "Oezbeeks (Afganistan)",
  "uz_Arab": "Oezbeeks (Arabies)",
  "uz_Arab_AF": "Oezbeeks (Arabies, Afganistan)",
  "uz_Cyrl": "Oezbeeks (Cyrillies)",
  "uz_Cyrl_UZ": "Oezbeeks (Sirillies, Oesbekistan)",
  "uz_Latn": "Oezbeeks (Latyns)",
  "uz_Latn_UZ": "Oezbeeks (Latyn, Oesbekistan)",
  "uz_UZ": "Oezbeeks (Oesbekistan)",
  "vai": "Vai",
  "vai_Latn": "Vai (Latyn)",
  "ve": "Venda",
  "vec": "Venesies",
  "vep": "Veps",
  "vi": "Viëtnamees",
  "vi_VN": "Viëtnamees (Viëtnam)",
  "vls": "Wes-Vlaams",
  "vmf": "Hoof-Frankies",
  "vo": "Volapük",
  "vot": "Voties",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wak": "Wakashan-taal",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Sorbiese taal",
  "wo": "Wolof",
  "wuu": "Wu-Sjinees",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Jiddisj",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigerië)",
  "ypk": "Yupik-taal",
  "yrl": "Nheengatu",
  "yue": "Kantonees",
  "yue_Hans": "Kantonees (vereenvoudigde Sjinees)",
  "yue_Hant": "Kantonees (tradisionele Chinese)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandies",
  "zen": "Zenaga",
  "zgh": "Standaard Marokkaanse Tamazight",
  "zh": "Sjinees",
  "zh_CN": "Chinees (Sjina)",
  "zh_HK": "Chinees (Hongkong SAS Sjina)",
  "zh_Hans": "Mandarynse Sjinees (Vereenvoudig)",
  "zh_Hans_CN": "Chinees (Vereenvoudig, Sjina)",
  "zh_Hans_HK": "Chinees (Vereenvoudig, Hongkong SAS Sjina)",
  "zh_Hans_MO": "Chinees (Vereenvoudig, Macau SAS Sjina)",
  "zh_Hans_SG": "Chinees (Vereenvoudig, Singapoer)",
  "zh_Hant": "Mandarynse Sjinees (Tradisioneel)",
  "zh_Hant_HK": "Chinees (Tradisioneel, Hongkong SAS Sjina)",
  "zh_Hant_MO": "Chinees (Tradisioneel, Macau SAS Sjina)",
  "zh_Hant_TW": "Chinees (Tradisioneel, Taiwan SAS Sjina)",
  "zh_MO": "Chinees (Macau SAS Sjina)",
  "zh_SG": "Chinees (Singapoer)",
  "zh_TW": "Chinees (Taiwan SAS Sjina)",
  "znd": "Zande",
  "zu": "Zoeloe",
  "zu_ZA": "Zoeloe (Suid-Afrika)",
  "zun": "Zuni",
  "zxx": "Geen taalinhoud nie",
  "zza": "Zaza"
};
