const names = {
  "AC": "Islas Ascensión",
  "AD": "Andorra",
  "AE": "Emiratos Árabes Unidos",
  "AF": "Afganistán",
  "AG": "Antigua y Barbuda",
  "AI": "Anguila",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antártida",
  "AR": "Argentina",
  "AS": "Samoa Americana",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Islas Åland",
  "AZ": "Azerbaiyán",
  "BA": "Bosnia y Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Bélgica",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Baréin",
  "BI": "Burundi",
  "BJ": "Benín",
  "BL": "San Bartolomé",
  "BM": "Bermudas",
  "BN": "Brunéi",
  "BO": "Bolivia",
  "BQ": "Bonaire",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bután",
  "BV": "Isla Bouvet",
  "BW": "Botsuana",
  "BY": "Belarús",
  "BZ": "Belice",
  "CA": "Canadá",
  "CC": "Islas Cocos",
  "CD": "Congo (RDC)",
  "CF": "República Centroafricana",
  "CG": "Congo",
  "CH": "Suiza",
  "CI": "Côte d’Ivoire",
  "CK": "Islas Cook",
  "CL": "Chile",
  "CM": "Camerún",
  "CN": "China",
  "CO": "Colombia",
  "CP": "Isla Clipperton",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curazao",
  "CX": "Isla Christmas",
  "CY": "Chipre",
  "CZ": "Chequia",
  "DE": "Alemania",
  "DG": "Diego García",
  "DJ": "Yibuti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Argelia",
  "EA": "Ceuta y Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egipto",
  "EH": "Sahara Occidental",
  "ER": "Eritrea",
  "ES": "España",
  "ET": "Etiopía",
  "FI": "Finlandia",
  "FJ": "Fiyi",
  "FK": "Islas Malvinas",
  "FM": "Micronesia",
  "FO": "Islas Feroe",
  "FR": "Francia",
  "GA": "Gabón",
  "GB": "Reino Unido",
  "GD": "Granada",
  "GE": "Georgia",
  "GF": "Guayana Francesa",
  "GG": "Guernesey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenlandia",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadalupe",
  "GQ": "Guinea Ecuatorial",
  "GR": "Grecia",
  "GS": "Georgia del Sur e Islas Sandwich del Sur",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bisáu",
  "GY": "Guyana",
  "HK": "Hong Kong (RAE)",
  "HM": "Islas Heard y McDonald",
  "HN": "Honduras",
  "HR": "Croacia",
  "HT": "Haití",
  "HU": "Hungría",
  "IC": "Islas Canarias",
  "ID": "Indonesia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Isla de Man",
  "IN": "India",
  "IO": "Territorio Británico del Océano Índico",
  "IQ": "Irak",
  "IR": "Irán",
  "IS": "Islandia",
  "IT": "Italia",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordania",
  "JP": "Japón",
  "KE": "Kenia",
  "KG": "Kirguistán",
  "KH": "Camboya",
  "KI": "Kiribati",
  "KM": "Comoras",
  "KN": "San Cristóbal y Nieves",
  "KP": "Corea del Norte",
  "KR": "Corea del Sur",
  "KW": "Kuwait",
  "KY": "Islas Caimán",
  "KZ": "Kazajistán",
  "LA": "Laos",
  "LB": "Líbano",
  "LC": "Santa Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesoto",
  "LT": "Lituania",
  "LU": "Luxemburgo",
  "LV": "Letonia",
  "LY": "Libia",
  "MA": "Marruecos",
  "MC": "Mónaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "San Martín",
  "MG": "Madagascar",
  "MH": "Islas Marshall",
  "MK": "Macedonia del Norte",
  "ML": "Malí",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao RAE",
  "MP": "Islas Marianas del Norte",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauricio",
  "MV": "Maldivas",
  "MW": "Malawi",
  "MX": "México",
  "MY": "Malasia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "Nueva Caledonia",
  "NE": "Níger",
  "NF": "Isla Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Países Bajos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nueva Zelanda",
  "OM": "Omán",
  "PA": "Panamá",
  "PE": "Perú",
  "PF": "Polinesia Francesa",
  "PG": "Papúa Nueva Guinea",
  "PH": "Filipinas",
  "PK": "Pakistán",
  "PL": "Polonia",
  "PM": "San Pedro y Miquelón",
  "PN": "Islas Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Palestina Kamachikuq",
  "PT": "Portugal",
  "PW": "Palaos",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Reunión",
  "RO": "Rumania",
  "RS": "Serbia",
  "RU": "Rusia",
  "RW": "Ruanda",
  "SA": "Arabia Saudí",
  "SB": "Islas Salomón",
  "SC": "Seychelles",
  "SD": "Sudán",
  "SE": "Suecia",
  "SG": "Singapur",
  "SH": "Santa Elena",
  "SI": "Eslovenia",
  "SJ": "Svalbard y Jan Mayen",
  "SK": "Eslovaquia",
  "SL": "Sierra Leona",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Sudán del Sur",
  "ST": "Santo Tomé y Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Suazilandia",
  "TA": "Tristán de Acuña",
  "TC": "Islas Turcas y Caicos",
  "TD": "Chad",
  "TF": "Territorios Australes Franceses",
  "TG": "Togo",
  "TH": "Tailandia",
  "TJ": "Tayikistán",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistán",
  "TN": "Túnez",
  "TO": "Tonga",
  "TR": "Turquía",
  "TT": "Trinidad y Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwán",
  "TZ": "Tanzania",
  "UA": "Ucrania",
  "UG": "Uganda",
  "UM": "Islas menores alejadas de los EE.UU.",
  "US": "Estados Unidos",
  "UY": "Uruguay",
  "UZ": "Uzbekistán",
  "VA": "Santa Sede (Ciudad del Vaticano)",
  "VC": "San Vicente y las Granadinas",
  "VE": "Venezuela",
  "VG": "Islas Vírgenes Británicas",
  "VI": "EE.UU. Islas Vírgenes",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis y Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "Sudáfrica",
  "ZM": "Zambia",
  "ZW": "Zimbabue",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans Simi",
  "af_NA": "Afrikaans Simi (Namibia)",
  "af_ZA": "Afrikaans Simi (Sudáfrica)",
  "afh": "Afrihili",
  "agq": "Aghem Simi",
  "ain": "Ainu",
  "ak": "Akan Simi",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Amarico Simi",
  "am_ET": "Amarico Simi (Etiopía)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "Arabe Simi",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Arabic (United Arab Emirates)",
  "ar_BH": "Arabe Simi (Bahréin)",
  "ar_DJ": "Arabe Simi (Yibuti)",
  "ar_DZ": "Arabe Simi (Argelia)",
  "ar_EG": "Arabe Simi (Egipto)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arabe Simi (Eritrea)",
  "ar_IL": "Arabe Simi (Israel)",
  "ar_IQ": "Arabe Simi (Iraq)",
  "ar_JO": "Arabe Simi (Jordania)",
  "ar_KM": "Arabe Simi (Comoras)",
  "ar_KW": "Arabe Simi (Kuwait)",
  "ar_LB": "Arabe Simi (Líbano)",
  "ar_LY": "Arabic (Libya)",
  "ar_MA": "Arabe Simi (Marruecos)",
  "ar_MR": "Arabe Simi (Mauritania)",
  "ar_OM": "Arabe Simi (Omán)",
  "ar_PS": "Arabe Simi (Palestina Kamachikuq)",
  "ar_QA": "Arabe Simi (Qatar)",
  "ar_SA": "Arabe Simi (Arabia Saudí)",
  "ar_SD": "Arabe Simi (Sudán)",
  "ar_SO": "Arabe Simi (Somalia)",
  "ar_SS": "Arabe Simi (Sudán del Sur)",
  "ar_SY": "Arabe Simi (Siria)",
  "ar_TD": "Arabe Simi (Chad)",
  "ar_TN": "Arabe Simi (Túnez)",
  "ar_YE": "Arabe Simi (Yemen)",
  "arc": "Aramaic",
  "arn": "Mapuche Simi",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Asames Simi",
  "as_IN": "Asames Simi (India)",
  "asa": "Asu Simi",
  "ase": "American Sign Language",
  "ast": "Asturiano Simi",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara Simi",
  "az": "Azerbaiyano Simi",
  "az_AZ": "Azerbaiyano Simi (Azerbaiyán)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Baskir Simi",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa Simi",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Bielorruso Simi",
  "be_BY": "Bielorruso Simi (Belarús)",
  "bej": "Beja",
  "bem": "Bemba Simi",
  "bew": "Betawi",
  "bez": "Bena Simi",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaro Simi",
  "bg_BG": "Bulgaro Simi (Bulgaria)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara Simi",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bangla Simi",
  "bn_BD": "Bangla Simi (Bangladesh)",
  "bn_IN": "Bangla Simi (India)",
  "bo": "Tibetano Simi",
  "bo_CN": "Tibetano Simi (China)",
  "bo_IN": "Tibetano Simi (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton Simi",
  "br_FR": "Breton Simi (Francia)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo Simi",
  "bs": "Bosnio Simi",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan Simi",
  "ca_AD": "Catalan Simi (Andorra)",
  "ca_ES": "Catalan Simi (España)",
  "ca_FR": "Catalan Simi (Francia)",
  "ca_IT": "Catalan Simi (Italia)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma Simi",
  "ce": "Checheno Simi",
  "ceb": "Cebuano Simi",
  "cgg": "Kiga Simi",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cheroqui Simi",
  "chy": "Cheyenne",
  "ckb": "Chawpi Kurdo Simi",
  "co": "Corso Simi",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "Checo Simi",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "Eslavo Eclesiástico Simi",
  "cv": "Chuvash",
  "cy": "Gales Simi",
  "cy_GB": "Gales Simi (Reino Unido)",
  "da": "Danes Simi",
  "da_DK": "Danes Simi (Dinamarca)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita Simi",
  "de": "Aleman Simi",
  "de_AT": "Aleman Simi (Austria)",
  "de_BE": "Aleman Simi (Bélgica)",
  "de_CH": "Aleman Simi (Suiza)",
  "de_DE": "Aleman Simi (Alemania)",
  "de_LI": "Aleman Simi (Liechtenstein)",
  "de_LU": "Aleman Simi (Luxemburgo)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma Simi",
  "doi": "Dogri",
  "dsb": "Bajo Sorbio Simi",
  "dtp": "Central Dusun",
  "dua": "Duala Simi",
  "dum": "Middle Dutch",
  "dv": "Divehi Simi",
  "dyo": "Jola-Fonyi Simi",
  "dyu": "Dyula",
  "dz": "Butanés Simi",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu Simi",
  "ee": "Ewé Simi",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Griego Simi",
  "el_CY": "Griego Simi (Chipre)",
  "el_GR": "Griego Simi (Grecia)",
  "elx": "Elamite",
  "en": "Ingles Simi",
  "en_AG": "English (Antigua & Barbuda)",
  "en_AI": "English (Anguilla)",
  "en_AS": "Ingles Simi (Samoa Americana)",
  "en_AU": "Ingles Simi (Australia)",
  "en_BB": "English (Barbados)",
  "en_BE": "Ingles Simi (Bélgica)",
  "en_BM": "English (Bermuda)",
  "en_BS": "Ingles Simi (Bahamas)",
  "en_BW": "Ingles Simi (Botsuana)",
  "en_BZ": "English (Belize)",
  "en_CA": "English (Canada)",
  "en_CC": "Ingles Simi (Islas Cocos)",
  "en_CK": "English (Cook Islands)",
  "en_CM": "Ingles Simi (Camerún)",
  "en_CX": "Ingles Simi (Isla Christmas)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Ingles Simi (Dominica)",
  "en_ER": "Ingles Simi (Eritrea)",
  "en_FJ": "Ingles Simi (Fiyi)",
  "en_FK": "English (Falkland Islands)",
  "en_FM": "Ingles Simi (Micronesia)",
  "en_GB": "Ingles Simi (Reino Unido)",
  "en_GD": "English (Grenada)",
  "en_GG": "Ingles Simi (Guernsey)",
  "en_GH": "Ingles Simi (Ghana)",
  "en_GI": "English (Gibraltar)",
  "en_GM": "Ingles Simi (Gambia)",
  "en_GU": "Ingles Simi (Guam)",
  "en_GY": "Ingles Simi (Guyana)",
  "en_HK": "Ingles Simi (Hong Kong (RAE))",
  "en_IE": "English (Ireland)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Ingles Simi (India)",
  "en_IO": "English (British Indian Ocean Territory)",
  "en_JE": "Ingles Simi (Jersey)",
  "en_JM": "English (Jamaica)",
  "en_KE": "Ingles Simi (Kenia)",
  "en_KI": "Ingles Simi (Kiribati)",
  "en_KN": "Ingles Simi (San Cristóbal y Nieves)",
  "en_KY": "English (Cayman Islands)",
  "en_LC": "English (St. Lucia)",
  "en_LR": "Ingles Simi (Liberia)",
  "en_LS": "Ingles Simi (Lesoto)",
  "en_MG": "Ingles Simi (Madagascar)",
  "en_MH": "Ingles Simi (Islas Marshall)",
  "en_MO": "Ingles Simi (Macao RAE)",
  "en_MP": "Ingles Simi (Islas Marianas del Norte)",
  "en_MS": "English (Montserrat)",
  "en_MT": "Ingles Simi (Malta)",
  "en_MU": "Ingles Simi (Mauricio)",
  "en_MW": "Ingles Simi (Malawi)",
  "en_MY": "English (Malaysia)",
  "en_NA": "Ingles Simi (Namibia)",
  "en_NF": "Ingles Simi (Isla Norfolk)",
  "en_NG": "Ingles Simi (Nigeria)",
  "en_NR": "Ingles Simi (Nauru)",
  "en_NU": "English (Niue)",
  "en_NZ": "English (New Zealand)",
  "en_PG": "Ingles Simi (Papúa Nueva Guinea)",
  "en_PH": "Ingles Simi (Filipinas)",
  "en_PK": "Ingles Simi (Pakistán)",
  "en_PN": "Ingles Simi (Islas Pitcairn)",
  "en_PR": "Ingles Simi (Puerto Rico)",
  "en_PW": "Ingles Simi (Palaos)",
  "en_RW": "Ingles Simi (Ruanda)",
  "en_SB": "English (Solomon Islands)",
  "en_SC": "Ingles Simi (Seychelles)",
  "en_SD": "Ingles Simi (Sudán)",
  "en_SG": "Ingles Simi (Singapur)",
  "en_SH": "English (St. Helena)",
  "en_SL": "Ingles Simi (Sierra Leona)",
  "en_SS": "Ingles Simi (Sudán del Sur)",
  "en_SX": "Ingles Simi (Sint Maarten)",
  "en_SZ": "Ingles Simi (Suazilandia)",
  "en_TC": "English (Turks & Caicos Islands)",
  "en_TK": "English (Tokelau)",
  "en_TO": "Ingles Simi (Tonga)",
  "en_TT": "Ingles Simi (Trinidad y Tobago)",
  "en_TV": "English (Tuvalu)",
  "en_TZ": "Ingles Simi (Tanzania)",
  "en_UG": "Ingles Simi (Uganda)",
  "en_UM": "Ingles Simi (Islas menores alejadas de los EE.UU.)",
  "en_US": "Ingles Simi (Estados Unidos)",
  "en_VC": "English (St. Vincent & Grenadines)",
  "en_VG": "English (British Virgin Islands)",
  "en_VI": "Ingles Simi (EE.UU. Islas Vírgenes)",
  "en_VU": "Ingles Simi (Vanuatu)",
  "en_WS": "Ingles Simi (Samoa)",
  "en_ZA": "Ingles Simi (Sudáfrica)",
  "en_ZM": "Ingles Simi (Zambia)",
  "en_ZW": "Ingles Simi (Zimbabue)",
  "enm": "Middle English",
  "eo": "Esperanto Simi",
  "es": "Español Simi",
  "es_419": "Español Simi (Latino América)",
  "es_AR": "Español Simi (Argentina)",
  "es_BO": "Español Simi (Bolivia)",
  "es_CL": "Español Simi (Chile)",
  "es_CO": "Español Simi (Colombia)",
  "es_CR": "Español Simi (Costa Rica)",
  "es_CU": "Español Simi (Cuba)",
  "es_DO": "Spanish (Dominican Republic)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Español Simi (Ecuador)",
  "es_ES": "Español Simi (España)",
  "es_GQ": "Español Simi (Guinea Ecuatorial)",
  "es_GT": "Español Simi (Guatemala)",
  "es_HN": "Español Simi (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Español Simi (México)",
  "es_NI": "Español Simi (Nicaragua)",
  "es_PA": "Español Simi (Panamá)",
  "es_PE": "Español Simi (Perú)",
  "es_PH": "Español Simi (Filipinas)",
  "es_PR": "Español Simi (Puerto Rico)",
  "es_PY": "Español Simi (Paraguay)",
  "es_SV": "Español Simi (El Salvador)",
  "es_US": "Español Simi (Estados Unidos)",
  "es_UY": "Español Simi (Uruguay)",
  "es_VE": "Español Simi (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estonio Simi",
  "et_EE": "Estonio Simi (Estonia)",
  "eu": "Euskera Simi",
  "eu_ES": "Euskera Simi (España)",
  "ewo": "Ewondo Simi",
  "ext": "Extremaduran",
  "fa": "Persa Simi",
  "fa_AF": "Persa Simi (Afganistán)",
  "fa_IR": "Persa Simi (Irán)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah Simi",
  "ff_CM": "Fulah Simi (Camerún)",
  "ff_GN": "Fulah Simi (Guinea)",
  "ff_MR": "Fulah Simi (Mauritania)",
  "ff_SN": "Fulah Simi (Senegal)",
  "fi": "Fines Simi",
  "fi_FI": "Fines Simi (Finlandia)",
  "fil": "Filipino Simi",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Feroes Simi",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Frances Simi",
  "fr_BE": "Frances Simi (Bélgica)",
  "fr_BF": "French (Burkina Faso)",
  "fr_BI": "Frances Simi (Burundi)",
  "fr_BJ": "Frances Simi (Benín)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "French (Canada)",
  "fr_CD": "Frances Simi (Congo (RDC))",
  "fr_CF": "French (Central African Republic)",
  "fr_CG": "Frances Simi (Congo)",
  "fr_CH": "Frances Simi (Suiza)",
  "fr_CI": "Frances Simi (Côte dʼIvoire)",
  "fr_CM": "Frances Simi (Camerún)",
  "fr_DJ": "Frances Simi (Yibuti)",
  "fr_DZ": "Frances Simi (Argelia)",
  "fr_FR": "Frances Simi (Francia)",
  "fr_GA": "Frances Simi (Gabón)",
  "fr_GF": "French (French Guiana)",
  "fr_GN": "Frances Simi (Guinea)",
  "fr_GP": "French (Guadeloupe)",
  "fr_GQ": "Frances Simi (Guinea Ecuatorial)",
  "fr_HT": "Frances Simi (Haití)",
  "fr_KM": "Frances Simi (Comoras)",
  "fr_LU": "Frances Simi (Luxemburgo)",
  "fr_MA": "Frances Simi (Marruecos)",
  "fr_MC": "Frances Simi (Mónaco)",
  "fr_MF": "Frances Simi (San Martín)",
  "fr_MG": "Frances Simi (Madagascar)",
  "fr_ML": "Frances Simi (Malí)",
  "fr_MQ": "French (Martinique)",
  "fr_MR": "Frances Simi (Mauritania)",
  "fr_MU": "Frances Simi (Mauricio)",
  "fr_NC": "Frances Simi (Nueva Caledonia)",
  "fr_NE": "Frances Simi (Níger)",
  "fr_PF": "Frances Simi (Polinesia Francesa)",
  "fr_PM": "Frances Simi (San Pedro y Miquelón)",
  "fr_RE": "French (Réunion)",
  "fr_RW": "Frances Simi (Ruanda)",
  "fr_SC": "Frances Simi (Seychelles)",
  "fr_SN": "Frances Simi (Senegal)",
  "fr_SY": "Frances Simi (Siria)",
  "fr_TD": "Frances Simi (Chad)",
  "fr_TG": "Frances Simi (Togo)",
  "fr_TN": "Frances Simi (Túnez)",
  "fr_VU": "Frances Simi (Vanuatu)",
  "fr_WF": "Frances Simi (Wallis, Futuna)",
  "fr_YT": "French (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulano Simi",
  "fy": "Frison Simi",
  "fy_NL": "Frison Simi (Países Bajos)",
  "ga": "Irlandes Simi",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Gaelico Escoces Simi",
  "gd_GB": "Gaelico Escoces Simi (Reino Unido)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Gallego Simi",
  "gl_ES": "Gallego Simi (España)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Alsaciano Simi",
  "gu": "Gujarati Simi",
  "gu_IN": "Gujarati Simi (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Guzí Simi",
  "gv": "Manés Simi",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa Simi",
  "ha_GH": "Hausa Simi (Ghana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa Simi (Níger)",
  "ha_NG": "Hausa Simi (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiano Simi",
  "he": "Hebreo Simi",
  "he_IL": "Hebreo Simi (Israel)",
  "hi": "Hindi Simi",
  "hi_IN": "Hindi Simi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong Daw Simi",
  "ho": "Hiri Motu",
  "hr": "Croata Simi",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croata Simi (Croacia)",
  "hsb": "Alto Sorbio Simi",
  "hsn": "Xiang Chinese",
  "ht": "Haitiano Criollo Simi",
  "hu": "Hungaro Simi",
  "hu_HU": "Hungarian (Hungary)",
  "hup": "Hupa",
  "hy": "Armenio Simi",
  "hy_AM": "Armenio Simi (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua Simi",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indonesio Simi",
  "id_ID": "Indonesio Simi (Indonesia)",
  "ie": "Interlingue",
  "ig": "Igbo Simi",
  "ig_NG": "Igbo Simi (Nigeria)",
  "ii": "Yi Simi",
  "ii_CN": "Yi Simi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Islandes Simi",
  "is_IS": "Islandes Simi (Islandia)",
  "it": "Italiano Simi",
  "it_CH": "Italiano Simi (Suiza)",
  "it_IT": "Italiano Simi (Italia)",
  "it_SM": "Italiano Simi (San Marino)",
  "iu": "Inuktitut Simi",
  "izh": "Ingrian",
  "ja": "Japones Simi",
  "ja_JP": "Japanese (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba Simi",
  "jmc": "Machame Simi",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Javanés Simi",
  "ka": "Georgiano Simi",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Cabilio Simi",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba Simi",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde Simi",
  "kea": "Caboverdiano Simi",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini Simi",
  "khw": "Khowar",
  "ki": "Kikuyu Simi",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazajo Simi",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazajo Simi (Kazajistan)",
  "kkj": "Kako Simi",
  "kl": "Groenlandes Simi",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin Simi",
  "km": "Khmer Simi",
  "km_KH": "Khmer Simi (Camboya)",
  "kmb": "Kimbundu",
  "kn": "Kannada Simi",
  "kn_IN": "Kannada Simi (India)",
  "ko": "Coreano Simi",
  "ko_KP": "Coreano Simi (Corea del Norte)",
  "ko_KR": "Coreano Simi (Corea del Sur)",
  "koi": "Komi-Permyak",
  "kok": "Konkani Simi",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Cachemir Simi",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala Simi",
  "ksf": "Bafia Simi",
  "ksh": "Kölsch Simi",
  "ku": "Kurdo Simi",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Córnico Simi",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kirghiz Simi",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kirghiz Simi (Kirguistán)",
  "la": "Latín Simi",
  "lad": "Ladino",
  "lag": "Langi Simi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxemburgues Simi",
  "lb_LU": "Luxemburgues Simi (Luxemburgo)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Luganda Simi",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota Simi",
  "lmo": "Lombard",
  "ln": "Lingala Simi",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao Simi",
  "lo_LA": "Lao Simi (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lrc": "Luri septentrional Simi",
  "lt": "Lituano Simi",
  "lt_LT": "Lituano Simi (Lituania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga Simi",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo Simi",
  "lus": "Mizo",
  "luy": "Luyia Simi",
  "lv": "Leton Simi",
  "lv_LV": "Leton Simi (Letonia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai Simi",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru Simi",
  "mfe": "Mauriciano Simi",
  "mg": "Malgache Simi",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto Simi",
  "mgo": "Metaʼ Simi",
  "mh": "Marshallese",
  "mi": "Maori Simi",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonio Simi",
  "mk_MK": "Macedonio Simi (ERY Macedonia)",
  "ml": "Malayalam Simi",
  "ml_IN": "Malayalam Simi (India)",
  "mn": "Mongol Simi",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk Simi",
  "mos": "Mossi",
  "mr": "Marathi Simi",
  "mr_IN": "Marathi Simi (India)",
  "mrj": "Western Mari",
  "ms": "Malayo Simi",
  "ms_BN": "Malayo Simi (Brunéi)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malayo Simi (Singapur)",
  "mt": "Maltes Simi",
  "mt_MT": "Maltes Simi (Malta)",
  "mua": "Mundang Simi",
  "mul": "Idiomas M´últiples Simi",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Birmano Simi",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazandaraní Simi",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama Simi",
  "nb": "Noruego Bokmål Simi",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "Ndebele septentrional Simi",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Bajo Alemán Simi",
  "ne": "Nepali Simi",
  "ne_IN": "Nepali Simi (India)",
  "ne_NP": "Nepali Simi (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Neerlandes Simi",
  "nl_AW": "Dutch (Aruba)",
  "nl_BE": "Neerlandes Simi (Bélgica)",
  "nl_BQ": "Neerlandes Simi (Bonaire)",
  "nl_CW": "Neerlandes Simi (Curazao)",
  "nl_NL": "Neerlandes Simi (Países Bajos)",
  "nl_SR": "Neerlandes Simi (Surinam)",
  "nl_SX": "Neerlandes Simi (Sint Maarten)",
  "nmg": "Kwasio Ngumba Simi",
  "nn": "Noruego Nynorsk Simi",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon Simi",
  "no": "Noruego Simi",
  "no_NO": "Noruego Simi (Noruega)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Sesotho Sa Leboa Simi",
  "nus": "Nuer Simi",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja Simi",
  "nym": "Nyamwezi",
  "nyn": "Nyankole Simi",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitano Simi",
  "oj": "Ojibwa",
  "om": "Oromo Simi",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Odia Simi",
  "or_IN": "Odia Simi (India)",
  "os": "Osetio Simi",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "Punyabi Simi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punyabi Simi (India)",
  "pa_PK": "Punyabi Simi (Pakistán)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento Simi",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Polaco Simi",
  "pl_PL": "Polaco Simi (Polonia)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prusiano Simi",
  "pro": "Old Provençal",
  "ps": "Pashto Simi",
  "ps_AF": "Pashto Simi (Afganistán)",
  "pt": "Portugues Simi",
  "pt_AO": "Portugues Simi (Angola)",
  "pt_BR": "Portugues Simi (Brasil)",
  "pt_CV": "Portuguese (Cape Verde)",
  "pt_GW": "Portugues Simi (Guinea-Bissau)",
  "pt_MO": "Portugues Simi (Macao RAE)",
  "pt_MZ": "Portugues Simi (Mozambique)",
  "pt_PT": "Portugues Simi (Portugal)",
  "pt_ST": "Portugues Simi (Santo Tomé y Príncipe)",
  "pt_TL": "Portugues Simi (Timor-Leste)",
  "qu": "Runasimi",
  "qu_BO": "Runasimi (Bolivia)",
  "qu_EC": "Runasimi (Ecuador)",
  "qu_PE": "Runasimi (Perú)",
  "quc": "Kʼicheʼ Simi",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romanche Simi",
  "rm_CH": "Romanche Simi (Suiza)",
  "rn": "Rundi Simi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Rumano Simi",
  "ro_MD": "Rumano Simi (Moldova)",
  "ro_RO": "Romanian (Romania)",
  "rof": "Rombo Simi",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Ruso Simi",
  "ru_BY": "Ruso Simi (Belarús)",
  "ru_KG": "Ruso Simi (Kirguistán)",
  "ru_KZ": "Ruso Simi (Kazajistan)",
  "ru_MD": "Ruso Simi (Moldova)",
  "ru_RU": "Ruso Simi (Rusia)",
  "ru_UA": "Russian (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Kinyarwanda Simi",
  "rw_RW": "Kinyarwanda Simi (Ruanda)",
  "rwk": "Rwa Simi",
  "sa": "Sanscrito Simi",
  "sad": "Sandawe",
  "sah": "Sakha Simi",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu Simi",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu Simi",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi Simi",
  "sdc": "Sassarese Sardinian",
  "se": "Chincha Sami Simi",
  "se_FI": "Chincha Sami Simi (Finlandia)",
  "se_NO": "Chincha Sami Simi (Noruega)",
  "se_SE": "Chincha Sami Simi (Suecia)",
  "see": "Seneca",
  "seh": "Sena Simi",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni Simi",
  "sg": "Sango Simi",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tashelhit Simi",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Cingales Simi",
  "si_LK": "Cingales Simi (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Eslovaco Simi",
  "sk_SK": "Eslovaco Simi (Eslovaquia)",
  "sl": "Esloveno Simi",
  "sl_SI": "Esloveno Simi (Eslovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoano Simi",
  "sma": "Qulla Sami Simi",
  "smj": "Sami Lule Simi",
  "smn": "Sami Inari Simi",
  "sms": "Sami Skolt Simi",
  "sn": "Shona Simi",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somali Simi",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdien",
  "sq": "Albanes Simi",
  "sq_AL": "Albanes Simi (Albania)",
  "sq_MK": "Albanes Simi (ERY Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbio Simi",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbio Simi (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Soto Meridional Simi",
  "stq": "Saterland Frisian",
  "su": "Sundanés Simi",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Sueco Simi",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Sueco Simi (Finlandia)",
  "sv_SE": "Sueco Simi (Suecia)",
  "sw": "Suajili Simi",
  "sw_CD": "Suajili Simi (Congo (RDC))",
  "sw_KE": "Suajili Simi (Kenia)",
  "sw_TZ": "Suajili Simi (Tanzania)",
  "sw_UG": "Suajili Simi (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Siriaco Simi",
  "szl": "Silesian",
  "ta": "Tamil Simi",
  "ta_IN": "Tamil Simi (India)",
  "ta_LK": "Tamil Simi (Sri Lanka)",
  "ta_MY": "Tamil (Malaysia)",
  "ta_SG": "Tamil Simi (Singapur)",
  "tcy": "Tulu",
  "te": "Telugu Simi",
  "te_IN": "Telugu Simi (India)",
  "tem": "Timne",
  "teo": "Teso Simi",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tayiko Simi",
  "th": "Tailandes Simi",
  "th_TH": "Tailandes Simi (Tailandia)",
  "ti": "Tigriña Simi",
  "ti_ER": "Tigriña Simi (Eritrea)",
  "ti_ET": "Tigriña Simi (Etiopía)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turcomano Simi",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Setsuana Simi",
  "to": "Tongano Simi",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Turco Simi",
  "tr_CY": "Turco Simi (Chipre)",
  "tr_TR": "Turco Simi (Turquía)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tartaro Simi",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq Simi",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Tamazight Simi",
  "udm": "Udmurt",
  "ug": "Uigur Simi",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uigur Simi (China)",
  "uga": "Ugaritic",
  "uk": "Ucraniano Simi",
  "uk_UA": "Ukrainian (Ukraine)",
  "umb": "Umbundu",
  "und": "Mana Riqsisqa Simi",
  "ur": "Urdu Simi",
  "ur_IN": "Urdu Simi (India)",
  "ur_PK": "Urdu Simi (Pakistán)",
  "uz": "Uzbeko Simi",
  "uz_AF": "Uzbeko Simi (Afganistán)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbeko Simi (Uzbekistán)",
  "vai": "Vai Simi",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Vietnamita Simi",
  "vi_VN": "Vietnamita Simi (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük Simi",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo Simi",
  "wa": "Walloon",
  "wae": "Walser Simi",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof Simi",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Isixhosa Simi",
  "xmf": "Mingrelian",
  "xog": "Soga Simi",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben Simi",
  "ybb": "Yemba",
  "yi": "Yiddish Simi",
  "yo": "Yoruba Simi",
  "yo_BJ": "Yoruba Simi (Benín)",
  "yo_NG": "Yoruba Simi (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "Cantonés Simi",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Bereber Marroquí Estándar Simi",
  "zh": "Chino Simi",
  "zh_CN": "Chino Simi (China)",
  "zh_HK": "Chino Simi (Hong Kong (RAE))",
  "zh_Hans": "Chino Simi (Simplificado)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chino Simi (Tradicional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chino Simi (Macao RAE)",
  "zh_SG": "Chino Simi (Singapur)",
  "zh_TW": "Chinese (Taiwan)",
  "zu": "Isizulu Simi",
  "zu_ZA": "Isizulu Simi (Sudáfrica)",
  "zun": "Zuni",
  "zxx": "Sin contenido linguístico",
  "zza": "Zaza"
};
