const names = {
  "001": "འཛམ་གླིང་།",
  "002": "ཨཕྲི་ཀ།",
  "053": "ཨསྟྲེ་ལི་ཡ་དང་། ནིའུ་ཛི་ལན྄ཌ།",
  "142": "ཨེ་ཤི་ཡ།",
  "150": "ཡུ་རོབ།",
  "AD": "ཨེན་ཌོ་ར།",
  "AE": "ཨ་རབ། ཨི་མི་རཊ྄། ཆིག་སྒྲིལ་རྒྱལ་ཁབ།",
  "AF": "ཨཕ་ག་ནི་སྟཱན།",
  "AG": "ཨེན་ཊི་གུ་དང་། བྷར་བུ་ཌ།",
  "AI": "ཨང་གུའི་ལ།",
  "AL": "ཨལ་བཱ་ནི་ཡ།",
  "AM": "ཨར་མེ་ནི་ཡ།",
  "AO": "ཨང་གཽ་ལ།",
  "AQ": "ལྷོ་རྩེའི་མཐའ་གླིང་།",
  "AR": "ཨར་ཇེན་ཊི་ན།",
  "AS": "American Samoa",
  "AT": "ཨསྟྲི་ཡ།",
  "AU": "ཨསྟྲེ་ལི་ཡ།",
  "AW": "ཨ་རུ་བ།",
  "AX": "Åland Islands",
  "AZ": "ཨཛར་བཡེ་ཇན།",
  "Arab": "འ་ལ་པོའི་སྐད་ཡིག་།",
  "BA": "བོསྣི་ཡ་དང་ཧརྫོ་གོ་ཝི་ན།",
  "BB": "བཱརྦ་ཌོས྄།",
  "BD": "བངྒ་ལ་དེཤ།",
  "BE": "བེལ་ཇི་ཡམ།",
  "BF": "བརཀི་ན། ཕསོ།",
  "BG": "བུལ་ག་རི་ཡ།",
  "BH": "བྷཱ་རེན།",
  "BI": "བུ་རུན་ཌི།",
  "BJ": "བཱེ་ནིན།",
  "BL": "St. Barthélemy",
  "BM": "བར་མུ་ཌ།",
  "BN": "བུ་རུ་ནེ།",
  "BO": "བོ་ལི་ཝིཡ།",
  "BQ": "Caribbean Netherlands",
  "BR": "བ་རཱ་ཛིལ།",
  "BS": "བྷཱ་མས྄།",
  "BT": "འབྲུག་ཡུལ།",
  "BV": "Bouvet Island",
  "BW": "བོཙ་ཝ་ན།",
  "BY": "བེ་ལུ་རུ་སུ།",
  "BZ": "བེ་ལིཛ།",
  "CA": "ཁེ་ན་ཌ།",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo - Kinshasa",
  "CF": "Central African Republic",
  "CG": "Congo - Brazzaville",
  "CH": "ཧྲུད་ཧྲི།",
  "CI": "ཀོ་ཊེ་ཌི། ཨི་ཝོ་རེ།",
  "CK": "ཀཱུག གླིང་ཕྲེན་རྒྱལ་ཁབ།",
  "CL": "ཅི་ལི།",
  "CM": "ཀ་མེ་རུན།",
  "CN": "རྒྱ་ནག",
  "CO": "ཀོ་ལོམ་བི་ཡ།",
  "CR": "ཀོ་ས྄ཊ་རི་ཀ།",
  "CU": "ཁྱུའུ་བ།",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "སཱཡེ་པ་རས྄།",
  "CZ": "ཅཻག་སྤྱི་མཐུན་རྒྱལ་ཁབ།",
  "Cyrl": "གོ་སའི་ལ་ཧྥུ་སྐད་ཡིག་།",
  "DE": "འཇར་མན་",
  "DJ": "ཛི་བུ་ཏི།",
  "DK": "ཌེན་མཱརྐ།",
  "DM": "ཌོ་མིན་ནི་ཀ།",
  "DO": "ཌོ་མིནནི་ཀན་སྤྱི་མཐུན་རྒྱལ་ཁབ།",
  "DZ": "ཨལ་ཇི་རི་ཡ།",
  "Deva": "དེ་བ་ནཱ་ག་རཱི་སྐད་ཡིག",
  "EC": "ཨི་ཁྭ་ཌོར།",
  "EE": "ཨིསྟོ་ནི་ཡ།",
  "EG": "ཨི་ཇིབྚ།",
  "EH": "Western Sahara",
  "ER": "ཨེ་རི་ཏྲེ་ཨ།",
  "ES": "སི་པན།",
  "ET": "ཨི་ཐིའོ་པི་ཡ།",
  "FI": "ཕིན་ལན྄ཌ།",
  "FJ": "ཕི་ཇི།",
  "FK": "ཕལྐ་ལནྜ་གླིང་ཕྲན།",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "ཕ་རཱན་སི།",
  "GA": "གེ་བཽན།",
  "GB": "དབྱིན་ཇི་",
  "GD": "གྷ་རི་ན་ཌ།",
  "GE": "ཇོར་ཇི་ཡ།",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "གྷ་ན།",
  "GI": "ཇིབ་རཱལ་ཊར།",
  "GL": "Greenland",
  "GM": "གྷམ་བི་ཡ།",
  "GN": "གྷི་ནི་ཡ།",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "གྷི་རཱི་སི།",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "གྷོ་ཊེ་མ་ལ།",
  "GU": "Guam",
  "GW": "གྷི་ནི་ཡ་བིས྄་སོ།",
  "GY": "གྷུ་ཡཱ་ན།",
  "Gujr": "གུཇ་རཱཏི་སྐད།",
  "HK": "ཧོང་ཀོང༌།",
  "HM": "Heard & McDonald Islands",
  "HN": "ཧོན་དུ་རས྄།",
  "HR": "ཀུརོ་ཤི་ཡ།",
  "HT": "ཧེ་ཏི།",
  "HU": "ཧངྒ་རི།",
  "Hans": "རྒྱ་ཡིག་གསར་པ།",
  "Hant": "རྒྱ་ཡིག་རྙིང་པ།",
  "ID": "ཨིན་ཌོ་ནེ་ཤི་ཡ།",
  "IE": "ཨ་ཡར་ལནཌ།",
  "IL": "ཨི་ཛ྄་རེལ།",
  "IM": "Isle of Man",
  "IN": "རྒྱ་གར་",
  "IO": "British Indian Ocean Territory",
  "IQ": "ཨི་རག།",
  "IR": "ཨི་རཱན།",
  "IS": "ཨ་ཨི་སི་ལནད།",
  "IT": "ཨི་ཀྲར་ལི་",
  "JE": "Jersey",
  "JM": "ཛ་མེ་ཀ།",
  "JO": "ཇོར་ཌན།",
  "JP": "ཉི་ཧོང་",
  "KE": "ཁེན་ཉི་ཡ།",
  "KG": "ཁིར་གིཛ་སྟཱན།",
  "KH": "ཀམ་བོ་ཌི་ཡ།",
  "KI": "ཀི་རི་བཱ་ཏི།",
  "KM": "Comoros",
  "KN": "སེནྚ། ཀིཊྚས྄། དང༌། ནེ་བིས྄།",
  "KP": "North Korea",
  "KR": "ལྷོ་ཀོ་རི་ཡ།",
  "KW": "ཀུ་ཝེད་རྒྱལ་ཁབ།",
  "KY": "ཁེ་མེན་གླིང་ཕྲན།",
  "KZ": "ཁ་ཛཱག་སྟཱན།",
  "LA": "ལཱ་འོས།",
  "LB": "ལེབ་ནོན།",
  "LC": "སེནྚ། ལུ་ཤི་ཡ།",
  "LI": "ལེག་ཏེན་ཚིན།",
  "LK": "ཤྲཱི་ལངྐ་།",
  "LR": "ལི་བེ་རི་ཡ།",
  "LS": "ལེ་སོ་ཐོ།",
  "LT": "ལི་ཐུ་ཨེ་ནི་ཡ།",
  "LU": "ལཀ་ཛམ་བོརྒ།",
  "LV": "ལཏ་བི་ཡ།",
  "LY": "ལི་བི་ཡ།",
  "Latn": "ལ་ཏིན་སྐད་ཡིག་།",
  "MA": "མོ་རོ་ཀྐོ།",
  "MC": "མོ་ན་ཀོ།",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "མ་དཱ་གྷསྐཱར།",
  "MH": "མཱར་ཤལ་གླིང་ཕྲེན།",
  "MK": "North Macedonia",
  "ML": "མ་ལི།",
  "MM": "འབར་མ།",
  "MN": "སོག་ཡུལ།",
  "MO": "མེ་ཀའོ།",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "མཽ་རི་ཏ་ནི་ཡ།",
  "MS": "Montserrat",
  "MT": "མལ་ཊ།",
  "MU": "མཽ་རིཤས྄།",
  "MV": "མལ་དྭིབ།",
  "MW": "མཱ་ལཱ་ཝི།",
  "MX": "མེཀ་སི་ཀོ།",
  "MY": "མ་ལེ་ཤི་ཡ།",
  "MZ": "མོ་ཛམ་བིག།",
  "Mymr": "འབར་མའི་སྐད་ཡིག",
  "NA": "ན་མི་བི་ཡ།",
  "NC": "New Caledonia",
  "NE": "ནའི་ཇར།",
  "NF": "Norfolk Island",
  "NG": "ནཱའི་ཇི་རི་ཡ།",
  "NI": "ནི་ཀ་ར་གུ་ཨ།",
  "NL": "ཧའོ་ལན།",
  "NO": "ནོར་ཝེ།",
  "NP": "བལ་ཡུལ་",
  "NR": "ནཽ་རུ།",
  "NU": "ནིའུ་ཝ།",
  "NZ": "ནིའུ་ཛི་ལན྄ཌ།",
  "OM": "ཨོ་མན།",
  "PA": "པ་ནཱ་མ།",
  "PE": "པེ་རུ།",
  "PF": "French Polynesia",
  "PG": "པ་པུ་ཨ། ནིའུ། གྷི་ནི།",
  "PH": "ཕི་ལི་པིནས྄།",
  "PK": "པཀི་སྟཱན།",
  "PL": "པོ་ལནྜ།",
  "PM": "St. Pierre & Miquelon",
  "PN": "Pitcairn Islands",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territories",
  "PT": "པོར་ཏུ་གྷལ།",
  "PW": "པ་ལཽ།",
  "PY": "པཱ་ར་གེ།",
  "QA": "ཀ་ཏཱར།",
  "RE": "Réunion",
  "RO": "རོ་མཱ་ནིཡ།",
  "RS": "སེར་བི་ཡ།",
  "RU": "ཨུ་རུ་སུ་",
  "RW": "རུ་ཝན་ཌ།",
  "SA": "སཽ་དྷི་ཨ་རཱ་བི་ཡ།",
  "SB": "སོ་ལོ་མོན། གླིང་ཕྲན་ཚོ་ཁག།",
  "SC": "སཱ་ཤཻལ།",
  "SD": "སུ་དཱན།",
  "SE": "ཧྲུའི་ཏན།",
  "SG": "སིངྒ་པུར།",
  "SH": "སེནྚ། ཧེ་ལི་ན།",
  "SI": "ས་ལཽ་ཝེ་ནི་ཡ།",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "ས་ལཽ་ཝཀྱ།",
  "SL": "སེ་ཡར་ར། ལིའོན།",
  "SM": "སན་མེ་རི་ནོ།",
  "SN": "སེ་ནི་གྷལ།",
  "SO": "སོ་མཱལི་ཡ།",
  "SR": "སུ་རི་ནཱམ།",
  "SS": "South Sudan",
  "ST": "ས་འོ་ཏོད་མད། དང༌། པ྄རིན་སི་པེ།",
  "SV": "ཨེལ། སཱལ་ཝ་ཌོར།",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TC": "Turks & Caicos Islands",
  "TD": "ཅཻཌ།",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "ཏུརཀི།",
  "TT": "Trinidad & Tobago",
  "TV": "ཐུ་ཝ་ལུ།",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tibt": "བོད་ཡིག་",
  "UA": "ཡུ་ཀྲན།",
  "UG": "ཡུ་གན་ཌ།",
  "UM": "U.S. Outlying Islands",
  "US": "ཨ་མེ་རི་ཀ།",
  "UY": "ཨུ་རུ་གྷེ།",
  "UZ": "ཨུཛ་བེ་ཀིསྟཱན།",
  "VA": "ཝེ་ཊི་ཀན།",
  "VC": "སེནྚ། ཝིན་སན། དང༌། གྷིརིན་ཌིན།",
  "VE": "ཝེ་ནི་ཛུའེ་ལ།",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "བི་དི་ནམ།",
  "VU": "ཝ་ནུ་ཨ་ཐུ།",
  "WF": "Wallis & Futuna",
  "WS": "ནུ་བ་ས་མོ་འ།",
  "YE": "ཡེ་མེན།",
  "YT": "Mayotte",
  "ZA": "ལྷོ་ ཨཕྲི་ཀ།",
  "ZM": "ཛམ་བི་ཡ།",
  "ZW": "ཛིམ་བྷཱ་བེ།",
  "ZZ": "མིའི་ཤེས་རྟོགས་མ་བྱུང་བའི་ཁོར་ཡུག",
  "Zxxx": "སྙན་བརྒྱུད། ཡིག་རིགས་སུ་མ་བཀོད་པའི་ཟིན་ཐོ།",
  "Zzzz": "མིའི་ཤེས་རྟོགས་མ་བྱུང་བ། ཡང་ན་ཆད་ལྷག་ཅན་གྱི་ཟིན་བྲིས།",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Amharic",
  "am_ET": "Amharic (Ethiopia)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "Arabic",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Arabic (United Arab Emirates)",
  "ar_BH": "Arabic (Bahrain)",
  "ar_DJ": "Arabic (Djibouti)",
  "ar_DZ": "Arabic (Algeria)",
  "ar_EG": "Arabic (Egypt)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arabic (Eritrea)",
  "ar_IL": "Arabic (Israel)",
  "ar_IQ": "Arabic (Iraq)",
  "ar_JO": "Arabic (Jordan)",
  "ar_KM": "Arabic (Comoros)",
  "ar_KW": "Arabic (Kuwait)",
  "ar_LB": "Arabic (Lebanon)",
  "ar_LY": "Arabic (Libya)",
  "ar_MA": "Arabic (Morocco)",
  "ar_MR": "Arabic (Mauritania)",
  "ar_OM": "Arabic (Oman)",
  "ar_PS": "Arabic (Palestinian Territories)",
  "ar_QA": "Arabic (Qatar)",
  "ar_SA": "Arabic (Saudi Arabia)",
  "ar_SD": "Arabic (Sudan)",
  "ar_SO": "Arabic (Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Arabic (Syria)",
  "ar_TD": "Arabic (Chad)",
  "ar_TN": "Arabic (Tunisia)",
  "ar_YE": "Arabic (Yemen)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarusian",
  "be_BY": "Belarusian (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgarian",
  "bg_BG": "Bulgarian (Bulgaria)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "བྷང་ག་ལའི་སྐད།",
  "bn_BD": "Bengali (Bangladesh)",
  "bn_IN": "Bengali (India)",
  "bo": "བོད་སྐད་",
  "bo_CN": "བོད་སྐད་ (རྒྱ་ནག)",
  "bo_IN": "བོད་སྐད་ (རྒྱ་གར་)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "Czech",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "ཏེན་མག་གི་སྐད།",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "འཇར་མན་གྱི།",
  "de_AT": "German (Austria)",
  "de_BE": "German (Belgium)",
  "de_CH": "German (Switzerland)",
  "de_DE": "German (Germany)",
  "de_LI": "German (Liechtenstein)",
  "de_LU": "German (Luxembourg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "རྫོང་ཁ",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Greek",
  "el_CY": "Greek (Cyprus)",
  "el_GR": "Greek (Greece)",
  "elx": "Elamite",
  "en": "དབྱིན་ཇིའི་སྐད།",
  "en_AG": "English (Antigua & Barbuda)",
  "en_AI": "English (Anguilla)",
  "en_AS": "English (American Samoa)",
  "en_AU": "English (Australia)",
  "en_BB": "English (Barbados)",
  "en_BE": "English (Belgium)",
  "en_BM": "English (Bermuda)",
  "en_BS": "English (Bahamas)",
  "en_BW": "English (Botswana)",
  "en_BZ": "English (Belize)",
  "en_CA": "དབྱིན་ཇིའི་སྐད། (ཁེ་ན་ཌ་)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "English (Cook Islands)",
  "en_CM": "English (Cameroon)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "English (Dominica)",
  "en_ER": "English (Eritrea)",
  "en_FJ": "English (Fiji)",
  "en_FK": "English (Falkland Islands)",
  "en_FM": "English (Micronesia)",
  "en_GB": "དབྱིན་ཇིའི་སྐད། (དབྱིན་ལན་)",
  "en_GD": "English (Grenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "English (Ghana)",
  "en_GI": "English (Gibraltar)",
  "en_GM": "English (Gambia)",
  "en_GU": "English (Guam)",
  "en_GY": "English (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "English (Ireland)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "English (India)",
  "en_IO": "English (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "English (Jamaica)",
  "en_KE": "English (Kenya)",
  "en_KI": "English (Kiribati)",
  "en_KN": "English (St. Kitts & Nevis)",
  "en_KY": "English (Cayman Islands)",
  "en_LC": "English (St. Lucia)",
  "en_LR": "English (Liberia)",
  "en_LS": "English (Lesotho)",
  "en_MG": "English (Madagascar)",
  "en_MH": "English (Marshall Islands)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "English (Northern Mariana Islands)",
  "en_MS": "English (Montserrat)",
  "en_MT": "English (Malta)",
  "en_MU": "English (Mauritius)",
  "en_MW": "English (Malawi)",
  "en_MY": "English (Malaysia)",
  "en_NA": "English (Namibia)",
  "en_NF": "English (Norfolk Island)",
  "en_NG": "English (Nigeria)",
  "en_NR": "English (Nauru)",
  "en_NU": "English (Niue)",
  "en_NZ": "English (New Zealand)",
  "en_PG": "English (Papua New Guinea)",
  "en_PH": "English (Philippines)",
  "en_PK": "English (Pakistan)",
  "en_PN": "English (Pitcairn Islands)",
  "en_PR": "English (Puerto Rico)",
  "en_PW": "English (Palau)",
  "en_RW": "English (Rwanda)",
  "en_SB": "English (Solomon Islands)",
  "en_SC": "English (Seychelles)",
  "en_SD": "English (Sudan)",
  "en_SG": "English (Singapore)",
  "en_SH": "English (St. Helena)",
  "en_SL": "English (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "English (Swaziland)",
  "en_TC": "English (Turks & Caicos Islands)",
  "en_TK": "English (Tokelau)",
  "en_TO": "English (Tonga)",
  "en_TT": "English (Trinidad & Tobago)",
  "en_TV": "English (Tuvalu)",
  "en_TZ": "English (Tanzania)",
  "en_UG": "English (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "དབྱིན་ཇིའི་སྐད། (ཨ་རི་)",
  "en_VC": "English (St. Vincent & Grenadines)",
  "en_VG": "English (British Virgin Islands)",
  "en_VI": "English (U.S. Virgin Islands)",
  "en_VU": "English (Vanuatu)",
  "en_WS": "English (Samoa)",
  "en_ZA": "English (South Africa)",
  "en_ZM": "English (Zambia)",
  "en_ZW": "English (Zimbabwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "ཞི་པན་ཡའི།",
  "es_419": "Latin American Spanish",
  "es_AR": "Spanish (Argentina)",
  "es_BO": "Spanish (Bolivia)",
  "es_CL": "Spanish (Chile)",
  "es_CO": "Spanish (Colombia)",
  "es_CR": "Spanish (Costa Rica)",
  "es_CU": "Spanish (Cuba)",
  "es_DO": "Spanish (Dominican Republic)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Spanish (Ecuador)",
  "es_ES": "Spanish (Spain)",
  "es_GQ": "Spanish (Equatorial Guinea)",
  "es_GT": "Spanish (Guatemala)",
  "es_HN": "Spanish (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Spanish (Mexico)",
  "es_NI": "Spanish (Nicaragua)",
  "es_PA": "Spanish (Panama)",
  "es_PE": "Spanish (Peru)",
  "es_PH": "Spanish (Philippines)",
  "es_PR": "Spanish (Puerto Rico)",
  "es_PY": "Spanish (Paraguay)",
  "es_SV": "Spanish (El Salvador)",
  "es_US": "Spanish (United States)",
  "es_UY": "Spanish (Uruguay)",
  "es_VE": "Spanish (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Persian",
  "fa_AF": "Persian (Afghanistan)",
  "fa_IR": "Persian (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "ཧྥ་རན་སིའི་།",
  "fr_BE": "French (Belgium)",
  "fr_BF": "French (Burkina Faso)",
  "fr_BI": "French (Burundi)",
  "fr_BJ": "French (Benin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "French (Canada)",
  "fr_CD": "French (Congo - Kinshasa)",
  "fr_CF": "French (Central African Republic)",
  "fr_CG": "French (Congo - Brazzaville)",
  "fr_CH": "French (Switzerland)",
  "fr_CI": "French (Côte d’Ivoire)",
  "fr_CM": "French (Cameroon)",
  "fr_DJ": "French (Djibouti)",
  "fr_DZ": "French (Algeria)",
  "fr_FR": "French (France)",
  "fr_GA": "French (Gabon)",
  "fr_GF": "French (French Guiana)",
  "fr_GN": "French (Guinea)",
  "fr_GP": "French (Guadeloupe)",
  "fr_GQ": "French (Equatorial Guinea)",
  "fr_HT": "French (Haiti)",
  "fr_KM": "French (Comoros)",
  "fr_LU": "French (Luxembourg)",
  "fr_MA": "French (Morocco)",
  "fr_MC": "French (Monaco)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "French (Madagascar)",
  "fr_ML": "French (Mali)",
  "fr_MQ": "French (Martinique)",
  "fr_MR": "French (Mauritania)",
  "fr_MU": "French (Mauritius)",
  "fr_NC": "French (New Caledonia)",
  "fr_NE": "French (Niger)",
  "fr_PF": "French (French Polynesia)",
  "fr_PM": "French (St. Pierre & Miquelon)",
  "fr_RE": "French (Réunion)",
  "fr_RW": "French (Rwanda)",
  "fr_SC": "French (Seychelles)",
  "fr_SN": "French (Senegal)",
  "fr_SY": "French (Syria)",
  "fr_TD": "French (Chad)",
  "fr_TG": "French (Togo)",
  "fr_TN": "French (Tunisia)",
  "fr_VU": "French (Vanuatu)",
  "fr_WF": "French (Wallis & Futuna)",
  "fr_YT": "French (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "གཱ་སྐད།",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "གུཇ་རཱཏི་སྐད།",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "ཧིན་དི",
  "hi_IN": "ཧིན་དི (རྒྱ་གར་)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "Hungarian",
  "hu_HU": "Hungarian (Hungary)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "ཨིན་དོ་ནི་སི་སྐད།",
  "id_ID": "Indonesian (Indonesia)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "དབྱི་ཏ་་ལའི་མི།",
  "it_CH": "Italian (Switzerland)",
  "it_IT": "Italian (Italy)",
  "it_SM": "Italian (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "ཉི་ཧོང་སྐད་",
  "ja_JP": "རི་པིན་སྐད་ (རི་པིན་)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Javanese",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodia)",
  "kmb": "Kimbundu",
  "kn": "ཀནྣ་ཌ་སྐད།",
  "kn_IN": "Kannada (India)",
  "ko": "ཁོ་རེ་ཡའི་སྐད།",
  "ko_KP": "Korean (North Korea)",
  "ko_KR": "Korean (South Korea)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "ལཱ་ཏིན་སྐད།",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "སོག་སྐད།",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "མ་ར་ཐི་སྐད།",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "མ་ལ་ཡ་སྐད།",
  "ms_BN": "Malay (Brunei)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malay (Singapore)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "འབར་མའི་སྐད།",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "ན་མི་བི་ཡ།",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "ནེ་པ་ལི",
  "ne_IN": "ནེ་པ་ལི (རྒྱ་གར་)",
  "ne_NP": "ནེ་པ་ལི (བར་ཡུལ་)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "ཧའོ་ལན་སྐད།",
  "nl_AW": "Dutch (Aruba)",
  "nl_BE": "Dutch (Belgium)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Dutch (Netherlands)",
  "nl_SR": "Dutch (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "ནོ་ཝེ་སྐད།",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "ཨཽ་རི་ཡ་སྐད།",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "Punjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "པོ་ལན་སྐད།",
  "pl_PL": "Polish (Poland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "ཕི་ཐོ་ཡའི།",
  "pt_AO": "Portuguese (Angola)",
  "pt_BR": "པ་ཞའི་མི། ཕི་ཐོ་ཡའི་མི།",
  "pt_CV": "Portuguese (Cape Verde)",
  "pt_GW": "Portuguese (Guinea-Bissau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Portuguese (Mozambique)",
  "pt_PT": "Portuguese (Portugal)",
  "pt_ST": "Portuguese (São Tomé & Príncipe)",
  "pt_TL": "Portuguese (Timor-Leste)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Romanian",
  "ro_MD": "Romanian (Moldova)",
  "ro_RO": "Romanian (Romania)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "ཨུ་རུ་སུ་སྐད་",
  "ru_BY": "Russian (Belarus)",
  "ru_KG": "Russian (Kyrgyzstan)",
  "ru_KZ": "Russian (Kazakhstan)",
  "ru_MD": "Russian (Moldova)",
  "ru_RU": "ཨུ་རུ་སུ་སྐད་ (ཨུ་རུ་སུ་)",
  "ru_UA": "Russian (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "སཾ་སྐྲྀ་ཏ།",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "ཞི་ལན་སྐད།",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somali",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "ཧྲུའི་ཏན་སྐད།",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Swedish (Finland)",
  "sv_SE": "Swedish (Sweden)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "ཏཱ་མིལ་སྐད།",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Malaysia)",
  "ta_SG": "Tamil (Singapore)",
  "tcy": "Tulu",
  "te": "ཏེ་ལུ་གུ་སྐད།",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "ཐའའི་ཡུལ་སྐད།",
  "th_TH": "Thai (Thailand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "ཐུར་ཁེའི་སྐད།",
  "tr_CY": "Turkish (Cyprus)",
  "tr_TR": "Turkish (Turkey)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "ཡུ་གུར་སྐད།",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "ཡུ་ཀྲ་ནི་སྐད།",
  "uk_UA": "Ukrainian (Ukraine)",
  "umb": "Umbundu",
  "und": "མིའི་ཤེས་རྟོགས་མ་བྱུང་བ། ཡང་ན་ཆད་ལྷག་ཅན་གྱི་སྐད་བརྡ།",
  "ur": "ཝུའུ་ཏུའུ་སྐད།",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "ཡོ་ནན་སྐད།",
  "vi_VN": "Vietnamese (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "ཟེ་ན་གཱ་སྐད།",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "རྒྱ་སྐད་",
  "zh_CN": "རྒྱ་སྐད་ (རྒྱ་ནག)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "སྟབས་བརྡའི། ཀྲུང་གོའི།",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "སྲོལ་རྒྱུན་གྱི།",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Chinese (Singapore)",
  "zh_TW": "Chinese (Taiwan)",
  "zu": "ཟུ་ལུ་སྐད།",
  "zu_ZA": "Zulu (South Africa)",
  "zun": "ཟུ་ནི་སྐད།",
  "zxx": "No linguistic content",
  "zza": "ཟ་ཟའ་སྐད།"
};
