const names = {
  "MK": "North Macedonia",
  "aa": "Afar",
  "ab": "abkhaziskt",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "af": "afríska",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "an": "Aragonese",
  "anp": "Angika",
  "ar_001": "Modern Standard Arabic",
  "arn": "Mapuche",
  "arp": "Arapaho",
  "asa": "asu (Tanzania)",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "az": "azerbaijaniskt",
  "ba": "Bashkir",
  "ban": "Balinese",
  "bas": "Basaa",
  "bez": "bena (Tanzania)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bn": "bengaliskt",
  "bo": "tibetanskt",
  "brx": "Bodo",
  "bug": "Buginese",
  "byn": "Blin",
  "ca": "katalanskt",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "valisiskt",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de_CH": "týskt (Sveis)",
  "dgr": "Dogrib",
  "dje": "Zarma",
  "dsb": "Lower Sorbian",
  "dua": "Duala",
  "dyo": "Jola-Fonyi",
  "dzg": "Dazaga",
  "ebu": "kiembu",
  "ee": "Ewe",
  "eka": "Ekajuk",
  "el": "grikiskt",
  "et": "estlendskt",
  "ewo": "Ewondo",
  "ff": "Fulah",
  "fj": "fidjianskt",
  "fon": "Fon",
  "fur": "Friulian",
  "fy": "vestfrisikt",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gor": "Gorontalo",
  "gsw": "Swiss German",
  "gu": "gujariti",
  "guz": "Gusii",
  "gv": "Manx",
  "gwi": "Gwichʼin",
  "ha": "haussa",
  "hak": "Hakka Chinese",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "haitiskt",
  "hup": "Hupa",
  "hz": "Herero",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ii": "Sichuan Yi",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "iu": "Inuktitut",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jv": "javanesiskt",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "kapverdiskt",
  "kfo": "Koro",
  "kha": "Khasi",
  "khq": "Koyra Chiini",
  "ki": "Kikuyu",
  "kj": "Kuanyama",
  "kk": "kazakiskt",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kln": "Kalenjin",
  "km": "kambodjanskt",
  "kmb": "Kimbundu",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "kashmiriskt",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "kum": "Kumyk",
  "kv": "Komi",
  "kw": "Cornish",
  "ky": "kirgisikt",
  "lad": "Ladino",
  "lag": "Langi",
  "lb": "luxemburgiskt",
  "lez": "Lezghian",
  "lg": "Ganda",
  "li": "Limburgish",
  "lkt": "Lakota",
  "lo": "laotiskt",
  "loz": "Lozi",
  "lt": "litavskt",
  "lu": "Luba-Katanga",
  "lua": "Luba-Lulua",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "olulujia",
  "lv": "latviskt",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "mas": "Masai",
  "mdf": "Moksha",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "malagasiskt",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "maoriskt",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "makedonskt",
  "mn": "mongoliskt",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "marathiskt",
  "ms": "malajiskt",
  "mt": "maltesiskt",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "norskt bokmál",
  "nd": "North Ndebele",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl": "hollendskt",
  "nl_BE": "hollendskt (Belgia)",
  "nmg": "Kwasio",
  "nnh": "Ngiemboon",
  "nog": "Nogai",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nyn": "Nyankole",
  "oc": "occitan",
  "om": "Oromo",
  "or": "oriya",
  "pa": "punjabiskt",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pl": "polskt",
  "prg": "Prussian",
  "ps": "afghanskt",
  "pt": "portugisiskt",
  "pt_BR": "portugisiskt (Brasilia)",
  "pt_PT": "portugisiskt (Portugal)",
  "quc": "Kʼicheʼ",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "romansh",
  "ro": "romanskt",
  "ro_MD": "romanskt (Moldova)",
  "rof": "Rombo",
  "rup": "Aromanian",
  "rw": "ruanda",
  "rwk": "Rwa",
  "sad": "Sandawe",
  "sah": "Sakha",
  "saq": "Samburu",
  "sat": "Santali",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "se": "Northern Sami",
  "seh": "Sena",
  "ses": "Koyraboro Senni",
  "shi": "Tachelhit",
  "shn": "Shan",
  "si": "sinhalesiskt",
  "sm": "samoiskt",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "snk": "Soninke",
  "srn": "Sranan Tongo",
  "ssy": "Saho",
  "suk": "Sukuma",
  "swb": "shimaoré",
  "syr": "Syriac",
  "te": "telugiskt",
  "tem": "Timne",
  "teo": "Teso",
  "tg": "tajikiskt",
  "th": "thailendskt",
  "tig": "Tigre",
  "trv": "Taroko",
  "tt": "tatariskt",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "twq": "Tasawaq",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "uighur",
  "umb": "Umbundu",
  "und": "ukjent mál",
  "uz": "uzbekiskt",
  "vai": "Vai",
  "vi": "vietnamesiskt",
  "vo": "Volapük",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xog": "Soga",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yue": "kantonesískt",
  "zgh": "Standard Moroccan Tamazight",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hant": "Chinese (Traditional)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
