const names = {
  "009": "ཨོཤི་ཡཱན་ན།",
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua & Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AZ": "Azerbaijan",
  "BA": "Bosnia & Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CH": "Switzerland",
  "CI": "Côte d’Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FR": "France",
  "GA": "Gabon",
  "GD": "Grenada",
  "GE": "Georgia",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GM": "Gambia",
  "GN": "Guinea",
  "GR": "Greece",
  "GT": "Guatemala",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong SAR China",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "JM": "Jamaica",
  "JO": "Jordan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KN": "St. Kitts & Nevis",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao SAR China",
  "MR": "Mauritania",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NE": "Niger",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RO": "Romania",
  "RS": "Serbia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "St. Helena",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "ST": "São Tomé & Príncipe",
  "SV": "El Salvador",
  "TD": "Chad",
  "TR": "Turkey",
  "TV": "Tuvalu",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "VC": "St. Vincent & Grenadines",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WS": "Samoa",
  "YE": "Yemen",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "bn": "Bengali",
  "da": "Danish",
  "de": "German",
  "en": "English",
  "en_CA": "English (Canada)",
  "en_GB": "English (United Kingdom)",
  "en_US": "English (United States)",
  "es": "Spanish",
  "fr": "French",
  "gaa": "Ga",
  "gu": "Gujarati",
  "id": "Indonesian",
  "it": "Italian",
  "ja": "རི་པིན་སྐད་",
  "kn": "Kannada",
  "ko": "Korean",
  "la": "Latin",
  "mn": "Mongolian",
  "mr": "Marathi",
  "ms": "Malay",
  "my": "Burmese",
  "nan": "Min Nan Chinese",
  "nl": "Dutch",
  "nn": "Norwegian Nynorsk",
  "or": "Oriya",
  "pl": "Polish",
  "pt": "Portuguese",
  "pt_BR": "Portuguese (Brazil)",
  "sa": "Sanskrit",
  "si": "Sinhala",
  "sv": "Swedish",
  "ta": "Tamil",
  "te": "Telugu",
  "th": "Thai",
  "tr": "Turkish",
  "ug": "Uyghur",
  "uk": "Ukrainian",
  "und": "Unknown Language",
  "ur": "Urdu",
  "vi": "Vietnamese",
  "zen": "Zenaga",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hant": "Chinese (Traditional)",
  "zu": "Zulu",
  "zun": "Zuni",
  "zza": "Zaza"
};
