const names = {
  "CO": "Colombia",
  "af": "Afrikaans",
  "agq": "Aghem",
  "ar_001": "Modern Standard Arabic",
  "as": "Assamese",
  "ast": "Asturian",
  "az": "Azerbaijani",
  "bm": "Bambara",
  "bn": "Bangaali",
  "bo": "Tibetan",
  "br": "Breton",
  "bs": "Bosnian",
  "ca": "Catalan",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "chr": "Cherokee",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cu": "Church Slavic",
  "da": "Danish",
  "dav": "Taita",
  "dua": "Duala",
  "dyo": "Jola-Fonyi",
  "dz": "Dzongkha",
  "ebu": "Embu",
  "ee": "Ewe",
  "es_419": "Latin American Spanish",
  "es_ES": "Isbaanish (Isbeyn)",
  "et": "Estonian",
  "eu": "Basque",
  "ewo": "Ewondo",
  "ff": "Fulah",
  "fi": "Finnish",
  "fil": "Filipino",
  "fo": "Faroese",
  "frc": "Cajun French",
  "fur": "Friulian",
  "ga": "Irish",
  "gd": "Scottish Gaelic",
  "gl": "Galician",
  "gn": "Guarani",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "guz": "Gusii",
  "gv": "Manx",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "hmn": "Hmong",
  "hr": "Croatian",
  "hsb": "Upper Sorbian",
  "ht": "Haitian",
  "hy": "Armenian",
  "ia": "Interlingua",
  "id": "Indunuusiyaan",
  "ii": "Sichuan Yi",
  "is": "Icelandic",
  "ja": "Jabbaaniis",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "ka": "Georgian",
  "kab": "Kabyle",
  "kam": "Kamba",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "khq": "Koyra Chiini",
  "ki": "Kikuyu",
  "kk": "Kazakh",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kln": "Kalenjin",
  "kn": "Kannada",
  "ks": "Kashmiri",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kw": "Cornish",
  "ky": "Kyrgyz",
  "la": "Latin",
  "lag": "Langi",
  "lb": "Luxembourgish",
  "lg": "Ganda",
  "lkt": "Lakota",
  "lt": "Lithuanian",
  "lu": "Luba-Katanga",
  "luo": "Luo",
  "luy": "Luyia",
  "lv": "Latvian",
  "mai": "Maithili",
  "mas": "Masai",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mi": "Maori",
  "mk": "Macedonian",
  "mn": "Mongolian",
  "mr": "Marathi",
  "mt": "Maltese",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mzn": "Mazanderani",
  "nb": "Norwegian Bokmål",
  "nd": "North Ndebele",
  "nds": "Low German",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "nus": "Nuer",
  "ny": "Nyanja",
  "nyn": "Nyankole",
  "oc": "Occitan",
  "or": "Oriya",
  "os": "Ossetic",
  "prg": "Prussian",
  "ps": "Pashto",
  "qu": "Quechua",
  "rm": "Romansh",
  "rn": "Rundi",
  "root": "Root",
  "rw": "Rwanda",
  "rwk": "Rwa",
  "sah": "Sakha",
  "saq": "Samburu",
  "sd": "Sindhi",
  "se": "Northern Sami",
  "seh": "Sena",
  "ses": "Koyraboro Senni",
  "sh": "Serbo-Croatian",
  "shi": "Tachelhit",
  "si": "Sinhala",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sm": "Samoan",
  "smn": "Inari Sami",
  "sn": "Shona",
  "sq": "Albanian",
  "sr": "Serbian",
  "st": "Southern Sotho",
  "su": "Sundanese",
  "sw": "Swahili",
  "te": "Telugu",
  "teo": "Teso",
  "tg": "Tajik",
  "tk": "Turkmen",
  "tlh": "Klingon",
  "to": "Tongan",
  "tt": "Tatar",
  "tw": "Twi",
  "twq": "Tasawaq",
  "tzm": "Central Atlas Tamazight",
  "ug": "Uyghur",
  "und": "Unknown Language",
  "uz": "Uzbek",
  "vai": "Vai",
  "vo": "Volapük",
  "vun": "Vunjo",
  "wae": "Walser",
  "wo": "Wolof",
  "xh": "Xhosa",
  "xog": "Soga",
  "yav": "Yangben",
  "yi": "Yiddish",
  "yue": "Cantonese",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "Jayniis",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hant": "Chinese (Traditional)",
  "zxx": "No linguistic content"
};
