const names = {
  "Arab": "persisk-arabiska",
  "ar_PS": "arabiska (Palestinska området)",
  "ar_SD": "arabiska (Nordsudan)",
  "bbc": "Batak Toba",
  "cps": "Capiznon",
  "cy_GB": "walesiska (Förenade kungariket)",
  "dz": "bhutanesiska",
  "en_GB": "engelska (Förenade kungariket)",
  "en_KN": "engelska (Saint Kitts och Nevis)",
  "en_LC": "engelska (Saint Lucia)",
  "en_PN": "engelska (Pitcairn)",
  "en_SD": "engelska (Nordsudan)",
  "en_SH": "engelska (Saint Helena)",
  "en_SX": "engelska (Sint Martin)",
  "en_TK": "engelska (Tokelauöarna)",
  "en_US": "engelska (Förenta staterna)",
  "en_VC": "engelska (Saint Vincent och Grenadinerna)",
  "es_US": "spanska (Förenta staterna)",
  "esu": "Central Yupik",
  "ext": "Extremaduran",
  "fr_BL": "franska (Saint-Barthélemy)",
  "fr_CD": "franska (Demokratiska republiken Kongo)",
  "fr_CG": "franska (Kongo)",
  "fr_MF": "franska (S:t Martin (franska delen))",
  "fr_PM": "franska (Saint Pierre och Miquelon)",
  "fr_WF": "franska (Wallis- och Futuna)",
  "gd": "höglandsskotska",
  "gd_GB": "höglandsskotska (Förenade kungariket)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "ken": "Kenyang",
  "kgp": "Kaingang",
  "khq": "Timbuktu-songhoy",
  "kiu": "Kirmanjki",
  "km": "khmer",
  "km_KH": "khmer (Kambodja)",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "ks": "kashmiri",
  "ks_Arab": "kashmiri (arabiska)",
  "ks_Arab_IN": "kashmiri (arabiska, Indien)",
  "ks_IN": "kashmiri (Indien)",
  "kw_GB": "korniska (Förenade kungariket)",
  "ky_Cyrl": "kirgiziska (kyrilliska)",
  "ky_Cyrl_KG": "kirgiziska (kyrilliska, Kirgizistan)",
  "ky_KG": "kirgiziska (Kirgizistan)",
  "lfn": "Lingua Franca Nova",
  "ln_CD": "lingala (Demokratiska republiken Kongo)",
  "ln_CG": "lingala (Kongo)",
  "lo": "lao",
  "lo_LA": "lao (Laos)",
  "lu_CD": "luba-katanga (Demokratiska republiken Kongo)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mwv": "Mentawai",
  "my_MM": "burmesiska (Burma)",
  "na": "nauru",
  "nb": "bokmål",
  "nb_NO": "bokmål (Norge)",
  "nb_SJ": "bokmål (Svalbard och Jan Mayen)",
  "njo": "Ao Naga",
  "nl_BQ": "nederländska (Bonaire, S:t Eustatius och Saba)",
  "nl_SX": "nederländska (Sint Martin)",
  "nov": "Novial",
  "pa": "panjabi",
  "pa_Arab": "panjabi (arabiska)",
  "pa_Arab_PK": "panjabi (arabiska, Pakistan)",
  "pa_Guru": "panjabi (gurmukhi)",
  "pa_Guru_IN": "panjabi (gurmukhi, Indien)",
  "pa_IN": "panjabi (Indien)",
  "pa_PK": "panjabi (Pakistan)",
  "pon": "ponape",
  "ps": "pashto",
  "ps_AF": "pashto (Afghanistan)",
  "sc": "sardiska",
  "sei": "Seri",
  "ses": "Gao-songhay",
  "shu": "Chad-arabiska",
  "sly": "Selayar",
  "te_IN": "telugu (Indien)",
  "th": "thai",
  "th_TH": "thai (Thailand)",
  "ti": "tigrinska",
  "ti_ER": "tigrinska (Eritrea)",
  "ti_ET": "tigrinska (Etiopien)",
  "tkr": "Tsakhur",
  "tru": "Turoyo",
  "ttt": "Muslim Tat",
  "wbp": "Warlpiri",
  "xmf": "Mingrelian",
  "yrl": "Nheengatu"
};
