const names = {
  "aa": "Afarski",
  "ace": "Ačineski",
  "ach": "Akoli",
  "ada": "Adangmejski",
  "ady": "Adigejski",
  "ae": "Avestanski",
  "afh": "Afrihili",
  "ain": "Ainu",
  "ak": "akan",
  "akk": "Akadijski",
  "ale": "Aljut",
  "alt": "Južni altai",
  "an": "Aragonežanski",
  "ang": "Staroengleski",
  "anp": "Angika",
  "ar_001": "moderan standardni arapski",
  "arc": "Armajski",
  "arp": "Arapaho",
  "arw": "Aravak",
  "ast": "Asturijski",
  "av": "Avarski",
  "awa": "Avadhi",
  "ay": "Ajmara",
  "bal": "Baluči",
  "ban": "Balinezijski",
  "bas": "Basa",
  "bej": "Beja",
  "bho": "Bojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bla": "Sisika",
  "bra": "Braj",
  "bua": "Buriat",
  "bug": "Buginežanski",
  "byn": "Blin",
  "cad": "Kado",
  "car": "Karipski",
  "cch": "Atsamski",
  "ce": "Čečenski",
  "ceb": "Cebuano",
  "ch": "Čamoro",
  "chb": "Čibča",
  "chg": "Čagatai",
  "chk": "Čukeski",
  "chm": "Mari",
  "chn": "Činukski",
  "cho": "Čoktavski",
  "chp": "Čipvijanski",
  "chy": "Čejenski",
  "ckb": "sorani kurdski",
  "cop": "Koptski",
  "cr": "Kri",
  "crh": "Krimeanski turski",
  "csb": "Kašubijanski",
  "cu": "Staroslovenski",
  "cv": "Čuvaški",
  "dak": "Dakota",
  "dar": "Dargva",
  "del": "Delaver",
  "den": "Slavski",
  "dgr": "Dogrib",
  "din": "Dinka",
  "doi": "Dogri",
  "dsb": "donji lužičkosrpski",
  "dum": "Srednji holandski",
  "dv": "Divehijski",
  "dyu": "Đula",
  "dzg": "Dazaga",
  "efi": "Efikski",
  "egy": "Staroegipatski",
  "eka": "Ekajuk",
  "elx": "Elamitski",
  "es_419": "Latin American Spanish",
  "ewo": "Evondo",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "fon": "Fon",
  "frc": "Cajun French",
  "frm": "Srednji francuski",
  "fro": "Starofrancuski",
  "frr": "Severno-frizijski",
  "frs": "Istočni frizijski",
  "fur": "Friulijski",
  "gaa": "Ga",
  "gay": "Gajo",
  "gba": "Gbaja",
  "gd": "Škotski Galski",
  "gez": "Džiz",
  "gil": "Gilbertški",
  "gmh": "Srednji visoki nemački",
  "goh": "Staronemački",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gotski",
  "grb": "Grebo",
  "grc": "Starogrčki",
  "gsw": "Švajcarski nemački",
  "gv": "Manks",
  "gwi": "Gvič’in",
  "hai": "Haida",
  "hil": "Hiligajnon",
  "hit": "Hitite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hsb": "gornji lužičkosrpski",
  "ht": "Haitski",
  "hup": "Hupa",
  "hz": "Herero",
  "ia": "Interlingva",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ie": "Međujezički",
  "ii": "sečuan ji",
  "ik": "Unupiak",
  "ilo": "Iloko",
  "inh": "Ingviški",
  "io": "Ido",
  "iu": "inuktitut",
  "jbo": "Lojban",
  "jpr": "Judeo-persijski",
  "jrb": "Judeo-arapski",
  "kaa": "Kara-kalpaški",
  "kac": "Kačin",
  "kaj": "Đu",
  "kaw": "Kavi",
  "kbd": "Kabardijski",
  "kcg": "Tjap",
  "kea": "zelenortski kreolski",
  "kfo": "Koro",
  "kg": "Kongo",
  "kha": "Kasi",
  "kho": "Kotaneški",
  "kj": "Kuanjama",
  "kkj": "Kako",
  "kl": "kalalisut",
  "kln": "kalendžin",
  "kmb": "Kimbundu",
  "kos": "Kosreanski",
  "kpe": "Kpele",
  "kr": "Kanuri",
  "krc": "Karačaj-balkar",
  "kri": "Krio",
  "krl": "Karelijski",
  "kru": "Kurukh",
  "ksh": "Colognian",
  "kum": "Kumik",
  "kut": "Kutenai",
  "kv": "Komi",
  "lad": "Ladino",
  "lah": "Landa",
  "lam": "Lamba",
  "lez": "Lezgian",
  "li": "Limburgiš",
  "lo": "laoški",
  "lol": "Mongo",
  "loz": "Lozi",
  "lua": "Luba-lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "lus": "Lušai",
  "mad": "Madureški",
  "mag": "Magahi",
  "mai": "Maitili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "masai",
  "mdf": "Mokša",
  "mdr": "Mandar",
  "men": "Mende",
  "mga": "Srednji irski",
  "mgh": "makuva-meeto",
  "mh": "Maršalski",
  "mic": "Mikmak",
  "min": "Minangkabau",
  "mnc": "Manču",
  "mni": "Manipuri",
  "moh": "mohok",
  "mos": "Mosi",
  "mus": "Kriški",
  "mwl": "Mirandeški",
  "mwr": "Marvari",
  "myv": "Erzija",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitanski",
  "nb": "norveški bokmal",
  "nds": "Niski nemački",
  "new": "Nevari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl_BE": "holandski (Belgija)",
  "nnh": "Ngiemboon",
  "no": "Norveški",
  "nog": "Nogai",
  "non": "Stari norski",
  "nqo": "N’ko",
  "nr": "Južni ndebele",
  "nso": "Severni soto",
  "nv": "Navaho",
  "nwc": "Klasični nevari",
  "ny": "Njanja",
  "nym": "Njamvezi",
  "nyo": "Njoro",
  "nzi": "Nzima",
  "oc": "Provansalski",
  "oj": "Ojibva",
  "or": "orija",
  "os": "Osetski",
  "osa": "Osage",
  "ota": "Otomanski turski",
  "pa": "pandžabi",
  "pag": "Pangasinski",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauanski",
  "peo": "Staropersijski",
  "phn": "Feničanski",
  "pi": "Pali",
  "pon": "Ponpejski",
  "prg": "Prussian",
  "pro": "Staroprovansalski",
  "raj": "Rađastani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "reto-romanski",
  "rn": "rundi",
  "rom": "Romani",
  "root": "Rut",
  "rup": "Aromanijski",
  "sad": "Sandave",
  "sah": "Jakut",
  "sam": "Samaritanski aramejski",
  "sas": "Sasak",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinjaski",
  "scn": "Sicilijanski",
  "sco": "Škotski",
  "sel": "Selkap",
  "sga": "Staroirski",
  "sh": "Srpskohrvatski",
  "shn": "Šan",
  "si": "sinhalski",
  "sid": "Sidamo",
  "sm": "Samoanski",
  "snk": "Soninke",
  "sog": "Sodžijenski",
  "srn": "Srananski tongo",
  "srr": "Serer",
  "ss": "Svati",
  "ssy": "Saho",
  "st": "Sesoto",
  "su": "sudanski",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerski",
  "swb": "Komorski",
  "syc": "Klasični sirijski",
  "syr": "Sirijski",
  "tem": "Timne",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tađik",
  "th": "tajlandski",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tkl": "Tokelau",
  "tl": "Tagalski",
  "tlh": "Klingonski",
  "tli": "Tlingit",
  "tmh": "Tamašek",
  "tn": "Tsvana",
  "to": "tonga",
  "tog": "Njasa tonga",
  "tpi": "Tok Pisin",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsi": "Tsimšian",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Tvi",
  "ty": "Tahićanski",
  "tyv": "Tuvinijski",
  "udm": "Udmurt",
  "uga": "Ugaritski",
  "umb": "Umbundu",
  "ve": "Venda",
  "vo": "Volapuk",
  "vot": "Votski",
  "wa": "Valun",
  "wae": "Walser",
  "wal": "Valamo",
  "war": "Varaj",
  "was": "Vašo",
  "wbp": "Warlpiri",
  "xal": "Kalmik",
  "yao": "Jao",
  "yap": "Japeški",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Jidiš",
  "yue": "Kantonski",
  "za": "Žuang",
  "zap": "Zapotečki",
  "zbl": "Blisimboli",
  "zen": "Zenaga",
  "zh_Hans": "kineski (pojednostavljeno kinesko pismo)",
  "zh_Hant": "kineski (tradicionalno kinesko pismo)",
  "zun": "Zuni",
  "zza": "Zaza"
};
