const names = {
  "av": "Avaric",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bug": "Buginese",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chy": "Cheyenne",
  "ckb": "სორანი ქურთული",
  "dak": "დაკოტა",
  "del": "დელავარული",
  "den": "Slave",
  "dum": "Middle Dutch",
  "dzg": "Dazaga",
  "eka": "Ekajuk",
  "enm": "Middle English",
  "ff": "Fulah",
  "frm": "Middle French",
  "gaa": "Ga",
  "gil": "Gilbertese",
  "gmh": "Middle High German",
  "gor": "Gorontalo",
  "gwi": "Gwichʼin",
  "hil": "Hiligaynon",
  "hit": "ხეთური ენა",
  "hmn": "Hmong",
  "ht": "ჰაიტიური",
  "hup": "Hupa",
  "hz": "Herero",
  "ilo": "Iloko",
  "kaj": "Jju",
  "kcg": "Tyap",
  "kfo": "Koro",
  "kha": "Khasi",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kos": "Kosraean",
  "ksh": "Colognian",
  "lt": "ლიტვური",
  "lua": "Luba-Lulua",
  "mad": "Madurese",
  "mak": "Makasar",
  "mga": "Middle Irish",
  "mgo": "მეტა’ ენა",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mos": "Mossi",
  "mul": "Multiple Languages",
  "mzn": "Mazanderani",
  "nds": "Low German",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nnh": "Ngiemboon",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "prg": "Prussian",
  "root": "Root",
  "rup": "Aromanian",
  "sad": "Sandawe",
  "sat": "Santali",
  "sba": "Ngambay",
  "sco": "Scots",
  "sma": "სამხრეთ საამური",
  "snk": "Soninke",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "suk": "Sukuma",
  "tem": "Timne",
  "tet": "Tetum",
  "ti": "თიგრინია",
  "tpi": "Tok Pisin",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "ty": "Tahitian",
  "umb": "Umbundu",
  "ve": "Venda",
  "vo": "Volapük",
  "wa": "Walloon",
  "wae": "Walser",
  "war": "Waray",
  "wbp": "Warlpiri",
  "yav": "Yangben",
  "ybb": "Yemba",
  "zun": "Zuni"
};
