const names = {
  "Arab": "Basa Arab",
  "BR": "Brasil",
  "CN": "Tiongkok",
  "Cyrl": "Sirilik",
  "DE": "Jérman",
  "FR": "Prancis",
  "GB": "Inggris Raya",
  "Hans": "Sederhana",
  "Hant": "Tradisional",
  "IN": "India",
  "IT": "Italia",
  "JP": "Jepang",
  "Latn": "Latin",
  "RU": "Rusia",
  "US": "Amérika Sarikat",
  "ZZ": "Wilayah Teu Dipikaterang",
  "Zxxx": "Non-tulisan",
  "Zzzz": "Skrip Teu Dipikaterang",
  "de": "Jérman",
  "de_AT": "Jérman Austria",
  "de_CH": "Jérman Swiss Luhur",
  "en": "Inggris",
  "en_AU": "Inggris Australia",
  "en_CA": "Inggris Kanada",
  "en_GB": "Inggris Inggris",
  "en_US": "Inggris Amerika",
  "es": "Spanyol",
  "es_419": "Spanyol Amérika Latin",
  "es_ES": "Spanyol Éropa",
  "es_MX": "Spanyol Méksiko",
  "fr": "Prancis",
  "fr_CA": "Prancis Kanada",
  "fr_CH": "Prancis Swiss",
  "it": "Italia",
  "ja": "Jepang",
  "pt": "Portugis",
  "pt_BR": "Portugis Brasil",
  "pt_PT": "Portugis Éropa",
  "ru": "Rusia",
  "su": "Basa Sunda",
  "und": "Teu Dipikaterang",
  "zh": "Tiongkok",
  "zh_Hans": "Tiongkok Sederhana",
  "zh_Hant": "Tiongkok Tradisional"
};
