const names = {
  "001": "Mundo",
  "002": "África",
  "003": "América do Norte",
  "005": "América do Sur",
  "009": "Oceanía",
  "011": "África Occidental",
  "013": "América Central",
  "014": "África Oriental",
  "015": "África Setentrional",
  "017": "África Central",
  "018": "África Meridional",
  "019": "América",
  "021": "América Setentrional",
  "029": "Caribe",
  "030": "Asia Oriental",
  "034": "Asia Meridional",
  "035": "Sueste Asiático",
  "039": "Europa Meridional",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Rexión de Micronesia",
  "061": "Polinesia",
  "062": "Centro-sur de Asia",
  "142": "Asia",
  "143": "Asia Central",
  "145": "Asia Occidental",
  "150": "Europa",
  "151": "Europa do Leste",
  "154": "Europa Setentrional",
  "155": "Europa Occidental",
  "172": "Comunidade de Estados Independentes",
  "200": "Checoslovaquia",
  "202": "África subsahariana",
  "419": "América Latina",
  "830": "Illas da Canle",
  "AC": "Illa de Ascensión",
  "AD": "Andorra",
  "AE": "Os Emiratos Árabes Unidos",
  "AF": "Afganistán",
  "AG": "Antigua e Barbuda",
  "AI": "Anguila",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antillas Holandesas",
  "AO": "Angola",
  "AQ": "A Antártida",
  "AR": "A Arxentina",
  "AS": "Samoa Americana",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Illas Åland",
  "AZ": "Acerbaixán",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Albanés caucásico",
  "Ahom": "Ahom",
  "Arab": "árabe",
  "Aran": "Nastaliq",
  "Armi": "Arameo imperial",
  "Armn": "armenio",
  "Avst": "Avestán",
  "BA": "Bosnia e Hercegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Bélxica",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benín",
  "BL": "Saint Barthélemy",
  "BM": "Illas Bermudas",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribe Neerlandés",
  "BR": "O Brasil",
  "BS": "Bahamas",
  "BT": "Bután",
  "BV": "Illa Bouvet",
  "BW": "Botswana",
  "BY": "Belarús",
  "BZ": "Belize",
  "Bali": "Balinés",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "bengalí",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "bopomofo",
  "Brah": "Brahmi",
  "Brai": "braille",
  "Bugi": "Buginés",
  "Buhd": "Buhid",
  "CA": "O Canadá",
  "CC": "Illas Cocos (Keeling)",
  "CD": "República Democrática do Congo",
  "CF": "República Centroafricana",
  "CG": "República do Congo",
  "CH": "Suíza",
  "CI": "Côte d’Ivoire",
  "CK": "Illas Cook",
  "CL": "Chile",
  "CM": "Camerún",
  "CN": "A China",
  "CO": "Colombia",
  "CP": "Illa Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia e Montenegro",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Illa Christmas",
  "CY": "Chipre",
  "CZ": "Chequia",
  "Cakm": "Chakma",
  "Cans": "Silabario aborixe canadiano unificado",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Corasmian",
  "Cirt": "Cirth",
  "Copt": "Copto",
  "Cprt": "Chipriota",
  "Cyrl": "cirílico",
  "Cyrs": "Cirílico eslavo da igrexa vella",
  "DD": "Alemaña Oriental",
  "DE": "Alemaña",
  "DG": "Diego García",
  "DJ": "Djibuti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Alxeria",
  "Deva": "devanágari",
  "Diak": "Dives Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Abreviación de Duployan",
  "EA": "Ceuta e Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Exipto",
  "EH": "O Sáhara Occidental",
  "ER": "Eritrea",
  "ES": "España",
  "ET": "Etiopía",
  "EU": "Unión Europea",
  "EZ": "Eurozona",
  "Egyd": "Demótico exipcio",
  "Egyh": "Hierático exipcio",
  "Egyp": "Xeroglifos exipcios",
  "Elba": "Elbasan",
  "Elym": "Elímaico",
  "Ethi": "etíope",
  "FI": "Finlandia",
  "FJ": "Fixi",
  "FK": "Illas Malvinas",
  "FM": "Micronesia",
  "FO": "Illas Feroe",
  "FR": "Francia",
  "FX": "Francia metropolitana",
  "GA": "Gabón",
  "GB": "O Reino Unido",
  "GD": "Granada",
  "GE": "Xeorxia",
  "GF": "Güiana Francesa",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Xibraltar",
  "GL": "Groenlandia",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadalupe",
  "GQ": "Guinea Ecuatorial",
  "GR": "Grecia",
  "GS": "Illas Xeorxia do Sur e Sandwich do Sur",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "A Guinea Bissau",
  "GY": "Güiana",
  "Geok": "Khutsuri xeorxiano",
  "Geor": "xeorxiano",
  "Glag": "Glagolítico",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gótico",
  "Gran": "Grantha",
  "Grek": "grego",
  "Gujr": "guxarati",
  "Guru": "gurmukhi",
  "HK": "Hong Kong RAE da China",
  "HM": "Illa Heard e Illas McDonald",
  "HN": "Honduras",
  "HR": "Croacia",
  "HT": "Haití",
  "HU": "Hungría",
  "Hanb": "han con bopomofo",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "Hanunoo",
  "Hans": "simplificado",
  "Hant": "tradicional",
  "Hatr": "Hatran",
  "Hebr": "hebreo",
  "Hira": "hiragana",
  "Hluw": "Xeroglifos anatolianos",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "silabarios xaponeses",
  "Hung": "Húngaro antigo",
  "IC": "Illas Canarias",
  "ID": "Indonesia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Illa de Man",
  "IN": "A India",
  "IO": "Territorio Británico do Océano Índico",
  "IQ": "Iraq",
  "IR": "Irán",
  "IS": "Islandia",
  "IT": "Italia",
  "Inds": "Indo",
  "Ital": "Cursiva antiga",
  "JE": "Jersey",
  "JM": "Xamaica",
  "JO": "Xordania",
  "JP": "O Xapón",
  "Jamo": "jamo",
  "Java": "Xavanés",
  "Jpan": "xaponés",
  "Jurc": "Jurchen",
  "KE": "Kenya",
  "KG": "Kirguizistán",
  "KH": "Camboxa",
  "KI": "Kiribati",
  "KM": "Comores",
  "KN": "Saint Kitts e Nevis",
  "KP": "Corea do Norte",
  "KR": "Corea do Sur",
  "KW": "Kuwait",
  "KY": "Illas Caimán",
  "KZ": "Kazakistán",
  "Kali": "Kayah Li",
  "Kana": "katakana",
  "Khar": "Kharoshthi",
  "Khmr": "khmer",
  "Khoj": "Khojki",
  "Kits": "Pequeno guión Khitan",
  "Knda": "kannará",
  "Kore": "coreano",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "O Líbano",
  "LC": "Santa Lucía",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lituania",
  "LU": "Luxemburgo",
  "LV": "Letonia",
  "LY": "Libia",
  "Lana": "Lanna",
  "Laoo": "laosiano",
  "Latf": "Latín Fraktur",
  "Latg": "Latín gaélico",
  "Latn": "latino",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Lineal A",
  "Linb": "Lineal B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lidio",
  "MA": "Marrocos",
  "MC": "Mónaco",
  "MD": "Moldavia",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Illas Marshall",
  "MI": "Illas Midway",
  "MK": "Macedonia do Norte",
  "ML": "Malí",
  "MM": "Myanmar (Birmania)",
  "MN": "Mongolia",
  "MO": "Macau RAE da China",
  "MP": "Illas Marianas do Norte",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauricio",
  "MV": "Maldivas",
  "MW": "Malawi",
  "MX": "México",
  "MY": "Malaisia",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandeano",
  "Mani": "Maniqueo",
  "Marc": "Marchen",
  "Maya": "Xeroglifos maias",
  "Medf": "Medefaidrina",
  "Mend": "Mende",
  "Merc": "Cursivo meroítico",
  "Mero": "Meroítico",
  "Mlym": "malabar",
  "Modi": "Modi",
  "Mong": "mongol",
  "Moon": "Lúa",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "birmano",
  "NA": "Namibia",
  "NC": "Nova Caledonia",
  "NE": "Níxer",
  "NF": "Illa Norfolk",
  "NG": "Nixeria",
  "NI": "Nicaragua",
  "NL": "Países Baixos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Zona Neutral",
  "NU": "Niue",
  "NZ": "Nova Zelandia",
  "Nand": "Nandinagari",
  "Narb": "Antigo árabe do norte",
  "Nbat": "Nabateo",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Omán",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "odiá",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Panamá",
  "PC": "Territorio de confianza das illas do Pacífico",
  "PE": "O Perú",
  "PF": "A Polinesia Francesa",
  "PG": "Papúa-Nova Guinea",
  "PH": "Filipinas",
  "PK": "Paquistán",
  "PL": "Polonia",
  "PM": "Saint Pierre et Miquelon",
  "PN": "Illas Pitcairn",
  "PR": "Porto Rico",
  "PS": "Territorios Palestinos",
  "PT": "Portugal",
  "PU": "Varios Estados Unidos Illas do Pacífico",
  "PW": "Palau",
  "PY": "O Paraguai",
  "PZ": "Zona da Canle de Panamá",
  "Palm": "Palmireno",
  "Pauc": "Pau Cin Hau",
  "Perm": "Vello Permic",
  "Phag": "Phags-pa",
  "Phli": "Pahlavi inscricional",
  "Phlp": "Salterio Pahlavi",
  "Phlv": "Libro Pahlavi",
  "Phnx": "Fenicio",
  "Plrd": "Fonética de Pollard",
  "Prti": "Parto inscricional",
  "QA": "Qatar",
  "QO": "Territorios afastados de Oceanía",
  "Qaag": "Zawgyi",
  "RE": "Reunión",
  "RO": "Romanía",
  "RS": "Serbia",
  "RU": "Rusia",
  "RW": "Ruanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Rúnico",
  "SA": "Arabia Saudita",
  "SB": "Illas Salomón",
  "SC": "Seychelles",
  "SD": "O Sudán",
  "SE": "Suecia",
  "SG": "Singapur",
  "SH": "Santa Helena",
  "SI": "Eslovenia",
  "SJ": "Svalbard e Jan Mayen",
  "SK": "Eslovaquia",
  "SL": "Serra Leoa",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "O Sudán do Sur",
  "ST": "San Tomé e Príncipe",
  "SU": "Unión de Repúblicas Socialistas Soviéticas",
  "SV": "O Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Eswatini",
  "Samr": "Samaritano",
  "Sara": "Sarati",
  "Sarb": "Vello árabe do sur",
  "Saur": "Saurashtra",
  "Sgnw": "Escritura de signos",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "cingalés",
  "Sogd": "Sogdian",
  "Sogo": "Vello Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundanés",
  "Sylo": "Syloti Nagri",
  "Syrc": "Siríaco",
  "Syre": "Siriaco estrangelo",
  "Syrj": "Siríaco occidental",
  "Syrn": "Siríaco oriental",
  "TA": "Tristán da Cunha",
  "TC": "Illas Turks e Caicos",
  "TD": "Chad",
  "TF": "Territorios Austrais Franceses",
  "TG": "Togo",
  "TH": "Tailandia",
  "TJ": "Taxiquistán",
  "TK": "Tokelau",
  "TL": "Timor Leste",
  "TM": "Turkmenistán",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turquía",
  "TT": "Trinidad e Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwán",
  "TZ": "Tanzania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Novo Tai Lue",
  "Taml": "támil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalo",
  "Thaa": "thaana",
  "Thai": "tailandés",
  "Tibt": "tibetano",
  "Tirh": "Tirhuta",
  "UA": "Ucraína",
  "UG": "Uganda",
  "UM": "Illas Menores Distantes dos Estados Unidos",
  "UN": "Nacións Unidas",
  "US": "Os Estados Unidos",
  "UY": "O Uruguai",
  "UZ": "Uzbekistán",
  "Ugar": "Ugarítico",
  "VA": "Cidade do Vaticano",
  "VC": "San Vicente e As Granadinas",
  "VD": "Vietnam do Norte",
  "VE": "Venezuela",
  "VG": "Illas Virxes Británicas",
  "VI": "Illas Virxes Estadounidenses",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Fala visible",
  "WF": "Wallis e Futuna",
  "WK": "Illa Wake",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudoacentos",
  "XB": "Pseudobidireccional",
  "XK": "Kosovo",
  "Xpeo": "Persa antigo",
  "Xsux": "Cuneiforme sumero-acadio",
  "YD": "República Democrática Popular do Iemen",
  "YE": "O Iemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Si",
  "ZA": "Suráfrica",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Rexión descoñecida",
  "Zanb": "Praza Zanabazar",
  "Zinh": "Herdado",
  "Zmth": "notación matemática",
  "Zsye": "emojis",
  "Zsym": "símbolos",
  "Zxxx": "non escrito",
  "Zyyy": "común",
  "Zzzz": "sistema de escritura descoñecido",
  "aa": "afar",
  "ab": "abkhazo",
  "ace": "achinés",
  "ach": "acholí",
  "ada": "adangme",
  "ady": "adigueo",
  "ae": "Avestán",
  "aeb": "Árabe tunisiano",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibia)",
  "af_ZA": "afrikaans (Sudáfrica)",
  "afa": "lingua afro-asiática",
  "afh": "Afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akán (Gana)",
  "akk": "Acadio",
  "akz": "Alabama",
  "ale": "aleutiano",
  "alg": "lingua algonquina",
  "aln": "Gheg Albanés",
  "alt": "altai meridional",
  "am": "amhárico",
  "am_ET": "amárico (Etiopía)",
  "an": "aragonés",
  "ang": "Inglés antigo",
  "anp": "angika",
  "apa": "lingua apache",
  "ar": "árabe",
  "ar_001": "árabe estándar moderno",
  "ar_AE": "árabe (Emiratos Árabes Unidos)",
  "ar_BH": "árabe (Bahrein)",
  "ar_DJ": "árabe (Xibuti)",
  "ar_DZ": "árabe (Arxelia)",
  "ar_EG": "árabe (Exipto)",
  "ar_EH": "árabe (Sahara Occidental)",
  "ar_ER": "árabe (Eritrea)",
  "ar_IL": "árabe (Israel)",
  "ar_IQ": "árabe (Iraq)",
  "ar_JO": "árabe (Xordania)",
  "ar_KM": "árabe (Comores)",
  "ar_KW": "árabe (Kuwait)",
  "ar_LB": "árabe (Líbano)",
  "ar_LY": "árabe (Libia)",
  "ar_MA": "árabe (Marrocos)",
  "ar_MR": "árabe (Mauritania)",
  "ar_OM": "árabe (Omán)",
  "ar_PS": "árabe (Territorios palestinos)",
  "ar_QA": "árabe (Qatar)",
  "ar_SA": "árabe (Arabia Saudita)",
  "ar_SD": "árabe (Sudán)",
  "ar_SO": "árabe (Somalia)",
  "ar_SS": "árabe (Sudán do sur)",
  "ar_SY": "árabe (Siria)",
  "ar_TD": "árabe (Chad)",
  "ar_TN": "árabe (Tunisia)",
  "ar_YE": "árabe (Iemen)",
  "arc": "arameo",
  "arn": "mapuche",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Árabe alxerino",
  "ars": "Árabe Najdi",
  "art": "lingua artificial",
  "arw": "Arawak",
  "ary": "Árabe marroquí",
  "arz": "Árabe exipcio",
  "as": "assamés",
  "as_IN": "assamés (India)",
  "asa": "asu",
  "ase": "Lingua de signos americana",
  "ast": "asturiano",
  "ath": "Lingua atapascana",
  "aus": "lingua australiana",
  "av": "avar",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aimará",
  "az": "acerbaixano",
  "az_AZ": "acerbaixano (Acerbaixán)",
  "az_Arab": "acerbaixano (árabe)",
  "az_Cyrl": "acerbaixano (Cirílico)",
  "az_Cyrl_AZ": "acerbaixano (Cirílico, Acerbaixán)",
  "az_Latn": "acerbaixano (Latino)",
  "az_Latn_AZ": "acerbaixano (Latino, Acerbaixán)",
  "azb": "South Azerbaijani",
  "ba": "baxkir",
  "bad": "Banda",
  "bai": "Lingua Bamileke",
  "bal": "Baluchi",
  "ban": "balinés",
  "bar": "Bávaro",
  "bas": "basaa",
  "bat": "lingua báltica",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "belaruso",
  "be_BY": "bielorruso (Bielorrusia)",
  "bej": "Beja",
  "bem": "bemba",
  "ber": "Bereber",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "búlgaro",
  "bg_BG": "búlgaro (Bulgaria)",
  "bgn": "baluchi occidental",
  "bh": "bihariano",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "Bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "siksiká",
  "bm": "bambara",
  "bm_Latn": "bambara (Latino)",
  "bm_Latn_ML": "bambara (Latino, Mali)",
  "bn": "bengalí",
  "bn_BD": "bengalí (Bangladesh)",
  "bn_IN": "bengalí (India)",
  "bnt": "Bantú",
  "bo": "tibetano",
  "bo_CN": "tibetano (China)",
  "bo_IN": "tibetano (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretón",
  "br_FR": "bretón (Francia)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "bodo",
  "bs": "bosníaco",
  "bs_BA": "bosnio (Bosnia e Hercegovina)",
  "bs_Cyrl": "bosnio (Cirílico)",
  "bs_Cyrl_BA": "bosnio (Cirílico, Bosnia e Hercegovina)",
  "bs_Latn": "bosnio (Latino)",
  "bs_Latn_BA": "bosnio (Latino, Bosnia e Hercegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "buginés",
  "bum": "Bulu",
  "byn": "blin",
  "byv": "Medumba",
  "ca": "catalán",
  "ca_AD": "catalán (Andorra)",
  "ca_ES": "catalán (España)",
  "ca_FR": "catalán (Francia)",
  "ca_IT": "catalán (Italia)",
  "cad": "Caddo",
  "cai": "lingua india centroamericana",
  "car": "Carib",
  "cau": "lingua caucásica",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "chakma",
  "ce": "checheno",
  "ceb": "cebuano",
  "cel": "lingua céltica",
  "cgg": "kiga",
  "ch": "chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "chuuk",
  "chm": "mari",
  "chn": "Chinook Jargon",
  "cho": "choctaw",
  "chp": "Chipewyan",
  "chr": "cherokee",
  "chy": "cheyenne",
  "cic": "Chickasaw",
  "ckb": "kurdo central",
  "cmc": "Linguaxe Chamic",
  "co": "corso",
  "cop": "Coptic",
  "cpe": "Criollo ou Pidgin baseado en inglés",
  "cpf": "Criollo ou Pidgin de base francesa",
  "cpp": "Criollo ou Pidgin de base portuguesa",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "crp": "Crioulo ou pidgin",
  "crs": "seselwa (crioulo das Seychelles)",
  "cs": "checo",
  "cs_CZ": "checo (República Checa)",
  "csb": "Kashubian",
  "cu": "eslavo eclesiástico",
  "cus": "Linguaxe Cushitic",
  "cv": "chuvaxo",
  "cy": "galés",
  "cy_GB": "galés (Reino Unido)",
  "da": "dinamarqués",
  "da_DK": "dinamarqués (Dinamarca)",
  "da_GL": "dinamarqués (Grenlandia)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "day": "Dayak",
  "de": "alemán",
  "de_AT": "alemán (Austria)",
  "de_BE": "alemán (Bélxica)",
  "de_CH": "alemán (Suíza)",
  "de_DE": "alemán (Alemaña)",
  "de_LI": "alemán (Liechtenstein)",
  "de_LU": "alemán (Luxemburgo)",
  "del": "Delaware",
  "den": "Escravo",
  "dgr": "dogrib",
  "din": "Dinka",
  "dje": "zarma",
  "doi": "Dogri",
  "dra": "Lingua Dravidiana",
  "dsb": "baixo sorbio",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "Holandés medio",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "Dyula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bután)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "ewe",
  "ee_GH": "ewé (Gana)",
  "ee_TG": "ewé (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "exipcio antigo",
  "eka": "ekajuk",
  "el": "grego",
  "el_CY": "grego (Chipre)",
  "el_GR": "grego (Grecia)",
  "elx": "Elamite",
  "en": "inglés",
  "en_AG": "inglés (Antiga e Barbuda)",
  "en_AI": "inglés (Anguila)",
  "en_AS": "inglés (Samoa Americana)",
  "en_AU": "inglés (Australia)",
  "en_BB": "inglés (Barbados)",
  "en_BE": "inglés (Bélxica)",
  "en_BM": "inglés (Bermudas)",
  "en_BS": "inglés (Bahamas)",
  "en_BW": "inglés (Botsuana)",
  "en_BZ": "inglés (Belice)",
  "en_CA": "inglés (Canadá)",
  "en_CC": "inglés (Illas Cocos (Keeling))",
  "en_CK": "inglés (Illas Cook)",
  "en_CM": "inglés (Camerún)",
  "en_CX": "inglés (Illa Christmas)",
  "en_DG": "inglés (Diego García)",
  "en_DM": "inglés (Dominica)",
  "en_Dsrt": "Inglés (Deseret)",
  "en_ER": "inglés (Eritrea)",
  "en_FJ": "inglés (Fixi)",
  "en_FK": "inglés (Illas Malvinas)",
  "en_FM": "inglés (Micronesia)",
  "en_GB": "inglés (Reino Unido)",
  "en_GD": "inglés (Granada)",
  "en_GG": "inglés (Guernsey)",
  "en_GH": "inglés (Gana)",
  "en_GI": "inglés (Xibraltar)",
  "en_GM": "inglés (Gambia)",
  "en_GU": "inglés (Guam)",
  "en_GY": "inglés (Güiana)",
  "en_HK": "inglés (Hong Kong RAE de China)",
  "en_IE": "inglés (Irlanda)",
  "en_IM": "inglés (Illa de Man)",
  "en_IN": "inglés (India)",
  "en_IO": "inglés (Territorio Británico do Océano Índico)",
  "en_JE": "inglés (Jersey)",
  "en_JM": "inglés (Xamaica)",
  "en_KE": "inglés (Quenia)",
  "en_KI": "inglés (Kiribati)",
  "en_KN": "inglés (San Cristovo e Nevis)",
  "en_KY": "inglés (Illas Caimán)",
  "en_LC": "inglés (Santa Lucía)",
  "en_LR": "inglés (Liberia)",
  "en_LS": "inglés (Lesotho)",
  "en_MG": "inglés (Madagascar)",
  "en_MH": "inglés (Illas Marshall)",
  "en_MO": "inglés (Macau RAE de China)",
  "en_MP": "inglés (Illas Marianas do norte)",
  "en_MS": "inglés (Montserrat)",
  "en_MT": "inglés (Malta)",
  "en_MU": "inglés (Mauricio)",
  "en_MW": "inglés (Malaui)",
  "en_MY": "inglés (Malaisia)",
  "en_NA": "inglés (Namibia)",
  "en_NF": "inglés (Illa Norfolk)",
  "en_NG": "inglés (Nixeria)",
  "en_NR": "inglés (Nauru)",
  "en_NU": "inglés (Niue)",
  "en_NZ": "inglés (Nova Celandia)",
  "en_PG": "inglés (Papúa Nova Guinea)",
  "en_PH": "inglés (Filipinas)",
  "en_PK": "inglés (Paquistán)",
  "en_PN": "inglés (Illas Pitcairn)",
  "en_PR": "inglés (Porto Rico)",
  "en_PW": "inglés (Palau)",
  "en_RW": "inglés (Ruanda)",
  "en_SB": "inglés (Illas Salomón)",
  "en_SC": "inglés (Seixeles)",
  "en_SD": "inglés (Sudán)",
  "en_SG": "inglés (Singapur)",
  "en_SH": "inglés (Santa Helena)",
  "en_SL": "inglés (Serra Leoa)",
  "en_SS": "inglés (Sudán do sur)",
  "en_SX": "inglés (Sint Maarten)",
  "en_SZ": "inglés (Suacilandia)",
  "en_TC": "inglés (Illas Turks e Caicos)",
  "en_TK": "inglés (Tokelau)",
  "en_TO": "inglés (Tonga)",
  "en_TT": "inglés (Trindade e Tobago)",
  "en_TV": "inglés (Tuvalu)",
  "en_TZ": "inglés (Tanzania)",
  "en_UG": "inglés (Uganda)",
  "en_UM": "inglés (Illas Menores Distantes dos EUA.)",
  "en_US": "inglés (Estados Unidos de América)",
  "en_VC": "inglés (San Vicente e Granadinas)",
  "en_VG": "inglés (Illas Virxes Británicas)",
  "en_VI": "inglés (Illas Virxes Estadounidenses)",
  "en_VU": "inglés (Vanuatu)",
  "en_WS": "inglés (Samoa)",
  "en_ZA": "inglés (Sudáfrica)",
  "en_ZM": "inglés (Zambia)",
  "en_ZW": "inglés (Cimbabue)",
  "enm": "Inglés medio",
  "eo": "esperanto",
  "es": "español",
  "es_419": "español de América",
  "es_AR": "español (Arxentina)",
  "es_BO": "español (Bolivia)",
  "es_CL": "español (Chile)",
  "es_CO": "español (Colombia)",
  "es_CR": "español (Costa Rica)",
  "es_CU": "español (Cuba)",
  "es_DO": "español (República Dominicana)",
  "es_EA": "español (Ceuta e Melilla)",
  "es_EC": "español (Ecuador)",
  "es_ES": "español (España)",
  "es_GQ": "español (Guinea Ecuatorial)",
  "es_GT": "español (Guatemala)",
  "es_HN": "español (Honduras)",
  "es_IC": "español (Illas Canarias)",
  "es_MX": "español (México)",
  "es_NI": "español (Nicaragua)",
  "es_PA": "español (Panamá)",
  "es_PE": "español (Perú)",
  "es_PH": "español (Filipinas)",
  "es_PR": "español (Porto Rico)",
  "es_PY": "español (Paraguai)",
  "es_SV": "español (El Salvador)",
  "es_US": "español (Estados Unidos de América)",
  "es_UY": "español (Uruguai)",
  "es_VE": "español (Venezuela)",
  "esu": "Central Yupik",
  "et": "estoniano",
  "et_EE": "estoniano (Estonia)",
  "eu": "éuscaro",
  "eu_ES": "éuscaro (España)",
  "ewo": "ewondo",
  "ext": "Estremeño",
  "fa": "persa",
  "fa_AF": "persa (Afganistán)",
  "fa_IR": "persa (Irán)",
  "fan": "Colmillo",
  "fat": "Fanti",
  "ff": "fula",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "finés",
  "fi_FI": "finés (Finlandia)",
  "fil": "filipino",
  "fit": "Tornedalen finés",
  "fiu": "lingua finno-úgrica",
  "fj": "fixiano",
  "fo": "feroés",
  "fo_FO": "faroés (Illas Feroe)",
  "fon": "fon",
  "fr": "francés",
  "fr_BE": "francés (Bélxica)",
  "fr_BF": "francés (Burkina Faso)",
  "fr_BI": "francés (Burundi)",
  "fr_BJ": "francés (Benin)",
  "fr_BL": "francés (San Bartolomé)",
  "fr_CA": "francés (Canadá)",
  "fr_CD": "francés (República Democrática do Congo)",
  "fr_CF": "francés (República Africana Central)",
  "fr_CG": "francés (Congo)",
  "fr_CH": "francés (Suíza)",
  "fr_CI": "francés (Costa de Marfil)",
  "fr_CM": "francés (Camerún)",
  "fr_DJ": "francés (Xibuti)",
  "fr_DZ": "francés (Arxelia)",
  "fr_FR": "francés (Francia)",
  "fr_GA": "francés (Gabón)",
  "fr_GF": "francés (Güiana Francesa)",
  "fr_GN": "francés (Guinea)",
  "fr_GP": "francés (Guadalupe)",
  "fr_GQ": "francés (Guinea Ecuatorial)",
  "fr_HT": "francés (Haití)",
  "fr_KM": "francés (Comores)",
  "fr_LU": "francés (Luxemburgo)",
  "fr_MA": "francés (Marrocos)",
  "fr_MC": "francés (Mónaco)",
  "fr_MF": "francés (San Martiño)",
  "fr_MG": "francés (Madagascar)",
  "fr_ML": "francés (Mali)",
  "fr_MQ": "francés (Martinica)",
  "fr_MR": "francés (Mauritania)",
  "fr_MU": "francés (Mauricio)",
  "fr_NC": "francés (Nova Caledonia)",
  "fr_NE": "francés (Níxer)",
  "fr_PF": "francés (Polinesia Francesa)",
  "fr_PM": "francés (San Pedro e Miguelón)",
  "fr_RE": "francés (Reunión)",
  "fr_RW": "francés (Ruanda)",
  "fr_SC": "francés (Seixeles)",
  "fr_SN": "francés (Senegal)",
  "fr_SY": "francés (Siria)",
  "fr_TD": "francés (Chad)",
  "fr_TG": "francés (Togo)",
  "fr_TN": "francés (Tunisia)",
  "fr_VU": "francés (Vanuatu)",
  "fr_WF": "francés (Wallis e Futuna)",
  "fr_YT": "francés (Mayotte)",
  "frc": "Francés cajún",
  "frm": "Francés medio",
  "fro": "Francés antigo",
  "frp": "Arpitan",
  "frr": "Frisón do norte",
  "frs": "Frisón oriental",
  "fur": "friulano",
  "fy": "frisón occidental",
  "fy_NL": "frisón (Países Baixos)",
  "ga": "irlandés",
  "ga_IE": "irlandés (Irlanda)",
  "gaa": "ga",
  "gag": "gagauz",
  "gan": "Chinés gan",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Dari zoroastriano",
  "gd": "gaélico escocés",
  "gd_GB": "gaélico escocés (Reino Unido)",
  "gem": "lingua xermánica",
  "gez": "ge’ez",
  "gil": "kiribatiano",
  "gl": "galego",
  "gl_ES": "galego (España)",
  "glk": "Gilaki",
  "gmh": "Alto alemán medio",
  "gn": "guaraní",
  "goh": "Alto alemán antigo",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "gorontalo",
  "got": "Gótico",
  "grb": "Grebo",
  "grc": "grego antigo",
  "gsw": "alemán suízo",
  "gu": "guxarati",
  "gu_IN": "guxaratiano (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusii",
  "gv": "manx",
  "gv_IM": "manx (Illa de Man)",
  "gwi": "gwichʼin",
  "ha": "hausa",
  "ha_GH": "hausa (Gana)",
  "ha_Latn": "hausa (Latino)",
  "ha_Latn_GH": "hausa (Latino, Gana)",
  "ha_Latn_NE": "hausa (Latino, Níxer)",
  "ha_Latn_NG": "hausa (Latino, Nixeria)",
  "ha_NE": "hausa (Níxer)",
  "ha_NG": "hausa (Nixeria)",
  "hai": "Haida",
  "hak": "Hakka chinés",
  "haw": "hawaiano",
  "he": "hebreo",
  "he_IL": "hebreo (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "him": "Himachali",
  "hit": "Hittite",
  "hmn": "hmong",
  "ho": "Hiri Motu",
  "hr": "croata",
  "hr_BA": "croata (Bosnia e Hercegovina)",
  "hr_HR": "croata (Croacia)",
  "hsb": "alto sorbio",
  "hsn": "Chinés Xiang",
  "ht": "crioulo haitiano",
  "hu": "húngaro",
  "hu_HU": "húngaro (Hungría)",
  "hup": "hupa",
  "hy": "armenio",
  "hy_AM": "armenio (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonesio",
  "id_ID": "indonesio (Indonesia)",
  "ie": "Interlingue",
  "ig": "igbo",
  "ig_NG": "ibo (Nixeria)",
  "ii": "yi sichuanés",
  "ii_CN": "yi sichuanés (China)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "ilocano",
  "inc": "lingua índica",
  "ine": "lingua indoeuropea",
  "inh": "inguxo",
  "io": "ido",
  "ira": "Lingua iraniana",
  "iro": "Lingua Iroquoiana",
  "is": "islandés",
  "is_IS": "islandés (Islandia)",
  "it": "italiano",
  "it_CH": "italiano (Suíza)",
  "it_IT": "italiano (Italia)",
  "it_SM": "italiano (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "xaponés",
  "ja_JP": "xaponés (Xapón)",
  "jam": "Inglés crioulo xamaicano",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "xavanés",
  "ka": "xeorxiano",
  "ka_GE": "xeorxiano (Xeorxia)",
  "kaa": "Kara-Kalpak",
  "kab": "cabila",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "cabardiano",
  "kbl": "Kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "caboverdiano",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "Kaingang",
  "kha": "khasi",
  "khi": "Lingua Khoisan",
  "kho": "Khotanese",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Quenia)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "kazako",
  "kk_Cyrl": "casaco (Cirílico)",
  "kk_Cyrl_KZ": "casaco (Cirílico, Kazakhstan)",
  "kk_KZ": "casaco (Kazakhstan)",
  "kkj": "kako",
  "kl": "groenlandés",
  "kl_GL": "groenlandés (Grenlandia)",
  "kln": "kalenjin",
  "km": "khmer",
  "km_KH": "cambodiano (Cambodia)",
  "kmb": "kimbundu",
  "kn": "kannará",
  "kn_IN": "kannada (India)",
  "ko": "coreano",
  "ko_KP": "coreano (Corea do Norte)",
  "ko_KR": "coreano (Corea do Sur)",
  "koi": "komi permio",
  "kok": "konkani",
  "kos": "Kosraean",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "carachaio-bálcara",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "carelio",
  "kro": "Kru",
  "kru": "kurukh",
  "ks": "caxemirés",
  "ks_Arab": "cachemir (Árabe)",
  "ks_Arab_IN": "cachemir (Árabe, India)",
  "ks_IN": "cachemir (India)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kölsch",
  "ku": "kurdo",
  "kum": "kumyk",
  "kut": "Kutenai",
  "kv": "komi",
  "kw": "córnico",
  "kw_GB": "córnico (Reino Unido)",
  "ky": "kirguiz",
  "ky_Cyrl": "quirguiz (Cirílico)",
  "ky_Cyrl_KG": "quirguiz (Cirílico, Quirguicistán)",
  "ky_KG": "quirguiz (Quirguicistán)",
  "la": "latín",
  "lad": "ladino",
  "lag": "langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "luxemburgués",
  "lb_LU": "luxemburgués (Luxemburgo)",
  "lez": "lezguio",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgués",
  "lij": "Ligur",
  "liv": "Livoniano",
  "lkt": "lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (República Democrática do Congo)",
  "ln_CF": "lingala (República Africana Central)",
  "ln_CG": "lingala (Congo)",
  "lo": "laosiano",
  "lo_LA": "laotiano (Laos)",
  "lol": "Mongo",
  "lou": "Crioulo de Louisiana",
  "loz": "lozi",
  "lrc": "luri setentrional",
  "lt": "lituano",
  "lt_LT": "lituano (Lituania)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (República Democrática do Congo)",
  "lua": "luba-lulua",
  "lui": "Luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "mizo",
  "luy": "luyia",
  "lv": "letón",
  "lv_LV": "letón (Letonia)",
  "lzh": "Chinés literario",
  "lzz": "Laz",
  "mad": "madurés",
  "maf": "Mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "Mandingo",
  "map": "Lingua austronesia",
  "mas": "masai",
  "mde": "Maba",
  "mdf": "moksha",
  "mdr": "Mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "crioulo mauriciano",
  "mg": "malgaxe",
  "mg_MG": "malgaxe (Madagascar)",
  "mga": "Irlandés medio",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshalés",
  "mi": "maorí",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "lingua miscelánea",
  "mk": "macedonio",
  "mk_MK": "macedonio (Macedonia)",
  "mkh": "Lingua Mon-Khmer",
  "ml": "malabar",
  "ml_IN": "malabar (India)",
  "mn": "mongol",
  "mn_Cyrl": "mongol (Cirílico)",
  "mn_Cyrl_MN": "mongol (Cirílico, Mongolia)",
  "mn_MN": "mongol (Mongolia)",
  "mnc": "Manchu",
  "mni": "manipuri",
  "mno": "Lingua Manobo",
  "mo": "Moldavo",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "Mari occidental",
  "ms": "malaio",
  "ms_BN": "malaio (Brunei)",
  "ms_Latn": "malaio (Latino)",
  "ms_Latn_BN": "malaio (Latino, Brunei)",
  "ms_Latn_MY": "malaio (Latino, Malaisia)",
  "ms_Latn_SG": "malaio (Latino, Singapur)",
  "ms_MY": "malaio (Malaisia)",
  "ms_SG": "malaio (Singapur)",
  "mt": "maltés",
  "mt_MT": "maltés (Malta)",
  "mua": "mundang",
  "mul": "varias linguas",
  "mun": "Lingua Munda",
  "mus": "creek",
  "mwl": "mirandés",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "birmano",
  "my_MM": "birmano (Myanmar (Birmania))",
  "mye": "Myene",
  "myn": "Lingua Maya",
  "myv": "erzya",
  "mzn": "mazandaraní",
  "na": "nauruano",
  "nah": "Náhuatl",
  "nai": "lingua india norteamericana",
  "nan": "Min Nan Chinese",
  "nap": "napolitano",
  "naq": "nama",
  "nb": "noruegués bokmål",
  "nb_NO": "noruegués bokmal (Noruega)",
  "nb_SJ": "noruegués bokmal (Svalbard e Jan Mayen)",
  "nd": "ndebele setentrional",
  "nd_ZW": "ndebele do norte (Cimbabue)",
  "nds": "baixo alemán",
  "nds_NL": "baixo saxón",
  "ne": "nepalí",
  "ne_IN": "nepalí (India)",
  "ne_NP": "nepalí (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "Lingua Niger-Kordofaniana",
  "niu": "niueano",
  "njo": "Ao Naga",
  "nl": "neerlandés",
  "nl_AW": "holandés (Aruba)",
  "nl_BE": "holandés (Bélxica)",
  "nl_BQ": "holandés (Caribe neerlandés)",
  "nl_CW": "holandés (Curaçao)",
  "nl_NL": "holandés (Países Baixos)",
  "nl_SR": "holandés (Surinam)",
  "nl_SX": "holandés (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "noruegués nynorsk",
  "nn_NO": "noruegués nynorsk (Noruega)",
  "nnh": "ngiemboon",
  "no": "noruegués",
  "no_NO": "noruegués (Noruega)",
  "nog": "nogai",
  "non": "Nórdico antigo",
  "nov": "Novial",
  "nqo": "n’ko",
  "nr": "ndebele meridional",
  "nso": "sesotho do norte",
  "nub": "lingua nubia",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "Newari clásico",
  "ny": "chewa",
  "nym": "Nyamwezi",
  "nyn": "nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "occitano",
  "oj": "Ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiopía)",
  "om_KE": "oromo (Quenia)",
  "or": "odiá",
  "or_IN": "oriya (India)",
  "os": "ossetio",
  "os_GE": "osetio (Xeorxia)",
  "os_RU": "osetio (Rusia)",
  "osa": "Osage",
  "ota": "Turco otomán",
  "oto": "Lingua Otomiana",
  "pa": "panxabí",
  "pa_Arab": "punjabi (Árabe)",
  "pa_Arab_PK": "punjabi (Árabe, Paquistán)",
  "pa_Guru": "punjabi (Gurmukhi)",
  "pa_Guru_IN": "punjabi (Gurmukhi, India)",
  "pa_IN": "punjabi (India)",
  "pa_PK": "punjabi (Paquistán)",
  "paa": "Lingua Papua",
  "pag": "pangasinan",
  "pal": "Pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palauano",
  "pcd": "Picard",
  "pcm": "pidgin nixeriano",
  "pdc": "Alemán de Pensilvania",
  "pdt": "Plautdietsch",
  "peo": "Persa antigo",
  "pfl": "Alemán palatino",
  "phi": "lingua filipina",
  "phn": "Fenicio",
  "pi": "Pali",
  "pl": "polaco",
  "pl_PL": "Polaco (Polonia)",
  "pms": "Piamontés",
  "pnt": "Póntico",
  "pon": "Pohnpeian",
  "pra": "Lingua prácrita",
  "prg": "prusiano",
  "pro": "Antigo provenzal",
  "ps": "paxto",
  "ps_AF": "paxtún (Afganistán)",
  "pt": "portugués",
  "pt_AO": "portugués (Angola)",
  "pt_BR": "portugués (Brasil)",
  "pt_CV": "portugués (Cabo Verde)",
  "pt_GW": "portugués (Guinea-Bissau)",
  "pt_MO": "portugués (Macau RAE de China)",
  "pt_MZ": "portugués (Mozambique)",
  "pt_PT": "portugués (Portugal)",
  "pt_ST": "portugués (San Tomé e Príncipe)",
  "pt_TL": "portugués (Timor Leste)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivia)",
  "qu_EC": "quechua (Ecuador)",
  "qu_PE": "quechua (Perú)",
  "quc": "quiché",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "rapanui",
  "rar": "rarotongano",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "romanche",
  "rm_CH": "romanche (Suíza)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "romanés",
  "ro_MD": "romanés (Moldova)",
  "ro_RO": "romanés (Romanía)",
  "roa": "lingua románica",
  "rof": "rombo",
  "rom": "Xitanos",
  "root": "raíz",
  "rtm": "Rotuman",
  "ru": "ruso",
  "ru_BY": "ruso (Bielorrusia)",
  "ru_KG": "ruso (Quirguicistán)",
  "ru_KZ": "ruso (Kazakhstan)",
  "ru_MD": "ruso (Moldova)",
  "ru_RU": "ruso (Rusia)",
  "ru_UA": "ruso (Ucraína)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromanés",
  "rw": "kiñaruanda",
  "rw_RW": "ruandés (Ruanda)",
  "rwk": "rwa",
  "sa": "sánscrito",
  "sad": "sandawe",
  "sah": "iacuto",
  "sai": "lingua india sudamericana",
  "sal": "Lingua Salishan",
  "sam": "Aramea samaritano",
  "saq": "samburu",
  "sas": "Sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardo",
  "scn": "siciliano",
  "sco": "escocés",
  "sd": "sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sardo sassarés",
  "sdh": "kurdo meridional",
  "se": "saami setentrional",
  "se_FI": "sami do norte (Finlandia)",
  "se_NO": "sami do norte (Noruega)",
  "se_SE": "sami do norte (Suecia)",
  "see": "Séneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "lingua semita",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (República Africana Central)",
  "sga": "Old Irish",
  "sgn": "lingua de signos",
  "sgs": "Samogitian",
  "sh": "serbocroata",
  "sh_BA": "serbocroata (Bosnia e Hercegovina)",
  "shi": "tachelhit",
  "shi_Latn": "Shilha (latín)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "shan",
  "shu": "Árabe chadiano",
  "si": "cingalés",
  "si_LK": "cingalés (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Lingua Siouan",
  "sit": "Lingua sino-tibetana",
  "sk": "eslovaco",
  "sk_SK": "eslovaco (Eslovaquia)",
  "sl": "esloveno",
  "sl_SI": "esloveno (Eslovenia)",
  "sla": "lingua eslávica",
  "sli": "Baixo Silesia",
  "sly": "Selayar",
  "sm": "samoano",
  "sma": "saami meridional",
  "smi": "Lingua sami",
  "smj": "saami de Lule",
  "smn": "saami de Inari",
  "sms": "saami skolt",
  "sn": "shona",
  "sn_ZW": "shona (Cimbabue)",
  "snk": "soninke",
  "so": "somalí",
  "so_DJ": "somalí (Xibuti)",
  "so_ET": "somalí (Etiopía)",
  "so_KE": "somalí (Quenia)",
  "so_SO": "somalí (Somalia)",
  "sog": "Sogdien",
  "son": "Songhai",
  "sq": "albanés",
  "sq_AL": "albanés (Albania)",
  "sq_MK": "albanés (Macedonia)",
  "sq_XK": "albanés (Kosovo)",
  "sr": "serbio",
  "sr_BA": "serbio (Bosnia e Hercegovina)",
  "sr_Cyrl": "serbio (Cirílico)",
  "sr_Cyrl_BA": "serbio (Cirílico, Bosnia e Hercegovina)",
  "sr_Cyrl_ME": "serbio (Cirílico, Montenegro)",
  "sr_Cyrl_RS": "serbio (Cirílico, Serbia)",
  "sr_Cyrl_XK": "serbio (Cirílico, Kosovo)",
  "sr_Latn": "serbio (Latino)",
  "sr_Latn_BA": "serbio (Latino, Bosnia e Hercegovina)",
  "sr_Latn_ME": "serbio (Latino, Montenegro)",
  "sr_Latn_RS": "serbio (Latino, Serbia)",
  "sr_Latn_XK": "serbio (Latino, Kosovo)",
  "sr_ME": "serbio (Montenegro)",
  "sr_RS": "serbio (Serbia)",
  "sr_XK": "serbio (Kosovo)",
  "srn": "sranan tongo",
  "srr": "Serer",
  "ss": "suazi",
  "ssa": "lingua do nilo-sáhara",
  "ssy": "saho",
  "st": "sesotho",
  "stq": "Frisón saterlandés",
  "su": "sundanés",
  "suk": "sukuma",
  "sus": "Susu",
  "sux": "Sumerio",
  "sv": "sueco",
  "sv_AX": "sueco (Illas Aland)",
  "sv_FI": "sueco (Finlandia)",
  "sv_SE": "sueco (Suecia)",
  "sw": "suahili",
  "sw_CD": "suahili congolés",
  "sw_KE": "swahili (Quenia)",
  "sw_TZ": "swahili (Tanzania)",
  "sw_UG": "swahili (Uganda)",
  "swb": "comoriano",
  "swc": "Suahili do Congo",
  "syc": "Siríaco clásico",
  "syr": "siríaco",
  "szl": "Silesian",
  "ta": "támil",
  "ta_IN": "tamil (India)",
  "ta_LK": "tamil (Sri Lanka)",
  "ta_MY": "tamil (Malaisia)",
  "ta_SG": "tamil (Singapur)",
  "tai": "Lingua Tai",
  "tcy": "Tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "teso",
  "ter": "Tereno",
  "tet": "tetun",
  "tg": "taxico",
  "th": "tailandés",
  "th_TH": "tailandés (Tailandia)",
  "ti": "tigriña",
  "ti_ER": "tigriña (Eritrea)",
  "ti_ET": "tigriña (Etiopía)",
  "tig": "tigré",
  "tiv": "Tiv",
  "tk": "turkmeno",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "tagalo",
  "tl_PH": "tagalo (Filipinas)",
  "tlh": "klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "tswana",
  "to": "tongano",
  "to_TO": "tonganés (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "tok pisin",
  "tr": "turco",
  "tr_CY": "turco (Chipre)",
  "tr_TR": "turco (Turquía)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "tártaro",
  "ttt": "Tatuaxe musulmá",
  "tum": "tumbuka",
  "tup": "Linguaxe Tupi",
  "tut": "lingua altaica",
  "tvl": "tuvalés",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitiano",
  "tyv": "tuvaniano",
  "tzm": "tamazight de Marrocos central",
  "udm": "udmurto",
  "ug": "uigur",
  "ug_Arab": "uigur (Árabe)",
  "ug_Arab_CN": "uigur (Árabe, China)",
  "ug_CN": "uigur (China)",
  "uga": "Ugarítico",
  "uk": "ucraíno",
  "uk_UA": "ucraíno (Ucraína)",
  "umb": "umbundu",
  "und": "lingua descoñecida",
  "ur": "urdú",
  "ur_IN": "urdú (India)",
  "ur_PK": "urdú (Paquistán)",
  "uz": "uzbeko",
  "uz_AF": "uzbeco (Afganistán)",
  "uz_Arab": "uzbeco (Árabe)",
  "uz_Arab_AF": "uzbeco (Árabe, Afganistán)",
  "uz_Cyrl": "uzbeco (Cirílico)",
  "uz_Cyrl_UZ": "uzbeco (Cirílico, Uzbekistán)",
  "uz_Latn": "uzbeco (Latino)",
  "uz_Latn_UZ": "uzbeco (Latino, Uzbekistán)",
  "uz_UZ": "uzbeco (Uzbekistán)",
  "vai": "vai",
  "vai_Latn": "Vai (latín)",
  "ve": "venda",
  "vec": "Veneciano",
  "vep": "Veps",
  "vi": "vietnamita",
  "vi_VN": "vietnamita (Vietnam)",
  "vls": "Flamenco occidental",
  "vmf": "Main-Franconian",
  "vo": "volapuk",
  "vot": "Vótico",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "valón",
  "wae": "walser",
  "wak": "Lingua Wakashan",
  "wal": "wolaytta",
  "war": "waray-waray",
  "was": "Washo",
  "wbp": "walrpiri",
  "wen": "Lingua soraba",
  "wo": "wólof",
  "wuu": "Wu chinés",
  "xal": "calmuco",
  "xh": "xhosa",
  "xmf": "Mingrelian",
  "xog": "soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "yiddish",
  "yo": "ioruba",
  "yo_BJ": "ioruba (Benin)",
  "yo_NG": "ioruba (Nixeria)",
  "ypk": "Linguaxe Yupik",
  "yrl": "Nheengatu",
  "yue": "cantonés",
  "yue_Hans": "Cantonés (chinés simplificado)",
  "yue_Hant": "Cantonés (chinés tradicional)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "tamazight marroquí estándar",
  "zh": "chinés",
  "zh_CN": "chinés (China)",
  "zh_HK": "chinés (Hong Kong RAE de China)",
  "zh_Hans": "chinés (Simplificado)",
  "zh_Hans_CN": "chinés (Simplificado, China)",
  "zh_Hans_HK": "chinés (Simplificado, Hong Kong RAE de China)",
  "zh_Hans_MO": "chinés (Simplificado, Macau RAE de China)",
  "zh_Hans_SG": "chinés (Simplificado, Singapur)",
  "zh_Hant": "chinés (Tradicional)",
  "zh_Hant_HK": "chinés (Tradicional, Hong Kong RAE de China)",
  "zh_Hant_MO": "chinés (Tradicional, Macau RAE de China)",
  "zh_Hant_TW": "chinés (Tradicional, Taiwán)",
  "zh_MO": "chinés (Macau RAE de China)",
  "zh_SG": "chinés (Singapur)",
  "zh_TW": "chinés (Taiwán)",
  "znd": "Zande",
  "zu": "zulú",
  "zu_ZA": "zulú (Sudáfrica)",
  "zun": "zuni",
  "zxx": "sen contido lingüístico",
  "zza": "zazaki"
};
