const names = {
  "001": "Welt",
  "002": "Afrika",
  "003": "Nordamerika",
  "005": "Südamerika",
  "009": "Ozeanien",
  "011": "Westafrika",
  "013": "Mëttelamerika",
  "014": "Ostafrika",
  "015": "Nordafrika",
  "017": "Zentralafrika",
  "018": "Südlecht Afrika",
  "019": "Amerika",
  "021": "Nërdlecht Amerika",
  "029": "Karibik",
  "030": "Ostasien",
  "034": "Südasien",
  "035": "Südostasien",
  "039": "Südeuropa",
  "053": "Australien an Neiséiland",
  "054": "Melanesien",
  "057": "Mikronesescht Inselgebitt",
  "061": "Polynesien",
  "142": "Asien",
  "143": "Zentralasien",
  "145": "Westasien",
  "150": "Europa",
  "151": "Osteuropa",
  "154": "Nordeuropa",
  "155": "Westeuropa",
  "419": "Latäinamerika",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Vereenegt Arabesch Emirater",
  "AF": "Afghanistan",
  "AG": "Antigua a Barbuda",
  "AI": "Anguilla",
  "AL": "Albanien",
  "AM": "Armenien",
  "AO": "Angola",
  "AQ": "Antarktis",
  "AR": "Argentinien",
  "AS": "Amerikanesch-Samoa",
  "AT": "Éisträich",
  "AU": "Australien",
  "AW": "Aruba",
  "AX": "Ålandinselen",
  "AZ": "Aserbaidschan",
  "Arab": "Arabesch",
  "Armn": "Armenesch",
  "Avst": "Avestesch",
  "BA": "Bosnien an Herzegowina",
  "BB": "Barbados",
  "BD": "Bangladesch",
  "BE": "Belsch",
  "BF": "Burkina Faso",
  "BG": "Bulgarien",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivien",
  "BQ": "Karibescht Holland",
  "BR": "Brasilien",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvetinsel",
  "BW": "Botsuana",
  "BY": "Wäissrussland",
  "BZ": "Belize",
  "Bali": "Balinesesch",
  "Batk": "Battakesch",
  "Beng": "Bengalesch",
  "Blis": "Bliss-Symboler",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Blanneschrëft",
  "Bugi": "Buginesesch",
  "Buhd": "Buhid",
  "CA": "Kanada",
  "CC": "Kokosinselen",
  "CD": "Kongo-Kinshasa",
  "CF": "Zentralafrikanesch Republik",
  "CG": "Kongo-Brazzaville",
  "CH": "Schwäiz",
  "CI": "Côte d’Ivoire",
  "CK": "Cookinselen",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "China",
  "CO": "Kolumbien",
  "CP": "Clipperton-Insel",
  "CR": "Costa Rica",
  "CU": "Kuba",
  "CV": "Kap Verde",
  "CW": "Curaçao",
  "CX": "Chrëschtdagsinsel",
  "CY": "Zypern",
  "CZ": "Tschechien",
  "Cans": "UCAS",
  "Cari": "Karesch",
  "Cher": "Cherokee",
  "Cirt": "Cirth",
  "Copt": "Koptesch",
  "Cprt": "Zypriotesch",
  "Cyrl": "Kyrillesch",
  "Cyrs": "Alkiercheslawesch",
  "DE": "Däitschland",
  "DG": "Diego Garcia",
  "DJ": "Dschibuti",
  "DK": "Dänemark",
  "DM": "Dominica",
  "DO": "Dominikanesch Republik",
  "DZ": "Algerien",
  "Deva": "Devanagari",
  "Dsrt": "Deseret",
  "EA": "Ceuta a Melilla",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Egypten",
  "EH": "Westsahara",
  "ER": "Eritrea",
  "ES": "Spanien",
  "ET": "Ethiopien",
  "EU": "Europäesch Unioun",
  "Egyd": "Egyptesch-Demotesch",
  "Egyh": "Egyptesch-Hieratesch",
  "Egyp": "Egyptesch Hieroglyphen",
  "Ethi": "Ethiopesch",
  "FI": "Finnland",
  "FJ": "Fidschi",
  "FK": "Falklandinselen",
  "FM": "Mikronesien",
  "FO": "Färöer",
  "FR": "Frankräich",
  "GA": "Gabun",
  "GB": "Groussbritannien",
  "GD": "Grenada",
  "GE": "Georgien",
  "GF": "Guayane",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grönland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorialguinea",
  "GR": "Griicheland",
  "GS": "Südgeorgien an déi Südlech Sandwichinselen",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "Khutsuri",
  "Geor": "Georgesch",
  "Glag": "Glagolitesch",
  "Goth": "Gotesch",
  "Grek": "Griichesch",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Spezialverwaltungszon Hong Kong",
  "HM": "Heard- a McDonald-Inselen",
  "HN": "Honduras",
  "HR": "Kroatien",
  "HT": "Haiti",
  "HU": "Ungarn",
  "Hang": "Hangul",
  "Hani": "Chinesesch",
  "Hano": "Hanunoo",
  "Hans": "Vereinfacht",
  "Hant": "Traditionell",
  "Hebr": "Hebräesch",
  "Hira": "Hiragana",
  "Hmng": "Pahawh Hmong",
  "Hrkt": "Katakana oder Hiragana",
  "Hung": "Alungaresch",
  "IC": "Kanaresch Inselen",
  "ID": "Indonesien",
  "IE": "Irland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "Indien",
  "IO": "Britescht Territorium am Indeschen Ozean",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italien",
  "Inds": "Indus-Schrëft",
  "Ital": "Alitalesch",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Jordanien",
  "JP": "Japan",
  "Java": "Javanesesch",
  "Jpan": "Japanesch",
  "KE": "Kenia",
  "KG": "Kirgisistan",
  "KH": "Kambodscha",
  "KI": "Kiribati",
  "KM": "Komoren",
  "KN": "St. Kitts an Nevis",
  "KP": "Nordkorea",
  "KR": "Südkorea",
  "KW": "Kuwait",
  "KY": "Kaimaninselen",
  "KZ": "Kasachstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Knda": "Kannada",
  "Kore": "Koreanesch",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litauen",
  "LU": "Lëtzebuerg",
  "LV": "Lettland",
  "LY": "Libyen",
  "Lana": "Lanna",
  "Laoo": "Laotesch",
  "Latf": "Laténgesch-Fraktur-Variant",
  "Latg": "Laténgesch-Gällesch Variant",
  "Latn": "Laténgesch",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Linear A",
  "Linb": "Linear B",
  "Lyci": "Lykesch",
  "Lydi": "Lydesch",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldawien",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagaskar",
  "MH": "Marshallinselen",
  "MK": "Nordmazedonien",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolei",
  "MO": "Spezialverwaltungszon Macau",
  "MP": "Nërdlech Marianen",
  "MQ": "Martinique",
  "MR": "Mauretanien",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldiven",
  "MW": "Malawi",
  "MX": "Mexiko",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "Mand": "Mandäesch",
  "Mani": "Manichäesch",
  "Maya": "Maya-Hieroglyphen",
  "Mero": "Meroitesch",
  "Mlym": "Malaysesch",
  "Mong": "Mongolesch",
  "Moon": "Moon",
  "Mtei": "Meitei Mayek",
  "Mymr": "Birmanesch",
  "NA": "Namibia",
  "NC": "Neikaledonien",
  "NE": "Niger",
  "NF": "Norfolkinsel",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Holland",
  "NO": "Norwegen",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Neiséiland",
  "Nkoo": "N’Ko",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orchon-Runen",
  "Orya": "Oriya",
  "Osma": "Osmanesch",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Franséisch-Polynesien",
  "PG": "Papua-Neiguinea",
  "PH": "Philippinnen",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "St. Pierre a Miquelon",
  "PN": "Pitcairninselen",
  "PR": "Puerto Rico",
  "PS": "Palestinensesch Autonomiegebidder",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "Perm": "Alpermesch",
  "Phag": "Phags-pa",
  "Phlv": "Pahlavi",
  "Phnx": "Phönizesch",
  "Plrd": "Pollard Phonetesch",
  "QA": "Katar",
  "QO": "Baussecht Ozeanien",
  "RE": "Réunion",
  "RO": "Rumänien",
  "RS": "Serbien",
  "RU": "Russland",
  "RW": "Ruanda",
  "Rjng": "Rejang",
  "Roro": "Rongorongo",
  "Runr": "Runeschrëft",
  "SA": "Saudi-Arabien",
  "SB": "Salomonen",
  "SC": "Seychellen",
  "SD": "Sudan",
  "SE": "Schweden",
  "SG": "Singapur",
  "SH": "St. Helena",
  "SI": "Slowenien",
  "SJ": "Svalbard a Jan Mayen",
  "SK": "Slowakei",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Südsudan",
  "ST": "São Tomé a Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syrien",
  "SZ": "Swasiland",
  "Samr": "Samaritanesch",
  "Sara": "Sarati",
  "Saur": "Saurashtra",
  "Sgnw": "Zeechesprooch",
  "Shaw": "Shaw-Alphabet",
  "Sinh": "Singhalesesch",
  "Sund": "Sundanesesch",
  "Sylo": "Syloti Nagri",
  "Syrc": "Syresch",
  "Syre": "Syresch-Estrangelo-Variant",
  "Syrj": "Westsyresch",
  "Syrn": "Ostsyresch",
  "TA": "Tristan da Cunha",
  "TC": "Turks- a Caicosinselen",
  "TD": "Tschad",
  "TF": "Franséisch Süd- an Antarktisgebidder",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadschikistan",
  "TK": "Tokelau",
  "TL": "Osttimor",
  "TM": "Turkmenistan",
  "TN": "Tunesien",
  "TO": "Tonga",
  "TR": "Tierkei",
  "TT": "Trinidad an Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansania",
  "Tale": "Tai Le",
  "Talu": "Tai Lue",
  "Taml": "Tamilesch",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Dagalog",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibetesch",
  "UA": "Ukrain",
  "UG": "Uganda",
  "UM": "Amerikanesch-Ozeanien",
  "US": "Vereenegt Staaten",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "Ugar": "Ugaritesch",
  "VA": "Vatikanstad",
  "VC": "St. Vincent an d’Grenadinnen",
  "VE": "Venezuela",
  "VG": "Britesch Joffereninselen",
  "VI": "Amerikanesch Joffereninselen",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Siichtbar Sprooch",
  "WF": "Wallis a Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "Xpeo": "Alpersesch",
  "Xsux": "Sumeresch-akkadesch Keilschrëft",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yiii": "Yi",
  "ZA": "Südafrika",
  "ZM": "Sambia",
  "ZW": "Simbabwe",
  "ZZ": "Onbekannt Regioun",
  "Zinh": "Geierfte Schrëftwäert",
  "Zsym": "Symboler",
  "Zxxx": "Ouni Schrëft",
  "Zyyy": "Onbestëmmt",
  "Zzzz": "Oncodéiert Schrëft",
  "aa": "Afar",
  "ab": "Abchasesch",
  "ace": "Aceh-Sprooch",
  "ach": "Acholi-Sprooch",
  "ada": "Adangme",
  "ady": "Adygéiesch",
  "ae": "Avestesch",
  "aeb": "Tunesescht Arabesch",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (Südafrika)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu-Sprooch",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadesch",
  "akz": "Alabama",
  "ale": "Aleutesch",
  "aln": "Gegesch",
  "alt": "Süd-Alaesch",
  "am": "Amharesch",
  "am_ET": "Amharesch (Ethiopien)",
  "an": "Aragonesesch",
  "ang": "Alenglesch",
  "anp": "Angika",
  "ar": "Arabesch",
  "ar_001": "Modernt Héicharabesch",
  "ar_AE": "Arabesch (Vereenegt Arabesch Emirater)",
  "ar_BH": "Arabesch (Bahrain)",
  "ar_DJ": "Arabesch (Dschibuti)",
  "ar_DZ": "Arabesch (Algerien)",
  "ar_EG": "Arabesch (Egypten)",
  "ar_EH": "Arabesch (Westsahara)",
  "ar_ER": "Arabesch (Eritrea)",
  "ar_IL": "Arabesch (Israel)",
  "ar_IQ": "Arabesch (Irak)",
  "ar_JO": "Arabesch (Jordanien)",
  "ar_KM": "Arabesch (Komoren)",
  "ar_KW": "Arabesch (Kuwait)",
  "ar_LB": "Arabesch (Libanon)",
  "ar_LY": "Arabesch (Libyen)",
  "ar_MA": "Arabesch (Marokko)",
  "ar_MR": "Arabesch (Mauretanien)",
  "ar_OM": "Arabesch (Oman)",
  "ar_PS": "Arabesch (Palestinensesch Autonomiegebidder)",
  "ar_QA": "Arabesch (Katar)",
  "ar_SA": "Arabesch (Saudi-Arabien)",
  "ar_SD": "Arabesch (Sudan)",
  "ar_SO": "Arabesch (Somalia)",
  "ar_SS": "Arabesch (Südsudan)",
  "ar_SY": "Arabesch (Syrien)",
  "ar_TD": "Arabesch (Tschad)",
  "ar_TN": "Arabesch (Tunesien)",
  "ar_YE": "Arabesch (Jemen)",
  "arc": "Aramäesch",
  "arn": "Araukanesch",
  "aro": "Araona",
  "arp": "Arapaho-Sprooch",
  "arq": "Algerescht Arabesch",
  "arw": "Arawak-Sprooch",
  "ary": "Marokkanescht Arabesch",
  "arz": "Egyptescht Arabesch",
  "as": "Assamesesch",
  "as_IN": "Assamesesch (Indien)",
  "asa": "Asu (Tanzania)",
  "ase": "Amerikanesch Zeechesprooch",
  "ast": "Asturianesch",
  "av": "Awaresch",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Aserbaidschanesch",
  "az_AZ": "Aserbaidschanesch (Aserbaidschan)",
  "az_Cyrl": "Aserbaidschanesch (Kyrillesch)",
  "az_Cyrl_AZ": "Aserbaidschanesch (Kyrillesch, Aserbaidschan)",
  "az_Latn": "Aserbaidschanesch (Laténgesch)",
  "az_Latn_AZ": "Aserbaidschanesch (Laténgesch, Aserbaidschan)",
  "azb": "Süd-Aserbaidschanesch",
  "ba": "Baschkiresch",
  "bal": "Belutschesch",
  "ban": "Balinesesch",
  "bar": "Bairesch",
  "bas": "Basaa-Sprooch",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomálá’",
  "be": "Wäissrussesch",
  "be_BY": "Wäissrussesch (Wäissrussland)",
  "bej": "Bedauye",
  "bem": "Bemba-Sprooch",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaresch",
  "bg_BG": "Bulgaresch (Bulgarien)",
  "bho": "Bhodschpuri",
  "bi": "Bislama",
  "bik": "Bikol-Sprooch",
  "bin": "Bini-Sprooch",
  "bjn": "Banjaresesch",
  "bkm": "Kom",
  "bla": "Blackfoot-Sprooch",
  "bm": "Bambara-Sprooch",
  "bm_Latn": "Bambara-Sprooch (Laténgesch)",
  "bm_Latn_ML": "Bambara-Sprooch (Laténgesch, Mali)",
  "bn": "Bengalesch",
  "bn_BD": "Bengalesch (Bangladesch)",
  "bn_IN": "Bengalesch (Indien)",
  "bo": "Tibetesch",
  "bo_CN": "Tibetesch (China)",
  "bo_IN": "Tibetesch (Indien)",
  "bpy": "Bishnupriya",
  "bqi": "Bachtiaresch",
  "br": "Bretonesch",
  "br_FR": "Bretonesch (Frankräich)",
  "bra": "Braj-Bhakha",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnesch",
  "bs_BA": "Bosnesch (Bosnien an Herzegowina)",
  "bs_Cyrl": "Bosnesch (Kyrillesch)",
  "bs_Cyrl_BA": "Bosnesch (Kyrillesch, Bosnien an Herzegowina)",
  "bs_Latn": "Bosnesch (Laténgesch)",
  "bs_Latn_BA": "Bosnesch (Laténgesch, Bosnien an Herzegowina)",
  "bss": "Akoose",
  "bua": "Burjatesch",
  "bug": "Buginesesch",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalanesch",
  "ca_AD": "Katalanesch (Andorra)",
  "ca_ES": "Katalanesch (Spanien)",
  "ca_FR": "Katalanesch (Frankräich)",
  "ca_IT": "Katalanesch (Italien)",
  "cad": "Caddo",
  "car": "Karibesch",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Tschetschenesch",
  "ceb": "Cebuano",
  "cgg": "Kiga",
  "ch": "Chamorro-Sprooch",
  "chb": "Chibcha-Sprooch",
  "chg": "Tschagataesch",
  "chk": "Trukesesch",
  "chm": "Mari",
  "chn": "Chinook",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Sorani",
  "co": "Korsesch",
  "cop": "Koptesch",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Krimtataresch",
  "cs": "Tschechesch",
  "cs_CZ": "Tschechesch (Tschechien)",
  "csb": "Kaschubesch",
  "cu": "Kiercheslawesch",
  "cv": "Tschuwaschesch",
  "cy": "Walisesch",
  "cy_GB": "Walisesch (Groussbritannien)",
  "da": "Dänesch",
  "da_DK": "Dänesch (Dänemark)",
  "da_GL": "Dänesch (Grönland)",
  "dak": "Dakota-Sprooch",
  "dar": "Darginesch",
  "dav": "Taita",
  "de": "Däitsch",
  "de_AT": "Däitsch (Éisträich)",
  "de_BE": "Däitsch (Belsch)",
  "de_CH": "Däitsch (Schwäiz)",
  "de_DE": "Däitsch (Däitschland)",
  "de_LI": "Däitsch (Liechtenstein)",
  "de_LU": "Däitsch (Lëtzebuerg)",
  "del": "Delaware-Sprooch",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka-Sprooch",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Niddersorbesch",
  "dtp": "Zentral-Dusun",
  "dua": "Duala",
  "dum": "Mëttelhollännesch",
  "dv": "Maldivesch",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula-Sprooch",
  "dz": "Bhutanesch",
  "dz_BT": "Bhutanesch (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Kiembu",
  "ee": "Ewe-Sprooch",
  "ee_GH": "Ewe-Sprooch (Ghana)",
  "ee_TG": "Ewe-Sprooch (Togo)",
  "efi": "Efik",
  "egl": "Emilianesch",
  "egy": "Egyptesch",
  "eka": "Ekajuk",
  "el": "Griichesch",
  "el_CY": "Griichesch (Zypern)",
  "el_GR": "Griichesch (Griicheland)",
  "elx": "Elamesch",
  "en": "Englesch",
  "en_AG": "Englesch (Antigua a Barbuda)",
  "en_AI": "Englesch (Anguilla)",
  "en_AS": "Englesch (Amerikanesch-Samoa)",
  "en_AU": "Englesch (Australien)",
  "en_BB": "Englesch (Barbados)",
  "en_BE": "Englesch (Belsch)",
  "en_BM": "Englesch (Bermuda)",
  "en_BS": "Englesch (Bahamas)",
  "en_BW": "Englesch (Botsuana)",
  "en_BZ": "Englesch (Belize)",
  "en_CA": "Englesch (Kanada)",
  "en_CC": "Englesch (Kokosinselen)",
  "en_CK": "Englesch (Cookinselen)",
  "en_CM": "Englesch (Kamerun)",
  "en_CX": "Englesch (Chrëschtdagsinsel)",
  "en_DG": "Englesch (Diego Garcia)",
  "en_DM": "Englesch (Dominica)",
  "en_ER": "Englesch (Eritrea)",
  "en_FJ": "Englesch (Fidschi)",
  "en_FK": "Englesch (Falklandinselen)",
  "en_FM": "Englesch (Mikronesien)",
  "en_GB": "Englesch (Groussbritannien)",
  "en_GD": "Englesch (Grenada)",
  "en_GG": "Englesch (Guernsey)",
  "en_GH": "Englesch (Ghana)",
  "en_GI": "Englesch (Gibraltar)",
  "en_GM": "Englesch (Gambia)",
  "en_GU": "Englesch (Guam)",
  "en_GY": "Englesch (Guyana)",
  "en_HK": "Englesch (Spezialverwaltungszon Hong Kong)",
  "en_IE": "Englesch (Irland)",
  "en_IM": "Englesch (Isle of Man)",
  "en_IN": "Englesch (Indien)",
  "en_IO": "Englesch (Britescht Territorium am Indeschen Ozean)",
  "en_JE": "Englesch (Jersey)",
  "en_JM": "Englesch (Jamaika)",
  "en_KE": "Englesch (Kenia)",
  "en_KI": "Englesch (Kiribati)",
  "en_KN": "Englesch (St. Kitts an Nevis)",
  "en_KY": "Englesch (Kaimaninselen)",
  "en_LC": "Englesch (St. Lucia)",
  "en_LR": "Englesch (Liberia)",
  "en_LS": "Englesch (Lesotho)",
  "en_MG": "Englesch (Madagaskar)",
  "en_MH": "Englesch (Marshallinselen)",
  "en_MO": "Englesch (Spezialverwaltungszon Macau)",
  "en_MP": "Englesch (Nërdlech Marianen)",
  "en_MS": "Englesch (Montserrat)",
  "en_MT": "Englesch (Malta)",
  "en_MU": "Englesch (Mauritius)",
  "en_MW": "Englesch (Malawi)",
  "en_MY": "Englesch (Malaysia)",
  "en_NA": "Englesch (Namibia)",
  "en_NF": "Englesch (Norfolkinsel)",
  "en_NG": "Englesch (Nigeria)",
  "en_NR": "Englesch (Nauru)",
  "en_NU": "Englesch (Niue)",
  "en_NZ": "Englesch (Neiséiland)",
  "en_PG": "Englesch (Papua-Neiguinea)",
  "en_PH": "Englesch (Philippinnen)",
  "en_PK": "Englesch (Pakistan)",
  "en_PN": "Englesch (Pitcairninselen)",
  "en_PR": "Englesch (Puerto Rico)",
  "en_PW": "Englesch (Palau)",
  "en_RW": "Englesch (Ruanda)",
  "en_SB": "Englesch (Salomonen)",
  "en_SC": "Englesch (Seychellen)",
  "en_SD": "Englesch (Sudan)",
  "en_SG": "Englesch (Singapur)",
  "en_SH": "Englesch (St. Helena)",
  "en_SL": "Englesch (Sierra Leone)",
  "en_SS": "Englesch (Südsudan)",
  "en_SX": "Englesch (Sint Maarten)",
  "en_SZ": "Englesch (Swasiland)",
  "en_TC": "Englesch (Turks- a Caicosinselen)",
  "en_TK": "Englesch (Tokelau)",
  "en_TO": "Englesch (Tonga)",
  "en_TT": "Englesch (Trinidad an Tobago)",
  "en_TV": "Englesch (Tuvalu)",
  "en_TZ": "Englesch (Tansania)",
  "en_UG": "Englesch (Uganda)",
  "en_UM": "Englesch (Amerikanesch-Ozeanien)",
  "en_US": "Englesch (Vereenegt Staate vun Amerika)",
  "en_VC": "Englesch (St. Vincent an d’Grenadinnen)",
  "en_VG": "Englesch (Britesch Joffereninselen)",
  "en_VI": "Englesch (Amerikanesch Joffereninselen)",
  "en_VU": "Englesch (Vanuatu)",
  "en_WS": "Englesch (Samoa)",
  "en_ZA": "Englesch (Südafrika)",
  "en_ZM": "Englesch (Sambia)",
  "en_ZW": "Englesch (Simbabwe)",
  "enm": "Mëttelenglesch",
  "eo": "Esperanto",
  "es": "Spuenesch",
  "es_419": "Latäinamerikanescht Spuenesch",
  "es_AR": "Spuenesch (Argentinien)",
  "es_BO": "Spuenesch (Bolivien)",
  "es_CL": "Spuenesch (Chile)",
  "es_CO": "Spuenesch (Kolumbien)",
  "es_CR": "Spuenesch (Costa Rica)",
  "es_CU": "Spuenesch (Kuba)",
  "es_DO": "Spuenesch (Dominikanesch Republik)",
  "es_EA": "Spuenesch (Ceuta a Melilla)",
  "es_EC": "Spuenesch (Ecuador)",
  "es_ES": "Spuenesch (Spanien)",
  "es_GQ": "Spuenesch (Equatorialguinea)",
  "es_GT": "Spuenesch (Guatemala)",
  "es_HN": "Spuenesch (Honduras)",
  "es_IC": "Spuenesch (Kanaresch Inselen)",
  "es_MX": "Spuenesch (Mexiko)",
  "es_NI": "Spuenesch (Nicaragua)",
  "es_PA": "Spuenesch (Panama)",
  "es_PE": "Spuenesch (Peru)",
  "es_PH": "Spuenesch (Philippinnen)",
  "es_PR": "Spuenesch (Puerto Rico)",
  "es_PY": "Spuenesch (Paraguay)",
  "es_SV": "Spuenesch (El Salvador)",
  "es_US": "Spuenesch (Vereenegt Staate vun Amerika)",
  "es_UY": "Spuenesch (Uruguay)",
  "es_VE": "Spuenesch (Venezuela)",
  "esu": "Yup’ik",
  "et": "Estnesch",
  "et_EE": "Estnesch (Estland)",
  "eu": "Baskesch",
  "eu_ES": "Baskesch (Spanien)",
  "ewo": "Ewondo",
  "ext": "Extremaduresch",
  "fa": "Persesch",
  "fa_AF": "Persesch (Afghanistan)",
  "fa_IR": "Persesch (Iran)",
  "fan": "Pangwe-Sprooch",
  "fat": "Fanti-Sprooch",
  "ff": "Ful",
  "ff_CM": "Ful (Kamerun)",
  "ff_GN": "Ful (Guinea)",
  "ff_MR": "Ful (Mauretanien)",
  "ff_SN": "Ful (Senegal)",
  "fi": "Finnesch",
  "fi_FI": "Finnesch (Finnland)",
  "fil": "Filipino",
  "fit": "Meänkieli",
  "fj": "Fidschianesch",
  "fo": "Färöesch",
  "fo_FO": "Färöesch (Färöer)",
  "fon": "Fon-Sprooch",
  "fr": "Franséisch",
  "fr_BE": "Franséisch (Belsch)",
  "fr_BF": "Franséisch (Burkina Faso)",
  "fr_BI": "Franséisch (Burundi)",
  "fr_BJ": "Franséisch (Benin)",
  "fr_BL": "Franséisch (Saint-Barthélemy)",
  "fr_CA": "Franséisch (Kanada)",
  "fr_CD": "Franséisch (Kongo-Kinshasa)",
  "fr_CF": "Franséisch (Zentralafrikanesch Republik)",
  "fr_CG": "Franséisch (Kongo-Brazzaville)",
  "fr_CH": "Franséisch (Schwäiz)",
  "fr_CI": "Franséisch (Elfebeeküst)",
  "fr_CM": "Franséisch (Kamerun)",
  "fr_DJ": "Franséisch (Dschibuti)",
  "fr_DZ": "Franséisch (Algerien)",
  "fr_FR": "Franséisch (Frankräich)",
  "fr_GA": "Franséisch (Gabun)",
  "fr_GF": "Franséisch (Guayane)",
  "fr_GN": "Franséisch (Guinea)",
  "fr_GP": "Franséisch (Guadeloupe)",
  "fr_GQ": "Franséisch (Equatorialguinea)",
  "fr_HT": "Franséisch (Haiti)",
  "fr_KM": "Franséisch (Komoren)",
  "fr_LU": "Franséisch (Lëtzebuerg)",
  "fr_MA": "Franséisch (Marokko)",
  "fr_MC": "Franséisch (Monaco)",
  "fr_MF": "Franséisch (St. Martin)",
  "fr_MG": "Franséisch (Madagaskar)",
  "fr_ML": "Franséisch (Mali)",
  "fr_MQ": "Franséisch (Martinique)",
  "fr_MR": "Franséisch (Mauretanien)",
  "fr_MU": "Franséisch (Mauritius)",
  "fr_NC": "Franséisch (Neikaledonien)",
  "fr_NE": "Franséisch (Niger)",
  "fr_PF": "Franséisch (Franséisch-Polynesien)",
  "fr_PM": "Franséisch (St. Pierre a Miquelon)",
  "fr_RE": "Franséisch (Réunion)",
  "fr_RW": "Franséisch (Ruanda)",
  "fr_SC": "Franséisch (Seychellen)",
  "fr_SN": "Franséisch (Senegal)",
  "fr_SY": "Franséisch (Syrien)",
  "fr_TD": "Franséisch (Tschad)",
  "fr_TG": "Franséisch (Togo)",
  "fr_TN": "Franséisch (Tunesien)",
  "fr_VU": "Franséisch (Vanuatu)",
  "fr_WF": "Franséisch (Wallis a Futuna)",
  "fr_YT": "Franséisch (Mayotte)",
  "frc": "Cajun",
  "frm": "Mëttelfranséisch",
  "fro": "Alfranséisch",
  "frp": "Frankoprovenzalesch",
  "frr": "Nordfriesesch",
  "frs": "Ostfriesesch",
  "fur": "Friulesch",
  "fy": "Westfriesesch",
  "fy_NL": "Westfriesesch (Holland)",
  "ga": "Iresch",
  "ga_IE": "Iresch (Irland)",
  "gaa": "Ga-Sprooch",
  "gag": "Gagausesch",
  "gan": "Gan-Chinesesch",
  "gay": "Gayo",
  "gba": "Gbaya-Sprooch",
  "gbz": "Zoroastrianescht Dari",
  "gd": "Schottescht Gällesch",
  "gd_GB": "Schottescht Gällesch (Groussbritannien)",
  "gez": "Geez",
  "gil": "Gilbertesesch",
  "gl": "Galizesch",
  "gl_ES": "Galizesch (Spanien)",
  "glk": "Gilaki",
  "gmh": "Mëttelhéichdäitsch",
  "gn": "Guarani",
  "goh": "Alhéichdäitsch",
  "gom": "Goan-Konkani",
  "gon": "Gondi-Sprooch",
  "gor": "Mongondou",
  "got": "Gotesch",
  "grb": "Grebo-Sprooch",
  "grc": "Algriichesch",
  "gsw": "Schwäizerdäitsch",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (Indien)",
  "guc": "Wayuu",
  "gur": "Farefare",
  "guz": "Gusii-Sprooch",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Kutchin-Sprooch",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Laténgesch)",
  "ha_Latn_GH": "Hausa (Laténgesch, Ghana)",
  "ha_Latn_NE": "Hausa (Laténgesch, Niger)",
  "ha_Latn_NG": "Hausa (Laténgesch, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida-Sprooch",
  "hak": "Hakka-Chinesesch",
  "haw": "Hawaiesch",
  "he": "Hebräesch",
  "he_IL": "Hebräesch (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (Indien)",
  "hif": "Fidschi-Hindi",
  "hil": "Hiligaynon-Sprooch",
  "hit": "Hethitesch",
  "hmn": "Miao-Sprooch",
  "ho": "Hiri-Motu",
  "hr": "Kroatesch",
  "hr_BA": "Kroatesch (Bosnien an Herzegowina)",
  "hr_HR": "Kroatesch (Kroatien)",
  "hsb": "Uewersorbesch",
  "hsn": "Xiang-Chinesesch",
  "ht": "Haitianesch",
  "hu": "Ungaresch",
  "hu_HU": "Ungaresch (Ungarn)",
  "hup": "Hupa",
  "hy": "Armenesch",
  "hy_AM": "Armenesch (Armenien)",
  "hz": "Herero-Sprooch",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indonesesch",
  "id_ID": "Indonesesch (Indonesien)",
  "ie": "Interlingue",
  "ig": "Igbo-Sprooch",
  "ig_NG": "Igbo-Sprooch (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiak",
  "ilo": "Ilokano-Sprooch",
  "inh": "Inguschesch",
  "io": "Ido-Sprooch",
  "is": "Islännesch",
  "is_IS": "Islännesch (Island)",
  "it": "Italienesch",
  "it_CH": "Italienesch (Schwäiz)",
  "it_IT": "Italienesch (Italien)",
  "it_SM": "Italienesch (San Marino)",
  "iu": "Inukitut",
  "izh": "Ischoresch",
  "ja": "Japanesch",
  "ja_JP": "Japanesch (Japan)",
  "jam": "Jamaikanesch-Kreolesch",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Jiddesch-Persesch",
  "jrb": "Jiddesch-Arabesch",
  "jut": "Jütesch",
  "jv": "Javanesch",
  "ka": "Georgesch",
  "ka_GE": "Georgesch (Georgien)",
  "kaa": "Karakalpakesch",
  "kab": "Kabylesch",
  "kac": "Kachin-Sprooch",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardinesch",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongolesesch",
  "kgp": "Kaingang",
  "kha": "Khasi-Sprooch",
  "kho": "Sakesch",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu-Sprooch",
  "ki_KE": "Kikuyu-Sprooch (Kenia)",
  "kiu": "Kirmanjki",
  "kj": "Kwanyama",
  "kk": "Kasachesch",
  "kk_Cyrl": "Kasachesch (Kyrillesch)",
  "kk_Cyrl_KZ": "Kasachesch (Kyrillesch, Kasachstan)",
  "kk_KZ": "Kasachesch (Kasachstan)",
  "kkj": "Kako",
  "kl": "Grönlännesch",
  "kl_GL": "Grönlännesch (Grönland)",
  "kln": "Kalenjin",
  "km": "Kambodschanesch",
  "km_KH": "Kambodschanesch (Kambodscha)",
  "kmb": "Kimbundu-Sprooch",
  "kn": "Kannada",
  "kn_IN": "Kannada (Indien)",
  "ko": "Koreanesch",
  "ko_KP": "Koreanesch (Nordkorea)",
  "ko_KR": "Koreanesch (Südkorea)",
  "koi": "Komi-Permiak",
  "kok": "Konkani",
  "kos": "Kosraeanesch",
  "kpe": "Kpelle-Sprooch",
  "kr": "Kanuri-Sprooch",
  "krc": "Karatschaiesch-Balkaresch",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelesch",
  "kru": "Oraon-Sprooch",
  "ks": "Kaschmiresch",
  "ks_Arab": "Kaschmiresch (Arabesch)",
  "ks_Arab_IN": "Kaschmiresch (Arabesch, Indien)",
  "ks_IN": "Kaschmiresch (Indien)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Kölsch",
  "ku": "Kurdesch",
  "kum": "Kumükesch",
  "kut": "Kutenai-Sprooch",
  "kv": "Komi-Sprooch",
  "kw": "Kornesch",
  "kw_GB": "Kornesch (Groussbritannien)",
  "ky": "Kirgisesch",
  "ky_Cyrl": "Kirgisesch (Kyrillesch)",
  "ky_Cyrl_KG": "Kirgisesch (Kyrillesch, Kirgisistan)",
  "ky_KG": "Kirgisesch (Kirgisistan)",
  "la": "Latäin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba-Sprooch",
  "lb": "Lëtzebuergesch",
  "lb_LU": "Lëtzebuergesch (Lëtzebuerg)",
  "lez": "Lesgesch",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda-Sprooch",
  "lg_UG": "Ganda-Sprooch (Uganda)",
  "li": "Limburgesch",
  "lij": "Liguresch",
  "liv": "Livesch",
  "lkt": "Lakota-Sprooch",
  "lmo": "Lombardesch",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Kongo-Kinshasa)",
  "ln_CF": "Lingala (Zentralafrikanesch Republik)",
  "ln_CG": "Lingala (Kongo-Brazzaville)",
  "lo": "Laotesch",
  "lo_LA": "Laotesch (Laos)",
  "lol": "Mongo",
  "loz": "Rotse-Sprooch",
  "lt": "Litauesch",
  "lt_LT": "Litauesch (Litauen)",
  "ltg": "Lettgallesch",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Kongo-Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno-Sprooch",
  "lun": "Lunda-Sprooch",
  "luo": "Luo-Sprooch",
  "lus": "Lushai-Sprooch",
  "luy": "Olulujia",
  "lv": "Lettesch",
  "lv_LV": "Lettesch (Lettland)",
  "lzh": "Klassescht Chinesesch",
  "lzz": "Lasesch Sprooch",
  "mad": "Maduresesch",
  "maf": "Mafa",
  "mag": "Khotta",
  "mai": "Maithili",
  "mak": "Makassaresch",
  "man": "Manding-Sprooch",
  "mas": "Massai-Sprooch",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandaresesch",
  "men": "Mende-Sprooch",
  "mer": "Meru-Sprooch",
  "mfe": "Morisyen",
  "mg": "Malagassi-Sprooch",
  "mg_MG": "Malagassi-Sprooch (Madagaskar)",
  "mga": "Mëtteliresch",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta’",
  "mh": "Marschallesesch",
  "mi": "Maori",
  "mic": "Micmac-Sprooch",
  "min": "Minangkabau-Sprooch",
  "mk": "Mazedonesch",
  "mk_MK": "Mazedonesch (Mazedonien)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (Indien)",
  "mn": "Mongolesch",
  "mn_Cyrl": "Mongolesch (Kyrillesch)",
  "mn_Cyrl_MN": "Mongolesch (Kyrillesch, Mongolei)",
  "mn_MN": "Mongolesch (Mongolei)",
  "mnc": "Mandschuresch",
  "mni": "Meithei-Sprooch",
  "moh": "Mohawk-Sprooch",
  "mos": "Mossi-Sprooch",
  "mr": "Marathi",
  "mr_IN": "Marathi (Indien)",
  "mrj": "West-Mari",
  "ms": "Malaiesch",
  "ms_BN": "Malaiesch (Brunei)",
  "ms_Latn": "Malaiesch (Laténgesch)",
  "ms_Latn_BN": "Malaiesch (Laténgesch, Brunei)",
  "ms_Latn_MY": "Malaiesch (Laténgesch, Malaysia)",
  "ms_Latn_SG": "Malaiesch (Laténgesch, Singapur)",
  "ms_MY": "Malaiesch (Malaysia)",
  "ms_SG": "Malaiesch (Singapur)",
  "mt": "Maltesesch",
  "mt_MT": "Maltesesch (Malta)",
  "mua": "Mundang",
  "mul": "Méisproocheg",
  "mus": "Muskogee-Sprooch",
  "mwl": "Mirandesesch",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Birmanesch",
  "my_MM": "Birmanesch (Myanmar)",
  "mye": "Myene",
  "myv": "Ersja-Mordwinesch",
  "mzn": "Mazandarani",
  "na": "Nauruesch",
  "nan": "Min-Nan-Chinesesch",
  "nap": "Neapolitanesch",
  "naq": "Nama",
  "nb": "Norwegesch Bokmål",
  "nb_NO": "Norwegesch Bokmål (Norwegen)",
  "nb_SJ": "Norwegesch Bokmål (Svalbard a Jan Mayen)",
  "nd": "Nord-Ndebele-Sprooch",
  "nd_ZW": "Nord-Ndebele-Sprooch (Simbabwe)",
  "nds": "Nidderdäitsch",
  "ne": "Nepalesesch",
  "ne_IN": "Nepalesesch (Indien)",
  "ne_NP": "Nepalesesch (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias-Sprooch",
  "niu": "Niue-Sprooch",
  "njo": "Ao Naga",
  "nl": "Hollännesch",
  "nl_AW": "Hollännesch (Aruba)",
  "nl_BE": "Hollännesch (Belsch)",
  "nl_BQ": "Hollännesch (Karibescht Holland)",
  "nl_CW": "Hollännesch (Curaçao)",
  "nl_NL": "Hollännesch (Holland)",
  "nl_SR": "Hollännesch (Suriname)",
  "nl_SX": "Hollännesch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegesch Nynorsk",
  "nn_NO": "Norwegesch Nynorsk (Norwegen)",
  "nnh": "Ngiemboon",
  "no": "Norwegesch",
  "no_NO": "Norwegesch (Norwegen)",
  "nog": "Nogai",
  "non": "Alnordesch",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Süd-Ndebele-Sprooch",
  "nso": "Nord-Sotho-Sprooch",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Al-Newari",
  "ny": "Nyanja-Sprooch",
  "nym": "Nyamwezi-Sprooch",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Okzitanesch",
  "oj": "Ojibwa-Sprooch",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopien)",
  "om_KE": "Oromo (Kenia)",
  "or": "Orija",
  "or_IN": "Orija (Indien)",
  "os": "Ossetesch",
  "os_GE": "Ossetesch (Georgien)",
  "os_RU": "Ossetesch (Russland)",
  "osa": "Osage-Sprooch",
  "ota": "Osmanesch",
  "pa": "Pandschabesch",
  "pa_Arab": "Pandschabesch (Arabesch)",
  "pa_Arab_PK": "Pandschabesch (Arabesch, Pakistan)",
  "pa_Guru": "Pandschabesch (Gurmukhi)",
  "pa_Guru_IN": "Pandschabesch (Gurmukhi, Indien)",
  "pa_IN": "Pandschabesch (Indien)",
  "pa_PK": "Pandschabesch (Pakistan)",
  "pag": "Pangasinan-Sprooch",
  "pal": "Mëttelpersesch",
  "pam": "Pampanggan-Sprooch",
  "pap": "Papiamento",
  "pau": "Palau",
  "pcd": "Picardesch",
  "pdc": "Pennsylvaniadäitsch",
  "pdt": "Plattdäitsch",
  "peo": "Alpersesch",
  "pfl": "Pfälzesch Däitsch",
  "phn": "Phönikesch",
  "pi": "Pali",
  "pl": "Polnesch",
  "pl_PL": "Polnesch (Polen)",
  "pms": "Piemontesesch",
  "pnt": "Pontesch",
  "pon": "Ponapeanesch",
  "prg": "Preisesch",
  "pro": "Alprovenzalesch",
  "ps": "Paschtu",
  "ps_AF": "Paschtu (Afghanistan)",
  "pt": "Portugisesch",
  "pt_AO": "Portugisesch (Angola)",
  "pt_BR": "Portugisesch (Brasilien)",
  "pt_CV": "Portugisesch (Kap Verde)",
  "pt_GW": "Portugisesch (Guinea-Bissau)",
  "pt_MO": "Portugisesch (Spezialverwaltungszon Macau)",
  "pt_MZ": "Portugisesch (Mosambik)",
  "pt_PT": "Portugisesch (Portugal)",
  "pt_ST": "Portugisesch (São Tomé a Príncipe)",
  "pt_TL": "Portugisesch (Osttimor)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivien)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Quiché-Sprooch",
  "qug": "Kichwa (Chimborazo-Gebidder)",
  "raj": "Rajasthani",
  "rap": "Ouschterinsel-Sprooch",
  "rar": "Rarotonganesch",
  "rgn": "Romagnol",
  "rif": "Tarifit",
  "rm": "Rätoromanesch",
  "rm_CH": "Rätoromanesch (Schwäiz)",
  "rn": "Rundi-Sprooch",
  "rn_BI": "Rundi-Sprooch (Burundi)",
  "ro": "Rumänesch",
  "ro_MD": "Rumänesch (Moldawien)",
  "ro_RO": "Rumänesch (Rumänien)",
  "rof": "Rombo",
  "rom": "Romani",
  "root": "Root",
  "rtm": "Rotumanesch",
  "ru": "Russesch",
  "ru_BY": "Russesch (Wäissrussland)",
  "ru_KG": "Russesch (Kirgisistan)",
  "ru_KZ": "Russesch (Kasachstan)",
  "ru_MD": "Russesch (Moldawien)",
  "ru_RU": "Russesch (Russland)",
  "ru_UA": "Russesch (Ukrain)",
  "rue": "Russinesch",
  "rug": "Roviana",
  "rup": "Aromunesch",
  "rw": "Ruandesch",
  "rw_RW": "Ruandesch (Ruanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe-Sprooch",
  "sah": "Jakutesch",
  "sam": "Samaritanesch",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardesch",
  "scn": "Sizilianesch",
  "sco": "Schottesch",
  "sd": "Sindhi",
  "sdc": "Sassaresesch",
  "se": "Nordsamesch",
  "se_FI": "Nordsamesch (Finnland)",
  "se_NO": "Nordsamesch (Norwegen)",
  "se_SE": "Nordsamesch (Schweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkupesch",
  "ses": "Koyra Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Zentralafrikanesch Republik)",
  "sga": "Aliresch",
  "sgs": "Samogitesch",
  "sh": "Serbo-Kroatesch",
  "sh_BA": "Serbo-Kroatesch (Bosnien an Herzegowina)",
  "shi": "Taschelhit",
  "shn": "Schan-Sprooch",
  "shu": "Tschadesch-Arabesch",
  "si": "Singhalesesch",
  "si_LK": "Singhalesesch (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slowakesch",
  "sk_SK": "Slowakesch (Slowakei)",
  "sl": "Slowenesch",
  "sl_SI": "Slowenesch (Slowenien)",
  "sli": "Nidderschlesesch",
  "sly": "Selayar",
  "sm": "Samoanesch",
  "sma": "Südsamesch",
  "smj": "Lule-Lappesch",
  "smn": "Inari-Lappesch",
  "sms": "Skolt-Lappesch",
  "sn": "Shona",
  "sn_ZW": "Shona (Simbabwe)",
  "snk": "Soninke-Sprooch",
  "so": "Somali",
  "so_DJ": "Somali (Dschibuti)",
  "so_ET": "Somali (Ethiopien)",
  "so_KE": "Somali (Kenia)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdesch",
  "sq": "Albanesch",
  "sq_AL": "Albanesch (Albanien)",
  "sq_MK": "Albanesch (Mazedonien)",
  "sq_XK": "Albanesch (Kosovo)",
  "sr": "Serbesch",
  "sr_BA": "Serbesch (Bosnien an Herzegowina)",
  "sr_Cyrl": "Serbesch (Kyrillesch)",
  "sr_Cyrl_BA": "Serbesch (Kyrillesch, Bosnien an Herzegowina)",
  "sr_Cyrl_ME": "Serbesch (Kyrillesch, Montenegro)",
  "sr_Cyrl_RS": "Serbesch (Kyrillesch, Serbien)",
  "sr_Cyrl_XK": "Serbesch (Kyrillesch, Kosovo)",
  "sr_Latn": "Serbesch (Laténgesch)",
  "sr_Latn_BA": "Serbesch (Laténgesch, Bosnien an Herzegowina)",
  "sr_Latn_ME": "Serbesch (Laténgesch, Montenegro)",
  "sr_Latn_RS": "Serbesch (Laténgesch, Serbien)",
  "sr_Latn_XK": "Serbesch (Laténgesch, Kosovo)",
  "sr_ME": "Serbesch (Montenegro)",
  "sr_RS": "Serbesch (Serbien)",
  "sr_XK": "Serbesch (Kosovo)",
  "srn": "Srananesch",
  "srr": "Serer-Sprooch",
  "ss": "Swazi",
  "ssy": "Saho",
  "st": "Süd-Sotho-Sprooch",
  "stq": "Saterfriesesch",
  "su": "Sundanesesch",
  "suk": "Sukuma-Sprooch",
  "sus": "Susu",
  "sux": "Sumeresch",
  "sv": "Schwedesch",
  "sv_AX": "Schwedesch (Ålandinselen)",
  "sv_FI": "Schwedesch (Finnland)",
  "sv_SE": "Schwedesch (Schweden)",
  "sw": "Suaheli",
  "sw_CD": "Kongo-Swahili",
  "sw_KE": "Suaheli (Kenia)",
  "sw_TZ": "Suaheli (Tansania)",
  "sw_UG": "Suaheli (Uganda)",
  "swb": "Komoresch",
  "swc": "Kongo-Swahili",
  "syc": "Alsyresch",
  "syr": "Syresch",
  "szl": "Schlesesch",
  "ta": "Tamilesch",
  "ta_IN": "Tamilesch (Indien)",
  "ta_LK": "Tamilesch (Sri Lanka)",
  "ta_MY": "Tamilesch (Malaysia)",
  "ta_SG": "Tamilesch (Singapur)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (Indien)",
  "tem": "Temne",
  "teo": "Teso",
  "ter": "Tereno-Sprooch",
  "tet": "Tetum-Sprooch",
  "tg": "Tadschikesch",
  "th": "Thailännesch",
  "th_TH": "Thailännesch (Thailand)",
  "ti": "Tigrinja",
  "ti_ER": "Tigrinja (Eritrea)",
  "ti_ET": "Tigrinja (Ethiopien)",
  "tig": "Tigre",
  "tiv": "Tiv-Sprooch",
  "tk": "Turkmenesch",
  "tkl": "Tokelauanesch",
  "tkr": "Tsachuresch",
  "tl": "Dagalog",
  "tl_PH": "Dagalog (Philippinnen)",
  "tlh": "Klingonesch",
  "tli": "Tlingit-Sprooch",
  "tly": "Talesch",
  "tmh": "Tamaseq",
  "tn": "Tswana-Sprooch",
  "to": "Tongaesch",
  "to_TO": "Tongaesch (Tonga)",
  "tog": "Tsonga-Sprooch",
  "tpi": "Neimelanesesch",
  "tr": "Tierkesch",
  "tr_CY": "Tierkesch (Zypern)",
  "tr_TR": "Tierkesch (Tierkei)",
  "tru": "Turoyo",
  "trv": "Seediq",
  "ts": "Tsonga",
  "tsd": "Tsakonesch",
  "tsi": "Tsimshian-Sprooch",
  "tt": "Tataresch",
  "ttt": "Tatesch",
  "tum": "Tumbuka-Sprooch",
  "tvl": "Elliceanesch",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitesch",
  "tyv": "Tuwinesch",
  "tzm": "Mëttlert-Atlas-Tamazight",
  "udm": "Udmurtesch",
  "ug": "Uiguresch",
  "ug_Arab": "Uiguresch (Arabesch)",
  "ug_Arab_CN": "Uiguresch (Arabesch, China)",
  "ug_CN": "Uiguresch (China)",
  "uga": "Ugaritesch",
  "uk": "Ukrainesch",
  "uk_UA": "Ukrainesch (Ukrain)",
  "umb": "Mbundu-Sprooch",
  "und": "Onbestëmmt Sprooch",
  "ur": "Urdu",
  "ur_IN": "Urdu (Indien)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Usbekesch",
  "uz_AF": "Usbekesch (Afghanistan)",
  "uz_Arab": "Usbekesch (Arabesch)",
  "uz_Arab_AF": "Usbekesch (Arabesch, Afghanistan)",
  "uz_Cyrl": "Usbekesch (Kyrillesch)",
  "uz_Cyrl_UZ": "Usbekesch (Kyrillesch, Usbekistan)",
  "uz_Latn": "Usbekesch (Laténgesch)",
  "uz_Latn_UZ": "Usbekesch (Laténgesch, Usbekistan)",
  "uz_UZ": "Usbekesch (Usbekistan)",
  "vai": "Vai-Sprooch",
  "ve": "Venda-Sprooch",
  "vec": "Venezesch",
  "vep": "Wepsesch",
  "vi": "Vietnamesesch",
  "vi_VN": "Vietnamesesch (Vietnam)",
  "vls": "Westflämesch",
  "vmf": "Mainfränkesch",
  "vo": "Volapük",
  "vot": "Wotesch",
  "vro": "Voro",
  "vun": "Vunjo",
  "wa": "Wallounesch",
  "wae": "Walliserdäitsch",
  "wal": "Walamo-Sprooch",
  "war": "Waray",
  "was": "Washo-Sprooch",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu-Chinesesch",
  "xal": "Kalmückesch",
  "xh": "Xhosa",
  "xmf": "Mingrelesch Sprooch",
  "xog": "Soga",
  "yao": "Yao-Sprooch",
  "yap": "Yapesesch",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Jiddesch",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "Kantonesesch",
  "za": "Zhuang",
  "zap": "Zapotekesch",
  "zbl": "Bliss-Symboler",
  "zea": "Seelännesch",
  "zen": "Zenaga",
  "zgh": "Marokkanescht Standard-Tamazight",
  "zh": "Chinesesch",
  "zh_CN": "Chinesesch (China)",
  "zh_HK": "Chinesesch (Spezialverwaltungszon Hong Kong)",
  "zh_Hans": "Chinesesch (Vereinfacht)",
  "zh_Hans_CN": "Chinesesch (Vereinfacht, China)",
  "zh_Hans_HK": "Chinesesch (Vereinfacht, Spezialverwaltungszon Hong Kong)",
  "zh_Hans_MO": "Chinesesch (Vereinfacht, Spezialverwaltungszon Macau)",
  "zh_Hans_SG": "Chinesesch (Vereinfacht, Singapur)",
  "zh_Hant": "Chinesesch (Traditionell)",
  "zh_Hant_HK": "Chinesesch (Traditionell, Spezialverwaltungszon Hong Kong)",
  "zh_Hant_MO": "Chinesesch (Traditionell, Spezialverwaltungszon Macau)",
  "zh_Hant_TW": "Chinesesch (Traditionell, Taiwan)",
  "zh_MO": "Chinesesch (Spezialverwaltungszon Macau)",
  "zh_SG": "Chinesesch (Singapur)",
  "zh_TW": "Chinesesch (Taiwan)",
  "zu": "Zulu",
  "zu_ZA": "Zulu (Südafrika)",
  "zun": "Zuni-Sprooch",
  "zxx": "Keng Sproochinhalter",
  "zza": "Zaza"
};
