const names = {
  "aa": "Afar",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "afh": "Afrihili",
  "ain": "Ainu",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "arc": "Aramaic",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "ba": "बाश्किर",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "वेलारूसी",
  "bej": "Beja",
  "bew": "Betawi",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "bra": "Braj",
  "brh": "Brahui",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chy": "Cheyenne",
  "ckb": "सोरानी कुर्दिश",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "da": "डेनिश",
  "dak": "Dakota",
  "dar": "Dargwa",
  "de_AT": "जर्मन (अष्ट्रिया)",
  "de_CH": "जर्मन (स्विजरल्याण्ड)",
  "del": "Delaware",
  "dgr": "Dogrib",
  "din": "Dinka",
  "doi": "Dogri",
  "dtp": "Central Dusun",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyu": "Dyula",
  "dzg": "Dazaga",
  "ee": "इवि",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "elx": "Elamite",
  "en": "अंग्रेजी",
  "en_AU": "अंग्रेजी (अष्ट्रेलिया)",
  "en_CA": "अंग्रेजी (क्यानाडा)",
  "en_GB": "अंग्रेजी (बेलायत)",
  "en_US": "अंग्रेजी (संयुक्त राज्य)",
  "enm": "Middle English",
  "es": "स्पेनिस",
  "es_419": "Latin American Spanish",
  "es_ES": "स्पेनिस (स्पेन)",
  "es_MX": "स्पेनिस (मेक्सिको)",
  "esu": "Central Yupik",
  "et": "इस्टोनियाली",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa_AF": "फारसी (अफगानिस्तान)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "fi": "फिनिश",
  "fj": "फिजियाली",
  "fon": "Fon",
  "fr_CA": "फ्रान्सेली (क्यानाडा)",
  "fr_CH": "फ्रान्सेली (स्विजरल्याण्ड)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "फ्रिजीयन",
  "ga": "आइरिश",
  "gaa": "Ga",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gd": "Scottish Gaelic",
  "gez": "Geez",
  "gil": "Gilbertese",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "गुजरानी",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gur": "Frafra",
  "gwi": "Gwichʼin",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "क्रोएशियाली",
  "hsn": "Xiang Chinese",
  "ht": "हैटियाली",
  "hu": "हंग्रीयाली",
  "hup": "Hupa",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ie": "Interlingue",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "आइसल्यान्डिक",
  "it": "इटालियन",
  "iu": "लनुक्टिटुट",
  "izh": "Ingrian",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "गोम्बा",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "जाभानिज",
  "kaa": "Kara-Kalpak",
  "kac": "Kachin",
  "kaj": "Jju",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khw": "Khowar",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kmb": "Kimbundu",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "काश्मीरी",
  "ksh": "Colognian",
  "ku": "कुर्दिश",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "कोर्निश",
  "lad": "Ladino",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "लक्जेम्बर्गिस",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "लोकोता",
  "lmo": "Lombard",
  "ln": "लिंगाला",
  "lol": "Mongo",
  "loz": "Lozi",
  "ltg": "Latgalian",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "lus": "Mizo",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "मासाल",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mga": "Middle Irish",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "म्याकेडोनियन",
  "mn": "मंगोल",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mos": "Mossi",
  "ms": "मलाया",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "वर्मेली",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "nd": "उत्तर नेडेबेले",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl_BE": "डच (बेल्जियम)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "or": "ओरिया",
  "os": "Ossetic",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "पोलिश",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "पाश्तो",
  "pt_BR": "पोर्तुगी (ब्राजिल)",
  "pt_PT": "पोर्तुगी (पोर्चुगल)",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "रोमानिश",
  "rn": "रूण्डी",
  "ro_MD": "रोमानियाली (माल्डोभा)",
  "root": "Root",
  "ru": "रूसी",
  "rup": "Aromanian",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sga": "Old Irish",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "सिन्हाला",
  "sli": "Lower Silesian",
  "sm": "Samoan",
  "snk": "Soninke",
  "sq": "अल्बेनियन",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "स्विडिश",
  "swb": "Comorian",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "tem": "Timne",
  "tet": "Tetum",
  "ti": "तिग्रीन्या",
  "tig": "Tigre",
  "tlh": "Klingon",
  "tn": "Tswana",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "trv": "Taroko",
  "ts": "Tsonga",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "udm": "Udmurt",
  "umb": "Umbundu",
  "ve": "Venda",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "xal": "Kalmyk",
  "xmf": "Mingrelian",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "zbl": "Blissymbols",
  "zh_Hans": "चिनियाँ (सरलिकृत चिनी)",
  "zh_Hant": "चिनियाँ (परम्परागत चिनी)",
  "zun": "Zuni",
  "zza": "Zaza"
};
