const names = {
  "001": "Lefatše",
  "002": "Afrika",
  "003": "Amerika e Leboea",
  "005": "Amerika e Boroa",
  "009": "Oceania",
  "011": "Afrika Bophirimela",
  "013": "Amerika Bohareng",
  "014": "Afrika Bochabela",
  "015": "Afrika Leboea",
  "017": "Afrika Bohareng",
  "018": "Afrika Boroa",
  "019": "Amerika",
  "021": "Amerika Leboea",
  "029": "Caribbean",
  "030": "Asia Bochabela",
  "034": "Asia Boroa",
  "035": "Asia Boroa-bochabela",
  "039": "Europe Boroa",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Sebaka sa Micronesia",
  "061": "Polynesia",
  "062": "Asia Boroa-Bohareng",
  "142": "Asia",
  "143": "Asia Bohareng",
  "145": "Asia Bophirimela",
  "150": "Europe",
  "151": "Europe Bochabela",
  "154": "Europe Leboea",
  "155": "Europe Bophirimela",
  "172": "Commonwealth ea Linaha Tse Ikemetseng",
  "200": "Czechoslovakia",
  "202": "Afrika e ka boroa ho Sahara",
  "419": "Amerika Boroa",
  "830": "Lihlekehleke tsa Channel",
  "AC": "Sehlekehleke sa Ascension",
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua le Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antilles ea Netherlands",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Lihlekehleke tsa Åland",
  "AZ": "Azerbaijan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Sealbania sa Caucasus",
  "Ahom": "Ahom",
  "Arab": "Searabia",
  "Aran": "Nastaliq",
  "Armi": "Searame sa Imperial",
  "Armn": "Searmenia",
  "Avst": "Mongolo wa Avestan",
  "BA": "Bosnia le Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Mohalaleli Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Netherlands Netherlands",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Sehlekehleke sa Bouvet",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "Balinese",
  "Bamu": "Se-Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Mabatak",
  "Beng": "Bangla",
  "Bhks": "Bhaiksuki",
  "Blis": "Boitumelo",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "SeBuginese",
  "Buhd": "Buhid",
  "CA": "Canada",
  "CC": "Lihlekehleke tsa Cocos (Keeling)",
  "CD": "Congo - Kinshasa",
  "CF": "Rephaboliki ea Afrika Bohareng",
  "CG": "Congo - Brazzaville",
  "CH": "Switzerland",
  "CI": "Côte d'Ivoire",
  "CK": "Lihlekehleke tsa Cook",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "Chaena",
  "CO": "Colombia",
  "CP": "Sehlekehleke sa Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia le Montenegro",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Sehlekehleke sa Keresemese",
  "CY": "Cyprase",
  "CZ": "Riphaboliki ea Czech",
  "Cakm": "Chakma",
  "Cans": "Bonngoe ba Maaborigine Syllabics",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Sekoptiki",
  "Cprt": "Cyprase",
  "Cyrl": "Cyrillic",
  "Cyrs": "Kereke ea Khale Slavonic Cyrillic",
  "DD": "Jeremane Bochabela",
  "DE": "Jeremane",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "Deva": "Devanagari",
  "Diak": "Ho qoela Akuru",
  "Dogr": "Ntja",
  "Dsrt": "Deseret",
  "Dupl": "Khutsufatso ea Duployan",
  "EA": "Ceuta & Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egepeta",
  "EH": "Sahara Bophirimela",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "EU": "mokhatlo oa linaha tsa Iropa",
  "EZ": "Eurozone",
  "Egyd": "Boikokobetso ba Baegepeta",
  "Egyh": "Boikarabello ba Baegepeta",
  "Egyp": "Li-hieroglyphs tsa Baegepeta",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "Moethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Lihlekehleke tsa Falkland",
  "FM": "Micronesia",
  "FO": "Lihlekehleke tsa Faroe",
  "FR": "Fora",
  "FX": "Metropolitan Fora",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Guinea ea Equatorial",
  "GR": "Greece",
  "GS": "Lihlekehleke tsa South Georgia le South Sandwich",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "Khutsuri oa Segeorgia",
  "Geor": "Segeorgia",
  "Glag": "Se-Glagolitic",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Se-Gothic",
  "Gran": "Grantha",
  "Grek": "Segerike",
  "Gujr": "Segujarati",
  "Guru": "Gurmukhi",
  "HK": "Hong Kong SAR China",
  "HM": "Lihlekehleke tsa Heard & McDonald",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "Hanb": "Han le Bopomofo",
  "Hang": "Hangul",
  "Hani": "Monghali Han",
  "Hano": "Hanunoo",
  "Hans": "E nolofalitsoe",
  "Hant": "Tloaelo",
  "Hatr": "Hatran",
  "Hebr": "Seheberu",
  "Hira": "Hiragana",
  "Hluw": "Li-Hieroglyph tsa Anatolia",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Li-syllabaries tsa Majapane",
  "Hung": "Sehungary sa Khale",
  "IC": "Lihlekehleke tsa Canary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Iseraele",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "Sebaka sa Leoatle la Indian Indian",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "Inds": "Indus",
  "Ital": "Mongolo o Khale",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordane",
  "JP": "Japane",
  "Jamo": "Jamo",
  "Java": "Sejava",
  "Jpan": "Sejapane",
  "Jurc": "Moahloli",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Li-Comoros",
  "KN": "Mohalaleli Kitts le Nevis",
  "KP": "Korea Leboea",
  "KR": "Korea Boroa",
  "KW": "Kuwait",
  "KY": "Lihlekehleke tsa Cayman",
  "KZ": "Kazakhstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kits": "Mongolo o monyane oa Khitan",
  "Knda": "Sekannada",
  "Kore": "Sekorea",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Lebanone",
  "LC": "Mohalaleli Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "Lana": "Lanna",
  "Laoo": "Lao",
  "Latf": "Selatine sa Fraktur",
  "Latg": "Selatine sa Gaelic",
  "Latn": "Selatine",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Linear A",
  "Linb": "Linear B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Se-Lycian",
  "Lydi": "Lydian",
  "MA": "Moroko",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Mohalaleli Martin",
  "MG": "Madagascar",
  "MH": "Lihlekehleke tsa Marshall",
  "MI": "Lihlekehleke tsa Midway",
  "MK": "Macedonia Leboea",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao SAR China",
  "MP": "Lihlekehleke tsa Mariana Leboea",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "Li-hieroglyphs tsa Mayan",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Mongolo oa Meroitic",
  "Mero": "Meroitic",
  "Mlym": "Semalayalam",
  "Modi": "Modi",
  "Mong": "Semongolia",
  "Moon": "Khoeli",
  "Mroo": "Mong",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Myanmar",
  "NA": "Namibia",
  "NC": "Caledonia e ncha",
  "NE": "Niger",
  "NF": "Sehlekehleke sa Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Sebaka se sa nke Lehlakore",
  "NU": "Niue",
  "NZ": "New Zealand",
  "Nand": "Nandinagari",
  "Narb": "Arabia ea khale ea Leboea",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N'Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Odia",
  "Osge": "Ho sebedisa",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Sebaka sa Tšepo sa Pacific Islands",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Mohalaleli Pierre le Miquelon",
  "PN": "Lihlekehleke tsa Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Libaka tsa Palestina",
  "PT": "Portugal",
  "PU": "Lihlekehleke tsa Pacific tse fapaneng tsa U.S.",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Sebaka sa Panal Canal",
  "Palm": "Palema",
  "Pauc": "Pau Cin Hau",
  "Perm": "Permic ea Khale",
  "Phag": "Phags-pa",
  "Phli": "Mongolo o ngotsoeng Pahlavi",
  "Phlp": "Mofumahali Psalter Pahlavi",
  "Phlv": "Buka Pahlavi",
  "Phnx": "Mofenisia",
  "Plrd": "Pollard Fonotiki",
  "Prti": "Sengoloa sa Parthian",
  "QA": "Qatar",
  "QO": "Oceania e ka thoko",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Saudi Arabia",
  "SB": "Lihlekehleke tsa Solomon",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Mohalaleli Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard le Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Sudan Boroa",
  "ST": "Sao Tomé & Príncipe",
  "SU": "Union of Soviet Socialist Republics",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "Samr": "Mosamaria",
  "Sara": "Sarati",
  "Sarb": "Arabia ea khale ea Boroa",
  "Saur": "Saurashtra",
  "Sgnw": "Ho Ngola Matsoho",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "Sinhala",
  "Sogd": "Sogdian",
  "Sogo": "Sogdian oa khale",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Sesundanese",
  "Sylo": "Syloti Nagri",
  "Syrc": "Sesyria",
  "Syre": "Estrangelo Syriac",
  "Syrj": "Syriac ea Bophirimela",
  "Syrn": "Sesyria ea Bochabela",
  "TA": "Tristan da Cunha",
  "TC": "Lihlekehleke tsa Turks & Caicos",
  "TD": "Chad",
  "TF": "Libaka tse ka Boroa tsa Mafora",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "kalakuni",
  "TT": "Trinidad le Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Tai Lue e ncha",
  "Taml": "Setamile",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Setelugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Setagalog",
  "Thaa": "Thaana",
  "Thai": "Sethai",
  "Tibt": "Setibetan",
  "Tirh": "Tirhuta",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "Lihlekehleke tsa U.S.",
  "UN": "Machaba a Kopaneng",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "Ugar": "SeUgarit",
  "VA": "Motse oa Vatican",
  "VC": "Mohalaleli Vincent le Grenadines",
  "VD": "Vietnam Leboea",
  "VE": "Venezuela",
  "VG": "Lihlekehleke tsa Briteni tsa Borithane",
  "VI": "Lihlekehleke tsa U.S. Virgin",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Monghali Vai",
  "Visp": "Puo e bonahalang",
  "WF": "Wallis & Futuna",
  "WK": "Sehlekehleke sa Wake",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Mantsoe a iqapetsoeng",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "Old Persian",
  "Xsux": "Cuneiform ea Sumero-Akkadian",
  "YD": "People's Democratic Republic of Yemen",
  "YE": "Yemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "Afrika Boroa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Sebaka se sa Tsejoeng",
  "Zanb": "Lebala la Zanabazar",
  "Zinh": "Lefa",
  "Zmth": "Tsebiso ea lipalo",
  "Zsye": "Emoji",
  "Zsym": "Matšoao",
  "Zxxx": "E sa ngoloa",
  "Zyyy": "Tloaelehileng",
  "Zzzz": "Mongolo o sa Tsejoeng",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Maholi",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Mongolo wa Avestan",
  "aeb": "Searabia sa Tunisia",
  "af": "Seafrikanse",
  "af_NA": "Seafrikanse (Namibia)",
  "af_ZA": "Seafrikanse (Afrika Boroa)",
  "afa": "Puo ea Afro-Asiatic",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Tsoela pele",
  "ak": "SeAkan",
  "ak_GH": "Se-Akan (Ghana)",
  "akk": "SeAkadian",
  "akz": "Alabama",
  "ale": "Molemo",
  "alg": "Puo ea Algonquian",
  "aln": "Sealbania sa Gheg",
  "alt": "Southern Altai",
  "am": "Seamharic",
  "am_ET": "Se-Amharic (Ethiopia)",
  "an": "SeAragon",
  "ang": "Senyesemane sa Khale",
  "anp": "Angika",
  "apa": "Puo ea Apache",
  "ar": "Searabia",
  "ar_001": "Searabia sa Sejoale-joale sa Maemo",
  "ar_AE": "Searabia (United Arab Emirates)",
  "ar_BH": "Searabia (Bahrain)",
  "ar_DJ": "Searabia (Djibouti)",
  "ar_DZ": "Searabia (Algeria)",
  "ar_EG": "Searabia (Egypt)",
  "ar_EH": "Searabia (Sahara Bophirimela)",
  "ar_ER": "Searabia (Eritrea)",
  "ar_IL": "Searabia (Israel)",
  "ar_IQ": "Searabia (Iraq)",
  "ar_JO": "Searabia (Jordan)",
  "ar_KM": "Searabia (Comoros)",
  "ar_KW": "Searabia (Kuwait)",
  "ar_LB": "Searabia (Lebanon)",
  "ar_LY": "Searabia (Libya)",
  "ar_MA": "Searabia (Morocco)",
  "ar_MR": "Searabia (Mauritania)",
  "ar_OM": "Searabia (Oman)",
  "ar_PS": "Searabia (Libaka tsa Palestina)",
  "ar_QA": "Searabia (Qatar)",
  "ar_SA": "Searabia (Saudi Arabia)",
  "ar_SD": "Searabia (Sudan)",
  "ar_SO": "Searabia (Somalia)",
  "ar_SS": "Searabia (South Sudan)",
  "ar_SY": "Searabia (Syria)",
  "ar_TD": "Searabia (Chad)",
  "ar_TN": "Searabia (Tunisia)",
  "ar_YE": "Searabia (Yemen)",
  "arc": "Searame",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Searabia sa Algeria",
  "ars": "Searabia sa Najdi",
  "art": "Puo ea Maiketsetso",
  "arw": "Arawak",
  "ary": "Searabia sa Morocco",
  "arz": "Searabia sa Baegepeta",
  "as": "Seassamese",
  "as_IN": "Seassamese (India)",
  "asa": "Asu",
  "ase": "Puo ea Matsoho ea Amerika",
  "ast": "Setsebi",
  "ath": "Puo ea Athapascan",
  "aus": "Puo ea Australia",
  "av": "Sevarvar",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Seazerbaijani (Azerbaijan)",
  "az_Arab": "Azerbaijani (Searabia)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Seazerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Selatine)",
  "az_Latn_AZ": "Azerbaijani (Selatine, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bad": "Banda",
  "bai": "Puo ea Bamileke",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "SeBavaria",
  "bas": "Basaa",
  "bat": "Puo ea Baltic",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Sebelarusi",
  "be_BY": "Sebelarusi (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Sebulgaria",
  "bg_BG": "Sebulgaria (Bulgaria)",
  "bgn": "Balochi Bophirimela",
  "bh": "Se-bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Selatine)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bangla",
  "bn_BD": "Sebengali (Bangladesh)",
  "bn_IN": "Sebengali (India)",
  "bnt": "Bantu",
  "bo": "Setibetan",
  "bo_CN": "Setibetan (China)",
  "bo_IN": "Setibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Sebreton",
  "br_FR": "Breton (Fora)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Sebosnia",
  "bs_BA": "Sebosnia (Bosnia le Herzegovina)",
  "bs_Cyrl": "Sebosnia (Cyrillic)",
  "bs_Cyrl_BA": "Sebosnia (Cyrillic, Bosnia le Herzegovina)",
  "bs_Latn": "Sebosnia (Selatine)",
  "bs_Latn_BA": "Sebosnia (Selatine, Bosnia le Herzegovina)",
  "bss": "Akoose",
  "btk": "Mabatak",
  "bua": "Buriat",
  "bug": "SeBuginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "SeCatalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "SeCatalan (Spain)",
  "ca_FR": "SeCatalan (France)",
  "ca_IT": "SeCatalan (Italy)",
  "cad": "Caddo",
  "cai": "Puo ea India ea Amerika Bohareng",
  "car": "Caribbean",
  "cau": "Puo ea Caucasus",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cel": "Puo ea Macelt",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Se-Chuukese",
  "chm": "Se-Mari",
  "chn": "Chinook Jargon",
  "cho": "Khetho",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Kurdish e Bohareng",
  "cmc": "Puo ea Chamic",
  "co": "Corsican",
  "cop": "Sekoptiki",
  "cpe": "Secreole se thehiloeng Senyesemane kapa Pidgin",
  "cpf": "Secreole se thehiloeng Fora kapa Pidgin",
  "cpp": "Secreole se thehiloeng Sepotoketsi kapa Pidgin",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Seturkey sa Crimea",
  "crp": "Creole kapa Pidgin",
  "crs": "Seselwa Creole French",
  "cs": "Czech",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "Seslav sa Kereke",
  "cus": "Puo ea Cushitic",
  "cv": "Chuvash",
  "cy": "Se-Welsh",
  "cy_GB": "Se-Welsh (United Kingdom)",
  "da": "Sedanishe",
  "da_DK": "Sedanishe (Denmark)",
  "da_GL": "Sedanishe (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Sejeremane",
  "de_AT": "Sejeremane (Austria)",
  "de_BE": "Sejeremane (Belgium)",
  "de_CH": "Sejeremane (Switzerland)",
  "de_DE": "Sejeremane (Jeremane)",
  "de_LI": "Sejeremane (Liechtenstein)",
  "de_LU": "Sejeremane (Luxembourg)",
  "del": "Delaware",
  "den": "Lekhoba",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Ntja",
  "dra": "Puo ea Dravidian",
  "dsb": "Sesorbia se ka tlase",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Sedache se Bohareng",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Se-Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "SeEwe (Ghana)",
  "ee_TG": "Se-Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emily",
  "egy": "Moegepeta oa boholo-holo",
  "eka": "Ekajuk",
  "el": "Segerike",
  "el_CY": "Segerike (Cyprus)",
  "el_GR": "Segerike (Greece)",
  "elx": "Baelame",
  "en": "Senyesemane",
  "en_AG": "Senyesemane (Antigua & Barbuda)",
  "en_AI": "Senyesemane (Anguilla)",
  "en_AS": "Senyesemane (American Samoa)",
  "en_AU": "Senyesemane (Australia)",
  "en_BB": "Senyesemane (Barbados)",
  "en_BE": "Senyesemane (Belgium)",
  "en_BM": "Senyesemane (Bermuda)",
  "en_BS": "Senyesemane (Bahamas)",
  "en_BW": "Setswana (Botswana)",
  "en_BZ": "Senyesemane (Belize)",
  "en_CA": "Senyesemane (Canada)",
  "en_CC": "Senyesemane (Cocos (Keeling) Islands)",
  "en_CK": "Senyesemane (Lihlekehleke tsa Cook)",
  "en_CM": "Senyesemane (Cameroon)",
  "en_CX": "Senyesemane (Sehlekehleke sa Keresemese)",
  "en_DG": "Senyesemane (Diego Garcia)",
  "en_DM": "Senyesemane (Dominica)",
  "en_Dsrt": "Senyesemane (Deseret)",
  "en_ER": "Senyesemane (Eritrea)",
  "en_FJ": "Senyesemane (Fiji)",
  "en_FK": "Senyesemane (Falkland Islands)",
  "en_FM": "Senyesemane (Micronesia)",
  "en_GB": "Setswana (Aforika Borwa)",
  "en_GD": "Senyesemane (Grenada)",
  "en_GG": "Senyesemane (Guernsey)",
  "en_GH": "Senyesemane (Ghana)",
  "en_GI": "Senyesemane (Gibraltar)",
  "en_GM": "Senyesemane (Gambia)",
  "en_GU": "Senyesemane (Guam)",
  "en_GY": "Senyesemane (Guyana)",
  "en_HK": "Senyesemane (Hong Kong SAR China)",
  "en_IE": "Senyesemane (Ireland)",
  "en_IM": "Senyesemane (Isle of Man)",
  "en_IN": "Senyesemane (India)",
  "en_IO": "Senyesemane (Sebaka sa Leoatle la Indian Indian)",
  "en_JE": "Senyesemane (Jersey)",
  "en_JM": "Senyesemane (Jamaica)",
  "en_KE": "Senyesemane (Kenya)",
  "en_KI": "Senyesemane (Kiribati)",
  "en_KN": "Senyesemane (St. Kitts & Nevis)",
  "en_KY": "Senyesemane (Lihlekehleke tsa Cayman)",
  "en_LC": "Senyesemane (St. Lucia)",
  "en_LR": "Senyesemane (Liberia)",
  "en_LS": "Senyesemane (Lesotho)",
  "en_MG": "Senyesemane (Madagascar)",
  "en_MH": "Senyesemane (Marshall Islands)",
  "en_MO": "Senyesemane (Macau SAR China)",
  "en_MP": "Senyesemane (Lihlekehleke tsa Mariana Leboea)",
  "en_MS": "Senyesemane (Montserrat)",
  "en_MT": "Senyesemane (Malta)",
  "en_MU": "Senyesemane (Mauritius)",
  "en_MW": "Senyesemane (Malawi)",
  "en_MY": "Senyesemane (Malaysia)",
  "en_NA": "Senyesemane (Namibia)",
  "en_NF": "Senyesemane (Sehlekehleke sa Norfolk)",
  "en_NG": "Senyesemane (Nigeria)",
  "en_NR": "Senyesemane (Nauru)",
  "en_NU": "Senyesemane (Niue)",
  "en_NZ": "Senyesemane (New Zealand)",
  "en_PG": "Senyesemane (Papua New Guinea)",
  "en_PH": "Senyesemane (Philippines)",
  "en_PK": "Senyesemane (Pakistan)",
  "en_PN": "Senyesemane (Pitcairn Islands)",
  "en_PR": "Senyesemane (Puerto Rico)",
  "en_PW": "Senyesemane (Palau)",
  "en_RW": "Senyesemane (Rwanda)",
  "en_SB": "Senyesemane (Solomon Islands)",
  "en_SC": "Senyesemane (Seychelles)",
  "en_SD": "Senyesemane (Sudan)",
  "en_SG": "Senyesemane (Singapore)",
  "en_SH": "Senyesemane (St. Helena)",
  "en_SL": "Senyesemane (Sierra Leone)",
  "en_SS": "Senyesemane (South Sudan)",
  "en_SX": "Senyesemane (Sint Maarten)",
  "en_SZ": "Senyesemane (Swaziland)",
  "en_TC": "Senyesemane (Lihlekehleke tsa Turks & Caicos)",
  "en_TK": "Senyesemane (Tokelau)",
  "en_TO": "Senyesemane (Tonga)",
  "en_TT": "Senyesemane (Trinidad & Tobago)",
  "en_TV": "Senyesemane (Tuvalu)",
  "en_TZ": "Senyesemane (Tanzania)",
  "en_UG": "Senyesemane (Uganda)",
  "en_UM": "Senyesemane (U.S. Outlying Islands)",
  "en_US": "Setswana (Aforika Borwa)",
  "en_VC": "Senyesemane (St. Vincent & Grenadines)",
  "en_VG": "Senyesemane (British Virgin Islands)",
  "en_VI": "Senyesemane (U.S. Virgin Islands)",
  "en_VU": "Senyesemane (Vanuatu)",
  "en_WS": "Senyesemane (Samoa)",
  "en_ZA": "Setswana (Aforika Borwa)",
  "en_ZM": "Senyesemane (Zambia)",
  "en_ZW": "Senyesemane (Zimbabwe)",
  "enm": "Senyesemane sa Middle",
  "eo": "Seesperanto",
  "es": "Sepanishe",
  "es_419": "Sepanishe ea Latin America",
  "es_AR": "Sepanish (Argentina)",
  "es_BO": "Sepanish (Bolivia)",
  "es_CL": "Sepanish (Chile)",
  "es_CO": "Sepanishe (Colombia)",
  "es_CR": "Sepanish (Costa Rica)",
  "es_CU": "Sepanishe (Cuba)",
  "es_DO": "Sepanish (Rephabliki ea Dominican)",
  "es_EA": "Sepanish (Ceuta & Melilla)",
  "es_EC": "Sepanish (Ecuador)",
  "es_ES": "Sepanish (Spain)",
  "es_GQ": "Sepanishe (Guinea ea Equatorial)",
  "es_GT": "Sepanishe (Guatemala)",
  "es_HN": "Sepanish (Honduras)",
  "es_IC": "Sepanish (Lihlekehleke tsa Canary)",
  "es_MX": "Sepanish (Mexico)",
  "es_NI": "Sepanishe (Nicaragua)",
  "es_PA": "Sepanish (Panama)",
  "es_PE": "Sepanish (Peru)",
  "es_PH": "Sepanish (Philippines)",
  "es_PR": "Sepanish (Puerto Rico)",
  "es_PY": "Sepanish (Paraguay)",
  "es_SV": "Sepanishe (El Salvador)",
  "es_US": "Sepanishe (United States)",
  "es_UY": "Sepanish (Uruguay)",
  "es_VE": "Sepanishe (Venezuela)",
  "esu": "Yupik e Bohareng",
  "et": "Seestonia",
  "et_EE": "Seestonia (Estonia)",
  "eu": "Se-basque",
  "eu_ES": "Se-basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Sepersia",
  "fa_AF": "Sepersia (Afghanistan)",
  "fa_IR": "Sepersia (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fula",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Sefinnishe",
  "fi_FI": "Sefinnishe (Finland)",
  "fil": "Sefilipino",
  "fit": "Tornedalen Sefinnishe",
  "fiu": "Puo ea Finno-Ugrian",
  "fj": "Sefijian",
  "fo": "Sefaroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Sefora",
  "fr_BE": "Sefora (Belgium)",
  "fr_BF": "Sefora (Burkina Faso)",
  "fr_BI": "Sefora (Burundi)",
  "fr_BJ": "Sefora (Benin)",
  "fr_BL": "Sefora (St. Barthélemy)",
  "fr_CA": "Sefora (Canada)",
  "fr_CD": "Sefora (Congo - Kinshasa)",
  "fr_CF": "French (Central African Republic)",
  "fr_CG": "Sefora (Congo - Brazzaville)",
  "fr_CH": "Sefora (Switzerland)",
  "fr_CI": "Sefora (Côte d'Ivoire)",
  "fr_CM": "Sefora (Cameroon)",
  "fr_DJ": "Sefora (Djibouti)",
  "fr_DZ": "Sefora (Algeria)",
  "fr_FR": "Sefora (France)",
  "fr_GA": "Sefora (Gabon)",
  "fr_GF": "Sefora (French Guiana)",
  "fr_GN": "Sefora (Guinea)",
  "fr_GP": "Sefora (Guadeloupe)",
  "fr_GQ": "Sefora (Equatorial Guinea)",
  "fr_HT": "Sefora (Haiti)",
  "fr_KM": "Sefora (Li-Comoros)",
  "fr_LU": "Sefora (Luxembourg)",
  "fr_MA": "Sefora (Morocco)",
  "fr_MC": "Sefora (Monaco)",
  "fr_MF": "Sefora (St. Martin)",
  "fr_MG": "Sefora (Madagascar)",
  "fr_ML": "Sefora (Mali)",
  "fr_MQ": "Sefora (Martinique)",
  "fr_MR": "Sefora (Mauritania)",
  "fr_MU": "Sefora (Mauritius)",
  "fr_NC": "Sefora (New Caledonia)",
  "fr_NE": "Sefora (Niger)",
  "fr_PF": "Sefora (French Polynesia)",
  "fr_PM": "Sefora (St. Pierre & Miquelon)",
  "fr_RE": "Sefora (Réunion)",
  "fr_RW": "Sefora (Rwanda)",
  "fr_SC": "Sefora (Seychelles)",
  "fr_SN": "Sefora (Senegal)",
  "fr_SY": "Sefora (Syria)",
  "fr_TD": "Sefora (Chad)",
  "fr_TG": "Sefora (Togo)",
  "fr_TN": "Sefora (Tunisia)",
  "fr_VU": "Sefora (Vanuatu)",
  "fr_WF": "Sefora (Wallis & Futuna)",
  "fr_YT": "Sefora (Mayotte)",
  "frc": "Sefora sa Cajun",
  "frm": "Middle French",
  "fro": "Sefora sa Khale",
  "frp": "Searpite",
  "frr": "Frisian Leboea",
  "frs": "Frisian Bochabela",
  "fur": "Mofriia",
  "fy": "Bophirimela ba Frisian",
  "fy_NL": "Frisian Bophirimela (Netherlands)",
  "ga": "Ireland",
  "ga_IE": "Se-Ireland (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Sechaena sa Gan",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Gaelic ea Scotland",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gem": "Puo ea Sejeremane",
  "gez": "Geez",
  "gil": "Se-Gilbertese",
  "gl": "Segalicia",
  "gl_ES": "Se-Galicia (Spain)",
  "glk": "Gilaki",
  "gmh": "Sejeremane se Bohareng",
  "gn": "Se-guarani",
  "goh": "Sejeremane sa Khale",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Se-Gothic",
  "grb": "Grebo",
  "grc": "Segerike sa boholo-holo",
  "gsw": "Sejeremane sa Switzerland",
  "gu": "Segujarati",
  "gu_IN": "Se-Gujarati (India)",
  "guc": "Tsela",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Sehausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Selatine)",
  "ha_Latn_GH": "Hausa (Selatine, Ghana)",
  "ha_Latn_NE": "Hausa (Selatine, Niger)",
  "ha_Latn_NG": "Hausa (Selatine, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Machaena a Hakka",
  "haw": "Sehawaii",
  "he": "Seheberu",
  "he_IL": "Seheberu (Israel)",
  "hi": "Sehindi",
  "hi_IN": "Sehindi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Bahethe",
  "hmn": "SeHmong",
  "ho": "Hiri Motu",
  "hr": "Kroatia",
  "hr_BA": "Kroatia (Bosnia le Herzegovina)",
  "hr_HR": "Secroatia (Croatia)",
  "hsb": "Sesorbia se Holimo",
  "hsn": "Xiang Chinese",
  "ht": "Secreole sa Haiti",
  "hu": "Sehungary",
  "hu_HU": "Sehungary (Hungary)",
  "hup": "Hupa",
  "hy": "Searmenia",
  "hy_AM": "Searmenia (Armenia)",
  "hz": "Herero",
  "ia": "Se-interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Seindonesia",
  "id_ID": "Seindonesia (Indonesia)",
  "ie": "Se-interlingue",
  "ig": "Segbo",
  "ig_NG": "Se-Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (Chaena)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Puo ea Indic",
  "ine": "Puo ea Indo-Europe",
  "inh": "Ingush",
  "io": "Ido",
  "ira": "Puo ea Irani",
  "iro": "Puo ea Iroquoian",
  "is": "SeIcelandic",
  "is_IS": "Se-Icelandic (Iceland)",
  "it": "Setaliana",
  "it_CH": "Setaliana (Switzerland)",
  "it_IT": "Setaliana (Italy)",
  "it_SM": "Setaliana (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Sejapane",
  "ja_JP": "Sejapane (Japane)",
  "jam": "Jamaican Creole Senyesemane",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judao-Persia",
  "jrb": "Judeo-Searabia",
  "jut": "Jutish",
  "jv": "Sejava",
  "ka": "Segeorgia",
  "ka_GE": "SeGeorgia (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Sekongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Puo ea Khoisan",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Sekikuyu",
  "ki_KE": "Sekikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Sekazakh",
  "kk_Cyrl": "Sekazakh (Cyrillic)",
  "kk_Cyrl_KZ": "SeKazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "SeKazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Khalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodia)",
  "kmb": "Kimbundu",
  "kn": "Sekannada",
  "kn_IN": "Sekannada (India)",
  "ko": "Sekorea",
  "ko_KP": "Sekorea (Korea Leboea)",
  "ko_KR": "Sekorea (Korea Boroa)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Sekosrae",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Sekrio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Sekashmiri (Searabia)",
  "ks_Arab_IN": "Sekashmiri (Searabia, India)",
  "ks_IN": "Sekashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Setsebi",
  "ku": "Sekurdi",
  "kum": "Mofumahali Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Sekyrgyz",
  "ky_Cyrl": "Sekyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Sekyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Sekyrgyz (Kyrgyzstan)",
  "la": "Selatine",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Se-Luxembourg",
  "lb_LU": "Se-Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "SeLigurian",
  "liv": "Livonia",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Selingala",
  "ln_AO": "Selingala (Angola)",
  "ln_CD": "Selingala (Congo - Kinshasa)",
  "ln_CF": "Selingala (Central African Republic)",
  "ln_CG": "Selingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "lou": "Secreole sa Louisiana",
  "loz": "Lozi",
  "lrc": "Luri Leboea",
  "lt": "Se-Lithuania",
  "lt_LT": "Lithuania (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "SeLatvia",
  "lv_LV": "Se-latvia (Latvia)",
  "lzh": "Lingoliloeng tsa China",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Puo ea Austronesia",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Semandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Semalagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "MaIrish a Bohareng",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Se-Marshallese",
  "mi": "Semoriori",
  "mic": "Mi'kmaq",
  "min": "Minangkabau",
  "mis": "Puo e fapaneng",
  "mk": "Semasedonia",
  "mk_MK": "Semasedonia (Masedonia)",
  "mkh": "Puo ea Mon-Khmer",
  "ml": "Semalayalam",
  "ml_IN": "Semalayalam (India)",
  "mn": "Semongolia",
  "mn_Cyrl": "Semongolia (Cyrillic)",
  "mn_Cyrl_MN": "Mongoli (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Puo ea Manobo",
  "mo": "Semoldavia",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Mari ea Bophirimela",
  "ms": "Semalay",
  "ms_BN": "Semalay (Brunei)",
  "ms_Latn": "Semalay (Latin)",
  "ms_Latn_BN": "Semalay (ka Selatine, Brunei)",
  "ms_Latn_MY": "Semalay (Latin, Malaysia)",
  "ms_Latn_SG": "Semalay (Latin, Singapore)",
  "ms_MY": "Semalay (Malaysia)",
  "ms_SG": "Semalay (Singapore)",
  "mt": "Semalta",
  "mt_MT": "Semalta (Malta)",
  "mua": "Mundang",
  "mul": "Lipuo tse ngata",
  "mun": "Puo ea Munda",
  "mus": "@Bonang_m",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Seburmese",
  "my_MM": "Seburmese (Myanmar (Burma))",
  "mye": "Myene",
  "myn": "Puo ea Mayan",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nah": "Senahuatl",
  "nai": "Puo ea Maindia a Amerika Leboea",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Senorway Bokmål",
  "nb_NO": "Senorway Bokmål (Norway)",
  "nb_SJ": "Senorway Bokmål (Svalbard le Jan Mayen)",
  "nd": "Ndebele ea Leboea",
  "nd_ZW": "Ndebele ea Leboea (Zimbabwe)",
  "nds": "Sejeremane se tlase",
  "nds_NL": "Saxon ea Dutch",
  "ne": "Nepali",
  "ne_IN": "Nepali (India)",
  "ne_NP": "Nepali (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Puo ea Niger-Kordofanian",
  "niu": "SeNiue",
  "njo": "Ao Naga",
  "nl": "Sedache",
  "nl_AW": "Sedache (Aruba)",
  "nl_BE": "Sedache (Belgium)",
  "nl_BQ": "Sedache (Netherlands Netherlands)",
  "nl_CW": "Sedache (Curaçao)",
  "nl_NL": "Sedache (Netherlands)",
  "nl_SR": "Sedache (Suriname)",
  "nl_SX": "Sedache (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norway Nynorsk",
  "nn_NO": "Senorway Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Senorway",
  "no_NO": "Senorway (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "N'Ko",
  "nr": "Ndebele ya Borwa",
  "nso": "Sesotho sa Leboa",
  "nub": "Puo ea Nubian",
  "nus": "Nuer",
  "nv": "Senavajo",
  "nwc": "Newari ea khale",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Se-occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Seoromo (Ethiopia)",
  "om_KE": "Se-Oromo (Kenya)",
  "or": "Odia",
  "or_IN": "Se-Oriya (India)",
  "os": "SeOssetiki",
  "os_GE": "SeOssetic (Georgia)",
  "os_RU": "SeOssetic (Russia)",
  "osa": "Ho sebedisa",
  "ota": "Seturkey sa Ottoman",
  "oto": "Puo ea Otomian",
  "pa": "Sepunjabi",
  "pa_Arab": "Sepunjabi (Searabia)",
  "pa_Arab_PK": "Sepunjabi (Searabia, Pakistan)",
  "pa_Guru": "Sepunjabi (Gurmukhi)",
  "pa_Guru_IN": "Sepunjabi (Gurmukhi, India)",
  "pa_IN": "Sepunjabi (India)",
  "pa_PK": "Sepunjabi (Pakistan)",
  "paa": "Puo ea Sepapua",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Sepapiamento",
  "pau": "SePalauan",
  "pcd": "Picard",
  "pcm": "Pidgin ea Nigeria",
  "pdc": "Sejeremane sa Pennsylvania",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine Sejeremane",
  "phi": "Puo ea Philippines",
  "phn": "Mofenisia",
  "pi": "Pali",
  "pl": "Sepolishe",
  "pl_PL": "Sepolishe (Poland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "pra": "Puo ea Prakrit",
  "prg": "Prussia",
  "pro": "Provençal ea khale",
  "ps": "Pashto",
  "ps_AF": "Se-Pashto (Afghanistan)",
  "pt": "Sepotoketsi",
  "pt_AO": "Sepotoketsi (Angola)",
  "pt_BR": "Sepotoketsi (Brazil)",
  "pt_CV": "Sepotoketsi (Cape Verde)",
  "pt_GW": "Sepotoketsi (Guinea-Bissau)",
  "pt_MO": "Sepotoketsi (Macau SAR China)",
  "pt_MZ": "Sepotoketsi (Mozambique)",
  "pt_PT": "Sepotoketsi (Portugal)",
  "pt_ST": "Sepotoketsi (São Tomé & Príncipe)",
  "pt_TL": "Sepotoketsi (Timor-Leste)",
  "qu": "Sequechua",
  "qu_BO": "Sequechua (Bolivia)",
  "qu_EC": "Sequechua (Ecuador)",
  "qu_PE": "Sequechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Lerato",
  "rif": "Riffian",
  "rm": "Seromani",
  "rm_CH": "Se-Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Serundi (Burundi)",
  "ro": "Seromania",
  "ro_MD": "Seromania (Moldova)",
  "ro_RO": "Seromania (Romania)",
  "roa": "Puo ea Lerato",
  "rof": "Rombo",
  "rom": "Seromani",
  "root": "Motso",
  "rtm": "Rotuman",
  "ru": "Serussia",
  "ru_BY": "Serussia (Belarus)",
  "ru_KG": "Serussia (Kyrgyzstan)",
  "ru_KZ": "Serussia (Kazakhstan)",
  "ru_MD": "Serussia (Moldova)",
  "ru_RU": "Serussia (Russia)",
  "ru_UA": "Serussia (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Searomani",
  "rw": "Sekinyarwanda",
  "rw_RW": "Sekinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sai": "Puo ea India ea Amerika Boroa",
  "sal": "Puo ea Salishan",
  "sam": "Searame sa Sesamaria",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sesindhi",
  "sd_Deva": "Se-Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "Kurdish e ka boroa",
  "se": "Sami sa Leboea",
  "se_FI": "Sami sa Leboea (Finland)",
  "se_NO": "Sami sa Leboea (Norway)",
  "se_SE": "Sami sa Leboea (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Puo ea Semiti",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgn": "Puo ea Matsoho",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatia",
  "sh_BA": "Serbo-Croatia (Bosnia le Herzegovina)",
  "shi": "Shilha",
  "shi_Latn": "Shilha (Selatine)",
  "shi_Tfng": "Distancia Mafikeng-Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Searabia sa Chadian",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Puo ea Siouan",
  "sit": "Puo ea Sino-Tibetan",
  "sk": "Seslovak",
  "sk_SK": "Seslovak (Slovakia)",
  "sl": "Seslovenia",
  "sl_SI": "Seslovenia (Slovenia)",
  "sla": "Puo ea Slavic",
  "sli": "Silesian e ka tlase",
  "sly": "Selayar",
  "sm": "Sesamoa",
  "sma": "Sami e ka Boroa",
  "smi": "Puo ea Sami",
  "smj": "Lule Sami",
  "smn": "Sami Sami",
  "sms": "Skolt Sami",
  "sn": "Seshona",
  "sn_ZW": "Seshona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somali",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "E tiisitsoe",
  "son": "Songhai",
  "sq": "Sealbania",
  "sq_AL": "Sealbania (Albania)",
  "sq_MK": "Sealbania (Macedonia)",
  "sq_XK": "Sealbania (Kosovo)",
  "sr": "Seserbia",
  "sr_BA": "Seserbia (Bosnia le Herzegovina)",
  "sr_Cyrl": "Seserbia (Cyrillic)",
  "sr_Cyrl_BA": "Seserbia (Cyrillic, Bosnia le Herzegovina)",
  "sr_Cyrl_ME": "Seserbia (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Seserbia (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Seserbia (Cyrillic, Kosovo)",
  "sr_Latn": "Seserbia (Selatine)",
  "sr_Latn_BA": "Seserbia (Selatine, Bosnia le Herzegovina)",
  "sr_Latn_ME": "Seserbia (Selatine, Montenegro)",
  "sr_Latn_RS": "Seserbia (Selatine, Serbia)",
  "sr_Latn_XK": "Seserbia (Selatine, Kosovo)",
  "sr_ME": "Seserbia (Montenegro)",
  "sr_RS": "Seserbia (Serbia)",
  "sr_XK": "Seserbia (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssa": "Puo ea Nilo-Sahara",
  "ssy": "Saho",
  "st": "Sesotho",
  "stq": "Saterland Frisian",
  "su": "Sesundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumeria",
  "sv": "Seswedishe",
  "sv_AX": "Seswedishe (Islandsland Islands)",
  "sv_FI": "Seswedishe (Finland)",
  "sv_SE": "Seswedishe (Sweden)",
  "sw": "Seswahili",
  "sw_CD": "Congo Swahili",
  "sw_KE": "Seswahili (Kenya)",
  "sw_TZ": "Seswahili (Tanzania)",
  "sw_UG": "Seswahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Sesyria sa khale",
  "syr": "Sesyria",
  "szl": "Silesia",
  "ta": "Setamile",
  "ta_IN": "Setamil (India)",
  "ta_LK": "Setamil (Sri Lanka)",
  "ta_MY": "Setamil (Malaysia)",
  "ta_SG": "Setamil (Singapore)",
  "tai": "Puo ea Tai",
  "tcy": "Tulu",
  "te": "Setelugu",
  "te_IN": "Setelugu (India)",
  "tem": "Nako",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Setetum",
  "tg": "Se-tajik",
  "th": "Sethai",
  "th_TH": "Sethai (Thailand)",
  "ti": "Setigrinya",
  "ti_ER": "Setigrinya (Eritrea)",
  "ti_ET": "Setigrinya (Ethiopia)",
  "tig": "Tiger",
  "tiv": "Tiv",
  "tk": "MaTurkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Setagalog",
  "tl_PH": "Setagalog (Philippines)",
  "tlh": "SeKlingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Setongan",
  "to_TO": "Setongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Setok Pisin",
  "tr": "Seturkey",
  "tr_CY": "Seturkey (Cyprus)",
  "tr_TR": "Seturkey (Turkey)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonia",
  "tsi": "Tsimshian",
  "tt": "Setatare",
  "ttt": "Mamosleme Tat",
  "tum": "Tumbuka",
  "tup": "Puo ea Tupi",
  "tut": "Puo ea Sealtaic",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Setahiti",
  "tyv": "Setuvinian",
  "tzm": "Tamazight ea Bohareng ba Atlas",
  "udm": "Tlhompho",
  "ug": "SeUghur",
  "ug_Arab": "SeUghur (Searabia)",
  "ug_Arab_CN": "Uyghur (Searabia, Chaena)",
  "ug_CN": "Uyghur (China)",
  "uga": "SeUgarit",
  "uk": "Seukraine",
  "uk_UA": "Seukraine (Ukraine)",
  "umb": "Umbundu",
  "und": "Puo e sa Tsejoeng",
  "ur": "Seurdu",
  "ur_IN": "Seurdu (India)",
  "ur_PK": "Seurdu (Pakistan)",
  "uz": "Seuzbek",
  "uz_AF": "SeUzbek (Afghanistan)",
  "uz_Arab": "SeUzbek (Searabia)",
  "uz_Arab_AF": "Uzbek (Searabia, Afghanistan)",
  "uz_Cyrl": "SeUzbek (Cyrillic)",
  "uz_Cyrl_UZ": "SeUzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "SeUzbek (Selatine)",
  "uz_Latn_UZ": "SeUzbek (Selatine, Uzbekistan)",
  "uz_UZ": "SeUzbek (Uzbekistan)",
  "vai": "Monghali Vai",
  "vai_Latn": "Se-Vai (Selatine)",
  "ve": "SeVenda",
  "vec": "Se-Venetian",
  "vep": "Veps",
  "vi": "Sevietnam",
  "vi_VN": "SeVietnam (Vietnam)",
  "vls": "Flemish Bophirimela",
  "vmf": "Main-Franconia",
  "vo": "Sekolo sa Volapük",
  "vot": "E mahlonoko",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wak": "Puo ea Wakashan",
  "wal": "Mohlankana",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Puo ea Sesorbia",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Sexhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "SeYiddish",
  "yo": "SeYoruba",
  "yo_BJ": "Seyoruba (Benin)",
  "yo_NG": "Seyoruba (Nigeria)",
  "ypk": "Puo ea Yupik",
  "yrl": "Nheengatu",
  "yue": "Se-Cantonese",
  "yue_Hans": "Se-Cantonese (Sechaena se Nolofalitsoeng)",
  "yue_Hant": "Se-Cantonese (Sechaena sa Setso)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Boitumelo",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Tamazight e tloaelehileng ea Morocco",
  "zh": "Sechaena",
  "zh_CN": "Sechaena (China)",
  "zh_HK": "Se-china (Hong Kong SAR China)",
  "zh_Hans": "Sechaena (se Nolofalitsoeng)",
  "zh_Hans_CN": "Sechaena (se Nolofalitsoeng, Chaena)",
  "zh_Hans_HK": "Se-china (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Sechaena (Simplified, Singapore)",
  "zh_Hant": "Sechaena (sa Setso)",
  "zh_Hant_HK": "Se-china (Setso, Hong Kong SAR China)",
  "zh_Hant_MO": "Sechaena (Setso, Macau SAR China)",
  "zh_Hant_TW": "Sechaena (Setso, Taiwan)",
  "zh_MO": "Se-china (Macau SAR China)",
  "zh_SG": "Sechaena (Singapore)",
  "zh_TW": "Sechaena (Taiwan)",
  "znd": "Zande",
  "zu": "Sezulu",
  "zu_ZA": "Sezulu (Afrika Borwa)",
  "zun": "Zuni",
  "zxx": "Ha ho litaba tsa puo",
  "zza": "Zaza"
};
