const names = {
  "001": "mund",
  "002": "Africa",
  "003": "America dal Nord",
  "005": "America dal Sid",
  "009": "Oceania",
  "011": "Africa dal Vest",
  "013": "America Centrala",
  "014": "Africa da l’Ost",
  "015": "Africa dal Nord",
  "017": "Africa Centrala",
  "018": "Africa Meridiunala",
  "019": "America dal Nord, America Centrala ed America dal Sid",
  "029": "Caribica",
  "030": "Asia da l’Ost",
  "034": "Asia dal Sid",
  "035": "Asia dal Sidost",
  "039": "Europa dal Sid",
  "053": "Australia e Nova Zelanda",
  "054": "Melanesia",
  "057": "Regiun Micronesica",
  "061": "Polinesia",
  "142": "Asia",
  "143": "Asia Centrala",
  "145": "Asia dal Vest",
  "150": "Europa",
  "151": "Europa Orientala",
  "154": "Europa dal Nord",
  "155": "Europa dal Vest",
  "419": "America Latina",
  "AD": "Andorra",
  "AE": "Emirats Arabs Unids",
  "AF": "Afghanistan",
  "AG": "Antigua e Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antillas Ollandaisas",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentinia",
  "AS": "Samoa Americana",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Inslas Aland",
  "AZ": "Aserbaidschan",
  "Arab": "arab",
  "Armi": "arameic imperial",
  "Armn": "armen",
  "Avst": "avestic",
  "BA": "Bosnia ed Erzegovina",
  "BB": "Barbados",
  "BD": "Bangladesch",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Son Barthélemy",
  "BM": "Bermudas",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Brasilia",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Insla Bouvet",
  "BW": "Botswana",
  "BY": "Bielorussia",
  "BZ": "Belize",
  "Bali": "balinais",
  "Batk": "batak",
  "Beng": "bengal",
  "Blis": "simbols da Bliss",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "scrittira da Braille",
  "Bugi": "buginais",
  "Buhd": "buhid",
  "CA": "Canada",
  "CC": "Inslas Cocos",
  "CD": "Republica Democratica dal Congo",
  "CF": "Republica Centralafricana",
  "CG": "Congo",
  "CH": "Svizra",
  "CI": "Costa d’Ivur",
  "CK": "Inslas Cook",
  "CL": "Chile",
  "CM": "Camerun",
  "CN": "China",
  "CO": "Columbia",
  "CR": "Costa Rica",
  "CS": "Serbia e Montenegro",
  "CU": "Cuba",
  "CV": "Cap Verd",
  "CW": "Curaçao",
  "CX": "Insla da Christmas",
  "CY": "Cipra",
  "CZ": "Republica Tscheca",
  "Cakm": "chakma",
  "Cans": "simbols autoctons canadais unifitgads",
  "Cari": "carian",
  "Cham": "cham",
  "Cher": "cherokee",
  "Cirt": "cirth",
  "Copt": "coptic",
  "Cprt": "cipriot",
  "Cyrl": "cirillic",
  "Cyrs": "slav da baselgia vegl",
  "DD": "Germania da l'Ost",
  "DE": "Germania",
  "DJ": "Dschibuti",
  "DK": "Danemarc",
  "DM": "Dominica",
  "DO": "Republica Dominicana",
  "DZ": "Algeria",
  "Deva": "devanagari",
  "Dsrt": "deseret",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egipta",
  "EH": "Sahara Occidentala",
  "ER": "Eritrea",
  "ES": "Spagna",
  "ET": "Etiopia",
  "EU": "Uniun europeica",
  "Egyd": "egipzian demotic",
  "Egyh": "egipzian ieratic",
  "Egyp": "ieroglifas egipzianas",
  "Ethi": "etiopic",
  "FI": "Finlanda",
  "FJ": "Fidschi",
  "FK": "Inslas dal Falkland",
  "FM": "Micronesia",
  "FO": "Inslas Feroe",
  "FR": "Frantscha",
  "FX": "Frantscha Metropolitana",
  "GA": "Gabun",
  "GB": "Reginavel Unì",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Guyana Franzosa",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grönlanda",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Guinea Equatoriala",
  "GR": "Grezia",
  "GS": "Georgia dal Sid e las Inslas Sandwich dal Sid",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "kutsuri",
  "Geor": "georgian",
  "Glag": "glagolitic",
  "Goth": "gotic",
  "Grek": "grec",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "Regiun d’administraziun speziala da Hongkong, China",
  "HM": "Inslas da Heard e da McDonald",
  "HN": "Honduras",
  "HR": "Croazia",
  "HT": "Haiti",
  "HU": "Ungaria",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanunoo",
  "Hans": "scrittira chinaisa simplifitgada",
  "Hant": "scrittira chinaisa tradiziunala",
  "Hebr": "ebraic",
  "Hira": "hiragana",
  "Hmng": "pahawn hmong",
  "Hrkt": "katanaka u hiragana",
  "Hung": "ungarais vegl",
  "ID": "Indonesia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Insla da Man",
  "IN": "India",
  "IO": "Territori Britannic en l’Ocean Indic",
  "IQ": "Irac",
  "IR": "Iran",
  "IS": "Islanda",
  "IT": "Italia",
  "Inds": "indus",
  "Ital": "italic vegl",
  "JE": "Jersey",
  "JM": "Giamaica",
  "JO": "Jordania",
  "JP": "Giapun",
  "Java": "javanais",
  "Jpan": "giapunais",
  "KE": "Kenia",
  "KG": "Kirghisistan",
  "KH": "Cambodscha",
  "KI": "Kiribati",
  "KM": "Comoras",
  "KN": "Saint Kitts e Nevis",
  "KP": "Corea dal Nord",
  "KR": "Corea dal Sid",
  "KW": "Kuwait",
  "KY": "Inslas Cayman",
  "KZ": "Kasachstan",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharoshthi",
  "Khmr": "khmer/cambodschan",
  "Knda": "kannada",
  "Kore": "corean",
  "Kthi": "kaithi",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lituania",
  "LU": "Luxemburg",
  "LV": "Lettonia",
  "LY": "Libia",
  "Lana": "lanna",
  "Laoo": "laot",
  "Latf": "latin (scrittira gotica)",
  "Latg": "latin (scrittira gaelica)",
  "Latn": "latin",
  "Lepc": "lepcha",
  "Limb": "limbu",
  "Lina": "linear A",
  "Linb": "linear B",
  "Lyci": "lichic",
  "Lydi": "lidic",
  "MA": "Maroc",
  "MC": "Monaco",
  "MD": "Moldavia",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Inslas da Marshall",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Regiun d’administraziun speziala Macao, China",
  "MP": "Inslas Mariannas dal Nord",
  "MQ": "Martinique",
  "MR": "Mauretania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldivas",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaisia",
  "MZ": "Mosambic",
  "Mand": "mandaic",
  "Mani": "manicheic",
  "Maya": "ieroglifas maya",
  "Mero": "meroitic",
  "Mlym": "malaisian",
  "Mong": "mongolic",
  "Moon": "moon",
  "Mtei": "meetei mayek",
  "Mymr": "burmais",
  "NA": "Namibia",
  "NC": "Nova Caledonia",
  "NE": "Niger",
  "NF": "Insla Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Pajais Bass",
  "NO": "Norvegia",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Zona neutrala",
  "NU": "Niue",
  "NZ": "Nova Zelanda",
  "Nkoo": "n’ko",
  "OM": "Oman",
  "Ogam": "ogham",
  "Olck": "ol chiki",
  "Orkh": "orkhon",
  "Orya": "oriya",
  "Osma": "osman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Polinesia Franzosa",
  "PG": "Papua Nova Guinea",
  "PH": "Filippinas",
  "PK": "Pakistan",
  "PL": "Pologna",
  "PM": "Saint Pierre e Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Territori Palestinais",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguai",
  "Perm": "permic vegl",
  "Phag": "phags-pa",
  "Phli": "pahlavi dad inscripziuns",
  "Phlp": "pahlavi da psalms",
  "Phlv": "pahlavi da cudeschs",
  "Phnx": "fenizian",
  "Plrd": "fonetica da Pollard",
  "Prti": "partic dad inscripziuns",
  "QA": "Katar",
  "QO": "Oceania Periferica",
  "RE": "Réunion",
  "RO": "Rumenia",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Ruanda",
  "Rjng": "rejang",
  "Roro": "rongorongo",
  "Runr": "runic",
  "SA": "Arabia Saudita",
  "SB": "Salomonas",
  "SC": "Seychellas",
  "SD": "Sudan",
  "SE": "Svezia",
  "SG": "Singapur",
  "SH": "Sontg’Elena",
  "SI": "Slovenia",
  "SJ": "Svalbard e Jan Mayen",
  "SK": "Slovachia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Sudan dal Sid",
  "ST": "São Tomé e Principe",
  "SU": "Uniun Sovietica",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Swaziland",
  "Samr": "samaritan",
  "Sara": "sarati",
  "Saur": "saurashtra",
  "Sgnw": "lingua da segns",
  "Shaw": "shavian",
  "Sinh": "singalais",
  "Sund": "sundanais",
  "Sylo": "syloti nagri",
  "Syrc": "siric",
  "Syre": "siric estrangelo",
  "Syrj": "siric dal vest",
  "Syrn": "siric da l’ost",
  "TC": "Inslas Turks e Caicos",
  "TD": "Tschad",
  "TF": "Territoris Franzos Meridiunals",
  "TG": "Togo",
  "TH": "Tailanda",
  "TJ": "Tadschikistan",
  "TK": "Tokelau",
  "TL": "Timor da l’Ost",
  "TM": "Turkmenistan",
  "TN": "Tunesia",
  "TO": "Tonga",
  "TR": "Tirchia",
  "TT": "Trinidad e Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansania",
  "Tagb": "tagbanwa",
  "Tale": "tai le",
  "Talu": "tai lue",
  "Taml": "tamil",
  "Tavt": "tai viet",
  "Telu": "telugu",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagalog",
  "Thaa": "thaana",
  "Thai": "tailandais",
  "Tibt": "tibetan",
  "UA": "Ucraina",
  "UG": "Uganda",
  "UM": "Inslas pitschnas perifericas dals Stadis Unids da l’America",
  "US": "Stadis Unids da l’America",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "Ugar": "ugaritic",
  "VA": "Citad dal Vatican",
  "VC": "Saint Vincent e las Grenadinas",
  "VE": "Venezuela",
  "VG": "Inslas Virginas Britannicas",
  "VI": "Inslas Virginas Americanas",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vaii",
  "Visp": "alfabet visibel",
  "WF": "Wallis e Futuna",
  "WS": "Samoa",
  "Xpeo": "persian vegl",
  "Xsux": "scrittira a cugn sumeric-accadica",
  "YD": "Republica Democratica Populara da Jemen",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yiii": "yi",
  "ZA": "Africa dal Sid",
  "ZM": "Sambia",
  "ZW": "Simbabwe",
  "ZZ": "Regiun betg encouschenta u nunvalaivla",
  "Zinh": "ertà",
  "Zmth": "notaziun matematica",
  "Zsym": "simbols",
  "Zxxx": "linguas na scrittas",
  "Zyyy": "betg determinà",
  "Zzzz": "scrittira nunenconuschenta u nunvalaivla",
  "aa": "afar",
  "ab": "abchasian",
  "ace": "aceh",
  "ach": "acoli",
  "ada": "andangme",
  "ady": "adygai",
  "ae": "avestic",
  "aeb": "Tunisian Arabic",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibia)",
  "af_ZA": "afrikaans (Africa dal Sid)",
  "afa": "lingua afro-asiatica",
  "afh": "afrihili",
  "agq": "Aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "accadic",
  "akz": "Alabama",
  "ale": "aleutic",
  "alg": "linguas algonchinas",
  "aln": "Gheg Albanian",
  "alt": "altaic dal sid",
  "am": "amaric",
  "am_ET": "amaric (Etiopia)",
  "an": "aragonais",
  "ang": "englais vegl",
  "anp": "angika",
  "apa": "linguas apachas",
  "ar": "arab",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "arab (Emirats Arabs Unids)",
  "ar_BH": "arab (Bahrain)",
  "ar_DJ": "arab (Dschibuti)",
  "ar_DZ": "arab (Algeria)",
  "ar_EG": "arab (Egipta)",
  "ar_EH": "arab (Sahara Occidentala)",
  "ar_ER": "arab (Eritrea)",
  "ar_IL": "arab (Israel)",
  "ar_IQ": "arab (Irac)",
  "ar_JO": "arab (Jordania)",
  "ar_KM": "arab (Comoras)",
  "ar_KW": "arab (Kuwait)",
  "ar_LB": "arab (Libanon)",
  "ar_LY": "arab (Libia)",
  "ar_MA": "arab (Maroc)",
  "ar_MR": "arab (Mauretania)",
  "ar_OM": "arab (Oman)",
  "ar_PS": "arab (Territori Palestinais)",
  "ar_QA": "arab (Katar)",
  "ar_SA": "arab (Arabia Saudita)",
  "ar_SD": "arab (Sudan)",
  "ar_SO": "arab (Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "arab (Siria)",
  "ar_TD": "arab (Tschad)",
  "ar_TN": "arab (Tunesia)",
  "ar_YE": "arab (Jemen)",
  "arc": "arameic",
  "arn": "araucanic",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "art": "lingua artifiziala",
  "arw": "arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "assami",
  "as_IN": "assami (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "asturian",
  "ath": "linguas athapascas",
  "aus": "linguas australianas",
  "av": "avaric",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aymara",
  "az": "aserbeidschanic",
  "az_AZ": "aserbeidschanic (Aserbaidschan)",
  "az_Cyrl": "aserbeidschanic (cirillic)",
  "az_Cyrl_AZ": "aserbeidschanic (cirillic, Aserbaidschan)",
  "az_Latn": "aserbeidschanic (latin)",
  "az_Latn_AZ": "aserbeidschanic (latin, Aserbaidschan)",
  "azb": "South Azerbaijani",
  "ba": "baschkir",
  "bad": "banda",
  "bai": "lingua bamileka",
  "bal": "belutschi",
  "ban": "balinais",
  "bar": "Bavarian",
  "bas": "basaa",
  "bat": "lingua baltica",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "bieloruss",
  "be_BY": "bieloruss (Bielorussia)",
  "bej": "bedscha",
  "bem": "bemba",
  "ber": "berb",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "bulgar",
  "bg_BG": "bulgar (Bulgaria)",
  "bh": "bihari",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latin)",
  "bm_Latn_ML": "bambara (latin, Mali)",
  "bn": "bengal",
  "bn_BD": "bengal (Bangladesch)",
  "bn_IN": "bengal (India)",
  "bnt": "bantu",
  "bo": "tibetan",
  "bo_CN": "tibetan (China)",
  "bo_IN": "tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "breton",
  "br_FR": "breton (Frantscha)",
  "bra": "braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "bosniac",
  "bs_BA": "bosniac (Bosnia ed Erzegovina)",
  "bs_Cyrl": "bosniac (cirillic)",
  "bs_Cyrl_BA": "bosniac (cirillic, Bosnia ed Erzegovina)",
  "bs_Latn": "bosniac (latin)",
  "bs_Latn_BA": "bosniac (latin, Bosnia ed Erzegovina)",
  "bss": "Akoose",
  "btk": "batak",
  "bua": "buriat",
  "bug": "bugi",
  "bum": "Bulu",
  "byn": "blin",
  "byv": "Medumba",
  "ca": "catalan",
  "ca_AD": "catalan (Andorra)",
  "ca_ES": "catalan (Spagna)",
  "ca_FR": "catalan (Frantscha)",
  "ca_IT": "catalan (Italia)",
  "cad": "caddo",
  "cai": "linguas dals Indians da l'America centrala",
  "car": "caribic",
  "cau": "linguas dal Caucasus",
  "cay": "Cayuga",
  "cch": "atsam",
  "ce": "tschetschen",
  "ceb": "cebuano",
  "cel": "linguas celticas",
  "cgg": "Chiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "tschagataic",
  "chk": "chuukais",
  "chm": "mari",
  "chn": "patuà chinook",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cherokee",
  "chy": "cheyenne",
  "ckb": "Central Kurdish",
  "cmc": "linguas chamicas",
  "co": "cors",
  "cop": "coptic",
  "cpe": "creol u pidgin che sa basan sin l'englais",
  "cpf": "creol u pidgin che sa basan sin il franzos",
  "cpp": "creol u pidgin che sa basan sin il portugais",
  "cps": "Capiznon",
  "cr": "cree",
  "crh": "tirc crimean",
  "crp": "creolic u pidgin",
  "cs": "tschec",
  "cs_CZ": "tschec (Republica Tscheca)",
  "csb": "kaschubic",
  "cu": "slav da baselgia",
  "cus": "linguas cuschiticas",
  "cv": "tschuvasch",
  "cy": "kimric",
  "cy_GB": "kimric (Reginavel Unì)",
  "da": "danais",
  "da_DK": "danais (Danemarc)",
  "da_GL": "danais (Grönlanda)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "Taita",
  "day": "dayak",
  "de": "tudestg",
  "de_AT": "tudestg (Austria)",
  "de_BE": "tudestg (Belgia)",
  "de_CH": "tudestg (Svizra)",
  "de_DE": "tudestg (Germania)",
  "de_LI": "tudestg (Liechtenstein)",
  "de_LU": "tudestg (Luxemburg)",
  "del": "delaware",
  "den": "slavey",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "Zarma",
  "doi": "dogri",
  "dra": "lingua dravidica",
  "dsb": "bass sorb",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "ollandais mesaun",
  "dv": "maledivic",
  "dyo": "Jola-Fonyi",
  "dyu": "diula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "ewe",
  "ee_GH": "ewe (Ghana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "egipzian vegl",
  "eka": "ekajuk",
  "el": "grec",
  "el_CY": "grec (Cipra)",
  "el_GR": "grec (Grezia)",
  "elx": "elamitic",
  "en": "englais",
  "en_AG": "englais (Antigua e Barbuda)",
  "en_AI": "englais (Anguilla)",
  "en_AS": "englais (Samoa Americana)",
  "en_AU": "englais (Australia)",
  "en_BB": "englais (Barbados)",
  "en_BE": "englais (Belgia)",
  "en_BM": "englais (Bermudas)",
  "en_BS": "englais (Bahamas)",
  "en_BW": "englais (Botswana)",
  "en_BZ": "englais (Belize)",
  "en_CA": "englais (Canada)",
  "en_CC": "englais (Inslas Cocos)",
  "en_CK": "englais (Inslas Cook)",
  "en_CM": "englais (Camerun)",
  "en_CX": "englais (Insla da Christmas)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "englais (Dominica)",
  "en_ER": "englais (Eritrea)",
  "en_FJ": "englais (Fidschi)",
  "en_FK": "englais (Inslas dal Falkland)",
  "en_FM": "englais (Micronesia)",
  "en_GB": "englais (Reginavel Unì)",
  "en_GD": "englais (Grenada)",
  "en_GG": "englais (Guernsey)",
  "en_GH": "englais (Ghana)",
  "en_GI": "englais (Gibraltar)",
  "en_GM": "englais (Gambia)",
  "en_GU": "englais (Guam)",
  "en_GY": "englais (Guyana)",
  "en_HK": "englais (Regiun d’administraziun speziala da Hongkong, China)",
  "en_IE": "englais (Irlanda)",
  "en_IM": "englais (Insla da Man)",
  "en_IN": "englais (India)",
  "en_IO": "englais (Territori Britannic en l’Ocean Indic)",
  "en_JE": "englais (Jersey)",
  "en_JM": "englais (Giamaica)",
  "en_KE": "englais (Kenia)",
  "en_KI": "englais (Kiribati)",
  "en_KN": "englais (Saint Kitts e Nevis)",
  "en_KY": "englais (Inslas Cayman)",
  "en_LC": "englais (Saint Lucia)",
  "en_LR": "englais (Liberia)",
  "en_LS": "englais (Lesotho)",
  "en_MG": "englais (Madagascar)",
  "en_MH": "englais (Inslas da Marshall)",
  "en_MO": "englais (Regiun d’administraziun speziala Macao, China)",
  "en_MP": "englais (Inslas Mariannas dal Nord)",
  "en_MS": "englais (Montserrat)",
  "en_MT": "englais (Malta)",
  "en_MU": "englais (Mauritius)",
  "en_MW": "englais (Malawi)",
  "en_MY": "englais (Malaisia)",
  "en_NA": "englais (Namibia)",
  "en_NF": "englais (Insla Norfolk)",
  "en_NG": "englais (Nigeria)",
  "en_NR": "englais (Nauru)",
  "en_NU": "englais (Niue)",
  "en_NZ": "englais (Nova Zelanda)",
  "en_PG": "englais (Papua Nova Guinea)",
  "en_PH": "englais (Filippinas)",
  "en_PK": "englais (Pakistan)",
  "en_PN": "englais (Pitcairn)",
  "en_PR": "englais (Puerto Rico)",
  "en_PW": "englais (Palau)",
  "en_RW": "englais (Ruanda)",
  "en_SB": "englais (Salomonas)",
  "en_SC": "englais (Seychellas)",
  "en_SD": "englais (Sudan)",
  "en_SG": "englais (Singapur)",
  "en_SH": "englais (Sontg’Elena)",
  "en_SL": "englais (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "englais (Swaziland)",
  "en_TC": "englais (Inslas Turks e Caicos)",
  "en_TK": "englais (Tokelau)",
  "en_TO": "englais (Tonga)",
  "en_TT": "englais (Trinidad e Tobago)",
  "en_TV": "englais (Tuvalu)",
  "en_TZ": "englais (Tansania)",
  "en_UG": "englais (Uganda)",
  "en_UM":
      "englais (Inslas pitschnas perifericas dals Stadis Unids da l’America)",
  "en_US": "englais (Stadis Unids da l’America)",
  "en_VC": "englais (Saint Vincent e las Grenadinas)",
  "en_VG": "englais (Inslas Verginas Britannicas)",
  "en_VI": "englais (Inslas Verginas Americanas)",
  "en_VU": "englais (Vanuatu)",
  "en_WS": "englais (Samoa)",
  "en_ZA": "englais (Africa dal Sid)",
  "en_ZM": "englais (Sambia)",
  "en_ZW": "englais (Simbabwe)",
  "enm": "englais mesaun",
  "eo": "esperanto",
  "es": "spagnol",
  "es_419": "spagnol latinamerican",
  "es_AR": "spagnol (Argentinia)",
  "es_BO": "spagnol (Bolivia)",
  "es_CL": "spagnol (Chile)",
  "es_CO": "spagnol (Columbia)",
  "es_CR": "spagnol (Costa Rica)",
  "es_CU": "spagnol (Cuba)",
  "es_DO": "spagnol (Republica Dominicana)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "spagnol (Ecuador)",
  "es_ES": "spagnol (Spagna)",
  "es_GQ": "spagnol (Guinea Equatoriala)",
  "es_GT": "spagnol (Guatemala)",
  "es_HN": "spagnol (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "spagnol (Mexico)",
  "es_NI": "spagnol (Nicaragua)",
  "es_PA": "spagnol (Panama)",
  "es_PE": "spagnol (Peru)",
  "es_PH": "spagnol (Filippinas)",
  "es_PR": "spagnol (Puerto Rico)",
  "es_PY": "spagnol (Paraguai)",
  "es_SV": "spagnol (El Salvador)",
  "es_US": "spagnol (Stadis Unids da l’America)",
  "es_UY": "spagnol (Uruguay)",
  "es_VE": "spagnol (Venezuela)",
  "esu": "Central Yupik",
  "et": "eston",
  "et_EE": "eston (Estonia)",
  "eu": "basc",
  "eu_ES": "basc (Spagna)",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fa": "persian",
  "fa_AF": "persian (Afghanistan)",
  "fa_IR": "persian (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fulah",
  "ff_CM": "fulah (Camerun)",
  "ff_GN": "fulah (Guinea)",
  "ff_MR": "fulah (Mauretania)",
  "ff_SN": "fulah (Senegal)",
  "fi": "finlandais",
  "fi_FI": "finlandais (Finlanda)",
  "fil": "filippino",
  "fit": "Tornedalen Finnish",
  "fiu": "lingua ungrofinnica",
  "fj": "fidschian",
  "fo": "ferrais",
  "fo_FO": "ferrais (Inslas Feroe)",
  "fon": "fon",
  "fr": "franzos",
  "fr_BE": "franzos (Belgia)",
  "fr_BF": "franzos (Burkina Faso)",
  "fr_BI": "franzos (Burundi)",
  "fr_BJ": "franzos (Benin)",
  "fr_BL": "franzos (Son Barthélemy)",
  "fr_CA": "franzos (Canada)",
  "fr_CD": "franzos (Republica Democratica dal Congo)",
  "fr_CF": "franzos (Republica Centralafricana)",
  "fr_CG": "franzos (Congo)",
  "fr_CH": "franzos (Svizra)",
  "fr_CI": "franzos (Costa d’Ivur)",
  "fr_CM": "franzos (Camerun)",
  "fr_DJ": "franzos (Dschibuti)",
  "fr_DZ": "franzos (Algeria)",
  "fr_FR": "franzos (Frantscha)",
  "fr_GA": "franzos (Gabun)",
  "fr_GF": "franzos (Guyana Franzosa)",
  "fr_GN": "franzos (Guinea)",
  "fr_GP": "franzos (Guadeloupe)",
  "fr_GQ": "franzos (Guinea Equatoriala)",
  "fr_HT": "franzos (Haiti)",
  "fr_KM": "franzos (Comoras)",
  "fr_LU": "franzos (Luxemburg)",
  "fr_MA": "franzos (Maroc)",
  "fr_MC": "franzos (Monaco)",
  "fr_MF": "franzos (Saint Martin)",
  "fr_MG": "franzos (Madagascar)",
  "fr_ML": "franzos (Mali)",
  "fr_MQ": "franzos (Martinique)",
  "fr_MR": "franzos (Mauretania)",
  "fr_MU": "franzos (Mauritius)",
  "fr_NC": "franzos (Nova Caledonia)",
  "fr_NE": "franzos (Niger)",
  "fr_PF": "franzos (Polinesia Franzosa)",
  "fr_PM": "franzos (Saint Pierre e Miquelon)",
  "fr_RE": "franzos (Réunion)",
  "fr_RW": "franzos (Ruanda)",
  "fr_SC": "franzos (Seychellas)",
  "fr_SN": "franzos (Senegal)",
  "fr_SY": "franzos (Siria)",
  "fr_TD": "franzos (Tschad)",
  "fr_TG": "franzos (Togo)",
  "fr_TN": "franzos (Tunesia)",
  "fr_VU": "franzos (Vanuatu)",
  "fr_WF": "franzos (Wallis e Futuna)",
  "fr_YT": "franzos (Mayotte)",
  "frc": "Cajun French",
  "frm": "franzos mesaun",
  "fro": "franzos vegl",
  "frp": "Arpitan",
  "frr": "fris dal nord",
  "frs": "fris da l’ost",
  "fur": "friulan",
  "fy": "fris",
  "fy_NL": "fris (Pajais Bass)",
  "ga": "irlandais",
  "ga_IE": "irlandais (Irlanda)",
  "gaa": "ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "gaelic scot",
  "gd_GB": "gaelic scot (Reginavel Unì)",
  "gem": "lingua germana",
  "gez": "geez",
  "gil": "gilbertais",
  "gl": "galician",
  "gl_ES": "galician (Spagna)",
  "glk": "Gilaki",
  "gmh": "tudestg mesaun",
  "gn": "guarani",
  "goh": "vegl tudestg da scrittira",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotic",
  "grb": "grebo",
  "grc": "grec vegl",
  "gsw": "tudestg svizzer",
  "gu": "gujarati",
  "gu_IN": "gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "manx",
  "gv_IM": "manx (Insla da Man)",
  "gwi": "gwichʼin",
  "ha": "haussa",
  "ha_GH": "haussa (Ghana)",
  "ha_Latn": "haussa (latin)",
  "ha_Latn_GH": "haussa (latin, Ghana)",
  "ha_Latn_NE": "haussa (latin, Niger)",
  "ha_Latn_NG": "haussa (latin, Nigeria)",
  "ha_NE": "haussa (Niger)",
  "ha_NG": "haussa (Nigeria)",
  "hai": "haida",
  "hak": "Hakka Chinese",
  "haw": "hawaian",
  "he": "ebraic",
  "he_IL": "ebraic (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "him": "himachali",
  "hit": "ettitic",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croat",
  "hr_BA": "croat (Bosnia ed Erzegovina)",
  "hr_HR": "croat (Croazia)",
  "hsb": "aut sorb",
  "hsn": "Xiang Chinese",
  "ht": "haitian",
  "hu": "ungarais",
  "hu_HU": "ungarais (Ungaria)",
  "hup": "hupa",
  "hy": "armen",
  "hy_AM": "armen (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "Ibibio",
  "id": "indonais",
  "id_ID": "indonais (Indonesia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigeria)",
  "ii": "sichuan yi",
  "ii_CN": "sichuan yi (China)",
  "ijo": "ijo",
  "ik": "inupiak",
  "ilo": "ilocano",
  "inc": "lingua indiana",
  "ine": "lingua indoeuropeica",
  "inh": "ingush",
  "io": "ido",
  "ira": "lingua da l'Iran",
  "iro": "linguas irochesas",
  "is": "islandais",
  "is_IS": "islandais (Islanda)",
  "it": "talian",
  "it_CH": "talian (Svizra)",
  "it_IT": "talian (Italia)",
  "it_SM": "talian (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "giapunais",
  "ja_JP": "giapunais (Giapun)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "giudaic-persian",
  "jrb": "giudaic-arab",
  "jut": "Jutish",
  "jv": "javanais",
  "ka": "georgian",
  "ka_GE": "georgian (Georgia)",
  "kaa": "karakalpak",
  "kab": "kabyle",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "kabardic",
  "kbl": "Kanembu",
  "kcg": "tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongo",
  "kgp": "Kaingang",
  "kha": "khasi",
  "khi": "lingua khoisan",
  "kho": "khotanais",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenia)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "casac",
  "kk_Cyrl": "casac (cirillic)",
  "kk_Cyrl_KZ": "casac (cirillic, Kasachstan)",
  "kk_KZ": "casac (Kasachstan)",
  "kkj": "Kako",
  "kl": "grönlandais",
  "kl_GL": "grönlandais (Grönlanda)",
  "kln": "Kalenjin",
  "km": "cambodschan",
  "km_KH": "cambodschan (Cambodscha)",
  "kmb": "kimbundu",
  "kn": "kannada",
  "kn_IN": "kannada (India)",
  "ko": "corean",
  "ko_KP": "corean (Corea dal Nord)",
  "ko_KR": "corean (Corea dal Sid)",
  "koi": "Komi-Permyak",
  "kok": "konkani",
  "kos": "kosraean",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karachay-balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "carelian",
  "kro": "kru",
  "kru": "kurukh",
  "ks": "kashmiri",
  "ks_Arab": "kashmiri (arab)",
  "ks_Arab_IN": "kashmiri (arab, India)",
  "ks_IN": "kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "curd",
  "kum": "kumuk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "cornic",
  "kw_GB": "cornic (Reginavel Unì)",
  "ky": "kirghis",
  "ky_Cyrl": "kirghis (cirillic)",
  "ky_Cyrl_KG": "kirghis (cirillic, Kirghisistan)",
  "ky_KG": "kirghis (Kirghisistan)",
  "la": "latin",
  "lad": "ladino",
  "lag": "Langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxemburgais",
  "lb_LU": "luxemburgais (Luxemburg)",
  "lez": "lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgais",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Republica Democratica dal Congo)",
  "ln_CF": "lingala (Republica Centralafricana)",
  "ln_CG": "lingala (Congo)",
  "lo": "laot",
  "lo_LA": "laot (Laos)",
  "lol": "lomongo",
  "loz": "lozi",
  "lt": "lituan",
  "lt_LT": "lituan (Lituania)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Republica Democratica dal Congo)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushai",
  "luy": "Luyia",
  "lv": "letton",
  "lv_LV": "letton (Lettonia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "madurais",
  "maf": "Mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makassar",
  "man": "mandingo",
  "map": "austronesian",
  "mas": "masai",
  "mde": "Maba",
  "mdf": "moksha",
  "mdr": "mandar",
  "men": "mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "malagassi",
  "mg_MG": "malagassi (Madagascar)",
  "mga": "irlandais mesaun",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "marschallais",
  "mi": "maori",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "diversas linguas",
  "mk": "macedon",
  "mk_MK": "macedon (Macedonia)",
  "mkh": "lingua mon-khmer",
  "ml": "malayalam",
  "ml_IN": "malayalam (India)",
  "mn": "mongolic",
  "mn_Cyrl": "mongolic (cirillic)",
  "mn_Cyrl_MN": "mongolic (cirillic, Mongolia)",
  "mn_MN": "mongolic (Mongolia)",
  "mnc": "manchu",
  "mni": "manipuri",
  "mno": "manobo",
  "mo": "moldav",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "Western Mari",
  "ms": "malaic",
  "ms_BN": "malaic (Brunei)",
  "ms_Latn": "malaic (latin)",
  "ms_Latn_BN": "malaic (latin, Brunei)",
  "ms_Latn_MY": "malaic (latin, Malaisia)",
  "ms_Latn_SG": "malaic (latin, Singapur)",
  "ms_MY": "malaic (Malaisia)",
  "ms_SG": "malaic (Singapur)",
  "mt": "maltais",
  "mt_MT": "maltais (Malta)",
  "mua": "Mundang",
  "mul": "pluriling",
  "mun": "lingua munda",
  "mus": "creek",
  "mwl": "mirandais",
  "mwr": "marwari",
  "mwv": "Mentawai",
  "my": "birman",
  "my_MM": "birman (Myanmar)",
  "mye": "Myene",
  "myn": "lingau maya",
  "myv": "erzya",
  "mzn": "Mazanderani",
  "na": "nauru",
  "nah": "nahuatl",
  "nai": "lingua indiana da l'America dal Nord",
  "nan": "Min Nan Chinese",
  "nap": "neapolitan",
  "naq": "Nama",
  "nb": "norvegais bokmål",
  "nb_NO": "norvegais bokmål (Norvegia)",
  "nb_SJ": "norvegais bokmål (Svalbard e Jan Mayen)",
  "nd": "ndebele dal nord",
  "nd_ZW": "ndebele dal nord (Simbabwe)",
  "nds": "bass tudestg",
  "ne": "nepalais",
  "ne_IN": "nepalais (India)",
  "ne_NP": "nepalais (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "lingua niger-cordofanica",
  "niu": "niue",
  "njo": "Ao Naga",
  "nl": "ollandais",
  "nl_AW": "ollandais (Aruba)",
  "nl_BE": "ollandais (Belgia)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "ollandais (Pajais Bass)",
  "nl_SR": "ollandais (Surinam)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "norvegiais nynorsk",
  "nn_NO": "norvegiais nynorsk (Norvegia)",
  "nnh": "Ngiemboon",
  "no": "norvegiais",
  "no_NO": "norvegiais (Norvegia)",
  "nog": "nogai",
  "non": "nordic vegl",
  "nov": "Novial",
  "nqo": "n’ko",
  "nr": "ndebele dal sid",
  "nso": "sotho dal nord",
  "nub": "linguas nubicas",
  "nus": "Nuer",
  "nv": "navajo",
  "nwc": "newari classic",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "occitan",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiopia)",
  "om_KE": "oromo (Kenia)",
  "or": "oriya",
  "or_IN": "oriya (India)",
  "os": "ossetic",
  "os_GE": "ossetic (Georgia)",
  "os_RU": "ossetic (Russia)",
  "osa": "osage",
  "ota": "tirc ottoman",
  "oto": "linguas otomangue",
  "pa": "punjabi",
  "pa_Arab": "punjabi (arab)",
  "pa_Arab_PK": "punjabi (arab, Pakistan)",
  "pa_Guru": "punjabi (gurmukhi)",
  "pa_Guru_IN": "punjabi (gurmukhi, India)",
  "pa_IN": "punjabi (India)",
  "pa_PK": "punjabi (Pakistan)",
  "paa": "lingua papuana",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palau",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "persian vegl",
  "pfl": "Palatine German",
  "phi": "lingua filippina",
  "phn": "fenizian",
  "pi": "pali",
  "pl": "polac",
  "pl_PL": "polac (Pologna)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "ponapean",
  "pra": "prakrit",
  "prg": "Prussian",
  "pro": "provenzal vegl",
  "ps": "paschto",
  "ps_AF": "paschto (Afghanistan)",
  "pt": "portugais",
  "pt_AO": "portugais (Angola)",
  "pt_BR": "portugais (Brasila)",
  "pt_CV": "portugais (Cap Verd)",
  "pt_GW": "portugais (Guinea-Bissau)",
  "pt_MO": "portugais (Regiun d’administraziun speziala Macao, China)",
  "pt_MZ": "portugais (Mosambic)",
  "pt_PT": "portugais (Portugal)",
  "pt_ST": "portugais (São Tomé e Principe)",
  "pt_TL": "portugais (Timor da l’Ost)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivia)",
  "qu_EC": "quechua (Ecuador)",
  "qu_PE": "quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotonga",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "rumantsch",
  "rm_CH": "rumantsch (Svizra)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "rumen",
  "ro_MD": "rumen (Moldavia)",
  "ro_RO": "rumen (Rumenia)",
  "roa": "lingua romana",
  "rof": "Rombo",
  "rom": "romani",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "russ",
  "ru_BY": "russ (Bielorussia)",
  "ru_KG": "russ (Kirghisistan)",
  "ru_KZ": "russ (Kasachstan)",
  "ru_MD": "russ (Moldavia)",
  "ru_RU": "russ (Russia)",
  "ru_UA": "russ (Ucraina)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromunic",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Ruanda)",
  "rwk": "Rwa",
  "sa": "sanscrit",
  "sad": "sandawe",
  "sah": "jakut",
  "sai": "lingua indiana da l'America dal Sid",
  "sal": "lingua salish",
  "sam": "arameic samaritan",
  "saq": "Samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "sard",
  "scn": "sicilian",
  "sco": "scot",
  "sd": "sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "sami dal nord",
  "se_FI": "sami dal nord (Finlanda)",
  "se_NO": "sami dal nord (Norvegia)",
  "se_SE": "sami dal nord (Svezia)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "selkup",
  "sem": "lingua semitica",
  "ses": "Koyraboro Senni",
  "sg": "sango",
  "sg_CF": "sango (Republica Centralafricana)",
  "sga": "irlandais vegl",
  "sgn": "lingua da segns",
  "sgs": "Samogitian",
  "sh": "serbo-croat",
  "sh_BA": "serbo-croat (Bosnia ed Erzegovina)",
  "shi": "Tachelhit",
  "shn": "shan",
  "shu": "Chadian Arabic",
  "si": "singalais",
  "si_LK": "singalais (Sri Lanka)",
  "sid": "sidamo",
  "sio": "linguas sioux",
  "sit": "linguas sino-tibetanas",
  "sk": "slovac",
  "sk_SK": "slovac (Slovachia)",
  "sl": "sloven",
  "sl_SI": "sloven (Slovenia)",
  "sla": "lingua slava",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoan",
  "sma": "sami dal sid",
  "smi": "lingua sami",
  "smj": "sami lule",
  "smn": "sami inari",
  "sms": "sami skolt",
  "sn": "shona",
  "sn_ZW": "shona (Simbabwe)",
  "snk": "soninke",
  "so": "somali",
  "so_DJ": "somali (Dschibuti)",
  "so_ET": "somali (Etiopia)",
  "so_KE": "somali (Kenia)",
  "so_SO": "somali (Somalia)",
  "sog": "sogdian",
  "son": "songhai",
  "sq": "albanais",
  "sq_AL": "albanais (Albania)",
  "sq_MK": "albanais (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "serb",
  "sr_BA": "serb (Bosnia ed Erzegovina)",
  "sr_Cyrl": "serb (cirillic)",
  "sr_Cyrl_BA": "serb (cirillic, Bosnia ed Erzegovina)",
  "sr_Cyrl_ME": "serb (cirillic, Montenegro)",
  "sr_Cyrl_RS": "serb (cirillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "serb (latin)",
  "sr_Latn_BA": "serb (latin, Bosnia ed Erzegovina)",
  "sr_Latn_ME": "serb (latin, Montenegro)",
  "sr_Latn_RS": "serb (latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "serb (Montenegro)",
  "sr_RS": "serb (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "sranan tongo",
  "srr": "serer",
  "ss": "swazi",
  "ssa": "lingua nilo-sahariana",
  "ssy": "Saho",
  "st": "sotho dal sid",
  "stq": "Saterland Frisian",
  "su": "sundanais",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumeric",
  "sv": "svedais",
  "sv_AX": "svedais (Inslas Aland)",
  "sv_FI": "svedais (Finlanda)",
  "sv_SE": "svedais (Svezia)",
  "sw": "suahili",
  "sw_KE": "suahili (Kenia)",
  "sw_TZ": "suahili (Tansania)",
  "sw_UG": "suahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "siric classic",
  "syr": "siric",
  "szl": "Silesian",
  "ta": "tamil",
  "ta_IN": "tamil (India)",
  "ta_LK": "tamil (Sri Lanka)",
  "ta_MY": "tamil (Malaisia)",
  "ta_SG": "tamil (Singapur)",
  "tai": "lingua tai",
  "tcy": "Tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "Teso",
  "ter": "tereno",
  "tet": "tetum",
  "tg": "tadjik",
  "th": "tailandais",
  "th_TH": "tailandais (Tailanda)",
  "ti": "tigrinya",
  "ti_ER": "tigrinya (Eritrea)",
  "ti_ET": "tigrinya (Etiopia)",
  "tig": "tigre",
  "tiv": "tiv",
  "tk": "turkmen",
  "tkl": "tokelau",
  "tkr": "Tsakhur",
  "tl": "tagalog",
  "tl_PH": "tagalog (Filippinas)",
  "tlh": "klingonic",
  "tli": "tlingit",
  "tly": "Talysh",
  "tmh": "tamasheq",
  "tn": "tswana",
  "to": "tonga",
  "to_TO": "tonga (Tonga)",
  "tog": "lingua tsonga",
  "tpi": "tok pisin",
  "tr": "tirc",
  "tr_CY": "tirc (Cipra)",
  "tr_TR": "tirc (Tirchia)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshian",
  "tt": "tatar",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tup": "linguas tupi",
  "tut": "linguas altaicas",
  "tvl": "tuvalu",
  "tw": "twi",
  "twq": "Tasawaq",
  "ty": "tahitian",
  "tyv": "tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "udmurt",
  "ug": "uiguric",
  "ug_Arab": "uiguric (arab)",
  "ug_Arab_CN": "uiguric (arab, China)",
  "ug_CN": "uiguric (China)",
  "uga": "ugaritic",
  "uk": "ucranais",
  "uk_UA": "ucranais (Ucraina)",
  "umb": "mbundu",
  "und": "linguas betg determinadas",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakistan)",
  "uz": "usbec",
  "uz_AF": "usbec (Afghanistan)",
  "uz_Arab": "usbec (arab)",
  "uz_Arab_AF": "usbec (arab, Afghanistan)",
  "uz_Cyrl": "usbec (cirillic)",
  "uz_Cyrl_UZ": "usbec (cirillic, Usbekistan)",
  "uz_Latn": "usbec (latin)",
  "uz_Latn_UZ": "usbec (latin, Usbekistan)",
  "uz_UZ": "usbec (Usbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnamais",
  "vi_VN": "vietnamais (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapuk",
  "vot": "votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "vallon",
  "wae": "Walser",
  "wak": "linguas wakash",
  "wal": "walamo",
  "war": "waray",
  "was": "washo",
  "wbp": "Warlpiri",
  "wen": "sorb",
  "wo": "wolof",
  "wuu": "Wu Chinese",
  "xal": "kalmuk",
  "xh": "xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "yao",
  "yap": "yapais",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "jiddic",
  "yo": "yoruba",
  "yo_BJ": "yoruba (Benin)",
  "yo_NG": "yoruba (Nigeria)",
  "ypk": "linguas yupik",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "zhuang",
  "zap": "zapotec",
  "zbl": "simbols da Bliss",
  "zea": "Zeelandic",
  "zen": "zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "chinais",
  "zh_CN": "chinais (China)",
  "zh_HK": "chinais (Regiun d’administraziun speziala da Hongkong, China)",
  "zh_Hans": "chinais (simplifitgada)",
  "zh_Hans_CN": "chinais (scrittira chinaisa simplifitgada, China)",
  "zh_Hans_HK":
      "chinais (scrittira chinaisa simplifitgada, Regiun d’administraziun speziala da Hongkong, China)",
  "zh_Hans_MO":
      "chinais (scrittira chinaisa simplifitgada, Regiun d’administraziun speziala Macao, China)",
  "zh_Hans_SG": "chinais (scrittira chinaisa simplifitgada, Singapur)",
  "zh_Hant": "chinais (tradiziunala)",
  "zh_Hant_HK":
      "chinais (scrittira chinaisa tradiziunala, Regiun d’administraziun speziala da Hongkong, China)",
  "zh_Hant_MO":
      "chinais (scrittira chinaisa tradiziunala, Regiun d’administraziun speziala Macao, China)",
  "zh_Hant_TW": "chinais (scrittira chinaisa tradiziunala, Taiwan)",
  "zh_MO": "chinais (Regiun d’administraziun speziala Macao, China)",
  "zh_SG": "chinais (Singapur)",
  "zh_TW": "chinais (Taiwan)",
  "znd": "zande",
  "zu": "zulu",
  "zu_ZA": "zulu (Africa dal Sid)",
  "zun": "zuni",
  "zxx": "nagins cuntegns linguistics",
  "zza": "zaza"
};
