const names = {
  "ace": "Achinese",
  "ale": "Aleut",
  "arn": "Araukanya Dili",
  "ast": "Asturyasca",
  "az": "Azerice",
  "bal": "Baluchi",
  "ban": "Bali Dili",
  "bar": "Bavyera Dili",
  "be": "Beyaz Rusça",
  "bej": "Beja Dili",
  "bla": "Siksika",
  "bua": "Buryat",
  "cad": "Caddo",
  "cay": "Cayuga",
  "ceb": "Cebuano",
  "cgg": "Kigaca",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Çağatay Dili",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chy": "Şayen Dili",
  "cr": "Cree",
  "dak": "Dakota",
  "den": "Slavey",
  "din": "Dinka",
  "dv": "Divehi",
  "dz": "Butan Dili",
  "ff": "Fulah",
  "fj": "Fiji Dili",
  "fo": "Faroe Dili",
  "fur": "Friulian",
  "gaa": "Ga",
  "gay": "Gayo",
  "gd": "İskoç Gal Dili",
  "gil": "Kiribati Dili",
  "gn": "Guarani Dili",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "grb": "Grebo",
  "guc": "Wayuu",
  "gv": "Manks",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "hai": "Haida",
  "haw": "Hawaii Dili",
  "hil": "Hiligaynon",
  "ht": "Haiti Dili",
  "hup": "Hupa",
  "hz": "Herero",
  "ia": "Interlingua",
  "ibb": "Ibibio",
  "ig": "İbo Dili",
  "ik": "Inupiak",
  "iu": "Inuktitut",
  "jv": "Cava Dili",
  "kac": "Kaçin",
  "kg": "Kongo",
  "kha": "Khasi",
  "kl": "Grönland Dili",
  "km": "Kmerce",
  "kn": "Kannada",
  "kok": "Konkani",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "kru": "Kurukh",
  "ks": "Keşmirce",
  "ksb": "Shambala",
  "ksh": "Köln Diyalekti",
  "kut": "Kutenai",
  "lam": "Lamba",
  "lo": "Laoca",
  "lt": "Litvanyaca",
  "mdf": "Mokşa Dili",
  "men": "Mende",
  "mh": "Marshall Adaları Dili",
  "mi": "Maori Dili",
  "ml": "Malayalam",
  "mnc": "Mançurya Dili",
  "mni": "Manipuri",
  "moh": "Mohavk Dili",
  "mr": "Marathi",
  "mus": "Creek",
  "mwl": "Miranda Dili",
  "my": "Burmaca",
  "na": "Nauru Dili",
  "niu": "Niuean",
  "nl": "Hollandaca",
  "non": "Eski Norse",
  "nso": "Kuzey Sotho",
  "nv": "Navaho Dili",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibva Dili",
  "om": "Oromo",
  "pag": "Pangasinan",
  "pau": "Palau Dili",
  "phn": "Fenike Dili",
  "qu": "Keçuvaca",
  "rap": "Rapanui",
  "ro": "Romence",
  "sa": "Sanskritçe",
  "sc": "Sardunya Dili",
  "sco": "Scots",
  "sd": "Sindhi",
  "se": "Kuzey Sami",
  "see": "Seneca",
  "sel": "Selkup",
  "shi": "Taşelhit",
  "shn": "Shan Dili",
  "si": "Seylanca",
  "sid": "Sidamo",
  "sm": "Samoa Dili",
  "sma": "Güney Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "srr": "Serer",
  "st": "Güney Sotho",
  "su": "Sunda Dili",
  "suk": "Sukuma",
  "sw": "Svahili",
  "te": "Telugu Dili",
  "ti": "Tigrinya",
  "tkl": "Tokelau",
  "tl": "Takalotça",
  "to": "Tongaca",
  "tvl": "Tuvalu",
  "ty": "Tahiti Dili",
  "tzm": "Orta Fas Tamazigti",
  "uga": "Ugarit Dili",
  "ve": "Venda",
  "vep": "Veps",
  "vot": "Votic",
  "xh": "Zosa",
  "za": "Zhuang",
  "zap": "Zapotek Dili",
  "zen": "Zenaga",
  "zgh": "Standart Berberi Dili Tamazight",
  "zun": "Zuni"
};
