const names = {
  "AD": "Andôro",
  "AE": "Arâbo Emirâti Ôko",
  "AF": "Faganïta, Afganïstäan",
  "AG": "Antîgua na Barbûda",
  "AI": "Angûîla",
  "AL": "Albanïi",
  "AM": "Armenïi",
  "AN": "Antîyi tî Holânde",
  "AO": "Angoläa",
  "AQ": "Antarctica",
  "AR": "Arzantîna",
  "AS": "Samöa tî Amerîka",
  "AT": "Otrîsi",
  "AU": "Ostralïi, Sotralïi",
  "AW": "Arûba",
  "AX": "Åland Islands",
  "AZ": "Zerebaidyäan, Azerbaidyäan,",
  "BA": "Bosnïi na Herzegovînni",
  "BB": "Barabâda",
  "BD": "Bengladêshi",
  "BE": "Bêleze, Belezîki",
  "BF": "Burkina Faso",
  "BG": "Bulugarïi",
  "BH": "Bahrâina",
  "BI": "Burundïi",
  "BJ": "Benëen",
  "BL": "St. Barthélemy",
  "BM": "Beremûda",
  "BN": "Brunêi",
  "BO": "Bolivïi",
  "BQ": "Caribbean Netherlands",
  "BR": "Brezîli",
  "BS": "Bahâmasa",
  "BT": "Butäan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarüsi",
  "BZ": "Belîzi",
  "CA": "Kanadäa",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Ködörösêse tî Ngunuhalëzo tî kongö",
  "CF": "Ködörösêse tî Bêafrîka",
  "CG": "Kongö",
  "CH": "Sûîsi",
  "CI": "Kôdivüära",
  "CK": "âzûâ Kûku",
  "CL": "Shilïi",
  "CM": "Kamerûne",
  "CN": "Shîna",
  "CO": "Kolombïi",
  "CR": "Kôsta Rîka",
  "CS": "Serbïi na Möntënegröo",
  "CU": "Kubäa",
  "CV": "Azûâ tî Kâpo-Vêre",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Sîpri",
  "CZ": "Ködörösêse tî Tyêki",
  "DE": "Zâmani",
  "DJ": "Dibutùii",
  "DK": "Danemêrke",
  "DM": "Dömïnîka",
  "DO": "Ködörösêse tî Dominîka",
  "DZ": "Alzerïi",
  "EC": "Ekuatëre",
  "EE": "Estonïi",
  "EG": "Kâmitâ",
  "EH": "Western Sahara",
  "ER": "Eritrëe",
  "ES": "Espânye",
  "ET": "Etiopïi",
  "FI": "Fëlânde",
  "FJ": "Fidyïi",
  "FK": "Âzûâ tî Mälüîni",
  "FM": "Mikronezïi",
  "FO": "Faroe Islands",
  "FR": "Farânzi",
  "GA": "Gaböon",
  "GB": "Ködörögbïä--Ôko",
  "GD": "Grenâda",
  "GE": "Zorzïi",
  "GF": "Güyâni tî farânzi",
  "GG": "Guernsey",
  "GH": "Ganäa",
  "GI": "Zibraltära, Zibaratära",
  "GL": "Gorolânde",
  "GM": "Gambïi",
  "GN": "Ginëe",
  "GP": "Guadelûpu",
  "GQ": "Ginëe tî Ekuatëre",
  "GR": "Gerêsi",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Guatêmälä",
  "GU": "Guâm",
  "GW": "Gninëe-Bisau",
  "GY": "Gayâna",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Honduräsi",
  "HR": "Kroasïi",
  "HT": "Haitïi",
  "HU": "Hongirùii",
  "ID": "Ênndonezïi",
  "IE": "Irlânde",
  "IL": "Israëli",
  "IM": "Isle of Man",
  "IN": "Ênnde",
  "IO": "Sêse tî Anglëe na Ngûyämä tî Ênnde",
  "IQ": "Irâki",
  "IR": "Iräan",
  "IS": "Islânde",
  "IT": "Italùii",
  "JE": "Jersey",
  "JM": "Zamaîka",
  "JO": "Zordanïi",
  "JP": "Zapöon",
  "KE": "Kenyäa",
  "KG": "Kirigizitùaan",
  "KH": "Kämbôzi",
  "KI": "Kiribati",
  "KM": "Kömôro",
  "KN": "Sên-Krïstôfo-na-Nevîsi",
  "KP": "Korëe tî Banga",
  "KR": "Korëe tî Mbongo",
  "KW": "Köwêti",
  "KY": "Âzûâ Ngundë, Kaimäni",
  "KZ": "Kazakisitäan",
  "LA": "Lùaôsi",
  "LB": "Libùaan",
  "LC": "Sênt-Lisïi",
  "LI": "Liechtenstein,",
  "LK": "Sirî-Lanka",
  "LR": "Liberïa",
  "LS": "Lesôtho",
  "LT": "Lituanïi",
  "LU": "Lugzambûru",
  "LV": "Letonùii",
  "LY": "Libïi",
  "MA": "Marôko",
  "MC": "Monaköo",
  "MD": "Moldavùii",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagaskära",
  "MH": "Âzûâ Märshâl",
  "MK": "Maseduäni",
  "ML": "Malïi",
  "MM": "Myämâra",
  "MN": "Mongolïi",
  "MO": "Macao SAR China",
  "MP": "Âzûâ Märïâni tî Banga",
  "MQ": "Märtïnîki",
  "MR": "Moritanïi",
  "MS": "Monserâte",
  "MT": "Mâlta",
  "MU": "Mörîsi",
  "MV": "Maldîva",
  "MW": "Malawïi",
  "MX": "Mekisîki",
  "MY": "Malezïi",
  "MZ": "Mözämbîka",
  "NA": "Namibùii",
  "NC": "Finî Kaledonïi",
  "NE": "Nizëre",
  "NF": "Zûâ Nôrfôlko",
  "NG": "Nizerïa",
  "NI": "Nikaragua",
  "NL": "Holände",
  "NO": "Nörvêzi",
  "NP": "Nëpâli",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Finî Zelânde",
  "OM": "Omâni",
  "PA": "Panama",
  "PE": "Perüu",
  "PF": "Polinezïi tî farânzi",
  "PG": "Papû Finî Ginëe, Papuazïi",
  "PH": "Filipîni",
  "PK": "Pakistäan",
  "PL": "Pölôni",
  "PM": "Sên-Pyêre na Mikelöon",
  "PN": "Pitikêrni",
  "PR": "Porto Rîko",
  "PS": "Sêse tî Palestîni",
  "PT": "Pörtugäle, Ködörö Pûra",
  "PW": "Palau",
  "PY": "Paraguëe",
  "QA": "Katära",
  "RE": "Reinïon",
  "RO": "Rumanïi",
  "RS": "Serbia",
  "RU": "Rusïi",
  "RW": "Ruandäa",
  "SA": "Saûdi Arabïi",
  "SB": "Zûâ Salomöon",
  "SC": "Sëyshêle",
  "SD": "Sudäan",
  "SE": "Suêde",
  "SG": "Sïngäpûru",
  "SH": "Sênt-Helêna",
  "SI": "Solovenïi",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Solovakïi",
  "SL": "Sierä-Leône",
  "SM": "Sên-Marëen",
  "SN": "Senegäle",
  "SO": "Somalïi",
  "SR": "Surinäm",
  "SS": "Sudäan-Mbongo",
  "ST": "Sâô Tömê na Prinsîpe",
  "SV": "Salvadöro",
  "SX": "Sint Maarten",
  "SY": "Sirïi",
  "SZ": "Swäzïlânde",
  "TC": "Âzûâ Turku na Kaîki",
  "TD": "Tyâde",
  "TF": "French Southern Territories",
  "TG": "Togö",
  "TH": "Tailânde",
  "TJ": "Taazikiistäan",
  "TK": "Tokelau",
  "TL": "Timôro tî Tö",
  "TM": "Turkumenistäan",
  "TN": "Tunizïi",
  "TO": "Tonga",
  "TR": "Turukïi",
  "TT": "Trinitùee na Tobagö",
  "TV": "Tüvalü",
  "TW": "Tâiwâni",
  "TZ": "Tanzanïi",
  "UA": "Ukrêni",
  "UG": "Ugandäa",
  "UM": "U.S. Outlying Islands",
  "US": "ÂLeaa-Ôko tî Amerika",
  "UY": "Uruguëe",
  "UZ": "Uzbekistäan",
  "VA": "Letëe tî Vatikäan",
  "VC": "Sên-Vensäan na âGrenadîni",
  "VE": "Venezueläa",
  "VG": "Âzôâ Viîrîggo tî Anglëe",
  "VI": "Âzûâ Virîgo tî Amerîka",
  "VN": "Vietnäm",
  "VU": "Vanuatü",
  "WF": "Walîsi na Futuna",
  "WS": "Samoäa",
  "YE": "Yëmêni",
  "YT": "Mäyôte",
  "ZA": "Mbongo-Afrîka",
  "ZM": "Zambïi",
  "ZW": "Zimbäbwe",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akâan",
  "ak_GH": "Akâan (Ganäa)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Amarîki",
  "am_ET": "Amarîki (Etiopïi)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "Arâbo",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Arâbo (Arâbo Emirâti Ôko)",
  "ar_BH": "Arâbo (Bahrâina)",
  "ar_DJ": "Arâbo (Dibutùii)",
  "ar_DZ": "Arâbo (Alzerïi)",
  "ar_EG": "Arâbo (Kâmitâ)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arâbo (Eritrëe)",
  "ar_IL": "Arâbo (Israëli)",
  "ar_IQ": "Arâbo (Irâki)",
  "ar_JO": "Arâbo (Zordanïi)",
  "ar_KM": "Arâbo (Kömôro)",
  "ar_KW": "Arâbo (Köwêti)",
  "ar_LB": "Arâbo (Libùaan)",
  "ar_LY": "Arâbo (Libïi)",
  "ar_MA": "Arâbo (Marôko)",
  "ar_MR": "Arâbo (Moritanïi)",
  "ar_OM": "Arâbo (Omâni)",
  "ar_PS": "Arâbo (Sêse tî Palestîni)",
  "ar_QA": "Arâbo (Katära)",
  "ar_SA": "Arâbo (Saûdi Arabïi)",
  "ar_SD": "Arâbo (Sudäan)",
  "ar_SO": "Arâbo (Somalïi)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Arâbo (Sirïi)",
  "ar_TD": "Arâbo (Tyâde)",
  "ar_TN": "Arâbo (Tunizïi)",
  "ar_YE": "Arâbo (Yëmêni)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Bielörûsi",
  "be_BY": "Bielörûsi (Belarüsi)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulugäri",
  "bg_BG": "Bulugäri (Bulugarïi)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bengäli",
  "bn_BD": "Bengäli (Bengladêshi)",
  "bn_IN": "Bengäli (Ênnde)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "Tyêki",
  "cs_CZ": "Tyêki (Ködörösêse tî Tyêki)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "Zâmani",
  "de_AT": "Zâmani (Otrîsi)",
  "de_BE": "Zâmani (Bêleze, Belezîki)",
  "de_CH": "Zâmani (Sûîsi)",
  "de_DE": "Zâmani (Zâmani)",
  "de_LI": "Zâmani (Liechtenstein,)",
  "de_LU": "Zâmani (Lugzambûru)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Gerêki",
  "el_CY": "Gerêki (Sîpri)",
  "el_GR": "Gerêki (Gerêsi)",
  "elx": "Elamite",
  "en": "Anglëe",
  "en_AG": "Anglëe (Antîgua na Barbûda)",
  "en_AI": "Anglëe (Angûîla)",
  "en_AS": "Anglëe (Samöa tî Amerîka)",
  "en_AU": "Anglëe (Ostralïi, Sotralïi)",
  "en_BB": "Anglëe (Barabâda)",
  "en_BE": "Anglëe (Bêleze, Belezîki)",
  "en_BM": "Anglëe (Beremûda)",
  "en_BS": "Anglëe (Bahâmasa)",
  "en_BW": "Anglëe (Botswana)",
  "en_BZ": "Anglëe (Belîzi)",
  "en_CA": "Anglëe (Kanadäa)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Anglëe (âzûâ Kûku)",
  "en_CM": "Anglëe (Kamerûne)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Anglëe (Dömïnîka)",
  "en_ER": "Anglëe (Eritrëe)",
  "en_FJ": "Anglëe (Fidyïi)",
  "en_FK": "Anglëe (Âzûâ tî Mälüîni)",
  "en_FM": "Anglëe (Mikronezïi)",
  "en_GB": "Anglëe (Ködörögbïä--Ôko)",
  "en_GD": "Anglëe (Grenâda)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Anglëe (Ganäa)",
  "en_GI": "Anglëe (Zibraltära, Zibaratära)",
  "en_GM": "Anglëe (Gambïi)",
  "en_GU": "Anglëe (Guâm)",
  "en_GY": "Anglëe (Gayâna)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Anglëe (Irlânde)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Anglëe (Ênnde)",
  "en_IO": "Anglëe (Sêse tî Anglëe na Ngûyämä tî Ênnde)",
  "en_JE": "English (Jersey)",
  "en_JM": "Anglëe (Zamaîka)",
  "en_KE": "Anglëe (Kenyäa)",
  "en_KI": "Anglëe (Kiribati)",
  "en_KN": "Anglëe (Sên-Krïstôfo-na-Nevîsi)",
  "en_KY": "Anglëe (Âzûâ Ngundë, Kaimäni)",
  "en_LC": "Anglëe (Sênt-Lisïi)",
  "en_LR": "Anglëe (Liberïa)",
  "en_LS": "Anglëe (Lesôtho)",
  "en_MG": "Anglëe (Madagaskära)",
  "en_MH": "Anglëe (Âzûâ Märshâl)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Anglëe (Âzûâ Märïâni tî Banga)",
  "en_MS": "Anglëe (Monserâte)",
  "en_MT": "Anglëe (Mâlta)",
  "en_MU": "Anglëe (Mörîsi)",
  "en_MW": "Anglëe (Malawïi)",
  "en_MY": "Anglëe (Malezïi)",
  "en_NA": "Anglëe (Namibùii)",
  "en_NF": "Anglëe (Zûâ Nôrfôlko)",
  "en_NG": "Anglëe (Nizerïa)",
  "en_NR": "Anglëe (Nauru)",
  "en_NU": "Anglëe (Niue)",
  "en_NZ": "Anglëe (Finî Zelânde)",
  "en_PG": "Anglëe (Papû Finî Ginëe, Papuazïi)",
  "en_PH": "Anglëe (Filipîni)",
  "en_PK": "Anglëe (Pakistäan)",
  "en_PN": "Anglëe (Pitikêrni)",
  "en_PR": "Anglëe (Porto Rîko)",
  "en_PW": "Anglëe (Palau)",
  "en_RW": "Anglëe (Ruandäa)",
  "en_SB": "Anglëe (Zûâ Salomöon)",
  "en_SC": "Anglëe (Sëyshêle)",
  "en_SD": "Anglëe (Sudäan)",
  "en_SG": "Anglëe (Sïngäpûru)",
  "en_SH": "Anglëe (Sênt-Helêna)",
  "en_SL": "Anglëe (Sierä-Leône)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Anglëe (Swäzïlânde)",
  "en_TC": "Anglëe (Âzûâ Turku na Kaîki)",
  "en_TK": "Anglëe (Tokelau)",
  "en_TO": "Anglëe (Tonga)",
  "en_TT": "Anglëe (Trinitùee na Tobagö)",
  "en_TV": "Anglëe (Tüvalü)",
  "en_TZ": "Anglëe (Tanzanïi)",
  "en_UG": "Anglëe (Ugandäa)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Anglëe (ÂLeaa-Ôko tî Amerika)",
  "en_VC": "Anglëe (Sên-Vensäan na âGrenadîni)",
  "en_VG": "Anglëe (Âzôâ Viîrîggo tî Anglëe)",
  "en_VI": "Anglëe (Âzûâ Virîgo tî Amerîka)",
  "en_VU": "Anglëe (Vanuatü)",
  "en_WS": "Anglëe (Samoäa)",
  "en_ZA": "Anglëe (Mbongo-Afrîka)",
  "en_ZM": "Anglëe (Zambïi)",
  "en_ZW": "Anglëe (Zimbäbwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "Espanyöl",
  "es_419": "Latin American Spanish",
  "es_AR": "Espanyöl (Arzantîna)",
  "es_BO": "Espanyöl (Bolivïi)",
  "es_CL": "Espanyöl (Shilïi)",
  "es_CO": "Espanyöl (Kolombïi)",
  "es_CR": "Espanyöl (Kôsta Rîka)",
  "es_CU": "Espanyöl (Kubäa)",
  "es_DO": "Espanyöl (Ködörösêse tî Dominîka)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Espanyöl (Ekuatëre)",
  "es_ES": "Espanyöl (Espânye)",
  "es_GQ": "Espanyöl (Ginëe tî Ekuatëre)",
  "es_GT": "Espanyöl (Guatêmälä)",
  "es_HN": "Espanyöl (Honduräsi)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Espanyöl (Mekisîki)",
  "es_NI": "Espanyöl (Nikaragua)",
  "es_PA": "Espanyöl (Panama)",
  "es_PE": "Espanyöl (Perüu)",
  "es_PH": "Espanyöl (Filipîni)",
  "es_PR": "Espanyöl (Porto Rîko)",
  "es_PY": "Espanyöl (Paraguëe)",
  "es_SV": "Espanyöl (Salvadöro)",
  "es_US": "Espanyöl (ÂLeaa-Ôko tî Amerika)",
  "es_UY": "Espanyöl (Uruguëe)",
  "es_VE": "Espanyöl (Venezueläa)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Farsî",
  "fa_AF": "Farsî (Faganïta, Afganïstäan)",
  "fa_IR": "Farsî (Iräan)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Farânzi",
  "fr_BE": "Farânzi (Bêleze, Belezîki)",
  "fr_BF": "Farânzi (Burkina Faso)",
  "fr_BI": "Farânzi (Burundïi)",
  "fr_BJ": "Farânzi (Benëen)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Farânzi (Kanadäa)",
  "fr_CD": "Farânzi (Ködörösêse tî Ngunuhalëzo tî kongö)",
  "fr_CF": "Farânzi (Ködörösêse tî Bêafrîka)",
  "fr_CG": "Farânzi (Kongö)",
  "fr_CH": "Farânzi (Sûîsi)",
  "fr_CI": "Farânzi (Kôdivüära)",
  "fr_CM": "Farânzi (Kamerûne)",
  "fr_DJ": "Farânzi (Dibutùii)",
  "fr_DZ": "Farânzi (Alzerïi)",
  "fr_FR": "Farânzi (Farânzi)",
  "fr_GA": "Farânzi (Gaböon)",
  "fr_GF": "Farânzi (Güyâni tî farânzi)",
  "fr_GN": "Farânzi (Ginëe)",
  "fr_GP": "Farânzi (Guadelûpu)",
  "fr_GQ": "Farânzi (Ginëe tî Ekuatëre)",
  "fr_HT": "Farânzi (Haitïi)",
  "fr_KM": "Farânzi (Kömôro)",
  "fr_LU": "Farânzi (Lugzambûru)",
  "fr_MA": "Farânzi (Marôko)",
  "fr_MC": "Farânzi (Monaköo)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Farânzi (Madagaskära)",
  "fr_ML": "Farânzi (Malïi)",
  "fr_MQ": "Farânzi (Märtïnîki)",
  "fr_MR": "Farânzi (Moritanïi)",
  "fr_MU": "Farânzi (Mörîsi)",
  "fr_NC": "Farânzi (Finî Kaledonïi)",
  "fr_NE": "Farânzi (Nizëre)",
  "fr_PF": "Farânzi (Polinezïi tî farânzi)",
  "fr_PM": "Farânzi (Sên-Pyêre na Mikelöon)",
  "fr_RE": "Farânzi (Reinïon)",
  "fr_RW": "Farânzi (Ruandäa)",
  "fr_SC": "Farânzi (Sëyshêle)",
  "fr_SN": "Farânzi (Senegäle)",
  "fr_SY": "Farânzi (Sirïi)",
  "fr_TD": "Farânzi (Tyâde)",
  "fr_TG": "Farânzi (Togö)",
  "fr_TN": "Farânzi (Tunizïi)",
  "fr_VU": "Farânzi (Vanuatü)",
  "fr_WF": "Farânzi (Walîsi na Futuna)",
  "fr_YT": "Farânzi (Mäyôte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Haüsä",
  "ha_GH": "Haüsä (Ganäa)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Haüsä (Nizëre)",
  "ha_NG": "Haüsä (Nizerïa)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "Hîndi",
  "hi_IN": "Hîndi (Ênnde)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "Hongruäa",
  "hu_HU": "Hongruäa (Hongirùii)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Enndonezïi",
  "id_ID": "Enndonezïi (Ênndonezïi)",
  "ie": "Interlingue",
  "ig": "Ïgbö",
  "ig_NG": "Ïgbö (Nizerïa)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "Ênnde",
  "it_CH": "Ênnde (Sûîsi)",
  "it_IT": "Ênnde (Italùii)",
  "it_SM": "Ênnde (Sên-Marëen)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Zaponëe",
  "ja_JP": "Zaponëe (Zapöon)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Zavanëe",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Kmêre",
  "km_KH": "Kmêre (Kämbôzi)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Koreyëen",
  "ko_KP": "Koreyëen (Korëe tî Banga)",
  "ko_KR": "Koreyëen (Korëe tî Mbongo)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Malëe",
  "ms_BN": "Malëe (Brunêi)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malëe (Malezïi)",
  "ms_SG": "Malëe (Sïngäpûru)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Miamära, Birimäni",
  "my_MM": "Miamära, Birimäni (Myämâra)",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "Nepalëe",
  "ne_IN": "Nepalëe (Ênnde)",
  "ne_NP": "Nepalëe (Nëpâli)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Holandëe",
  "nl_AW": "Holandëe (Arûba)",
  "nl_BE": "Holandëe (Bêleze, Belezîki)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Holandëe (Holände)",
  "nl_SR": "Holandëe (Surinäm)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "Penzäbï",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Penzäbï (Ênnde)",
  "pa_PK": "Penzäbï (Pakistäan)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Polonëe",
  "pl_PL": "Polonëe (Pölôni)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Portugëe, Pûra",
  "pt_AO": "Portugëe, Pûra (Angoläa)",
  "pt_BR": "Portugëe, Pûra (Brezîli)",
  "pt_CV": "Portugëe, Pûra (Azûâ tî Kâpo-Vêre)",
  "pt_GW": "Portugëe, Pûra (Gninëe-Bisau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Portugëe, Pûra (Mözämbîka)",
  "pt_PT": "Portugëe, Pûra (Pörtugäle, Ködörö Pûra)",
  "pt_ST": "Portugëe, Pûra (Sâô Tömê na Prinsîpe)",
  "pt_TL": "Portugëe, Pûra (Timôro tî Tö)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Rumëen",
  "ro_MD": "Rumëen (Moldavùii)",
  "ro_RO": "Rumëen (Rumanïi)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Rûsi",
  "ru_BY": "Rûsi (Belarüsi)",
  "ru_KG": "Rûsi (Kirigizitùaan)",
  "ru_KZ": "Rûsi (Kazakisitäan)",
  "ru_MD": "Rûsi (Moldavùii)",
  "ru_RU": "Rûsi (Rusïi)",
  "ru_UA": "Rûsi (Ukrêni)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Ruandäa",
  "rw_RW": "Ruandäa (Ruandäa)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sängö",
  "sg_CF": "Sängö (Ködörösêse tî Bêafrîka)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somalïi",
  "so_DJ": "Somalïi (Dibutùii)",
  "so_ET": "Somalïi (Etiopïi)",
  "so_KE": "Somalïi (Kenyäa)",
  "so_SO": "Somalïi (Somalïi)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Sueduäa",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Sueduäa (Fëlânde)",
  "sv_SE": "Sueduäa (Suêde)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Tämûli",
  "ta_IN": "Tämûli (Ênnde)",
  "ta_LK": "Tämûli (Sirî-Lanka)",
  "ta_MY": "Tämûli (Malezïi)",
  "ta_SG": "Tämûli (Sïngäpûru)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "Thâi",
  "th_TH": "Thâi (Tailânde)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Tûrûku",
  "tr_CY": "Tûrûku (Sîpri)",
  "tr_TR": "Tûrûku (Turukïi)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "Ukrêni",
  "uk_UA": "Ukrêni (Ukrêni)",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "Ûrdu",
  "ur_IN": "Ûrdu (Ênnde)",
  "ur_PK": "Ûrdu (Pakistäan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Vietnäm",
  "vi_VN": "Vietnäm (Vietnäm)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benëen)",
  "yo_NG": "Yoruba (Nizerïa)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "Shinuäa",
  "zh_CN": "Shinuäa (Shîna)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Shinuäa (Sïngäpûru)",
  "zh_TW": "Shinuäa (Tâiwâni)",
  "zu": "Zûlu",
  "zu_ZA": "Zûlu (Mbongo-Afrîka)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
