const names = {
  "AD": "Andora",
  "AE": "United Arab Emirates",
  "AF": "Afuganistani",
  "AG": "Antigua ne Barbuda",
  "AI": "Anguila",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Netherlands Antilles",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Ajentina",
  "AS": "Samoa ye Amerika",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Arubha",
  "AX": "Åland Islands",
  "AZ": "Azabajani",
  "BA": "Boznia ne Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladeshi",
  "BE": "Beljium",
  "BF": "Bukinafaso",
  "BG": "Bulgaria",
  "BH": "Bahareni",
  "BI": "Burundi",
  "BJ": "Benini",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Burunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazil",
  "BS": "Bahama",
  "BT": "Bhutani",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarusi",
  "BZ": "Belize",
  "CA": "Kanada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Democratic Republic of the Congo",
  "CF": "Central African Republic",
  "CG": "Kongo",
  "CH": "Switzerland",
  "CI": "Ivory Coast",
  "CK": "Zvitsuwa zveCook",
  "CL": "Chile",
  "CM": "Kameruni",
  "CN": "China",
  "CO": "Kolombia",
  "CR": "Kostarika",
  "CS": "Serbia and Montenegro",
  "CU": "Cuba",
  "CV": "Zvitsuwa zveCape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Aljeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Etiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Zvitsuwa zveFalklands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Honduras",
  "HR": "Korasia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Izuraeri",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Kambodia",
  "KI": "Kiribati",
  "KM": "Komoro",
  "KN": "Saint Kitts and Nevis",
  "KP": "Korea, North",
  "KR": "Korea, South",
  "KW": "Kuwait",
  "KY": "Zvitsuwa zveCayman",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagascar",
  "MH": "Zvitsuwa zveMarshall",
  "MK": "North Makedhonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao SAR China",
  "MP": "Zvitsuwa zvekumaodzanyemba eMariana",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Chitsuwa cheNorfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territories",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Zvitsuwa zvaSolomon",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Saint Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "São Tomé and Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Swaziland",
  "TC": "Zvitsuwa zveTurk neCaico",
  "TD": "Chadi",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "East Timor",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "U.S. Outlying Islands",
  "US": "Amerika",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican State",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela",
  "VG": "Zvitsuwa zveHingirandi",
  "VI": "Zvitsuwa zveAmerika",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "chiAkani",
  "ak_GH": "chiAkani (Ghana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "chiAmaric",
  "am_ET": "chiAmaric (Etiopia)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "chiArabu",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "chiArabu (United Arab Emirates)",
  "ar_BH": "chiArabu (Bahareni)",
  "ar_DJ": "chiArabu (Djibouti)",
  "ar_DZ": "chiArabu (Aljeria)",
  "ar_EG": "chiArabu (Egypt)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "chiArabu (Eritrea)",
  "ar_IL": "chiArabu (Izuraeri)",
  "ar_IQ": "chiArabu (Iraq)",
  "ar_JO": "chiArabu (Jordan)",
  "ar_KM": "chiArabu (Komoro)",
  "ar_KW": "chiArabu (Kuwait)",
  "ar_LB": "chiArabu (Lebanon)",
  "ar_LY": "chiArabu (Libya)",
  "ar_MA": "chiArabu (Morocco)",
  "ar_MR": "chiArabu (Mauritania)",
  "ar_OM": "chiArabu (Oman)",
  "ar_PS": "Arabic (Palestinian Territories)",
  "ar_QA": "chiArabu (Qatar)",
  "ar_SA": "chiArabu (Saudi Arabia)",
  "ar_SD": "chiArabu (Sudan)",
  "ar_SO": "chiArabu (Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "chiArabu (Syria)",
  "ar_TD": "chiArabu (Chadi)",
  "ar_TN": "chiArabu (Tunisia)",
  "ar_YE": "chiArabu (Yemen)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "chiBelarusi",
  "be_BY": "chiBelarusi (Belarusi)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "chiBulgarian",
  "bg_BG": "chiBulgarian (Bulgaria)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "chiBengali",
  "bn_BD": "chiBengali (Bangladeshi)",
  "bn_IN": "chiBengali (India)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "chiCzech",
  "cs_CZ": "chiCzech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "chiJerimani",
  "de_AT": "chiJerimani (Austria)",
  "de_BE": "chiJerimani (Beljium)",
  "de_CH": "chiJerimani (Switzerland)",
  "de_DE": "chiJerimani (Germany)",
  "de_LI": "chiJerimani (Liechtenstein)",
  "de_LU": "chiJerimani (Luxembourg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "chiGreek",
  "el_CY": "chiGreek (Cyprus)",
  "el_GR": "chiGreek (Greece)",
  "elx": "Elamite",
  "en": "Chirungu",
  "en_AG": "Chirungu (Antigua ne Barbuda)",
  "en_AI": "Chirungu (Anguila)",
  "en_AS": "Chirungu (Samoa ye Amerika)",
  "en_AU": "Chirungu (Australia)",
  "en_BB": "Chirungu (Barbados)",
  "en_BE": "Chirungu (Beljium)",
  "en_BM": "Chirungu (Bermuda)",
  "en_BS": "Chirungu (Bahama)",
  "en_BW": "Chirungu (Botswana)",
  "en_BZ": "Chirungu (Belize)",
  "en_CA": "Chirungu (Kanada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Chirungu (Zvitsuwa zveCook)",
  "en_CM": "Chirungu (Kameruni)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Chirungu (Dominica)",
  "en_ER": "Chirungu (Eritrea)",
  "en_FJ": "Chirungu (Fiji)",
  "en_FK": "Chirungu (Zvitsuwa zveFalklands)",
  "en_FM": "Chirungu (Micronesia)",
  "en_GB": "Chirungu (United Kingdom)",
  "en_GD": "Chirungu (Grenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Chirungu (Ghana)",
  "en_GI": "Chirungu (Gibraltar)",
  "en_GM": "Chirungu (Gambia)",
  "en_GU": "Chirungu (Guam)",
  "en_GY": "Chirungu (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Chirungu (Ireland)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Chirungu (India)",
  "en_IO": "Chirungu (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "Chirungu (Jamaica)",
  "en_KE": "Chirungu (Kenya)",
  "en_KI": "Chirungu (Kiribati)",
  "en_KN": "Chirungu (Saint Kitts and Nevis)",
  "en_KY": "Chirungu (Zvitsuwa zveCayman)",
  "en_LC": "Chirungu (Saint Lucia)",
  "en_LR": "Chirungu (Liberia)",
  "en_LS": "Chirungu (Lesotho)",
  "en_MG": "Chirungu (Madagascar)",
  "en_MH": "Chirungu (Zvitsuwa zveMarshall)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Chirungu (Zvitsuwa zvekumaodzanyemba eMariana)",
  "en_MS": "Chirungu (Montserrat)",
  "en_MT": "Chirungu (Malta)",
  "en_MU": "Chirungu (Mauritius)",
  "en_MW": "Chirungu (Malawi)",
  "en_MY": "Chirungu (Malaysia)",
  "en_NA": "Chirungu (Namibia)",
  "en_NF": "Chirungu (Chitsuwa cheNorfolk)",
  "en_NG": "Chirungu (Nigeria)",
  "en_NR": "Chirungu (Nauru)",
  "en_NU": "Chirungu (Niue)",
  "en_NZ": "Chirungu (New Zealand)",
  "en_PG": "Chirungu (Papua New Guinea)",
  "en_PH": "Chirungu (Philippines)",
  "en_PK": "Chirungu (Pakistan)",
  "en_PN": "Chirungu (Pitcairn)",
  "en_PR": "Chirungu (Puerto Rico)",
  "en_PW": "Chirungu (Palau)",
  "en_RW": "Chirungu (Rwanda)",
  "en_SB": "Chirungu (Zvitsuwa zvaSolomon)",
  "en_SC": "Chirungu (Seychelles)",
  "en_SD": "Chirungu (Sudan)",
  "en_SG": "Chirungu (Singapore)",
  "en_SH": "Chirungu (Saint Helena)",
  "en_SL": "Chirungu (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Chirungu (Swaziland)",
  "en_TC": "Chirungu (Zvitsuwa zveTurk neCaico)",
  "en_TK": "Chirungu (Tokelau)",
  "en_TO": "Chirungu (Tonga)",
  "en_TT": "Chirungu (Trinidad and Tobago)",
  "en_TV": "Chirungu (Tuvalu)",
  "en_TZ": "Chirungu (Tanzania)",
  "en_UG": "Chirungu (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Chirungu (Amerika)",
  "en_VC": "Chirungu (Saint Vincent and the Grenadines)",
  "en_VG": "Chirungu (Zvitsuwa zveHingirandi)",
  "en_VI": "Chirungu (Zvitsuwa zveAmerika)",
  "en_VU": "Chirungu (Vanuatu)",
  "en_WS": "Chirungu (Samoa)",
  "en_ZA": "Chirungu (South Africa)",
  "en_ZM": "Chirungu (Zambia)",
  "en_ZW": "Chirungu (Zimbabwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "chiSpanish",
  "es_419": "Latin American Spanish",
  "es_AR": "chiSpanish (Ajentina)",
  "es_BO": "chiSpanish (Bolivia)",
  "es_CL": "chiSpanish (Chile)",
  "es_CO": "chiSpanish (Kolombia)",
  "es_CR": "chiSpanish (Kostarika)",
  "es_CU": "chiSpanish (Cuba)",
  "es_DO": "chiSpanish (Dominican Republic)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "chiSpanish (Ecuador)",
  "es_ES": "chiSpanish (Spain)",
  "es_GQ": "chiSpanish (Equatorial Guinea)",
  "es_GT": "chiSpanish (Guatemala)",
  "es_HN": "chiSpanish (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "chiSpanish (Mexico)",
  "es_NI": "chiSpanish (Nicaragua)",
  "es_PA": "chiSpanish (Panama)",
  "es_PE": "chiSpanish (Peru)",
  "es_PH": "chiSpanish (Philippines)",
  "es_PR": "chiSpanish (Puerto Rico)",
  "es_PY": "chiSpanish (Paraguay)",
  "es_SV": "chiSpanish (El Salvador)",
  "es_US": "chiSpanish (Amerika)",
  "es_UY": "chiSpanish (Uruguay)",
  "es_VE": "chiSpanish (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "chiPeshiya",
  "fa_AF": "chiPeshiya (Afuganistani)",
  "fa_IR": "chiPeshiya (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "chiFurenchi",
  "fr_BE": "chiFurenchi (Beljium)",
  "fr_BF": "chiFurenchi (Bukinafaso)",
  "fr_BI": "chiFurenchi (Burundi)",
  "fr_BJ": "chiFurenchi (Benini)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "chiFurenchi (Kanada)",
  "fr_CD": "chiFurenchi (Democratic Republic of the Congo)",
  "fr_CF": "chiFurenchi (Central African Republic)",
  "fr_CG": "chiFurenchi (Kongo)",
  "fr_CH": "chiFurenchi (Switzerland)",
  "fr_CI": "chiFurenchi (Ivory Coast)",
  "fr_CM": "chiFurenchi (Kameruni)",
  "fr_DJ": "chiFurenchi (Djibouti)",
  "fr_DZ": "chiFurenchi (Aljeria)",
  "fr_FR": "chiFurenchi (France)",
  "fr_GA": "chiFurenchi (Gabon)",
  "fr_GF": "chiFurenchi (French Guiana)",
  "fr_GN": "chiFurenchi (Guinea)",
  "fr_GP": "chiFurenchi (Guadeloupe)",
  "fr_GQ": "chiFurenchi (Equatorial Guinea)",
  "fr_HT": "chiFurenchi (Haiti)",
  "fr_KM": "chiFurenchi (Komoro)",
  "fr_LU": "chiFurenchi (Luxembourg)",
  "fr_MA": "chiFurenchi (Morocco)",
  "fr_MC": "chiFurenchi (Monaco)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "chiFurenchi (Madagascar)",
  "fr_ML": "chiFurenchi (Mali)",
  "fr_MQ": "chiFurenchi (Martinique)",
  "fr_MR": "chiFurenchi (Mauritania)",
  "fr_MU": "chiFurenchi (Mauritius)",
  "fr_NC": "chiFurenchi (New Caledonia)",
  "fr_NE": "chiFurenchi (Niger)",
  "fr_PF": "chiFurenchi (French Polynesia)",
  "fr_PM": "chiFurenchi (Saint Pierre and Miquelon)",
  "fr_RE": "chiFurenchi (Réunion)",
  "fr_RW": "chiFurenchi (Rwanda)",
  "fr_SC": "chiFurenchi (Seychelles)",
  "fr_SN": "chiFurenchi (Senegal)",
  "fr_SY": "chiFurenchi (Syria)",
  "fr_TD": "chiFurenchi (Chadi)",
  "fr_TG": "chiFurenchi (Togo)",
  "fr_TN": "chiFurenchi (Tunisia)",
  "fr_VU": "chiFurenchi (Vanuatu)",
  "fr_WF": "chiFurenchi (Wallis and Futuna)",
  "fr_YT": "chiFurenchi (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "chiHausa",
  "ha_GH": "chiHausa (Ghana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "chiHausa (Niger)",
  "ha_NG": "chiHausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "chiHindi",
  "hi_IN": "chiHindi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "chiHungari",
  "hu_HU": "chiHungari (Hungary)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "chiIndonesia",
  "id_ID": "chiIndonesia (Indonesia)",
  "ie": "Interlingue",
  "ig": "chiIgbo",
  "ig_NG": "chiIgbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "chiTariana",
  "it_CH": "chiTariana (Switzerland)",
  "it_IT": "chiTariana (Italy)",
  "it_SM": "chiTariana (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "chiJapani",
  "ja_JP": "chiJapani (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "chiJava",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "chiKhema",
  "km_KH": "chiKhema (Kambodia)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "chiKoria",
  "ko_KP": "chiKoria (Korea, North)",
  "ko_KR": "chiKoria (Korea, South)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "chiMalay",
  "ms_BN": "chiMalay (Burunei)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "chiMalay (Malaysia)",
  "ms_SG": "chiMalay (Singapore)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "chiBurma",
  "my_MM": "chiBurma (Myanmar)",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "chiNepali",
  "ne_IN": "chiNepali (India)",
  "ne_NP": "chiNepali (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "chiDutch",
  "nl_AW": "chiDutch (Arubha)",
  "nl_BE": "chiDutch (Beljium)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "chiDutch (Netherlands)",
  "nl_SR": "chiDutch (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "chiPunjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "chiPunjabi (India)",
  "pa_PK": "chiPunjabi (Pakistan)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "chiPolish",
  "pl_PL": "chiPolish (Poland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "chiPutukezi",
  "pt_AO": "chiPutukezi (Angola)",
  "pt_BR": "chiPutukezi (Brazil)",
  "pt_CV": "chiPutukezi (Zvitsuwa zveCape Verde)",
  "pt_GW": "chiPutukezi (Guinea-Bissau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "chiPutukezi (Mozambique)",
  "pt_PT": "chiPutukezi (Portugal)",
  "pt_ST": "chiPutukezi (São Tomé and Príncipe)",
  "pt_TL": "chiPutukezi (East Timor)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "chiRomanian",
  "ro_MD": "chiRomanian (Moldova)",
  "ro_RO": "chiRomanian (Romania)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "chiRashiya",
  "ru_BY": "chiRashiya (Belarusi)",
  "ru_KG": "chiRashiya (Kyrgyzstan)",
  "ru_KZ": "chiRashiya (Kazakhstan)",
  "ru_MD": "chiRashiya (Moldova)",
  "ru_RU": "chiRashiya (Russia)",
  "ru_UA": "chiRashiya (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "chiRwanda",
  "rw_RW": "chiRwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "chiShona",
  "sn_ZW": "chiShona (Zimbabwe)",
  "snk": "Soninke",
  "so": "chiSomali",
  "so_DJ": "chiSomali (Djibouti)",
  "so_ET": "chiSomali (Etiopia)",
  "so_KE": "chiSomali (Kenya)",
  "so_SO": "chiSomali (Somalia)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "chiSwedish",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "chiSwedish (Finland)",
  "sv_SE": "chiSwedish (Sweden)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "chiTamil",
  "ta_IN": "chiTamil (India)",
  "ta_LK": "chiTamil (Sri Lanka)",
  "ta_MY": "chiTamil (Malaysia)",
  "ta_SG": "chiTamil (Singapore)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "chiThai",
  "th_TH": "chiThai (Thailand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "chiTurkish",
  "tr_CY": "chiTurkish (Cyprus)",
  "tr_TR": "chiTurkish (Turkey)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "chiUkrenia",
  "uk_UA": "chiUkrenia (Ukraine)",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "chiUrdu",
  "ur_IN": "chiUrdu (India)",
  "ur_PK": "chiUrdu (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "chiVietnam",
  "vi_VN": "chiVietnam (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "chiYoruba",
  "yo_BJ": "chiYoruba (Benini)",
  "yo_NG": "chiYoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "chiChinese",
  "zh_CN": "chiChinese (China)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "chiChinese (Singapore)",
  "zh_TW": "chiChinese (Taiwan)",
  "zu": "chiZulu",
  "zu_ZA": "chiZulu (South Africa)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
