const names = {
  "ace": "achinese",
  "ach": "acoli",
  "ae": "avestan",
  "ain": "ainu",
  "akk": "akkadian",
  "arn": "araukanski",
  "arw": "arawak",
  "ay": "aymara",
  "bal": "baluchi",
  "ban": "balinezijski",
  "bik": "bikol",
  "bn": "bengalski",
  "bo": "tibetanski",
  "bua": "buriat",
  "chb": "chibcha",
  "chg": "chagatai",
  "chm": "mari",
  "chr": "čeroki",
  "cv": "chuvash",
  "dsb": "lužičkosrpski",
  "dum": "nizozemski, srednji",
  "enm": "engleski, srednji",
  "ff": "fulah",
  "fil": "filipino",
  "frc": "Cajun French",
  "frm": "francuski, srednji",
  "fur": "friulski",
  "gan": "Gan Chinese",
  "gd": "škotski-galski",
  "gez": "staroetiopski",
  "gmh": "njemački, srednji visoki",
  "gn": "guarani",
  "goh": "staronjemački, visoki",
  "got": "gothic",
  "hak": "Hakka Chinese",
  "hil": "hiligaynon",
  "hsn": "Xiang Chinese",
  "ht": "kreolski",
  "ii": "sichuan yi",
  "kac": "kachin",
  "kbd": "kabardian",
  "kn": "kannadski",
  "koi": "komski ili permski",
  "ky": "kirgiški",
  "li": "limburgish",
  "mga": "irski, srednji",
  "moh": "mohawk",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nb": "književni norveški",
  "nn": "novonorveški",
  "nso": "sjeverni sotho",
  "nus": "nuer",
  "ny": "nyanja",
  "prg": "Prussian",
  "ps": "paštu",
  "qu": "kečua",
  "rm": "romanš",
  "sat": "santali",
  "sd": "sindhi",
  "se": "južni sami",
  "sma": "sjeverni sami",
  "te": "telugu",
  "tmh": "tamashek",
  "tyv": "tuvinian",
  "tzm": "marokanski tamazight",
  "vot": "votic",
  "wae": "walser",
  "wbp": "Warlpiri",
  "wo": "wolof",
  "wuu": "Wu Chinese",
  "yo": "joruba",
  "zap": "zapotec",
  "zbl": "blissymbols",
  "zgh": "standardni marokanski tamazight",
  "zh_Hans": "kineski (pojednostavljeno pismo)",
  "zh_Hant": "kineski (tradicionalno pismo)"
};
