const names = {
  "AF": "Afghanistan",
  "AG": "Antigua & Barbuda",
  "AQ": "Antarctica",
  "AT": "Austria",
  "AX": "Åland Islands",
  "BA": "Bosnia & Herzegovina",
  "BE": "Belgium",
  "BL": "St. Barthélemy",
  "BV": "Bouvet Island",
  "BY": "Belarus",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo - Kinshasa",
  "CG": "Congo - Brazzaville",
  "CH": "Switzerland",
  "CK": "Cook Islands",
  "CM": "Cameroon",
  "CN": "China",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DK": "Denmark",
  "DZ": "Algeria",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ES": "Spain",
  "FI": "Finland",
  "FK": "Falkland Islands",
  "FO": "Faroe Islands",
  "FR": "France",
  "GB": "United Kingdom",
  "GR": "Greece",
  "HK": "Hong Kong SAR China",
  "HR": "Croatia",
  "HU": "Hungary",
  "IE": "Ireland",
  "IQ": "Iraq",
  "IS": "Iceland",
  "IT": "Italy",
  "JO": "Jordan",
  "JP": "Japan",
  "KH": "Cambodia",
  "KN": "St. Kitts & Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LB": "Lebanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LV": "Latvia",
  "MA": "Morocco",
  "MF": "St. Martin",
  "MG": "Madagascar",
  "MM": "Myanmar (Burma)",
  "MO": "Macao SAR China",
  "MX": "Mexico",
  "MZ": "Mozambique",
  "NC": "New Caledonia",
  "NL": "Netherlands",
  "NO": "Norway",
  "NZ": "New Zealand",
  "PG": "Papua New Guinea",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "St. Pierre & Miquelon",
  "PT": "Portugal",
  "QA": "Qatar",
  "RO": "Romania",
  "RU": "Russia",
  "SD": "Sudan",
  "SE": "Sweden",
  "SH": "St. Helena",
  "SJ": "Svalbard & Jan Mayen",
  "SS": "South Sudan",
  "ST": "São Tomé & Príncipe",
  "SZ": "Eswatini",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TR": "Turkey",
  "TT": "Trinidad & Tobago",
  "UA": "Ukraine",
  "US": "United States",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "WF": "Wallis & Futuna",
  "YE": "Yemen",
  "ZA": "South Africa",
  "ar": "Arabic",
  "az": "Azerbaijani",
  "bn": "Bengali",
  "cs": "Czech",
  "da": "Danish",
  "de": "German",
  "en": "English",
  "eo": "Esperanto",
  "es": "Spanish",
  "et": "Estonian",
  "fa": "Persian",
  "fi": "Finnish",
  "fo": "Faroese",
  "fr": "French",
  "ga": "Irish",
  "he": "Hebrew",
  "hi": "Hindi",
  "id": "Indonesian",
  "is": "Icelandic",
  "it": "Italian",
  "ja": "Japanese",
  "ko": "Korean",
  "ku": "Kurdish",
  "la": "Latin",
  "lt": "Lithuanian",
  "lv": "Latvian",
  "mg": "Malagasy",
  "mi": "Maori",
  "nl": "Dutch",
  "pl": "Polish",
  "ps": "Pashto",
  "pt": "Portuguese",
  "ro": "Romanian",
  "ru": "Russian",
  "sk": "Slovak",
  "sv": "Swedish",
  "sw": "Swahili",
  "th": "Thai",
  "tr": "Turkish",
  "uk": "Ukrainian",
  "und": "Unknown Language",
  "ur": "Urdu",
  "vi": "Vietnamese",
  "zh": "Chinese"
};
