const names = {
  "aa": "Afar",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ain": "Ainu",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar_001": "Kiarabu Sanifu cha Kisasa",
  "arc": "Aramaic",
  "arp": "Arapaho",
  "arq": "Kiarabu cha Kialjeria",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "ay": "Kiaimara",
  "az": "Kiazabajani",
  "ba": "Kibashkir",
  "ban": "Balinese",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbj": "Ghomala",
  "bej": "Beja",
  "bfd": "Bafut",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bkm": "Kom",
  "bla": "Siksika",
  "brx": "brx",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chy": "Cheyenne",
  "cop": "Coptic",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dgr": "Dogrib",
  "dsb": "Kidolnoserbski",
  "dyu": "Dyula",
  "dzg": "Dazaga",
  "efi": "Kiefiki",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "es_419": "Latin American Spanish",
  "eu": "Kibasque",
  "ewo": "Ewondo",
  "ff": "Fulah",
  "fi": "Kifinlandi",
  "fon": "Fon",
  "fro": "Old French",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "gaa": "Kiga",
  "gag": "Kigagauzi",
  "gba": "Gbaya",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gor": "Gorontalo",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hr": "Kroeshia",
  "hsb": "hsb",
  "hu": "Kihungari",
  "hz": "Herero",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ie": "Interlingue",
  "ii": "Sichuan Yi",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Kiaisilandi",
  "iu": "iu",
  "kaj": "Jju",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kha": "Khasi",
  "khq": "Kikoyra Chiini",
  "kj": "Kuanyama",
  "kk": "Kikazaki",
  "kkj": "Kako",
  "koi": "Kikomipermyak",
  "kok": "kok",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "ksh": "Colognian",
  "ky": "Kikirigizi",
  "lad": "Ladino",
  "lam": "Chilamba",
  "lez": "Lezghian",
  "lol": "Mongo",
  "lun": "Lunda",
  "lus": "Mizo",
  "mad": "Madurese",
  "maf": "Mafa",
  "mai": "Maithili",
  "mak": "Makasar",
  "mde": "Maba",
  "mdf": "Moksha",
  "men": "Mende",
  "mg": "Malagasi",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Kimasedonia",
  "ml": "Kimalayalam",
  "mni": "Manipuri",
  "moh": "Kimohoki",
  "mos": "Mossi",
  "ms": "Kimalesia",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "nb": "Kibokmal cha Norwe",
  "nds": "Low German",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl_BE": "Kiholanzi (Ubelgiji)",
  "nn": "Kinorwe Kipya",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "nog": "Nogai",
  "nr": "South Ndebele",
  "nv": "Navajo",
  "nym": "Nyamwezi",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "peo": "Old Persian",
  "prg": "Prussian",
  "qu": "Kiquechua",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "root": "Root",
  "rup": "Aromanian",
  "rwk": "Kirwo",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sh": "Serbo-Croatian",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "snk": "Soninke",
  "srn": "Sranan Tongo",
  "ssy": "Saho",
  "st": "Kisotho cha Kusini",
  "sus": "Susu",
  "swb": "Comorian",
  "syr": "Syriac",
  "ta": "Kitamil",
  "tem": "Timne",
  "th": "Kitailandi",
  "tig": "Tigre",
  "trv": "Taroko",
  "tvl": "Tuvalu",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Kiuiguri",
  "uk": "Kiukrania",
  "vo": "Volapük",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "xal": "Kalmyk",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Kiyidi",
  "yue": "Cantonese",
  "zgh": "Tamaziti Msingi ya Kimoroko",
  "zun": "Zuni",
  "zza": "Zaza"
};
