const names = {
  "001": "Monde",
  "002": "Afrique",
  "003": "Amérique du Nord",
  "005": "Amérique du Sud",
  "009": "Océanie",
  "011": "Afrique occidentale",
  "013": "Amérique centrale",
  "014": "Afrique orientale",
  "015": "Afrique septentrionale",
  "017": "Afrique centrale",
  "018": "Afrique australe",
  "019": "Amériques",
  "021": "Amérique septentrionale",
  "029": "Caraïbes",
  "030": "Asie de l’Est",
  "034": "Asie du Sud",
  "035": "Asie du Sud-Est",
  "039": "Europe du Sud",
  "053": "Australasie",
  "054": "Mélanésie",
  "057": "région micronésienne",
  "061": "Polynésie",
  "062": "Asie centrale du Sud",
  "142": "Asie",
  "143": "Asie centrale",
  "145": "Asie de l’Ouest",
  "150": "Europe",
  "151": "Europe de l’Est",
  "154": "Europe du Nord",
  "155": "Europe de l’Ouest",
  "172": "Communauté des États indépendants",
  "200": "Tchécoslovaquie",
  "202": "Afrique subsaharienne",
  "419": "Amérique latine",
  "830": "Îles anglo-normandes",
  "AC": "Île de l’Ascension",
  "AD": "Andorre",
  "AE": "Émirats arabes unis",
  "AF": "Afghanistan",
  "AG": "Antigua-et-Barbuda",
  "AI": "Anguilla",
  "AL": "Albanie",
  "AM": "Arménie",
  "AN": "Antilles néerlandaises",
  "AO": "Angola",
  "AQ": "Antarctique",
  "AR": "Argentine",
  "AS": "Samoa américaines",
  "AT": "Autriche",
  "AU": "Australie",
  "AW": "Aruba",
  "AX": "Îles Åland",
  "AZ": "Azerbaïdjan",
  "Adlm": "adlam",
  "Afak": "afaka",
  "Aghb": "aghbanien",
  "Ahom": "ahom",
  "Arab": "arabe",
  "Aran": "nastaliq",
  "Armi": "araméen impérial",
  "Armn": "arménien",
  "Avst": "avestique",
  "BA": "Bosnie-Herzégovine",
  "BB": "Barbade",
  "BD": "Bangladesh",
  "BE": "Belgique",
  "BF": "Burkina Faso",
  "BG": "Bulgarie",
  "BH": "Bahreïn",
  "BI": "Burundi",
  "BJ": "Bénin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermudes",
  "BN": "Brunéi Darussalam",
  "BO": "Bolivie",
  "BQ": "Pays-Bas caribéens",
  "BR": "Brésil",
  "BS": "Bahamas",
  "BT": "Bhoutan",
  "BV": "Île Bouvet",
  "BW": "Botswana",
  "BY": "Biélorussie",
  "BZ": "Belize",
  "Bali": "balinais",
  "Bamu": "bamoun",
  "Bass": "bassa",
  "Batk": "batak",
  "Beng": "bengali",
  "Bhks": "bhaïksouki",
  "Blis": "symboles Bliss",
  "Bopo": "bopomofo",
  "Brah": "brâhmî",
  "Brai": "braille",
  "Bugi": "bouguis",
  "Buhd": "bouhide",
  "CA": "Canada",
  "CC": "Îles Cocos",
  "CD": "Congo-Kinshasa",
  "CF": "République centrafricaine",
  "CG": "Congo-Brazzaville",
  "CH": "Suisse",
  "CI": "Côte d’Ivoire",
  "CK": "Îles Cook",
  "CL": "Chili",
  "CM": "Cameroun",
  "CN": "Chine",
  "CO": "Colombie",
  "CP": "Île Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbie-et-Monténégro",
  "CU": "Cuba",
  "CV": "Cap-Vert",
  "CW": "Curaçao",
  "CX": "Île Christmas",
  "CY": "Chypre",
  "CZ": "Tchéquie",
  "Cakm": "chakma",
  "Cans": "syllabaire autochtone canadien unifié",
  "Cari": "carien",
  "Cham": "cham",
  "Cher": "cherokee",
  "Chrs": "chorasmien",
  "Cirt": "cirth",
  "Copt": "copte",
  "Cprt": "syllabaire chypriote",
  "Cyrl": "cyrillique",
  "Cyrs": "cyrillique (variante slavonne)",
  "DD": "Allemagne de l'est",
  "DE": "Allemagne",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Danemark",
  "DM": "Dominique",
  "DO": "République dominicaine",
  "DZ": "Algérie",
  "Deva": "dévanagari",
  "Diak": "dives akuru",
  "Dogr": "dogri",
  "Dsrt": "déséret",
  "Dupl": "sténographie Duployé",
  "EA": "Ceuta et Melilla",
  "EC": "Équateur",
  "EE": "Estonie",
  "EG": "Égypte",
  "EH": "Sahara occidental",
  "ER": "Érythrée",
  "ES": "Espagne",
  "ET": "Éthiopie",
  "EU": "Union européenne",
  "EZ": "zone euro",
  "Egyd": "démotique égyptien",
  "Egyh": "hiératique égyptien",
  "Egyp": "hiéroglyphes égyptiens",
  "Elba": "elbasan",
  "Elym": "élymaïque",
  "Ethi": "éthiopique",
  "FI": "Finlande",
  "FJ": "Fidji",
  "FK": "Îles Malouines",
  "FM": "États fédérés de Micronésie",
  "FO": "Îles Féroé",
  "FR": "France",
  "FX": "France métropolitaine",
  "GA": "Gabon",
  "GB": "Royaume-Uni",
  "GD": "Grenade",
  "GE": "Géorgie",
  "GF": "Guyane française",
  "GG": "Guernesey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenland",
  "GM": "Gambie",
  "GN": "Guinée",
  "GP": "Guadeloupe",
  "GQ": "Guinée équatoriale",
  "GR": "Grèce",
  "GS": "Géorgie du Sud et îles Sandwich du Sud",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinée-Bissau",
  "GY": "Guyana",
  "Geok": "géorgien khoutsouri",
  "Geor": "géorgien",
  "Glag": "glagolitique",
  "Gong": "gondi de Gundjala",
  "Gonm": "gondi de Masaram",
  "Goth": "gotique",
  "Gran": "grantha",
  "Grek": "grec",
  "Gujr": "goudjarâtî",
  "Guru": "gourmoukhî",
  "HK": "R.A.S. chinoise de Hong Kong",
  "HM": "Îles Heard et McDonald",
  "HN": "Honduras",
  "HR": "Croatie",
  "HT": "Haïti",
  "HU": "Hongrie",
  "Hanb": "han avec bopomofo",
  "Hang": "hangûl",
  "Hani": "sinogrammes",
  "Hano": "hanounóo",
  "Hans": "simplifié",
  "Hant": "traditionnel",
  "Hatr": "hatrénien",
  "Hebr": "hébreu",
  "Hira": "hiragana",
  "Hluw": "hiéroglyphes hittites",
  "Hmng": "pahawh hmong",
  "Hmnp": "nyiakeng puachue hmong",
  "Hrkt": "katakana ou hiragana",
  "Hung": "ancien hongrois",
  "IC": "Îles Canaries",
  "ID": "Indonésie",
  "IE": "Irlande",
  "IL": "Israël",
  "IM": "Île de Man",
  "IN": "Inde",
  "IO": "Territoire britannique de l’océan Indien",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Islande",
  "IT": "Italie",
  "Inds": "indus",
  "Ital": "ancien italique",
  "JE": "Jersey",
  "JM": "Jamaïque",
  "JO": "Jordanie",
  "JP": "Japon",
  "Jamo": "jamo",
  "Java": "javanais",
  "Jpan": "japonais",
  "Jurc": "jurchen",
  "KE": "Kenya",
  "KG": "Kirghizistan",
  "KH": "Cambodge",
  "KI": "Kiribati",
  "KM": "Comores",
  "KN": "Saint-Christophe-et-Niévès",
  "KP": "Corée du Nord",
  "KR": "Corée du Sud",
  "KW": "Koweït",
  "KY": "Îles Caïmans",
  "KZ": "Kazakhstan",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharochthî",
  "Khmr": "khmer",
  "Khoj": "khodjki",
  "Kits": "petite écriture khitan",
  "Knda": "kannara",
  "Kore": "coréen",
  "Kpel": "kpelle",
  "Kthi": "kaithî",
  "LA": "Laos",
  "LB": "Liban",
  "LC": "Sainte-Lucie",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Libéria",
  "LS": "Lesotho",
  "LT": "Lituanie",
  "LU": "Luxembourg",
  "LV": "Lettonie",
  "LY": "Libye",
  "Lana": "lanna",
  "Laoo": "lao",
  "Latf": "latin (variante brisée)",
  "Latg": "latin (variante gaélique)",
  "Latn": "latin",
  "Lepc": "lepcha",
  "Limb": "limbou",
  "Lina": "linéaire A",
  "Linb": "linéaire B",
  "Lisu": "lisu",
  "Loma": "loma",
  "Lyci": "lycien",
  "Lydi": "lydien",
  "MA": "Maroc",
  "MC": "Monaco",
  "MD": "Moldavie",
  "ME": "Monténégro",
  "MF": "Saint-Martin",
  "MG": "Madagascar",
  "MH": "Îles Marshall",
  "MI": "Îles Midway",
  "MK": "Macédoine du Nord",
  "ML": "Mali",
  "MM": "Myanmar (Birmanie)",
  "MN": "Mongolie",
  "MO": "R.A.S. chinoise de Macao",
  "MP": "Îles Mariannes du Nord",
  "MQ": "Martinique",
  "MR": "Mauritanie",
  "MS": "Montserrat",
  "MT": "Malte",
  "MU": "Maurice",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexique",
  "MY": "Malaisie",
  "MZ": "Mozambique",
  "Mahj": "mahadjani",
  "Maka": "makasar",
  "Mand": "mandéen",
  "Mani": "manichéen",
  "Marc": "mar chen",
  "Maya": "hiéroglyphes mayas",
  "Medf": "medefidrin",
  "Mend": "mendé",
  "Merc": "méroïtique cursif",
  "Mero": "méroïtique",
  "Mlym": "malayalam",
  "Modi": "modi",
  "Mong": "mongol",
  "Moon": "moon",
  "Mroo": "mro",
  "Mtei": "meitei mayek",
  "Mult": "multani",
  "Mymr": "birman",
  "NA": "Namibie",
  "NC": "Nouvelle-Calédonie",
  "NE": "Niger",
  "NF": "Île Norfolk",
  "NG": "Nigéria",
  "NI": "Nicaragua",
  "NL": "Pays-Bas",
  "NO": "Norvège",
  "NP": "Népal",
  "NR": "Nauru",
  "NT": "Zone neutre",
  "NU": "Niue",
  "NZ": "Nouvelle-Zélande",
  "Nand": "nandinagari",
  "Narb": "nord-arabique",
  "Nbat": "nabatéen",
  "Newa": "néwa",
  "Nkgb": "géba",
  "Nkoo": "n’ko",
  "Nshu": "nüshu",
  "OM": "Oman",
  "Ogam": "ogam",
  "Olck": "ol tchiki",
  "Orkh": "orkhon",
  "Orya": "odia",
  "Osge": "osage",
  "Osma": "osmanais",
  "PA": "Panama",
  "PC": "Territoire sous tutelle des îles du Pacifique",
  "PE": "Pérou",
  "PF": "Polynésie française",
  "PG": "Papouasie-Nouvelle-Guinée",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Pologne",
  "PM": "Saint-Pierre-et-Miquelon",
  "PN": "Îles Pitcairn",
  "PR": "Porto Rico",
  "PS": "Territoires palestiniens",
  "PT": "Portugal",
  "PU": "États-Unis Divers Îles du Pacifique",
  "PW": "Palaos",
  "PY": "Paraguay",
  "PZ": "Zone du canal de Panama",
  "Palm": "palmyrénien",
  "Pauc": "paou chin haou",
  "Perm": "ancien permien",
  "Phag": "phags pa",
  "Phli": "pehlevi des inscriptions",
  "Phlp": "pehlevi des psautiers",
  "Phlv": "pehlevi des livres",
  "Phnx": "phénicien",
  "Plrd": "phonétique de Pollard",
  "Prti": "parthe des inscriptions",
  "QA": "Qatar",
  "QO": "régions éloignées de l’Océanie",
  "Qaag": "zawgyi",
  "RE": "La Réunion",
  "RO": "Roumanie",
  "RS": "Serbie",
  "RU": "Russie",
  "RW": "Rwanda",
  "Rjng": "rejang",
  "Rohg": "hanifi",
  "Roro": "rongorongo",
  "Runr": "runique",
  "SA": "Arabie saoudite",
  "SB": "Îles Salomon",
  "SC": "Seychelles",
  "SD": "Soudan",
  "SE": "Suède",
  "SG": "Singapour",
  "SH": "Sainte-Hélène",
  "SI": "Slovénie",
  "SJ": "Svalbard et Jan Mayen",
  "SK": "Slovaquie",
  "SL": "Sierra Leone",
  "SM": "Saint-Marin",
  "SN": "Sénégal",
  "SO": "Somalie",
  "SR": "Suriname",
  "SS": "Soudan du Sud",
  "ST": "Sao Tomé-et-Principe",
  "SU": "Union des Républiques socialistes soviétiques",
  "SV": "Salvador",
  "SX": "Saint-Martin (partie néerlandaise)",
  "SY": "Syrie",
  "SZ": "Eswatini",
  "Samr": "samaritain",
  "Sara": "sarati",
  "Sarb": "sudarabique",
  "Saur": "saurashtra",
  "Sgnw": "écriture des signes",
  "Shaw": "shavien",
  "Shrd": "charada",
  "Sidd": "siddham",
  "Sind": "sindhi",
  "Sinh": "cingalais",
  "Sogd": "sogdien",
  "Sogo": "sogdien ancien",
  "Sora": "sora sompeng",
  "Soyo": "soyombo",
  "Sund": "sundanais",
  "Sylo": "sylotî nâgrî",
  "Syrc": "syriaque",
  "Syre": "syriaque estranghélo",
  "Syrj": "syriaque occidental",
  "Syrn": "syriaque oriental",
  "TA": "Tristan da Cunha",
  "TC": "Îles Turques-et-Caïques",
  "TD": "Tchad",
  "TF": "Terres australes françaises",
  "TG": "Togo",
  "TH": "Thaïlande",
  "TJ": "Tadjikistan",
  "TK": "Tokelau",
  "TL": "Timor oriental",
  "TM": "Turkménistan",
  "TN": "Tunisie",
  "TO": "Tonga",
  "TR": "Turquie",
  "TT": "Trinité-et-Tobago",
  "TV": "Tuvalu",
  "TW": "Taïwan",
  "TZ": "Tanzanie",
  "Tagb": "tagbanoua",
  "Takr": "takri",
  "Tale": "taï-le",
  "Talu": "nouveau taï-lue",
  "Taml": "tamoul",
  "Tang": "tangoute",
  "Tavt": "taï viêt",
  "Telu": "télougou",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagal",
  "Thaa": "thâna",
  "Thai": "thaï",
  "Tibt": "tibétain",
  "Tirh": "tirhouta",
  "UA": "Ukraine",
  "UG": "Ouganda",
  "UM": "Îles mineures éloignées des États-Unis",
  "UN": "Nations Unies",
  "US": "États-Unis",
  "UY": "Uruguay",
  "UZ": "Ouzbékistan",
  "Ugar": "ougaritique",
  "VA": "État de la Cité du Vatican",
  "VC": "Saint-Vincent-et-les-Grenadines",
  "VD": "Vietnam du Nord",
  "VE": "Venezuela",
  "VG": "Îles Vierges britanniques",
  "VI": "Îles Vierges des États-Unis",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vaï",
  "Visp": "parole visible",
  "WF": "Wallis-et-Futuna",
  "WK": "Île de Wake",
  "WS": "Samoa",
  "Wara": "warang citi",
  "Wcho": "wantcho",
  "Wole": "woléaï",
  "XA": "pseudo-accents",
  "XB": "pseudo-bidi",
  "XK": "Kosovo",
  "Xpeo": "cunéiforme persépolitain",
  "Xsux": "cunéiforme suméro-akkadien",
  "YD": "République démocratique populaire du Yémen",
  "YE": "Yémen",
  "YT": "Mayotte",
  "Yezi": "yézidi",
  "Yiii": "yi",
  "ZA": "Afrique du Sud",
  "ZM": "Zambie",
  "ZW": "Zimbabwe",
  "ZZ": "région indéterminée",
  "Zanb": "zanabazar carré",
  "Zinh": "hérité",
  "Zmth": "notation mathématique",
  "Zsye": "emoji",
  "Zsym": "symboles",
  "Zxxx": "non écrit",
  "Zyyy": "commun",
  "Zzzz": "écriture inconnue",
  "aa": "afar",
  "ab": "abkhaze",
  "ace": "aceh",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adyguéen",
  "ae": "avestique",
  "aeb": "arabe tunisien",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibie)",
  "af_ZA": "afrikaans (Afrique du Sud)",
  "afa": "langue afro-asiatique",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "aïnou",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "akkadien",
  "akz": "alabama",
  "ale": "aléoute",
  "alg": "langue algonquienne",
  "aln": "guègue",
  "alt": "altaï du Sud",
  "am": "amharique",
  "am_ET": "amharique (Éthiopie)",
  "an": "aragonais",
  "ang": "ancien anglais",
  "anp": "angika",
  "apa": "langue apache",
  "ar": "arabe",
  "ar_001": "arabe standard moderne",
  "ar_AE": "arabe (Émirats arabes unis)",
  "ar_BH": "arabe (Bahreïn)",
  "ar_DJ": "arabe (Djibouti)",
  "ar_DZ": "arabe (Algérie)",
  "ar_EG": "arabe (Égypte)",
  "ar_EH": "arabe (Sahara occidental)",
  "ar_ER": "arabe (Érythrée)",
  "ar_IL": "arabe (Israël)",
  "ar_IQ": "arabe (Irak)",
  "ar_JO": "arabe (Jordanie)",
  "ar_KM": "arabe (Comores)",
  "ar_KW": "arabe (Koweït)",
  "ar_LB": "arabe (Liban)",
  "ar_LY": "arabe (Libye)",
  "ar_MA": "arabe (Maroc)",
  "ar_MR": "arabe (Mauritanie)",
  "ar_OM": "arabe (Oman)",
  "ar_PS": "arabe (Territoires palestiniens)",
  "ar_QA": "arabe (Qatar)",
  "ar_SA": "arabe (Arabie saoudite)",
  "ar_SD": "arabe (Soudan)",
  "ar_SO": "arabe (Somalie)",
  "ar_SS": "arabe (Soudan du Sud)",
  "ar_SY": "arabe (Syrie)",
  "ar_TD": "arabe (Tchad)",
  "ar_TN": "arabe (Tunisie)",
  "ar_YE": "arabe (Yémen)",
  "arc": "araméen",
  "arn": "mapuche",
  "aro": "araona",
  "arp": "arapaho",
  "arq": "arabe algérien",
  "ars": "arabe najdi",
  "art": "langue artificielle",
  "arw": "arawak",
  "ary": "arabe marocain",
  "arz": "arabe égyptien",
  "as": "assamais",
  "as_IN": "assamais (Inde)",
  "asa": "asu",
  "ase": "langue des signes américaine",
  "ast": "asturien",
  "ath": "langue athapascane",
  "aus": "langue australienne",
  "av": "avar",
  "avk": "kotava",
  "awa": "awadhi",
  "ay": "aymara",
  "az": "azéri",
  "az_AZ": "azéri (Azerbaïdjan)",
  "az_Arab": "Azerbaïdjanais (arabe)",
  "az_Cyrl": "azéri (cyrillique)",
  "az_Cyrl_AZ": "azéri (cyrillique, Azerbaïdjan)",
  "az_Latn": "azéri (latin)",
  "az_Latn_AZ": "azéri (latin, Azerbaïdjan)",
  "azb": "South Azerbaijani",
  "ba": "bachkir",
  "bad": "banda",
  "bai": "langue bamilékée",
  "bal": "baloutchi",
  "ban": "balinais",
  "bar": "bavarois",
  "bas": "bassa",
  "bat": "langue balte",
  "bax": "bamoun",
  "bbc": "batak toba",
  "bbj": "ghomalaʼ",
  "be": "biélorusse",
  "be_BY": "biélorusse (Biélorussie)",
  "bej": "bedja",
  "bem": "bemba",
  "ber": "berbère",
  "bew": "betawi",
  "bez": "béna",
  "bfd": "bafut",
  "bfq": "badaga",
  "bg": "bulgare",
  "bg_BG": "bulgare (Bulgarie)",
  "bgn": "baloutchi occidental",
  "bh": "bihari",
  "bho": "bhodjpouri",
  "bi": "bichelamar",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latin)",
  "bm_Latn_ML": "bambara (latin, Mali)",
  "bn": "bengali",
  "bn_BD": "bengali (Bangladesh)",
  "bn_IN": "bengali (Inde)",
  "bnt": "bantou",
  "bo": "tibétain",
  "bo_CN": "tibétain (Chine)",
  "bo_IN": "tibétain (Inde)",
  "bpy": "bishnupriya",
  "bqi": "bakhtiari",
  "br": "breton",
  "br_FR": "breton (France)",
  "bra": "braj",
  "brh": "brahoui",
  "brx": "bodo",
  "bs": "bosniaque",
  "bs_BA": "bosniaque (Bosnie-Herzégovine)",
  "bs_Cyrl": "bosniaque (cyrillique)",
  "bs_Cyrl_BA": "bosniaque (cyrillique, Bosnie-Herzégovine)",
  "bs_Latn": "bosniaque (latin)",
  "bs_Latn_BA": "bosniaque (latin, Bosnie-Herzégovine)",
  "bss": "akoose",
  "btk": "batak",
  "bua": "bouriate",
  "bug": "bugi",
  "bum": "boulou",
  "byn": "blin",
  "byv": "médumba",
  "ca": "catalan",
  "ca_AD": "catalan (Andorre)",
  "ca_ES": "catalan (Espagne)",
  "ca_FR": "catalan (France)",
  "ca_IT": "catalan (Italie)",
  "cad": "caddo",
  "cai": "langue amérindienne centrale",
  "car": "caribe",
  "cau": "langue caucasienne",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "changma kodha",
  "ce": "tchétchène",
  "ceb": "cebuano",
  "cel": "langue celtique",
  "cgg": "kiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "tchaghataï",
  "chk": "chuuk",
  "chm": "mari",
  "chn": "jargon chinook",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cherokee",
  "chy": "cheyenne",
  "cic": "Chickasaw",
  "ckb": "sorani",
  "cmc": "langue chame",
  "co": "corse",
  "cop": "copte",
  "cpe": "créole ou pidgin anglais",
  "cpf": "créole ou pidgin français",
  "cpp": "créole ou pidgin portugais",
  "cps": "capiznon",
  "cr": "cree",
  "crh": "turc de Crimée",
  "crp": "créole ou pidgin",
  "crs": "créole seychellois",
  "cs": "tchèque",
  "cs_CZ": "tchèque (République tchèque)",
  "csb": "kachoube",
  "cu": "slavon d’église",
  "cus": "langue couchitique",
  "cv": "tchouvache",
  "cy": "gallois",
  "cy_GB": "gallois (Royaume-Uni)",
  "da": "danois",
  "da_DK": "danois (Danemark)",
  "da_GL": "danois (Groenland)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "day": "dayak",
  "de": "allemand",
  "de_AT": "allemand autrichien",
  "de_BE": "allemand (Belgique)",
  "de_CH": "allemand suisse",
  "de_DE": "allemand (Allemagne)",
  "de_LI": "allemand (Liechtenstein)",
  "de_LU": "allemand (Luxembourg)",
  "del": "delaware",
  "den": "esclave",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "langue dravidienne",
  "dsb": "bas-sorabe",
  "dtp": "dusun central",
  "dua": "douala",
  "dum": "moyen néerlandais",
  "dv": "maldivien",
  "dyo": "diola-fogny",
  "dyu": "dioula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhoutan)",
  "dzg": "dazaga",
  "ebu": "embou",
  "ee": "éwé",
  "ee_GH": "éwé (Ghana)",
  "ee_TG": "éwé (Togo)",
  "efi": "éfik",
  "egl": "émilien",
  "egy": "égyptien ancien",
  "eka": "ékadjouk",
  "el": "grec",
  "el_CY": "grec (Chypre)",
  "el_GR": "grec (Grèce)",
  "elx": "élamite",
  "en": "anglais",
  "en_AG": "anglais (Antigua-et-Barbuda)",
  "en_AI": "anglais (Anguilla)",
  "en_AS": "anglais (Samoa américaines)",
  "en_AU": "anglais (Australie)",
  "en_BB": "anglais (Barbade)",
  "en_BE": "anglais (Belgique)",
  "en_BM": "anglais (Bermudes)",
  "en_BS": "anglais (Bahamas)",
  "en_BW": "anglais (Botswana)",
  "en_BZ": "anglais (Belize)",
  "en_CA": "anglais (Canada)",
  "en_CC": "anglais (Îles Cocos)",
  "en_CK": "anglais (Îles Cook)",
  "en_CM": "anglais (Cameroun)",
  "en_CX": "anglais (Île Christmas)",
  "en_DG": "anglais (Diego Garcia)",
  "en_DM": "anglais (Dominique)",
  "en_Dsrt": "Anglais (Deseret)",
  "en_ER": "anglais (Érythrée)",
  "en_FJ": "anglais (Fidji)",
  "en_FK": "anglais (Îles Malouines)",
  "en_FM": "anglais (États fédérés de Micronésie)",
  "en_GB": "anglais (Royaume-Uni)",
  "en_GD": "anglais (Grenade)",
  "en_GG": "anglais (Guernesey)",
  "en_GH": "anglais (Ghana)",
  "en_GI": "anglais (Gibraltar)",
  "en_GM": "anglais (Gambie)",
  "en_GU": "anglais (Guam)",
  "en_GY": "anglais (Guyana)",
  "en_HK": "anglais (R.A.S. chinoise de Hong Kong)",
  "en_IE": "anglais (Irlande)",
  "en_IM": "anglais (Île de Man)",
  "en_IN": "anglais (Inde)",
  "en_IO": "anglais (Territoire britannique de l’océan Indien)",
  "en_JE": "anglais (Jersey)",
  "en_JM": "anglais (Jamaïque)",
  "en_KE": "anglais (Kenya)",
  "en_KI": "anglais (Kiribati)",
  "en_KN": "anglais (Saint-Christophe-et-Niévès)",
  "en_KY": "anglais (Îles Caïmans)",
  "en_LC": "anglais (Sainte-Lucie)",
  "en_LR": "anglais (Libéria)",
  "en_LS": "anglais (Lesotho)",
  "en_MG": "anglais (Madagascar)",
  "en_MH": "anglais (Îles Marshall)",
  "en_MO": "anglais (R.A.S. chinoise de Macao)",
  "en_MP": "anglais (Îles Mariannes du Nord)",
  "en_MS": "anglais (Montserrat)",
  "en_MT": "anglais (Malte)",
  "en_MU": "anglais (Maurice)",
  "en_MW": "anglais (Malawi)",
  "en_MY": "anglais (Malaisie)",
  "en_NA": "anglais (Namibie)",
  "en_NF": "anglais (Île Norfolk)",
  "en_NG": "anglais (Nigéria)",
  "en_NR": "anglais (Nauru)",
  "en_NU": "anglais (Niue)",
  "en_NZ": "anglais (Nouvelle-Zélande)",
  "en_PG": "anglais (Papouasie-Nouvelle-Guinée)",
  "en_PH": "anglais (Philippines)",
  "en_PK": "anglais (Pakistan)",
  "en_PN": "anglais (Pitcairn)",
  "en_PR": "anglais (Porto Rico)",
  "en_PW": "anglais (Palaos)",
  "en_RW": "anglais (Rwanda)",
  "en_SB": "anglais (Îles Salomon)",
  "en_SC": "anglais (Seychelles)",
  "en_SD": "anglais (Soudan)",
  "en_SG": "anglais (Singapour)",
  "en_SH": "anglais (Sainte-Hélène)",
  "en_SL": "anglais (Sierra Leone)",
  "en_SS": "anglais (Soudan du Sud)",
  "en_SX": "anglais (Saint-Martin (partie néerlandaise))",
  "en_SZ": "anglais (Swaziland)",
  "en_TC": "anglais (Îles Turques-et-Caïques)",
  "en_TK": "anglais (Tokelau)",
  "en_TO": "anglais (Tonga)",
  "en_TT": "anglais (Trinité-et-Tobago)",
  "en_TV": "anglais (Tuvalu)",
  "en_TZ": "anglais (Tanzanie)",
  "en_UG": "anglais (Ouganda)",
  "en_UM": "anglais (Îles mineures éloignées des États-Unis)",
  "en_US": "anglais (États-Unis)",
  "en_VC": "anglais (Saint-Vincent-et-les-Grenadines)",
  "en_VG": "anglais (Îles Vierges britanniques)",
  "en_VI": "anglais (Îles Vierges des États-Unis)",
  "en_VU": "anglais (Vanuatu)",
  "en_WS": "anglais (Samoa)",
  "en_ZA": "anglais (Afrique du Sud)",
  "en_ZM": "anglais (Zambie)",
  "en_ZW": "anglais (Zimbabwe)",
  "enm": "moyen anglais",
  "eo": "espéranto",
  "es": "espagnol",
  "es_419": "espagnol (Amérique latine)",
  "es_AR": "espagnol (Argentine)",
  "es_BO": "espagnol (Bolivie)",
  "es_CL": "espagnol (Chili)",
  "es_CO": "espagnol (Colombie)",
  "es_CR": "espagnol (Costa Rica)",
  "es_CU": "espagnol (Cuba)",
  "es_DO": "espagnol (République dominicaine)",
  "es_EA": "espagnol (Ceuta et Melilla)",
  "es_EC": "espagnol (Équateur)",
  "es_ES": "espagnol (Espagne)",
  "es_GQ": "espagnol (Guinée équatoriale)",
  "es_GT": "espagnol (Guatemala)",
  "es_HN": "espagnol (Honduras)",
  "es_IC": "espagnol (Îles Canaries)",
  "es_MX": "espagnol (Mexique)",
  "es_NI": "espagnol (Nicaragua)",
  "es_PA": "espagnol (Panama)",
  "es_PE": "espagnol (Pérou)",
  "es_PH": "espagnol (Philippines)",
  "es_PR": "espagnol (Porto Rico)",
  "es_PY": "espagnol (Paraguay)",
  "es_SV": "espagnol (El Salvador)",
  "es_US": "espagnol (États-Unis)",
  "es_UY": "espagnol (Uruguay)",
  "es_VE": "espagnol (Venezuela)",
  "esu": "youpik central",
  "et": "estonien",
  "et_EE": "estonien (Estonie)",
  "eu": "basque",
  "eu_ES": "basque (Espagne)",
  "ewo": "éwondo",
  "ext": "estrémègne",
  "fa": "persan",
  "fa_AF": "persan (Afghanistan)",
  "fa_IR": "persan (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "peul",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "peul (Cameroun)",
  "ff_GN": "peul (Guinée)",
  "ff_MR": "peul (Mauritanie)",
  "ff_SN": "peul (Sénégal)",
  "fi": "finnois",
  "fi_FI": "finnois (Finlande)",
  "fil": "filipino",
  "fit": "finnois tornédalien",
  "fiu": "langue finno-ougrienne",
  "fj": "fidjien",
  "fo": "féroïen",
  "fo_FO": "féroïen (Îles Féroé)",
  "fon": "fon",
  "fr": "français",
  "fr_BE": "français (Belgique)",
  "fr_BF": "français (Burkina Faso)",
  "fr_BI": "français (Burundi)",
  "fr_BJ": "français (Bénin)",
  "fr_BL": "français (Saint-Barthélemy)",
  "fr_CA": "français (Canada)",
  "fr_CD": "français (Congo-Kinshasa)",
  "fr_CF": "français (République centrafricaine)",
  "fr_CG": "français (Congo-Brazzaville)",
  "fr_CH": "français (Suisse)",
  "fr_CI": "français (Côte d’Ivoire)",
  "fr_CM": "français (Cameroun)",
  "fr_DJ": "français (Djibouti)",
  "fr_DZ": "français (Algérie)",
  "fr_FR": "français (France)",
  "fr_GA": "français (Gabon)",
  "fr_GF": "français (Guyane française)",
  "fr_GN": "français (Guinée)",
  "fr_GP": "français (Guadeloupe)",
  "fr_GQ": "français (Guinée équatoriale)",
  "fr_HT": "français (Haïti)",
  "fr_KM": "français (Comores)",
  "fr_LU": "français (Luxembourg)",
  "fr_MA": "français (Maroc)",
  "fr_MC": "français (Monaco)",
  "fr_MF": "français (Saint-Martin (partie française))",
  "fr_MG": "français (Madagascar)",
  "fr_ML": "français (Mali)",
  "fr_MQ": "français (Martinique)",
  "fr_MR": "français (Mauritanie)",
  "fr_MU": "français (Maurice)",
  "fr_NC": "français (Nouvelle-Calédonie)",
  "fr_NE": "français (Niger)",
  "fr_PF": "français (Polynésie française)",
  "fr_PM": "français (Saint-Pierre-et-Miquelon)",
  "fr_RE": "français (La Réunion)",
  "fr_RW": "français (Rwanda)",
  "fr_SC": "français (Seychelles)",
  "fr_SN": "français (Sénégal)",
  "fr_SY": "français (Syrie)",
  "fr_TD": "français (Tchad)",
  "fr_TG": "français (Togo)",
  "fr_TN": "français (Tunisie)",
  "fr_VU": "français (Vanuatu)",
  "fr_WF": "français (Wallis-et-Futuna)",
  "fr_YT": "français (Mayotte)",
  "frc": "français cadien",
  "frm": "moyen français",
  "fro": "ancien français",
  "frp": "francoprovençal",
  "frr": "frison du Nord",
  "frs": "frison oriental",
  "fur": "frioulan",
  "fy": "frison occidental",
  "fy_NL": "frison occidental (Pays-Bas)",
  "ga": "irlandais",
  "ga_IE": "irlandais (Irlande)",
  "gaa": "ga",
  "gag": "gagaouze",
  "gan": "gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "dari zoroastrien",
  "gd": "gaélique écossais",
  "gd_GB": "gaélique écossais (Royaume-Uni)",
  "gem": "langue germanique",
  "gez": "guèze",
  "gil": "gilbertin",
  "gl": "galicien",
  "gl_ES": "galicien (Espagne)",
  "glk": "gilaki",
  "gmh": "moyen haut-allemand",
  "gn": "guarani",
  "goh": "ancien haut allemand",
  "gom": "konkani de Goa",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotique",
  "grb": "grebo",
  "grc": "grec ancien",
  "gsw": "suisse allemand",
  "gu": "goudjerati",
  "gu_IN": "gujarati (Inde)",
  "guc": "wayuu",
  "gur": "gurenne",
  "guz": "gusii",
  "gv": "mannois",
  "gv_IM": "manx (Île de Man)",
  "gwi": "gwichʼin",
  "ha": "haoussa",
  "ha_GH": "haoussa (Ghana)",
  "ha_Latn": "haoussa (latin)",
  "ha_Latn_GH": "haoussa (latin, Ghana)",
  "ha_Latn_NE": "haoussa (latin, Niger)",
  "ha_Latn_NG": "haoussa (latin, Nigéria)",
  "ha_NE": "haoussa (Niger)",
  "ha_NG": "haoussa (Nigéria)",
  "hai": "haida",
  "hak": "hakka",
  "haw": "hawaïen",
  "he": "hébreu",
  "he_IL": "hébreu (Israël)",
  "hi": "hindi",
  "hi_IN": "hindi (Inde)",
  "hif": "hindi fidjien",
  "hil": "hiligaynon",
  "him": "himachali",
  "hit": "hittite",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croate",
  "hr_BA": "croate (Bosnie-Herzégovine)",
  "hr_HR": "croate (Croatie)",
  "hsb": "haut-sorabe",
  "hsn": "xiang",
  "ht": "créole haïtien",
  "hu": "hongrois",
  "hu_HU": "hongrois (Hongrie)",
  "hup": "hupa",
  "hy": "arménien",
  "hy_AM": "arménien (Arménie)",
  "hz": "héréro",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonésien",
  "id_ID": "indonésien (Indonésie)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigéria)",
  "ii": "yi du Sichuan",
  "ii_CN": "yi du Sichuan (Chine)",
  "ijo": "ijo",
  "ik": "inupiaq",
  "ilo": "ilocano",
  "inc": "langue indo-aryenne",
  "ine": "langue indo-européenne",
  "inh": "ingouche",
  "io": "ido",
  "ira": "langue iranienne",
  "iro": "langue iroquoienne",
  "is": "islandais",
  "is_IS": "islandais (Islande)",
  "it": "italien",
  "it_CH": "italien (Suisse)",
  "it_IT": "italien (Italie)",
  "it_SM": "italien (Saint-Marin)",
  "iu": "inuktitut",
  "izh": "ingrien",
  "ja": "japonais",
  "ja_JP": "japonais (Japon)",
  "jam": "créole jamaïcain",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "matchamé",
  "jpr": "judéo-persan",
  "jrb": "judéo-arabe",
  "jut": "jute",
  "jv": "javanais",
  "ka": "géorgien",
  "ka_GE": "géorgien (Géorgie)",
  "kaa": "karakalpak",
  "kab": "kabyle",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "kabarde",
  "kbl": "kanembou",
  "kcg": "tyap",
  "kde": "makondé",
  "kea": "capverdien",
  "ken": "kényang",
  "kfo": "koro",
  "kg": "kikongo",
  "kgp": "caingangue",
  "kha": "khasi",
  "khi": "langue khoïsan",
  "kho": "khotanais",
  "khq": "koyra chiini",
  "khw": "khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenya)",
  "kiu": "kirmanjki",
  "kj": "kuanyama",
  "kk": "kazakh",
  "kk_Cyrl": "kazakh (cyrillique)",
  "kk_Cyrl_KZ": "kazakh (cyrillique, Kazakhstan)",
  "kk_KZ": "kazakh (Kazakhstan)",
  "kkj": "kako",
  "kl": "groenlandais",
  "kl_GL": "groenlandais (Groenland)",
  "kln": "kalendjin",
  "km": "khmer",
  "km_KH": "khmer (Cambodge)",
  "kmb": "kimboundou",
  "kn": "kannada",
  "kn_IN": "kannada (Inde)",
  "ko": "coréen",
  "ko_KP": "coréen (Corée du Nord)",
  "ko_KR": "coréen (Corée du Sud)",
  "koi": "komi-permiak",
  "kok": "konkani",
  "kos": "kosraéen",
  "kpe": "kpellé",
  "kr": "kanouri",
  "krc": "karatchaï balkar",
  "kri": "krio",
  "krj": "kinaray-a",
  "krl": "carélien",
  "kro": "krou",
  "kru": "kouroukh",
  "ks": "cachemiri",
  "ks_Arab": "kashmiri (arabe)",
  "ks_Arab_IN": "kashmiri (arabe, Inde)",
  "ks_IN": "kashmiri (Inde)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "francique ripuaire",
  "ku": "kurde",
  "kum": "koumyk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "cornique",
  "kw_GB": "cornique (Royaume-Uni)",
  "ky": "kirghize",
  "ky_Cyrl": "kirghize (cyrillique)",
  "ky_Cyrl_KG": "kirghize (cyrillique, Kirghizistan)",
  "ky_KG": "kirghize (Kirghizistan)",
  "la": "latin",
  "lad": "ladino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxembourgeois",
  "lb_LU": "luxembourgeois (Luxembourg)",
  "lez": "lezghien",
  "lfn": "lingua franca nova",
  "lg": "ganda",
  "lg_UG": "ganda (Ouganda)",
  "li": "limbourgeois",
  "lij": "ligure",
  "liv": "livonien",
  "lkt": "lakota",
  "lmo": "lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Congo-Kinshasa)",
  "ln_CF": "lingala (République centrafricaine)",
  "ln_CG": "lingala (Congo-Brazzaville)",
  "lo": "lao",
  "lo_LA": "lao (Laos)",
  "lol": "mongo",
  "lou": "créole louisianais",
  "loz": "lozi",
  "lrc": "lori du Nord",
  "lt": "lituanien",
  "lt_LT": "lituanien (Lituanie)",
  "ltg": "latgalien",
  "lu": "luba-katanga (kiluba)",
  "lu_CD": "luba-katanga (Congo-Kinshasa)",
  "lua": "luba-kasaï (ciluba)",
  "lui": "luiseño",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushaï",
  "luy": "luyia",
  "lv": "letton",
  "lv_LV": "letton (Lettonie)",
  "lzh": "chinois littéraire",
  "lzz": "laze",
  "mad": "madurais",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maïthili",
  "mak": "makassar",
  "man": "mandingue",
  "map": "malayo-polynésien",
  "mas": "maasaï",
  "mde": "maba",
  "mdf": "mokcha",
  "mdr": "mandar",
  "men": "mendé",
  "mer": "meru",
  "mfe": "créole mauricien",
  "mg": "malgache",
  "mg_MG": "malgache (Madagascar)",
  "mga": "moyen irlandais",
  "mgh": "makua",
  "mgo": "metaʼ",
  "mh": "marshallais",
  "mi": "maori",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "langue diverse",
  "mk": "macédonien",
  "mk_MK": "macédonien (Macédoine)",
  "mkh": "langue mon-khmère",
  "ml": "malayalam",
  "ml_IN": "malayalam (Inde)",
  "mn": "mongol",
  "mn_Cyrl": "mongol (cyrillique)",
  "mn_Cyrl_MN": "mongol (cyrillique, Mongolie)",
  "mn_MN": "mongol (Mongolie)",
  "mnc": "mandchou",
  "mni": "manipuri",
  "mno": "langue manobo",
  "mo": "moldave",
  "moh": "mohawk",
  "mos": "moré",
  "mr": "marathi",
  "mr_IN": "marathe (Inde)",
  "mrj": "mari occidental",
  "ms": "malais",
  "ms_BN": "malais (Brunéi Darussalam)",
  "ms_Latn": "malais (latin)",
  "ms_Latn_BN": "malais (latin, Brunéi Darussalam)",
  "ms_Latn_MY": "malais (latin, Malaisie)",
  "ms_Latn_SG": "malais (latin, Singapour)",
  "ms_MY": "malais (Malaisie)",
  "ms_SG": "malais (Singapour)",
  "mt": "maltais",
  "mt_MT": "maltais (Malte)",
  "mua": "moundang",
  "mul": "multilingue",
  "mun": "langue mounda",
  "mus": "creek",
  "mwl": "mirandais",
  "mwr": "marwarî",
  "mwv": "mentawaï",
  "my": "birman",
  "my_MM": "birman (Myanmar)",
  "mye": "myènè",
  "myn": "langue maya",
  "myv": "erzya",
  "mzn": "mazandérani",
  "na": "nauruan",
  "nah": "nahuatl",
  "nai": "langue amérindienne du Nord",
  "nan": "minnan",
  "nap": "napolitain",
  "naq": "nama",
  "nb": "norvégien bokmål",
  "nb_NO": "norvégien bokmål (Norvège)",
  "nb_SJ": "norvégien bokmål (Svalbard et Jan Mayen)",
  "nd": "ndébélé du Nord",
  "nd_ZW": "ndébélé du Nord (Zimbabwe)",
  "nds": "bas-allemand",
  "nds_NL": "bas-saxon néerlandais",
  "ne": "népalais",
  "ne_IN": "népalais (Inde)",
  "ne_NP": "népalais (Népal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "niha",
  "nic": "langue nigéro-congolaise",
  "niu": "niuéen",
  "njo": "Ao Naga",
  "nl": "néerlandais",
  "nl_AW": "néerlandais (Aruba)",
  "nl_BE": "néerlandais (Belgique)",
  "nl_BQ": "néerlandais (Pays-Bas caribéens)",
  "nl_CW": "néerlandais (Curaçao)",
  "nl_NL": "néerlandais (Pays-Bas)",
  "nl_SR": "néerlandais (Suriname)",
  "nl_SX": "néerlandais (Saint-Martin (partie néerlandaise))",
  "nmg": "ngoumba",
  "nn": "norvégien nynorsk",
  "nn_NO": "norvégien nynorsk (Norvège)",
  "nnh": "ngiemboon",
  "no": "norvégien",
  "no_NO": "norvégien (Norvège)",
  "nog": "nogaï",
  "non": "vieux norrois",
  "nov": "novial",
  "nqo": "n’ko",
  "nr": "ndébélé du Sud",
  "nso": "sotho du Nord",
  "nub": "langue nubienne",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "newarî classique",
  "ny": "chewa",
  "nym": "nyamwezi",
  "nyn": "nyankolé",
  "nyo": "nyoro",
  "nzi": "nzema",
  "oc": "occitan",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Éthiopie)",
  "om_KE": "oromo (Kenya)",
  "or": "odia",
  "or_IN": "oriya (Inde)",
  "os": "ossète",
  "os_GE": "ossète (Géorgie)",
  "os_RU": "ossète (Russie)",
  "osa": "osage",
  "ota": "turc ottoman",
  "oto": "langue otomangue",
  "pa": "pendjabi",
  "pa_Arab": "pendjabi (arabe)",
  "pa_Arab_PK": "pendjabi (arabe, Pakistan)",
  "pa_Guru": "pendjabi (gourmoukhî)",
  "pa_Guru_IN": "pendjabi (gourmoukhî, Inde)",
  "pa_IN": "pendjabi (Inde)",
  "pa_PK": "pendjabi (Pakistan)",
  "paa": "langue papoue",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampangan",
  "pap": "papiamento",
  "pau": "palau",
  "pcd": "picard",
  "pcm": "pidgin nigérian",
  "pdc": "pennsilfaanisch",
  "pdt": "bas-prussien",
  "peo": "persan ancien",
  "pfl": "allemand palatin",
  "phi": "langue philippine",
  "phn": "phénicien",
  "pi": "pali",
  "pl": "polonais",
  "pl_PL": "polonais (Pologne)",
  "pms": "piémontais",
  "pnt": "pontique",
  "pon": "pohnpei",
  "pra": "langues prâkrit",
  "prg": "prussien",
  "pro": "provençal ancien",
  "ps": "pachto",
  "ps_AF": "pachto (Afghanistan)",
  "pt": "portugais",
  "pt_AO": "portugais (Angola)",
  "pt_BR": "portugais (Brésil)",
  "pt_CV": "portugais (Cap-Vert)",
  "pt_GW": "portugais (Guinée-Bissau)",
  "pt_MO": "portugais (R.A.S. chinoise de Macao)",
  "pt_MZ": "portugais (Mozambique)",
  "pt_PT": "portugais (Portugal)",
  "pt_ST": "portugais (Sao Tomé-et-Principe)",
  "pt_TL": "portugais (Timor oriental)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivie)",
  "qu_EC": "quechua (Équateur)",
  "qu_PE": "quechua (Pérou)",
  "quc": "k’iche’",
  "qug": "quichua du Haut-Chimborazo",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotongien",
  "rgn": "romagnol",
  "rif": "rifain",
  "rm": "romanche",
  "rm_CH": "romanche (Suisse)",
  "rn": "roundi",
  "rn_BI": "roundi (Burundi)",
  "ro": "roumain",
  "ro_MD": "roumain (Moldavie)",
  "ro_RO": "roumain (Roumanie)",
  "roa": "langue romane",
  "rof": "rombo",
  "rom": "romani",
  "root": "racine",
  "rtm": "rotuman",
  "ru": "russe",
  "ru_BY": "russe (Biélorussie)",
  "ru_KG": "russe (Kirghizistan)",
  "ru_KZ": "russe (Kazakhstan)",
  "ru_MD": "russe (Moldavie)",
  "ru_RU": "russe (Russie)",
  "ru_UA": "russe (Ukraine)",
  "rue": "ruthène",
  "rug": "roviana",
  "rup": "aroumain",
  "rw": "kinyarwanda",
  "rw_RW": "rwanda (Rwanda)",
  "rwk": "rwa",
  "sa": "sanskrit",
  "sad": "sandawe",
  "sah": "iakoute",
  "sai": "langue amérindienne du Sud",
  "sal": "langue salishenne",
  "sam": "araméen samaritain",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "saurashtra",
  "sba": "ngambay",
  "sbp": "isangu",
  "sc": "sarde",
  "scn": "sicilien",
  "sco": "écossais",
  "sd": "sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "sarde sassarais",
  "sdh": "kurde du Sud",
  "se": "same du Nord",
  "se_FI": "sami du Nord (Finlande)",
  "se_NO": "sami du Nord (Norvège)",
  "se_SE": "sami du Nord (Suède)",
  "see": "seneca",
  "seh": "cisena",
  "sei": "séri",
  "sel": "selkoupe",
  "sem": "langue sémitique",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sangho (République centrafricaine)",
  "sga": "ancien irlandais",
  "sgn": "langue des signes",
  "sgs": "samogitien",
  "sh": "serbo-croate",
  "sh_BA": "serbo-croate (Bosnie-Herzégovine)",
  "shi": "chleuh",
  "shi_Latn": "Shilha (latin)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "shan",
  "shu": "arabe tchadien",
  "si": "cingalais",
  "si_LK": "cinghalais (Sri Lanka)",
  "sid": "sidamo",
  "sio": "langue sioux",
  "sit": "langue sino-tibétaine",
  "sk": "slovaque",
  "sk_SK": "slovaque (Slovaquie)",
  "sl": "slovène",
  "sl_SI": "slovène (Slovénie)",
  "sla": "langue slave",
  "sli": "bas-silésien",
  "sly": "sélayar",
  "sm": "samoan",
  "sma": "same du Sud",
  "smi": "langue samie",
  "smj": "same de Lule",
  "smn": "same d’Inari",
  "sms": "same skolt",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabwe)",
  "snk": "soninké",
  "so": "somali",
  "so_DJ": "somali (Djibouti)",
  "so_ET": "somali (Éthiopie)",
  "so_KE": "somali (Kenya)",
  "so_SO": "somali (Somalie)",
  "sog": "sogdien",
  "son": "songhai",
  "sq": "albanais",
  "sq_AL": "albanais (Albanie)",
  "sq_MK": "albanais (Macédoine)",
  "sq_XK": "albanais (Kosovo)",
  "sr": "serbe",
  "sr_BA": "serbe (Bosnie-Herzégovine)",
  "sr_Cyrl": "serbe (cyrillique)",
  "sr_Cyrl_BA": "serbe (cyrillique, Bosnie-Herzégovine)",
  "sr_Cyrl_ME": "serbe (cyrillique, Monténégro)",
  "sr_Cyrl_RS": "serbe (cyrillique, Serbie)",
  "sr_Cyrl_XK": "serbe (cyrillique, Kosovo)",
  "sr_Latn": "serbe (latin)",
  "sr_Latn_BA": "serbe (latin, Bosnie-Herzégovine)",
  "sr_Latn_ME": "serbe (latin, Monténégro)",
  "sr_Latn_RS": "serbe (latin, Serbie)",
  "sr_Latn_XK": "serbe (latin, Kosovo)",
  "sr_ME": "serbe (Monténégro)",
  "sr_RS": "serbe (Serbie)",
  "sr_XK": "serbe (Kosovo)",
  "srn": "sranan tongo",
  "srr": "sérère",
  "ss": "swati",
  "ssa": "langue nilo-saharienne",
  "ssy": "saho",
  "st": "sotho du Sud",
  "stq": "saterlandais",
  "su": "soundanais",
  "suk": "soukouma",
  "sus": "soussou",
  "sux": "sumérien",
  "sv": "suédois",
  "sv_AX": "suédois (Îles Åland)",
  "sv_FI": "suédois (Finlande)",
  "sv_SE": "suédois (Suède)",
  "sw": "swahili",
  "sw_CD": "swahili du Congo",
  "sw_KE": "swahili (Kenya)",
  "sw_TZ": "swahili (Tanzanie)",
  "sw_UG": "swahili (Ouganda)",
  "swb": "comorien",
  "swc": "swahili du Congo",
  "syc": "syriaque classique",
  "syr": "syriaque",
  "szl": "silésien",
  "ta": "tamoul",
  "ta_IN": "tamoul (Inde)",
  "ta_LK": "tamoul (Sri Lanka)",
  "ta_MY": "tamoul (Malaisie)",
  "ta_SG": "tamoul (Singapour)",
  "tai": "langue taï",
  "tcy": "toulou",
  "te": "télougou",
  "te_IN": "télougou (Inde)",
  "tem": "timné",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tétoum",
  "tg": "tadjik",
  "th": "thaï",
  "th_TH": "thaï (Thaïlande)",
  "ti": "tigrigna",
  "ti_ER": "tigrigna (Érythrée)",
  "ti_ET": "tigrigna (Éthiopie)",
  "tig": "tigré",
  "tiv": "tiv",
  "tk": "turkmène",
  "tkl": "tokelau",
  "tkr": "tsakhour",
  "tl": "tagalog",
  "tl_PH": "tagalog (Philippines)",
  "tlh": "klingon",
  "tli": "tlingit",
  "tly": "talysh",
  "tmh": "tamacheq",
  "tn": "tswana",
  "to": "tongien",
  "to_TO": "tonguien (Tonga)",
  "tog": "tonga nyasa",
  "tpi": "tok pisin",
  "tr": "turc",
  "tr_CY": "turc (Chypre)",
  "tr_TR": "turc (Turquie)",
  "tru": "touroyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "tsakonien",
  "tsi": "tsimshian",
  "tt": "tatar",
  "ttt": "tati caucasien",
  "tum": "tumbuka",
  "tup": "langue tupi",
  "tut": "langue altaïque",
  "tvl": "tuvalu",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitien",
  "tyv": "touvain",
  "tzm": "amazighe de l’Atlas central",
  "udm": "oudmourte",
  "ug": "ouïghour",
  "ug_Arab": "ouïghour (arabe)",
  "ug_Arab_CN": "ouïghour (arabe, Chine)",
  "ug_CN": "ouïghour (Chine)",
  "uga": "ougaritique",
  "uk": "ukrainien",
  "uk_UA": "ukrainien (Ukraine)",
  "umb": "umbundu",
  "und": "langue indéterminée",
  "ur": "ourdou",
  "ur_IN": "ourdou (Inde)",
  "ur_PK": "ourdou (Pakistan)",
  "uz": "ouzbek",
  "uz_AF": "ouzbek (Afghanistan)",
  "uz_Arab": "ouzbek (arabe)",
  "uz_Arab_AF": "ouzbek (arabe, Afghanistan)",
  "uz_Cyrl": "ouzbek (cyrillique)",
  "uz_Cyrl_UZ": "ouzbek (cyrillique, Ouzbékistan)",
  "uz_Latn": "ouzbek (latin)",
  "uz_Latn_UZ": "ouzbek (latin, Ouzbékistan)",
  "uz_UZ": "ouzbek (Ouzbékistan)",
  "vai": "vaï",
  "vai_Latn": "Vai (latin)",
  "ve": "venda",
  "vec": "vénitien",
  "vep": "vepse",
  "vi": "vietnamien",
  "vi_VN": "vietnamien (Vietnam)",
  "vls": "flamand occidental",
  "vmf": "franconien du Main",
  "vo": "volapük",
  "vot": "vote",
  "vro": "võro",
  "vun": "vunjo",
  "wa": "wallon",
  "wae": "walser",
  "wak": "langues wakashennes",
  "wal": "walamo",
  "war": "waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wen": "langue sorabe",
  "wo": "wolof",
  "wuu": "wu",
  "xal": "kalmouk",
  "xh": "xhosa",
  "xmf": "mingrélien",
  "xog": "soga",
  "yao": "yao",
  "yap": "yapois",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "yiddish",
  "yo": "yoruba",
  "yo_BJ": "yoruba (Bénin)",
  "yo_NG": "yoruba (Nigéria)",
  "ypk": "langues yupik",
  "yrl": "nheengatou",
  "yue": "cantonais",
  "yue_Hans": "Cantonais (chinois simplifié)",
  "yue_Hant": "Cantonais (chinois traditionnel)",
  "za": "zhuang",
  "zap": "zapotèque",
  "zbl": "symboles Bliss",
  "zea": "zélandais",
  "zen": "zenaga",
  "zgh": "amazighe standard marocain",
  "zh": "chinois",
  "zh_CN": "chinois (Chine)",
  "zh_HK": "chinois (R.A.S. chinoise de Hong Kong)",
  "zh_Hans": "chinois (simplifié)",
  "zh_Hans_CN": "chinois (simplifié, Chine)",
  "zh_Hans_HK": "chinois (simplifié, R.A.S. chinoise de Hong Kong)",
  "zh_Hans_MO": "chinois (simplifié, R.A.S. chinoise de Macao)",
  "zh_Hans_SG": "chinois (simplifié, Singapour)",
  "zh_Hant": "chinois (traditionnel)",
  "zh_Hant_HK": "chinois (traditionnel, R.A.S. chinoise de Hong Kong)",
  "zh_Hant_MO": "chinois (traditionnel, R.A.S. chinoise de Macao)",
  "zh_Hant_TW": "chinois (traditionnel, Taïwan)",
  "zh_MO": "chinois (R.A.S. chinoise de Macao)",
  "zh_SG": "chinois (Singapour)",
  "zh_TW": "chinois (Taïwan)",
  "znd": "zandé",
  "zu": "zoulou",
  "zu_ZA": "zoulou (Afrique du Sud)",
  "zun": "zuñi",
  "zxx": "sans contenu linguistique",
  "zza": "zazaki"
};
