const names = {
  "001": "Welt",
  "002": "Afrika",
  "003": "Nordamerika",
  "005": "Südamerika",
  "009": "Ozeanien",
  "011": "Westafrika",
  "013": "Mittelamerika",
  "014": "Ostafrika",
  "015": "Nordafrika",
  "017": "Zentralafrika",
  "018": "Südliches Afrika",
  "019": "Amerika",
  "021": "Nördliches Amerika",
  "029": "Karibik",
  "030": "Ostasien",
  "034": "Südasien",
  "035": "Südostasien",
  "039": "Südeuropa",
  "053": "Australasien",
  "054": "Melanesien",
  "057": "Mikronesisches Inselgebiet",
  "061": "Polynesien",
  "062": "Süd-Zentralasien",
  "142": "Asien",
  "143": "Zentralasien",
  "145": "Westasien",
  "150": "Europa",
  "151": "Osteuropa",
  "154": "Nordeuropa",
  "155": "Westeuropa",
  "172": "Gemeinschaft Unabhängiger Staaten",
  "200": "Tschechoslowakei",
  "202": "Subsahara-Afrika",
  "419": "Lateinamerika",
  "830": "Kanalinseln",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Vereinigte Arabische Emirate",
  "AF": "Afghanistan",
  "AG": "Antigua und Barbuda",
  "AI": "Anguilla",
  "AL": "Albanien",
  "AM": "Armenien",
  "AN": "Niederländische Antillen",
  "AO": "Angola",
  "AQ": "Antarktis",
  "AR": "Argentinien",
  "AS": "Amerikanisch-Samoa",
  "AT": "Österreich",
  "AU": "Australien",
  "AW": "Aruba",
  "AX": "Ålandinseln",
  "AZ": "Aserbaidschan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Kaukasisch-Albanisch",
  "Ahom": "Ahom",
  "Arab": "Arabisch",
  "Aran": "Nastaliq",
  "Armi": "Armi",
  "Armn": "Armenisch",
  "Avst": "Avestisch",
  "BA": "Bosnien und Herzegowina",
  "BB": "Barbados",
  "BD": "Bangladesch",
  "BE": "Belgien",
  "BF": "Burkina Faso",
  "BG": "Bulgarien",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei Darussalam",
  "BO": "Bolivien",
  "BQ": "Bonaire, Sint Eustatius und Saba",
  "BR": "Brasilien",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvetinsel",
  "BW": "Botsuana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "Balinesisch",
  "Bamu": "Bamun",
  "Bass": "Bassa",
  "Batk": "Battakisch",
  "Beng": "Bengalisch",
  "Bhks": "Bhaiksuki",
  "Blis": "Bliss-Symbole",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Buginesisch",
  "Buhd": "Buhid",
  "CA": "Kanada",
  "CC": "Kokosinseln",
  "CD": "Kongo-Kinshasa",
  "CF": "Zentralafrikanische Republik",
  "CG": "Kongo-Brazzaville",
  "CH": "Schweiz",
  "CI": "Côte d’Ivoire",
  "CK": "Cookinseln",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "China",
  "CO": "Kolumbien",
  "CP": "Clipperton-Insel",
  "CR": "Costa Rica",
  "CS": "Serbien und Montenegro",
  "CU": "Kuba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Weihnachtsinsel",
  "CY": "Zypern",
  "CZ": "Tschechien",
  "Cakm": "Chakma",
  "Cans": "UCAS",
  "Cari": "Karisch",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Koptisch",
  "Cprt": "Zypriotisch",
  "Cyrl": "Kyrillisch",
  "Cyrs": "Altkirchenslawisch",
  "DD": "Ost-Deutschland",
  "DE": "Deutschland",
  "DG": "Diego Garcia",
  "DJ": "Dschibuti",
  "DK": "Dänemark",
  "DM": "Dominica",
  "DO": "Dominikanische Republik",
  "DZ": "Algerien",
  "Deva": "Devanagari",
  "Diak": "Taucht Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Duployanisch",
  "EA": "Ceuta und Melilla",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Ägypten",
  "EH": "Westsahara",
  "ER": "Eritrea",
  "ES": "Spanien",
  "ET": "Äthiopien",
  "EU": "Europäische Union",
  "EZ": "Eurozone",
  "Egyd": "Ägyptisch - Demotisch",
  "Egyh": "Ägyptisch - Hieratisch",
  "Egyp": "Ägyptische Hieroglyphen",
  "Elba": "Elbasanisch",
  "Elym": "Elymäisch",
  "Ethi": "Äthiopisch",
  "FI": "Finnland",
  "FJ": "Fidschi",
  "FK": "Falklandinseln",
  "FM": "Mikronesien",
  "FO": "Färöer",
  "FR": "Frankreich",
  "FX": "Metropolitan-Frankreich",
  "GA": "Gabun",
  "GB": "Vereinigtes Königreich",
  "GD": "Grenada",
  "GE": "Georgien",
  "GF": "Französisch-Guayana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grönland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Äquatorialguinea",
  "GR": "Griechenland",
  "GS": "Südgeorgien und die Südlichen Sandwichinseln",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "Khutsuri",
  "Geor": "Georgisch",
  "Glag": "Glagolitisch",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram-Gondi",
  "Goth": "Gotisch",
  "Gran": "Grantha",
  "Grek": "Griechisch",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Sonderverwaltungsregion Hongkong",
  "HM": "Heard und McDonaldinseln",
  "HN": "Honduras",
  "HR": "Kroatien",
  "HT": "Haiti",
  "HU": "Ungarn",
  "Hanb": "Han mit Bopomofo",
  "Hang": "Hangul",
  "Hani": "Chinesisch",
  "Hano": "Hanunoo",
  "Hans": "Vereinfacht",
  "Hant": "Traditionell",
  "Hatr": "Hatranisch",
  "Hebr": "Hebräisch",
  "Hira": "Hiragana",
  "Hluw": "Hieroglyphen-Luwisch",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Japanische Silbenschrift",
  "Hung": "Altungarisch",
  "IC": "Kanarische Inseln",
  "ID": "Indonesien",
  "IE": "Irland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "Indien",
  "IO": "Britisches Territorium im Indischen Ozean",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italien",
  "Inds": "Indus-Schrift",
  "Ital": "Altitalisch",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Jordanien",
  "JP": "Japan",
  "Jamo": "Jamo",
  "Java": "Javanesisch",
  "Jpan": "Japanisch",
  "Jurc": "Jurchen",
  "KE": "Kenia",
  "KG": "Kirgisistan",
  "KH": "Kambodscha",
  "KI": "Kiribati",
  "KM": "Komoren",
  "KN": "St. Kitts und Nevis",
  "KP": "Nordkorea",
  "KR": "Südkorea",
  "KW": "Kuwait",
  "KY": "Kaimaninseln",
  "KZ": "Kasachstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kits": "Khitan kleine Schrift",
  "Knda": "Kannada",
  "Kore": "Koreanisch",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litauen",
  "LU": "Luxemburg",
  "LV": "Lettland",
  "LY": "Libyen",
  "Lana": "Lanna",
  "Laoo": "Laotisch",
  "Latf": "Lateinisch - Fraktur-Variante",
  "Latg": "Lateinisch - Gälische Variante",
  "Latn": "Lateinisch",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Linear A",
  "Linb": "Linear B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lykisch",
  "Lydi": "Lydisch",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Republik Moldau",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagaskar",
  "MH": "Marshallinseln",
  "MI": "Midway Islands",
  "MK": "Nordmazedonien",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolei",
  "MO": "Sonderverwaltungsregion Macau",
  "MP": "Nördliche Marianen",
  "MQ": "Martinique",
  "MR": "Mauretanien",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Malediven",
  "MW": "Malawi",
  "MX": "Mexiko",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandäisch",
  "Mani": "Manichäisch",
  "Marc": "Marchen",
  "Maya": "Maya-Hieroglyphen",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitisch kursiv",
  "Mero": "Meroitisch",
  "Mlym": "Malayalam",
  "Modi": "Modi",
  "Mong": "Mongolisch",
  "Moon": "Moon",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Birmanisch",
  "NA": "Namibia",
  "NC": "Neukaledonien",
  "NE": "Niger",
  "NF": "Norfolkinsel",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Niederlande",
  "NO": "Norwegen",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Neutrale Zone",
  "NU": "Niue",
  "NZ": "Neuseeland",
  "Nand": "Nandinagari",
  "Narb": "Altnordarabisch",
  "Nbat": "Nabatäisch",
  "Newa": "Newa",
  "Nkgb": "Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Frauenschrift",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orchon-Runen",
  "Orya": "Oriya",
  "Osge": "Osage",
  "Osma": "Osmanisch",
  "PA": "Panama",
  "PC": "Pacific Islands Trust Territory",
  "PE": "Peru",
  "PF": "Französisch-Polynesien",
  "PG": "Papua-Neuguinea",
  "PH": "Philippinen",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "St. Pierre und Miquelon",
  "PN": "Pitcairninseln",
  "PR": "Puerto Rico",
  "PS": "Palästinensische Autonomiegebiete",
  "PT": "Portugal",
  "PU": "Verschiedene US-Pazifikinseln",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Panamakanal-Zone",
  "Palm": "Palmyrenisch",
  "Pauc": "Pau Cin Hau",
  "Perm": "Altpermisch",
  "Phag": "Phags-pa",
  "Phli": "Buch-Pahlavi",
  "Phlp": "Psalter-Pahlavi",
  "Phlv": "Pahlavi",
  "Phnx": "Phönizisch",
  "Plrd": "Pollard Phonetisch",
  "Prti": "Parthisch",
  "QA": "Katar",
  "QO": "Äußeres Ozeanien",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Rumänien",
  "RS": "Serbien",
  "RU": "Russland",
  "RW": "Ruanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runenschrift",
  "SA": "Saudi-Arabien",
  "SB": "Salomonen",
  "SC": "Seychellen",
  "SD": "Sudan",
  "SE": "Schweden",
  "SG": "Singapur",
  "SH": "St. Helena",
  "SI": "Slowenien",
  "SJ": "Spitzbergen und Jan Mayen",
  "SK": "Slowakei",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Südsudan",
  "ST": "São Tomé und Príncipe",
  "SU": "Union der Sozialistischen Sowjetrepubliken",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syrien",
  "SZ": "Eswatini",
  "Samr": "Samaritanisch",
  "Sara": "Sarati",
  "Sarb": "Altsüdarabisch",
  "Saur": "Saurashtra",
  "Sgnw": "Gebärdensprache",
  "Shaw": "Shaw-Alphabet",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "Singhalesisch",
  "Sogd": "Sogdisch",
  "Sogo": "Alt-Sogdisch",
  "Sora": "Sora Sompeng",
  "Soyo": "Sojombo",
  "Sund": "Sundanesisch",
  "Sylo": "Syloti Nagri",
  "Syrc": "Syrisch",
  "Syre": "Syrisch - Estrangelo-Variante",
  "Syrj": "Westsyrisch",
  "Syrn": "Ostsyrisch",
  "TA": "Tristan da Cunha",
  "TC": "Turks- und Caicosinseln",
  "TD": "Tschad",
  "TF": "Französische Süd- und Antarktisgebiete",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadschikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunesien",
  "TO": "Tonga",
  "TR": "Türkei",
  "TT": "Trinidad und Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Tai Lue",
  "Taml": "Tamilisch",
  "Tang": "Xixia",
  "Tavt": "Tai-Viet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibetisch",
  "Tirh": "Tirhuta",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "Amerikanische Überseeinseln",
  "UN": "Vereinte Nationen",
  "US": "Vereinigte Staaten",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "Ugar": "Ugaritisch",
  "VA": "Vatikanstadt",
  "VC": "St. Vincent und die Grenadinen",
  "VD": "Nordvietnam",
  "VE": "Venezuela",
  "VG": "Britische Jungferninseln",
  "VI": "Amerikanische Jungferninseln",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Sichtbare Sprache",
  "WF": "Wallis und Futuna",
  "WK": "Wake Island",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleaianisch",
  "XA": "Pseudo-Akzente",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "Altpersisch",
  "Xsux": "Sumerisch-akkadische Keilschrift",
  "YD": "Demokratische Volksrepublik Jemen",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "Südafrika",
  "ZM": "Sambia",
  "ZW": "Simbabwe",
  "ZZ": "Unbekannte Region",
  "Zanb": "Dsanabadsar-Quadratschrift",
  "Zinh": "Geerbter Schriftwert",
  "Zmth": "Mathematische Notation",
  "Zsye": "Emoji",
  "Zsym": "Symbole",
  "Zxxx": "Schriftlos",
  "Zyyy": "Verbreitet",
  "Zzzz": "Unbekannte Schrift",
  "aa": "Afar",
  "ab": "Abchasisch",
  "ace": "Aceh-Sprache",
  "ach": "Acholi-Sprache",
  "ada": "Adangme",
  "ady": "Adygeisch",
  "ae": "Avestisch",
  "aeb": "Tunesisches Arabisch",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (Südafrika)",
  "afa": "Afroasiatisch",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu-Sprache",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadisch",
  "akz": "Alabama",
  "ale": "Aleutisch",
  "alg": "Algonkin-Sprache",
  "aln": "Gegisch",
  "alt": "Süd-Altaisch",
  "am": "Amharisch",
  "am_ET": "Amharisch (Äthiopien)",
  "an": "Aragonesisch",
  "ang": "Altenglisch",
  "anp": "Angika",
  "apa": "Apache-Sprache",
  "ar": "Arabisch",
  "ar_001": "Modernes Hocharabisch",
  "ar_AE": "Arabisch (Vereinigte Arabische Emirate)",
  "ar_BH": "Arabisch (Bahrain)",
  "ar_DJ": "Arabisch (Dschibuti)",
  "ar_DZ": "Arabisch (Algerien)",
  "ar_EG": "Arabisch (Ägypten)",
  "ar_EH": "Arabisch (Westsahara)",
  "ar_ER": "Arabisch (Eritrea)",
  "ar_IL": "Arabisch (Israel)",
  "ar_IQ": "Arabisch (Irak)",
  "ar_JO": "Arabisch (Jordanien)",
  "ar_KM": "Arabisch (Komoren)",
  "ar_KW": "Arabisch (Kuwait)",
  "ar_LB": "Arabisch (Libanon)",
  "ar_LY": "Arabisch (Libyen)",
  "ar_MA": "Arabisch (Marokko)",
  "ar_MR": "Arabisch (Mauretanien)",
  "ar_OM": "Arabisch (Oman)",
  "ar_PS": "Arabisch (Palästinensische Autonomiegebiete)",
  "ar_QA": "Arabisch (Katar)",
  "ar_SA": "Arabisch (Saudi-Arabien)",
  "ar_SD": "Arabisch (Sudan)",
  "ar_SO": "Arabisch (Somalia)",
  "ar_SS": "Arabisch (Südsudan)",
  "ar_SY": "Arabisch (Syrien)",
  "ar_TD": "Arabisch (Tschad)",
  "ar_TN": "Arabisch (Tunesien)",
  "ar_YE": "Arabisch (Jemen)",
  "arc": "Aramäisch",
  "arn": "Araukanisch",
  "aro": "Araona",
  "arp": "Arapaho-Sprache",
  "arq": "Algerisches Arabisch",
  "ars": "Arabisch (Nadschd)",
  "art": "Kunstsprache",
  "arw": "Arawak-Sprache",
  "ary": "Marokkanisches Arabisch",
  "arz": "Ägyptisches Arabisch",
  "as": "Assamesisch",
  "as_IN": "Assamesisch (Indien)",
  "asa": "Pare",
  "ase": "Amerikanische Gebärdensprache",
  "ast": "Asturianisch",
  "ath": "Athapaskisch",
  "aus": "Australisch",
  "av": "Awarisch",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Aserbaidschanisch",
  "az_AZ": "Aserbaidschanisch (Aserbaidschan)",
  "az_Arab": "Aserbaidschanisch (Arabisch)",
  "az_Cyrl": "Aserbaidschanisch (Kyrillisch)",
  "az_Cyrl_AZ": "Aserbaidschanisch (Kyrillisch, Aserbaidschan)",
  "az_Latn": "Aserbaidschanisch (Lateinisch)",
  "az_Latn_AZ": "Aserbaidschanisch (Lateinisch, Aserbaidschan)",
  "azb": "Südaserbaidschanisch",
  "ba": "Baschkirisch",
  "bad": "Banda-Sprache",
  "bai": "Bamileke-Sprache",
  "bal": "Belutschisch",
  "ban": "Balinesisch",
  "bar": "Bairisch",
  "bas": "Basaa-Sprache",
  "bat": "Baltisch",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Weißrussisch",
  "be_BY": "Weißrussisch (Belarus)",
  "bej": "Bedauye",
  "bem": "Bemba-Sprache",
  "ber": "Berbersprache",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgarisch",
  "bg_BG": "Bulgarisch (Bulgarien)",
  "bgn": "Westliches Belutschi",
  "bh": "Biharisch",
  "bho": "Bhodschpuri",
  "bi": "Bislama",
  "bik": "Bikol-Sprache",
  "bin": "Bini-Sprache",
  "bjn": "Banjaresisch",
  "bkm": "Kom",
  "bla": "Blackfoot-Sprache",
  "bm": "Bambara-Sprache",
  "bm_Latn": "Bambara-Sprache (Lateinisch)",
  "bm_Latn_ML": "Bambara-Sprache (Lateinisch, Mali)",
  "bn": "Bengalisch",
  "bn_BD": "Bengalisch (Bangladesch)",
  "bn_IN": "Bengalisch (Indien)",
  "bnt": "Bantusprache",
  "bo": "Tibetisch",
  "bo_CN": "Tibetisch (China)",
  "bo_IN": "Tibetisch (Indien)",
  "bpy": "Bishnupriya",
  "bqi": "Bachtiarisch",
  "br": "Bretonisch",
  "br_FR": "Bretonisch (Frankreich)",
  "bra": "Braj-Bhakha",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnisch",
  "bs_BA": "Bosnisch (Bosnien und Herzegowina)",
  "bs_Cyrl": "Bosnisch (Kyrillisch)",
  "bs_Cyrl_BA": "Bosnisch (Kyrillisch, Bosnien und Herzegowina)",
  "bs_Latn": "Bosnisch (Lateinisch)",
  "bs_Latn_BA": "Bosnisch (Lateinisch, Bosnien und Herzegowina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Burjatisch",
  "bug": "Buginesisch",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalanisch",
  "ca_AD": "Katalanisch (Andorra)",
  "ca_ES": "Katalanisch (Spanien)",
  "ca_FR": "Katalanisch (Frankreich)",
  "ca_IT": "Katalanisch (Italien)",
  "cad": "Caddo",
  "cai": "Zentralamerikanische Indianersprache",
  "car": "Karibisch",
  "cau": "Kaukasisch",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Tschetschenisch",
  "ceb": "Cebuano",
  "cel": "Keltisch",
  "cgg": "Rukiga",
  "ch": "Chamorro-Sprache",
  "chb": "Chibcha-Sprache",
  "chg": "Tschagataisch",
  "chk": "Trukesisch",
  "chm": "Mari",
  "chn": "Chinook",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Sorani",
  "cmc": "Cham-Sprache",
  "co": "Korsisch",
  "cop": "Koptisch",
  "cpe": "Kreolisch-Englische Sprache",
  "cpf": "Kreolisch-Französische Sprache",
  "cpp": "Kreolisch-Portugiesische Sprache",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Krimtatarisch",
  "crp": "Kreolische Sprache",
  "crs": "Seychellenkreol",
  "cs": "Tschechisch",
  "cs_CZ": "Tschechisch (Tschechische Republik)",
  "csb": "Kaschubisch",
  "cu": "Kirchenslawisch",
  "cus": "Kuschitisch",
  "cv": "Tschuwaschisch",
  "cy": "Walisisch",
  "cy_GB": "Walisisch (Vereinigtes Königreich)",
  "da": "Dänisch",
  "da_DK": "Dänisch (Dänemark)",
  "da_GL": "Dänisch (Grönland)",
  "dak": "Dakota-Sprache",
  "dar": "Darginisch",
  "dav": "Taita",
  "day": "Dajak",
  "de": "Deutsch",
  "de_AT": "Deutsch (Österreich)",
  "de_BE": "Deutsch (Belgien)",
  "de_CH": "Deutsch (Schweiz)",
  "de_DE": "Deutsch (Deutschland)",
  "de_LI": "Deutsch (Liechtenstein)",
  "de_LU": "Deutsch (Luxemburg)",
  "del": "Delaware-Sprache",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka-Sprache",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Drawidisch",
  "dsb": "Niedersorbisch",
  "dtp": "Zentral-Dusun",
  "dua": "Duala",
  "dum": "Mittelniederländisch",
  "dv": "Maledivisch",
  "dyo": "Diola",
  "dyu": "Dyula-Sprache",
  "dz": "Bhutanisch",
  "dz_BT": "Bhutanisch (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilianisch",
  "egy": "Ägyptisch",
  "eka": "Ekajuk",
  "el": "Griechisch",
  "el_CY": "Griechisch (Zypern)",
  "el_GR": "Griechisch (Griechenland)",
  "elx": "Elamisch",
  "en": "Englisch",
  "en_AG": "Englisch (Antigua und Barbuda)",
  "en_AI": "Englisch (Anguilla)",
  "en_AS": "Englisch (Amerikanisch-Samoa)",
  "en_AU": "Englisch (Australien)",
  "en_BB": "Englisch (Barbados)",
  "en_BE": "Englisch (Belgien)",
  "en_BM": "Englisch (Bermuda)",
  "en_BS": "Englisch (Bahamas)",
  "en_BW": "Englisch (Botsuana)",
  "en_BZ": "Englisch (Belize)",
  "en_CA": "Englisch (Kanada)",
  "en_CC": "Englisch (Kokosinseln)",
  "en_CK": "Englisch (Cookinseln)",
  "en_CM": "Englisch (Kamerun)",
  "en_CX": "Englisch (Weihnachtsinsel)",
  "en_DG": "Englisch (Diego Garcia)",
  "en_DM": "Englisch (Dominica)",
  "en_Dsrt": "Englisch (Deseret)",
  "en_ER": "Englisch (Eritrea)",
  "en_FJ": "Englisch (Fidschi)",
  "en_FK": "Englisch (Falklandinseln)",
  "en_FM": "Englisch (Mikronesien)",
  "en_GB": "Englisch (Vereinigtes Königreich)",
  "en_GD": "Englisch (Grenada)",
  "en_GG": "Englisch (Guernsey)",
  "en_GH": "Englisch (Ghana)",
  "en_GI": "Englisch (Gibraltar)",
  "en_GM": "Englisch (Gambia)",
  "en_GU": "Englisch (Guam)",
  "en_GY": "Englisch (Guyana)",
  "en_HK": "Englisch (Sonderverwaltungszone Hongkong)",
  "en_IE": "Englisch (Irland)",
  "en_IM": "Englisch (Isle of Man)",
  "en_IN": "Englisch (Indien)",
  "en_IO": "Englisch (Britisches Territorium im Indischen Ozean)",
  "en_JE": "Englisch (Jersey)",
  "en_JM": "Englisch (Jamaika)",
  "en_KE": "Englisch (Kenia)",
  "en_KI": "Englisch (Kiribati)",
  "en_KN": "Englisch (St. Kitts und Nevis)",
  "en_KY": "Englisch (Kaimaninseln)",
  "en_LC": "Englisch (St. Lucia)",
  "en_LR": "Englisch (Liberia)",
  "en_LS": "Englisch (Lesotho)",
  "en_MG": "Englisch (Madagaskar)",
  "en_MH": "Englisch (Marshallinseln)",
  "en_MO": "Englisch (Sonderverwaltungsregion Macau)",
  "en_MP": "Englisch (Nördliche Marianen)",
  "en_MS": "Englisch (Montserrat)",
  "en_MT": "Englisch (Malta)",
  "en_MU": "Englisch (Mauritius)",
  "en_MW": "Englisch (Malawi)",
  "en_MY": "Englisch (Malaysia)",
  "en_NA": "Englisch (Namibia)",
  "en_NF": "Englisch (Norfolkinsel)",
  "en_NG": "Englisch (Nigeria)",
  "en_NR": "Englisch (Nauru)",
  "en_NU": "Englisch (Niue)",
  "en_NZ": "Englisch (Neuseeland)",
  "en_PG": "Englisch (Papua-Neuguinea)",
  "en_PH": "Englisch (Philippinen)",
  "en_PK": "Englisch (Pakistan)",
  "en_PN": "Englisch (Pitcairninseln)",
  "en_PR": "Englisch (Puerto Rico)",
  "en_PW": "Englisch (Palau)",
  "en_RW": "Englisch (Ruanda)",
  "en_SB": "Englisch (Salomonen)",
  "en_SC": "Englisch (Seychellen)",
  "en_SD": "Englisch (Sudan)",
  "en_SG": "Englisch (Singapur)",
  "en_SH": "Englisch (St. Helena)",
  "en_SL": "Englisch (Sierra Leone)",
  "en_SS": "Englisch (Südsudan)",
  "en_SX": "Englisch (Sint Maarten)",
  "en_SZ": "Englisch (Swasiland)",
  "en_TC": "Englisch (Turks- und Caicosinseln)",
  "en_TK": "Englisch (Tokelau)",
  "en_TO": "Englisch (Tonga)",
  "en_TT": "Englisch (Trinidad und Tobago)",
  "en_TV": "Englisch (Tuvalu)",
  "en_TZ": "Englisch (Tansania)",
  "en_UG": "Englisch (Uganda)",
  "en_UM": "Englisch (Amerikanisch-Ozeanien)",
  "en_US": "Englisch (Vereinigte Staaten)",
  "en_VC": "Englisch (St. Vincent und die Grenadinen)",
  "en_VG": "Englisch (Britische Jungferninseln)",
  "en_VI": "Englisch (Amerikanische Jungferninseln)",
  "en_VU": "Englisch (Vanuatu)",
  "en_WS": "Englisch (Samoa)",
  "en_ZA": "Englisch (Südafrika)",
  "en_ZM": "Englisch (Sambia)",
  "en_ZW": "Englisch (Simbabwe)",
  "enm": "Mittelenglisch",
  "eo": "Esperanto",
  "es": "Spanisch",
  "es_419": "Lateinamerikanisches Spanisch",
  "es_AR": "Spanisch (Argentinien)",
  "es_BO": "Spanisch (Bolivien)",
  "es_CL": "Spanisch (Chile)",
  "es_CO": "Spanisch (Kolumbien)",
  "es_CR": "Spanisch (Costa Rica)",
  "es_CU": "Spanisch (Kuba)",
  "es_DO": "Spanisch (Dominikanische Republik)",
  "es_EA": "Spanisch (Ceuta und Melilla)",
  "es_EC": "Spanisch (Ecuador)",
  "es_ES": "Spanisch (Spanien)",
  "es_GQ": "Spanisch (Äquatorialguinea)",
  "es_GT": "Spanisch (Guatemala)",
  "es_HN": "Spanisch (Honduras)",
  "es_IC": "Spanisch (Kanarische Inseln)",
  "es_MX": "Spanisch (Mexiko)",
  "es_NI": "Spanisch (Nicaragua)",
  "es_PA": "Spanisch (Panama)",
  "es_PE": "Spanisch (Peru)",
  "es_PH": "Spanisch (Philippinen)",
  "es_PR": "Spanisch (Puerto Rico)",
  "es_PY": "Spanisch (Paraguay)",
  "es_SV": "Spanisch (El Salvador)",
  "es_US": "Spanisch (Vereinigte Staaten)",
  "es_UY": "Spanisch (Uruguay)",
  "es_VE": "Spanisch (Venezuela)",
  "esu": "Zentral-Alaska-Yupik",
  "et": "Estnisch",
  "et_EE": "Estnisch (Estland)",
  "eu": "Baskisch",
  "eu_ES": "Baskisch (Spanien)",
  "ewo": "Ewondo",
  "ext": "Extremadurisch",
  "fa": "Persisch",
  "fa_AF": "Persisch (Afghanistan)",
  "fa_IR": "Persisch (Iran)",
  "fan": "Pangwe-Sprache",
  "fat": "Fanti-Sprache",
  "ff": "Ful",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Ful (Kamerun)",
  "ff_GN": "Ful (Guinea)",
  "ff_MR": "Ful (Mauretanien)",
  "ff_SN": "Ful (Senegal)",
  "fi": "Finnisch",
  "fi_FI": "Finnisch (Finnland)",
  "fil": "Filipino",
  "fit": "Meänkieli",
  "fiu": "Finnougrisch",
  "fj": "Fidschi",
  "fo": "Färöisch",
  "fo_FO": "Färöisch (Färöer)",
  "fon": "Fon-Sprache",
  "fr": "Französisch",
  "fr_BE": "Französisch (Belgien)",
  "fr_BF": "Französisch (Burkina Faso)",
  "fr_BI": "Französisch (Burundi)",
  "fr_BJ": "Französisch (Benin)",
  "fr_BL": "Französisch (St. Barthélemy)",
  "fr_CA": "Französisch (Kanada)",
  "fr_CD": "Französisch (Kongo-Kinshasa)",
  "fr_CF": "Französisch (Zentralafrikanische Republik)",
  "fr_CG": "Französisch (Kongo-Brazzaville)",
  "fr_CH": "Französisch (Schweiz)",
  "fr_CI": "Französisch (Côte d’Ivoire)",
  "fr_CM": "Französisch (Kamerun)",
  "fr_DJ": "Französisch (Dschibuti)",
  "fr_DZ": "Französisch (Algerien)",
  "fr_FR": "Französisch (Frankreich)",
  "fr_GA": "Französisch (Gabun)",
  "fr_GF": "Französisch (Französisch-Guayana)",
  "fr_GN": "Französisch (Guinea)",
  "fr_GP": "Französisch (Guadeloupe)",
  "fr_GQ": "Französisch (Äquatorialguinea)",
  "fr_HT": "Französisch (Haiti)",
  "fr_KM": "Französisch (Komoren)",
  "fr_LU": "Französisch (Luxemburg)",
  "fr_MA": "Französisch (Marokko)",
  "fr_MC": "Französisch (Monaco)",
  "fr_MF": "Französisch (St. Martin)",
  "fr_MG": "Französisch (Madagaskar)",
  "fr_ML": "Französisch (Mali)",
  "fr_MQ": "Französisch (Martinique)",
  "fr_MR": "Französisch (Mauretanien)",
  "fr_MU": "Französisch (Mauritius)",
  "fr_NC": "Französisch (Neukaledonien)",
  "fr_NE": "Französisch (Niger)",
  "fr_PF": "Französisch (Französisch-Polynesien)",
  "fr_PM": "Französisch (St. Pierre und Miquelon)",
  "fr_RE": "Französisch (Réunion)",
  "fr_RW": "Französisch (Ruanda)",
  "fr_SC": "Französisch (Seychellen)",
  "fr_SN": "Französisch (Senegal)",
  "fr_SY": "Französisch (Syrien)",
  "fr_TD": "Französisch (Tschad)",
  "fr_TG": "Französisch (Togo)",
  "fr_TN": "Französisch (Tunesien)",
  "fr_VU": "Französisch (Vanuatu)",
  "fr_WF": "Französisch (Wallis und Futuna)",
  "fr_YT": "Französisch (Mayotte)",
  "frc": "Cajun",
  "frm": "Mittelfranzösisch",
  "fro": "Altfranzösisch",
  "frp": "Frankoprovenzalisch",
  "frr": "Nordfriesisch",
  "frs": "Ostfriesisch",
  "fur": "Friulisch",
  "fy": "Westfriesisch",
  "fy_NL": "Westfriesisch (Niederlande)",
  "ga": "Irisch",
  "ga_IE": "Irisch (Irland)",
  "gaa": "Ga-Sprache",
  "gag": "Gagausisch",
  "gan": "Gan",
  "gay": "Gayo",
  "gba": "Gbaya-Sprache",
  "gbz": "Gabri",
  "gd": "Schottisches Gälisch",
  "gd_GB": "Schottisches Gälisch (Vereinigtes Königreich)",
  "gem": "Germanisch",
  "gez": "Geez",
  "gil": "Gilbertesisch",
  "gl": "Galizisch",
  "gl_ES": "Galizisch (Spanien)",
  "glk": "Gilaki",
  "gmh": "Mittelhochdeutsch",
  "gn": "Guarani",
  "goh": "Althochdeutsch",
  "gom": "Goa-Konkani",
  "gon": "Gondi-Sprache",
  "gor": "Mongondou",
  "got": "Gotisch",
  "grb": "Grebo-Sprache",
  "grc": "Altgriechisch",
  "gsw": "Schweizerdeutsch",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (Indien)",
  "guc": "Wayúu",
  "gur": "Farefare",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Kutchin-Sprache",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Lateinisch)",
  "ha_Latn_GH": "Hausa (Lateinisch, Ghana)",
  "ha_Latn_NE": "Hausa (Lateinisch, Niger)",
  "ha_Latn_NG": "Hausa (Lateinisch, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida-Sprache",
  "hak": "Hakka",
  "haw": "Hawaiisch",
  "he": "Hebräisch",
  "he_IL": "Hebräisch (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (Indien)",
  "hif": "Fidschi-Hindi",
  "hil": "Hiligaynon-Sprache",
  "him": "Himachali",
  "hit": "Hethitisch",
  "hmn": "Miao-Sprache",
  "ho": "Hiri-Motu",
  "hr": "Kroatisch",
  "hr_BA": "Kroatisch (Bosnien und Herzegowina)",
  "hr_HR": "Kroatisch (Kroatien)",
  "hsb": "Obersorbisch",
  "hsn": "Xiang",
  "ht": "Haitianisch",
  "hu": "Ungarisch",
  "hu_HU": "Ungarisch (Ungarn)",
  "hup": "Hupa",
  "hy": "Armenisch",
  "hy_AM": "Armenisch (Armenien)",
  "hz": "Herero-Sprache",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indonesisch",
  "id_ID": "Indonesisch (Indonesien)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Yi",
  "ii_CN": "Yi (China)",
  "ijo": "Ijo-Sprache",
  "ik": "Inupiak",
  "ilo": "Ilokano-Sprache",
  "inc": "Indoarisch",
  "ine": "Indogermanisch",
  "inh": "Inguschisch",
  "io": "Ido-Sprache",
  "ira": "Iranische Sprache",
  "iro": "Irokesische Sprache",
  "is": "Isländisch",
  "is_IS": "Isländisch (Island)",
  "it": "Italienisch",
  "it_CH": "Italienisch (Schweiz)",
  "it_IT": "Italienisch (Italien)",
  "it_SM": "Italienisch (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ischorisch",
  "ja": "Japanisch",
  "ja_JP": "Japanisch (Japan)",
  "jam": "Jamaikanisch-kreolische Sprache",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Jüdisch-Persisch",
  "jrb": "Jüdisch-Arabisch",
  "jut": "Jütisch",
  "jv": "Javanisch",
  "ka": "Georgisch",
  "ka_GE": "Georgisch (Georgien)",
  "kaa": "Karakalpakisch",
  "kab": "Kabylisch",
  "kac": "Kachin-Sprache",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karenisch",
  "kaw": "Kawi",
  "kbd": "Kabardinisch",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongolesisch",
  "kgp": "Kaingang",
  "kha": "Khasi-Sprache",
  "khi": "Khoisan-Sprache",
  "kho": "Sakisch",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenia)",
  "kiu": "Kirmanjki",
  "kj": "Kwanyama",
  "kk": "Kasachisch",
  "kk_Cyrl": "Kasachisch (Kyrillisch)",
  "kk_Cyrl_KZ": "Kasachisch (Kyrillisch, Kasachstan)",
  "kk_KZ": "Kasachisch (Kasachstan)",
  "kkj": "Kako",
  "kl": "Grönländisch",
  "kl_GL": "Grönländisch (Grönland)",
  "kln": "Kalenjin",
  "km": "Kambodschanisch",
  "km_KH": "Kambodschanisch (Kambodscha)",
  "kmb": "Kimbundu-Sprache",
  "kn": "Kannada",
  "kn_IN": "Kannada (Indien)",
  "ko": "Koreanisch",
  "ko_KP": "Koreanisch (Demokratische Volksrepublik Korea)",
  "ko_KR": "Koreanisch (Republik Korea)",
  "koi": "Komi-Permjakisch",
  "kok": "Konkani",
  "kos": "Kosraeanisch",
  "kpe": "Kpelle-Sprache",
  "kr": "Kanuri-Sprache",
  "krc": "Karatschaiisch-Balkarisch",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelisch",
  "kro": "Kru-Sprache",
  "kru": "Oraon-Sprache",
  "ks": "Kaschmirisch",
  "ks_Arab": "Kaschmirisch (Arabisch)",
  "ks_Arab_IN": "Kaschmirisch (Arabisch, Indien)",
  "ks_IN": "Kaschmirisch (Indien)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Kölsch",
  "ku": "Kurdisch",
  "kum": "Kumükisch",
  "kut": "Kutenai-Sprache",
  "kv": "Komi-Sprache",
  "kw": "Kornisch",
  "kw_GB": "Kornisch (Vereinigtes Königreich)",
  "ky": "Kirgisisch",
  "ky_Cyrl": "Kirgisisch (Kyrillisch)",
  "ky_Cyrl_KG": "Kirgisisch (Kyrillisch, Kirgisistan)",
  "ky_KG": "Kirgisisch (Kirgisistan)",
  "la": "Latein",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba-Sprache",
  "lb": "Luxemburgisch",
  "lb_LU": "Luxemburgisch (Luxemburg)",
  "lez": "Lesgisch",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgisch",
  "lij": "Ligurisch",
  "liv": "Livisch",
  "lkt": "Lakota",
  "lmo": "Lombardisch",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Kongo-Kinshasa)",
  "ln_CF": "Lingala (Zentralafrikanische Republik)",
  "ln_CG": "Lingala (Kongo-Brazzaville)",
  "lo": "Laotisch",
  "lo_LA": "Laotisch (Laos)",
  "lol": "Mongo",
  "lou": "Kreol (Louisiana)",
  "loz": "Rotse-Sprache",
  "lrc": "Nördliches Luri",
  "lt": "Litauisch",
  "lt_LT": "Litauisch (Litauen)",
  "ltg": "Lettgallisch",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Kongo-Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno-Sprache",
  "lun": "Lunda-Sprache",
  "luo": "Luo-Sprache",
  "lus": "Lushai-Sprache",
  "luy": "Luhya",
  "lv": "Lettisch",
  "lv_LV": "Lettisch (Lettland)",
  "lzh": "Klassisches Chinesisch",
  "lzz": "Lasisch",
  "mad": "Maduresisch",
  "maf": "Mafa",
  "mag": "Khotta",
  "mai": "Maithili",
  "mak": "Makassarisch",
  "man": "Manding-Sprache",
  "map": "Austronesisch",
  "mas": "Massai-Sprache",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandaresisch",
  "men": "Mende-Sprache",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Madagassisch",
  "mg_MG": "Madagassisch (Madagaskar)",
  "mga": "Mittelirisch",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta’",
  "mh": "Marschallesisch",
  "mi": "Maori",
  "mic": "Micmac-Sprache",
  "min": "Minangkabau-Sprache",
  "mis": "Andere Sprache",
  "mk": "Mazedonisch",
  "mk_MK": "Mazedonisch (Mazedonien)",
  "mkh": "Mon-Khmer-Sprache",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (Indien)",
  "mn": "Mongolisch",
  "mn_Cyrl": "Mongolisch (Kyrillisch)",
  "mn_Cyrl_MN": "Mongolisch (Kyrillisch, Mongolei)",
  "mn_MN": "Mongolisch (Mongolei)",
  "mnc": "Mandschurisch",
  "mni": "Meithei-Sprache",
  "mno": "Manobo-Sprache",
  "mo": "Moldauisch",
  "moh": "Mohawk",
  "mos": "Mossi-Sprache",
  "mr": "Marathi",
  "mr_IN": "Marathi (Indien)",
  "mrj": "Bergmari",
  "ms": "Malaiisch",
  "ms_BN": "Malaiisch (Brunei Darussalam)",
  "ms_Latn": "Malaiisch (Lateinisch)",
  "ms_Latn_BN": "Malaiisch (Lateinisch, Brunei Darussalam)",
  "ms_Latn_MY": "Malaiisch (Lateinisch, Malaysia)",
  "ms_Latn_SG": "Malaiisch (Lateinisch, Singapur)",
  "ms_MY": "Malaiisch (Malaysia)",
  "ms_SG": "Malaiisch (Singapur)",
  "mt": "Maltesisch",
  "mt_MT": "Maltesisch (Malta)",
  "mua": "Mundang",
  "mul": "Mehrsprachig",
  "mun": "Munda-Sprache",
  "mus": "Muskogee-Sprache",
  "mwl": "Mirandesisch",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Birmanisch",
  "my_MM": "Birmanisch (Myanmar)",
  "mye": "Myene",
  "myn": "Maya-Sprache",
  "myv": "Ersja-Mordwinisch",
  "mzn": "Masanderanisch",
  "na": "Nauruisch",
  "nah": "Nahuatl",
  "nai": "Nordamerikanische Indianersprache",
  "nan": "Min Nan",
  "nap": "Neapolitanisch",
  "naq": "Nama",
  "nb": "Norwegisch Bokmål",
  "nb_NO": "Norwegisch Bokmål (Norwegen)",
  "nb_SJ": "Norwegisch Bokmål (Svalbard und Jan Mayen)",
  "nd": "Nord-Ndebele-Sprache",
  "nd_ZW": "Nord-Ndebele-Sprache (Simbabwe)",
  "nds": "Niederdeutsch",
  "nds_NL": "Niedersächsisch",
  "ne": "Nepalesisch",
  "ne_IN": "Nepalesisch (Indien)",
  "ne_NP": "Nepalesisch (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias-Sprache",
  "nic": "Nigerkordofanisch",
  "niu": "Niue-Sprache",
  "njo": "Ao-Naga",
  "nl": "Niederländisch",
  "nl_AW": "Niederländisch (Aruba)",
  "nl_BE": "Niederländisch (Belgien)",
  "nl_BQ": "Niederländisch (Karibische Niederlande)",
  "nl_CW": "Niederländisch (Curaçao)",
  "nl_NL": "Niederländisch (Niederlande)",
  "nl_SR": "Niederländisch (Suriname)",
  "nl_SX": "Niederländisch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegisch Nynorsk",
  "nn_NO": "Norwegisch Nynorsk (Norwegen)",
  "nnh": "Ngiemboon",
  "no": "Norwegisch",
  "no_NO": "Norwegisch (Norwegen)",
  "nog": "Nogai",
  "non": "Altnordisch",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Süd-Ndebele-Sprache",
  "nso": "Nord-Sotho-Sprache",
  "nub": "Nubisch",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Alt-Newari",
  "ny": "Nyanja-Sprache",
  "nym": "Nyamwezi-Sprache",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Okzitanisch",
  "oj": "Ojibwa-Sprache",
  "om": "Oromo",
  "om_ET": "Oromo (Äthiopien)",
  "om_KE": "Oromo (Kenia)",
  "or": "Oriya",
  "or_IN": "Oriya (Indien)",
  "os": "Ossetisch",
  "os_GE": "Ossetisch (Georgien)",
  "os_RU": "Ossetisch (Russische Föderation)",
  "osa": "Osage-Sprache",
  "ota": "Osmanisch",
  "oto": "Otomangue-Sprache",
  "pa": "Panjabi",
  "pa_Arab": "Panjabi (Arabisch)",
  "pa_Arab_PK": "Panjabi (Arabisch, Pakistan)",
  "pa_Guru": "Panjabi (Gurmukhi)",
  "pa_Guru_IN": "Panjabi (Gurmukhi, Indien)",
  "pa_IN": "Panjabi (Indien)",
  "pa_PK": "Panjabi (Pakistan)",
  "paa": "Papuasprache",
  "pag": "Pangasinan-Sprache",
  "pal": "Mittelpersisch",
  "pam": "Pampanggan-Sprache",
  "pap": "Papiamento",
  "pau": "Palau",
  "pcd": "Picardisch",
  "pcm": "Nigerianisches Pidgin",
  "pdc": "Pennsylvaniadeutsch",
  "pdt": "Plautdietsch",
  "peo": "Altpersisch",
  "pfl": "Pfälzisch",
  "phi": "Philippinen-Austronesisch",
  "phn": "Phönikisch",
  "pi": "Pali",
  "pl": "Polnisch",
  "pl_PL": "Polnisch (Polen)",
  "pms": "Piemontesisch",
  "pnt": "Pontisch",
  "pon": "Ponapeanisch",
  "pra": "Prakrit",
  "prg": "Altpreußisch",
  "pro": "Altprovenzalisch",
  "ps": "Paschtu",
  "ps_AF": "Paschtu (Afghanistan)",
  "pt": "Portugiesisch",
  "pt_AO": "Portugiesisch (Angola)",
  "pt_BR": "Portugiesisch (Brasilien)",
  "pt_CV": "Portugiesisch (Kap Verde)",
  "pt_GW": "Portugiesisch (Guinea-Bissau)",
  "pt_MO": "Portugiesisch (Sonderverwaltungsregion Macau)",
  "pt_MZ": "Portugiesisch (Mosambik)",
  "pt_PT": "Portugiesisch (Portugal)",
  "pt_ST": "Portugiesisch (São Tomé und Príncipe)",
  "pt_TL": "Portugiesisch (Timor-Leste)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivien)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "K’iche’",
  "qug": "Chimborazo Hochland-Quechua",
  "raj": "Rajasthani",
  "rap": "Osterinsel-Sprache",
  "rar": "Rarotonganisch",
  "rgn": "Romagnol",
  "rif": "Tarifit",
  "rm": "Rätoromanisch",
  "rm_CH": "Rätoromanisch (Schweiz)",
  "rn": "Rundi-Sprache",
  "rn_BI": "Rundi-Sprache (Burundi)",
  "ro": "Rumänisch",
  "ro_MD": "Rumänisch (Republik Moldau)",
  "ro_RO": "Rumänisch (Rumänien)",
  "roa": "Romanische Sprache",
  "rof": "Rombo",
  "rom": "Romani",
  "root": "Root",
  "rtm": "Rotumanisch",
  "ru": "Russisch",
  "ru_BY": "Russisch (Belarus)",
  "ru_KG": "Russisch (Kirgisistan)",
  "ru_KZ": "Russisch (Kasachstan)",
  "ru_MD": "Russisch (Republik Moldau)",
  "ru_RU": "Russisch (Russische Föderation)",
  "ru_UA": "Russisch (Ukraine)",
  "rue": "Russinisch",
  "rug": "Roviana",
  "rup": "Aromunisch",
  "rw": "Ruandisch",
  "rw_RW": "Ruandisch (Ruanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe-Sprache",
  "sah": "Jakutisch",
  "sai": "Südamerikanische Indianersprache",
  "sal": "Salish-Sprache",
  "sam": "Samaritanisch",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardisch",
  "scn": "Sizilianisch",
  "sco": "Schottisch",
  "sd": "Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarisch",
  "sdh": "Südkurdisch",
  "se": "Nord-Samisch",
  "se_FI": "Nord-Samisch (Finnland)",
  "se_NO": "Nord-Samisch (Norwegen)",
  "se_SE": "Nord-Samisch (Schweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkupisch",
  "sem": "Semitisch",
  "ses": "Koyra Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Zentralafrikanische Republik)",
  "sga": "Altirisch",
  "sgn": "Gebärdensprache",
  "sgs": "Samogitisch",
  "sh": "Serbo-Kroatisch",
  "sh_BA": "Serbo-Kroatisch (Bosnien und Herzegowina)",
  "shi": "Taschelhit",
  "shi_Latn": "Shilha (lateinisch)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Schan-Sprache",
  "shu": "Tschadisch-Arabisch",
  "si": "Singhalesisch",
  "si_LK": "Singhalesisch (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Sioux-Sprache",
  "sit": "Sinotibetisch",
  "sk": "Slowakisch",
  "sk_SK": "Slowakisch (Slowakei)",
  "sl": "Slowenisch",
  "sl_SI": "Slowenisch (Slowenien)",
  "sla": "Slawisch",
  "sli": "Schlesisch",
  "sly": "Selayar",
  "sm": "Samoanisch",
  "sma": "Süd-Samisch",
  "smi": "Lappisch",
  "smj": "Lule-Lappisch",
  "smn": "Inari-Lappisch",
  "sms": "Skolt-Lappisch",
  "sn": "Shona",
  "sn_ZW": "Shona (Simbabwe)",
  "snk": "Soninke-Sprache",
  "so": "Somali",
  "so_DJ": "Somali (Dschibuti)",
  "so_ET": "Somali (Äthiopien)",
  "so_KE": "Somali (Kenia)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdisch",
  "son": "Songhai-Sprache",
  "sq": "Albanisch",
  "sq_AL": "Albanisch (Albanien)",
  "sq_MK": "Albanisch (Mazedonien)",
  "sq_XK": "Albanisch (Kosovo)",
  "sr": "Serbisch",
  "sr_BA": "Serbisch (Bosnien und Herzegowina)",
  "sr_Cyrl": "Serbisch (Kyrillisch)",
  "sr_Cyrl_BA": "Serbisch (Kyrillisch, Bosnien und Herzegowina)",
  "sr_Cyrl_ME": "Serbisch (Kyrillisch, Montenegro)",
  "sr_Cyrl_RS": "Serbisch (Kyrillisch, Serbien)",
  "sr_Cyrl_XK": "Serbisch (Kyrillisch, Kosovo)",
  "sr_Latn": "Serbisch (Lateinisch)",
  "sr_Latn_BA": "Serbisch (Lateinisch, Bosnien und Herzegowina)",
  "sr_Latn_ME": "Serbisch (Lateinisch, Montenegro)",
  "sr_Latn_RS": "Serbisch (Lateinisch, Serbien)",
  "sr_Latn_XK": "Serbisch (Lateinisch, Kosovo)",
  "sr_ME": "Serbisch (Montenegro)",
  "sr_RS": "Serbisch (Serbien)",
  "sr_XK": "Serbisch (Kosovo)",
  "srn": "Srananisch",
  "srr": "Serer-Sprache",
  "ss": "Swazi",
  "ssa": "Nilosaharanisch",
  "ssy": "Saho",
  "st": "Süd-Sotho-Sprache",
  "stq": "Saterfriesisch",
  "su": "Sundanesisch",
  "suk": "Sukuma-Sprache",
  "sus": "Susu",
  "sux": "Sumerisch",
  "sv": "Schwedisch",
  "sv_AX": "Schwedisch (Åland-Inseln)",
  "sv_FI": "Schwedisch (Finnland)",
  "sv_SE": "Schwedisch (Schweden)",
  "sw": "Suaheli",
  "sw_CD": "Kongo-Swahili",
  "sw_KE": "Suaheli (Kenia)",
  "sw_TZ": "Suaheli (Tansania)",
  "sw_UG": "Suaheli (Uganda)",
  "swb": "Komorisch",
  "swc": "Kongo-Suaheli",
  "syc": "Altsyrisch",
  "syr": "Syrisch",
  "szl": "Schlesisch (Polen)",
  "ta": "Tamilisch",
  "ta_IN": "Tamilisch (Indien)",
  "ta_LK": "Tamilisch (Sri Lanka)",
  "ta_MY": "Tamilisch (Malaysia)",
  "ta_SG": "Tamilisch (Singapur)",
  "tai": "Tai-Sprache",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (Indien)",
  "tem": "Temne",
  "teo": "Teso",
  "ter": "Tereno-Sprache",
  "tet": "Tetum-Sprache",
  "tg": "Tadschikisch",
  "th": "Thailändisch",
  "th_TH": "Thailändisch (Thailand)",
  "ti": "Tigrinja",
  "ti_ER": "Tigrinja (Eritrea)",
  "ti_ET": "Tigrinja (Äthiopien)",
  "tig": "Tigre",
  "tiv": "Tiv-Sprache",
  "tk": "Turkmenisch",
  "tkl": "Tokelauanisch",
  "tkr": "Tsachurisch",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippinen)",
  "tlh": "Klingonisch",
  "tli": "Tlingit-Sprache",
  "tly": "Talisch",
  "tmh": "Tamaseq",
  "tn": "Tswana-Sprache",
  "to": "Tongaisch",
  "to_TO": "Tongaisch (Tonga)",
  "tog": "Tsonga-Sprache",
  "tpi": "Neumelanesisch",
  "tr": "Türkisch",
  "tr_CY": "Türkisch (Zypern)",
  "tr_TR": "Türkisch (Türkei)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonisch",
  "tsi": "Tsimshian-Sprache",
  "tt": "Tatarisch",
  "ttt": "Tatisch",
  "tum": "Tumbuka-Sprache",
  "tup": "Tupi-Sprache",
  "tut": "Altaisch",
  "tvl": "Elliceanisch",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitisch",
  "tyv": "Tuwinisch",
  "tzm": "Zentralatlas-Tamazight",
  "udm": "Udmurtisch",
  "ug": "Uigurisch",
  "ug_Arab": "Uigurisch (Arabisch)",
  "ug_Arab_CN": "Uigurisch (Arabisch, China)",
  "ug_CN": "Uigurisch (China)",
  "uga": "Ugaritisch",
  "uk": "Ukrainisch",
  "uk_UA": "Ukrainisch (Ukraine)",
  "umb": "Mbundu-Sprache",
  "und": "Unbestimmte Sprache",
  "ur": "Urdu",
  "ur_IN": "Urdu (Indien)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Usbekisch",
  "uz_AF": "Usbekisch (Afghanistan)",
  "uz_Arab": "Usbekisch (Arabisch)",
  "uz_Arab_AF": "Usbekisch (Arabisch, Afghanistan)",
  "uz_Cyrl": "Usbekisch (Kyrillisch)",
  "uz_Cyrl_UZ": "Usbekisch (Kyrillisch, Usbekistan)",
  "uz_Latn": "Usbekisch (Lateinisch)",
  "uz_Latn_UZ": "Usbekisch (Lateinisch, Usbekistan)",
  "uz_UZ": "Usbekisch (Usbekistan)",
  "vai": "Vai",
  "vai_Latn": "Vai (lateinisch)",
  "ve": "Venda-Sprache",
  "vec": "Venetisch",
  "vep": "Wepsisch",
  "vi": "Vietnamesisch",
  "vi_VN": "Vietnamesisch (Vietnam)",
  "vls": "Westflämisch",
  "vmf": "Mainfränkisch",
  "vo": "Volapük",
  "vot": "Wotisch",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Wallonisch",
  "wae": "Walser-Dialekte",
  "wak": "Wakashanisch",
  "wal": "Walamo-Sprache",
  "war": "Waray",
  "was": "Washo-Sprache",
  "wbp": "Warlpiri",
  "wen": "Sorbisch",
  "wo": "Wolof",
  "wuu": "Wu",
  "xal": "Kalmückisch",
  "xh": "Xhosa",
  "xmf": "Mingrelisch",
  "xog": "Soga",
  "yao": "Yao-Sprache",
  "yap": "Yapesisch",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Jiddisch",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "ypk": "Yupik-Sprache",
  "yrl": "Nheengatu",
  "yue": "Kantonesisch",
  "yue_Hans": "Kantonesisch (vereinfachtes Chinesisch)",
  "yue_Hant": "Kantonesisch (traditionelles Chinesisch)",
  "za": "Zhuang",
  "zap": "Zapotekisch",
  "zbl": "Bliss-Symbole",
  "zea": "Seeländisch",
  "zen": "Zenaga",
  "zgh": "Tamazight",
  "zh": "Chinesisch",
  "zh_CN": "Chinesisch (China)",
  "zh_HK": "Chinesisch (Sonderverwaltungszone Hongkong)",
  "zh_Hans": "Chinesisch (Vereinfacht)",
  "zh_Hans_CN": "Chinesisch (Vereinfacht, China)",
  "zh_Hans_HK": "Chinesisch (Vereinfacht, Sonderverwaltungszone Hongkong)",
  "zh_Hans_MO": "Chinesisch (Vereinfacht, Sonderverwaltungsregion Macau)",
  "zh_Hans_SG": "Chinesisch (Vereinfacht, Singapur)",
  "zh_Hant": "Chinesisch (Traditionell)",
  "zh_Hant_HK": "Chinesisch (Traditionell, Sonderverwaltungszone Hongkong)",
  "zh_Hant_MO": "Chinesisch (Traditionell, Sonderverwaltungsregion Macau)",
  "zh_Hant_TW": "Chinesisch (Traditionell, Taiwan)",
  "zh_MO": "Chinesisch (Sonderverwaltungsregion Macau)",
  "zh_SG": "Chinesisch (Singapur)",
  "zh_TW": "Chinesisch (Taiwan)",
  "znd": "Zande-Sprache",
  "zu": "Zulu",
  "zu_ZA": "Zulu (Südafrika)",
  "zun": "Zuni-Sprache",
  "zxx": "Keine Sprachinhalte",
  "zza": "Zaza"
};
