const names = {
  "aa": "Afar",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "aeb": "Tunisian Arabic",
  "ain": "Ainu",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "am": "amarike",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "arc": "Aramaic",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "azere",
  "az_AZ": "azere (Azerbajxhan)",
  "az_Cyrl": "azere (cirilik)",
  "az_Cyrl_AZ": "azere (cirilik, Azerbajxhan)",
  "az_Latn": "azere (latin)",
  "az_Latn_AZ": "azere (latin, Azerbajxhan)",
  "ban": "Balinese",
  "bas": "Basaa",
  "bem": "bemba",
  "bez": "bena",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bm": "bambara",
  "br": "bretone",
  "brx": "bodo",
  "bug": "Buginese",
  "byn": "Blin",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chr": "çeroki",
  "chy": "Cheyenne",
  "ckb": "kurdishte sorani",
  "co": "korsikanisht",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "taitisht",
  "de_AT": "gjermanisht (Austri)",
  "de_CH": "gjermanisht (Zvicër)",
  "dgr": "Dogrib",
  "dje": "zarmisht",
  "dua": "dualisht",
  "dv": "Divehi",
  "dyo": "xhula-fonji",
  "dz": "xongka",
  "dzg": "Dazaga",
  "ee": "juisht",
  "efi": "Efik",
  "eka": "Ekajuk",
  "en_AU": "anglisht (Australi)",
  "en_CA": "anglisht (Kanada)",
  "en_GB": "anglisht (Mbretëria e Bashkuar)",
  "en_US": "anglisht (Shtetet e Bashkuara të Amerikës)",
  "es_ES": "spanjisht (Spanjë)",
  "es_MX": "spanjisht (Meksikë)",
  "ewo": "Ewondo",
  "fa_AF": "persisht (Afganistan)",
  "ff": "Fulah",
  "fil": "filipinase",
  "fj": "fixhiane",
  "fon": "Fon",
  "fr_CA": "frëngjisht (Kanada)",
  "fr_CH": "frëngjisht (Zvicër)",
  "fur": "Friulian",
  "fy": "frizianisht",
  "ga": "irlandezçe",
  "gaa": "Ga",
  "gd": "Scottish Gaelic",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "galike",
  "gor": "Gorontalo",
  "gv": "mankse",
  "gwi": "Gwichʼin",
  "haw": "hauajane",
  "hi": "indishte",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hsb": "sorbiane e sipërme",
  "ht": "haitiançe",
  "hup": "Hupa",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ie": "Interlingue",
  "ig": "igbe",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "iu": "inuktitut",
  "jbo": "Lojban",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "kambishte",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kea": "kabuverdianisht",
  "kfo": "Koro",
  "kha": "Khasi",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kl": "kalalisute",
  "kln": "kalenjinisht",
  "km": "kmere",
  "kmb": "Kimbundu",
  "kn": "kanade",
  "koi": "komishte permiake",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "kashmire",
  "ksh": "Colognian",
  "ku": "kurde",
  "kum": "Kumyk",
  "kv": "Komi",
  "lad": "Ladino",
  "lb": "luksemburgase",
  "lez": "Lezghian",
  "lg": "gandisht",
  "li": "Limburgish",
  "loz": "Lozi",
  "lu": "Lubakatange",
  "lua": "Luba-Lulua",
  "lun": "Lunda",
  "lus": "Mizo",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "mdf": "Moksha",
  "men": "Mende",
  "mfe": "norisjene",
  "mg": "malageze",
  "mgh": "makuamito",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "ml": "malajalame",
  "mni": "Manipuri",
  "moh": "mohaukisht",
  "mos": "Mossi",
  "mua": "mundagishte",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "naq": "namaishte",
  "nb": "bokmalishte norvegjeze",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl_BE": "holandisht (Belgjikë)",
  "nn": "ninorske norvegjeze",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "nog": "Nogai",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nv": "Navajo",
  "ny": "Nyanja",
  "oc": "Occitan",
  "or": "orije",
  "os": "Ossetic",
  "pa": "panxhabe",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "prg": "Prussian",
  "ps": "pashto",
  "pt_BR": "portugalisht (Brazil)",
  "pt_PT": "portugalisht (Portugali)",
  "qu": "keçua",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "rome",
  "ro_MD": "rumanisht (Moldavi)",
  "rof": "romboishte",
  "root": "Root",
  "rup": "Aromanian",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "sindi",
  "seh": "senaishte",
  "sh": "Serbo-Kroatisht",
  "shi": "taçelit",
  "shn": "Shan",
  "si": "sinhale",
  "sm": "Samoan",
  "smj": "samishte luleje",
  "smn": "samishte inarie",
  "sms": "samishte skolte",
  "snk": "Soninke",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "suk": "Sukuma",
  "swb": "Comorian",
  "syr": "Syriac",
  "ta": "tamile",
  "te": "teluge",
  "tem": "Timne",
  "teo": "tezoisht",
  "tet": "Tetum",
  "ti": "tigrinje",
  "tig": "Tigre",
  "tlh": "Klingon",
  "tn": "Tswana",
  "tpi": "Tok Pisin",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "tasaukisht",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "tamaziatishte atlase qendrore",
  "udm": "Udmurt",
  "ug": "ujgure",
  "umb": "Umbundu",
  "und": "e panjohur",
  "ur": "urdu",
  "uz": "uzbeke",
  "ve": "Venda",
  "vo": "Volapük",
  "vun": "vunjisht",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "wo": "ulufisht",
  "xal": "Kalmyk",
  "xh": "xhose",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "jorubisht",
  "yue": "Cantonese",
  "zgh": "tamazishte standarde marokene",
  "zh_Hans": "kinezisht (i thjeshtuar)",
  "zh_Hant": "kinezisht (tradicional)",
  "zu": "zulu",
  "zun": "Zuni",
  "zza": "Zaza"
};
