const names = {
  "001": "Wrâld",
  "002": "Afrika",
  "003": "Noard-Amerika",
  "005": "Sûd-Amerika",
  "009": "Oceanië",
  "011": "West-Afrika",
  "013": "Midden-Amerika",
  "014": "East-Afrika",
  "015": "Noard-Afrika",
  "017": "Sintraal-Afrika",
  "018": "Sûdelijk Afrika",
  "019": "Amerika",
  "021": "Noardlik Amerika",
  "029": "Karibysk gebiet",
  "030": "East-Azië",
  "034": "Sûd-Azië",
  "035": "Sûdoost-Azië",
  "039": "Sûd-Europa",
  "053": "Australazië",
  "054": "Melanesië",
  "057": "Micronesyske regio",
  "061": "Polynesië",
  "062": "Súd-Sintraal-Aazje",
  "142": "Azië",
  "143": "Sintraal-Azië",
  "145": "West-Azië",
  "150": "Europa",
  "151": "East-Europa",
  "154": "Noard-Europa",
  "155": "West-Europa",
  "172": "Commonwealth of Independent States",
  "200": "Tsjechoslowakije",
  "202": "Sub-Sahara Afrika",
  "419": "Latynsk-Amearika",
  "830": "Kanaaleilannen",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Verenigde Arabyske Emiraten",
  "AF": "Afghanistan",
  "AG": "Antigua en Barbuda",
  "AI": "Anguilla",
  "AL": "Albanië",
  "AM": "Armenië",
  "AN": "Nederlânske Antillen",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentinië",
  "AS": "Amerikaansk Samoa",
  "AT": "Eastenryk",
  "AU": "Australië",
  "AW": "Aruba",
  "AX": "Ålân",
  "AZ": "Azerbeidzjan",
  "Adlm": "Adlam",
  "Afak": "Defaka",
  "Aghb": "Kaukasyske Albaneesk",
  "Ahom": "Ahom",
  "Arab": "Arabysk",
  "Aran": "Nastaliq",
  "Armi": "Keizerlijk Aramees",
  "Armn": "Armeens",
  "Avst": "Avestaansk",
  "BA": "Bosnië en Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "België",
  "BF": "Burkina Faso",
  "BG": "Bulgarije",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Karibysk Nederlân",
  "BR": "Brazilië",
  "BS": "Bahama’s",
  "BT": "Bhutan",
  "BV": "Bouveteilân",
  "BW": "Botswana",
  "BY": "Wit-Ruslân",
  "BZ": "Belize",
  "Bali": "Balineesk",
  "Bamu": "Bamoun",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Bengalees",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbolen",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Bugineesk",
  "Buhd": "Buhid",
  "CA": "Canada",
  "CC": "Kokosilanen",
  "CD": "Congo-Kinshasa",
  "CF": "Sintraal-Afrikaanske Republyk",
  "CG": "Congo-Brazzaville",
  "CH": "Switserlân",
  "CI": "Ivoorkust",
  "CK": "Cookeilannen",
  "CL": "Chili",
  "CM": "Kameroen",
  "CN": "Sina",
  "CO": "Kolombia",
  "CP": "Clipperton",
  "CR": "Costa Rica",
  "CS": "Servje en Montenegro",
  "CU": "Kuba",
  "CV": "Kaapverdië",
  "CW": "Curaçao",
  "CX": "Krysteilan",
  "CY": "Syprus",
  "CZ": "Tsjechje",
  "Cakm": "Chakma",
  "Cans": "Verenigde Canadese Aboriginal-symbolen",
  "Cari": "Karysk",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Koptysk",
  "Cprt": "Syprysk",
  "Cyrl": "Syrillysk",
  "Cyrs": "Aldkerkslavysk Syrillysk",
  "DD": "East-Dútslân",
  "DE": "Dútslân",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Denemarken",
  "DM": "Dominika",
  "DO": "Dominikaanske Republyk",
  "DZ": "Algerije",
  "Deva": "Devanagari",
  "Diak": "Dûkt Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Duployan snelschrift",
  "EA": "Ceuta en Melilla",
  "EC": "Ecuador",
  "EE": "Estlân",
  "EG": "Egypte",
  "EH": "Westelijke Sahara",
  "ER": "Eritrea",
  "ES": "Spanje",
  "ET": "Ethiopië",
  "EU": "Europeeske Unie",
  "EZ": "Eurosône",
  "Egyd": "Egyptysk demotysk",
  "Egyh": "Egyptysk hiëratysk",
  "Egyp": "Egyptyske hiërogliefen",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "Ethiopysk",
  "FI": "Finlân",
  "FJ": "Fiji",
  "FK": "Falklâneilannen",
  "FM": "Micronesië",
  "FO": "Faeröer",
  "FR": "Frankrijk",
  "FX": "Metropolitan Frankryk",
  "GA": "Gabon",
  "GB": "Verenigd Koninkrijk",
  "GD": "Grenada",
  "GE": "Georgië",
  "GF": "Frans-Guyana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grienlân",
  "GM": "Gambia",
  "GN": "Guinee",
  "GP": "Guadeloupe",
  "GQ": "Equatoriaal-Guinea",
  "GR": "Grikelân",
  "GS": "Sûd-Georgia en Sûdlike Sandwicheilannen",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinee-Bissau",
  "GY": "Guyana",
  "Geok": "Georgysk Khutsuri",
  "Geor": "Georgysk",
  "Glag": "Glagolitysk",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gothysk",
  "Gran": "Grantha",
  "Grek": "Grieks",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Hongkong SAR van Sina",
  "HM": "Heard- en McDonaldeilannen",
  "HN": "Honduras",
  "HR": "Kroatië",
  "HT": "Haïti",
  "HU": "Hongarije",
  "Hanb": "Han mei Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "Ferienfâldigd",
  "Hant": "Traditjoneel",
  "Hatr": "Hatran",
  "Hebr": "Hebreeuwsk",
  "Hira": "Hiragana",
  "Hluw": "Anatolyske hiërogliefen",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Katakana of Hiragana",
  "Hung": "Aldhongaars",
  "IC": "Kanaryske Eilânnen",
  "ID": "Yndonesië",
  "IE": "Ierlân",
  "IL": "Israël",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "Britse Gebieden yn de Indyske Oseaan",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Yslân",
  "IT": "Italië",
  "Inds": "Indus",
  "Ital": "Ald-italysk",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordanië",
  "JP": "Japan",
  "Jamo": "Jamo",
  "Java": "Javaansk",
  "Jpan": "Japans",
  "Jurc": "Jurchen",
  "KE": "Kenia",
  "KG": "Kirgizië",
  "KH": "Cambodja",
  "KI": "Kiribati",
  "KM": "Comoren",
  "KN": "Saint Kitts en Nevis",
  "KP": "Noard-Korea",
  "KR": "Sûd-Korea",
  "KW": "Koeweit",
  "KY": "Caymaneilannen",
  "KZ": "Kazachstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kits": "Khitan lyts skript",
  "Knda": "Kannada",
  "Kore": "Koreaansk",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litouwen",
  "LU": "Luxemburg",
  "LV": "Letlân",
  "LY": "Libië",
  "Lana": "Lanna",
  "Laoo": "Lao",
  "Latf": "Gotysk Latyn",
  "Latg": "Gaelysk Latyn",
  "Latn": "Latyn",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Lineair A",
  "Linb": "Lineair B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycysk",
  "Lydi": "Lydysk",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldavië",
  "ME": "Montenegro",
  "MF": "Saint-Martin",
  "MG": "Madeiaskar",
  "MH": "Marshalleilannen",
  "MI": "Midway Islands",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar (Birma)",
  "MN": "Mongolië",
  "MO": "Macao SAR van Sina",
  "MP": "Noardlike Marianeneilannen",
  "MQ": "Martinique",
  "MR": "Mauritanië",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldiven",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Maleisië",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaeans",
  "Mani": "Manicheaansk",
  "Marc": "Marchen",
  "Maya": "Mayahiërogliefen",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitysk cursief",
  "Mero": "Meroïtysk",
  "Mlym": "Malayalam",
  "Modi": "Modi",
  "Mong": "Mongools",
  "Moon": "Moon",
  "Mroo": "Mro",
  "Mtei": "Meitei",
  "Mult": "Multani",
  "Mymr": "Myanmar",
  "NA": "Namibië",
  "NC": "Nij-Caledonië",
  "NE": "Niger",
  "NF": "Norfolkeilân",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Nederlân",
  "NO": "Noarwegen",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Neutrale sône",
  "NU": "Niue",
  "NZ": "Nij-Seelân",
  "Nand": "Nandinagari",
  "Narb": "Ald Noard-Arabysk",
  "Nbat": "Nabateaansk",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Odia",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Trustgebiet fan Pacific Islands",
  "PE": "Peru",
  "PF": "Frans-Polynesië",
  "PG": "Papoea-Nij-Guinea",
  "PH": "Filipijnen",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint-Pierre en Miquelon",
  "PN": "Pitcairneilannen",
  "PR": "Puerto Rico",
  "PS": "Palestynske gebieten",
  "PT": "Portugal",
  "PU": "Amerikaanske ferskate Pasifyske eilannen",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Panamakanalsône",
  "Palm": "Palmyreens",
  "Pauc": "Pau Cin Hau",
  "Perm": "Aldpermysk",
  "Phag": "Phags-pa",
  "Phli": "Inscriptioneel Pahlavi",
  "Phlp": "Psalmen Pahlavi",
  "Phlv": "Boek Pahlavi",
  "Phnx": "Foenicysk",
  "Plrd": "Pollard-fonetysk",
  "Prti": "Inscriptioneel Parthysk",
  "QA": "Qatar",
  "QO": "Oerig Oceanië",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Roemenië",
  "RS": "Servië",
  "RU": "Ruslân",
  "RW": "Rwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Saoedi-Arabië",
  "SB": "Salomonseilannen",
  "SC": "Seychellen",
  "SD": "Soedan",
  "SE": "Zweden",
  "SG": "Singapore",
  "SH": "Sint-Helena",
  "SI": "Slovenië",
  "SJ": "Spitsbergen en Jan Mayen",
  "SK": "Slowakije",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalië",
  "SR": "Suriname",
  "SS": "Sûd-Soedan",
  "ST": "Sao Tomé en Principe",
  "SU": "Uny fan Sovjet Sosjalistyske Republyk",
  "SV": "El Salvador",
  "SX": "Sint-Maarten",
  "SY": "Syrië",
  "SZ": "Swazilân",
  "Samr": "Samaritaansk",
  "Sara": "Sarati",
  "Sarb": "Ald Sûd-Arabysk",
  "Saur": "Saurashtra",
  "Sgnw": "SignWriting",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Sindhi",
  "Sinh": "Sinhala",
  "Sogd": "Sogdian",
  "Sogo": "Alde Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Soendaneesk",
  "Sylo": "Syloti Nagri",
  "Syrc": "Syriac",
  "Syre": "Estrangelo Arameesk",
  "Syrj": "West-Arameesk",
  "Syrn": "East-Arameesk",
  "TA": "Tristan da Cunha",
  "TC": "Turks- en Caicoseilannen",
  "TD": "Tsjaad",
  "TF": "Franse Gebieden in de zuidelijke Indyske Oseaan",
  "TG": "Togo",
  "TH": "Thailân",
  "TJ": "Tadzjikistan",
  "TK": "Tokelau",
  "TL": "East-Timor",
  "TM": "Turkmenistan",
  "TN": "Tunesië",
  "TO": "Tonga",
  "TR": "Turkije",
  "TT": "Trinidad en Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Nij Tai Lue",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Thais",
  "Tibt": "Tibetaansk",
  "Tirh": "Tirhuta",
  "UA": "Oekraïne",
  "UG": "Oeganda",
  "UM": "Lyts ôflizzen eilannen fan de Ferienigde Staten",
  "UN": "Feriene Naasjes",
  "US": "Ferienigde Staten",
  "UY": "Uruguay",
  "UZ": "Oezbekistan",
  "Ugar": "Ugaritysk",
  "VA": "Vaticaanstêd",
  "VC": "Saint Vincent en de Grenadines",
  "VD": "Noard-Fietnam",
  "VE": "Venezuela",
  "VG": "Britse Maagdeneilannen",
  "VI": "Amerikaanske Maagdeneilannen",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Sichtbere spraak",
  "WF": "Wallis en Futuna",
  "WK": "Wake Island",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudo-aksinten",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "Aldperzysk",
  "Xsux": "Sumero-Akkadian Cuneiform",
  "YD": "Folksdemokratyske Republyk Jemen",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "Sûd-Afrika",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Unbekend gebiet",
  "Zanb": "Zanabazar Square",
  "Zinh": "Oergeërfd",
  "Zmth": "Wiskundige notatie",
  "Zsye": "Emoji",
  "Zsym": "Symbolen",
  "Zxxx": "Ongeschreven",
  "Zyyy": "Algemeen",
  "Zzzz": "Onbekend schriftsysteem",
  "aa": "Afar",
  "ab": "Abchazysk",
  "ace": "Atjeesk",
  "ach": "Akoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestysk",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaansk",
  "af_NA": "Afrikaansk (Namibië)",
  "af_ZA": "Afrikaansk (Sûd-Afrika)",
  "afa": "Afro-Aziatyske taal",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadysk",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Algonkwynske taal",
  "aln": "Gheg Albanian",
  "alt": "Sûd-Altaïsk",
  "am": "Amhaarsk",
  "am_ET": "Amhaarsk (Ethiopië)",
  "an": "Aragoneesk",
  "ang": "âldingelsk",
  "anp": "Angika",
  "apa": "Apache Taal",
  "ar": "Arabysk",
  "ar_001": "Modern standert Arabysk",
  "ar_AE": "Arabysk (Verenigde Arabyske Emiraten)",
  "ar_BH": "Arabysk (Bahrein)",
  "ar_DJ": "Arabysk (Djibouti)",
  "ar_DZ": "Arabysk (Algerije)",
  "ar_EG": "Arabysk (Egypte)",
  "ar_EH": "Arabysk (Westelijke Sahara)",
  "ar_ER": "Arabysk (Eritrea)",
  "ar_IL": "Arabysk (Israël)",
  "ar_IQ": "Arabysk (Irak)",
  "ar_JO": "Arabysk (Jordanië)",
  "ar_KM": "Arabysk (Comoren)",
  "ar_KW": "Arabysk (Koeweit)",
  "ar_LB": "Arabysk (Libanon)",
  "ar_LY": "Arabysk (Libië)",
  "ar_MA": "Arabysk (Marokko)",
  "ar_MR": "Arabysk (Mauritanië)",
  "ar_OM": "Arabysk (Oman)",
  "ar_PS": "Arabysk (Palestynske gebieten)",
  "ar_QA": "Arabysk (Qatar)",
  "ar_SA": "Arabysk (Saoedi-Arabië)",
  "ar_SD": "Arabysk (Soedan)",
  "ar_SO": "Arabysk (Somalië)",
  "ar_SS": "Arabysk (Sûd-Soedan)",
  "ar_SY": "Arabysk (Syrië)",
  "ar_TD": "Arabysk (Tsjaad)",
  "ar_TN": "Arabysk (Tunesië)",
  "ar_YE": "Arabysk (Jemen)",
  "arc": "Arameesk",
  "arn": "Araukaansk",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "ars": "Najdi Arabysk",
  "art": "Keunstmjittige taal",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assameesk",
  "as_IN": "Assameesk (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturysk",
  "ath": "Athapaskyske taal",
  "aus": "Australyske taal",
  "av": "Avarysk",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbeidzjaansk",
  "az_AZ": "Azerbeidzjaansk (Azerbeidzjan)",
  "az_Arab": "Azerbeidzjaansk (Arabysk)",
  "az_Cyrl": "Azerbeidzjaansk (Syrillysk)",
  "az_Cyrl_AZ": "Azerbeidzjaansk (Syrillysk, Azerbeidzjan)",
  "az_Latn": "Azerbeidzjaansk (Latyn)",
  "az_Latn_AZ": "Azerbeidzjaansk (Latyn, Azerbeidzjan)",
  "azb": "South Azerbaijani",
  "ba": "Basjkiersk",
  "bad": "Banda",
  "bai": "Bamileke Taal",
  "bal": "Baloetsjysk",
  "ban": "Balineesk",
  "bar": "Bavarian",
  "bas": "Basa",
  "bat": "Baltyske taal",
  "bax": "Bamoun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala’",
  "be": "Wyt-Russysk",
  "be_BY": "Wyt-Russysk (Wit-Ruslân)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaarsk",
  "bg_BG": "Bulgaarsk (Bulgarije)",
  "bgn": "Westlike Balochi",
  "bh": "Bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latyn)",
  "bm_Latn_ML": "Bambara (Latyn, Mali)",
  "bn": "Bengaalsk",
  "bn_BD": "Bengaalsk (Bangladesh)",
  "bn_IN": "Bengaalsk (India)",
  "bnt": "Bantu",
  "bo": "Tibetaansk",
  "bo_CN": "Tibetaansk (Sina)",
  "bo_IN": "Tibetaansk (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Bretonsk",
  "br_FR": "Bretonsk (Frankrijk)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnysk",
  "bs_BA": "Bosnysk (Bosnië en Herzegovina)",
  "bs_Cyrl": "Bosnysk (Syrillysk)",
  "bs_Cyrl_BA": "Bosnysk (Syrillysk, Bosnië en Herzegovina)",
  "bs_Latn": "Bosnysk (Latyn)",
  "bs_Latn_BA": "Bosnysk (Latyn, Bosnië en Herzegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "Bugineesk",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalaansk",
  "ca_AD": "Katalaansk (Andorra)",
  "ca_ES": "Katalaansk (Spanje)",
  "ca_FR": "Katalaansk (Frankrijk)",
  "ca_IT": "Katalaansk (Italië)",
  "cad": "Kaddo",
  "cai": "Sintraal-Amerikaanske Yndiaanske taal",
  "car": "Karibysk",
  "cau": "Kaukasyske taal",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Tsjetsjeensk",
  "ceb": "Cebuano",
  "cel": "Keltyske taal",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukeesk",
  "chm": "Mari",
  "chn": "Chinook-jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Soranî",
  "cmc": "Chamic Language",
  "co": "Korsikaansk",
  "cop": "Koptysk",
  "cpe": "Ingelske kreoal as Pidgin",
  "cpf": "Frânsk-basearre kreoal as Pidgin",
  "cpp": "Portugeesk-basearre Creole as Pidgin",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Krim-Tataarsk",
  "crp": "Kreoalsk as Pidgin",
  "crs": "Seselwa Creole Frânsk",
  "cs": "Tsjechysk",
  "cs_CZ": "Tsjechysk (Tsjechje)",
  "csb": "Kasjoebysk",
  "cu": "Kerkslavysk",
  "cus": "Cushitic Taal",
  "cv": "Tsjoevasjysk",
  "cy": "Welsk",
  "cy_GB": "Welsk (Verenigd Koninkrijk)",
  "da": "Deensk",
  "da_DK": "Deensk (Denemarken)",
  "da_GL": "Deensk (Grienlân)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Dútsk",
  "de_AT": "Dútsk (Eastenryk)",
  "de_BE": "Dútsk (België)",
  "de_CH": "Dútsk (Switserlân)",
  "de_DE": "Dútsk (Dútslân)",
  "de_LI": "Dútsk (Liechtenstein)",
  "de_LU": "Dútsk (Luxemburg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Dravidyske taal",
  "dsb": "Nedersorbysk",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middelnederlânsk",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Aldegyptysk",
  "eka": "Ekajuk",
  "el": "Gryks",
  "el_CY": "Gryks (Syprus)",
  "el_GR": "Gryks (Grikelân)",
  "elx": "Elamitysk",
  "en": "Ingelsk",
  "en_AG": "Ingelsk (Antigua en Barbuda)",
  "en_AI": "Ingelsk (Anguilla)",
  "en_AS": "Ingelsk (Amerikaansk Samoa)",
  "en_AU": "Ingelsk (Australië)",
  "en_BB": "Ingelsk (Barbados)",
  "en_BE": "Ingelsk (België)",
  "en_BM": "Ingelsk (Bermuda)",
  "en_BS": "Ingelsk (Bahama’s)",
  "en_BW": "Ingelsk (Botswana)",
  "en_BZ": "Ingelsk (Belize)",
  "en_CA": "Ingelsk (Canada)",
  "en_CC": "Ingelsk (Kokosilanen)",
  "en_CK": "Ingelsk (Cookeilannen)",
  "en_CM": "Ingelsk (Kameroen)",
  "en_CX": "Ingelsk (Krysteilan)",
  "en_DG": "Ingelsk (Diego Garcia)",
  "en_DM": "Ingelsk (Dominika)",
  "en_Dsrt": "Ingelsk (Deseret)",
  "en_ER": "Ingelsk (Eritrea)",
  "en_FJ": "Ingelsk (Fiji)",
  "en_FK": "Ingelsk (Falklâneilannen)",
  "en_FM": "Ingelsk (Micronesië)",
  "en_GB": "Ingelsk (Verenigd Koninkrijk)",
  "en_GD": "Ingelsk (Grenada)",
  "en_GG": "Ingelsk (Guernsey)",
  "en_GH": "Ingelsk (Ghana)",
  "en_GI": "Ingelsk (Gibraltar)",
  "en_GM": "Ingelsk (Gambia)",
  "en_GU": "Ingelsk (Guam)",
  "en_GY": "Ingelsk (Guyana)",
  "en_HK": "Ingelsk (Hongkong SAR van Sina)",
  "en_IE": "Ingelsk (Ierlân)",
  "en_IM": "Ingelsk (Isle of Man)",
  "en_IN": "Ingelsk (India)",
  "en_IO": "Ingelsk (Britse Gebieden yn de Indyske Oseaan)",
  "en_JE": "Ingelsk (Jersey)",
  "en_JM": "Ingelsk (Jamaica)",
  "en_KE": "Ingelsk (Kenia)",
  "en_KI": "Ingelsk (Kiribati)",
  "en_KN": "Ingelsk (Saint Kitts en Nevis)",
  "en_KY": "Ingelsk (Caymaneilannen)",
  "en_LC": "Ingelsk (Saint Lucia)",
  "en_LR": "Ingelsk (Liberia)",
  "en_LS": "Ingelsk (Lesotho)",
  "en_MG": "Ingelsk (Madeiaskar)",
  "en_MH": "Ingelsk (Marshalleilannen)",
  "en_MO": "Ingelsk (Macao SAR van Sina)",
  "en_MP": "Ingelsk (Noardlike Marianeneilannen)",
  "en_MS": "Ingelsk (Montserrat)",
  "en_MT": "Ingelsk (Malta)",
  "en_MU": "Ingelsk (Mauritius)",
  "en_MW": "Ingelsk (Malawi)",
  "en_MY": "Ingelsk (Maleisië)",
  "en_NA": "Ingelsk (Namibië)",
  "en_NF": "Ingelsk (Norfolkeilân)",
  "en_NG": "Ingelsk (Nigeria)",
  "en_NR": "Ingelsk (Nauru)",
  "en_NU": "Ingelsk (Niue)",
  "en_NZ": "Ingelsk (Nij-Seelân)",
  "en_PG": "Ingelsk (Papoea-Nij-Guinea)",
  "en_PH": "Ingelsk (Filipijnen)",
  "en_PK": "Ingelsk (Pakistan)",
  "en_PN": "Ingelsk (Pitcairneilannen)",
  "en_PR": "Ingelsk (Puerto Rico)",
  "en_PW": "Ingelsk (Palau)",
  "en_RW": "Ingelsk (Rwanda)",
  "en_SB": "Ingelsk (Salomonseilannen)",
  "en_SC": "Ingelsk (Seychellen)",
  "en_SD": "Ingelsk (Soedan)",
  "en_SG": "Ingelsk (Singapore)",
  "en_SH": "Ingelsk (Sint-Helena)",
  "en_SL": "Ingelsk (Sierra Leone)",
  "en_SS": "Ingelsk (Sûd-Soedan)",
  "en_SX": "Ingelsk (Sint-Maarten)",
  "en_SZ": "Ingelsk (Swazilân)",
  "en_TC": "Ingelsk (Turks- en Caicoseilannen)",
  "en_TK": "Ingelsk (Tokelau)",
  "en_TO": "Ingelsk (Tonga)",
  "en_TT": "Ingelsk (Trinidad en Tobago)",
  "en_TV": "Ingelsk (Tuvalu)",
  "en_TZ": "Ingelsk (Tanzania)",
  "en_UG": "Ingelsk (Oeganda)",
  "en_UM": "Ingelsk (Lyts ôflizzen eilannen fan de Ferienigde Staten)",
  "en_US": "Ingelsk (Ferienigde Staten)",
  "en_VC": "Ingelsk (Saint Vincent en de Grenadines)",
  "en_VG": "Ingelsk (Britse Maagdeneilannen)",
  "en_VI": "Ingelsk (Amerikaanske Maagdeneilannen)",
  "en_VU": "Ingelsk (Vanuatu)",
  "en_WS": "Ingelsk (Samoa)",
  "en_ZA": "Ingelsk (Sûd-Afrika)",
  "en_ZM": "Ingelsk (Zambia)",
  "en_ZW": "Ingelsk (Zimbabwe)",
  "enm": "Middelingelsk",
  "eo": "Esperanto",
  "es": "Spaansk",
  "es_419": "Latynsk-Amerikaansk Spaansk",
  "es_AR": "Spaansk (Argentinië)",
  "es_BO": "Spaansk (Bolivia)",
  "es_CL": "Spaansk (Chili)",
  "es_CO": "Spaansk (Kolombia)",
  "es_CR": "Spaansk (Costa Rica)",
  "es_CU": "Spaansk (Kuba)",
  "es_DO": "Spaansk (Dominikaanske Republyk)",
  "es_EA": "Spaansk (Ceuta en Melilla)",
  "es_EC": "Spaansk (Ecuador)",
  "es_ES": "Spaansk (Spanje)",
  "es_GQ": "Spaansk (Equatoriaal-Guinea)",
  "es_GT": "Spaansk (Guatemala)",
  "es_HN": "Spaansk (Honduras)",
  "es_IC": "Spaansk (Kanaryske Eilânnen)",
  "es_MX": "Spaansk (Mexico)",
  "es_NI": "Spaansk (Nicaragua)",
  "es_PA": "Spaansk (Panama)",
  "es_PE": "Spaansk (Peru)",
  "es_PH": "Spaansk (Filipijnen)",
  "es_PR": "Spaansk (Puerto Rico)",
  "es_PY": "Spaansk (Paraguay)",
  "es_SV": "Spaansk (El Salvador)",
  "es_US": "Spaansk (Ferienigde Staten)",
  "es_UY": "Spaansk (Uruguay)",
  "es_VE": "Spaansk (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estlânsk",
  "et_EE": "Estlânsk (Estlân)",
  "eu": "Baskysk",
  "eu_ES": "Baskysk (Spanje)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Perzysk",
  "fa_AF": "Perzysk (Afghanistan)",
  "fa_IR": "Perzysk (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Kameroen)",
  "ff_GN": "Fulah (Guinee)",
  "ff_MR": "Fulah (Mauritanië)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finsk",
  "fi_FI": "Finsk (Finlân)",
  "fil": "Filipynsk",
  "fit": "Tornedalen Finnish",
  "fiu": "Fino-Ugryske taal",
  "fj": "Fijysk",
  "fo": "Faeröersk",
  "fo_FO": "Faeröersk (Faeröer)",
  "fon": "Fon",
  "fr": "Frânsk",
  "fr_BE": "Frânsk (België)",
  "fr_BF": "Frânsk (Burkina Faso)",
  "fr_BI": "Frânsk (Burundi)",
  "fr_BJ": "Frânsk (Benin)",
  "fr_BL": "Frânsk (Saint Barthélemy)",
  "fr_CA": "Frânsk (Canada)",
  "fr_CD": "Frânsk (Congo-Kinshasa)",
  "fr_CF": "Frânsk (Sintraal-Afrikaanske Republyk)",
  "fr_CG": "Frânsk (Congo-Brazzaville)",
  "fr_CH": "Frânsk (Switserlân)",
  "fr_CI": "Frânsk (Ivoorkust)",
  "fr_CM": "Frânsk (Kameroen)",
  "fr_DJ": "Frânsk (Djibouti)",
  "fr_DZ": "Frânsk (Algerije)",
  "fr_FR": "Frânsk (Frankrijk)",
  "fr_GA": "Frânsk (Gabon)",
  "fr_GF": "Frânsk (Frans-Guyana)",
  "fr_GN": "Frânsk (Guinee)",
  "fr_GP": "Frânsk (Guadeloupe)",
  "fr_GQ": "Frânsk (Equatoriaal-Guinea)",
  "fr_HT": "Frânsk (Haïti)",
  "fr_KM": "Frânsk (Comoren)",
  "fr_LU": "Frânsk (Luxemburg)",
  "fr_MA": "Frânsk (Marokko)",
  "fr_MC": "Frânsk (Monaco)",
  "fr_MF": "Frânsk (Saint-Martin)",
  "fr_MG": "Frânsk (Madeiaskar)",
  "fr_ML": "Frânsk (Mali)",
  "fr_MQ": "Frânsk (Martinique)",
  "fr_MR": "Frânsk (Mauritanië)",
  "fr_MU": "Frânsk (Mauritius)",
  "fr_NC": "Frânsk (Nij-Caledonië)",
  "fr_NE": "Frânsk (Niger)",
  "fr_PF": "Frânsk (Frans-Polynesië)",
  "fr_PM": "Frânsk (Saint-Pierre en Miquelon)",
  "fr_RE": "Frânsk (Réunion)",
  "fr_RW": "Frânsk (Rwanda)",
  "fr_SC": "Frânsk (Seychellen)",
  "fr_SN": "Frânsk (Senegal)",
  "fr_SY": "Frânsk (Syrië)",
  "fr_TD": "Frânsk (Tsjaad)",
  "fr_TG": "Frânsk (Togo)",
  "fr_TN": "Frânsk (Tunesië)",
  "fr_VU": "Frânsk (Vanuatu)",
  "fr_WF": "Frânsk (Wallis en Futuna)",
  "fr_YT": "Frânsk (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middelfrânsk",
  "fro": "Aldfrânsk",
  "frp": "Arpitan",
  "frr": "Noard-Frysk",
  "frs": "East-Frysk",
  "fur": "Friulysk",
  "fy": "West-Frysk",
  "fy_NL": "West-Frysk (Nederlân)",
  "ga": "Iersk",
  "ga_IE": "Iersk (Ierlân)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Schotsk Gaelic",
  "gd_GB": "Schotsk Gaelic (Verenigd Koninkrijk)",
  "gem": "Germaanske taal",
  "gez": "Geez",
  "gil": "Gilberteesk",
  "gl": "Galisysk",
  "gl_ES": "Galisysk (Spanje)",
  "glk": "Gilaki",
  "gmh": "Middelheechdútsk",
  "gn": "Guaraní",
  "goh": "Alsheechdútsk",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothysk",
  "grb": "Grebo",
  "grc": "Aldgryks",
  "gsw": "Switsers Dútsk",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manks",
  "gv_IM": "Manks (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latyn)",
  "ha_Latn_GH": "Hausa (Latyn, Ghana)",
  "ha_Latn_NE": "Hausa (Latyn, Niger)",
  "ha_Latn_NG": "Hausa (Latyn, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaïaansk",
  "he": "Hebreeuwsk",
  "he_IL": "Hebreeuwsk (Israël)",
  "hi": "Hindi",
  "hi_IN": "Hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hettitysk",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Kroatysk",
  "hr_BA": "Kroatysk (Bosnië en Herzegovina)",
  "hr_HR": "Kroatysk (Kroatië)",
  "hsb": "Oppersorbysk",
  "hsn": "Xiang Chinese",
  "ht": "Haïtiaansk",
  "hu": "Hongaarsk",
  "hu_HU": "Hongaarsk (Hongarije)",
  "hup": "Hupa",
  "hy": "Armeensk",
  "hy_AM": "Armeensk (Armenië)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Yndonezysk",
  "id_ID": "Yndonezysk (Yndonesië)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (Sina)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Oantsjutte taal",
  "ine": "Yndo-Jeropeeske taal",
  "inh": "Ingoesj",
  "io": "Ido",
  "ira": "Iraanske taal",
  "iro": "Iroquoian Taal",
  "is": "Yslâns",
  "is_IS": "Yslâns (Yslân)",
  "it": "Italiaansk",
  "it_CH": "Italiaansk (Switserlân)",
  "it_IT": "Italiaansk (Italië)",
  "it_SM": "Italiaansk (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Japans",
  "ja_JP": "Japans (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Perzysk",
  "jrb": "Judeo-Arabysk",
  "jut": "Jutish",
  "jv": "Javaansk",
  "ka": "Georgysk",
  "ka_GE": "Georgysk (Georgië)",
  "kaa": "Karakalpaks",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardysk",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kaapverdysk Creools",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Khoisan Taal",
  "kho": "Khotaneesk",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenia)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazachs",
  "kk_Cyrl": "Kazachs (Syrillysk)",
  "kk_Cyrl_KZ": "Kazachs (Syrillysk, Kazachstan)",
  "kk_KZ": "Kazachs (Kazachstan)",
  "kkj": "Kako",
  "kl": "Grienlâns",
  "kl_GL": "Grienlâns (Grienlân)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodja)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Koreaansk",
  "ko_KP": "Koreaansk (Noard-Korea)",
  "ko_KR": "Koreaansk (Sûd-Korea)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraeaansk",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelysk",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kasjmiri",
  "ks_Arab": "Kasjmiri (Arabysk)",
  "ks_Arab_IN": "Kasjmiri (Arabysk, India)",
  "ks_IN": "Kasjmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Kölsch",
  "ku": "Koerdysk",
  "kum": "Koemuks",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (Verenigd Koninkrijk)",
  "ky": "Kirgizysk",
  "ky_Cyrl": "Kirgizysk (Syrillysk)",
  "ky_Cyrl_KG": "Kirgizysk (Syrillysk, Kirgizië)",
  "ky_KG": "Kirgizysk (Kirgizië)",
  "la": "Latyn",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxemburgs",
  "lb_LU": "Luxemburgs (Luxemburg)",
  "lez": "Lezgysk",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Oeganda)",
  "li": "Limburgs",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo-Kinshasa)",
  "ln_CF": "Lingala (Sintraal-Afrikaanske Republyk)",
  "ln_CG": "Lingala (Congo-Brazzaville)",
  "lo": "Laotiaansk",
  "lo_LA": "Laotiaansk (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Noardlike Luri",
  "lt": "Litouws",
  "lt_LT": "Litouws (Litouwen)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo-Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Lushai",
  "luy": "Luyia",
  "lv": "Letlâns",
  "lv_LV": "Letlâns (Letlân)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurees",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makassaars",
  "man": "Mandingo",
  "map": "Austronesyske taal",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasysk",
  "mg_MG": "Malagasysk (Madeiaskar)",
  "mga": "Middeliers",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta’",
  "mh": "Marshallees",
  "mi": "Maori",
  "mic": "Mi’kmaq",
  "min": "Minangkabau",
  "mis": "Ferskate taal",
  "mk": "Macedonysk",
  "mk_MK": "Macedonysk (Macedonië)",
  "mkh": "Mon-Khmer Taal",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongools",
  "mn_Cyrl": "Mongools (Syrillysk)",
  "mn_Cyrl_MN": "Mongools (Syrillysk, Mongolië)",
  "mn_MN": "Mongools (Mongolië)",
  "mnc": "Mantsjoe",
  "mni": "Manipoeri",
  "mno": "Manobo Taal",
  "mo": "Moldavysk",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Maleis",
  "ms_BN": "Maleis (Brunei)",
  "ms_Latn": "Maleis (Latyn)",
  "ms_Latn_BN": "Maleis (Latyn, Brunei)",
  "ms_Latn_MY": "Maleis (Latyn, Maleisië)",
  "ms_Latn_SG": "Maleis (Latyn, Singapore)",
  "ms_MY": "Maleis (Maleisië)",
  "ms_SG": "Maleis (Singapore)",
  "mt": "Maltees",
  "mt_MT": "Maltees (Malta)",
  "mua": "Mundang",
  "mul": "Meardere talen",
  "mun": "Munda Taal",
  "mus": "Creek",
  "mwl": "Mirandees",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Birmees",
  "my_MM": "Birmees (Myanmar (Birma))",
  "mye": "Myene",
  "myn": "Mayaanske taal",
  "myv": "Erzja",
  "mzn": "Mazanderani",
  "na": "Nauruaansk",
  "nah": "Nahuatl",
  "nai": "Noard-Amerikaanske Yndiaanske taal",
  "nan": "Min Nan Chinese",
  "nap": "Napolitaansk",
  "naq": "Nama",
  "nb": "Noors - Bokmål",
  "nb_NO": "Noors - Bokmål (Noarwegen)",
  "nb_SJ": "Noors - Bokmål (Spitsbergen en Jan Mayen)",
  "nd": "Noard-Ndbele",
  "nd_ZW": "Noard-Ndbele (Zimbabwe)",
  "nds": "Laagduits",
  "nds_NL": "Nederlânsk Nedersaksysk",
  "ne": "Nepalees",
  "ne_IN": "Nepalees (India)",
  "ne_NP": "Nepalees (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Niger-Kordofanian taal",
  "niu": "Niueaansk",
  "njo": "Ao Naga",
  "nl": "Nederlânsk",
  "nl_AW": "Nederlânsk (Aruba)",
  "nl_BE": "Nederlânsk (België)",
  "nl_BQ": "Nederlânsk (Karibysk Nederlân)",
  "nl_CW": "Nederlânsk (Curaçao)",
  "nl_NL": "Nederlânsk (Nederlân)",
  "nl_SR": "Nederlânsk (Suriname)",
  "nl_SX": "Nederlânsk (Sint-Maarten)",
  "nmg": "Ngumba",
  "nn": "Noors - Nynorsk",
  "nn_NO": "Noors - Nynorsk (Noarwegen)",
  "nnh": "Ngiemboon",
  "no": "Noors",
  "no_NO": "Noors (Noarwegen)",
  "nog": "Nogai",
  "non": "Aldnoarsk",
  "nov": "Novial",
  "nqo": "N’ko",
  "nr": "Sûd-Ndbele",
  "nso": "Noard-Sotho",
  "nub": "Nubyske taal",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Klassiek Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitaansk",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopië)",
  "om_KE": "Oromo (Kenia)",
  "or": "Odia",
  "or_IN": "Odia (India)",
  "os": "Ossetysk",
  "os_GE": "Ossetysk (Georgië)",
  "os_RU": "Ossetysk (Ruslân)",
  "osa": "Osage",
  "ota": "Ottomaansk-Turks",
  "oto": "Otomyske taal",
  "pa": "Punjabi",
  "pa_Arab": "Punjabi (Arabysk)",
  "pa_Arab_PK": "Punjabi (Arabysk, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "paa": "Papoeaanske taal",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiaments",
  "pau": "Palauaansk",
  "pcd": "Picard",
  "pcm": "Nigeriaanske Pidgin",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Aldperzysk",
  "pfl": "Palatine German",
  "phi": "Filipynske taal",
  "phn": "Foenisysk",
  "pi": "Pali",
  "pl": "Poalsk",
  "pl_PL": "Poalsk (Polen)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeiaansk",
  "pra": "Prakrit Taal",
  "prg": "Prussian",
  "pro": "Aldprovençaals",
  "ps": "Pasjtoe",
  "ps_AF": "Pasjtoe (Afghanistan)",
  "pt": "Portugeesk",
  "pt_AO": "Portugeesk (Angola)",
  "pt_BR": "Portugeesk (Brazilië)",
  "pt_CV": "Portugeesk (Kaapverdië)",
  "pt_GW": "Portugeesk (Guinee-Bissau)",
  "pt_MO": "Portugeesk (Macao SAR van Sina)",
  "pt_MZ": "Portugeesk (Mozambique)",
  "pt_PT": "Portugeesk (Portugal)",
  "pt_ST": "Portugeesk (Sao Tomé en Principe)",
  "pt_TL": "Portugeesk (East-Timor)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Reto-Romaansk",
  "rm_CH": "Reto-Romaansk (Switserlân)",
  "rn": "Kirundi",
  "rn_BI": "Kirundi (Burundi)",
  "ro": "Roemeensk",
  "ro_MD": "Roemeensk (Moldavië)",
  "ro_RO": "Roemeensk (Roemenië)",
  "roa": "Romaanske taal",
  "rof": "Rombo",
  "rom": "Romani",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Russysk",
  "ru_BY": "Russysk (Wit-Ruslân)",
  "ru_KG": "Russysk (Kirgizië)",
  "ru_KZ": "Russysk (Kazachstan)",
  "ru_MD": "Russysk (Moldavië)",
  "ru_RU": "Russysk (Ruslân)",
  "ru_UA": "Russysk (Oekraïne)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromaniaansk",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskriet",
  "sad": "Sandawe",
  "sah": "Jakoets",
  "sai": "Súd-Amerikaanske Yndiaanske taal",
  "sal": "Salishan Taal",
  "sam": "Samaritaansk-Arameesk",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinysk",
  "scn": "Siciliaansk",
  "sco": "Schots",
  "sd": "Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "Súdlik Koerdysk",
  "se": "Noard-Samysk",
  "se_FI": "Noard-Samysk (Finlân)",
  "se_NO": "Noard-Samysk (Noarwegen)",
  "se_SE": "Noard-Samysk (Zweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Semityske taal",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Sintraal-Afrikaanske Republyk)",
  "sga": "Aldyrsk",
  "sgn": "Gebeartetaal",
  "sgs": "Samogitian",
  "sh": "Servokroatysk",
  "sh_BA": "Servokroatysk (Bosnië en Herzegovina)",
  "shi": "Tashelhiyt",
  "shi_Latn": "Shilha (Latyn)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Tsjadysk Arabysk",
  "si": "Singalees",
  "si_LK": "Singalees (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Siouan Taal",
  "sit": "Sino-Tibetaanske taal",
  "sk": "Slowaaks",
  "sk_SK": "Slowaaks (Slowakije)",
  "sl": "Sloveensk",
  "sl_SI": "Sloveensk (Slovenië)",
  "sla": "Slavyske taal",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoaansk",
  "sma": "Sûd-Samysk",
  "smi": "Sami Taal",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somalysk",
  "so_DJ": "Somalysk (Djibouti)",
  "so_ET": "Somalysk (Ethiopië)",
  "so_KE": "Somalysk (Kenia)",
  "so_SO": "Somalysk (Somalië)",
  "sog": "Sogdysk",
  "son": "Songhai",
  "sq": "Albaneesk",
  "sq_AL": "Albaneesk (Albanië)",
  "sq_MK": "Albaneesk (Macedonië)",
  "sq_XK": "Albaneesk (Kosovo)",
  "sr": "Servysk",
  "sr_BA": "Servysk (Bosnië en Herzegovina)",
  "sr_Cyrl": "Servysk (Syrillysk)",
  "sr_Cyrl_BA": "Servysk (Syrillysk, Bosnië en Herzegovina)",
  "sr_Cyrl_ME": "Servysk (Syrillysk, Montenegro)",
  "sr_Cyrl_RS": "Servysk (Syrillysk, Servië)",
  "sr_Cyrl_XK": "Servysk (Syrillysk, Kosovo)",
  "sr_Latn": "Servysk (Latyn)",
  "sr_Latn_BA": "Servysk (Latyn, Bosnië en Herzegovina)",
  "sr_Latn_ME": "Servysk (Latyn, Montenegro)",
  "sr_Latn_RS": "Servysk (Latyn, Servië)",
  "sr_Latn_XK": "Servysk (Latyn, Kosovo)",
  "sr_ME": "Servysk (Montenegro)",
  "sr_RS": "Servysk (Servië)",
  "sr_XK": "Servysk (Kosovo)",
  "srn": "Sranantongo",
  "srr": "Serer",
  "ss": "Swazi",
  "ssa": "Nilo-Saharaanske taal",
  "ssy": "Saho",
  "st": "Sûd-Sotho",
  "stq": "Saterland Frisian",
  "su": "Soendaneesk",
  "suk": "Sukuma",
  "sus": "Soesoe",
  "sux": "Soemerysk",
  "sv": "Zweeds",
  "sv_AX": "Zweeds (Ålân)",
  "sv_FI": "Zweeds (Finlân)",
  "sv_SE": "Zweeds (Zweden)",
  "sw": "Swahili",
  "sw_CD": "Congo Swahili",
  "sw_KE": "Swahili (Kenia)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Oeganda)",
  "swb": "Shimaore",
  "swc": "Congo Swahili",
  "syc": "Klassiek Syrysk",
  "syr": "Syrysk",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Maleisië)",
  "ta_SG": "Tamil (Singapore)",
  "tai": "Tai Taal",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetun",
  "tg": "Tadzjieks",
  "th": "Thais",
  "th_TH": "Thais (Thailân)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopië)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmeens",
  "tkl": "Tokelaus",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Filipijnen)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongaansk",
  "to_TO": "Tongaansk (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Turks",
  "tr_CY": "Turks (Syprus)",
  "tr_TR": "Turks (Turkije)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tataars",
  "ttt": "Muslim Tat",
  "tum": "Toemboeka",
  "tup": "Tupi Taal",
  "tut": "Altaïske taal",
  "tvl": "Tuvaluaansk",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitysk",
  "tyv": "Tuvinysk",
  "tzm": "Tamazight (Sintraal-Marokko)",
  "udm": "Oedmoerts",
  "ug": "Oeigoers",
  "ug_Arab": "Oeigoers (Arabysk)",
  "ug_Arab_CN": "Oeigoers (Arabysk, Sina)",
  "ug_CN": "Oeigoers (Sina)",
  "uga": "Oegaritysk",
  "uk": "Oekraïens",
  "uk_UA": "Oekraïens (Oekraïne)",
  "umb": "Umbundu",
  "und": "Onbekende taal",
  "ur": "Urdu",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Oezbeeks",
  "uz_AF": "Oezbeeks (Afghanistan)",
  "uz_Arab": "Oezbeeks (Arabysk)",
  "uz_Arab_AF": "Oezbeeks (Arabysk, Afghanistan)",
  "uz_Cyrl": "Oezbeeks (Syrillysk)",
  "uz_Cyrl_UZ": "Oezbeeks (Syrillysk, Oezbekistan)",
  "uz_Latn": "Oezbeeks (Latyn)",
  "uz_Latn_UZ": "Oezbeeks (Latyn, Oezbekistan)",
  "uz_UZ": "Oezbeeks (Oezbekistan)",
  "vai": "Vai",
  "vai_Latn": "Vai (Latyn)",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Vietnamees",
  "vi_VN": "Vietnamees (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votysk",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Waals",
  "wae": "Walser",
  "wak": "Wakashan Taal",
  "wal": "Walamo",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Sorbyske taal",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapees",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Jiddysk",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "ypk": "Yupik Taal",
  "yrl": "Nheengatu",
  "yue": "Kantoneesk",
  "yue_Hans": "Kantoneesk (ferienfâldige Sineesk)",
  "yue_Hant": "Kantoneesk (Tradisjoneel Sineesk)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbolen",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standert Marokkaanske Tamazight",
  "zh": "Sineesk",
  "zh_CN": "Sineesk (Sina)",
  "zh_HK": "Sineesk (Hongkong SAR van Sina)",
  "zh_Hans": "Sineesk (Ferienfâldigd)",
  "zh_Hans_CN": "Sineesk (Ferienfâldigd, Sina)",
  "zh_Hans_HK": "Sineesk (Ferienfâldigd, Hongkong SAR van Sina)",
  "zh_Hans_MO": "Sineesk (Ferienfâldigd, Macao SAR van Sina)",
  "zh_Hans_SG": "Sineesk (Ferienfâldigd, Singapore)",
  "zh_Hant": "Sineesk (Traditjoneel)",
  "zh_Hant_HK": "Sineesk (Traditjoneel, Hongkong SAR van Sina)",
  "zh_Hant_MO": "Sineesk (Traditjoneel, Macao SAR van Sina)",
  "zh_Hant_TW": "Sineesk (Traditjoneel, Taiwan)",
  "zh_MO": "Sineesk (Macao SAR van Sina)",
  "zh_SG": "Sineesk (Singapore)",
  "zh_TW": "Sineesk (Taiwan)",
  "znd": "Zande",
  "zu": "Zulu",
  "zu_ZA": "Zulu (Sûd-Afrika)",
  "zun": "Zuni",
  "zxx": "Gjin linguïstyske ynhâld",
  "zza": "Zaza"
};
