const names = {
  "001": "Wọld",
  "002": "Áfríka",
  "003": "Nọ́t Amẹ́ríka",
  "005": "Saút Amẹ́ríka",
  "009": "Oshẹnia",
  "011": "Wẹ́stán Áfríka",
  "013": "Mídúl Amẹ́ríka",
  "014": "Ístán Áfríká",
  "015": "Nọ́tán Áfríka",
  "017": "Mídúl Áfríka",
  "018": "Saútán Áfríka",
  "019": "Amẹ́ríkas",
  "021": "Nọ́tán Amẹ́ríka",
  "029": "Karíbián",
  "030": "Ístán Éshia",
  "034": "Saútán Éshia",
  "035": "Saútíst Éshiá",
  "039": "Saútán Yúrop",
  "053": "Ọstraléshia",
  "054": "Mẹlanẹíshia",
  "057": "Maikroníshia Ríjọn",
  "061": "Poliníshiá",
  "142": "Éshia",
  "143": "Mídúl Éshia",
  "145": "Wẹ́stán Éshia",
  "150": "Yúrop",
  "151": "Ístán Yúrop",
  "154": "Nọ́tán Yúrop",
  "155": "Wẹ́stán Yúrop",
  "202": "Áfríka Éria Biló Sahára",
  "419": "Látín Amẹ́ríka",
  "AC": "Asẹ́nshọ́n Aíland",
  "AD": "Andọ́ra",
  "AE": "Yunaítẹ́d Áráb Ẹ́mírets",
  "AF": "Afgánístan",
  "AG": "Antígwua & Barbúda",
  "AI": "Angwíla",
  "AL": "Albénia",
  "AM": "Armẹ́niá",
  "AO": "Angóla",
  "AQ": "Antáktíka",
  "AR": "Ajẹntína",
  "AS": "Amẹ́ríká Samoa",
  "AT": "Ọ́stria",
  "AU": "Ọstrélia",
  "AW": "Arúba",
  "AX": "Ọ́lánd Aílands",
  "AZ": "Azẹrbaijan",
  "Arab": "Arábík",
  "Armn": "Armẹ́nia",
  "BA": "Bọ́zniá & Hẹzẹgovína",
  "BB": "Barbédọs",
  "BD": "Bangladẹsh",
  "BE": "Bẹ́ljọm",
  "BF": "Burkína Fáso",
  "BG": "Bọlgéria",
  "BH": "Barein",
  "BI": "Burúndi",
  "BJ": "Binin",
  "BL": "Sént Batẹlẹ́mi",
  "BM": "Bẹmiúda",
  "BN": "Brunẹi",
  "BO": "Bolívia",
  "BQ": "Karíbián Nẹ́dalands",
  "BR": "Brázil",
  "BS": "Bahámas",
  "BT": "Butan",
  "BV": "Buvẹ́ Aíland",
  "BW": "Botswána",
  "BY": "Bẹ́larus",
  "BZ": "Bẹliz",
  "Beng": "Bángla",
  "Bopo": "Bopomófo",
  "Brai": "Blaínd Pípol Raítín Sístẹm",
  "CA": "Kánáda",
  "CC": "Kókós Aílands",
  "CD": "Kóngó – Kinshása",
  "CF": "Sẹ́ntrál Áfríkán Ripọ́blik",
  "CG": "Kóngo – Brázavil",
  "CH": "Swítsaland",
  "CI": "Aívri Kost",
  "CK": "Kúk Aílands",
  "CL": "Chílẹ",
  "CM": "Kamẹrun",
  "CN": "Chaína",
  "CO": "Kolómbia",
  "CP": "Klipatọ́n Aíland",
  "CR": "Kósta Ríka",
  "CU": "Kiúbá",
  "CV": "Kép Vẹ́d",
  "CW": "Kiurásao",
  "CX": "Krísmás Aíland",
  "CY": "Saíprọs",
  "CZ": "Chẹ́kia",
  "Cyrl": "Sírílik",
  "DE": "Jámáni",
  "DG": "Diẹ́gó Garsia",
  "DJ": "Jibúti",
  "DK": "Dẹ́nmak",
  "DM": "Dọmíníka",
  "DO": "Dọmíníka Ripọ́blik",
  "DZ": "Aljíria",
  "Deva": "Dẹvanágári",
  "EA": "Sẹúta & Mẹ́líla",
  "EC": "Ẹ́kwuádọ",
  "EE": "Ẹstónia",
  "EG": "Íjipt",
  "EH": "Wẹ́stán Sahára",
  "ER": "Ẹritrẹ́a",
  "ES": "Spen",
  "ET": "Ẹtiópia",
  "EU": "Yurópián Yúniọ́n",
  "EZ": "Yúróéria",
  "Ethi": "Ẹtiópik",
  "FI": "Fínland",
  "FJ": "Fíji",
  "FK": "Fọ́klánd Aílands",
  "FM": "Maikroníshia",
  "FO": "Fáro Aílands",
  "FR": "Frans",
  "GA": "Gabọn",
  "GB": "Yunáítẹ́d Kíndọm",
  "GD": "Grẹnéda",
  "GE": "Jọ́jia",
  "GF": "Frẹ́nch Giána",
  "GG": "Guẹnzi",
  "GH": "Gána",
  "GI": "Jibrọ́lta",
  "GL": "Grínland",
  "GM": "Gámbia",
  "GN": "Gíni",
  "GP": "Guadalúpẹ",
  "GQ": "Ikwétóriál Gíni",
  "GR": "Gris",
  "GS": "Saút Jọ́jia an Saút Sándwích Aílands",
  "GT": "Guátẹmála",
  "GU": "Guam",
  "GW": "Gíní-Bisáu",
  "GY": "Gayána",
  "Geor": "Jọ́jia",
  "Grek": "Grík",
  "Gujr": "Gujaráti",
  "Guru": "Gúrmukhi",
  "HK": "Họng Kọng SAR",
  "HM": "Hiád & MakDónáld Aílands",
  "HN": "Họndúras",
  "HR": "Kroéshia",
  "HT": "Haíti",
  "HU": "Họ́ngári",
  "Hanb": "Han Wit Bopomófo",
  "Hang": "Hángul",
  "Hani": "Chainiz",
  "Hans": "Ízí Chainíz Lángwej",
  "Hant": "Nọ́mal",
  "Hebr": "Híbrú",
  "Hira": "Hiagána",
  "Hrkt": "Pát ọf Japán Raítín Sístẹm",
  "IC": "Kenerí Aílands",
  "ID": "Indoníshia",
  "IE": "Ayaland",
  "IL": "Ízrẹl",
  "IM": "Aíl ọf Man",
  "IN": "Índia",
  "IO": "Brítísh Índián Óshen Tẹ́rẹ́tri",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Aísland",
  "IT": "Ítáli",
  "JE": "Jẹ́si",
  "JM": "Jamaíka",
  "JO": "Jọ́dan",
  "JP": "Japan",
  "Jamo": "Jámo",
  "Jpan": "Japan",
  "KE": "Kẹ́nya",
  "KG": "Kẹjístan",
  "KH": "Kambódia",
  "KI": "Kiribáti",
  "KM": "Kọ́mọ́ros",
  "KN": "Sent Kits & Nẹ́vis",
  "KP": "Nọ́t Koria",
  "KR": "Saút Koria",
  "KW": "Kuwét",
  "KY": "Kéman Aílands",
  "KZ": "Kazakstan",
  "Kana": "Katákána",
  "Khmr": "Kemẹẹ",
  "Knda": "Kánnad Raítín Sístẹm",
  "Kore": "Koria",
  "LA": "Laos",
  "LB": "Lẹ́bánọn",
  "LC": "Sent Lúshia",
  "LI": "Líktẹ́nstain",
  "LK": "Sri Lánka",
  "LR": "Laibẹ́ria",
  "LS": "Lẹsóto",
  "LT": "Lituénia",
  "LU": "Lọ́ksẹ́mbọg",
  "LV": "Látvia",
  "LY": "Líbia",
  "Laoo": "Lao",
  "Latn": "Látin",
  "MA": "Morọko",
  "MC": "Mọ́náko",
  "MD": "Mọldóva",
  "ME": "Mọntinígro",
  "MF": "Sent Mátin",
  "MG": "Madagáska",
  "MH": "Máshál Aílands",
  "MK": "Nọ́t Masidónia",
  "ML": "Máli",
  "MM": "Miánma (Bọ́ma)",
  "MN": "Mọngólia",
  "MO": "Makáo SAR Chaína",
  "MP": "Nọ́tán Mariána Aílands",
  "MQ": "Matínik",
  "MR": "Mọriténia",
  "MS": "Mọntsẹrat",
  "MT": "Mọ́lta",
  "MU": "Mọríshọs",
  "MV": "Mọ́ldivs",
  "MW": "Maláwi",
  "MX": "Mẹ́ksíko",
  "MY": "Maléshia",
  "MZ": "Mozámbik",
  "Mlym": "Maléyálam",
  "Mong": "Mọngólia",
  "Mymr": "Miánmar",
  "NA": "Namíbia",
  "NC": "Niú Kalẹdónia",
  "NE": "Nizhẹr",
  "NF": "Nọ́fọlk Aíland",
  "NG": "Naijíria",
  "NI": "Nikarágwua",
  "NL": "Nẹ́dalands",
  "NO": "Nọ́we",
  "NP": "Nẹ́pal",
  "NR": "Náuru",
  "NU": "Niúẹ",
  "NZ": "Niú Zíland",
  "OM": "Oman",
  "Orya": "Ódia",
  "PA": "Pánáma",
  "PE": "Pẹ́ru",
  "PF": "Frẹ́nch Poliníshia",
  "PG": "Pápuá Niú Gíni",
  "PH": "Fílípins",
  "PK": "Pakístan",
  "PL": "Póland",
  "PM": "Sent Piẹr & Míkẹlọn",
  "PN": "Pítkén Aílands",
  "PR": "Puẹ́rto Ríkọ",
  "PS": "Pálẹ́staín Éria-dẹm",
  "PT": "Pọ́túgal",
  "PW": "Palau",
  "PY": "Párágwue",
  "QA": "Kata",
  "QO": "Rimót Pát ọf Oshẹ́nia",
  "RE": "Réyúniọn",
  "RO": "Ruménia",
  "RS": "Sẹ́bia",
  "RU": "Rọ́shia",
  "RW": "Ruwánda",
  "SA": "Saúdí Arébia",
  "SB": "Sólómọ́n Aílands",
  "SC": "Sẹ́chẹls",
  "SD": "Sudan",
  "SE": "Swídẹn",
  "SG": "Singapọ",
  "SH": "Sent Hẹlẹ́na",
  "SI": "Slovẹ́nia",
  "SJ": "Sválbad & Jén Meyẹn",
  "SK": "Slovékia",
  "SL": "Siẹ́ra Líon",
  "SM": "San Maríno",
  "SN": "Sẹ́nẹ́gal",
  "SO": "Sọmália",
  "SR": "Súrínam",
  "SS": "Saút Sudan",
  "ST": "Sao Tómé & Prínsípẹ",
  "SV": "El Sálvádọ",
  "SX": "Sint Mátin",
  "SY": "Síria",
  "SZ": "Ẹswatíni",
  "Sinh": "Sinhála",
  "TA": "Trístán da Kúna",
  "TC": "Tọks an Kaíkọ́s Aílands",
  "TD": "Chad",
  "TF": "Frẹ́nch Saútán Tẹ́rẹ́tris",
  "TG": "Tógo",
  "TH": "Taíland",
  "TJ": "Tajíkstan",
  "TK": "Tókẹ́lau",
  "TL": "Íst Tímọ",
  "TM": "Tọkmẹ́nístan",
  "TN": "Tuníshia",
  "TO": "Tónga",
  "TR": "Tọ́ki",
  "TT": "Trínídad & Tobágo",
  "TV": "Tuválu",
  "TW": "Taiwan",
  "TZ": "Tanzánia",
  "Taml": "Támil",
  "Telu": "Tẹ́lúgu",
  "Thaa": "Tána",
  "Thai": "Taí",
  "Tibt": "Tíbẹt",
  "UA": "Yukrein",
  "UG": "Yugánda",
  "UM": "U.S. Faá Faá Aílands",
  "UN": "Yunaítẹd Néshọns",
  "US": "Yunaítẹ́d Stets",
  "UY": "Yúrugwue",
  "UZ": "Uzbẹ́kistan",
  "VA": "Vátíkán Síti",
  "VC": "Sent Vínsẹnt & Grẹ́nádians",
  "VE": "Vẹnẹzuẹ́la",
  "VG": "Brítísh Vájín Aílands",
  "VI": "U.S. Vájín Aílands",
  "VN": "Viẹ́tnam",
  "VU": "Vanuátu",
  "WF": "Wọ́lis & Fiutúna",
  "WS": "Samóa",
  "XA": "To yúz atifíshál vọis wẹ́n yu de tọk",
  "XB": "Atífíshál Tú-Wé Dairẹ́kshọn",
  "XK": "Kósóvo",
  "YE": "Yẹ́mẹn",
  "YT": "Meyọt",
  "ZA": "Saút Áfríka",
  "ZM": "Zámbia",
  "ZW": "Zimbábwẹ",
  "ZZ": "Ríjọn Wé Nóbọ́di Sabí",
  "Zmth": "Matimátiks Sains",
  "Zsye": "Ẹ́móji",
  "Zsym": "Símbuls",
  "Zxxx": "Wétín Dẹm Nó Rait",
  "Zyyy": "Jẹ́náral",
  "Zzzz": "Raítín Sístẹm Wé Nóbọ́di Sabí",
  "af": "Áfríkaans Lángwej",
  "agq": "Aghẹ́m Lángwej",
  "ak": "Akan Lángwej",
  "am": "Amhárík Lángwej",
  "ar": "Arábík Lángwej",
  "ar_001": "Gẹ́nárál Arábík Lángwej fọ dís taim",
  "as": "Asamíz Lángwej",
  "asa": "Asu Lángwej",
  "ast": "Astúriá Lángwej",
  "az": "Azẹrbaijáni Lángwej",
  "bas": "Básaa Lángwej",
  "be": "Bẹlarúsiá Lángwej",
  "bem": "Bẹ́mba Lángwej",
  "bez": "Bẹ́na Lángwej",
  "bg": "Bọlgériá Lángwej",
  "bm": "Bambára Lángwej",
  "bn": "Bángla Lángwej",
  "bo": "Tibẹ́tan",
  "br": "Brẹ́tọn Lángwej",
  "brx": "Bódo Lángwej",
  "bs": "Bọ́sniá Lángwej",
  "ca": "Kátála Lángwej",
  "ccp": "Chákma Lángwej",
  "ce": "Chẹ́chẹn Lángwej",
  "ceb": "Sẹbuáno Lángwej",
  "cgg": "Chíga Lángwej",
  "chr": "Chẹ́rókii Lángwej",
  "ckb": "Mídúl Kọ́dish Lángwej",
  "co": "Kọsíkan Lángwej",
  "cs": "Chẹ́k Lángwej",
  "cu": "Chọ́ch Slávik",
  "cy": "Wẹlsh",
  "da": "Dénísh Lángwej",
  "dav": "Taíta",
  "de": "Jámán Lángwej",
  "de_AT": "Ọ́stria Jámán",
  "de_CH": "Swítzaland Haí Jámán",
  "dje": "Zármá",
  "dsb": "Lówá Sorbiá",
  "dua": "Duála Lángwej",
  "dyo": "Jóla-Fónyi Lángwej",
  "dz": "Zọ́ngka Lángwej",
  "ebu": "Ẹmbu Lángwej",
  "ee": "Ẹ́wẹ́ Lángwej",
  "el": "Grík Lángwej",
  "en": "Ínglish",
  "en_AU": "Ọstréliá Ínglish",
  "en_CA": "Kánáda Ínglish",
  "en_GB": "Brítísh Ínglish",
  "en_US": "Amẹ́ríka Ínglish",
  "eo": "Ẹsperánto Lángwej",
  "es": "Spánish Lángwej",
  "es_419": "Látín Amẹ́ríka Spánish",
  "es_ES": "Yúrop Spánish",
  "es_MX": "Mẹ́ksiko Spánish",
  "et": "Ẹstóniá Lángwej",
  "eu": "Básk Lángwej",
  "ewo": "Ẹwondo Lángwej",
  "fa": "Pẹ́shiá Lángwej",
  "fa_AF": "Dári",
  "ff": "Fúlaní Lángwej",
  "fi": "Fínísh Lángwej",
  "fil": "Filipínó Lángwej",
  "fo": "Fáróís Lángwej",
  "fr": "Frẹ́nch Lángwej",
  "fr_CA": "Kánádá Frẹnch",
  "fr_CH": "Swítzalánd Frẹnch",
  "fur": "Friúlián Lángwej",
  "fy": "Wẹ́stán Frísiá Lángwej",
  "ga": "Aírísh Lángwej",
  "gd": "Gaelík Lángwej ọf Gael Pípol fọ Skọ́tland",
  "gl": "Galísiá Lángwej",
  "gsw": "Jámán Swis",
  "gu": "Gujarátí Lángwej",
  "guz": "Gusí Lángwej",
  "gv": "Mánks Lángwej",
  "ha": "Háusá Lángwej",
  "haw": "Hawaii Lángwej",
  "he": "Híbru Lángwej",
  "hi": "Híndi Lángwej",
  "hmn": "Mọ́ng Lángwej",
  "hr": "Kroéshia Lángwej",
  "hsb": "Sóbiá Lángwej di ọ́p-ọ́p wan",
  "ht": "Haítí Kriol",
  "hu": "Họngári Lángwej",
  "hy": "Armẹ́niá Lángwej",
  "ia": "Intalíngwuá Lángwej",
  "id": "Indoníshia Lángwej",
  "ig": "Igbo Lángwej",
  "ii": "Síchuan Yi",
  "is": "Aíslánd Lángwej",
  "it": "Ítáli Lángwej",
  "ja": "Japan Lángwej",
  "jgo": "Ngómbá Lángwej",
  "jmc": "Machámẹ́ Lángwej",
  "jv": "Javáníz Lángwej",
  "ka": "Jọ́jiá Lángwej",
  "kab": "Kabail Lángwej",
  "kam": "Kámbá Lángwej",
  "kde": "Makọ́ndẹ́ Lángwej",
  "kea": "Kábúvẹrdiánu Lángwej",
  "khq": "Koyra Chíní Lángwej",
  "ki": "Kikúyú Lángwej",
  "kk": "Kazák Lángwej",
  "kkj": "Kákó Lángwej",
  "kl": "Kalálísút Lángwej",
  "kln": "Kálẹ́njín Lángwej",
  "km": "Kmaí Lángwej",
  "kn": "Kánnáda Lángwej",
  "ko": "Koriá Lángwej",
  "kok": "Kónkéní Lángwej",
  "ks": "Kashmírí Lángwej",
  "ksb": "Shambala",
  "ksf": "Bafiá Lángwej",
  "ksh": "Kọlónián Lángwej",
  "ku": "Kọ́dísh Lángwej",
  "kw": "Kọ́nish Lángwej",
  "ky": "Kiẹ́gíz Lángwej",
  "la": "Látín Lángwej",
  "lag": "Langi Lángwej",
  "lb": "Lọ́ksémbọ́g Lángwej",
  "lg": "Gánda Lángwej",
  "lkt": "Lakótá Lángwej",
  "ln": "Lingálá Lángwej",
  "lo": "Láo Lángwej",
  "lrc": "Nọ́tán Lúrí Lángwej",
  "lt": "Lituéniá Lángwej",
  "lu": "Lúbá-Katángá Lángwej",
  "luo": "Luó Lángwej",
  "luy": "Luyia Lángwej",
  "lv": "Látvián Lángwej",
  "mas": "Masaí Lángwej",
  "mer": "Mẹ́rú Lángwej",
  "mfe": "Morísiẹ́n Lángwej",
  "mg": "Malagásí Lángwej",
  "mgh": "Makúwá-Mító",
  "mgo": "Mẹta’ Lángwej",
  "mi": "Maórí Lángwej",
  "mk": "Masẹdóniá Lángwej",
  "ml": "Maléyálám Lángwej",
  "mn": "Mọngóliá Lángwej",
  "mr": "Marátí Lángwej",
  "ms": "Malé Lángwej",
  "mt": "Mọ́ltá Lángwej",
  "mua": "Mundáng Lángwej",
  "mul": "Plẹ́ntí Lángwej-dẹm",
  "my": "Bọ́ma Lángwej",
  "mzn": "Mazandẹrání Lángwej",
  "naq": "Naámá Lángwej",
  "nb": "Nọwẹ́jiá Bokmál Lángwej",
  "nd": "Nọ́tán Ndẹbẹlẹ Lángwej",
  "nds": "Ló Jámán Lángwej",
  "ne": "Nẹpálí Lángwej",
  "nl": "Dọch Lángwej",
  "nl_BE": "Flẹ́mish Lángwej",
  "nmg": "Kwasió Lángwej",
  "nn": "Nọwẹ́jiá Niúnọsk",
  "nnh": "Ngiẹ́mbọn Lángwej",
  "nus": "Núa",
  "ny": "Nyánja",
  "nyn": "Nyankólẹ",
  "om": "Orómó",
  "or": "Ódiá",
  "os": "Osẹ́tik",
  "pa": "Punjábi",
  "pcm": "Naijíriá Píjin",
  "pl": "Pólánd Lángwej",
  "prg": "Prúshia",
  "ps": "Páshto",
  "pt": "Pọtiugiz",
  "pt_BR": "Brazíl Pọtiugíz",
  "pt_PT": "Yúróp Pọtiugíz",
  "qu": "Kẹchuá",
  "rm": "Románsh",
  "rn": "Rúndi",
  "ro": "Romániá Lángwej",
  "rof": "Rómbo",
  "ru": "Rọshiá Lángwej",
  "rw": "Kinyarwánda Lángwej",
  "rwk": "Rwa",
  "sa": "Sánskrit",
  "sah": "Sakhá",
  "saq": "Sambúru",
  "sbp": "Sangu",
  "sd": "Síndí",
  "se": "Nọ́tán Sámí Lángwej",
  "seh": "Sẹ́ná",
  "ses": "Kóiraboró Sẹ́nní Lángwej",
  "sg": "sàngo",
  "shi": "Táchẹ́lit",
  "si": "Sínhala",
  "sk": "Slóvak",
  "sl": "Slovẹ́niá Lángwej",
  "sm": "Samóá Lángwej",
  "smn": "Ínárí Sámí Lángwej",
  "sn": "Shóna",
  "so": "Sọmáli",
  "sq": "Albéniá Lángwej",
  "sr": "Sẹrbiá Lángwej",
  "st": "Saútán Sóto",
  "su": "Sọ́ndaniz",
  "sv": "Suwídẹ́n Lángwej",
  "sw": "Swahíli",
  "ta": "tàmil",
  "te": "Tẹlugu",
  "teo": "Tẹ́so",
  "tg": "Tájik",
  "th": "Taí",
  "ti": "Tigrínyá",
  "tk": "Tọ́kmẹn",
  "to": "Tóngan",
  "tr": "Tọ́ki",
  "tt": "Tatá",
  "twq": "Tasawak",
  "tzm": "Mídúl Atlás Támazígt Lángwej",
  "ug": "Wiúgọ",
  "uk": "Yukrénia",
  "und": "Lángwej wé nóbọ́di sabi",
  "ur": "Úrdú",
  "uz": "Úzbẹk",
  "vai": "Vaí",
  "vi": "Viẹ́tnám Lángwej",
  "vo": "Vólapiuk",
  "vun": "Vúnjo",
  "wae": "Wọ́lsa",
  "wo": "Wólof",
  "xh": "Kọ́sa",
  "xog": "sóga",
  "yav": "Yangbẹn",
  "yi": "Yídish",
  "yo": "Yorubá",
  "yue": "Kántọn Lángwej",
  "zgh": "Gẹ́nárál Morókó Támazígt Lángwej",
  "zh": "Mandarín Chainíz Lángwej",
  "zh_Hans": "Ízí Chainíz Lángwej",
  "zh_Hant": "Tradíshọ́nál Chainíz Lángwej",
  "zu": "Zúlu",
  "zxx": "Nó Lángwéj Kọ́ntẹnt"
};
