const names = {
  "akz": "Alabama",
  "aln": "Gheg Albanian",
  "arn": "araucà",
  "aro": "Araona",
  "arz": "Egyptian Arabic",
  "ase": "American Sign Language",
  "bar": "Bavarian",
  "bax": "bamun",
  "be": "bielorús",
  "bfq": "Badaga",
  "bin": "bini",
  "brh": "Brahui",
  "bum": "seki",
  "chy": "xeienne",
  "ckb": "kurd sorani",
  "den": "slavey",
  "egl": "Emilian",
  "ext": "Extremaduran",
  "frc": "Cajun French",
  "frs": "frisó occidental",
  "fy": "frisó oriental",
  "gan": "Gan Chinese",
  "glk": "Gilaki",
  "gom": "Goan Konkani",
  "guc": "Wayuu",
  "gwi": "gwichin",
  "hak": "Hakka Chinese",
  "hif": "Fiji Hindi",
  "hil": "hiligainon",
  "hsn": "Xiang Chinese",
  "ht": "haitià",
  "ilo": "ilocà",
  "jam": "Jamaican Creole English",
  "ken": "Kenyang",
  "kgp": "Kaingang",
  "kok": "konkani",
  "krc": "karatxai",
  "kri": "Krio",
  "ksh": "colognian",
  "lad": "ladí",
  "lij": "Ligurian",
  "lmo": "Lombard",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mos": "moré",
  "mrj": "Western Mari",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nov": "Novial",
  "os": "osset",
  "pag": "pangasi",
  "pam": "pampangà",
  "pap": "papiamento",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pfl": "Palatine German",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "prg": "Prussian",
  "quc": "quitxé",
  "rgn": "Romagnol",
  "sd": "sindhi",
  "sdc": "Sassarese Sardinian",
  "ss": "siswati",
  "su": "sundanès",
  "szl": "Silesian",
  "tet": "tetun",
  "th": "tailandès",
  "tkr": "Tsakhur",
  "tl": "tagàlog",
  "tly": "Talysh",
  "tmh": "tamazight",
  "tn": "tswana",
  "ttt": "Muslim Tat",
  "vec": "Venetian",
  "vep": "Veps",
  "vls": "West Flemish",
  "wal": "ameto",
  "war": "waray-waray",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "xmf": "Mingrelian",
  "yi": "jiddisch",
  "zea": "Zeelandic"
};
