const names = {
  "001": "svet",
  "002": "Afrika",
  "003": "Severna Amerika",
  "005": "Južna Amerika",
  "009": "Oceanija",
  "011": "Zahodna Afrika",
  "013": "Srednja Amerika",
  "014": "Vzhodna Afrika",
  "015": "Severna Afrika",
  "017": "Srednja Afrika",
  "018": "Južna Afrika",
  "019": "Amerike",
  "021": "severnoameriška celina",
  "029": "Karibi",
  "030": "Vzhodna Azija",
  "034": "Južna Azija",
  "035": "Jugovzhodna Azija",
  "039": "Južna Evropa",
  "053": "Avstralija in Nova Zelandija",
  "054": "Melanezija",
  "057": "mikronezijska regija",
  "061": "Polinezija",
  "062": "Južna Srednja Azija",
  "142": "Azija",
  "143": "Osrednja Azija",
  "145": "Zahodna Azija",
  "150": "Evropa",
  "151": "Vzhodna Evropa",
  "154": "Severna Evropa",
  "155": "Zahodna Evropa",
  "172": "Skupnost neodvisnih držav",
  "200": "Češkoslovaška",
  "202": "podsaharska Afrika",
  "419": "Latinska Amerika",
  "830": "Kanalski otoki",
  "AC": "Otok Ascension",
  "AD": "Andora",
  "AE": "Združeni arabski emirati",
  "AF": "Afganistan",
  "AG": "Antigva in Barbuda",
  "AI": "Angvila",
  "AL": "Albanija",
  "AM": "Armenija",
  "AN": "Nizozemski Antili",
  "AO": "Angola",
  "AQ": "Antarktika",
  "AR": "Argentina",
  "AS": "Ameriška Samoa",
  "AT": "Avstrija",
  "AU": "Avstralija",
  "AW": "Aruba",
  "AX": "Ålandski otoki",
  "AZ": "Azerbajdžan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Kavkaški albanski",
  "Ahom": "Ahom",
  "Arab": "arabski",
  "Aran": "Nastaliq",
  "Armi": "imperialno-aramejski",
  "Armn": "armenski",
  "Avst": "avestanski",
  "BA": "Bosna in Hercegovina",
  "BB": "Barbados",
  "BD": "Bangladeš",
  "BE": "Belgija",
  "BF": "Burkina Faso",
  "BG": "Bolgarija",
  "BH": "Bahrajn",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermudi",
  "BN": "Brunej",
  "BO": "Bolivija",
  "BQ": "Nizozemski Karibi",
  "BR": "Brazilija",
  "BS": "Bahami",
  "BT": "Butan",
  "BV": "Bouvetov otok",
  "BW": "Bocvana",
  "BY": "Belorusija",
  "BZ": "Belize",
  "Bali": "balijski",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "bataški",
  "Beng": "bengalski",
  "Bhks": "Bhaiksuki",
  "Blis": "znakovna pisava Bliss",
  "Bopo": "bopomofo",
  "Brah": "bramanski",
  "Brai": "braillova pisava",
  "Bugi": "buginski",
  "Buhd": "buhidski",
  "CA": "Kanada",
  "CC": "Kokosovi otoki",
  "CD": "Demokratična republika Kongo",
  "CF": "Centralnoafriška republika",
  "CG": "Kongo - Brazzaville",
  "CH": "Švica",
  "CI": "Slonokoščena obala",
  "CK": "Cookovi otoki",
  "CL": "Čile",
  "CM": "Kamerun",
  "CN": "Kitajska",
  "CO": "Kolumbija",
  "CP": "Otok Clipperton",
  "CR": "Kostarika",
  "CS": "Srbija in Črna gora",
  "CU": "Kuba",
  "CV": "Zelenortski otoki",
  "CW": "Curaçao",
  "CX": "Božični otok",
  "CY": "Ciper",
  "CZ": "Češka",
  "Cakm": "Chakma",
  "Cans": "poenotena zlogovna pisava kanadskih staroselcev",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "čerokeški",
  "Chrs": "Chorasmian",
  "Cirt": "kirt",
  "Copt": "koptski",
  "Cprt": "ciprski",
  "Cyrl": "cirilica",
  "Cyrs": "starocerkvenoslovanska cirilica",
  "DD": "Vzhodna Nemčija",
  "DE": "Nemčija",
  "DG": "Diego Garcia",
  "DJ": "Džibuti",
  "DK": "Danska",
  "DM": "Dominika",
  "DO": "Dominikanska republika",
  "DZ": "Alžirija",
  "Deva": "devanagarščica",
  "Diak": "Potaplja Akuru",
  "Dogr": "Dogra",
  "Dsrt": "fonetska pisava deseret",
  "Dupl": "Duployan stenografija",
  "EA": "Ceuta in Melilla",
  "EC": "Ekvador",
  "EE": "Estonija",
  "EG": "Egipt",
  "EH": "Zahodna Sahara",
  "ER": "Eritreja",
  "ES": "Španija",
  "ET": "Etiopija",
  "EU": "Evropska unija",
  "EZ": "evroobmočje",
  "Egyd": "demotska egipčanska pisava",
  "Egyh": "hieratska egipčanska pisava",
  "Egyp": "egipčanska slikovna pisava",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "etiopski",
  "FI": "Finska",
  "FJ": "Fidži",
  "FK": "Falklandski otoki",
  "FM": "Mikronezija",
  "FO": "Ferski otoki",
  "FR": "Francija",
  "FX": "Metropolitanska Francija",
  "GA": "Gabon",
  "GB": "Združeno kraljestvo",
  "GD": "Grenada",
  "GE": "Gruzija",
  "GF": "Francoska Gvajana",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Gibraltar",
  "GL": "Grenlandija",
  "GM": "Gambija",
  "GN": "Gvineja",
  "GP": "Guadeloupe",
  "GQ": "Ekvatorialna Gvineja",
  "GR": "Grčija",
  "GS": "Južna Georgia in Južni Sandwichevi otoki",
  "GT": "Gvatemala",
  "GU": "Guam",
  "GW": "Gvineja Bissau",
  "GY": "Gvajana",
  "Geok": "cerkvenogruzijski",
  "Geor": "gruzijski",
  "Glag": "glagoliški",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "gotski",
  "Gran": "Grantha",
  "Grek": "grški",
  "Gujr": "gudžaratski",
  "Guru": "gurmuki",
  "HK": "Posebno administrativno območje LR Kitajske Hongkong",
  "HM": "Heardov otok in McDonaldovi otoki",
  "HN": "Honduras",
  "HR": "Hrvaška",
  "HT": "Haiti",
  "HU": "Madžarska",
  "Hanb": "Han + Bopomofo",
  "Hang": "hangul",
  "Hani": "kanji",
  "Hano": "hanunski",
  "Hans": "poenostavljena pisava han",
  "Hant": "tradicionalna pisava han",
  "Hatr": "Hatran",
  "Hebr": "hebrejski",
  "Hira": "hiragana",
  "Hluw": "Anatolski hieroglifi",
  "Hmng": "pahavhmonska zlogovna pisava",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "japonska zlogovnica",
  "Hung": "staroogrski",
  "IC": "Kanarski otoki",
  "ID": "Indonezija",
  "IE": "Irska",
  "IL": "Izrael",
  "IM": "Otok Man",
  "IN": "Indija",
  "IO": "Britansko ozemlje v Indijskem oceanu",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Islandija",
  "IT": "Italija",
  "Inds": "induški",
  "Ital": "staroitalski",
  "JE": "Jersey",
  "JM": "Jamajka",
  "JO": "Jordanija",
  "JP": "Japonska",
  "Jamo": "Jamo",
  "Java": "javanski",
  "Jpan": "japonski",
  "Jurc": "Jurchen",
  "KE": "Kenija",
  "KG": "Kirgizistan",
  "KH": "Kambodža",
  "KI": "Kiribati",
  "KM": "Komori",
  "KN": "Saint Kitts in Nevis",
  "KP": "Severna Koreja",
  "KR": "Južna Koreja",
  "KW": "Kuvajt",
  "KY": "Kajmanski otoki",
  "KZ": "Kazahstan",
  "Kali": "karenski",
  "Kana": "katakana",
  "Khar": "gandarski",
  "Khmr": "kmerski",
  "Khoj": "Khojki",
  "Kits": "Khitan mali scenarij",
  "Knda": "kanadski",
  "Kore": "korejski",
  "Kpel": "Kpelle",
  "Kthi": "kajatski",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Lihtenštajn",
  "LK": "Šrilanka",
  "LR": "Liberija",
  "LS": "Lesoto",
  "LT": "Litva",
  "LU": "Luksemburg",
  "LV": "Latvija",
  "LY": "Libija",
  "Lana": "Lanna",
  "Laoo": "laoški",
  "Latf": "fraktura",
  "Latg": "gelski latinični",
  "Latn": "latinica",
  "Lepc": "lepški",
  "Limb": "limbuški",
  "Lina": "linearna pisava A",
  "Linb": "linearna pisava B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "licijski",
  "Lydi": "lidijski",
  "MA": "Maroko",
  "MC": "Monako",
  "MD": "Moldavija",
  "ME": "Črna gora",
  "MF": "Saint Martin",
  "MG": "Madagaskar",
  "MH": "Marshallovi otoki",
  "MI": "Midway Islands",
  "MK": "Severna Makedonija",
  "ML": "Mali",
  "MM": "Mjanmar (Burma)",
  "MN": "Mongolija",
  "MO": "Posebno administrativno območje LR Kitajske Macao",
  "MP": "Severni Marianski otoki",
  "MQ": "Martinik",
  "MR": "Mavretanija",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldivi",
  "MW": "Malavi",
  "MX": "Mehika",
  "MY": "Malezija",
  "MZ": "Mozambik",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "mandanski",
  "Mani": "manihejski",
  "Marc": "Marchen",
  "Maya": "majevska slikovna pisava",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitska kurzivnost",
  "Mero": "meroitski",
  "Mlym": "malajalamski",
  "Modi": "Modi",
  "Mong": "mongolska",
  "Moon": "Moonova pisava za slepe",
  "Mroo": "Mro",
  "Mtei": "manipurski",
  "Mult": "Multani",
  "Mymr": "mjanmarski",
  "NA": "Namibija",
  "NC": "Nova Kaledonija",
  "NE": "Niger",
  "NF": "Norfolški otok",
  "NG": "Nigerija",
  "NI": "Nikaragva",
  "NL": "Nizozemska",
  "NO": "Norveška",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Nevtralno območje",
  "NU": "Niue",
  "NZ": "Nova Zelandija",
  "Nand": "Nandinagari",
  "Narb": "Stara severnoarabska",
  "Nbat": "Nabatejski",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "ogamski",
  "Olck": "santalski",
  "Orkh": "orkonski",
  "Orya": "orijski",
  "Osge": "Osage",
  "Osma": "osmanski",
  "PA": "Panama",
  "PC": "Zaupno ozemlje pacifiških otokov",
  "PE": "Peru",
  "PF": "Francoska Polinezija",
  "PG": "Papua Nova Gvineja",
  "PH": "Filipini",
  "PK": "Pakistan",
  "PL": "Poljska",
  "PM": "Saint Pierre in Miquelon",
  "PN": "Pitcairn",
  "PR": "Portoriko",
  "PS": "Palestinsko ozemlje",
  "PT": "Portugalska",
  "PU": "Ameriški razni pacifiški otoki",
  "PW": "Palau",
  "PY": "Paragvaj",
  "PZ": "Cona Panamskega prekopa",
  "Palm": "Palmiren",
  "Pauc": "Pau Cin Hau",
  "Perm": "staropermijski",
  "Phag": "pagpajski",
  "Phli": "vrezani napisi pahlavi",
  "Phlp": "psalmski pahlavi",
  "Phlv": "knjižno palavanski",
  "Phnx": "feničanski",
  "Plrd": "Pollardova fonetska pisava",
  "Prti": "Natpisni Parthian",
  "QA": "Katar",
  "QO": "Ostala oceanija",
  "Qaag": "Zawgyi",
  "RE": "Reunion",
  "RO": "Romunija",
  "RS": "Srbija",
  "RU": "Rusija",
  "RW": "Ruanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingja",
  "Roro": "rongorongo",
  "Runr": "runski",
  "SA": "Saudova Arabija",
  "SB": "Salomonovi otoki",
  "SC": "Sejšeli",
  "SD": "Sudan",
  "SE": "Švedska",
  "SG": "Singapur",
  "SH": "Sveta Helena",
  "SI": "Slovenija",
  "SJ": "Svalbard in Jan Mayen",
  "SK": "Slovaška",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalija",
  "SR": "Surinam",
  "SS": "Južni Sudan",
  "ST": "Sao Tome in Principe",
  "SU": "Zveza sovjetskih socialističnih republik",
  "SV": "Salvador",
  "SX": "Sint Maarten",
  "SY": "Sirija",
  "SZ": "Esvatini",
  "Samr": "samaritanski",
  "Sara": "saratski",
  "Sarb": "Stara južnoarabska",
  "Saur": "Saurashtra",
  "Sgnw": "znakovna pisava",
  "Shaw": "šojevski",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "sinhalski",
  "Sogd": "Sogdian",
  "Sogo": "Stari Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "sundanski",
  "Sylo": "siletsko-nagarijski",
  "Syrc": "sirijski",
  "Syre": "sirska abeceda estrangelo",
  "Syrj": "zahodnosirijski",
  "Syrn": "vzhodnosirijski",
  "TA": "Tristan da Cunha",
  "TC": "Otoki Turks in Caicos",
  "TD": "Čad",
  "TF": "Francosko južno ozemlje",
  "TG": "Togo",
  "TH": "Tajska",
  "TJ": "Tadžikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunizija",
  "TO": "Tonga",
  "TR": "Turčija",
  "TT": "Trinidad in Tobago",
  "TV": "Tuvalu",
  "TW": "Tajvan",
  "TZ": "Tanzanija",
  "Tagb": "tagbanski",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Novi Tai Lue",
  "Taml": "tamilski",
  "Tang": "Tangut",
  "Tavt": "tajsko-vietnamski",
  "Telu": "teluški",
  "Teng": "tengvarski",
  "Tfng": "tifinajski",
  "Tglg": "tagaloški",
  "Thaa": "tanajski",
  "Thai": "tajski",
  "Tibt": "tibetanski",
  "Tirh": "Tirhuta",
  "UA": "Ukrajina",
  "UG": "Uganda",
  "UM": "Stranski zunanji otoki Združenih držav",
  "UN": "Združeni narodi",
  "US": "Združene države Amerike",
  "UY": "Urugvaj",
  "UZ": "Uzbekistan",
  "Ugar": "ugaritski",
  "VA": "Vatikan",
  "VC": "Saint Vincent in Grenadine",
  "VD": "Severni Vietnam",
  "VE": "Venezuela",
  "VG": "Britanski Deviški otoki",
  "VI": "Ameriški Deviški otoki",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "zlogovna pisava vai",
  "Visp": "vidni govor",
  "WF": "Wallis in Futuna",
  "WK": "Otok Wake",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "psevdonaglasi",
  "XB": "psevdobidi",
  "XK": "Kosovo",
  "Xpeo": "staroperzijski",
  "Xsux": "sumersko-akadski klinopis",
  "YD": "Ljudska demokratična republika Jemen",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "Južnoafriška republika",
  "ZM": "Zambija",
  "ZW": "Zimbabve",
  "ZZ": "Neznano ali neveljavno območje",
  "Zanb": "Trg Zanabazar",
  "Zinh": "podedovan",
  "Zmth": "matematična znamenja",
  "Zsye": "čustvenček",
  "Zsym": "simboli",
  "Zxxx": "nenapisano",
  "Zyyy": "splošno",
  "Zzzz": "neznan ali neveljaven zapis",
  "aa": "afarščina",
  "ab": "abhaščina",
  "ace": "ačejščina",
  "ach": "ačolijščina",
  "ada": "adangmejščina",
  "ady": "adigejščina",
  "ae": "avestijščina",
  "aeb": "Tunisian Arabic",
  "af": "afrikanščina",
  "af_NA": "afrikanščina (Namibija)",
  "af_ZA": "afrikanščina (Južnoafriška republika)",
  "afa": "afroazijski jezik",
  "afh": "afrihili",
  "agq": "aghemščina",
  "ain": "ainujščina",
  "ak": "akanščina",
  "ak_GH": "akanščina (Gana)",
  "akk": "akadščina",
  "akz": "Alabama",
  "ale": "aleutščina",
  "alg": "algonkinski jezik",
  "aln": "Gheg Albanian",
  "alt": "južna altajščina",
  "am": "amharščina",
  "am_ET": "amharščina (Etiopija)",
  "an": "aragonščina",
  "ang": "stara angleščina",
  "anp": "angikaščina",
  "apa": "apaški jezik",
  "ar": "arabščina",
  "ar_001": "sodobna standardna arabščina",
  "ar_AE": "arabščina (Združeni arabski emirati)",
  "ar_BH": "arabščina (Bahrajn)",
  "ar_DJ": "arabščina (Džibuti)",
  "ar_DZ": "arabščina (Alžirija)",
  "ar_EG": "arabščina (Egipt)",
  "ar_EH": "arabščina (Zahodna Sahara)",
  "ar_ER": "arabščina (Eritreja)",
  "ar_IL": "arabščina (Izrael)",
  "ar_IQ": "arabščina (Irak)",
  "ar_JO": "arabščina (Jordanija)",
  "ar_KM": "arabščina (Komori)",
  "ar_KW": "arabščina (Kuvajt)",
  "ar_LB": "arabščina (Libanon)",
  "ar_LY": "arabščina (Libija)",
  "ar_MA": "arabščina (Maroko)",
  "ar_MR": "arabščina (Mavretanija)",
  "ar_OM": "arabščina (Oman)",
  "ar_PS": "arabščina (Palestinsko ozemlje)",
  "ar_QA": "arabščina (Katar)",
  "ar_SA": "arabščina (Saudova Arabija)",
  "ar_SD": "arabščina (Sudan)",
  "ar_SO": "arabščina (Somalija)",
  "ar_SS": "arabščina (Južni Sudan)",
  "ar_SY": "arabščina (Sirija)",
  "ar_TD": "arabščina (Čad)",
  "ar_TN": "arabščina (Tunizija)",
  "ar_YE": "arabščina (Jemen)",
  "arc": "aramejščina",
  "arn": "aravkanščina",
  "aro": "Araona",
  "arp": "arapaščina",
  "arq": "Algerian Arabic",
  "ars": "Najdi arabščina",
  "art": "umetni jezik",
  "arw": "aravaščina",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "asamščina",
  "as_IN": "asamščina (Indija)",
  "asa": "asujščina",
  "ase": "American Sign Language",
  "ast": "asturijščina",
  "ath": "atabaški jezik",
  "aus": "avstralski jezik",
  "av": "avarščina",
  "avk": "Kotava",
  "awa": "avadščina",
  "ay": "ajmarščina",
  "az": "azerbajdžanščina",
  "az_AZ": "azerbajdžanščina (Azerbajdžan)",
  "az_Arab": "Azerbajdžanski (arabski)",
  "az_Cyrl": "azerbajdžanščina (cirilica)",
  "az_Cyrl_AZ": "azerbajdžanščina (cirilica, Azerbajdžan)",
  "az_Latn": "azerbajdžanščina (latinica)",
  "az_Latn_AZ": "azerbajdžanščina (latinica, Azerbajdžan)",
  "azb": "South Azerbaijani",
  "ba": "baškirščina",
  "bad": "bandaški jezik",
  "bai": "bamilekejski jezik",
  "bal": "beludžijščina",
  "ban": "balijščina",
  "bar": "Bavarian",
  "bas": "basa",
  "bat": "baltski jezik",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "beloruščina",
  "be_BY": "beloruščina (Belorusija)",
  "bej": "bedža",
  "bem": "bemba",
  "ber": "berberščina",
  "bew": "Betawi",
  "bez": "benajščina",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "bolgarščina",
  "bg_BG": "bolgarščina (Bolgarija)",
  "bgn": "zahodnobalučijščina",
  "bh": "biharščina",
  "bho": "bodžpuri",
  "bi": "bislamščina",
  "bik": "bikolski jezik",
  "bin": "edo",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "siksika",
  "bm": "bambarščina",
  "bm_Latn": "bambarščina (latinica)",
  "bm_Latn_ML": "bambarščina (latinica, Mali)",
  "bn": "bengalščina",
  "bn_BD": "bengalščina (Bangladeš)",
  "bn_IN": "bengalščina (Indija)",
  "bnt": "bantujščina",
  "bo": "tibetanščina",
  "bo_CN": "tibetanščina (Kitajska)",
  "bo_IN": "tibetanščina (Indija)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretonščina",
  "br_FR": "bretonščina (Francija)",
  "bra": "bradžbakanščina",
  "brh": "Brahui",
  "brx": "bodojščina",
  "bs": "bosanščina",
  "bs_BA": "bosanščina (Bosna in Hercegovina)",
  "bs_Cyrl": "bosanščina (cirilica)",
  "bs_Cyrl_BA": "bosanščina (cirilica, Bosna in Hercegovina)",
  "bs_Latn": "bosanščina (latinica)",
  "bs_Latn_BA": "bosanščina (latinica, Bosna in Hercegovina)",
  "bss": "Akoose",
  "btk": "bataški jezik",
  "bua": "burjatščina",
  "bug": "buginščina",
  "bum": "Bulu",
  "byn": "blinščina",
  "byv": "Medumba",
  "ca": "katalonščina",
  "ca_AD": "katalonščina (Andora)",
  "ca_ES": "katalonščina (Španija)",
  "ca_FR": "katalonščina (Francija)",
  "ca_IT": "katalonščina (Italija)",
  "cad": "kadoščina",
  "cai": "srednjeameriški indijanski jezik",
  "car": "karibski jezik",
  "cau": "kavkaški jezik",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "chakma",
  "ce": "čečenščina",
  "ceb": "sebuanščina",
  "cel": "keltski jezik",
  "cgg": "čigajščina",
  "ch": "čamorščina",
  "chb": "čibčevščina",
  "chg": "čagatajščina",
  "chk": "trukeščina",
  "chm": "marijščina",
  "chn": "činuški žargon",
  "cho": "čoktavščina",
  "chp": "čipevščina",
  "chr": "čerokeščina",
  "chy": "čejenščina",
  "cic": "Chickasaw",
  "ckb": "soranska kurdščina",
  "cmc": "camski jezik",
  "co": "korziščina",
  "cop": "koptščina",
  "cpe": "angleška kreolščina ali pidžinščina",
  "cpf": "francoska kreolščina ali pidžinščina",
  "cpp": "portugalska kreolščina ali pidžinščina",
  "cps": "Capiznon",
  "cr": "krijščina",
  "crh": "krimska tatarščina",
  "crp": "kreolščina ali pidžinščina",
  "crs": "sejšelska francoska kreolščina",
  "cs": "češčina",
  "cs_CZ": "češčina (Češka)",
  "csb": "kašubščina",
  "cu": "stara cerkvena slovanščina",
  "cus": "kušitščina",
  "cv": "čuvaščina",
  "cy": "valižanščina",
  "cy_GB": "valižanščina (Velika Britanija)",
  "da": "danščina",
  "da_DK": "danščina (Danska)",
  "da_GL": "danščina (Grenlandija)",
  "dak": "dakotščina",
  "dar": "darginščina",
  "dav": "taitajščina",
  "day": "dajaščina",
  "de": "nemščina",
  "de_AT": "nemščina (Avstrija)",
  "de_BE": "nemščina (Belgija)",
  "de_CH": "nemščina (Švica)",
  "de_DE": "nemščina (Nemčija)",
  "de_LI": "nemščina (Lihtenštajn)",
  "de_LU": "nemščina (Luksemburg)",
  "del": "delavarščina",
  "den": "slavejščina",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarmajščina",
  "doi": "dogri",
  "dra": "dravidski jezik",
  "dsb": "dolnja lužiška srbščina",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "srednja nizozemščina",
  "dv": "diveščina",
  "dyo": "jola-fonjiščina",
  "dyu": "diula",
  "dz": "dzonka",
  "dz_BT": "dzonka (Butan)",
  "dzg": "dazaga",
  "ebu": "embujščina",
  "ee": "evenščina",
  "ee_GH": "evenščina (Gana)",
  "ee_TG": "evenščina (Togo)",
  "efi": "efiščina",
  "egl": "Emilian",
  "egy": "stara egipčanščina",
  "eka": "ekajuk",
  "el": "grščina",
  "el_CY": "grščina (Ciper)",
  "el_GR": "grščina (Grčija)",
  "elx": "elamščina",
  "en": "angleščina",
  "en_AG": "angleščina (Antigva in Barbuda)",
  "en_AI": "angleščina (Angvila)",
  "en_AS": "angleščina (Ameriška Samoa)",
  "en_AU": "angleščina (Avstralija)",
  "en_BB": "angleščina (Barbados)",
  "en_BE": "angleščina (Belgija)",
  "en_BM": "angleščina (Bermudi)",
  "en_BS": "angleščina (Bahami)",
  "en_BW": "angleščina (Bocvana)",
  "en_BZ": "angleščina (Belize)",
  "en_CA": "angleščina (Kanada)",
  "en_CC": "angleščina (Kokosovi otoki)",
  "en_CK": "angleščina (Cookovi otoki)",
  "en_CM": "angleščina (Kamerun)",
  "en_CX": "angleščina (Božični otok)",
  "en_DG": "angleščina (Diego Garcia)",
  "en_DM": "angleščina (Dominika)",
  "en_Dsrt": "Angleščina (Deseret)",
  "en_ER": "angleščina (Eritreja)",
  "en_FJ": "angleščina (Fidži)",
  "en_FK": "angleščina (Falklandski otoki)",
  "en_FM": "angleščina (Mikronezija)",
  "en_GB": "angleščina (Velika Britanija)",
  "en_GD": "angleščina (Grenada)",
  "en_GG": "angleščina (Guernsey)",
  "en_GH": "angleščina (Gana)",
  "en_GI": "angleščina (Gibraltar)",
  "en_GM": "angleščina (Gambija)",
  "en_GU": "angleščina (Guam)",
  "en_GY": "angleščina (Gvajana)",
  "en_HK": "angleščina (Posebno administrativno območje LR Kitajske Hong Kong)",
  "en_IE": "angleščina (Irska)",
  "en_IM": "angleščina (Otok Man)",
  "en_IN": "angleščina (Indija)",
  "en_IO": "angleščina (Britansko ozemlje v Indijskem oceanu)",
  "en_JE": "angleščina (Jersey)",
  "en_JM": "angleščina (Jamajka)",
  "en_KE": "angleščina (Kenija)",
  "en_KI": "angleščina (Kiribati)",
  "en_KN": "angleščina (Saint Kitts in Nevis)",
  "en_KY": "angleščina (Kajmanski otoki)",
  "en_LC": "angleščina (Saint Lucia)",
  "en_LR": "angleščina (Liberija)",
  "en_LS": "angleščina (Lesoto)",
  "en_MG": "angleščina (Madagaskar)",
  "en_MH": "angleščina (Marshallovi otoki)",
  "en_MO": "angleščina (Posebno administrativno območje LR Kitajske Macao)",
  "en_MP": "angleščina (Severni Marianski otoki)",
  "en_MS": "angleščina (Montserrat)",
  "en_MT": "angleščina (Malta)",
  "en_MU": "angleščina (Mauritius)",
  "en_MW": "angleščina (Malavi)",
  "en_MY": "angleščina (Malezija)",
  "en_NA": "angleščina (Namibija)",
  "en_NF": "angleščina (Norfolški otok)",
  "en_NG": "angleščina (Nigerija)",
  "en_NR": "angleščina (Nauru)",
  "en_NU": "angleščina (Niue)",
  "en_NZ": "angleščina (Nova Zelandija)",
  "en_PG": "angleščina (Papua Nova Gvineja)",
  "en_PH": "angleščina (Filipini)",
  "en_PK": "angleščina (Pakistan)",
  "en_PN": "angleščina (Pitcairn)",
  "en_PR": "angleščina (Portoriko)",
  "en_PW": "angleščina (Palau)",
  "en_RW": "angleščina (Ruanda)",
  "en_SB": "angleščina (Salomonovi otoki)",
  "en_SC": "angleščina (Sejšeli)",
  "en_SD": "angleščina (Sudan)",
  "en_SG": "angleščina (Singapur)",
  "en_SH": "angleščina (Sveta Helena)",
  "en_SL": "angleščina (Sierra Leone)",
  "en_SS": "angleščina (Južni Sudan)",
  "en_SX": "angleščina (Sint Maarten)",
  "en_SZ": "angleščina (Svazi)",
  "en_TC": "angleščina (Otočji Turks in Caicos)",
  "en_TK": "angleščina (Tokelau)",
  "en_TO": "angleščina (Tonga)",
  "en_TT": "angleščina (Trinidad in Tobago)",
  "en_TV": "angleščina (Tuvalu)",
  "en_TZ": "angleščina (Tanzanija)",
  "en_UG": "angleščina (Uganda)",
  "en_UM": "angleščina (Druga ameriška ozemlja v Tihem oceanu)",
  "en_US": "angleščina (Združene države Amerike)",
  "en_VC": "angleščina (Saint Vincent in Grenadine)",
  "en_VG": "angleščina (Britanski Deviški otoki)",
  "en_VI": "angleščina (Ameriški Deviški otoki)",
  "en_VU": "angleščina (Vanuatu)",
  "en_WS": "angleščina (Samoa)",
  "en_ZA": "angleščina (Južnoafriška republika)",
  "en_ZM": "angleščina (Zambija)",
  "en_ZW": "angleščina (Zimbabve)",
  "enm": "srednja angleščina",
  "eo": "esperanto",
  "es": "španščina",
  "es_419": "latinskoameriška španščina",
  "es_AR": "španščina (Argentina)",
  "es_BO": "španščina (Bolivija)",
  "es_CL": "španščina (Čile)",
  "es_CO": "španščina (Kolumbija)",
  "es_CR": "španščina (Kostarika)",
  "es_CU": "španščina (Kuba)",
  "es_DO": "španščina (Dominikanska republika)",
  "es_EA": "španščina (Ceuta in Melilla)",
  "es_EC": "španščina (Ekvador)",
  "es_ES": "španščina (Španija)",
  "es_GQ": "španščina (Ekvatorialna Gvineja)",
  "es_GT": "španščina (Gvatemala)",
  "es_HN": "španščina (Honduras)",
  "es_IC": "španščina (Kanarski otoki)",
  "es_MX": "španščina (Mehika)",
  "es_NI": "španščina (Nikaragva)",
  "es_PA": "španščina (Panama)",
  "es_PE": "španščina (Peru)",
  "es_PH": "španščina (Filipini)",
  "es_PR": "španščina (Portoriko)",
  "es_PY": "španščina (Paragvaj)",
  "es_SV": "španščina (Salvador)",
  "es_US": "španščina (Združene države Amerike)",
  "es_UY": "španščina (Urugvaj)",
  "es_VE": "španščina (Venezuela)",
  "esu": "Central Yupik",
  "et": "estonščina",
  "et_EE": "estonščina (Estonija)",
  "eu": "baskovščina",
  "eu_ES": "baskovščina (Španija)",
  "ewo": "evondovščina",
  "ext": "Extremaduran",
  "fa": "perzijščina",
  "fa_AF": "perzijščina (Afganistan)",
  "fa_IR": "perzijščina (Iran)",
  "fan": "fangijščina",
  "fat": "fantijščina",
  "ff": "fulščina",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "fulščina (Kamerun)",
  "ff_GN": "fulščina (Gvineja)",
  "ff_MR": "fulščina (Mavretanija)",
  "ff_SN": "fulščina (Senegal)",
  "fi": "finščina",
  "fi_FI": "finščina (Finska)",
  "fil": "filipinščina",
  "fit": "Tornedalen Finnish",
  "fiu": "ugrofinski jezik",
  "fj": "fidžijščina",
  "fo": "ferščina",
  "fo_FO": "ferščina (Ferski otoki)",
  "fon": "fonščina",
  "fr": "francoščina",
  "fr_BE": "francoščina (Belgija)",
  "fr_BF": "francoščina (Burkina Faso)",
  "fr_BI": "francoščina (Burundi)",
  "fr_BJ": "francoščina (Benin)",
  "fr_BL": "francoščina (Saint Barthélemy)",
  "fr_CA": "francoščina (Kanada)",
  "fr_CD": "francoščina (Demokratična republika Kongo)",
  "fr_CF": "francoščina (Centralnoafriška republika)",
  "fr_CG": "francoščina (Kongo - Brazzaville)",
  "fr_CH": "francoščina (Švica)",
  "fr_CI": "francoščina (Slonokoščena obala)",
  "fr_CM": "francoščina (Kamerun)",
  "fr_DJ": "francoščina (Džibuti)",
  "fr_DZ": "francoščina (Alžirija)",
  "fr_FR": "francoščina (Francija)",
  "fr_GA": "francoščina (Gabon)",
  "fr_GF": "francoščina (Francoska Gvajana)",
  "fr_GN": "francoščina (Gvineja)",
  "fr_GP": "francoščina (Gvadalupe)",
  "fr_GQ": "francoščina (Ekvatorialna Gvineja)",
  "fr_HT": "francoščina (Haiti)",
  "fr_KM": "francoščina (Komori)",
  "fr_LU": "francoščina (Luksemburg)",
  "fr_MA": "francoščina (Maroko)",
  "fr_MC": "francoščina (Monako)",
  "fr_MF": "francoščina (Saint Martin)",
  "fr_MG": "francoščina (Madagaskar)",
  "fr_ML": "francoščina (Mali)",
  "fr_MQ": "francoščina (Martinik)",
  "fr_MR": "francoščina (Mavretanija)",
  "fr_MU": "francoščina (Mauritius)",
  "fr_NC": "francoščina (Nova Kaledonija)",
  "fr_NE": "francoščina (Niger)",
  "fr_PF": "francoščina (Francoska Polinezija)",
  "fr_PM": "francoščina (Saint Pierre in Miquelon)",
  "fr_RE": "francoščina (Reunion)",
  "fr_RW": "francoščina (Ruanda)",
  "fr_SC": "francoščina (Sejšeli)",
  "fr_SN": "francoščina (Senegal)",
  "fr_SY": "francoščina (Sirija)",
  "fr_TD": "francoščina (Čad)",
  "fr_TG": "francoščina (Togo)",
  "fr_TN": "francoščina (Tunizija)",
  "fr_VU": "francoščina (Vanuatu)",
  "fr_WF": "francoščina (Wallis in Futuna)",
  "fr_YT": "francoščina (Mayotte)",
  "frc": "cajunska francoščina",
  "frm": "srednja francoščina",
  "fro": "stara francoščina",
  "frp": "Arpitan",
  "frr": "severna frizijščina",
  "frs": "vzhodna frizijščina",
  "fur": "furlanščina",
  "fy": "zahodna frizijščina",
  "fy_NL": "frizijščina (Nizozemska)",
  "ga": "irščina",
  "ga_IE": "irščina (Irska)",
  "gaa": "ga",
  "gag": "gagavščina",
  "gan": "Gan Chinese",
  "gay": "gajščina",
  "gba": "gbajščina",
  "gbz": "Zoroastrian Dari",
  "gd": "škotska gelščina",
  "gd_GB": "škotska gelščina (Velika Britanija)",
  "gem": "germanski jezik",
  "gez": "etiopščina",
  "gil": "kiribatščina",
  "gl": "galicijščina",
  "gl_ES": "galicijščina (Španija)",
  "glk": "Gilaki",
  "gmh": "srednja visoka nemščina",
  "gn": "gvaranijščina",
  "goh": "stara visoka nemščina",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalščina",
  "got": "gotščina",
  "grb": "grebščina",
  "grc": "stara grščina",
  "gsw": "nemščina (Švica)",
  "gu": "gudžaratščina",
  "gu_IN": "gudžaratščina (Indija)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusijščina",
  "gv": "manščina",
  "gv_IM": "manščina (Otok Man)",
  "gwi": "gvičin",
  "ha": "havščina",
  "ha_GH": "havščina (Gana)",
  "ha_Latn": "havščina (latinica)",
  "ha_Latn_GH": "havščina (latinica, Gana)",
  "ha_Latn_NE": "havščina (latinica, Niger)",
  "ha_Latn_NG": "havščina (latinica, Nigerija)",
  "ha_NE": "havščina (Niger)",
  "ha_NG": "havščina (Nigerija)",
  "hai": "haidščina",
  "hak": "Hakka Chinese",
  "haw": "havajščina",
  "he": "hebrejščina",
  "he_IL": "hebrejščina (Izrael)",
  "hi": "hindujščina",
  "hi_IN": "hindujščina (Indija)",
  "hif": "Fiji Hindi",
  "hil": "hiligajnonščina",
  "him": "himačalščina",
  "hit": "hetitščina",
  "hmn": "hmonščina",
  "ho": "hiri motu",
  "hr": "hrvaščina",
  "hr_BA": "hrvaščina (Bosna in Hercegovina)",
  "hr_HR": "hrvaščina (Hrvaška)",
  "hsb": "gornja lužiška srbščina",
  "hsn": "Xiang Chinese",
  "ht": "haitijska kreolščina",
  "hu": "madžarščina",
  "hu_HU": "madžarščina (Madžarska)",
  "hup": "hupa",
  "hy": "armenščina",
  "hy_AM": "armenščina (Armenija)",
  "hz": "herero",
  "ia": "interlingva",
  "iba": "ibanščina",
  "ibb": "ibibijščina",
  "id": "indonezijščina",
  "id_ID": "indonezijščina (Indonezija)",
  "ie": "interlingve",
  "ig": "igboščina",
  "ig_NG": "igboščina (Nigerija)",
  "ii": "sečuanska jiščina",
  "ii_CN": "sečuanska jiščina (Kitajska)",
  "ijo": "ijo",
  "ik": "inupiaščina",
  "ilo": "ilokanščina",
  "inc": "indijski jezik",
  "ine": "indoevropski jezik",
  "inh": "inguščina",
  "io": "ido",
  "ira": "iranski jezik",
  "iro": "irokeški jezik",
  "is": "islandščina",
  "is_IS": "islandščina (Islandija)",
  "it": "italijanščina",
  "it_CH": "italijanščina (Švica)",
  "it_IT": "italijanščina (Italija)",
  "it_SM": "italijanščina (San Marino)",
  "iu": "inuktitutščina",
  "izh": "Ingrian",
  "ja": "japonščina",
  "ja_JP": "japonščina (Japonska)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "mačamejščina",
  "jpr": "judovska perzijščina",
  "jrb": "judovska arabščina",
  "jut": "Jutish",
  "jv": "javanščina",
  "ka": "gruzijščina",
  "ka_GE": "gruzinščina (Gruzija)",
  "kaa": "karakalpaščina",
  "kab": "kabilščina",
  "kac": "kačinščina",
  "kaj": "jju",
  "kam": "kambaščina",
  "kar": "karenščina",
  "kaw": "kavi",
  "kbd": "kabardinščina",
  "kbl": "Kanembu",
  "kcg": "tjapska nigerijščina",
  "kde": "makondščina",
  "kea": "zelenortskootoška kreolščina",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kongovščina",
  "kgp": "Kaingang",
  "kha": "kasi",
  "khi": "koisanski jezik",
  "kho": "kotanščina",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "kikujščina",
  "ki_KE": "kikujščina (Kenija)",
  "kiu": "Kirmanjki",
  "kj": "kvanjama",
  "kk": "kazaščina",
  "kk_Cyrl": "kazaščina (cirilica)",
  "kk_Cyrl_KZ": "kazaščina (cirilica, Kazahstan)",
  "kk_KZ": "kazaščina (Kazahstan)",
  "kkj": "kako",
  "kl": "grenlandščina",
  "kl_GL": "grenlandščina (Grenlandija)",
  "kln": "kalenjinščina",
  "km": "kmerščina",
  "km_KH": "kmerščina (Kambodža)",
  "kmb": "kimbundu",
  "kn": "kanareščina",
  "kn_IN": "kanada (Indija)",
  "ko": "korejščina",
  "ko_KP": "korejščina (Severna Koreja)",
  "ko_KR": "korejščina (Južna Koreja)",
  "koi": "komi-permjaščina",
  "kok": "konkanščina",
  "kos": "kosrajščina",
  "kpe": "kpelejščina",
  "kr": "kanurščina",
  "krc": "karačaj-balkarščina",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "karelščina",
  "kro": "jezik kru",
  "kru": "kuruk",
  "ks": "kašmirščina",
  "ks_Arab": "kašmirščina (arabski)",
  "ks_Arab_IN": "kašmirščina (arabski, Indija)",
  "ks_IN": "kašmirščina (Indija)",
  "ksb": "šambala",
  "ksf": "bafia",
  "ksh": "kölnsko narečje",
  "ku": "kurdščina",
  "kum": "kumiščina",
  "kut": "kutenajščina",
  "kv": "komijščina",
  "kw": "kornijščina",
  "kw_GB": "kornijščina (Velika Britanija)",
  "ky": "kirgiščina",
  "ky_Cyrl": "kirgiščina (cirilica)",
  "ky_Cyrl_KG": "kirgiščina (cirilica, Kirgizistan)",
  "ky_KG": "kirgiščina (Kirgizistan)",
  "la": "latinščina",
  "lad": "ladinščina",
  "lag": "langijščina",
  "lah": "landa",
  "lam": "lamba",
  "lb": "luksemburščina",
  "lb_LU": "luksemburščina (Luksemburg)",
  "lez": "lezginščina",
  "lfn": "Lingua Franca Nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburščina",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "lakotščina",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Demokratična republika Kongo)",
  "ln_CF": "lingala (Centralnoafriška republika)",
  "ln_CG": "lingala (Kongo - Brazzaville)",
  "lo": "laoščina",
  "lo_LA": "laoščina (Laos)",
  "lol": "mongo",
  "lou": "louisianska kreolščina",
  "loz": "lozi",
  "lrc": "severna lurijščina",
  "lt": "litovščina",
  "lt_LT": "litovščina (Litva)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Demokratična republika Kongo)",
  "lua": "luba-lulua",
  "lui": "luisenščina",
  "lun": "lunda",
  "luo": "luo",
  "lus": "mizojščina",
  "luy": "luhijščina",
  "lv": "latvijščina",
  "lv_LV": "latvijščina (Latvija)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "madurščina",
  "maf": "Mafa",
  "mag": "magadščina",
  "mai": "maitili",
  "mak": "makasarščina",
  "man": "mandingo",
  "map": "avstronezijski jezik",
  "mas": "masajščina",
  "mde": "Maba",
  "mdf": "mokšavščina",
  "mdr": "mandarščina",
  "men": "mende",
  "mer": "meru",
  "mfe": "morisjenščina",
  "mg": "malagaščina",
  "mg_MG": "malagaščina (Madagaskar)",
  "mga": "srednja irščina",
  "mgh": "makuva-meto",
  "mgo": "meta",
  "mh": "marshallovščina",
  "mi": "maorščina",
  "mic": "mikmaščina",
  "min": "minangkabau",
  "mis": "drugi jeziki",
  "mk": "makedonščina",
  "mk_MK": "makedonščina (Makedonija)",
  "mkh": "monsko-kmerski jezik",
  "ml": "malajalamščina",
  "ml_IN": "malajalamščina (Indija)",
  "mn": "mongolščina",
  "mn_Cyrl": "mongolščina (cirilica)",
  "mn_Cyrl_MN": "mongolščina (cirilica, Mongolija)",
  "mn_MN": "mongolščina (Mongolija)",
  "mnc": "mandžurščina",
  "mni": "manipurščina",
  "mno": "kotabatski manobo",
  "mo": "moldavščina",
  "moh": "mohoščina",
  "mos": "mosijščina",
  "mr": "maratščina",
  "mr_IN": "maratščina (Indija)",
  "mrj": "Western Mari",
  "ms": "malajščina",
  "ms_BN": "malajščina (Brunej)",
  "ms_Latn": "malajščina (latinica)",
  "ms_Latn_BN": "malajščina (latinica, Brunej)",
  "ms_Latn_MY": "malajščina (latinica, Malezija)",
  "ms_Latn_SG": "malajščina (latinica, Singapur)",
  "ms_MY": "malajščina (Malezija)",
  "ms_SG": "malajščina (Singapur)",
  "mt": "malteščina",
  "mt_MT": "malteščina (Malta)",
  "mua": "mundang",
  "mul": "več jezikov",
  "mun": "mundski jezik",
  "mus": "creekovščina",
  "mwl": "mirandeščina",
  "mwr": "marvarščina",
  "mwv": "Mentawai",
  "my": "burmanščina",
  "my_MM": "burmanščina (Mjanmar (Burma))",
  "mye": "Myene",
  "myn": "majevski jezik",
  "myv": "erzjanščina",
  "mzn": "mazanderanščina",
  "na": "naurujščina",
  "nah": "nahuatl",
  "nai": "severnoameriški indijanski jezik",
  "nan": "min nan kitajščina",
  "nap": "napolitanščina",
  "naq": "khoekhoe",
  "nb": "knjižna norveščina",
  "nb_NO": "knjižna norveščina (Norveška)",
  "nb_SJ": "knjižna norveščina (Svalbard in Jan Mayen)",
  "nd": "severna ndebelščina",
  "nd_ZW": "severna ndebelščina (Zimbabve)",
  "nds": "nizka nemščina",
  "nds_NL": "nizka saščina",
  "ne": "nepalščina",
  "ne_IN": "nepalščina (Indija)",
  "ne_NP": "nepalščina (Nepal)",
  "new": "nevarščina",
  "ng": "ndonga",
  "nia": "niaščina",
  "nic": "nigrsko-kordofanski jezik",
  "niu": "niuejščina",
  "njo": "Ao Naga",
  "nl": "nizozemščina",
  "nl_AW": "nizozemščina (Aruba)",
  "nl_BE": "nizozemščina (Belgija)",
  "nl_BQ": "nizozemščina (Nizozemski Karibi)",
  "nl_CW": "nizozemščina (Curaçao)",
  "nl_NL": "nizozemščina (Nizozemska)",
  "nl_SR": "nizozemščina (Surinam)",
  "nl_SX": "nizozemščina (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "novonorveščina",
  "nn_NO": "novonorveščina (Norveška)",
  "nnh": "ngiemboonščina",
  "no": "norveščina",
  "no_NO": "norveščina (Norveška)",
  "nog": "nogajščina",
  "non": "stara nordijščina",
  "nov": "Novial",
  "nqo": "n’ko",
  "nr": "južna ndebelščina",
  "nso": "severna sotščina",
  "nub": "nubijski jezik",
  "nus": "nuerščina",
  "nv": "navajščina",
  "nwc": "klasična nevarščina",
  "ny": "njanščina",
  "nym": "njamveščina",
  "nyn": "njankole",
  "nyo": "njoro",
  "nzi": "nzima",
  "oc": "okcitanščina",
  "oj": "anašinabščina",
  "om": "oromo",
  "om_ET": "oromo (Etiopija)",
  "om_KE": "oromo (Kenija)",
  "or": "odijščina",
  "or_IN": "orijščina (Indija)",
  "os": "osetinščina",
  "os_GE": "osetinščina (Gruzija)",
  "os_RU": "osetinščina (Rusija)",
  "osa": "osage",
  "ota": "otomanska turščina",
  "oto": "otomijski jezik",
  "pa": "pandžabščina",
  "pa_Arab": "pandžabščina (arabski)",
  "pa_Arab_PK": "pandžabščina (arabski, Pakistan)",
  "pa_Guru": "pandžabščina (gurmuki)",
  "pa_Guru_IN": "pandžabščina (gurmuki, Indija)",
  "pa_IN": "pandžabščina (Indija)",
  "pa_PK": "pandžabščina (Pakistan)",
  "paa": "papuanski jezik",
  "pag": "pangasinanščina",
  "pal": "Pahlavi",
  "pam": "pampanščina",
  "pap": "papiamentu",
  "pau": "palavanščina",
  "pcd": "Picard",
  "pcm": "nigerijski pidžin",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "stara perzijščina",
  "pfl": "Palatine German",
  "phi": "filipinski jezik",
  "phn": "feničanščina",
  "pi": "palijščina",
  "pl": "poljščina",
  "pl_PL": "poljščina (Poljska)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "ponpejščina",
  "pra": "prakritski jezik",
  "prg": "stara pruščina",
  "pro": "stara provansalščina",
  "ps": "paštunščina",
  "ps_AF": "paštunščina (Afganistan)",
  "pt": "portugalščina",
  "pt_AO": "portugalščina (Angola)",
  "pt_BR": "portugalščina (Brazilija)",
  "pt_CV": "portugalščina (Zelenortski otoki)",
  "pt_GW": "portugalščina (Gvineja Bissau)",
  "pt_MO": "portugalščina (Posebno administrativno območje LR Kitajske Macao)",
  "pt_MZ": "portugalščina (Mozambik)",
  "pt_PT": "portugalščina (Portugalska)",
  "pt_ST": "portugalščina (Sao Tome in Principe)",
  "pt_TL": "portugalščina (Vzhodni Timor)",
  "qu": "kečuanščina",
  "qu_BO": "kečuanščina (Bolivija)",
  "qu_EC": "kečuanščina (Ekvador)",
  "qu_PE": "kečuanščina (Peru)",
  "quc": "quiche",
  "qug": "Chimborazo Highland Quichua",
  "raj": "radžastanščina",
  "rap": "rapanujščina",
  "rar": "rarotongščina",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "retoromanščina",
  "rm_CH": "retoromanščina (Švica)",
  "rn": "rundščina",
  "rn_BI": "rundščina (Burundi)",
  "ro": "romunščina",
  "ro_MD": "romunščina (Moldavija)",
  "ro_RO": "romunščina (Romunija)",
  "roa": "romanski jezik",
  "rof": "rombo",
  "rom": "romščina",
  "root": "rootščina",
  "rtm": "Rotuman",
  "ru": "ruščina",
  "ru_BY": "ruščina (Belorusija)",
  "ru_KG": "ruščina (Kirgizistan)",
  "ru_KZ": "ruščina (Kazahstan)",
  "ru_MD": "ruščina (Moldavija)",
  "ru_RU": "ruščina (Rusija)",
  "ru_UA": "ruščina (Ukrajina)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromunščina",
  "rw": "ruandščina",
  "rw_RW": "ruandščina (Ruanda)",
  "rwk": "rwa",
  "sa": "sanskrt",
  "sad": "sandavščina",
  "sah": "jakutščina",
  "sai": "Južnoameriški indijski jezik",
  "sal": "Salishan jezik",
  "sam": "samaritanska aramejščina",
  "saq": "samburščina",
  "sas": "sasaščina",
  "sat": "santalščina",
  "saz": "Saurashtra",
  "sba": "ngambajščina",
  "sbp": "sangujščina",
  "sc": "sardinščina",
  "scn": "sicilijanščina",
  "sco": "škotščina",
  "sd": "sindščina",
  "sd_Deva": "Sindhi (devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "južna kurdščina",
  "se": "severna samijščina",
  "se_FI": "severna samijščina (Finska)",
  "se_NO": "severna samijščina (Norveška)",
  "se_SE": "severna samijščina (Švedska)",
  "see": "Seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "selkupščina",
  "sem": "semitski jezik",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (Centralnoafriška republika)",
  "sga": "stara irščina",
  "sgn": "znakovni jezik",
  "sgs": "Samogitian",
  "sh": "srbohrvaščina",
  "sh_BA": "srbohrvaščina (Bosna in Hercegovina)",
  "shi": "tahelitska berberščina",
  "shi_Latn": "Šilha (latinica)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "šanščina",
  "shu": "Chadian Arabic",
  "si": "sinhalščina",
  "si_LK": "singalščina (Šrilanka)",
  "sid": "sidamščina",
  "sio": "sijuščina",
  "sit": "kitajsko-tibetanski jezik",
  "sk": "slovaščina",
  "sk_SK": "slovaščina (Slovaška)",
  "sl": "slovenščina",
  "sl_SI": "slovenščina (Slovenija)",
  "sla": "slovanski jezik",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoanščina",
  "sma": "južna samijščina",
  "smi": "samijski jezik",
  "smj": "luleška samijščina",
  "smn": "inarska samijščina",
  "sms": "skoltska samijščina",
  "sn": "šonščina",
  "sn_ZW": "šonščina (Zimbabve)",
  "snk": "soninke",
  "so": "somalščina",
  "so_DJ": "somalščina (Džibuti)",
  "so_ET": "somalščina (Etiopija)",
  "so_KE": "somalščina (Kenija)",
  "so_SO": "somalščina (Somalija)",
  "sog": "Sogdien",
  "son": "songajščina",
  "sq": "albanščina",
  "sq_AL": "albanščina (Albanija)",
  "sq_MK": "albanščina (Makedonija)",
  "sq_XK": "albanščina (Kosovo)",
  "sr": "srbščina",
  "sr_BA": "srbščina (Bosna in Hercegovina)",
  "sr_Cyrl": "srbščina (cirilica)",
  "sr_Cyrl_BA": "srbščina (cirilica, Bosna in Hercegovina)",
  "sr_Cyrl_ME": "srbščina (cirilica, Črna gora)",
  "sr_Cyrl_RS": "srbščina (cirilica, Srbija)",
  "sr_Cyrl_XK": "srbščina (cirilica, Kosovo)",
  "sr_Latn": "srbščina (latinica)",
  "sr_Latn_BA": "srbščina (latinica, Bosna in Hercegovina)",
  "sr_Latn_ME": "srbščina (latinica, Črna gora)",
  "sr_Latn_RS": "srbščina (latinica, Srbija)",
  "sr_Latn_XK": "srbščina (latinica, Kosovo)",
  "sr_ME": "srbščina (Črna gora)",
  "sr_RS": "srbščina (Srbija)",
  "sr_XK": "srbščina (Kosovo)",
  "srn": "surinamska kreolščina",
  "srr": "sererščina",
  "ss": "svazijščina",
  "ssa": "nilsko-saharski jezik",
  "ssy": "saho",
  "st": "sesoto",
  "stq": "Saterland Frisian",
  "su": "sundanščina",
  "suk": "sukuma",
  "sus": "susujščina",
  "sux": "sumerščina",
  "sv": "švedščina",
  "sv_AX": "švedščina (Ålandski otoki)",
  "sv_FI": "švedščina (Finska)",
  "sv_SE": "švedščina (Švedska)",
  "sw": "svahili",
  "sw_CD": "kongoški svahili",
  "sw_KE": "svahili (Kenija)",
  "sw_TZ": "svahili (Tanzanija)",
  "sw_UG": "svahili (Uganda)",
  "swb": "šikomor",
  "swc": "svahili (Kongo)",
  "syc": "klasična sirščina",
  "syr": "sirščina",
  "szl": "Silesian",
  "ta": "tamilščina",
  "ta_IN": "tamilščina (Indija)",
  "ta_LK": "tamilščina (Šrilanka)",
  "ta_MY": "tamilščina (Malezija)",
  "ta_SG": "tamilščina (Singapur)",
  "tai": "tajski jezik",
  "tcy": "Tulu",
  "te": "telugijščina",
  "te_IN": "telugijščina (Indija)",
  "tem": "temnejščina",
  "teo": "teso",
  "ter": "Tereno",
  "tet": "tetumščina",
  "tg": "tadžiščina",
  "th": "tajščina",
  "th_TH": "tajščina (Tajska)",
  "ti": "tigrajščina",
  "ti_ER": "tigrajščina (Eritreja)",
  "ti_ET": "tigrajščina (Etiopija)",
  "tig": "tigrejščina",
  "tiv": "tivščina",
  "tk": "turkmenščina",
  "tkl": "tokelavščina",
  "tkr": "Tsakhur",
  "tl": "tagalogščina",
  "tl_PH": "tagalogščina (Filipini)",
  "tlh": "klingonščina",
  "tli": "tlingitščina",
  "tly": "Talysh",
  "tmh": "tamajaščina",
  "tn": "cvanščina",
  "to": "tongščina",
  "to_TO": "tongščina (Tonga)",
  "tog": "malavijska tongščina",
  "tpi": "tok pisin",
  "tr": "turščina",
  "tr_CY": "turščina (Ciper)",
  "tr_TR": "turščina (Turčija)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "congščina",
  "tsd": "Tsakonian",
  "tsi": "tsimščina",
  "tt": "tatarščina",
  "ttt": "Muslim Tat",
  "tum": "tumbukščina",
  "tup": "tupijski jezik",
  "tut": "altajski jezik",
  "tvl": "tuvalujščina",
  "tw": "tvi",
  "twq": "tasawaq",
  "ty": "tahitščina",
  "tyv": "tuvinščina",
  "tzm": "tamašek (Srednji Atlas)",
  "udm": "udmurtščina",
  "ug": "ujgurščina",
  "ug_Arab": "ujgurščina (arabski)",
  "ug_Arab_CN": "ujgurščina (arabski, Kitajska)",
  "ug_CN": "ujgurščina (Kitajska)",
  "uga": "ugaritski jezik",
  "uk": "ukrajinščina",
  "uk_UA": "ukrajinščina (Ukrajina)",
  "umb": "umbundščina",
  "und": "neznan jezik",
  "ur": "urdujščina",
  "ur_IN": "urdujščina (Indija)",
  "ur_PK": "urdujščina (Pakistan)",
  "uz": "uzbeščina",
  "uz_AF": "uzbeščina (Afganistan)",
  "uz_Arab": "uzbeščina (arabski)",
  "uz_Arab_AF": "uzbeščina (arabski, Afganistan)",
  "uz_Cyrl": "uzbeščina (cirilica)",
  "uz_Cyrl_UZ": "uzbeščina (cirilica, Uzbekistan)",
  "uz_Latn": "uzbeščina (latinica)",
  "uz_Latn_UZ": "uzbeščina (latinica, Uzbekistan)",
  "uz_UZ": "uzbeščina (Uzbekistan)",
  "vai": "vajščina",
  "vai_Latn": "Vai (latinica)",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnamščina",
  "vi_VN": "vietnamščina (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapuk",
  "vot": "votjaščina",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "valonščina",
  "wae": "walser",
  "wak": "vakaški jezik",
  "wal": "valamščina",
  "war": "varajščina",
  "was": "vašajščina",
  "wbp": "varlpirščina",
  "wen": "lužiško srbski jezik",
  "wo": "volofščina",
  "wuu": "Wu Chinese",
  "xal": "kalmiščina",
  "xh": "koščina",
  "xmf": "Mingrelian",
  "xog": "sogščina",
  "yao": "jaojščina",
  "yap": "japščina",
  "yav": "jangben",
  "ybb": "jembajščina",
  "yi": "jidiš",
  "yo": "jorubščina",
  "yo_BJ": "jorubščina (Benin)",
  "yo_NG": "jorubščina (Nigerija)",
  "ypk": "jupiški jezik",
  "yrl": "Nheengatu",
  "yue": "kantonščina",
  "yue_Hans": "Kantonščina (poenostavljena kitajščina)",
  "yue_Hant": "Kantonski (tradicionalna kitajščina)",
  "za": "Zhuang",
  "zap": "zapoteščina",
  "zbl": "znakovni jezik Bliss",
  "zea": "Zeelandic",
  "zen": "zenaščina",
  "zgh": "standardni maroški tamazig",
  "zh": "kitajščina",
  "zh_CN": "kitajščina (Kitajska)",
  "zh_HK": "kitajščina (Posebno administrativno območje LR Kitajske Hong Kong)",
  "zh_Hans": "kitajščina (poenostavljena pisava han)",
  "zh_Hans_CN": "kitajščina (poenostavljena pisava han, Kitajska)",
  "zh_Hans_HK":
      "kitajščina (poenostavljena pisava han, Posebno administrativno območje LR Kitajske Hong Kong)",
  "zh_Hans_MO":
      "kitajščina (poenostavljena pisava han, Posebno administrativno območje LR Kitajske Macao)",
  "zh_Hans_SG": "kitajščina (poenostavljena pisava han, Singapur)",
  "zh_Hant": "kitajščina (tradicionalna pisava han)",
  "zh_Hant_HK":
      "kitajščina (tradicionalna pisava han, Posebno administrativno območje LR Kitajske Hong Kong)",
  "zh_Hant_MO":
      "kitajščina (tradicionalna pisava han, Posebno administrativno območje LR Kitajske Macao)",
  "zh_Hant_TW": "kitajščina (tradicionalna pisava han, Tajvan)",
  "zh_MO": "kitajščina (Posebno administrativno območje LR Kitajske Macao)",
  "zh_SG": "kitajščina (Singapur)",
  "zh_TW": "kitajščina (Tajvan)",
  "znd": "zandejščina",
  "zu": "zulujščina",
  "zu_ZA": "zulujščina (Južnoafriška republika)",
  "zun": "zunijščina",
  "zxx": "brez jezikoslovne vsebine",
  "zza": "zazajščina"
};
