const names = {
  "001": "Agbáyé",
  "002": "Áfíríkà",
  "003": "Àríwá Amẹ́ríkà",
  "005": "Gúúṣù Amẹ́ríkà",
  "009": "Oceania",
  "011": "Ìwọ̀ oorùn Afíríkà",
  "013": "Ààrin Gbùgbùn Àmẹ́ríkà",
  "014": "Ìlà Oorùn Áfíríkà",
  "015": "Northern Africa",
  "017": "Ààrín gbùngbùn Afíríkà",
  "018": "Apágúúsù Áfíríkà",
  "019": "Amẹ́ríkà",
  "021": "Apáàríwá Amẹ́ríkà",
  "029": "Káríbíànù",
  "030": "Ìlà Òòrùn Eṣíà",
  "034": "Gúúṣù Eṣíà",
  "035": "Gúúṣù ìlà òòrùn Éṣíà",
  "039": "Gúúṣù Yúróòpù",
  "053": "Ọṣirélaṣíà",
  "054": "Mẹlanéṣíà",
  "057": "Agbègbè Maikironéṣíà",
  "061": "Polineṣíà",
  "062": "South-Central Asia",
  "142": "Asia",
  "143": "Ààrin Gbùngbùn Éṣíà",
  "145": "Ìwọ̀ Òòrùn Eṣíà",
  "150": "Europe",
  "151": "Ìlà Òrùn Yúrópù",
  "154": "Northern Europe",
  "155": "Ìwọ̀ Òòrùn Yúrópù",
  "172": "Ajo Agbaye ti Awọn Ipinle Ominira",
  "200": "Czechoslovakia",
  "202": "Sàhárà Áfíríkà",
  "419": "Látín Amẹ́ríkà",
  "830": "Awọn erekusu ikanni",
  "AC": "Erékùsù Ascension",
  "AD": "Orílẹ́ède Ààndórà",
  "AE": "Orílẹ́ède Ẹmirate ti Awọn Arabu",
  "AF": "Orílẹ́ède Àfùgànístánì",
  "AG": "Orílẹ́ède Ààntígúà àti Báríbúdà",
  "AI": "Orílẹ́ède Ààngúlílà",
  "AL": "Orílẹ́ède Àlùbàníánì",
  "AM": "Orílẹ́ède Améníà",
  "AN": "Orílẹ́ède Nedalandi ti Antelisi",
  "AO": "Orílẹ́ède Ààngólà",
  "AQ": "Antakítíkà",
  "AR": "Orílẹ́ède Agentínà",
  "AS": "Sámóánì ti Orílẹ́ède Àméríkà",
  "AT": "Orílẹ́ède Asítíríà",
  "AU": "Orílẹ́ède Ástràlìá",
  "AW": "Orílẹ́ède Árúbà",
  "AX": "Àwọn Erékùsù ti Åland",
  "AZ": "Orílẹ́ède Asẹ́bájánì",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Ọmọ Albania ti Caucasian",
  "Ahom": "Ahom",
  "Arab": "èdè Lárúbáwá",
  "Aran": "Nastaliq",
  "Armi": "Arameiki Imperial",
  "Armn": "Àmẹ́níà",
  "Avst": "Avestan",
  "BA": "Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà",
  "BB": "Orílẹ́ède Bábádósì",
  "BD": "Orílẹ́ède Bángáládésì",
  "BE": "Orílẹ́ède Bégíọ́mù",
  "BF": "Orílẹ́ède Bùùkíná Fasò",
  "BG": "Orílẹ́ède Bùùgáríà",
  "BH": "Orílẹ́ède Báránì",
  "BI": "Orílẹ́ède Bùùrúndì",
  "BJ": "Orílẹ́ède Bẹ̀nẹ̀",
  "BL": "St. Barthélemy",
  "BM": "Orílẹ́ède Bémúdà",
  "BN": "Orílẹ́ède Búrúnẹ́lì",
  "BO": "Orílẹ́ède Bọ̀lífíyà",
  "BQ": "Caribbean Netherlands",
  "BR": "Orilẹ̀-èdè Bàràsílì",
  "BS": "Orílẹ́ède Bàhámásì",
  "BT": "Orílẹ́ède Bútánì",
  "BV": "Erékùsù Bouvet",
  "BW": "Orílẹ́ède Bọ̀tìsúwánà",
  "BY": "Orílẹ́ède Bélárúsì",
  "BZ": "Orílẹ́ède Bèlísẹ̀",
  "Bali": "Balinese",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Báńgílà",
  "Bhks": "Bhaiksuki",
  "Blis": "Awọn aami bliss",
  "Bopo": "Bopomófò",
  "Brah": "Brahmi",
  "Brai": "Bíráìlè",
  "Bugi": "Buginese",
  "Buhd": "Buhid",
  "CA": "Orílẹ́ède Kánádà",
  "CC": "Erékùsù Cocos (Keeling)",
  "CD": "Orilẹ́ède Kóngò",
  "CF": "Orílẹ́ède Àrin gùngun Áfíríkà",
  "CG": "Orílẹ́ède Kóngò",
  "CH": "Orílẹ́ède switiṣilandi",
  "CI": "Orílẹ́ède Kóútè forà",
  "CK": "Orílẹ́ède Etíokun Kùúkù",
  "CL": "Orílẹ́ède ṣílè",
  "CM": "Orílẹ́ède Kamerúúnì",
  "CN": "Orilẹ̀-èdè Ṣáínà",
  "CO": "Orílẹ́ède Kòlómíbìa",
  "CP": "Erékùsù Clipperston",
  "CR": "Orílẹ́ède Kuusita Ríkà",
  "CS": "Orílẹ́ède sẹbia ati Mọtinegoro",
  "CU": "Orílẹ́ède Kúbà",
  "CV": "Orílẹ́ède Etíokun Kápé féndè",
  "CW": "Curaçao",
  "CX": "Erékùsù Christmas",
  "CY": "Orílẹ́ède Kúrúsì",
  "CZ": "Orílẹ́ède ṣẹ́ẹ́kì",
  "Cakm": "Chakma",
  "Cans": "Iṣọkan Aboriginal Syllabics",
  "Cari": "Arabinrin Carian",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Coptic",
  "Cprt": "Kipirọti",
  "Cyrl": "èdè ilẹ̀ Rọ́ṣíà",
  "Cyrs": "Ijo Slavonic Cyrillic atijọ",
  "DD": "Ila-oorun Jẹmánì",
  "DE": "Orílẹèdè Jámánì",
  "DG": "Diego Gaṣia",
  "DJ": "Orílẹ́ède Díbọ́ótì",
  "DK": "Orílẹ́ède Dẹ́mákì",
  "DM": "Orílẹ́ède Dòmíníkà",
  "DO": "Orilẹ́ède Dòmíníkánì",
  "DZ": "Orílẹ́ède Àlùgèríánì",
  "Deva": "Dẹfanagárì",
  "Diak": "Dives Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Duployan kukuru",
  "EA": "Seuta àti Melilla",
  "EC": "Orílẹ́ède Ekuádò",
  "EE": "Orílẹ́ède Esitonia",
  "EG": "Orílẹ́ède Égípítì",
  "EH": "Ìwọ̀òòrùn Sàhárà",
  "ER": "Orílẹ́ède Eritira",
  "ES": "Orílẹ́ède Sipani",
  "ET": "Orílẹ́ède Etopia",
  "EU": "Ìṣọ̀kan Yúròpù",
  "EZ": "Agbègbè Euro",
  "Egyd": "Ara ilu Egipti",
  "Egyh": "Egipti hieratic",
  "Egyp": "Awọn hieroglyph ti Egipti",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "Ẹtiópíìkì",
  "FI": "Orílẹ́ède Filandi",
  "FJ": "Orílẹ́ède Fiji",
  "FK": "Orílẹ́ède Etikun Fakalandi",
  "FM": "Orílẹ́ède Makoronesia",
  "FO": "Àwọn Erékùsù ti Faroe",
  "FR": "Orílẹ́ède Faranse",
  "FX": "Ilu Ilu Ilu Faranse",
  "GA": "Orílẹ́ède Gabon",
  "GB": "Orílẹ́èdè Gẹ̀ẹ́sì",
  "GD": "Orílẹ́ède Genada",
  "GE": "Orílẹ́ède Gọgia",
  "GF": "Orílẹ́ède Firenṣi Guana",
  "GG": "Guernsey",
  "GH": "Orílẹ́ède Gana",
  "GI": "Orílẹ́ède Gibaratara",
  "GL": "Orílẹ́ède Gerelandi",
  "GM": "Orílẹ́ède Gambia",
  "GN": "Orílẹ́ède Gene",
  "GP": "Orílẹ́ède Gadelope",
  "GQ": "Orílẹ́ède Ekutoria Gini",
  "GR": "Orílẹ́ède Geriisi",
  "GS": "Gúúsù Georgia àti Gúúsù Àwọn Erékùsù Sandwich",
  "GT": "Orílẹ́ède Guatemala",
  "GU": "Orílẹ́ède Guamu",
  "GW": "Orílẹ́ède Gene-Busau",
  "GY": "Orílẹ́ède Guyana",
  "Geok": "Georgian Khutsuri",
  "Geor": "Jọ́jíànù",
  "Glag": "Glagolitic",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gotik",
  "Gran": "Grantha",
  "Grek": "Jọ́jíà",
  "Gujr": "Gujaráti",
  "Guru": "Gurumúkhì",
  "HK": "Hong Kong SAR ti Ṣáìnà",
  "HM": "Erékùsù Heard àti Erékùsù McDonald",
  "HN": "Orílẹ́ède Hondurasi",
  "HR": "Orílẹ́ède Kòróátíà",
  "HT": "Orílẹ́ède Haati",
  "HU": "Orílẹ́ède Hungari",
  "Hanb": "Han pẹ̀lú Bopomófò",
  "Hang": "Háńgùlù",
  "Hani": "Háànù",
  "Hano": "Hanunoo",
  "Hans": "tí wọ́n mú rọrùn.",
  "Hant": "Hans àtọwọ́dọ́wọ́",
  "Hatr": "Hatran",
  "Hebr": "Hébérù",
  "Hira": "Hiragánà",
  "Hluw": "Anatolian Hieroglyphs",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "ìlànà àfọwọ́kọ ará Jàpánù",
  "Hung": "Ara Hungary atijọ",
  "IC": "Ẹrékùsù Kánárì",
  "ID": "Orílẹ́ède Indonesia",
  "IE": "Orílẹ́ède Ailandi",
  "IL": "Orílẹ́ède Iserẹli",
  "IM": "Isle of Man",
  "IN": "Orílẹ́ède India",
  "IO": "Orílẹ́ède Etíkun Índíánì ti Ìlú Bírítísì",
  "IQ": "Orílẹ́ède Iraki",
  "IR": "Orílẹ́ède Irani",
  "IS": "Orílẹ́ède Aṣilandi",
  "IT": "Orílẹ́ède Itáli",
  "Inds": "Indus",
  "Ital": "Italic atijọ",
  "JE": "Jersey",
  "JM": "Orílẹ́ède Jamaika",
  "JO": "Orílẹ́ède Jọdani",
  "JP": "Orílẹ́ède Japani",
  "Jamo": "Jamo",
  "Java": "Ede Javanese",
  "Jpan": "èdè jàpáànù",
  "Jurc": "Jurchen",
  "KE": "Orílẹ́ède Kenya",
  "KG": "Orílẹ́ède Kuriṣisitani",
  "KH": "Orílẹ́ède Kàmùbódíà",
  "KI": "Orílẹ́ède Kiribati",
  "KM": "Orílẹ́ède Kòmòrósì",
  "KN": "Orílẹ́ède Kiiti ati Neefi",
  "KP": "Orílẹ́ède Guusu Kọria",
  "KR": "Orílẹ́ède Ariwa Kọria",
  "KW": "Orílẹ́ède Kuweti",
  "KY": "Orílẹ́ède Etíokun Kámánì",
  "KZ": "Orílẹ́ède Kaṣaṣatani",
  "Kali": "Kayah Li",
  "Kana": "Katakánà",
  "Khar": "Kharoshthi",
  "Khmr": "Kẹmẹ̀",
  "Khoj": "Khojki",
  "Kits": "Iwe afọwọkọ kekere ti Khitan",
  "Knda": "Kanada",
  "Kore": "Kóríà",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Orílẹ́ède Laosi",
  "LB": "Orílẹ́ède Lebanoni",
  "LC": "Orílẹ́ède Luṣia",
  "LI": "Orílẹ́ède Lẹṣitẹnisiteni",
  "LK": "Orílẹ́ède Siri Lanka",
  "LR": "Orílẹ́ède Laberia",
  "LS": "Orílẹ́ède Lesoto",
  "LT": "Orílẹ́ède Lituania",
  "LU": "Orílẹ́ède Lusemogi",
  "LV": "Orílẹ́ède Latifia",
  "LY": "Orílẹ́ède Libiya",
  "Lana": "Lanna",
  "Laoo": "Láò",
  "Latf": "Fraktur Latin",
  "Latg": "Gaelic Latin",
  "Latn": "Èdè Látìn",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Laini A",
  "Linb": "Laini B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydian",
  "MA": "Orílẹ́ède Moroko",
  "MC": "Orílẹ́ède Monako",
  "MD": "Orílẹ́ède Modofia",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Orílẹ́ède Madasika",
  "MH": "Orílẹ́ède Etikun Máṣali",
  "MI": "Awọn erekusu Midway",
  "MK": "Àríwá Macedonia",
  "ML": "Orílẹ́ède Mali",
  "MM": "Orílẹ́ède Manamari",
  "MN": "Orílẹ́ède Mogolia",
  "MO": "Macao SAR ti Ṣáìnà",
  "MP": "Orílẹ́ède Etikun Guusu Mariana",
  "MQ": "Orílẹ́ède Matinikuwi",
  "MR": "Orílẹ́ède Maritania",
  "MS": "Orílẹ́ède Motserati",
  "MT": "Orílẹ́ède Malata",
  "MU": "Orílẹ́ède Maritiusi",
  "MV": "Orílẹ́ède Maladifi",
  "MW": "Orílẹ́ède Malawi",
  "MX": "Orílẹ́ède Mesiko",
  "MY": "Orílẹ́ède Malasia",
  "MZ": "Orílẹ́ède Moṣamibiku",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "Maero hieroglyphs",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Egun Meroitic",
  "Mero": "Meroitic",
  "Mlym": "Málàyálámù",
  "Modi": "Modi",
  "Mong": "Mòngólíà",
  "Moon": "Osupa",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Myánmarà",
  "NA": "Orílẹ́ède Namibia",
  "NC": "Orílẹ́ède Kaledonia Titun",
  "NE": "Orílẹ́ède Nàìjá",
  "NF": "Orílẹ́ède Etikun Nọ́úfókì",
  "NG": "Orilẹ̀-èdè Nàìjíríà",
  "NI": "Orílẹ́ède NIkaragua",
  "NL": "Orílẹ́ède Nedalandi",
  "NO": "Orílẹ́ède Nọọwii",
  "NP": "Orílẹ́ède Nepa",
  "NR": "Orílẹ́ède Nauru",
  "NT": "Eedu didoju",
  "NU": "Orílẹ́ède Niue",
  "NZ": "Orílẹ́ède ṣilandi Titun",
  "Nand": "Nandinagari",
  "Narb": "Ara Ariwa Ariwa Atijo",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Orílẹ́ède Ọọma",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Òdíà",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Orílẹ́ède Panama",
  "PC": "Ilẹ igbẹkẹle Pacific Islands",
  "PE": "Orílẹ́ède Peru",
  "PF": "Orílẹ́ède Firenṣi Polinesia",
  "PG": "Orílẹ́ède Paapu ti Giini",
  "PH": "Orílẹ́ède filipini",
  "PK": "Orílẹ́ède Pakisitan",
  "PL": "Orílẹ́ède Polandi",
  "PM": "Orílẹ́ède Pẹẹri ati mikuloni",
  "PN": "Orílẹ́ède Pikarini",
  "PR": "Orílẹ́ède Pọto Riko",
  "PS": "Agbègbè Palẹsítíànù",
  "PT": "Orílẹ́ède Pọ́túgà",
  "PU": "AMẸRIKA Oriṣiriṣi Awọn erekusu Pacific",
  "PW": "Orílẹ́ède Paalu",
  "PY": "Orílẹ́ède Paraguye",
  "PZ": "Agbegbe Canal Panama",
  "Palm": "Palmyrene",
  "Pauc": "Pau Cin Hau",
  "Perm": "Atijọ Permic",
  "Phag": "Phags-pa",
  "Phli": "Akọsilẹ Pahlavi",
  "Phlp": "Olorin Pahlavi",
  "Phlv": "Iwe Pahlavi",
  "Phnx": "Fenisiani",
  "Plrd": "Pollard Phonetic",
  "Prti": "Apaniyan Apanilẹkọ",
  "QA": "Orílẹ́ède Kota",
  "QO": "Agbègbè Oceania",
  "Qaag": "Zawgyi",
  "RE": "Orílẹ́ède Riuniyan",
  "RO": "Orílẹ́ède Romaniya",
  "RS": "Serbia",
  "RU": "Orílẹ́ède Rọṣia",
  "RW": "Orílẹ́ède Ruwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Orílẹ́ède Saudi Arabia",
  "SB": "Orílẹ́ède Etikun Solomoni",
  "SC": "Orílẹ́ède seṣẹlẹsi",
  "SD": "Orílẹ́ède Sudani",
  "SE": "Orílẹ́ède Swidini",
  "SG": "Orílẹ́ède Singapo",
  "SH": "Orílẹ́ède Hẹlena",
  "SI": "Orílẹ́ède Silofania",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Orílẹ́ède Silofakia",
  "SL": "Orílẹ́ède Siria looni",
  "SM": "Orílẹ́ède Sani Marino",
  "SN": "Orílẹ́ède Sẹnẹga",
  "SO": "Orílẹ́ède Somalia",
  "SR": "Orílẹ́ède Surinami",
  "SS": "Gúúsù Sudan",
  "ST": "Orílẹ́ède Sao tomi ati piriiṣipi",
  "SU": "Union of Soviet Socialist Republics",
  "SV": "Orílẹ́ède Ẹẹsáfádò",
  "SX": "Sint Maarten",
  "SY": "Orílẹ́ède Siria",
  "SZ": "Orílẹ́ède Saṣiland",
  "Samr": "Ara Samaria",
  "Sara": "Sarati",
  "Sarb": "Atijọ Arabian South",
  "Saur": "Saurashtra",
  "Sgnw": "Iforukọsilẹ",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddhamu",
  "Sind": "Khudawadi",
  "Sinh": "Sìnhálà",
  "Sogd": "Sogdian",
  "Sogo": "Atijọ Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundanese",
  "Sylo": "Syloti Nagri",
  "Syrc": "Síríákì",
  "Syre": "Estrangelo Syriac",
  "Syrj": "Western Syriac",
  "Syrn": "Orile-ede Syriac",
  "TA": "Tristan da Kunha",
  "TC": "Orílẹ́ède Tọọki ati Etikun Kakọsi",
  "TD": "Orílẹ́ède ṣààdì",
  "TF": "Agbègbè Gúúsù Faranṣé",
  "TG": "Orílẹ́ède Togo",
  "TH": "Orílẹ́ède Tailandi",
  "TJ": "Orílẹ́ède Takisitani",
  "TK": "Orílẹ́ède Tokelau",
  "TL": "Orílẹ́ède ÌlàOòrùn Tímọ̀",
  "TM": "Orílẹ́ède Tọọkimenisita",
  "TN": "Orílẹ́ède Tuniṣia",
  "TO": "Orílẹ́ède Tonga",
  "TR": "Orílẹ́ède Tọọki",
  "TT": "Orílẹ́ède Tirinida ati Tobaga",
  "TV": "Orílẹ́ède Tufalu",
  "TW": "Orílẹ́ède Taiwani",
  "TZ": "Orílẹ́ède Tàǹsáníà",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Titun Tai Lue",
  "Taml": "Támílì",
  "Tang": "Tangut",
  "Tavt": "Tai Vi Viett",
  "Telu": "Télúgù",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Taana",
  "Thai": "Thai",
  "Tibt": "Tíbétán",
  "Tirh": "Tirhuta",
  "UA": "Orílẹ́ède Ukarini",
  "UG": "Orílẹ́ède Uganda",
  "UM": "Àwọn Erékùsù Kékèké Agbègbè US",
  "UN": "Ìṣọ̀kan àgbáyé",
  "US": "Orílẹ̀-èdè Amẹrikà",
  "UY": "Orílẹ́ède Nruguayi",
  "UZ": "Orílẹ́ède Nṣibẹkisitani",
  "Ugar": "Ugaritiki",
  "VA": "Ìlú Vatican",
  "VC": "Orílẹ́ède Fisẹnnti ati Genadina",
  "VD": "Ariwa Vietnam",
  "VE": "Orílẹ́ède Fẹnẹṣuẹla",
  "VG": "Orílẹ́ède Etíkun Fágínì ti ìlú Bírítísì",
  "VI": "Orílẹ́ède Etikun Fagini ti Amẹrika",
  "VN": "Orílẹ́ède Fẹtinami",
  "VU": "Orílẹ́ède Faniatu",
  "Vaii": "Vai",
  "Visp": "Ọrọ Afihan",
  "WF": "Orílẹ́ède Wali ati futuna",
  "WK": "Wake Island",
  "WS": "Orílẹ́ède Samọ",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudo-Accents",
  "XB": "Pseudo-Bidi",
  "XK": "Kòsófò",
  "Xpeo": "Persia atijọ",
  "Xsux": "Sumero-Akkadian Kuniforimu",
  "YD": "Awọn eniyan Democratic Republic of Yemen",
  "YE": "Orílẹ́ède yemeni",
  "YT": "Orílẹ́ède Mayote",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "Gúúṣù Áfíríkà",
  "ZM": "Orílẹ́ède ṣamibia",
  "ZW": "Orílẹ́ède ṣimibabe",
  "ZZ": "Àgbègbè àìmọ̀",
  "Zanb": "Square Zanabazar",
  "Zinh": "Jegun",
  "Zmth": "Àmì Ìṣèsìrò",
  "Zsye": "Émójì",
  "Zsym": "Àwọn àmì",
  "Zxxx": "Aikọsilẹ",
  "Zyyy": "Wọ́pọ̀",
  "Zzzz": "Ìṣọwọ́kọ̀wé àìmọ̀",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Èdè Afrikani",
  "af_NA": "Èdè Afrikani (Orílẹ́ède Namibia)",
  "af_ZA": "Èdè Afrikani (Orílẹ́ède Ariwa Afirika)",
  "afa": "Ede Afro-Asiatic",
  "afh": "Afrihili",
  "agq": "Ágẹ̀ẹ̀mù",
  "ain": "Ainu",
  "ak": "Èdè Akani",
  "ak_GH": "Èdè Akani (Orílẹ́ède Gana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Ede Algonquian",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Èdè Amariki",
  "am_ET": "Èdè Amariki (Orílẹ́ède Etopia)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "apa": "Ede Apache",
  "ar": "Èdè Árábìkì",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Èdè Arabiki (Orílẹ́ède Ẹmirate ti Awọn Arabu)",
  "ar_BH": "Èdè Arabiki (Orílẹ́ède Báránì)",
  "ar_DJ": "Èdè Arabiki (Orílẹ́ède Díbọ́ótì)",
  "ar_DZ": "Èdè Arabiki (Orílẹ́ède Àlùgèríánì)",
  "ar_EG": "Èdè Arabiki (Orílẹ́ède Égípítì)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Èdè Arabiki (Orílẹ́ède Eritira)",
  "ar_IL": "Èdè Arabiki (Orílẹ́ède Iserẹli)",
  "ar_IQ": "Èdè Arabiki (Orílẹ́ède Iraki)",
  "ar_JO": "Èdè Arabiki (Orílẹ́ède Jọdani)",
  "ar_KM": "Èdè Arabiki (Orílẹ́ède Kòmòrósì)",
  "ar_KW": "Èdè Arabiki (Orílẹ́ède Kuweti)",
  "ar_LB": "Èdè Arabiki (Orílẹ́ède Lebanoni)",
  "ar_LY": "Èdè Arabiki (Orílẹ́ède Libiya)",
  "ar_MA": "Èdè Arabiki (Orílẹ́ède Moroko)",
  "ar_MR": "Èdè Arabiki (Orílẹ́ède Maritania)",
  "ar_OM": "Èdè Arabiki (Orílẹ́ède Ọọma)",
  "ar_PS": "Èdè Arabiki (Orílẹ́ède Iwọorun Pakisitian ati Gaṣa)",
  "ar_QA": "Èdè Arabiki (Orílẹ́ède Kota)",
  "ar_SA": "Èdè Arabiki (Orílẹ́ède Saudi Arabia)",
  "ar_SD": "Èdè Arabiki (Orílẹ́ède Sudani)",
  "ar_SO": "Èdè Arabiki (Orílẹ́ède Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Èdè Arabiki (Orílẹ́ède Siria)",
  "ar_TD": "Èdè Arabiki (Orílẹ́ède ṣààdì)",
  "ar_TN": "Èdè Arabiki (Orílẹ́ède Tuniṣia)",
  "ar_YE": "Èdè Arabiki (Orílẹ́ède yemeni)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "ars": "Ede Arabu Najdi",
  "art": "Ede Oríktificial",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Ti Assam",
  "as_IN": "Ti Assam (Orílẹ́ède India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "ath": "Ede Athapascan",
  "aus": "Ede Ọstrelia",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Èdè Azerbaijani",
  "az_AZ": "Èdè Azerbaijani (Orílẹ́ède Asẹ́bájánì)",
  "az_Arab": "Azerbaijani (Arabu)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bad": "Banda",
  "bai": "Ede Bamileke",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bat": "Ede Baltic",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Èdè Belarusi",
  "be_BY": "Èdè Belarusi (Orílẹ́ède Bélárúsì)",
  "bej": "Beja",
  "bem": "Béḿbà",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bẹ́nà",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Èdè Bugaria",
  "bg_BG": "Èdè Bugaria (Orílẹ́ède Bùùgáríà)",
  "bgn": "Balochi Oorun",
  "bh": "Èdè Bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Báḿbàrà",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Èdè Bengali",
  "bn_BD": "Èdè Bengali (Orílẹ́ède Bángáládésì)",
  "bn_IN": "Èdè Bengali (Orílẹ́ède India)",
  "bnt": "Bantu",
  "bo": "Tibetán",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Èdè Bretoni",
  "br_FR": "Èdè Bretoni (Orílẹ́ède Faranse)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bódò",
  "bs": "Èdè Bosnia",
  "bs_BA": "Èdè Bosnia (Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Èdè Catala",
  "ca_AD": "Èdè Catala (Orílẹ́ède Ààndórà)",
  "ca_ES": "Èdè Catala (Orílẹ́ède Sipani)",
  "ca_FR": "Èdè Catala (Orílẹ́ède Faranse)",
  "ca_IT": "Èdè Catala (Orílẹ́ède Italiyi)",
  "cad": "Caddo",
  "cai": "Ede Indian Central",
  "car": "Carib",
  "cau": "Ede Caucasian",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cel": "Ede Selitik",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Shẹ́rókiì",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Ààrin Gbùngbùn Kurdish",
  "cmc": "Ede Chamic",
  "co": "Corsican",
  "cop": "Coptic",
  "cpe": "Ede Gẹẹsi Creole tabi Pidgin",
  "cpf": "French-Creole tabi Pidgin",
  "cpp": "Ede Creole tabi Pidgin ti o jẹ ede Pọtugalii",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "crp": "Creole tabi Pidgin",
  "crs": "French Seselwa Creole",
  "cs": "Èdè seeki",
  "cs_CZ": "Èdè seeki (Orílẹ́ède ṣẹ́ẹ́kì)",
  "csb": "Kashubian",
  "cu": "Síláfííkì Ilé Ìjọ́sìn",
  "cus": "Ede Cushitic",
  "cv": "Chuvash",
  "cy": "Èdè Welshi",
  "cy_GB": "Èdè Welshi (Orílẹ́ède Omobabirin)",
  "da": "Èdè Ilẹ̀ Denmark",
  "da_DK": "Èdè Ilẹ̀ Denmark (Orílẹ́ède Dẹ́mákì)",
  "da_GL": "Èdè Ilẹ̀ Denmark (Orílẹ́ède Gerelandi)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Táítà",
  "day": "Dayak",
  "de": "Èdè Jámánì",
  "de_AT": "Èdè Jámánì (Ọ́síríà )",
  "de_BE": "Èdè Ilẹ̀ Gemani (Orílẹ́ède Bégíọ́mù)",
  "de_CH": "Èdè Ilẹ̀ Jámánì (Orílẹ́ède swítsàlandì)",
  "de_DE": "Èdè Ilẹ̀ Gemani (Orílẹ́ède Gemani)",
  "de_LI": "Èdè Ilẹ̀ Gemani (Orílẹ́ède Lẹṣitẹnisiteni)",
  "de_LU": "Èdè Ilẹ̀ Gemani (Orílẹ́ède Lusemogi)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Ṣárúmà",
  "doi": "Dogri",
  "dra": "Ede Dravidian",
  "dsb": "Ṣobíànù Ìpìlẹ̀",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Ẹmbù",
  "ee": "Ewè",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Èdè Giriki",
  "el_CY": "Èdè Giriki (Orílẹ́ède Kúrúsì)",
  "el_GR": "Èdè Giriki (Orílẹ́ède Geriisi)",
  "elx": "Elamite",
  "en": "Èdè Gẹ̀ẹ́sì",
  "en_AG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Ààntígúà àti Báríbúdà)",
  "en_AI": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Ààngúlílà)",
  "en_AS": "Èdè Gẹ̀ẹ́sì (Sámóánì ti Orílẹ́ède Àméríkà)",
  "en_AU": "Èdè Gẹ̀ẹ́sì (órílẹ̀-èdè Ọsirélíà)",
  "en_BB": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Bábádósì)",
  "en_BE": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Bégíọ́mù)",
  "en_BM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Bémúdà)",
  "en_BS": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Bàhámásì)",
  "en_BW": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Bọ̀tìsúwánà)",
  "en_BZ": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Bèlísẹ̀)",
  "en_CA": "Èdè Gẹ̀ẹ́sì (Orílẹ̀-èdè Kánádà)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etíokun Kùúkù)",
  "en_CM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Kamerúúnì)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Dòmíníkà)",
  "en_Dsrt": "Gẹẹsi (Deseret)",
  "en_ER": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Eritira)",
  "en_FJ": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Fiji)",
  "en_FK": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etikun Fakalandi)",
  "en_FM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Makoronesia)",
  "en_GB": "Èdè òyìnbó Gẹ̀ẹ́sì",
  "en_GD": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Genada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Gana)",
  "en_GI": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Gibaratara)",
  "en_GM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Gambia)",
  "en_GU": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Guamu)",
  "en_GY": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Ailandi)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède India)",
  "en_IO": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etíkun Índíánì ti Ìlú Bírítísì)",
  "en_JE": "English (Jersey)",
  "en_JM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Jamaika)",
  "en_KE": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Kenya)",
  "en_KI": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Kiribati)",
  "en_KN": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Kiiti ati Neefi)",
  "en_KY": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etíokun Kámánì)",
  "en_LC": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Luṣia)",
  "en_LR": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Laberia)",
  "en_LS": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Lesoto)",
  "en_MG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Madasika)",
  "en_MH": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etikun Máṣali)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etikun Guusu Mariana)",
  "en_MS": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Motserati)",
  "en_MT": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Malata)",
  "en_MU": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Maritiusi)",
  "en_MW": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Malawi)",
  "en_MY": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Malasia)",
  "en_NA": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Namibia)",
  "en_NF": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etikun Nọ́úfókì)",
  "en_NG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Nàìjíríà)",
  "en_NR": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Nauru)",
  "en_NU": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Niue)",
  "en_NZ": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède ṣilandi Titun)",
  "en_PG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Paapu ti Giini)",
  "en_PH": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède filipini)",
  "en_PK": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Pakisitan)",
  "en_PN": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Pikarini)",
  "en_PR": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Pọto Riko)",
  "en_PW": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Paalu)",
  "en_RW": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Ruwanda)",
  "en_SB": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etikun Solomoni)",
  "en_SC": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède seṣẹlẹsi)",
  "en_SD": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Sudani)",
  "en_SG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Singapo)",
  "en_SH": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Hẹlena)",
  "en_SL": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Siria looni)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Saṣiland)",
  "en_TC": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Tọọki ati Etikun Kakọsi)",
  "en_TK": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Tokelau)",
  "en_TO": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Tonga)",
  "en_TT": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Tirinida ati Tobaga)",
  "en_TV": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Tufalu)",
  "en_TZ": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Tanṣania)",
  "en_UG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Èdè Gẹ̀ẹ́sì (US)",
  "en_VC": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Fisẹnnti ati Genadina)",
  "en_VG": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etíkun Fágínì ti ìlú Bírítísì)",
  "en_VI": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Etikun Fagini ti Amẹrika)",
  "en_VU": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Faniatu)",
  "en_WS": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Samọ)",
  "en_ZA": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède Ariwa Afirika)",
  "en_ZM": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède ṣamibia)",
  "en_ZW": "Èdè Gẹ̀ẹ́sì (Orílẹ́ède ṣimibabe)",
  "enm": "Middle English",
  "eo": "Èdè Esperanto",
  "es": "Èdè Sípáníìṣì",
  "es_419":
      "Èdè Sípáníìṣì (orílẹ̀-èdè Látìn-Amẹ́ríkà) ( Èdè Sípáníìshì (Látìn-Amẹ́ríkà)",
  "es_AR": "Èdè Sipanisi (Orílẹ́ède Agentínà)",
  "es_BO": "Èdè Sipanisi (Orílẹ́ède Bọ̀lífíyà)",
  "es_CL": "Èdè Sipanisi (Orílẹ́ède ṣílè)",
  "es_CO": "Èdè Sipanisi (Orílẹ́ède Kòlómíbìa)",
  "es_CR": "Èdè Sipanisi (Orílẹ́ède Kuusita Ríkà)",
  "es_CU": "Èdè Sipanisi (Orílẹ́ède Kúbà)",
  "es_DO": "Èdè Sipanisi (Orilẹ́ède Dòmíníkánì)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Èdè Sipanisi (Orílẹ́ède Ekuádò)",
  "es_ES": "Èdè Sípáníìṣì (orílẹ̀-èdè Yúróòpù)",
  "es_GQ": "Èdè Sipanisi (Orílẹ́ède Ekutoria Gini)",
  "es_GT": "Èdè Sipanisi (Orílẹ́ède Guatemala)",
  "es_HN": "Èdè Sipanisi (Orílẹ́ède Hondurasi)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Èdè Sípáníìṣì (orílẹ̀-èdè Mẹ́síkò)",
  "es_NI": "Èdè Sipanisi (Orílẹ́ède NIkaragua)",
  "es_PA": "Èdè Sipanisi (Orílẹ́ède Panama)",
  "es_PE": "Èdè Sipanisi (Orílẹ́ède Peru)",
  "es_PH": "Èdè Sipanisi (Orílẹ́ède filipini)",
  "es_PR": "Èdè Sipanisi (Orílẹ́ède Pọto Riko)",
  "es_PY": "Èdè Sipanisi (Orílẹ́ède Paraguye)",
  "es_SV": "Èdè Sipanisi (Orílẹ́ède Ẹẹsáfádò)",
  "es_US": "Èdè Sipanisi (Orílẹ́ède Orilẹede Amerika)",
  "es_UY": "Èdè Sipanisi (Orílẹ́ède Nruguayi)",
  "es_VE": "Èdè Sipanisi (Orílẹ́ède Fẹnẹṣuẹla)",
  "esu": "Central Yupik",
  "et": "Èdè Estonia",
  "et_EE": "Èdè Estonia (Orílẹ́ède Esitonia)",
  "eu": "Èdè Baski",
  "eu_ES": "Èdè Baski (Orílẹ́ède Sipani)",
  "ewo": "Èwóǹdò",
  "ext": "Extremaduran",
  "fa": "Èdè Pasia",
  "fa_AF": "Èdè Pasia (Orílẹ́ède Àfùgànístánì)",
  "fa_IR": "Èdè Pasia (Orílẹ́ède Irani)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Èdè Fúlàní",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Èdè Finisi",
  "fi_FI": "Èdè Finisi (Orílẹ́ède Filandi)",
  "fil": "Èdè Filipino",
  "fit": "Tornedalen Finnish",
  "fiu": "Ede Finno-Ugrian",
  "fj": "Fijian",
  "fo": "Èdè Faroesi",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Èdè Faransé",
  "fr_BE": "Èdè Faransé (Orílẹ́ède Bégíọ́mù)",
  "fr_BF": "Èdè Faransé (Orílẹ́ède Bùùkíná Fasò)",
  "fr_BI": "Èdè Faransé (Orílẹ́ède Bùùrúndì)",
  "fr_BJ": "Èdè Faransé (Orílẹ́ède Bẹ̀nẹ̀)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Èdè Faransé (orílẹ̀-èdè Kánádà)",
  "fr_CD": "Èdè Faransé (Orilẹ́ède Kóngò)",
  "fr_CF": "Èdè Faransé (Orílẹ́ède Àrin gùngun Áfíríkà)",
  "fr_CG": "Èdè Faransé (Orílẹ́ède Kóngò)",
  "fr_CH": "Èdè Faranṣé (Súwísàlaǹdì)",
  "fr_CI": "Èdè Faransé (Orílẹ́ède Kóútè forà)",
  "fr_CM": "Èdè Faransé (Orílẹ́ède Kamerúúnì)",
  "fr_DJ": "Èdè Faransé (Orílẹ́ède Díbọ́ótì)",
  "fr_DZ": "Èdè Faransé (Orílẹ́ède Àlùgèríánì)",
  "fr_FR": "Èdè Faransé (Orílẹ́ède Faranse)",
  "fr_GA": "Èdè Faransé (Orílẹ́ède Gabon)",
  "fr_GF": "Èdè Faransé (Orílẹ́ède Firenṣi Guana)",
  "fr_GN": "Èdè Faransé (Orílẹ́ède Gene)",
  "fr_GP": "Èdè Faransé (Orílẹ́ède Gadelope)",
  "fr_GQ": "Èdè Faransé (Orílẹ́ède Ekutoria Gini)",
  "fr_HT": "Èdè Faransé (Orílẹ́ède Haati)",
  "fr_KM": "Èdè Faransé (Orílẹ́ède Kòmòrósì)",
  "fr_LU": "Èdè Faransé (Orílẹ́ède Lusemogi)",
  "fr_MA": "Èdè Faransé (Orílẹ́ède Moroko)",
  "fr_MC": "Èdè Faransé (Orílẹ́ède Monako)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Èdè Faransé (Orílẹ́ède Madasika)",
  "fr_ML": "Èdè Faransé (Orílẹ́ède Mali)",
  "fr_MQ": "Èdè Faransé (Orílẹ́ède Matinikuwi)",
  "fr_MR": "Èdè Faransé (Orílẹ́ède Maritania)",
  "fr_MU": "Èdè Faransé (Orílẹ́ède Maritiusi)",
  "fr_NC": "Èdè Faransé (Orílẹ́ède Kaledonia Titun)",
  "fr_NE": "Èdè Faransé (Orílẹ́ède Nàìjá)",
  "fr_PF": "Èdè Faransé (Orílẹ́ède Firenṣi Polinesia)",
  "fr_PM": "Èdè Faransé (Orílẹ́ède Pẹẹri ati mikuloni)",
  "fr_RE": "Èdè Faransé (Orílẹ́ède Riuniyan)",
  "fr_RW": "Èdè Faransé (Orílẹ́ède Ruwanda)",
  "fr_SC": "Èdè Faransé (Orílẹ́ède seṣẹlẹsi)",
  "fr_SN": "Èdè Faransé (Orílẹ́ède Sẹnẹga)",
  "fr_SY": "Èdè Faransé (Orílẹ́ède Siria)",
  "fr_TD": "Èdè Faransé (Orílẹ́ède ṣààdì)",
  "fr_TG": "Èdè Faransé (Orílẹ́ède Togo)",
  "fr_TN": "Èdè Faransé (Orílẹ́ède Tuniṣia)",
  "fr_VU": "Èdè Faransé (Orílẹ́ède Faniatu)",
  "fr_WF": "Èdè Faransé (Orílẹ́ède Wali ati futuna)",
  "fr_YT": "Èdè Faransé (Orílẹ́ède Mayote)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Firiúlíànì",
  "fy": "Èdè Frisia",
  "fy_NL": "Èdè Frisia (Orílẹ́ède Nedalandi)",
  "ga": "Èdè Ireland",
  "ga_IE": "Èdè Ireland (Orílẹ́ède Ailandi)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Èdè Gaelik ti Ilu Scotland",
  "gd_GB": "Èdè Gaelik ti Ilu Scotland (Orílẹ́ède Omobabirin)",
  "gem": "Ede Jamani",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Èdè Galicia",
  "gl_ES": "Èdè Galicia (Orílẹ́ède Sipani)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Èdè Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Súwísì ti Jámánì",
  "gu": "Èdè Gujarati",
  "gu_IN": "Èdè Gujarati (Orílẹ́ède India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Máǹkì",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Èdè Hausa",
  "ha_GH": "Èdè Hausa (Orílẹ́ède Gana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Èdè Hausa (Orílẹ́ède Nàìjá)",
  "ha_NG": "Èdè Hausa (Orílẹ́ède Nàìjíríà)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Èdè Heberu",
  "he_IL": "Èdè Heberu (Orílẹ́ède Iserẹli)",
  "hi": "Èdè Híńdì",
  "hi_IN": "Èdè Hindi (Orílẹ́ède India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Èdè Kroatia",
  "hr_BA": "Èdè Kroatia (Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà)",
  "hr_HR": "Èdè Kroatia (Orílẹ́ède Kòróátíà)",
  "hsb": "Sorbian Apá Òkè",
  "hsn": "Xiang Chinese",
  "ht": "Haitian Creole",
  "hu": "Èdè Hungaria",
  "hu_HU": "Èdè Hungaria (Orílẹ́ède Hungari)",
  "hup": "Hupa",
  "hy": "Èdè Ile Armenia",
  "hy_AM": "Èdè Ile Armenia (Orílẹ́ède Améníà)",
  "hz": "Herero",
  "ia": "Èdè pipo",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Èdè Indonéṣíà",
  "id_ID": "Èdè Indonasia (Orílẹ́ède Indonesia)",
  "ie": "Iru Èdè",
  "ig": "Èdè Yíbò",
  "ig_NG": "Èdè Ibo (Orílẹ́ède Nàìjíríà)",
  "ii": "Ṣíkuán Yì",
  "ii_CN": "Sichuan Yi (China)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Ede itọkasi",
  "ine": "Odè Indo-European",
  "inh": "Ingush",
  "io": "Ido",
  "ira": "Ede Ara Iran",
  "iro": "Ede Iroquoian",
  "is": "Èdè Icelandic",
  "is_IS": "Èdè Icelandic (Orílẹ́ède Aṣilandi)",
  "it": "Èdè Ítálì",
  "it_CH": "Èdè Italiani (Orílẹ́ède switiṣilandi)",
  "it_IT": "Èdè Italiani (Orílẹ́ède Italiyi)",
  "it_SM": "Èdè Italiani (Orílẹ́ède Sani Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Èdè Jàpáànù",
  "ja_JP": "Èdè Japanisi (Orílẹ́ède Japani)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ńgòmbà",
  "jmc": "Máṣámè",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Èdè Javanasi",
  "ka": "Èdè Georgia",
  "ka_GE": "Èdè Georgia (Orílẹ́ède Gọgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabilè",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Káńbà",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Mákondé",
  "kea": "Kabufadíánù",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Ede Khoisan",
  "kho": "Khotanese",
  "khq": "Koira Ṣíínì",
  "khw": "Khowar",
  "ki": "Kíkúyù",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kaṣakì",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kàkó",
  "kl": "Kalaalísùtì",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kálẹnjín",
  "km": "Èdè kameri",
  "km_KH": "Èdè kameri (Orílẹ́ède Kàmùbódíà)",
  "kmb": "Kimbundu",
  "kn": "Èdè Kannada",
  "kn_IN": "Èdè Kannada (Orílẹ́ède India)",
  "ko": "Èdè Kòríà",
  "ko_KP": "Èdè Koria (Orílẹ́ède Guusu Kọria)",
  "ko_KR": "Èdè Koria (Orílẹ́ède Ariwa Kọria)",
  "koi": "Komi-Permyak",
  "kok": "Kónkánì",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kaṣímirì",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Ṣáńbálà",
  "ksf": "Báfíà",
  "ksh": "Colognian",
  "ku": "Kọdiṣì",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Kọ́nììṣì",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kírígíìsì",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Èdè Latini",
  "lad": "Ladino",
  "lag": "Láńgì",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Lùṣẹ́mbọ́ọ̀gì",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lákota",
  "lmo": "Lombard",
  "ln": "Lìǹgálà",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Láò",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Apáàríwá Lúrì",
  "lt": "Èdè Lithuania",
  "lt_LT": "Èdè Lithuania (Orílẹ́ède Lituania)",
  "ltg": "Latgalian",
  "lu": "Lúbà-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyíà",
  "lv": "Èdè Latvianu",
  "lv_LV": "Èdè Latvianu (Orílẹ́ède Latifia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Ede Austronesian",
  "mas": "Másáì",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Mérù",
  "mfe": "Morisiyen",
  "mg": "Malagasì",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meeto",
  "mgo": "Métà",
  "mh": "Marshallese",
  "mi": "Màórì",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Ede Oniruuru",
  "mk": "Èdè Macedonia",
  "mk_MK": "Èdè Macedonia (Orílẹ́ède Masidonia)",
  "mkh": "Ede Mon-Khmer",
  "ml": "Málàyálámù",
  "ml_IN": "Malayalam (India)",
  "mn": "Mòngólíà",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Ede Manobo",
  "mo": "Moldavian",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Èdè marathi",
  "mr_IN": "Èdè marathi (Orílẹ́ède India)",
  "mrj": "Western Mari",
  "ms": "Èdè Malaya",
  "ms_BN": "Èdè Malaya (Orílẹ́ède Búrúnẹ́lì)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Èdè Malaya (Orílẹ́ède Malasia)",
  "ms_SG": "Èdè Malaya (Orílẹ́ède Singapo)",
  "mt": "Èdè Malta",
  "mt_MT": "Èdè Malta (Orílẹ́ède Malata)",
  "mua": "Múndàngì",
  "mul": "Ọlọ́pọ̀ èdè",
  "mun": "Ede Munda",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Èdè Bumiisi",
  "my_MM": "Èdè Bumiisi (Orílẹ́ède Manamari)",
  "mye": "Myene",
  "myn": "Ede Mayan",
  "myv": "Erzya",
  "mzn": "Masanderani",
  "na": "Nauru",
  "nah": "Ahudè Nahuatl",
  "nai": "Ede India Ariwa Amerika",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Námà",
  "nb": "Nọ́ọ́wè Bokímàl",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "Àríwá Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Jámánì ìpìlẹ̀",
  "nds_NL": "Dutch Saxon kekere",
  "ne": "Èdè Nepali",
  "ne_IN": "Èdè Nepali (Orílẹ́ède India)",
  "ne_NP": "Èdè Nepali (Orílẹ́ède Nepa)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Ede Niger-Kordofanian",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Èdè Dọ́ọ̀ṣì",
  "nl_AW": "Èdè Duki (Orílẹ́ède Árúbà)",
  "nl_BE": "Èdè Duki (Orílẹ́ède Bégíọ́mù)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Èdè Duki (Orílẹ́ède Nedalandi)",
  "nl_SR": "Èdè Duki (Orílẹ́ède Surinami)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kíwáṣíò",
  "nn": "Nọ́ọ́wè Nínọ̀sìkì",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiembùnù",
  "no": "Èdè Norway",
  "no_NO": "Èdè Norway (Orílẹ́ède Nọọwii)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nub": "Ede Nubian",
  "nus": "Núẹ̀",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Ńyájà",
  "nym": "Nyamwezi",
  "nyn": "Ńyákọ́lè",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Èdè Occitani",
  "oj": "Ojibwa",
  "om": "Òròmọ́",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Òdíà",
  "or_IN": "Oriya (India)",
  "os": "Ọṣẹ́tíìkì",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "oto": "Ede Otomia",
  "pa": "Èdè Punjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Èdè Punjabi (Orílẹ́ède India)",
  "pa_PK": "Èdè Punjabi (Orílẹ́ède Pakisitan)",
  "paa": "Ede Papuan",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pcm": "Pidgin ti Naijiria",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phi": "Ede Philippine",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Èdè Póláǹdì",
  "pl_PL": "Èdè Ilẹ̀ Polandi (Orílẹ́ède Polandi)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "pra": "Ede Prakrit",
  "prg": "Púrúṣíànù",
  "pro": "Old Provençal",
  "ps": "Páshítò",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Èdè Pọtogí",
  "pt_AO": "Èdè Pọtugi (Orílẹ́ède Ààngólà)",
  "pt_BR": "Èdè Pọtogí (Orilẹ̀-èdè Bràsíl)",
  "pt_CV": "Èdè Pọtugi (Orílẹ́ède Etíokun Kápé féndè)",
  "pt_GW": "Èdè Pọtugi (Orílẹ́ède Gene-Busau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Èdè Pọtugi (Orílẹ́ède Moṣamibiku)",
  "pt_PT": "Èdè Pọtogí (orílẹ̀-èdè Yúróòpù)",
  "pt_ST": "Èdè Pọtugi (Orílẹ́ède Sao tomi ati piriiṣipi)",
  "pt_TL": "Èdè Pọtugi (Orílẹ́ède ÌlàOòrùn Tímọ̀)",
  "qu": "Kúẹ́ńjùà",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Rómáǹṣì",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rúńdì",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Èdè Romania",
  "ro_MD": "Èdè Romania (Orílẹ́ède Modofia)",
  "ro_RO": "Èdè Romania (Orílẹ́ède Romaniya)",
  "roa": "Ede iferan",
  "rof": "Róńbò",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Èdè Rọ́ṣíà",
  "ru_BY": "Èdè ̣Rọọsia (Orílẹ́ède Bélárúsì)",
  "ru_KG": "Èdè ̣Rọọsia (Orílẹ́ède Kuriṣisitani)",
  "ru_KZ": "Èdè ̣Rọọsia (Orílẹ́ède Kaṣaṣatani)",
  "ru_MD": "Èdè ̣Rọọsia (Orílẹ́ède Modofia)",
  "ru_RU": "Èdè ̣Rọọsia (Orílẹ́ède Rọṣia)",
  "ru_UA": "Èdè ̣Rọọsia (Orílẹ́ède Ukarini)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Èdè Ruwanda",
  "rw_RW": "Èdè Ruwanda (Orílẹ́ède Ruwanda)",
  "rwk": "Riwa",
  "sa": "Èdè awon ara Indo",
  "sad": "Sandawe",
  "sah": "Sàkíhà",
  "sai": "Ede India ti Guusu Amerika",
  "sal": "Ede Salishan",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Èdè Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "Kurdish Guusu",
  "se": "Apáàríwá Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Ṣẹnà",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Ede Semitic",
  "ses": "Koiraboro Seni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgn": "Ede Ami",
  "sgs": "Samogitian",
  "sh": "Èdè Serbo-Croatiani",
  "sh_BA": "Èdè Serbo-Croatiani (Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà)",
  "shi": "Taṣelíìtì",
  "shi_Latn": "Shilha (Latin)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Èdè Sinhalese",
  "si_LK": "Èdè Sinhalese (Orílẹ́ède Siri Lanka)",
  "sid": "Sidamo",
  "sio": "Ede Siouan",
  "sit": "Ede Sino-Tibet",
  "sk": "Èdè Slovaki",
  "sk_SK": "Èdè Slovaki (Orílẹ́ède Silofakia)",
  "sl": "Èdè Slovenia",
  "sl_SI": "Èdè Slovenia (Orílẹ́ède Silofania)",
  "sla": "Ede Slavic",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Sámóánù",
  "sma": "Southern Sami",
  "smi": "Ede Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Ṣọnà",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Èdè ara Somalia",
  "so_DJ": "Èdè ara Somalia (Orílẹ́ède Díbọ́ótì)",
  "so_ET": "Èdè ara Somalia (Orílẹ́ède Etopia)",
  "so_KE": "Èdè ara Somalia (Orílẹ́ède Kenya)",
  "so_SO": "Èdè ara Somalia (Orílẹ́ède Somalia)",
  "sog": "Sogdien",
  "son": "Songhai",
  "sq": "Èdè Albania",
  "sq_AL": "Èdè Albania (Orílẹ́ède Àlùbàníánì)",
  "sq_MK": "Èdè Albania (Orílẹ́ède Masidonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Èdè Serbia",
  "sr_BA": "Èdè Serbia (Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssa": "Ede Nilo-Saharan",
  "ssy": "Saho",
  "st": "Èdè Sesoto",
  "stq": "Saterland Frisian",
  "su": "Èdè Sudani",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Èdè Suwidiisi",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Èdè Suwidiisi (Orílẹ́ède Filandi)",
  "sv_SE": "Èdè Suwidiisi (Orílẹ́ède Swidini)",
  "sw": "Èdè Swahili",
  "sw_CD": "Congo Swahili",
  "sw_KE": "Èdè Swahili (Orílẹ́ède Kenya)",
  "sw_TZ": "Èdè Swahili (Orílẹ́ède Tanṣania)",
  "sw_UG": "Èdè Swahili (Orílẹ́ède Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Èdè Tamili",
  "ta_IN": "Èdè Tamili (Orílẹ́ède India)",
  "ta_LK": "Èdè Tamili (Orílẹ́ède Siri Lanka)",
  "ta_MY": "Èdè Tamili (Orílẹ́ède Malasia)",
  "ta_SG": "Èdè Tamili (Orílẹ́ède Singapo)",
  "tai": "Tai Ede",
  "tcy": "Tulu",
  "te": "Èdè Telugu",
  "te_IN": "Èdè Telugu (Orílẹ́ède India)",
  "tem": "Timne",
  "teo": "Tẹ́sò",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tàjíìkì",
  "th": "Èdè Tai",
  "th_TH": "Èdè Tai (Orílẹ́ède Tailandi)",
  "ti": "Èdè Tigrinya",
  "ti_ER": "Èdè Tigrinya (Orílẹ́ède Eritira)",
  "ti_ET": "Èdè Tigrinya (Orílẹ́ède Etopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Èdè Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Èdè Klingoni",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tóńgàn",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Èdè Tọọkisi",
  "tr_CY": "Èdè Tọọkisi (Orílẹ́ède Kúrúsì)",
  "tr_TR": "Èdè Tọọkisi (Orílẹ́ède Tọọki)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatarí",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tup": "Ede Tupi",
  "tut": "Ede Altaiki",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawak",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Ààrin Gbùngbùn Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Yúgọ̀",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "Èdè Ukania",
  "uk_UA": "Èdè Ukania (Orílẹ́ède Ukarini)",
  "umb": "Umbundu",
  "und": "Èdè àìmọ̀",
  "ur": "Èdè Udu",
  "ur_IN": "Èdè Udu (Orílẹ́ède India)",
  "ur_PK": "Èdè Udu (Orílẹ́ède Pakisitan)",
  "uz": "Èdè Uzbek",
  "uz_AF": "Èdè Uzbek (Orílẹ́ède Àfùgànístánì)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Èdè Uzbek (Orílẹ́ède Nṣibẹkisitani)",
  "vai": "Vai",
  "vai_Latn": "Vai (Latin)",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Èdè Jetinamu",
  "vi_VN": "Èdè Jetinamu (Orílẹ́ède Fẹtinami)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Fọ́lápùùkù",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Funjo",
  "wa": "Walloon",
  "wae": "Wọsà",
  "wak": "Ede Wakashan",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Ede Sorbian",
  "wo": "Wọ́lọ́ọ̀fù",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Èdè Xhosa",
  "xmf": "Mingrelian",
  "xog": "Ṣógà",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangbẹn",
  "ybb": "Yemba",
  "yi": "Èdè Yiddishi",
  "yo": "Èdè Yorùbá",
  "yo_BJ": "Èdè Yorùbá (Orílẹ́ède Bẹ̀nẹ̀)",
  "yo_NG": "Èdè Yorùbá (Orílẹ́ède Nàìjíríà)",
  "ypk": "Ede Yupik",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "yue_Hans": "Cantonese (Ṣaina ti o rọrun)",
  "yue_Hant": "Cantonese (Ara Ṣaina Ibile)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Àfẹnùkò Támásáìtì ti Mòrókò",
  "zh": "Èdè Mandarin tí wọ́n ń sọ lórílẹ̀-èdè Ṣáínà",
  "zh_CN": "Èdè Mandari (Orílẹ́ède ṣáínà)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Èdè Ìbílẹ̀ Ṣáínà",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Èdè Mandari (Orílẹ́ède Singapo)",
  "zh_TW": "Èdè Mandari (Orílẹ́ède Taiwani)",
  "znd": "Zande",
  "zu": "Èdè Ṣulu",
  "zu_ZA": "Èdè Ṣulu (Orílẹ́ède Ariwa Afirika)",
  "zun": "Zuni",
  "zxx": "Kò sí àkóònú elédè",
  "zza": "Zaza"
};
