const names = {
  "aa": "Afar",
  "ace": "Achinese",
  "ada": "Adangme",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "akk": "акадзкая",
  "alt": "Southern Altai",
  "anp": "Angika",
  "ar_001": "Modern Standard Arabic",
  "arn": "Mapuche",
  "arp": "Arapaho",
  "asa": "Asu",
  "awa": "Awadhi",
  "ban": "Balinese",
  "bas": "Basaa",
  "bem": "Bemba",
  "bez": "Bena",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bm": "Bambara",
  "bo": "Tibetan",
  "brx": "Bodo",
  "bug": "Buginese",
  "byn": "Blin",
  "ca": "каталонская",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cu": "Church Slavic",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "dgr": "Dogrib",
  "dje": "Zarma",
  "dsb": "Lower Sorbian",
  "dua": "Duala",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dz": "Dzongkha",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "efi": "Efik",
  "egy": "стараэгіпецкая",
  "eka": "Ekajuk",
  "el": "грэцкая",
  "ewo": "Ewondo",
  "ff": "Fulah",
  "fil": "тагальская",
  "fj": "Fijian",
  "fon": "Fon",
  "fur": "Friulian",
  "fy": "фрызская",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gor": "Gorontalo",
  "grc": "старагрэцкая",
  "gsw": "Swiss German",
  "gu": "гуяраці",
  "guz": "Gusii",
  "gv": "Manx",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "haw": "Hawaiian",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hsb": "Upper Sorbian",
  "ht": "Haitian",
  "hup": "Hupa",
  "hz": "Herero",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ie": "інтэрлінгве",
  "ig": "Igbo",
  "ii": "Sichuan Yi",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "iu": "Inuktitut",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "kfo": "Koro",
  "kha": "Khasi",
  "khq": "Koyra Chiini",
  "ki": "Kikuyu",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kln": "Kalenjin",
  "km": "Khmer",
  "kmb": "Kimbundu",
  "kn": "каннада",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "kum": "Kumyk",
  "kv": "Komi",
  "kw": "Cornish",
  "ky": "Kyrgyz",
  "lad": "Ladino",
  "lag": "Langi",
  "lb": "Luxembourgish",
  "lez": "Lezghian",
  "lg": "Ganda",
  "li": "Limburgish",
  "lkt": "Lakota",
  "lol": "Mongo",
  "loz": "Lozi",
  "lu": "Luba-Katanga",
  "lua": "Luba-Lulua",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mdf": "Moksha",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "ml": "малаяламская",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "my": "Burmese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "нарвэская букмал",
  "nd": "North Ndebele",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl": "галандская",
  "nmg": "Kwasio",
  "nn": "нарвежская (нюнорск)",
  "nnh": "Ngiemboon",
  "nog": "Nogai",
  "non": "Old Norse",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "ny": "Nyanja",
  "nyn": "Nyankole",
  "oc": "правансальская",
  "oj": "Ojibwa",
  "om": "Oromo",
  "or": "Oriya",
  "os": "Ossetic",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "peo": "Old Persian",
  "phn": "Phoenician",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "qu": "Quechua",
  "quc": "Kʼicheʼ",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rm": "Romansh",
  "rn": "Rundi",
  "rof": "Rombo",
  "root": "Root",
  "rup": "Aromanian",
  "rw": "Kinyarwanda",
  "rwk": "Rwa",
  "sad": "Sandawe",
  "saq": "Samburu",
  "sat": "Santali",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "se": "Northern Sami",
  "seh": "Sena",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sga": "Old Irish",
  "sh": "сербска-харвацкая",
  "shi": "Tachelhit",
  "shn": "Shan",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "snk": "Soninke",
  "so": "самалійская",
  "srn": "Sranan Tongo",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "su": "суданская",
  "suk": "Sukuma",
  "sux": "Sumerian",
  "swb": "Comorian",
  "syr": "Syriac",
  "tem": "Timne",
  "teo": "Teso",
  "tet": "Tetum",
  "tg": "Tajik",
  "tig": "Tigre",
  "tlh": "клінгон",
  "tn": "Tswana",
  "to": "Tongan",
  "tpi": "Tok Pisin",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "umb": "Umbundu",
  "vai": "Vai",
  "ve": "Venda",
  "vo": "Volapük",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "xal": "Kalmyk",
  "xh": "хоса",
  "xog": "Soga",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yo": "Yoruba",
  "yue": "Cantonese",
  "zap": "Zapotec",
  "zgh": "Standard Moroccan Tamazight",
  "zh_Hans": "кітайская (спрошчанае кітайскае)",
  "zh_Hant": "кітайская (традыцыйнае кітайскае)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
