const names = {
  "001": "Bed",
  "002": "Afrika",
  "003": "Norzhamerika",
  "005": "Suamerika",
  "009": "Oseania",
  "011": "Afrika ar Cʼhornôg",
  "013": "Kreizamerika",
  "014": "Afrika ar Reter",
  "015": "Afrika an Norzh",
  "017": "Afrika ar Cʼhreiz",
  "018": "Afrika ar Su",
  "019": "Amerikaoù",
  "021": "Amerika an Norzh",
  "029": "Karib",
  "030": "Azia ar Reter",
  "034": "Azia ar Su",
  "035": "Azia ar Gevred",
  "039": "Europa ar Su",
  "053": "Aostralazia",
  "054": "Melanezia",
  "057": "Rannved Mikronezia",
  "061": "Polinezia",
  "142": "Azia",
  "143": "Azia ar Cʼhreiz",
  "145": "Azia ar Cʼhornôg",
  "150": "Europa",
  "151": "Europa ar Reter",
  "154": "Europa an Norzh",
  "155": "Europa ar Cʼhornôg",
  "202": "Afrika issaharat",
  "419": "Amerika Latin",
  "AC": "Enez Ascension",
  "AD": "Andorra",
  "AE": "Emirelezhioù Arab Unanet",
  "AF": "Afghanistan",
  "AG": "Antigua ha Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antilhez Nederlandat",
  "AO": "Angola",
  "AQ": "Antarktika",
  "AR": "Arcʼhantina",
  "AS": "Samoa Amerikan",
  "AT": "Aostria",
  "AU": "Aostralia",
  "AW": "Aruba",
  "AX": "Inizi Åland",
  "AZ": "Azerbaidjan",
  "Adlm": "adlam",
  "Arab": "arabek",
  "Armi": "arameek impalaerel",
  "Armn": "armenianek",
  "Avst": "avestek",
  "BA": "Bosnia ha Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Karib Nederlandat",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhoutan",
  "BV": "Enez Bouvet",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "balinek",
  "Bamu": "bamounek",
  "Batk": "batak",
  "Beng": "bengali",
  "Bopo": "bopomofo",
  "Brai": "Braille",
  "Bugi": "bougiek",
  "CA": "Kanada",
  "CC": "Inizi Kokoz",
  "CD": "Kongo - Kinshasa",
  "CF": "Republik Kreizafrikan",
  "CG": "Kongo - Brazzaville",
  "CH": "Suis",
  "CI": "Aod an Olifant",
  "CK": "Inizi Cook",
  "CL": "Chile",
  "CM": "Kameroun",
  "CN": "Sina",
  "CO": "Kolombia",
  "CP": "Enez Clipperton",
  "CR": "Costa Rica",
  "CU": "Kuba",
  "CV": "Kab-Glas",
  "CW": "Curaçao",
  "CX": "Enez Christmas",
  "CY": "Kiprenez",
  "CZ": "Tchekia",
  "Cakm": "chakmaek",
  "Cans": "silabennaoueg engenidik unvan Kanada",
  "Cham": "cham",
  "Cher": "cherokee",
  "Copt": "koptek",
  "Cprt": "silabennaoueg kipriek",
  "Cyrl": "kirillek",
  "Cyrs": "kirillek henslavonek",
  "DE": "Alamagn",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Danmark",
  "DM": "Dominica",
  "DO": "Republik Dominikan",
  "DZ": "Aljeria",
  "Deva": "devanagari",
  "Dupl": "berrskriverezh Duployé",
  "EA": "Ceuta ha Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egipt",
  "EH": "Sahara ar Cʼhornôg",
  "ER": "Eritrea",
  "ES": "Spagn",
  "ET": "Etiopia",
  "EU": "Unaniezh Europa",
  "EZ": "takad an euro",
  "Egyp": "hieroglifoù egiptek",
  "Ethi": "etiopek",
  "FI": "Finland",
  "FJ": "Fidji",
  "FK": "Inizi Falkland",
  "FM": "Mikronezia",
  "FO": "Inizi Faero",
  "FR": "Frañs",
  "GA": "Gabon",
  "GB": "Rouantelezh-Unanet",
  "GD": "Grenada",
  "GE": "Jorjia",
  "GF": "Gwiana cʼhall",
  "GG": "Gwernenez",
  "GH": "Ghana",
  "GI": "Jibraltar",
  "GL": "Greunland",
  "GM": "Gambia",
  "GN": "Ginea",
  "GP": "Gwadeloup",
  "GQ": "Ginea ar Cʼheheder",
  "GR": "Gres",
  "GS": "Inizi Georgia ar Su hag Inizi Sandwich ar Su",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Ginea-Bissau",
  "GY": "Guyana",
  "Geor": "jorjianek",
  "Glag": "glagolitek",
  "Goth": "gotek",
  "Grek": "gresianek",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "Hong Kong RMD Sina",
  "HM": "Inizi Heard ha McDonald",
  "HN": "Honduras",
  "HR": "Kroatia",
  "HT": "Haiti",
  "HU": "Hungaria",
  "Hanb": "han gant bopomofo",
  "Hang": "hangeul",
  "Hani": "sinalunioù (han)",
  "Hans": "eeunaet",
  "Hant": "hengounel",
  "Hebr": "hebraek",
  "Hira": "hiragana",
  "Hluw": "hieroglifoù Anatolia",
  "Hrkt": "silabennaouegoù japanek",
  "Hung": "henhungarek",
  "IC": "Inizi Kanariez",
  "ID": "Indonezia",
  "IE": "Iwerzhon",
  "IL": "Israel",
  "IM": "Enez Vanav",
  "IN": "India",
  "IO": "Tiriad breizhveurat Meurvor Indez",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italia",
  "Ital": "henitalek",
  "JE": "Jerzenez",
  "JM": "Jamaika",
  "JO": "Jordania",
  "JP": "Japan",
  "Jamo": "jamo",
  "Java": "javanek",
  "Jpan": "japanek",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Kambodja",
  "KI": "Kiribati",
  "KM": "Komorez",
  "KN": "Saint Kitts ha Nevis",
  "KP": "Korea an Norzh",
  "KR": "Korea ar Su",
  "KW": "Koweit",
  "KY": "Inizi Cayman",
  "KZ": "Kazakstan",
  "Kana": "katakana",
  "Khmr": "khmer",
  "Knda": "kannada",
  "Kore": "koreanek",
  "LA": "Laos",
  "LB": "Liban",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lituania",
  "LU": "Luksembourg",
  "LV": "Latvia",
  "LY": "Libia",
  "Laoo": "laosek",
  "Latg": "latin gouezelek",
  "Latn": "latin",
  "Lyci": "likiek",
  "Lydi": "lidiek",
  "MA": "Maroko",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagaskar",
  "MH": "Inizi Marshall",
  "MK": "Makedonia an Norzh",
  "ML": "Mali",
  "MM": "Myanmar (Birmania)",
  "MN": "Mongolia",
  "MO": "Macau RMD Sina",
  "MP": "Inizi Mariana an Norzh",
  "MQ": "Martinik",
  "MR": "Maouritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Moris",
  "MV": "Maldivez",
  "MW": "Malawi",
  "MX": "Mecʼhiko",
  "MY": "Malaysia",
  "MZ": "Mozambik",
  "Mani": "manikeek",
  "Maya": "hieroglifoù mayaek",
  "Mlym": "malayalam",
  "Mong": "mongolek",
  "Mymr": "myanmar",
  "NA": "Namibia",
  "NC": "Kaledonia Nevez",
  "NE": "Niger",
  "NF": "Enez Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Izelvroioù",
  "NO": "Norvegia",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Zeland-Nevez",
  "Narb": "henarabek an Norzh",
  "OM": "Oman",
  "Ogam": "ogam",
  "Orya": "oriya",
  "PA": "Panamá",
  "PE": "Perou",
  "PF": "Polinezia Cʼhall",
  "PG": "Papoua Ginea-Nevez",
  "PH": "Filipinez",
  "PK": "Pakistan",
  "PL": "Polonia",
  "PM": "Sant-Pêr-ha-Mikelon",
  "PN": "Enez Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Tiriadoù Palestina",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "Phnx": "fenikianek",
  "QA": "Qatar",
  "QO": "Oseania diabell",
  "RE": "Ar Reünion",
  "RO": "Roumania",
  "RS": "Serbia",
  "RU": "Rusia",
  "RW": "Rwanda",
  "Runr": "runek",
  "SA": "Arabia Saoudat",
  "SB": "Inizi Salomon",
  "SC": "Sechelez",
  "SD": "Soudan",
  "SE": "Sveden",
  "SG": "Singapour",
  "SH": "Saint-Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Susoudan",
  "ST": "São Tomé ha Príncipe",
  "SV": "Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Eswatini",
  "Samr": "samaritek",
  "Sarb": "henarabek ar Su",
  "Sinh": "singhalek",
  "Sund": "sundanek",
  "Syrc": "siriek",
  "Syre": "siriek Estrangelā",
  "Syrj": "siriek ar C’hornôg",
  "Syrn": "siriek ar Reter",
  "TA": "Tristan da Cunha",
  "TC": "Inizi Turks ha Caicos",
  "TD": "Tchad",
  "TF": "Douaroù aostral Frañs",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadjikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunizia",
  "TO": "Tonga",
  "TR": "Turkia",
  "TT": "Trinidad ha Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Taml": "tamilek",
  "Telu": "telougou",
  "Tglg": "tagalog",
  "Thaa": "thaana",
  "Thai": "thai",
  "Tibt": "tibetanek",
  "UA": "Ukraina",
  "UG": "Ouganda",
  "UM": "Inizi diabell ar Stadoù-Unanet",
  "UN": "Broadoù unanet",
  "US": "Stadoù-Unanet",
  "UY": "Uruguay",
  "UZ": "Ouzbekistan",
  "Ugar": "ougaritek",
  "VA": "Vatikan",
  "VC": "Sant Visant hag ar Grenadinez",
  "VE": "Venezuela",
  "VG": "Inizi Gwercʼh Breizh-Veur",
  "VI": "Inizi Gwercʼh ar Stadoù-Unanet",
  "VN": "Viêt Nam",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "WF": "Wallis ha Futuna",
  "WS": "Samoa",
  "XA": "pouez-mouezh gaou",
  "XB": "BiDi gaou",
  "XK": "Kosovo",
  "Xpeo": "persek kozh",
  "Xsux": "gennheñvel",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "Suafrika",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Rannved dianav",
  "Zinh": "hêrezh",
  "Zmth": "notadur jedoniel",
  "Zsye": "fromlunioù",
  "Zsym": "arouezioù",
  "Zxxx": "anskrivet",
  "Zyyy": "boutin",
  "Zzzz": "skritur dianav",
  "aa": "afar",
  "ab": "abkhazeg",
  "ace": "achineg",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adygeieg",
  "ae": "avesteg",
  "aeb": "arabeg Tunizia",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibia)",
  "af_ZA": "afrikaans (Suafrika)",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainoueg",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "akadeg",
  "akz": "alabamaeg",
  "ale": "aleouteg",
  "aln": "gegeg",
  "alt": "altaieg ar Su",
  "am": "amhareg",
  "am_ET": "amhareg (Etiopia)",
  "an": "aragoneg",
  "ang": "hensaozneg",
  "anp": "angika",
  "ar": "arabeg",
  "ar_001": "arabeg modern",
  "ar_AE": "arabeg (Emirelezhioù Arab Unanet)",
  "ar_BH": "arabeg (Bahrein)",
  "ar_DJ": "arabeg (Djibouti)",
  "ar_DZ": "arabeg (Aljeria)",
  "ar_EG": "arabeg (Egipt)",
  "ar_EH": "arabeg (Sahara ar Cʼhornôg)",
  "ar_ER": "arabeg (Eritrea)",
  "ar_IL": "arabeg (Israel)",
  "ar_IQ": "arabeg (Iraq)",
  "ar_JO": "arabeg (Jordania)",
  "ar_KM": "arabeg (Komorez)",
  "ar_KW": "arabeg (Koweit)",
  "ar_LB": "arabeg (Liban)",
  "ar_LY": "arabeg (Libia)",
  "ar_MA": "arabeg (Maroko)",
  "ar_MR": "arabeg (Maouritania)",
  "ar_OM": "arabeg (Oman)",
  "ar_PS": "arabeg (Tiriadoù Palestina)",
  "ar_QA": "arabeg (Qatar)",
  "ar_SA": "arabeg (Arabia Saoudat)",
  "ar_SD": "arabeg (Soudan)",
  "ar_SO": "arabeg (Somalia)",
  "ar_SS": "arabeg (Susoudan)",
  "ar_SY": "arabeg (Siria)",
  "ar_TD": "arabeg (Tchad)",
  "ar_TN": "arabeg (Tunizia)",
  "ar_YE": "arabeg (Yemen)",
  "arc": "arameeg",
  "arn": "araoukaneg",
  "aro": "araona",
  "arp": "arapaho",
  "arq": "arabeg Aljeria",
  "arw": "arawakeg",
  "ary": "arabeg Maroko",
  "arz": "arabeg Egipt",
  "as": "asameg",
  "as_IN": "asameg (India)",
  "asa": "asu",
  "ase": "yezh sinoù Amerika",
  "ast": "asturianeg",
  "av": "avar",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aymara",
  "az": "azerbaidjaneg",
  "az_AZ": "azeri (Azerbaidjan)",
  "az_Cyrl": "azeri (kirillek)",
  "az_Cyrl_AZ": "azeri (kirillek, Azerbaidjan)",
  "az_Latn": "azeri (latin)",
  "az_Latn_AZ": "azeri (latin, Azerbaidjan)",
  "azb": "azeri ar Su",
  "ba": "bachkir",
  "bal": "baloutchi",
  "ban": "balineg",
  "bar": "bavarieg",
  "bas": "basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "belaruseg",
  "be_BY": "belaruseg (Belarus)",
  "bej": "bedawieg",
  "bem": "bemba",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "bulgareg",
  "bg_BG": "bulgareg (Bulgaria)",
  "bgn": "baloutchi ar Cʼhornôg",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latin)",
  "bm_Latn_ML": "bambara (latin, Mali)",
  "bn": "bengali",
  "bn_BD": "bengali (Bangladesh)",
  "bn_IN": "bengali (India)",
  "bo": "tibetaneg",
  "bo_CN": "tibetaneg (Sina)",
  "bo_IN": "tibetaneg (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "brezhoneg",
  "br_FR": "brezhoneg (Frañs)",
  "bra": "braj",
  "brh": "brahweg",
  "brx": "bodo",
  "bs": "bosneg",
  "bs_BA": "bosneg (Bosnia ha Herzegovina)",
  "bs_Cyrl": "bosneg (kirillek)",
  "bs_Cyrl_BA": "bosneg (kirillek, Bosnia ha Herzegovina)",
  "bs_Latn": "bosneg (latin)",
  "bs_Latn_BA": "bosneg (latin, Bosnia ha Herzegovina)",
  "bss": "akoose",
  "bua": "bouriat",
  "bug": "bugi",
  "bum": "Bulu",
  "byn": "blin",
  "byv": "Medumba",
  "ca": "katalaneg",
  "ca_AD": "katalaneg (Andorra)",
  "ca_ES": "katalaneg (Spagn)",
  "ca_FR": "katalaneg (Frañs)",
  "ca_IT": "katalaneg (Italia)",
  "cad": "caddo",
  "car": "karibeg",
  "cay": "Cayuga",
  "cch": "atsam",
  "ccp": "chakmaeg",
  "ce": "tchetcheneg",
  "ceb": "cebuano",
  "cgg": "chigaeg",
  "ch": "chamorru",
  "chb": "chibcha",
  "chg": "Chagatai",
  "chk": "chuuk",
  "chm": "marieg",
  "chn": "Chinook Jargon",
  "cho": "choktaw",
  "chp": "chipewyan",
  "chr": "cherokee",
  "chy": "cheyenne",
  "ckb": "kurdeg sorani",
  "co": "korseg",
  "cop": "kopteg",
  "cps": "Capiznon",
  "cr": "kri",
  "crh": "turkeg Krimea",
  "crs": "kreoleg Sechelez",
  "cs": "tchekeg",
  "cs_CZ": "tchekeg (Republik Tchek)",
  "csb": "kachoubeg",
  "cu": "slavoneg iliz",
  "cv": "tchouvatch",
  "cy": "kembraeg",
  "cy_GB": "kembraeg (Rouantelezh-Unanet)",
  "da": "daneg",
  "da_DK": "daneg (Danmark)",
  "da_GL": "daneg (Greunland)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "de": "alamaneg",
  "de_AT": "alamaneg (Aostria)",
  "de_BE": "alamaneg (Belgia)",
  "de_CH": "alamaneg (Suis)",
  "de_DE": "alamaneg (Alamagn)",
  "de_LI": "alamaneg (Liechtenstein)",
  "de_LU": "alamaneg (Luksembourg)",
  "del": "delaware",
  "den": "Slave",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dsb": "izelsorabeg",
  "dtp": "Central Dusun",
  "dua": "douala",
  "dum": "nederlandeg krenn",
  "dv": "divehi",
  "dyo": "diola",
  "dyu": "dyula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhoutan)",
  "dzg": "dazagaeg",
  "ebu": "embu",
  "ee": "ewe",
  "ee_GH": "ewe (Ghana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "henegipteg",
  "eka": "ekajuk",
  "el": "gresianeg",
  "el_CY": "gresianeg (Kiprenez)",
  "el_GR": "gresianeg (Gres)",
  "elx": "elameg",
  "en": "saozneg",
  "en_AG": "saozneg (Antigua ha Barbuda)",
  "en_AI": "saozneg (Anguilla)",
  "en_AS": "saozneg (Samoa Amerikan)",
  "en_AU": "saozneg (Aostralia)",
  "en_BB": "saozneg (Barbados)",
  "en_BE": "saozneg (Belgia)",
  "en_BM": "saozneg (Bermuda)",
  "en_BS": "saozneg (Bahamas)",
  "en_BW": "saozneg (Botswana)",
  "en_BZ": "saozneg (Belize)",
  "en_CA": "saozneg (Kanada)",
  "en_CC": "saozneg (Inizi Kokoz)",
  "en_CK": "saozneg (Inizi Cook)",
  "en_CM": "saozneg (Kameroun)",
  "en_CX": "saozneg (Enez Christmas)",
  "en_DG": "saozneg (Diego Garcia)",
  "en_DM": "saozneg (Dominica)",
  "en_ER": "saozneg (Eritrea)",
  "en_FJ": "saozneg (Fidji)",
  "en_FK": "saozneg (Inizi Falkland)",
  "en_FM": "saozneg (Mikronezia)",
  "en_GB": "saozneg (Rouantelezh-Unanet)",
  "en_GD": "saozneg (Grenada)",
  "en_GG": "saozneg (Gwernenez)",
  "en_GH": "saozneg (Ghana)",
  "en_GI": "saozneg (Jibraltar)",
  "en_GM": "saozneg (Gambia)",
  "en_GU": "saozneg (Guam)",
  "en_GY": "saozneg (Guyana)",
  "en_HK": "saozneg (Hong Kong RMD Sina)",
  "en_IE": "saozneg (Iwerzhon)",
  "en_IM": "saozneg (Enez Vanav)",
  "en_IN": "saozneg (India)",
  "en_IO": "saozneg (Tiriad breizhveurat Meurvor Indez)",
  "en_JE": "saozneg (Jerzenez)",
  "en_JM": "saozneg (Jamaika)",
  "en_KE": "saozneg (Kenya)",
  "en_KI": "saozneg (Kiribati)",
  "en_KN": "saozneg (Saint Kitts ha Nevis)",
  "en_KY": "saozneg (Inizi Cayman)",
  "en_LC": "saozneg (Saint Lucia)",
  "en_LR": "saozneg (Liberia)",
  "en_LS": "saozneg (Lesotho)",
  "en_MG": "saozneg (Madagaskar)",
  "en_MH": "saozneg (Inizi Marshall)",
  "en_MO": "saozneg (Macau RMD Sina)",
  "en_MP": "saozneg (Inizi Mariana an Norzh)",
  "en_MS": "saozneg (Montserrat)",
  "en_MT": "saozneg (Malta)",
  "en_MU": "saozneg (Moris)",
  "en_MW": "saozneg (Malawi)",
  "en_MY": "saozneg (Malaysia)",
  "en_NA": "saozneg (Namibia)",
  "en_NF": "saozneg (Enez Norfolk)",
  "en_NG": "saozneg (Nigeria)",
  "en_NR": "saozneg (Nauru)",
  "en_NU": "saozneg (Niue)",
  "en_NZ": "saozneg (Zeland-Nevez)",
  "en_PG": "saozneg (Papoua Ginea-Nevez)",
  "en_PH": "saozneg (Filipinez)",
  "en_PK": "saozneg (Pakistan)",
  "en_PN": "saozneg (Enez Pitcairn)",
  "en_PR": "saozneg (Puerto Rico)",
  "en_PW": "saozneg (Palau)",
  "en_RW": "saozneg (Rwanda)",
  "en_SB": "saozneg (Salomon)",
  "en_SC": "saozneg (Sechelez)",
  "en_SD": "saozneg (Soudan)",
  "en_SG": "saozneg (Singapour)",
  "en_SH": "saozneg (Saint-Helena)",
  "en_SL": "saozneg (Sierra Leone)",
  "en_SS": "saozneg (Susoudan)",
  "en_SX": "saozneg (Sint Maarten)",
  "en_SZ": "saozneg (Swaziland)",
  "en_TC": "saozneg (Inizi Turks ha Caicos)",
  "en_TK": "saozneg (Tokelau)",
  "en_TO": "saozneg (Tonga)",
  "en_TT": "saozneg (Trinidad ha Tobago)",
  "en_TV": "saozneg (Tuvalu)",
  "en_TZ": "saozneg (Tanzania)",
  "en_UG": "saozneg (Ouganda)",
  "en_UM": "saozneg (Inizi diabell ar Stadoù-Unanet)",
  "en_US": "saozneg (Stadoù-Unanet)",
  "en_VC": "saozneg (Sant Visant hag ar Grenadinez)",
  "en_VG": "saozneg (Inizi Gwercʼh Breizh-Veur)",
  "en_VI": "saozneg (Inizi Gwercʼh ar Stadoù-Unanet)",
  "en_VU": "saozneg (Vanuatu)",
  "en_WS": "saozneg (Samoa)",
  "en_ZA": "saozneg (Suafrika)",
  "en_ZM": "saozneg (Zambia)",
  "en_ZW": "saozneg (Zimbabwe)",
  "enm": "krennsaozneg",
  "eo": "esperanteg",
  "es": "spagnoleg",
  "es_419": "spagnoleg Amerika latin",
  "es_AR": "spagnoleg (Arcʼhantina)",
  "es_BO": "spagnoleg (Bolivia)",
  "es_CL": "spagnoleg (Chile)",
  "es_CO": "spagnoleg (Kolombia)",
  "es_CR": "spagnoleg (Costa Rica)",
  "es_CU": "spagnoleg (Kuba)",
  "es_DO": "spagnoleg (Republik Dominikan)",
  "es_EA": "spagnoleg (Ceuta ha Melilla)",
  "es_EC": "spagnoleg (Ecuador)",
  "es_ES": "spagnoleg (Spagn)",
  "es_GQ": "spagnoleg (Ginea ar Cʼheheder)",
  "es_GT": "spagnoleg (Guatemala)",
  "es_HN": "spagnoleg (Honduras)",
  "es_IC": "spagnoleg (Inizi Kanariez)",
  "es_MX": "spagnoleg (Mecʼhiko)",
  "es_NI": "spagnoleg (Nicaragua)",
  "es_PA": "spagnoleg (Panamá)",
  "es_PE": "spagnoleg (Perou)",
  "es_PH": "spagnoleg (Filipinez)",
  "es_PR": "spagnoleg (Puerto Rico)",
  "es_PY": "spagnoleg (Paraguay)",
  "es_SV": "spagnoleg (Salvador)",
  "es_US": "spagnoleg (Stadoù-Unanet)",
  "es_UY": "spagnoleg (Uruguay)",
  "es_VE": "spagnoleg (Venezuela)",
  "esu": "Central Yupik",
  "et": "estoneg",
  "et_EE": "estoneg (Estonia)",
  "eu": "euskareg",
  "eu_ES": "euskareg (Spagn)",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fa": "perseg",
  "fa_AF": "perseg (Afghanistan)",
  "fa_IR": "perseg (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fula",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "finneg",
  "fi_FI": "finneg (Finland)",
  "fil": "filipineg",
  "fit": "finneg traoñienn an Torne",
  "fj": "fidjieg",
  "fo": "faeroeg",
  "fo_FO": "faeroeg (Inizi Faero)",
  "fon": "fon",
  "fr": "galleg",
  "fr_BE": "galleg (Belgia)",
  "fr_BF": "galleg (Burkina Faso)",
  "fr_BI": "galleg (Burundi)",
  "fr_BJ": "galleg (Benin)",
  "fr_BL": "galleg (Saint Barthélemy)",
  "fr_CA": "galleg Kanada",
  "fr_CD": "galleg (Kongo - Kinshasa)",
  "fr_CF": "galleg (Republik Kreizafrikan)",
  "fr_CG": "galleg (Kongo - Brazzaville)",
  "fr_CH": "galleg Suis",
  "fr_CI": "galleg (Aod an Olifant)",
  "fr_CM": "galleg (Kameroun)",
  "fr_DJ": "galleg (Djibouti)",
  "fr_DZ": "galleg (Aljeria)",
  "fr_FR": "galleg (Frañs)",
  "fr_GA": "galleg (Gabon)",
  "fr_GF": "galleg (Gwiana cʼhall)",
  "fr_GN": "galleg (Ginea)",
  "fr_GP": "galleg (Gwadeloup)",
  "fr_GQ": "galleg (Ginea ar Cʼheheder)",
  "fr_HT": "galleg (Haiti)",
  "fr_KM": "galleg (Komorez)",
  "fr_LU": "galleg (Luksembourg)",
  "fr_MA": "galleg (Maroko)",
  "fr_MC": "galleg (Monaco)",
  "fr_MF": "galleg (Saint Martin)",
  "fr_MG": "galleg (Madagaskar)",
  "fr_ML": "galleg (Mali)",
  "fr_MQ": "galleg (Martinik)",
  "fr_MR": "galleg (Maouritania)",
  "fr_MU": "galleg (Moris)",
  "fr_NC": "galleg (Kaledonia Nevez)",
  "fr_NE": "galleg (Niger)",
  "fr_PF": "galleg (Polinezia Cʼhall)",
  "fr_PM": "galleg (Sant-Pêr-ha-Mikelon)",
  "fr_RE": "galleg (Reünion)",
  "fr_RW": "galleg (Rwanda)",
  "fr_SC": "galleg (Sechelez)",
  "fr_SN": "galleg (Senegal)",
  "fr_SY": "galleg (Siria)",
  "fr_TD": "galleg (Tchad)",
  "fr_TG": "galleg (Togo)",
  "fr_TN": "galleg (Tunizia)",
  "fr_VU": "galleg (Vanuatu)",
  "fr_WF": "galleg (Wallis ha Futuna)",
  "fr_YT": "galleg (Mayotte)",
  "frc": "galleg cajun",
  "frm": "krenncʼhalleg",
  "fro": "hencʼhalleg",
  "frp": "arpitaneg",
  "frr": "frizeg an Norzh",
  "frs": "frizeg ar Reter",
  "fur": "frioulaneg",
  "fy": "frizeg ar Cʼhornôg",
  "fy_NL": "frizeg ar Cʼhornôg (Izelvroioù)",
  "ga": "iwerzhoneg",
  "ga_IE": "iwerzhoneg (Iwerzhon)",
  "gaa": "ga",
  "gag": "gagaouzeg",
  "gan": "sinaeg Gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "skoseg",
  "gd_GB": "skoseg (Rouantelezh-Unanet)",
  "gez": "gezeg",
  "gil": "gilberteg",
  "gl": "galizeg",
  "gl_ES": "galizeg (Spagn)",
  "glk": "Gilaki",
  "gmh": "krennalamaneg uhel",
  "gn": "guarani",
  "goh": "henalamaneg uhel",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "gorontalo",
  "got": "goteg",
  "grb": "grebo",
  "grc": "hencʼhresianeg",
  "gsw": "alamaneg Suis",
  "gu": "gujarati",
  "gu_IN": "gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusiieg",
  "gv": "manaveg",
  "gv_IM": "manaveg (Enez Vanav)",
  "gwi": "gwich’in",
  "ha": "haousa",
  "ha_GH": "haousa (Ghana)",
  "ha_Latn": "haousa (latin)",
  "ha_Latn_GH": "haousa (latin, Ghana)",
  "ha_Latn_NE": "haousa (latin, Niger)",
  "ha_Latn_NG": "haousa (latin, Nigeria)",
  "ha_NE": "haousa (Niger)",
  "ha_NG": "haousa (Nigeria)",
  "hai": "haida",
  "hak": "sinaeg Hakka",
  "haw": "hawaieg",
  "he": "hebraeg",
  "he_IL": "hebraeg (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "hit": "Hittite",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "kroateg",
  "hr_BA": "kroateg (Bosnia ha Herzegovina)",
  "hr_HR": "kroateg (Kroatia)",
  "hsb": "uhelsorabeg",
  "hsn": "sinaeg Xian",
  "ht": "haitieg",
  "hu": "hungareg",
  "hu_HU": "hungareg (Hungaria)",
  "hup": "hupa",
  "hy": "armenianeg",
  "hy_AM": "armenianeg (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonezeg",
  "id_ID": "indonezeg (Indonezia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "igbo (Nigeria)",
  "ii": "yieg Sichuan",
  "ii_CN": "yieg Sichuan (Sina)",
  "ik": "inupiaq",
  "ilo": "ilokanoeg",
  "inh": "ingoucheg",
  "io": "ido",
  "is": "islandeg",
  "is_IS": "islandeg (Island)",
  "it": "italianeg",
  "it_CH": "italianeg (Suis)",
  "it_IT": "italianeg (Italia)",
  "it_SM": "italianeg (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "japaneg",
  "ja_JP": "japaneg (Japan)",
  "jam": "kreoleg Jamaika",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "yuzev-perseg",
  "jrb": "yuzev-arabeg",
  "jut": "Jutish",
  "jv": "javaneg",
  "ka": "jorjianeg",
  "ka_GE": "jorjianeg (Jorjia)",
  "kaa": "karakalpak",
  "kab": "kabileg",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kaw": "Kawi",
  "kbd": "kabardeg",
  "kbl": "Kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "kabuverdianu",
  "ken": "Kenyang",
  "kfo": "koroeg",
  "kg": "kongo",
  "kgp": "Kaingang",
  "kha": "khasi",
  "kho": "khotaneg",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "kwanyama",
  "kk": "kazak",
  "kk_Cyrl": "kazak (kirillek)",
  "kk_Cyrl_KZ": "kazak (kirillek, Kazakstan)",
  "kk_KZ": "kazak (Kazakstan)",
  "kkj": "kakoeg",
  "kl": "greunlandeg",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "kalendjineg",
  "km": "khmer",
  "km_KH": "khmer (Kambodja)",
  "kmb": "kimbundu",
  "kn": "kanareg",
  "kn_IN": "kanareg (India)",
  "ko": "koreaneg",
  "ko_KP": "koreaneg (Korea an Norzh)",
  "ko_KR": "koreaneg (Korea ar Su)",
  "koi": "Komi-Permyak",
  "kok": "konkani",
  "kos": "kosrae",
  "kpe": "kpelle",
  "kr": "kanouri",
  "krc": "karatchay-balkar",
  "kri": "krio",
  "krj": "Kinaray-a",
  "krl": "karelieg",
  "kru": "kurukh",
  "ks": "kashmiri",
  "ks_Arab": "kashmiri (arabek)",
  "ks_Arab_IN": "kashmiri (arabek, India)",
  "ks_IN": "kashmiri (India)",
  "ksb": "shambala",
  "ksf": "bafiaeg",
  "ksh": "koluneg",
  "ku": "kurdeg",
  "kum": "koumikeg",
  "kut": "kutenai",
  "kv": "komieg",
  "kw": "kerneveureg",
  "kw_GB": "kerneveureg (Rouantelezh-Unanet)",
  "ky": "kirgiz",
  "ky_Cyrl": "kirgiz (kirillek)",
  "ky_Cyrl_KG": "kirgiz (kirillek, Kyrgyzstan)",
  "ky_KG": "kirgiz (Kyrgyzstan)",
  "la": "latin",
  "lad": "ladino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luksembourgeg",
  "lb_LU": "luksembourgeg (Luksembourg)",
  "lez": "lezgi",
  "lfn": "lingua franca nova",
  "lg": "ganda",
  "lg_UG": "ganda (Ouganda)",
  "li": "limbourgeg",
  "lij": "ligurieg",
  "liv": "Livonian",
  "lkt": "lakota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Kongo - Kinshasa)",
  "ln_CF": "lingala (Republik Kreizafrikan)",
  "ln_CG": "lingala (Kongo - Brazzaville)",
  "lo": "laoseg",
  "lo_LA": "laoseg (Laos)",
  "lol": "mongo",
  "lou": "kreoleg Louiziana",
  "loz": "lozi",
  "lrc": "loureg an Norzh",
  "lt": "lituaneg",
  "lt_LT": "lituaneg (Lituania)",
  "ltg": "Latgalian",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Kongo - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushai",
  "luy": "luyia",
  "lv": "latvieg",
  "lv_LV": "latvieg (Latvia)",
  "lzh": "sinaeg lennegel",
  "lzz": "Laz",
  "mad": "madoureg",
  "maf": "Mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "Mandingo",
  "mas": "masai",
  "mde": "Maba",
  "mdf": "moksha",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "moriseg",
  "mg": "malgacheg",
  "mg_MG": "malgacheg (Madagaskar)",
  "mga": "krenniwerzhoneg",
  "mgh": "makhuwa-meetto",
  "mgo": "metaʼ",
  "mh": "marshall",
  "mi": "maori",
  "mic": "mikmakeg",
  "min": "minangkabau",
  "mk": "makedoneg",
  "mk_MK": "makedoneg (Makedonia)",
  "ml": "malayalam",
  "ml_IN": "malayalam (India)",
  "mn": "mongoleg",
  "mn_Cyrl": "mongoleg (kirillek)",
  "mn_Cyrl_MN": "mongoleg (kirillek, Mongolia)",
  "mn_MN": "mongoleg (Mongolia)",
  "mnc": "manchou",
  "mni": "manipuri",
  "moh": "mohawk",
  "mos": "more",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "marieg ar Cʼhornôg",
  "ms": "malayseg",
  "ms_BN": "malayseg (Brunei)",
  "ms_Latn": "malayseg (latin)",
  "ms_Latn_BN": "malayseg (latin, Brunei)",
  "ms_Latn_MY": "malayseg (latin, Malaysia)",
  "ms_Latn_SG": "malayseg (latin, Singapour)",
  "ms_MY": "malayseg (Malaysia)",
  "ms_SG": "malayseg (Singapour)",
  "mt": "malteg",
  "mt_MT": "malteg (Malta)",
  "mua": "moundangeg",
  "mul": "yezhoù lies",
  "mus": "muskogi",
  "mwl": "mirandeg",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "birmaneg",
  "my_MM": "birmaneg (Myanmar (Birmania))",
  "mye": "Myene",
  "myv": "erza",
  "mzn": "mazanderaneg",
  "na": "naurueg",
  "nan": "sinaeg Min Nan",
  "nap": "napolitaneg",
  "naq": "nama",
  "nb": "norvegeg bokmål",
  "nb_NO": "norvegeg bokmål (Norvegia)",
  "nb_SJ": "norvegeg bokmål (Svalbard)",
  "nd": "ndebele an Norzh",
  "nd_ZW": "ndebele an Norzh (Zimbabwe)",
  "nds": "alamaneg izel",
  "nds_NL": "saksoneg izel",
  "ne": "nepaleg",
  "ne_IN": "nepaleg (India)",
  "ne_NP": "nepaleg (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "niu": "niue",
  "njo": "aoeg",
  "nl": "nederlandeg",
  "nl_AW": "nederlandeg (Aruba)",
  "nl_BE": "nederlandeg (Belgia)",
  "nl_BQ": "nederlandeg (Nederlandat Karib)",
  "nl_CW": "nederlandeg (Curaçao)",
  "nl_NL": "nederlandeg (Izelvroioù)",
  "nl_SR": "nederlandeg (Surinam)",
  "nl_SX": "nederlandeg (Sint Maarten)",
  "nmg": "ngoumbeg",
  "nn": "norvegeg nynorsk",
  "nn_NO": "norvegeg nynorsk (Norvegia)",
  "nnh": "ngiemboon",
  "no": "norvegeg",
  "no_NO": "norvegeg (Norvegia)",
  "nog": "nogay",
  "non": "hennorseg",
  "nov": "novial",
  "nqo": "nkoeg",
  "nr": "ndebele ar Su",
  "nso": "sotho an Norzh",
  "nus": "nouereg",
  "nv": "navacʼho",
  "nwc": "newari klasel",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "Nzima",
  "oc": "okitaneg",
  "oj": "ojibwa",
  "om": "oromoeg",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "oriya",
  "or_IN": "oriya (India)",
  "os": "oseteg",
  "os_GE": "oseteg (Jorjia)",
  "os_RU": "oseteg (Rusia)",
  "osa": "osage",
  "ota": "turkeg otoman",
  "pa": "punjabi",
  "pa_Arab": "punjabi (arabek)",
  "pa_Arab_PK": "punjabi (arabek, Pakistan)",
  "pa_Guru": "punjabi (gurmukhi)",
  "pa_Guru_IN": "punjabi (gurmukhi, India)",
  "pa_IN": "punjabi (India)",
  "pa_PK": "punjabi (Pakistan)",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palau",
  "pcd": "pikardeg",
  "pcm": "pidjin Nigeria",
  "pdc": "alamaneg Pennsylvania",
  "pdt": "Plautdietsch",
  "peo": "henberseg",
  "pfl": "Palatine German",
  "phn": "fenikianeg",
  "pi": "pali",
  "pl": "poloneg",
  "pl_PL": "poloneg (Polonia)",
  "pms": "piemonteg",
  "pnt": "ponteg",
  "pon": "pohnpei",
  "prg": "henbruseg",
  "pro": "henbrovañseg",
  "ps": "pachto",
  "ps_AF": "pachto (Afghanistan)",
  "pt": "portugaleg",
  "pt_AO": "portugaleg (Angola)",
  "pt_BR": "portugaleg (Brazil)",
  "pt_CV": "portugaleg (Kab Glas)",
  "pt_GW": "portugaleg (Ginea-Bissau)",
  "pt_MO": "portugaleg (Macau RMD Sina)",
  "pt_MZ": "portugaleg (Mozambik)",
  "pt_PT": "portugaleg (Portugal)",
  "pt_ST": "portugaleg (São Tomé ha Príncipe)",
  "pt_TL": "portugaleg (Timor-Leste)",
  "qu": "kechuaeg",
  "qu_BO": "kechuaeg (Bolivia)",
  "qu_EC": "kechuaeg (Ecuador)",
  "qu_PE": "kechuaeg (Perou)",
  "quc": "kʼicheʼ",
  "qug": "kichuaeg Chimborazo",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotonga",
  "rgn": "romagnoleg",
  "rif": "Riffian",
  "rm": "romañcheg",
  "rm_CH": "romañcheg (Suis)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "roumaneg",
  "ro_MD": "roumaneg (Moldova)",
  "ro_RO": "roumaneg (Roumania)",
  "rof": "rombo",
  "rom": "romanieg",
  "root": "gwrizienn",
  "rtm": "Rotuman",
  "ru": "rusianeg",
  "ru_BY": "rusianeg (Belarus)",
  "ru_KG": "rusianeg (Kyrgyzstan)",
  "ru_KZ": "rusianeg (Kazakstan)",
  "ru_MD": "rusianeg (Moldova)",
  "ru_RU": "rusianeg (Rusia)",
  "ru_UA": "rusianeg (Ukraina)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aroumaneg",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Rwanda)",
  "rwk": "rwa",
  "sa": "sanskriteg",
  "sad": "sandawe",
  "sah": "yakouteg",
  "sam": "arameeg ar Samaritaned",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambayeg",
  "sbp": "sangu",
  "sc": "sardeg",
  "scn": "sikilieg",
  "sco": "skoteg",
  "sd": "sindhi",
  "sdc": "sasareseg",
  "se": "sámi an Norzh",
  "se_FI": "sámi an Norzh (Finland)",
  "se_NO": "sámi an Norzh (Norvegia)",
  "se_SE": "sámi an Norzh (Sveden)",
  "see": "Seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (Republik Kreizafrikan)",
  "sga": "heniwerzhoneg",
  "sgs": "Samogitian",
  "sh": "serb-kroateg",
  "sh_BA": "serb-kroateg (Bosnia ha Herzegovina)",
  "shi": "tacheliteg",
  "shn": "shan",
  "shu": "arabeg Tchad",
  "si": "singhaleg",
  "si_LK": "singhaleg (Sri Lanka)",
  "sid": "sidamo",
  "sk": "slovakeg",
  "sk_SK": "slovakeg (Slovakia)",
  "sl": "sloveneg",
  "sl_SI": "sloveneg (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoan",
  "sma": "sámi ar Su",
  "smj": "sámi Luleå",
  "smn": "sámi Inari",
  "sms": "sámi Skolt",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabwe)",
  "snk": "soninke",
  "so": "somali",
  "so_DJ": "somali (Djibouti)",
  "so_ET": "somali (Etiopia)",
  "so_KE": "somali (Kenya)",
  "so_SO": "somali (Somalia)",
  "sog": "sogdieg",
  "sq": "albaneg",
  "sq_AL": "albaneg (Albania)",
  "sq_MK": "albaneg (Makedonia)",
  "sq_XK": "albaneg (Kosovo)",
  "sr": "serbeg",
  "sr_BA": "serbeg (Bosnia ha Herzegovina)",
  "sr_Cyrl": "serbeg (kirillek)",
  "sr_Cyrl_BA": "serbeg (kirillek, Bosnia ha Herzegovina)",
  "sr_Cyrl_ME": "serbeg (kirillek, Montenegro)",
  "sr_Cyrl_RS": "serbeg (kirillek, Serbia)",
  "sr_Cyrl_XK": "serbeg (kirillek, Kosovo)",
  "sr_Latn": "serbeg (latin)",
  "sr_Latn_BA": "serbeg (latin, Bosnia ha Herzegovina)",
  "sr_Latn_ME": "serbeg (latin, Montenegro)",
  "sr_Latn_RS": "serbeg (latin, Serbia)",
  "sr_Latn_XK": "serbeg (latin, Kosovo)",
  "sr_ME": "serbeg (Montenegro)",
  "sr_RS": "serbeg (Serbia)",
  "sr_XK": "serbeg (Kosovo)",
  "srn": "sranan tongo",
  "srr": "serer",
  "ss": "swati",
  "ssy": "sahoeg",
  "st": "sotho ar Su",
  "stq": "Saterland Frisian",
  "su": "sundaneg",
  "suk": "sukuma",
  "sus": "Susu",
  "sux": "sumereg",
  "sv": "svedeg",
  "sv_AX": "svedeg (Inizi Åland)",
  "sv_FI": "svedeg (Finland)",
  "sv_SE": "svedeg (Sveden)",
  "sw": "swahili",
  "sw_CD": "swahili Kongo",
  "sw_KE": "swahili (Kenya)",
  "sw_TZ": "swahili (Tanzania)",
  "sw_UG": "swahili (Ouganda)",
  "swb": "komoreg",
  "swc": "Congo Swahili",
  "syc": "sirieg klasel",
  "syr": "sirieg",
  "szl": "silezieg",
  "ta": "tamileg",
  "ta_IN": "tamileg (India)",
  "ta_LK": "tamileg (Sri Lanka)",
  "ta_MY": "tamileg (Malaysia)",
  "ta_SG": "tamileg (Singapour)",
  "tcy": "touloueg",
  "te": "telougou",
  "te_IN": "telougou (India)",
  "tem": "temne",
  "teo": "tesoeg",
  "ter": "tereno",
  "tet": "tetum",
  "tg": "tadjik",
  "th": "thai",
  "th_TH": "thai (Thailand)",
  "ti": "tigrigna",
  "ti_ER": "tigrigna (Eritrea)",
  "ti_ET": "tigrigna (Etiopia)",
  "tig": "tigreaneg",
  "tiv": "tiv",
  "tk": "turkmeneg",
  "tkl": "tokelau",
  "tkr": "Tsakhur",
  "tl": "tagalog",
  "tl_PH": "tagalog (Filipinez)",
  "tlh": "klingon",
  "tli": "tinglit",
  "tly": "Talysh",
  "tmh": "tamacheg",
  "tn": "tswana",
  "to": "tonga",
  "to_TO": "tonga (Tonga)",
  "tog": "nyasa tonga",
  "tpi": "tok pisin",
  "tr": "turkeg",
  "tr_CY": "turkeg (Kiprenez)",
  "tr_TR": "turkeg (Turkia)",
  "tru": "turoyoeg",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshian",
  "tt": "tatar",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tvl": "tuvalu",
  "tw": "twi",
  "twq": "tasawakeg",
  "ty": "tahitianeg",
  "tyv": "touva",
  "tzm": "tamazigteg Kreizatlas",
  "udm": "oudmourteg",
  "ug": "ouigoureg",
  "ug_Arab": "ouigoureg (arabek)",
  "ug_Arab_CN": "ouigoureg (arabek, Sina)",
  "ug_CN": "ouigoureg (Sina)",
  "uga": "ougariteg",
  "uk": "ukraineg",
  "uk_UA": "ukraineg (Ukraina)",
  "umb": "umbundu",
  "und": "yezh dianav",
  "ur": "ourdou",
  "ur_IN": "ourdou (India)",
  "ur_PK": "ourdou (Pakistan)",
  "uz": "ouzbekeg",
  "uz_AF": "ouzbekeg (Afghanistan)",
  "uz_Arab": "ouzbekeg (arabek)",
  "uz_Arab_AF": "ouzbekeg (arabek, Afghanistan)",
  "uz_Cyrl": "ouzbekeg (kirillek)",
  "uz_Cyrl_UZ": "ouzbekeg (kirillek, Ouzbekistan)",
  "uz_Latn": "ouzbekeg (latin)",
  "uz_Latn_UZ": "ouzbekeg (latin, Ouzbekistan)",
  "uz_UZ": "ouzbekeg (Ouzbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "venezieg",
  "vep": "vepseg",
  "vi": "vietnameg",
  "vi_VN": "vietnameg (Viêt Nam)",
  "vls": "flandrezeg ar c’hornôg",
  "vmf": "Main-Franconian",
  "vo": "volapük",
  "vot": "votyakeg",
  "vro": "voroeg",
  "vun": "vunjo",
  "wa": "walloneg",
  "wae": "walser",
  "wal": "walamo",
  "war": "waray",
  "was": "washo",
  "wbp": "Warlpiri",
  "wo": "wolof",
  "wuu": "sinaeg Wu",
  "xal": "kalmouk",
  "xh": "xhosa",
  "xmf": "megreleg",
  "xog": "sogaeg",
  "yao": "yao",
  "yap": "yapeg",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "yiddish",
  "yo": "yorouba",
  "yo_BJ": "yorouba (Benin)",
  "yo_NG": "yorouba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "kantoneg",
  "za": "zhuang",
  "zap": "zapoteg",
  "zbl": "Bliss",
  "zea": "zelandeg",
  "zen": "zenaga",
  "zgh": "tamacheg Maroko standart",
  "zh": "sinaeg",
  "zh_CN": "sinaeg (Sina)",
  "zh_HK": "sinaeg (Hong Kong RMD Sina)",
  "zh_Hans": "sinaeg (eeunaet)",
  "zh_Hans_CN": "sinaeg (eeunaet, Sina)",
  "zh_Hans_HK": "sinaeg (eeunaet, Hong Kong RMD Sina)",
  "zh_Hans_MO": "sinaeg (eeunaet, Macau RMD Sina)",
  "zh_Hans_SG": "sinaeg (eeunaet, Singapour)",
  "zh_Hant": "sinaeg (hengounel)",
  "zh_Hant_HK": "sinaeg (hengounel, Hong Kong RMD Sina)",
  "zh_Hant_MO": "sinaeg (hengounel, Macau RMD Sina)",
  "zh_Hant_TW": "sinaeg (hengounel, Taiwan)",
  "zh_MO": "sinaeg (Macau RMD Sina)",
  "zh_SG": "sinaeg (Singapour)",
  "zh_TW": "sinaeg (Taiwan)",
  "zu": "zouloueg",
  "zu_ZA": "zouloueg (Suafrika)",
  "zun": "zuni",
  "zxx": "diyezh",
  "zza": "zazakeg"
};
