const names = {
  "001": "Donya",
  "002": "Afrika",
  "003": "Amérika Lèr",
  "005": "Amérika Kidul",
  "009": "Oséania",
  "011": "Afrika Kulon",
  "013": "Amérika Tengah",
  "014": "Afrika Wétan",
  "015": "Afrika Lèr",
  "017": "Afrika Sisih Tengah",
  "018": "Afrika Sisih Kidul",
  "019": "Amérika",
  "021": "Amérika Sisih Lor",
  "029": "Karibia",
  "030": "Asia Wétan",
  "034": "Asia Kidul",
  "035": "Asia Kidul-wétan",
  "039": "Éropah Kidul",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Daerah Mikronesia",
  "061": "Polinesia",
  "142": "Asia",
  "143": "Asia Tengah",
  "145": "Asia Kulon",
  "150": "Éropah",
  "151": "Éropah Wétan",
  "154": "Éropah Lèr",
  "155": "Éropah Kulon",
  "202": "Afrika Kidule Sahara",
  "419": "Amérika Latin",
  "AC": "Pulo Ascension",
  "AD": "Andora",
  "AE": "Uni Émirat Arab",
  "AF": "Afganistan",
  "AG": "Antigua lan Barbuda",
  "AI": "Anguilla",
  "AL": "Albani",
  "AM": "Arménia",
  "AO": "Angola",
  "AQ": "Antartika",
  "AR": "Argèntina",
  "AS": "Samoa Amerika",
  "AT": "Ostenrik",
  "AU": "Ostrali",
  "AW": "Aruba",
  "AX": "Kapuloan Alan",
  "AZ": "Azerbaijan",
  "Arab": "hija’iyah",
  "Armn": "Armenia",
  "BA": "Bosnia lan Hèrségovina",
  "BB": "Barbadhos",
  "BD": "Banggaladésa",
  "BE": "Bèlgi",
  "BF": "Burkina Faso",
  "BG": "Bulgari",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Bénin",
  "BL": "Saint Barthélémi",
  "BM": "Bermuda",
  "BN": "Brunéi",
  "BO": "Bolivia",
  "BQ": "Karibia Walanda",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Pulo Bovèt",
  "BW": "Botswana",
  "BY": "Bélarus",
  "BZ": "Bélisé",
  "Beng": "Bangla",
  "Bopo": "Bopomofo",
  "Brai": "Braille",
  "CA": "Kanada",
  "CC": "Kapuloan Cocos (Keeling)",
  "CD": "Kongo - Kinshasa",
  "CF": "Républik Afrika Tengah",
  "CG": "Kongo - Brassaville",
  "CH": "Switserlan",
  "CI": "Pasisir Gadhing",
  "CK": "Kapuloan Cook",
  "CL": "Cilé",
  "CM": "Kamerun",
  "CN": "Tyongkok",
  "CO": "Kolombia",
  "CP": "Pulo Clipperton",
  "CR": "Kosta Rika",
  "CU": "Kuba",
  "CV": "Pongol Verdé",
  "CW": "Kurasao",
  "CX": "Pulo Natal",
  "CY": "Siprus",
  "CZ": "Céko",
  "Cyrl": "Sirilik",
  "DE": "Jérman",
  "DG": "Diego Garcia",
  "DJ": "Jibuti",
  "DK": "Dhènemarken",
  "DM": "Dominika",
  "DO": "Républik Dominika",
  "DZ": "Aljasair",
  "Deva": "Devanagari",
  "EA": "Séuta lan Melila",
  "EC": "Ékuadhor",
  "EE": "Éstonia",
  "EG": "Mesir",
  "EH": "Sahara Kulon",
  "ER": "Éritréa",
  "ES": "Sepanyol",
  "ET": "Étiopia",
  "EU": "Uni Éropah",
  "EZ": "Zona Éuro",
  "Ethi": "Ethiopik",
  "FI": "Finlan",
  "FJ": "Fiji",
  "FK": "Kapuloan Falkland",
  "FM": "Féderasi Mikronésia",
  "FO": "Kapuloan Faro",
  "FR": "Prancis",
  "GA": "Gabon",
  "GB": "Karajan Manunggal",
  "GD": "Grénada",
  "GE": "Géorgia",
  "GF": "Guyana Prancis",
  "GG": "Guernsei",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadélup",
  "GQ": "Guinéa Katulistiwa",
  "GR": "Grikenlan",
  "GS": "Georgia Kidul lan Kapuloan Sandwich Kidul",
  "GT": "Guatémala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geor": "Georgia",
  "Grek": "Yunani",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Laladan Administratif Astamiwa Hong Kong",
  "HM": "Kapuloan Heard lan McDonald",
  "HN": "Honduras",
  "HR": "Kroasia",
  "HT": "Haiti",
  "HU": "Honggari",
  "Hanb": "Han nganggo Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hans": "Prasaja",
  "Hant": "Tradhisional",
  "Hebr": "Ibrani",
  "Hira": "Hiragana",
  "Hrkt": "Silabaris Jepang",
  "IC": "Kapuloan Kanari",
  "ID": "Indonésia",
  "IE": "Républik Irlan",
  "IL": "Israèl",
  "IM": "Pulo Man",
  "IN": "Indhi",
  "IO": "Wilayah Inggris nang Segoro Hindia",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Èslan",
  "IT": "Itali",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Yordania",
  "JP": "Jepang",
  "Jpan": "Jepang",
  "KE": "Kénya",
  "KG": "Kirgistan",
  "KH": "Kamboja",
  "KI": "Kiribati",
  "KM": "Komoro",
  "KN": "Saint Kits lan Nèvis",
  "KP": "Koréa Lèr",
  "KR": "Koréa Kidul",
  "KW": "Kuwait",
  "KY": "Kapuloan Kéman",
  "KZ": "Kasakstan",
  "Kana": "Katakana",
  "Khmr": "Khmer",
  "Knda": "Kannada",
  "Kore": "Korea",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Santa Lusia",
  "LI": "Liktenstén",
  "LK": "Sri Lanka",
  "LR": "Libèria",
  "LS": "Lésotho",
  "LT": "Litowen",
  "LU": "Luksemburg",
  "LV": "Latvia",
  "LY": "Libya",
  "Laoo": "Lao",
  "Latn": "Latin",
  "MA": "Maroko",
  "MC": "Monako",
  "MD": "Moldova",
  "ME": "Montenégro",
  "MF": "Santa Martin",
  "MG": "Madagaskar",
  "MH": "Kapuloan Marshall",
  "MK": "Makédonia",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Laladan Administratif Astamiwa Makau",
  "MP": "Kapuloan Mariana Lor",
  "MQ": "Martinik",
  "MR": "Mauritania",
  "MS": "Monsérat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maladéwa",
  "MW": "Malawi",
  "MX": "Mèksiko",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "Mlym": "Malayalam",
  "Mong": "Mongolia",
  "Mymr": "Myanmar",
  "NA": "Namibia",
  "NC": "Kalédonia Anyar",
  "NE": "Nigér",
  "NF": "Pulo Norfolk",
  "NG": "Nigéria",
  "NI": "Nikaragua",
  "NL": "Walanda",
  "NO": "Nurwègen",
  "NP": "Népal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Niu Sélan",
  "OM": "Oman",
  "Orya": "Odia",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Polinesia Prancis",
  "PG": "Papua Nugini",
  "PH": "Pilipina",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint Pièr lan Mikuélon",
  "PN": "Kapuloan Pitcairn",
  "PR": "Puèrto Riko",
  "PS": "Tlatah Palèstina",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Katar",
  "QO": "Oseania Paling Njaba",
  "RE": "Réunion",
  "RO": "Ruméni",
  "RS": "Sèrbi",
  "RU": "Rusia",
  "RW": "Rwanda",
  "SA": "Arab Saudi",
  "SB": "Kapuloan Suleman",
  "SC": "Sésèl",
  "SD": "Sudan",
  "SE": "Swèdhen",
  "SG": "Singapura",
  "SH": "Saint Héléna",
  "SI": "Slovénia",
  "SJ": "Svalbard lan Jan Mayen",
  "SK": "Slowak",
  "SL": "Siéra Léoné",
  "SM": "San Marino",
  "SN": "Sénégal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Sudan Kidul",
  "ST": "Sao Tomé lan Principé",
  "SV": "Èl Salvador",
  "SX": "Sint Martén",
  "SY": "Suriah",
  "SZ": "Swasiland",
  "Sinh": "Sinhala",
  "TA": "Tristan da Cunha",
  "TC": "Turks lan Kapuloan Kaikos",
  "TD": "Chad",
  "TF": "Wilayah Prancis nang Kutub Kidul",
  "TG": "Togo",
  "TH": "Tanah Thai",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor Leste",
  "TM": "Turkménistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turki",
  "TT": "Trinidad lan Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansania",
  "Taml": "Tamil",
  "Telu": "Telugu",
  "Thaa": "Thaana",
  "Thai": "Thailand",
  "Tibt": "Tibetan",
  "UA": "Ukrania",
  "UG": "Uganda",
  "UM": "Kapuloan AS Paling Njaba",
  "UN": "Pasarékatan Bangsa-Bangsa",
  "US": "Amérika Sarékat",
  "UY": "Uruguay",
  "UZ": "Usbèkistan",
  "VA": "Kutha Vatikan",
  "VC": "Saint Vinsen lan Grénadin",
  "VE": "Vénésuéla",
  "VG": "Kapuloan Virgin Britania",
  "VI": "Kapuloan Virgin Amérika",
  "VN": "Viètnam",
  "VU": "Vanuatu",
  "WF": "Wallis lan Futuna",
  "WS": "Samoa",
  "XA": "Logat Semu",
  "XB": "Rong Arah Semu",
  "XK": "Kosovo",
  "YE": "Yaman",
  "YT": "Mayotte",
  "ZA": "Afrika Kidul",
  "ZM": "Sambia",
  "ZW": "Simbabwe",
  "ZZ": "Daerah Ora Dikenali",
  "Zmth": "Notasi Matematika",
  "Zsye": "Emoji",
  "Zsym": "Simbol",
  "Zxxx": "Ora Ketulis",
  "Zyyy": "Umum",
  "Zzzz": "Skrip Ora Dikenali",
  "af": "Afrika",
  "agq": "Aghem",
  "ak": "Akan",
  "am": "Amharik",
  "ar": "Arab",
  "ar_001": "Arab Standar Anyar",
  "as": "Assam",
  "asa": "Asu",
  "ast": "Asturia",
  "az": "Azerbaijan",
  "bas": "Basaa",
  "be": "Belarus",
  "bem": "Bemba",
  "bez": "Bena",
  "bg": "Bulgaria",
  "bm": "Bambara",
  "bn": "Bengali",
  "bo": "Tibet",
  "br": "Breton",
  "brx": "Bodo",
  "bs": "Bosnia lan Hercegovina",
  "ca": "Katala",
  "ccp": "Chakma",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "chr": "Cherokee",
  "ckb": "Kurdi Tengah",
  "co": "Korsika",
  "cs": "Ceska",
  "cu": "Slavia Gerejani",
  "cy": "Welsh",
  "da": "Dansk",
  "dav": "Taita",
  "de": "Jérman",
  "dje": "Zarma",
  "dsb": "Sorbia Non Standar",
  "dua": "Duala",
  "dyo": "Jola-Fonyi",
  "dz": "Dzongkha",
  "ebu": "Embu",
  "ee": "Ewe",
  "el": "Yunani",
  "en": "Inggris",
  "en_GB": "Inggris (Britania)",
  "eo": "Esperanto",
  "es": "Spanyol",
  "es_419": "Spanyol (Amerika Latin)",
  "es_ES": "Spanyol (Eropah)",
  "es_MX": "Spanyol (Meksiko)",
  "et": "Estonia",
  "eu": "Basque",
  "ewo": "Ewondo",
  "fa": "Persia",
  "ff": "Fulah",
  "fi": "Suomi",
  "fil": "Tagalog",
  "fo": "Faroe",
  "fr": "Prancis",
  "fur": "Friulian",
  "fy": "Frisia Sisih Kulon",
  "ga": "Irlandia",
  "gd": "Gaulia",
  "gl": "Galisia",
  "gsw": "Jerman Swiss",
  "gu": "Gujarat",
  "guz": "Gusii",
  "gv": "Manx",
  "ha": "Hausa",
  "haw": "Hawaii",
  "he": "Ibrani",
  "hi": "India",
  "hmn": "Hmong",
  "hr": "Kroasia",
  "hsb": "Sorbia Standar",
  "ht": "Kreol Haiti",
  "hu": "Hungaria",
  "hy": "Armenia",
  "ia": "Interlingua",
  "id": "Indonesia",
  "ig": "Iqbo",
  "ii": "Sichuan Yi",
  "is": "Islandia",
  "it": "Italia",
  "ja": "Jepang",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jv": "Jawa",
  "ka": "Georgia",
  "kab": "Kabyle",
  "kam": "Kamba",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "khq": "Koyra Chiini",
  "ki": "Kikuyu",
  "kk": "Kazakh",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kln": "Kalenjin",
  "km": "Khmer",
  "kn": "Kannada",
  "ko": "Korea",
  "kok": "Konkani",
  "ks": "Kashmiri",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colonia",
  "ku": "Kurdis",
  "kw": "Kernowek",
  "ky": "Kirgis",
  "la": "Latin",
  "lag": "Langi",
  "lb": "Luksemburg",
  "lg": "Ganda",
  "lkt": "Lakota",
  "ln": "Lingala",
  "lo": "Laos",
  "lrc": "Luri Sisih Lor",
  "lt": "Lithuania",
  "lu": "Luba-Katanga",
  "luo": "Luo",
  "luy": "Luyia",
  "lv": "Latvia",
  "mas": "Masai",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasi",
  "mgh": "Makhuwa-Meeto",
  "mgo": "Meta’",
  "mi": "Maori",
  "mk": "Makedonia",
  "ml": "Malayalam",
  "mn": "Mongolia",
  "mr": "Marathi",
  "ms": "Melayu",
  "mt": "Malta",
  "mua": "Mundang",
  "mul": "Basa Multilingua",
  "my": "Myanmar",
  "mzn": "Mazanderani",
  "naq": "Nama",
  "nb": "Bokmål Norwegia",
  "nd": "Ndebele Lor",
  "nds": "Jerman Non Standar",
  "ne": "Nepal",
  "nl": "Walanda",
  "nl_BE": "Flemis",
  "nmg": "Kwasio",
  "nn": "Nynorsk Norwegia",
  "nnh": "Ngiemboon",
  "nus": "Nuer",
  "ny": "Nyanja",
  "nyn": "Nyankole",
  "om": "Oromo",
  "or": "Odia",
  "os": "Ossetia",
  "pa": "Punjab",
  "pl": "Polandia",
  "prg": "Prusia",
  "ps": "Pashto",
  "pt": "Portugis",
  "qu": "Quechua",
  "rm": "Roman",
  "rn": "Rundi",
  "ro": "Rumania",
  "rof": "Rombo",
  "ru": "Rusia",
  "rw": "Kinyarwanda",
  "rwk": "Rwa",
  "sa": "Sanskerta",
  "sah": "Sakha",
  "saq": "Samburu",
  "sbp": "Sangu",
  "sd": "Sindhi",
  "se": "Sami Sisih Lor",
  "seh": "Sena",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "shi": "Tachelhit",
  "si": "Sinhala",
  "sk": "Slowakia",
  "sl": "Slovenia",
  "sm": "Samoa",
  "smn": "Inari Sami",
  "sn": "Shona",
  "so": "Somalia",
  "sq": "Albania",
  "sr": "Serbia",
  "st": "Sotho Sisih Kidul",
  "su": "Sunda",
  "sv": "Swedia",
  "sw": "Swahili",
  "ta": "Tamil",
  "te": "Telugu",
  "teo": "Teso",
  "tg": "Tajik",
  "th": "Thailand",
  "ti": "Tigrinya",
  "tk": "Turkmen",
  "to": "Tonga",
  "tr": "Turki",
  "tt": "Tatar",
  "twq": "Tasawaq",
  "tzm": "Tamazight Atlas Tengah",
  "ug": "Uighur",
  "uk": "Ukraina",
  "und": "Basa Ora Dikenali",
  "ur": "Urdu",
  "uz": "Uzbek",
  "vai": "Vai",
  "vi": "Vietnam",
  "vo": "Volapuk",
  "vun": "Vunjo",
  "wae": "Walser",
  "wo": "Wolof",
  "xh": "Xhosa",
  "xog": "Soga",
  "yav": "Yangben",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yue": "Kanton",
  "zgh": "Tamazight Moroko Standar",
  "zh": "Tyonghwa",
  "zh_Hans": "Tyonghwa (Gampang)",
  "zh_Hant": "Tyonghwa (Tradisional)",
  "zu": "Zulu",
  "zxx": "Konten tanpa linguistik"
};
