const names = {
  "001": "ዓለም",
  "002": "አፍሪካ",
  "005": "ደቡባዊ አሜሪካ",
  "009": "ኦሽኒያ",
  "011": "ምዕራባዊ አፍሪካ",
  "014": "ምስራቃዊ አፍሪካ",
  "015": "ሰሜናዊ አፍሪካ",
  "017": "መካከለኛ አፍሪካ",
  "018": "ደቡባዊ አፍሪካ",
  "019": "አሜሪካዎች",
  "021": "ሰሜናዊ አሜሪካ",
  "029": "ካሪቢያን",
  "034": "ምሥራቃዊ እስያ",
  "039": "ደቡባዊ አውሮፓ",
  "053": "አውስትራሊያ እና ኒው ዚላንድ",
  "054": "ሜላኔሲያ",
  "061": "ፖሊኔዢያ",
  "142": "እስያ",
  "145": "ምዕራባዊ እስያ",
  "150": "አውሮፓ",
  "151": "ምስራቃዊ አውሮፓ",
  "154": "ሰሜናዊ አውሮፓ",
  "155": "ምዕራባዊ አውሮፓ",
  "AC": "አሴንሽን ደሴት",
  "AD": "አንዶራ",
  "AE": "ሕቡራት ኢማራት ዓረብ",
  "AF": "አፍጋኒስታን",
  "AG": "ኣንቲጓን ባሩዳን",
  "AI": "አንጉኢላ",
  "AL": "አልባኒያ",
  "AM": "አርሜኒያ",
  "AO": "አንጐላ",
  "AQ": "አንታርክቲካ",
  "AR": "አርጀንቲና",
  "AS": "ናይ ኣሜሪካ ሳሞኣ",
  "AT": "ኦስትሪያ",
  "AU": "አውስትሬሊያ",
  "AW": "አሩባ",
  "AX": "ደሴታት ኣላንድ",
  "AZ": "አዘርባጃን",
  "BA": "ቦዝንያን ሄርዘጎቪናን",
  "BB": "ባርቤዶስ",
  "BD": "ባንግላዲሽ",
  "BE": "ቤልጄም",
  "BF": "ቡርኪና ፋሶ",
  "BG": "ቡልጌሪያ",
  "BH": "ባህሬን",
  "BI": "ብሩንዲ",
  "BJ": "ቤኒን",
  "BL": "ቅዱስ ባርተለሚይ",
  "BM": "ቤርሙዳ",
  "BN": "ብሩኒ",
  "BO": "ቦሊቪያ",
  "BQ": "ካሪቢያን ኔዘርላንድስ",
  "BR": "ብራዚል",
  "BS": "ባሃማስ",
  "BT": "ቡህታን",
  "BV": "ደሴታት ቦውቬት",
  "BW": "ቦትስዋና",
  "BY": "ቤላሩስ",
  "BZ": "ቤሊዘ",
  "CA": "ካናዳ",
  "CC": "ኮኮስ ኬሊንግ ደሴቶች",
  "CD": "ኮንጎ",
  "CF": "ማእከላይ ኣፍሪቃ ሪፓብሊክ",
  "CG": "ኮንጎ ሪፓብሊክ",
  "CH": "ስዊዘርላንድ",
  "CI": "ኮት ዲቯር",
  "CK": "ደሴታት ኩክ",
  "CL": "ቺሊ",
  "CM": "ካሜሩን",
  "CN": "ቻይና",
  "CO": "ኮሎምቢያ",
  "CP": "ክሊፐርቶን ደሴት",
  "CR": "ኮስታ ሪካ",
  "CU": "ኩባ",
  "CV": "ኬፕ ቬርዴ",
  "CW": "ኩራካዎ",
  "CX": "ደሴታት ክሪስትማስ",
  "CY": "ሳይፕረስ",
  "CZ": "ቼክ ሪፓብሊክ",
  "DE": "ጀርመን",
  "DG": "ዲየጎ ጋርሺያ",
  "DJ": "ጂቡቲ",
  "DK": "ዴንማርክ",
  "DM": "ዶሚኒካ",
  "DO": "ዶመኒካ ሪፓብሊክ",
  "DZ": "አልጄሪያ",
  "EA": "ሲውታን ሜሊላን",
  "EC": "ኢኳዶር",
  "EE": "ኤስቶኒያ",
  "EG": "ግብጽ",
  "EH": "ምዕራባዊ ሳህራ",
  "ER": "ኤርትራ",
  "ES": "ስፔን",
  "ET": "ኢትዮጵያ",
  "Ethi": "ፊደል",
  "FI": "ፊንላንድ",
  "FJ": "ፊጂ",
  "FK": "ደሴታት ፎክላንድ",
  "FM": "ሚክሮኔዢያ",
  "FO": "ደሴታት ፋራኦ",
  "FR": "ፈረንሳይ",
  "GA": "ጋቦን",
  "GB": "እንግሊዝ",
  "GD": "ግሬናዳ",
  "GE": "ጆርጂያ",
  "GF": "ናይ ፈረንሳይ ጉይና",
  "GG": "ገርንሲ",
  "GH": "ጋና",
  "GI": "ጊብራልታር",
  "GL": "ግሪንላንድ",
  "GM": "ጋምቢያ",
  "GN": "ጊኒ",
  "GP": "ጉዋደሉፕ",
  "GQ": "ኢኳቶሪያል ጊኒ",
  "GR": "ግሪክ",
  "GS": "ደሴታት ደቡብ ጆርጂያን ደቡድ ሳንድዊችን",
  "GT": "ጉዋቲማላ",
  "GU": "ጉዋም",
  "GW": "ቢሳዎ",
  "GY": "ጉያና",
  "HK": "ሆንግ ኮንግ",
  "HM": "ደሴታት ሀርድን ማክዶናልድን",
  "HN": "ሆንዱራስ",
  "HR": "ክሮኤሽያ",
  "HT": "ሀይቲ",
  "HU": "ሀንጋሪ",
  "IC": "ደሴታት ካናሪ",
  "ID": "ኢንዶኔዢያ",
  "IE": "አየርላንድ",
  "IL": "እስራኤል",
  "IM": "አይል ኦፍ ማን",
  "IN": "ህንዲ",
  "IO": "ናይ ብሪጣንያ ህንዳዊ ውቅያኖስ ግዝኣት",
  "IQ": "ኢራቅ",
  "IR": "ኢራን",
  "IS": "አይስላንድ",
  "IT": "ጣሊያን",
  "JE": "ጀርሲ",
  "JM": "ጃማይካ",
  "JO": "ጆርዳን",
  "JP": "ጃፓን",
  "KE": "ኬንያ",
  "KG": "ኪርጂስታን",
  "KH": "ካምቦዲያ",
  "KI": "ኪሪባቲ",
  "KM": "ኮሞሮስ",
  "KN": "ቅዱስ ኪትስን ኔቪስን",
  "KP": "ሰሜን ኮሪያ",
  "KR": "ደቡብ ኮሪያ",
  "KW": "ክዌት",
  "KY": "ካይማን ደሴቶች",
  "KZ": "ካዛኪስታን",
  "LA": "ላኦስ",
  "LB": "ሊባኖስ",
  "LC": "ሴንት ሉቺያ",
  "LI": "ሊችተንስታይን",
  "LK": "ሲሪላንካ",
  "LR": "ላይቤሪያ",
  "LS": "ሌሶቶ",
  "LT": "ሊቱዌኒያ",
  "LU": "ሉክሰምበርግ",
  "LV": "ላትቪያ",
  "LY": "ሊቢያ",
  "Latn": "ላቲን",
  "MA": "ሞሮኮ",
  "MC": "ሞናኮ",
  "MD": "ሞልዶቫ",
  "ME": "ሞንቴኔግሮ",
  "MF": "ሴንት ማርቲን",
  "MG": "ማዳጋስካር",
  "MH": "ማርሻል አይላንድ",
  "MK": "ሰሜን መቆዶንያ",
  "ML": "ማሊ",
  "MM": "ማያንማር",
  "MN": "ሞንጎሊያ",
  "MO": "ማካዎ",
  "MP": "ደሴታት ሰሜናዊ ማሪያና",
  "MQ": "ማርቲኒክ",
  "MR": "ሞሪቴኒያ",
  "MS": "ሞንትሴራት",
  "MT": "ማልታ",
  "MU": "ማሩሸስ",
  "MV": "ማልዲቭስ",
  "MW": "ማላዊ",
  "MX": "ሜክሲኮ",
  "MY": "ማሌዢያ",
  "MZ": "ሞዛምቢክ",
  "NA": "ናሚቢያ",
  "NC": "ኒው ካሌዶኒያ",
  "NE": "ኒጀር",
  "NF": "ኖርፎልክ ደሴት",
  "NG": "ናይጄሪያ",
  "NI": "ኒካራጓ",
  "NL": "ኔዘርላንድስ",
  "NO": "ኖርዌ",
  "NP": "ኔፓል",
  "NR": "ናኡሩ",
  "NU": "ኒኡይ",
  "NZ": "ኒው ዚላንድ",
  "OM": "ኦማን",
  "PA": "ፓናማ",
  "PE": "ፔሩ",
  "PF": "ናይ ፈረንሳይ ፖሊነዝያ",
  "PG": "ፓፑዋ ኒው ጊኒ",
  "PH": "ፊሊፒንስ",
  "PK": "ፓኪስታን",
  "PL": "ፖላንድ",
  "PM": "ቅዱስ ፒዬርን ሚኩኤሎን",
  "PN": "ፒትካኢርን",
  "PR": "ፖርታ ሪኮ",
  "PS": "ምምሕዳር ፍልስጤም",
  "PT": "ፖርቱጋል",
  "PW": "ፓላው",
  "PY": "ፓራጓይ",
  "QA": "ቀጠር",
  "QO": "ወጣ ያለ ኦሽኒያ",
  "RE": "ሪዩኒየን",
  "RO": "ሮሜኒያ",
  "RS": "ሰርቢያ",
  "RU": "ራሺያ",
  "RW": "ሩዋንዳ",
  "SA": "ስዑዲ ዓረብ",
  "SB": "ሰሎሞን ደሴት",
  "SC": "ሲሼልስ",
  "SD": "ሱዳን",
  "SE": "ስዊድን",
  "SG": "ሲንጋፖር",
  "SH": "ሴንት ሄለና",
  "SI": "ስሎቬኒያ",
  "SJ": "ስቫልባርድን ዣን ማየን ደሴታት",
  "SK": "ስሎቫኪያ",
  "SL": "ሴራሊዮን",
  "SM": "ሳን ማሪኖ",
  "SN": "ሴኔጋል",
  "SO": "ሱማሌ",
  "SR": "ሱሪናም",
  "SS": "ደቡብ ሱዳን",
  "ST": "ሳኦ ቶሜን ፕሪንሲፔን",
  "SV": "ኤል ሳልቫዶር",
  "SX": "ሲንት ማርቲን",
  "SY": "ሲሪያ",
  "SZ": "ሱዋዚላንድ",
  "TA": "ትሪስን ዳ ኩንሃ",
  "TC": "ደሴታት ቱርክን ካይኮስን",
  "TD": "ጫድ",
  "TF": "ናይ ፈረንሳይ ደቡባዊ ግዝኣታት",
  "TG": "ቶጐ",
  "TH": "ታይላንድ",
  "TJ": "ታጃኪስታን",
  "TK": "ቶክላው",
  "TL": "ምብራቕ ቲሞር",
  "TM": "ቱርክሜኒስታን",
  "TN": "ቱኒዚያ",
  "TO": "ቶንጋ",
  "TR": "ቱርክ",
  "TT": "ትሪኒዳድን ቶባጎን",
  "TV": "ቱቫሉ",
  "TW": "ታይዋን",
  "TZ": "ታንዛኒያ",
  "UA": "ዩክሬን",
  "UG": "ዩጋንዳ",
  "UM": "ናይ ኣሜሪካ ፍንትት ዝበሉ ደሴታት",
  "US": "አሜሪካ",
  "UY": "ኡራጓይ",
  "UZ": "ዩዝበኪስታን",
  "VA": "ቫቲካን",
  "VC": "ቅዱስ ቪንሴንትን ግሬናዲንስን",
  "VE": "ቬንዙዌላ",
  "VG": "ቨርጂን ደሴታት እንግሊዝ",
  "VI": "ቨርጂን ደሴታት ኣሜሪካ",
  "VN": "ቬትናም",
  "VU": "ቫኑአቱ",
  "WF": "ዋሊስን ፉቱናን",
  "WS": "ሳሞአ",
  "XK": "ኮሶቮ",
  "YE": "የመን",
  "YT": "ሜይኦቴ",
  "ZA": "ደቡብ አፍሪካ",
  "ZM": "ዛምቢያ",
  "ZW": "ዚምቧቤ",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "አፍሪቃንሰኛ",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "አምሐረኛ",
  "am_ET": "Amharic (Ethiopia)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "ዓረበኛ",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Arabic (United Arab Emirates)",
  "ar_BH": "Arabic (Bahrain)",
  "ar_DJ": "Arabic (Djibouti)",
  "ar_DZ": "Arabic (Algeria)",
  "ar_EG": "Arabic (Egypt)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arabic (Eritrea)",
  "ar_IL": "Arabic (Israel)",
  "ar_IQ": "Arabic (Iraq)",
  "ar_JO": "Arabic (Jordan)",
  "ar_KM": "Arabic (Comoros)",
  "ar_KW": "Arabic (Kuwait)",
  "ar_LB": "Arabic (Lebanon)",
  "ar_LY": "Arabic (Libya)",
  "ar_MA": "Arabic (Morocco)",
  "ar_MR": "Arabic (Mauritania)",
  "ar_OM": "Arabic (Oman)",
  "ar_PS": "Arabic (Palestinian Territories)",
  "ar_QA": "Arabic (Qatar)",
  "ar_SA": "Arabic (Saudi Arabia)",
  "ar_SD": "Arabic (Sudan)",
  "ar_SO": "Arabic (Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Arabic (Syria)",
  "ar_TD": "Arabic (Chad)",
  "ar_TN": "Arabic (Tunisia)",
  "ar_YE": "Arabic (Yemen)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "አዜርባይጃንኛ",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "አዜርባይጃንኛ (ላቲን)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "ቤላራሻኛ",
  "be_BY": "Belarusian (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "ቡልጋሪኛ",
  "bg_BG": "Bulgarian (Bulgaria)",
  "bh": "ቢሃሪ",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "በንጋሊኛ",
  "bn_BD": "Bengali (Bangladesh)",
  "bn_IN": "Bengali (India)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "ብሬቶን",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "ቦስኒያን",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "ቦስኒያን (ላቲን)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "ካታላን",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "ቼክኛ",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "ወልሽ",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "ዴኒሽ",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "ጀርመን",
  "de_AT": "German (Austria)",
  "de_BE": "German (Belgium)",
  "de_CH": "German (Switzerland)",
  "de_DE": "German (Germany)",
  "de_LI": "German (Liechtenstein)",
  "de_LU": "German (Luxembourg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "ግሪከኛ",
  "el_CY": "Greek (Cyprus)",
  "el_GR": "Greek (Greece)",
  "elx": "Elamite",
  "en": "እንግሊዝኛ",
  "en_AG": "English (Antigua & Barbuda)",
  "en_AI": "English (Anguilla)",
  "en_AS": "English (American Samoa)",
  "en_AU": "English (Australia)",
  "en_BB": "English (Barbados)",
  "en_BE": "English (Belgium)",
  "en_BM": "English (Bermuda)",
  "en_BS": "English (Bahamas)",
  "en_BW": "English (Botswana)",
  "en_BZ": "English (Belize)",
  "en_CA": "English (Canada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "English (Cook Islands)",
  "en_CM": "English (Cameroon)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "English (Dominica)",
  "en_ER": "English (Eritrea)",
  "en_FJ": "English (Fiji)",
  "en_FK": "English (Falkland Islands)",
  "en_FM": "English (Micronesia)",
  "en_GB": "እንግሊዝኛ (GB)",
  "en_GD": "English (Grenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "English (Ghana)",
  "en_GI": "English (Gibraltar)",
  "en_GM": "English (Gambia)",
  "en_GU": "English (Guam)",
  "en_GY": "English (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "English (Ireland)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "English (India)",
  "en_IO": "English (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "English (Jamaica)",
  "en_KE": "English (Kenya)",
  "en_KI": "English (Kiribati)",
  "en_KN": "English (St. Kitts & Nevis)",
  "en_KY": "English (Cayman Islands)",
  "en_LC": "English (St. Lucia)",
  "en_LR": "English (Liberia)",
  "en_LS": "English (Lesotho)",
  "en_MG": "English (Madagascar)",
  "en_MH": "English (Marshall Islands)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "English (Northern Mariana Islands)",
  "en_MS": "English (Montserrat)",
  "en_MT": "English (Malta)",
  "en_MU": "English (Mauritius)",
  "en_MW": "English (Malawi)",
  "en_MY": "English (Malaysia)",
  "en_NA": "English (Namibia)",
  "en_NF": "English (Norfolk Island)",
  "en_NG": "English (Nigeria)",
  "en_NR": "English (Nauru)",
  "en_NU": "English (Niue)",
  "en_NZ": "English (New Zealand)",
  "en_PG": "English (Papua New Guinea)",
  "en_PH": "English (Philippines)",
  "en_PK": "English (Pakistan)",
  "en_PN": "English (Pitcairn Islands)",
  "en_PR": "English (Puerto Rico)",
  "en_PW": "English (Palau)",
  "en_RW": "English (Rwanda)",
  "en_SB": "English (Solomon Islands)",
  "en_SC": "English (Seychelles)",
  "en_SD": "English (Sudan)",
  "en_SG": "English (Singapore)",
  "en_SH": "English (St. Helena)",
  "en_SL": "English (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "English (Swaziland)",
  "en_TC": "English (Turks & Caicos Islands)",
  "en_TK": "English (Tokelau)",
  "en_TO": "English (Tonga)",
  "en_TT": "English (Trinidad & Tobago)",
  "en_TV": "English (Tuvalu)",
  "en_TZ": "English (Tanzania)",
  "en_UG": "English (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "እንግሊዝኛ (US)",
  "en_VC": "English (St. Vincent & Grenadines)",
  "en_VG": "English (British Virgin Islands)",
  "en_VI": "English (U.S. Virgin Islands)",
  "en_VU": "English (Vanuatu)",
  "en_WS": "English (Samoa)",
  "en_ZA": "English (South Africa)",
  "en_ZM": "English (Zambia)",
  "en_ZW": "English (Zimbabwe)",
  "enm": "Middle English",
  "eo": "ኤስፐራንቶ",
  "es": "ስፓኒሽ",
  "es_419": "Latin American Spanish",
  "es_AR": "Spanish (Argentina)",
  "es_BO": "Spanish (Bolivia)",
  "es_CL": "Spanish (Chile)",
  "es_CO": "Spanish (Colombia)",
  "es_CR": "Spanish (Costa Rica)",
  "es_CU": "Spanish (Cuba)",
  "es_DO": "Spanish (Dominican Republic)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Spanish (Ecuador)",
  "es_ES": "Spanish (Spain)",
  "es_GQ": "Spanish (Equatorial Guinea)",
  "es_GT": "Spanish (Guatemala)",
  "es_HN": "Spanish (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Spanish (Mexico)",
  "es_NI": "Spanish (Nicaragua)",
  "es_PA": "Spanish (Panama)",
  "es_PE": "Spanish (Peru)",
  "es_PH": "Spanish (Philippines)",
  "es_PR": "Spanish (Puerto Rico)",
  "es_PY": "Spanish (Paraguay)",
  "es_SV": "Spanish (El Salvador)",
  "es_US": "Spanish (United States)",
  "es_UY": "Spanish (Uruguay)",
  "es_VE": "Spanish (Venezuela)",
  "esu": "Central Yupik",
  "et": "ኤስቶኒአን",
  "et_EE": "Estonian (Estonia)",
  "eu": "ባስክኛ",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "ፐርሲያኛ",
  "fa_AF": "Persian (Afghanistan)",
  "fa_IR": "Persian (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "ፊኒሽ",
  "fi_FI": "Finnish (Finland)",
  "fil": "ታጋሎገኛ",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "ፋሮኛ",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "ፈረንሳይኛ",
  "fr_BE": "French (Belgium)",
  "fr_BF": "French (Burkina Faso)",
  "fr_BI": "French (Burundi)",
  "fr_BJ": "French (Benin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "French (Canada)",
  "fr_CD": "French (Congo - Kinshasa)",
  "fr_CF": "French (Central African Republic)",
  "fr_CG": "French (Congo - Brazzaville)",
  "fr_CH": "French (Switzerland)",
  "fr_CI": "French (Côte d’Ivoire)",
  "fr_CM": "French (Cameroon)",
  "fr_DJ": "French (Djibouti)",
  "fr_DZ": "French (Algeria)",
  "fr_FR": "French (France)",
  "fr_GA": "French (Gabon)",
  "fr_GF": "French (French Guiana)",
  "fr_GN": "French (Guinea)",
  "fr_GP": "French (Guadeloupe)",
  "fr_GQ": "French (Equatorial Guinea)",
  "fr_HT": "French (Haiti)",
  "fr_KM": "French (Comoros)",
  "fr_LU": "French (Luxembourg)",
  "fr_MA": "French (Morocco)",
  "fr_MC": "French (Monaco)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "French (Madagascar)",
  "fr_ML": "French (Mali)",
  "fr_MQ": "French (Martinique)",
  "fr_MR": "French (Mauritania)",
  "fr_MU": "French (Mauritius)",
  "fr_NC": "French (New Caledonia)",
  "fr_NE": "French (Niger)",
  "fr_PF": "French (French Polynesia)",
  "fr_PM": "French (St. Pierre & Miquelon)",
  "fr_RE": "French (Réunion)",
  "fr_RW": "French (Rwanda)",
  "fr_SC": "French (Seychelles)",
  "fr_SN": "French (Senegal)",
  "fr_SY": "French (Syria)",
  "fr_TD": "French (Chad)",
  "fr_TG": "French (Togo)",
  "fr_TN": "French (Tunisia)",
  "fr_VU": "French (Vanuatu)",
  "fr_WF": "French (Wallis & Futuna)",
  "fr_YT": "French (Mayotte)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "ፍሪሰኛ",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "አይሪሽ",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "እስኮትስ ጌልክኛ",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "ጋለቪኛ",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "ጓራኒ",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "ጉጃራቲኛ",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "ዕብራስጥ",
  "he_IL": "Hebrew (Israel)",
  "hi": "ሕንደኛ",
  "hi_IN": "Hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "ክሮሽያንኛ",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "ሀንጋሪኛ",
  "hu_HU": "Hungarian (Hungary)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "ኢንቴር ቋንቋ",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "እንዶኑሲኛ",
  "id_ID": "Indonesian (Indonesia)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "አይስላንደኛ",
  "is_IS": "Icelandic (Iceland)",
  "it": "ጣሊያንኛ",
  "it_CH": "Italian (Switzerland)",
  "it_IT": "Italian (Italy)",
  "it_SM": "Italian (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "ጃፓንኛ",
  "ja_JP": "Japanese (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "ጃቫንኛ",
  "ka": "ጊዮርጊያኛ",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodia)",
  "kmb": "Kimbundu",
  "kn": "ካማደኛ",
  "kn_IN": "Kannada (India)",
  "ko": "ኮሪያኛ",
  "ko_KP": "Korean (North Korea)",
  "ko_KR": "Korean (South Korea)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "ኩርድሽ",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "ኪሩጋዚ",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "ላቲንኛ",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "ሊቱአኒየን",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "ላቲቪያን",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "ማክዶኒኛ",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "ማላያላምኛ",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "ማራቲኛ",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "ማላይኛ",
  "ms_BN": "Malay (Brunei)",
  "ms_Latn": "ማላይኛ (ላቲን)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malay (Singapore)",
  "mt": "ማልቲስኛ",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Burmese",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "ኔፖሊኛ",
  "ne_IN": "Nepali (India)",
  "ne_NP": "Nepali (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "ደች",
  "nl_AW": "Dutch (Aruba)",
  "nl_BE": "Dutch (Belgium)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Dutch (Netherlands)",
  "nl_SR": "Dutch (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "ኖርዌይኛ (ናይ ኝኖርስክ)",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "ኖርዌጂያን",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "ኦኪታንኛ",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "ኦሪያ",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "ፑንጃቢኛ",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "ፖሊሽ",
  "pl_PL": "Polish (Poland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "ፓሽቶ",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "ፖርቱጋሊኛ",
  "pt_AO": "Portuguese (Angola)",
  "pt_BR": "ፖርቱጋልኛ (ናይ ብራዚል)",
  "pt_CV": "Portuguese (Cape Verde)",
  "pt_GW": "Portuguese (Guinea-Bissau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Portuguese (Mozambique)",
  "pt_PT": "ፖርቱጋልኛ (ናይ ፖርቱጋል)",
  "pt_ST": "Portuguese (São Tomé & Príncipe)",
  "pt_TL": "Portuguese (Timor-Leste)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "ሮማኒያን",
  "ro_MD": "Romanian (Moldova)",
  "ro_RO": "Romanian (Romania)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "ራሽኛ",
  "ru_BY": "Russian (Belarus)",
  "ru_KG": "Russian (Kyrgyzstan)",
  "ru_KZ": "Russian (Kazakhstan)",
  "ru_MD": "Russian (Moldova)",
  "ru_RU": "Russian (Russia)",
  "ru_UA": "Russian (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "ሰርቦ- ክሮዊታን",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "ስንሃልኛ",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "ስሎቨክኛ",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "ስቁቪኛ",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somali",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "Sogdien",
  "sq": "አልቤኒኛ",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "ሰርቢኛ",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "ሰርቢኛ (ላቲን)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "ሰሴቶ",
  "stq": "Saterland Frisian",
  "su": "ሱዳንኛ",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "ስዊድንኛ",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Swedish (Finland)",
  "sv_SE": "Swedish (Sweden)",
  "sw": "ሰዋሂሊኛ",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "ታሚልኛ",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Malaysia)",
  "ta_SG": "Tamil (Singapore)",
  "tcy": "Tulu",
  "te": "ተሉጉኛ",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "ታይኛ",
  "th_TH": "Thai (Thailand)",
  "ti": "ትግርኛ",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "ናይ ቱርኪ ሰብዓይ (ቱርካዊ)",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "ክሊንግኦንኛ",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "ቱርከኛ",
  "tr_CY": "Turkish (Cyprus)",
  "tr_TR": "Turkish (Turkey)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "ትዊ",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "ዩክረኒኛ",
  "uk_UA": "Ukrainian (Ukraine)",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "ኡርዱኛ",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "ኡዝበክኛ",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "ኡዝበክኛ (ላቲን)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "ቪትናምኛ",
  "vi_VN": "Vietnamese (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "ዞሳኛ",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "ዪዲሽ",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "Chinese",
  "zh_CN": "Chinese (China)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Chinese (Singapore)",
  "zh_TW": "Chinese (Taiwan)",
  "zu": "ዙሉኛ",
  "zu_ZA": "Zulu (South Africa)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
