const names = {
  "009": "Oceânia",
  "015": "Norte de África",
  "018": "África Austral",
  "029": "Caraíbas",
  "034": "Ásia do Sul",
  "039": "Europa do Sul",
  "154": "Europa do Norte",
  "202": "África subsariana",
  "AC": "Ascensão",
  "AE": "Emiratos Árabes Unidos",
  "AM": "Arménia",
  "AQ": "Antárctica",
  "AX": "Alanda",
  "Aran": "nasta’liq",
  "Armi": "aramaico imperial",
  "Armn": "arménio",
  "BD": "Bangladeche",
  "BF": "Burkina-Faso",
  "BH": "Barém",
  "BJ": "Benim",
  "BS": "Baamas",
  "BW": "Botswana",
  "Beng": "bengalês",
  "Blis": "símbolos Bliss",
  "CC": "Ilhas dos Cocos (Keeling)",
  "CD": "Congo-Kinshasa",
  "CG": "Congo-Brazzaville",
  "CI": "Côte d’Ivoire (Costa do Marfim)",
  "CW": "Curaçau",
  "CX": "Ilha do Natal",
  "CZ": "Chéquia",
  "Cakm": "chakma",
  "DJ": "Jibuti",
  "DM": "Domínica",
  "EA": "Ceuta e Melilha",
  "EE": "Estónia",
  "EG": "Egipto",
  "EH": "Sara Ocidental",
  "EZ": "Zona Euro",
  "Egyd": "egípcio demótico",
  "Egyh": "egípcio hierático",
  "Ethi": "etíope",
  "FK": "Ilhas Malvinas (Falkland)",
  "FM": "Estados Federados da Micronésia",
  "FO": "Ilhas Faroé",
  "FX": "França (continental)",
  "GB": "GB",
  "GG": "Guernesey",
  "GL": "Gronelândia",
  "GU": "Guame",
  "HK": "Região Administrativa Especial de Hong Kong",
  "Hanb": "han com bopomofo",
  "IR": "Irão",
  "Inds": "indus",
  "KE": "Quénia",
  "KG": "Quirguizistão",
  "KI": "Quiribáti",
  "KN": "São Cristóvão e Neves",
  "KW": "Koweit",
  "KY": "Ilhas Caimão",
  "Kthi": "kaithi",
  "LA": "Laos, República Popular Democrática do",
  "LI": "Listenstaine",
  "LK": "Sri Lanca",
  "LV": "Letónia",
  "Laoo": "Lao",
  "MC": "Mónaco",
  "MD": "Moldávia",
  "MG": "Madagáscar",
  "MK": "Macedónia do Norte",
  "MO": "Região Administrativa Especial de Macau",
  "MP": "Ilhas Mariana do Norte",
  "MS": "Monserrate",
  "MU": "Maurícia",
  "MW": "Maláui",
  "Mand": "mandeu",
  "NC": "Nova Caledónia",
  "NU": "Niuê",
  "Orya": "odia",
  "PG": "Papuásia-Nova Guiné",
  "PL": "Polónia",
  "PS": "Territórios palestinianos",
  "Phli": "pahlavi escrito",
  "Prti": "parthian escrito",
  "QA": "Qatar",
  "QO": "Oceânia Insular",
  "RO": "Roménia",
  "SI": "Eslovénia",
  "SM": "São Marinho",
  "SV": "Salvador",
  "SX": "São Martinho (Sint Maarten)",
  "Sgnw": "escrita gestual",
  "Sylo": "siloti nagri",
  "TF": "Territórios Austrais Franceses",
  "TJ": "Tajiquistão",
  "TK": "Toquelau",
  "TM": "Turquemenistão",
  "TT": "Trindade e Tobago",
  "Tale": "tai le",
  "Taml": "tamil",
  "Telu": "telugu",
  "UM": "Ilhas Menores Afastadas dos EUA",
  "UZ": "Usbequistão",
  "VI": "Ilhas Virgens dos EUA",
  "VN": "Vietname",
  "XA": "pseudoacentos",
  "XB": "pseudobidirecional",
  "Xsux": "cuneiforme sumero-acadiano",
  "YE": "Iémen",
  "YT": "Maiote",
  "ZW": "Zimbabué",
  "Zsye": "emoji",
  "Zsym": "símbolos",
  "Zxxx": "não escrito",
  "Zzzz": "inválido ou desconhecido",
  "af": "africanês",
  "af_NA": "africânder (Namíbia)",
  "af_ZA": "africânder (África do Sul)",
  "alt": "altai do sul",
  "ang": "inglês antigo",
  "ar_001": "árabe moderno padrão",
  "ar_BH": "árabe (Barém)",
  "ar_DJ": "árabe (Jibuti)",
  "ar_EG": "árabe (Egipto)",
  "ar_PS": "árabe (Território Palestiniano)",
  "ar_YE": "árabe (Iémen)",
  "arn": "mapuche",
  "ars": "árabe do Négede",
  "art": "idioma artifical",
  "av": "avaric",
  "awa": "Awadhi",
  "ay": "aimara",
  "az": "azeri",
  "bai": "bamileke Languages",
  "bax": "bamun",
  "bbj": "ghomala",
  "bn": "bengalês",
  "bua": "buriat",
  "bug": "Buginese",
  "ccp": "changma",
  "ce": "chechene",
  "cel": "idioma céltico",
  "chk": "chuquês",
  "chn": "jargão chinook",
  "chr": "cherokee",
  "chy": "cheyenne",
  "ckb": "sorani curdo",
  "co": "córsico",
  "cpe": "crioulo ou pidgin do inglês",
  "cpf": "crioulo ou pidgin do francês",
  "cpp": "crioulo ou pidgin do português",
  "crs": "francês crioulo seselwa",
  "cs": "checo",
  "cs_CZ": "checo (República Checa)",
  "cus": "idioma cuchita",
  "cv": "chuvash",
  "da_GL": "dinamarquês (Gronelândia)",
  "dra": "idioma dravítico",
  "dsb": "baixo sórabio",
  "dyu": "diula",
  "ee": "ewe",
  "ee_GH": "ewe (Gana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egy": "egípcio clássico",
  "en_AI": "inglês (Anguila)",
  "en_BW": "inglês (Botswana)",
  "en_CC": "inglês (Ilhas Cocos)",
  "en_CM": "inglês (Camarões)",
  "en_CX": "inglês (Ilha do Natal)",
  "en_DM": "inglês (Domínica)",
  "en_FK": "inglês (Ilhas Falkland)",
  "en_GU": "inglês (Guame)",
  "en_KE": "inglês (Quénia)",
  "en_KY": "inglês (Ilhas Caimão)",
  "en_MG": "inglês (Madagáscar)",
  "en_MS": "inglês (Monserrate)",
  "en_MU": "inglês (Maurícia)",
  "en_PN": "inglês (Pitcairn)",
  "en_SC": "inglês (Seicheles)",
  "en_SG": "inglês (Singapura)",
  "en_TC": "inglês (Ilhas Turcas e Caicos)",
  "en_TK": "inglês (Toquelau)",
  "en_TT": "inglês (Trindade e Tobago)",
  "en_ZW": "inglês (Zimbabué)",
  "enm": "inglês medieval",
  "et": "estónio",
  "et_EE": "estónio (Estónia)",
  "fa_IR": "persa (Irão)",
  "ff_CM": "fula (Camarões)",
  "fiu": "idioma ugro-finês",
  "fo_FO": "feroês (Ilhas Faroé)",
  "fon": "fon",
  "fr_BJ": "francês (Benim)",
  "fr_CD": "francês (Congo-Kinshasa)",
  "fr_CG": "francês (Congo-Brazzaville)",
  "fr_CM": "francês (Camarões)",
  "fr_DJ": "francês (Jibuti)",
  "fr_MC": "francês (Mónaco)",
  "fr_MG": "francês (Madagáscar)",
  "fr_MU": "francês (Maurícia)",
  "fr_NC": "francês (Nova Caledónia)",
  "fr_SC": "francês (Seicheles)",
  "fr_YT": "francês (Maiote)",
  "frc": "Cajun French",
  "frm": "francês medieval",
  "fro": "francês antigo",
  "frs": "frísio oriental",
  "fy": "frísico ocidental",
  "fy_NL": "frísico ocidental (Países Baixos)",
  "gan": "Gan Chinese",
  "gez": "geʼez",
  "gmh": "alemão medieval alto",
  "goh": "alemão alto antigo",
  "grc": "grego clássico",
  "gsw": "alemão suíço",
  "ha": "haúça",
  "ha_GH": "haúça (Gana)",
  "ha_Latn": "haúça (latim)",
  "ha_Latn_GH": "haúça (latim, Gana)",
  "ha_Latn_NE": "haúça (latim, Níger)",
  "ha_Latn_NG": "haúça (latim, Nigéria)",
  "ha_NE": "haúça (Níger)",
  "ha_NG": "haúça (Nigéria)",
  "hak": "Hakka Chinese",
  "hi": "hindi",
  "hi_IN": "hindi (Índia)",
  "hsb": "sorbiano superior",
  "hsn": "Xiang Chinese",
  "hy": "arménio",
  "hy_AM": "arménio (Arménia)",
  "iba": "Iban",
  "ig_NG": "igbo (Nigéria)",
  "ik": "Inupiaq",
  "it_SM": "italiano (São Marino)",
  "jv": "jv",
  "kbd": "cabardiano",
  "kea": "cabo-verdiano",
  "kg": "conguês",
  "khi": "khoisan",
  "ki_KE": "quicuio (Quénia)",
  "kj": "kuanyama",
  "kl": "gronelandês",
  "kl_GL": "groenlandês (Gronelândia)",
  "km": "cmer",
  "km_KH": "cmer (Camboja)",
  "kn_IN": "canarim (Índia)",
  "krc": "carachaio-bálcaro",
  "krl": "idioma carélio",
  "lez": "lezghiano",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "ln_CD": "lingala (Congo-Kinshasa)",
  "ln_CG": "lingala (Congo-Brazzaville)",
  "lou": "crioulo de Louisiana",
  "lrc": "luri do norte",
  "lu_CD": "luba-catanga (Congo-Kinshasa)",
  "lv_LV": "letão (Letónia)",
  "mak": "makassarês",
  "mg_MG": "malgaxe (Madagáscar)",
  "mga": "irlandês, medieval (900-1200)",
  "mk": "macedónio",
  "mk_MK": "macedónio (Macedónia)",
  "moh": "mohawk",
  "mr": "marata",
  "ms_Latn_SG": "malaio (latim, Singapura)",
  "ms_SG": "malaio (Singapura)",
  "mul": "vários idiomas",
  "mzn": "Mazanderani",
  "nah": "Nauatle",
  "nan": "Min Nan Chinese",
  "nb": "norueguês bokmål",
  "nb_NO": "norueguês bokmål (Noruega)",
  "nb_SJ": "norueguês bokmål (Svalbard e Jan Mayen)",
  "nd_ZW": "ndebele do norte (Zimbabué)",
  "nds": "baixo-alemão",
  "nds_NL": "baixo-saxão",
  "ne": "nepali",
  "nic": "nigeriano - cordofano",
  "nl": "neerlandês",
  "nl_CW": "holandês (Curaçau)",
  "nl_NL": "holandês (Países Baixos)",
  "nn": "norueguês nynorsk",
  "nn_NO": "norueguês nynorsk (Noruega)",
  "non": "nórdico antigo",
  "oc": "occitano",
  "om_KE": "oromo (Quénia)",
  "or": "oriya",
  "os": "ossético",
  "os_GE": "ossético (Geórgia)",
  "os_RU": "ossético (Rússia)",
  "pag": "língua pangasinesa",
  "pam": "pampango",
  "peo": "persa antigo",
  "pl": "polaco",
  "pl_PL": "polaco (Polónia)",
  "pon": "língua pohnpeica",
  "pra": "idioma prácito",
  "prg": "Prussian",
  "pro": "provençal antigo",
  "ps": "pastó",
  "ps_AF": "pastó (Afeganistão)",
  "pt_GW": "português (Guiné-Bissau)",
  "raj": "rajastanês",
  "rm": "Romanche",
  "ro_RO": "romeno (Roménia)",
  "rom": "romanês",
  "root": "Root",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Ruanda)",
  "sai": "idioma indígeno sul-americano",
  "sal": "salishan languages",
  "sco": "escocês",
  "se": "sami do norte",
  "sga": "irlandês antigo",
  "sgn": "linguages de sinais",
  "shu": "árabe do Chade",
  "sl_SI": "esloveno (Eslovénia)",
  "sma": "sami do sul",
  "smj": "lule sami",
  "smn": "inari sami",
  "sms": "skolt sami",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabué)",
  "so_DJ": "somali (Jibuti)",
  "so_KE": "somali (Quénia)",
  "sq_MK": "albanês (Macedónia)",
  "srn": "idioma surinamês",
  "ss": "swati",
  "ssa": "idioma nilo-sariano",
  "sus": "sosso",
  "sw_KE": "suaíli (Quénia)",
  "swb": "língua comoriana",
  "ta": "Tâmil",
  "ta_SG": "tâmil (Singapura)",
  "tai": "idioma tailândes",
  "te": "telugu",
  "tem": "temne",
  "tet": "Tétum",
  "tg": "tajique",
  "tk": "turcomano",
  "to": "tonga",
  "to_TO": "tonga (Tonga)",
  "tog": "toganês",
  "tsi": "tsimshian",
  "tt": "tatar",
  "tzm": "tamazight do Atlas Central",
  "udm": "udmurt",
  "uz": "usbeque",
  "vi_VN": "vietnamita (Vietname)",
  "vot": "votic",
  "wal": "walamo",
  "wbp": "Warlpiri",
  "wen": "idioma sórbio",
  "wo": "uólofe",
  "wuu": "Wu Chinese",
  "xh": "xosa",
  "xog": "soga",
  "yo": "ioruba",
  "yo_BJ": "ioruba (Benim)",
  "zap": "zapoteca",
  "zgh": "tamazight marroquino padrão",
  "zh_Hans": "chinês (han simplificado)",
  "zh_Hans_CN": "chinês (han simplificado, China)",
  "zh_Hans_HK": "chinês (han simplificado, Hong Kong, RAE da China)",
  "zh_Hans_MO": "chinês (han simplificado, Macau, RAE da China)",
  "zh_Hans_SG": "chinês (han simplificado, Singapura)",
  "zh_Hant": "chinês (han tradicional)",
  "zh_Hant_HK": "chinês (han tradicional, Hong Kong, RAE da China)",
  "zh_Hant_MO": "chinês (han tradicional, Macau, RAE da China)",
  "zh_Hant_TW": "chinês (han tradicional, Taiwan)",
  "zh_SG": "chinês (Singapura)",
  "zun": "zuni",
  "zza": "zaza"
};
