const names = {
  "001": "Dünya",
  "002": "Afrika",
  "003": "Kuzey Amerika",
  "005": "Güney Amerika",
  "009": "Okyanusya",
  "011": "Batı Afrika",
  "013": "Orta Amerika",
  "014": "Doğu Afrika",
  "015": "Kuzey Afrika",
  "017": "Orta Afrika",
  "018": "Afrika’nın Güneyi",
  "019": "Amerika",
  "021": "Amerika’nın Kuzeyi",
  "029": "Karayipler",
  "030": "Doğu Asya",
  "034": "Güney Asya",
  "035": "Güneydoğu Asya",
  "039": "Güney Avrupa",
  "053": "Avustralasya",
  "054": "Melanezya",
  "057": "Mikronezya Bölgesi",
  "061": "Polinezya",
  "142": "Asya",
  "143": "Orta Asya",
  "145": "Batı Asya",
  "150": "Avrupa",
  "151": "Doğu Avrupa",
  "154": "Kuzey Avrupa",
  "155": "Batı Avrupa",
  "202": "Sahra Altı Afrika",
  "419": "Latin Amerika",
  "AC": "Ascension Adası",
  "AD": "Andorra",
  "AE": "Birleşik Arap Emirlikleri",
  "AF": "Afganistan",
  "AG": "Antigua ve Barbuda",
  "AI": "Anguilla",
  "AL": "Arnavutluk",
  "AM": "Ermenistan",
  "AN": "Hollanda Antilleri",
  "AO": "Angola",
  "AQ": "Antarktika",
  "AR": "Arjantin",
  "AS": "Amerikan Samoası",
  "AT": "Avusturya",
  "AU": "Avustralya",
  "AW": "Aruba",
  "AX": "Åland Adaları",
  "AZ": "Azerbaycan",
  "Afak": "Afaka",
  "Aghb": "Kafkas Albanyası",
  "Arab": "Arap",
  "Aran": "Nestâlik",
  "Armi": "İmparatorluk Aramicesi",
  "Armn": "Ermeni",
  "Avst": "Avesta",
  "BA": "Bosna-Hersek",
  "BB": "Barbados",
  "BD": "Bangladeş",
  "BE": "Belçika",
  "BF": "Burkina Faso",
  "BG": "Bulgaristan",
  "BH": "Bahreyn",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthelemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivya",
  "BQ": "Karayip Hollandası",
  "BR": "Brezilya",
  "BS": "Bahamalar",
  "BT": "Butan",
  "BV": "Bouvet Adası",
  "BW": "Botsvana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "Bali Dili",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Bengal",
  "Blis": "Blis Sembolleri",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Bugis",
  "Buhd": "Buhid",
  "CA": "Kanada",
  "CC": "Cocos (Keeling) Adaları",
  "CD": "Kongo - Kinşasa",
  "CF": "Orta Afrika Cumhuriyeti",
  "CG": "Kongo - Brazavil",
  "CH": "İsviçre",
  "CI": "Côte d’Ivoire",
  "CK": "Cook Adaları",
  "CL": "Şili",
  "CM": "Kamerun",
  "CN": "Çin",
  "CO": "Kolombiya",
  "CP": "Clipperton Adası",
  "CR": "Kosta Rika",
  "CS": "Sırbistan-Karadağ",
  "CU": "Küba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Adası",
  "CY": "Kıbrıs",
  "CZ": "Çekya",
  "Cakm": "Chakma",
  "Cans": "UCAS",
  "Cari": "Karya",
  "Cham": "Cham",
  "Cher": "Çeroki",
  "Cirt": "Cirth",
  "Copt": "Kıpti",
  "Cprt": "Kıbrıs",
  "Cyrl": "Kiril",
  "Cyrs": "Eski Kilise Slavcası Kiril",
  "DE": "Almanya",
  "DG": "Diego Garcia",
  "DJ": "Cibuti",
  "DK": "Danimarka",
  "DM": "Dominika",
  "DO": "Dominik Cumhuriyeti",
  "DZ": "Cezayir",
  "Deva": "Devanagari",
  "Dsrt": "Deseret",
  "Dupl": "Duployé Stenografi",
  "EA": "Ceuta ve Melilla",
  "EC": "Ekvador",
  "EE": "Estonya",
  "EG": "Mısır",
  "EH": "Batı Sahra",
  "ER": "Eritre",
  "ES": "İspanya",
  "ET": "Etiyopya",
  "EU": "Avrupa Birliği",
  "EZ": "Euro Bölgesi",
  "Egyd": "Demotik Mısır",
  "Egyh": "Hiyeratik Mısır",
  "Egyp": "Mısır Hiyeroglifleri",
  "Elba": "Elbasan",
  "Ethi": "Etiyopya",
  "FI": "Finlandiya",
  "FJ": "Fiji",
  "FK": "Falkland Adaları",
  "FM": "Mikronezya",
  "FO": "Faroe Adaları",
  "FR": "Fransa",
  "FX": "Fransa, Metropolitan",
  "GA": "Gabon",
  "GB": "Birleşik Krallık",
  "GD": "Grenada",
  "GE": "Gürcistan",
  "GF": "Fransız Guyanası",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Cebelitarık",
  "GL": "Grönland",
  "GM": "Gambiya",
  "GN": "Gine",
  "GP": "Guadeloupe",
  "GQ": "Ekvator Ginesi",
  "GR": "Yunanistan",
  "GS": "Güney Georgia ve Güney Sandwich Adaları",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Gine-Bissau",
  "GY": "Guyana",
  "Geok": "Hutsuri Gürcü",
  "Geor": "Gürcü",
  "Glag": "Glagolit",
  "Goth": "Gotik",
  "Gran": "Grantha",
  "Grek": "Yunan",
  "Gujr": "Gücerat",
  "Guru": "Gurmukhi",
  "HK": "Çin Hong Kong ÖİB",
  "HM": "Heard Adası ve McDonald Adaları",
  "HN": "Honduras",
  "HR": "Hırvatistan",
  "HT": "Haiti",
  "HU": "Macaristan",
  "Hanb": "Han - Bopomofo",
  "Hang": "Hangıl",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "Basitleştirilmiş",
  "Hant": "Geleneksel",
  "Hebr": "İbrani",
  "Hira": "Hiragana",
  "Hluw": "Anadolu Hiyeroglifleri",
  "Hmng": "Pahavh Hmong",
  "Hrkt": "Japon hece alfabeleri",
  "Hung": "Eski Macar",
  "IC": "Kanarya Adaları",
  "ID": "Endonezya",
  "IE": "İrlanda",
  "IL": "İsrail",
  "IM": "Man Adası",
  "IN": "Hindistan",
  "IO": "Britanya Hint Okyanusu Toprakları",
  "IQ": "Irak",
  "IR": "İran",
  "IS": "İzlanda",
  "IT": "İtalya",
  "Inds": "Indus",
  "Ital": "Eski İtalyan",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Ürdün",
  "JP": "Japonya",
  "Jamo": "Jamo",
  "Java": "Cava Dili",
  "Jpan": "Japon",
  "Jurc": "Jurchen",
  "KE": "Kenya",
  "KG": "Kırgızistan",
  "KH": "Kamboçya",
  "KI": "Kiribati",
  "KM": "Komorlar",
  "KN": "Saint Kitts ve Nevis",
  "KP": "Kuzey Kore",
  "KR": "Güney Kore",
  "KW": "Kuveyt",
  "KY": "Cayman Adaları",
  "KZ": "Kazakistan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Kmer",
  "Khoj": "Khojki",
  "Knda": "Kannada",
  "Kore": "Korece",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Lübnan",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberya",
  "LS": "Lesotho",
  "LT": "Litvanya",
  "LU": "Lüksemburg",
  "LV": "Letonya",
  "LY": "Libya",
  "Lana": "Lanna",
  "Laoo": "Lao",
  "Latf": "Fraktur Latin",
  "Latg": "Gael Latin",
  "Latn": "Latin",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Lineer A",
  "Linb": "Lineer B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Likya",
  "Lydi": "Lidya",
  "MA": "Fas",
  "MC": "Monako",
  "MD": "Moldova",
  "ME": "Karadağ",
  "MF": "Saint Martin",
  "MG": "Madagaskar",
  "MH": "Marshall Adaları",
  "MK": "Kuzey Makedonya",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Moğolistan",
  "MO": "Çin Makao ÖİB",
  "MP": "Kuzey Mariana Adaları",
  "MQ": "Martinik",
  "MR": "Moritanya",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldivler",
  "MW": "Malavi",
  "MX": "Meksika",
  "MY": "Malezya",
  "MZ": "Mozambik",
  "Mahj": "Mahajani",
  "Mand": "Manden",
  "Maya": "Maya Hiyeroglifleri",
  "Mend": "Mende",
  "Merc": "Meroitik El Yazısı",
  "Mero": "Meroitik",
  "Mlym": "Malayalam",
  "Modi": "Modi",
  "Mong": "Moğol",
  "Moon": "Moon",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mymr": "Burma",
  "NA": "Namibya",
  "NC": "Yeni Kaledonya",
  "NE": "Nijer",
  "NF": "Norfolk Adası",
  "NG": "Nijerya",
  "NI": "Nikaragua",
  "NL": "Hollanda",
  "NO": "Norveç",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Yeni Zelanda",
  "Narb": "Eski Kuzey Arap",
  "Nbat": "Nebati",
  "Nkgb": "Naksi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Umman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orhun",
  "Orya": "Oriya",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Fransız Polinezyası",
  "PG": "Papua Yeni Gine",
  "PH": "Filipinler",
  "PK": "Pakistan",
  "PL": "Polonya",
  "PM": "Saint Pierre ve Miquelon",
  "PN": "Pitcairn Adaları",
  "PR": "Porto Riko",
  "PS": "Filistin Bölgeleri",
  "PT": "Portekiz",
  "PW": "Palau",
  "PY": "Paraguay",
  "Palm": "Palmira",
  "Pauc": "Pau Cin Hau",
  "Perm": "Eski Permik",
  "Phag": "Phags-pa",
  "Phli": "Pehlevi Kitabe Dili",
  "Phlp": "Psalter Pehlevi",
  "Phlv": "Kitap Pehlevi Dili",
  "Phnx": "Fenike",
  "Plrd": "Pollard Fonetik",
  "Prti": "Partça Kitabe Dili",
  "QA": "Katar",
  "QO": "Uzak Okyanusya",
  "Qaag": "Zawgyi",
  "RE": "Reunion",
  "RO": "Romanya",
  "RS": "Sırbistan",
  "RU": "Rusya",
  "RW": "Ruanda",
  "Rjng": "Rejang",
  "Roro": "Rongorongo",
  "Runr": "Runik",
  "SA": "Suudi Arabistan",
  "SB": "Solomon Adaları",
  "SC": "Seyşeller",
  "SD": "Sudan",
  "SE": "İsveç",
  "SG": "Singapur",
  "SH": "Saint Helena",
  "SI": "Slovenya",
  "SJ": "Svalbard ve Jan Mayen",
  "SK": "Slovakya",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somali",
  "SR": "Surinam",
  "SS": "Güney Sudan",
  "ST": "Sao Tome ve Principe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Suriye",
  "SZ": "Esvatini",
  "Samr": "Samarit",
  "Sara": "Sarati",
  "Sarb": "Eski Güney Arap",
  "Saur": "Saurashtra",
  "Sgnw": "İşaret Dili",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudabadi",
  "Sinh": "Seylan",
  "Sora": "Sora Sompeng",
  "Sund": "Sunda",
  "Sylo": "Syloti Nagri",
  "Syrc": "Süryani",
  "Syre": "Estrangela Süryani",
  "Syrj": "Batı Süryani",
  "Syrn": "Doğu Süryani",
  "TA": "Tristan da Cunha",
  "TC": "Turks ve Caicos Adaları",
  "TD": "Çad",
  "TF": "Fransız Güney Toprakları",
  "TG": "Togo",
  "TH": "Tayland",
  "TJ": "Tacikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Türkmenistan",
  "TN": "Tunus",
  "TO": "Tonga",
  "TR": "Türkiye",
  "TT": "Trinidad ve Tobago",
  "TV": "Tuvalu",
  "TW": "Tayvan",
  "TZ": "Tanzanya",
  "Tagb": "Tagbanva",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "New Tai Lue",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Telugu",
  "Teng": "Tengvar",
  "Tfng": "Tifinagh",
  "Tglg": "Takalot",
  "Thaa": "Thaana",
  "Thai": "Tay",
  "Tibt": "Tibet",
  "Tirh": "Tirhuta",
  "UA": "Ukrayna",
  "UG": "Uganda",
  "UM": "ABD Küçük Harici Adaları",
  "UN": "Birleşmiş Milletler",
  "US": "Amerika Birleşik Devletleri",
  "UY": "Uruguay",
  "UZ": "Özbekistan",
  "Ugar": "Ugarit Çivi Yazısı",
  "VA": "Vatikan",
  "VC": "Saint Vincent ve Grenadinler",
  "VE": "Venezuela",
  "VG": "Britanya Virjin Adaları",
  "VI": "ABD Virjin Adaları",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Konuşma Sesleri Çizimlemesi",
  "WF": "Wallis ve Futuna",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wole": "Woleai",
  "XA": "Psödo Aksanlar",
  "XB": "Psödo Bidi",
  "XK": "Kosova",
  "Xpeo": "Eski Fars",
  "Xsux": "Sümer-Akad Çivi Yazısı",
  "YE": "Yemen",
  "YT": "Mayotte",
  "Yiii": "Yi",
  "ZA": "Güney Afrika",
  "ZM": "Zambiya",
  "ZW": "Zimbabve",
  "ZZ": "Bilinmeyen Bölge",
  "Zinh": "Kalıtsal",
  "Zmth": "Matematiksel Gösterim",
  "Zsye": "Emoji",
  "Zsym": "Sembol",
  "Zxxx": "Yazılı Olmayan",
  "Zyyy": "Ortak",
  "Zzzz": "Bilinmeyen Alfabe",
  "aa": "Afar",
  "ab": "Abhazca",
  "ace": "Açece",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adigece",
  "ae": "Avestçe",
  "aeb": "Tunus Arapçası",
  "af": "Afrikaanca",
  "af_NA": "Afrikaanca (Namibya)",
  "af_ZA": "Afrikaanca (Güney Afrika)",
  "afa": "Afro-Asyatik Diller",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ayni Dili",
  "ak": "Akan",
  "ak_GH": "Akan (Gana)",
  "akk": "Akad Dili",
  "akz": "Alabamaca",
  "ale": "Aleut dili",
  "alg": "Algonkin Dili",
  "aln": "Gheg Arnavutçası",
  "alt": "Güney Altayca",
  "am": "Amharca",
  "am_ET": "Amharca (Etiyopya)",
  "an": "Aragonca",
  "ang": "Eski İngilizce",
  "anp": "Angika",
  "apa": "Apaçi Dilleri",
  "ar": "Arapça",
  "ar_001": "Modern Standart Arapça",
  "ar_AE": "Arapça (Birleşik Arap Emirlikleri)",
  "ar_BH": "Arapça (Bahreyn)",
  "ar_DJ": "Arapça (Cibuti)",
  "ar_DZ": "Arapça (Cezayir)",
  "ar_EG": "Arapça (Mısır)",
  "ar_EH": "Arapça (Batı Sahara)",
  "ar_ER": "Arapça (Eritre)",
  "ar_IL": "Arapça (İsrail)",
  "ar_IQ": "Arapça (Irak)",
  "ar_JO": "Arapça (Ürdün)",
  "ar_KM": "Arapça (Komorlar)",
  "ar_KW": "Arapça (Kuveyt)",
  "ar_LB": "Arapça (Lübnan)",
  "ar_LY": "Arapça (Libya)",
  "ar_MA": "Arapça (Fas)",
  "ar_MR": "Arapça (Moritanya)",
  "ar_OM": "Arapça (Umman)",
  "ar_PS": "Arapça (Filistin Bölgeleri)",
  "ar_QA": "Arapça (Katar)",
  "ar_SA": "Arapça (Suudi Arabistan)",
  "ar_SD": "Arapça (Sudan)",
  "ar_SO": "Arapça (Somali)",
  "ar_SS": "Arapça (Güney Sudan)",
  "ar_SY": "Arapça (Suriye)",
  "ar_TD": "Arapça (Çad)",
  "ar_TN": "Arapça (Tunus)",
  "ar_YE": "Arapça (Yemen)",
  "arc": "Aramice",
  "arn": "Mapuçe dili",
  "aro": "Araona",
  "arp": "Arapaho Dili",
  "arq": "Cezayir Arapçası",
  "ars": "Necd Arapçası",
  "art": "Yapay Diller",
  "arw": "Arawak Dili",
  "ary": "Fas Arapçası",
  "arz": "Mısır Arapçası",
  "as": "Assamca",
  "as_IN": "Assamca (Hindistan)",
  "asa": "Asu",
  "ase": "Amerikan İşaret Dili",
  "ast": "Asturyasça",
  "ath": "Atabaşkan Dilleri",
  "aus": "Avustralya Dilleri",
  "av": "Avar Dili",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaycan dili",
  "az_AZ": "Azerice (Azerbaycan)",
  "az_Arab": "Güney Azerice",
  "az_Cyrl": "Azerice (Kiril)",
  "az_Cyrl_AZ": "Azerice (Kiril, Azerbaycan)",
  "az_Latn": "Azerice (Latin)",
  "az_Latn_AZ": "Azerice (Latin, Azerbaycan)",
  "azb": "Güney Azerice",
  "ba": "Başkırtça",
  "bad": "Banda Dili",
  "bai": "Bamileke Dilleri",
  "bal": "Beluçça",
  "ban": "Bali dili",
  "bar": "Bavyera dili",
  "bas": "Basa Dili",
  "bat": "Baltık Dilleri",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarusça",
  "be_BY": "Beyaz Rusça (Beyaz Rusya)",
  "bej": "Beja dili",
  "bem": "Bemba",
  "ber": "Berberi",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgarca",
  "bg_BG": "Bulgarca (Bulgaristan)",
  "bgn": "Batı Balochi",
  "bh": "Bihari",
  "bho": "Arayanice",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar Dili",
  "bkm": "Kom",
  "bla": "Karaayak dili",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bengalce",
  "bn_BD": "Bengalce (Bangladeş)",
  "bn_IN": "Bengalce (Hindistan)",
  "bnt": "Bantu Dili",
  "bo": "Tibetçe",
  "bo_CN": "Tibetçe (Çin)",
  "bo_IN": "Tibetçe (Hindistan)",
  "bpy": "Bishnupriya",
  "bqi": "Bahtiyari",
  "br": "Bretonca",
  "br_FR": "Bretonca (Fransa)",
  "bra": "Braj",
  "brh": "Brohice",
  "brx": "Bodo",
  "bs": "Boşnakça",
  "bs_BA": "Boşnakça (Bosna Hersek)",
  "bs_Cyrl": "Boşnakça (Kiril)",
  "bs_Cyrl_BA": "Boşnakça (Kiril, Bosna Hersek)",
  "bs_Latn": "Boşnakça (Latin)",
  "bs_Latn_BA": "Boşnakça (Latin, Bosna Hersek)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buryatça",
  "bug": "Bugis",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalanca",
  "ca_AD": "Katalanca (Andorra)",
  "ca_ES": "Katalanca (İspanya)",
  "ca_FR": "Katalanca (Fransa)",
  "ca_IT": "Katalanca (İtalya)",
  "cad": "Kado dili",
  "cai": "Orta Amerika Yerli Dilleri",
  "car": "Carib",
  "cau": "Kafkas Dilleri",
  "cay": "Kayuga dili",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Çeçence",
  "ceb": "Sebuano dili",
  "cel": "Kelt Dilleri",
  "cgg": "Kiga",
  "ch": "Çamorro dili",
  "chb": "Çibça dili",
  "chg": "Çağatayca",
  "chk": "Chuukese",
  "chm": "Mari dili",
  "chn": "Çinuk dili",
  "cho": "Çoktav dili",
  "chp": "Çipevya dili",
  "chr": "Çerokice",
  "chy": "Şayence",
  "ckb": "Orta Kürtçe",
  "cmc": "Chamic Dilleri",
  "co": "Korsikaca",
  "cop": "Kıptice",
  "cpe": "İngilizce tabanlı Creole ve Pidgin Dilleri",
  "cpf": "Fransızca tabanlı Creole ve Pidgin Dilleri",
  "cpp": "Portekizce tabanlı Creole ve Pidgin Dilleri",
  "cps": "Capiznon",
  "cr": "Krice",
  "crh": "Kırım Türkçesi",
  "crp": "Creole ve Pidgin Dilleri",
  "crs": "Seselwa Kreole Fransızcası",
  "cs": "Çekçe",
  "cs_CZ": "Çekçe (Çek Cumhuriyeti)",
  "csb": "Kashubian",
  "cu": "Kilise Slavcası",
  "cus": "Kuşitik Diller",
  "cv": "Çuvaşça",
  "cy": "Galce",
  "cy_GB": "Galce (Birleşik Krallık)",
  "da": "Danca",
  "da_DK": "Danca (Danimarka)",
  "da_GL": "Danca (Grönland)",
  "dak": "Dakotaca",
  "dar": "Dargince",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Almanca",
  "de_AT": "Almanca (Avusturya)",
  "de_BE": "Almanca (Belçika)",
  "de_CH": "Almanca (İsviçre)",
  "de_DE": "Almanca (Almanya)",
  "de_LI": "Almanca (Liechtenstein)",
  "de_LU": "Almanca (Lüksemburg)",
  "del": "Delaware",
  "den": "Slavey dili",
  "dgr": "Dogrib",
  "din": "Dinka dili",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Dravid Dilleri",
  "dsb": "Aşağı Sorbça",
  "dtp": "Orta Kadazan",
  "dua": "Duala",
  "dum": "Ortaçağ Felemenkçesi",
  "dv": "Divehi dili",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Butan Dili (Butan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Gana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilia Dili",
  "egy": "Eski Mısır Dili",
  "eka": "Ekajuk",
  "el": "Yunanca",
  "el_CY": "Yunanca (Güney Kıbrıs Rum Kesimi)",
  "el_GR": "Yunanca (Yunanistan)",
  "elx": "Elam",
  "en": "İngilizce",
  "en_AG": "İngilizce (Antigua ve Barbuda)",
  "en_AI": "İngilizce (Anguilla)",
  "en_AS": "İngilizce (Amerikan Samoası)",
  "en_AU": "İngilizce (Avustralya)",
  "en_BB": "İngilizce (Barbados)",
  "en_BE": "İngilizce (Belçika)",
  "en_BM": "İngilizce (Bermuda)",
  "en_BS": "İngilizce (Bahamalar)",
  "en_BW": "İngilizce (Botsvana)",
  "en_BZ": "İngilizce (Belize)",
  "en_CA": "İngilizce (Kanada)",
  "en_CC": "İngilizce (Cocos (Keeling) Adaları)",
  "en_CK": "İngilizce (Cook Adaları)",
  "en_CM": "İngilizce (Kamerun)",
  "en_CX": "İngilizce (Christmas Adası)",
  "en_DG": "İngilizce (Diego Garcia)",
  "en_DM": "İngilizce (Dominika)",
  "en_ER": "İngilizce (Eritre)",
  "en_FJ": "İngilizce (Fiji)",
  "en_FK": "İngilizce (Falkland Adaları)",
  "en_FM": "İngilizce (Mikronezya)",
  "en_GB": "İngilizce (Birleşik Krallık)",
  "en_GD": "İngilizce (Grenada)",
  "en_GG": "İngilizce (Guernsey)",
  "en_GH": "İngilizce (Gana)",
  "en_GI": "İngilizce (Cebelitarık)",
  "en_GM": "İngilizce (Gambiya)",
  "en_GU": "İngilizce (Guam)",
  "en_GY": "İngilizce (Guyana)",
  "en_HK": "İngilizce (Çin Hong Kong ÖYB)",
  "en_IE": "İngilizce (İrlanda)",
  "en_IM": "İngilizce (Man Adası)",
  "en_IN": "İngilizce (Hindistan)",
  "en_IO": "İngilizce (Britanya Hint Okyanusu Toprakları)",
  "en_JE": "İngilizce (Jersey)",
  "en_JM": "İngilizce (Jamaika)",
  "en_KE": "İngilizce (Kenya)",
  "en_KI": "İngilizce (Kiribati)",
  "en_KN": "İngilizce (Saint Kitts ve Nevis)",
  "en_KY": "İngilizce (Cayman Adaları)",
  "en_LC": "İngilizce (Saint Lucia)",
  "en_LR": "İngilizce (Liberya)",
  "en_LS": "İngilizce (Lesoto)",
  "en_MG": "İngilizce (Madagaskar)",
  "en_MH": "İngilizce (Marshall Adaları)",
  "en_MO": "İngilizce (Çin Makao ÖYB)",
  "en_MP": "İngilizce (Kuzey Mariana Adaları)",
  "en_MS": "İngilizce (Montserrat)",
  "en_MT": "İngilizce (Malta)",
  "en_MU": "İngilizce (Mauritius)",
  "en_MW": "İngilizce (Malavi)",
  "en_MY": "İngilizce (Malezya)",
  "en_NA": "İngilizce (Namibya)",
  "en_NF": "İngilizce (Norfolk Adası)",
  "en_NG": "İngilizce (Nijerya)",
  "en_NR": "İngilizce (Nauru)",
  "en_NU": "İngilizce (Niue)",
  "en_NZ": "İngilizce (Yeni Zelanda)",
  "en_PG": "İngilizce (Papua Yeni Gine)",
  "en_PH": "İngilizce (Filipinler)",
  "en_PK": "İngilizce (Pakistan)",
  "en_PN": "İngilizce (Pitcairn Adaları)",
  "en_PR": "İngilizce (Porto Riko)",
  "en_PW": "İngilizce (Palau)",
  "en_RW": "İngilizce (Ruanda)",
  "en_SB": "İngilizce (Solomon Adaları)",
  "en_SC": "İngilizce (Seyşeller)",
  "en_SD": "İngilizce (Sudan)",
  "en_SG": "İngilizce (Singapur)",
  "en_SH": "İngilizce (Saint Helena)",
  "en_SL": "İngilizce (Sierra Leone)",
  "en_SS": "İngilizce (Güney Sudan)",
  "en_SX": "İngilizce (Sint Maarten)",
  "en_SZ": "İngilizce (Svaziland)",
  "en_TC": "İngilizce (Turks ve Caicos Adaları)",
  "en_TK": "İngilizce (Tokelau)",
  "en_TO": "İngilizce (Tonga)",
  "en_TT": "İngilizce (Trinidad ve Tobago)",
  "en_TV": "İngilizce (Tuvalu)",
  "en_TZ": "İngilizce (Tanzanya)",
  "en_UG": "İngilizce (Uganda)",
  "en_UM": "İngilizce (ABD Uzak Adaları)",
  "en_US": "İngilizce (ABD)",
  "en_VC": "İngilizce (Saint Vincent ve Grenadinler)",
  "en_VG": "İngilizce (Britanya Virjin Adaları)",
  "en_VI": "İngilizce (ABD Virjin Adaları)",
  "en_VU": "İngilizce (Vanuatu)",
  "en_WS": "İngilizce (Samoa)",
  "en_ZA": "İngilizce (Güney Afrika)",
  "en_ZM": "İngilizce (Zambiya)",
  "en_ZW": "İngilizce (Zimbabve)",
  "enm": "Ortaçağ İngilizcesi",
  "eo": "Esperanto",
  "es": "İspanyolca",
  "es_419": "Latin Amerika İspanyolcası",
  "es_AR": "İspanyolca (Arjantin)",
  "es_BO": "İspanyolca (Bolivya)",
  "es_CL": "İspanyolca (Şili)",
  "es_CO": "İspanyolca (Kolombiya)",
  "es_CR": "İspanyolca (Kosta Rika)",
  "es_CU": "İspanyolca (Küba)",
  "es_DO": "İspanyolca (Dominik Cumhuriyeti)",
  "es_EA": "İspanyolca (Septe ve Melilla)",
  "es_EC": "İspanyolca (Ekvador)",
  "es_ES": "İspanyolca (İspanya)",
  "es_GQ": "İspanyolca (Ekvator Ginesi)",
  "es_GT": "İspanyolca (Guatemala)",
  "es_HN": "İspanyolca (Honduras)",
  "es_IC": "İspanyolca (Kanarya Adaları)",
  "es_MX": "İspanyolca (Meksika)",
  "es_NI": "İspanyolca (Nikaragua)",
  "es_PA": "İspanyolca (Panama)",
  "es_PE": "İspanyolca (Peru)",
  "es_PH": "İspanyolca (Filipinler)",
  "es_PR": "İspanyolca (Porto Riko)",
  "es_PY": "İspanyolca (Paraguay)",
  "es_SV": "İspanyolca (El Salvador)",
  "es_US": "İspanyolca (ABD)",
  "es_UY": "İspanyolca (Uruguay)",
  "es_VE": "İspanyolca (Venezuela)",
  "esu": "Merkezi Yupikçe",
  "et": "Estonca",
  "et_EE": "Estonca (Estonya)",
  "eu": "Baskça",
  "eu_ES": "Baskça (İspanya)",
  "ewo": "Ewondo",
  "ext": "Ekstremadura Dili",
  "fa": "Farsça",
  "fa_AF": "Farsça (Afganistan)",
  "fa_IR": "Farsça (İran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fula dili",
  "ff_CM": "Fulah (Kamerun)",
  "ff_GN": "Fulah (Gine)",
  "ff_MR": "Fulah (Moritanya)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Fince",
  "fi_FI": "Fince (Finlandiya)",
  "fil": "Filipince",
  "fit": "Tornedalin Fincesi",
  "fiu": "Finno - Ugrik Diller",
  "fj": "Fiji dili",
  "fo": "Faroe dili",
  "fo_FO": "Faroe Dili (Faroe Adaları)",
  "fon": "Fon",
  "fr": "Fransızca",
  "fr_BE": "Fransızca (Belçika)",
  "fr_BF": "Fransızca (Burkina Faso)",
  "fr_BI": "Fransızca (Burundi)",
  "fr_BJ": "Fransızca (Benin)",
  "fr_BL": "Fransızca (Saint Barthelemy)",
  "fr_CA": "Fransızca (Kanada)",
  "fr_CD": "Fransızca (Kongo - Kinşasa)",
  "fr_CF": "Fransızca (Orta Afrika Cumhuriyeti)",
  "fr_CG": "Fransızca (Kongo - Brazavil)",
  "fr_CH": "Fransızca (İsviçre)",
  "fr_CI": "Fransızca (Fildişi Sahili)",
  "fr_CM": "Fransızca (Kamerun)",
  "fr_DJ": "Fransızca (Cibuti)",
  "fr_DZ": "Fransızca (Cezayir)",
  "fr_FR": "Fransızca (Fransa)",
  "fr_GA": "Fransızca (Gabon)",
  "fr_GF": "Fransızca (Fransız Guyanası)",
  "fr_GN": "Fransızca (Gine)",
  "fr_GP": "Fransızca (Guadalupe)",
  "fr_GQ": "Fransızca (Ekvator Ginesi)",
  "fr_HT": "Fransızca (Haiti)",
  "fr_KM": "Fransızca (Komorlar)",
  "fr_LU": "Fransızca (Lüksemburg)",
  "fr_MA": "Fransızca (Fas)",
  "fr_MC": "Fransızca (Monako)",
  "fr_MF": "Fransızca (Saint Martin)",
  "fr_MG": "Fransızca (Madagaskar)",
  "fr_ML": "Fransızca (Mali)",
  "fr_MQ": "Fransızca (Martinik)",
  "fr_MR": "Fransızca (Moritanya)",
  "fr_MU": "Fransızca (Mauritius)",
  "fr_NC": "Fransızca (Yeni Kaledonya)",
  "fr_NE": "Fransızca (Nijer)",
  "fr_PF": "Fransızca (Fransız Polinezyası)",
  "fr_PM": "Fransızca (Saint Pierre ve Miquelon)",
  "fr_RE": "Fransızca (Réunion)",
  "fr_RW": "Fransızca (Ruanda)",
  "fr_SC": "Fransızca (Seyşeller)",
  "fr_SN": "Fransızca (Senegal)",
  "fr_SY": "Fransızca (Suriye)",
  "fr_TD": "Fransızca (Çad)",
  "fr_TG": "Fransızca (Togo)",
  "fr_TN": "Fransızca (Tunus)",
  "fr_VU": "Fransızca (Vanuatu)",
  "fr_WF": "Fransızca (Wallis ve Futuna Adaları)",
  "fr_YT": "Fransızca (Mayotte)",
  "frc": "Cajun Fransızcası",
  "frm": "Ortaçağ Fransızcası",
  "fro": "Eski Fransızca",
  "frp": "Arpitanca",
  "frr": "Kuzey Frizce",
  "frs": "Doğu Frizcesi",
  "fur": "Friuli dili",
  "fy": "Batı Frizcesi",
  "fy_NL": "Batı Frizcesi (Hollanda)",
  "ga": "İrlandaca",
  "ga_IE": "İrlandaca (İrlanda)",
  "gaa": "Ga dili",
  "gag": "Gagavuzca",
  "gan": "Gan Çincesi",
  "gay": "Gayo dili",
  "gba": "Gbaya",
  "gbz": "Zerdüşt Daricesi",
  "gd": "İskoç Gaelcesi",
  "gd_GB": "İskoç Gal Dili (Birleşik Krallık)",
  "gem": "Cermen Dilleri",
  "gez": "Geez",
  "gil": "Kiribatice",
  "gl": "Galiçyaca",
  "gl_ES": "Galiçyaca (İspanya)",
  "glk": "Gilanice",
  "gmh": "Ortaçağ Yüksek Almancası",
  "gn": "Guarani dili",
  "goh": "Eski Yüksek Almanca",
  "gom": "Goa Konkanicesi",
  "gon": "Gondi dili",
  "gor": "Gorontalo dili",
  "got": "Gotça",
  "grb": "Grebo dili",
  "grc": "Antik Yunanca",
  "gsw": "İsviçre Almancası",
  "gu": "Güceratça",
  "gu_IN": "Güceratça (Hindistan)",
  "guc": "Wayuu dili",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Man dili",
  "gv_IM": "Manks (Man Adası)",
  "gwi": "Guçince",
  "ha": "Hausa dili",
  "ha_GH": "Hausa (Gana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Gana)",
  "ha_Latn_NE": "Hausa (Latin, Nijer)",
  "ha_Latn_NG": "Hausa (Latin, Nijerya)",
  "ha_NE": "Hausa (Nijer)",
  "ha_NG": "Hausa (Nijerya)",
  "hai": "Haydaca",
  "hak": "Hakka Çincesi",
  "haw": "Hawaii dili",
  "he": "İbranice",
  "he_IL": "İbranice (İsrail)",
  "hi": "Hintçe",
  "hi_IN": "Hintçe (Hindistan)",
  "hif": "Fiji Hintçesi",
  "hil": "Hiligaynon dili",
  "him": "Himachali",
  "hit": "Hititçe",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Hırvatça",
  "hr_BA": "Hırvatça (Bosna Hersek)",
  "hr_HR": "Hırvatça (Hırvatistan)",
  "hsb": "Yukarı Sorbça",
  "hsn": "Xiang Çincesi",
  "ht": "Haiti Kreyolu",
  "hu": "Macarca",
  "hu_HU": "Macarca (Macaristan)",
  "hup": "Hupaca",
  "hy": "Ermenice",
  "hy_AM": "Ermenice (Ermenistan)",
  "hz": "Herero dili",
  "ia": "İnterlingua",
  "iba": "Iban",
  "ibb": "İbibio dili",
  "id": "Endonezce",
  "id_ID": "Endonezce (Endonezya)",
  "ie": "Interlingue",
  "ig": "İbo dili",
  "ig_NG": "İbo Dili (Nijerya)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (Çin)",
  "ijo": "Ijo",
  "ik": "İnyupikçe",
  "ilo": "Iloko",
  "inc": "Hint Dilleri",
  "ine": "Hint-Avrupa Dilleri",
  "inh": "İnguşça",
  "io": "Ido",
  "ira": "İran Dilleri",
  "iro": "İroqua Dili",
  "is": "İzlandaca",
  "is_IS": "İzlandaca (İzlanda)",
  "it": "İtalyanca",
  "it_CH": "İtalyanca (İsviçre)",
  "it_IT": "İtalyanca (İtalya)",
  "it_SM": "İtalyanca (San Marino)",
  "iu": "İnuktitut dili",
  "izh": "İngriya Dili",
  "ja": "Japonca",
  "ja_JP": "Japonca (Japonya)",
  "jam": "Jamaika Patois Dili",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Yahudi Farsçası",
  "jrb": "Yahudi Arapçası",
  "jut": "Yutland Dili",
  "jv": "Cava dili",
  "ka": "Gürcüce",
  "ka_GE": "Gürcüce (Gürcistan)",
  "kaa": "Karakalpakça",
  "kab": "Kabiliyece",
  "kac": "Kaçin dili",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardeyce",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo dili",
  "kgp": "Kaingang",
  "kha": "Khasi dili",
  "khi": "Hoisan Dilleri",
  "kho": "Hotanca",
  "khq": "Koyra Chiini",
  "khw": "Çitral Dili",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kırmançça",
  "kj": "Kuanyama",
  "kk": "Kazakça",
  "kk_Cyrl": "Kazakça (Kiril)",
  "kk_Cyrl_KZ": "Kazakça (Kiril, Kazakistan)",
  "kk_KZ": "Kazakça (Kazakistan)",
  "kkj": "Kako",
  "kl": "Grönland dili",
  "kl_GL": "Grönland Dili (Grönland)",
  "kln": "Kalenjin",
  "km": "Khmer dili",
  "km_KH": "Kmerce (Kamboçya)",
  "kmb": "Kimbundu",
  "kn": "Kannada dili",
  "kn_IN": "Kannada (Hindistan)",
  "ko": "Korece",
  "ko_KP": "Korece (Kuzey Kore)",
  "ko_KR": "Korece (Güney Kore)",
  "koi": "Komi-Permyak",
  "kok": "Konkani dili",
  "kos": "Kosraean",
  "kpe": "Kpelle dili",
  "kr": "Kanuri dili",
  "krc": "Karaçay-Balkarca",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelyaca",
  "kro": "Kru",
  "kru": "Kurukh dili",
  "ks": "Keşmir dili",
  "ks_Arab": "Keşmirce (Arap)",
  "ks_Arab_IN": "Keşmirce (Arap, Hindistan)",
  "ks_IN": "Keşmirce (Hindistan)",
  "ksb": "Şambala",
  "ksf": "Bafia",
  "ksh": "Köln lehçesi",
  "ku": "Kürtçe",
  "kum": "Kumukça",
  "kut": "Kutenai dili",
  "kv": "Komi",
  "kw": "Kernevekçe",
  "kw_GB": "Kernevekçe (Birleşik Krallık)",
  "ky": "Kırgızca",
  "ky_Cyrl": "Kırgızca (Kiril)",
  "ky_Cyrl_KG": "Kırgızca (Kiril, Kırgızistan)",
  "ky_KG": "Kırgızca (Kırgızistan)",
  "la": "Latince",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba dili",
  "lb": "Lüksemburgca",
  "lb_LU": "Lüksemburgca (Lüksemburg)",
  "lez": "Lezgice",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgca",
  "lij": "Ligurca",
  "liv": "Livonca",
  "lkt": "Lakotaca",
  "lmo": "Lombardça",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Kongo - Kinşasa)",
  "ln_CF": "Lingala (Orta Afrika Cumhuriyeti)",
  "ln_CG": "Lingala (Kongo - Brazavil)",
  "lo": "Lao dili",
  "lo_LA": "Laoca (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Kreolcesi",
  "loz": "Lozi",
  "lrc": "Kuzey Luri",
  "lt": "Litvanca",
  "lt_LT": "Litvanyaca (Litvanya)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Kongo - Kinşasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Lushai",
  "luy": "Luyia",
  "lv": "Letonca",
  "lv_LV": "Letonca (Letonya)",
  "lzh": "Edebi Çince",
  "lzz": "Lazca",
  "mad": "Madura Dili",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Avustronezya Dili",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Mokşa dili",
  "mdr": "Mandar",
  "men": "Mende dili",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malgaşça",
  "mg_MG": "Malgaşça (Madagaskar)",
  "mga": "Ortaçağ İrlandacası",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta’",
  "mh": "Marshall Adaları dili",
  "mi": "Maori dili",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Çeşitli Diller",
  "mk": "Makedonca",
  "mk_MK": "Makedonca (Makedonya)",
  "mkh": "Mon-Khmer Dilleri",
  "ml": "Malayalam dili",
  "ml_IN": "Malayalam (Hindistan)",
  "mn": "Moğolca",
  "mn_Cyrl": "Moğolca (Kiril)",
  "mn_Cyrl_MN": "Moğolca (Kiril, Moğolistan)",
  "mn_MN": "Moğolca (Moğolistan)",
  "mnc": "Mançurya dili",
  "mni": "Manipuri dili",
  "mno": "Manobo Dilleri",
  "mo": "Moldovaca",
  "moh": "Mohavk dili",
  "mos": "Mossi",
  "mr": "Marathi dili",
  "mr_IN": "Marathi (Hindistan)",
  "mrj": "Ova Çirmişçesi",
  "ms": "Malayca",
  "ms_BN": "Malayca (Brunei)",
  "ms_Latn": "Malayca (Latin)",
  "ms_Latn_BN": "Malayca (Latin, Brunei)",
  "ms_Latn_MY": "Malayca (Latin, Malezya)",
  "ms_Latn_SG": "Malayca (Latin, Singapur)",
  "ms_MY": "Malayca (Malezya)",
  "ms_SG": "Malayca (Singapur)",
  "mt": "Maltaca",
  "mt_MT": "Maltaca (Malta)",
  "mua": "Mundang",
  "mul": "Birden Fazla Dil",
  "mun": "Munda Dilleri",
  "mus": "Krikçe",
  "mwl": "Miranda dili",
  "mwr": "Marvari",
  "mwv": "Mentawai",
  "my": "Birman dili",
  "my_MM": "Burmaca (Myanmar (Burma))",
  "mye": "Myene",
  "myn": "Maya Dilleri",
  "myv": "Erzya",
  "mzn": "Mazenderanca",
  "na": "Nauru dili",
  "nah": "Nahuatl",
  "nai": "Kuzey Amerika Yerli Dilleri",
  "nan": "Min Nan Çincesi",
  "nap": "Napolice",
  "naq": "Nama",
  "nb": "Norveççe Bokmål",
  "nb_NO": "Norveççe Bokmål (Norveç)",
  "nb_SJ": "Norveççe Bokmål (Svalbard ve Jan Mayen Adaları)",
  "nd": "Kuzey Ndebele",
  "nd_ZW": "Kuzey Ndebele (Zimbabve)",
  "nds": "Aşağı Almanca",
  "nds_NL": "Aşağı Saksonca",
  "ne": "Nepalce",
  "ne_IN": "Nepalce (Hindistan)",
  "ne_NP": "Nepalce (Nepal)",
  "new": "Nevari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Nijer-Kordofan Dilleri",
  "niu": "Niue dili",
  "njo": "Ao Naga",
  "nl": "Felemenkçe",
  "nl_AW": "Hollandaca (Aruba)",
  "nl_BE": "Hollandaca (Belçika)",
  "nl_BQ": "Hollandaca (Karayip Hollanda)",
  "nl_CW": "Hollandaca (Curaçao)",
  "nl_NL": "Hollandaca (Hollanda)",
  "nl_SR": "Hollandaca (Surinam)",
  "nl_SX": "Hollandaca (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norveççe Nynorsk",
  "nn_NO": "Norveççe Nynorsk (Norveç)",
  "nnh": "Ngiemboon",
  "no": "Norveççe",
  "no_NO": "Norveççe (Norveç)",
  "nog": "Nogayca",
  "non": "Eski Nors dili",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Güney Ndebele",
  "nso": "Kuzey Sotho dili",
  "nub": "Nubian Dilleri",
  "nus": "Nuer",
  "nv": "Navaho dili",
  "nwc": "Klasik Nevari",
  "ny": "Nyanja",
  "nym": "Nyamvezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima dili",
  "oc": "Oksitan dili",
  "oj": "Ojibva dili",
  "om": "Oromo dili",
  "om_ET": "Oromo (Etiyopya)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya Dili",
  "or_IN": "Oriya Dili (Hindistan)",
  "os": "Osetçe",
  "os_GE": "Osetçe (Gürcistan)",
  "os_RU": "Osetçe (Rusya)",
  "osa": "Osage",
  "ota": "Osmanlı Türkçesi",
  "oto": "Otomi Dilleri",
  "pa": "Pencapça",
  "pa_Arab": "Pencapça (Arap)",
  "pa_Arab_PK": "Pencapça (Arap, Pakistan)",
  "pa_Guru": "Pencapça (Gurmukhi)",
  "pa_Guru_IN": "Pencapça (Gurmukhi, Hindistan)",
  "pa_IN": "Pencapça (Hindistan)",
  "pa_PK": "Pencapça (Pakistan)",
  "paa": "Papua Dilleri",
  "pag": "Pangasinan dili",
  "pal": "Pehlevi Dili",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palau dili",
  "pcd": "Picard Dili",
  "pcm": "Nijerya Pidgin dili",
  "pdc": "Pensilvanya Almancası",
  "pdt": "Plautdietsch",
  "peo": "Eski Farsça",
  "pfl": "Palatin Almancası",
  "phi": "Filipinler Dilleri",
  "phn": "Fenike dili",
  "pi": "Pali",
  "pl": "Lehçe",
  "pl_PL": "Lehçe (Polonya)",
  "pms": "Piyemontece",
  "pnt": "Kuzeybatı Kafkasya",
  "pon": "Pohnpeian",
  "pra": "Prakrit Dilleri",
  "prg": "Prusyaca",
  "pro": "Eski Provensal",
  "ps": "Peştuca",
  "ps_AF": "Peştuca (Afganistan)",
  "pt": "Portekizce",
  "pt_AO": "Portekizce (Angola)",
  "pt_BR": "Portekizce (Brezilya)",
  "pt_CV": "Portekizce (Cape Verde)",
  "pt_GW": "Portekizce (Gine-Bissau)",
  "pt_MO": "Portekizce (Çin Makao ÖYB)",
  "pt_MZ": "Portekizce (Mozambik)",
  "pt_PT": "Portekizce (Portekiz)",
  "pt_ST": "Portekizce (São Tomé ve Príncipe)",
  "pt_TL": "Portekizce (Timor-Leste)",
  "qu": "Keçuva dili",
  "qu_BO": "Keçuvaca (Bolivya)",
  "qu_EC": "Keçuvaca (Ekvador)",
  "qu_PE": "Keçuvaca (Peru)",
  "quc": "Kiçece",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui dili",
  "rar": "Rarotongan",
  "rgn": "Romanyolca",
  "rif": "Rif Berbericesi",
  "rm": "Romanşça",
  "rm_CH": "Romanşça (İsviçre)",
  "rn": "Kirundi",
  "rn_BI": "Kirundi (Burundi)",
  "ro": "Rumence",
  "ro_MD": "Romence (Moldova)",
  "ro_RO": "Romence (Romanya)",
  "roa": "Roman Dilleri",
  "rof": "Rombo",
  "rom": "Romanca",
  "root": "Köken",
  "rtm": "Rotuman",
  "ru": "Rusça",
  "ru_BY": "Rusça (Beyaz Rusya)",
  "ru_KG": "Rusça (Kırgızistan)",
  "ru_KZ": "Rusça (Kazakistan)",
  "ru_MD": "Rusça (Moldova)",
  "ru_RU": "Rusça (Rusya)",
  "ru_UA": "Rusça (Ukrayna)",
  "rue": "Rusince",
  "rug": "Roviana",
  "rup": "Ulahça",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Ruanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandave",
  "sah": "Yakutça",
  "sai": "Güney Amerika Yerli Dilleri",
  "sal": "Salishan Dilleri",
  "sam": "Samarit Aramcası",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardunya dili",
  "scn": "Sicilyaca",
  "sco": "İskoçça",
  "sd": "Sindhi dili",
  "sdc": "Sassari Sarduca",
  "sdh": "Güney Kürtçesi",
  "se": "Kuzey Laponcası",
  "se_FI": "Kuzey Sami (Finlandiya)",
  "se_NO": "Kuzey Sami (Norveç)",
  "se_SE": "Kuzey Sami (İsveç)",
  "see": "Seneca dili",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup dili",
  "sem": "Semitik Diller",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Orta Afrika Cumhuriyeti)",
  "sga": "Eski İrlandaca",
  "sgn": "İşaret Dilleri",
  "sgs": "Samogitçe",
  "sh": "Sırp-Hırvat Dili",
  "sh_BA": "Sırp-Hırvat Dili (Bosna Hersek)",
  "shi": "Taşelit",
  "shn": "Shan dili",
  "shu": "Çad Arapçası",
  "si": "Sinhali dili",
  "si_LK": "Seylanca (Sri Lanka)",
  "sid": "Sidamo dili",
  "sio": "Siu Dilleri",
  "sit": "Sino-Tibet Dilleri",
  "sk": "Slovakça",
  "sk_SK": "Slovakça (Slovakya)",
  "sl": "Slovence",
  "sl_SI": "Slovence (Slovenya)",
  "sla": "Slav Dilleri",
  "sli": "Aşağı Silezyaca",
  "sly": "Selayar",
  "sm": "Samoa dili",
  "sma": "Güney Laponcası",
  "smi": "Sami Dilleri",
  "smj": "Lule Laponcası",
  "smn": "İnari Laponcası",
  "sms": "Skolt Laponcası",
  "sn": "Şona dili",
  "sn_ZW": "Shona (Zimbabve)",
  "snk": "Soninke",
  "so": "Somalice",
  "so_DJ": "Somalice (Cibuti)",
  "so_ET": "Somalice (Etiyopya)",
  "so_KE": "Somalice (Kenya)",
  "so_SO": "Somalice (Somali)",
  "sog": "Sogdiana Dili",
  "son": "Songhai",
  "sq": "Arnavutça",
  "sq_AL": "Arnavutça (Arnavutluk)",
  "sq_MK": "Arnavutça (Makedonya)",
  "sq_XK": "Arnavutça (Kosova)",
  "sr": "Sırpça",
  "sr_BA": "Sırpça (Bosna Hersek)",
  "sr_Cyrl": "Sırpça (Kiril)",
  "sr_Cyrl_BA": "Sırpça (Kiril, Bosna Hersek)",
  "sr_Cyrl_ME": "Sırpça (Kiril, Karadağ)",
  "sr_Cyrl_RS": "Sırpça (Kiril, Sırbistan)",
  "sr_Cyrl_XK": "Sırpça (Kiril, Kosova)",
  "sr_Latn": "Sırpça (Latin)",
  "sr_Latn_BA": "Sırpça (Latin, Bosna Hersek)",
  "sr_Latn_ME": "Sırpça (Latin, Karadağ)",
  "sr_Latn_RS": "Sırpça (Latin, Sırbistan)",
  "sr_Latn_XK": "Sırpça (Latin, Kosova)",
  "sr_ME": "Sırpça (Karadağ)",
  "sr_RS": "Sırpça (Sırbistan)",
  "sr_XK": "Sırpça (Kosova)",
  "srn": "Sranan Tongo",
  "srr": "Serer dili",
  "ss": "Sisvati",
  "ssa": "Nil-Sahara Dilleri",
  "ssy": "Saho",
  "st": "Güney Sotho dili",
  "stq": "Saterland Frizcesi",
  "su": "Sunda dili",
  "suk": "Sukuma dili",
  "sus": "Susu",
  "sux": "Sümerce",
  "sv": "İsveççe",
  "sv_AX": "İsveççe (Åland Adaları)",
  "sv_FI": "İsveççe (Finlandiya)",
  "sv_SE": "İsveççe (İsveç)",
  "sw": "Svahili dili",
  "sw_CD": "Kongo Svahili",
  "sw_KE": "Svahili (Kenya)",
  "sw_TZ": "Svahili (Tanzanya)",
  "sw_UG": "Svahili (Uganda)",
  "swb": "Komorca",
  "swc": "Kongo Svahili",
  "syc": "Klasik Süryanice",
  "syr": "Süryanice",
  "szl": "Silezyaca",
  "ta": "Tamilce",
  "ta_IN": "Tamilce (Hindistan)",
  "ta_LK": "Tamilce (Sri Lanka)",
  "ta_MY": "Tamilce (Malezya)",
  "ta_SG": "Tamilce (Singapur)",
  "tai": "Tai Dili",
  "tcy": "Tuluca",
  "te": "Telugu dili",
  "te_IN": "Telugu Dili (Hindistan)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tacikçe",
  "th": "Tayca",
  "th_TH": "Tayca (Tayland)",
  "ti": "Tigrinya dili",
  "ti_ER": "Tigrinya (Eritre)",
  "ti_ET": "Tigrinya (Etiyopya)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Türkmence",
  "tkl": "Tokelau dili",
  "tkr": "Sahurca",
  "tl": "Tagalogca",
  "tl_PH": "Takalotça (Filipinler)",
  "tlh": "Klingonca",
  "tli": "Tlingit",
  "tly": "Talışça",
  "tmh": "Tamaşek",
  "tn": "Setsvana",
  "to": "Tonga dili",
  "to_TO": "Tongaca (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Türkçe",
  "tr_CY": "Türkçe (Güney Kıbrıs Rum Kesimi)",
  "tr_TR": "Türkçe (Türkiye)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonca",
  "tsi": "Tsimshian",
  "tt": "Tatarca",
  "ttt": "Tatça",
  "tum": "Tumbuka",
  "tup": "Tupi Dilleri",
  "tut": "Altay Dilleri",
  "tvl": "Tuvalyanca",
  "tw": "Tvi",
  "twq": "Tasawaq",
  "ty": "Tahiti dili",
  "tyv": "Tuvaca",
  "tzm": "Orta Atlas Tamazigti",
  "udm": "Udmurtça",
  "ug": "Uygurca",
  "ug_Arab": "Uygurca (Arap)",
  "ug_Arab_CN": "Uygurca (Arap, Çin)",
  "ug_CN": "Uygurca (Çin)",
  "uga": "Ugarit dili",
  "uk": "Ukraynaca",
  "uk_UA": "Ukraynaca (Ukrayna)",
  "umb": "Umbundu",
  "und": "Bilinmeyen Dil",
  "ur": "Urduca",
  "ur_IN": "Urduca (Hindistan)",
  "ur_PK": "Urduca (Pakistan)",
  "uz": "Özbekçe",
  "uz_AF": "Özbekçe (Afganistan)",
  "uz_Arab": "Özbekçe (Arap)",
  "uz_Arab_AF": "Özbekçe (Arap, Afganistan)",
  "uz_Cyrl": "Özbekçe (Kiril)",
  "uz_Cyrl_UZ": "Özbekçe (Kiril, Özbekistan)",
  "uz_Latn": "Özbekçe (Latin)",
  "uz_Latn_UZ": "Özbekçe (Latin, Özbekistan)",
  "uz_UZ": "Özbekçe (Özbekistan)",
  "vai": "Vai",
  "ve": "Venda dili",
  "vec": "Venedikçe",
  "vep": "Veps dili",
  "vi": "Vietnamca",
  "vi_VN": "Vietnamca (Vietnam)",
  "vls": "Batı Flamanca",
  "vmf": "Main Frankonya Dili",
  "vo": "Volapük",
  "vot": "Votça",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Valonca",
  "wae": "Walser",
  "wak": "Vakaşan Dilleri",
  "wal": "Valamo",
  "war": "Varay",
  "was": "Vaşo",
  "wbp": "Warlpiri",
  "wen": "Sorb Dilleri",
  "wo": "Volofça",
  "wuu": "Wu Çincesi",
  "xal": "Kalmıkça",
  "xh": "Zosa dili",
  "xmf": "Megrelce",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapça",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yidiş",
  "yo": "Yorubaca",
  "yo_BJ": "Yorubaca (Benin)",
  "yo_NG": "Yorubaca (Nijerya)",
  "ypk": "Yupik Dili",
  "yrl": "Nheengatu",
  "yue": "Kantonca",
  "za": "Zhuangca",
  "zap": "Zapotek dili",
  "zbl": "Blis Sembolleri",
  "zea": "Zelandaca",
  "zen": "Zenaga dili",
  "zgh": "Standart Fas Tamazigti",
  "zh": "Çince",
  "zh_CN": "Çince (Çin)",
  "zh_HK": "Çince (Çin Hong Kong ÖYB)",
  "zh_Hans": "Çince (Basitleştirilmiş)",
  "zh_Hans_CN": "Çince (Basitleştirilmiş, Çin)",
  "zh_Hans_HK": "Çince (Basitleştirilmiş, Çin Hong Kong ÖYB)",
  "zh_Hans_MO": "Çince (Basitleştirilmiş, Çin Makao ÖYB)",
  "zh_Hans_SG": "Çince (Basitleştirilmiş, Singapur)",
  "zh_Hant": "Çince (Geleneksel)",
  "zh_Hant_HK": "Çince (Geleneksel, Çin Hong Kong ÖYB)",
  "zh_Hant_MO": "Çince (Geleneksel, Çin Makao ÖYB)",
  "zh_Hant_TW": "Çince (Geleneksel, Tayvan)",
  "zh_MO": "Çince (Çin Makao ÖYB)",
  "zh_SG": "Çince (Singapur)",
  "zh_TW": "Çince (Tayvan)",
  "znd": "Zande",
  "zu": "Zuluca",
  "zu_ZA": "Zuluca (Güney Afrika)",
  "zun": "Zunice",
  "zxx": "Dilbilim içeriği yok",
  "zza": "Zazaca"
};
