const names = {
  "001": "verden",
  "002": "Afrika",
  "003": "Nord-Amerika",
  "005": "Sør-Amerika",
  "009": "Oseania",
  "011": "Vest-Afrika",
  "013": "Mellom-Amerika",
  "014": "Øst-Afrika",
  "015": "Nord-Afrika",
  "017": "Sentral-Afrika",
  "018": "Sørlige Afrika",
  "019": "Amerika",
  "021": "Nordlige Amerika",
  "029": "Karibia",
  "030": "Øst-Asia",
  "034": "Sør-Asia",
  "035": "Sørøst-Asia",
  "039": "Sør-Europa",
  "053": "Australasia",
  "054": "Melanesia",
  "057": "Mikronesia",
  "061": "Polynesia",
  "142": "Asia",
  "143": "Sentral-Asia",
  "145": "Vest-Asia",
  "150": "Europa",
  "151": "Øst-Europa",
  "154": "Nord-Europa",
  "155": "Vest-Europa",
  "202": "Afrika sør for Sahara",
  "419": "Latin-Amerika",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "De forente arabiske emirater",
  "AF": "Afghanistan",
  "AG": "Antigua og Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "De nederlandske antiller",
  "AO": "Angola",
  "AQ": "Antarktis",
  "AR": "Argentina",
  "AS": "Amerikansk Samoa",
  "AT": "Østerrike",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland",
  "AZ": "Aserbajdsjan",
  "Afak": "afaka",
  "Aghb": "kaukasus-albansk",
  "Ahom": "ahom",
  "Arab": "arabisk",
  "Aran": "nastaliq",
  "Armi": "arameisk",
  "Armn": "armensk",
  "Avst": "avestisk",
  "BA": "Bosnia-Hercegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Karibisk Nederland",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvetøya",
  "BW": "Botswana",
  "BY": "Hviterussland",
  "BZ": "Belize",
  "Bali": "balinesisk",
  "Bamu": "bamum",
  "Bass": "bassa vah",
  "Batk": "batak",
  "Beng": "bengalsk",
  "Blis": "blissymbol",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "punktskrift",
  "Bugi": "buginesisk",
  "Buhd": "buhid",
  "CA": "Canada",
  "CC": "Kokosøyene",
  "CD": "Kongo-Kinshasa",
  "CF": "Den sentralafrikanske republikk",
  "CG": "Kongo-Brazzaville",
  "CH": "Sveits",
  "CI": "Elfenbenskysten",
  "CK": "Cookøyene",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "Kina",
  "CO": "Colombia",
  "CP": "Clippertonøya",
  "CR": "Costa Rica",
  "CS": "Serbia og Montenegro",
  "CU": "Cuba",
  "CV": "Kapp Verde",
  "CW": "Curaçao",
  "CX": "Christmasøya",
  "CY": "Kypros",
  "CZ": "Tsjekkia",
  "Cakm": "chakma",
  "Cans": "felles kanadiske urspråksstavelser",
  "Cari": "karisk",
  "Cham": "cham",
  "Cher": "cherokee",
  "Cirt": "cirth",
  "Copt": "koptisk",
  "Cprt": "kypriotisk",
  "Cyrl": "kyrillisk",
  "Cyrs": "kirkeslavisk kyrillisk",
  "DE": "Tyskland",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Danmark",
  "DM": "Dominica",
  "DO": "Den dominikanske republikk",
  "DZ": "Algerie",
  "Deva": "devanagari",
  "Dsrt": "deseret",
  "Dupl": "duployan stenografi",
  "EA": "Ceuta og Melilla",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Egypt",
  "EH": "Vest-Sahara",
  "ER": "Eritrea",
  "ES": "Spania",
  "ET": "Etiopia",
  "EU": "Den europeiske union",
  "EZ": "eurosonen",
  "Egyd": "egyptisk demotisk",
  "Egyh": "egyptisk hieratisk",
  "Egyp": "egyptiske hieroglyfer",
  "Elba": "elbasisk",
  "Ethi": "etiopisk",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falklandsøyene",
  "FM": "Mikronesiaføderasjonen",
  "FO": "Færøyene",
  "FR": "Frankrike",
  "GA": "Gabon",
  "GB": "Storbritannia",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Fransk Guyana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grønland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Ekvatorial-Guinea",
  "GR": "Hellas",
  "GS": "Sør-Georgia og Sør-Sandwichøyene",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "Geok": "georgisk khutsuri",
  "Geor": "georgisk",
  "Glag": "glagolittisk",
  "Goth": "gotisk",
  "Gran": "gammeltamilsk",
  "Grek": "gresk",
  "Gujr": "gujarati",
  "Guru": "gurmukhi",
  "HK": "Hongkong S.A.R. Kina",
  "HM": "Heard- og McDonaldøyene",
  "HN": "Honduras",
  "HR": "Kroatia",
  "HT": "Haiti",
  "HU": "Ungarn",
  "Hanb": "hanb",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanunoo",
  "Hans": "forenklet",
  "Hant": "tradisjonell",
  "Hatr": "hatransk armensk",
  "Hebr": "hebraisk",
  "Hira": "hiragana",
  "Hluw": "anatoliske hieroglyfer",
  "Hmng": "pahawh hmong",
  "Hrkt": "japanske stavelsesskrifter",
  "Hung": "gammelungarsk",
  "IC": "Kanariøyene",
  "ID": "Indonesia",
  "IE": "Irland",
  "IL": "Israel",
  "IM": "Man",
  "IN": "India",
  "IO": "Det britiske territoriet i Indiahavet",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italia",
  "Inds": "indus",
  "Ital": "gammelitalisk",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "Jamo": "jamo",
  "Java": "javanesisk",
  "Jpan": "japansk",
  "Jurc": "jurchen",
  "KE": "Kenya",
  "KG": "Kirgisistan",
  "KH": "Kambodsja",
  "KI": "Kiribati",
  "KM": "Komorene",
  "KN": "Saint Kitts og Nevis",
  "KP": "Nord-Korea",
  "KR": "Sør-Korea",
  "KW": "Kuwait",
  "KY": "Caymanøyene",
  "KZ": "Kasakhstan",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharoshthi",
  "Khmr": "khmer",
  "Khoj": "khojki",
  "Knda": "kannada",
  "Kore": "koreansk",
  "Kpel": "kpelle",
  "Kthi": "kaithisk",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litauen",
  "LU": "Luxemburg",
  "LV": "Latvia",
  "LY": "Libya",
  "Lana": "lanna",
  "Laoo": "laotisk",
  "Latf": "frakturlatinsk",
  "Latg": "gælisk latinsk",
  "Latn": "latinsk",
  "Lepc": "lepcha",
  "Limb": "limbu",
  "Lina": "lineær A",
  "Linb": "lineær B",
  "Lisu": "fraser",
  "Loma": "loma",
  "Lyci": "lykisk",
  "Lydi": "lydisk",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint-Martin",
  "MG": "Madagaskar",
  "MH": "Marshalløyene",
  "MK": "Nord-Makedonia",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao S.A.R. Kina",
  "MP": "Nord-Marianene",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldivene",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "Mahj": "mahajani",
  "Mand": "mandaisk",
  "Mani": "manikeisk",
  "Maya": "maya-hieroglyfer",
  "Mend": "mende",
  "Merc": "meroitisk kursiv",
  "Mero": "meroitisk",
  "Mlym": "malayalam",
  "Modi": "modi",
  "Mong": "mongolsk",
  "Moon": "moon",
  "Mroo": "mro",
  "Mtei": "meitei-mayek",
  "Mult": "multani",
  "Mymr": "burmesisk",
  "NA": "Namibia",
  "NC": "Ny-Caledonia",
  "NE": "Niger",
  "NF": "Norfolkøya",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Nederland",
  "NO": "Norge",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "Narb": "gammelnordarabisk",
  "Nbat": "nabataeansk",
  "Nkgb": "naxi geba",
  "Nkoo": "n’ko",
  "Nshu": "nüshu",
  "OM": "Oman",
  "Ogam": "ogham",
  "Olck": "ol-chiki",
  "Orkh": "orkhon",
  "Orya": "odia",
  "Osma": "osmanya",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Fransk Polynesia",
  "PG": "Papua Ny-Guinea",
  "PH": "Filippinene",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint-Pierre-et-Miquelon",
  "PN": "Pitcairnøyene",
  "PR": "Puerto Rico",
  "PS": "Det palestinske området",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "Palm": "palmyrensk",
  "Pauc": "pau cin hau",
  "Perm": "gammelpermisk",
  "Phag": "phags-pa",
  "Phli": "inskripsjonspahlavi",
  "Phlp": "psalter pahlavi",
  "Phlv": "pahlavi",
  "Phnx": "fønikisk",
  "Plrd": "pollard-fonetisk",
  "Prti": "inskripsjonsparthisk",
  "QA": "Qatar",
  "QO": "Ytre Oseania",
  "Qaag": "zawgyi",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russland",
  "RW": "Rwanda",
  "Rjng": "rejang",
  "Roro": "rongorongo",
  "Runr": "runer",
  "SA": "Saudi-Arabia",
  "SB": "Salomonøyene",
  "SC": "Seychellene",
  "SD": "Sudan",
  "SE": "Sverige",
  "SG": "Singapore",
  "SH": "St. Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard og Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Sør-Sudan",
  "ST": "São Tomé og Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "Samr": "samaritansk",
  "Sara": "sarati",
  "Sarb": "gammelsørarabisk",
  "Saur": "saurashtra",
  "Sgnw": "tegnskrift",
  "Shaw": "shavisk",
  "Shrd": "sharada",
  "Sidd": "siddham",
  "Sind": "khudawadi",
  "Sinh": "singalesisk",
  "Sora": "sora sompeng",
  "Sund": "sundanesisk",
  "Sylo": "syloti nagri",
  "Syrc": "syrisk",
  "Syre": "estrangelosyriakisk",
  "Syrj": "vestlig syriakisk",
  "Syrn": "østlig syriakisk",
  "TA": "Tristan da Cunha",
  "TC": "Turks- og Caicosøyene",
  "TD": "Tsjad",
  "TF": "De franske sørterritorier",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadsjikistan",
  "TK": "Tokelau",
  "TL": "Øst-Timor",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Tyrkia",
  "TT": "Trinidad og Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "tagbanwa",
  "Takr": "takri",
  "Tale": "tai le",
  "Talu": "ny tai lue",
  "Taml": "tamilsk",
  "Tang": "tangut",
  "Tavt": "tai viet",
  "Telu": "telugu",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagalog",
  "Thaa": "taana",
  "Thai": "thai",
  "Tibt": "tibetansk",
  "Tirh": "tirhuta",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "USAs ytre øyer",
  "UN": "FN",
  "US": "USA",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "Ugar": "ugaritisk",
  "VA": "Vatikanstaten",
  "VC": "St. Vincent og Grenadinene",
  "VE": "Venezuela",
  "VG": "De britiske jomfruøyene",
  "VI": "De amerikanske jomfruøyene",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "Visp": "synlig tale",
  "WF": "Wallis og Futuna",
  "WS": "Samoa",
  "Wara": "varang kshiti",
  "Wole": "woleai",
  "XA": "pseudospråk – aksenter",
  "XB": "pseudospråk – RTL",
  "XK": "Kosovo",
  "Xpeo": "gammelpersisk",
  "Xsux": "sumersk-akkadisk kileskrift",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yiii": "yi",
  "ZA": "Sør-Afrika",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "ukjent område",
  "Zinh": "nedarvet",
  "Zmth": "matematisk notasjon",
  "Zsye": "emoji",
  "Zsym": "symboler",
  "Zxxx": "språk uten skrift",
  "Zyyy": "felles",
  "Zzzz": "ukjent skrift",
  "aa": "afar",
  "ab": "abkhasisk",
  "ace": "achinesisk",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adygeisk",
  "ae": "avestisk",
  "aeb": "tunisisk-arabisk",
  "af": "afrikaans",
  "af_NA": "afrikaans (Namibia)",
  "af_ZA": "afrikaans (Sør-Afrika)",
  "afa": "afroasiatisk språk",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Ghana)",
  "akk": "akkadisk",
  "akz": "alabama",
  "ale": "aleutisk",
  "alg": "algonkinsk språk",
  "aln": "gegisk-albansk",
  "alt": "søraltaisk",
  "am": "amharisk",
  "am_ET": "amharisk (Etiopia)",
  "an": "aragonsk",
  "ang": "gammelengelsk",
  "anp": "angika",
  "apa": "apachespråk",
  "ar": "arabisk",
  "ar_001": "moderne standardarabisk",
  "ar_AE": "arabisk (De forente arabiske emirater)",
  "ar_BH": "arabisk (Bahrain)",
  "ar_DJ": "arabisk (Djibouti)",
  "ar_DZ": "arabisk (Algerie)",
  "ar_EG": "arabisk (Egypt)",
  "ar_EH": "arabisk (Vest-Sahara)",
  "ar_ER": "arabisk (Eritrea)",
  "ar_IL": "arabisk (Israel)",
  "ar_IQ": "arabisk (Irak)",
  "ar_JO": "arabisk (Jordan)",
  "ar_KM": "arabisk (Komorene)",
  "ar_KW": "arabisk (Kuwait)",
  "ar_LB": "arabisk (Libanon)",
  "ar_LY": "arabisk (Libya)",
  "ar_MA": "arabisk (Marokko)",
  "ar_MR": "arabisk (Mauritania)",
  "ar_OM": "arabisk (Oman)",
  "ar_PS": "arabisk (Det palestinske området)",
  "ar_QA": "arabisk (Qatar)",
  "ar_SA": "arabisk (Saudi-Arabia)",
  "ar_SD": "arabisk (Sudan)",
  "ar_SO": "arabisk (Somalia)",
  "ar_SS": "arabisk (Sør-Sudan)",
  "ar_SY": "arabisk (Syria)",
  "ar_TD": "arabisk (Tsjad)",
  "ar_TN": "arabisk (Tunisia)",
  "ar_YE": "arabisk (Jemen)",
  "arc": "arameisk",
  "arn": "mapudungun",
  "aro": "araona",
  "arp": "arapaho",
  "arq": "algerisk arabisk",
  "ars": "najdi-arabisk",
  "art": "kunstig språk",
  "arw": "arawak",
  "ary": "marokkansk-arabisk",
  "arz": "egyptisk arabisk",
  "as": "assamesisk",
  "as_IN": "assamisk (India)",
  "asa": "asu",
  "ase": "amerikansk tegnspråk",
  "ast": "asturisk",
  "ath": "athapaskansk språk",
  "aus": "australsk språk",
  "av": "avarisk",
  "avk": "kotava",
  "awa": "avadhi",
  "ay": "aymara",
  "az": "aserbajdsjansk",
  "az_AZ": "aserbajdsjansk (Aserbajdsjan)",
  "az_Cyrl": "aserbajdsjansk (kyrillisk)",
  "az_Cyrl_AZ": "aserbajdsjansk (kyrillisk, Aserbajdsjan)",
  "az_Latn": "aserbajdsjansk (latinsk)",
  "az_Latn_AZ": "aserbajdsjansk (latinsk, Aserbajdsjan)",
  "azb": "South Azerbaijani",
  "ba": "basjkirsk",
  "bad": "banda",
  "bai": "bamilekisk språk",
  "bal": "baluchi",
  "ban": "balinesisk",
  "bar": "bairisk",
  "bas": "basaa",
  "bat": "baltisk språk",
  "bax": "bamun",
  "bbc": "batak toba",
  "bbj": "ghomala",
  "be": "hviterussisk",
  "be_BY": "hviterussisk (Hviterussland)",
  "bej": "beja",
  "bem": "bemba",
  "ber": "berbisk",
  "bew": "betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "badaga",
  "bg": "bulgarsk",
  "bg_BG": "bulgarsk (Bulgaria)",
  "bgn": "vestbalutsji",
  "bh": "bihari",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latinsk)",
  "bm_Latn_ML": "bambara (latinsk, Mali)",
  "bn": "bengali",
  "bn_BD": "bengali (Bangladesh)",
  "bn_IN": "bengali (India)",
  "bnt": "bantu",
  "bo": "tibetansk",
  "bo_CN": "tibetansk (Kina)",
  "bo_IN": "tibetansk (India)",
  "bpy": "bishnupriya",
  "bqi": "bakhtiari",
  "br": "bretonsk",
  "br_FR": "bretonsk (Frankrike)",
  "bra": "braj",
  "brh": "brahui",
  "brx": "bodo",
  "bs": "bosnisk",
  "bs_BA": "bosnisk (Bosnia-Hercegovina)",
  "bs_Cyrl": "bosnisk (kyrillisk)",
  "bs_Cyrl_BA": "bosnisk (kyrillisk, Bosnia-Hercegovina)",
  "bs_Latn": "bosnisk (latinsk)",
  "bs_Latn_BA": "bosnisk (latinsk, Bosnia-Hercegovina)",
  "bss": "akose",
  "btk": "batak",
  "bua": "burjatisk",
  "bug": "buginesisk",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "katalansk",
  "ca_AD": "katalansk (Andorra)",
  "ca_ES": "katalansk (Spania)",
  "ca_FR": "katalansk (Frankrike)",
  "ca_IT": "katalansk (Italia)",
  "cad": "caddo",
  "cai": "sentralamerikansk indiansk språk",
  "car": "karibisk",
  "cau": "kaukasisk språk",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "chakma",
  "ce": "tsjetsjensk",
  "ceb": "cebuansk",
  "cel": "keltisk språk",
  "cgg": "kiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "tsjagatai",
  "chk": "chuukesisk",
  "chm": "mari",
  "chn": "chinook",
  "cho": "choctaw",
  "chp": "chipewiansk",
  "chr": "cherokesisk",
  "chy": "cheyenne",
  "ckb": "kurdisk (sorani)",
  "cmc": "kamisk språk",
  "co": "korsikansk",
  "cop": "koptisk",
  "cpe": "engelskbasert kreol- eller pidginspråk",
  "cpf": "franskbasert kreol- eller pidginspråk",
  "cpp": "portugisiskbasert kreol- eller pidginspråk",
  "cps": "kapiz",
  "cr": "cree",
  "crh": "krimtatarisk",
  "crp": "kreol- eller pidginspråk",
  "crs": "seselwa",
  "cs": "tsjekkisk",
  "cs_CZ": "tsjekkisk (Tsjekkia)",
  "csb": "kasjubisk",
  "cu": "kirkeslavisk",
  "cus": "kusjitisk språk",
  "cv": "tsjuvasjisk",
  "cy": "walisisk",
  "cy_GB": "walisisk (Storbritannia)",
  "da": "dansk",
  "da_DK": "dansk (Danmark)",
  "da_GL": "dansk (Grønland)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "day": "dayak",
  "de": "tysk",
  "de_AT": "tysk (Østerrike)",
  "de_BE": "tysk (Belgia)",
  "de_CH": "tysk (Sveits)",
  "de_DE": "tysk (Tyskland)",
  "de_LI": "tysk (Liechtenstein)",
  "de_LU": "tysk (Luxemburg)",
  "del": "delaware",
  "den": "slavey",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "dravidisk språk",
  "dsb": "lavsorbisk",
  "dtp": "sentraldusun",
  "dua": "duala",
  "dum": "mellomnederlandsk",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "dyula",
  "dz": "dzongkha",
  "dz_BT": "dzongkha (Bhutan)",
  "dzg": "dazaga",
  "ebu": "kiembu",
  "ee": "ewe",
  "ee_GH": "ewe (Ghana)",
  "ee_TG": "ewe (Togo)",
  "efi": "efik",
  "egl": "emiliansk",
  "egy": "gammelegyptisk",
  "eka": "ekajuk",
  "el": "gresk",
  "el_CY": "gresk (Kypros)",
  "el_GR": "gresk (Hellas)",
  "elx": "elamittisk",
  "en": "engelsk",
  "en_AG": "engelsk (Antigua og Barbuda)",
  "en_AI": "engelsk (Anguilla)",
  "en_AS": "engelsk (Amerikansk Samoa)",
  "en_AU": "engelsk (Australia)",
  "en_BB": "engelsk (Barbados)",
  "en_BE": "engelsk (Belgia)",
  "en_BM": "engelsk (Bermuda)",
  "en_BS": "engelsk (Bahamas)",
  "en_BW": "engelsk (Botswana)",
  "en_BZ": "engelsk (Belize)",
  "en_CA": "engelsk (Canada)",
  "en_CC": "engelsk (Kokosøyene)",
  "en_CK": "engelsk (Cookøyene)",
  "en_CM": "engelsk (Kamerun)",
  "en_CX": "engelsk (Christmasøya)",
  "en_DG": "engelsk (Diego Garcia)",
  "en_DM": "engelsk (Dominica)",
  "en_ER": "engelsk (Eritrea)",
  "en_FJ": "engelsk (Fiji)",
  "en_FK": "engelsk (Falklandsøyene)",
  "en_FM": "engelsk (Mikronesiaføderasjonen)",
  "en_GB": "engelsk (Storbritannia)",
  "en_GD": "engelsk (Grenada)",
  "en_GG": "engelsk (Guernsey)",
  "en_GH": "engelsk (Ghana)",
  "en_GI": "engelsk (Gibraltar)",
  "en_GM": "engelsk (Gambia)",
  "en_GU": "engelsk (Guam)",
  "en_GY": "engelsk (Guyana)",
  "en_HK": "engelsk (Hongkong S.A.R. Kina)",
  "en_IE": "engelsk (Irland)",
  "en_IM": "engelsk (Man)",
  "en_IN": "engelsk (India)",
  "en_IO": "engelsk (Britiske territorier i Indiahavet)",
  "en_JE": "engelsk (Jersey)",
  "en_JM": "engelsk (Jamaica)",
  "en_KE": "engelsk (Kenya)",
  "en_KI": "engelsk (Kiribati)",
  "en_KN": "engelsk (St. Kitts og Nevis)",
  "en_KY": "engelsk (Caymanøyene)",
  "en_LC": "engelsk (St. Lucia)",
  "en_LR": "engelsk (Liberia)",
  "en_LS": "engelsk (Lesotho)",
  "en_MG": "engelsk (Madagaskar)",
  "en_MH": "engelsk (Marshalløyene)",
  "en_MO": "engelsk (Macao S.A.R. Kina)",
  "en_MP": "engelsk (Nord-Marianene)",
  "en_MS": "engelsk (Montserrat)",
  "en_MT": "engelsk (Malta)",
  "en_MU": "engelsk (Mauritius)",
  "en_MW": "engelsk (Malawi)",
  "en_MY": "engelsk (Malaysia)",
  "en_NA": "engelsk (Namibia)",
  "en_NF": "engelsk (Norfolkøya)",
  "en_NG": "engelsk (Nigeria)",
  "en_NR": "engelsk (Nauru)",
  "en_NU": "engelsk (Niue)",
  "en_NZ": "engelsk (New Zealand)",
  "en_PG": "engelsk (Papua Ny-Guinea)",
  "en_PH": "engelsk (Filippinene)",
  "en_PK": "engelsk (Pakistan)",
  "en_PN": "engelsk (Pitcairn)",
  "en_PR": "engelsk (Puerto Rico)",
  "en_PW": "engelsk (Palau)",
  "en_RW": "engelsk (Rwanda)",
  "en_SB": "engelsk (Salomonøyene)",
  "en_SC": "engelsk (Seychellene)",
  "en_SD": "engelsk (Sudan)",
  "en_SG": "engelsk (Singapore)",
  "en_SH": "engelsk (St. Helena)",
  "en_SL": "engelsk (Sierra Leone)",
  "en_SS": "engelsk (Sør-Sudan)",
  "en_SX": "engelsk (Sint Maarten)",
  "en_SZ": "engelsk (Swaziland)",
  "en_TC": "engelsk (Turks- og Caicosøyene)",
  "en_TK": "engelsk (Tokelau)",
  "en_TO": "engelsk (Tonga)",
  "en_TT": "engelsk (Trinidad og Tobago)",
  "en_TV": "engelsk (Tuvalu)",
  "en_TZ": "engelsk (Tanzania)",
  "en_UG": "engelsk (Uganda)",
  "en_UM": "engelsk (USAs ytre øyer)",
  "en_US": "engelsk (USA)",
  "en_VC": "engelsk (St. Vincent og Grenadinene)",
  "en_VG": "engelsk (De britiske jomfruøyene)",
  "en_VI": "engelsk (De amerikanske jomfruøyene)",
  "en_VU": "engelsk (Vanuatu)",
  "en_WS": "engelsk (Samoa)",
  "en_ZA": "engelsk (Sør-Afrika)",
  "en_ZM": "engelsk (Zambia)",
  "en_ZW": "engelsk (Zimbabwe)",
  "enm": "mellomengelsk",
  "eo": "esperanto",
  "es": "spansk",
  "es_419": "latinamerikansk spansk",
  "es_AR": "spansk (Argentina)",
  "es_BO": "spansk (Bolivia)",
  "es_CL": "spansk (Chile)",
  "es_CO": "spansk (Colombia)",
  "es_CR": "spansk (Costa Rica)",
  "es_CU": "spansk (Cuba)",
  "es_DO": "spansk (Den dominikanske republikk)",
  "es_EA": "spansk (Ceuta og Melilla)",
  "es_EC": "spansk (Ecuador)",
  "es_ES": "spansk (Spania)",
  "es_GQ": "spansk (Ekvatorial-Guinea)",
  "es_GT": "spansk (Guatemala)",
  "es_HN": "spansk (Honduras)",
  "es_IC": "spansk (Kanariøyene)",
  "es_MX": "spansk (Mexico)",
  "es_NI": "spansk (Nicaragua)",
  "es_PA": "spansk (Panama)",
  "es_PE": "spansk (Peru)",
  "es_PH": "spansk (Filippinene)",
  "es_PR": "spansk (Puerto Rico)",
  "es_PY": "spansk (Paraguay)",
  "es_SV": "spansk (El Salvador)",
  "es_US": "spansk (USA)",
  "es_UY": "spansk (Uruguay)",
  "es_VE": "spansk (Venezuela)",
  "esu": "sentralyupik",
  "et": "estisk",
  "et_EE": "estisk (Estland)",
  "eu": "baskisk",
  "eu_ES": "baskisk (Spania)",
  "ewo": "ewondo",
  "ext": "ekstremaduransk",
  "fa": "persisk",
  "fa_AF": "persisk (Afghanistan)",
  "fa_IR": "persisk (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "fulfulde",
  "ff_CM": "fulani (Kamerun)",
  "ff_GN": "fulani (Guinea)",
  "ff_MR": "fulani (Mauritania)",
  "ff_SN": "fulani (Senegal)",
  "fi": "finsk",
  "fi_FI": "finsk (Finland)",
  "fil": "filipino",
  "fit": "Tornedalen Finnish",
  "fiu": "finsk-ugrisk språk",
  "fj": "fijiansk",
  "fo": "færøysk",
  "fo_FO": "færøysk (Færøyene)",
  "fon": "fon",
  "fr": "fransk",
  "fr_BE": "fransk (Belgia)",
  "fr_BF": "fransk (Burkina Faso)",
  "fr_BI": "fransk (Burundi)",
  "fr_BJ": "fransk (Benin)",
  "fr_BL": "fransk (Saint-Barthélemy)",
  "fr_CA": "fransk (Canada)",
  "fr_CD": "fransk (Kongo-Kinshasa)",
  "fr_CF": "fransk (Den sentralafrikanske republikk)",
  "fr_CG": "fransk (Kongo-Brazzaville)",
  "fr_CH": "fransk (Sveits)",
  "fr_CI": "fransk (Elfenbenskysten)",
  "fr_CM": "fransk (Kamerun)",
  "fr_DJ": "fransk (Djibouti)",
  "fr_DZ": "fransk (Algerie)",
  "fr_FR": "fransk (Frankrike)",
  "fr_GA": "fransk (Gabon)",
  "fr_GF": "fransk (Fransk Guyana)",
  "fr_GN": "fransk (Guinea)",
  "fr_GP": "fransk (Guadeloupe)",
  "fr_GQ": "fransk (Ekvatorial-Guinea)",
  "fr_HT": "fransk (Haiti)",
  "fr_KM": "fransk (Komorene)",
  "fr_LU": "fransk (Luxemburg)",
  "fr_MA": "fransk (Marokko)",
  "fr_MC": "fransk (Monaco)",
  "fr_MF": "fransk (Saint-Martin)",
  "fr_MG": "fransk (Madagaskar)",
  "fr_ML": "fransk (Mali)",
  "fr_MQ": "fransk (Martinique)",
  "fr_MR": "fransk (Mauritania)",
  "fr_MU": "fransk (Mauritius)",
  "fr_NC": "fransk (Ny-Caledonia)",
  "fr_NE": "fransk (Niger)",
  "fr_PF": "fransk (Fransk Polynesia)",
  "fr_PM": "fransk (St. Pierre og Miquelon)",
  "fr_RE": "fransk (Réunion)",
  "fr_RW": "fransk (Rwanda)",
  "fr_SC": "fransk (Seychellene)",
  "fr_SN": "fransk (Senegal)",
  "fr_SY": "fransk (Syria)",
  "fr_TD": "fransk (Tsjad)",
  "fr_TG": "fransk (Togo)",
  "fr_TN": "fransk (Tunisia)",
  "fr_VU": "fransk (Vanuatu)",
  "fr_WF": "fransk (Wallis og Futuna)",
  "fr_YT": "fransk (Mayotte)",
  "frc": "cajunfransk",
  "frm": "mellomfransk",
  "fro": "gammelfransk",
  "frp": "arpitansk",
  "frr": "nordfrisisk",
  "frs": "østfrisisk",
  "fur": "friuliansk",
  "fy": "vestfrisisk",
  "fy_NL": "vestfrisisk (Nederland)",
  "ga": "irsk",
  "ga_IE": "irsk (Irland)",
  "gaa": "ga",
  "gag": "gagausisk",
  "gan": "gan",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "zoroastrisk dari",
  "gd": "skotsk-gælisk",
  "gd_GB": "skotsk gælisk (Storbritannia)",
  "gem": "germansk språk",
  "gez": "geez",
  "gil": "kiribatisk",
  "gl": "galisisk",
  "gl_ES": "galisisk (Spania)",
  "glk": "gileki",
  "gmh": "mellomhøytysk",
  "gn": "guarani",
  "goh": "gammelhøytysk",
  "gom": "goansk konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotisk",
  "grb": "grebo",
  "grc": "gammelgresk",
  "gsw": "sveitsertysk",
  "gu": "gujarati",
  "gu_IN": "gujarati (India)",
  "guc": "wayuu",
  "gur": "frafra",
  "guz": "gusii",
  "gv": "mansk",
  "gv_IM": "mansk (Man)",
  "gwi": "gwichin",
  "ha": "hausa",
  "ha_GH": "hausa (Ghana)",
  "ha_Latn": "hausa (latinsk)",
  "ha_Latn_GH": "hausa (latinsk, Ghana)",
  "ha_Latn_NE": "hausa (latinsk, Niger)",
  "ha_Latn_NG": "hausa (latinsk, Nigeria)",
  "ha_NE": "hausa (Niger)",
  "ha_NG": "hausa (Nigeria)",
  "hai": "haida",
  "hak": "hakka",
  "haw": "hawaiisk",
  "he": "hebraisk",
  "he_IL": "hebraisk (Israel)",
  "hi": "hindi",
  "hi_IN": "hindi (India)",
  "hif": "fijiansk hindi",
  "hil": "hiligaynon",
  "him": "himachali",
  "hit": "hettittisk",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "kroatisk",
  "hr_BA": "kroatisk (Bosnia-Hercegovina)",
  "hr_HR": "kroatisk (Kroatia)",
  "hsb": "høysorbisk",
  "hsn": "xiang",
  "ht": "haitisk",
  "hu": "ungarsk",
  "hu_HU": "ungarsk (Ungarn)",
  "hup": "hupa",
  "hy": "armensk",
  "hy_AM": "armensk (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonesisk",
  "id_ID": "indonesisk (Indonesia)",
  "ie": "interlingue",
  "ig": "ibo",
  "ig_NG": "ibo (Nigeria)",
  "ii": "sichuan-yi",
  "ii_CN": "sichuan-yi (Kina)",
  "ijo": "ijo",
  "ik": "inupiak",
  "ilo": "iloko",
  "inc": "indisk språk",
  "ine": "indoeuropeisk språk",
  "inh": "ingusjisk",
  "io": "ido",
  "ira": "iransk språk",
  "iro": "irokansk språk",
  "is": "islandsk",
  "is_IS": "islandsk (Island)",
  "it": "italiensk",
  "it_CH": "italiensk (Sveits)",
  "it_IT": "italiensk (Italia)",
  "it_SM": "italiensk (San Marino)",
  "iu": "inuktitut",
  "izh": "ingrisk",
  "ja": "japansk",
  "ja_JP": "japansk (Japan)",
  "jam": "jamaicansk kreolengelsk",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "jødepersisk",
  "jrb": "jødearabisk",
  "jut": "jysk",
  "jv": "javanesisk",
  "ka": "georgisk",
  "ka_GE": "georgisk (Georgia)",
  "kaa": "karakalpakisk",
  "kab": "kabylsk",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karensk",
  "kaw": "kawi",
  "kbd": "kabardisk",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "kappverdisk",
  "ken": "kenyang",
  "kfo": "koro",
  "kg": "kikongo",
  "kgp": "kaingang",
  "kha": "khasi",
  "khi": "khoisanspråk",
  "kho": "khotanesisk",
  "khq": "koyra chiini",
  "khw": "khowar",
  "ki": "kikuyu",
  "ki_KE": "kikuyu (Kenya)",
  "kiu": "kirmancki",
  "kj": "kuanyama",
  "kk": "kasakhisk",
  "kk_Cyrl": "kasakhisk (kyrillisk)",
  "kk_Cyrl_KZ": "kasakhisk (kyrillisk, Kasakhstan)",
  "kk_KZ": "kasakhisk (Kasakhstan)",
  "kkj": "kako",
  "kl": "grønlandsk",
  "kl_GL": "grønlandsk (Grønland)",
  "kln": "kalenjin",
  "km": "khmer",
  "km_KH": "khmer (Kambodsja)",
  "kmb": "kimbundu",
  "kn": "kannada",
  "kn_IN": "kannada (India)",
  "ko": "koreansk",
  "ko_KP": "koreansk (Nord-Korea)",
  "ko_KR": "koreansk (Sør-Korea)",
  "koi": "komipermjakisk",
  "kok": "konkani",
  "kos": "kosraeansk",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karatsjajbalkarsk",
  "kri": "krio",
  "krj": "kinaray-a",
  "krl": "karelsk",
  "kro": "kru",
  "kru": "kurukh",
  "ks": "kasjmiri",
  "ks_Arab": "kasjmiri (arabisk)",
  "ks_Arab_IN": "kasjmiri (arabisk, India)",
  "ks_IN": "kasjmiri (India)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kølnsk",
  "ku": "kurdisk",
  "kum": "kumykisk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "kornisk",
  "kw_GB": "kornisk (Storbritannia)",
  "ky": "kirgisisk",
  "ky_Cyrl": "kirgisisk (kyrillisk)",
  "ky_Cyrl_KG": "kirgisisk (kyrillisk, Kirgisistan)",
  "ky_KG": "kirgisisk (Kirgisistan)",
  "la": "latin",
  "lad": "ladinsk",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxemburgsk",
  "lb_LU": "luxemburgsk (Luxemburg)",
  "lez": "lesgisk",
  "lfn": "lingua franca nova",
  "lg": "ganda",
  "lg_UG": "ganda (Uganda)",
  "li": "limburgsk",
  "lij": "ligurisk",
  "liv": "livisk",
  "lkt": "lakota",
  "lmo": "lombardisk",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Kongo-Kinshasa)",
  "ln_CF": "lingala (Den sentralafrikanske republikk)",
  "ln_CG": "lingala (Kongo-Brazzaville)",
  "lo": "laotisk",
  "lo_LA": "laotisk (Laos)",
  "lol": "mongo",
  "lou": "louisianakreolsk",
  "loz": "lozi",
  "lrc": "nord-luri",
  "lt": "litauisk",
  "lt_LT": "litauisk (Litauen)",
  "ltg": "latgallisk",
  "lu": "luba-katanga",
  "lu_CD": "luba-katanga (Kongo-Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "mizo",
  "luy": "luhya",
  "lv": "latvisk",
  "lv_LV": "latvisk (Latvia)",
  "lzh": "klassisk kinesisk",
  "lzz": "lazisk",
  "mad": "maduresisk",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "mandingo",
  "map": "austronesisk språk",
  "mas": "masai",
  "mde": "maba",
  "mdf": "moksja",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "mauritisk-kreolsk",
  "mg": "gassisk",
  "mg_MG": "madagassisk (Madagaskar)",
  "mga": "mellomirsk",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshallesisk",
  "mi": "maori",
  "mic": "micmac",
  "min": "minangkabau",
  "mis": "annet språk",
  "mk": "makedonsk",
  "mk_MK": "makedonsk (Makedonia)",
  "mkh": "mon-khmerspråk",
  "ml": "malayalam",
  "ml_IN": "malayalam (India)",
  "mn": "mongolsk",
  "mn_Cyrl": "mongolsk (kyrillisk)",
  "mn_Cyrl_MN": "mongolsk (kyrillisk, Mongolia)",
  "mn_MN": "mongolsk (Mongolia)",
  "mnc": "mandsju",
  "mni": "manipuri",
  "mno": "manobospråk",
  "mo": "moldavisk",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "marathi",
  "mr_IN": "marathi (India)",
  "mrj": "vestmarisk",
  "ms": "malayisk",
  "ms_BN": "malayisk (Brunei)",
  "ms_Latn": "malayisk (latinsk)",
  "ms_Latn_BN": "malayisk (latinsk, Brunei)",
  "ms_Latn_MY": "malayisk (latinsk, Malaysia)",
  "ms_Latn_SG": "malayisk (latinsk, Singapore)",
  "ms_MY": "malayisk (Malaysia)",
  "ms_SG": "malayisk (Singapore)",
  "mt": "maltesisk",
  "mt_MT": "maltesisk (Malta)",
  "mua": "mundang",
  "mul": "flere språk",
  "mun": "mundaspråk",
  "mus": "creek",
  "mwl": "mirandesisk",
  "mwr": "marwari",
  "mwv": "mentawai",
  "my": "burmesisk",
  "my_MM": "burmesisk (Myanmar (Burma))",
  "mye": "myene",
  "myn": "mayaspråk",
  "myv": "erzia",
  "mzn": "mazandarani",
  "na": "nauru",
  "nah": "nahuatl",
  "nai": "nordamerikansk indiansk språk",
  "nan": "minnan",
  "nap": "napolitansk",
  "naq": "nama",
  "nb": "norsk bokmål",
  "nb_NO": "norsk bokmål (Norge)",
  "nb_SJ": "norsk bokmål (Svalbard og Jan Mayen)",
  "nd": "nord-ndebele",
  "nd_ZW": "nord-ndebele (Zimbabwe)",
  "nds": "nedertysk",
  "nds_NL": "nedersaksisk",
  "ne": "nepali",
  "ne_IN": "nepali (India)",
  "ne_NP": "nepali (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "nic": "niger-kordofiansk språk",
  "niu": "niueansk",
  "njo": "ao naga",
  "nl": "nederlandsk",
  "nl_AW": "nederlandsk (Aruba)",
  "nl_BE": "nederlandsk (Belgia)",
  "nl_BQ": "nederlandsk (Karibisk Nederland)",
  "nl_CW": "nederlandsk (Curaçao)",
  "nl_NL": "nederlandsk (Nederland)",
  "nl_SR": "nederlandsk (Surinam)",
  "nl_SX": "nederlandsk (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "norsk nynorsk",
  "nn_NO": "norsk nynorsk (Norge)",
  "nnh": "ngiemboon",
  "no": "norsk",
  "no_NO": "norsk (Norge)",
  "nog": "nogaisk",
  "non": "gammelnorsk",
  "nov": "novial",
  "nqo": "nʼko",
  "nr": "sør-ndebele",
  "nso": "nord-sotho",
  "nub": "nubisk språk",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "klassisk newari",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "oksitansk",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiopia)",
  "om_KE": "oromo (Kenya)",
  "or": "odia",
  "or_IN": "oriya (India)",
  "os": "ossetisk",
  "os_GE": "ossetisk (Georgia)",
  "os_RU": "ossetisk (Russland)",
  "osa": "osage",
  "ota": "ottomansk tyrkisk",
  "oto": "otomisk språk",
  "pa": "panjabi",
  "pa_Arab": "punjabi (arabisk)",
  "pa_Arab_PK": "punjabi (arabisk, Pakistan)",
  "pa_Guru": "punjabi (gurmukhi)",
  "pa_Guru_IN": "punjabi (gurmukhi, India)",
  "pa_IN": "punjabi (India)",
  "pa_PK": "punjabi (Pakistan)",
  "paa": "papuisk språk",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palauisk",
  "pcd": "pikardisk",
  "pcm": "nigeriansk pidginspråk",
  "pdc": "pennsylvaniatysk",
  "pdt": "plautdietsch",
  "peo": "gammelpersisk",
  "pfl": "palatintysk",
  "phi": "filippinsk språk",
  "phn": "fønikisk",
  "pi": "pali",
  "pl": "polsk",
  "pl_PL": "polsk (Polen)",
  "pms": "piemontesisk",
  "pnt": "pontisk",
  "pon": "ponapisk",
  "pra": "prakritspråk",
  "prg": "prøyssisk",
  "pro": "gammelprovençalsk",
  "ps": "pashto",
  "ps_AF": "pashto (Afghanistan)",
  "pt": "portugisisk",
  "pt_AO": "portugisisk (Angola)",
  "pt_BR": "portugisisk (Brasil)",
  "pt_CV": "portugisisk (Kapp Verde)",
  "pt_GW": "portugisisk (Guinea-Bissau)",
  "pt_MO": "portugisisk (Macao S.A.R. Kina)",
  "pt_MZ": "portugisisk (Mosambik)",
  "pt_PT": "portugisisk (Portugal)",
  "pt_ST": "portugisisk (São Tomé og Príncipe)",
  "pt_TL": "portugisisk (Øst-Timor)",
  "qu": "quechua",
  "qu_BO": "quechua (Bolivia)",
  "qu_EC": "quechua (Ecuador)",
  "qu_PE": "quechua (Peru)",
  "quc": "k’iche’",
  "qug": "kichwa (Chimborazo-høylandet)",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotongansk",
  "rgn": "romagnolsk",
  "rif": "riff",
  "rm": "retoromansk",
  "rm_CH": "retoromansk (Sveits)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "rumensk",
  "ro_MD": "rumensk (Moldova)",
  "ro_RO": "rumensk (Romania)",
  "roa": "romansk språk",
  "rof": "rombo",
  "rom": "romani",
  "root": "rot",
  "rtm": "rotumansk",
  "ru": "russisk",
  "ru_BY": "russisk (Hviterussland)",
  "ru_KG": "russisk (Kirgisistan)",
  "ru_KZ": "russisk (Kasakhstan)",
  "ru_MD": "russisk (Moldova)",
  "ru_RU": "russisk (Russland)",
  "ru_UA": "russisk (Ukraina)",
  "rue": "rusinsk",
  "rug": "roviana",
  "rup": "aromansk",
  "rw": "kinyarwanda",
  "rw_RW": "kinyarwanda (Rwanda)",
  "rwk": "rwa",
  "sa": "sanskrit",
  "sad": "sandawe",
  "sah": "sakha",
  "sai": "søramerikansk indiansk språk",
  "sal": "salishansk språk",
  "sam": "samaritansk arameisk",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardisk",
  "scn": "siciliansk",
  "sco": "skotsk",
  "sd": "sindhi",
  "sdc": "sassaresisk sardisk",
  "sdh": "sørkurdisk",
  "se": "nordsamisk",
  "se_FI": "nordsamisk (Finland)",
  "se_NO": "nordsamisk (Norge)",
  "se_SE": "nordsamisk (Sverige)",
  "see": "seneca",
  "seh": "sena",
  "sei": "seri",
  "sel": "selkupisk",
  "sem": "semittisk språk",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (Den sentralafrikanske republikk)",
  "sga": "gammelirsk",
  "sgn": "tegnspråk",
  "sgs": "samogitisk",
  "sh": "serbokroatisk",
  "sh_BA": "serbokroatisk (Bosnia-Hercegovina)",
  "shi": "tachelhit",
  "shn": "shan",
  "shu": "tsjadisk arabisk",
  "si": "singalesisk",
  "si_LK": "singalesisk (Sri Lanka)",
  "sid": "sidamo",
  "sio": "siouxspråk",
  "sit": "sino-tibetansk språk",
  "sk": "slovakisk",
  "sk_SK": "slovakisk (Slovakia)",
  "sl": "slovensk",
  "sl_SI": "slovensk (Slovenia)",
  "sla": "slavisk språk",
  "sli": "lavschlesisk",
  "sly": "selayar",
  "sm": "samoansk",
  "sma": "sørsamisk",
  "smi": "samisk språk",
  "smj": "lulesamisk",
  "smn": "enaresamisk",
  "sms": "skoltesamisk",
  "sn": "shona",
  "sn_ZW": "shona (Zimbabwe)",
  "snk": "soninke",
  "so": "somali",
  "so_DJ": "somali (Djibouti)",
  "so_ET": "somali (Etiopia)",
  "so_KE": "somali (Kenya)",
  "so_SO": "somali (Somalia)",
  "sog": "sogdisk",
  "son": "songhai",
  "sq": "albansk",
  "sq_AL": "albansk (Albania)",
  "sq_MK": "albansk (Makedonia)",
  "sq_XK": "albansk (Kosovo)",
  "sr": "serbisk",
  "sr_BA": "serbisk (Bosnia-Hercegovina)",
  "sr_Cyrl": "serbisk (kyrillisk)",
  "sr_Cyrl_BA": "serbisk (kyrillisk, Bosnia-Hercegovina)",
  "sr_Cyrl_ME": "serbisk (kyrillisk, Montenegro)",
  "sr_Cyrl_RS": "serbisk (kyrillisk, Serbia)",
  "sr_Cyrl_XK": "serbisk (kyrillisk, Kosovo)",
  "sr_Latn": "serbisk (latinsk)",
  "sr_Latn_BA": "serbisk (latinsk, Bosnia-Hercegovina)",
  "sr_Latn_ME": "serbisk (latinsk, Montenegro)",
  "sr_Latn_RS": "serbisk (latinsk, Serbia)",
  "sr_Latn_XK": "serbisk (latinsk, Kosovo)",
  "sr_ME": "serbisk (Montenegro)",
  "sr_RS": "serbisk (Serbia)",
  "sr_XK": "serbisk (Kosovo)",
  "srn": "sranan",
  "srr": "serer",
  "ss": "swati",
  "ssa": "nilo-saharaspråk",
  "ssy": "saho",
  "st": "sør-sotho",
  "stq": "saterfrisisk",
  "su": "sundanesisk",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumerisk",
  "sv": "svensk",
  "sv_AX": "svensk (Åland)",
  "sv_FI": "svensk (Finland)",
  "sv_SE": "svensk (Sverige)",
  "sw": "swahili",
  "sw_CD": "kongolesisk swahili",
  "sw_KE": "swahili (Kenya)",
  "sw_TZ": "swahili (Tanzania)",
  "sw_UG": "swahili (Uganda)",
  "swb": "komorisk",
  "swc": "kongolesisk swahili",
  "syc": "klassisk syrisk",
  "syr": "syriakisk",
  "szl": "schlesisk",
  "ta": "tamil",
  "ta_IN": "tamilsk (India)",
  "ta_LK": "tamilsk (Sri Lanka)",
  "ta_MY": "tamilsk (Malaysia)",
  "ta_SG": "tamilsk (Singapore)",
  "tai": "taispråk",
  "tcy": "tulu",
  "te": "telugu",
  "te_IN": "telugu (India)",
  "tem": "temne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tetum",
  "tg": "tadsjikisk",
  "th": "thai",
  "th_TH": "thai (Thailand)",
  "ti": "tigrinja",
  "ti_ER": "tigrinja (Eritrea)",
  "ti_ET": "tigrinja (Etiopia)",
  "tig": "tigré",
  "tiv": "tiv",
  "tk": "turkmensk",
  "tkl": "tokelauisk",
  "tkr": "tsakhursk",
  "tl": "tagalog",
  "tl_PH": "tagalog (Filippinene)",
  "tlh": "klingon",
  "tli": "tlingit",
  "tly": "talysj",
  "tmh": "tamasjek",
  "tn": "setswana",
  "to": "tongansk",
  "to_TO": "tongansk (Tonga)",
  "tog": "nyasa-tongansk",
  "tpi": "tok pisin",
  "tr": "tyrkisk",
  "tr_CY": "tyrkisk (Kypros)",
  "tr_TR": "tyrkisk (Tyrkia)",
  "tru": "turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "tsakonisk",
  "tsi": "tsimshian",
  "tt": "tatarisk",
  "ttt": "muslimsk tat",
  "tum": "tumbuka",
  "tup": "tupispråk",
  "tut": "altaisk språk",
  "tvl": "tuvalsk",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitisk",
  "tyv": "tuvinsk",
  "tzm": "sentralmarokkansk tamazight",
  "udm": "udmurtisk",
  "ug": "uigurisk",
  "ug_Arab": "uigurisk (arabisk)",
  "ug_Arab_CN": "uigurisk (arabisk, Kina)",
  "ug_CN": "uigurisk (Kina)",
  "uga": "ugaritisk",
  "uk": "ukrainsk",
  "uk_UA": "ukrainsk (Ukraina)",
  "umb": "umbundu",
  "und": "ukjent språk",
  "ur": "urdu",
  "ur_IN": "urdu (India)",
  "ur_PK": "urdu (Pakistan)",
  "uz": "usbekisk",
  "uz_AF": "usbekisk (Afghanistan)",
  "uz_Arab": "usbekisk (arabisk)",
  "uz_Arab_AF": "usbekisk (arabisk, Afghanistan)",
  "uz_Cyrl": "usbekisk (kyrillisk)",
  "uz_Cyrl_UZ": "usbekisk (kyrillisk, Usbekistan)",
  "uz_Latn": "usbekisk (latinsk)",
  "uz_Latn_UZ": "usbekisk (latinsk, Usbekistan)",
  "uz_UZ": "usbekisk (Usbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "venetiansk",
  "vep": "vepsisk",
  "vi": "vietnamesisk",
  "vi_VN": "vietnamesisk (Vietnam)",
  "vls": "vestflamsk",
  "vmf": "Main-frankisk",
  "vo": "volapyk",
  "vot": "votisk",
  "vro": "sørestisk",
  "vun": "vunjo",
  "wa": "vallonsk",
  "wae": "walsertysk",
  "wak": "wakasjansk språk",
  "wal": "wolaytta",
  "war": "waray-waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wen": "sorbisk språk",
  "wo": "wolof",
  "wuu": "wu",
  "xal": "kalmukkisk",
  "xh": "xhosa",
  "xmf": "mingrelsk",
  "xog": "soga",
  "yao": "yao",
  "yap": "yapesisk",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "jiddisk",
  "yo": "joruba",
  "yo_BJ": "joruba (Benin)",
  "yo_NG": "joruba (Nigeria)",
  "ypk": "jupisk språk",
  "yrl": "nheengatu",
  "yue": "kantonesisk",
  "za": "zhuang",
  "zap": "zapotekisk",
  "zbl": "blissymboler",
  "zea": "zeeuws",
  "zen": "zenaga",
  "zgh": "standard marrokansk tamazight",
  "zh": "kinesisk",
  "zh_CN": "kinesisk (Kina)",
  "zh_HK": "kinesisk (Hongkong S.A.R. Kina)",
  "zh_Hans": "kinesisk (forenklet)",
  "zh_Hans_CN": "kinesisk (forenklet, Kina)",
  "zh_Hans_HK": "kinesisk (forenklet, Hongkong S.A.R. Kina)",
  "zh_Hans_MO": "kinesisk (forenklet, Macao S.A.R. Kina)",
  "zh_Hans_SG": "kinesisk (forenklet, Singapore)",
  "zh_Hant": "kinesisk (tradisjonell)",
  "zh_Hant_HK": "kinesisk (tradisjonell, Hongkong S.A.R. Kina)",
  "zh_Hant_MO": "kinesisk (tradisjonell, Macao S.A.R. Kina)",
  "zh_Hant_TW": "kinesisk (tradisjonell, Taiwan)",
  "zh_MO": "kinesisk (Macao S.A.R. Kina)",
  "zh_SG": "kinesisk (Singapore)",
  "zh_TW": "kinesisk (Taiwan)",
  "znd": "zande",
  "zu": "zulu",
  "zu_ZA": "zulu (Sør-Afrika)",
  "zun": "zuni",
  "zxx": "uten språklig innhold",
  "zza": "zazaisk"
};
