const names = {
  "AD": "Andorra",
  "AE": "De forente arabiske emirater",
  "AF": "Afghanistan",
  "AG": "Antigua og Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antarktis",
  "AR": "Argentina",
  "AS": "Amerikansk Samoa",
  "AT": "Østerrike",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland",
  "AZ": "Aserbajdsjan",
  "BA": "Bosnia-Hercegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Karibisk Nederland",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvetøya",
  "BW": "Botswana",
  "BY": "Hviterussland",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Kokosøyene",
  "CD": "Kongo-Kinshasa",
  "CF": "Den sentralafrikanske republikk",
  "CG": "Kongo-Brazzaville",
  "CH": "Sveits",
  "CI": "Elfenbenskysten",
  "CK": "Cookøyene",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "Kina",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Kapp Verde",
  "CW": "Curaçao",
  "CX": "Christmasøya",
  "CY": "Kypros",
  "CZ": "Tsjekkia",
  "DE": "Tyskland",
  "DJ": "Djibouti",
  "DK": "Danmark",
  "DM": "Dominica",
  "DO": "Den dominikanske republikk",
  "DZ": "Algerie",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Egypt",
  "EH": "Vest-Sahara",
  "ER": "Eritrea",
  "ES": "Spania",
  "ET": "Etiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falklandsøyene",
  "FM": "Mikronesiaføderasjonen",
  "FO": "Færøyene",
  "FR": "Frankrike",
  "GA": "Gabon",
  "GB": "Storbritannia",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Fransk Guyana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grønland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Ekvatorial-Guinea",
  "GR": "Hellas",
  "GS": "Sør-Georgia og Sør-Sandwichøyene",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hongkong S.A.R. Kina",
  "HM": "Heard- og McDonaldøyene",
  "HN": "Honduras",
  "HR": "Kroatia",
  "HT": "Haiti",
  "HU": "Ungarn",
  "ID": "Indonesia",
  "IE": "Irland",
  "IL": "Israel",
  "IM": "Man",
  "IN": "India",
  "IO": "Det britiske territoriet i Indiahavet",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italia",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kirgisistan",
  "KH": "Kambodsja",
  "KI": "Kiribati",
  "KM": "Komorene",
  "KN": "Saint Kitts og Nevis",
  "KP": "Nord-Korea",
  "KR": "Sør-Korea",
  "KW": "Kuwait",
  "KY": "Caymanøyene",
  "KZ": "Kasakhstan",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litauen",
  "LU": "Luxemburg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint-Martin",
  "MG": "Madagaskar",
  "MH": "Marshalløyene",
  "MK": "Nord-Makedonia",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao S.A.R. Kina",
  "MP": "Nord-Marianene",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldivene",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "NA": "Namibia",
  "NC": "Ny-Caledonia",
  "NE": "Niger",
  "NF": "Norfolkøya",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Nederland",
  "NO": "Norge",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Fransk Polynesia",
  "PG": "Papua Ny-Guinea",
  "PH": "Filippinene",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint-Pierre-et-Miquelon",
  "PN": "Pitcairnøyene",
  "PR": "Puerto Rico",
  "PS": "Det palestinske området",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russland",
  "RW": "Rwanda",
  "SA": "Saudi-Arabia",
  "SB": "Salomonøyene",
  "SC": "Seychellene",
  "SD": "Sudan",
  "SE": "Sverige",
  "SG": "Singapore",
  "SH": "St. Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard og Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Sør-Sudan",
  "ST": "São Tomé og Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TC": "Turks- og Caicosøyene",
  "TD": "Tsjad",
  "TF": "De franske sørterritorier",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadsjikistan",
  "TK": "Tokelau",
  "TL": "Øst-Timor",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Tyrkia",
  "TT": "Trinidad og Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "USAs ytre øyer",
  "US": "USA",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "VA": "Vatikanstaten",
  "VC": "St. Vincent og Grenadinene",
  "VE": "Venezuela",
  "VG": "De britiske jomfruøyene",
  "VI": "De amerikanske jomfruøyene",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis og Futuna",
  "WS": "Samoa",
  "YE": "Jemen",
  "YT": "Mayotte",
  "ZA": "Sør-Afrika",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "aa": "afar",
  "ab": "abkhasisk",
  "ace": "achinesisk",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adyghe",
  "ae": "avestisk",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "akkadisk",
  "akz": "Alabama",
  "ale": "aleutisk",
  "aln": "Gheg Albanian",
  "alt": "søraltaisk",
  "am": "Amharic",
  "am_ET": "Amharic (Ethiopia)",
  "an": "aragonsk",
  "ang": "gammelengelsk",
  "anp": "angika",
  "ar": "Arabic",
  "ar_001": "moderne standard arabisk",
  "ar_AE": "Arabic (United Arab Emirates)",
  "ar_BH": "Arabic (Bahrain)",
  "ar_DJ": "Arabic (Djibouti)",
  "ar_DZ": "Arabic (Algeria)",
  "ar_EG": "Arabic (Egypt)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Arabic (Eritrea)",
  "ar_IL": "Arabic (Israel)",
  "ar_IQ": "Arabic (Iraq)",
  "ar_JO": "Arabic (Jordan)",
  "ar_KM": "Arabic (Comoros)",
  "ar_KW": "Arabic (Kuwait)",
  "ar_LB": "Arabic (Lebanon)",
  "ar_LY": "Arabic (Libya)",
  "ar_MA": "Arabic (Morocco)",
  "ar_MR": "Arabic (Mauritania)",
  "ar_OM": "Arabic (Oman)",
  "ar_PS": "Arabic (Palestinian Territories)",
  "ar_QA": "Arabic (Qatar)",
  "ar_SA": "Arabic (Saudi Arabia)",
  "ar_SD": "Arabic (Sudan)",
  "ar_SO": "Arabic (Somalia)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Arabic (Syria)",
  "ar_TD": "Arabic (Chad)",
  "ar_TN": "Arabic (Tunisia)",
  "ar_YE": "Arabic (Yemen)",
  "arc": "arameisk",
  "arn": "araukansk",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "arw": "arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "asu",
  "ase": "American Sign Language",
  "ast": "asturisk",
  "av": "avarisk",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "basjkirsk",
  "bal": "baluchi",
  "ban": "balinesisk",
  "bar": "Bavarian",
  "bas": "basa",
  "bax": "bamun",
  "bbc": "Batak Toba",
  "bbj": "ghomala",
  "be": "Belarusian",
  "be_BY": "Belarusian (Belarus)",
  "bej": "beja",
  "bem": "bemba",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "Badaga",
  "bg": "Bulgarian",
  "bg_BG": "Bulgarian (Bulgaria)",
  "bho": "bhojpuri",
  "bi": "bislama",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bengali",
  "bn_BD": "Bengali (Bangladesh)",
  "bn_IN": "Bengali (India)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "braj",
  "brh": "Brahui",
  "brx": "bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "akose",
  "bua": "buriat",
  "bug": "buginesisk",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "caddo",
  "car": "karibisk",
  "cay": "cayuga",
  "cch": "atsam",
  "ce": "tsjetsjensk",
  "ceb": "cebuansk",
  "cgg": "kiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "chagatai",
  "chk": "chuukesisk",
  "chm": "mari",
  "chn": "chinook",
  "cho": "choctaw",
  "chp": "chipewiansk",
  "chr": "cherokesisk",
  "chy": "cheyenne",
  "ckb": "kurdisk (sorani)",
  "co": "korsikansk",
  "cop": "koptisk",
  "cps": "Capiznon",
  "cr": "cree",
  "crh": "krimtatarisk",
  "cs": "Czech",
  "cs_CZ": "Czech (Czech Republic)",
  "csb": "kasjubisk",
  "cu": "kirkeslavisk",
  "cv": "tsjuvansk",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "dakota",
  "dar": "dargwa",
  "dav": "taita",
  "de": "German",
  "de_AT": "German (Austria)",
  "de_BE": "German (Belgium)",
  "de_CH": "German (Switzerland)",
  "de_DE": "German (Germany)",
  "de_LI": "German (Liechtenstein)",
  "de_LU": "German (Luxembourg)",
  "del": "delaware",
  "den": "slavisk",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dsb": "lavsorbisk",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "mellomnederlandsk",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "dazaga",
  "ebu": "kiembu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "efik",
  "egl": "Emilian",
  "egy": "gammelegyptisk",
  "eka": "ekajuk",
  "el": "Greek",
  "el_CY": "Greek (Cyprus)",
  "el_GR": "Greek (Greece)",
  "elx": "elamittisk",
  "en": "English",
  "en_AG": "English (Antigua & Barbuda)",
  "en_AI": "English (Anguilla)",
  "en_AS": "English (American Samoa)",
  "en_AU": "English (Australia)",
  "en_BB": "English (Barbados)",
  "en_BE": "English (Belgium)",
  "en_BM": "English (Bermuda)",
  "en_BS": "English (Bahamas)",
  "en_BW": "English (Botswana)",
  "en_BZ": "English (Belize)",
  "en_CA": "English (Canada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "English (Cook Islands)",
  "en_CM": "English (Cameroon)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "English (Dominica)",
  "en_ER": "English (Eritrea)",
  "en_FJ": "English (Fiji)",
  "en_FK": "English (Falkland Islands)",
  "en_FM": "English (Micronesia)",
  "en_GB": "English (United Kingdom)",
  "en_GD": "English (Grenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "English (Ghana)",
  "en_GI": "English (Gibraltar)",
  "en_GM": "English (Gambia)",
  "en_GU": "English (Guam)",
  "en_GY": "English (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "English (Ireland)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "English (India)",
  "en_IO": "English (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "English (Jamaica)",
  "en_KE": "English (Kenya)",
  "en_KI": "English (Kiribati)",
  "en_KN": "English (St. Kitts & Nevis)",
  "en_KY": "English (Cayman Islands)",
  "en_LC": "English (St. Lucia)",
  "en_LR": "English (Liberia)",
  "en_LS": "English (Lesotho)",
  "en_MG": "English (Madagascar)",
  "en_MH": "English (Marshall Islands)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "English (Northern Mariana Islands)",
  "en_MS": "English (Montserrat)",
  "en_MT": "English (Malta)",
  "en_MU": "English (Mauritius)",
  "en_MW": "English (Malawi)",
  "en_MY": "English (Malaysia)",
  "en_NA": "English (Namibia)",
  "en_NF": "English (Norfolk Island)",
  "en_NG": "English (Nigeria)",
  "en_NR": "English (Nauru)",
  "en_NU": "English (Niue)",
  "en_NZ": "English (New Zealand)",
  "en_PG": "English (Papua New Guinea)",
  "en_PH": "English (Philippines)",
  "en_PK": "English (Pakistan)",
  "en_PN": "English (Pitcairn Islands)",
  "en_PR": "English (Puerto Rico)",
  "en_PW": "English (Palau)",
  "en_RW": "English (Rwanda)",
  "en_SB": "English (Solomon Islands)",
  "en_SC": "English (Seychelles)",
  "en_SD": "English (Sudan)",
  "en_SG": "English (Singapore)",
  "en_SH": "English (St. Helena)",
  "en_SL": "English (Sierra Leone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "English (Swaziland)",
  "en_TC": "English (Turks & Caicos Islands)",
  "en_TK": "English (Tokelau)",
  "en_TO": "English (Tonga)",
  "en_TT": "English (Trinidad & Tobago)",
  "en_TV": "English (Tuvalu)",
  "en_TZ": "English (Tanzania)",
  "en_UG": "English (Uganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "English (United States)",
  "en_VC": "English (St. Vincent & Grenadines)",
  "en_VG": "English (British Virgin Islands)",
  "en_VI": "English (U.S. Virgin Islands)",
  "en_VU": "English (Vanuatu)",
  "en_WS": "English (Samoa)",
  "en_ZA": "English (South Africa)",
  "en_ZM": "English (Zambia)",
  "en_ZW": "English (Zimbabwe)",
  "enm": "mellomengelsk",
  "eo": "Esperanto",
  "es": "Spanish",
  "es_419": "latinamerikansk spansk",
  "es_AR": "Spanish (Argentina)",
  "es_BO": "Spanish (Bolivia)",
  "es_CL": "Spanish (Chile)",
  "es_CO": "Spanish (Colombia)",
  "es_CR": "Spanish (Costa Rica)",
  "es_CU": "Spanish (Cuba)",
  "es_DO": "Spanish (Dominican Republic)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Spanish (Ecuador)",
  "es_ES": "Spanish (Spain)",
  "es_GQ": "Spanish (Equatorial Guinea)",
  "es_GT": "Spanish (Guatemala)",
  "es_HN": "Spanish (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Spanish (Mexico)",
  "es_NI": "Spanish (Nicaragua)",
  "es_PA": "Spanish (Panama)",
  "es_PE": "Spanish (Peru)",
  "es_PH": "Spanish (Philippines)",
  "es_PR": "Spanish (Puerto Rico)",
  "es_PY": "Spanish (Paraguay)",
  "es_SV": "Spanish (El Salvador)",
  "es_US": "Spanish (United States)",
  "es_UY": "Spanish (Uruguay)",
  "es_VE": "Spanish (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fa": "Persian",
  "fa_AF": "Persian (Afghanistan)",
  "fa_IR": "Persian (Iran)",
  "fan": "fang",
  "fat": "fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "filippinsk",
  "fit": "Tornedalen Finnish",
  "fj": "fijiansk",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "fon",
  "fr": "French",
  "fr_BE": "French (Belgium)",
  "fr_BF": "French (Burkina Faso)",
  "fr_BI": "French (Burundi)",
  "fr_BJ": "French (Benin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "French (Canada)",
  "fr_CD": "French (Congo - Kinshasa)",
  "fr_CF": "French (Central African Republic)",
  "fr_CG": "French (Congo - Brazzaville)",
  "fr_CH": "French (Switzerland)",
  "fr_CI": "French (Côte d’Ivoire)",
  "fr_CM": "French (Cameroon)",
  "fr_DJ": "French (Djibouti)",
  "fr_DZ": "French (Algeria)",
  "fr_FR": "French (France)",
  "fr_GA": "French (Gabon)",
  "fr_GF": "French (French Guiana)",
  "fr_GN": "French (Guinea)",
  "fr_GP": "French (Guadeloupe)",
  "fr_GQ": "French (Equatorial Guinea)",
  "fr_HT": "French (Haiti)",
  "fr_KM": "French (Comoros)",
  "fr_LU": "French (Luxembourg)",
  "fr_MA": "French (Morocco)",
  "fr_MC": "French (Monaco)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "French (Madagascar)",
  "fr_ML": "French (Mali)",
  "fr_MQ": "French (Martinique)",
  "fr_MR": "French (Mauritania)",
  "fr_MU": "French (Mauritius)",
  "fr_NC": "French (New Caledonia)",
  "fr_NE": "French (Niger)",
  "fr_PF": "French (French Polynesia)",
  "fr_PM": "French (St. Pierre & Miquelon)",
  "fr_RE": "French (Réunion)",
  "fr_RW": "French (Rwanda)",
  "fr_SC": "French (Seychelles)",
  "fr_SN": "French (Senegal)",
  "fr_SY": "French (Syria)",
  "fr_TD": "French (Chad)",
  "fr_TG": "French (Togo)",
  "fr_TN": "French (Tunisia)",
  "fr_VU": "French (Vanuatu)",
  "fr_WF": "French (Wallis & Futuna)",
  "fr_YT": "French (Mayotte)",
  "frc": "Cajun French",
  "frm": "mellomfransk",
  "fro": "gammelfransk",
  "frp": "Arpitan",
  "frr": "nordfrisisk",
  "frs": "østfrisisk",
  "fur": "friuliansk",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "ga",
  "gag": "gagausisk",
  "gan": "Gan Chinese",
  "gay": "gayo",
  "gba": "gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "ges",
  "gil": "kiribatisk",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "mellomhøytysk",
  "gn": "guarani",
  "goh": "gammelhøytysk",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gotisk",
  "grb": "grebo",
  "grc": "gammelgresk",
  "gsw": "sveitsertysk",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "gwichin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "haida",
  "hak": "Hakka Chinese",
  "haw": "hawaiisk",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "hit": "hettittisk",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "høysorbisk",
  "hsn": "Xiang Chinese",
  "ht": "haitisk",
  "hu": "Hungarian",
  "hu_HU": "Hungarian (Hungary)",
  "hup": "hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "herero",
  "ia": "interlingua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "Indonesian",
  "id_ID": "Indonesian (Indonesia)",
  "ie": "interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "inupiak",
  "ilo": "iloko",
  "inh": "ingusjisk",
  "io": "ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "Italian",
  "it_CH": "Italian (Switzerland)",
  "it_IT": "Italian (Italy)",
  "it_SM": "Italian (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "Japanese",
  "ja_JP": "Japanese (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "ngomba",
  "jmc": "machame",
  "jpr": "jødepersisk",
  "jrb": "jødearabisk",
  "jut": "Jutish",
  "jv": "javanesisk",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "karakalpakisk",
  "kab": "kabylsk",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kaw": "kawi",
  "kbd": "kabardisk",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "makonde",
  "kea": "kappverdisk",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "kikongo",
  "kgp": "Kaingang",
  "kha": "khasi",
  "kho": "khotanesisk",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodia)",
  "kmb": "kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Korean",
  "ko_KP": "Korean (North Korea)",
  "ko_KR": "Korean (South Korea)",
  "koi": "komipermjakisk",
  "kok": "konkani",
  "kos": "kosraeansk",
  "kpe": "kpelle",
  "kr": "kanuri",
  "krc": "karachay-balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "karelsk",
  "kru": "kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kølnsk",
  "ku": "kurdisk",
  "kum": "kumyk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "latin",
  "lad": "ladinsk",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "limburgisk",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "mongo",
  "loz": "lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushai",
  "luy": "luhya",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "maduresisk",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "mandingo",
  "mas": "masai",
  "mde": "maba",
  "mdf": "moksha",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "mauritisk-kreolsk",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "mellomirsk",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mh": "marshallesisk",
  "mi": "maori",
  "mic": "micmac",
  "min": "minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "mandsju",
  "mni": "manipuri",
  "moh": "mohawk",
  "mos": "mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Malay",
  "ms_BN": "Malay (Brunei)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malay (Malaysia)",
  "ms_SG": "Malay (Singapore)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "mundang",
  "mul": "flere språk",
  "mus": "creek",
  "mwl": "mirandesisk",
  "mwr": "marwari",
  "mwv": "Mentawai",
  "my": "Burmese",
  "my_MM": "Burmese (Myanmar (Burma))",
  "mye": "myene",
  "myv": "erzya",
  "mzn": "Mazanderani",
  "na": "nauru",
  "nan": "Min Nan Chinese",
  "nap": "napolitansk",
  "naq": "nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "lavtysk",
  "ne": "Nepali",
  "ne_IN": "Nepali (India)",
  "ne_NP": "Nepali (Nepal)",
  "new": "newari",
  "ng": "ndonga",
  "nia": "nias",
  "niu": "niueansk",
  "njo": "Ao Naga",
  "nl": "Dutch",
  "nl_AW": "Dutch (Aruba)",
  "nl_BE": "Dutch (Belgium)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Dutch (Netherlands)",
  "nl_SR": "Dutch (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "nogai",
  "non": "gammelnorsk",
  "nov": "Novial",
  "nqo": "nkå",
  "nr": "sør-ndebele",
  "nso": "nord-sotho",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "klassisk newari",
  "ny": "nyanja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "oksitansk",
  "oj": "ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "osage",
  "ota": "ottomansk tyrkisk",
  "pa": "Punjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "pag": "pangasinan",
  "pal": "pahlavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palauisk",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "gammelpersisk",
  "pfl": "Palatine German",
  "phn": "fønikisk",
  "pi": "pali",
  "pl": "Polish",
  "pl_PL": "Polish (Poland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "ponapisk",
  "prg": "Prussian",
  "pro": "gammelprovençalsk",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Portuguese",
  "pt_AO": "Portuguese (Angola)",
  "pt_BR": "Portuguese (Brazil)",
  "pt_CV": "Portuguese (Cape Verde)",
  "pt_GW": "Portuguese (Guinea-Bissau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Portuguese (Mozambique)",
  "pt_PT": "Portuguese (Portugal)",
  "pt_ST": "Portuguese (São Tomé & Príncipe)",
  "pt_TL": "Portuguese (Timor-Leste)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "quiché",
  "qug": "Chimborazo Highland Quichua",
  "raj": "rajasthani",
  "rap": "rapanui",
  "rar": "rarotongansk",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Romanian",
  "ro_MD": "Romanian (Moldova)",
  "ro_RO": "Romanian (Romania)",
  "rof": "rombo",
  "rom": "romani",
  "root": "rot",
  "rtm": "Rotuman",
  "ru": "Russian",
  "ru_BY": "Russian (Belarus)",
  "ru_KG": "Russian (Kyrgyzstan)",
  "ru_KZ": "Russian (Kazakhstan)",
  "ru_MD": "Russian (Moldova)",
  "ru_RU": "Russian (Russia)",
  "ru_UA": "Russian (Ukraine)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromansk",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "rwa",
  "sa": "sanskrit",
  "sad": "sandawe",
  "sah": "jakutsk",
  "sam": "samaritansk arameisk",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardinsk",
  "scn": "siciliansk",
  "sco": "skotsk",
  "sd": "sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "selkupisk",
  "ses": "koyraboro senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "gammelirsk",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "tachelhit",
  "shn": "shan",
  "shu": "Tsjad-arabisk",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoansk",
  "sma": "sørsamisk",
  "smj": "lulesamisk",
  "smn": "enaresamisk",
  "sms": "skoltesamisk",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "soninke",
  "so": "Somali",
  "so_DJ": "Somali (Djibouti)",
  "so_ET": "Somali (Ethiopia)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somalia)",
  "sog": "sogdisk",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "sranan tongo",
  "srr": "serer",
  "ss": "swati",
  "ssy": "saho",
  "st": "sør-sotho",
  "stq": "Saterland Frisian",
  "su": "sundanesisk",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumerisk",
  "sv": "Swedish",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Swedish (Finland)",
  "sv_SE": "Swedish (Sweden)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "komorisk",
  "swc": "kongolesisk swahili",
  "syc": "klassisk syrisk",
  "syr": "syrisk",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Malaysia)",
  "ta_SG": "Tamil (Singapore)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "temne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tetum",
  "tg": "tadsjikisk",
  "th": "Thai",
  "th_TH": "Thai (Thailand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "tigré",
  "tiv": "tiv",
  "tk": "turkmensk",
  "tkl": "tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "klingon",
  "tli": "tlingit",
  "tly": "Talysh",
  "tmh": "tamasjek",
  "tn": "setswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "nyasa-tongansk",
  "tpi": "tok pisin",
  "tr": "Turkish",
  "tr_CY": "Turkish (Cyprus)",
  "tr_TR": "Turkish (Turkey)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshian",
  "tt": "tatarisk",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tvl": "tuvalu",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "tahitisk",
  "tyv": "tuvinisk",
  "tzm": "sentralmarokkansk tamazight",
  "udm": "udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "ugaritisk",
  "uk": "Ukrainian",
  "uk_UA": "Ukrainian (Ukraine)",
  "umb": "umbundu",
  "und": "ukjent språk",
  "ur": "Urdu",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "vai",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Vietnamese",
  "vi_VN": "Vietnamese (Vietnam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapyk",
  "vot": "votisk",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "vallonsk",
  "wae": "walser",
  "wal": "walamo",
  "war": "waray",
  "was": "washo",
  "wbp": "Warlpiri",
  "wo": "wolof",
  "wuu": "Wu Chinese",
  "xal": "kalmyk",
  "xh": "xhosa",
  "xmf": "Mingrelian",
  "xog": "soga",
  "yao": "yao",
  "yap": "yapesisk",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "yrl": "Nheengatu",
  "yue": "kantonesisk",
  "za": "zhuang",
  "zap": "zapotec",
  "zbl": "blissymboler",
  "zea": "Zeelandic",
  "zen": "zenaga",
  "zgh": "standard marrokansk tamazight",
  "zh": "Chinese",
  "zh_CN": "Chinese (China)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Chinese (Singapore)",
  "zh_TW": "Chinese (Taiwan)",
  "zu": "Zulu",
  "zu_ZA": "Zulu (South Africa)",
  "zun": "zuni",
  "zxx": "uten språklig innhold",
  "zza": "zaza"
};
