const names = {
  "BN": "Brunei",
  "BW": "Botswana",
  "BY": "Weissrussland",
  "CV": "Kapverden",
  "GB": "Grossbritannien",
  "QO": "Äusseres Ozeanien",
  "SB": "Salomon-Inseln",
  "TL": "Osttimor",
  "ZW": "Zimbabwe",
  "ar_DJ": "Arabisch (Djibouti)",
  "ars": "Nadschd-Arabisch",
  "be": "Weissrussisch",
  "be_BY": "Weissrussisch (Weissrussland)",
  "bn_BD": "Bengalisch (Bangladesh)",
  "chm": "Tscheremissisch",
  "cy_GB": "Walisisch (Grossbritannien)",
  "en_BW": "Englisch (Botswana)",
  "en_GB": "Englisch (Grossbritannien)",
  "en_MH": "Englisch (Marshall-Inseln)",
  "en_RW": "Englisch (Rwanda)",
  "en_SB": "Englisch (Salomon-Inseln)",
  "en_ZW": "Englisch (Zimbabwe)",
  "fr_DJ": "Französisch (Djibouti)",
  "fr_RW": "Französisch (Rwanda)",
  "gd_GB": "Schottisches Gälisch (Grossbritannien)",
  "kw_GB": "Kornisch (Grossbritannien)",
  "ms_BN": "Malaiisch (Brunei)",
  "ms_Latn_BN": "Malaiisch (Lateinisch, Brunei)",
  "nd_ZW": "Nord-Ndebele-Sprache (Zimbabwe)",
  "prg": "Altpreussisch",
  "pt_CV": "Portugiesisch (Kapverden)",
  "pt_ST": "Portugiesisch (Sao Tomé und Principe)",
  "ru_BY": "Russisch (Weissrussland)",
  "rw_RW": "Ruandisch (Rwanda)",
  "sn_ZW": "Shona (Zimbabwe)",
  "so_DJ": "Somali (Djibouti)"
};
