const names = {
  "af": "африканерски",
  "agq": "aghem",
  "ar_001": "moderni standardni arapski",
  "asa": "asu",
  "be": "белоруски",
  "bez": "bena",
  "bn": "бенгласки",
  "brx": "bodo",
  "cgg": "čiga",
  "ckb": "soranski kurdski",
  "cu": "старословенски",
  "dav": "taita",
  "de": "немачки",
  "de_CH": "немачки (Швајцарска)",
  "dje": "zarma",
  "dsb": "ниски сорбијански",
  "dyo": "jola-fonyi",
  "ebu": "embu",
  "fil": "тагалог",
  "fy": "фризијски",
  "gsw": "швајцарски немачки",
  "guz": "gusii",
  "hsb": "горњи сорбијски",
  "ht": "хаитски",
  "ii": "сичуан ји",
  "jgo": "ngomba",
  "jmc": "machame",
  "kde": "makonde",
  "kea": "zelenortski",
  "khq": "koyra chiini",
  "kk": "козачки",
  "kkj": "Kako",
  "kln": "kalenjin",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "Colognian",
  "lag": "langi",
  "lkt": "lakota",
  "luy": "luyia",
  "lv": "летонски",
  "mer": "meru",
  "mfe": "mauricijski kreolski",
  "mgh": "makhuwa-meetto",
  "mgo": "meta’",
  "mt": "мелтешки",
  "mua": "mundang",
  "mzn": "Mazanderani",
  "naq": "nama",
  "nd": "северни ндебеле",
  "nds": "ниски немачки",
  "nl_BE": "холандски (Белгија)",
  "nmg": "kwasio",
  "nn": "норвешки њорск",
  "nnh": "Ngiemboon",
  "nso": "северни сото",
  "nus": "nuer",
  "or": "оријски",
  "pa": "панџабски",
  "prg": "Prussian",
  "ro_MD": "румунски (Молдавија)",
  "rof": "rombo",
  "rwk": "rua",
  "sah": "јакут",
  "saq": "samburu",
  "sbp": "sangu",
  "se": "северни сами",
  "seh": "sena",
  "ses": "kojraboro seni",
  "shi": "tahelhit",
  "si": "сингалески",
  "sl": "словеначки",
  "su": "судански",
  "teo": "teso",
  "tg": "тађик",
  "twq": "tasavak",
  "tzm": "marokanski tamazigt",
  "und": "непознат или неважећи језик",
  "vun": "vunjo",
  "wae": "Walser",
  "xh": "ксхоса",
  "xog": "soga",
  "yav": "Yangben",
  "zgh": "standardni marokanski tamazigt",
  "zh_Hans": "кинески (поједностављено кинеско писмо)"
};
