const names = {
  "AD": "Andora",
  "AE": "Leta Zunze Ubumwe z’Abarabu",
  "AF": "Afuganisitani",
  "AG": "Antigwa na Baribuda",
  "AI": "Angwila",
  "AL": "Alubaniya",
  "AM": "Arumeniya",
  "AN": "Antiye y'Abaholandi",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Arijantine",
  "AS": "Samowa nyamerika",
  "AT": "Otirishe",
  "AU": "Ositaraliya",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerubayijani",
  "BA": "Bosiniya na Herigozevine",
  "BB": "Barubadosi",
  "BD": "Bangaladeshi",
  "BE": "Ububiligi",
  "BF": "Burukina Faso",
  "BG": "Buligariya",
  "BH": "Bahareyini",
  "BI": "Uburundi",
  "BJ": "Bene",
  "BL": "St. Barthélemy",
  "BM": "Berimuda",
  "BN": "Buruneyi",
  "BO": "Boliviya",
  "BQ": "Caribbean Netherlands",
  "BR": "Burezili",
  "BS": "Bahamasi",
  "BT": "Butani",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belausi",
  "BZ": "Belize",
  "CA": "Kanada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Repubulika Iharanira Demokarasi ya Kongo",
  "CF": "Repubulika ya Santarafurika",
  "CG": "Kongo",
  "CH": "Ubusuwisi",
  "CI": "Kotedivuware",
  "CK": "Izinga rya Kuku",
  "CL": "Shili",
  "CM": "Kameruni",
  "CN": "Ubushinwa",
  "CO": "Kolombiya",
  "CR": "Kositarika",
  "CS": "Seribiya na Montenegoro",
  "CU": "Kiba",
  "CV": "Ibirwa bya Kapuveri",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Izinga rya Shipure",
  "CZ": "Repubulika ya Ceke",
  "DE": "Ubudage",
  "DJ": "Jibuti",
  "DK": "Danimariki",
  "DM": "Dominika",
  "DO": "Repubulika ya Dominika",
  "DZ": "Alijeriya",
  "EC": "Ekwateri",
  "EE": "Esitoniya",
  "EG": "Misiri",
  "EH": "Western Sahara",
  "ER": "Elitereya",
  "ES": "Hisipaniya",
  "ET": "Etiyopiya",
  "FI": "Finilandi",
  "FJ": "Fiji",
  "FK": "Izinga rya Filikilandi",
  "FM": "Mikoroniziya",
  "FO": "Faroe Islands",
  "FR": "Ubufaransa",
  "GA": "Gabo",
  "GB": "Ubwongereza",
  "GD": "Gerenada",
  "GE": "Jeworujiya",
  "GF": "Gwayana y’Abafaransa",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Juburalitari",
  "GL": "Gurunilandi",
  "GM": "Gambiya",
  "GN": "Guneya",
  "GP": "Gwadelupe",
  "GQ": "Gineya Ekwatoriyali",
  "GR": "Ubugereki",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Gwatemala",
  "GU": "Gwamu",
  "GW": "Gineya Bisawu",
  "GY": "Guyane",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Hondurasi",
  "HR": "Korowasiya",
  "HT": "Hayiti",
  "HU": "Hungariya",
  "ID": "Indoneziya",
  "IE": "Irilandi",
  "IL": "Isiraheli",
  "IM": "Isle of Man",
  "IN": "Ubuhindi",
  "IO": "Intara y’Ubwongereza yo mu birwa by’Abahindi",
  "IQ": "Iraki",
  "IR": "Irani",
  "IS": "Ayisilandi",
  "IT": "Ubutaliyani",
  "JE": "Jersey",
  "JM": "Jamayika",
  "JO": "Yorudaniya",
  "JP": "Ubuyapani",
  "KE": "Kenya",
  "KG": "Kirigisitani",
  "KH": "Kamboje",
  "KI": "Kiribati",
  "KM": "Izinga rya Komore",
  "KN": "Sekitsi na Nevisi",
  "KP": "Koreya y’amajaruguru",
  "KR": "Koreya y’amajepfo",
  "KW": "Koweti",
  "KY": "Ibirwa bya Keyimani",
  "KZ": "Kazakisitani",
  "LA": "Layosi",
  "LB": "Libani",
  "LC": "Selusiya",
  "LI": "Lishyitenshitayini",
  "LK": "Sirilanka",
  "LR": "Liberiya",
  "LS": "Lesoto",
  "LT": "Lituwaniya",
  "LU": "Lukusamburu",
  "LV": "Lativa",
  "LY": "Libiya",
  "MA": "Maroke",
  "MC": "Monako",
  "MD": "Moludavi",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagasikari",
  "MH": "Izinga rya Marishari",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Birimaniya",
  "MN": "Mongoliya",
  "MO": "Macao SAR China",
  "MP": "Amazinga ya Mariyana ryo mu majaruguru",
  "MQ": "Maritiniki",
  "MR": "Moritaniya",
  "MS": "Monteserati",
  "MT": "Malita",
  "MU": "Izinga rya Morise",
  "MV": "Moludave",
  "MW": "Malawi",
  "MX": "Migizike",
  "MY": "Maleziya",
  "MZ": "Mozambiki",
  "NA": "Namibiya",
  "NC": "Niyukaledoniya",
  "NE": "Nijeri",
  "NF": "izinga rya Norufoluke",
  "NG": "Nijeriya",
  "NI": "Nikaragwa",
  "NL": "Ubuholandi",
  "NO": "Noruveji",
  "NP": "Nepali",
  "NR": "Nawuru",
  "NU": "Niyuwe",
  "NZ": "Nuvelizelandi",
  "OM": "Omani",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Polineziya y’Abafaransa",
  "PG": "Papuwa Niyugineya",
  "PH": "Amazinga ya Filipine",
  "PK": "Pakisitani",
  "PL": "Polonye",
  "PM": "Sempiyeri na Mikeloni",
  "PN": "Pitikeyirini",
  "PR": "Puwetoriko",
  "PS": "Palesitina Wesitibanka na Gaza",
  "PT": "Porutugali",
  "PW": "Palawu",
  "PY": "Paragwe",
  "QA": "Katari",
  "RE": "Amazinga ya Reyiniyo",
  "RO": "Rumaniya",
  "RS": "Serbia",
  "RU": "Uburusiya",
  "RW": "u Rwanda",
  "SA": "Arabiya Sawudite",
  "SB": "Amazinga ya Salumoni",
  "SC": "Amazinga ya Seyisheli",
  "SD": "Sudani",
  "SE": "Suwedi",
  "SG": "Singapuru",
  "SH": "Sehelene",
  "SI": "Siloveniya",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Silovakiya",
  "SL": "Siyeralewone",
  "SM": "Sanimarino",
  "SN": "Senegali",
  "SO": "Somaliya",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sawotome na Perensipe",
  "SV": "Eli Saluvatori",
  "SX": "Sint Maarten",
  "SY": "Siriya",
  "SZ": "Suwazilandi",
  "TC": "Amazinga ya Turkisi na Cayikosi",
  "TD": "Cadi",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Tayilandi",
  "TJ": "Tajikisitani",
  "TK": "Tokelawu",
  "TL": "Timoru y’iburasirazuba",
  "TM": "Turukumenisitani",
  "TN": "Tuniziya",
  "TO": "Tonga",
  "TR": "Turukiya",
  "TT": "Tirinidadi na Tobago",
  "TV": "Tuvalu",
  "TW": "Tayiwani",
  "TZ": "Tanzaniya",
  "UA": "Ikerene",
  "UG": "Ubugande",
  "UM": "U.S. Outlying Islands",
  "US": "Leta Zunze Ubumwe za Amerika",
  "UY": "Irigwe",
  "UZ": "Uzubekisitani",
  "VA": "Umurwa wa Vatikani",
  "VC": "Sevensa na Gerenadine",
  "VE": "Venezuwela",
  "VG": "Ibirwa by’isugi by’Abongereza",
  "VI": "Amazinga y’Isugi y’Abanyamerika",
  "VN": "Viyetinamu",
  "VU": "Vanuwatu",
  "WF": "Walisi na Futuna",
  "WS": "Samowa",
  "YE": "Yemeni",
  "YT": "Mayote",
  "ZA": "Afurika y’Epfo",
  "ZM": "Zambiya",
  "ZW": "Zimbabwe",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Igikani",
  "ak_GH": "Igikani (Gana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Ikimuhariki",
  "am_ET": "Ikimuhariki (Etiyopiya)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "Icarabu",
  "ar_001": "Modern Standard Arabic",
  "ar_AE": "Icarabu (Leta Zunze Ubumwe z’Abarabu)",
  "ar_BH": "Icarabu (Bahareyini)",
  "ar_DJ": "Icarabu (Jibuti)",
  "ar_DZ": "Icarabu (Alijeriya)",
  "ar_EG": "Icarabu (Misiri)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Icarabu (Elitereya)",
  "ar_IL": "Icarabu (Isiraheli)",
  "ar_IQ": "Icarabu (Iraki)",
  "ar_JO": "Icarabu (Yorudaniya)",
  "ar_KM": "Icarabu (Izinga rya Komore)",
  "ar_KW": "Icarabu (Koweti)",
  "ar_LB": "Icarabu (Libani)",
  "ar_LY": "Icarabu (Libiya)",
  "ar_MA": "Icarabu (Maroke)",
  "ar_MR": "Icarabu (Moritaniya)",
  "ar_OM": "Icarabu (Omani)",
  "ar_PS": "Icarabu (Palesitina Wesitibanka na Gaza)",
  "ar_QA": "Icarabu (Katari)",
  "ar_SA": "Icarabu (Arabiya Sawudite)",
  "ar_SD": "Icarabu (Sudani)",
  "ar_SO": "Icarabu (Somaliya)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Icarabu (Siriya)",
  "ar_TD": "Icarabu (Cadi)",
  "ar_TN": "Icarabu (Tuniziya)",
  "ar_YE": "Icarabu (Yemeni)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Assamese",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Ikibelarusiya",
  "be_BY": "Ikibelarusiya (Belausi)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Ikinyabuligariya",
  "bg_BG": "Ikinyabuligariya (Buligariya)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Ikibengali",
  "bn_BD": "Ikibengali (Bangaladeshi)",
  "bn_IN": "Ikibengali (Ubuhindi)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Breton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnian",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Central Kurdish",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "Igiceke",
  "cs_CZ": "Igiceke (Repubulika ya Ceke)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "Ikidage",
  "de_AT": "Ikidage (Otirishe)",
  "de_BE": "Ikidage (Ububiligi)",
  "de_CH": "Ikidage (Ubusuwisi)",
  "de_DE": "Ikidage (Ubudage)",
  "de_LI": "Ikidage (Lishyitenshitayini)",
  "de_LU": "Ikidage (Lukusamburu)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Ikigereki",
  "el_CY": "Ikigereki (Izinga rya Shipure)",
  "el_GR": "Ikigereki (Ubugereki)",
  "elx": "Elamite",
  "en": "Icongereza",
  "en_AG": "Icongereza (Antigwa na Baribuda)",
  "en_AI": "Icongereza (Angwila)",
  "en_AS": "Icongereza (Samowa nyamerika)",
  "en_AU": "Icongereza (Ositaraliya)",
  "en_BB": "Icongereza (Barubadosi)",
  "en_BE": "Icongereza (Ububiligi)",
  "en_BM": "Icongereza (Berimuda)",
  "en_BS": "Icongereza (Bahamasi)",
  "en_BW": "Icongereza (Botswana)",
  "en_BZ": "Icongereza (Belize)",
  "en_CA": "Icongereza (Kanada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Icongereza (Izinga rya Kuku)",
  "en_CM": "Icongereza (Kameruni)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Icongereza (Dominika)",
  "en_ER": "Icongereza (Elitereya)",
  "en_FJ": "Icongereza (Fiji)",
  "en_FK": "Icongereza (Izinga rya Filikilandi)",
  "en_FM": "Icongereza (Mikoroniziya)",
  "en_GB": "Icongereza (Ubwongereza)",
  "en_GD": "Icongereza (Gerenada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Icongereza (Gana)",
  "en_GI": "Icongereza (Juburalitari)",
  "en_GM": "Icongereza (Gambiya)",
  "en_GU": "Icongereza (Gwamu)",
  "en_GY": "Icongereza (Guyane)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Icongereza (Irilandi)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Icongereza (Ubuhindi)",
  "en_IO": "Icongereza (Intara y’Ubwongereza yo mu birwa by’Abahindi)",
  "en_JE": "English (Jersey)",
  "en_JM": "Icongereza (Jamayika)",
  "en_KE": "Icongereza (Kenya)",
  "en_KI": "Icongereza (Kiribati)",
  "en_KN": "Icongereza (Sekitsi na Nevisi)",
  "en_KY": "Icongereza (Ibirwa bya Keyimani)",
  "en_LC": "Icongereza (Selusiya)",
  "en_LR": "Icongereza (Liberiya)",
  "en_LS": "Icongereza (Lesoto)",
  "en_MG": "Icongereza (Madagasikari)",
  "en_MH": "Icongereza (Izinga rya Marishari)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Icongereza (Amazinga ya Mariyana ryo mu majaruguru)",
  "en_MS": "Icongereza (Monteserati)",
  "en_MT": "Icongereza (Malita)",
  "en_MU": "Icongereza (Izinga rya Morise)",
  "en_MW": "Icongereza (Malawi)",
  "en_MY": "Icongereza (Maleziya)",
  "en_NA": "Icongereza (Namibiya)",
  "en_NF": "Icongereza (izinga rya Norufoluke)",
  "en_NG": "Icongereza (Nijeriya)",
  "en_NR": "Icongereza (Nawuru)",
  "en_NU": "Icongereza (Niyuwe)",
  "en_NZ": "Icongereza (Nuvelizelandi)",
  "en_PG": "Icongereza (Papuwa Niyugineya)",
  "en_PH": "Icongereza (Amazinga ya Filipine)",
  "en_PK": "Icongereza (Pakisitani)",
  "en_PN": "Icongereza (Pitikeyirini)",
  "en_PR": "Icongereza (Puwetoriko)",
  "en_PW": "Icongereza (Palawu)",
  "en_RW": "Icongereza (u Rwanda)",
  "en_SB": "Icongereza (Amazinga ya Salumoni)",
  "en_SC": "Icongereza (Amazinga ya Seyisheli)",
  "en_SD": "Icongereza (Sudani)",
  "en_SG": "Icongereza (Singapuru)",
  "en_SH": "Icongereza (Sehelene)",
  "en_SL": "Icongereza (Siyeralewone)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Icongereza (Suwazilandi)",
  "en_TC": "Icongereza (Amazinga ya Turkisi na Cayikosi)",
  "en_TK": "Icongereza (Tokelawu)",
  "en_TO": "Icongereza (Tonga)",
  "en_TT": "Icongereza (Tirinidadi na Tobago)",
  "en_TV": "Icongereza (Tuvalu)",
  "en_TZ": "Icongereza (Tanzaniya)",
  "en_UG": "Icongereza (Ubugande)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Icongereza (Leta Zunze Ubumwe za Amerika)",
  "en_VC": "Icongereza (Sevensa na Gerenadine)",
  "en_VG": "Icongereza (Ibirwa by’isugi by’Abongereza)",
  "en_VI": "Icongereza (Amazinga y’Isugi y’Abanyamerika)",
  "en_VU": "Icongereza (Vanuwatu)",
  "en_WS": "Icongereza (Samowa)",
  "en_ZA": "Icongereza (Afurika y’Epfo)",
  "en_ZM": "Icongereza (Zambiya)",
  "en_ZW": "Icongereza (Zimbabwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "Icesipanyolo",
  "es_419": "Latin American Spanish",
  "es_AR": "Icesipanyolo (Arijantine)",
  "es_BO": "Icesipanyolo (Boliviya)",
  "es_CL": "Icesipanyolo (Shili)",
  "es_CO": "Icesipanyolo (Kolombiya)",
  "es_CR": "Icesipanyolo (Kositarika)",
  "es_CU": "Icesipanyolo (Kiba)",
  "es_DO": "Icesipanyolo (Repubulika ya Dominika)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Icesipanyolo (Ekwateri)",
  "es_ES": "Icesipanyolo (Hisipaniya)",
  "es_GQ": "Icesipanyolo (Gineya Ekwatoriyali)",
  "es_GT": "Icesipanyolo (Gwatemala)",
  "es_HN": "Icesipanyolo (Hondurasi)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Icesipanyolo (Migizike)",
  "es_NI": "Icesipanyolo (Nikaragwa)",
  "es_PA": "Icesipanyolo (Panama)",
  "es_PE": "Icesipanyolo (Peru)",
  "es_PH": "Icesipanyolo (Amazinga ya Filipine)",
  "es_PR": "Icesipanyolo (Puwetoriko)",
  "es_PY": "Icesipanyolo (Paragwe)",
  "es_SV": "Icesipanyolo (Eli Saluvatori)",
  "es_US": "Icesipanyolo (Leta Zunze Ubumwe za Amerika)",
  "es_UY": "Icesipanyolo (Irigwe)",
  "es_VE": "Icesipanyolo (Venezuwela)",
  "esu": "Central Yupik",
  "et": "Estonian",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Igiperisi",
  "fa_AF": "Igiperisi (Afuganisitani)",
  "fa_IR": "Igiperisi (Irani)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finnish",
  "fi_FI": "Finnish (Finland)",
  "fil": "Filipino",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Igifaransa",
  "fr_BE": "Igifaransa (Ububiligi)",
  "fr_BF": "Igifaransa (Burukina Faso)",
  "fr_BI": "Igifaransa (Uburundi)",
  "fr_BJ": "Igifaransa (Bene)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Igifaransa (Kanada)",
  "fr_CD": "Igifaransa (Repubulika Iharanira Demokarasi ya Kongo)",
  "fr_CF": "Igifaransa (Repubulika ya Santarafurika)",
  "fr_CG": "Igifaransa (Kongo)",
  "fr_CH": "Igifaransa (Ubusuwisi)",
  "fr_CI": "Igifaransa (Kotedivuware)",
  "fr_CM": "Igifaransa (Kameruni)",
  "fr_DJ": "Igifaransa (Jibuti)",
  "fr_DZ": "Igifaransa (Alijeriya)",
  "fr_FR": "Igifaransa (Ubufaransa)",
  "fr_GA": "Igifaransa (Gabo)",
  "fr_GF": "Igifaransa (Gwayana y’Abafaransa)",
  "fr_GN": "Igifaransa (Guneya)",
  "fr_GP": "Igifaransa (Gwadelupe)",
  "fr_GQ": "Igifaransa (Gineya Ekwatoriyali)",
  "fr_HT": "Igifaransa (Hayiti)",
  "fr_KM": "Igifaransa (Izinga rya Komore)",
  "fr_LU": "Igifaransa (Lukusamburu)",
  "fr_MA": "Igifaransa (Maroke)",
  "fr_MC": "Igifaransa (Monako)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Igifaransa (Madagasikari)",
  "fr_ML": "Igifaransa (Mali)",
  "fr_MQ": "Igifaransa (Maritiniki)",
  "fr_MR": "Igifaransa (Moritaniya)",
  "fr_MU": "Igifaransa (Izinga rya Morise)",
  "fr_NC": "Igifaransa (Niyukaledoniya)",
  "fr_NE": "Igifaransa (Nijeri)",
  "fr_PF": "Igifaransa (Polineziya y’Abafaransa)",
  "fr_PM": "Igifaransa (Sempiyeri na Mikeloni)",
  "fr_RE": "Igifaransa (Amazinga ya Reyiniyo)",
  "fr_RW": "Igifaransa (u Rwanda)",
  "fr_SC": "Igifaransa (Amazinga ya Seyisheli)",
  "fr_SN": "Igifaransa (Senegali)",
  "fr_SY": "Igifaransa (Siriya)",
  "fr_TD": "Igifaransa (Cadi)",
  "fr_TG": "Igifaransa (Togo)",
  "fr_TN": "Igifaransa (Tuniziya)",
  "fr_VU": "Igifaransa (Vanuwatu)",
  "fr_WF": "Igifaransa (Walisi na Futuna)",
  "fr_YT": "Igifaransa (Mayote)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Irish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Scottish Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guarani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Swiss German",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Igihawusa",
  "ha_GH": "Igihawusa (Gana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Igihawusa (Nijeri)",
  "ha_NG": "Igihawusa (Nijeriya)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "he_IL": "Hebrew (Israel)",
  "hi": "Igihindi",
  "hi_IN": "Igihindi (Ubuhindi)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Upper Sorbian",
  "hsn": "Xiang Chinese",
  "ht": "Haitian",
  "hu": "Ikinyahongiriya",
  "hu_HU": "Ikinyahongiriya (Hungariya)",
  "hup": "Hupa",
  "hy": "Armenian",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Ikinyendoziya",
  "id_ID": "Ikinyendoziya (Indoneziya)",
  "ie": "Interlingue",
  "ig": "Ikigubo",
  "ig_NG": "Ikigubo (Nijeriya)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Icelandic",
  "is_IS": "Icelandic (Iceland)",
  "it": "Igitaliyani",
  "it_CH": "Igitaliyani (Ubusuwisi)",
  "it_IT": "Igitaliyani (Ubutaliyani)",
  "it_SM": "Igitaliyani (Sanimarino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Ikiyapani",
  "ja_JP": "Ikiyapani (Ubuyapani)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Ikinyejava",
  "ka": "Georgian",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Igikambodiya",
  "km_KH": "Igikambodiya (Kamboje)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Ikinyakoreya",
  "ko_KP": "Ikinyakoreya (Koreya y’amajaruguru)",
  "ko_KR": "Ikinyakoreya (Koreya y’amajepfo)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdish",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kyrgyz",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lt": "Lithuanian",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latvian",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Macedonian",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Ikinyamaleziya",
  "ms_BN": "Ikinyamaleziya (Buruneyi)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Ikinyamaleziya (Maleziya)",
  "ms_SG": "Ikinyamaleziya (Singapuru)",
  "mt": "Maltese",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Ikinyabirimaniya",
  "my_MM": "Ikinyabirimaniya (Birimaniya)",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "Ikinepali",
  "ne_IN": "Ikinepali (Ubuhindi)",
  "ne_NP": "Ikinepali (Nepali)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Igiholandi",
  "nl_AW": "Igiholandi (Aruba)",
  "nl_BE": "Igiholandi (Ububiligi)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Igiholandi (Ubuholandi)",
  "nl_SR": "Igiholandi (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Norwegian",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriya",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "Igipunjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Igipunjabi (Ubuhindi)",
  "pa_PK": "Igipunjabi (Pakisitani)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Ikinyapolonye",
  "pl_PL": "Ikinyapolonye (Polonye)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Prussian",
  "pro": "Old Provençal",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Igiporutugari",
  "pt_AO": "Igiporutugari (Angola)",
  "pt_BR": "Igiporutugari (Burezili)",
  "pt_CV": "Igiporutugari (Ibirwa bya Kapuveri)",
  "pt_GW": "Igiporutugari (Gineya Bisawu)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Igiporutugari (Mozambiki)",
  "pt_PT": "Igiporutugari (Porutugali)",
  "pt_ST": "Igiporutugari (Sawotome na Perensipe)",
  "pt_TL": "Igiporutugari (Timoru y’iburasirazuba)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Ikirundi",
  "rn_BI": "Ikirundi (Uburundi)",
  "ro": "Ikinyarumaniya",
  "ro_MD": "Ikinyarumaniya (Moludavi)",
  "ro_RO": "Ikinyarumaniya (Rumaniya)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Ikirusiya",
  "ru_BY": "Ikirusiya (Belausi)",
  "ru_KG": "Ikirusiya (Kirigisitani)",
  "ru_KZ": "Ikirusiya (Kazakisitani)",
  "ru_MD": "Ikirusiya (Moludavi)",
  "ru_RU": "Ikirusiya (Uburusiya)",
  "ru_UA": "Ikirusiya (Ikerene)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Ikinyarwanda",
  "rw_RW": "Ikinyarwanda (u Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindhi",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Serbo-Croatian",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhala",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Slovenian",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Igisomali",
  "so_DJ": "Igisomali (Jibuti)",
  "so_ET": "Igisomali (Etiyopiya)",
  "so_KE": "Igisomali (Kenya)",
  "so_SO": "Igisomali (Somaliya)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Serbian",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Southern Sotho",
  "stq": "Saterland Frisian",
  "su": "Sundanese",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Igisuweduwa",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Igisuweduwa (Finilandi)",
  "sv_SE": "Igisuweduwa (Suwedi)",
  "sw": "Swahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Igitamili",
  "ta_IN": "Igitamili (Ubuhindi)",
  "ta_LK": "Igitamili (Sirilanka)",
  "ta_MY": "Igitamili (Maleziya)",
  "ta_SG": "Igitamili (Singapuru)",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "Ikinyatayilandi",
  "th_TH": "Ikinyatayilandi (Tayilandi)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmen",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Igiturukiya",
  "tr_CY": "Igiturukiya (Izinga rya Shipure)",
  "tr_TR": "Igiturukiya (Turukiya)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Central Atlas Tamazight",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "Ikinyayukereni",
  "uk_UA": "Ikinyayukereni (Ikerene)",
  "umb": "Umbundu",
  "und": "Unknown Language",
  "ur": "Inyeyurudu",
  "ur_IN": "Inyeyurudu (Ubuhindi)",
  "ur_PK": "Inyeyurudu (Pakisitani)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Ikinyaviyetinamu",
  "vi_VN": "Ikinyaviyetinamu (Viyetinamu)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Ikiyoruba",
  "yo_BJ": "Ikiyoruba (Bene)",
  "yo_NG": "Ikiyoruba (Nijeriya)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "Igishinwa",
  "zh_CN": "Igishinwa (Ubushinwa)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Chinese (Simplified)",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Chinese (Traditional)",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Igishinwa (Singapuru)",
  "zh_TW": "Igishinwa (Tayiwani)",
  "zu": "Ikizulu",
  "zu_ZA": "Ikizulu (Afurika y’Epfo)",
  "zun": "Zuni",
  "zxx": "No linguistic content",
  "zza": "Zaza"
};
