const names = {
  "001": "wereld",
  "002": "Afrika",
  "003": "Noord-Amerika",
  "005": "Zuid-Amerika",
  "009": "Oceanië",
  "011": "West-Afrika",
  "013": "Midden-Amerika",
  "014": "Oost-Afrika",
  "015": "Noord-Afrika",
  "017": "Centraal-Afrika",
  "018": "Zuidelijk Afrika",
  "019": "Amerika",
  "021": "Noordelijk Amerika",
  "029": "Caribisch gebied",
  "030": "Oost-Azië",
  "034": "Zuid-Azië",
  "035": "Zuidoost-Azië",
  "039": "Zuid-Europa",
  "053": "Australazië",
  "054": "Melanesië",
  "057": "Micronesische regio",
  "061": "Polynesië",
  "062": "Zuid-Centraal Azië",
  "142": "Azië",
  "143": "Centraal-Azië",
  "145": "West-Azië",
  "150": "Europa",
  "151": "Oost-Europa",
  "154": "Noord-Europa",
  "155": "West-Europa",
  "172": "Gemenebest van onafhankelijke staten",
  "200": "Tsjecho-Slowakije",
  "202": "Sub-Saharaans Afrika",
  "419": "Latijns-Amerika",
  "830": "Kanaal eilanden",
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Verenigde Arabische Emiraten",
  "AF": "Afghanistan",
  "AG": "Antigua en Barbuda",
  "AI": "Anguilla",
  "AL": "Albanië",
  "AM": "Armenië",
  "AN": "Nederlandse Antillen",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentinië",
  "AS": "Amerikaans-Samoa",
  "AT": "Oostenrijk",
  "AU": "Australië",
  "AW": "Aruba",
  "AX": "Åland",
  "AZ": "Azerbeidzjan",
  "Adlm": "Adlam",
  "Afak": "Defaka",
  "Aghb": "Kaukasisch Albanees",
  "Ahom": "Ahom",
  "Arab": "Arabisch",
  "Aran": "Nastaliq",
  "Armi": "Keizerlijk Aramees",
  "Armn": "Armeens",
  "Avst": "Avestaans",
  "BA": "Bosnië en Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "België",
  "BF": "Burkina Faso",
  "BG": "Bulgarije",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribisch Nederland",
  "BR": "Brazilië",
  "BS": "Bahama’s",
  "BT": "Bhutan",
  "BV": "Bouveteiland",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "Bali": "Balinees",
  "Bamu": "Bamoun",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Bengaals",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbolen",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Buginees",
  "Buhd": "Buhid",
  "CA": "Canada",
  "CC": "Cocoseilanden",
  "CD": "Congo-Kinshasa",
  "CF": "Centraal-Afrikaanse Republiek",
  "CG": "Congo-Brazzaville",
  "CH": "Zwitserland",
  "CI": "Ivoorkust",
  "CK": "Cookeilanden",
  "CL": "Chili",
  "CM": "Kameroen",
  "CN": "China",
  "CO": "Colombia",
  "CP": "Clipperton",
  "CR": "Costa Rica",
  "CS": "Servië en Montenegro",
  "CU": "Cuba",
  "CV": "Kaapverdië",
  "CW": "Curaçao",
  "CX": "Christmaseiland",
  "CY": "Cyprus",
  "CZ": "Tsjechië",
  "Cakm": "Chakma",
  "Cans": "Verenigde Canadese Aboriginal-symbolen",
  "Cari": "Carisch",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Chrs": "Chorasmisch",
  "Cirt": "Cirth",
  "Copt": "Koptisch",
  "Cprt": "Cyprisch",
  "Cyrl": "Cyrillisch",
  "Cyrs": "Oudkerkslavisch Cyrillisch",
  "DD": "Oost-Duitsland",
  "DE": "Duitsland",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Denemarken",
  "DM": "Dominica",
  "DO": "Dominicaanse Republiek",
  "DZ": "Algerije",
  "Deva": "Devanagari",
  "Diak": "Dives Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Duployan snelschrift",
  "EA": "Ceuta en Melilla",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Egypte",
  "EH": "Westelijke Sahara",
  "ER": "Eritrea",
  "ES": "Spanje",
  "ET": "Ethiopië",
  "EU": "Europese Unie",
  "EZ": "eurozone",
  "Egyd": "Egyptisch demotisch",
  "Egyh": "Egyptisch hiëratisch",
  "Egyp": "Egyptische hiërogliefen",
  "Elba": "Elbasan",
  "Elym": "Elymaisch",
  "Ethi": "Ethiopisch",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falklandeilanden",
  "FM": "Micronesia",
  "FO": "Faeröer",
  "FR": "Frankrijk",
  "FX": "Europese Frankrijk",
  "GA": "Gabon",
  "GB": "Verenigd Koninkrijk",
  "GD": "Grenada",
  "GE": "Georgië",
  "GF": "Frans-Guyana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenland",
  "GM": "Gambia",
  "GN": "Guinee",
  "GP": "Guadeloupe",
  "GQ": "Equatoriaal-Guinea",
  "GR": "Griekenland",
  "GS": "Zuid-Georgia en Zuidelijke Sandwicheilanden",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinee-Bissau",
  "GY": "Guyana",
  "Geok": "Georgisch Khutsuri",
  "Geor": "Georgisch",
  "Glag": "Glagolitisch",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gothisch",
  "Gran": "Grantha",
  "Grek": "Grieks",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Hongkong SAR van China",
  "HM": "Heard en McDonaldeilanden",
  "HN": "Honduras",
  "HR": "Kroatië",
  "HT": "Haïti",
  "HU": "Hongarije",
  "Hanb": "Han met Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "vereenvoudigd",
  "Hant": "traditioneel",
  "Hatr": "Hatran",
  "Hebr": "Hebreeuws",
  "Hira": "Hiragana",
  "Hluw": "Anatolische hiërogliefen",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Katakana of Hiragana",
  "Hung": "Oudhongaars",
  "IC": "Canarische Eilanden",
  "ID": "Indonesië",
  "IE": "Ierland",
  "IL": "Israël",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "Brits Indische Oceaanterritorium",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "IJsland",
  "IT": "Italië",
  "Inds": "Indus",
  "Ital": "Oud-italisch",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordanië",
  "JP": "Japan",
  "Jamo": "Jamo",
  "Java": "Javaans",
  "Jpan": "Japans",
  "Jurc": "Jurchen",
  "KE": "Kenia",
  "KG": "Kirgizië",
  "KH": "Cambodja",
  "KI": "Kiribati",
  "KM": "Comoren",
  "KN": "Saint Kitts en Nevis",
  "KP": "Noord-Korea",
  "KR": "Zuid-Korea",
  "KW": "Koeweit",
  "KY": "Kaaimaneilanden",
  "KZ": "Kazachstan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kits": "Kitaans kleinschrift",
  "Knda": "Kannada",
  "Kore": "Koreaans",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litouwen",
  "LU": "Luxemburg",
  "LV": "Letland",
  "LY": "Libië",
  "Lana": "Lanna",
  "Laoo": "Laotiaans",
  "Latf": "Gotisch Latijns",
  "Latg": "Gaelisch Latijns",
  "Latn": "Latijns",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Lineair A",
  "Linb": "Lineair B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycisch",
  "Lydi": "Lydisch",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldavië",
  "ME": "Montenegro",
  "MF": "Saint-Martin",
  "MG": "Madagaskar",
  "MH": "Marshalleilanden",
  "MI": "Midway-eilanden",
  "MK": "Noord-Macedonië",
  "ML": "Mali",
  "MM": "Myanmar (Birma)",
  "MN": "Mongolië",
  "MO": "Macau SAR van China",
  "MP": "Noordelijke Marianen",
  "MQ": "Martinique",
  "MR": "Mauritanië",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldiven",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Maleisië",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaeans",
  "Mani": "Manicheaans",
  "Marc": "Marchen",
  "Maya": "Mayahiërogliefen",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitisch cursief",
  "Mero": "Meroïtisch",
  "Mlym": "Malayalam",
  "Modi": "Modi",
  "Mong": "Mongools",
  "Moon": "Moon",
  "Mroo": "Mro",
  "Mtei": "Meitei",
  "Mult": "Multani",
  "Mymr": "Birmaans",
  "NA": "Namibië",
  "NC": "Nieuw-Caledonië",
  "NE": "Niger",
  "NF": "Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Nederland",
  "NO": "Noorwegen",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Neutrale zone",
  "NU": "Niue",
  "NZ": "Nieuw-Zeeland",
  "Nand": "Nandinagari",
  "Narb": "Oud Noord-Arabisch",
  "Nbat": "Nabateaans",
  "Newa": "Newari",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Odia",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Pacific Islands Trust Territory",
  "PE": "Peru",
  "PF": "Frans-Polynesië",
  "PG": "Papoea-Nieuw-Guinea",
  "PH": "Filipijnen",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint-Pierre en Miquelon",
  "PN": "Pitcairneilanden",
  "PR": "Puerto Rico",
  "PS": "Palestijnse gebieden",
  "PT": "Portugal",
  "PU": "Diverse Amerikaanse eilanden in de Stille Oceaan",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Panamakanaalzone",
  "Palm": "Palmyreens",
  "Pauc": "Pau Cin Hau",
  "Perm": "Oudpermisch",
  "Phag": "Phags-pa",
  "Phli": "Inscriptioneel Pahlavi",
  "Phlp": "Psalmen Pahlavi",
  "Phlv": "Boek Pahlavi",
  "Phnx": "Foenicisch",
  "Plrd": "Pollard-fonetisch",
  "Prti": "Inscriptioneel Parthisch",
  "QA": "Qatar",
  "QO": "overig Oceanië",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Roemenië",
  "RS": "Servië",
  "RU": "Rusland",
  "RW": "Rwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Saoedi-Arabië",
  "SB": "Salomonseilanden",
  "SC": "Seychellen",
  "SD": "Soedan",
  "SE": "Zweden",
  "SG": "Singapore",
  "SH": "Sint-Helena",
  "SI": "Slovenië",
  "SJ": "Spitsbergen en Jan Mayen",
  "SK": "Slowakije",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalië",
  "SR": "Suriname",
  "SS": "Zuid-Soedan",
  "ST": "Sao Tomé en Principe",
  "SU": "Unie van Socialistische Sovjetrepublieken",
  "SV": "El Salvador",
  "SX": "Sint-Maarten",
  "SY": "Syrië",
  "SZ": "eSwatini",
  "Samr": "Samaritaans",
  "Sara": "Sarati",
  "Sarb": "Oud Zuid-Arabisch",
  "Saur": "Saurashtra",
  "Sgnw": "SignWriting",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Sindhi",
  "Sinh": "Singalees",
  "Sogd": "Sogdisch",
  "Sogo": "Oud Sogdisch",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Soendanees",
  "Sylo": "Syloti Nagri",
  "Syrc": "Syriac",
  "Syre": "Estrangelo Aramees",
  "Syrj": "West-Aramees",
  "Syrn": "Oost-Aramees",
  "TA": "Tristan da Cunha",
  "TC": "Turks- en Caicoseilanden",
  "TD": "Tsjaad",
  "TF": "Franse Gebieden in de zuidelijke Indische Oceaan",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadzjikistan",
  "TK": "Tokelau",
  "TL": "Oost-Timor",
  "TM": "Turkmenistan",
  "TN": "Tunesië",
  "TO": "Tonga",
  "TR": "Turkije",
  "TT": "Trinidad en Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Nieuw Tai Lue",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibetaans",
  "Tirh": "Tirhuta",
  "UA": "Oekraïne",
  "UG": "Oeganda",
  "UM": "Kleine afgelegen eilanden van de Verenigde Staten",
  "UN": "Verenigde Naties",
  "US": "Verenigde Staten",
  "UY": "Uruguay",
  "UZ": "Oezbekistan",
  "Ugar": "Ugaritisch",
  "VA": "Vaticaanstad",
  "VC": "Saint Vincent en de Grenadines",
  "VD": "Noord-Vietnam",
  "VE": "Venezuela",
  "VG": "Britse Maagdeneilanden",
  "VI": "Amerikaanse Maagdeneilanden",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Zichtbare spraak",
  "WF": "Wallis en Futuna",
  "WK": "Wake Island",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Pseudo-Accenten",
  "XB": "Pseudo-Bidi",
  "XK": "Kosovo",
  "Xpeo": "Oudperzisch",
  "Xsux": "Sumero-Akkadian Cuneiform",
  "YD": "Democratische Volksrepubliek Jemen",
  "YE": "Jemen",
  "YT": "Mayotte",
  "Yezi": "Jezidi",
  "Yiii": "Yi",
  "ZA": "Zuid-Afrika",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "onbekend gebied",
  "Zanb": "vierkant Zanabazar",
  "Zinh": "Overgeërfd",
  "Zmth": "Wiskundige notatie",
  "Zsye": "emoji",
  "Zsym": "Symbolen",
  "Zxxx": "ongeschreven",
  "Zyyy": "algemeen",
  "Zzzz": "onbekend schriftsysteem",
  "aa": "Afar",
  "ab": "Abchazisch",
  "ace": "Atjehs",
  "ach": "Akoli",
  "ada": "Adangme",
  "ady": "Adygees",
  "ae": "Avestisch",
  "aeb": "Tunesisch Arabisch",
  "af": "Afrikaans",
  "af_NA": "Afrikaans (Namibië)",
  "af_ZA": "Afrikaans (Zuid-Afrika)",
  "afa": "Afro-Aziatische taal",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Aino",
  "ak": "Akan",
  "ak_GH": "Akan (Ghana)",
  "akk": "Akkadisch",
  "akz": "Alabama",
  "ale": "Aleoetisch",
  "alg": "Algonkium-taal",
  "aln": "Gegisch",
  "alt": "Zuid-Altaïsch",
  "am": "Amhaars",
  "am_ET": "Amhaars (Ethiopië)",
  "an": "Aragonees",
  "ang": "Oudengels",
  "anp": "Angika",
  "apa": "Apache-taal",
  "ar": "Arabisch",
  "ar_001": "modern standaard Arabisch",
  "ar_AE": "Arabisch (Verenigde Arabische Emiraten)",
  "ar_BH": "Arabisch (Bahrein)",
  "ar_DJ": "Arabisch (Djibouti)",
  "ar_DZ": "Arabisch (Algerije)",
  "ar_EG": "Arabisch (Egypte)",
  "ar_EH": "Arabisch (Westelijke Sahara)",
  "ar_ER": "Arabisch (Eritrea)",
  "ar_IL": "Arabisch (Israël)",
  "ar_IQ": "Arabisch (Irak)",
  "ar_JO": "Arabisch (Jordanië)",
  "ar_KM": "Arabisch (Comoren)",
  "ar_KW": "Arabisch (Koeweit)",
  "ar_LB": "Arabisch (Libanon)",
  "ar_LY": "Arabisch (Libië)",
  "ar_MA": "Arabisch (Marokko)",
  "ar_MR": "Arabisch (Mauritanië)",
  "ar_OM": "Arabisch (Oman)",
  "ar_PS": "Arabisch (Palestijnse gebieden)",
  "ar_QA": "Arabisch (Qatar)",
  "ar_SA": "Arabisch (Saoedi-Arabië)",
  "ar_SD": "Arabisch (Soedan)",
  "ar_SO": "Arabisch (Somalië)",
  "ar_SS": "Arabisch (Zuid-Soedan)",
  "ar_SY": "Arabisch (Syrië)",
  "ar_TD": "Arabisch (Tsjaad)",
  "ar_TN": "Arabisch (Tunesië)",
  "ar_YE": "Arabisch (Jemen)",
  "arc": "Aramees",
  "arn": "Mapudungun",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerijns Arabisch",
  "ars": "Nadjdi-Arabisch",
  "art": "Kunstmatige taal",
  "arw": "Arawak",
  "ary": "Marokkaans Arabisch",
  "arz": "Egyptisch Arabisch",
  "as": "Assamees",
  "as_IN": "Assamees (India)",
  "asa": "Asu",
  "ase": "Amerikaanse Gebarentaal",
  "ast": "Asturisch",
  "ath": "Athapascaanse taal",
  "aus": "Australische taal",
  "av": "Avarisch",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbeidzjaans",
  "az_AZ": "Azerbeidzjaans (Azerbeidzjan)",
  "az_Arab": "Azerbeidzjaans (Arabisch)",
  "az_Cyrl": "Azerbeidzjaans (Cyrillisch)",
  "az_Cyrl_AZ": "Azerbeidzjaans (Cyrillisch, Azerbeidzjan)",
  "az_Latn": "Azerbeidzjaans (Latijn)",
  "az_Latn_AZ": "Azerbeidzjaans (Latijn, Azerbeidzjan)",
  "azb": "Zuid-Azerbeidzjaans Arabisch",
  "ba": "Basjkiers",
  "bad": "Banda",
  "bai": "Bamileke-taal",
  "bal": "Beloetsji",
  "ban": "Balinees",
  "bar": "Beiers",
  "bas": "Basa",
  "bat": "Baltische taal",
  "bax": "Bamoun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala’",
  "be": "Wit-Russisch",
  "be_BY": "Wit-Russisch (Wit-Rusland)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaars",
  "bg_BG": "Bulgaars (Bulgarije)",
  "bgn": "Westers Beloetsji",
  "bh": "Bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latijn)",
  "bm_Latn_ML": "Bambara (Latijn, Mali)",
  "bn": "Bengaals",
  "bn_BD": "Bengaals (Bangladesh)",
  "bn_IN": "Bengaals (India)",
  "bnt": "Bantoe",
  "bo": "Tibetaans",
  "bo_CN": "Tibetaans (China)",
  "bo_IN": "Tibetaans (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Bretons",
  "br_FR": "Bretons (Frankrijk)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnisch",
  "bs_BA": "Bosnisch (Bosnië en Herzegovina)",
  "bs_Cyrl": "Bosnisch (Cyrillisch)",
  "bs_Cyrl_BA": "Bosnisch (Cyrillisch, Bosnië en Herzegovina)",
  "bs_Latn": "Bosnisch (Latijn)",
  "bs_Latn_BA": "Bosnisch (Latijn, Bosnië en Herzegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Boerjatisch",
  "bug": "Buginees",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalaans",
  "ca_AD": "Catalaans (Andorra)",
  "ca_ES": "Catalaans (Spanje)",
  "ca_FR": "Catalaans (Frankrijk)",
  "ca_IT": "Catalaans (Italië)",
  "cad": "Caddo",
  "cai": "Midden-Amerikaans Indiaanse taal",
  "car": "Caribisch",
  "cau": "Kaukasische taal",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Tsjetsjeens",
  "ceb": "Cebuano",
  "cel": "Keltische taal",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukees",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Soranî",
  "cmc": "Chamische taal",
  "co": "Corsicaans",
  "cop": "Koptisch",
  "cpe": "Op Engels gebaseerd Creools of Pidgin",
  "cpf": "Op Frans gebaseerd Creools of Pidgin",
  "cpp": "Op Portugees gebaseerd Creools of Pidgin",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Krim-Tataars",
  "crp": "Creools of Pidgin",
  "crs": "Seychellencreools",
  "cs": "Tsjechisch",
  "cs_CZ": "Tsjechisch (Tsjechië)",
  "csb": "Kasjoebisch",
  "cu": "Kerkslavisch",
  "cus": "Koesjitische taal",
  "cv": "Tsjoevasjisch",
  "cy": "Welsh",
  "cy_GB": "Welsh (Verenigd Koninkrijk)",
  "da": "Deens",
  "da_DK": "Deens (Denemarken)",
  "da_GL": "Deens (Groenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dajak",
  "de": "Duits",
  "de_AT": "Duits (Oostenrijk)",
  "de_BE": "Duits (België)",
  "de_CH": "Duits (Zwitserland)",
  "de_DE": "Duits (Duitsland)",
  "de_LI": "Duits (Liechtenstein)",
  "de_LU": "Duits (Luxemburg)",
  "del": "Delaware",
  "den": "Slavey",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Dravidische taal",
  "dsb": "Nedersorbisch",
  "dtp": "Dusun",
  "dua": "Duala",
  "dum": "Middelnederlands",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emiliano",
  "egy": "Oudegyptisch",
  "eka": "Ekajuk",
  "el": "Grieks",
  "el_CY": "Grieks (Cyprus)",
  "el_GR": "Grieks (Griekenland)",
  "elx": "Elamitisch",
  "en": "Engels",
  "en_AG": "Engels (Antigua en Barbuda)",
  "en_AI": "Engels (Anguilla)",
  "en_AS": "Engels (Amerikaans-Samoa)",
  "en_AU": "Engels (Australië)",
  "en_BB": "Engels (Barbados)",
  "en_BE": "Engels (België)",
  "en_BM": "Engels (Bermuda)",
  "en_BS": "Engels (Bahama’s)",
  "en_BW": "Engels (Botswana)",
  "en_BZ": "Engels (Belize)",
  "en_CA": "Engels (Canada)",
  "en_CC": "Engels (Cocoseilanden)",
  "en_CK": "Engels (Cookeilanden)",
  "en_CM": "Engels (Kameroen)",
  "en_CX": "Engels (Christmaseiland)",
  "en_DG": "Engels (Diego Garcia)",
  "en_DM": "Engels (Dominica)",
  "en_Dsrt": "Engels (Deseret)",
  "en_ER": "Engels (Eritrea)",
  "en_FJ": "Engels (Fiji)",
  "en_FK": "Engels (Falklandeilanden)",
  "en_FM": "Engels (Micronesia)",
  "en_GB": "Engels (Verenigd Koninkrijk)",
  "en_GD": "Engels (Grenada)",
  "en_GG": "Engels (Guernsey)",
  "en_GH": "Engels (Ghana)",
  "en_GI": "Engels (Gibraltar)",
  "en_GM": "Engels (Gambia)",
  "en_GU": "Engels (Guam)",
  "en_GY": "Engels (Guyana)",
  "en_HK": "Engels (Hongkong SAR van China)",
  "en_IE": "Engels (Ierland)",
  "en_IM": "Engels (Isle of Man)",
  "en_IN": "Engels (India)",
  "en_IO": "Engels (Britse Gebieden in de Indische Oceaan)",
  "en_JE": "Engels (Jersey)",
  "en_JM": "Engels (Jamaica)",
  "en_KE": "Engels (Kenia)",
  "en_KI": "Engels (Kiribati)",
  "en_KN": "Engels (Saint Kitts en Nevis)",
  "en_KY": "Engels (Caymaneilanden)",
  "en_LC": "Engels (Saint Lucia)",
  "en_LR": "Engels (Liberia)",
  "en_LS": "Engels (Lesotho)",
  "en_MG": "Engels (Madagaskar)",
  "en_MH": "Engels (Marshalleilanden)",
  "en_MO": "Engels (Macau SAR van China)",
  "en_MP": "Engels (Noordelijke Marianen)",
  "en_MS": "Engels (Montserrat)",
  "en_MT": "Engels (Malta)",
  "en_MU": "Engels (Mauritius)",
  "en_MW": "Engels (Malawi)",
  "en_MY": "Engels (Maleisië)",
  "en_NA": "Engels (Namibië)",
  "en_NF": "Engels (Norfolk)",
  "en_NG": "Engels (Nigeria)",
  "en_NR": "Engels (Nauru)",
  "en_NU": "Engels (Niue)",
  "en_NZ": "Engels (Nieuw-Zeeland)",
  "en_PG": "Engels (Papoea-Nieuw-Guinea)",
  "en_PH": "Engels (Filipijnen)",
  "en_PK": "Engels (Pakistan)",
  "en_PN": "Engels (Pitcairneilanden)",
  "en_PR": "Engels (Puerto Rico)",
  "en_PW": "Engels (Palau)",
  "en_RW": "Engels (Rwanda)",
  "en_SB": "Engels (Salomonseilanden)",
  "en_SC": "Engels (Seychellen)",
  "en_SD": "Engels (Soedan)",
  "en_SG": "Engels (Singapore)",
  "en_SH": "Engels (Sint-Helena)",
  "en_SL": "Engels (Sierra Leone)",
  "en_SS": "Engels (Zuid-Soedan)",
  "en_SX": "Engels (Sint-Maarten)",
  "en_SZ": "Engels (Swaziland)",
  "en_TC": "Engels (Turks- en Caicoseilanden)",
  "en_TK": "Engels (Tokelau)",
  "en_TO": "Engels (Tonga)",
  "en_TT": "Engels (Trinidad en Tobago)",
  "en_TV": "Engels (Tuvalu)",
  "en_TZ": "Engels (Tanzania)",
  "en_UG": "Engels (Oeganda)",
  "en_UM": "Engels (Kleine afgelegen eilanden van de Verenigde Staten)",
  "en_US": "Engels (Verenigde Staten)",
  "en_VC": "Engels (Saint Vincent en de Grenadines)",
  "en_VG": "Engels (Britse Maagdeneilanden)",
  "en_VI": "Engels (Amerikaanse Maagdeneilanden)",
  "en_VU": "Engels (Vanuatu)",
  "en_WS": "Engels (Samoa)",
  "en_ZA": "Engels (Zuid-Afrika)",
  "en_ZM": "Engels (Zambia)",
  "en_ZW": "Engels (Zimbabwe)",
  "enm": "Middelengels",
  "eo": "Esperanto",
  "es": "Spaans",
  "es_419": "Latijns-Amerikaans Spaans",
  "es_AR": "Spaans (Argentinië)",
  "es_BO": "Spaans (Bolivia)",
  "es_CL": "Spaans (Chili)",
  "es_CO": "Spaans (Colombia)",
  "es_CR": "Spaans (Costa Rica)",
  "es_CU": "Spaans (Cuba)",
  "es_DO": "Spaans (Dominicaanse Republiek)",
  "es_EA": "Spaans (Ceuta en Melilla)",
  "es_EC": "Spaans (Ecuador)",
  "es_ES": "Spaans (Spanje)",
  "es_GQ": "Spaans (Equatoriaal-Guinea)",
  "es_GT": "Spaans (Guatemala)",
  "es_HN": "Spaans (Honduras)",
  "es_IC": "Spaans (Canarische Eilanden)",
  "es_MX": "Spaans (Mexico)",
  "es_NI": "Spaans (Nicaragua)",
  "es_PA": "Spaans (Panama)",
  "es_PE": "Spaans (Peru)",
  "es_PH": "Spaans (Filipijnen)",
  "es_PR": "Spaans (Puerto Rico)",
  "es_PY": "Spaans (Paraguay)",
  "es_SV": "Spaans (El Salvador)",
  "es_US": "Spaans (Verenigde Staten)",
  "es_UY": "Spaans (Uruguay)",
  "es_VE": "Spaans (Venezuela)",
  "esu": "Yupik",
  "et": "Estisch",
  "et_EE": "Estisch (Estland)",
  "eu": "Baskisch",
  "eu_ES": "Baskisch (Spanje)",
  "ewo": "Ewondo",
  "ext": "Extremeens",
  "fa": "Perzisch",
  "fa_AF": "Perzisch (Afghanistan)",
  "fa_IR": "Perzisch (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Kameroen)",
  "ff_GN": "Fulah (Guinee)",
  "ff_MR": "Fulah (Mauritanië)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Fins",
  "fi_FI": "Fins (Finland)",
  "fil": "Filipijns",
  "fit": "Tornedal-Fins",
  "fiu": "Fins-Oegrische taal",
  "fj": "Fijisch",
  "fo": "Faeröers",
  "fo_FO": "Faeröers (Faeröer)",
  "fon": "Fon",
  "fr": "Frans",
  "fr_BE": "Frans (België)",
  "fr_BF": "Frans (Burkina Faso)",
  "fr_BI": "Frans (Burundi)",
  "fr_BJ": "Frans (Benin)",
  "fr_BL": "Frans (Saint-Barthélemy)",
  "fr_CA": "Frans (Canada)",
  "fr_CD": "Frans (Congo-Kinshasa)",
  "fr_CF": "Frans (Centraal-Afrikaanse Republiek)",
  "fr_CG": "Frans (Congo-Brazzaville)",
  "fr_CH": "Frans (Zwitserland)",
  "fr_CI": "Frans (Ivoorkust)",
  "fr_CM": "Frans (Kameroen)",
  "fr_DJ": "Frans (Djibouti)",
  "fr_DZ": "Frans (Algerije)",
  "fr_FR": "Frans (Frankrijk)",
  "fr_GA": "Frans (Gabon)",
  "fr_GF": "Frans (Frans-Guyana)",
  "fr_GN": "Frans (Guinee)",
  "fr_GP": "Frans (Guadeloupe)",
  "fr_GQ": "Frans (Equatoriaal-Guinea)",
  "fr_HT": "Frans (Haïti)",
  "fr_KM": "Frans (Comoren)",
  "fr_LU": "Frans (Luxemburg)",
  "fr_MA": "Frans (Marokko)",
  "fr_MC": "Frans (Monaco)",
  "fr_MF": "Frans (Saint-Martin)",
  "fr_MG": "Frans (Madagaskar)",
  "fr_ML": "Frans (Mali)",
  "fr_MQ": "Frans (Martinique)",
  "fr_MR": "Frans (Mauritanië)",
  "fr_MU": "Frans (Mauritius)",
  "fr_NC": "Frans (Nieuw-Caledonië)",
  "fr_NE": "Frans (Niger)",
  "fr_PF": "Frans (Frans-Polynesië)",
  "fr_PM": "Frans (Saint-Pierre en Miquelon)",
  "fr_RE": "Frans (Réunion)",
  "fr_RW": "Frans (Rwanda)",
  "fr_SC": "Frans (Seychellen)",
  "fr_SN": "Frans (Senegal)",
  "fr_SY": "Frans (Syrië)",
  "fr_TD": "Frans (Tsjaad)",
  "fr_TG": "Frans (Togo)",
  "fr_TN": "Frans (Tunesië)",
  "fr_VU": "Frans (Vanuatu)",
  "fr_WF": "Frans (Wallis en Futuna)",
  "fr_YT": "Frans (Mayotte)",
  "frc": "Cajun-Frans",
  "frm": "Middelfrans",
  "fro": "Oudfrans",
  "frp": "Arpitaans",
  "frr": "Noord-Fries",
  "frs": "Oost-Fries",
  "fur": "Friulisch",
  "fy": "Fries",
  "fy_NL": "Fries (Nederland)",
  "ga": "Iers",
  "ga_IE": "Iers (Ierland)",
  "gaa": "Ga",
  "gag": "Gagaoezisch",
  "gan": "Ganyu",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrisch Dari",
  "gd": "Schots-Gaelisch",
  "gd_GB": "Schots-Gaelisch (Verenigd Koninkrijk)",
  "gem": "Germaanse taal",
  "gez": "Ge’ez",
  "gil": "Gilbertees",
  "gl": "Galicisch",
  "gl_ES": "Galicisch (Spanje)",
  "glk": "Gilaki",
  "gmh": "Middelhoogduits",
  "gn": "Guaraní",
  "goh": "Oudhoogduits",
  "gom": "Goa Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothisch",
  "grb": "Grebo",
  "grc": "Oudgrieks",
  "gsw": "Zwitserduits",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Gurune",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Ghana)",
  "ha_Latn": "Hausa (Latijn)",
  "ha_Latn_GH": "Hausa (Latijn, Ghana)",
  "ha_Latn_NE": "Hausa (Latijn, Niger)",
  "ha_Latn_NG": "Hausa (Latijn, Nigeria)",
  "ha_NE": "Hausa (Niger)",
  "ha_NG": "Hausa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka",
  "haw": "Hawaïaans",
  "he": "Hebreeuws",
  "he_IL": "Hebreeuws (Israël)",
  "hi": "Hindi",
  "hi_IN": "Hindi (India)",
  "hif": "Fijisch Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hettitisch",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Kroatisch",
  "hr_BA": "Kroatisch (Bosnië en Herzegovina)",
  "hr_HR": "Kroatisch (Kroatië)",
  "hsb": "Oppersorbisch",
  "hsn": "Xiangyu",
  "ht": "Haïtiaans Creools",
  "hu": "Hongaars",
  "hu_HU": "Hongaars (Hongarije)",
  "hup": "Hupa",
  "hy": "Armeens",
  "hy_AM": "Armeens (Armenië)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indonesisch",
  "id_ID": "Indonesisch (Indonesië)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Yi",
  "ii_CN": "Yi (China)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Indische taal",
  "ine": "Indo-Europese taal",
  "inh": "Ingoesjetisch",
  "io": "Ido",
  "ira": "Iraanse taal",
  "iro": "Irokese taal",
  "is": "IJslands",
  "is_IS": "IJslands (IJsland)",
  "it": "Italiaans",
  "it_CH": "Italiaans (Zwitserland)",
  "it_IT": "Italiaans (Italië)",
  "it_SM": "Italiaans (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrisch",
  "ja": "Japans",
  "ja_JP": "Japans (Japan)",
  "jam": "Jamaicaans Creools",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Perzisch",
  "jrb": "Judeo-Arabisch",
  "jut": "Jutlands",
  "jv": "Javaans",
  "ka": "Georgisch",
  "ka_GE": "Georgisch (Georgië)",
  "kaa": "Karakalpaks",
  "kab": "Kabylisch",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardisch",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kaapverdisch Creools",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Khoisan-taal",
  "kho": "Khotanees",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Gikuyu",
  "ki_KE": "Gikuyu (Kenia)",
  "kiu": "Kirmanckî",
  "kj": "Kuanyama",
  "kk": "Kazachs",
  "kk_Cyrl": "Kazachs (Cyrillisch)",
  "kk_Cyrl_KZ": "Kazachs (Cyrillisch, Kazachstan)",
  "kk_KZ": "Kazachs (Kazachstan)",
  "kkj": "Kako",
  "kl": "Groenlands",
  "kl_GL": "Groenlands (Groenland)",
  "kln": "Kalenjin",
  "km": "Khmer",
  "km_KH": "Khmer (Cambodja)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Koreaans",
  "ko_KP": "Koreaans (Noord-Korea)",
  "ko_KR": "Koreaans (Zuid-Korea)",
  "koi": "Komi-Permjaaks",
  "kok": "Konkani",
  "kos": "Kosraeaans",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karatsjaj-Balkarisch",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelisch",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kasjmiri",
  "ks_Arab": "Kasjmiri (Arabisch)",
  "ks_Arab_IN": "Kasjmiri (Arabisch, India)",
  "ks_IN": "Kasjmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Kölsch",
  "ku": "Koerdisch",
  "kum": "Koemuks",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (Verenigd Koninkrijk)",
  "ky": "Kirgizisch",
  "ky_Cyrl": "Kirgizisch (Cyrillisch)",
  "ky_Cyrl_KG": "Kirgizisch (Cyrillisch, Kirgizië)",
  "ky_KG": "Kirgizisch (Kirgizië)",
  "la": "Latijn",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxemburgs",
  "lb_LU": "Luxemburgs (Luxemburg)",
  "lez": "Lezgisch",
  "lfn": "Lingua Franca Nova",
  "lg": "Luganda",
  "lg_UG": "Luganda (Oeganda)",
  "li": "Limburgs",
  "lij": "Ligurisch",
  "liv": "Lijfs",
  "lkt": "Lakota",
  "lmo": "Lombardisch",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo-Kinshasa)",
  "ln_CF": "Lingala (Centraal-Afrikaanse Republiek)",
  "ln_CG": "Lingala (Congo-Brazzaville)",
  "lo": "Laotiaans",
  "lo_LA": "Laotiaans (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana-Creools",
  "loz": "Lozi",
  "lrc": "Noordelijk Luri",
  "lt": "Litouws",
  "lt_LT": "Litouws (Litouwen)",
  "ltg": "Letgaals",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo-Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Lets",
  "lv_LV": "Lets (Letland)",
  "lzh": "Klassiek Chinees",
  "lzz": "Lazisch",
  "mad": "Madoerees",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makassaars",
  "man": "Mandingo",
  "map": "Austronesisch",
  "mas": "Maa",
  "mde": "Maba",
  "mdf": "Moksja",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagassisch",
  "mg_MG": "Malagassisch (Madagaskar)",
  "mga": "Middeliers",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta’",
  "mh": "Marshallees",
  "mi": "Maori",
  "mic": "Mi’kmaq",
  "min": "Minangkabau",
  "mis": "Diverse talen",
  "mk": "Macedonisch",
  "mk_MK": "Macedonisch (Macedonië)",
  "mkh": "Mon-Khmer-taal",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongools",
  "mn_Cyrl": "Mongools (Cyrillisch)",
  "mn_Cyrl_MN": "Mongools (Cyrillisch, Mongolië)",
  "mn_MN": "Mongools (Mongolië)",
  "mnc": "Mantsjoe",
  "mni": "Meitei",
  "mno": "Manobo-taal",
  "mo": "Moldavisch",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "West-Mari",
  "ms": "Maleis",
  "ms_BN": "Maleis (Brunei)",
  "ms_Latn": "Maleis (Latijn)",
  "ms_Latn_BN": "Maleis (Latijn, Brunei)",
  "ms_Latn_MY": "Maleis (Latijn, Maleisië)",
  "ms_Latn_SG": "Maleis (Latijn, Singapore)",
  "ms_MY": "Maleis (Maleisië)",
  "ms_SG": "Maleis (Singapore)",
  "mt": "Maltees",
  "mt_MT": "Maltees (Malta)",
  "mua": "Mundang",
  "mul": "Meerdere talen",
  "mun": "Munda-taal",
  "mus": "Creek",
  "mwl": "Mirandees",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Birmaans",
  "my_MM": "Birmaans (Myanmar (Birma))",
  "mye": "Myene",
  "myn": "Mayan-taal",
  "myv": "Erzja",
  "mzn": "Mazanderani",
  "na": "Nauruaans",
  "nah": "Nahuatl",
  "nai": "Noord-Amerikaans Indiaanse taal",
  "nan": "Minnanyu",
  "nap": "Napolitaans",
  "naq": "Nama",
  "nb": "Noors - Bokmål",
  "nb_NO": "Noors - Bokmål (Noorwegen)",
  "nb_SJ": "Noors - Bokmål (Spitsbergen en Jan Mayen)",
  "nd": "Noord-Ndebele",
  "nd_ZW": "Noord-Ndebele (Zimbabwe)",
  "nds": "Nedersaksisch",
  "nds_NL": "Nederduits",
  "ne": "Nepalees",
  "ne_IN": "Nepalees (India)",
  "ne_NP": "Nepalees (Nepal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Niger-Kordofanische taal",
  "niu": "Niueaans",
  "njo": "Ao Naga",
  "nl": "Nederlands",
  "nl_AW": "Nederlands (Aruba)",
  "nl_BE": "Nederlands (België)",
  "nl_BQ": "Nederlands (Caribisch Nederland)",
  "nl_CW": "Nederlands (Curaçao)",
  "nl_NL": "Nederlands (Nederland)",
  "nl_SR": "Nederlands (Suriname)",
  "nl_SX": "Nederlands (Sint-Maarten)",
  "nmg": "Ngumba",
  "nn": "Noors - Nynorsk",
  "nn_NO": "Noors - Nynorsk (Noorwegen)",
  "nnh": "Ngiemboon",
  "no": "Noors",
  "no_NO": "Noors (Noorwegen)",
  "nog": "Nogai",
  "non": "Oudnoors",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Zuid-Ndbele",
  "nso": "Noord-Sotho",
  "nub": "Nubische taal",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Klassiek Nepalbhasa",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Occitaans",
  "oj": "Ojibwa",
  "om": "Afaan Oromo",
  "om_ET": "Afaan Oromo (Ethiopië)",
  "om_KE": "Afaan Oromo (Kenia)",
  "or": "Odia",
  "or_IN": "Odia (India)",
  "os": "Ossetisch",
  "os_GE": "Ossetisch (Georgië)",
  "os_RU": "Ossetisch (Rusland)",
  "osa": "Osage",
  "ota": "Ottomaans-Turks",
  "oto": "Otomi-taal",
  "pa": "Punjabi",
  "pa_Arab": "Punjabi (Arabisch)",
  "pa_Arab_PK": "Punjabi (Arabisch, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (India)",
  "pa_PK": "Punjabi (Pakistan)",
  "paa": "Papoeataal",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiaments",
  "pau": "Palaus",
  "pcd": "Picardisch",
  "pcm": "Nigeriaans Pidgin",
  "pdc": "Pennsylvania-Duits",
  "pdt": "Plautdietsch",
  "peo": "Oudperzisch",
  "pfl": "Paltsisch",
  "phi": "Filippijnse taal",
  "phn": "Foenicisch",
  "pi": "Pali",
  "pl": "Pools",
  "pl_PL": "Pools (Polen)",
  "pms": "Piëmontees",
  "pnt": "Pontisch",
  "pon": "Pohnpeiaans",
  "pra": "Prakrit-taal",
  "prg": "Oudpruisisch",
  "pro": "Oudprovençaals",
  "ps": "Pasjtoe",
  "ps_AF": "Pasjtoe (Afghanistan)",
  "pt": "Portugees",
  "pt_AO": "Portugees (Angola)",
  "pt_BR": "Portugees (Brazilië)",
  "pt_CV": "Portugees (Kaapverdië)",
  "pt_GW": "Portugees (Guinee-Bissau)",
  "pt_MO": "Portugees (Macau SAR van China)",
  "pt_MZ": "Portugees (Mozambique)",
  "pt_PT": "Portugees (Portugal)",
  "pt_ST": "Portugees (Sao Tomé en Principe)",
  "pt_TL": "Portugees (Oost-Timor)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "K’iche’",
  "qug": "Kichwa",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffijns",
  "rm": "Reto-Romaans",
  "rm_CH": "Reto-Romaans (Zwitserland)",
  "rn": "Kirundi",
  "rn_BI": "Kirundi (Burundi)",
  "ro": "Roemeens",
  "ro_MD": "Roemeens (Moldavië)",
  "ro_RO": "Roemeens (Roemenië)",
  "roa": "Romaanse taal",
  "rof": "Rombo",
  "rom": "Romani",
  "root": "Root",
  "rtm": "Rotumaans",
  "ru": "Russisch",
  "ru_BY": "Russisch (Wit-Rusland)",
  "ru_KG": "Russisch (Kirgizië)",
  "ru_KZ": "Russisch (Kazachstan)",
  "ru_MD": "Russisch (Moldavië)",
  "ru_RU": "Russisch (Rusland)",
  "ru_UA": "Russisch (Oekraïne)",
  "rue": "Roetheens",
  "rug": "Roviana",
  "rup": "Aroemeens",
  "rw": "Kinyarwanda",
  "rw_RW": "Kinyarwanda (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sanskriet",
  "sad": "Sandawe",
  "sah": "Jakoets",
  "sai": "Zuid-Amerikaans Indiaanse taal",
  "sal": "Salishan-taal",
  "sam": "Samaritaans-Aramees",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardijns",
  "scn": "Siciliaans",
  "sco": "Schots",
  "sd": "Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarees",
  "sdh": "Pahlavani",
  "se": "Noord-Samisch",
  "se_FI": "Noord-Samisch (Finland)",
  "se_NO": "Noord-Samisch (Noorwegen)",
  "se_SE": "Noord-Samisch (Zweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkoeps",
  "sem": "Semitische taal",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Centraal-Afrikaanse Republiek)",
  "sga": "Oudiers",
  "sgn": "Gebarentaal",
  "sgs": "Samogitisch",
  "sh": "Servo-Kroatisch",
  "sh_BA": "Servokroatisch (Bosnië en Herzegovina)",
  "shi": "Tashelhiyt",
  "shi_Latn": "Shilha (Latijns)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Tsjadisch Arabisch",
  "si": "Singalees",
  "si_LK": "Singalees (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Siouaanse talen",
  "sit": "Sino-Tibetaanse taal",
  "sk": "Slowaaks",
  "sk_SK": "Slowaaks (Slowakije)",
  "sl": "Sloveens",
  "sl_SI": "Sloveens (Slovenië)",
  "sla": "Slavische taal",
  "sli": "Silezisch Duits",
  "sly": "Selayar",
  "sm": "Samoaans",
  "sma": "Zuid-Samisch",
  "smi": "Sami-taal",
  "smj": "Lule-Samisch",
  "smn": "Inari-Samisch",
  "sms": "Skolt-Samisch",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somalisch",
  "so_DJ": "Somalisch (Djibouti)",
  "so_ET": "Somalisch (Ethiopië)",
  "so_KE": "Somalisch (Kenia)",
  "so_SO": "Somalisch (Somalië)",
  "sog": "Sogdisch",
  "son": "Songhai",
  "sq": "Albanees",
  "sq_AL": "Albanees (Albanië)",
  "sq_MK": "Albanees (Macedonië)",
  "sq_XK": "Albanees (Kosovo)",
  "sr": "Servisch",
  "sr_BA": "Servisch (Bosnië en Herzegovina)",
  "sr_Cyrl": "Servisch (Cyrillisch)",
  "sr_Cyrl_BA": "Servisch (Cyrillisch, Bosnië en Herzegovina)",
  "sr_Cyrl_ME": "Servisch (Cyrillisch, Montenegro)",
  "sr_Cyrl_RS": "Servisch (Cyrillisch, Servië)",
  "sr_Cyrl_XK": "Servisch (Cyrillisch, Kosovo)",
  "sr_Latn": "Servisch (Latijn)",
  "sr_Latn_BA": "Servisch (Latijn, Bosnië en Herzegovina)",
  "sr_Latn_ME": "Servisch (Latijn, Montenegro)",
  "sr_Latn_RS": "Servisch (Latijn, Servië)",
  "sr_Latn_XK": "Servisch (Latijn, Kosovo)",
  "sr_ME": "Servisch (Montenegro)",
  "sr_RS": "Servisch (Servië)",
  "sr_XK": "Servisch (Kosovo)",
  "srn": "Sranantongo",
  "srr": "Serer",
  "ss": "Swazi",
  "ssa": "Nilo-Saharaanse taal",
  "ssy": "Saho",
  "st": "Zuid-Sotho",
  "stq": "Saterfries",
  "su": "Soendanees",
  "suk": "Sukuma",
  "sus": "Soesoe",
  "sux": "Soemerisch",
  "sv": "Zweeds",
  "sv_AX": "Zweeds (Åland)",
  "sv_FI": "Zweeds (Finland)",
  "sv_SE": "Zweeds (Zweden)",
  "sw": "Swahili",
  "sw_CD": "Congo Swahili",
  "sw_KE": "Swahili (Kenia)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Oeganda)",
  "swb": "Shimaore",
  "swc": "Congo Swahili",
  "syc": "Klassiek Syrisch",
  "syr": "Syrisch",
  "szl": "Silezisch",
  "ta": "Tamil",
  "ta_IN": "Tamil (India)",
  "ta_LK": "Tamil (Sri Lanka)",
  "ta_MY": "Tamil (Maleisië)",
  "ta_SG": "Tamil (Singapore)",
  "tai": "Tai-taal",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetun",
  "tg": "Tadzjieks",
  "th": "Thai",
  "th_TH": "Thais (Thailand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopië)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkmeens",
  "tkl": "Tokelaus",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Filipijnen)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongaans",
  "to_TO": "Tongaans (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Turks",
  "tr_CY": "Turks (Cyprus)",
  "tr_TR": "Turks (Turkije)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonisch",
  "tsi": "Tsimshian",
  "tt": "Tataars",
  "ttt": "Moslim Tat",
  "tum": "Toemboeka",
  "tup": "Tupi-taal",
  "tut": "Altaïsche taal",
  "tvl": "Tuvaluaans",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitiaans",
  "tyv": "Toevaans",
  "tzm": "Tamazight (Centraal-Marokko)",
  "udm": "Oedmoerts",
  "ug": "Oeigoers",
  "ug_Arab": "Oeigoers (Arabisch)",
  "ug_Arab_CN": "Oeigoers (Arabisch, China)",
  "ug_CN": "Oeigoers (China)",
  "uga": "Oegaritisch",
  "uk": "Oekraïens",
  "uk_UA": "Oekraïens (Oekraïne)",
  "umb": "Umbundu",
  "und": "onbekende taal",
  "ur": "Urdu",
  "ur_IN": "Urdu (India)",
  "ur_PK": "Urdu (Pakistan)",
  "uz": "Oezbeeks",
  "uz_AF": "Oezbeeks (Afghanistan)",
  "uz_Arab": "Oezbeeks (Arabisch)",
  "uz_Arab_AF": "Oezbeeks (Arabisch, Afghanistan)",
  "uz_Cyrl": "Oezbeeks (Cyrillisch)",
  "uz_Cyrl_UZ": "Oezbeeks (Cyrillisch, Oezbekistan)",
  "uz_Latn": "Oezbeeks (Latijn)",
  "uz_Latn_UZ": "Oezbeeks (Latijn, Oezbekistan)",
  "uz_UZ": "Oezbeeks (Oezbekistan)",
  "vai": "Vai",
  "vai_Latn": "Vai (Latijns)",
  "ve": "Venda",
  "vec": "Venetiaans",
  "vep": "Wepsisch",
  "vi": "Vietnamees",
  "vi_VN": "Vietnamees (Vietnam)",
  "vls": "West-Vlaams",
  "vmf": "Opperfrankisch",
  "vo": "Volapük",
  "vot": "Votisch",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Waals",
  "wae": "Walser",
  "wak": "Wakashan-taal",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Sorbische taal",
  "wo": "Wolof",
  "wuu": "Wuyu",
  "xal": "Kalmuks",
  "xh": "Xhosa",
  "xmf": "Mingreels",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapees",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Jiddisch",
  "yo": "Yoruba",
  "yo_BJ": "Yoruba (Benin)",
  "yo_NG": "Yoruba (Nigeria)",
  "ypk": "Yupik-talen",
  "yrl": "Nheengatu",
  "yue": "Kantonees",
  "yue_Hans": "Kantonees (Vereenvoudigd Chinees)",
  "yue_Hant": "Kantonees (traditioneel Chinees)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbolen",
  "zea": "Zeeuws",
  "zen": "Zenaga",
  "zgh": "Standaard Marokkaanse Tamazight",
  "zh": "Chinees",
  "zh_CN": "Chinees (China)",
  "zh_HK": "Chinees (Hongkong SAR van China)",
  "zh_Hans": "Chinees (vereenvoudigd)",
  "zh_Hans_CN": "Chinees (vereenvoudigd, China)",
  "zh_Hans_HK": "Chinees (vereenvoudigd, Hongkong SAR van China)",
  "zh_Hans_MO": "Chinees (vereenvoudigd, Macau SAR van China)",
  "zh_Hans_SG": "Chinees (vereenvoudigd, Singapore)",
  "zh_Hant": "Chinees (traditioneel)",
  "zh_Hant_HK": "Chinees (traditioneel, Hongkong SAR van China)",
  "zh_Hant_MO": "Chinees (traditioneel, Macau SAR van China)",
  "zh_Hant_TW": "Chinees (traditioneel, Taiwan)",
  "zh_MO": "Chinees (Macau SAR van China)",
  "zh_SG": "Chinees (Singapore)",
  "zh_TW": "Chinees (Taiwan)",
  "znd": "Zande",
  "zu": "Zoeloe",
  "zu_ZA": "Zoeloe (Zuid-Afrika)",
  "zun": "Zuni",
  "zxx": "geen linguïstische inhoud",
  "zza": "Zaza"
};
