const names = {
  "001": "Duniya",
  "002": "Afirka",
  "003": "North America",
  "005": "South America",
  "009": "Oceania",
  "011": "Afirka ta Yamma",
  "013": "Central America",
  "014": "Afirka ta Gabas",
  "015": "Arewacin Africa",
  "017": "Afirka ta Tsakiya",
  "018": "Kudancin Afirka",
  "019": "nahiyoyin Amurka",
  "021": "Arewacin Amurka",
  "029": "Caribbean",
  "030": "Gabashin Asiya",
  "034": "kudancin Asiya",
  "035": "Kudu Maso Gabashin Asiya",
  "039": "Kudancin Turai",
  "053": "Tsibarai na Austraila da New Zealand da maƙota",
  "054": "Tsibirai na New Guinea da Fiji da maƙota",
  "057": "Yankin Micronesia",
  "061": "tsibiri",
  "142": "Asiya",
  "143": "Asiya ta Tsakiya",
  "145": "Yammacin Asiya",
  "150": "Turai",
  "151": "Gabashin Turai",
  "154": "Arewacin Turai",
  "155": "Yammacin Turai",
  "202": "Sub-Saharan Africa",
  "419": "Latin America",
  "AC": "Tsibirin Ascension",
  "AD": "Andora",
  "AE": "Haɗaɗɗiyar Daular Larabawa",
  "AF": "Afaganistan",
  "AG": "Antigwa da Barbuba",
  "AI": "Angila",
  "AL": "Albaniya",
  "AM": "Armeniya",
  "AN": "Antiya Na Holan",
  "AO": "Angola",
  "AQ": "Antatika",
  "AR": "Arjantiniya",
  "AS": "Samowa Ta Amurka",
  "AT": "Ostiriya",
  "AU": "Ostareliya",
  "AW": "Aruba",
  "AX": "Tsibirai na Åland",
  "AZ": "Azarbaijan",
  "Arab": "Larabci",
  "Armn": "Armeniyawa",
  "BA": "Bosniya Harzagobina",
  "BB": "Barbadas",
  "BD": "Bangiladas",
  "BE": "Belgiyom",
  "BF": "Burkina Faso",
  "BG": "Bulgariya",
  "BH": "Baharan",
  "BI": "Burundi",
  "BJ": "Binin",
  "BL": "St. Barthélemy",
  "BM": "Barmuda",
  "BN": "Burune",
  "BO": "Bolibiya",
  "BQ": "Caribbean Netherlands",
  "BR": "Birazil",
  "BS": "Bahamas",
  "BT": "Butan",
  "BV": "Tsibirin Bouvet",
  "BW": "Baswana",
  "BY": "Belarus",
  "BZ": "Beliz",
  "Beng": "Bangla",
  "Bopo": "Bopomofo",
  "Brai": "Rubutun Makafi",
  "CA": "Kanada",
  "CC": "Tsibirai Cocos (Keeling)",
  "CD": "Jamhuriyar Dimokuraɗiyyar Kongo",
  "CF": "Jamhuriyar Afirka Ta Tsakiya",
  "CG": "Kongo",
  "CH": "Suwizalan",
  "CI": "Aibari Kwas",
  "CK": "Tsibiran Kuku",
  "CL": "Cayile",
  "CM": "Kamaru",
  "CN": "Sin",
  "CO": "Kolambiya",
  "CP": "Tsibirin Clipperton",
  "CR": "Kwasta Rika",
  "CS": "Sarbiya Da Mantanegiro",
  "CU": "Kyuba",
  "CV": "Tsibiran Kap Barde",
  "CW": "Kasar Curaçao",
  "CX": "Tsibirin Kirsmati",
  "CY": "Sifurus",
  "CZ": "Jamhuriyar Cak",
  "Cyrl": "Cyrillic",
  "DE": "Jamus",
  "DG": "Tsibirn Diego Garcia",
  "DJ": "Jibuti",
  "DK": "Danmark",
  "DM": "Dominika",
  "DO": "Jamhuriyar Dominika",
  "DZ": "Aljeriya",
  "Deva": "Devanagari",
  "EA": "Ceuta & Melilla",
  "EC": "Ekwador",
  "EE": "Estoniya",
  "EG": "Misira",
  "EH": "Yammacin Sahara",
  "ER": "Eritireya",
  "ES": "Sipen",
  "ET": "Habasha",
  "EU": "Tarayyar Turai",
  "EZ": "Sashin Turai",
  "Ethi": "Ethiopic",
  "FI": "Finlan",
  "FJ": "Fiji",
  "FK": "Tsibiran Falkilan",
  "FM": "Mikuronesiya",
  "FO": "Tsibirai na Faroe",
  "FR": "Faransa",
  "GA": "Gabon",
  "GB": "Biritaniya",
  "GD": "Girnada",
  "GE": "Jiwarjiya",
  "GF": "Gini Ta Faransa",
  "GG": "Yankin Guernsey",
  "GH": "Gana",
  "GI": "Jibaraltar",
  "GL": "Grinlan",
  "GM": "Gambiya",
  "GN": "Gini",
  "GP": "Gwadaluf",
  "GQ": "Gini Ta Ikwaita",
  "GR": "Girka",
  "GS": "Kudancin Geogia da Kudancin Tsibirin Sandiwic",
  "GT": "Gwatamala",
  "GU": "Gwam",
  "GW": "Gini Bisau",
  "GY": "Guyana",
  "Geor": "Georgian",
  "Grek": "Girka",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "HK": "Hong Kong Babban Birnin Kasar Chana",
  "HM": "Tsibirin Heard da McDonald",
  "HN": "Honduras",
  "HR": "Kurowaishiya",
  "HT": "Haiti",
  "HU": "Hungari",
  "Hanb": "Han with Bopomofo",
  "Hang": "Yaren Hangul",
  "Hani": "Mutanen Han na ƙasar Sin",
  "Hans": "Sauƙaƙaƙƙen",
  "Hant": "Na gargajiya",
  "Hebr": "Ibrananci",
  "Hira": "Tsarin Rubutun Hiragana",
  "Hrkt": "kalaman Jafananci",
  "IC": "Canary Islands",
  "ID": "Indunusiya",
  "IE": "Ayalan",
  "IL": "Iziraʼila",
  "IM": "Isle na Mutum",
  "IN": "Indiya",
  "IO": "Yankin Birtaniya Na Tekun Indiya",
  "IQ": "Iraƙi",
  "IR": "Iran",
  "IS": "Aisalan",
  "IT": "Italiya",
  "JE": "Kasar Jersey",
  "JM": "Jamaika",
  "JO": "Jordan",
  "JP": "Jàpân",
  "Jpan": "Jafanis",
  "KE": "Kenya",
  "KG": "Kirgizistan",
  "KH": "Kambodiya",
  "KI": "Kiribati",
  "KM": "Kwamoras",
  "KN": "San Kiti Da Nebis",
  "KP": "Koriya Ta Arewa",
  "KR": "Koriya Ta Kudu",
  "KW": "Kwiyat",
  "KY": "Tsibiran Kaiman",
  "KZ": "Kazakistan",
  "Kana": "Tsarin Rubutun Katakana",
  "Khmr": "Yaren Khmer",
  "Knda": "Yaren Kannada",
  "Kore": "Koriya",
  "LA": "Lawas",
  "LB": "Labanan",
  "LC": "San Lusiya",
  "LI": "Licansitan",
  "LK": "Siri Lanka",
  "LR": "Laberiya",
  "LS": "Lesoto",
  "LT": "Lituweniya",
  "LU": "Lukusambur",
  "LV": "latibiya",
  "LY": "Libiya",
  "Laoo": "Mutanen Laos",
  "Latn": "Latin",
  "MA": "Maroko",
  "MC": "Monako",
  "MD": "Maldoba",
  "ME": "Mantanegara",
  "MF": "St. Martin",
  "MG": "Madagaskar",
  "MH": "Tsibiran Marshal",
  "MK": "Macedonia ta Arewa",
  "ML": "Mali",
  "MM": "Burma, Miyamar",
  "MN": "Mangoliya",
  "MO": "Babban Birnin Mulki na Chana",
  "MP": "Tsibiran Mariyana Na Arewa",
  "MQ": "Martinik",
  "MR": "Moritaniya",
  "MS": "Manserati",
  "MT": "Malta",
  "MU": "Moritus",
  "MV": "Maldibi",
  "MW": "Malawi",
  "MX": "Makasiko",
  "MY": "Malaisiya",
  "MZ": "Mozambik",
  "Mlym": "Yaren Malayalam",
  "Mong": "Na kasar Mongolia",
  "Mymr": "Ƙasar Myanmar",
  "NA": "Namibiya",
  "NC": "Kaledoniya Sabuwa",
  "NE": "Nijar",
  "NF": "Tsibirin Narfalk",
  "NG": "Najeriya",
  "NI": "Nikaraguwa",
  "NL": "Holan",
  "NO": "Norwe",
  "NP": "Nefal",
  "NR": "Nauru",
  "NU": "Niyu",
  "NZ": "Nuzilan",
  "OM": "Oman",
  "Orya": "Yaren Odia",
  "PA": "Panama",
  "PE": "Feru",
  "PF": "Folinesiya Ta Faransa",
  "PG": "Papuwa Nugini",
  "PH": "Filipin",
  "PK": "Pakistan",
  "PL": "Polan",
  "PM": "San Piyar Da Mikelan",
  "PN": "Pitakarin",
  "PR": "Porto Riko",
  "PS": "Palasɗinu",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Faragwai",
  "QA": "Katar",
  "QO": "Bakin Teku",
  "RE": "Rawuniyan",
  "RO": "Romaniya",
  "RS": "Sabiya",
  "RU": "Rasha",
  "RW": "Ruwanda",
  "SA": "Saudiyya",
  "SB": "Tsibiran Salaman",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Suwedan",
  "SG": "Singapur",
  "SH": "San Helena",
  "SI": "Sulobeniya",
  "SJ": "Svalbard da Jan Mayen",
  "SK": "Sulobakiya",
  "SL": "Salewo",
  "SM": "San Marino",
  "SN": "Sanigal",
  "SO": "Somaliya",
  "SR": "Suriname",
  "SS": "Sudan ta kudu",
  "ST": "Sawo Tome Da Paransip",
  "SV": "El Salbador",
  "SX": "Sint Maarten",
  "SY": "Sham, Siriya",
  "SZ": "Eswatini",
  "Sinh": "Yaren Sinhala",
  "TA": "Tritan da Kunha",
  "TC": "Turkis Da Tsibiran Kaikwas",
  "TD": "Cadi",
  "TF": "Yankin Faransi ta Kudu",
  "TG": "Togo",
  "TH": "Tailan",
  "TJ": "Tajikistan",
  "TK": "Takelau",
  "TL": "Timor Ta Gabas",
  "TM": "Turkumenistan",
  "TN": "Tunisiya",
  "TO": "Tonga",
  "TR": "Turkiyya",
  "TT": "Tirinidad Da Tobago",
  "TV": "Tubalu",
  "TW": "Taiwan",
  "TZ": "Tanzaniya",
  "Taml": "Yaren Tamil",
  "Telu": "Yaren Telugu",
  "Thaa": "Yaren Thaana",
  "Tibt": "Yaren Tibet",
  "UA": "Yukaran",
  "UG": "Yuganda",
  "UM": "Rukunin Tsibirin U.S",
  "UN": "Majalisar Dinkin Duniya",
  "US": "Amurka",
  "UY": "Yurigwai",
  "UZ": "Uzubekistan",
  "VA": "Batikan",
  "VC": "San Binsan Da Girnadin",
  "VE": "Benezuwela",
  "VG": "Tsibirin Birjin Na Birtaniya",
  "VI": "Tsibiran Birjin Ta Amurka",
  "VN": "Biyetinam",
  "VU": "Banuwatu",
  "WF": "Walis Da Futuna",
  "WS": "Samoa",
  "XA": "Gogewar Kwalwa",
  "XB": "Gano wani abu ta hanyar amfani da fasaha",
  "XK": "Kasar Kosovo",
  "YE": "Yamal",
  "YT": "Mayoti",
  "ZA": "Afirka Ta Kudu",
  "ZM": "Zambiya",
  "ZW": "Zimbabuwe",
  "ZZ": "Yanki da ba a sani ba",
  "Zmth": "Alamar Lissafi",
  "Zsye": "Alama ta hoto",
  "Zsym": "Alamomi",
  "Zxxx": "Ba rubutacce ba",
  "Zyyy": "Gama-gari",
  "Zzzz": "Rubutun da ba sani ba",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afirkanci",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afh": "Afrihili",
  "agq": "Aghem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Gana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Amharik",
  "am_ET": "Amharik (Habasha)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "ar": "Larabci",
  "ar_001": "Larabci Asali Na Zamani",
  "ar_AE": "Larabci (Haɗaɗɗiyar Daular Larabawa)",
  "ar_BH": "Larabci (Baharan)",
  "ar_DJ": "Larabci (Jibuti)",
  "ar_DZ": "Larabci (Aljeriya)",
  "ar_EG": "Larabci (Masar, Misira)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Larabci (Eritireya)",
  "ar_IL": "Larabci (Iziraʼila)",
  "ar_IQ": "Larabci (Iraƙi)",
  "ar_JO": "Larabci (Jordan)",
  "ar_KM": "Larabci (Kwamoras)",
  "ar_KW": "Larabci (Kwiyat)",
  "ar_LB": "Larabci (Labanan)",
  "ar_LY": "Larabci (Libiya)",
  "ar_MA": "Larabci (Maroko)",
  "ar_MR": "Larabci (Moritaniya)",
  "ar_OM": "Larabci (Oman)",
  "ar_PS": "Larabci (Palasɗinu)",
  "ar_QA": "Larabci (Kwatar)",
  "ar_SA": "Larabci (Ƙasar Makka)",
  "ar_SD": "Larabci (Sudan)",
  "ar_SO": "Larabci (Somaliya)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Larabci (Sham, Siriya)",
  "ar_TD": "Larabci (Cadi)",
  "ar_TN": "Larabci (Tunisiya)",
  "ar_YE": "Larabci (Yamal)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Asamisanci",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Asturian",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Azerbaijanci",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarusanci",
  "be_BY": "Belarusanci (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgaranci",
  "bg_BG": "Bulgaranci (Bulgariya)",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bengali",
  "bn_BD": "Bengali (Bangiladas)",
  "bn_IN": "Bengali (Indiya)",
  "bo": "Tibetan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Buretananci",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosniyanci",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Kataloniyanci",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "car": "Carib",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Chakma",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "cgg": "Chiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Cherokee",
  "chy": "Cheyenne",
  "ckb": "Kurdish na Tsaka",
  "co": "Corsican",
  "cop": "Coptic",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "cs": "Harshen Cak",
  "cs_CZ": "Harshen Cak (Jamhuriyar Cak)",
  "csb": "Kashubian",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "cy": "Kabilar Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Danish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taita",
  "de": "Jamusanci",
  "de_AT": "Jamusanci (Ostiriya)",
  "de_BE": "Jamusanci (Belgiyom)",
  "de_CH": "Jamusanci (Suwizalan)",
  "de_DE": "Jamusanci (Jamus)",
  "de_LI": "Jamusanci (Licansitan)",
  "de_LU": "Jamusanci (Lukusambur)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embu",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Girkanci",
  "el_CY": "Girkanci (Sifurus)",
  "el_GR": "Girkanci (Girka)",
  "elx": "Elamite",
  "en": "Turanci",
  "en_AG": "Turanci (Antigwa da Barbuba)",
  "en_AI": "Turanci (Angila)",
  "en_AS": "Turanci (Samowa Ta Amurka)",
  "en_AU": "Turanci (Ostareliya)",
  "en_BB": "Turanci (Barbadas)",
  "en_BE": "Turanci (Belgiyom)",
  "en_BM": "Turanci (Barmuda)",
  "en_BS": "Turanci (Bahamas)",
  "en_BW": "Turanci (Baswana)",
  "en_BZ": "Turanci (Beliz)",
  "en_CA": "Turanci (Kanada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Turanci (Tsibiran Kuku)",
  "en_CM": "Turanci (Kamaru)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Turanci (Dominika)",
  "en_ER": "Turanci (Eritireya)",
  "en_FJ": "Turanci (Fiji)",
  "en_FK": "Turanci (Tsibiran Falkilan)",
  "en_FM": "Turanci (Mikuronesiya)",
  "en_GB": "Turanci (Birtaniya)",
  "en_GD": "Turanci (Girnada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Turanci (Gana)",
  "en_GI": "Turanci (Jibaraltar)",
  "en_GM": "Turanci (Gambiya)",
  "en_GU": "Turanci (Gwam)",
  "en_GY": "Turanci (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Turanci (Ayalan)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Turanci (Indiya)",
  "en_IO": "Turanci (Yankin Birtaniya Na Tekun Indiya)",
  "en_JE": "English (Jersey)",
  "en_JM": "Turanci (Jamaika)",
  "en_KE": "Turanci (Kenya)",
  "en_KI": "Turanci (Kiribati)",
  "en_KN": "Turanci (San Kiti Da Nebis)",
  "en_KY": "Turanci (Tsibiran Kaiman)",
  "en_LC": "Turanci (San Lusiya)",
  "en_LR": "Turanci (Laberiya)",
  "en_LS": "Turanci (Lesoto)",
  "en_MG": "Turanci (Madagaskar)",
  "en_MH": "Turanci (Tsibiran Marshal)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Turanci (Tsibiran Mariyana Na Arewa)",
  "en_MS": "Turanci (Manserati)",
  "en_MT": "Turanci (Malta)",
  "en_MU": "Turanci (Moritus)",
  "en_MW": "Turanci (Malawi)",
  "en_MY": "Turanci (Malaisiya)",
  "en_NA": "Turanci (Namibiya)",
  "en_NF": "Turanci (Tsibirin Narfalk)",
  "en_NG": "Turanci (Najeriya)",
  "en_NR": "Turanci (Nauru)",
  "en_NU": "Turanci (Niyu)",
  "en_NZ": "Turanci (Nuzilan)",
  "en_PG": "Turanci (Papuwa Nugini)",
  "en_PH": "Turanci (Filipin)",
  "en_PK": "Turanci (Pakistan)",
  "en_PN": "Turanci (Pitakarin)",
  "en_PR": "Turanci (Porto Riko)",
  "en_PW": "Turanci (Palau)",
  "en_RW": "Turanci (Ruwanda)",
  "en_SB": "Turanci (Tsibiran Salaman)",
  "en_SC": "Turanci (Saishal)",
  "en_SD": "Turanci (Sudan)",
  "en_SG": "Turanci (Singapur)",
  "en_SH": "Turanci (San Helena)",
  "en_SL": "Turanci (Salewo)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Turanci (Suwazilan)",
  "en_TC": "Turanci (Turkis Da Tsibiran Kaikwas)",
  "en_TK": "Turanci (Takelau)",
  "en_TO": "Turanci (Tanga)",
  "en_TT": "Turanci (Tirinidad Da Tobago)",
  "en_TV": "Turanci (Tubalu)",
  "en_TZ": "Turanci (Tanzaniya)",
  "en_UG": "Turanci (Yuganda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Turanci (Amurka)",
  "en_VC": "Turanci (San Binsan Da Girnadin)",
  "en_VG": "Turanci (Tsibirin Birjin Na Birtaniya)",
  "en_VI": "Turanci (Tsibiran Birjin Ta Amurka)",
  "en_VU": "Turanci (Banuwatu)",
  "en_WS": "Turanci (Samowa)",
  "en_ZA": "Turanci (Afirka Ta Kudu)",
  "en_ZM": "Turanci (Zambiya)",
  "en_ZW": "Turanci (Zimbabuwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "Sifaniyanci",
  "es_419": "Sifaniyancin (Latin Amirka)",
  "es_AR": "Ispaniyanci (Arjantiniya)",
  "es_BO": "Ispaniyanci (Bolibiya)",
  "es_CL": "Ispaniyanci (Cayile)",
  "es_CO": "Ispaniyanci (Kolambiya)",
  "es_CR": "Ispaniyanci (Kwasta Rika)",
  "es_CU": "Ispaniyanci (Kyuba)",
  "es_DO": "Ispaniyanci (Jamhuriyar Dominika)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Ispaniyanci (Ekwador)",
  "es_ES": "Sifaniyanci (Sipen)",
  "es_GQ": "Ispaniyanci (Gini Ta Ikwaita)",
  "es_GT": "Ispaniyanci (Gwatamala)",
  "es_HN": "Ispaniyanci (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Sifaniyanci (Meziko)",
  "es_NI": "Ispaniyanci (Nikaraguwa)",
  "es_PA": "Ispaniyanci (Panama)",
  "es_PE": "Ispaniyanci (Peru)",
  "es_PH": "Ispaniyanci (Filipin)",
  "es_PR": "Ispaniyanci (Porto Riko)",
  "es_PY": "Ispaniyanci (Paragai)",
  "es_SV": "Ispaniyanci (El Salbador)",
  "es_US": "Ispaniyanci (Amurka)",
  "es_UY": "Ispaniyanci (Yurugai)",
  "es_VE": "Ispaniyanci (Benezuwela)",
  "esu": "Central Yupik",
  "et": "Istoniyanci",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basque",
  "eu_ES": "Basque (Spain)",
  "ewo": "Ewondo",
  "ext": "Extremaduran",
  "fa": "Parisanci",
  "fa_AF": "Parisanci (Afaganistan)",
  "fa_IR": "Parisanci (Iran)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fulah",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Yaren mutanen Finland",
  "fi_FI": "Finnish (Finland)",
  "fil": "Dan Filifin",
  "fit": "Tornedalen Finnish",
  "fj": "Fijian",
  "fo": "Faroese",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Faransanci",
  "fr_BE": "Faransanci (Belgiyom)",
  "fr_BF": "Faransanci (Burkina Faso)",
  "fr_BI": "Faransanci (Burundi)",
  "fr_BJ": "Faransanci (Binin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Faransanci (Kanada)",
  "fr_CD": "Faransanci (Jamhuriyar Dimokuraɗiyyar Kongo)",
  "fr_CF": "Faransanci (Jamhuriyar Afirka Ta Tsakiya)",
  "fr_CG": "Faransanci (Kongo)",
  "fr_CH": "Faransanci (Suwizalan)",
  "fr_CI": "Faransanci (Aibari Kwas)",
  "fr_CM": "Faransanci (Kamaru)",
  "fr_DJ": "Faransanci (Jibuti)",
  "fr_DZ": "Faransanci (Aljeriya)",
  "fr_FR": "Faransanci (Faransa)",
  "fr_GA": "Faransanci (Gabon)",
  "fr_GF": "Faransanci (Gini Ta Faransa)",
  "fr_GN": "Faransanci (Gini)",
  "fr_GP": "Faransanci (Gwadaluf)",
  "fr_GQ": "Faransanci (Gini Ta Ikwaita)",
  "fr_HT": "Faransanci (Haiti)",
  "fr_KM": "Faransanci (Kwamoras)",
  "fr_LU": "Faransanci (Lukusambur)",
  "fr_MA": "Faransanci (Maroko)",
  "fr_MC": "Faransanci (Monako)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Faransanci (Madagaskar)",
  "fr_ML": "Faransanci (Mali)",
  "fr_MQ": "Faransanci (Martinik)",
  "fr_MR": "Faransanci (Moritaniya)",
  "fr_MU": "Faransanci (Moritus)",
  "fr_NC": "Faransanci (Kaledoniya Sabuwa)",
  "fr_NE": "Faransanci (Nijar)",
  "fr_PF": "Faransanci (Folinesiya Ta Faransa)",
  "fr_PM": "Faransanci (San Piyar Da Mikelan)",
  "fr_RE": "Faransanci (Rawuniyan)",
  "fr_RW": "Faransanci (Ruwanda)",
  "fr_SC": "Faransanci (Saishal)",
  "fr_SN": "Faransanci (Sinigal)",
  "fr_SY": "Faransanci (Sham, Siriya)",
  "fr_TD": "Faransanci (Cadi)",
  "fr_TG": "Faransanci (Togo)",
  "fr_TN": "Faransanci (Tunisiya)",
  "fr_VU": "Faransanci (Banuwatu)",
  "fr_WF": "Faransanci (Walis Da Futuna)",
  "fr_YT": "Faransanci (Mayoti)",
  "frc": "Cajun French",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Friulian",
  "fy": "Western Frisian",
  "fy_NL": "Western Frisian (Netherlands)",
  "ga": "Dan Ailan",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Kʼabilan Scots Gaelic",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Bagalike",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guwaraniyanci",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Jamusanci Swiss",
  "gu": "Gujarati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manx",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hausa",
  "ha_GH": "Hausa (Gana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hausa (Nijar)",
  "ha_NG": "Hausa (Najeriya)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaiian",
  "he": "Ibrananci",
  "he_IL": "Hebrew (Israel)",
  "hi": "Harshen Hindi",
  "hi_IN": "Harshen Hindi (Indiya)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "hit": "Hittite",
  "hmn": "Hmong",
  "ho": "Hiri Motu",
  "hr": "Kuroshiyan",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Sorbianci ta Sama",
  "hsn": "Xiang Chinese",
  "ht": "Haitian Creole",
  "hu": "Harshen Hungari",
  "hu_HU": "Harshen Hungari (Hungari)",
  "hup": "Hupa",
  "hy": "Armeniyanci",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Yare Tsakanin Kasashe",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Harshen Indunusiya",
  "id_ID": "Harshen Indunusiya (Indunusiya)",
  "ie": "Intagulanci",
  "ig": "Inyamuranci",
  "ig_NG": "Inyamuranci (Najeriya)",
  "ii": "Sichuan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "is": "Yaren mutanen Iceland",
  "is_IS": "Icelandic (Iceland)",
  "it": "Italiyanci",
  "it_CH": "Italiyanci (Suwizalan)",
  "it_IT": "Italiyanci (Italiya)",
  "it_SM": "Italiyanci (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Japananci",
  "ja_JP": "Japananci (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Machame",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Jabananci",
  "ka": "Jojiyanci",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabyle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kamba",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Makonde",
  "kea": "Kabuverdianu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Khowar",
  "ki": "Kikuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kazakh",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Harshen Kimar",
  "km_KH": "Harshen Kimar (Kambodiya)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Harshen Koreya",
  "ko_KP": "Harshen Koreya (Koreya Ta Arewa)",
  "ko_KR": "Harshen Koreya (Koreya Ta Kudu)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ks": "Kashmiri",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambala",
  "ksf": "Bafia",
  "ksh": "Colognian",
  "ku": "Kurdanci",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Cornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kirgizanci",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Dan Kabilar Latin",
  "lad": "Ladino",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luxembourgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Laothian",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "loz": "Lozi",
  "lrc": "Northern Luri",
  "lt": "Lituweniyanci",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luo",
  "lus": "Mizo",
  "luy": "Luyia",
  "lv": "Latbiyanci",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "mas": "Harshen Masai",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meru",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Metaʼ",
  "mh": "Marshallese",
  "mi": "Maori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mk": "Dan Masedoniya",
  "mk_MK": "Macedonian (Macedonia)",
  "ml": "Kabilar Maleyalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongolian",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Kʼabilan Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Harshen Malai",
  "ms_BN": "Harshen Malai (Burune)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Harshen Malai (Malaisiya)",
  "ms_SG": "Harshen Malai (Singapur)",
  "mt": "Harshen Maltis",
  "mt_MT": "Maltese (Malta)",
  "mua": "Mundang",
  "mul": "Harsuna masu yawa",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Burmanci",
  "my_MM": "Burmanci (Burma, Miyamar)",
  "mye": "Myene",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Norwegian Bokmål",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "North Ndebele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Low German",
  "ne": "Nepali",
  "ne_IN": "Nepali (Indiya)",
  "ne_NP": "Nepali (Nefal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Holanci",
  "nl_AW": "Holanci (Aruba)",
  "nl_BE": "Holanci (Belgiyom)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Holanci (Holan)",
  "nl_SR": "Holanci (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwegian Nynorsk",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ngiemboon",
  "no": "Yaren mutanen Norway",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nus": "Nuer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Nyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Ositanci",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oriyanci",
  "or_IN": "Oriya (India)",
  "os": "Ossetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "pa": "Punjabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Punjabi (Indiya)",
  "pa_PK": "Punjabi (Pakistan)",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Harshen Polan",
  "pl_PL": "Harshen Polan (Polan)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "prg": "Ferusawa",
  "pro": "Old Provençal",
  "ps": "Pashtanci",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Harshen Fotugis",
  "pt_AO": "Harshen Portugal (Angola)",
  "pt_BR": "Harshen Portugal (Birazil)",
  "pt_CV": "Harshen Portugal (Tsibiran Kap Barde)",
  "pt_GW": "Harshen Portugal (Gini Bisau)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Harshen Portugal (Mozambik)",
  "pt_PT": "Harshen Fotugis (Portugal)",
  "pt_ST": "Harshen Portugal (Sawo Tome Da Paransip)",
  "pt_TL": "Harshen Portugal (Timor Ta Gabas)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romansh",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Romaniyanci",
  "ro_MD": "Romaniyanci (Maldoba)",
  "ro_RO": "Romaniyanci (Romaniya)",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Root",
  "rtm": "Rotuman",
  "ru": "Rashanci",
  "ru_BY": "Rashanci (Belarus)",
  "ru_KG": "Rashanci (Kirgizistan)",
  "ru_KZ": "Rashanci (Kazakistan)",
  "ru_MD": "Rashanci (Maldoba)",
  "ru_RU": "Rashanci (Rasha)",
  "ru_UA": "Rashanci (Yukaran)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Kiniyaruwanda",
  "rw_RW": "Kiniyaruwanda (Ruwanda)",
  "rwk": "yaren Rwa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sam": "Samaritan Aramaic",
  "saq": "Samburu",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Sindiyanci",
  "sdc": "Sassarese Sardinian",
  "se": "Northern Sami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selkup",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgs": "Samogitian",
  "sh": "Kuroweshiyancin-Sabiya",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhalanci",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sk": "Basulke",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Basulabe",
  "sl_SI": "Slovenian (Slovenia)",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samoan",
  "sma": "Southern Sami",
  "smj": "Lule Sami",
  "smn": "Inari Sami",
  "sms": "Skolt Sami",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Somalianci",
  "so_DJ": "Somali (Jibuti)",
  "so_ET": "Somali (Habasha)",
  "so_KE": "Somali (Kenya)",
  "so_SO": "Somali (Somaliya)",
  "sog": "Sogdien",
  "sq": "Albanian",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Sabiyan",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssy": "Saho",
  "st": "Sesotanci",
  "stq": "Saterland Frisian",
  "su": "Sudananci",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Harshen Suwedan",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Harshen Suwedan (Finlan)",
  "sv_SE": "Harshen Suwedan (Suwedan)",
  "sw": "Harshen Suwahili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Tamil",
  "ta_IN": "Tamil (Indiya)",
  "ta_LK": "Tamil (Siri Lanka)",
  "ta_MY": "Tamil (Malaisiya)",
  "ta_SG": "Tamil (Singapur)",
  "tcy": "Tulu",
  "te": "Dʼan/ʼYar Kabilar Telug",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Tajik",
  "th": "Thai",
  "th_TH": "Thai (Tailan)",
  "ti": "Tigriyanci",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Tukmenistanci",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Klingon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Harshen Turkiyya",
  "tr_CY": "Harshen Turkiyya (Sifurus)",
  "tr_TR": "Harshen Turkiyya (Turkiyya)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Tatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tvl": "Tuvalu",
  "tw": "Tiwiniyanci",
  "twq": "Tasawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Tamazight na Atlas Tsaka",
  "udm": "Udmurt",
  "ug": "Ugiranci",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "Harshen Yukuren",
  "uk_UA": "Harshen Yukuren (Yukaran)",
  "umb": "Umbundu",
  "und": "Harshen da ba a sani ba",
  "ur": "Urdawa",
  "ur_IN": "Harshen Urdu (Indiya)",
  "ur_PK": "Harshen Urdu (Pakistan)",
  "uz": "Uzbek",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Vai",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Harshen Biyetinam",
  "vi_VN": "Harshen Biyetinam (Biyetinam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Volapük",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wo": "Wolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Bazosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "Yiddish",
  "yo": "Yarbanci",
  "yo_BJ": "Yarbanci (Binin)",
  "yo_NG": "Yarbanci (Najeriya)",
  "yrl": "Nheengatu",
  "yue": "Cantonese",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Standard Moroccan Tamazight",
  "zh": "Harshen Sinanci",
  "zh_CN": "Harshen Sin (Caina, Sin)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Sauƙaƙaƙƙen Sinanci",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Sinanci na gargajiya",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Harshen Sin (Singapur)",
  "zh_TW": "Harshen Sin (Taiwan)",
  "zu": "Harshen Zulu",
  "zu_ZA": "Harshen Zulu (Afirka Ta Kudu)",
  "zun": "Zuni",
  "zxx": "Babu abun-ciki na yare",
  "zza": "Zaza"
};
