const names = {
  "aa": "Afar",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "af": "ایفریکانز",
  "ain": "Ainu",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "an": "Aragonese",
  "anp": "Angika",
  "arp": "Arapaho",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "Awadhi",
  "az": "آزربائیجانی",
  "ban": "Balinese",
  "bas": "Basaa",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bn": "بنگالی",
  "bs": "بوسنی",
  "bug": "Buginese",
  "byn": "Blin",
  "ca": "کاٹالانین",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chy": "Cheyenne",
  "ckb": "سورانی کردش",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "dak": "Dakota",
  "dar": "Dargwa",
  "de_AT": "جرمن (آسٹریا)",
  "de_CH": "جرمن (سوئٹزر لینڈ)",
  "dgr": "Dogrib",
  "dzg": "Dazaga",
  "eka": "Ekajuk",
  "en_AU": "انگریزی (آسٹریلیا)",
  "en_CA": "انگریزی (کینیڈا)",
  "en_GB": "انگریزی (سلطنت متحدہ)",
  "en_US": "انگریزی (ریاستہائے متحدہ)",
  "es_ES": "ہسپانوی (ہسپانیہ)",
  "es_MX": "ہسپانوی (میکسیکو)",
  "ewo": "Ewondo",
  "fa_AF": "فارسی (افغانستان)",
  "ff": "Fulah",
  "fon": "Fon",
  "fr_CA": "فرانسیسی (کینیڈا)",
  "fr_CH": "فرانسیسی (سوئٹزر لینڈ)",
  "frc": "Cajun French",
  "fur": "Friulian",
  "gan": "Gan Chinese",
  "gd": "سکاٹ گیلِک",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gor": "Gorontalo",
  "gwi": "Gwichʼin",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hup": "Hupa",
  "hy": "ارمینی",
  "hz": "Herero",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "jbo": "Lojban",
  "ka": "جارجی",
  "kac": "Kachin",
  "kaj": "Jju",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kde": "ماكونده",
  "kea": "كابويرديانو",
  "kfo": "Koro",
  "kha": "Khasi",
  "khq": "كويرا شيني",
  "ki": "کیکو",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kl": "كالاليست",
  "kln": "كالينجين",
  "kmb": "Kimbundu",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ksh": "Colognian",
  "kum": "Kumyk",
  "kv": "Komi",
  "lad": "Ladino",
  "lb": "لگژمبرگ کا باشندہ",
  "lez": "Lezghian",
  "li": "Limburgish",
  "lt": "لتھُواینین",
  "lu": "لبا-كاتانجا",
  "lun": "Lunda",
  "lus": "Mizo",
  "mad": "Madurese",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Makasar",
  "mas": "ماسای",
  "mdf": "Moksha",
  "men": "Mende",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mn": "منگؤلی",
  "mni": "Manipuri",
  "mos": "Mossi",
  "ms": "مالائی",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl_BE": "ڈچ (بیلجیم)",
  "nmg": "كوايسو",
  "nn": "نورویجینی نینورسک",
  "nnh": "Ngiemboon",
  "nog": "Nogai",
  "nr": "South Ndebele",
  "nv": "Navajo",
  "oc": "آكسیٹان",
  "or": "اورِیا",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pl": "پولستانی",
  "prg": "Prussian",
  "pt_BR": "پُرتگالی (برازیلی)",
  "pt_PT": "پُرتگالی (پرتگال)",
  "quc": "كيشی",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "ro": "رومنی",
  "ro_MD": "رومنی (مالدووا)",
  "root": "Root",
  "rup": "Aromanian",
  "sa": "سَنسکرِت",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "ses": "كويرابورو سينی",
  "sg": "سانغو",
  "shn": "Shan",
  "snk": "Soninke",
  "sr": "صربی",
  "srn": "Sranan Tongo",
  "ssy": "Saho",
  "suk": "Sukuma",
  "swb": "Comorian",
  "syr": "Syriac",
  "tem": "Timne",
  "tig": "Tigre",
  "tl": "Tagalog",
  "trv": "Taroko",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "tyv": "Tuvinian",
  "udm": "Udmurt",
  "umb": "Umbundu",
  "vo": "Volapük",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "xal": "Kalmyk",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yue": "Cantonese",
  "zh_Hans": "چینی (آسان)",
  "zh_Hant": "چینی (روایتی)",
  "zun": "Zuni",
  "zza": "Zaza"
};
