const names = {
  "arn": "araukansk",
  "bas": "basa",
  "crh": "krim tyrkisk",
  "frc": "Cajun French",
  "fy": "frisisk",
  "gan": "Gan Chinese",
  "hak": "Hakka Chinese",
  "hsn": "Xiang Chinese",
  "ms": "malay",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nap": "neapolitansk",
  "niu": "niuean",
  "nyo": "nyoro sprog",
  "ota": "osmannisk-tyrkisk",
  "pa": "punjabi",
  "prg": "Prussian",
  "rar": "rarotongan",
  "sam": "samaritansk",
  "shu": "tchadisk-arabisk",
  "so": "somalisk",
  "ta": "tamilsk",
  "tg": "tajik",
  "th": "thailandsk",
  "tvl": "tuvalu",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "xh": "xhosa"
};
