const names = {
  "001": "Dunida",
  "002": "Afrika",
  "003": "Waqooyi Ameerika",
  "005": "Koonfur Ameerika",
  "009": "Osheeniya",
  "011": "Galbeeka Afrika",
  "013": "Bartamaha Ameerika",
  "014": "Afrikada Bari",
  "015": "Waqooyiga Afrika",
  "017": "Afrikada Dhexe",
  "018": "Afrikada Koonfureed",
  "019": "Ameerikaas",
  "021": "Waqooyiga Ameerika",
  "029": "Karibiyaan",
  "030": "Aasiyada Bari",
  "034": "Aasiyada Koonfureed",
  "035": "Aasiyada Koonfur-galbeed",
  "039": "Yurubta Koonfureed",
  "053": "Austraalaasiya",
  "054": "Melaneesiya",
  "057": "Gobolka Aasiyada yar",
  "061": "Booliyneesiya",
  "062": "Koonfurta-Bartamaha Aasiya",
  "142": "Aasiya",
  "143": "Bartamaha Aasiya",
  "145": "Aasiyada Galbeed",
  "150": "Yurub",
  "151": "Yurubta Bari",
  "154": "Yurubta Waqooyi",
  "155": "Yurubta Galbeed",
  "172": "Barwaaqo Sooranka Dawladaha Madaxa Banaan",
  "200": "Czechoslovakia",
  "202": "Afrikada ka hooseysa Saxaraha",
  "419": "Laatiin Ameerika",
  "830": "Jasiiradaha Channel",
  "AC": "Jasiiradda Asensiyoon",
  "AD": "Andora",
  "AE": "Imaaraadka Carabta ee Midoobay",
  "AF": "Afgaanistaan",
  "AG": "Antigua & Barbuuda",
  "AI": "Anguula",
  "AL": "Albaaniya",
  "AM": "Armeeniya",
  "AN": "Netherlands Antilles",
  "AO": "Angoola",
  "AQ": "Antaarktika",
  "AR": "Arjentiina",
  "AS": "Samowa Ameerika",
  "AT": "Awsteriya",
  "AU": "Awstaraaliya",
  "AW": "Aruba",
  "AX": "Jasiiradda Aland",
  "AZ": "Asarbajan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Qoraalka Luuqada Caucasian Albanian",
  "Ahom": "Dadka Ahom",
  "Arab": "Carabi",
  "Aran": "Farta Luuqada Faarsiga",
  "Armi": "Luuqada Imperial Aramaic",
  "Armn": "Armeeniyaan",
  "Avst": "Luuqada Avestan",
  "BA": "Boosniya & Harsegofina",
  "BB": "Baarbadoos",
  "BD": "Bangladesh",
  "BE": "Biljam",
  "BF": "Burkiina Faaso",
  "BG": "Bulgaariya",
  "BH": "Baxreyn",
  "BI": "Burundi",
  "BJ": "Biniin",
  "BL": "St. Baathelemiy",
  "BM": "Barmuuda",
  "BN": "Buruneeya",
  "BO": "Boliifiya",
  "BQ": "Karibiyaan Nadarlands",
  "BR": "Baraasiil",
  "BS": "Bahaamas",
  "BT": "Buutan",
  "BV": "Buufet Island",
  "BW": "Botuswaana",
  "BY": "Belarus",
  "BZ": "Beliis",
  "Bali": "Baliniis",
  "Bamu": "Bamum",
  "Bass": "Qoraalka Vah",
  "Batk": "Batak",
  "Beng": "Baangla",
  "Bhks": "Qoraalka Bhaiksuki",
  "Blis": "Calaamadaha xasaasiga ah",
  "Bopo": "Farta Manadariinka Taywaan",
  "Brah": "Dhirta Brahmi",
  "Brai": "Qoraalka Indhoolaha",
  "Bugi": "Luuqada Buginiiska",
  "Buhd": "Luuqada Buhid",
  "CA": "Kanada",
  "CC": "Jasiiradda Kookoos",
  "CD": "Jamhuuriyadda Dimuquraadiga Kongo",
  "CF": "Jamhuuriyadda Afrikada Dhexe",
  "CG": "Kongo",
  "CH": "Swiiserlaand",
  "CI": "Ayfori Koost",
  "CK": "Jasiiradda Kook",
  "CL": "Jili",
  "CM": "Kaameruun",
  "CN": "Shiinaha",
  "CO": "Koloombiya",
  "CP": "Jasiiradda Kilibarton",
  "CR": "Kosta Riika",
  "CS": "serbiya iyo Monteneegro",
  "CU": "Kuuba",
  "CV": "Jasiiradda Kayb Faarde",
  "CW": "Kurakaaw",
  "CX": "Jasiiradda Kirismas",
  "CY": "Qubrus",
  "CZ": "Jekiya",
  "Cakm": "Jakma",
  "Cans": "Qoraalka Luuqada Aborajiinka ee Kanada",
  "Cari": "Luuqada kaariyaanka",
  "Cham": "Jam",
  "Cher": "Jerokee",
  "Chrs": "Luuqada Korasmiyaanka",
  "Cirt": "Cirth",
  "Copt": "Dadka Kotiga",
  "Cprt": "sibraas dhalad ah",
  "Cyrl": "Siriylik",
  "Cyrs": "Kaniisada Old Slavonic Cyrillic",
  "DD": "Bariga Jarmalka",
  "DE": "Jarmal",
  "DG": "Diyeego Karsiya",
  "DJ": "Jabuuti",
  "DK": "Denmark",
  "DM": "Dominika",
  "DO": "Jamhuuriyaddda Dominika",
  "DZ": "Aljeeriya",
  "Deva": "Dhefangaari",
  "Diak": "Luuqadaha Dives Akuru",
  "Dogr": "Dadka Dogra",
  "Dsrt": "Gobalka Deseret",
  "Dupl": "Qoraalka Duployan shorthand",
  "EA": "Seyuta & Meliila",
  "EC": "Ikuwadoor",
  "EE": "Estooniya",
  "EG": "Masar",
  "EH": "Saxaraha Galbeed",
  "ER": "Eritreeya",
  "ES": "Isbeyn",
  "ET": "Itoobiya",
  "EU": "Midowga Yurub",
  "EZ": "Yurusoon",
  "Egyd": "Dimoqraadi Masaari ah",
  "Egyh": "Hieratic Masri ah",
  "Egyp": "Fartii hore ee Masaarida",
  "Elba": "Magaalada Elbasan",
  "Elym": "Qoraalka Elymaic",
  "Ethi": "Itoobiya",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Jaziiradaha Fooklaan",
  "FM": "Mikroneesiya",
  "FO": "Jasiiradda Faroo",
  "FR": "Faransiis",
  "FX": "Magaalada Metropolitan",
  "GA": "Gaaboon",
  "GB": "Boqortooyada Midowday",
  "GD": "Giriinaada",
  "GE": "Joorjiya",
  "GF": "Faransiis Gini",
  "GG": "Guurnsey",
  "GH": "Gaana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambiya",
  "GN": "Gini",
  "GP": "Guadeluub",
  "GQ": "Ekuwatooriyal Gini",
  "GR": "Giriig",
  "GS": "Jasiiradda Joorjiyada Koonfureed & Sandwij",
  "GT": "Guwaatamaala",
  "GU": "Guaam",
  "GW": "Gini-Bisaaw",
  "GY": "Guyana",
  "Geok": "Khutsuri reer Georgia",
  "Geor": "Jiyoorjoyaan",
  "Glag": "Qoraalka Glagolitic",
  "Gong": "Gumjala Gondi",
  "Gonm": "Qoraalka Masaram Gondi",
  "Goth": "Dadka Gothic",
  "Gran": "Qoraalka Grantha",
  "Grek": "Giriik",
  "Gujr": "Gujaraati",
  "Guru": "Luuqada gujarati",
  "HK": "Hong Kong",
  "HM": "Jasiiradda Haad & MakDonald",
  "HN": "Honduras",
  "HR": "Korweeshiya",
  "HT": "Haiti",
  "HU": "Hangari",
  "Hanb": "luuqada Han iyo Farta Mandariinka Taywaan",
  "Hang": "Hanguul",
  "Hani": "Luuqada Han",
  "Hano": "Qoraalka Hanunoo",
  "Hans": "La fududeeyay",
  "Hant": "Hore",
  "Hatr": "Qoraalka Hatran",
  "Hebr": "Cibraani",
  "Hira": "Hiragana",
  "Hluw": "Qoraalka Anatolian Hieroglyphs",
  "Hmng": "Hmonga pahawh",
  "Hmnp": "Hmonga Nyiakeng Puachue",
  "Hrkt": "Qoraalka Xuruufta Jabaaniiska",
  "Hung": "Hangariyaankii Hore",
  "IC": "Jasiiradda Kanari",
  "ID": "Indoneesiya",
  "IE": "Ayrlaand",
  "IL": "Israaʼiil",
  "IM": "Jasiiradda Isle of Man",
  "IN": "Hindiya",
  "IO": "Dhul xadeedka Badweynta Hindiya ee Biritishka",
  "IQ": "Ciraaq",
  "IR": "Iiraan",
  "IS": "Ayslaand",
  "IT": "Talyaani",
  "Inds": "Indus",
  "Ital": "Itaaliggii Hore",
  "JE": "Jaarsey",
  "JM": "Jamaaika",
  "JO": "Urdun",
  "JP": "Jabaan",
  "Jamo": "Jaamo",
  "Java": "Jafaniis",
  "Jpan": "Jabaaniis",
  "Jurc": "Jurchen",
  "KE": "Kenya",
  "KG": "Kirgistaan",
  "KH": "Kamboodiya",
  "KI": "Kiribati",
  "KM": "Komooros",
  "KN": "St. Kitts & Nefis",
  "KP": "Kuuriyada Waqooyi",
  "KR": "Kuuriyada Koonfureed",
  "KW": "Kuwayt",
  "KY": "Cayman Islands",
  "KZ": "Kasaakhistaan",
  "Kali": "Kayah LI",
  "Kana": "Katakaana",
  "Khar": "Koraalka kharooshi",
  "Khmr": "Khamer",
  "Khoj": "Qoraalka Khojki",
  "Kits": "Qoraalka yar ee Khitan",
  "Knda": "Kanada",
  "Kore": "Kuuriyaan",
  "Kpel": "Kpelle",
  "Kthi": "kaithi",
  "LA": "Laos",
  "LB": "Lubnaan",
  "LC": "St. Lusia",
  "LI": "Liyjtensteyn",
  "LK": "Sirilaanka",
  "LR": "Laybeeriya",
  "LS": "Losooto",
  "LT": "Lituweeniya",
  "LU": "Luksemboorg",
  "LV": "Latfiya",
  "LY": "Liibya",
  "Lana": "Lanna",
  "Laoo": "Dalka Lao",
  "Latf": "Fraktur Latin",
  "Latg": "Gaelic Latin",
  "Latn": "Laatiin",
  "Lepc": "Lebja",
  "Limb": "Limbu",
  "Lina": "Nidaamka qoraalka Linear A",
  "Linb": "Nidaamka qoraalka Linear B",
  "Lisu": "Wabiga Fraser",
  "Loma": "Loma",
  "Lyci": "Lyciantii Hore",
  "Lydi": "Lydian",
  "MA": "Morooko",
  "MC": "Moonako",
  "MD": "Moldofa",
  "ME": "Moontenegro",
  "MF": "St. Maartin",
  "MG": "Madagaskar",
  "MH": "Jasiiradda Maarshal",
  "MI": "Jasiiradaha Midway",
  "MK": "Masedooniya Waqooyi",
  "ML": "Maali",
  "MM": "Miyanmar",
  "MN": "Mongooliya",
  "MO": "Makaaw",
  "MP": "Jasiiradda Waqooyiga Mariaana",
  "MQ": "Maartinik",
  "MR": "Muritaaniya",
  "MS": "Montserrat",
  "MT": "Maalta",
  "MU": "Mawrishiyaas",
  "MV": "Maaldiqeen",
  "MW": "Malaawi",
  "MX": "Meksiko",
  "MY": "Malaysia",
  "MZ": "Musambiik",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Luuqada Mandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "Mayaan hieroglyphs",
  "Medf": "Madefaidrin",
  "Mend": "Mende",
  "Merc": "Meroitic Curve",
  "Mero": "Meroitic",
  "Mlym": "Maalayalam",
  "Modi": "Moodi",
  "Mong": "Mongooliyaan",
  "Moon": "Dayax",
  "Mroo": "Mro",
  "Mtei": "Qoraalka Luuqada Meitei",
  "Mult": "Multani",
  "Mymr": "Mayanmaar",
  "NA": "Namiibiya",
  "NC": "Jasiiradda Niyuu Kaledooniya",
  "NE": "Nayjer",
  "NF": "Jasiiradda Noorfolk",
  "NG": "Nayjeeriya",
  "NI": "Nikaraaguwa",
  "NL": "Nederlaands",
  "NO": "Noorweey",
  "NP": "Nebaal",
  "NR": "Nauru",
  "NT": "Aagga Dhex-dhexaad ah",
  "NU": "Niue",
  "NZ": "Niyuusiilaand",
  "Nand": "Nandinagari",
  "Narb": "Carabiyadii Hore ee Wuqooye",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Cumaan",
  "Ogam": "Ogham",
  "Olck": "Ol Jiki",
  "Orkh": "Orkhon",
  "Orya": "Oodhiya",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Baanama",
  "PC": "Territory Aaminaada Jasiiradaha Baasifigga",
  "PE": "Beeru",
  "PF": "Booliyneesiya Faransiiska",
  "PG": "Babua Niyuu Gini",
  "PH": "Filibiin",
  "PK": "Bakistaan",
  "PL": "Booland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Bitkairn",
  "PR": "Bueerto Riiko",
  "PS": "Falastiin Daanka galbeed iyo Qasa",
  "PT": "Bortugaal",
  "PU": "Jasiiradaha Baasifigga ee Kaladuwan",
  "PW": "Balaaw",
  "PY": "Baraguaay",
  "PZ": "Aaga Kanaalka Panama",
  "Palm": "Palmyrene",
  "Pauc": "Baaw Sin Haaw",
  "Perm": "Permic gii hore",
  "Phag": "Qoraalka Phags-pa",
  "Phli": "Qoraaladii hore ee Pahlavi",
  "Phlp": "Qoraalka midig laga bilaabo ee faarsiyiintii",
  "Phlv": "Buugga Pahlavi",
  "Phnx": "Luuqada Phoenicianka",
  "Plrd": "Shibanaha",
  "Prti": "Qoraalka Parthian",
  "QA": "Qadar",
  "QO": "Dhulxeebeedka Osheeniya",
  "Qaag": "Qoraalka Sawgiga",
  "RE": "Riyuuniyon",
  "RO": "Rumaaniya",
  "RS": "Seerbiya",
  "RU": "Ruush",
  "RW": "Ruwanda",
  "Rjng": "Dadka Rejan",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Dadka Rejang",
  "SA": "Sacuudi Carabiya",
  "SB": "Jasiiradda Solomon",
  "SC": "Sishelis",
  "SD": "Suudaan",
  "SE": "Iswidhan",
  "SG": "Singaboor",
  "SH": "Saint Helena",
  "SI": "Islofeeniya",
  "SJ": "Jasiiradda Sfaldbaad & Jaan Mayen",
  "SK": "Islofaakiya",
  "SL": "Siraaliyoon",
  "SM": "San Marino",
  "SN": "Sinigaal",
  "SO": "Soomaaliya",
  "SR": "Surineym",
  "SS": "Koonfur Suudaan",
  "ST": "Sao Tome & Birincibal",
  "SU": "Midowgii Jamhuuriyadda Soofiyeeti ee Soofiyeeti",
  "SV": "El Salfadoor",
  "SX": "Siint Maarteen",
  "SY": "Suuriya",
  "SZ": "Eswaatiini",
  "Samr": "Dadka Samaritan",
  "Sara": "Sarati",
  "Sarb": "Crabiyaankii Hore ee Wuqooyi",
  "Saur": "Sawrashtra",
  "Sgnw": "Qaabka dhagoolka loola hadlo",
  "Shaw": "calaamad qoris",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "khudwadi",
  "Sinh": "Sinhaala",
  "Sogd": "Sogdiyaan",
  "Sogo": "Sogdiyaankii Hore",
  "Sora": "Qoraalka Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Dadka Sundaniiska",
  "Sylo": "Qoraalka Luuqada Sylheti",
  "Syrc": "Lahjada Syriac",
  "Syre": "Estrangelo Syriac",
  "Syrj": "Galbeedka Syriac",
  "Syrn": "Bariga Siiriya",
  "TA": "Tiristan da Kunha",
  "TC": "Turks & Kaikos Island",
  "TD": "Jaad",
  "TF": "Dhul xadeedka Koonfureed ee Faransiiska",
  "TG": "Toogo",
  "TH": "Taylaand",
  "TJ": "Tajikistan",
  "TK": "Tokelaaw",
  "TL": "Timoor",
  "TM": "Turkmenistan",
  "TN": "Tuniisiya",
  "TO": "Tonga",
  "TR": "Turki",
  "TT": "Tirinidaad & Tobago",
  "TV": "Tufaalu",
  "TW": "Taywaan",
  "TZ": "Tansaaniya",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Tai Lue cusub",
  "Taml": "Taamiil",
  "Tang": "Luuqada Tangut",
  "Tavt": "Farta lagu Qoro Luuqadaha Tai",
  "Telu": "Teeluguu",
  "Teng": "Tengwar",
  "Tfng": "Farta Tifinagh",
  "Tglg": "Luuqada Tagalog",
  "Thaa": "Daana",
  "Thai": "Taay",
  "Tibt": "Tibetaan",
  "Tirh": "Qoraalka Luuqada Maithili",
  "UA": "Yukrayn",
  "UG": "Ugaanda",
  "UM": "Jasiiradaha ka baxsan Maraykanka",
  "UN": "Qaramada Midoobay",
  "US": "Maraykanka",
  "UY": "Uruguwaay",
  "UZ": "Uusbakistaan",
  "Ugar": "Luuqada Ugaritic",
  "VA": "Faatikaan",
  "VC": "St. Finsent & Girenadiins",
  "VD": "Waqooyiga Fiyatnaam",
  "VE": "Fenisuweela",
  "VG": "Biritish Farjin Island",
  "VI": "U.S Fargin Island",
  "VN": "Fiyetnaam",
  "VU": "Fanuaatu",
  "Vaii": "Dadka Vai",
  "Visp": "Khudbad Muuqata",
  "WF": "Walis & Futuna",
  "WK": "Jasiiradda Wake",
  "WS": "Samoowa",
  "Wara": "Nidaamka Qoraalka Luuqada Ho",
  "Wcho": "Dadka wanjo",
  "Wole": "Woleai",
  "XA": "Shigshiga",
  "XB": "Pseudo-Bidi",
  "XK": "Koosofo",
  "Xpeo": "Faarsigii Hore",
  "Xsux": "Qoraalkii Hore ee dadka Sumaariyiinta ee dhulka mesobataamiya",
  "YD": "Jamhuuriyadda Dimuqraadiga ah ee Yemen",
  "YE": "Yaman",
  "YT": "Mayotte",
  "Yezi": "Dadka Yesiidiga",
  "Yiii": "Tiknoolajiyada Yi",
  "ZA": "Koonfur Afrika",
  "ZM": "Saambiya",
  "ZW": "Simbaabwe",
  "ZZ": "Gobol aan la aqoonin amase aan saxnayn",
  "Zanb": "Xarafka laba jibaaran ee kujira Xarfaha Zanabazar",
  "Zinh": "Dhaxlay",
  "Zmth": "Aqoonsiga Xisaabta",
  "Zsye": "Calaamad Dareen Muujin",
  "Zsym": "Calaamado",
  "Zxxx": "Aan la qorin",
  "Zyyy": "Caadi ahaan",
  "Zzzz": "Far aan la aqoon amase aan saxnayn",
  "aa": "Afar",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adyghe",
  "ae": "Avestan",
  "aeb": "Tunisian Arabic",
  "af": "Afrikaanka",
  "af_NA": "Afrikaans (Namibia)",
  "af_ZA": "Afrikaans (South Africa)",
  "afa": "Luqadda Afro-Easiya",
  "afh": "Afrihili",
  "agq": "Ageem",
  "ain": "Ainu",
  "ak": "Akan",
  "ak_GH": "Akan (Gaana)",
  "akk": "Akkadian",
  "akz": "Alabama",
  "ale": "Aleut",
  "alg": "Luqadda Algonquian",
  "aln": "Gheg Albanian",
  "alt": "Southern Altai",
  "am": "Axmaari",
  "am_ET": "Axmaari (Itoobiya)",
  "an": "Aragonese",
  "ang": "Old English",
  "anp": "Angika",
  "apa": "Afka Apache",
  "ar": "Carabi",
  "ar_001": "Carabiga rasmiga ah",
  "ar_AE": "Carabi (Imaaraadka Carabta ee Midoobay)",
  "ar_BH": "Carabi (Baxreyn)",
  "ar_DJ": "Carabi (Jabuuti)",
  "ar_DZ": "Carabi (Aljeeriya)",
  "ar_EG": "Carabi (Masar)",
  "ar_EH": "Arabic (Western Sahara)",
  "ar_ER": "Carabi (Eretereeya)",
  "ar_IL": "Carabi (Israaʼiil)",
  "ar_IQ": "Carabi (Ciraaq)",
  "ar_JO": "Carabi (Urdun)",
  "ar_KM": "Carabi (Komooros)",
  "ar_KW": "Carabi (Kuwayt)",
  "ar_LB": "Carabi (Lubnaan)",
  "ar_LY": "Carabi (Liibiya)",
  "ar_MA": "Carabi (Marooko)",
  "ar_MR": "Carabi (Muritaaniya)",
  "ar_OM": "Carabi (Cumaan)",
  "ar_PS": "Carabi (Falastiin Daanka galbeed iyo Qasa)",
  "ar_QA": "Carabi (Qadar)",
  "ar_SA": "Carabi (Sacuudi Carabiya)",
  "ar_SD": "Carabi (Suudaan)",
  "ar_SO": "Carabi (Soomaaliya)",
  "ar_SS": "Arabic (South Sudan)",
  "ar_SY": "Carabi (Suuriya)",
  "ar_TD": "Carabi (Jaad)",
  "ar_TN": "Carabi (Tuniisiya)",
  "ar_YE": "Carabi (Yaman)",
  "arc": "Aramaic",
  "arn": "Mapuche",
  "aro": "Araona",
  "arp": "Arapaho",
  "arq": "Algerian Arabic",
  "ars": "Najdi Carabi",
  "art": "Luqad macmal ah",
  "arw": "Arawak",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "Asaamiis",
  "as_IN": "Assamese (India)",
  "asa": "Asu",
  "ase": "American Sign Language",
  "ast": "Astuuriyaan",
  "ath": "Luqadda Athapascan",
  "aus": "Luqadda Australia",
  "av": "Avaric",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymara",
  "az": "Asarbayjan",
  "az_AZ": "Azerbaijani (Azerbaijan)",
  "az_Arab": "Azerbaijan (Carabi)",
  "az_Cyrl": "Azerbaijani (Cyrillic)",
  "az_Cyrl_AZ": "Azerbaijani (Cyrillic, Azerbaijan)",
  "az_Latn": "Azerbaijani (Latin)",
  "az_Latn_AZ": "Azerbaijani (Latin, Azerbaijan)",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bad": "Banda",
  "bai": "Luqadda Bamileke",
  "bal": "Baluchi",
  "ban": "Balinese",
  "bar": "Bavarian",
  "bas": "Basaa",
  "bat": "Luqadda Baltiga",
  "bax": "Bamun",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Beleruusiyaan",
  "be_BY": "Beleruusiyaan (Belarus)",
  "bej": "Beja",
  "bem": "Bemba",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Bafut",
  "bfq": "Badaga",
  "bg": "Bulgeeriyaan",
  "bg_BG": "Bulgeeriyaan (Bulgaariya)",
  "bgn": "Galbeedka Balochi",
  "bh": "Bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Kom",
  "bla": "Siksika",
  "bm": "Bambaara",
  "bm_Latn": "Bambara (Latin)",
  "bm_Latn_ML": "Bambara (Latin, Mali)",
  "bn": "Bangladesh",
  "bn_BD": "Bangaali (Bangaaladheesh)",
  "bn_IN": "Bangaali (Hindiya)",
  "bnt": "Bantu",
  "bo": "Tibeetaan",
  "bo_CN": "Tibetan (China)",
  "bo_IN": "Tibetan (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Biriton",
  "br_FR": "Breton (France)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosniyaan",
  "bs_BA": "Bosnian (Bosnia & Herzegovina)",
  "bs_Cyrl": "Bosnian (Cyrillic)",
  "bs_Cyrl_BA": "Bosnian (Cyrillic, Bosnia & Herzegovina)",
  "bs_Latn": "Bosnian (Latin)",
  "bs_Latn_BA": "Bosnian (Latin, Bosnia & Herzegovina)",
  "bss": "Akoose",
  "btk": "Batak",
  "bua": "Buriat",
  "bug": "Buginese",
  "bum": "Bulu",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Katalaan",
  "ca_AD": "Catalan (Andorra)",
  "ca_ES": "Catalan (Spain)",
  "ca_FR": "Catalan (France)",
  "ca_IT": "Catalan (Italy)",
  "cad": "Caddo",
  "cai": "Luuqada Hindida Dhexe ee Ameerika",
  "car": "Carib",
  "cau": "Luqadda Caucasian",
  "cay": "Cayuga",
  "cch": "Atsam",
  "ccp": "Jakma",
  "ce": "Jejen",
  "ceb": "Sebuano",
  "cel": "Luqadda Celtic",
  "cgg": "Jiga",
  "ch": "Chamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukese",
  "chm": "Mari",
  "chn": "Chinook Jargon",
  "cho": "Choctaw",
  "chp": "Chipewyan",
  "chr": "Jerookee",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Bartamaha Kurdish",
  "cmc": "Luqadda Chamic",
  "co": "Korsikan",
  "cop": "Coptic",
  "cpe": "Ingiriis ku saleysan Creole ama Pidgin",
  "cpf": "Faransiis ku saleysan Creole ama Pidgin",
  "cpp": "Creole ama Pidgin oo saldhigeedu yahay Boortaqiiska",
  "cps": "Capiznon",
  "cr": "Cree",
  "crh": "Crimean Turkish",
  "crp": "Creole ama Pidgin",
  "crs": "Seselwa Creole Faransiis",
  "cs": "Jeeg",
  "cs_CZ": "Jeeg (Jamhuuriyadda Jek)",
  "csb": "Kashubian",
  "cu": "Kaniisadda Islaafik",
  "cus": "Luuqada Kuushitiga",
  "cv": "Chuvash",
  "cy": "Welsh",
  "cy_GB": "Welsh (United Kingdom)",
  "da": "Dhaanish",
  "da_DK": "Danish (Denmark)",
  "da_GL": "Danish (Greenland)",
  "dak": "Dakota",
  "dar": "Dargwa",
  "dav": "Taiita",
  "day": "Dayak",
  "de": "Jarmal",
  "de_AT": "Jarmal (Awsteriya)",
  "de_BE": "Jarmal (Biljam)",
  "de_CH": "Jarmal (Swiiserlaand)",
  "de_DE": "Jarmal (Jarmal)",
  "de_LI": "Jarmal (Liechtenstein)",
  "de_LU": "Jarmal (Luksemboorg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinka",
  "dje": "Zarma",
  "doi": "Dogri",
  "dra": "Luqadda Dravidian",
  "dsb": "Lower Sorbian",
  "dtp": "Central Dusun",
  "dua": "Duaala",
  "dum": "Middle Dutch",
  "dv": "Divehi",
  "dyo": "Joola-Foonyi",
  "dyu": "Dyula",
  "dz": "D’zongqa",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embuu",
  "ee": "Eewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Ancient Egyptian",
  "eka": "Ekajuk",
  "el": "Giriik",
  "el_CY": "Giriik (Qubrus)",
  "el_GR": "Giriik (Giriig)",
  "elx": "Elamite",
  "en": "Ingiriisi",
  "en_AG": "Ingiriisi (Antigua iyo Barbuda)",
  "en_AI": "Ingiriisi (Anguilla)",
  "en_AS": "Ingiriisi (Samowa Ameerika)",
  "en_AU": "Ingiriisi (Awstaraaliya)",
  "en_BB": "Ingiriisi (Baarbadoos)",
  "en_BE": "Ingiriisi (Biljam)",
  "en_BM": "Ingiriisi (Bermuuda)",
  "en_BS": "Ingiriisi (Bahaamas)",
  "en_BW": "Ingiriisi (Botuswaana)",
  "en_BZ": "Ingiriisi (Belize)",
  "en_CA": "Ingiriisi (Kanada)",
  "en_CC": "English (Cocos (Keeling) Islands)",
  "en_CK": "Ingiriisi (Jaziiradda Cook)",
  "en_CM": "Ingiriisi (Kaameruun)",
  "en_CX": "English (Christmas Island)",
  "en_DG": "English (Diego Garcia)",
  "en_DM": "Ingiriisi (Domeenika)",
  "en_Dsrt": "Ingiriisi (Deseret)",
  "en_ER": "Ingiriisi (Eretereeya)",
  "en_FJ": "Ingiriisi (Fiji)",
  "en_FK": "Ingiriisi (Jaziiradaha Fooklaan)",
  "en_FM": "Ingiriisi (Micronesia)",
  "en_GB": "Ingiriisi (United Kingdom)",
  "en_GD": "Ingiriisi (Giriinaada)",
  "en_GG": "English (Guernsey)",
  "en_GH": "Ingiriisi (Gaana)",
  "en_GI": "Ingiriisi (Gibraltar)",
  "en_GM": "Ingiriisi (Gambiya)",
  "en_GU": "Ingiriisi (Guam)",
  "en_GY": "Ingiriisi (Guyana)",
  "en_HK": "English (Hong Kong SAR China)",
  "en_IE": "Ingiriisi (Ayrlaand)",
  "en_IM": "English (Isle of Man)",
  "en_IN": "Ingiriisi (Hindiya)",
  "en_IO": "Ingiriisi (British Indian Ocean Territory)",
  "en_JE": "English (Jersey)",
  "en_JM": "Ingiriisi (Jameyka)",
  "en_KE": "Ingiriisi (Kiiniya)",
  "en_KI": "Ingiriisi (Kiribati)",
  "en_KN": "Ingiriisi (Saint Kitts and Nevis)",
  "en_KY": "Ingiriisi (Cayman Islands)",
  "en_LC": "Ingiriisi (Saint Lucia)",
  "en_LR": "Ingiriisi (Laybeeriya)",
  "en_LS": "Ingiriisi (Losooto)",
  "en_MG": "Ingiriisi (Madagaskar)",
  "en_MH": "Ingiriisi (Marshall Islands)",
  "en_MO": "English (Macau SAR China)",
  "en_MP": "Ingiriisi (Northern Mariana Islands)",
  "en_MS": "Ingiriisi (Montserrat)",
  "en_MT": "Ingiriisi (Maalda)",
  "en_MU": "Ingiriisi (Murishiyoos)",
  "en_MW": "Ingiriisi (Malaawi)",
  "en_MY": "Ingiriisi (Malaysia)",
  "en_NA": "Ingiriisi (Namiibiya)",
  "en_NF": "Ingiriisi (Norfolk Island)",
  "en_NG": "Ingiriisi (Nayjeeriya)",
  "en_NR": "Ingiriisi (Nauru)",
  "en_NU": "Ingiriisi (Niue)",
  "en_NZ": "Ingiriisi (Neyuusilaand)",
  "en_PG": "Ingiriisi (Papua New Guinea)",
  "en_PH": "Ingiriisi (Filibiin)",
  "en_PK": "Ingiriisi (Bakistaan)",
  "en_PN": "Ingiriisi (Pitcairn)",
  "en_PR": "Ingiriisi (Puerto Rico)",
  "en_PW": "Ingiriisi (Palau)",
  "en_RW": "Ingiriisi (Ruwanda)",
  "en_SB": "Ingiriisi (Solomon Islands)",
  "en_SC": "Ingiriisi (Sishelis)",
  "en_SD": "Ingiriisi (Suudaan)",
  "en_SG": "Ingiriisi (Singaboor)",
  "en_SH": "Ingiriisi (Saint Helena)",
  "en_SL": "Ingiriisi (Siraaliyoon)",
  "en_SS": "English (South Sudan)",
  "en_SX": "English (Sint Maarten)",
  "en_SZ": "Ingiriisi (Iswaasilaand)",
  "en_TC": "Ingiriisi (Turks and Caicos Islands)",
  "en_TK": "Ingiriisi (Tokelau)",
  "en_TO": "Ingiriisi (Tonga)",
  "en_TT": "Ingiriisi (Trinidad and Tobago)",
  "en_TV": "Ingiriisi (Tuvalu)",
  "en_TZ": "Ingiriisi (Tansaaniya)",
  "en_UG": "Ingiriisi (Ugaanda)",
  "en_UM": "English (U.S. Outlying Islands)",
  "en_US": "Ingiriisi (Maraykanka)",
  "en_VC": "Ingiriisi (Saint Vincent and the Grenadines)",
  "en_VG": "Ingiriisi (British Virgin Islands)",
  "en_VI": "Ingiriisi (U.S. Virgin Islands)",
  "en_VU": "Ingiriisi (Vanuatu)",
  "en_WS": "Ingiriisi (Samoa)",
  "en_ZA": "Ingiriisi (Koonfur Afrika)",
  "en_ZM": "Ingiriisi (Saambiya)",
  "en_ZW": "Ingiriisi (Simbaabwe)",
  "enm": "Middle English",
  "eo": "Esperanto",
  "es": "Isbaanish",
  "es_419": "Isbaanishka (Laatiin Ameerika)",
  "es_AR": "Isbaanish (Arjantiin)",
  "es_BO": "Isbaanish (Boliifiya)",
  "es_CL": "Isbaanish (Jili)",
  "es_CO": "Isbaanish (Kolombiya)",
  "es_CR": "Isbaanish (Kosta Riika)",
  "es_CU": "Isbaanish (Kuuba)",
  "es_DO": "Isbaanish (Jamhuuriyadda Domeenika)",
  "es_EA": "Spanish (Ceuta & Melilla)",
  "es_EC": "Isbaanish (Ikuwadoor)",
  "es_ES": "Isbaanish (Isbayn)",
  "es_GQ": "Isbaanish (Equatorial Guinea)",
  "es_GT": "Isbaanish (Guwaatamaala)",
  "es_HN": "Isbaanish (Honduras)",
  "es_IC": "Spanish (Canary Islands)",
  "es_MX": "Isbaanish (Meksiko)",
  "es_NI": "Isbaanish (Nikaraaguwa)",
  "es_PA": "Isbaanish (Panama)",
  "es_PE": "Isbaanish (Peru)",
  "es_PH": "Isbaanish (Filibiin)",
  "es_PR": "Isbaanish (Puerto Rico)",
  "es_PY": "Isbaanish (Paraguay)",
  "es_SV": "Isbaanish (El Salvador)",
  "es_US": "Isbaanish (Maraykanka)",
  "es_UY": "Isbaanish (Uruguwaay)",
  "es_VE": "Isbaanish (Fenisuweela)",
  "esu": "Central Yupik",
  "et": "Istooniyaan",
  "et_EE": "Estonian (Estonia)",
  "eu": "Basquu",
  "eu_ES": "Basque (Spain)",
  "ewo": "Eewondho",
  "ext": "Extremaduran",
  "fa": "Faarisi",
  "fa_AF": "Faarisi (Afgaanistaan)",
  "fa_IR": "Faarisi (Iiraan)",
  "fan": "Fang",
  "fat": "Fanti",
  "ff": "Fuulah",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Fulah (Cameroon)",
  "ff_GN": "Fulah (Guinea)",
  "ff_MR": "Fulah (Mauritania)",
  "ff_SN": "Fulah (Senegal)",
  "fi": "Finishka",
  "fi_FI": "Finnish (Finland)",
  "fil": "Tagalog",
  "fit": "Tornedalen Finnish",
  "fiu": "Luqadda Finno-Ugrian",
  "fj": "Fijian",
  "fo": "Farowsi",
  "fo_FO": "Faroese (Faroe Islands)",
  "fon": "Fon",
  "fr": "Faransiis",
  "fr_BE": "Faransiis (Biljam)",
  "fr_BF": "Faransiis (Burkiina Faaso)",
  "fr_BI": "Faransiis (Burundi)",
  "fr_BJ": "Faransiis (Biniin)",
  "fr_BL": "French (St. Barthélemy)",
  "fr_CA": "Faransiis (Kanada)",
  "fr_CD": "Faransiis (Jamhuuriyadda Dimuquraadiga Kongo)",
  "fr_CF": "Faransiis (Jamhuuriyadda Afrikada Dhexe)",
  "fr_CG": "Faransiis (Kongo)",
  "fr_CH": "Faransiis (Swiiserlaand)",
  "fr_CI": "Faransiis (Ivory coast)",
  "fr_CM": "Faransiis (Kaameruun)",
  "fr_DJ": "Faransiis (Jabuuti)",
  "fr_DZ": "Faransiis (Aljeeriya)",
  "fr_FR": "Faransiis (Faransiis)",
  "fr_GA": "Faransiis (Gaaboon)",
  "fr_GF": "Faransiis (French Guiana)",
  "fr_GN": "Faransiis (Gini)",
  "fr_GP": "Faransiis (Guadeloupe)",
  "fr_GQ": "Faransiis (Equatorial Guinea)",
  "fr_HT": "Faransiis (Hayti)",
  "fr_KM": "Faransiis (Komooros)",
  "fr_LU": "Faransiis (Luksemboorg)",
  "fr_MA": "Faransiis (Marooko)",
  "fr_MC": "Faransiis (Moonako)",
  "fr_MF": "French (St. Martin)",
  "fr_MG": "Faransiis (Madagaskar)",
  "fr_ML": "Faransiis (Maali)",
  "fr_MQ": "Faransiis (Martinique)",
  "fr_MR": "Faransiis (Muritaaniya)",
  "fr_MU": "Faransiis (Murishiyoos)",
  "fr_NC": "Faransiis (New Caledonia)",
  "fr_NE": "Faransiis (Nayjer)",
  "fr_PF": "Faransiis (French Polynesia)",
  "fr_PM": "Faransiis (Saint Pierre and Miquelon)",
  "fr_RE": "Faransiis (Réunion)",
  "fr_RW": "Faransiis (Ruwanda)",
  "fr_SC": "Faransiis (Sishelis)",
  "fr_SN": "Faransiis (Sinigaal)",
  "fr_SY": "Faransiis (Suuriya)",
  "fr_TD": "Faransiis (Jaad)",
  "fr_TG": "Faransiis (Toogo)",
  "fr_TN": "Faransiis (Tuniisiya)",
  "fr_VU": "Faransiis (Vanuatu)",
  "fr_WF": "Faransiis (Wallis and Futuna)",
  "fr_YT": "Faransiis (Mayotte)",
  "frc": "Faransiiska Cajun",
  "frm": "Middle French",
  "fro": "Old French",
  "frp": "Arpitan",
  "frr": "Northern Frisian",
  "frs": "Eastern Frisian",
  "fur": "Firiyuuliyaan",
  "fy": "Firiisiyan Galbeed",
  "fy_NL": "Firiisiyan Galbeed (Netherlands)",
  "ga": "Ayrish",
  "ga_IE": "Irish (Ireland)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gbz": "Zoroastrian Dari",
  "gd": "Iskot Giilik",
  "gd_GB": "Scottish Gaelic (United Kingdom)",
  "gem": "Luqadda Jarmalka",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gl": "Galiisiyaan",
  "gl_ES": "Galician (Spain)",
  "glk": "Gilaki",
  "gmh": "Middle High German",
  "gn": "Guraani",
  "goh": "Old High German",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "Ancient Greek",
  "gsw": "Jarmal Iswiis",
  "gu": "Gujaraati",
  "gu_IN": "Gujarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Guusii",
  "gv": "Mankis",
  "gv_IM": "Manx (Isle of Man)",
  "gwi": "Gwichʼin",
  "ha": "Hawsa",
  "ha_GH": "Hawsa (Gaana)",
  "ha_Latn": "Hausa (Latin)",
  "ha_Latn_GH": "Hausa (Latin, Ghana)",
  "ha_Latn_NE": "Hausa (Latin, Niger)",
  "ha_Latn_NG": "Hausa (Latin, Nigeria)",
  "ha_NE": "Hawsa (Nayjer)",
  "ha_NG": "Hawsa (Nayjeeriya)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawaay",
  "he": "Cibraani",
  "he_IL": "Hebrew (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (Hindiya)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hittite",
  "hmn": "Hamong",
  "ho": "Hiri Motu",
  "hr": "Koro’eeshiyaan",
  "hr_BA": "Croatian (Bosnia & Herzegovina)",
  "hr_HR": "Croatian (Croatia)",
  "hsb": "Sorobiyaanka Sare",
  "hsn": "Xiang Chinese",
  "ht": "Heeytiyaan Karawle",
  "hu": "Hangariyaan",
  "hu_HU": "Hangariyaan (Hangeri)",
  "hup": "Hupa",
  "hy": "Armeeniyaan",
  "hy_AM": "Armenian (Armenia)",
  "hz": "Herero",
  "ia": "Interlinguwa",
  "iba": "Iban",
  "ibb": "Ibibio",
  "id": "Indunusiyaan",
  "id_ID": "Indunuusiyaan (Indoneesiya)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nayjeeriya)",
  "ii": "Sijuwan Yi",
  "ii_CN": "Sichuan Yi (China)",
  "ijo": "Ijo",
  "ik": "Inupiaq",
  "ilo": "Iloko",
  "inc": "Luqadda Ind",
  "ine": "Luuqada Indo-European",
  "inh": "Ingush",
  "io": "Ido",
  "ira": "Luuqada Iiraan",
  "iro": "Luqadda Iroquoian",
  "is": "Ayslandays",
  "is_IS": "Icelandic (Iceland)",
  "it": "Talyaani",
  "it_CH": "Talyaani (Swiiserlaand)",
  "it_IT": "Talyaani (Talyaani)",
  "it_SM": "Talyaani (San Marino)",
  "iu": "Inuktitut",
  "izh": "Ingrian",
  "ja": "Jabaaniis",
  "ja_JP": "Jabbaaniis (Jabaan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ingoomba",
  "jmc": "Chaga",
  "jpr": "Judeo-Persian",
  "jrb": "Judeo-Arabic",
  "jut": "Jutish",
  "jv": "Jafaaniis",
  "ka": "Joorijiyaan",
  "ka_GE": "Georgian (Georgia)",
  "kaa": "Kara-Kalpak",
  "kab": "Kabayle",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Kaamba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Kabardian",
  "kbl": "Kanembu",
  "kcg": "Tyap",
  "kde": "Kimakonde",
  "kea": "Kabuferdiyanu",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Kongo",
  "kgp": "Kaingang",
  "kha": "Khasi",
  "khi": "Luqadda Khoisan",
  "kho": "Khotanese",
  "khq": "Koyra Jiini",
  "khw": "Khowar",
  "ki": "Kikuuyu",
  "ki_KE": "Kikuyu (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Kasaaq",
  "kk_Cyrl": "Kazakh (Cyrillic)",
  "kk_Cyrl_KZ": "Kazakh (Cyrillic, Kazakhstan)",
  "kk_KZ": "Kazakh (Kazakhstan)",
  "kkj": "Kaako",
  "kl": "Kalaallisuut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjiin",
  "km": "Kamboodhian",
  "km_KH": "Kamboodhian (Kamboodiya)",
  "kmb": "Kimbundu",
  "kn": "Kannadays",
  "kn_IN": "Kannada (India)",
  "ko": "Kuuriyaan",
  "ko_KP": "Kuuriyaan (Kuuriyada Waqooyi)",
  "ko_KR": "Kuuriyaan (Kuuriyada Koonfureed)",
  "koi": "Komi-Permyak",
  "kok": "Konkani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Karelian",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Kaashmiir",
  "ks_Arab": "Kashmiri (Arabic)",
  "ks_Arab_IN": "Kashmiri (Arabic, India)",
  "ks_IN": "Kashmiri (India)",
  "ksb": "Shambaala",
  "ksf": "Bafiya",
  "ksh": "Kologniyaan",
  "ku": "Kurdishka",
  "kum": "Kumyk",
  "kut": "Kutenai",
  "kv": "Komi",
  "kw": "Kornish",
  "kw_GB": "Cornish (United Kingdom)",
  "ky": "Kirgiis",
  "ky_Cyrl": "Kyrgyz (Cyrillic)",
  "ky_Cyrl_KG": "Kyrgyz (Cyrillic, Kyrgyzstan)",
  "ky_KG": "Kyrgyz (Kyrgyzstan)",
  "la": "Laatiin",
  "lad": "Ladino",
  "lag": "Laangi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Luksaamboorgish",
  "lb_LU": "Luxembourgish (Luxembourg)",
  "lez": "Lezghian",
  "lfn": "Lingua Franca Nova",
  "lg": "Gandha",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limburgish",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Laakoota",
  "lmo": "Lombard",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Congo - Kinshasa)",
  "ln_CF": "Lingala (Central African Republic)",
  "ln_CG": "Lingala (Congo - Brazzaville)",
  "lo": "Lao",
  "lo_LA": "Lao (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Koonfurta Luuri",
  "lt": "Lituwaanays",
  "lt_LT": "Lithuanian (Lithuania)",
  "ltg": "Latgalian",
  "lu": "Luuba-kataanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lunda",
  "luo": "Luwada",
  "lus": "Mizo",
  "luy": "Luhya",
  "lv": "Laatfiyaan",
  "lv_LV": "Latvian (Latvia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madurese",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Dadka Maithili",
  "mak": "Makasar",
  "man": "Mandingo",
  "map": "Luqadda Austronesian",
  "mas": "Masaay",
  "mde": "Maba",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mer": "Meeru",
  "mfe": "Moorisayn",
  "mg": "Malagaasi",
  "mg_MG": "Malagasy (Madagascar)",
  "mga": "Middle Irish",
  "mgh": "Makhuwa",
  "mgo": "Meetaa",
  "mh": "Marshallese",
  "mi": "Maaoori",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mis": "Luqado kala duwan",
  "mk": "Masadooniyaan",
  "mk_MK": "Macedonian (Macedonia)",
  "mkh": "Luqadda Mon-Khmer",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mangooli",
  "mn_Cyrl": "Mongolian (Cyrillic)",
  "mn_Cyrl_MN": "Mongolian (Cyrillic, Mongolia)",
  "mn_MN": "Mongolian (Mongolia)",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "Luqadda Manobo",
  "mo": "Moldavian",
  "moh": "Mohawk",
  "mos": "Mossi",
  "mr": "Maarati",
  "mr_IN": "Marathi (India)",
  "mrj": "Western Mari",
  "ms": "Malaay",
  "ms_BN": "Malaay (Buruneeya)",
  "ms_Latn": "Malay (Latin)",
  "ms_Latn_BN": "Malay (Latin, Brunei)",
  "ms_Latn_MY": "Malay (Latin, Malaysia)",
  "ms_Latn_SG": "Malay (Latin, Singapore)",
  "ms_MY": "Malaay (Malaysia)",
  "ms_SG": "Malaay (Singaboor)",
  "mt": "Maltiis",
  "mt_MT": "Maltese (Malta)",
  "mua": "Miyundhaang",
  "mul": "Luuqado kala duwan",
  "mun": "Luqadda Munda",
  "mus": "Creek",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Burmese",
  "my_MM": "Burmese (Myanmar)",
  "mye": "Myene",
  "myn": "Luuqada Mayan",
  "myv": "Erzya",
  "mzn": "Masanderaani",
  "na": "Nauru",
  "nah": "Nahuatl",
  "nai": "Luuqada Hindida Waqooyiga Ameerika",
  "nan": "Min Nan Chinese",
  "nap": "Neapolitan",
  "naq": "Nama",
  "nb": "Noorwijiyaan Bokma",
  "nb_NO": "Norwegian Bokmål (Norway)",
  "nb_SJ": "Norwegian Bokmål (Svalbard & Jan Mayen)",
  "nd": "Indhebeele",
  "nd_ZW": "North Ndebele (Zimbabwe)",
  "nds": "Jarmal Hooseeya",
  "nds_NL": "Dutch-ka Saxon",
  "ne": "Nebaali",
  "ne_IN": "Nebaali (Hindiya)",
  "ne_NP": "Nebaali (Nebaal)",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Niger-Kordofanian Luqad",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Holandays",
  "nl_AW": "Holandays (Aruba)",
  "nl_BE": "Holandays (Biljam)",
  "nl_BQ": "Dutch (Caribbean Netherlands)",
  "nl_CW": "Dutch (Curaçao)",
  "nl_NL": "Holandays (Netherlands)",
  "nl_SR": "Holandays (Suriname)",
  "nl_SX": "Dutch (Sint Maarten)",
  "nmg": "Kuwaasiyo",
  "nn": "Nowrwejiyan (naynoroski)",
  "nn_NO": "Norwegian Nynorsk (Norway)",
  "nnh": "Ingiyembuun",
  "no": "Af Noorwiijiyaan",
  "no_NO": "Norwegian (Norway)",
  "nog": "Nogai",
  "non": "Old Norse",
  "nov": "Novial",
  "nqo": "NʼKo",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "nub": "Luqadda Nubiyanka",
  "nus": "Nuweer",
  "nv": "Navajo",
  "nwc": "Classical Newari",
  "ny": "Inyaanja",
  "nym": "Nyamwezi",
  "nyn": "Inyankoole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oc": "Okitaan",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Oodhiya",
  "or_IN": "Oriya (India)",
  "os": "Oseetic",
  "os_GE": "Ossetic (Georgia)",
  "os_RU": "Ossetic (Russia)",
  "osa": "Osage",
  "ota": "Ottoman Turkish",
  "oto": "Luuqada Otomia",
  "pa": "Bunjaabi",
  "pa_Arab": "Punjabi (Arabic)",
  "pa_Arab_PK": "Punjabi (Arabic, Pakistan)",
  "pa_Guru": "Punjabi (Gurmukhi)",
  "pa_Guru_IN": "Punjabi (Gurmukhi, India)",
  "pa_IN": "Bunjaabi (Hindiya)",
  "pa_PK": "Bunjaabi (Bakistaan)",
  "paa": "Luqadda Papuan",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pcd": "Picard",
  "pcm": "Nigerian Pidgin",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "Old Persian",
  "pfl": "Palatine German",
  "phi": "Luuqada Filibiin",
  "phn": "Phoenician",
  "pi": "Pali",
  "pl": "Boolish",
  "pl_PL": "Boolish (Booland)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "Pohnpeian",
  "pra": "Luuqada Prakrit",
  "prg": "Brashiyaanki Hore",
  "pro": "Old Provençal",
  "ps": "Bashtuu",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Boortaqiis",
  "pt_AO": "Boortaqiis (Angoola)",
  "pt_BR": "Boortaqiis (Braasiil)",
  "pt_CV": "Boortaqiis (Cape Verde Islands)",
  "pt_GW": "Boortaqiis (Gini-Bisaaw)",
  "pt_MO": "Portuguese (Macau SAR China)",
  "pt_MZ": "Boortaqiis (Musambiig)",
  "pt_PT": "Boortaqiis (Bortuqaal)",
  "pt_ST": "Boortaqiis (São Tomé and Príncipe)",
  "pt_TL": "Boortaqiis (Timorka bari)",
  "qu": "Quwejuwa",
  "qu_BO": "Quechua (Bolivia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Peru)",
  "quc": "Kʼicheʼ",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Romaanis",
  "rm_CH": "Romansh (Switzerland)",
  "rn": "Rundhi",
  "rn_BI": "Rundi (Burundi)",
  "ro": "Romanka",
  "ro_MD": "Romanka (Moldofa)",
  "ro_RO": "Romanka (Rumaaniya)",
  "roa": "Luqadda Jaceylka",
  "rof": "Rombo",
  "rom": "Romany",
  "root": "Xidid",
  "rtm": "Rotuman",
  "ru": "Ruush",
  "ru_BY": "Ruush (Belarus)",
  "ru_KG": "Ruush (Kirgistaan)",
  "ru_KZ": "Ruush (Kasaakhistaan)",
  "ru_MD": "Ruush (Moldofa)",
  "ru_RU": "Ruush (Ruush)",
  "ru_UA": "Ruush (Ukrayn)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromanian",
  "rw": "Ruwaandha",
  "rw_RW": "Rwanda (Ruwanda)",
  "rwk": "Raawa",
  "sa": "Sanskrit",
  "sad": "Sandawe",
  "sah": "Saaqa",
  "sai": "Afka Hindida Koonfurta Ameerika",
  "sal": "Luuqada Salishan",
  "sam": "Samaritan Aramaic",
  "saq": "Sambuuru",
  "sas": "Sasak",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambay",
  "sbp": "Sangu",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "sd": "Siindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sassarese Sardinian",
  "sdh": "Kurdiyiinta Koofureed",
  "se": "Koonfurta Saami",
  "se_FI": "Northern Sami (Finland)",
  "se_NO": "Northern Sami (Norway)",
  "se_SE": "Northern Sami (Sweden)",
  "see": "Seneca",
  "seh": "Seena",
  "sei": "Seri",
  "sel": "Selkup",
  "sem": "Luqadda Semitic",
  "ses": "Koyraboro Seenni",
  "sg": "Sango",
  "sg_CF": "Sango (Central African Republic)",
  "sga": "Old Irish",
  "sgn": "Luqadda Saxeexa",
  "sgs": "Samogitian",
  "sh": "Serbiyaan",
  "sh_BA": "Serbo-Croatian (Bosnia & Herzegovina)",
  "shi": "Shilha",
  "shi_Latn": "Shilha (Laatiin)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Chadian Arabic",
  "si": "Sinhaleys",
  "si_LK": "Sinhala (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Luqadda Siouan",
  "sit": "Luqadda Sino-Tibetan",
  "sk": "Isloofaak",
  "sk_SK": "Slovak (Slovakia)",
  "sl": "Islofeeniyaan",
  "sl_SI": "Slovenian (Slovenia)",
  "sla": "Luqadda Slavic",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "Samowan",
  "sma": "Southern Sami",
  "smi": "Luqadda Saami",
  "smj": "Lule Sami",
  "smn": "Inaari Saami",
  "sms": "Skolt Sami",
  "sn": "Shoona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninke",
  "so": "Soomaali",
  "so_DJ": "Soomaali (Jabuuti)",
  "so_ET": "Soomaali (Itoobiya)",
  "so_KE": "Soomaali (Kiiniya)",
  "so_SO": "Soomaali (Soomaaliya)",
  "sog": "Sogdien",
  "son": "Songhai",
  "sq": "Albeeniyaan",
  "sq_AL": "Albanian (Albania)",
  "sq_MK": "Albanian (Macedonia)",
  "sq_XK": "Albanian (Kosovo)",
  "sr": "Seerbiyaan",
  "sr_BA": "Serbian (Bosnia & Herzegovina)",
  "sr_Cyrl": "Serbian (Cyrillic)",
  "sr_Cyrl_BA": "Serbian (Cyrillic, Bosnia & Herzegovina)",
  "sr_Cyrl_ME": "Serbian (Cyrillic, Montenegro)",
  "sr_Cyrl_RS": "Serbian (Cyrillic, Serbia)",
  "sr_Cyrl_XK": "Serbian (Cyrillic, Kosovo)",
  "sr_Latn": "Serbian (Latin)",
  "sr_Latn_BA": "Serbian (Latin, Bosnia & Herzegovina)",
  "sr_Latn_ME": "Serbian (Latin, Montenegro)",
  "sr_Latn_RS": "Serbian (Latin, Serbia)",
  "sr_Latn_XK": "Serbian (Latin, Kosovo)",
  "sr_ME": "Serbian (Montenegro)",
  "sr_RS": "Serbian (Serbia)",
  "sr_XK": "Serbian (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serer",
  "ss": "Swati",
  "ssa": "Luqadda Salo-Saxaraha",
  "ssy": "Saho",
  "st": "Sesooto",
  "stq": "Saterland Frisian",
  "su": "Suudaaniis",
  "suk": "Sukuma",
  "sus": "Susu",
  "sux": "Sumerian",
  "sv": "Swiidhis",
  "sv_AX": "Swedish (Åland Islands)",
  "sv_FI": "Swiidhis (Finland)",
  "sv_SE": "Swiidhis (Iswidhan)",
  "sw": "Sawaaxili",
  "sw_CD": "Congo Sawaaxili",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comorian",
  "swc": "Congo Swahili",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Tamiil",
  "ta_IN": "Tamiil (Hindiya)",
  "ta_LK": "Tamiil (Sirilaanka)",
  "ta_MY": "Tamiil (Malaysia)",
  "ta_SG": "Tamiil (Singaboor)",
  "tai": "Luqadda Tai",
  "tcy": "Tulu",
  "te": "Teluugu",
  "te_IN": "Telugu (India)",
  "tem": "Timne",
  "teo": "Teeso",
  "ter": "Tereno",
  "tet": "Tetum",
  "tg": "Taajik",
  "th": "Taaylandays",
  "th_TH": "Taaylandays (Taylaand)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigre",
  "tiv": "Tiv",
  "tk": "Turkumaanish",
  "tkl": "Tokelau",
  "tkr": "Tsakhur",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Philippines)",
  "tlh": "Kiligoon",
  "tli": "Tlingit",
  "tly": "Talysh",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Toongan",
  "to_TO": "Tongan (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Turkish",
  "tr_CY": "Turkish (Qubrus)",
  "tr_TR": "Turkish (Turki)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsonga",
  "tsd": "Tsakonian",
  "tsi": "Tsimshian",
  "tt": "Taatar",
  "ttt": "Muslim Tat",
  "tum": "Tumbuka",
  "tup": "Luqadda Tupi",
  "tut": "Luqadda Altaic",
  "tvl": "Tuvalu",
  "tw": "Tiwiyan",
  "twq": "Tasaawaq",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "tzm": "Bartamaha Atlaas Tamasayt",
  "udm": "Udmurt",
  "ug": "Uighur",
  "ug_Arab": "Uyghur (Arabic)",
  "ug_Arab_CN": "Uyghur (Arabic, China)",
  "ug_CN": "Uyghur (China)",
  "uga": "Ugaritic",
  "uk": "Yukreeniyaan",
  "uk_UA": "Yukreeniyaan (Ukrayn)",
  "umb": "Umbundu",
  "und": "Af aan la aqoon ama aan sax ahayn",
  "ur": "Urduu",
  "ur_IN": "Urduu (Hindiya)",
  "ur_PK": "Urduu (Bakistaan)",
  "uz": "Usbakis",
  "uz_AF": "Uzbek (Afghanistan)",
  "uz_Arab": "Uzbek (Arabic)",
  "uz_Arab_AF": "Uzbek (Arabic, Afghanistan)",
  "uz_Cyrl": "Uzbek (Cyrillic)",
  "uz_Cyrl_UZ": "Uzbek (Cyrillic, Uzbekistan)",
  "uz_Latn": "Uzbek (Latin)",
  "uz_Latn_UZ": "Uzbek (Latin, Uzbekistan)",
  "uz_UZ": "Uzbek (Uzbekistan)",
  "vai": "Faayi",
  "vai_Latn": "Vai (Laatiin)",
  "ve": "Venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "Fiitnaamays",
  "vi_VN": "Fiitnaamays (Fiyetnaam)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "Folabuuk",
  "vot": "Votic",
  "vro": "Võro",
  "vun": "Fuunjo",
  "wa": "Walloon",
  "wae": "Walseer",
  "wak": "Luuqada Wakashan",
  "wal": "Wolaytta",
  "war": "Waray",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Luqadda Sorbian",
  "wo": "Woolof",
  "wuu": "Wu Chinese",
  "xal": "Kalmyk",
  "xh": "Hoosta",
  "xmf": "Mingrelian",
  "xog": "Sooga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Yaangbeen",
  "ybb": "Yemba",
  "yi": "Yadhish",
  "yo": "Yoruuba",
  "yo_BJ": "Yoruuba (Biniin)",
  "yo_NG": "Yoruuba (Nayjeeriya)",
  "ypk": "Luqadda Yupik",
  "yrl": "Nheengatu",
  "yue": "Kantoneese",
  "yue_Hans": "Kantonese (Shiinees Fudud)",
  "yue_Hant": "Kantonese (Shiine Dhaqameed)",
  "za": "Zhuang",
  "zap": "Zapotec",
  "zbl": "Blissymbols",
  "zea": "Zeelandic",
  "zen": "Zenaga",
  "zgh": "Morokaanka Tamasayt Rasmiga",
  "zh": "Shiinaha Mandarin",
  "zh_CN": "Jayniis (Shiinaha)",
  "zh_HK": "Chinese (Hong Kong SAR China)",
  "zh_Hans": "Shiinaha Rasmiga ah",
  "zh_Hans_CN": "Chinese (Simplified, China)",
  "zh_Hans_HK": "Chinese (Simplified, Hong Kong SAR China)",
  "zh_Hans_MO": "Chinese (Simplified, Macau SAR China)",
  "zh_Hans_SG": "Chinese (Simplified, Singapore)",
  "zh_Hant": "Shiinahii Hore",
  "zh_Hant_HK": "Chinese (Traditional, Hong Kong SAR China)",
  "zh_Hant_MO": "Chinese (Traditional, Macau SAR China)",
  "zh_Hant_TW": "Chinese (Traditional, Taiwan)",
  "zh_MO": "Chinese (Macau SAR China)",
  "zh_SG": "Jayniis (Singaboor)",
  "zh_TW": "Jayniis (Taywaan)",
  "znd": "Zande",
  "zu": "Zuulu",
  "zu_ZA": "Zuulu (Koonfur Afrika)",
  "zun": "Zuni",
  "zxx": "Luuqad Looma Hayo",
  "zza": "Zaza"
};
