const names = {
  "001": "Cîhan",
  "002": "Afrîka",
  "003": "Amerîkaya Bakur",
  "005": "Amerîkaya Başûr",
  "009": "Okyanûsya",
  "011": "Afrîkaya Rojava",
  "013": "Amerîkaya Navîn",
  "014": "Afrîkaya Rojhilat",
  "015": "Afrîkaya Bakur",
  "017": "Afrîkaya Navîn",
  "018": "Afrîkaya Başûr",
  "019": "Amerîka",
  "021": "Amerîkaya Bakur",
  "029": "Karîb",
  "030": "Rojhilata Asya",
  "034": "Asya Başûr",
  "035": "Başûrê Asya",
  "039": "Ewropaya Başûr",
  "053": "Awistralasya",
  "054": "Melanezya",
  "057": "Herêma Mîkronezya",
  "061": "Polînezya",
  "062": "Asya Başûr-Navîn",
  "142": "Asya",
  "143": "Asyaya Navîn",
  "145": "Asya rojava",
  "150": "Ewropa",
  "151": "Ewropaya Rojhilat",
  "154": "Ewropaya Bakur",
  "155": "Ewropaya Rojava",
  "172": "Hevpeymaniya Dewletên Serbixwe",
  "200": "Çêkoslovakya",
  "202": "Afrîkaya Bin-Saharî",
  "419": "Amerîkaya Latînî",
  "830": "Giravên Kanalê",
  "AC": "Girava Hilkişînê",
  "AD": "Andorra",
  "AE": "Emîrtiyên Erebî yên Yekbûyî",
  "AF": "Efxanistan",
  "AG": "Antîgua û Berbûda",
  "AI": "Anguilla",
  "AL": "Albanya",
  "AM": "Ermenistan",
  "AN": "Antilles Hollanda",
  "AO": "Angola",
  "AQ": "Antarktîka",
  "AR": "Arjentîn",
  "AS": "Samoaya Amerîkanî",
  "AT": "Awistirya",
  "AU": "Awistralya",
  "AW": "Arûba",
  "AX": "Åland Islands",
  "AZ": "Azerbaycan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Kafkasya Albanî",
  "Ahom": "Ahom",
  "Arab": "erebî",
  "Aran": "Nastaliq",
  "Armi": "Permraliya Aramî",
  "Armn": "ermenî",
  "Avst": "Avestan",
  "BA": "Bosniya û Herzegovîna",
  "BB": "Barbados",
  "BD": "Bangladeş",
  "BE": "Belçîka",
  "BF": "Burkîna Faso",
  "BG": "Bulgaristan",
  "BH": "Behreyn",
  "BI": "Burundî",
  "BJ": "Bênîn",
  "BL": "Saint-Barthélemy",
  "BM": "Bermûda",
  "BN": "Brûney",
  "BO": "Bolîvya",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazîl",
  "BS": "Bahama",
  "BT": "Bûtan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarûs",
  "BZ": "Belîze",
  "Bali": "Balînî",
  "Bamu": "Bamum",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "bengalî",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braîlî",
  "Bugi": "Buginese",
  "Buhd": "Buhid",
  "CA": "Kanada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Kongo - Kînşasa",
  "CF": "Komara Afrîkaya Navend",
  "CG": "Kongo - Brazzaville",
  "CH": "Swîsre",
  "CI": "Peravê Diranfîl",
  "CK": "Giravên Cook",
  "CL": "Şîle",
  "CM": "Kamerûn",
  "CN": "Çîn",
  "CO": "Kolombiya",
  "CP": "Girava Clipperton",
  "CR": "Kosta Rîka",
  "CS": "Serbia û Montenegro",
  "CU": "Kûba",
  "CV": "Kap Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Kîpros",
  "CZ": "Çekya",
  "Cakm": "Çakma",
  "Cans": "Syllabics Aboriginal Canadian yekbûyî",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Çerokî",
  "Chrs": "Xorasmî",
  "Cirt": "Jidayikbûn",
  "Copt": "Koptî",
  "Cprt": "Qibrisî",
  "Cyrl": "kirîlî",
  "Cyrs": "Kirîlî ya Slavî ya Dêrê ya Kevn",
  "DD": "Almanyaya Rojhilat",
  "DE": "Almanya",
  "DG": "Diego Garcia",
  "DJ": "Cîbûtî",
  "DK": "Danîmarka",
  "DM": "Domînîka",
  "DO": "Komara Domînîk",
  "DZ": "Cezayir",
  "Deva": "devanagarî",
  "Diak": "Dive Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Kurtenivîsa Duployan",
  "EA": "Ceuta & Melilla",
  "EC": "Ekuador",
  "EE": "Estonya",
  "EG": "Misir",
  "EH": "Sahraya Rojava",
  "ER": "Erîtrea",
  "ES": "Spanya",
  "ET": "Etiyopya",
  "EU": "Yekîtiya Ewropayê",
  "EZ": "Ewrûpa",
  "Egyd": "Demotîkî Misirî",
  "Egyh": "Hieratîk Misirî",
  "Egyp": "Hieroglîfên Misirî",
  "Elba": "Elbasan",
  "Elym": "Elymaic",
  "Ethi": "Etiyopîk",
  "FI": "Fînlenda",
  "FJ": "Fîjî",
  "FK": "Giravên Malvîn",
  "FM": "Mîkronezya",
  "FO": "Giravên Feroe",
  "FR": "Fransa",
  "FX": "Metropolitan France",
  "GA": "Gabon",
  "GB": "Keyaniya Yekbûyî",
  "GD": "Grenada",
  "GE": "Gurcistan",
  "GF": "Guyanaya Fransî",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Cîbraltar",
  "GL": "Grînlenda",
  "GM": "Gambiya",
  "GN": "Gîne",
  "GP": "Guadeloupe",
  "GQ": "Gîneya Rojbendî",
  "GR": "Yewnanistan",
  "GS": "South Georgia & South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Gîne-Bissau",
  "GY": "Guyana",
  "Geok": "Xutsuri Gurcî",
  "Geor": "gurcî",
  "Glag": "Glagolîtîk",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gotikî",
  "Gran": "Grantha",
  "Grek": "yewnanî",
  "Gujr": "Gujaratî",
  "Guru": "Gurmukhi",
  "HK": "Hong Kong SAR China",
  "HM": "Heard & McDonald Islands",
  "HN": "Hondûras",
  "HR": "Kroatya",
  "HT": "Haîtî",
  "HU": "Macaristan",
  "Hanb": "Han bi Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "sadekirî",
  "Hant": "kevneşopî",
  "Hatr": "Hatran",
  "Hebr": "Îbranî",
  "Hira": "Hiragana",
  "Hluw": "Hieroglîfên Anatoliyê",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Silavnameyên Japonî",
  "Hung": "Old Hungarian",
  "IC": "Giravên Qenariyê",
  "ID": "Îndonezya",
  "IE": "Îrlenda",
  "IL": "Îsraêl",
  "IM": "Girava Man",
  "IN": "Hindistan",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Îran",
  "IS": "Îslenda",
  "IT": "Îtalya",
  "Inds": "Usndus",
  "Ital": "Kevn Italtalî",
  "JE": "Jersey",
  "JM": "Jamaîka",
  "JO": "Urdun",
  "JP": "Japon",
  "Jamo": "Jamo",
  "Java": "Javanesî",
  "Jpan": "japonî",
  "Jurc": "Jurchen",
  "KE": "Kenya",
  "KG": "Qirgizistan",
  "KH": "Kamboca",
  "KI": "Kirîbatî",
  "KM": "Komor",
  "KN": "Saint Kitts û Nevîs",
  "KP": "Korêya Bakur",
  "KR": "Korêya Başûr",
  "KW": "Kuweyt",
  "KY": "Giravên Kaymanê",
  "KZ": "Qazaxistan",
  "Kali": "Kayah Li",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "ximêrî",
  "Khoj": "Khojki",
  "Kits": "Khitan nivîsara piçûk",
  "Knda": "Kanadayî",
  "Kore": "koreyî",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Libnan",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Srî Lanka",
  "LR": "Lîberya",
  "LS": "Lesoto",
  "LT": "Lîtvanya",
  "LU": "Lûksembûrg",
  "LV": "Letonya",
  "LY": "Lîbya",
  "Lana": "Lanna",
  "Laoo": "Laoyî",
  "Latf": "Fraktur Latînî",
  "Latg": "Gaelic Latin",
  "Latn": "latînî",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Linear A",
  "Linb": "Hêl B",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydian",
  "MA": "Maroko",
  "MC": "Monako",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "MF",
  "MG": "Madagaskar",
  "MH": "Giravên Marşal",
  "MI": "Giravên Midway",
  "MK": "Makedonya",
  "ML": "Malî",
  "MM": "Myanmar (Birmanya)",
  "MN": "Mongolya",
  "MO": "Macao SAR China",
  "MP": "Giravên Bakurê Marianan",
  "MQ": "Martinique",
  "MR": "Morîtanya",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Maurîtius",
  "MV": "Maldîv",
  "MW": "Malawî",
  "MX": "Meksîk",
  "MY": "Malezya",
  "MZ": "Mozambîk",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Manî",
  "Marc": "Marchen",
  "Mong": "mongolî",
  "NA": "Namîbya",
  "NC": "Kaledonyaya Nû",
  "NE": "Nîjer",
  "NF": "Girava Norfolk",
  "NG": "Nîjerya",
  "NI": "Nîkaragua",
  "NL": "Holenda",
  "NO": "Norwêc",
  "NP": "Nepal",
  "NR": "Naûrû",
  "NU": "Niûe",
  "NZ": "Nû Zelenda",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Perû",
  "PF": "Polînezyaya Fransî",
  "PG": "Papua Gîneya Nû",
  "PH": "Filîpîn",
  "PK": "Pakistan",
  "PL": "Polonya",
  "PM": "Saint-Pierre û Miquelon",
  "PN": "Giravên Pitcairn",
  "PR": "Porto Rîko",
  "PS": "Xakên filistînî",
  "PT": "Portûgal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qeter",
  "RE": "Réunion",
  "RO": "Romanya",
  "RS": "Serbistan",
  "RU": "Rûsya",
  "RW": "Rwanda",
  "SA": "Erebistana Siyûdî",
  "SB": "Giravên Salomon",
  "SC": "Seyşel",
  "SD": "Sûdan",
  "SE": "Swêd",
  "SG": "Singapûr",
  "SH": "St. Helena",
  "SI": "Slovenya",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Slovakya",
  "SL": "Sierra Leone",
  "SM": "San Marîno",
  "SN": "Senegal",
  "SO": "Somalya",
  "SR": "Sûrînam",
  "SS": "Sûdana Başûr",
  "ST": "Sao Tome û Prînsîpe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Sûrî",
  "SZ": "Swazîlenda",
  "TC": "Giravên Turk û Kaîkos",
  "TD": "Çad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Taylenda",
  "TJ": "Tacîkistan",
  "TK": "Tokelau",
  "TL": "Tîmora-Leste",
  "TM": "Tirkmenistan",
  "TN": "Tûnis",
  "TO": "Tonga",
  "TR": "Tirkiye",
  "TT": "Trînîdad û Tobago",
  "TV": "Tûvalû",
  "TW": "Taywan",
  "TZ": "Tanzanya",
  "Tibt": "tîbetî",
  "UA": "Ûkrayna",
  "UG": "Ûganda",
  "UM": "U.S. Outlying Islands",
  "UN": "Neteweyên Yekbûyî",
  "US": "Dewletên Yekbûyî yên Amerîkayê",
  "UY": "Ûrûguay",
  "UZ": "Ûzbêkistan",
  "VA": "Vatîkan",
  "VC": "Saint Vincent û Giravên Grenadîn",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Viyetnam",
  "VU": "Vanûatû",
  "WF": "Wallis û Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "Afrîkaya Başûr",
  "ZM": "Zambiya",
  "ZW": "Zîmbabwe",
  "Zsym": "sembol",
  "Zxxx": "ne nivîsandî",
  "Zyyy": "hevpar",
  "Zzzz": "nivîsa nenas",
  "aa": "afarî",
  "ab": "abxazî",
  "ace": "açehî",
  "ady": "adîgeyî",
  "af": "afrîkansî",
  "ain": "aynuyî",
  "ale": "alêwîtî",
  "am": "amharî",
  "an": "aragonî",
  "ar": "erebî",
  "ar_001": "erebiya standard",
  "as": "asamî",
  "ast": "astûrî",
  "av": "avarî",
  "ay": "aymarayî",
  "az": "azerî",
  "ba": "başkîrî",
  "ban": "balînî",
  "be": "belarusî",
  "bem": "bembayî",
  "bg": "bulgarî",
  "bho": "bojpûrî",
  "bi": "bîslamayî",
  "bla": "blakfotî",
  "bm": "bambarayî",
  "bn": "bengalî",
  "bo": "tîbetî",
  "br": "bretonî",
  "bs": "bosnî",
  "bug": "bugî",
  "ca": "katalanî",
  "ce": "çeçenî",
  "ceb": "sebwanoyî",
  "ch": "çamoroyî",
  "chk": "çûkî",
  "chm": "marî",
  "chr": "çerokî",
  "chy": "çeyenî",
  "ckb": "soranî",
  "co": "korsîkayî",
  "cs": "çekî",
  "cv": "çuvaşî",
  "cy": "weylsî",
  "da": "danmarkî",
  "de": "elmanî",
  "dsb": "sorbiya jêrîn",
  "dua": "diwalayî",
  "dv": "divehî",
  "dz": "conxayî",
  "ee": "eweyî",
  "el": "yewnanî",
  "en": "îngilîzî",
  "eo": "esperantoyî",
  "es": "spanî",
  "et": "estonî",
  "eu": "baskî",
  "fa": "farisî",
  "ff": "fulahî",
  "fi": "fînî",
  "fil": "fîlîpînoyî",
  "fj": "fîjî",
  "fo": "ferî",
  "fr": "frensî",
  "fur": "friyolî",
  "fy": "frîsî",
  "ga": "îrî",
  "gd": "gaelîka skotî",
  "gil": "kîrîbatî",
  "gl": "galîsî",
  "gn": "guwaranî",
  "gor": "gorontaloyî",
  "gsw": "elmanîşî",
  "gu": "gujaratî",
  "gv": "manksî",
  "ha": "hawsayî",
  "haw": "hawayî",
  "he": "îbranî",
  "hi": "hindî",
  "hil": "hîlîgaynonî",
  "hr": "xirwatî",
  "hsb": "sorbiya jorîn",
  "ht": "haîtî",
  "hu": "mecarî",
  "hy": "ermenî",
  "hz": "hereroyî",
  "ia": "interlingua",
  "id": "indonezî",
  "ig": "îgboyî",
  "ilo": "îlokanoyî",
  "inh": "îngûşî",
  "io": "îdoyî",
  "is": "îzlendî",
  "it": "îtalî",
  "iu": "înuîtî",
  "ja": "japonî",
  "jbo": "lojbanî",
  "jv": "javayî",
  "ka": "gurcî",
  "kab": "kabîlî",
  "kea": "kapverdî",
  "kk": "qazaxî",
  "kl": "kalalîsûtî",
  "km": "ximêrî",
  "kn": "kannadayî",
  "ko": "koreyî",
  "kok": "konkanî",
  "ks": "keşmîrî",
  "ksh": "rîpwarî",
  "ku": "kurdî",
  "kv": "komî",
  "kw": "kornî",
  "ky": "kirgizî",
  "lad": "ladînoyî",
  "lb": "luksembûrgî",
  "lez": "lezgînî",
  "lg": "lugandayî",
  "li": "lîmbûrgî",
  "lkt": "lakotayî",
  "ln": "lingalayî",
  "lo": "lawsî",
  "lrc": "luriya bakur",
  "lt": "lîtwanî",
  "lv": "latviyayî",
  "mad": "madurayî",
  "mas": "masayî",
  "mdf": "mokşayî",
  "mg": "malagasî",
  "mh": "marşalî",
  "mi": "maorî",
  "mic": "mîkmakî",
  "min": "mînangkabawî",
  "mk": "makedonî",
  "ml": "malayalamî",
  "mn": "mongolî",
  "moh": "mohawkî",
  "mr": "maratî",
  "ms": "malezî",
  "mt": "maltayî",
  "my": "burmayî",
  "myv": "erzayî",
  "mzn": "mazenderanî",
  "na": "nawrûyî",
  "nap": "napolîtanî",
  "nb": "norwecî (bokmål)",
  "ne": "nepalî",
  "niu": "nîwî",
  "nl": "holendî",
  "nl_BE": "flamî",
  "nn": "norwecî (nynorsk)",
  "nso": "sotoyiya bakur",
  "nv": "navajoyî",
  "oc": "oksîtanî",
  "om": "oromoyî",
  "or": "oriyayî",
  "os": "osetî",
  "pa": "puncabî",
  "pam": "kapampanganî",
  "pap": "papyamentoyî",
  "pau": "palawî",
  "pl": "polonî",
  "prg": "prûsyayî",
  "ps": "peştûyî",
  "pt": "portugalî",
  "qu": "keçwayî",
  "rap": "rapanuyî",
  "rar": "rarotongî",
  "rm": "romancî",
  "ro": "romanî",
  "ru": "rusî",
  "rup": "aromanî",
  "rw": "kînyariwandayî",
  "sa": "sanskrîtî",
  "sc": "sardînî",
  "scn": "sicîlî",
  "sco": "skotî",
  "sd": "sindhî",
  "se": "samiya bakur",
  "si": "kîngalî",
  "sk": "slovakî",
  "sl": "slovenî",
  "sm": "samoayî",
  "smn": "samiya înarî",
  "sn": "şonayî",
  "so": "somalî",
  "sq": "elbanî",
  "sr": "sirbî",
  "srn": "sirananî",
  "ss": "swazî",
  "st": "sotoyiya başûr",
  "su": "sundanî",
  "sv": "swêdî",
  "sw": "swahîlî",
  "swb": "komorî",
  "syr": "siryanî",
  "ta": "tamîlî",
  "te": "telûgûyî",
  "tet": "tetûmî",
  "tg": "tacikî",
  "th": "tayî",
  "ti": "tigrînî",
  "tk": "tirkmenî",
  "tlh": "klîngonî",
  "tn": "tswanayî",
  "to": "tongî",
  "tpi": "tokpisinî",
  "tr": "tirkî",
  "trv": "tarokoyî",
  "ts": "tsongayî",
  "tt": "teterî",
  "tum": "tumbukayî",
  "tvl": "tuvalûyî",
  "ty": "tahîtî",
  "tzm": "temazîxtî",
  "udm": "udmurtî",
  "ug": "oygurî",
  "uk": "ukraynî",
  "und": "zimanê nenas",
  "ur": "urdûyî",
  "uz": "ozbekî",
  "vi": "viyetnamî",
  "vo": "volapûkî",
  "wa": "walonî",
  "war": "warayî",
  "wo": "wolofî",
  "xh": "xosayî",
  "yi": "yidîşî",
  "yo": "yorubayî",
  "yue": "kantonî",
  "zh": "çînî",
  "zh_Hans": "çîniya sadekirî",
  "zh_Hant": "çîniya kevneşopî",
  "zu": "zuluyî",
  "zza": "zazakî"
};
