const names = {
  "001": "Mundo",
  "002": "África",
  "003": "América do Norte",
  "005": "América do Sul",
  "009": "Oceania",
  "011": "África Ocidental",
  "013": "América Central",
  "014": "África Oriental",
  "015": "África do Norte",
  "017": "África Central",
  "018": "África Meridional",
  "019": "Américas",
  "021": "América Setentrional",
  "029": "Caribe",
  "030": "Ásia Oriental",
  "034": "Ásia Meridional",
  "035": "Sudeste Asiático",
  "039": "Europa Meridional",
  "053": "Australásia",
  "054": "Melanésia",
  "057": "Região da Micronésia",
  "061": "Polinésia",
  "142": "Ásia",
  "143": "Ásia Central",
  "145": "Ásia Ocidental",
  "150": "Europa",
  "151": "Europa Oriental",
  "154": "Europa Setentrional",
  "155": "Europa Ocidental",
  "202": "África Subsaariana",
  "419": "América Latina",
  "AC": "Ilha de Ascensão",
  "AD": "Andorra",
  "AE": "Emirados Árabes Unidos",
  "AF": "Afeganistão",
  "AG": "Antígua e Barbuda",
  "AI": "Anguila",
  "AL": "Albânia",
  "AM": "Armênia",
  "AN": "Antilhas Holandesas",
  "AO": "Angola",
  "AQ": "Antártida",
  "AR": "Argentina",
  "AS": "Samoa Americana",
  "AT": "Áustria",
  "AU": "Austrália",
  "AW": "Aruba",
  "AX": "Ilhas Aland",
  "AZ": "Azerbaijão",
  "Arab": "árabe",
  "Aran": "nastaliq",
  "Armi": "armi",
  "Armn": "armênio",
  "Avst": "avéstico",
  "BA": "Bósnia e Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Bélgica",
  "BF": "Burquina Faso",
  "BG": "Bulgária",
  "BH": "Bahrein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "São Bartolomeu",
  "BM": "Bermudas",
  "BN": "Brunei",
  "BO": "Bolívia",
  "BQ": "Países Baixos Caribenhos",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Butão",
  "BV": "Ilha Bouvet",
  "BW": "Botsuana",
  "BY": "Bielorrússia",
  "BZ": "Belize",
  "Bali": "balinês",
  "Bamu": "bamum",
  "Batk": "bataque",
  "Beng": "bengali",
  "Blis": "símbolos bliss",
  "Bopo": "bopomofo",
  "Brah": "brahmi",
  "Brai": "braille",
  "Bugi": "buginês",
  "Buhd": "buhid",
  "CA": "Canadá",
  "CC": "Ilhas Cocos (Keeling)",
  "CD": "Congo - Kinshasa",
  "CF": "República Centro-Africana",
  "CG": "República do Congo",
  "CH": "Suíça",
  "CI": "Costa do Marfim",
  "CK": "Ilhas Cook",
  "CL": "Chile",
  "CM": "Camarões",
  "CN": "China",
  "CO": "Colômbia",
  "CP": "Ilha de Clipperton",
  "CR": "Costa Rica",
  "CS": "Sérvia e Montenegro",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Ilha Christmas",
  "CY": "Chipre",
  "CZ": "Tchéquia",
  "Cakm": "cakm",
  "Cans": "escrita silábica unificada dos aborígenes canadenses",
  "Cari": "cariano",
  "Cham": "cham",
  "Cher": "cherokee",
  "Cirt": "cirth",
  "Copt": "cóptico",
  "Cprt": "cipriota",
  "Cyrl": "cirílico",
  "Cyrs": "cirílico eslavo eclesiástico",
  "DE": "Alemanha",
  "DG": "Diego Garcia",
  "DJ": "Djibuti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Argélia",
  "Deva": "devanágari",
  "Dsrt": "deseret",
  "EA": "Ceuta e Melilla",
  "EC": "Equador",
  "EE": "Estônia",
  "EG": "Egito",
  "EH": "Saara Ocidental",
  "ER": "Eritreia",
  "ES": "Espanha",
  "ET": "Etiópia",
  "EU": "União Europeia",
  "EZ": "zona do euro",
  "Egyd": "demótico egípcio",
  "Egyh": "hierático egípcio",
  "Egyp": "hieróglifos egípcios",
  "Ethi": "etiópico",
  "FI": "Finlândia",
  "FJ": "Fiji",
  "FK": "Ilhas Malvinas",
  "FM": "Micronésia",
  "FO": "Ilhas Faroe",
  "FR": "França",
  "GA": "Gabão",
  "GB": "Reino Unido",
  "GD": "Granada",
  "GE": "Geórgia",
  "GF": "Guiana Francesa",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Gibraltar",
  "GL": "Groenlândia",
  "GM": "Gâmbia",
  "GN": "Guiné",
  "GP": "Guadalupe",
  "GQ": "Guiné Equatorial",
  "GR": "Grécia",
  "GS": "Ilhas Geórgia do Sul e Sandwich do Sul",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guiné-Bissau",
  "GY": "Guiana",
  "Geok": "khutsuri georgiano",
  "Geor": "georgiano",
  "Glag": "glagolítico",
  "Goth": "gótico",
  "Grek": "grego",
  "Gujr": "guzerate",
  "Guru": "gurmuqui",
  "HK": "Hong Kong, RAE da China",
  "HM": "Ilhas Heard e McDonald",
  "HN": "Honduras",
  "HR": "Croácia",
  "HT": "Haiti",
  "HU": "Hungria",
  "Hanb": "hanb",
  "Hang": "hangul",
  "Hani": "han",
  "Hano": "hanunoo",
  "Hans": "simplificado",
  "Hant": "tradicional",
  "Hebr": "hebraico",
  "Hira": "hiragana",
  "Hmng": "pahawh hmong",
  "Hrkt": "silabários japoneses",
  "Hung": "húngaro antigo",
  "IC": "Ilhas Canárias",
  "ID": "Indonésia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Ilha de Man",
  "IN": "Índia",
  "IO": "Território Britânico do Oceano Índico",
  "IQ": "Iraque",
  "IR": "Irã",
  "IS": "Islândia",
  "IT": "Itália",
  "Inds": "indo",
  "Ital": "itálico antigo",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordânia",
  "JP": "Japão",
  "Jamo": "jamo",
  "Java": "javanês",
  "Jpan": "japonês",
  "KE": "Quênia",
  "KG": "Quirguistão",
  "KH": "Camboja",
  "KI": "Quiribati",
  "KM": "Comores",
  "KN": "São Cristóvão e Névis",
  "KP": "Coreia do Norte",
  "KR": "Coreia do Sul",
  "KW": "Kuwait",
  "KY": "Ilhas Cayman",
  "KZ": "Cazaquistão",
  "Kali": "kayah li",
  "Kana": "katakana",
  "Khar": "kharoshthi",
  "Khmr": "khmer",
  "Knda": "kannada",
  "Kore": "coreano",
  "Kthi": "kthi",
  "LA": "Laos",
  "LB": "Líbano",
  "LC": "Santa Lúcia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Libéria",
  "LS": "Lesoto",
  "LT": "Lituânia",
  "LU": "Luxemburgo",
  "LV": "Letônia",
  "LY": "Líbia",
  "Lana": "lanna",
  "Laoo": "lao",
  "Latf": "latim fraktur",
  "Latg": "latim gaélico",
  "Latn": "latim",
  "Lepc": "lepcha",
  "Limb": "limbu",
  "Lina": "linear A",
  "Linb": "linear B",
  "Lisu": "lisu",
  "Lyci": "lício",
  "Lydi": "lídio",
  "MA": "Marrocos",
  "MC": "Mônaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "São Martinho",
  "MG": "Madagascar",
  "MH": "Ilhas Marshall",
  "MK": "Macedônia do Norte",
  "ML": "Mali",
  "MM": "Mianmar (Birmânia)",
  "MN": "Mongólia",
  "MO": "Macau, RAE da China",
  "MP": "Ilhas Marianas do Norte",
  "MQ": "Martinica",
  "MR": "Mauritânia",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Maurício",
  "MV": "Maldivas",
  "MW": "Malaui",
  "MX": "México",
  "MY": "Malásia",
  "MZ": "Moçambique",
  "Mand": "mandaico",
  "Mani": "maniqueano",
  "Maya": "hieróglifos maias",
  "Merc": "meroítico cursivo",
  "Mero": "meroítico",
  "Mlym": "malaiala",
  "Mong": "mongol",
  "Moon": "moon",
  "Mtei": "meitei mayek",
  "Mymr": "birmanês",
  "NA": "Namíbia",
  "NC": "Nova Caledônia",
  "NE": "Níger",
  "NF": "Ilha Norfolk",
  "NG": "Nigéria",
  "NI": "Nicarágua",
  "NL": "Países Baixos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nova Zelândia",
  "Nkoo": "n’ko",
  "OM": "Omã",
  "Ogam": "ogâmico",
  "Olck": "ol chiki",
  "Orkh": "orkhon",
  "Orya": "oriá",
  "Osma": "osmania",
  "PA": "Panamá",
  "PE": "Peru",
  "PF": "Polinésia Francesa",
  "PG": "Papua-Nova Guiné",
  "PH": "Filipinas",
  "PK": "Paquistão",
  "PL": "Polônia",
  "PM": "São Pedro e Miquelão",
  "PN": "Ilhas Pitcairn",
  "PR": "Porto Rico",
  "PS": "Territórios palestinos",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguai",
  "Perm": "pérmico antigo",
  "Phag": "phags-pa",
  "Phli": "phli",
  "Phlp": "phlp",
  "Phlv": "pahlavi antigo",
  "Phnx": "fenício",
  "Plrd": "fonético pollard",
  "Prti": "prti",
  "QA": "Catar",
  "QO": "Oceania Remota",
  "Qaag": "zawgyi",
  "RE": "Reunião",
  "RO": "Romênia",
  "RS": "Sérvia",
  "RU": "Rússia",
  "RW": "Ruanda",
  "Rjng": "rejang",
  "Roro": "rongorongo",
  "Runr": "rúnico",
  "SA": "Arábia Saudita",
  "SB": "Ilhas Salomão",
  "SC": "Seicheles",
  "SD": "Sudão",
  "SE": "Suécia",
  "SG": "Singapura",
  "SH": "Santa Helena",
  "SI": "Eslovênia",
  "SJ": "Svalbard e Jan Mayen",
  "SK": "Eslováquia",
  "SL": "Serra Leoa",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somália",
  "SR": "Suriname",
  "SS": "Sudão do Sul",
  "ST": "São Tomé e Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Síria",
  "SZ": "Essuatíni",
  "Samr": "samaritano",
  "Sara": "sarati",
  "Saur": "saurashtra",
  "Sgnw": "signwriting",
  "Shaw": "shaviano",
  "Sinh": "cingalês",
  "Sund": "sundanês",
  "Sylo": "syloti nagri",
  "Syrc": "siríaco",
  "Syre": "siríaco estrangelo",
  "Syrj": "siríaco ocidental",
  "Syrn": "siríaco oriental",
  "TA": "Tristão da Cunha",
  "TC": "Ilhas Turcas e Caicos",
  "TD": "Chade",
  "TF": "Territórios Franceses do Sul",
  "TG": "Togo",
  "TH": "Tailândia",
  "TJ": "Tadjiquistão",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turcomenistão",
  "TN": "Tunísia",
  "TO": "Tonga",
  "TR": "Turquia",
  "TT": "Trinidad e Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzânia",
  "Tagb": "tagbanwa",
  "Tale": "tai Le",
  "Talu": "novo tai lue",
  "Taml": "tâmil",
  "Tavt": "tavt",
  "Telu": "télugo",
  "Teng": "tengwar",
  "Tfng": "tifinagh",
  "Tglg": "tagalo",
  "Thaa": "thaana",
  "Thai": "tailandês",
  "Tibt": "tibetano",
  "UA": "Ucrânia",
  "UG": "Uganda",
  "UM": "Ilhas Menores Distantes dos EUA",
  "UN": "Nações Unidas",
  "US": "Estados Unidos",
  "UY": "Uruguai",
  "UZ": "Uzbequistão",
  "Ugar": "ugarítico",
  "VA": "Cidade do Vaticano",
  "VC": "São Vicente e Granadinas",
  "VE": "Venezuela",
  "VG": "Ilhas Virgens Britânicas",
  "VI": "Ilhas Virgens Americanas",
  "VN": "Vietnã",
  "VU": "Vanuatu",
  "Vaii": "vai",
  "Visp": "visible speech",
  "WF": "Wallis e Futuna",
  "WS": "Samoa",
  "XA": "Pseudossotaques",
  "XB": "Pseudobidirecional",
  "XK": "Kosovo",
  "Xpeo": "persa antigo",
  "Xsux": "sumério-acadiano cuneiforme",
  "YE": "Iêmen",
  "YT": "Mayotte",
  "Yiii": "yi",
  "ZA": "África do Sul",
  "ZM": "Zâmbia",
  "ZW": "Zimbábue",
  "ZZ": "Região desconhecida",
  "Zinh": "herdado",
  "Zmth": "notação matemática",
  "Zsye": "Emoji",
  "Zsym": "zsym",
  "Zxxx": "ágrafo",
  "Zyyy": "comum",
  "Zzzz": "escrita desconhecida",
  "aa": "afar",
  "ab": "abcázio",
  "ace": "achém",
  "ach": "acoli",
  "ada": "adangme",
  "ady": "adigue",
  "ae": "avéstico",
  "aeb": "Tunisian Arabic",
  "af": "africâner",
  "af_NA": "africâner (Namíbia)",
  "af_ZA": "africâner (África do Sul)",
  "afa": "idioma afro-asiático",
  "afh": "afrihili",
  "agq": "aghem",
  "ain": "ainu",
  "ak": "akan",
  "ak_GH": "akan (Gana)",
  "akk": "acadiano",
  "akz": "Alabama",
  "ale": "aleúte",
  "alg": "idioma algonquiano",
  "aln": "Gheg Albanian",
  "alt": "altai meridional",
  "am": "amárico",
  "am_ET": "amárico (Etiópia)",
  "an": "aragonês",
  "ang": "inglês arcaico",
  "anp": "angika",
  "apa": "idioma apache",
  "ar": "árabe",
  "ar_001": "árabe moderno",
  "ar_AE": "árabe (Emirados Árabes Unidos)",
  "ar_BH": "árabe (Bahrein)",
  "ar_DJ": "árabe (Djibuti)",
  "ar_DZ": "árabe (Argélia)",
  "ar_EG": "árabe (Egito)",
  "ar_EH": "árabe (Saara Ocidental)",
  "ar_ER": "árabe (Eritreia)",
  "ar_IL": "árabe (Israel)",
  "ar_IQ": "árabe (Iraque)",
  "ar_JO": "árabe (Jordânia)",
  "ar_KM": "árabe (Comores)",
  "ar_KW": "árabe (Kuwait)",
  "ar_LB": "árabe (Líbano)",
  "ar_LY": "árabe (Líbia)",
  "ar_MA": "árabe (Marrocos)",
  "ar_MR": "árabe (Mauritânia)",
  "ar_OM": "árabe (Omã)",
  "ar_PS": "árabe (Territórios palestinos)",
  "ar_QA": "árabe (Catar)",
  "ar_SA": "árabe (Arábia Saudita)",
  "ar_SD": "árabe (Sudão)",
  "ar_SO": "árabe (Somália)",
  "ar_SS": "árabe (Sudão do Sul)",
  "ar_SY": "árabe (Síria)",
  "ar_TD": "árabe (Chade)",
  "ar_TN": "árabe (Tunísia)",
  "ar_YE": "árabe (Iêmen)",
  "arc": "aramaico",
  "arn": "mapudungun",
  "aro": "Araona",
  "arp": "arapaho",
  "arq": "Algerian Arabic",
  "ars": "árabe négede",
  "art": "idioma artificial",
  "arw": "arauaqui",
  "ary": "Moroccan Arabic",
  "arz": "Egyptian Arabic",
  "as": "assamês",
  "as_IN": "assamês (Índia)",
  "asa": "asu",
  "ase": "American Sign Language",
  "ast": "asturiano",
  "ath": "idioma atabascano",
  "aus": "idioma australiano",
  "av": "avárico",
  "avk": "Kotava",
  "awa": "awadhi",
  "ay": "aimará",
  "az": "azerbaijano",
  "az_AZ": "azerbaijano (Azerbaijão)",
  "az_Arab": "azeri sul",
  "az_Cyrl": "azerbaijano (cirílico)",
  "az_Cyrl_AZ": "azerbaijano (cirílico, Azerbaijão)",
  "az_Latn": "azerbaijano (latim)",
  "az_Latn_AZ": "azerbaijano (latim, Azerbaijão)",
  "azb": "South Azerbaijani",
  "ba": "bashkir",
  "bad": "banda",
  "bai": "idioma bamileke",
  "bal": "balúchi",
  "ban": "balinês",
  "bar": "Bavarian",
  "bas": "basa",
  "bat": "idioma báltico",
  "bax": "bamum",
  "bbc": "Batak Toba",
  "bbj": "ghomala’",
  "be": "bielorrusso",
  "be_BY": "bielorrusso (Bielorrússia)",
  "bej": "beja",
  "bem": "bemba",
  "ber": "berbere",
  "bew": "Betawi",
  "bez": "bena",
  "bfd": "bafut",
  "bfq": "Badaga",
  "bg": "búlgaro",
  "bg_BG": "búlgaro (Bulgária)",
  "bgn": "balúchi ocidental",
  "bh": "biari",
  "bho": "bhojpuri",
  "bi": "bislamá",
  "bik": "bikol",
  "bin": "bini",
  "bjn": "Banjar",
  "bkm": "kom",
  "bla": "siksika",
  "bm": "bambara",
  "bm_Latn": "bambara (latim)",
  "bm_Latn_ML": "bambara (latim, Mali)",
  "bn": "bengali",
  "bn_BD": "bengali (Bangladesh)",
  "bn_IN": "bengali (Índia)",
  "bnt": "banto",
  "bo": "tibetano",
  "bo_CN": "tibetano (China)",
  "bo_IN": "tibetano (Índia)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "bretão",
  "br_FR": "bretão (França)",
  "bra": "braj",
  "brh": "Brahui",
  "brx": "bodo",
  "bs": "bósnio",
  "bs_BA": "bósnio (Bósnia e Herzegovina)",
  "bs_Cyrl": "bósnio (cirílico)",
  "bs_Cyrl_BA": "bósnio (cirílico, Bósnia e Herzegovina)",
  "bs_Latn": "bósnio (latim)",
  "bs_Latn_BA": "bósnio (latim, Bósnia e Herzegovina)",
  "bss": "akoose",
  "btk": "bataque",
  "bua": "buriato",
  "bug": "buginês",
  "bum": "bulu",
  "byn": "blin",
  "byv": "medumba",
  "ca": "catalão",
  "ca_AD": "catalão (Andorra)",
  "ca_ES": "catalão (Espanha)",
  "ca_FR": "catalão (França)",
  "ca_IT": "catalão (Itália)",
  "cad": "caddo",
  "cai": "idioma indígena centro-americano",
  "car": "caribe",
  "cau": "idioma caucásico",
  "cay": "cayuga",
  "cch": "atsam",
  "ccp": "chakma",
  "ce": "checheno",
  "ceb": "cebuano",
  "cel": "idioma celta",
  "cgg": "chiga",
  "ch": "chamorro",
  "chb": "chibcha",
  "chg": "chagatai",
  "chk": "chuukese",
  "chm": "mari",
  "chn": "jargão Chinook",
  "cho": "choctaw",
  "chp": "chipewyan",
  "chr": "cheroqui",
  "chy": "cheiene",
  "ckb": "curdo central",
  "cmc": "idioma chamic",
  "co": "corso",
  "cop": "copta",
  "cpe": "crioulo ou pidgin baseado no inglês",
  "cpf": "crioulo ou pidgin baseado no francês",
  "cpp": "crioulo ou pidgin baseado no português",
  "cps": "Capiznon",
  "cr": "cree",
  "crh": "turco da Crimeia",
  "crp": "crioulo ou pidgin",
  "crs": "crioulo francês seichelense",
  "cs": "tcheco",
  "cs_CZ": "tcheco (República Tcheca)",
  "csb": "kashubian",
  "cu": "eslavo eclesiástico",
  "cus": "idioma cuchítico",
  "cv": "tchuvache",
  "cy": "galês",
  "cy_GB": "galês (Reino Unido)",
  "da": "dinamarquês",
  "da_DK": "dinamarquês (Dinamarca)",
  "da_GL": "dinamarquês (Groenlândia)",
  "dak": "dacota",
  "dar": "dargwa",
  "dav": "taita",
  "day": "dayak",
  "de": "alemão",
  "de_AT": "alemão (Áustria)",
  "de_BE": "alemão (Bélgica)",
  "de_CH": "alemão (Suíça)",
  "de_DE": "alemão (Alemanha)",
  "de_LI": "alemão (Liechtenstein)",
  "de_LU": "alemão (Luxemburgo)",
  "del": "delaware",
  "den": "slave",
  "dgr": "dogrib",
  "din": "dinka",
  "dje": "zarma",
  "doi": "dogri",
  "dra": "idioma dravidiano",
  "dsb": "baixo sorábio",
  "dtp": "Central Dusun",
  "dua": "duala",
  "dum": "holandês médio",
  "dv": "divehi",
  "dyo": "jola-fonyi",
  "dyu": "diúla",
  "dz": "dzonga",
  "dz_BT": "dzonga (Butão)",
  "dzg": "dazaga",
  "ebu": "embu",
  "ee": "eve",
  "ee_GH": "eve (Gana)",
  "ee_TG": "eve (Togo)",
  "efi": "efique",
  "egl": "Emilian",
  "egy": "egípcio arcaico",
  "eka": "ekajuk",
  "el": "grego",
  "el_CY": "grego (Chipre)",
  "el_GR": "grego (Grécia)",
  "elx": "elamite",
  "en": "inglês",
  "en_AG": "inglês (Antígua e Barbuda)",
  "en_AI": "inglês (Anguilla)",
  "en_AS": "inglês (Samoa Americana)",
  "en_AU": "inglês (Austrália)",
  "en_BB": "inglês (Barbados)",
  "en_BE": "inglês (Bélgica)",
  "en_BM": "inglês (Bermudas)",
  "en_BS": "inglês (Bahamas)",
  "en_BW": "inglês (Botsuana)",
  "en_BZ": "inglês (Belize)",
  "en_CA": "inglês (Canadá)",
  "en_CC": "inglês (Ilhas Cocos (Keeling))",
  "en_CK": "inglês (Ilhas Cook)",
  "en_CM": "inglês (República dos Camarões)",
  "en_CX": "inglês (Ilha Christmas)",
  "en_DG": "inglês (Diego Garcia)",
  "en_DM": "inglês (Dominica)",
  "en_ER": "inglês (Eritreia)",
  "en_FJ": "inglês (Fiji)",
  "en_FK": "inglês (Ilhas Malvinas)",
  "en_FM": "inglês (Micronésia)",
  "en_GB": "inglês (Reino Unido)",
  "en_GD": "inglês (Granada)",
  "en_GG": "inglês (Guernsey)",
  "en_GH": "inglês (Gana)",
  "en_GI": "inglês (Gibraltar)",
  "en_GM": "inglês (Gâmbia)",
  "en_GU": "inglês (Guam)",
  "en_GY": "inglês (Guiana)",
  "en_HK": "inglês (Hong Kong, RAE da China)",
  "en_IE": "inglês (Irlanda)",
  "en_IM": "inglês (Ilha de Man)",
  "en_IN": "inglês (Índia)",
  "en_IO": "inglês (Território Britânico do Oceano Índico)",
  "en_JE": "inglês (Jersey)",
  "en_JM": "inglês (Jamaica)",
  "en_KE": "inglês (Quênia)",
  "en_KI": "inglês (Quiribati)",
  "en_KN": "inglês (São Cristóvão e Nevis)",
  "en_KY": "inglês (Ilhas Caiman)",
  "en_LC": "inglês (Santa Lúcia)",
  "en_LR": "inglês (Libéria)",
  "en_LS": "inglês (Lesoto)",
  "en_MG": "inglês (Madagascar)",
  "en_MH": "inglês (Ilhas Marshall)",
  "en_MO": "inglês (Macau, RAE da China)",
  "en_MP": "inglês (Ilhas Marianas do Norte)",
  "en_MS": "inglês (Montserrat)",
  "en_MT": "inglês (Malta)",
  "en_MU": "inglês (Maurício)",
  "en_MW": "inglês (Malawi)",
  "en_MY": "inglês (Malásia)",
  "en_NA": "inglês (Namíbia)",
  "en_NF": "inglês (Ilha Norfolk)",
  "en_NG": "inglês (Nigéria)",
  "en_NR": "inglês (Nauru)",
  "en_NU": "inglês (Niue)",
  "en_NZ": "inglês (Nova Zelândia)",
  "en_PG": "inglês (Papua-Nova Guiné)",
  "en_PH": "inglês (Filipinas)",
  "en_PK": "inglês (Paquistão)",
  "en_PN": "inglês (Ilhas Pitcairn)",
  "en_PR": "inglês (Porto Rico)",
  "en_PW": "inglês (Palau)",
  "en_RW": "inglês (Ruanda)",
  "en_SB": "inglês (Ilhas Salomão)",
  "en_SC": "inglês (Seychelles)",
  "en_SD": "inglês (Sudão)",
  "en_SG": "inglês (Cingapura)",
  "en_SH": "inglês (Santa Helena)",
  "en_SL": "inglês (Serra Leoa)",
  "en_SS": "inglês (Sudão do Sul)",
  "en_SX": "inglês (Sint Maarten)",
  "en_SZ": "inglês (Suazilândia)",
  "en_TC": "inglês (Ilhas Turks e Caicos)",
  "en_TK": "inglês (Tokelau)",
  "en_TO": "inglês (Tonga)",
  "en_TT": "inglês (Trinidad e Tobago)",
  "en_TV": "inglês (Tuvalu)",
  "en_TZ": "inglês (Tanzânia)",
  "en_UG": "inglês (Uganda)",
  "en_UM": "inglês (Ilhas Distantes dos EUA)",
  "en_US": "inglês (Estados Unidos)",
  "en_VC": "inglês (São Vicente e Granadinas)",
  "en_VG": "inglês (Ilhas Virgens Britânicas)",
  "en_VI": "inglês (Ilhas Virgens dos EUA)",
  "en_VU": "inglês (Vanuatu)",
  "en_WS": "inglês (Samoa)",
  "en_ZA": "inglês (África do Sul)",
  "en_ZM": "inglês (Zâmbia)",
  "en_ZW": "inglês (Zimbábue)",
  "enm": "inglês médio",
  "eo": "esperanto",
  "es": "espanhol",
  "es_419": "espanhol latino-americano",
  "es_AR": "espanhol (Argentina)",
  "es_BO": "espanhol (Bolívia)",
  "es_CL": "espanhol (Chile)",
  "es_CO": "espanhol (Colômbia)",
  "es_CR": "espanhol (Costa Rica)",
  "es_CU": "espanhol (Cuba)",
  "es_DO": "espanhol (República Dominicana)",
  "es_EA": "espanhol (Ceuta e Melilha)",
  "es_EC": "espanhol (Equador)",
  "es_ES": "espanhol (Espanha)",
  "es_GQ": "espanhol (Guiné Equatorial)",
  "es_GT": "espanhol (Guatemala)",
  "es_HN": "espanhol (Honduras)",
  "es_IC": "espanhol (Ilhas Canárias)",
  "es_MX": "espanhol (México)",
  "es_NI": "espanhol (Nicarágua)",
  "es_PA": "espanhol (Panamá)",
  "es_PE": "espanhol (Peru)",
  "es_PH": "espanhol (Filipinas)",
  "es_PR": "espanhol (Porto Rico)",
  "es_PY": "espanhol (Paraguai)",
  "es_SV": "espanhol (El Salvador)",
  "es_US": "espanhol (Estados Unidos)",
  "es_UY": "espanhol (Uruguai)",
  "es_VE": "espanhol (Venezuela)",
  "esu": "Central Yupik",
  "et": "estoniano",
  "et_EE": "estoniano (Estônia)",
  "eu": "basco",
  "eu_ES": "basco (Espanha)",
  "ewo": "ewondo",
  "ext": "Extremaduran",
  "fa": "persa",
  "fa_AF": "persa (Afeganistão)",
  "fa_IR": "persa (Irã)",
  "fan": "fangue",
  "fat": "fanti",
  "ff": "fula",
  "ff_CM": "fula (República dos Camarões)",
  "ff_GN": "fula (Guiné)",
  "ff_MR": "fula (Mauritânia)",
  "ff_SN": "fula (Senegal)",
  "fi": "finlandês",
  "fi_FI": "finlandês (Finlândia)",
  "fil": "filipino",
  "fit": "Tornedalen Finnish",
  "fiu": "idioma fino-úgrico",
  "fj": "fijiano",
  "fo": "feroês",
  "fo_FO": "feroês (Ilhas Faroe)",
  "fon": "fom",
  "fr": "francês",
  "fr_BE": "francês (Bélgica)",
  "fr_BF": "francês (Burquina Faso)",
  "fr_BI": "francês (Burundi)",
  "fr_BJ": "francês (Benin)",
  "fr_BL": "francês (São Bartolomeu)",
  "fr_CA": "francês (Canadá)",
  "fr_CD": "francês (Congo - Kinshasa)",
  "fr_CF": "francês (República Centro-Africana)",
  "fr_CG": "francês (Congo - Brazzaville)",
  "fr_CH": "francês (Suíça)",
  "fr_CI": "francês (Costa do Marfim)",
  "fr_CM": "francês (República dos Camarões)",
  "fr_DJ": "francês (Djibuti)",
  "fr_DZ": "francês (Argélia)",
  "fr_FR": "francês (França)",
  "fr_GA": "francês (Gabão)",
  "fr_GF": "francês (Guiana Francesa)",
  "fr_GN": "francês (Guiné)",
  "fr_GP": "francês (Guadalupe)",
  "fr_GQ": "francês (Guiné Equatorial)",
  "fr_HT": "francês (Haiti)",
  "fr_KM": "francês (Comores)",
  "fr_LU": "francês (Luxemburgo)",
  "fr_MA": "francês (Marrocos)",
  "fr_MC": "francês (Mônaco)",
  "fr_MF": "francês (São Martinho)",
  "fr_MG": "francês (Madagascar)",
  "fr_ML": "francês (Mali)",
  "fr_MQ": "francês (Martinica)",
  "fr_MR": "francês (Mauritânia)",
  "fr_MU": "francês (Maurício)",
  "fr_NC": "francês (Nova Caledônia)",
  "fr_NE": "francês (Níger)",
  "fr_PF": "francês (Polinésia Francesa)",
  "fr_PM": "francês (Saint Pierre e Miquelon)",
  "fr_RE": "francês (Reunião)",
  "fr_RW": "francês (Ruanda)",
  "fr_SC": "francês (Seychelles)",
  "fr_SN": "francês (Senegal)",
  "fr_SY": "francês (Síria)",
  "fr_TD": "francês (Chade)",
  "fr_TG": "francês (Togo)",
  "fr_TN": "francês (Tunísia)",
  "fr_VU": "francês (Vanuatu)",
  "fr_WF": "francês (Wallis e Futuna)",
  "fr_YT": "francês (Mayotte)",
  "frc": "francês cajun",
  "frm": "francês médio",
  "fro": "francês arcaico",
  "frp": "Arpitan",
  "frr": "frísio setentrional",
  "frs": "frisão oriental",
  "fur": "friulano",
  "fy": "frísio ocidental",
  "fy_NL": "frísio ocidental (Holanda)",
  "ga": "irlandês",
  "ga_IE": "irlandês (Irlanda)",
  "gaa": "ga",
  "gag": "gagauz",
  "gan": "gan",
  "gay": "gayo",
  "gba": "gbaia",
  "gbz": "Zoroastrian Dari",
  "gd": "gaélico escocês",
  "gd_GB": "gaélico escocês (Reino Unido)",
  "gem": "idioma germânico",
  "gez": "geez",
  "gil": "gilbertês",
  "gl": "galego",
  "gl_ES": "galego (Espanha)",
  "glk": "Gilaki",
  "gmh": "alto alemão médio",
  "gn": "guarani",
  "goh": "alemão arcaico alto",
  "gom": "Goan Konkani",
  "gon": "gondi",
  "gor": "gorontalo",
  "got": "gótico",
  "grb": "grebo",
  "grc": "grego arcaico",
  "gsw": "alemão (Suíça)",
  "gu": "guzerate",
  "gu_IN": "guzerate (Índia)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "gusii",
  "gv": "manx",
  "gv_IM": "manx (Ilha de Man)",
  "gwi": "gwichʼin",
  "ha": "hauçá",
  "ha_GH": "hauçá (Gana)",
  "ha_Latn": "hauçá (latim)",
  "ha_Latn_GH": "hauçá (latim, Gana)",
  "ha_Latn_NE": "hauçá (latim, Níger)",
  "ha_Latn_NG": "hauçá (latim, Nigéria)",
  "ha_NE": "hauçá (Níger)",
  "ha_NG": "hauçá (Nigéria)",
  "hai": "haida",
  "hak": "hacá",
  "haw": "havaiano",
  "he": "hebraico",
  "he_IL": "hebraico (Israel)",
  "hi": "híndi",
  "hi_IN": "híndi (Índia)",
  "hif": "Fiji Hindi",
  "hil": "hiligaynon",
  "him": "himachali",
  "hit": "hitita",
  "hmn": "hmong",
  "ho": "hiri motu",
  "hr": "croata",
  "hr_BA": "croata (Bósnia e Herzegovina)",
  "hr_HR": "croata (Croácia)",
  "hsb": "alto sorábio",
  "hsn": "xiang",
  "ht": "haitiano",
  "hu": "húngaro",
  "hu_HU": "húngaro (Hungria)",
  "hup": "hupa",
  "hy": "armênio",
  "hy_AM": "armênio (Armênia)",
  "hz": "herero",
  "ia": "interlíngua",
  "iba": "iban",
  "ibb": "ibibio",
  "id": "indonésio",
  "id_ID": "indonésio (Indonésia)",
  "ie": "interlingue",
  "ig": "igbo",
  "ig_NG": "ibo (Nigéria)",
  "ii": "sichuan yi",
  "ii_CN": "sichuan yi (China)",
  "ijo": "ijo",
  "ik": "inupiaque",
  "ilo": "ilocano",
  "inc": "idioma índico",
  "ine": "idioma indo-europeu",
  "inh": "inguche",
  "io": "ido",
  "ira": "iraniano",
  "iro": "idioma iroquês",
  "is": "islandês",
  "is_IS": "islandês (Islândia)",
  "it": "italiano",
  "it_CH": "italiano (Suíça)",
  "it_IT": "italiano (Itália)",
  "it_SM": "italiano (San Marino)",
  "iu": "inuktitut",
  "izh": "Ingrian",
  "ja": "japonês",
  "ja_JP": "japonês (Japão)",
  "jam": "Jamaican Creole English",
  "jbo": "lojban",
  "jgo": "nguemba",
  "jmc": "machame",
  "jpr": "judaico-persa",
  "jrb": "judaico-arábico",
  "jut": "Jutish",
  "jv": "javanês",
  "ka": "georgiano",
  "ka_GE": "georgiano (Geórgia)",
  "kaa": "kara-kalpak",
  "kab": "kabyle",
  "kac": "kachin",
  "kaj": "jju",
  "kam": "kamba",
  "kar": "karen",
  "kaw": "kawi",
  "kbd": "kabardiano",
  "kbl": "kanembu",
  "kcg": "tyap",
  "kde": "maconde",
  "kea": "crioulo cabo-verdiano",
  "ken": "Kenyang",
  "kfo": "koro",
  "kg": "congolês",
  "kgp": "Kaingang",
  "kha": "khasi",
  "khi": "idioma coisã",
  "kho": "khotanês",
  "khq": "koyra chiini",
  "khw": "Khowar",
  "ki": "quicuio",
  "ki_KE": "quicuio (Quênia)",
  "kiu": "Kirmanjki",
  "kj": "cuanhama",
  "kk": "cazaque",
  "kk_Cyrl": "cazaque (cirílico)",
  "kk_Cyrl_KZ": "cazaque (cirílico, Cazaquistão)",
  "kk_KZ": "cazaque (Cazaquistão)",
  "kkj": "kako",
  "kl": "groenlandês",
  "kl_GL": "groenlandês (Groenlândia)",
  "kln": "kalenjin",
  "km": "khmer",
  "km_KH": "khmer (Camboja)",
  "kmb": "quimbundo",
  "kn": "canarim",
  "kn_IN": "canarês (Índia)",
  "ko": "coreano",
  "ko_KP": "coreano (Coreia do Norte)",
  "ko_KR": "coreano (Coreia do Sul)",
  "koi": "komi-permyak",
  "kok": "concani",
  "kos": "kosraean",
  "kpe": "kpelle",
  "kr": "canúri",
  "krc": "karachay-balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "carélio",
  "kro": "kru",
  "kru": "kurukh",
  "ks": "caxemira",
  "ks_Arab": "caxemira (árabe)",
  "ks_Arab_IN": "caxemira (árabe, Índia)",
  "ks_IN": "caxemira (Índia)",
  "ksb": "shambala",
  "ksf": "bafia",
  "ksh": "kölsch",
  "ku": "curdo",
  "kum": "kumyk",
  "kut": "kutenai",
  "kv": "komi",
  "kw": "córnico",
  "kw_GB": "córnico (Reino Unido)",
  "ky": "quirguiz",
  "ky_Cyrl": "quirguiz (cirílico)",
  "ky_Cyrl_KG": "quirguiz (cirílico, Quirguistão)",
  "ky_KG": "quirguiz (Quirguistão)",
  "la": "latim",
  "lad": "ladino",
  "lag": "langi",
  "lah": "lahnda",
  "lam": "lamba",
  "lb": "luxemburguês",
  "lb_LU": "luxemburguês (Luxemburgo)",
  "lez": "lezgui",
  "lfn": "Lingua Franca Nova",
  "lg": "luganda",
  "lg_UG": "luganda (Uganda)",
  "li": "limburguês",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "lacota",
  "lmo": "Lombard",
  "ln": "lingala",
  "ln_AO": "lingala (Angola)",
  "ln_CD": "lingala (Congo - Kinshasa)",
  "ln_CF": "lingala (República Centro-Africana)",
  "ln_CG": "lingala (Congo - Brazzaville)",
  "lo": "laosiano",
  "lo_LA": "laosiano (Laos)",
  "lol": "mongo",
  "lou": "crioulo da Louisiana",
  "loz": "lozi",
  "lrc": "luri setentrional",
  "lt": "lituano",
  "lt_LT": "lituano (Lituânia)",
  "ltg": "Latgalian",
  "lu": "luba-catanga",
  "lu_CD": "luba-catanga (Congo - Kinshasa)",
  "lua": "luba-lulua",
  "lui": "luiseno",
  "lun": "lunda",
  "luo": "luo",
  "lus": "lushai",
  "luy": "luyia",
  "lv": "letão",
  "lv_LV": "letão (Letônia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "madurês",
  "maf": "mafa",
  "mag": "magahi",
  "mai": "maithili",
  "mak": "makasar",
  "man": "mandinga",
  "map": "austronésio",
  "mas": "massai",
  "mde": "maba",
  "mdf": "mocsa",
  "mdr": "mandar",
  "men": "mende",
  "mer": "meru",
  "mfe": "morisyen",
  "mg": "malgaxe",
  "mg_MG": "malgaxe (Madagascar)",
  "mga": "irlandês médio",
  "mgh": "macua",
  "mgo": "meta’",
  "mh": "marshalês",
  "mi": "maori",
  "mic": "miquemaque",
  "min": "minangkabau",
  "mis": "idiomas diversos",
  "mk": "macedônio",
  "mk_MK": "macedônio (Macedônia)",
  "mkh": "idioma mon-khmer",
  "ml": "malaiala",
  "ml_IN": "malaiala (Índia)",
  "mn": "mongol",
  "mn_Cyrl": "mongol (cirílico)",
  "mn_Cyrl_MN": "mongol (cirílico, Mongólia)",
  "mn_MN": "mongol (Mongólia)",
  "mnc": "manchu",
  "mni": "manipuri",
  "mno": "idioma manobo",
  "mo": "moldávio",
  "moh": "moicano",
  "mos": "mossi",
  "mr": "marati",
  "mr_IN": "marata (Índia)",
  "mrj": "Western Mari",
  "ms": "malaio",
  "ms_BN": "malaio (Brunei)",
  "ms_Latn": "malaio (latim)",
  "ms_Latn_BN": "malaio (latim, Brunei)",
  "ms_Latn_MY": "malaio (latim, Malásia)",
  "ms_Latn_SG": "malaio (latim, Cingapura)",
  "ms_MY": "malaio (Malásia)",
  "ms_SG": "malaio (Cingapura)",
  "mt": "maltês",
  "mt_MT": "maltês (Malta)",
  "mua": "mundang",
  "mul": "múltiplos idiomas",
  "mun": "idiomas munda",
  "mus": "creek",
  "mwl": "mirandês",
  "mwr": "marwari",
  "mwv": "Mentawai",
  "my": "birmanês",
  "my_MM": "birmanês (Mianmar (Birmânia))",
  "mye": "myene",
  "myn": "maia",
  "myv": "erzya",
  "mzn": "mazandarani",
  "na": "nauruano",
  "nah": "náuatle",
  "nai": "idioma indígena norte-americano",
  "nan": "min nan",
  "nap": "napolitano",
  "naq": "nama",
  "nb": "bokmål norueguês",
  "nb_NO": "bokmål norueguês (Noruega)",
  "nb_SJ": "bokmål norueguês (Svalbard e Jan Mayen)",
  "nd": "ndebele do norte",
  "nd_ZW": "ndebele do norte (Zimbábue)",
  "nds": "baixo alemão",
  "nds_NL": "baixo saxão",
  "ne": "nepalês",
  "ne_IN": "nepali (Índia)",
  "ne_NP": "nepali (Nepal)",
  "new": "newari",
  "ng": "dongo",
  "nia": "nias",
  "nic": "idioma cordofano-nigeriano",
  "niu": "niueano",
  "njo": "Ao Naga",
  "nl": "holandês",
  "nl_AW": "holandês (Aruba)",
  "nl_BE": "holandês (Bélgica)",
  "nl_BQ": "holandês (Países Baixos Caribenhos)",
  "nl_CW": "holandês (Curaçao)",
  "nl_NL": "holandês (Holanda)",
  "nl_SR": "holandês (Suriname)",
  "nl_SX": "holandês (Sint Maarten)",
  "nmg": "kwasio",
  "nn": "nynorsk norueguês",
  "nn_NO": "nynorsk norueguês (Noruega)",
  "nnh": "ngiemboon",
  "no": "norueguês",
  "no_NO": "norueguês (Noruega)",
  "nog": "nogai",
  "non": "nórdico arcaico",
  "nov": "Novial",
  "nqo": "n’ko",
  "nr": "ndebele do sul",
  "nso": "soto setentrional",
  "nub": "idioma núbio",
  "nus": "nuer",
  "nv": "navajo",
  "nwc": "newari clássico",
  "ny": "nianja",
  "nym": "nyamwezi",
  "nyn": "nyankole",
  "nyo": "nyoro",
  "nzi": "nzima",
  "oc": "occitânico",
  "oj": "ojibwa",
  "om": "oromo",
  "om_ET": "oromo (Etiópia)",
  "om_KE": "oromo (Quênia)",
  "or": "oriá",
  "or_IN": "oriya (Índia)",
  "os": "osseto",
  "os_GE": "ossetic (Geórgia)",
  "os_RU": "ossetic (Rússia)",
  "osa": "osage",
  "ota": "turco otomano",
  "oto": "idioma otomano",
  "pa": "panjabi",
  "pa_Arab": "panjabi (árabe)",
  "pa_Arab_PK": "panjabi (árabe, Paquistão)",
  "pa_Guru": "panjabi (gurmuqui)",
  "pa_Guru_IN": "panjabi (gurmuqui, Índia)",
  "pa_IN": "panjabi (Índia)",
  "pa_PK": "panjabi (Paquistão)",
  "paa": "idioma papuano",
  "pag": "pangasinã",
  "pal": "pálavi",
  "pam": "pampanga",
  "pap": "papiamento",
  "pau": "palauano",
  "pcd": "Picard",
  "pcm": "pidgin nigeriano",
  "pdc": "Pennsylvania German",
  "pdt": "Plautdietsch",
  "peo": "persa arcaico",
  "pfl": "Palatine German",
  "phi": "idioma filipino",
  "phn": "fenício",
  "pi": "páli",
  "pl": "polonês",
  "pl_PL": "polonês (Polônia)",
  "pms": "Piedmontese",
  "pnt": "Pontic",
  "pon": "pohnpeiano",
  "pra": "idioma prácrito",
  "prg": "prussiano",
  "pro": "provençal arcaico",
  "ps": "pashto",
  "ps_AF": "pashto (Afeganistão)",
  "pt": "português",
  "pt_AO": "português (Angola)",
  "pt_BR": "português (Brasil)",
  "pt_CV": "português (Cabo Verde)",
  "pt_GW": "português (Guiné Bissau)",
  "pt_MO": "português (Macau, RAE da China)",
  "pt_MZ": "português (Moçambique)",
  "pt_PT": "português (Portugal)",
  "pt_ST": "português (São Tomé e Príncipe)",
  "pt_TL": "português (Timor-Leste)",
  "qu": "quíchua",
  "qu_BO": "quíchua (Bolívia)",
  "qu_EC": "quíchua (Equador)",
  "qu_PE": "quíchua (Peru)",
  "quc": "quiché",
  "qug": "Chimborazo Highland Quichua",
  "raj": "rajastani",
  "rap": "rapanui",
  "rar": "rarotongano",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "romanche",
  "rm_CH": "romanche (Suíça)",
  "rn": "rundi",
  "rn_BI": "rundi (Burundi)",
  "ro": "romeno",
  "ro_MD": "romeno (Moldávia)",
  "ro_RO": "romeno (Romênia)",
  "roa": "idioma românico",
  "rof": "rombo",
  "rom": "romani",
  "root": "raiz",
  "rtm": "Rotuman",
  "ru": "russo",
  "ru_BY": "russo (Bielorrússia)",
  "ru_KG": "russo (Quirguistão)",
  "ru_KZ": "russo (Cazaquistão)",
  "ru_MD": "russo (Moldávia)",
  "ru_RU": "russo (Rússia)",
  "ru_UA": "russo (Ucrânia)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "aromeno",
  "rw": "quiniaruanda",
  "rw_RW": "ruanda (Ruanda)",
  "rwk": "rwa",
  "sa": "sânscrito",
  "sad": "sandawe",
  "sah": "sakha",
  "sai": "idioma indígena sul-americano",
  "sal": "idioma salisano",
  "sam": "aramaico samaritano",
  "saq": "samburu",
  "sas": "sasak",
  "sat": "santali",
  "saz": "Saurashtra",
  "sba": "ngambay",
  "sbp": "sangu",
  "sc": "sardo",
  "scn": "siciliano",
  "sco": "scots",
  "sd": "sindi",
  "sdc": "Sassarese Sardinian",
  "sdh": "curdo meridional",
  "se": "sami setentrional",
  "se_FI": "sami do norte (Finlândia)",
  "se_NO": "sami do norte (Noruega)",
  "se_SE": "sami do norte (Suécia)",
  "see": "seneca",
  "seh": "sena",
  "sei": "Seri",
  "sel": "selkup",
  "sem": "idioma semítico",
  "ses": "koyraboro senni",
  "sg": "sango",
  "sg_CF": "sango (República Centro-Africana)",
  "sga": "irlandês arcaico",
  "sgn": "linguagem de sinais",
  "sgs": "Samogitian",
  "sh": "servo-croata",
  "sh_BA": "servo-croata (Bósnia e Herzegovina)",
  "shi": "tachelhit",
  "shn": "shan",
  "shu": "árabe chadiano",
  "si": "cingalês",
  "si_LK": "cingalês (Sri Lanka)",
  "sid": "sidamo",
  "sio": "idioma sioux",
  "sit": "idioma sino-tibetano",
  "sk": "eslovaco",
  "sk_SK": "eslovaco (Eslováquia)",
  "sl": "esloveno",
  "sl_SI": "esloveno (Eslovênia)",
  "sla": "idioma eslavo",
  "sli": "Lower Silesian",
  "sly": "Selayar",
  "sm": "samoano",
  "sma": "sami meridional",
  "smi": "idioma sami",
  "smj": "sami de Lule",
  "smn": "sami de Inari",
  "sms": "sami de Skolt",
  "sn": "xona",
  "sn_ZW": "shona (Zimbábue)",
  "snk": "soninquê",
  "so": "somali",
  "so_DJ": "somali (Djibuti)",
  "so_ET": "somali (Etiópia)",
  "so_KE": "somali (Quênia)",
  "so_SO": "somali (Somália)",
  "sog": "sogdiano",
  "son": "songai",
  "sq": "albanês",
  "sq_AL": "albanês (Albânia)",
  "sq_MK": "albanês (Macedônia)",
  "sq_XK": "albanês (Kosovo)",
  "sr": "sérvio",
  "sr_BA": "sérvio (Bósnia e Herzegovina)",
  "sr_Cyrl": "sérvio (cirílico)",
  "sr_Cyrl_BA": "sérvio (cirílico, Bósnia e Herzegovina)",
  "sr_Cyrl_ME": "sérvio (cirílico, Montenegro)",
  "sr_Cyrl_RS": "sérvio (cirílico, Sérvia)",
  "sr_Cyrl_XK": "sérvio (cirílico, Kosovo)",
  "sr_Latn": "sérvio (latim)",
  "sr_Latn_BA": "sérvio (latim, Bósnia e Herzegovina)",
  "sr_Latn_ME": "sérvio (latim, Montenegro)",
  "sr_Latn_RS": "sérvio (latim, Sérvia)",
  "sr_Latn_XK": "sérvio (latim, Kosovo)",
  "sr_ME": "sérvio (Montenegro)",
  "sr_RS": "sérvio (Sérvia)",
  "sr_XK": "sérvio (Kosovo)",
  "srn": "surinamês",
  "srr": "serere",
  "ss": "suázi",
  "ssa": "idioma nilo-saariano",
  "ssy": "saho",
  "st": "soto do sul",
  "stq": "Saterland Frisian",
  "su": "sundanês",
  "suk": "sukuma",
  "sus": "susu",
  "sux": "sumério",
  "sv": "sueco",
  "sv_AX": "sueco (Ilhas Åland)",
  "sv_FI": "sueco (Finlândia)",
  "sv_SE": "sueco (Suécia)",
  "sw": "suaíli",
  "sw_CD": "suaíli do Congo",
  "sw_KE": "suaíli (Quênia)",
  "sw_TZ": "suaíli (Tanzânia)",
  "sw_UG": "suaíli (Uganda)",
  "swb": "comoriano",
  "swc": "suaíli do Congo",
  "syc": "siríaco clássico",
  "syr": "siríaco",
  "szl": "Silesian",
  "ta": "tâmil",
  "ta_IN": "tâmil (Índia)",
  "ta_LK": "tâmil (Sri Lanka)",
  "ta_MY": "tâmil (Malásia)",
  "ta_SG": "tâmil (Cingapura)",
  "tai": "idioma tailandês",
  "tcy": "Tulu",
  "te": "télugo",
  "te_IN": "telugu (Índia)",
  "tem": "timne",
  "teo": "teso",
  "ter": "tereno",
  "tet": "tétum",
  "tg": "tadjique",
  "th": "tailandês",
  "th_TH": "tailandês (Tailândia)",
  "ti": "tigrínia",
  "ti_ER": "tigrínia (Eritreia)",
  "ti_ET": "tigrínia (Etiópia)",
  "tig": "tigré",
  "tiv": "tiv",
  "tk": "turcomeno",
  "tkl": "toquelauano",
  "tkr": "Tsakhur",
  "tl": "tagalo",
  "tl_PH": "tagalo (Filipinas)",
  "tlh": "klingon",
  "tli": "tlinguite",
  "tly": "Talysh",
  "tmh": "tamaxeque",
  "tn": "tswana",
  "to": "tonganês",
  "to_TO": "tonganês (Tonga)",
  "tog": "tonganês de Nyasa",
  "tpi": "tok pisin",
  "tr": "turco",
  "tr_CY": "turco (Chipre)",
  "tr_TR": "turco (Turquia)",
  "tru": "Turoyo",
  "trv": "taroko",
  "ts": "tsonga",
  "tsd": "Tsakonian",
  "tsi": "tsimshiano",
  "tt": "tártaro",
  "ttt": "Muslim Tat",
  "tum": "tumbuka",
  "tup": "idioma tupi",
  "tut": "idioma altaico",
  "tvl": "tuvaluano",
  "tw": "twi",
  "twq": "tasawaq",
  "ty": "taitiano",
  "tyv": "tuviniano",
  "tzm": "tamazirte do Atlas Central",
  "udm": "udmurte",
  "ug": "uigur",
  "ug_Arab": "uigur (árabe)",
  "ug_Arab_CN": "uigur (árabe, China)",
  "ug_CN": "uigur (China)",
  "uga": "ugarítico",
  "uk": "ucraniano",
  "uk_UA": "ucraniano (Ucrânia)",
  "umb": "umbundu",
  "und": "idioma desconhecido",
  "ur": "urdu",
  "ur_IN": "urdu (Índia)",
  "ur_PK": "urdu (Paquistão)",
  "uz": "uzbeque",
  "uz_AF": "usbeque (Afeganistão)",
  "uz_Arab": "usbeque (árabe)",
  "uz_Arab_AF": "usbeque (árabe, Afeganistão)",
  "uz_Cyrl": "usbeque (cirílico)",
  "uz_Cyrl_UZ": "usbeque (cirílico, Uzbequistão)",
  "uz_Latn": "usbeque (latim)",
  "uz_Latn_UZ": "usbeque (latim, Uzbequistão)",
  "uz_UZ": "usbeque (Uzbequistão)",
  "vai": "vai",
  "ve": "venda",
  "vec": "Venetian",
  "vep": "Veps",
  "vi": "vietnamita",
  "vi_VN": "vietnamita (Vietnã)",
  "vls": "West Flemish",
  "vmf": "Main-Franconian",
  "vo": "volapuque",
  "vot": "vótico",
  "vro": "Võro",
  "vun": "vunjo",
  "wa": "valão",
  "wae": "walser",
  "wak": "idioma wakashan",
  "wal": "wolaytta",
  "war": "waray",
  "was": "washo",
  "wbp": "warlpiri",
  "wen": "idioma sorábio",
  "wo": "uolofe",
  "wuu": "wu",
  "xal": "kalmyk",
  "xh": "xhosa",
  "xmf": "Mingrelian",
  "xog": "lusoga",
  "yao": "yao",
  "yap": "yapese",
  "yav": "yangben",
  "ybb": "yemba",
  "yi": "iídiche",
  "yo": "iorubá",
  "yo_BJ": "ioruba (Benin)",
  "yo_NG": "ioruba (Nigéria)",
  "ypk": "idioma iúpique",
  "yrl": "Nheengatu",
  "yue": "cantonês",
  "za": "zhuang",
  "zap": "zapoteco",
  "zbl": "símbolos blis",
  "zea": "Zeelandic",
  "zen": "zenaga",
  "zgh": "tamazirte marroqino padrão",
  "zh": "chinês",
  "zh_CN": "chinês (China)",
  "zh_HK": "chinês (Hong Kong, RAE da China)",
  "zh_Hans": "chinês (simplificado)",
  "zh_Hans_CN": "chinês (simplificado, China)",
  "zh_Hans_HK": "chinês (simplificado, Hong Kong, RAE da China)",
  "zh_Hans_MO": "chinês (simplificado, Macau, RAE da China)",
  "zh_Hans_SG": "chinês (simplificado, Cingapura)",
  "zh_Hant": "chinês (tradicional)",
  "zh_Hant_HK": "chinês (tradicional, Hong Kong, RAE da China)",
  "zh_Hant_MO": "chinês (tradicional, Macau, RAE da China)",
  "zh_Hant_TW": "chinês (tradicional, Taiwan)",
  "zh_MO": "chinês (Macau, RAE da China)",
  "zh_SG": "chinês (Cingapura)",
  "zh_TW": "chinês (Taiwan)",
  "znd": "zande",
  "zu": "zulu",
  "zu_ZA": "zulu (África do Sul)",
  "zun": "zunhi",
  "zxx": "sem conteúdo linguístico",
  "zza": "zazaki"
};
