const names = {
  "be": "bielorusă",
  "ceb": "cebuano",
  "ckb": "kurdă sorani",
  "dum": "olandeză mijlocie",
  "enm": "engleză mijlocie",
  "et": "estoniană",
  "frc": "Cajun French",
  "frm": "franceză mijlocie",
  "gan": "Gan Chinese",
  "gmh": "germană mijlocie înaltă",
  "goh": "germană veche înaltă",
  "gsw": "germană elvețiană",
  "hak": "Hakka Chinese",
  "hsn": "Xiang Chinese",
  "ii": "sichuan yi",
  "kho": "limbp khotaneză",
  "lus": "lusahi",
  "mga": "irlandeză mijlocie",
  "mni": "manipur",
  "mul": "limbi multiple",
  "my": "birmaneză",
  "mzn": "Mazanderani",
  "nan": "Min Nan Chinese",
  "nl": "olandeză",
  "or": "oriya",
  "prg": "Prussian",
  "root": "root",
  "smj": "lule sami",
  "smn": "inari sami",
  "sms": "skolt sami",
  "to": "tonga",
  "tzm": "tamazight central marocană",
  "vot": "votic",
  "wal": "walamo",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese"
};
