const names = {
  "af": "আফ্রিকান্স",
  "as": "আসামি",
  "brx": "বড়ো",
  "ckb": "সোরানি কুর্দিশ",
  "dyo": "জলা-ফনী",
  "dzg": "Dazaga",
  "ee": "এয়ে",
  "fj": "ফিজিও",
  "fo": "ফেরাউনি",
  "frc": "Cajun French",
  "fy": "পশ্চিম ফ্রিসিয়",
  "gan": "Gan Chinese",
  "hsn": "Xiang Chinese",
  "ht": "হাইতিয়ান",
  "ibb": "Ibibio",
  "it": "ইতালীয়",
  "jv": "জাভানি",
  "ki": "কিকু্ইয়ু",
  "kkj": "Kako",
  "kn": "কান্নাড়ী",
  "ks": "কাশ্মীরী",
  "ksh": "Colognian",
  "ku": "কুর্দি",
  "la": "লাটিন",
  "lus": "লুশাই",
  "min": "মিনাঙ্গ্‌কাবাউ",
  "mul": "বহুগুণিতক ভাষাসমূহ",
  "mzn": "Mazanderani",
  "nl": "ডাচ",
  "nnh": "Ngiemboon",
  "nzi": "এন্.জিমা",
  "prg": "Prussian",
  "ps": "পাশ্তু",
  "sa": "সংষ্কৃত",
  "sah": "ইয়াকুট",
  "sba": "Ngambay",
  "so": "সোমালী",
  "ssy": "Saho",
  "swb": "Comorian",
  "te": "তেলেগু",
  "trv": "Taroko",
  "wae": "Walser",
  "wbp": "Warlpiri",
  "wuu": "Wu Chinese",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yi": "য়িদ্দিশ",
  "yue": "Cantonese"
};
