const names = {
  "AC": "جزیرہ اسینشن",
  "AX": "جزائر آلینڈ",
  "BV": "جزیرہ بوویت",
  "CC": "جزائر (کیلنگ) کوکوس",
  "CK": "جزائر کک",
  "CP": "جزیرہ کلپرٹن",
  "DG": "ڈیگو گارشیا",
  "FK": "جزائر فاکلینڈ",
  "FO": "جزائر فیرو",
  "GF": "فرانسیسی گیانا",
  "HM": "جزائر ہرڈ و مکڈونلڈ",
  "IC": "جزائر کناری",
  "IO": "برطانوی بحرہند خطہ",
  "MH": "جزائر مارشل",
  "MP": "جزائر شمالی ماریانا",
  "NF": "جزیرہ نارفوک",
  "PN": "جزائر پٹکیرن",
  "SB": "جزائر سلیمان",
  "TA": "ترسٹان دا کونیا",
  "TC": "جزائر کیکس و ترکیہ",
  "UM": "امریکی بیرونی جزائر",
  "VG": "برطانوی جزائر ورجن",
  "VI": "امریکی جزائر ورجن",
  "aa": "Afar",
  "ace": "Achinese",
  "ada": "Adangme",
  "ady": "Adyghe",
  "af_NA": "افریقی (نامیبیا)",
  "af_ZA": "افریقی (جنوبی افریقہ)",
  "ain": "Ainu",
  "ale": "Aleut",
  "alt": "Southern Altai",
  "an": "Aragonese",
  "anp": "Angika",
  "ar_001": "جدید معیاری عربی",
  "arp": "Arapaho",
  "ast": "Asturian",
  "av": "Avaric",
  "awa": "اودھی",
  "az": "آزربائیجانی",
  "ban": "Balinese",
  "bas": "Basaa",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bin": "Bini",
  "bla": "Siksika",
  "bm": "بامبرا",
  "bm_Latn": "بامبرا (لاطینی)",
  "bm_Latn_ML": "بامبرا (لاطینی, مالی)",
  "bn": "بنگالی",
  "bs": "بوسنی",
  "bug": "Buginese",
  "byn": "Blin",
  "ca": "کتالان",
  "ca_AD": "کتالان (انڈورا)",
  "ca_ES": "کتالان (ہسپانیہ)",
  "ca_FR": "کتالان (فرانس)",
  "ca_IT": "کتالان (اٹلی)",
  "ce": "Chechen",
  "ceb": "Cebuano",
  "ch": "Chamorro",
  "chk": "Chuukese",
  "chm": "Mari",
  "cho": "Choctaw",
  "chy": "Cheyenne",
  "ckb": "سورانی کردی",
  "co": "کارسیکائی",
  "cu": "Church Slavic",
  "cv": "Chuvash",
  "dak": "Dakota",
  "dar": "Dargwa",
  "de_AT": "جرمن (آسٹریا)",
  "de_CH": "جرمن (سوئٹزر لینڈ)",
  "dgr": "Dogrib",
  "dje": "زرمہ",
  "dzg": "Dazaga",
  "eka": "Ekajuk",
  "en_AU": "انگریزی (آسٹریلیا)",
  "en_BB": "انگریزی (بارباڈوس)",
  "en_CA": "انگریزی (کینیڈا)",
  "en_CC": "انگریزی (جزائر (کیلنگ) کوکوس)",
  "en_CK": "انگریزی (جزائر کک)",
  "en_DG": "انگریزی (ڈیگو گارشیا)",
  "en_FK": "انگریزی (جزائر فاکلینڈ)",
  "en_GB": "انگریزی (سلطنت متحدہ)",
  "en_GD": "انگریزی (گریناڈا)",
  "en_IO": "انگریزی (برطانوی بحرہند خطہ)",
  "en_MH": "انگریزی (جزائر مارشل)",
  "en_MP": "انگریزی (جزائر شمالی ماریانا)",
  "en_NF": "انگریزی (جزیرہ نارفولک)",
  "en_NR": "انگریزی (ناورو)",
  "en_PH": "انگریزی (فلپائن)",
  "en_PN": "انگریزی (جزائر پٹکیرن)",
  "en_SB": "انگریزی (جزائر سلیمان)",
  "en_TC": "انگریزی (جزائر کیکس و ترکیہ)",
  "en_UM": "انگریزی (امریکی بیرونی جزائر)",
  "en_US": "انگریزی (ریاستہائے متحدہ)",
  "en_VG": "انگریزی (برطانوی جزائر ورجن)",
  "en_VI": "انگریزی (امریکی جزائر ورجن)",
  "es_ES": "ہسپانوی (ہسپانیہ)",
  "es_IC": "ہسپانوی (جزائر کناری)",
  "es_MX": "ہسپانوی (میکسیکو)",
  "es_PH": "ہسپانوی (فلپائن)",
  "et": "اسٹونی",
  "et_EE": "اسٹونی (اسٹونیا)",
  "ewo": "Ewondo",
  "fa_AF": "فارسی (افغانستان)",
  "ff": "Fulah",
  "fo": "فارويز",
  "fo_FO": "فارويز (جزائرفارو)",
  "fon": "Fon",
  "fr_CA": "فرانسیسی (کینیڈا)",
  "fr_CH": "فرانسیسی (سوئٹزر لینڈ)",
  "fr_CI": "فرانسیسی (کوت داوواغ)",
  "fr_GF": "فرانسیسی (فرانسیسی گیانا)",
  "frc": "Cajun French",
  "fur": "Friulian",
  "fy": "مغربی فریسیائی",
  "fy_NL": "مغربی فریسیائی (نیدر لینڈز)",
  "gan": "Gan Chinese",
  "gd": "سکاٹ گیلِک",
  "gez": "Geez",
  "gil": "Gilbertese",
  "gor": "Gorontalo",
  "gv": "مانوی",
  "gv_IM": "مانوی (آئل آف مین)",
  "gwi": "Gwichʼin",
  "hil": "Hiligaynon",
  "hmn": "Hmong",
  "hr": "کروشین",
  "hup": "Hupa",
  "hy": "ارمینی",
  "hz": "Herero",
  "iba": "Iban",
  "ibb": "Ibibio",
  "ii": "سشوان ی",
  "ii_CN": "سشوان ی (چین)",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "jbo": "Lojban",
  "jv": "جاوانیز",
  "ka": "جارجيائى",
  "kac": "Kachin",
  "kaj": "Jju",
  "kbd": "Kabardian",
  "kcg": "Tyap",
  "kde": "ماكونده",
  "kea": "كابويرديانو",
  "kfo": "Koro",
  "kha": "Khasi",
  "khq": "كويرا شيني",
  "ki_KE": "کیکویو (کینیا)",
  "kj": "Kuanyama",
  "kkj": "Kako",
  "kl": "کلالیسٹ",
  "kln": "كالينجين",
  "kmb": "Kimbundu",
  "kn": "کنڑ",
  "kn_IN": "کنڑ (بھارت)",
  "kpe": "Kpelle",
  "kr": "Kanuri",
  "krc": "Karachay-Balkar",
  "krl": "Karelian",
  "kru": "Kurukh",
  "ksh": "Colognian",
  "ku": "کرد",
  "kum": "Kumyk",
  "kv": "Komi",
  "kw": "کورنوالی",
  "kw_GB": "کورنوالی (سلطنت متحدہ)",
  "lad": "Ladino",
  "lb": "لکسمبرگی",
  "lb_LU": "لکسمبرگی (لگژمبرگ)",
  "lez": "Lezghian",
  "li": "Limburgish",
  "lt": "لتھُواینین",
  "lu": "لبا-كاتانجا",
  "lun": "Lunda",
  "lus": "Mizo",
  "lv": "لٹويای",
  "lv_LV": "لٹويای (لٹویا)",
  "mad": "Madurese",
  "mag": "مگہی",
  "mai": "Maithili",
  "mak": "Makasar",
  "mas": "ماسای",
  "mdf": "Moksha",
  "men": "Mende",
  "mh": "Marshallese",
  "mic": "Micmac",
  "min": "Minangkabau",
  "mn": "منگؤلی",
  "mni": "Manipuri",
  "mos": "Mossi",
  "ms": "مالائی",
  "mul": "Multiple Languages",
  "mus": "Creek",
  "mwl": "Mirandese",
  "myv": "Erzya",
  "mzn": "Mazanderani",
  "na": "Nauru",
  "nap": "Neapolitan",
  "nds": "Low German",
  "new": "Newari",
  "ng": "Ndonga",
  "nia": "Nias",
  "niu": "Niuean",
  "nl_BE": "ڈچ (بیلجیم)",
  "nmg": "كوايسو",
  "nn": "نورویجینی نینورسک",
  "nnh": "Ngiemboon",
  "nog": "Nogai",
  "nr": "South Ndebele",
  "nv": "Navajo",
  "oc": "آكسیٹان",
  "or": "اورِیا",
  "os_RU": "اوسیٹک (روس)",
  "pag": "Pangasinan",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palauan",
  "pl": "پولستانی",
  "prg": "Prussian",
  "pt_BR": "پُرتگالی (برازیل)",
  "pt_PT": "پُرتگالی (پرتگال)",
  "quc": "كيشی",
  "rap": "Rapanui",
  "rar": "Rarotongan",
  "ro": "رومانوی",
  "ro_MD": "رومانوی (مالدووا)",
  "ro_RO": "رومانوی (رومانیا)",
  "root": "Root",
  "ru_RU": "روسی (روس)",
  "rup": "Aromanian",
  "sa": "سَنسکرِت",
  "sad": "Sandawe",
  "sah": "Sakha",
  "sat": "Santali",
  "sba": "Ngambay",
  "sc": "Sardinian",
  "scn": "Sicilian",
  "sco": "Scots",
  "ses": "كويرابورو سينی",
  "sg": "سانجو",
  "sg_CF": "سانجو (وسط افریقی جمہوریہ)",
  "shn": "Shan",
  "snk": "Soninke",
  "sr": "صربی",
  "srn": "Sranan Tongo",
  "ssy": "Saho",
  "suk": "Sukuma",
  "sv_AX": "سویڈش (جزائر ایلانڈ)",
  "swb": "Comorian",
  "syr": "Syriac",
  "tem": "Timne",
  "tig": "Tigre",
  "tl": "Tagalog",
  "trv": "Taroko",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "tyv": "Tuvinian",
  "udm": "Udmurt",
  "ug": "آئغور",
  "ug_Arab": "آئغور (عربی)",
  "ug_Arab_CN": "آئغور (عربی, چین)",
  "ug_CN": "آئغور (چین)",
  "umb": "Umbundu",
  "vo": "Volapük",
  "wa": "Walloon",
  "wae": "Walser",
  "wal": "Wolaytta",
  "war": "Waray",
  "wbp": "Warlpiri",
  "xal": "Kalmyk",
  "yav": "Yangben",
  "ybb": "Yemba",
  "yue": "Cantonese",
  "zgh": "معیاری مراقشی تمازیقی",
  "zh_Hans": "چینی (آسان)",
  "zh_Hant": "چینی (روایتی)",
  "zun": "Zuni",
  "zza": "Zaza"
};
