const names = {
  "001": "Y Byd",
  "002": "Affrica",
  "003": "Gogledd America",
  "005": "De America",
  "009": "Oceania",
  "011": "Gorllewin Affrica",
  "013": "Canolbarth America",
  "014": "Dwyrain Affrica",
  "015": "Gogledd Affrica",
  "017": "Canol Affrica",
  "018": "Deheudir Affrica",
  "019": "Yr Amerig",
  "021": "America i’r Gogledd o Fecsico",
  "029": "Y Caribî",
  "030": "Dwyrain Asia",
  "034": "De Asia",
  "035": "De-Ddwyrain Asia",
  "039": "De Ewrop",
  "053": "Awstralasia",
  "054": "Melanesia",
  "057": "Rhanbarth Micronesia",
  "061": "Polynesia",
  "062": "De-Ganol Asia",
  "142": "Asia",
  "143": "Canol Asia",
  "145": "Gorllewin Asia",
  "150": "Ewrop",
  "151": "Dwyrain Ewrop",
  "154": "Gogledd Ewrop",
  "155": "Gorllewin Ewrop",
  "172": "Cymanwlad y Gwladwriaethau Annibynnol",
  "200": "Tsiecoslofacia",
  "202": "Affrica Is-Sahara",
  "419": "America Ladin",
  "830": "Ynysoedd y Sianel",
  "AC": "Ynys Ascension",
  "AD": "Andorra",
  "AE": "Emiradau Arabaidd Unedig",
  "AF": "Afghanistan",
  "AG": "Antigua a Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Antilles yr Iseldiroedd",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Yr Ariannin",
  "AS": "Samoa America",
  "AT": "Awstria",
  "AU": "Awstralia",
  "AW": "Aruba",
  "AX": "Ynysoedd Åland",
  "AZ": "Azerbaijan",
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "Albanwr Cawcasaidd",
  "Ahom": "Ahom",
  "Arab": "Arabaidd",
  "Aran": "Nastaliq",
  "Armi": "Aramaeg Ymerodrol",
  "Armn": "Armenaidd",
  "Avst": "Avestan",
  "BA": "Bosnia a Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Gwlad Belg",
  "BF": "Burkina Faso",
  "BG": "Bwlgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolifia",
  "BQ": "Antilles yr Iseldiroedd",
  "BR": "Brasil",
  "BS": "Y Bahamas",
  "BT": "Bhutan",
  "BV": "Ynys Bouvet",
  "BW": "Botswana",
  "BY": "Belarws",
  "BZ": "Belize",
  "Bali": "Balïaidd",
  "Bamu": "Bamwm",
  "Bass": "Bassa Vah",
  "Batk": "Batak",
  "Beng": "Bangla",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Buginese",
  "Buhd": "Buhid",
  "CA": "Canada",
  "CC": "Ynysoedd Cocos (Keeling)",
  "CD": "Y Congo - Kinshasa",
  "CF": "Gweriniaeth Canolbarth Affrica",
  "CG": "Y Congo - Brazzaville",
  "CH": "Y Swistir",
  "CI": "Côte d’Ivoire",
  "CK": "Ynysoedd Cook",
  "CL": "Chile",
  "CM": "Camerŵn",
  "CN": "Tsieina",
  "CO": "Colombia",
  "CP": "Ynys Clipperton",
  "CR": "Costa Rica",
  "CS": "Serbia a Montenegro",
  "CU": "Ciwba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Ynys y Nadolig",
  "CY": "Cyprus",
  "CZ": "Tsiecia",
  "Cakm": "Chakma",
  "Cans": "Maes Llafur Unedig Canada",
  "Cari": "Carian",
  "Cham": "Swyn",
  "Cher": "Cherokee",
  "Chrs": "Chorasmian",
  "Cirt": "Cirth",
  "Copt": "Coptig",
  "Cprt": "Cyprus",
  "Cyrl": "Cyrilig",
  "Cyrs": "Cyrillig Slafonaidd yr Hen Eglwys",
  "DD": "Dwyrain yr Almaen",
  "DE": "Yr Almaen",
  "DG": "Diego Garcia",
  "DJ": "Djibouti",
  "DK": "Denmarc",
  "DM": "Dominica",
  "DO": "Gweriniaeth Dominica",
  "DZ": "Algeria",
  "Deva": "Devanagari",
  "Diak": "Deifio Akuru",
  "Dogr": "Dogra",
  "Dsrt": "Deseret",
  "Dupl": "Llaw-fer Duployan",
  "EA": "Ceuta a Melilla",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Yr Aifft",
  "EH": "Gorllewin Sahara",
  "ER": "Eritrea",
  "ES": "Sbaen",
  "ET": "Ethiopia",
  "EU": "Yr Undeb Ewropeaidd",
  "EZ": "Ardal yr Ewro",
  "Egyd": "Demotig yr Aifft",
  "Egyh": "Hiraratig yr Aifft",
  "Egyp": "Hieroglyffau yr Aifft",
  "Elba": "Elbasan",
  "Elym": "Elymaig",
  "Ethi": "Ethiopig",
  "FI": "Y Ffindir",
  "FJ": "Fiji",
  "FK": "Ynysoedd y Falkland/Malvinas",
  "FM": "Micronesia",
  "FO": "Ynysoedd Ffaro",
  "FR": "Ffrainc",
  "FX": "Ffrainc Fetropolitan",
  "GA": "Gabon",
  "GB": "Y Deyrnas Unedig",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "Guyane Ffrengig",
  "GG": "Ynys y Garn",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Yr Ynys Las",
  "GM": "Gambia",
  "GN": "Guinée",
  "GP": "Guadeloupe",
  "GQ": "Guinea Gyhydeddol",
  "GR": "Gwlad Groeg",
  "GS": "De Georgia ac Ynysoedd Sandwich y De",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guiné-Bissau",
  "GY": "Guyana",
  "Geok": "Khutsuri Sioraidd",
  "Geor": "Georgaidd",
  "Glag": "Glagolitic",
  "Gong": "Gunjala Gondi",
  "Gonm": "Masaram Gondi",
  "Goth": "Gothig",
  "Gran": "Grantha",
  "Grek": "Groegaidd",
  "Gujr": "Gwjarataidd",
  "Guru": "Gwrmwci",
  "HK": "Hong Kong SAR Tseina",
  "HM": "Ynys Heard ac Ynysoedd McDonald",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hwngari",
  "Hanb": "Han gyda Bopomofo",
  "Hang": "Hangul",
  "Hani": "Han",
  "Hano": "Hanunoo",
  "Hans": "Symledig",
  "Hant": "Traddodiadol",
  "Hatr": "Hatran",
  "Hebr": "Hebreig",
  "Hira": "Hiragana",
  "Hluw": "Hieroglyffau Anatolian",
  "Hmng": "Pahawh Hmong",
  "Hmnp": "Nyiakeng Puachue Hmong",
  "Hrkt": "Syllwyddor Japaneaidd",
  "Hung": "Hen Hwngari",
  "IC": "Yr Ynysoedd Dedwydd",
  "ID": "Indonesia",
  "IE": "Iwerddon",
  "IL": "Israel",
  "IM": "Ynys Manaw",
  "IN": "India",
  "IO": "Tiriogaeth Brydeinig Cefnfor India",
  "IQ": "Irac",
  "IR": "Iran",
  "IS": "Gwlad yr Iâ",
  "IT": "Yr Eidal",
  "Inds": "Indus",
  "Ital": "Hen Italeg",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Gwlad Iorddonen",
  "JP": "Japan",
  "Jamo": "Jamo",
  "Java": "Jafanese",
  "Jpan": "Japaneaidd",
  "Jurc": "Jurchen",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts a Nevis",
  "KP": "Gogledd Korea",
  "KR": "De Korea",
  "KW": "Kuwait",
  "KY": "Ynysoedd Cayman",
  "KZ": "Kazakstan",
  "Kali": "Kayah Li",
  "Kana": "Catacana",
  "Khar": "Kharoshthi",
  "Khmr": "Chmeraidd",
  "Khoj": "Khojki",
  "Kits": "Sgript fach Khitan",
  "Knda": "Canaraidd",
  "Kore": "Coreaidd",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "LA": "Laos",
  "LB": "Libanus",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Lwcsembwrg",
  "LV": "Latfia",
  "LY": "Libya",
  "Lana": "Lanna",
  "Laoo": "Laoaidd",
  "Latf": "Lladin Fraktur",
  "Latg": "Lladin Gaeleg",
  "Latn": "Lladin",
  "Lepc": "Lepcha",
  "Limb": "Limbu",
  "Lina": "Llinol A.",
  "Linb": "Llinol B.",
  "Lisu": "Fraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydian",
  "MA": "Moroco",
  "MC": "Monaco",
  "MD": "Moldofa",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Ynysoedd Marshall",
  "MI": "Ynysoedd Midway",
  "MK": "Gogledd Macedonia",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macau RhGA Tsieina",
  "MP": "Ynysoedd Gogledd Mariana",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Y Maldives",
  "MW": "Malawi",
  "MX": "Mecsico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "Mandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "Hieroglyffau Maya",
  "Medf": "Medefaidrin",
  "Mend": "Mende",
  "Merc": "Melltigedig Meroitic",
  "Mero": "Meroitic",
  "Mlym": "Malayalamaidd",
  "Modi": "Modi",
  "Mong": "Mongolaidd",
  "Moon": "Lleuad",
  "Mroo": "Mro",
  "Mtei": "Meitei Mayek",
  "Mult": "Multani",
  "Mymr": "Myanmaraidd",
  "NA": "Namibia",
  "NC": "Caledonia Newydd",
  "NE": "Niger",
  "NF": "Ynys Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Yr Iseldiroedd",
  "NO": "Norwy",
  "NP": "Nepal",
  "NR": "Nauru",
  "NT": "Parth Niwtral",
  "NU": "Niue",
  "NZ": "Seland Newydd",
  "Nand": "Nandinagari",
  "Narb": "Hen Ogledd Arabia",
  "Nbat": "Nabataean",
  "Newa": "Newa",
  "Nkgb": "Naxi Geba",
  "Nkoo": "N’Ko",
  "Nshu": "Nüshu",
  "OM": "Oman",
  "Ogam": "Ogham",
  "Olck": "Ol Chiki",
  "Orkh": "Orkhon",
  "Orya": "Orïaidd",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "PA": "Panama",
  "PC": "Tiriogaeth Ymddiriedolaeth Ynysoedd y Môr Tawel",
  "PE": "Periw",
  "PF": "Polynesia Ffrengig",
  "PG": "Papua Guinea Newydd",
  "PH": "Y Philipinau",
  "PK": "Pakistan",
  "PL": "Gwlad Pwyl",
  "PM": "Saint-Pierre-et-Miquelon",
  "PN": "Ynysoedd Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Tiriogaethau Palesteinaidd",
  "PT": "Portiwgal",
  "PU": "Ynysoedd Môr Tawel Amrywiol yr Unol Daleithiau",
  "PW": "Palau",
  "PY": "Paraguay",
  "PZ": "Parth Camlas Panama",
  "Palm": "Palmyrene",
  "Pauc": "Pau Cin Hau",
  "Perm": "Hen Permig",
  "Phag": "Phags-pa",
  "Phli": "Pahlavi arysgrif",
  "Phlp": "Salmydd Pahlavi",
  "Phlv": "Llyfr Pahlavi",
  "Phnx": "Phoenician",
  "Plrd": "Seinegol Pollard",
  "Prti": "Parthian arysgrif",
  "QA": "Qatar",
  "QO": "Oceania Bellennig",
  "Qaag": "Zawgyi",
  "RE": "Réunion",
  "RO": "Rwmania",
  "RS": "Serbia",
  "RU": "Rwsia",
  "RW": "Rwanda",
  "Rjng": "Rejang",
  "Rohg": "Hanifi Rohingya",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "SA": "Saudi Arabia",
  "SB": "Ynysoedd Solomon",
  "SC": "Seychelles",
  "SD": "Swdan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Saint Helena",
  "SI": "Slofenia",
  "SJ": "Svalbard a Jan Mayen",
  "SK": "Slofacia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "De Swdan",
  "ST": "São Tomé a Príncipe",
  "SU": "Undeb Gweriniaethwyr Sosialaidd Sofietaidd",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "Samr": "Samariad",
  "Sara": "Sarati",
  "Sarb": "Hen Dde Arabia",
  "Saur": "Saurashtra",
  "Sgnw": "SignWriting",
  "Shaw": "Shavian",
  "Shrd": "Sharada",
  "Sidd": "Siddham",
  "Sind": "Khudawadi",
  "Sinh": "Sinhanaidd",
  "Sogd": "Sogdian",
  "Sogo": "Hen Sogdian",
  "Sora": "Sora Sompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundaneg",
  "Sylo": "Syloti Nagri",
  "Syrc": "Syrieg",
  "Syre": "Syrieg Estrangelo",
  "Syrj": "Syrieg y Gorllewin",
  "Syrn": "Syrieg y Dwyrain",
  "TA": "Tristan da Cunha",
  "TC": "Ynysoedd Turks a Caicos",
  "TD": "Tchad",
  "TF": "Tiroedd Deheuol ac Antarctig Ffrainc",
  "TG": "Togo",
  "TH": "Gwlad Thai",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Twrci",
  "TT": "Trinidad a Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "Tagb": "Tagbanwa",
  "Takr": "Takri",
  "Tale": "Tai Le",
  "Talu": "Tai Lue Newydd",
  "Taml": "Tamilaidd",
  "Tang": "Tangut",
  "Tavt": "Tai Viet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "Tifinagh",
  "Tglg": "Tagalog",
  "Thaa": "Thaana",
  "Thai": "Tai",
  "Tibt": "Tibetaidd",
  "Tirh": "Tirhuta",
  "UA": "Wcráin",
  "UG": "Uganda",
  "UM": "Ynysoedd Pellennig UDA",
  "UN": "y Cenhedloedd Unedig",
  "US": "Yr Unol Daleithiau",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "Ugar": "Ugaritic",
  "VA": "Y Fatican",
  "VC": "Saint Vincent a’r Grenadines",
  "VD": "Gogledd Fietnam",
  "VE": "Venezuela",
  "VG": "Ynysoedd Gwyryf Prydain",
  "VI": "Ynysoedd Gwyryf yr Unol Daleithiau",
  "VN": "Fietnam",
  "VU": "Vanuatu",
  "Vaii": "Vai",
  "Visp": "Araith Weladwy",
  "WF": "Wallis a Futuna",
  "WK": "Ynys Wake",
  "WS": "Samoa",
  "Wara": "Varang Kshiti",
  "Wcho": "Wancho",
  "Wole": "Woleai",
  "XA": "Acenion Ffug",
  "XB": "Bidi Ffug",
  "XK": "Kosovo",
  "Xpeo": "Hen Berseg",
  "Xsux": "Cuneiform Sumero-Akkadian",
  "YD": "Gweriniaeth Ddemocrataidd People’s Yemen",
  "YE": "Yemen",
  "YT": "Mayotte",
  "Yezi": "Yezidi",
  "Yiii": "Yi",
  "ZA": "De Affrica",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "ZZ": "Rhanbarth Anhysbys",
  "Zanb": "Sgwâr Zanabazar",
  "Zinh": "Etifeddol",
  "Zmth": "Nodiant Mathemategol",
  "Zsye": "Emoji",
  "Zsym": "Symbolau",
  "Zxxx": "Anysgrifenedig",
  "Zyyy": "Cyffredin",
  "Zzzz": "Sgript anhysbys",
  "aa": "Affareg",
  "ab": "Abchaseg",
  "ace": "Acehneg",
  "ach": "Acoli",
  "ada": "Adangmeg",
  "ady": "Circaseg Gorllewinol",
  "ae": "Afestaneg",
  "aeb": "Arabeg Tunisia",
  "af": "Affricâneg",
  "af_NA": "Affricâneg (Namibia)",
  "af_ZA": "Affricâneg (De Affrica)",
  "afa": "Iaith Affro-Asiatig",
  "afh": "Affrihili",
  "agq": "Aghemeg",
  "ain": "Ainŵeg",
  "ak": "Acaneg",
  "ak_GH": "Acaneg (Ghana)",
  "akk": "Acadeg",
  "akz": "Alabamäeg",
  "ale": "Alewteg",
  "alg": "Iaith Algonquian",
  "aln": "Ghegeg Albania",
  "alt": "Altäeg Deheuol",
  "am": "Amhareg",
  "am_ET": "Amhareg (Ethiopia)",
  "an": "Aragoneg",
  "ang": "Hen Saesneg",
  "anp": "Angika",
  "apa": "Iaith Apache",
  "ar": "Arabeg",
  "ar_001": "Arabeg Modern Safonol",
  "ar_AE": "Arabeg (Emiradau Arabaidd Unedig)",
  "ar_BH": "Arabeg (Bahrain)",
  "ar_DJ": "Arabeg (Djibouti)",
  "ar_DZ": "Arabeg (Algeria)",
  "ar_EG": "Arabeg (Yr Aifft)",
  "ar_EH": "Arabeg (Gorllewin Sahara)",
  "ar_ER": "Arabeg (Eritrea)",
  "ar_IL": "Arabeg (Israel)",
  "ar_IQ": "Arabeg (Irac)",
  "ar_JO": "Arabeg (Gwlad Iorddonen)",
  "ar_KM": "Arabeg (Comoros)",
  "ar_KW": "Arabeg (Kuwait)",
  "ar_LB": "Arabeg (Libanus)",
  "ar_LY": "Arabeg (Libya)",
  "ar_MA": "Arabeg (Moroco)",
  "ar_MR": "Arabeg (Mauritania)",
  "ar_OM": "Arabeg (Oman)",
  "ar_PS": "Arabeg (Tiriogaethau Palesteinaidd)",
  "ar_QA": "Arabeg (Qatar)",
  "ar_SA": "Arabeg (Saudi Arabia)",
  "ar_SD": "Arabeg (Swdan)",
  "ar_SO": "Arabeg (Somalia)",
  "ar_SS": "Arabeg (De Swdan)",
  "ar_SY": "Arabeg (Syria)",
  "ar_TD": "Arabeg (Tchad)",
  "ar_TN": "Arabeg (Tunisia)",
  "ar_YE": "Arabeg (Yemen)",
  "arc": "Aramaeg",
  "arn": "Arawcaneg",
  "aro": "Araonaeg",
  "arp": "Arapaho",
  "arq": "Arabeg Algeria",
  "ars": "Arabeg Najdi",
  "art": "Iaith Artiffisial",
  "arw": "Arawaceg",
  "ary": "Arabeg Moroco",
  "arz": "Arabeg yr Aifft",
  "as": "Asameg",
  "as_IN": "Asameg (India)",
  "asa": "Asw",
  "ase": "Iaith Arwyddion America",
  "ast": "Astwrianeg",
  "ath": "Iaith Athapascan",
  "aus": "Iaith Awstralia",
  "av": "Afareg",
  "avk": "Kotava",
  "awa": "Awadhi",
  "ay": "Aymareg",
  "az": "Aserbaijaneg",
  "az_AZ": "Aserbaijaneg (Azerbaijan)",
  "az_Arab": "Aserbaijaneg Deheuol",
  "az_Cyrl": "Aserbaijaneg (Cyrilig)",
  "az_Cyrl_AZ": "Aserbaijaneg (Cyrilig, Azerbaijan)",
  "az_Latn": "Aserbaijaneg (Lladin)",
  "az_Latn_AZ": "Aserbaijaneg (Lladin, Azerbaijan)",
  "azb": "Aserbaijaneg Deheuol",
  "ba": "Bashcorteg",
  "bad": "Banda",
  "bai": "Iaith Bamileke",
  "bal": "Balwtsi",
  "ban": "Balïeg",
  "bar": "Bavarian",
  "bas": "Basâeg",
  "bat": "Iaith Baltig",
  "bax": "Bamwmeg",
  "bbc": "Batak Toba",
  "bbj": "Ghomala",
  "be": "Belarwseg",
  "be_BY": "Belarwseg (Belarws)",
  "bej": "Bejäeg",
  "bem": "Bembeg",
  "ber": "Berber",
  "bew": "Betawi",
  "bez": "Bena",
  "bfd": "Baffwteg",
  "bfq": "Badaga",
  "bg": "Bwlgareg",
  "bg_BG": "Bwlgareg (Bwlgaria)",
  "bgn": "Balochi Gorllewinol",
  "bh": "Bihari",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bik": "Bikol",
  "bin": "Bini",
  "bjn": "Banjar",
  "bkm": "Comeg",
  "bla": "Siksika",
  "bm": "Bambareg",
  "bm_Latn": "Bambareg (Lladin)",
  "bm_Latn_ML": "Bambareg (Lladin, Mali)",
  "bn": "Bengaleg",
  "bn_BD": "Bengaleg (Bangladesh)",
  "bn_IN": "Bengaleg (India)",
  "bnt": "Bantu",
  "bo": "Tibeteg",
  "bo_CN": "Tibeteg (Tsieina)",
  "bo_IN": "Tibeteg (India)",
  "bpy": "Bishnupriya",
  "bqi": "Bakhtiari",
  "br": "Llydaweg",
  "br_FR": "Llydaweg (Ffrainc)",
  "bra": "Braj",
  "brh": "Brahui",
  "brx": "Bodo",
  "bs": "Bosnieg",
  "bs_BA": "Bosnieg (Bosnia a Hercegovina)",
  "bs_Cyrl": "Bosnieg (Cyrilig)",
  "bs_Cyrl_BA": "Bosnieg (Cyrilig, Bosnia a Hercegovina)",
  "bs_Latn": "Bosnieg (Lladin)",
  "bs_Latn_BA": "Bosnieg (Lladin, Bosnia a Hercegovina)",
  "bss": "Acwseg",
  "btk": "Batak",
  "bua": "Bwriateg",
  "bug": "Bwginaeg",
  "bum": "Bwlw",
  "byn": "Blin",
  "byv": "Medumba",
  "ca": "Catalaneg",
  "ca_AD": "Catalaneg (Andorra)",
  "ca_ES": "Catalaneg (Sbaen)",
  "ca_FR": "Catalaneg (Ffrainc)",
  "ca_IT": "Catalaneg (Yr Eidal)",
  "cad": "Cado",
  "cai": "Iaith Indiaidd Canol America",
  "car": "Caribeg",
  "cau": "Iaith Cawcasaidd",
  "cay": "Cayuga",
  "cch": "Atsameg",
  "ccp": "Tsiacma",
  "ce": "Tsietsieneg",
  "ceb": "Cebuano",
  "cel": "Iaith Geltaidd",
  "cgg": "Tsiga",
  "ch": "Tsiamorro",
  "chb": "Chibcha",
  "chg": "Chagatai",
  "chk": "Chuukaeg",
  "chm": "Marieg",
  "chn": "Chinook Jargon",
  "cho": "Siocto",
  "chp": "Chipewyan",
  "chr": "Tsierocî",
  "chy": "Cheyenne",
  "cic": "Chickasaw",
  "ckb": "Cwrdeg Sorani",
  "cmc": "Iaith Chamig",
  "co": "Corseg",
  "cop": "Copteg",
  "cpe": "Creole neu Pidgin o Loegr",
  "cpf": "Creole neu Pidgin o Ffrainc",
  "cpp": "Creole neu Pidgin o Bortiwgal",
  "cps": "Capiznon",
  "cr": "Cri",
  "crh": "Tyrceg y Crimea",
  "crp": "Creole neu Pidgin",
  "crs": "Ffrangeg Seselwa Creole",
  "cs": "Tsieceg",
  "cs_CZ": "Tsieceg (Gweriniaeth Tsiec)",
  "csb": "Kashubian",
  "cu": "Hen Slafoneg",
  "cus": "Iaith Cushitic",
  "cv": "Tshwfasheg",
  "cy": "Cymraeg",
  "cy_GB": "Cymraeg (Y Deyrnas Unedig)",
  "da": "Daneg",
  "da_DK": "Daneg (Denmarc)",
  "da_GL": "Daneg (Yr Ynys Las)",
  "dak": "Dacotaeg",
  "dar": "Dargwa",
  "dav": "Taita",
  "day": "Dayak",
  "de": "Almaeneg",
  "de_AT": "Almaeneg (Awstria)",
  "de_BE": "Almaeneg (Gwlad Belg)",
  "de_CH": "Almaeneg (Y Swistir)",
  "de_DE": "Almaeneg (Yr Almaen)",
  "de_LI": "Almaeneg (Liechtenstein)",
  "de_LU": "Almaeneg (Lwcsembwrg)",
  "del": "Delaware",
  "den": "Slave",
  "dgr": "Dogrib",
  "din": "Dinca",
  "dje": "Sarmaeg",
  "doi": "Dogri",
  "dra": "Iaith Dravidian",
  "dsb": "Sorbeg Isaf",
  "dtp": "Central Dusun",
  "dua": "Diwaleg",
  "dum": "Iseldireg Canol",
  "dv": "Difehi",
  "dyo": "Jola-Fonyi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "dz_BT": "Dzongkha (Bhutan)",
  "dzg": "Dazaga",
  "ebu": "Embw",
  "ee": "Ewe",
  "ee_GH": "Ewe (Ghana)",
  "ee_TG": "Ewe (Togo)",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "Hen Eiffteg",
  "eka": "Ekajuk",
  "el": "Groeg",
  "el_CY": "Groeg (Cyprus)",
  "el_GR": "Groeg (Gwlad Groeg)",
  "elx": "Elameg",
  "en": "Saesneg",
  "en_AG": "Saesneg (Antigua a Barbuda)",
  "en_AI": "Saesneg (Anguilla)",
  "en_AS": "Saesneg (Samoa America)",
  "en_AU": "Saesneg (Awstralia)",
  "en_BB": "Saesneg (Barbados)",
  "en_BE": "Saesneg (Gwlad Belg)",
  "en_BM": "Saesneg (Bermuda)",
  "en_BS": "Saesneg (Y Bahamas)",
  "en_BW": "Saesneg (Botswana)",
  "en_BZ": "Saesneg (Belize)",
  "en_CA": "Saesneg (Canada)",
  "en_CC": "Saesneg (Ynysoedd Cocos (Keeling))",
  "en_CK": "Saesneg (Ynysoedd Cook)",
  "en_CM": "Saesneg (Camerŵn)",
  "en_CX": "Saesneg (Ynys y Nadolig)",
  "en_DG": "Saesneg (Diego Garcia)",
  "en_DM": "Saesneg (Dominica)",
  "en_Dsrt": "Saesneg (Deseret)",
  "en_ER": "Saesneg (Eritrea)",
  "en_FJ": "Saesneg (Fiji)",
  "en_FK": "Saesneg (Ynysoedd y Falkland/Malvinas)",
  "en_FM": "Saesneg (Micronesia)",
  "en_GB": "Saesneg (Y Deyrnas Unedig)",
  "en_GD": "Saesneg (Grenada)",
  "en_GG": "Saesneg (Ynys y Garn)",
  "en_GH": "Saesneg (Ghana)",
  "en_GI": "Saesneg (Gibraltar)",
  "en_GM": "Saesneg (Gambia)",
  "en_GU": "Saesneg (Guam)",
  "en_GY": "Saesneg (Guyana)",
  "en_HK": "Saesneg (Hong Kong RhGA Tsieina)",
  "en_IE": "Saesneg (Iwerddon)",
  "en_IM": "Saesneg (Ynys Manaw)",
  "en_IN": "Saesneg (India)",
  "en_IO": "Saesneg (Tiriogaeth Brydeinig Cefnfor India)",
  "en_JE": "Saesneg (Jersey)",
  "en_JM": "Saesneg (Jamaica)",
  "en_KE": "Saesneg (Kenya)",
  "en_KI": "Saesneg (Kiribati)",
  "en_KN": "Saesneg (Saint Kitts a Nevis)",
  "en_KY": "Saesneg (Ynysoedd Cayman)",
  "en_LC": "Saesneg (Saint Lucia)",
  "en_LR": "Saesneg (Liberia)",
  "en_LS": "Saesneg (Lesotho)",
  "en_MG": "Saesneg (Madagascar)",
  "en_MH": "Saesneg (Ynysoedd Marshall)",
  "en_MO": "Saesneg (Macau RhGA Tsieina)",
  "en_MP": "Saesneg (Ynysoedd Gogledd Mariana)",
  "en_MS": "Saesneg (Montserrat)",
  "en_MT": "Saesneg (Malta)",
  "en_MU": "Saesneg (Mauritius)",
  "en_MW": "Saesneg (Malawi)",
  "en_MY": "Saesneg (Malaysia)",
  "en_NA": "Saesneg (Namibia)",
  "en_NF": "Saesneg (Ynys Norfolk)",
  "en_NG": "Saesneg (Nigeria)",
  "en_NR": "Saesneg (Nauru)",
  "en_NU": "Saesneg (Niue)",
  "en_NZ": "Saesneg (Seland Newydd)",
  "en_PG": "Saesneg (Papua Guinea Newydd)",
  "en_PH": "Saesneg (Pilipinas)",
  "en_PK": "Saesneg (Pakistan)",
  "en_PN": "Saesneg (Ynysoedd Pitcairn)",
  "en_PR": "Saesneg (Puerto Rico)",
  "en_PW": "Saesneg (Palau)",
  "en_RW": "Saesneg (Rwanda)",
  "en_SB": "Saesneg (Ynysoedd Solomon)",
  "en_SC": "Saesneg (Seychelles)",
  "en_SD": "Saesneg (Swdan)",
  "en_SG": "Saesneg (Singapore)",
  "en_SH": "Saesneg (Saint Helena)",
  "en_SL": "Saesneg (Sierra Leone)",
  "en_SS": "Saesneg (De Swdan)",
  "en_SX": "Saesneg (Sint Maarten)",
  "en_SZ": "Saesneg (Gwlad Swazi)",
  "en_TC": "Saesneg (Ynysoedd Turks a Caicos)",
  "en_TK": "Saesneg (Tokelau)",
  "en_TO": "Saesneg (Tonga)",
  "en_TT": "Saesneg (Trinidad a Tobago)",
  "en_TV": "Saesneg (Tuvalu)",
  "en_TZ": "Saesneg (Tanzania)",
  "en_UG": "Saesneg (Uganda)",
  "en_UM": "Saesneg (Ynysoedd Pellennig UDA)",
  "en_US": "Saesneg (Yr Unol Daleithiau)",
  "en_VC": "Saesneg (Saint Vincent a’r Grenadines)",
  "en_VG": "Saesneg (Ynysoedd Gwyryf Prydain)",
  "en_VI": "Saesneg (Ynysoedd Gwyryf yr Unol Daleithiau)",
  "en_VU": "Saesneg (Vanuatu)",
  "en_WS": "Saesneg (Samoa)",
  "en_ZA": "Saesneg (De Affrica)",
  "en_ZM": "Saesneg (Zambia)",
  "en_ZW": "Saesneg (Zimbabwe)",
  "enm": "Saesneg Canol",
  "eo": "Esperanto",
  "es": "Sbaeneg",
  "es_419": "Sbaeneg America Ladin",
  "es_AR": "Sbaeneg (Yr Ariannin)",
  "es_BO": "Sbaeneg (Bolifia)",
  "es_CL": "Sbaeneg (Chile)",
  "es_CO": "Sbaeneg (Colombia)",
  "es_CR": "Sbaeneg (Costa Rica)",
  "es_CU": "Sbaeneg (Ciwba)",
  "es_DO": "Sbaeneg (Gweriniaeth Dominica)",
  "es_EA": "Sbaeneg (Ceuta a Melilla)",
  "es_EC": "Sbaeneg (Ecuador)",
  "es_ES": "Sbaeneg (Sbaen)",
  "es_GQ": "Sbaeneg (Guinea Gyhydeddol)",
  "es_GT": "Sbaeneg (Guatemala)",
  "es_HN": "Sbaeneg (Honduras)",
  "es_IC": "Sbaeneg (Yr Ynysoedd Dedwydd)",
  "es_MX": "Sbaeneg (Mecsico)",
  "es_NI": "Sbaeneg (Nicaragua)",
  "es_PA": "Sbaeneg (Panama)",
  "es_PE": "Sbaeneg (Periw)",
  "es_PH": "Sbaeneg (Pilipinas)",
  "es_PR": "Sbaeneg (Puerto Rico)",
  "es_PY": "Sbaeneg (Paraguay)",
  "es_SV": "Sbaeneg (El Salvador)",
  "es_US": "Sbaeneg (Yr Unol Daleithiau)",
  "es_UY": "Sbaeneg (Uruguay)",
  "es_VE": "Sbaeneg (Venezuela)",
  "esu": "Central Yupik",
  "et": "Estoneg",
  "et_EE": "Estoneg (Estonia)",
  "eu": "Basgeg",
  "eu_ES": "Basgeg (Sbaen)",
  "ewo": "Ewondo",
  "ext": "Extremadureg",
  "fa": "Perseg",
  "fa_AF": "Perseg (Afghanistan)",
  "fa_IR": "Perseg (Iran)",
  "fan": "Fang",
  "fat": "Ffanti",
  "ff": "Ffwla",
  "ff_Adlm": "Fula (Adlam)",
  "ff_CM": "Ffwla (Camerŵn)",
  "ff_GN": "Ffwla (Guinée)",
  "ff_MR": "Ffwla (Mauritania)",
  "ff_SN": "Ffwla (Sénégal)",
  "fi": "Ffinneg",
  "fi_FI": "Ffinneg (Y Ffindir)",
  "fil": "Ffilipineg",
  "fit": "Ffinneg Tornedal",
  "fiu": "Iaith Finno-Ugrian",
  "fj": "Ffijïeg",
  "fo": "Ffaröeg",
  "fo_FO": "Ffaröeg (Føroyar)",
  "fon": "Fon",
  "fr": "Ffrangeg",
  "fr_BE": "Ffrangeg (Gwlad Belg)",
  "fr_BF": "Ffrangeg (Burkina Faso)",
  "fr_BI": "Ffrangeg (Burundi)",
  "fr_BJ": "Ffrangeg (Benin)",
  "fr_BL": "Ffrangeg (Saint Barthélemy)",
  "fr_CA": "Ffrangeg (Canada)",
  "fr_CD": "Ffrangeg (Y Congo - Kinshasa)",
  "fr_CF": "Ffrangeg (Gweriniaeth Canolbarth Affrica)",
  "fr_CG": "Ffrangeg (Y Congo - Brazzaville)",
  "fr_CH": "Ffrangeg (Y Swistir)",
  "fr_CI": "Ffrangeg (Côte d’Ivoire)",
  "fr_CM": "Ffrangeg (Camerŵn)",
  "fr_DJ": "Ffrangeg (Djibouti)",
  "fr_DZ": "Ffrangeg (Algeria)",
  "fr_FR": "Ffrangeg (Ffrainc)",
  "fr_GA": "Ffrangeg (Gabon)",
  "fr_GF": "Ffrangeg (Guyane Ffrengig)",
  "fr_GN": "Ffrangeg (Guinée)",
  "fr_GP": "Ffrangeg (Guadeloupe)",
  "fr_GQ": "Ffrangeg (Guinea Gyhydeddol)",
  "fr_HT": "Ffrangeg (Haiti)",
  "fr_KM": "Ffrangeg (Comoros)",
  "fr_LU": "Ffrangeg (Lwcsembwrg)",
  "fr_MA": "Ffrangeg (Moroco)",
  "fr_MC": "Ffrangeg (Monaco)",
  "fr_MF": "Ffrangeg (Saint Martin)",
  "fr_MG": "Ffrangeg (Madagascar)",
  "fr_ML": "Ffrangeg (Mali)",
  "fr_MQ": "Ffrangeg (Martinique)",
  "fr_MR": "Ffrangeg (Mauritania)",
  "fr_MU": "Ffrangeg (Mauritius)",
  "fr_NC": "Ffrangeg (Caledonia Newydd)",
  "fr_NE": "Ffrangeg (Niger)",
  "fr_PF": "Ffrangeg (Polynesia Ffrengig)",
  "fr_PM": "Ffrangeg (Saint-Pierre-et-Miquelon)",
  "fr_RE": "Ffrangeg (Réunion)",
  "fr_RW": "Ffrangeg (Rwanda)",
  "fr_SC": "Ffrangeg (Seychelles)",
  "fr_SN": "Ffrangeg (Sénégal)",
  "fr_SY": "Ffrangeg (Syria)",
  "fr_TD": "Ffrangeg (Tchad)",
  "fr_TG": "Ffrangeg (Togo)",
  "fr_TN": "Ffrangeg (Tunisia)",
  "fr_VU": "Ffrangeg (Vanuatu)",
  "fr_WF": "Ffrangeg (Wallis a Futuna)",
  "fr_YT": "Ffrangeg (Mayotte)",
  "frc": "Ffrangeg Cajwn",
  "frm": "Ffrangeg Canol",
  "fro": "Hen Ffrangeg",
  "frp": "Arpitaneg",
  "frr": "Ffriseg Gogleddol",
  "frs": "Ffriseg y Dwyrain",
  "fur": "Ffriwleg",
  "fy": "Ffriseg y Gorllewin",
  "fy_NL": "Ffriseg y Gorllewin (Yr Iseldiroedd)",
  "ga": "Gwyddeleg",
  "ga_IE": "Gwyddeleg (Iwerddon)",
  "gaa": "Ga",
  "gag": "Gagauz",
  "gan": "Gan Chinese",
  "gay": "Gaio",
  "gba": "Gbaia",
  "gbz": "Dareg y Zoroastriaid",
  "gd": "Gaeleg yr Alban",
  "gd_GB": "Gaeleg yr Alban (Y Deyrnas Unedig)",
  "gem": "Iaith Germanaidd",
  "gez": "Geez",
  "gil": "Gilberteg",
  "gl": "Galisieg",
  "gl_ES": "Galisieg (Sbaen)",
  "glk": "Gilaki",
  "gmh": "Almaeneg Uchel Canol",
  "gn": "Guaraní",
  "goh": "Hen Almaeneg Uchel",
  "gom": "Goan Konkani",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gotheg",
  "grb": "Grebo",
  "grc": "Hen Roeg",
  "gsw": "Almaeneg y Swistir",
  "gu": "Gwjarati",
  "gu_IN": "Gwjarati (India)",
  "guc": "Wayuu",
  "gur": "Frafra",
  "guz": "Gusii",
  "gv": "Manaweg",
  "gv_IM": "Manaweg (Ynys Manaw)",
  "gwi": "Gwichʼin",
  "ha": "Hawsa",
  "ha_GH": "Hawsa (Ghana)",
  "ha_Latn": "Hawsa (Lladin)",
  "ha_Latn_GH": "Hawsa (Lladin, Ghana)",
  "ha_Latn_NE": "Hawsa (Lladin, Niger)",
  "ha_Latn_NG": "Hawsa (Lladin, Nigeria)",
  "ha_NE": "Hawsa (Niger)",
  "ha_NG": "Hawsa (Nigeria)",
  "hai": "Haida",
  "hak": "Hakka Chinese",
  "haw": "Hawäieg",
  "he": "Hebraeg",
  "he_IL": "Hebraeg (Israel)",
  "hi": "Hindi",
  "hi_IN": "Hindi (India)",
  "hif": "Fiji Hindi",
  "hil": "Hiligaynon",
  "him": "Himachali",
  "hit": "Hetheg",
  "hmn": "Hmongeg",
  "ho": "Hiri Motu",
  "hr": "Croateg",
  "hr_BA": "Croateg (Bosnia a Hercegovina)",
  "hr_HR": "Croateg (Croatia)",
  "hsb": "Sorbeg Uchaf",
  "hsn": "Xiang Chinese",
  "ht": "Creol Haiti",
  "hu": "Hwngareg",
  "hu_HU": "Hwngareg (Hwngari)",
  "hup": "Hupa",
  "hy": "Armeneg",
  "hy_AM": "Armeneg (Armenia)",
  "hz": "Herero",
  "ia": "Interlingua",
  "iba": "Ibaneg",
  "ibb": "Ibibio",
  "id": "Indoneseg",
  "id_ID": "Indoneseg (Indonesia)",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ig_NG": "Igbo (Nigeria)",
  "ii": "Nwosw",
  "ii_CN": "Nwosw (Tsieina)",
  "ijo": "Ijo",
  "ik": "Inwpiaceg",
  "ilo": "Ilocaneg",
  "inc": "Dangos Iaith",
  "ine": "Iaith Indo-Ewropeaidd",
  "inh": "Ingwsieg",
  "io": "Ido",
  "ira": "Iaith Iran",
  "iro": "Iaith Iroquoian",
  "is": "Islandeg",
  "is_IS": "Islandeg (Gwlad yr Iâ)",
  "it": "Eidaleg",
  "it_CH": "Eidaleg (Y Swistir)",
  "it_IT": "Eidaleg (Yr Eidal)",
  "it_SM": "Eidaleg (San Marino)",
  "iu": "Inwctitwt",
  "izh": "Ingrian",
  "ja": "Japaneeg",
  "ja_JP": "Japaneeg (Japan)",
  "jam": "Jamaican Creole English",
  "jbo": "Lojban",
  "jgo": "Ngomba",
  "jmc": "Matsiame",
  "jpr": "Iddew-Bersieg",
  "jrb": "Iddew-Arabeg",
  "jut": "Jutish",
  "jv": "Jafanaeg",
  "ka": "Georgeg",
  "ka_GE": "Georgeg (Georgia)",
  "kaa": "Cara-Calpaceg",
  "kab": "Cabileg",
  "kac": "Kachin",
  "kaj": "Jju",
  "kam": "Camba",
  "kar": "Karen",
  "kaw": "Kawi",
  "kbd": "Cabardieg",
  "kbl": "Kanembu",
  "kcg": "Tyapeg",
  "kde": "Macondeg",
  "kea": "Caboferdianeg",
  "ken": "Kenyang",
  "kfo": "Koro",
  "kg": "Congo",
  "kgp": "Kaingang",
  "kha": "Càseg",
  "khi": "Iaith Khoisan",
  "kho": "Khotanese",
  "khq": "Koyra Chiini",
  "khw": "Chowareg",
  "ki": "Kikuyu",
  "ki_KE": "ki (Kenya)",
  "kiu": "Kirmanjki",
  "kj": "Kuanyama",
  "kk": "Casacheg",
  "kk_Cyrl": "Casacheg (Cyrilig)",
  "kk_Cyrl_KZ": "Casacheg (Cyrilig, Kazakstan)",
  "kk_KZ": "Casacheg (Kazakstan)",
  "kkj": "Kako",
  "kl": "Kalaallisut",
  "kl_GL": "Kalaallisut (Greenland)",
  "kln": "Kalenjin",
  "km": "Chmereg",
  "km_KH": "Chmereg (Cambodia)",
  "kmb": "Kimbundu",
  "kn": "Kannada",
  "kn_IN": "Kannada (India)",
  "ko": "Coreeg",
  "ko_KP": "Coreeg (Gogledd Korea)",
  "ko_KR": "Coreeg (De Korea)",
  "koi": "Komi-Permyak",
  "kok": "Concani",
  "kos": "Kosraean",
  "kpe": "Kpelle",
  "kr": "Canwri",
  "krc": "Karachay-Balkar",
  "kri": "Krio",
  "krj": "Kinaray-a",
  "krl": "Careleg",
  "kro": "Kru",
  "kru": "Kurukh",
  "ks": "Cashmireg",
  "ks_Arab": "Cashmireg (Arabaidd)",
  "ks_Arab_IN": "Cashmireg (Arabaidd, India)",
  "ks_IN": "Cashmireg (India)",
  "ksb": "Shambala",
  "ksf": "Baffia",
  "ksh": "Cwleneg",
  "ku": "Cwrdeg",
  "kum": "Cwmiceg",
  "kut": "Kutenai",
  "kv": "Comi",
  "kw": "Cernyweg",
  "kw_GB": "Cernyweg (Y Deyrnas Unedig)",
  "ky": "Cirgiseg",
  "ky_Cyrl": "Cirgiseg (Cyrilig)",
  "ky_Cyrl_KG": "Cirgiseg (Cyrilig, Kyrgyzstan)",
  "ky_KG": "Cirgiseg (Kyrgyzstan)",
  "la": "Lladin",
  "lad": "Iddew-Sbaeneg",
  "lag": "Langi",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lb": "Lwcsembwrgeg",
  "lb_LU": "Lwcsembwrgeg (Lwcsembwrg)",
  "lez": "Lezgheg",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "lg_UG": "Ganda (Uganda)",
  "li": "Limbwrgeg",
  "lij": "Ligurian",
  "liv": "Livonian",
  "lkt": "Lakota",
  "lmo": "Lombardeg",
  "ln": "Lingala",
  "ln_AO": "Lingala (Angola)",
  "ln_CD": "Lingala (Y Congo - Kinshasa)",
  "ln_CF": "Lingala (Gweriniaeth Canolbarth Affrica)",
  "ln_CG": "Lingala (Y Congo - Brazzaville)",
  "lo": "Laoeg",
  "lo_LA": "Laoeg (Laos)",
  "lol": "Mongo",
  "lou": "Louisiana Creole",
  "loz": "Lozi",
  "lrc": "Luri Gogleddol",
  "lt": "Lithwaneg",
  "lt_LT": "Lithwaneg (Lithuania)",
  "ltg": "Latgaleg",
  "lu": "Luba-Katanga",
  "lu_CD": "Luba-Katanga (Congo - Kinshasa)",
  "lua": "Luba-Lulua",
  "lui": "Luiseno",
  "lun": "Lwnda",
  "luo": "Lŵo",
  "lus": "Lwshaieg",
  "luy": "Lwyia",
  "lv": "Latfieg",
  "lv_LV": "Latfieg (Latfia)",
  "lzh": "Literary Chinese",
  "lzz": "Laz",
  "mad": "Madwreg",
  "maf": "Mafa",
  "mag": "Magahi",
  "mai": "Maithili",
  "mak": "Macasareg",
  "man": "Mandingo",
  "map": "Iaith Awstronesaidd",
  "mas": "Masai",
  "mde": "Maba",
  "mdf": "Mocsia",
  "mdr": "Mandareg",
  "men": "Mendeg",
  "mer": "Mêrw",
  "mfe": "Morisyen",
  "mg": "Malagaseg",
  "mg_MG": "Malagaseg (Madagascar)",
  "mga": "Gwyddeleg Canol",
  "mgh": "Makhuwa-Meetto",
  "mgo": "Meta",
  "mh": "Marsialeg",
  "mi": "Maori",
  "mic": "Micmaceg",
  "min": "Minangkabau",
  "mis": "Iaith Amrywiol",
  "mk": "Macedoneg",
  "mk_MK": "Macedoneg (Macedonia)",
  "mkh": "Iaith Mon-Khmer",
  "ml": "Malayalam",
  "ml_IN": "Malayalam (India)",
  "mn": "Mongoleg",
  "mn_Cyrl": "Mongoleg (Cyrilig)",
  "mn_Cyrl_MN": "Mongoleg (Cyrilig, Mongolia)",
  "mn_MN": "Mongoleg (Mongolia)",
  "mnc": "Manshw",
  "mni": "Manipwri",
  "mno": "Iaith Manobo",
  "mo": "Moldavian",
  "moh": "Mohoceg",
  "mos": "Mosi",
  "mr": "Marathi",
  "mr_IN": "Marathi (India)",
  "mrj": "Mari Gorllewinol",
  "ms": "Maleieg",
  "ms_BN": "Maleieg (Brunei)",
  "ms_Latn": "Maleieg (Lladin)",
  "ms_Latn_BN": "Maleieg (Lladin, Brunei)",
  "ms_Latn_MY": "Maleieg (Lladin, Malaysia)",
  "ms_Latn_SG": "Maleieg (Lladin, Singapore)",
  "ms_MY": "Maleieg (Malaysia)",
  "ms_SG": "Maleieg (Singapore)",
  "mt": "Malteg",
  "mt_MT": "Malteg (Malta)",
  "mua": "Mundang",
  "mul": "Mwy nag un iaith",
  "mun": "Iaith Munda",
  "mus": "Creek",
  "mwl": "Mirandeg",
  "mwr": "Marwari",
  "mwv": "Mentawai",
  "my": "Byrmaneg",
  "my_MM": "Byrmaneg (Myanmar (Burma))",
  "mye": "Myene",
  "myn": "Iaith Maya",
  "myv": "Erzya",
  "mzn": "Masanderani",
  "na": "Nawrŵeg",
  "nah": "Nahuatl",
  "nai": "Iaith Indiaidd Gogledd America",
  "nan": "Min Nan Chinese",
  "nap": "Naplieg",
  "naq": "Nama",
  "nb": "Norwyeg Bokmål",
  "nb_NO": "Norwyeg Bokmål (Norwy)",
  "nb_SJ": "Norwyeg Bokmål (Svalbard a Jan Mayen)",
  "nd": "Ndebele Gogleddol",
  "nd_ZW": "Ndebele Gogleddol (Zimbabwe)",
  "nds": "Almaeneg Isel",
  "nds_NL": "Sacsoneg Isel",
  "ne": "Nepaleg",
  "ne_IN": "Nepaleg (India)",
  "ne_NP": "Nepaleg (Nepal)",
  "new": "Newaeg",
  "ng": "Ndonga",
  "nia": "Nias",
  "nic": "Iaith Niger-Kordofanian",
  "niu": "Niuean",
  "njo": "Ao Naga",
  "nl": "Iseldireg",
  "nl_AW": "Iseldireg (Aruba)",
  "nl_BE": "Fflemeg",
  "nl_BQ": "Iseldireg (Antilles yr Iseldiroedd)",
  "nl_CW": "Iseldireg (Curaçao)",
  "nl_NL": "Iseldireg (Yr Iseldiroedd)",
  "nl_SR": "Iseldireg (Suriname)",
  "nl_SX": "Iseldireg (Sint Maarten)",
  "nmg": "Kwasio",
  "nn": "Norwyeg Nynorsk",
  "nn_NO": "Norwyeg Nynorsk (Norwy)",
  "nnh": "Ngiemboon",
  "no": "Norwyeg",
  "no_NO": "Norwyeg (Norwy)",
  "nog": "Nogai",
  "non": "Hen Norseg",
  "nov": "Novial",
  "nqo": "N’Ko",
  "nr": "Ndebele Deheuol",
  "nso": "Sotho Gogleddol",
  "nub": "Iaith Nubian",
  "nus": "Nŵereg",
  "nv": "Nafaho",
  "nwc": "Hen Newari",
  "ny": "Nianja",
  "nym": "Niamwezi",
  "nyn": "Niancole",
  "nyo": "Nioro",
  "nzi": "Nzimeg",
  "oc": "Ocsitaneg",
  "oj": "Ojibwa",
  "om": "Oromo",
  "om_ET": "Oromo (Ethiopia)",
  "om_KE": "Oromo (Kenya)",
  "or": "Odia",
  "or_IN": "Oriya (India)",
  "os": "Oseteg",
  "os_GE": "Oseteg (Georgia)",
  "os_RU": "Oseteg (Rwsia)",
  "osa": "Osageg",
  "ota": "Tyrceg Otoman",
  "oto": "Iaith Otomaidd",
  "pa": "Pwnjabeg",
  "pa_Arab": "Pwnjabeg (Arabaidd)",
  "pa_Arab_PK": "Pwnjabeg (Arabaidd, Pakistan)",
  "pa_Guru": "Pwnjabeg (Gwrmwci)",
  "pa_Guru_IN": "Pwnjabeg (Gwrmwci, India)",
  "pa_IN": "Pwnjabeg (India)",
  "pa_PK": "Pwnjabeg (Pakistan)",
  "paa": "Iaith Papuan",
  "pag": "Pangasineg",
  "pal": "Pahlafi",
  "pam": "Pampanga",
  "pap": "Papiamento",
  "pau": "Palawan",
  "pcd": "Picardeg",
  "pcm": "Pidgin Nigeria",
  "pdc": "Almaeneg Pensylfania",
  "pdt": "Plautdietsch",
  "peo": "Hen Bersieg",
  "pfl": "Almaeneg Palatin",
  "phi": "Iaith Philippine",
  "phn": "Phoeniceg",
  "pi": "Pali",
  "pl": "Pwyleg",
  "pl_PL": "Pwyleg (Gwlad Pwyl)",
  "pms": "Piedmonteg",
  "pnt": "Ponteg",
  "pon": "Pohnpeianeg",
  "pra": "Iaith Prakrit",
  "prg": "Prwseg",
  "pro": "Hen Brofensaleg",
  "ps": "Pashto",
  "ps_AF": "Pashto (Afghanistan)",
  "pt": "Portiwgeeg",
  "pt_AO": "Portiwgeeg (Angola)",
  "pt_BR": "Portiwgeeg (Brasil)",
  "pt_CV": "Portiwgeeg (Cabo Verde)",
  "pt_GW": "Portiwgeeg (Guiné-Bissau)",
  "pt_MO": "Portiwgeeg (Macau RhGA Tsieina)",
  "pt_MZ": "Portiwgeeg (Mozambique)",
  "pt_PT": "Portiwgeeg (Portiwgal)",
  "pt_ST": "Portiwgeeg (São Tomé a Príncipe)",
  "pt_TL": "Portiwgeeg (Timor-Leste)",
  "qu": "Quechua",
  "qu_BO": "Quechua (Bolifia)",
  "qu_EC": "Quechua (Ecuador)",
  "qu_PE": "Quechua (Periw)",
  "quc": "K’iche’",
  "qug": "Chimborazo Highland Quichua",
  "raj": "Rajasthaneg",
  "rap": "Rapanŵi",
  "rar": "Raratongeg",
  "rgn": "Romagnol",
  "rif": "Riffian",
  "rm": "Románsh",
  "rm_CH": "Romaunsch (Y Swistir)",
  "rn": "Rwndi",
  "rn_BI": "Rwndi (Burundi)",
  "ro": "Rwmaneg",
  "ro_MD": "Rwmaneg (Moldofa)",
  "ro_RO": "Rwmaneg (Rwmania)",
  "roa": "Iaith Rhamant",
  "rof": "Rombo",
  "rom": "Romani",
  "root": "Y Gwraidd",
  "rtm": "Rotumaneg",
  "ru": "Rwseg",
  "ru_BY": "Rwseg (Belarws)",
  "ru_KG": "Rwseg (Kyrgyzstan)",
  "ru_KZ": "Rwseg (Kazakstan)",
  "ru_MD": "Rwseg (Moldofa)",
  "ru_RU": "Rwseg (Rwsia)",
  "ru_UA": "Rwseg (Wcráin)",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rup": "Aromaneg",
  "rw": "Ciniarŵandeg",
  "rw_RW": "Ciniarŵandeg (Rwanda)",
  "rwk": "Rwa",
  "sa": "Sansgrit",
  "sad": "Sandäweg",
  "sah": "Sakha",
  "sai": "Iaith Indiaidd De America",
  "sal": "Iaith Salishan",
  "sam": "Aramaeg Samaria",
  "saq": "Sambŵrw",
  "sas": "Sasaceg",
  "sat": "Santali",
  "saz": "Saurashtra",
  "sba": "Ngambeieg",
  "sbp": "Sangw",
  "sc": "Sardeg",
  "scn": "Sisileg",
  "sco": "Sgoteg",
  "sd": "Sindhi",
  "sd_Deva": "Sindhi (Devanagari)",
  "sdc": "Sasareseg Sardinia",
  "sdh": "Cwrdeg Deheuol",
  "se": "Sami Gogleddol",
  "se_FI": "Sami Gogleddol (Y Ffindir)",
  "se_NO": "Sami Gogleddol (Norwy)",
  "se_SE": "Sami Gogleddol (Sweden)",
  "see": "Seneca",
  "seh": "Sena",
  "sei": "Seri",
  "sel": "Selcypeg",
  "sem": "Iaith Semitig",
  "ses": "Koyraboro Senni",
  "sg": "Sango",
  "sg_CF": "Sango (Gweriniaeth Canolbarth Affrica)",
  "sga": "Hen Wyddeleg",
  "sgn": "Iaith Arwyddion",
  "sgs": "Samogiteg",
  "sh": "Serbo-Croateg",
  "sh_BA": "Serbo-Croateg (Bosnia a Hercegovina)",
  "shi": "Tachelhit",
  "shi_Latn": "Shilha (Lladin)",
  "shi_Tfng": "Shilha (Tifinagh)",
  "shn": "Shan",
  "shu": "Arabeg Chad",
  "si": "Sinhaleg",
  "si_LK": "Sinhaleg (Sri Lanka)",
  "sid": "Sidamo",
  "sio": "Iaith Siouan",
  "sit": "Iaith Sino-Tibetaidd",
  "sk": "Slofaceg",
  "sk_SK": "Slofaceg (Slofacia)",
  "sl": "Slofeneg",
  "sl_SI": "Slofeneg (Slofenia)",
  "sla": "Iaith Slafaidd",
  "sli": "Is-silesieg",
  "sly": "Selayar",
  "sm": "Samöeg",
  "sma": "Sami Deheuol",
  "smi": "Iaith Sami",
  "smj": "Sami Lwle",
  "smn": "Inari Sami",
  "sms": "Sami Scolt",
  "sn": "Shona",
  "sn_ZW": "Shona (Zimbabwe)",
  "snk": "Soninceg",
  "so": "Somaleg",
  "so_DJ": "Somaleg (Djibouti)",
  "so_ET": "Somaleg (Ethiopia)",
  "so_KE": "Somaleg (Kenya)",
  "so_SO": "Somaleg (Somalia)",
  "sog": "Sogdeg",
  "son": "Songhai",
  "sq": "Albaneg",
  "sq_AL": "Albaneg (Albania)",
  "sq_MK": "Albaneg (Macedonia)",
  "sq_XK": "Albaneg (Kosovo)",
  "sr": "Serbeg",
  "sr_BA": "Serbeg (Bosnia a Hercegovina)",
  "sr_Cyrl": "Serbeg (Cyrilig)",
  "sr_Cyrl_BA": "Serbeg (Cyrilig, Bosnia a Hercegovina)",
  "sr_Cyrl_ME": "Serbeg (Cyrilig, Montenegro)",
  "sr_Cyrl_RS": "Serbeg (Cyrilig, Serbia)",
  "sr_Cyrl_XK": "Serbeg (Cyrilig, Kosovo)",
  "sr_Latn": "Serbeg (Lladin)",
  "sr_Latn_BA": "Serbeg (Lladin, Bosnia a Hercegovina)",
  "sr_Latn_ME": "Serbeg (Lladin, Montenegro)",
  "sr_Latn_RS": "Serbeg (Lladin, Serbia)",
  "sr_Latn_XK": "Serbeg (Lladin, Kosovo)",
  "sr_ME": "Serbeg (Montenegro)",
  "sr_RS": "Serbeg (Serbia)",
  "sr_XK": "Serbeg (Kosovo)",
  "srn": "Sranan Tongo",
  "srr": "Serereg",
  "ss": "Swati",
  "ssa": "Iaith Nilo-Sahara",
  "ssy": "Saho",
  "st": "Sesotheg Deheuol",
  "stq": "Ffriseg Saterland",
  "su": "Swndaneg",
  "suk": "Swcwma",
  "sus": "Swsŵeg",
  "sux": "Swmereg",
  "sv": "Swedeg",
  "sv_AX": "Swedeg (Ynysoedd Åland)",
  "sv_FI": "Swedeg (Y Ffindir)",
  "sv_SE": "Swedeg (Sweden)",
  "sw": "Swahili",
  "sw_CD": "Swahili’r Congo",
  "sw_KE": "Swahili (Kenya)",
  "sw_TZ": "Swahili (Tanzania)",
  "sw_UG": "Swahili (Uganda)",
  "swb": "Comoreg",
  "swc": "Swahili’r Congo",
  "syc": "Hen Syrieg",
  "syr": "Syrieg",
  "szl": "Silesieg",
  "ta": "Tamileg",
  "ta_IN": "Tamileg (India)",
  "ta_LK": "Tamileg (Sri Lanka)",
  "ta_MY": "Tamileg (Malaysia)",
  "ta_SG": "Tamileg (Singapore)",
  "tai": "Iaith Tai",
  "tcy": "Tulu",
  "te": "Telugu",
  "te_IN": "Telugu (India)",
  "tem": "Timneg",
  "teo": "Teso",
  "ter": "Terena",
  "tet": "Tetumeg",
  "tg": "Tajiceg",
  "th": "Thai",
  "th_TH": "Thai (Gwlad Thai)",
  "ti": "Tigrinya",
  "ti_ER": "Tigrinya (Eritrea)",
  "ti_ET": "Tigrinya (Ethiopia)",
  "tig": "Tigreg",
  "tiv": "Tifeg",
  "tk": "Tyrcmeneg",
  "tkl": "Tocelaweg",
  "tkr": "Tsakhureg",
  "tl": "Tagalog",
  "tl_PH": "Tagalog (Pilipinas)",
  "tlh": "Klingon",
  "tli": "Llingit",
  "tly": "Talysheg",
  "tmh": "Tamasheceg",
  "tn": "Tswana",
  "to": "Tongeg",
  "to_TO": "Tongeg (Tonga)",
  "tog": "Nyasa Tonga",
  "tpi": "Tok Pisin",
  "tr": "Tyrceg",
  "tr_CY": "Tyrceg (Cyprus)",
  "tr_TR": "Tyrceg (Twrci)",
  "tru": "Turoyo",
  "trv": "Taroko",
  "ts": "Tsongaeg",
  "tsd": "Tsaconeg",
  "tsi": "Tsimshian",
  "tt": "Tatareg",
  "ttt": "Muslim Tat",
  "tum": "Twmbwca",
  "tup": "Iaith Tupi",
  "tut": "Iaith Altaig",
  "tvl": "Twfalweg",
  "tw": "Twi",
  "twq": "Tasawaq",
  "ty": "Tahitïeg",
  "tyv": "Twfwnieg",
  "tzm": "Tamazight Canol yr Atlas",
  "udm": "Fotiaceg",
  "ug": "Uighur",
  "ug_Arab": "Uighur (Arabaidd)",
  "ug_Arab_CN": "Uighur (Arabaidd, Tsieina)",
  "ug_CN": "Uighur (Tsieina)",
  "uga": "Wgariteg",
  "uk": "Wcreineg",
  "uk_UA": "Wcreineg (Wcráin)",
  "umb": "Umbundu",
  "und": "Iaith anhysbys",
  "ur": "Wrdw",
  "ur_IN": "Wrdw (India)",
  "ur_PK": "Wrdw (Pakistan)",
  "uz": "Wsbeceg",
  "uz_AF": "Wsbeceg (Afghanistan)",
  "uz_Arab": "Wsbeceg (Arabaidd)",
  "uz_Arab_AF": "Wsbeceg (Arabaidd, Afghanistan)",
  "uz_Cyrl": "Wsbeceg (Cyrilig)",
  "uz_Cyrl_UZ": "Wsbeceg (Cyrilig, Uzbekistan)",
  "uz_Latn": "Wsbeceg (Lladin)",
  "uz_Latn_UZ": "Wsbeceg (Lladin, Uzbekistan)",
  "uz_UZ": "Wsbeceg (Uzbekistan)",
  "vai": "Faieg",
  "vai_Latn": "Vai (Lladin)",
  "ve": "Fendeg",
  "vec": "Feniseg",
  "vep": "Feps",
  "vi": "Fietnameg",
  "vi_VN": "Fietnameg (Fietnam)",
  "vls": "Fflemeg Gorllewinol",
  "vmf": "Main-Franconian",
  "vo": "Folapük",
  "vot": "Foteg",
  "vro": "Võro",
  "vun": "Funjo",
  "wa": "Walwneg",
  "wae": "Walsereg",
  "wak": "Iaith Wakashan",
  "wal": "Walamo",
  "war": "Winarayeg",
  "was": "Washo",
  "wbp": "Warlpiri",
  "wen": "Iaith Sorbian",
  "wo": "Woloff",
  "wuu": "Wu Chinese",
  "xal": "Calmyceg",
  "xh": "Xhosa",
  "xmf": "Mingrelian",
  "xog": "Soga",
  "yao": "Yao",
  "yap": "Yapese",
  "yav": "Iangben",
  "ybb": "Iembaeg",
  "yi": "Iddew-Almaeneg",
  "yo": "Iorwba",
  "yo_BJ": "Iorwba (Benin)",
  "yo_NG": "Iorwba (Nigeria)",
  "ypk": "Iaith Yupik",
  "yrl": "Nheengatu",
  "yue": "Cantoneeg",
  "yue_Hans": "Cantoneg (Tsieineaidd Syml)",
  "yue_Hant": "Cantoneg (Tsieineaidd Traddodiadol)",
  "za": "Zhuang",
  "zap": "Zapoteceg",
  "zbl": "Blisssymbols",
  "zea": "Zêlandeg",
  "zen": "Zenaga",
  "zgh": "Tamaseit Safonol",
  "zh": "Tsieinëeg",
  "zh_CN": "Tsieineeg (Tsieina)",
  "zh_HK": "Tsieineeg (Hong Kong RhGA Tsieina)",
  "zh_Hans": "Tsieinëeg (Symledig)",
  "zh_Hans_CN": "Tsieineeg (Symledig, Tsieina)",
  "zh_Hans_HK": "Tsieineeg (Symledig, Hong Kong RhGA Tsieina)",
  "zh_Hans_MO": "Tsieineeg (Symledig, Macau RhGA Tsieina)",
  "zh_Hans_SG": "Tsieineeg (Symledig, Singapore)",
  "zh_Hant": "Tsieinëeg (Traddodiadol)",
  "zh_Hant_HK": "Tsieineeg (Traddodiadol, Hong Kong RhGA Tsieina)",
  "zh_Hant_MO": "Tsieineeg (Traddodiadol, Macau RhGA Tsieina)",
  "zh_Hant_TW": "Tsieineeg (Traddodiadol, Taiwan)",
  "zh_MO": "Tsieineeg (Macau RhGA Tsieina)",
  "zh_SG": "Tsieineeg (Singapore)",
  "zh_TW": "Tsieineeg (Taiwan)",
  "znd": "Zande",
  "zu": "Swlw",
  "zu_ZA": "Swlw (De Affrica)",
  "zun": "Swni",
  "zxx": "Dim cynnwys ieithyddol",
  "zza": "Sasäeg"
};
