const names = {
  "001": "Dünýä",
  "002": "Afrika",
  "003": "Demirgazyk Amerika",
  "005": "Günorta Amerika",
  "009": "Okeaniýa",
  "011": "Günbatar Afrika",
  "013": "Orta Amerika",
  "014": "Gündogar Afrika",
  "015": "Demirgazyk Afrika",
  "017": "Orta Afrika",
  "018": "Afrikanyň günorta sebitleri",
  "019": "Amerika",
  "021": "Amerikanyň demirgazyk ýurtlary",
  "029": "Karib basseýni",
  "030": "Gündogar Aziýa",
  "034": "Günorta Aziýa",
  "035": "Günorta-gündogar Aziýa",
  "039": "Günorta Ýewropa",
  "053": "Awstralaziýa",
  "054": "Melaneziýa",
  "057": "Mikroneziýa sebti",
  "061": "Polineziýa",
  "142": "Aziýa",
  "143": "Merkezi Aziýa",
  "145": "Günbatar Aziýa",
  "150": "Ýewropa",
  "151": "Gündogar Ýewropa",
  "154": "Demirgazyk Ýewropa",
  "155": "Günbatar Ýewropa",
  "202": "Saharadan aşakdaky Afrika",
  "419": "Latyn Amerikasy",
  "AC": "Beýgeliş adasy",
  "AD": "Andorra",
  "AE": "Birleşen Arap Emirlikleri",
  "AF": "Owganystan",
  "AG": "Antigua we Barbuda",
  "AI": "Angilýa",
  "AL": "Albaniýa",
  "AM": "Ermenistan",
  "AO": "Angola",
  "AQ": "Antarktika",
  "AR": "Argentina",
  "AS": "Amerikan Samoasy",
  "AT": "Awstriýa",
  "AU": "Awstraliýa",
  "AW": "Aruba",
  "AX": "Aland adalary",
  "AZ": "Azerbaýjan",
  "Arab": "Arap elipbiýi",
  "Armn": "Ermeni elipbiýi",
  "BA": "Bosniýa we Gersegowina",
  "BB": "Barbados",
  "BD": "Bangladeş",
  "BE": "Belgiýa",
  "BF": "Burkina-Faso",
  "BG": "Bolgariýa",
  "BH": "Bahreýn",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Sen-Bartelemi",
  "BM": "Bermuda",
  "BN": "Bruneý",
  "BO": "Boliwiýa",
  "BQ": "Karib Niderlandlary",
  "BR": "Braziliýa",
  "BS": "Bagama adalary",
  "BT": "Butan",
  "BV": "Buwe adasy",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Beliz",
  "Beng": "Bengal elipbiýi",
  "Bopo": "Bopomofo elipbiýi",
  "Brai": "Braýl elipbiýi",
  "CA": "Kanada",
  "CC": "Kokos (Kiling) adalary",
  "CD": "Kongo - Kinşasa",
  "CF": "Merkezi Afrika Respublikasy",
  "CG": "Kongo - Brazzawil",
  "CH": "Şweýsariýa",
  "CI": "Kot-d’Iwuar",
  "CK": "Kuk adalary",
  "CL": "Çili",
  "CM": "Kamerun",
  "CN": "Hytaý",
  "CO": "Kolumbiýa",
  "CP": "Klipperton adasy",
  "CR": "Kosta-Rika",
  "CU": "Kuba",
  "CV": "Kabo-Werde",
  "CW": "Kýurasao",
  "CX": "Roždestwo adasy",
  "CY": "Kipr",
  "CZ": "Çehiýa",
  "Cyrl": "Kiril elipbiýi",
  "DE": "Germaniýa",
  "DG": "Diýego-Garsiýa",
  "DJ": "Jibuti",
  "DK": "Daniýa",
  "DM": "Dominika",
  "DO": "Dominikan Respublikasy",
  "DZ": "Alžir",
  "Deva": "Dewanagari elipbiýi",
  "EA": "Seuta we Melilýa",
  "EC": "Ekwador",
  "EE": "Estoniýa",
  "EG": "Müsür",
  "EH": "Günbatar Sahara",
  "ER": "Eritreýa",
  "ES": "Ispaniýa",
  "ET": "Efiopiýa",
  "EU": "Ýewropa Bileleşigi",
  "EZ": "Ýewro sebiti",
  "Ethi": "Efiop elipbiýi",
  "FI": "Finlýandiýa",
  "FJ": "Fiji",
  "FK": "Folklend adalary",
  "FM": "Mikroneziýa",
  "FO": "Farer adalary",
  "FR": "Fransiýa",
  "GA": "Gabon",
  "GB": "Birleşen Patyşalyk",
  "GD": "Grenada",
  "GE": "Gruziýa",
  "GF": "Fransuz Gwianasy",
  "GG": "Gernsi",
  "GH": "Gana",
  "GI": "Gibraltar",
  "GL": "Grenlandiýa",
  "GM": "Gambiýa",
  "GN": "Gwineýa",
  "GP": "Gwadelupa",
  "GQ": "Ekwatorial Gwineýa",
  "GR": "Gresiýa",
  "GS": "Günorta Georgiýa we Günorta Sendwiç adasy",
  "GT": "Gwatemala",
  "GU": "Guam",
  "GW": "Gwineýa-Bisau",
  "GY": "Gaýana",
  "Geor": "Gruzin elipbiýi",
  "Grek": "Grek elipbiýi",
  "Gujr": "Gujarati elipbiýi",
  "Guru": "Gurmuhi elipbiýi",
  "HK": "Gonkong AAS Hytaý",
  "HM": "Herd we Makdonald adalary",
  "HN": "Gonduras",
  "HR": "Horwatiýa",
  "HT": "Gaiti",
  "HU": "Wengriýa",
  "Hanb": "Bopomofo han elipbiýi",
  "Hang": "Hangyl elipbiýi",
  "Hani": "Han elipbiýi",
  "Hans": "Ýönekeýleşdirilen",
  "Hant": "Adaty",
  "Hebr": "Ýewreý elipbiýi",
  "Hira": "Hiragana elipbiýi",
  "Hrkt": "Ýapon bogun elipbiýleri",
  "IC": "Kanar adalary",
  "ID": "Indoneziýa",
  "IE": "Irlandiýa",
  "IL": "Ysraýyl",
  "IM": "Men adasy",
  "IN": "Hindistan",
  "IO": "Britaniýanyň Hindi okeanyndaky territoriýalary",
  "IQ": "Yrak",
  "IR": "Eýran",
  "IS": "Islandiýa",
  "IT": "Italiýa",
  "JE": "Jersi",
  "JM": "Ýamaýka",
  "JO": "Iordaniýa",
  "JP": "Ýaponiýa",
  "Jamo": "Jamo elipbiýi",
  "Jpan": "Ýapon elipbiýi",
  "KE": "Keniýa",
  "KG": "Gyrgyzystan",
  "KH": "Kamboja",
  "KI": "Kiribati",
  "KM": "Komor adalary",
  "KN": "Sent-Kits we Newis",
  "KP": "Demirgazyk Koreýa",
  "KR": "Günorta Koreýa",
  "KW": "Kuweýt",
  "KY": "Kaýman adalary",
  "KZ": "Gazagystan",
  "Kana": "Katakana elipbiýi",
  "Khmr": "Khmer elipbiýi",
  "Knda": "Kannada elipbiýi",
  "Kore": "Koreý elipbiýi",
  "LA": "Laos",
  "LB": "Liwan",
  "LC": "Sent-Lýusiýa",
  "LI": "Lihtenşteýn",
  "LK": "Şri-Lanka",
  "LR": "Liberiýa",
  "LS": "Lesoto",
  "LT": "Litwa",
  "LU": "Lýuksemburg",
  "LV": "Latwiýa",
  "LY": "Liwiýa",
  "Laoo": "Laos elipbiýi",
  "Latn": "Latyn elipbiýi",
  "MA": "Marokko",
  "MC": "Monako",
  "MD": "Moldowa",
  "ME": "Montenegro",
  "MF": "Sen-Marten",
  "MG": "Madagaskar",
  "MH": "Marşall adalary",
  "MK": "Demirgazyk Makedoniýa",
  "ML": "Mali",
  "MM": "Mýanma (Burma)",
  "MN": "Mongoliýa",
  "MO": "Makau AAS Hytaý",
  "MP": "Demirgazyk Mariana adalary",
  "MQ": "Martinika",
  "MR": "Mawritaniýa",
  "MS": "Monserrat",
  "MT": "Malta",
  "MU": "Mawrikiý",
  "MV": "Maldiwler",
  "MW": "Malawi",
  "MX": "Meksika",
  "MY": "Malaýziýa",
  "MZ": "Mozambik",
  "Mlym": "Malaýalam elipbiýi",
  "Mong": "Mongol elipbiýi",
  "Mymr": "Mýanma elipbiýi",
  "NA": "Namibiýa",
  "NC": "Täze Kaledoniýa",
  "NE": "Niger",
  "NF": "Norfolk adasy",
  "NG": "Nigeriýa",
  "NI": "Nikaragua",
  "NL": "Niderlandlar",
  "NO": "Norwegiýa",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Täze Zelandiýa",
  "OM": "Oman",
  "Orya": "Oriýa elipbiýi",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Fransuz Polineziýasy",
  "PG": "Papua - Täze Gwineýa",
  "PH": "Filippinler",
  "PK": "Pakistan",
  "PL": "Polşa",
  "PM": "Sen-Pýer we Mikelon",
  "PN": "Pitkern adalary",
  "PR": "Puerto-Riko",
  "PS": "Palestina territoriýasy",
  "PT": "Portugaliýa",
  "PW": "Palau",
  "PY": "Paragwaý",
  "QA": "Katar",
  "QO": "Daşky Okeaniýa",
  "RE": "Reýunýon",
  "RO": "Rumyniýa",
  "RS": "Serbiýa",
  "RU": "Russiýa",
  "RW": "Ruanda",
  "SA": "Saud Arabystany",
  "SB": "Solomon adalary",
  "SC": "Seýşel adalary",
  "SD": "Sudan",
  "SE": "Şwesiýa",
  "SG": "Singapur",
  "SH": "Keramatly Ýelena adasy",
  "SI": "Sloweniýa",
  "SJ": "Şpisbergen we Ýan-Maýen",
  "SK": "Slowakiýa",
  "SL": "Sýerra-Leone",
  "SM": "San-Marino",
  "SN": "Senegal",
  "SO": "Somali",
  "SR": "Surinam",
  "SS": "Günorta Sudan",
  "ST": "San-Tome we Prinsipi",
  "SV": "Salwador",
  "SX": "Sint-Marten",
  "SY": "Siriýa",
  "SZ": "Eswatini",
  "Sinh": "Singal elipbiýi",
  "TA": "Tristan-da-Kunýa",
  "TC": "Terks we Kaýkos adalary",
  "TD": "Çad",
  "TF": "Fransuz günorta territoriýalary",
  "TG": "Togo",
  "TH": "Taýland",
  "TJ": "Täjigistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Türkmenistan",
  "TN": "Tunis",
  "TO": "Tonga",
  "TR": "Türkiýe",
  "TT": "Trinidad we Tobago",
  "TV": "Tuwalu",
  "TW": "Taýwan",
  "TZ": "Tanzaniýa",
  "Taml": "Tamil elipbiýi",
  "Telu": "Telugu elipbiýi",
  "Thaa": "Taana elipbiýi",
  "Thai": "Taý elipbiýi",
  "Tibt": "Tibet elipbiýi",
  "UA": "Ukraina",
  "UG": "Uganda",
  "UM": "ABŞ-nyň daşarky adalary",
  "UN": "Birleşen Milletler Guramasy",
  "US": "Amerikanyň Birleşen Ştatlary",
  "UY": "Urugwaý",
  "UZ": "Özbegistan",
  "VA": "Watikan",
  "VC": "Sent-Winsent we Grenadinler",
  "VE": "Wenesuela",
  "VG": "Britan Wirgin adalary",
  "VI": "ABŞ-nyň Wirgin adalary",
  "VN": "Wýetnam",
  "VU": "Wanuatu",
  "WF": "Uollis we Futuna",
  "WS": "Samoa",
  "XA": "psewdo-şiweler",
  "XB": "psewdo-bidi",
  "XK": "Kosowo",
  "YE": "Ýemen",
  "YT": "Maýotta",
  "ZA": "Günorta Afrika",
  "ZM": "Zambiýa",
  "ZW": "Zimbabwe",
  "ZZ": "Näbelli sebit",
  "Zmth": "Matematiki belgiler",
  "Zsye": "Emoji",
  "Zsym": "Nyşanlar",
  "Zxxx": "Ýazuwsyz",
  "Zyyy": "Umumy",
  "Zzzz": "Näbelli elipbiý",
  "aa": "afar dili",
  "ab": "abhaz dili",
  "ace": "açeh dili",
  "ada": "adangme dili",
  "ady": "adygeý dili",
  "af": "afrikaans dili",
  "agq": "ahem dili",
  "ain": "aýn dili",
  "ak": "akan dili",
  "ale": "aleut dili",
  "alt": "günorta Altaý dili",
  "am": "amhar dili",
  "an": "aragon dili",
  "anp": "angika dili",
  "ar": "arap dili",
  "ar_001": "häzirki zaman standart arap dili",
  "arn": "mapuçe dili",
  "arp": "arapaho dili",
  "as": "assam dili",
  "asa": "asu dili",
  "ast": "asturiý dili",
  "av": "awar dili",
  "awa": "awadhi dili",
  "ay": "aýmara dili",
  "az": "azerbaýjan dili",
  "ba": "başgyrt dili",
  "ban": "baliý dili",
  "bas": "basaa dili",
  "be": "belarus dili",
  "bem": "bemba dili",
  "bez": "bena dili",
  "bg": "bolgar dili",
  "bho": "bhojpuri dili",
  "bi": "bislama dili",
  "bin": "bini dili",
  "bla": "siksika dili",
  "bm": "bamana",
  "bn": "bengal dili",
  "bo": "tibet dili",
  "br": "breton dili",
  "brx": "bodo dili",
  "bs": "boşnak dili",
  "bug": "bugiý dili",
  "byn": "blin dili",
  "ca": "katalan dili",
  "ccp": "çakma dili",
  "ce": "çeçen dili",
  "ceb": "sebuan dili",
  "cgg": "kiga",
  "ch": "çamorro",
  "chk": "çuuk dili",
  "chm": "mariý dili",
  "cho": "çokto",
  "chr": "çeroki",
  "chy": "şaýenn dili",
  "ckb": "merkezi kürt dili",
  "co": "korsikan dili",
  "crs": "seselwa kreole-fransuz dili",
  "cs": "çeh dili",
  "cu": "buthana slaw dili",
  "cv": "çuwaş dili",
  "cy": "walliý dili",
  "da": "daniýa dili",
  "dak": "dakota dili",
  "dar": "dargi dili",
  "dav": "taita dili",
  "de": "nemes dili",
  "de_CH": "ýokarky nemes dili (Şweýsariýa)",
  "dgr": "dogrib dili",
  "dje": "zarma dili",
  "dsb": "aşaky lužits dili",
  "dua": "duala dili",
  "dv": "diwehi dili",
  "dyo": "ýola-fonýi dili",
  "dz": "dzong-ke dili",
  "dzg": "daza dili",
  "ebu": "embu dili",
  "ee": "ewe dili",
  "efi": "efik dili",
  "eka": "ekajuk dili",
  "el": "grek dili",
  "en": "iňlis dili",
  "en_GB": "iňlis dili (Beýik Britaniýa)",
  "en_US": "iňlis dili (Amerika)",
  "eo": "esperanto dili",
  "es": "ispan dili",
  "es_ES": "ispan dili (Ýewropa)",
  "et": "eston dili",
  "eu": "bask dili",
  "ewo": "ewondo dili",
  "fa": "pars dili",
  "fa_AF": "dari dili",
  "ff": "fula dili",
  "fi": "fin dili",
  "fil": "filippin dili",
  "fj": "fiji dili",
  "fo": "farer dili",
  "fon": "fon dili",
  "fr": "fransuz dili",
  "fur": "friul dili",
  "fy": "günbatar friz dili",
  "ga": "irland dili",
  "gaa": "ga dili",
  "gd": "şotland kelt dili",
  "gez": "geez dili",
  "gil": "gilbert dili",
  "gl": "galisiý dili",
  "gn": "guarani dili",
  "gor": "gorontalo dili",
  "gsw": "nemes dili (Şweýsariýa)",
  "gu": "gujarati dili",
  "guz": "gusii dili",
  "gv": "men dili",
  "gwi": "gwiçin dili",
  "ha": "hausa dili",
  "haw": "gawaý dili",
  "he": "ýewreý dili",
  "hi": "hindi dili",
  "hil": "hiligaýnon dili",
  "hmn": "hmong dili",
  "hr": "horwat dili",
  "hsb": "ýokarky lužits dili",
  "ht": "gaiti kreol dili",
  "hu": "wenger dili",
  "hup": "hupa",
  "hy": "ermeni dili",
  "hz": "gerero dili",
  "ia": "interlingwa dili",
  "iba": "iban dili",
  "ibb": "ibibio dili",
  "id": "indonez dili",
  "ig": "igbo dili",
  "ii": "syçuan-i dili",
  "ilo": "iloko dili",
  "inh": "inguş dili",
  "io": "ido dili",
  "is": "island dili",
  "it": "italýan dili",
  "iu": "inuktitut dili",
  "ja": "ýapon dili",
  "jbo": "lojban dili",
  "jgo": "ngomba dili",
  "jmc": "maçame dili",
  "jv": "ýawa dili",
  "ka": "gruzin dili",
  "kab": "kabil dili",
  "kac": "kaçin dili",
  "kaj": "ju dili",
  "kam": "kamba dili",
  "kbd": "kabardin dili",
  "kcg": "tiap dili",
  "kde": "makonde dili",
  "kea": "kabuwerdianu dili",
  "kfo": "koro dili",
  "kha": "khasi dili",
  "khq": "koýra-Çini dili",
  "ki": "kikuýu dili",
  "kj": "kwanýama dili",
  "kk": "gazak dili",
  "kkj": "kako dili",
  "kl": "grenland dili",
  "kln": "kalenjin dili",
  "km": "khmer dili",
  "kmb": "kimbundu dili",
  "kn": "kannada dili",
  "ko": "koreý dili",
  "kok": "konkani dili",
  "kpe": "kpelle dili",
  "kr": "kanuri",
  "krc": "karaçaý-balkar dili",
  "krl": "karel dili",
  "kru": "kuruh dili",
  "ks": "kaşmiri dili",
  "ksb": "şambala dili",
  "ksf": "bafia dili",
  "ksh": "keln dili",
  "ku": "kürt dili",
  "kum": "kumyk dili",
  "kv": "komi dili",
  "kw": "korn dili",
  "ky": "gyrgyz dili",
  "la": "latyn dili",
  "lad": "ladino dili",
  "lag": "langi dili",
  "lb": "lýuksemburg dili",
  "lez": "lezgin dili",
  "lg": "ganda dili",
  "li": "limburg dili",
  "lkt": "lakota dili",
  "ln": "lingala dili",
  "lo": "laos dili",
  "loz": "lozi dili",
  "lrc": "demirgazyk luri dili",
  "lt": "litwa dili",
  "lu": "luba-katanga dili",
  "lua": "luba-Lulua dili",
  "lun": "lunda dili",
  "luo": "luo dili",
  "lus": "mizo dili",
  "luy": "luýýa dili",
  "lv": "latyş dili",
  "mad": "madur dili",
  "mag": "magahi dili",
  "mai": "maýthili dili",
  "mak": "makasar dili",
  "mas": "masai dili",
  "mdf": "mokşa dili",
  "men": "mende dili",
  "mer": "meru dili",
  "mfe": "morisýen dili",
  "mg": "malagasiý dili",
  "mgh": "makuwa-mito dili",
  "mgo": "meta dili",
  "mh": "marşall dili",
  "mi": "maori dili",
  "mic": "mikmak dili",
  "min": "minangkabau dili",
  "mk": "makedon dili",
  "ml": "malaýalam dili",
  "mn": "mongol dili",
  "mni": "manipuri dili",
  "moh": "mogauk dili",
  "mos": "mossi dili",
  "mr": "marathi dili",
  "ms": "malaý dili",
  "mt": "malta dili",
  "mua": "mundang dili",
  "mul": "birnäçe dil",
  "mus": "krik dili",
  "mwl": "mirand dili",
  "my": "birma dili",
  "myv": "erzýan dili",
  "mzn": "mazanderan dili",
  "na": "nauru dili",
  "nap": "neapolitan dili",
  "naq": "nama dili",
  "nb": "norwegiýa bukmol dili",
  "nd": "demirgazyk ndebele dili",
  "nds": "aşaky nemes dili",
  "ne": "nepal dili",
  "new": "newari dili",
  "ng": "ndonga dili",
  "nia": "nias dili",
  "niu": "niue dili",
  "nl": "niderland dili",
  "nl_BE": "flamand dili",
  "nmg": "kwasio dili",
  "nn": "norwegiýa nýunorsk dili",
  "nnh": "ngembun dili",
  "nog": "nogaý dili",
  "nqo": "nko dili",
  "nr": "günorta ndebele dili",
  "nso": "demirgazyk soto dili",
  "nus": "nuer dili",
  "nv": "nawaho dili",
  "ny": "nýanja dili",
  "nyn": "nýankole dili",
  "oc": "oksitan dili",
  "om": "oromo dili",
  "or": "oriýa dili",
  "os": "osetin dili",
  "pa": "penjab dili",
  "pag": "pangansinan dili",
  "pam": "kapampangan dili",
  "pap": "papýamento dili",
  "pau": "palau dili",
  "pcm": "nigeriý-pijin dili",
  "pl": "polýak dili",
  "prg": "prussiýa dili",
  "ps": "peştun dili",
  "pt": "portugal dili",
  "pt_PT": "portugal dili (Ýewropa)",
  "qu": "keçua dili",
  "quc": "kiçe dili",
  "rap": "rapanuý dili",
  "rar": "kuk dili",
  "rm": "retoroman dili",
  "rn": "rundi dili",
  "ro": "rumyn dili",
  "ro_MD": "moldaw dili",
  "rof": "rombo dili",
  "root": "kök",
  "ru": "rus dili",
  "rup": "arumyn dili",
  "rw": "kinýaruanda dili",
  "rwk": "rwa dili",
  "sa": "sanskrit dili",
  "sad": "sandawe dili",
  "sah": "ýakut dili",
  "saq": "samburu dili",
  "sat": "santali dili",
  "sba": "ngambaý dili",
  "sbp": "sangu dili",
  "sc": "sardin dili",
  "scn": "sisiliýa dili",
  "sco": "şotland dili",
  "sd": "sindhi dili",
  "se": "demirgazyk saam dili",
  "seh": "sena dili",
  "ses": "koýraboro-senni dili",
  "sg": "sango dili",
  "shi": "tahelhit dili",
  "shn": "şan dili",
  "si": "singal dili",
  "sk": "slowak dili",
  "sl": "slowen dili",
  "sm": "samoa dili",
  "sma": "günorta saam dili",
  "smj": "lule-saam dili",
  "smn": "inari-saam dili",
  "sms": "skolt-saam dili",
  "sn": "şona dili",
  "snk": "soninke dili",
  "so": "somali dili",
  "sq": "alban dili",
  "sr": "serb dili",
  "srn": "sranan-tongo dili",
  "ss": "swati dili",
  "ssy": "saho dili",
  "st": "günorta soto dili",
  "su": "sundan dili",
  "suk": "sukuma dili",
  "sv": "şwed dili",
  "sw": "suahili dili",
  "sw_CD": "kongo suahili dili",
  "swb": "komor dili",
  "syr": "siriýa dili",
  "ta": "tamil dili",
  "te": "telugu dili",
  "tem": "temne dili",
  "teo": "teso dili",
  "tet": "tetum dili",
  "tg": "täjik dili",
  "th": "taý dili",
  "ti": "tigrinýa dili",
  "tig": "tigre dili",
  "tk": "türkmen dili",
  "tlh": "klingon dili",
  "tn": "tswana dili",
  "to": "tongan dili",
  "tpi": "tok-pisin dili",
  "tr": "türk dili",
  "trv": "taroko dili",
  "ts": "tsonga dili",
  "tt": "tatar dili",
  "tum": "tumbuka dili",
  "tvl": "tuwalu dili",
  "twq": "tasawak dili",
  "ty": "taiti dili",
  "tyv": "tuwa dili",
  "tzm": "orta-atlas tamazight dili",
  "udm": "udmurt dili",
  "ug": "uýgur dili",
  "uk": "ukrain dili",
  "umb": "umbundu dili",
  "und": "näbelli dil",
  "ur": "urdu",
  "uz": "özbek dili",
  "vai": "wai dili",
  "ve": "wenda dili",
  "vi": "wýetnam dili",
  "vo": "wolapýuk dili",
  "vun": "wunýo dili",
  "wa": "wallon dili",
  "wae": "walzer dili",
  "wal": "wolaýta dili",
  "war": "waraý dili",
  "wo": "wolof dili",
  "xal": "galmyk dili",
  "xh": "kosa dili",
  "xog": "soga dili",
  "yav": "ýangben dili",
  "ybb": "ýemba dili",
  "yi": "idiş dili",
  "yo": "ýoruba dili",
  "yue": "kanton dili",
  "zgh": "standart Marokko tamazight dili",
  "zh": "hytaý dili",
  "zh_Hans": "ýönekeýleşdirilen hytaý dili",
  "zh_Hant": "adaty hytaý dili",
  "zu": "zulu dili",
  "zun": "zuni dili",
  "zxx": "dilçilige degişli mazmun ýok",
  "zza": "zazaki dili"
};
